### ISSUE TITLE
Uncaught Error: ELOOP: too many symbolic links encountered, open '/Users/slauae/.atom/keymap.cson'

### ISSUE THREAD

**Issue by aeslaughter** [atom/atom#10007]
I am attempting to store my keymap.cson in another folder (git repo) so I can update and share it on multiple computers. I cannot use the sync package that exists because of network limitations at my office.

To get this error:
1. move keymap.cson to another folder
2. create symlink: ln -s /myother/folder/keymap.cson ~/.atom/keymap.cson
3. attempt to access the keymap file from Atom Settings

Note, my keybindings work like expected, just can't access them from settings.

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ELOOP: too many symbolic links encountered, open '/Users/slauae/.atom/keymap.cson'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:486

Error: ELOOP: too many symbolic links encountered, open '/Users/slauae/.atom/keymap.cson'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Workspace.module.exports.Workspace.openTextFile (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:528:27)
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:461:23)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:393:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:337:38
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:454:22)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:393:19)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1035:19)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:201:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:03.7.0 settings-view:open (div.pane-item.native-key-bindings.about)
     -0:00.7.0 application:open-your-keymap (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "autocomplete-clang",
      "emacs-mode",
      "transient-emacs",
      "tabs",
      "autocomplete-snippets",
      "tree-view",
      "autocomplete-plus"
    ],
    "destroyEmptyPanes": false,
    "audioBeep": false
  },
  "editor": {
    "invisibles": {},
    "fontSize": 12,
    "showIndentGuide": true,
    "showInvisibles": true,
    "preferredLineLength": 120,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-moose, v0.19.0
language-moose, v0.16.0
pane-info, v1.0.0

# Dev
No dev packages
```

**Comment by aeslaughter** [comment]
I notice an extra self-referencing symbolic link in my .atom directory, which was the true root of this error.
