### ISSUE TITLE
Non-fatal Segmentation fault of fedora with 1.3.0

### ISSUE THREAD

**Issue by keirlawson** [atom/atom#10002]
Atom runs just fine, but I do get this outputted to the console:

```
/usr/bin/atom: line 113:  8100 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 207ms
Failed to get crash dump id.
Report Id: 
```

**Comment by jakebailey** [comment]
I get the same error, however it only happens when I open a second instance of Atom, either into a different directory, or the same directory (in which case only the original instance stays).

**Comment by cmtonkinson** [comment]
Also on Arch using Atom `v1.3.1`. When I execute `atom -n .; atom -n .;` (an alias to start two Windows at once in the current directory), I see the following:

```
/usr/bin/atom: line 114: 30693 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
auto-updater is not iFailed to get crash dump id.
Report Id: 
pdater is not implemented on this platform
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:11:13)
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:14:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at AutoUpdateManager.module.exports.AutoUpdateManager.setupAutoUpdater (/usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:51:23)
    at /usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:42:24
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at NavigationController.loadUrl (/usr/share/atom/resources/atom.asar/browser/api/lib/navigation-controller.js:59:24)
    at EventEmitter.webContents.(anonymous function) [as loadUrl] (/usr/share/atom/resources/atom.asar/browser/api/lib/web-contents.js:81:27)
    at BrowserWindow.loadUrl (/usr/share/atom/resources/atom.asar/browser/api/lib/browser-window.js:121:37)
    at AtomWindow.module.exports.AtomWindow.setLoadSettings (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:125:33)
    at new AtomWindow (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:111:12)
    at AtomApplication.module.exports.AtomApplication.openPaths (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:667:24)
    at AtomApplication.module.exports.AtomApplication.openWithOptions (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:131:21)
    at new AtomApplication (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:111:14)
    at createAtomApplication (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:60:16)
    at Function.module.exports.AtomApplication.open (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:63:9)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/main.js:55:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
App load time: 298ms
```

As issue title suggests, this is non-fatal for me as well.

**Comment by js02sixty** [comment]
running on Arch and the app wont even load.
/usr/bin/atom: line 114: 20758 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 189ms
Failed to get crash dump id.
Report Id:

**Comment by 50Wliu** [comment]
The people in #10195 have reported that this segfault has been fixed in the 1.5.0 betas, so I'm going to close this out.  If anyone can still reproduce using 1.5.0 or later, please comment here!

**Comment by jchia** [comment]
I don't think #10195 has been fixed. I can still repro #10195 in 1.5.3. I don't know if #10195 is really a duplicate of this issue but I'm commenting here per @50Wliu's request.

**Comment by forivall** [comment]
@50Wliu @jchia Yeah, it hasn't been fixed for me either; it seemed like it was fixed in 1.5.0, but it's still happening in more recent releases. (https://github.com/atom/atom/issues/10195#issuecomment-178204556)

**Comment by madspark** [comment]
Still happening with 1.6.0 (reproduced on Fedora 23).

**Comment by yuriploc** [comment]
Same here..
Infos:
$ uname -r
4.4.6-200.fc22.x86_64
$ atom --version
1.6.2
$ atom .
$ /usr/bin/atom: line 117: 26472 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 1320ms
Failed to get crash dump id.
Report Id:

**Comment by wjbryant** [comment]
Same for me on Fedora 23 (4.4.7-300.fc23.x86_64) with Atom v1.6.2.

```
/usr/bin/atom: line 117:  9731 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 187ms
Failed to get crash dump id.
Report Id:
```

**Comment by kejn** [comment]
installing the packages described in the 'building' > 'Ubuntu / Debian' section fixes the issue.
