### ISSUE TITLE
Uncaught Error: Error: Cannot find where you keep your Bower packages.

### ISSUE THREAD

**Issue by pilargmez** [atom/atom#10021]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Error: Cannot find where you keep your Bower packages.

```
At events.js:141

Error: Error: Cannot find where you keep your Bower packages.
    at C:\Users\Pilar\AppData\Roaming\npm\node_modules\generator-webapp\node_modules\wiredep\wiredep.js:30:56
    at findBowerDirectory (C:\Users\Pilar\AppData\Roaming\npm\node_modules\generator-webapp\node_modules\wiredep\wiredep.js:108:27)
    at wiredep (C:\Users\Pilar\AppData\Roaming\npm\node_modules\generator-webapp\node_modules\wiredep\wiredep.js:37:43)
    at [object Object].module.exports.generators.Base.extend.end (C:\Users\Pilar\AppData\Roaming\npm\node_modules\generator-webapp\app\index.js:315:5)
    at C:\Users\Pilar\AppData\Roaming\npm\node_modules\generator-webapp\node_modules\yeoman-generator\lib\base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -1:50.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:50.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:50.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:50.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:49.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:49.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:49.8.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:49.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:47.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -1:38 emmet:evaluate-math-expression (atom-text-editor.editor.mini.is-focused)
     -1:31.7.0 yo:yeoman (atom-text-editor.editor.mini.is-focused)
     -1:29.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:27.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -1:26.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:42.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  9x -0:35.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
color-picker, v2.0.14
color-tabs, v0.1.8
emmet, v2.3.17
file-icons, v1.6.13
linter, v1.11.3
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
minimap, v4.18.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
This looks like an issue with [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) – feel free to reopen an issue there.
