### ISSUE TITLE
Failed to load the line-ending-selector package(EPERM: operation not permitted, write)

### ISSUE THREAD

**Issue by LendLord** [atom/atom#10056]
[Enter steps to reproduce below:]

1. Install atom
2. Error occured

**Atom Version**: 1.2.4
**System**: Unknown Windows Version (Windows 10, version 1511, build 10586.29)
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.3.0

### Stack Trace

Failed to load the line-ending-selector package

```
At C:/Users/Lord/AppData/Local/atom/app-1.2.4/resources/app.asar/node_modules/line-ending-selector/lib/status-bar-item.js: EPERM: operation not permitted, write

Error: C:/Users/Lord/AppData/Local/atom/app-1.2.4/resources/app.asar/node_modules/line-ending-selector/lib/status-bar-item.js: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:663:20)
    at SyncWriteStream.write (fs.js:1981:6)
    at Function.log (C:\Users\Lord\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\babel-core\node_modules\debug\node.js:106:17)
    at enabled (C:\Users\Lord\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\babel-core\node_modules\debug\debug.js:117:11)
    at Logger.debug (C:\Users\Lord\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\babel-core\lib\transformation\file\logger.js:92:31)
    at File.parse (C:\Users\Lord\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:573:14)
    at File.parseCode (C:\Users\Lord\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:691:20)
    at C:\Users\Lord\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\babel-core\lib\transformation\pipeline.js:167:12
    at File.wrap (C:\Users\Lord\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:639:16)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
linter, v1.11.3
linter-php, v1.1.6

# Dev
No dev packages
```

linter-php gives the same error

**Comment by 50Wliu** [comment]
Already reported at atom/line-ending-selector#18.

**Comment by abe33** [comment]
@50Wliu I don't think this is the wrong repo, actually the issue occurs with different packages and is likely due to right issues in Atom itself.

**Comment by abe33** [comment]
I reopen this issue, as it's clearly an issue with Atom that can occurs when compiling a js file with `use babel` pragma (see how the same error occurs with minimap). 

What we need now is to find what trigger this issue.

**Comment by joshaber** [comment]
This seems a whole lot like https://github.com/atom/electron/issues/2033#issuecomment-114560015, though it's curious that in the minimap issue people report that reloading or disable/enable fixed it.

It certainly seems related to the compile cache. /cc @maxbrunsfeld for any theories

**Comment by maxbrunsfeld** [comment]
@LendLord Di you by any chance have the `DEBUG` or `DEBUG_FD` environment variables set when loading Atom? It looks like a module that we use, [babel](https://github.com/babel/babel) uses a [logging utility library](https://github.com/visionmedia/debug) that tries to write to `stderr` if that variable is set. I think this will cause errors in Windows GUI programs because they don't have a stderr stream.
