### ISSUE TITLE
Did not open

### ISSUE THREAD

**Issue by AppIns** [atom/atom#10065]
The text editor did not open and it displays this error

Please note that i substituted my user name for *MYNAME*
```
SyntaxError: Unexpected token 
at Object.parse (native)
    at FileSystemBlobStore.load (C:\Users\MYNAME\AppData\Local\atom\app-
1.3.0\resources\app.asar\src\file-system-blob-store.js:31:31)
    at Function.load (C:\Users\MYNAME\AppData\Local\atom\app-1.3.0\resources\app.asar\src\file-system-blob-store.js:10:14)
    at window.onload (file:///C:/Users/MYNAME/AppData/Local/atom/app-1.3.0/resources/app.asar/static/index.js:18:39)
```
Need more info? [Email me!](mailto:alexandersonone@gmail.com)

**Comment by AppIns** [comment]
I am reinstalling by tomorrow! Please ask me before then

**Comment by 50Wliu** [comment]
Please update to Atom 1.3.1 - that should fix your issue.  If not, also try deleting the `C:\Users\MYNAME\.atom\blob-store` folder.

**Comment by AppIns** [comment]
Thanks, I used the second method and it worked.
