### ISSUE TITLE
TextEditorPresenter spec is flaky

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#10089]
https://janky.githubapp.com/2593440/output

```
>> TextEditorPresenter
>>   ::getState()
>>     .content
>>       .tiles
>>         [tileId].lines[lineId]
>>           .decorationClasses
>>             it adds decoration classes to the relevant line state objects, both initially and when decorations change
>>               timeout: timed out after 1000 msec waiting for presenter state to update
>>             it honors the 'onlyEmpty' option on line decorations
>>               Error: Leaking subscriptions for paths: /private/var/lib/jenkins/workspace/atom/spec/fixtures/sample.js
>>                 at ensureNoPathSubscriptions (/private/var/lib/jenkins/workspace/atom/spec/spec-helper.coffee:122:15)
>>                 at [object Object].<anonymous> (/private/var/lib/jenkins/workspace/atom/spec/spec-helper.coffee:115:3)
>>                 at doNTCallback0 (node.js:419:9)
>>                 at process._tickCallback (node.js:348:13)
```

**Comment by joshaber** [comment]
Rolling this into #10435.
