### ISSUE TITLE
Uncaught Error: dlopen(/Applications/Atom 2.app/Contents/Resources/app.asar.unpacked/node_modules...

### ISSUE THREAD

**Issue by usojoe** [atom/atom#10099]
[Enter steps to reproduce below:]

1. ...edited an admin-protected file (hosts) in atom
2. ...saved an admin-protected file (hosts) in atom

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/Applications/Atom 2.app/Contents/Resources/app.asar.unpacked/node_modules/runas/build/Release/runas.node, 1): image not found

```
At /Applications/Atom 2.app/Contents/Resources/app.asar/src/pane.js:829

Error: dlopen(/Applications/Atom 2.app/Contents/Resources/app.asar.unpacked/node_modules/runas/build/Release/runas.node, 1): image not found
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:148:18)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom 2.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/runas/lib/runas.js:4:11)
    at Object.<anonymous> (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/runas/lib/runas.js:47:4)
    at Module._compile (/Applications/Atom 2.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom 2.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom 2.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:403:21)
    at File.module.exports.File.writeSync (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:355:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1046:19)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1030:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom 2.app/Contents/Resources/app.asar/src/text-editor.js:588:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom 2.app/Contents/Resources/app.asar/src/pane.js:534:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom 2.app/Contents/Resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom 2.app/Contents/Resources/app.asar/src/workspace.js:633:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom 2.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom 2.app/Contents/Resources/app.asar/src/atom-environment.js:1010:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -1:04.3.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -1:04.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:03.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:03.3.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -1:03.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:56.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:56.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:56.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:56.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:56.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:56.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:55.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:55.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:55.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:49.4.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:41.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "editor": {
    "fontSize": 18
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
This looks like a corrupt version of Atom.

Can you try re-downloading Atom from https://atom.io/ and see if you still experience this?

I'm going to close this out for now but will reopen if you are still experiencing it.
