### ISSUE TITLE
Ubuntu (15.10) : Atom not responding

### ISSUE THREAD

**Issue by harikt** [atom/atom#10102]
Hi, 

I have been using atom earlier. Uninstalled it due to certain strange actions ( cannot click on the text on editor ) .

Installed again with `dpkg -i` command.

```
$atom --version
1.3.1

$ apm links
/home/hari/.atom/dev/packages (0)
└── (no links)
/home/hari/.atom/packages (0)
└── (no links)

$apm install --check
Checking for native build tools ✓
```

Ran `atom --safe` still it is not responding . The menu `project` and `find` have no submenus. When you click on many of the submenus  Eg : ( about ) it cannot even show the about information.

Tried opening folder from safe mode and it worked.

> Edit : once only . Cannot open the debug bar for it is not responding either.

Not sure what is happening. Tried many times.

There is no plugins installed currently. The old `~/.atom` folder was removed before the fresh install.

**Comment by maxbrunsfeld** [comment]
If you run `atom --foreground`, are errors reported in the console?

**Comment by harikt** [comment]
```bash
 atom --foreground
auto-updater is not implemented on this platform
Error: auto-updater is not implemented on this platform
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:11:13)
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:14:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at AutoUpdateManager.module.exports.AutoUpdateManager.setupAutoUpdater (/usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:51:23)
    at /usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:42:24
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at NavigationController.loadUrl (/usr/share/atom/resources/atom.asar/browser/api/lib/navigation-controller.js:59:24)
    at EventEmitter.webContents.(anonymous function) [as loadUrl] (/usr/share/atom/resources/atom.asar/browser/api/lib/web-contents.js:81:27)
    at BrowserWindow.loadUrl (/usr/share/atom/resources/atom.asar/browser/api/lib/browser-window.js:121:37)
    at AtomWindow.module.exports.AtomWindow.setLoadSettings (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:125:33)
    at new AtomWindow (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:111:12)
    at AtomApplication.module.exports.AtomApplication.openPaths (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:667:24)
    at AtomApplication.module.exports.AtomApplication.openWithOptions (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:131:21)
    at AtomApplication.module.exports.AtomApplication.loadState (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:749:16)
    at new AtomApplication (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:113:14)
    at createAtomApplication (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:60:16)
    at Function.module.exports.AtomApplication.open (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:63:9)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/main.js:55:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
App load time: 1763ms
```

**Comment by 50Wliu** [comment]
The auto-updater error shouldn't affect anything and will be fixed by #9627.  Is it still hanging in foreground mode?

**Comment by harikt** [comment]
yes. It is still hanging. Not working at present.

*Hari K T*

You can ring me : +91 9388 75 8821

http://harikt.com , https://github.com/harikt ,
http://www.linkedin.com/in/harikt , http://www.xing.com/profile/Hari_KT

Skype  : kthari85
Twitter : harikt

**Comment by oldoni** [comment]
Hi, I'm have a similar problem. 
Execute in foreground just show the auto-updater erro.
```
 $ atom --version
 1.3.2

$: apm links
/home/marcelo/.atom/dev/packages (0)
└── (no links)
/home/marcelo/.atom/packages (0)
└── (no links)

$: apm install --check
Checking for native build tools ✓

 $ atom --foreground
auto-updater is not implemented on this platform
Error: auto-updater is not implemented on this platform
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:11:13)
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:14:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at AutoUpdateManager.module.exports.AutoUpdateManager.setupAutoUpdater (/usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:51:23)
    at /usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:42:24
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at NavigationController.loadUrl (/usr/share/atom/resources/atom.asar/browser/api/lib/navigation-controller.js:59:24)
    at EventEmitter.webContents.(anonymous function) [as loadUrl] (/usr/share/atom/resources/atom.asar/browser/api/lib/web-contents.js:81:27)
    at BrowserWindow.loadUrl (/usr/share/atom/resources/atom.asar/browser/api/lib/browser-window.js:121:37)
    at AtomWindow.module.exports.AtomWindow.setLoadSettings (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:125:33)
    at new AtomWindow (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:111:12)
    at AtomApplication.module.exports.AtomApplication.openPaths (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:667:24)
    at AtomApplication.module.exports.AtomApplication.openWithOptions (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:131:21)
    at AtomApplication.module.exports.AtomApplication.loadState (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:749:16)
    at new AtomApplication (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:113:14)
    at createAtomApplication (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:60:16)
    at Function.module.exports.AtomApplication.open (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:63:9)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/main.js:55:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
App load time: 275ms
```
I'm using ubuntu 15.04.
there another log i can get to resolve ?
