### ISSUE TITLE
Failed to load the terminal-runner package

### ISSUE THREAD

**Issue by bedna-KU** [atom/atom#10304]
1. Run Atom on Debian Jessie with command atom
2. After Atom start throw error: Failed to load the terminal-runner package

**Atom Version**: 1.3.2
**System**: antiX 15
**Thrown From**: [terminal-runner](https://github.com/lackac/terminal-runner) package, v0.0.2

### Stack Trace

Failed to load the terminal-runner package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (<anonymous>:1:21)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:663:34)
    at /usr/share/atom/resources/app.asar/src/package.js:115:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:438:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:390:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:682:21)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
terminal-runner, v0.0.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The terminal-runner package is no longer maintained.  I would suggest uninstalling it and finding an alternative.

**Comment by bedna-KU** [comment]
OK, thanks.
I use official Atom package - https://github.com/atom/atom/releases/tag/v1.3.2
