### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by blanchma** [atom/atom#10319]
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at FileSystemBlobStore.load (/Users/blanchma/Downloads/Atom.app/Contents/Resources/app.asar/src/file-system-blob-store.js:36:31)
    at Function.load (/Users/blanchma/Downloads/Atom.app/Contents/Resources/app.asar/src/file-system-blob-store.js:10:14)
    at window.onload (file:///Users/blanchma/Downloads/Atom.app/Contents/Resources/app.asar/static/index.js:18:39)
 
Since this morning, after a crash of my computer, ATOM stop working. I try to download it again but the error persist.

**Comment by 50Wliu** [comment]
Hi @blanchma, try deleting the `~/.atom/blob-store` folder and try again.  Sorry for the inconvenience!

**Comment by blanchma** [comment]
I did. It works. Thanks

2016-01-07 11:36 GMT-03:00 Wliu <notifications@github.com>:
