### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by medensqui** [atom/atom#10343]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:298

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:351:9)
    at Object.exports.fork (child_process.js:56:10)
    at new Task (/Applications/4Peaks.app/Atom.app/Contents/Resources/app.asar/src/task.js:41:40)
    at Function.module.exports.Task.once (/Applications/4Peaks.app/Atom.app/Contents/Resources/app.asar/src/task.js:17:14)
    at GitRepository.module.exports.GitRepository.refreshStatus (/Applications/4Peaks.app/Atom.app/Contents/Resources/app.asar/src/git-repository.js:374:37)
    at /Applications/4Peaks.app/Atom.app/Contents/Resources/app.asar/src/git-repository.js:75:26
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by damieng** [comment]
No repro steps at all. Closing.
