### ISSUE TITLE
Uncaught Error: Unknown system error -25: Unknown system error -25, fdatasync

### ISSUE THREAD

**Issue by n-aia** [atom/atom#10372]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Unknown system error -25: Unknown system error -25, fdatasync

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:829

Error: Unknown system error -25: Unknown system error -25, fdatasync
    at Error (native)
    at Object.fs.fdatasyncSync (fs.js:773:18)
    at TextBuffer.module.exports.TextBuffer.backUpFileContentsBeforeWriting (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1122:10)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1043:31)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1030:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:602:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:534:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:633:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:44.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:44.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:37.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:37.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:31.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:31.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:27.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:27.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:58 core:save (atom-text-editor.editor.is-focused)
     -1:29.8.0 tree-view:remove (span.name.icon.icon-file-text)
     -0:53.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:44 core:paste (atom-text-editor.editor.is-focused)
     -0:40 core:save (atom-text-editor.editor.is-focused)
     -0:18.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:07.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:01.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai-seti"
    ],
    "openEmptyEditorOnStart": false
  },
  "editor": {
    "invisibles": {},
    "fontSize": 13,
    "backUpBeforeSaving": true
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.13
color-picker, v2.0.14
emmet, v2.3.17
monokai-seti, v0.7.0

# Dev
No dev packages
```

**Comment by kepta** [comment]
If I am reading it correct, there seems to be a problem in emmet package here.
