### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/tuneonmymind/.atom/keymap.cson'

### ISSUE THREAD

**Issue by whereismymind7** [atom/atom#10406]
Hello. Got a bug.
1. Open keymap.cson by 'Open your keymap'
2. Edit
3. Try save

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/tuneonmymind/.atom/keymap.cson'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:829

Error: ENOENT: no such file or directory, open '/Users/tuneonmymind/.atom/keymap.cson'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.writeFileSync (fs.js:1171:15)
    at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:282:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:398:21)
    at File.module.exports.File.writeSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:355:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1053:19)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:602:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:534:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:643:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -0:29.5.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:16.5.0 core:paste (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:12.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  9x -0:11.9.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:09.5.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:09.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:08.2.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:04.2.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```
### Config

``` json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "tool-bar",
      "git-projects"
    ],
    "disabledPackages": [
      "todo-show",
      "atom-ctags",
      "autocomplete-ctags"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.21
atom-ternjs, v0.12.2
auto-detect-indentation, v0.4.2
auto-update-packages, v1.0.0
autoclose-html, v0.19.0
autocomplete-modules, v1.3.1
autocomplete-ruby, v0.1.0
color-picker, v2.0.14
docblockr, v0.7.3
git-log, v0.4.1
imdone-atom, v1.3.20
language-gherkin, v1.0.3
language-jade, v0.6.2
language-r, v0.4.0
language-slim, v0.5.0
minimap, v4.19.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
node-debugger, v1.3.2
preview-plus, v1.2.6
project-manager, v2.7.3
project-viewer, v0.2.26
sync-settings, v0.6.0
term3, v0.21.0
tree-view-git-status, v0.2.2
vim-mode, v0.64.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
* Can you reproduce this reliably?
* Can you reproduce this in Safe Mode?
* Does the file exist?
* What are the permissions on the `~/.atom` directory and the `~/.atom/keymap.cson` file?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/10406#issuecomment-171551847. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
