### ISSUE TITLE
Flaky text-editor-presenter spec

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#10435]
https://travis-ci.org/atom/atom/jobs/102501079

Internal CI passed for this commit.

/cc @kuychaco

**Comment by as-cii** [comment]
This seems related to #10089 and I suspect it's because of the call to `waitsForStateToUpdate`. Maybe bumping the timeout a little bit could solve the problem?

**Comment by joshaber** [comment]
`GitRepositoryAsync` has a similarly flaky failure: https://travis-ci.org/atom/atom/jobs/102702554

```
>> GitRepositoryAsync
>>   .checkoutHeadForEditor(editor)
>>     it does not display a dialog when confirmation is disabled
>>       Error: Leaking subscriptions for paths: /private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/atom-working-dir116015-49834-1jigq4q/a.txt
>>         at ensureNoPathSubscriptions (/Users/travis/build/atom/atom/spec/spec-helper.coffee:123:15)
>>         at [object Object].<anonymous> (/Users/travis/build/atom/atom/spec/spec-helper.coffee:116:3)
>>         at process._tickCallback (node.js:368:9)
>> 
>> 
```

**Comment by kuychaco** [comment]
Similar failure here - https://janky.githubapp.com/2716352/output
Passed just fine on travis - https://travis-ci.org/atom/atom/builds/106365370
(part of PR #10605)

```
>> TextEditorPresenter
>>   ::get(Pre|Post)MeasurementState()
>>     .content
>>       .cursors
>>         it updates when block decorations change
>>           timeout: timed out after 1000 msec waiting for presenter state to update
>>         it updates when ::scrollTop changes
>>           Error: Leaking subscriptions for paths: /private/var/lib/jenkins/workspace/atom/spec/fixtures/sample.js
>>             at ensureNoPathSubscriptions (/private/var/lib/jenkins/workspace/atom/spec/spec-helper.coffee:122:15)
>>             at [object Object].<anonymous> (/private/var/lib/jenkins/workspace/atom/spec/spec-helper.coffee:115:3)
>>             at process._tickCallback (node.js:368:9)
```

**Comment by joshaber** [comment]
That one :point_up: is pretty annoyingly consistent.

**Comment by kuychaco** [comment]
Another TextEditorPresenter spec failure, plus some Metadata.framework Error (that didn't cause any failures) - https://travis-ci.org/atom/atom/builds/108673841
