### ISSUE TITLE
%1 is not a valid Win32 application

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#10450]
Trying to use Atom on or after `4d740d33468a2fe427c379fc6a0719efcb89930a` results in a NodeGit error `%1 is not a valid Win32 application`.

Full stack trace:
```
Error: %1 is not a valid Win32 application.
\\?\C:\Program Files\Atom\resources\app.asar.unpacked\node_modules\nodegit\build\Release\nodegit.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:162:18)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:173:16)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Program Files\Atom\resources\app.asar\node_modules\nodegit\lib\nodegit.js:8:12)
    at Module._compile (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Program Files\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Program Files/Atom/resources/app.asar/src/git-repository-async.js:4:24)
    at Module._compile (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Program Files\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Program Files\Atom\resources\app.asar\src\git-repository.js:12:24)
    at Object.<anonymous> (C:\Program Files\Atom\resources\app.asar\src\git-repository.js:424:4)
    at Module._compile (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Program Files\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
```

Also reported by @Haacked at #10271.

/cc @joshaber, @johnhaley81

EDIT: Forgot to mention that I'm running Windows 10 x64.

**Comment by joshaber** [comment]
Huh, I can't reproduce this.

@50Wliu @Haacked Could you check something for me? Run `node -e 'console.log(process.arch)'` and paste the output in here.

**Comment by 50Wliu** [comment]
`x64` through Git Bash, empty output using `cmd`.
Running `console.log(process.arch)` in the Atom dev tools that appear when the error occurs gives `ia32` (which I'm guessing is the issue).

**Comment by Haacked** [comment]
@joshaber `x64`

**Comment by paulcbetts** [comment]
Atom is a 32-bit application even on 64-bit platforms and node-pre-gyp is Guessing Wrong

**Comment by joshaber** [comment]
Yeah, I fixed this in one place previously. Trying to figure out where else I need to override.

**Comment by joshaber** [comment]
Huh, I can't even bootstrap with a 64-bit version of Node without it failing, much less actually building the thing.

**Comment by joshaber** [comment]
I'm gonna keep poking at this next week because I'd hate to tell people they have to reinstall 32-bit node, but I'm not sure if/how building with 64-bit node ever worked.

**Comment by joshaber** [comment]
@50Wliu @Haacked In the mean time, installing 32-bit node should do the trick if this is blocking you.

**Comment by benogle** [comment]
:boot: :bug:

**Comment by johnhaley81** [comment]
:+1:

**Comment by Stanzilla** [comment]
For reference https://github.com/atom/atom/issues/4881 :)

**Comment by kiamlaluno** [comment]
It happens to me when I try to check for updates from the _Settings_ panel, with version 1.22.1.

**Comment by kiamlaluno** [comment]
I installed the beta version of Atom. and I don't have the error message anymore.
