### ISSUE TITLE
Uncaught Error: The element cannot be null or undefined.

### ISSUE THREAD

**Issue by monkcs** [atom/atom#10481]
Starting Atom with a C# project folder open

**Atom Version**: 1.4.0
**System**: Ubuntu 15.10
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: The element cannot be null or undefined.

```
At /usr/share/atom/resources/app.asar/src/lines-tile-component.js:71

Error: The element cannot be null or undefined.
    at DOMElementPool.module.exports.DOMElementPool.free (/usr/share/atom/resources/app.asar/src/dom-element-pool.js:80:15)
    at DOMElementPool.module.exports.DOMElementPool.freeElementAndDescendants (/usr/share/atom/resources/app.asar/src/dom-element-pool.js:63:12)
    at LinesTileComponent.module.exports.LinesTileComponent.removeLineNode (/usr/share/atom/resources/app.asar/src/lines-tile-component.js:111:27)
    at LinesTileComponent.module.exports.LinesTileComponent.updateLineNodes (/usr/share/atom/resources/app.asar/src/lines-tile-component.js:123:16)
    at LinesTileComponent.module.exports.LinesTileComponent.updateSync (/usr/share/atom/resources/app.asar/src/lines-tile-component.js:98:12)
    at LinesComponent.module.exports.TiledComponent.updateTileNodes (/usr/share/atom/resources/app.asar/src/tiled-component.js:67:19)
    at LinesComponent.module.exports.TiledComponent.updateSync (/usr/share/atom/resources/app.asar/src/tiled-component.js:30:12)
    at LinesYardstick.module.exports.LinesYardstick.prepareScreenRowsForMeasurement (/usr/share/atom/resources/app.asar/src/lines-yardstick.js:26:37)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/usr/share/atom/resources/app.asar/src/text-editor-presenter.js:182:27)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/share/atom/resources/app.asar/src/text-editor-component.js:195:38)
    at /usr/share/atom/resources/app.asar/src/text-editor-component.js:298:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app.asar/src/view-registry.js:215:9)
    at /usr/share/atom/resources/app.asar/src/view-registry.js:3:61
```
### Commands

```
  4x -0:06.0 core:backspace (atom-text-editor.editor.is-focused.omnisharp-editor)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
atom-yeoman, v0.3.15
json-schema, v0.1.15
linter, v1.11.3
omnisharp-atom, v0.26.7

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
:eyes: @as-cii @nathansobo

**Comment by as-cii** [comment]
Thank you for the feedback, @monkcs! And thanks @mnquintana for pointing this out.

Seems like we're freeing an element that doesn't exist in the DOM objects pool: this should never happen in theory, so there must be something wrong with the code that keeps the lines state although it's kinda difficult to track it down, as it seems like a corner case.

@monkcs: can you reproduce it consistently? It would be awesome if you could provide a zipped directory for us to inspect that shows this problem, so that we can track down what is causing it. Thanks! :sparkles:

**Comment by lee-dohm** [comment]
@as-cii I was noticing this part:

```
  4x -0:06.0 core:backspace (atom-text-editor.editor.is-focused.omnisharp-editor)
```

Specifically the part about the `omnisharp-editor`. Is it possible that the `omnisharp-atom` plugin is doing something to the editor or creating a subclassed editor of some kind that isn't behaving well?

**Comment by ktravelet** [comment]
I just hit this same issue.  Hopefully its just a 1-off thing.

[Enter steps to reproduce:]

1. Open Atom with blank, new page.
2. Open file with remote-edit. 

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: The element cannot be null or undefined.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/dom-element-pool.js:66

Error: The element cannot be null or undefined.
    at DOMElementPool.free (/app.asar/src/dom-element-pool.js:66:34)
    at DOMElementPool.free (/app.asar/src/dom-element-pool.js:86:12)
    at DOMElementPool.free (/app.asar/src/dom-element-pool.js:86:12)
    at DOMElementPool.free (/app.asar/src/dom-element-pool.js:86:12)
    at DOMElementPool.free (/app.asar/src/dom-element-pool.js:86:12)
    at DOMElementPool.free (/app.asar/src/dom-element-pool.js:86:12)
    at DOMElementPool.free (/app.asar/src/dom-element-pool.js:86:12)
    at DOMElementPool.free (/app.asar/src/dom-element-pool.js:86:12)
    at DOMElementPool.freeElementAndDescendants (/app.asar/src/dom-element-pool.js:54:10)
    at LinesTileComponent.removeLineNode (/app.asar/src/lines-tile-component.js:84:25)
    at LinesTileComponent.removeLineNodes (/app.asar/src/lines-tile-component.js:79:12)
    at LinesTileComponent.destroy (/app.asar/src/lines-tile-component.js:24:10)
    at LinesComponent.module.exports.TiledComponent.removeTileNode (/app.asar/src/tiled-component.js:30:40)
    at LinesComponent.module.exports.TiledComponent.updateTileNodes (/app.asar/src/tiled-component.js:42:16)
    at LinesComponent.module.exports.TiledComponent.updateSync (/app.asar/src/tiled-component.js:18:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/app.asar/src/text-editor-component.js:264:34)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/app.asar/src/text-editor-component.js:196:12)
    at /app.asar/src/text-editor-component.js:323:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/app.asar/src/view-registry.js:219:9)
    at /app.asar/src/view-registry.js:3:59
```

### Commands

```
     -1:12.9.0 remote-edit:browse (input.hidden-input)
```

### Non-Core Packages

```
docblockr 0.9.1 
linter 1.11.23 
linter-jshint 3.0.2 
remote-edit 1.9.0 
split-diff 1.2.0 
```

**Comment by controversial** [comment]
I just saw this after exiting fullscreen on Atom 1.18.0 beta (macOS latest)

**Comment by mh-cbon** [comment]
same here, total random so far, been using the same version for weeks without meeting with it, happened today while doing copy/paste.

```
usr/share/atom/resources/app.asar/src/dom-element-pool.js:66
Hide Stack Trace
Error: The element cannot be null or undefined.
    at DOMElementPool.free (/usr/share/atom/resources/app.asar/src/dom-element-pool.js:66:34)
    at DOMElementPool.free (/usr/share/atom/resources/app.asar/src/dom-element-pool.js:86:12)
    at DOMElementPool.free (/usr/share/atom/resources/app.asar/src/dom-element-pool.js:86:12)
    at DOMElementPool.free (/usr/share/atom/resources/app.asar/src/dom-element-pool.js:86:12)
    at DOMElementPool.free (/usr/share/atom/resources/app.asar/src/dom-element-pool.js:86:12)
    at DOMElementPool.freeElementAndDescendants (/usr/share/atom/resources/app.asar/src/dom-element-pool.js:54:10)
    at LinesTileComponent.removeLineNode (/usr/share/atom/resources/app.asar/src/lines-tile-component.js:84:25)
    at LinesTileComponent.updateLineNodes (/usr/share/atom/resources/app.asar/src/lines-tile-component.js:111:14)
    at LinesTileComponent.updateSync (/usr/share/atom/resources/app.asar/src/lines-tile-component.js:73:10)
    at LinesComponent.module.exports.TiledComponent.updateTileNodes (/usr/share/atom/resources/app.asar/src/tiled-component.js:55:19)
    at LinesComponent.module.exports.TiledComponent.updateSync (/usr/share/atom/resources/app.asar/src/tiled-component.js:18:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/usr/share/atom/resources/app.asar/src/text-editor-component.js:264:34)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/share/atom/resources/app.asar/src/text-editor-component.js:196:12)
    at /usr/share/atom/resources/app.asar/src/text-editor-component.js:323:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app.asar/src/view-registry.js:219:9)
    at /usr/share/atom/resources/app.asar/src/view-registry.js:3:59
```

**Comment by mh-cbon** [comment]
yup total random in my case, shortly after my comment it happened again after i keyed  "enter key", also after a ctrl-x. both non systematic, one out of ???? it will trigger the exception. I did several others new lines, save, ctrl-x without this failure : s

**Comment by AgentME** [comment]
I just had this right after opening a file. I couldn't reproduce it afterward.

**Comment by thbgh** [comment]
Had anyone solved this problem? please give me a hand,Atom does not work!

**Comment by outfrost** [comment]
Just popped up for me, out of the blue, upon scrolling a C source file, with 2 panes open side-by-side (not of the same file).

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Linux Mint
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: The element cannot be null or undefined.

```
At /usr/share/atom/resources/app/src/dom-element-pool.js:66

Error: The element cannot be null or undefined.
    at DOMElementPool.free (/usr/share/atom/resources/app/src/dom-element-pool.js:66:40)
    at DOMElementPool.freeElementAndDescendants (/usr/share/atom/resources/app/src/dom-element-pool.js:54:16)
    at LinesTileComponent.removeLineNode (/usr/share/atom/resources/app/src/lines-tile-component.js:84:31)
    at LinesTileComponent.removeLineNodes (/usr/share/atom/resources/app/src/lines-tile-component.js:79:18)
    at LinesTileComponent.destroy (/usr/share/atom/resources/app/src/lines-tile-component.js:24:16)
    at LinesComponent.module.exports.TiledComponent.removeTileNode (/usr/share/atom/resources/app/src/tiled-component.js:30:46)
    at LinesComponent.module.exports.TiledComponent.updateTileNodes (/usr/share/atom/resources/app/src/tiled-component.js:42:22)
    at LinesComponent.module.exports.TiledComponent.updateSync (/usr/share/atom/resources/app/src/tiled-component.js:18:18)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/usr/share/atom/resources/app/src/text-editor-component.js:266:40)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/share/atom/resources/app/src/text-editor-component.js:198:18)
    at /usr/share/atom/resources/app/src/text-editor-component.js:325:34
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app/src/view-registry.js:223:15)
    at /usr/share/atom/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -4:47.4.0 core:cancel (input.hidden-input)
     -4:44.8.0 editor:consolidate-selections (input.hidden-input)
     -4:44.8.0 core:cancel (input.hidden-input)
     -4:44.5.0 editor:consolidate-selections (input.hidden-input)
     -4:44.5.0 core:cancel (input.hidden-input)
     -4:44.3.0 editor:consolidate-selections (input.hidden-input)
     -4:44.3.0 core:cancel (input.hidden-input)
     -4:44.2.0 editor:consolidate-selections (input.hidden-input)
     -4:44.2.0 core:cancel (input.hidden-input)
     -4:44.1.0 editor:consolidate-selections (input.hidden-input)
     -4:44.1.0 core:cancel (input.hidden-input)
     -4:35.9.0 diff-pane:execute (input.hidden-input)
  2x -3:09.9.0 core:confirm (input.hidden-input)
     -1:59.1.0 core:undo (input.hidden-input)
  2x -1:58.2.0 core:redo (input.hidden-input)
     -1:57.1.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
atom-terminal 0.8.0 
base16-ocean-dark-syntax-theme 0.1.10 
city-lights-syntax 1.1.4 
city-lights-ui 1.2.0 
duotone-berries-syntax 0.1.1 
duotone-dank-green-syntax 0.0.0 
duotone-dark-drawbridge-syntax 0.1.7 
duotone-dark-syntax 2.1.0 
GAS-x86_64-highlighter 0.3.7 
github-atom-dark-syntax 0.5.0 
gotham-syntax 0.2.0 
hybrid-next-syntax 0.9.2 
language-assembly 0.7.2 
language-rust 0.4.12 
loved-syntax 1.0.2 
markdown-preview-plus 2.4.16 
markdown-themeable-pdf 1.2.0 
nord-atom-syntax 0.9.1 
northem-dark-atom-syntax 2.1.0 
pigments 0.39.1 
pure-syntax 0.3.0 
railscast-theme 0.4.0 
split-diff 1.5.1 
styri-syntax 0.1.1 
wombat-dark-syntax 1.2.0 
```

**Comment by 50Wliu** [comment]
Has anyone been able to reproduce this on Atom 1.19 or later?

**Comment by as-cii** [comment]
I think this can be closed because `DOMElementPool` has been deleted from the codebase as part of #13880.

Thanks everyone for the reports, and thanks for the heads-up on this @50Wliu! 🙇
