### ISSUE TITLE
Atom throws error when open it as sudo user.

### ISSUE THREAD

**Issue by ULTIMATEUPGRADE** [atom/atom#10616]
Atom throws the following error when open it as sudo user.
Error: EACCES: permission denied, open '/home/harmony-12/.atom/compile-cache/less/df1b7fbc57dbeed23a8f1f8de95b4dfebcc06066/imports.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.writeFileSync (fs.js:1171:15)
    at Object.fsPlus.writeFileSync (/opt/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (/opt/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:155:17)
    at LessCache.module.exports.LessCache.setImportPaths (/opt/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:113:12)
    at new LessCache (/opt/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:32:12)
    at new LessCompileCache (/opt/atom/resources/app.asar/src/less-compile-cache.js:20:20)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/opt/atom/resources/app.asar/src/theme-manager.js:270:26)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/opt/atom/resources/app.asar/src/theme-manager.js:257:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (/opt/atom/resources/app.asar/src/theme-manager.js:174:24)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (/opt/atom/resources/app.asar/src/theme-manager.js:237:12)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (/opt/atom/resources/app.asar/src/theme-manager.js:232:19)
    at new AtomEnvironment (/opt/atom/resources/app.asar/src/atom-environment.js:250:19)
    at module.exports (/opt/atom/resources/app.asar/src/initialize-application-window.js:19:19)
    at setupWindow (file:///opt/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///opt/atom/resources/app.asar/static/index.js:41:9)

I tried to open it from the command line

**Comment by kingdido999** [comment]
This is a bug on linux reported before: #9569

**Comment by 50Wliu** [comment]
Thanks @kingdido999!
