### ISSUE TITLE
Initial window size is only a few pixels wide on Linux

### ISSUE THREAD

**Issue by stevejarvis** [atom/atom#10649]
I followed the instructions to install on Fedora 23 and I get no application window when launched from the command line or the desktop. 

In the end, it does imply the window is open, and the atom process continues to run, there's simply no UI other than the menu bar drop down. 

This is Fedora 23 with Gnome, Atom version 1.4.1-0.1.fc21. Same behavior on both x11 and wayland.

Here is what ends up in syslog. Any ideas what's going on? Let me know what other information might be helpful.

```
[7165:0201/205854:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[7165:0201/205854:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[7165:0201/205854:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[7165:0201/205854:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[7165:0201/205854:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[7212:0201/205854:ERROR:renderer_main.cc(200)] Running without renderer sandbox
auto-updater is not implemented on this platform
Error: auto-updater is not implemented on this platform
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:11:13)
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:14:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at AutoUpdateManager.module.exports.AutoUpdateManager.setupAutoUpdater (/usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:51:23)
    at /usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:42:24
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at NavigationController.loadUrl (/usr/share/atom/resources/atom.asar/browser/api/lib/navigation-controller.js:59:24)
    at EventEmitter.webContents.(anonymous function) [as loadUrl] (/usr/share/atom/resources/atom.asar/browser/api/lib/web-contents.js:81:27)
    at BrowserWindow.loadUrl (/usr/share/atom/resources/atom.asar/browser/api/lib/browser-window.js:121:37)
    at AtomWindow.module.exports.AtomWindow.setLoadSettings (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:124:33)
    at new AtomWindow (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:110:12)
    at AtomApplication.module.exports.AtomApplication.openPaths (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:686:24)
    at AtomApplication.module.exports.AtomApplication.openWithOptions (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:132:21)
    at AtomApplication.module.exports.AtomApplication.loadState (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:770:16)
    at new AtomApplication (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:114:14)
    at createAtomApplication (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:60:16)
    at Function.module.exports.AtomApplication.open (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:63:9)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/main.js:55:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
App load time: 390ms
[7165:0201/205855:INFO:CONSOLE(52)] "Window load time: 970ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (52)
[7165:0201/205855:INFO:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
[7165:0201/205855:INFO:CONSOLE(0)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  
```

**Comment by 50Wliu** [comment]
@stevejarvis Can you clarify what you mean by the "menu bar drop down"?  Thanks.

Also, the `auto-updater` stacktrace is completely harmless (and has been fixed in #9627).

**Comment by stevejarvis** [comment]
@50Wliu yeah, I meant the top bar in the Gnome3 desktop. I don't know if its presence is significant, it just demonstrates that the app is running and has focus. Here's a screenshot:

![atom-shot](https://cloud.githubusercontent.com/assets/2515575/12737805/a1118af2-c929-11e5-989c-584891086b5a.png)

**Comment by 50Wliu** [comment]
Ok...there's been a few issues where Atom actually spawns offscreen - can you see if that's the case here?

**Comment by stevejarvis** [comment]
Hey, that wasn't the case here, but it did lead to solving the mystery... I used the keyboard shortcut to fill the current window (super + up arrow) and atom filled the screen, so the window exists. Then I dragged the window (in Gnome3 dragging a maximized window will reset it to its previous size) and it disappeared again.

It seems that the default window size is literally a single pixel (or something equally invisible). So the window is there, it just has a 1x1 size or something, and this issue is mistitled, but still seems like a problem.

I'm on a HiDPI monitor with scaling in effect, [like described on the Arch wiki](https://wiki.archlinux.org/index.php/HiDPI), and that seems potentially relevant now.

**Comment by lee-dohm** [comment]
You might want to try:

1. Completely exiting all instances of Atom
1. Deleting the `~/.atom/storage` directory
1. Starting Atom as normal

Let us know if that helps.

**Comment by GeorgeSapkin** [comment]
Clearing `~/.atom/storage` didn't solve it for me on 1.4.2. Had to revert to 1.3.3.

**Comment by stevejarvis** [comment]
@lee-dohm this was a brand new install, atom didn't exist on this system beforehand.

**Comment by 50Wliu** [comment]
This was reported before at #5900, but the person couldn't reproduce it :confused:.

**Comment by GeorgeSapkin** [comment]
Same issue with 1.5.1.

**Comment by GeorgeSapkin** [comment]
Same issue with 1.6.0 beta 8. What can I do to help resolve this?

**Comment by GeorgeSapkin** [comment]
After looking into it, looks like the issue is with Maximus Two extension for Gnome: https://extensions.gnome.org/extension/844/maximus-two/
After disabling it Atom 1.6.0 seems to load. It is virtually the only program that has an issue with that extension though.

**Comment by tosalles** [comment]
Thanks for the hint @GeorgeSapkin :) For me disabling the Maximus Two Gnome extension also worked. For me my cursor changed to a cross on startup of Atom. Until I clicked somewhere with mouse, Atom seemed started (as @stevejarvis' screenshot showed) but no window was visible. After the mouse click, the Atom window appeared and everything works well.

Workaround for me is using the Maximus NG extension and blacklist Atom in its configuration (so the extension is not activated for Atom windows).https://extensions.gnome.org/extension/1026/maximus-ng/

Fedora 23, Gnome 3.18.2, Atom 1.6.2,

**Comment by 50Wliu** [comment]
@stevejarvis Do you also have the Maximus Two extension?

**Comment by stevejarvis** [comment]
I do not, no.

**Comment by bashtoni** [comment]
I have this issue too, and do not have the Maximum Two extension.  I have a keyboard shortcut bound to maximise, and when hitting that key combo atom was visible.  Prior to that I tried clear the .atom dir and it did nothing.

I have a HiDPI display, which may or may not be relevant.

**Comment by lee-dohm** [comment]
@bashtoni The latest versions of Atom don't store their saved state in `~/.atom/storage` anymore. To clear the state now you can exit Atom and then launch it with `atom --clear-window-state`.

**Comment by AaronM04** [comment]
I'm experiencing this problem with Fedora 24 on a HiDPI (4K resolution) display with GNOME 3. I don't have the Maximus Two extension installed. The state of `~/.atom` doesn't make a difference (I moved it out of the way and restarted Atom and the problem persisted).

Pressing Super-Up does make the window appear, as @stevejarvis described.

I think the problem here is that the Atom window's default size can be extremely tiny in some situations. I can tell this because if I drag it away from being maximized, the window appears to be only a couple pixels wide and about as high as the title bar.

**Comment by 50Wliu** [comment]
Ok, it looks like this might have something to do with HiDPI/scaling.
