### ISSUE TITLE
Uncaught Error: Invalid package /opt/atom/resources/app.asar

### ISSUE THREAD

**Issue by hynekdav** [atom/atom#10704]
Fresh installation of atom.

**Atom Version**: 1.4.3
**System**: Ubuntu 14.04.3
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: Invalid package /opt/atom/resources/app.asar

```
At /usr/share/atom/resources/app.asar/src/workspace.js:497

Error: Invalid package /opt/atom/resources/app.asar
    at invalidArchiveError (ATOM_SHELL_ASAR.js:117:13)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:141:9)
    at Workspace.module.exports.Workspace.openTextFile (/usr/share/atom/resources/app.asar/src/workspace.js:539:27)
    at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app.asar/src/workspace.js:472:23)
    at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app.asar/src/workspace.js:404:19)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/usr/share/atom/resources/app.asar/src/atom-environment.js:1038:19)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:244:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "language-shellscript",
      "language-shellscript"
    ],
    "ignoredNames": [
      ".* *~"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```
### Installed Packages

``` coffee
# User
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Refs #9653.
