### ISSUE TITLE
ATOM_DEV_RESOURCE_PATH needs to be set to run specs

### ISSUE THREAD

**Issue by PaulAik** [atom/atom#10719]
Having some trouble running the test specs on OSX on version 1.6.0-dev-17bf2b4 (latest from master).

The command `atom --test spec` produces:

```
Downloading Update: Could not get code signature for running application
[26691:0206/133702:INFO:CONSOLE(85)] "Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'atom-styles'. A type with that name is already registered.
  at Error (native)
  at Object.<anonymous> (/Users/paulaikman/dev/Git/external/unchangedAtom/src/styles-element.coffee:117:43)
  at Object.<anonymous> (/Users/paulaikman/dev/Git/external/unchangedAtom/src/styles-element.coffee:1:1)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/paulaikman/dev/Git/external/unchangedAtom/src/atom-environment.coffee:12:17)
  at Object.<anonymous> (/Users/paulaikman/dev/Git/external/unchangedAtom/src/atom-environment.coffee:1:1)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/paulaikman/dev/Git/external/unchangedAtom/spec/atom-environment-spec.coffee:6:19)
  at Object.<anonymous> (/Users/paulaikman/dev/Git/external/unchangedAtom/spec/atom-environment-spec.coffee:1:1)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at requireSpecs (/Applications/Atom.app/Contents/Resources/app.asar/spec/jasmine-test-runner.js:94:9)
  at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/spec/jasmine-test-runner.js:47:7)
  at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-test-window.js:71:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
", source: /Applications/Atom.app/Contents/Resources/app.asar/src/initialize-test-window.js (85)
```

Atom runs fine when booted up, but I can't seem to get the tests to pass using the script/test method (runs the specs, but fails some) or apm test (same error as above) method either.

Environment:

Node v4.1.1
Python 2.7.10
OSX 10.11.2

**Comment by lee-dohm** [comment]
It seems to be working for me using Atom v1.6.0-dev-ed43eda on Mac OS X 10.11.3. (I haven't tried from the commit you mention.) I know there are some environment variables that can be set that help things run better at the command line. All I seem to have set though is `ATOM_REPOS_HOME`. I also have `~/github` symlinked to the same directory listed in `ATOM_REPOS_HOME`.

**Comment by 50Wliu** [comment]
I'd like to chime in that I'm hitting this as well in a Cloud9 workspace.  `script/clean && script/build && sudo script/grunt install` doesn't seem to fix the issue.  I don't believe I have any Atom environment variables set.

I've also run into this on Windows, but I forget exactly how I resolved it (if I ever did).

**Comment by PaulAik** [comment]
Grabbed the latest and tried again, unfortunately same result. 

I tried running `script/test` again: it ran the tests, but gave a series of failures in notifications specs and welcome specs with the error _Error Downloading Update: Could not get code signature for running application_ and then output from the various failed tests, e.g:

```
 Error Downloading Update: Could not get code signature for running application
 ......F.
 
 Welcome
   reporting events
     GuideView events
       it captures button events
         Error: Leaking subscriptions for paths: /Users/paulaikman/.atom/init.coffee
           at ensureNoPathSubscriptions (/Users/paulaikman/Dev/Git/external/atom/spec/spec-helper.coffee:122:15)
           at [object Object].<anonymous> (/Users/paulaikman/Dev/Git/external/atom/spec/spec-helper.coffee:115:3)
```

I had another look through the documentation, but couldn't find much more on how to set up my dev environment for contributing to core.

Also tried booting up the package test suite within atom (opened in dev mode with the source directory set as the repo root), but it didn't go so well:

![image](https://cloud.githubusercontent.com/assets/99102/12899738/d62d4452-ceaa-11e5-8c03-8e0b52e02cee.png)

**Comment by 50Wliu** [comment]
> Error Downloading Update: Could not get code signature for running application

That error seems to be harmless.  Not sure about the leaking subscriptions.

Can you also share the failing Notifications specs?

**Comment by lee-dohm** [comment]
When I run `script/test` I get some notifications package test failures ... but I don't want this to turn into an Issue tracking "Atom has some specs failing" :grinning: So let's try to limit this to `atom --test spec` or `apm test` from atom/atom and get your environment working @PaulAik.

Also you mention:

> I tried running `script/test` again: it ran the tests

This would seem to indicate that your environment is working.

**Comment by PaulAik** [comment]
Ok, summarising to help focus the issue:

- Grabbing latest and running `script/test` after a `script/clean` and `script/build` results in one failure in the welcome specs. I can confirm the notification tests pass after a fresh clean and rebuild.
- `atom --test spec` results in the `ailed to execute 'registerElement' on 'Document'` error noted above.
- Trying to run the specs inside atom via the spec runner results in a similar issue.

Appreciate I can probably get on with what I was looking to fix originally the `script/test` method, but I'm keen to figure out why the other methods fail. If it's just a missing env variable or setup step, we can add it to the docs for others in the same situation.

**Comment by joshaber** [comment]
I had this problem when I first started working on Atom too. You should be able to fix it by setting the `ATOM_DEV_RESOURCE_PATH` environment variable to the path of the local Atom clone (`~/Dev/Git/external/atom` from the look of it).

See https://github.com/atom/atom/issues/3872#issuecomment-59540222 for more info.

**Comment by PaulAik** [comment]
Thanks @joshaber. That allowed the specs to start running via the command line (still got an error in the GUI spec runner), but I was getting all sorts of errors and test failures.

When I moved the files to the default directory (~/github/atom), everything started to work as it should.

I guess at this stage we could update the docs to say "install to this directory for tests to work", or figure out why setting the `ATOM_DEV_RESOURCE_PATH` didn't have the desired effect?

I had a look for where that variable is used, and it seems to be within [src/browser/main.coffee](https://github.com/atom/atom/blob/master/src/browser/main.coffee), but I couldn't see this file loaded via the inspector when atom was running. Not sure if I'm able to see it at that point.

**Comment by 50Wliu** [comment]
"Module did not self-register" usually indicates that one of the native modules was built incorrectly.  I'm not sure why it would magically start to work though if you moved it to `~/github/atom`.

**Comment by joshaber** [comment]
>still got an error in the GUI spec runner

Ah, so I should have noted: if you're setting the environment variable, that'll only get inherited into Atom's environment if it is launched from the command line. Apps launched from, e.g., the Dock, don't get their environment from anywhere useful.

**Comment by PaulAik** [comment]
@50Wliu yeah it's a strange one! Could possibly be a side-effect of something else in the environment.

@joshaber no worries, it's pretty clear what's going on with the var in `main.coffee`. I was launching atom with `atom -d` after setting `ATOM_DEV_RESOURCE_PATH`.

Current conclusion: `¯\_(ツ)_/¯`

**Comment by lee-dohm** [comment]
Sounds like this is a bug somewhere.

@PaulAik I wanted to make sure that you do have a working environment. Can you confirm?

**Comment by PaulAik** [comment]
Tried again with latest tonight, results are (in terminal):

- running `script/clean` then `script/build` then running the specs in `~/github/atom` results in successful boot of the test runner and passing tests.
- executing `export ATOM_DEV_RESOURCE_PATH=/users/paulaikman/my-custom-dir`, then running `script/clean` then `script/build`, then running the specs in `/users/paulaikman/my-custom-dir` results in failure to run tests (error shown in screenshot above).

The above should be fairly easy to replicate on another Mac to confirm whether it's a real issue or not!

**Comment by lee-dohm** [comment]
I can reproduce the described behavior after I deleted my symlink from `~/github` to my source directory, whether or not I set `ATOM_DEV_RESOURCE_PATH`.

**Comment by ArnaudRinquin** [comment]
I had got the exact same issue as @PaulAik, I was able to run the tests after:

1. `export ATOM_DEV_RESOURCE_PATH=/path/to/atom/repo`
1. `apm test`

**Comment by lee-dohm** [comment]
@ArnaudRinquin Which version of Atom are you using?

**Comment by PaulAik** [comment]
@ArnaudRinquin also... can you run the specs from the GUI spec suite (see error I get above)?

**Comment by ArnaudRinquin** [comment]
@lee-dohm I was using latest `master` on OS X

@PaulAik I can run them from both `apm test` and from `View > Developers > Run package specs`

**Comment by PaulAik** [comment]
@ArnaudRinquin merged latest and it seems to be working for me. 

Thanks for testing everyone!

**Comment by 50Wliu** [comment]
Re-opening as it's not documented anywhere that `ATOM_DEV_RESOURCE_PATH` needs to be set in order to run specs, and really it shouldn't be needed in the first place.
