### ISSUE TITLE
Atom problem.

### ISSUE THREAD

**Issue by ShadowXsc** [atom/atom#10718]
![screenshot from 2016-02-06 12 02 45](https://cloud.githubusercontent.com/assets/17096004/12866106/0cc3b826-ccca-11e5-8570-44d449b1b054.png)

That's all I can do in Atom, what should I do now?
I've tried to reinstall, the same result..

P.S.: I don't speak english good.. so.. please don't blame me for what I'm writing here.

**Comment by 50Wliu** [comment]
@ShadowXsc Please click the red `X` button with a 1 next to it and copy/paste the error here.  Thanks!

**Comment by disc0ninja** [comment]
I am having the same issue here is my error:

`Error: EPERM: operation not permitted, open 'C:\Users\disc0\.atom\compile-cache\less\e55f7f0c2f1464335d05bab6adf25375ec61d0f7\imports.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.writeFileSync (fs.js:1171:15)
    at Object.fsPlus.writeFileSync (C:\Users\disc0\Documents\tools\Atom\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (C:\Users\disc0\Documents\tools\Atom\resources\app.asar\node_modules\less-cache\lib\less-cache.js:155:17)
    at LessCache.module.exports.LessCache.setImportPaths (C:\Users\disc0\Documents\tools\Atom\resources\app.asar\node_modules\less-cache\lib\less-cache.js:113:12)
    at new LessCache (C:\Users\disc0\Documents\tools\Atom\resources\app.asar\node_modules\less-cache\lib\less-cache.js:32:12)
    at new LessCompileCache (C:\Users\disc0\Documents\tools\Atom\resources\app.asar\src\less-compile-cache.js:20:20)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\disc0\Documents\tools\Atom\resources\app.asar\src\theme-manager.js:270:26)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (C:\Users\disc0\Documents\tools\Atom\resources\app.asar\src\theme-manager.js:257:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (C:\Users\disc0\Documents\tools\Atom\resources\app.asar\src\theme-manager.js:174:24)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (C:\Users\disc0\Documents\tools\Atom\resources\app.asar\src\theme-manager.js:237:12)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (C:\Users\disc0\Documents\tools\Atom\resources\app.asar\src\theme-manager.js:232:19)
    at new AtomEnvironment (C:\Users\disc0\Documents\tools\Atom\resources\app.asar\src\atom-environment.js:250:19)
    at module.exports (C:\Users\disc0\Documents\tools\Atom\resources\app.asar\src\initialize-application-window.js:19:19)
    at setupWindow (file:///C:/Users/disc0/Documents/tools/Atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///C:/Users/disc0/Documents/tools/Atom/resources/app.asar/static/index.js:41:9)`

**Comment by ShadowXsc** [comment]
I just uninstall the atom editor text, and then detele all the cache files from home (~) directory..
Then... reinstall it and works!...

Sorry for useless TOPIC, my bad. You can close it now.

**Comment by 50Wliu** [comment]
Ok, thanks for the update @ShadowXsc!
