### ISSUE TITLE
Compilation error on FreeBSD

### ISSUE THREAD

**Issue by amiramix** [atom/atom#10739]
Following instructions from here:
https://github.com/atom/atom/blob/master/docs/build-instructions/freebsd.md

The same error no matter if compiling as unprivileged user or as root:

```
g@serv:~/atom % script/build
Node: v5.5.0
npm: v2.14.7
Installing build modules...
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 526, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 502, in gyp_main
    params, options.check, options.circular_check)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2756, in Load
    RemoveLinkDependenciesFromNoneTargets(targets)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1501, in RemoveLinkDependenciesFromNoneTargets
    if targets[t].get('variables', {}).get('link_dependency', 0):
KeyError: 'deps/breakpad/breakpad.gyp:dump_syms#target'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System FreeBSD 10.2-RELEASE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/g/atom/build/node_modules/minidump
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! FreeBSD 10.2-RELEASE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--userconfig=/usr/home/g/atom/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v5.5.0
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minidump@0.9.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/g/atom/build/npm-debug.log
```

```
root@serv:~/atom # script/build
Node: v5.5.0
npm: v2.14.7
Installing build modules...
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 526, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 502, in gyp_main
    params, options.check, options.circular_check)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2756, in Load
    RemoveLinkDependenciesFromNoneTargets(targets)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1501, in RemoveLinkDependenciesFromNoneTargets
    if targets[t].get('variables', {}).get('link_dependency', 0):
KeyError: 'deps/breakpad/breakpad.gyp:dump_syms#target'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System FreeBSD 10.2-RELEASE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/atom/build/node_modules/minidump
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! FreeBSD 10.2-RELEASE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--userconfig=/root/atom/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v5.5.0
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minidump@0.9.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/atom/build/npm-debug.log
```

[npm-debug.log.txt](https://github.com/atom/atom/files/122882/npm-debug.log.txt)

```
g@serv:~/atom % uname -a
FreeBSD crayon2.yoonka.com 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 15:26:37 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

```
root@serv:~/atom # npm config list
; cli configs
user-agent = "npm/2.14.7 node/v5.5.0 freebsd x64"

; globalconfig /usr/local/etc/npmrc
python = "/usr/local/bin/python2"

; node bin location = /usr/local/bin/node
; cwd = /root/atom
; HOME = /root
; 'npm config ls -l' to show all defaults.
```

```
root@serv:~/atom # pkg version | egrep "node|npm|libgnome-keyring"
libgnome-keyring-3.12.0_2          =
node-5.5.0                         =
npm-2.14.7_2                       =
```

**Comment by hyshka** [comment]
I get virtually the same error when building.

`OpenBSD 5.8
Node 0.10.35
npm 1.4.28
libgnome-keyring 3.12.0
python 2.7.10
gcc 4.2.1`

It doesn't seem to be related to package versions so it could be BSD specific.

**Comment by 50Wliu** [comment]
Ok, closing in favor of #6035.

**Comment by kenno** [comment]
This issue is not exactly the same as #6035. This one is related to building Atom on FreeBSD 10.2 vs 11.0 (on #6035).

Could this issue be re-opened and renamed to Atom fail to build on FreeBSD 10.2?
Alternatively, I can also create a new issue if it's preferred.

Thanks.

**Comment by 50Wliu** [comment]
@kenno would the versions be similar enough that they would experience the same problems?  That seems to be what's happening.

**Comment by kenno** [comment]
@50Wliu the versions of node and npm packages could be a bit newer on FreeBSD 11.0. Unfortunately, I don't have 11.0 to test.
Well, on a second thought, since there has been no luck on 11.0  yet, maybe it's related after all.

There's no need to re-open this issue. Thanks for your attention.

**Comment by amiramix** [comment]
I think the priority is to fix the build on any FreeBSD version. Once that's done it should be easy to port the fix to other versions if necessary.

**Comment by indykish** [comment]
@amiramix @hyshka  Is anyone running atom in `FreeBSD` or its still `broke` ?

**Comment by amiramix** [comment]
I didn't check since I posted the bug.

**Comment by hyshka** [comment]
Same here. Doesn't seem like there's been much progress. If you take a look at #6035 they seem to think it will take significant developer investment.
