### ISSUE TITLE
After update, Atom crashes on start (segfault)

### ISSUE THREAD

**Issue by tinloaf** [atom/atom#10759]
Hi,

I just upgraded my atom to the latest git master. Please don't ask me what version I was using before... ;) I'm running Gentoo Linux.

Now, when I start Atom, I get a segfault with this backtrace:

```
tinloaf@janeway LabelRotation % /home/tinloaf/opt/atom/bin/atom: line 117: 28084 Segmentation fault      nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 221ms
auto-updater is not implemented on this platform
Error: auto-updater is not implemented on this platform
    at Object.<anonymous> (/home/tinloaf/opt/atom/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:11:13)
    at Object.<anonymous> (/home/tinloaf/opt/atom/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:14:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/home/tinloaf/opt/atom/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at AutoUpdateManager.module.exports.AutoUpdateManager.setupAutoUpdater (/home/tinloaf/opt/atom/share/atom/resources/app.asar/src/browser/auto-update-manager.js:62:23)
    at /home/tinloaf/opt/atom/share/atom/resources/app.asar/src/browser/auto-update-manager.js:53:24
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Failed to get crash dump id.
Report Id:
```

Please let me know if I can help you in any way tracking down this crash. I know how to handle a debugger, if that helps.

**Comment by tinloaf** [comment]
PS: Since "latest git master" might be rather volatile - I'm at 3cca5cdc3e124860ebc67cfb926d2efbba3ab477

**Comment by tinloaf** [comment]
I just tried 1.5.0 and 1.6.0-beta0, both are also affected, although the traceback looks slightly different:

```
tinloaf@janeway LabelRotation % /home/tinloaf/opt/atom/bin/atom: line 117: 28873 Segmentation fault      nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
auto-updater is not implemented on this platform
Error: auto-updater is not implemented on this platform
    at Object.<anonymous> (/home/tinloaf/opt/atom/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:11:13)
    at Object.<anonymous> (/home/tinloaf/opt/atom/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:14:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/home/tinloaf/opt/atom/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at AutoUpdateManager.module.exports.AutoUpdateManager.setupAutoUpdater (/home/tinloaf/opt/atom/share/atom/resources/app.asar/src/browser/auto-update-manager.js:62:23)
    at /home/tinloaf/opt/atom/share/atom/resources/app.asar/src/browser/auto-update-manager.js:53:24
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at NavigationController.loadUrl (/home/tinloaf/opt/atom/share/atom/resources/atom.asar/browser/api/lib/navigation-controller.js:59:24)
    at EventEmitter.webContents.(anonymous function) [as loadUrl] (/home/tinloaf/opt/atom/share/atom/resources/atom.asar/browser/api/lib/web-contents.js:81:27)
    at BrowserWindow.loadUrl (/home/tinloaf/opt/atom/share/atom/resources/atom.asar/browser/api/lib/browser-window.js:121:37)
    at AtomWindow.module.exports.AtomWindow.setLoadSettings (/home/tinloaf/opt/atom/share/atom/resources/app.asar/src/browser/atom-window.js:124:33)
    at new AtomWindow (/home/tinloaf/opt/atom/share/atom/resources/app.asar/src/browser/atom-window.js:110:12)
    at AtomApplication.module.exports.AtomApplication.openPaths (/home/tinloaf/opt/atom/share/atom/resources/app.asar/src/browser/atom-application.js:710:24)
    at AtomApplication.module.exports.AtomApplication.openWithOptions (/home/tinloaf/opt/atom/share/atom/resources/app.asar/src/browser/atom-application.js:131:21)
    at new AtomApplication (/home/tinloaf/opt/atom/share/atom/resources/app.asar/src/browser/atom-application.js:111:14)
    at createAtomApplication (/home/tinloaf/opt/atom/share/atom/resources/app.asar/src/browser/atom-application.js:60:16)
    at Function.module.exports.AtomApplication.open (/home/tinloaf/opt/atom/share/atom/resources/app.asar/src/browser/atom-application.js:63:9)
    at EventEmitter.<anonymous> (/home/tinloaf/opt/atom/share/atom/resources/app.asar/src/browser/main.js:55:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
App load time: 485ms
Failed to get crash dump id.
Report Id: 

```

**Comment by Zireael07** [comment]
Auto-updater isn't implemented on Linux.

No clue why that would prevent you from starting, though. Maybe related somehow to the recent addition of an option that allows you to disable auto-update?

**Comment by 50Wliu** [comment]
The auto-updater stacktrace is harmless and doesn't break anything.

**Comment by tinloaf** [comment]
Oh! This does not seem to be a problem in Atom itself, but rather in the build process:

I tried compiling different versions and when going backwards, I started to do "scripts/clean" in between builds. That actually fixed it, i.e. after a "scripts/clean ; scripts/build", current master also works for me.

The question is: Should the build process work for upgrades without doing "scripts/clean"? If so, this still is a bug (altough a very different one). If not, it's just my stupidity.

Shall I close this issue?

**Comment by 50Wliu** [comment]
Sorry for the late response - `script/clean` is generally not needed between upgrades, though sometimes it is because the build script isn't smart enough to realize that the dependency structure/version changed.  You probably ran into a problem of Atom expecting one Electron version but receiving a different one.

Closing this for now but if you experience it again please feel free to create a new issue!
