### ISSUE TITLE
Spawn/ENOENT thrown if the app is moved while it is open

### ISSUE THREAD

**Issue by joshaber** [atom/atom#10774]
https://github.com/atom/atom/issues/9594 is a good example of this.

**Comment by losmaven** [comment]
seeing this issue after i moved a file to a different directory while the file was open in Atom.
interestingly, i cannot reproduce it by creating a new file and then moving it to a different directory while it is open, but it keeps happening only for this 1 particular file! and it happens even if i quite Atom and restart it!
i had installed a Package called file-watcher and that was the only recent change in Atom for me, but even after i uninstalled the package, i am still seeing this issue.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: ENOENT: no such file or directory, close

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:896

Error: ENOENT: no such file or directory, close
    at Error (native)
    at Object.fs.closeSync (fs.js:518:18)
    at Object.closeSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/graceful-fs/graceful-fs.js:51:27)
    at Object.fs.writeFileSync (fs.js:1188:8)
    at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:282:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:398:21)
    at File.module.exports.File.writeSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:355:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1059:19)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1043:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:629:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:613:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:596:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:673:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:205:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:37.2.0 core:save (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:35 tool-panel:unfocus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:33.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:33.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:00.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "genesis-syntax"
    ]
  },
  "editor": {
    "fontSize": 11,
    "invisibles": {},
    "preferredLineLength": 120,
    "showIndentGuide": true,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
genesis-syntax, v1.0.6
language-groovy, v0.6.0
linter, v1.11.4
linter-flake8, v1.13.0
python-indent, v0.4.2
python-tools, v0.6.7

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@losmaven Your issue doesn't seem to be related to this one.  If you can still reproduce it after deleting the `~/.atom/storage` folder and trying safe mode (`atom --safe`), please file a new issue.  Thanks!

**Comment by losmaven** [comment]
@50Wliu tried after performing the steps in your suggestion and still seeing this issue! will open a new issue.

**Comment by EmiLithium** [comment]
So my issue #17796 got marked as a duplicate of this one, but I never moved my Atom while it was open. 

I did have a problem where Atom didn't install the `bin` folder in `%LOCALAPPDATA%\Atom\`. I had to run these commands:

    > cd %LOCALAPPDATA%\Atom\
    > atom --squirrel-updated

This was the only change I made in my folder before I started getting my "Uncaught Error: ENOENT" error message.
