### ISSUE TITLE
Uncaught TypeError: view[methodName] is not a function

### ISSUE THREAD

**Issue by Huaraz2** [atom/atom#10776]
[Enter steps to reproduce below:]

1. Install git-control and pull down my tags PR: jacogr/atom-git-control/pull/151
2. try to push tags to origin or upstream via my `Push Tags` button.

**Atom Version**: 1.5.3
**System**: Ubuntu 15.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: view[methodName] is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220

TypeError: view[methodName] is not a function
    at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:08.2.0 git-control:toggle (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "packagesWithKeymapsDisabled": [
      "activate-power-mode",
      "latex"
    ],
    "projectHome": "/home/huaraz2/Documents/Programming/",
    "themes": [
      "one-dark-ui",
      "the-matrix-syntax"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "fontSize": 15,
    "invisibles": {},
    "softWrap": true,
    "softWrapAtPreferredLineLength": true
  }
}
```

### Installed Packages

```coffee
# User
achievements, v0.9.0
atom-2048, v3.1.0
atom-typescript, v8.2.0
autocomplete-bibtex, v0.6.2
autocomplete-python, v1.6.1
battery-status, v0.10.3
bottom-dock, v0.3.7
color-picker, v2.1.1
contextual-preview, v0.1.0
git-control, v0.4.0
language-SCSS, v0.4.0
language-brainfuck, v0.2.0
language-haskell, v1.5.2
language-latex, v0.6.1
language-r, v0.4.0
language-sage, v0.3.0
language-vb, v0.1.0-pre1
latex, v0.29.0
latextools, v0.7.6
less-autocompile, v1.0.0
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-hlint, v0.4.3
linter-htmlhint, v1.0.2
linter-manager, v0.2.8
linter-pylint, v1.2.0
linter-shellcheck, v1.1.0
minimap, v4.19.0
minimap-linter, v1.1.1
pigments, v0.23.1
rst-preview-pandoc, v0.1.12
terminal-plus, v0.14.5
the-matrix-syntax, v0.5.1
tree-view-background, v0.4.0

# Dev
git-control, v0.7.0
linter-coffeelint, v1.1.2
```

**Comment by lee-dohm** [comment]
This sounds like there is a bug in your code. Have you tried debugging the code that is connected to your `Push Tags` button?
