### ISSUE TITLE
Empty folder problem

### ISSUE THREAD

**Issue by keremciu** [atom/atom#10796]
I tried to open a empty folder on Atom with right click commands, I found a bug

12/02/16 19:58:21,679 Atom[4497]: Cannot read property 'substr' of null
12/02/16 19:58:21,680 Atom[4497]: TypeError: Cannot read property 'substr' of null
    at AtomWindow.module.exports.AtomWindow.getLoadSettings (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-window.js:135:71)
    at AtomApplication.module.exports.AtomApplication.saveState (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:777:37)
    at BrowserWindow.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:198:26)
    at emitOne (events.js:82:20)
    at BrowserWindow.emit (events.js:169:7)

It's not working now.

OS X: El Capitan
Atom: 1.5.2

**Comment by amytruong** [comment]
Can you clarify the steps you used to open the empty folder? 
Going to try and take reproduce this if I can for you. Thank you!
