### ISSUE TITLE
editor is blank

### ISSUE THREAD

**Issue by Yomi0** [atom/atom#10847]
![shot-2016-02-16_18-28-06](https://cloud.githubusercontent.com/assets/3170531/13094778/114a968a-d4db-11e5-9054-27a13eadd44d.png)

Console appears on launch with the following: 
```
Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:170:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/node_modules/nodegit/lib/nodegit.js:7:12)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository-async.js:25:16)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository.js:12:24)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository.js:428:4)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
```

Atom Version: 1.7.0-dev-41161dd

**Comment by lee-dohm** [comment]
Have you tried running `script/clean` followed by `script/build`?

**Comment by Yomi0** [comment]
Ran ```script/clean``` and rebuilt. The editor loads, but crashes shortly afterwards. 
Same atom version as above.

**Comment by lee-dohm** [comment]
What does it crash with?

**Comment by Yomi0** [comment]
Running atom via terminal produces no output when ```atom --dev --log-file```. 
Where is the log file stored?

It simply crashes with a dialog displaying, The editor has crashed. 

![screenshot_2016-02-16_22-59-39](https://cloud.githubusercontent.com/assets/3170531/13099524/feaa880c-d500-11e5-883c-4e76d5d9ebcd.png)

**Comment by pleonex** [comment]
In most Linux distros you need to enable the coredump with `ulimit -c unlimited` (by default the max coredump size is set to 0).

After `script/clean` it's working for me in Fedora 23 with Gnome 3 (the first time I started, just when I saw the Atom window, gnome-shell crashed...)

PS: It could be a good idea to include a note for the `script/clean` step in the build instructions.

**Comment by Yomi0** [comment]
> In most Linux distros you need to enable the coredump with ulimit -c unlimited (by default the max coredump size is set to 0).

> After script/clean it's working for me in Fedora 23 with Gnome 3 (the first time I started, just when I saw the Atom window, gnome-shell crashed...)

> PS: It could be a good idea to include a note for the script/clean step in the build instructions.

I enabled coredump and ran atom again, but atom doesn't seem to be producing a coredump.

**Comment by Yomi0** [comment]
I checked out to cfab689 and built atom and it works. 
Checked out one commit ahead, 4bc969d, and I met that white atom window I posted at the very top of this issue. (I ran script/clean)

**Comment by lee-dohm** [comment]
Try `rm -rf ./node_modules/nodegit` and then build again.

**Comment by Yomi0** [comment]
> Try rm -rf ./node_modules/nodegit and then build again.

I tried that and rebuilt and it still crashes. 

I got a backtrace and it's pretty long and repeating...
 
[atomcrash.txt](https://github.com/atom/atom/files/137002/atomcrash.txt)

Atom    : 1.7.0-dev-fe1e9d5
Electron: 0.36.7
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by Yomi0** [comment]
Got it. Atom seems to have an issue with freetype versions > freetype2-2.6.2 (Arch Linux) 
Downgrading from 2.6.3 to 2.6.2 seems to have fixed it.
