### ISSUE TITLE
Uncaught TypeError: promise.then(...).fail is not a function

### ISSUE THREAD

**Issue by hoverlover** [atom/atom#10875]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: promise.then(...).fail is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:825

TypeError: promise.then(...).fail is not a function
    at ProjectPaletteFinder.scanProject (<anonymous>:228:6)
    at <anonymous>:116:10
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -0:33.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:33.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:32.2.0 editor:newline-above (atom-text-editor.editor.is-focused)
     -0:18.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:14.3.0 core:paste (atom-text-editor.editor.is-focused)
  4x -0:13 core:move-up (atom-text-editor.editor.is-focused)
     -0:11.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:10.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:09.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:07.4.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
  2x -0:07.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:06.1.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:05.8.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -0:05.6.0 core:move-left (atom-text-editor.editor.is-focused)
  4x -0:04.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-color-highlight"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "editor": {
    "fontSize": 13,
    "invisibles": {},
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
atom-eco, v0.2.0
atom-pair, v2.0.10
file-icons, v1.6.13
language-haml, v0.23.14
pain-split, v1.4.0
project-palette-finder, v2.4.15
react, v0.12.10
symbols-tree-view, v0.11.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The project-palette-finder is no longer maintained and it is suggested to instead use the [pigments](https://atom.io/packages/pigments) package.
