### ISSUE TITLE
Atom open always in developer mode.

### ISSUE THREAD

**Issue by ULTIMATEUPGRADE** [atom/atom#10880]
I build my atom from the github source. When I open atom from command line it always open in dev mode and shows the following error.

Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:170:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/home/harmony-12/Desktop/karthik/atom/out/Atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/harmony-12/Desktop/karthik/atom/out/Atom/resources/app.asar/node_modules/nodegit/lib/nodegit.js:7:12)
    at Module._compile (/home/harmony-12/Desktop/karthik/atom/out/Atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/home/harmony-12/Desktop/karthik/atom/out/Atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/home/harmony-12/Desktop/karthik/atom/out/Atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/harmony-12/Desktop/karthik/atom/out/Atom/resources/app.asar/src/git-repository-async.js:25:16)
    at Module._compile (/home/harmony-12/Desktop/karthik/atom/out/Atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/home/harmony-12/Desktop/karthik/atom/out/Atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/home/harmony-12/Desktop/karthik/atom/out/Atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/harmony-12/Desktop/karthik/atom/out/Atom/resources/app.asar/src/git-repository.js:12:24)
    at Object.<anonymous> (/home/harmony-12/Desktop/karthik/atom/out/Atom/resources/app.asar/src/git-repository.js:428:4)
    at Module._compile (/home/harmony-12/Desktop/karthik/atom/out/Atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/home/harmony-12/Desktop/karthik/atom/out/Atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/home/harmony-12/Desktop/karthik/atom/out/Atom/resources/app.asar/src/native-compile-cache.js:50:27)

**Comment by Kampfmoehre** [comment]
Get the same error since yesterday. My Node version is 0.10.25.

When you checkout the latest release like it is explained in https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md atom works as expected.

**Comment by 50Wliu** [comment]
Please try running `script/clean`, then `script/build` again.  The Electron version was bumped (which included a Chrome version bump as well) which may cause existing build modules to conflict.

**Comment by ULTIMATEUPGRADE** [comment]
I get this while doing the above steps

Node: v0.10.42
npm: v1.4.29
Installing build modules...
npm ERR! git clone https://github.com/atom/grunt-coffeelint.git Cloning into bare repository '/home/harmony-12/.atom/.npm/_git-remotes/https-github-com-atom-grunt-coffeelint-git-152db383'...
npm ERR! git clone https://github.com/atom/grunt-coffeelint.git fatal: unable to access 'https://github.com/atom/grunt-coffeelint.git/': Operation timed out after 0 milliseconds with 0 out of 0 bytes received
npm ERR! Error: Command failed: Cloning into bare repository '/home/harmony-12/.atom/.npm/_git-remotes/https-github-com-atom-grunt-coffeelint-git-152db383'...
npm ERR! fatal: unable to access 'https://github.com/atom/grunt-coffeelint.git/': Operation timed out after 0 milliseconds with 0 out of 0 bytes received
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:766:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "--userconfig=/home/harmony-12/Desktop/karthik/atom/build/.npmrc" "install" "--loglevel" "error"
npm ERR! cwd /home/harmony-12/Desktop/karthik/atom/build
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.4.29
npm ERR! code 128
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/harmony-12/Desktop/karthik/atom/build/npm-debug.log
npm ERR! not ok code 0

**Comment by 50Wliu** [comment]
Looks like a network issue.  Try again in a few hours.
