### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/redacted/.atom/packages/save-sessio...

### ISSUE THREAD

**Issue by smiller171** [atom/atom#10893]
[Enter steps to reproduce below:]

I have no idea how to reproduce this

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/smiller/.atom/packages/save-session/projects//Users/smiller/src/go-redirect/project.json'

```
At fs.js:60

Error: ENOENT: no such file or directory, open '/home/smiller/.atom/packages/save-session/projects//Users/smiller/src/go-redirect/project.json'
    at Error (native)
    at EventEmitter.ipc.sendSync (/Users/smiller/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Users/smiller/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Users/smiller/Downloads/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Users/smiller/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Users/smiller/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -5:40.4.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:36.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:26.2.0 tree-view:move (span.name.icon.icon-file-text)
     -5:24.9.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -5:24.2.0 core:delete (atom-text-editor.editor.mini.is-focused)
     -5:24 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -1:24.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:07.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
circle-ci, v0.10.1
fonts, v1.1.0
language-docker, v1.1.6
linter, v1.11.3
linter-pep8, v1.2.1
release-notes, v0.53.0
save-session, v0.15.7
saveallthetime, v0.2.1
sync-settings, v0.6.0
travis-ci-status, v1.0.0
vagrant, v0.1.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please uninstall the save-session package, as it has been deprecated and all of its existing functionality is now provided by Atom itself.

**Comment by smiller171** [comment]
Thanks @50Wliu
