### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/.atom/packages/save-session/projects//...

### ISSUE THREAD

**Issue by troyxmccall** [atom/atom#10906]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '~/.atom/packages/save-session/projects//Users/tmccall/projects/monodify/project.json'

```
At fs.js:60

Error: ENOENT: no such file or directory, open '~/.atom/packages/save-session/projects//Users/tmccall/projects/monodify/project.json'
    at Error (native)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as getSize] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:575:29)
    at AtomEnvironment.module.exports.AtomEnvironment.storeDefaultWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:607:25)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:181:35)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61
```

### Commands

```
     -1:46.8.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -1:37.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:34.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:18.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:18.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:16.7.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:15.7.0 project-find:show (atom-text-editor.editor.is-focused)
  2x -0:13.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:11.9.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
     -0:09.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 core:close (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:03.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-js-specs"
    ],
    "themes": [
      "flatland-dark-ui",
      "flatland"
    ]
  },
  "editor": {
    "fontSize": 15,
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
aligner-php, v1.0.0
angularjs, v0.3.4
atom-beautify, v0.28.22
atom-pair, v2.0.10
atom-wordpress, v0.3.0
autocomplete-php, v0.3.7
autocomplete-sass, v0.1.0
editor-stats, v0.17.0
editorconfig, v1.2.4
emmet, v2.4.1
flatland, v0.16.0
flatland-dark-ui, v0.2.4
language-apache, v1.4.0
language-applescript, v0.2.0
language-nginx, v0.6.1
laravel, v0.7.0
linter, v1.11.3
linter-php, v1.1.8
local-history, v3.2.3
markdown-preview-opener, v0.1.1
markdown-preview-plus, v2.2.2
node-debugger, v1.4.1
php-cs-fixer, v2.5.6
php-debug, v0.2.2
project-manager, v2.7.6
save-session, v0.16.0
tabs-to-spaces, v1.0.2
wakatime, v5.0.2
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please uninstall the `save-session` package, as it has been deprecated and all of its functionality is now provided by Atom itself.

**Comment by troyxmccall** [comment]
thanks @50Wliu
