### ISSUE TITLE
"This TextEditor has been destroyed" when closing a file opened in multiple panes

### ISSUE THREAD

**Issue by BinaryMuse** [atom/atom#10957]
### Description

Opening a file in two different panes and then closing one of them causes the other pane to be uneditable; it throws an exception:

```
Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:794:15)
    at TextEditorMarker.module.exports.TextEditorMarker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:179:33)
    at Cursor.module.exports.Cursor.getScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:73:26)
    at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1467:35)
    at TextEditor.module.exports.TextEditor.isFoldedAtCursorRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2670:44)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:123:23)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:41:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.handleChangedText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1320:20)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:834:14)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1251:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:639:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

Seems to be the same exception (though perhaps not the same cause) as #178.

### Steps to Reproduce

1. Open a file
2. Split a new pane
3. Open the same file
4. Close the newly opened file
5. Attempt to type in the original pane

### Versions

Observed on:

```
Atom    : 1.7.0-dev-5612f1a
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

and

```
Atom    : 1.7.0-dev-e39d200
Electron: 0.36.7
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by 50Wliu** [comment]
Confirmed by accident while trying to track down the cause of #10903.  Though for me the remaining pane is still editable; it just throws this error everytime you type something.  The error is also saying that it's from bracket-matcher.

Follow #10903's reproduction steps, reload Atom, close bottom pane, attempt to edit the pane that's left.

**Atom Version**: 1.7.0-dev-3bc9eb6
**System**: Microsoft Windows 10 Home
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.80.0


### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At C:\Program Files\Atom\resources\app.asar\src\display-buffer.js:794

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (C:\Program Files\Atom\resources\app.asar\src\display-buffer.js:794:15)
    at TextEditorMarker.module.exports.TextEditorMarker.getHeadScreenPosition (C:\Program Files\Atom\resources\app.asar\src\text-editor-marker.js:179:33)
    at Cursor.module.exports.Cursor.getScreenPosition (C:\Program Files\Atom\resources\app.asar\src\cursor.js:73:26)
    at TextEditor.module.exports.TextEditor.getCursorScreenPosition (C:\Program Files\Atom\resources\app.asar\src\text-editor.js:1467:35)
    at TextEditor.module.exports.TextEditor.isFoldedAtCursorRow (C:\Program Files\Atom\resources\app.asar\src\text-editor.js:2670:44)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (C:\Program Files\Atom\resources\app.asar\node_modules\bracket-matcher\lib\bracket-matcher-view.js:123:23)
    at C:\Program Files\Atom\resources\app.asar\node_modules\bracket-matcher\lib\bracket-matcher-view.js:41:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Program Files\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Program Files\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.emitChangeTextEvent (C:\Program Files\Atom\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1332:20)
    at TextBuffer.module.exports.TextBuffer.transact (C:\Program Files\Atom\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:845:14)
    at TextEditor.module.exports.TextEditor.transact (C:\Program Files\Atom\resources\app.asar\src\text-editor.js:1251:26)
    at C:\Program Files\Atom\resources\app.asar\src\text-editor.js:845:24
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Program Files\Atom\resources\app.asar\src\text-editor.js:2143:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Program Files\Atom\resources\app.asar\src\text-editor.js:2109:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Program Files\Atom\resources\app.asar\src\text-editor.js:843:19)
    at TextEditor.module.exports.TextEditor.insertText (C:\Program Files\Atom\resources\app.asar\src\text-editor.js:809:19)
    at TextEditor.object.(anonymous function) [as insertText] (C:\Program Files\Atom\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (C:\Program Files\Atom\resources\app.asar\src\text-editor-component.js:473:35)
    at HTMLDivElement.<anonymous> (C:\Program Files\Atom\resources\app.asar\src\text-editor-component.js:3:61)
```

### Commands

```
     -1:14.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:08.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:08.0 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "archive-view",
      "autoflow",
      "background-tips",
      "image-view",
      "open-on-github",
      "release-notes",
      "spell-check",
      "styleguide",
      "welcome",
      "feedback",
      "autosave",
      "incompatible-packages",
      "wrap-guide"
    ],
    "projectHome": "C:\\Users\\username\\Documents\\Github",
    "themes": [
      "one-light-ui",
      "fizzy"
    ]
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.6.15
fizzy, v0.16.0
language-c, v0.51.1
language-coffee-script, v0.46.1
language-csharp, v0.11.0
language-gfm, v0.84.0
language-git, v0.11.1
language-html, v0.44.1
language-java, v0.17.0
language-javascript, v0.110.0
language-latex, v0.6.1
language-make, v0.21.0
language-objective-c, v0.15.1
language-php, v0.37.0
language-python, v0.43.0
language-ruby, v0.68.1
language-sass, v0.42.1
language-shellscript, v0.20.0
language-sourcepawn, v0.6.0
language-sql, v0.19.0
language-toml, v0.17.0
language-xml, v0.34.3
language-yaml, v0.25.1
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-csslint, v1.3.1
linter-eslint, v7.0.0
linter-javac, v1.7.0
markdown-preview, v0.157.3
notifications, v0.62.2
pdf-view, v0.39.0
tabs, v0.89.0
travis-ci-status, v1.0.0
tree-view, v0.201.2

# Dev
No dev packages
```
(I do not remember hitting any keybinding to consolidate selections, nor do I remember having multiple selections in the first place)
