### ISSUE TITLE
Portable switch issue

### ISSUE THREAD

**Issue by DoumanAsh** [atom/atom#10980]
### Prerequisites
- Do not have existing ```~/.atom```
- Have ```[binary-dir]/.atom```

### Description
Switch ```--portable``` has description:
```
Set portable mode. Copies the ~/.atom folder to be a sibling of the
 installed Atom location if a .atom folder is not already there.
```
So, it should two things:
1. Sets portable mode i.e. use ```[binary-dir]/.atom```
2. Copy from ```~/.atom``` to ```[binary-dir]/.atom``` if it is still does not exist

But if you do not have ```~/.atom``` it throws error and ignores setting portable mode
What is strange: it should not to try to check ```~/.atom``` if there is already existing ```[binary-dir]/.atom```

As i understand it works from assumption that ```~/.atom``` exists
But i think it should be properly handled to when it does not exist too.
At least portable mode should be set.

```
Failed copying portable directory 'C:\Users\Douman\.atom' to 'E:\Soft\Main\.atom'
ENOENT: no such file or directory, scandir 'C:\Users\Douman\.atom' Error: ENOENT: no such file or directory, scandir 'C:\Users\Douman\.atom'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at Object.fsPlus.copySync (E:\Soft\Main\Atom\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:325:20)
    at Function.module.exports.AtomPortable.setPortable (E:\Soft\Main\Atom\resources\app.asar\src\browser\atom-portable.js:20:17)
    at setupAtomHome (E:\Soft\Main\Atom\resources\app.asar\src\browser\main.js:101:22)
    at start (E:\Soft\Main\Atom\resources\app.asar\src\browser\main.js:33:5)
    at Object.<anonymous> (E:\Soft\Main\Atom\resources\app.asar\src\browser\main.js:209:3)
    at Object.<anonymous> (E:\Soft\Main\Atom\resources\app.asar\src\browser\main.js:211:4)
    at Module._compile (module.js:434:26)
```
### Steps to Reproduce

1. Run atom first time to create ```~/.atom```
2. Copy ```~/.atom``` into ```[binary-dir]```
3. Delete  ```~/.atom``` 
4. Run ```./atom.exe --portable```

**Expected behavior:** portable mode set and ```[binary-dir]/.atom``` is used

**Actual behavior:** portable mode is not set and ```~/.atom``` is used

### Versions

1.5.3

### Note
The portable look-up is not working when you run just Atom.
Even if i have ```[binary-dir]/.atom``` it is ignored for some reason

**Comment by DoumanAsh** [comment]
Sorry, it seems i had misunderstanding of portable concept.
It expects to have neighbor ```.atom``` directory to ```[binary-dir]```, not to binary
