### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by PaulAndreRada** [atom/atom#10991]
[Enter steps to reproduce below:]
1. Create a JSX script.
2. Create a React object in it.
3. Attempt to collapse one of the methods in the React object by selecting the arrow next to the number.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1052

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1052:15)
    at DisplayBuffer.module.exports.DisplayBuffer.decorateFold (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1356:19)
    at DisplayBuffer.module.exports.DisplayBuffer.createFold (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:628:16)
    at TextEditor.module.exports.TextEditor.createFold (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2659:33)
    at LanguageMode.module.exports.LanguageMode.foldBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:147:30)
    at TextEditor.module.exports.TextEditor.foldBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2599:32)
    at LineNumberGutterComponent.module.exports.LineNumberGutterComponent.onClick (/Applications/Atom.app/Contents/Resources/app.asar/src/line-number-gutter-component.js:137:30)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/line-number-gutter-component.js:3:61)
```
### Commands

```
     -0:34.5.0 core:save (atom-text-editor.editor.emacs-plus.is-focused)
  2x -0:29.7.0 core:move-left (atom-text-editor.editor.emacs-plus.is-focused)
     -0:27.5.0 core:backspace (atom-text-editor.editor.emacs-plus.is-focused.autocomplete-active)
  2x -0:25.2.0 core:save (atom-text-editor.editor.emacs-plus.is-focused)
 11x -0:22.4.0 core:move-down (atom-text-editor.editor.emacs-plus.is-focused)
  8x -0:20 core:move-up (atom-text-editor.editor.emacs-plus.is-focused)
 10x -0:18.2.0 core:move-down (atom-text-editor.editor.emacs-plus.is-focused)
  2x -0:15.1.0 core:move-up (atom-text-editor.editor.emacs-plus.is-focused)
     -0:12 snippets:next-tab-stop (atom-text-editor.editor.emacs-plus.is-focused)
     -0:12 snippets:expand (atom-text-editor.editor.emacs-plus.is-focused)
     -0:12 editor:indent (atom-text-editor.editor.emacs-plus.is-focused)
  6x -0:10.6.0 core:backspace (atom-text-editor.editor.emacs-plus.is-focused.autocomplete-active)
     -0:07.2.0 editor:newline (atom-text-editor.editor.emacs-plus.is-focused)
     -0:06.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.emacs-plus.is-focused)
     -0:06.2.0 core:move-down (atom-text-editor.editor.emacs-plus.is-focused)
  8x -0:05.0 core:backspace (atom-text-editor.editor.emacs-plus.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 16,
    "invisibles": {}
  }
}
```
### Installed Packages

``` coffee
# User
emacs-plus, v0.9.11
react, v0.14.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Can you try reproducing this in safe mode (`atom --safe`)?  Thanks!

**Comment by PaulAndreRada** [comment]
I just tried it, in safe mode on the same file. Nothing happened. 
The collapse worked perfectly, the first time without reporting the error.

Before it would error on the first click of arrow and work on the second click, by both highlighting the arrow and collapsing the method without an issue.

**Comment by 50Wliu** [comment]
Ok.  If it doesn't happen in safe mode, and you were working on a React object, the issue is *probably* coming from the React package - you'll probably want to report this issue over there.

I'll leave this open just in case this can be better handled in Atom core though.

**Comment by michael-k** [comment]
Happens not only with the React package.

[Enter steps to reproduce below:]

1. Open a `py` (Python) file
2. Try to collapse a class, method, function, … (stack trace below is from trying to collapse a method)

**Atom Version**: 1.5.3-3e71894
**System**: Debian GNU/Linux
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /home/mfk/repos/coffeescript/atom-install/share/atom/resources/app.asar/src/display-buffer.js:1052

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/home/mfk/repos/coffeescript/atom-install/share/atom/resources/app.asar/src/display-buffer.js:1052:15)
    at DisplayBuffer.module.exports.DisplayBuffer.decorateFold (/home/mfk/repos/coffeescript/atom-install/share/atom/resources/app.asar/src/display-buffer.js:1356:19)
    at DisplayBuffer.module.exports.DisplayBuffer.createFold (/home/mfk/repos/coffeescript/atom-install/share/atom/resources/app.asar/src/display-buffer.js:628:16)
    at TextEditor.module.exports.TextEditor.createFold (/home/mfk/repos/coffeescript/atom-install/share/atom/resources/app.asar/src/text-editor.js:2659:33)
    at LanguageMode.module.exports.LanguageMode.foldBufferRow (/home/mfk/repos/coffeescript/atom-install/share/atom/resources/app.asar/src/language-mode.js:147:30)
    at TextEditor.module.exports.TextEditor.foldBufferRow (/home/mfk/repos/coffeescript/atom-install/share/atom/resources/app.asar/src/text-editor.js:2599:32)
    at LineNumberGutterComponent.module.exports.LineNumberGutterComponent.onClick (/home/mfk/repos/coffeescript/atom-install/share/atom/resources/app.asar/src/line-number-gutter-component.js:137:30)
    at HTMLDivElement.<anonymous> (/home/mfk/repos/coffeescript/atom-install/share/atom/resources/app.asar/src/line-number-gutter-component.js:3:61)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-pylint",
      "git-grep",
      "language-python"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "fontFamily": "Inconsolata",
    "fontSize": 13,
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "softTabs": false,
    "softWrap": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
MagicPython, v0.5.8
atom-django, v0.3.2
atomatigit, v1.5.5
autocomplete-python, v1.6.1
clipboard-plus, v0.5.1
emacs-plus, v0.9.11
ember-snippets, v1.4.0
formatter, v2.12.3
language-diff, v0.4.0
language-docker, v1.1.6
linter, v1.11.3
linter-pylama, v0.2.6
python-autopep8, v0.1.3
python-iresolve, v0.0.3
python-isort, v0.0.7
python-jedi, v0.3.6
python-tools, v0.6.7
standard-formatter, v2.0.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@michael-k Please try reproducing this in safe mode: `atom --safe`.

**Comment by michael-k** [comment]
As I wrote above, I cannot reproduce this in safe mode, because the icon to collapse a piece of python code is not there in safe mode.

**Comment by 50Wliu** [comment]
Sorry, I missed that.  Can you try the [package-cop](https://atom.io/packages/package-cop) package to track down which package is giving you this error?

**Comment by shouya** [comment]
The same issue here. I guess it might caused by `emacs-plus` package.


**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1052

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1052:15)
    at DisplayBuffer.module.exports.DisplayBuffer.decorateFold (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1356:19)
    at DisplayBuffer.module.exports.DisplayBuffer.createFold (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:628:16)
    at TextEditor.module.exports.TextEditor.createFold (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2659:33)
    at LanguageMode.module.exports.LanguageMode.foldBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:147:30)
    at TextEditor.module.exports.TextEditor.foldBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2599:32)
    at LineNumberGutterComponent.module.exports.LineNumberGutterComponent.onClick (/Applications/Atom.app/Contents/Resources/app.asar/src/line-number-gutter-component.js:137:30)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/line-number-gutter-component.js:3:61)
```

### Commands

```
     -0:09.4.0 autoflow:reflow-selection (atom-text-editor.editor.is-focused.emacs-plus)
  2x -0:08.7.0 core:move-up (atom-text-editor.editor.is-focused.emacs-plus)
     -0:08.1.0 core:move-right (atom-text-editor.editor.is-focused.emacs-plus)
     -0:07.7.0 core:move-left (atom-text-editor.editor.is-focused.emacs-plus)
     -0:07.5.0 core:move-right (atom-text-editor.editor.is-focused.emacs-plus)
  2x -0:07.4.0 core:move-left (atom-text-editor.editor.is-focused.emacs-plus)
     -0:06.9.0 core:move-right (atom-text-editor.editor.is-focused.emacs-plus)
  2x -0:06.6.0 core:move-left (atom-text-editor.editor.is-focused.emacs-plus)
     -0:06.1.0 core:move-right (atom-text-editor.editor.is-focused.emacs-plus)
  2x -0:06.1.0 core:move-left (atom-text-editor.editor.is-focused.emacs-plus)
     -0:05.5.0 core:move-down (atom-text-editor.editor.is-focused.emacs-plus)
  2x -0:05.3.0 core:move-left (atom-text-editor.editor.is-focused.emacs-plus)
     -0:04.8.0 core:move-down (atom-text-editor.editor.is-focused.emacs-plus)
  2x -0:04.7.0 core:move-left (atom-text-editor.editor.is-focused.emacs-plus)
     -0:03.7.0 core:move-right (atom-text-editor.editor.is-focused.emacs-plus)
     -0:03.3.0 core:move-left (atom-text-editor.editor.is-focused.emacs-plus)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "line-ending-selector",
      "browser-plus",
      "latex",
      "fancy-bracket-matcher",
      "atom-bracket-highlight",
      "language-mustache"
    ],
    "projectHome": "/Users/shou/project",
    "themes": [
      "yosemate-ui",
      "atom-light-syntax"
    ]
  },
  "editor": {
    "autoIndent": false,
    "backUpBeforeSaving": true,
    "fontSize": 12,
    "invisibles": {},
    "preferredLineLength": 70,
    "showIndentGuide": true,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
animated-page-scroll, v1.0.0
clip-history, v0.1.12
emacs-plus, v0.9.12
file-type-icons, v0.7.4
highlight-selected, v0.11.2
keyboard-sounds, v0.2.0
language-latex, v0.6.1
latex-autocomplete, v0.3.1
latex-plus, v0.8.4
minimap, v4.20.0
pdf-view, v0.50.0
yosemate-ui, v0.7.1

# Dev
No dev packages
```

**Comment by MaximilianR** [comment]
FYI I get this very frequently during rebases when using git in 1.18

**Comment by beerendlauwers** [comment]
I've just started encountering this with version 1.263.1 x64. Stack trace:

```
/usr/share/atom/resources/app/src/decoration-manager.js:191
Hide Stack Trace
Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/usr/share/atom/resources/app/src/decoration-manager.js:183:27)
    at TextEditor.decorateMarker (/usr/share/atom/resources/app/src/text-editor.js:2137:41)
    at new Selection (/usr/share/atom/resources/app/src/selection.js:20:41)
    at TextEditor.addSelection (/usr/share/atom/resources/app/src/text-editor.js:3276:27)
    at /usr/share/atom/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:79:24
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at MarkerLayer.module.exports.MarkerLayer.createMarker (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker-layer.js:450:28)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker-layer.js:225:25)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:105:58)
    at TextEditor.addSelectionForBufferRange (/usr/share/atom/resources/app/src/text-editor.js:2873:38)
    at TextEditor.createLastSelectionIfNeeded (/usr/share/atom/resources/app/src/text-editor.js:3328:18)
    at TextEditor.getLastCursor (/usr/share/atom/resources/app/src/text-editor.js:2665:16)
    at TextEditor.getCursorBufferPosition (/usr/share/atom/resources/app/src/text-editor.js:2448:23)
    at SubsequenceProvider.bufferToSubsequenceMatches (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/subsequence-provider.js:136:60)
    at Array.map (native)
    at SubsequenceProvider.getSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/subsequence-provider.js:252:18)
    at providers.forEach.provider (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:300:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:271:21)
    at AutocompleteManager.findSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:263:23)
    at AutocompleteManager.requestNewSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1748:32)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:975:18)
    at TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1839:30)
    at mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:1386:25)
    at TextEditor.mergeSelections (/usr/share/atom/resources/app/src/text-editor.js:3249:53)
    at TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:3223:42)
    at TextEditor.mutateSelectedText (/usr/share/atom/resources/app/src/text-editor.js:1385:23)
    at TextEditor.insertText (/usr/share/atom/resources/app/src/text-editor.js:1349:31)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/usr/share/atom/resources/app/src/text-editor-component.js:1661:30)
```

package-cop identified Atom as the offending package.

**Comment by phaseOne** [comment]
I've also had this issue when resolving Git merge conflicts. When issuing a **GitHub: Resolve as Ours then Theirs** command from the palette, I receive this error. I think it may be because I resolved some conflicts myself, and then I tried to automate the rest from the palette.
