### ISSUE TITLE
Uncaught TypeError: Cannot read property 'serialize' of undefined when closing last pane

### ISSUE THREAD

**Issue by izuzak** [atom/atom#11002]
As far as I can tell, this started happening recently, after #10737 was merged. /cc @benogle @natalieogle

Steps to reproduce:

1. Open a bunch of files
2. Start closing them one-by-one
3. Exception is thrown after last one is closed

Here's a GIF (notice how the exception doesn't happen when closing or opening files until the last one is closed):

![w](https://cloud.githubusercontent.com/assets/38924/13387539/fcf4e866-deb7-11e5-9ab3-7468bdf2d108.gif)

**Atom Version**: 1.7.0-dev-b589e28
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'serialize' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:88

TypeError: Cannot read property 'serialize' of undefined
    at Pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:88:26)
    at Pane.module.exports.Pane.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:93:10)
    at PaneContainer.module.exports.PaneContainer.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:54:51)
    at Workspace.module.exports.Workspace.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:149:43)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:739:35)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:946:27
```

### Commands

```
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false
  },
  "editor": {
    "fontFamily": "Hasklig",
    "fontSize": 17,
    "invisibles": {},
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by natalieogle** [comment]
I'll look into this tomorrow!

**Comment by benogle** [comment]
Thanks @izuzak for the report

**Comment by nfantone** [comment]
:+1: Came here for this. Nice to find out it's fixed.
