### ISSUE TITLE
Atom error

### ISSUE THREAD

**Issue by dshm** [atom/atom#11013]
Windows 10
### Steps to Reproduce

1. [press ctrl+alt+p]
2. [and other plugin cant open]

**Expected behavior:** index.js:62 Error: Cannot find module 'C:\OpenServer\domains\localhost\parketiko.lc\spec'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\dshm\AppData\Local\atom\app-1.5.3\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\dshm\AppData\Local\atom\app-1.5.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at requireSpecs (C:\Users\dshm\AppData\Local\atom\app-1.5.3\resources\app.asar\spec\jasmine-test-runner.js:101:7)
    at module.exports (C:\Users\dshm\AppData\Local\atom\app-1.5.3\resources\app.asar\spec\jasmine-test-runner.js:49:7)
    at module.exports (C:\Users\dshm\AppData\Local\atom\app-1.5.3\resources\app.asar\src\initialize-test-window.js:71:17)
    at setupWindow (file:///C:/Users/dshm/AppData/Local/atom/app-1.5.3/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///C:/Users/dshm/AppData/Local/atom/app-1.5.3/resources/app.asar/static/index.js:41:9)]

### 1.5.3

apm  1.6.0
npm  2.13.3
node 0.10.40
python 3.5.0
git 2.6.2.windows.1

**Comment by lee-dohm** [comment]
I'm not sure what you're saying is going on here. I assume you mean that the exception there is the actual behavior, not the expected behavior? What does it mean when you say "and other plugin can't open"?

**Comment by dshm** [comment]
Sorry, the problem was in my environment :(
