### ISSUE TITLE
Uncaught Error: The element cannot be null or undefined.

### ISSUE THREAD

**Issue by nicka101** [atom/atom#11069]
1. Have omnisharp-atom loaded and be editing a C# file
2. While typing at the start of a line that already has valid code on it (specifically when the cursor is at the start of another word) this error starts spamming constantly and doesn't stop until the editor is restarted

**Atom Version**: 1.5.4
**System**: Ubuntu 15.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The element cannot be null or undefined.

```
At /usr/share/atom/resources/app.asar/src/lines-tile-component.js:71

Error: The element cannot be null or undefined.
    at DOMElementPool.module.exports.DOMElementPool.free (/usr/share/atom/resources/app.asar/src/dom-element-pool.js:80:15)
    at DOMElementPool.module.exports.DOMElementPool.freeElementAndDescendants (/usr/share/atom/resources/app.asar/src/dom-element-pool.js:63:12)
    at LinesTileComponent.module.exports.LinesTileComponent.removeLineNode (/usr/share/atom/resources/app.asar/src/lines-tile-component.js:111:27)
    at LinesTileComponent.module.exports.LinesTileComponent.updateLineNodes (/usr/share/atom/resources/app.asar/src/lines-tile-component.js:123:16)
    at LinesTileComponent.module.exports.LinesTileComponent.updateSync (/usr/share/atom/resources/app.asar/src/lines-tile-component.js:98:12)
    at LinesComponent.module.exports.TiledComponent.updateTileNodes (/usr/share/atom/resources/app.asar/src/tiled-component.js:67:19)
    at LinesComponent.module.exports.TiledComponent.updateSync (/usr/share/atom/resources/app.asar/src/tiled-component.js:30:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/usr/share/atom/resources/app.asar/src/text-editor-component.js:249:34)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/share/atom/resources/app.asar/src/text-editor-component.js:192:12)
    at /usr/share/atom/resources/app.asar/src/text-editor-component.js:303:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app.asar/src/view-registry.js:215:9)
    at /usr/share/atom/resources/app.asar/src/view-registry.js:3:61
```

### Commands

```
  2x -1:03.4.0 core:move-down (atom-text-editor.editor.is-focused.omnisharp-editor.autocomplete-active)
  3x -1:02.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.omnisharp-editor.autocomplete-active)
     -0:57.9.0 core:move-right (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:56.3.0 editor:newline (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:50.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.omnisharp-editor.autocomplete-active)
     -0:50.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused.omnisharp-editor)
  2x -0:47.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:42.8.0 editor:newline (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:41.3.0 core:move-down (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:41 core:move-right (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:39.5.0 core:move-up (atom-text-editor.editor.is-focused.omnisharp-editor)
  2x -0:39.3.0 core:move-right (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:37.6.0 editor:newline (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:35.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:33.7.0 core:backspace (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:33.3.0 editor:newline (atom-text-editor.editor.is-focused.omnisharp-editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-gcc"
    ]
  },
  "editor": {
    "fontFamily": "DejaVu Sans Mono",
    "fontSize": 12,
    "invisibles": {},
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
autocomplete-clang, v0.8.9
autocomplete-cmake, v0.3.1
build-tools, v4.3.4
json-schema, v0.1.15
language-cmake, v0.1.4
linter, v1.11.3
omnisharp-atom, v0.26.13

# Dev
No dev packages
```

**Comment by perbnielsen** [comment]
This issue appears when I enable Enhanced Highlighting. If I disable Enhanced Highlighting I have no problems.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: The element cannot be null or undefined.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/lines-tile-component.js:72

Error: The element cannot be null or undefined.
    at DOMElementPool.module.exports.DOMElementPool.free (/Applications/Atom.app/Contents/Resources/app.asar/src/dom-element-pool.js:80:15)
    at DOMElementPool.module.exports.DOMElementPool.freeElementAndDescendants (/Applications/Atom.app/Contents/Resources/app.asar/src/dom-element-pool.js:63:12)
    at LinesTileComponent.module.exports.LinesTileComponent.removeLineNode (/Applications/Atom.app/Contents/Resources/app.asar/src/lines-tile-component.js:113:27)
    at LinesTileComponent.module.exports.LinesTileComponent.updateLineNodes (/Applications/Atom.app/Contents/Resources/app.asar/src/lines-tile-component.js:127:16)
    at LinesTileComponent.module.exports.LinesTileComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/lines-tile-component.js:100:12)
    at LinesComponent.module.exports.TiledComponent.updateTileNodes (/Applications/Atom.app/Contents/Resources/app.asar/src/tiled-component.js:67:19)
    at LinesComponent.module.exports.TiledComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/tiled-component.js:30:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:265:34)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:205:12)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:221:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```

### Commands

```
     -7:12.5.0 omnisharp-atom:settings (atom-workspace.workspace.scrollbars-visible-when-scrolling.use-animations.theme-atom-material-syntax.theme-atom-material-ui)
  2x -7:09.0 core:cancel (div.package-detail.panels-item)
     -5:11.9.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -5:08.8.0 fuzzy-finder:invert-confirm (atom-text-editor.editor.mini.is-focused)
     -4:49.5.0 editor:consolidate-selections (atom-text-editor.editor.omnisharp-editor.is-focused)
     -4:49.5.0 core:cancel (atom-text-editor.editor.omnisharp-editor.is-focused)
     -4:35.8.0 editor:consolidate-selections (atom-text-editor.editor.omnisharp-editor.is-focused)
     -4:35.8.0 core:cancel (atom-text-editor.editor.omnisharp-editor.is-focused)
     -4:33.5.0 editor:consolidate-selections (atom-text-editor.editor.omnisharp-editor.is-focused)
     -4:33.5.0 core:cancel (atom-text-editor.editor.omnisharp-editor.is-focused)
     -3:28.8.0 editor:consolidate-selections (atom-text-editor.editor.omnisharp-editor.is-focused)
     -3:28.8.0 core:cancel (atom-text-editor.editor.omnisharp-editor.is-focused)
     -3:19.6.0 settings-view:open (atom-text-editor.editor.omnisharp-editor.is-focused)
     -2:31.4.0 core:cancel (div.package-detail.panels-item)
     -2:26.4.0 editor:consolidate-selections (atom-text-editor.editor.omnisharp-editor.is-focused)
     -2:26.4.0 core:cancel (atom-text-editor.editor.omnisharp-editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "atom-replace-pane"
    ],
    "ignoredNames": [
      ".DS_Store",
      ".gitignore",
      ".settings",
      "*.meta"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "fontFamily": "Ubuntu Mono derivative Powerline",
    "fontSize": 13,
    "invisibles": {},
    "lineHeight": 1.1,
    "preferredLineLength": 130,
    "scrollPastEnd": true,
    "softTabs": false,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.10
atom-yeoman, v0.3.15
gutter-shadow, v0.6.0
json-schema, v0.1.15
linter, v1.11.4
linter-php, v1.2.0
omnisharp-atom, v0.28.0
pane-jump, v0.2.0

# Dev
No dev packages
```

**Comment by perbnielsen** [comment]
I forgot to mention that the Enhanced Highlighting is in the omnisharp-atom plugin, that this issue is triggered while viewing a C# file and that it appears together with issue https://github.com/atom/atom/issues/10350.

**Comment by 50Wliu** [comment]
As both of these exceptions seem to be triggered by omnisharp-atom, please report this issue over there instead.  Thanks!

**Comment by tonybenoy** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.0-dev-3fd0d30
**Electron Version**: 0.37.8
**System**: linux 4.6.3-1-ARCH
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: The element cannot be null or undefined.

```
At /usr/share/atom-git/resources/app.asar/src/lines-tile-component.js:70

Error: The element cannot be null or undefined.
    at DOMElementPool.module.exports.DOMElementPool.free (/usr/share/atom-git/resources/app.asar/src/dom-element-pool.js:80:15)
    at DOMElementPool.module.exports.DOMElementPool.freeElementAndDescendants (/usr/share/atom-git/resources/app.asar/src/dom-element-pool.js:63:12)
    at LinesTileComponent.module.exports.LinesTileComponent.removeLineNode (/usr/share/atom-git/resources/app.asar/src/lines-tile-component.js:106:27)
    at LinesTileComponent.module.exports.LinesTileComponent.updateLineNodes (/usr/share/atom-git/resources/app.asar/src/lines-tile-component.js:120:16)
    at LinesTileComponent.module.exports.LinesTileComponent.updateSync (/usr/share/atom-git/resources/app.asar/src/lines-tile-component.js:94:12)
    at LinesComponent.module.exports.TiledComponent.updateTileNodes (/usr/share/atom-git/resources/app.asar/src/tiled-component.js:67:19)
    at LinesComponent.module.exports.TiledComponent.updateSync (/usr/share/atom-git/resources/app.asar/src/tiled-component.js:30:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/usr/share/atom-git/resources/app.asar/src/text-editor-component.js:265:34)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/share/atom-git/resources/app.asar/src/text-editor-component.js:205:12)
    at /usr/share/atom-git/resources/app.asar/src/text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom-git/resources/app.asar/src/view-registry.js:221:9)
    at /usr/share/atom-git/resources/app.asar/src/view-registry.js:3:61
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "activate-power-mode",
      "autocomplete-python",
      "autocomplete-html",
      "autocomplete-css",
      "background-tips",
      "language-coffee-script",
      "language-csharp",
      "language-css",
      "language-go",
      "language-html",
      "language-java",
      "language-javascript",
      "language-json",
      "language-less",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-ruby-on-rails",
      "language-ruby",
      "language-sass",
      "language-shellscript",
      "language-text",
      "language-toml",
      "language-yaml",
      "language-xml"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "fontSize": 13,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0 (inactive)
autocomplete-python, v1.8.1 (inactive)
highlight-selected, v0.11.2 (active)
linter, v1.11.14 (active)
MagicPython, v0.5.12 (active)
minimap, v4.24.7 (active)
minimap-highlight-selected, v4.4.0 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.4.0 (active)
one-light-ui, v1.4.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about-arch, v1.5.18 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (inactive)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.200.0 (inactive)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.1 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
notifications, v0.65.0 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.1 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.99.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.1 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.0 (inactive)
language-gfm2, v0.90.4 (active)
language-liquid, v0.5.1 (active)
language-git, v0.14.0 (active)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.1 (inactive)
language-less, v0.29.4 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.1 (inactive)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.6 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.55.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (active)
language-sql, v0.22.0 (active)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by JayXon** [comment]
Just got this error and #13377 at the same time without doing anything, I don't have omnisharp-atom installed.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Ubuntu 14.04
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: The element cannot be null or undefined.

```
At /usr/share/atom/resources/app.asar/src/dom-element-pool.js:80

Error: The element cannot be null or undefined.
    at DOMElementPool.module.exports.DOMElementPool.free (/usr/share/atom/resources/app.asar/src/dom-element-pool.js:80:15)
    at DOMElementPool.module.exports.DOMElementPool.freeDescendants (/usr/share/atom/resources/app.asar/src/dom-element-pool.js:72:14)
    at DOMElementPool.module.exports.DOMElementPool.freeElementAndDescendants (/usr/share/atom/resources/app.asar/src/dom-element-pool.js:64:19)
    at LinesTileComponent.removeLineNode (/usr/share/atom/resources/app.asar/src/lines-tile-component.js:84:25)
    at LinesTileComponent.removeLineNodes (/usr/share/atom/resources/app.asar/src/lines-tile-component.js:79:12)
    at LinesTileComponent.destroy (/usr/share/atom/resources/app.asar/src/lines-tile-component.js:24:10)
    at LinesComponent.module.exports.TiledComponent.removeTileNode (/usr/share/atom/resources/app.asar/src/tiled-component.js:30:40)
    at LinesComponent.module.exports.TiledComponent.updateTileNodes (/usr/share/atom/resources/app.asar/src/tiled-component.js:42:16)
    at LinesComponent.module.exports.TiledComponent.updateSync (/usr/share/atom/resources/app.asar/src/tiled-component.js:18:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/usr/share/atom/resources/app.asar/src/text-editor-component.js:264:34)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/share/atom/resources/app.asar/src/text-editor-component.js:196:12)
    at /usr/share/atom/resources/app.asar/src/text-editor-component.js:323:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app.asar/src/view-registry.js:219:9)
    at /usr/share/atom/resources/app.asar/src/view-registry.js:3:59
```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.cpp": [
        "h"
      ]
    },
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "metrics",
      "package-generator",
      "git-blame",
      "you-complete-me",
      "atom-beautify",
      "open-on-github",
      "git-control",
      "file-hyperclick",
      "styleguide",
      "linter-glint"
    ],
    "packagesWithKeymapsDisabled": [
      "clang-format",
      "atom-material-ui",
      "autocomplete-clang"
    ],
    "telemetryConsent": "no",
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "fontFamily": "Roboto Mono",
    "invisibles": {},
    "scrollSensitivity": 60,
    "showInvisibles": true,
    "softWrap": true,
    "zoomFontWhenCtrlScrolling": false
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.2.0 (active)
atom-beautify, v0.29.17 (inactive)
atom-material-syntax, v1.0.2 (inactive)
atom-material-syntax-dark, v0.2.7 (inactive)
atom-material-ui, v1.3.9 (active)
atom-monokai, v0.10.7 (inactive)
auto-detect-indentation, v1.3.0 (active)
autocomplete-clang, v0.10.0 (active)
autocomplete-paths, v1.0.5 (active)
autocomplete-python, v1.8.40 (active)
blame, v0.10.2 (inactive)
clang-format, v1.27.0 (active)
file-icons, v2.0.14 (active)
git-blame, v0.4.11 (inactive)
git-control, v0.8.2 (inactive)
git-plus, v7.2.0 (active)
git-time-machine, v1.5.4 (inactive)
highlight-selected, v0.12.0 (active)
hyperclick, v0.0.40 (active)
language-batchfile, v0.5.2 (active)
language-bazel, v0.3.2 (active)
language-diff, v0.7.0 (active)
language-gcl, v0.0.2 (inactive)
language-log, v1.8.0 (active)
language-proto, v0.7.0 (active)
language-x86-64-assembly, v2.2.8 (active)
line-count, v0.5.0 (inactive)
line-count-status, v0.0.3 (active)
line-diff-details, v1.4.0 (active)
linter, v1.11.21 (active)
linter-clang, v3.4.6 (active)
linter-cppcheck, v0.2.2 (active)
linter-cpplint, v1.0.1 (active)
linter-glint, v0.1.0 (inactive)
linter-mixed-indent, v1.1.0 (active)
linter-pylint, v1.2.2 (active)
linter-shellcheck, v1.4.3 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.26.8 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.5.0 (active)
minimap-linter, v1.6.0 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.6.0 (inactive)
sort-lines, v0.14.0 (inactive)
split-diff, v1.1.1 (inactive)
tab-smart-sort, v0.3.0 (active)
you-complete-me, v0.7.11 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```
