### ISSUE TITLE
Uncaught TypeError: this.peekTop(...).setTarget is not a function

### ISSUE THREAD

**Issue by Byron-TW** [atom/atom#11105]
[Enter steps to reproduce below:]

Unfortunately, it's rather hard to determine when it happens. But while working, it happens multiple times a day, usually just when navigating.
I know it's vague and may be hard to reproduce - if it's too much so, please feel free to close.
Also I will amend to this ticket in case I learn when exactly it happens.

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.peekTop(...).setTarget is not a function

```
At /Users/sthiel/dev/cs/atom-vim-mode-plus/lib/operation-stack.coffee:45

TypeError: this.peekTop(...).setTarget is not a function
    at OperationStack.process (/Users/sthiel/dev/cs/atom-vim-mode-plus/lib/operation-stack.coffee:57:20)
    at OperationStack.run (/Users/sthiel/dev/cs/atom-vim-mode-plus/lib/operation-stack.coffee:37:8)
    at run (/Users/sthiel/dev/cs/atom-vim-mode-plus/lib/base.coffee:13:29)
    at atom-text-editor.<anonymous> (/Users/sthiel/dev/cs/atom-vim-mode-plus/lib/base.coffee:200:65)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:44.1.0 find-and-replace:confirm (atom-text-editor.editor.mini.is-focused)
     -0:42.8.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
     -0:42.8.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:42.2.0 find-and-replace:replace-all (atom-text-editor.editor.mini.is-focused)
     -0:40.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:40.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  3x -0:40.9.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:40.1.0 core:save (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:38.9.0 blur (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.characterwise)
     -0:34.4.0 linter:next-error (atom-text-editor.editor.vim-mode-plus.visual-mode.characterwise.is-focused)
  2x -0:34.4.0 blur (atom-text-editor.editor.vim-mode-plus.visual-mode.characterwise.is-focused)
     -0:20.9.0 vim-mode-plus:find (atom-text-editor.editor.vim-mode-plus.visual-mode.characterwise.is-focused)
  3x -0:20.9.0 blur (atom-text-editor.editor.vim-mode-plus.visual-mode.characterwise.is-focused)
     -0:19.1.0 vim-mode-plus:find (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:18.6.0 vim-mode-plus:move-to-previous-paragraph (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  4x -0:14.8.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-jshint"
    ],
    "excludeVcsIgnoredPaths": true,
    "packagesWithKeymapsDisabled": [
      "turbo-javascript",
      "git-blame",
      "vim-mode-plus",
      "es6-javascript",
      "emmet",
      "node-debugger"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 16,
    "invisibles": {},
    "scrollPastEnd": true,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.19.1
atom-beautify, v0.28.26
atom-material-ui, v1.2.0
atom-ternjs, v0.13.2
atom-typescript, v8.3.0
autocomplete-ctags, v0.4.0
autocomplete-python, v1.7.0
autocomplete-ruby, v0.1.0
build, v0.55.0
build-cargo, v0.12.0
build-make, v0.7.0
coffee-compile, v0.21.1
css-snippets, v0.9.0
cursor-history, v0.5.9
emmet, v2.4.2
expand-region, v0.2.4
javascript-snippets, v1.2.1
language-apache, v1.4.0
language-elm, v1.3.3
language-escript, v0.1.0
language-jade, v0.6.3
language-mako, v0.6.0
language-rust, v0.4.6
linter, v1.11.3
linter-clang, v3.4.4
linter-coffeelint, v1.1.2
linter-csslint, v1.3.2
linter-docker, v0.1.2
linter-elm-make, v0.4.0
linter-eslint, v7.0.0
linter-flake8, v1.13.0
linter-golinter, v1.2.0
linter-htmlhint, v1.0.3
linter-javac, v1.8.0
linter-js-standard, v3.2.1
linter-js-yaml, v1.2.5
linter-jscs, v3.4.8
linter-jsonlint, v1.1.6
linter-jsxhint, v0.1.2
linter-lua, v1.0.1
linter-markdown, v1.5.0
linter-pylint, v1.2.0
linter-python-pep8, v0.2.0
linter-ruby, v1.2.2
linter-rust, v0.4.1
linter-sass-lint, v1.1.1
linter-scss-lint, v2.5.1
linter-shellcheck, v1.1.0
linter-tslint, v0.8.3
linter-xmllint, v1.3.4
minimap, v4.19.0
minimap-git-diff, v4.1.8
minimap-linter, v1.1.1
node_modules, vundefined
pretty-json, v0.4.1
project-manager, v2.7.6
racer, v0.18.0
react, v0.14.1
react-es6-snippets, v0.3.0
react-snippets, v0.3.0
rust-api-docs-helper, v0.5.1
snippets-jade, v0.1.1
source-preview-jade, v0.1.1
source-preview-react, v0.2.0
symbol-gen, v1.0.0
symbols-tree-view, v0.11.0
vim-mode-plus, v0.23.0
you-complete-me, v0.7.1

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
Hmmm, not sure why this was reported as thrown from Atom core, but this looks like a [vim-mode-plus](https://atom.io/packages/vim-mode-plus) issue (and like you might have linked a local version of it into packages with `apm link` sometime ago), so I'm going to close this out.

**Comment by Byron-TW** [comment]
Thanks ! How could I miss this :) ! Maybe I trust tooling too much sometimes.
The bug was reposted here [in the respective repository](https://github.com/t9md/atom-vim-mode-plus/issues/185).
Maybe the possibility of atom posting exceptions to the incorrect repository is something worth looking at, provided the author of `vim-mode-plus` (@t9md) didn't do anything special.

**Comment by 50Wliu** [comment]
@Byron-TW I suspect it has to do with the fact that it wasn't located in `ATOM_HOME/packages` and was instead symlinked.  Hopefully I'll have time to take a look at it.
