### ISSUE TITLE
npm install on windows fails on nodegit

### ISSUE THREAD

**Issue by BrainCrumbz** [atom/atom#11137]
We're trying to start again contribution on atom core issue #5901 , but we're not able to `npm install` successfully, and then not even to run `apm test`. Build instead completes fine.

Environment:
* Win 10 x64
* node 4.3.2
* npm 3.8.0
* git 2.7.2.windows.1
* Python 2.7.10
* GYP_MSVS_VERSION=2013
* PYTHON=C:\Python27\python.exe
* local atom root path: `D:\atom`

Also tried setting `ATOM_ELECTRON_URL=http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist`, with no apparent effect. We tried several times, with no luck. I think that we started with a little deeper root path and failure happened on another module. Then we moved to current top level directory.

`npm install` output log ends with:

~~~
[nodegit] Everything is ready to go, attempting compilation
[ 'rebuild' ]
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v4.3.2/node-v4.3.2-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (D:\atom\node_modules\nodegit\node_modules\node-gyp\lib\install.js:244:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (D:\atom\node_modules\nodegit\node_modules\request\request.js:951:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:412:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:302:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\atom\\node_modules\\nodegit\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\atom\node_modules\nodegit
gyp ERR! node -v v4.3.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
1
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.3.2
npm ERR! npm  v3.8.0
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.11.6 install: `node lifecycleScripts/install`
npm ERR! Exit status 13
npm ERR!
npm ERR! Failed at the nodegit@0.11.6 install script 'node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\atom\npm-debug.log
~~~

**Comment by 50Wliu** [comment]
Have you tried `script\build` instead?

**Comment by BrainCrumbz** [comment]
Yes, that works. But I got that 'npm install' is needed in order to *develop* on project. In both cases, 'apm' cannot be found, and so no 'apm test' can be launched. And we need that while making changes and adding tests.

**Comment by 50Wliu** [comment]
`script\build` runs `npm install` internally.  When building Atom, the `atom` and `apm` commands are not added to the path by default, but you can add them yourselves (they should be located in `%PROGRAMFILES%\Atom\resources\cli`.

**Comment by BrainCrumbz** [comment]
Thanks for your suggestions. I'll try that!

**Comment by BrainCrumbz** [comment]
Update:

atom has been successfully built into `%PROGRAMFILES%\Atom`, `%PROGRAMFILES%\Atom\resources\cli` has been appendend to path, then `apm test` was launched from within `D:\atom`. Now, console output showed right away the following

~~~
Cannot find module '../build/Release/nslog.node'
Error: Cannot find module '../build/Release/nslog.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Program Files\Atom\resources\app.asar\node_modules\nslog\lib\nslog.js:5:11)
    at Object.<anonymous> (C:\Program Files\Atom\resources\app.asar\node_modules\nslog\lib\nslog.js:15:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
~~~

and since then it has been sitting there idle for the last 10 mins or so. Any suggestion on how to proceed? Thank you

**Comment by 50Wliu** [comment]
Hmm, I've never seen that error before.  Does running a `script\clean && script\build` help at all?  If that doesn't, does setting `ATOM_DEV_RESOURCE_PATH` to `D:\atom` help?

**Comment by BrainCrumbz** [comment]
After (successful) clean & build, `apm test` still reported errors and terminated right away (below what seemed the error). Then we set ATOM_DEV_RESOURCE_PATH as you suggested, and `apm test` ran fine. 

Console shows a bunch of `INFO:CONSOLE` messages complaining about apparent *problems*, e.g. `Error setting item in object: Validation failed at foo.bar.int, [...]`. It also shows a number of `F` spreaded in a sea of dots, and a green `Tests passed`. So, all in all, it looks *green* to me.

Thanks for your help @50Wliu . Maybe adding those hints to Windows build problems might be helpful to others as well.

~~~
7700:6984:0314/113256:ERROR:crash_service.cc(301)] could not start dumper
[7764:2820:0314/113256:ERROR:crash_service.cc(301)] could not start dumper
[3424:0314/113301:WARNING:archive.cc(144)] Opening file:\C:\Program%20Files\Atom\resources\app.asar: FILE_ERROR_FAILED
[3976:0314/113301:INFO:CONSOLE(88)] "Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'atom-styles'. A type with that name is already registered.
    at Error (native)
    at Object.<anonymous> (file:///D:/atom/src/styles-element.coffee:117:43)
    at Object.<anonymous> (file:///D:/atom/src/styles-element.coffee:1:1)
    at Module._compile (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Program Files\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (C:\Program Files\Atom\resources\app.asar\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///D:/atom/src/atom-environment.coffee:12:17)
    at Object.<anonymous> (file:///D:/atom/src/atom-environment.coffee:1:1)
    at Module._compile (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Program Files\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (C:\Program Files\Atom\resources\app.asar\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///D:/atom/spec/atom-environment-spec.coffee:6:19)
    at Object.<anonymous> (file:///D:/atom/spec/atom-environment-spec.coffee:1:1)
    at Module._compile (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Program Files\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (C:\Program Files\Atom\resources\app.asar\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at requireSpecs (C:\Program Files\Atom\resources\app.asar\spec\jasmine-test-runner.js:94:9)
    at module.exports (C:\Program Files\Atom\resources\app.asar\spec\jasmine-test-runner.js:47:7)
    at module.exports (C:\Program Files\Atom\resources\app.asar\src\initialize-test-window.js:72:17)
    at setupWindow (file:///C:/Program%20Files/Atom/resources/app.asar/static/index.js:87:12)
    at window.onload (file:///C:/Program%20Files/Atom/resources/app.asar/static/index.js:41:9)", source: C:\Program Files\Atom\resources\app.asar\src\initialize-test-window.js (88)
~~~

**Comment by 50Wliu** [comment]
@BrainCrumbz thanks for the update.  What you're reporting is pretty weird...`F`s signify that the test failed, so `apm` definitely shouldn't be returning `Tests passed`.

The `ATOM_DEV_RESOURCE_PATH` issue has already been discussed in #10719 - I'm about to reopen that bug as people shouldn't have to set an extra environment variable just to run tests.

**Comment by BrainCrumbz** [comment]
Please let us know if we can run some command or post some results here in order to better understand what is going on with that `Tests passed`.

**Comment by 50Wliu** [comment]
Can you see what `echo %ERRORLEVEL%` returns after running `apm test`?

**Comment by BrainCrumbz** [comment]
Couple of feedbacks:

1. Current head in my local repo is (on master) at 1043dc083982c63a23d8d13f7653e34bd4453c50

1. (Before reading your `%ERROLEVEL%` request) Ran `apm test` again, after the mentioned "successful" run. At a first look things seem the same. Console output, 01, is [here](https://gist.github.com/BrainCrumbz/ac6bf6fcea40de218474#file-apm-test-01-log): stderr comes first and then at the end there's stdout (redirected to file through command line). 

1. Ran in sequence: `script\clean`, `script\build` (`Done, without errors.`), then `apm test`. Things seem the same. Console output, 02, is [here](https://gist.github.com/BrainCrumbz/ac6bf6fcea40de218474#file-apm-test-02-log), all together *as is* this time. ERRORLEVEL is 0.

**Comment by 50Wliu** [comment]
So, Atom is definitely **not** supposed to run out of memory when running tests.  Most of the errors look like part of the usual process though.

**Comment by BrainCrumbz** [comment]
Don't know if it's related, but at some point CPU temperature was rising sensibly.

**Comment by BrainCrumbz** [comment]
Just an update: we're trying again now, after having pulled latest revision from master

**Comment by BrainCrumbz** [comment]
Good news: no funky issues with the "full" build from `script\build`. 

Bad news: running `apm test` gives some failures with code as-is. But this is for another story/issue.

Probably we could close this issue by now.

Thanks for support!
