### ISSUE TITLE
Something broke Atom

### ISSUE THREAD

**Issue by PierBover** [atom/atom#11147]
I was working with Atom and then I noticed a keyboard shortcut wasn't working. I thought maybe it was a glitch so I closed Atom and when I opened it again the main window wouldn't open. The OSX system menu only had the Atom menu and so no file, edit, view, or any of the other menus.

I closed Atom again, and reopened it. Nothing.

I tried opening Atom using Terminal, nothing.

I tried `atom --safe`, nothing.

Deleted the .atom/storage folder, reopened Atom. Nothing.

Deleted the whole .atom folder, reopened Atom, still Nothing.

I deleted the Atom.app, downloaded it again and now it works, although I have to reconfigure everything again.

Here is an error from Console.app, I'm afraid this is the best I can give you.

```
3/12/16 9:45:15.611 PM Atom[2602]: SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/scoped-property-store/node_modules/atom-slick/index.js:5:72)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/scoped-property-store/lib/scoped-property-store.js:5:11)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/scoped-property-store/lib/scoped-property-store.js:263:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:23:25)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:1102:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

My Atom configuration was quite simple. Only a few shortcuts and settings. I had less than 10 packages installed which I can try to list if that would help.

**Comment by 50Wliu** [comment]
@PierBover What was the broken keyboard shortcut?

**Comment by PierBover** [comment]
It was a shortcut I had assigned to "Select All" which is usually `control+command+g`. Other shortcuts I had defined were working fine.

**Comment by abhinav-shah** [comment]
I am facing the same issue. I only see the Atom menu.
