### ISSUE TITLE
atom module no longer available in tasks

### ISSUE THREAD

**Issue by abe33** [atom/atom#11160]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

The `atom` module can no longer be required in a task created using the `Task` class. It breaks the `fuzzy-finder` as well as any other packages that uses core classes from that module (like the `Emitter` or the `Disposable` classes).

For instance, when running in safe mode, the `fuzzy-finder` package is failing with: 

```
Cannot find module 'atom' Error: Cannot find module 'atom'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/load-paths-handler.js:12:19)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/load-paths-handler.js:180:4)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:110:13)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:112:4)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at [eval]:2:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:425:26)
    at node.js:602:27
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)(anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:52
/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)(anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:52
```

I suspect this is a bug and was not an intended change, but if it was I may point out that this will likely break a lot of packages and should trigger a major version bump.

### Versions

```
> atom --version
Atom    : 1.7.0-dev-579b6b7
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by abe33** [comment]
It appears the issue appeared with either commit 430a0e0 or 63ec054, but I haven't identified the root cause yet.

**Comment by joshaber** [comment]
https://github.com/atom/atom/pull/11153 seems like a likely fix.

**Comment by abe33** [comment]
Yes, looks like it is. I close my issue then since @lee-dohm caught it already, I should have searched in PRs too.

**Comment by joshaber** [comment]
No worries! Definitely a good to make sure we didn't miss it.
