### ISSUE TITLE
Uncaught Error: ENFILE: file table overflow, open '/Library/WebServer/cgi-bin/PG/src/ICDO3_morpho...

### ISSUE THREAD

**Issue by mbaudis** [atom/atom#11171]
1. open file
2. crash

Actually there are constant crashes/freezes when opening text files. This one was very small (26kB), but I had a 76MB file open before (VCF). Though I actually had realized that large file viewing doesn't work in Atom (bless TextWrangler/BBedit!), I can't give up the hope ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: ENFILE: file table overflow, open '/Library/WebServer/cgi-bin/PG/src/ICDO3_morphologies.tab'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:498

Error: ENFILE: file table overflow, open '/Library/WebServer/cgi-bin/PG/src/ICDO3_morphologies.tab'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Workspace.module.exports.Workspace.openTextFile (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:540:27)
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:472:23)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:404:19)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1038:19)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:244:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "openEmptyEditorOnStart": false
  },
  "editor": {
    "invisibles": {},
    "softWrap": true
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Refs #10947.

**Comment by mbaudis** [comment]
Ah - thanks. So basically "don't try to open a file somewhere high up in your directory hierarchy, or Atom tries to glob the system"?

**Comment by 50Wliu** [comment]
Possibly - this is only the second report we've gotten, so things are still unclear over what causes this issue.

**Comment by mel111** [comment]
STOPPPPPPPPPPPPPPPPPPPPPPPPPPPP SENDING THIS CRAP OR I WILL REPORT !

**Comment by chrisknu** [comment]
Running multiple node processes concurrently (ie, a ton of files open at the system level) seems to trigger the issue. Doubt it's atom related, but more OSX-y
