### ISSUE TITLE
Haskell-ghc-mod: ghc-mod command check failed with error Error

### ISSUE THREAD

**Issue by rwobben** [atom/atom#11174]
[Enter steps to reproduce below:]

1. Make a file with this contents 

    module Main where

    import Lib
    import Control.Monad(forever)
    import Data.Char (toLower)
    import Data.Maybe (isJust)
    import Data.List (intersperse)
    import System.Exit(exitSuccess)
    import System.Ramdom(randomRIO)

    type WordList = [String]

    minWordLength :: Int
    minWordLength = 5

    maxWordLength :: Int
    maxWordLength = 9

    allWords :: IO WordList
    allWords = do
      dict <- readfille ¨data/words
      return (lines dict)

    gameWords :: IO WordList
    gameWords = do
      aw <- allWords
      return (filter gameLength aw)
      where gameLength w =
        let l = length (w :: String)
        in l > winWordLength && l < maxWordLength

    randomWord :: Wordlist -> IO String
    randomWord wl = do
      randomIndex <- randomIO ( 0, length wl - 1 )
      return $ wl !! randomIndex

    randomWord' :: IO String
    randomWord' = gameWords >>= randomWord

2. .Save the file 

*Atom Version**: 1.5.4
**System**: Ubuntu 15.10
**Thrown From**: Atom Core

### Stack Trace

Haskell-ghc-mod: ghc-mod command check failed with error Error

```
At caps: {"version":[5,5,0,0],"legacyInteractive":true,"fileMap":true,"rootExec":false,"quoteArgs":true,"optparse":true}
URI: /home/roelof/Documents/haskellbook/chapter_13/hangman/app/Main.hs
Args: --
message: spawn ghc-mod ENOENT
log:
-28.82s: Trying to run ghc-modi in /home/roelof/Documents/haskellbook/chapter_13/hangman
-28.819s: Checking for ghc-modi in /home/roelof/Documents/haskellbook/chapter_13/hangman
-28.819s: Found running ghc-modi instance for /home/roelof/Documents/haskellbook/chapter_13/hangman
-28.816s: Timeout
-28.768s: Trying to run ghc-modi in /home/roelof/Documents/haskellbook/chapter_13/hangman
-28.768s: Checking for ghc-modi in /home/roelof/Documents/haskellbook/chapter_13/hangman
-28.768s: Found running ghc-modi instance for /home/roelof/Documents/haskellbook/chapter_13/hangman
-28.768s: Timeout
-0.094s: running ghc-mod check,/home/roelof/Documents/haskellbook/chapter_13/hangman/app/Main.hs,-- with options.cwd = /home/roelof/Documents/haskellbook/chapter_13/hangman,options.env = [object Object],options.encoding = utf-8
-0.076s: running ghc-mod lint,/home/roelof/Documents/haskellbook/chapter_13/hangman/app/Main.hs,-- with options.cwd = /home/roelof/Documents/haskellbook/chapter_13/hangman,options.env = [object Object],options.encoding = utf-8
-0.063s: Main did-save triggered
-0.063s: Main updating
-0.063s: running ghc-mod browse,-d,--,Main with options.cwd = /home/roelof/Documents/haskellbook/chapter_13/hangman,options.env = [object Object],options.encoding = utf-8
-0.047s: Using fallback child_process because of spawn ghc-mod ENOENT
-0.029s: Using fallback child_process because of spawn ghc-mod ENOENT
-0.016s: Using fallback child_process because of spawn ghc-mod ENOENT
0s: Error: spawn ghc-mod ENOENT

Error: spawn ghc-mod ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

### Commands

```
     -2:36.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:46.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:31.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:27.9.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -1:26.3.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:20.2.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:18.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:17.9.0 core:move-down (atom-text-editor.editor.is-focused)
  5x -1:17 core:move-up (atom-text-editor.editor.is-focused)
  5x -1:15.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:44.2.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:41.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:30.5.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:29.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:07.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:02.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.6.2
haskell-ghc-mod, v1.11.0
ide-haskell, v1.5.3
ide-haskell-repl, v0.0.19
ide-haskell-stack, v0.0.3
language-haskell, v1.7.2

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
Sorry you're running into trouble here! This looks like an issue with [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) though – feel free to open an issue there.

**Comment by lierdakil** [comment]
Sorry about this, apparently child_process reports incomplete stack in its error object, so that's why this happened. Should be fixed in latest release.
