### ISSUE TITLE
Uncaught Error: Pane items must be objects. Attempted to add item undefined.

### ISSUE THREAD

**Issue by smlombardi** [atom/atom#11189]
**Steps to Reproduce:**
1. Open a new empty Atom in safe mode
1. If an untitled tab was created by the `Open Empty Editor on Start` configuration option close it so the pane is empty
1. Run `pane:split-[direction]-and-move-active-item` from the command palette

**Atom Version**: 1.7.0-beta0
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: Pane items must be objects. Attempted to add item undefined.

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:450

Error: Pane items must be objects. Attempted to add item undefined.
    at Pane.module.exports.Pane.addItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:450:15)
    at Pane.module.exports.Pane.moveItemToPane (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:609:19)
    at PaneContainer.module.exports.PaneContainer.moveActiveItemToPane (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane-container.js:276:23)
    at atom-pane-container.module.exports.PaneContainerElement.moveActiveItemToNearestPaneInDirection (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane-container-element.js:96:20)
    at atom-pane-container.module.exports.PaneContainerElement.moveActiveItemToPaneOnLeft (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane-container-element.js:80:19)
    at atom-workspace.module.exports.WorkspaceElement.moveActiveItemToPaneOnLeft (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/workspace-element.js:151:33)
    at atom-workspace.commandRegistry.add.window:move-active-item-to-pane-on-left (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/register-default-commands.js:170:21)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -2:07.7.0 pane:split-right-and-copy-active-item (atom-text-editor.editor.is-focused)
     -2:04.0 core:close (atom-text-editor.editor.is-focused)
  2x -1:10 editor:newline (atom-text-editor.editor.is-focused)
     -1:04.6.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:01.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:58.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:37.5.0 pane:split-right (atom-text-editor.editor.is-focused)
  2x -0:09.7.0 window:move-active-item-to-pane-on-right (atom-pane.pane.active)
     -0:01.5.0 window:move-active-item-to-pane-on-left (atom-pane.pane.active)
     -0:00.9.0 window:move-active-item-to-pane-on-right (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "preview-tabs",
      "autocomplete-snippets",
      "gulp-control",
      "SFTP-deployment",
      "atom-color-highlight",
      "linter-jscs"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-dark-ui",
      "gruvbox-syntax"
    ]
  },
  "editor": {
    "fontFamily": "OperatorMono-Book",
    "invisibles": {},
    "lineHeight": 1.7,
    "nonWordCharacters": "/\\\\()\\\"':,.;<>~!%^
```

**Comment by dbc60** [comment]
I ran into this problem, too. I'm running Atom 1.6.0 on Windows 10 x64. After adding new key bindings to use the nifty new pane commands, all I did was:

1. open two or more documents
2. Ctrl-k down
3. Ctrl-k m down

My keymap is:

```
# New pane manipulation keybindings for Windows and Linux
'.platform-win32, .platform-linux':
  # Create an empty split pane
  'ctrl-k left':  'pane:split-left'
  'ctrl-k right': 'pane:split-right'
  'ctrl-k up':    'pane:split-up'
  'ctrl-k down':  'pane:split-down'

  # Create a split pane with the current pane item moved into it
  'ctrl-k m left':  'pane:split-left-and-move-active-item'
  'ctrl-k m right': 'pane:split-right-and-move-active-item'
  'ctrl-k m up':    'pane:split-up-and-move-active-item'
  'ctrl-k m down':  'pane:split-down-and-move-active-item'

  # Create a split pane with the current pane item duplicated
  'ctrl-k d left':  'pane:split-left-and-copy-active-item'
  'ctrl-k d right': 'pane:split-right-and-copy-active-item'
  'ctrl-k d up':    'pane:split-up-and-copy-active-item'
  'ctrl-k d down':  'pane:split-down-and-copy-active-item'

  # Move the current pane item to the target split pane
  'alt-ctrl-shift-left':  'window:move-active-item-to-pane-on-left'
  'alt-ctrl-shift-right': 'window:move-active-item-to-pane-on-right'
  'alt-ctrl-shift-up':    'window:move-active-item-to-pane-above'
  'alt-ctrl-shift-down':  'window:move-active-item-to-pane-below'
```

Here's the stack trace:

```
Error: Pane items must be objects. Attempted to add item undefined.
    at Pane.module.exports.Pane.addItem (C:\Users\Doug\AppData\Local\atom\app-1.6.0\resources\app.asar\src\pane.js:355:15)
    at Pane.module.exports.Pane.moveItemToPane (C:\Users\Doug\AppData\Local\atom\app-1.6.0\resources\app.asar\src\pane.js:505:19)
    at Pane.module.exports.Pane.split (C:\Users\Doug\AppData\Local\atom\app-1.6.0\resources\app.asar\src\pane.js:792:14)
    at Pane.module.exports.Pane.splitDown (C:\Users\Doug\AppData\Local\atom\app-1.6.0\resources\app.asar\src\pane.js:759:19)
    at atom-pane.commandRegistry.add.pane:split-down-and-move-active-item (C:\Users\Doug\AppData\Local\atom\app-1.6.0\resources\app.asar\src\register-default-commands.js:268:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Doug\AppData\Local\atom\app-1.6.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Doug\AppData\Local\atom\app-1.6.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Doug\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Doug\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Doug\AppData\Local\atom\app-1.6.0\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\Doug\AppData\Local\atom\app-1.6.0\resources\app.asar\src\window-event-handler.js:3:61)
```

**Comment by Ben3eeE** [comment]
I can reproduce this in safe mode with the steps that @dbc60 mentioned.
Here are my minimal repro steps without custom keymap definitions that work every time.

1. Open a new empty atom window in safe mode.
2. Run pane:split-down from command palette.
3. Run pane:split-down-and-move-active-item from the command palette.

atom 1.6.2 Windows 7

Refs https://github.com/atom/atom/pull/7953

cc @50Wliu or someone for adding correct labels to issue.

**Comment by Ben3eeE** [comment]
Tried to repro in 1.11-beta5 https://github.com/atom/command-palette/issues/67 is linked as duplicate using the steps I posted.

**Comment by 50Wliu** [comment]
Notifications loves targeting Command Palette as the source of the exceptions if you execute some commands through the command palette.
