### ISSUE TITLE
Atom 1.6.0 editor doesnt show, dev tools instead (Linux Mint 17.1 )

### ISSUE THREAD

**Issue by xunorus** [atom/atom#11215]
Hi, I was using Atom 1.6 normally on Mint 17.1. (I installed it on a 32bit machin using webupd8 ppa)
After updating some packages within Atom it broke.
Now, when I open Atom i get  the Developer tools console ...

I tried reinstalling and cleaning paths without success.
I really appreciate some help!

This is the log, 
index.js:62 Error: Cannot find module '../build/Debug/nodegit.node'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/node_modules/nodegit/lib/nodegit.js:17:12)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/src/git-repository-async.js:25:16)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/src/git-repository.js:12:24)
    at Object.<anonymous> (/opt/atom/resources/app.asar/src/git-repository.js:428:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/src/git-repository-provider.js:8:19)
    at Object.<anonymous> (/opt/atom/resources/app.asar/src/git-repository-provider.js:83:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
handleSetupError	@	index.js:62
.

**Comment by ZuBB** [comment]
same thing

14.04 + atom (1.6.0-1~webupd8~0)

**Comment by ZuBB** [comment]
I guess we will not get any support since this is unofficial build..

**Comment by Narrat** [comment]
Building 1.6.0 from source I get the same behaviour.
Still appearing with the safe mode, deleted ATOM_HOME and cache files.

Following a log obtained via -f, if it's of any help.

>$ atom -f .
[2452:0320/160324:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[2452:0320/160326:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[2452:0320/160326:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[2452:0320/160326:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[2452:0320/160326:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[2485:0320/160326:ERROR:renderer_main.cc(200)] Running without renderer sandbox
auto-updater is not implemented on this platform
Error: auto-updater is not implemented on this platform
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:11:13)
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:14:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at AutoUpdateManager.module.exports.AutoUpdateManager.setupAutoUpdater (/usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:62:23)
    at /usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:53:24
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at NavigationController.loadUrl (/usr/share/atom/resources/atom.asar/browser/api/lib/navigation-controller.js:59:24)
    at EventEmitter.webContents.(anonymous function) [as loadUrl] (/usr/share/atom/resources/atom.asar/browser/api/lib/web-contents.js:81:27)
    at BrowserWindow.loadUrl (/usr/share/atom/resources/atom.asar/browser/api/lib/browser-window.js:121:37)
    at AtomWindow.module.exports.AtomWindow.setLoadSettings (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:124:33)
    at new AtomWindow (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:110:12)
    at AtomApplication.module.exports.AtomApplication.openPaths (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:710:24)
    at AtomApplication.module.exports.AtomApplication.openWithOptions (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:131:21)
    at new AtomApplication (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:111:14)
    at createAtomApplication (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:60:16)
    at Function.module.exports.AtomApplication.open (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:63:9)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/main.js:55:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
App load time: 988ms
[2501:0320/160327:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[2452:0320/160327:INFO:CONSOLE(62)] "Error: Cannot find module '../build/Debug/nodegit.node'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/nodegit/lib/nodegit.js:17:12)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/git-repository-async.js:25:16)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/git-repository.js:12:24)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/git-repository.js:428:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/git-repository-provider.js:8:19)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/git-repository-provider.js:83:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)", source: file:///usr/share/atom/resources/app.asar/static/index.js (62)
[2452:0320/160327:WARNING:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)

**Comment by Arakaki** [comment]
This issue seems to be related with #10819.

**Comment by Narrat** [comment]
Thanks for the note Arakaki. In my case this seems to the same and made a note about it there.

**Comment by xunorus** [comment]
QUICK DIRTY FIX: **Revert to Atom Version 1.5.4.1 for  x86** 
(file found in thread #10819 )
sudo apt-get remove atom

wget https://bugs.launchpad.net/~nilarimogard/+archive/ubuntu/test3/+build/9292390/+files/atom_1.5.4-1~webupd8~0_i386.deb

sudo dpkg -i atom_1.5.4-1~webupd8~0_i386.deb

I close this for now, Think we better follow  #10819 to see if we can upgrade to 1.7
