### ISSUE TITLE
Uncaught Error: Invalid package /Users/maurodegiorgi/Project/mfeed_app/Applications/Atom.app/Cont...

### ISSUE THREAD

**Issue by mdgart** [atom/atom#11231]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Invalid package /Users/maurodegiorgi/Project/mfeed_app/Applications/Atom.app/Contents/Resources/app.asar

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:517

Error: Invalid package /Users/maurodegiorgi/Project/mfeed_app/Applications/Atom.app/Contents/Resources/app.asar
    at invalidArchiveError (ATOM_SHELL_ASAR.js:117:13)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:141:9)
    at Workspace.module.exports.Workspace.openTextFile (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:564:27)
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:491:23)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:419:19)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1038:19)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:244:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-elixir"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
Parinfer, v1.14.0
autocomplete-elixir, v1.5.13
autocomplete-plus, v2.29.1
elixir-docs, v0.1.6
iex, v0.9.27
language-elm, v1.3.3
linter, v1.11.4
linter-clojure, v1.1.2
linter-elm-make, v0.4.0
proto-repl, v1.1.3

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment]
Duplicate of https://github.com/atom/atom/issues/10704 ?

**Comment by mdgart** [comment]
I solved with `npm install -g asar`
