### ISSUE TITLE
Haskell-ghc-mod: ghc-mod command browse failed with error Error

### ISSUE THREAD

**Issue by sgraf812** [atom/atom#11266]
1. Configure the plugin to work with `stack` (hopefully I've succeeded at that?!)
1. Create a `Simple` project with the `stack` tool
2. Open `Main.hs`

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Haskell-ghc-mod: ghc-mod command browse failed with error Error

```
At caps: {"version":[5,5,0,0],"legacyInteractive":true,"fileMap":true,"rootExec":false,"quoteArgs":true,"optparse":true,"typeConstraints":false,"browseParents":false,"interactiveCaseSplit":false}
URI: undefined
Args: -d,--,Main
message: spawn ghc-mod ENOENT
log:
-7.346s: Main did-save triggered
-7.346s: Main updating
-7.344s: running ghc-mod browse,-d,--,Main with options.cwd = /Users/sgraf/Documents/code/haskell/feed-gipeda,options.env = [object Object],options.encoding = utf-8
-7.333s: running ghc-mod check,/Users/sgraf/Documents/code/haskell/feed-gipeda/src/Main.hs,-- with options.cwd = /Users/sgraf/Documents/code/haskell/feed-gipeda,options.env = [object Object],options.encoding = utf-8
-7.329s: running ghc-mod lint,/Users/sgraf/Documents/code/haskell/feed-gipeda/src/Main.hs,-- with options.cwd = /Users/sgraf/Documents/code/haskell/feed-gipeda,options.env = [object Object],options.encoding = utf-8
-7.322s: Using fallback child_process because of spawn ghc-mod ENOENT
-7.318s: Using fallback child_process because of spawn ghc-mod ENOENT
-7.314s: Using fallback child_process because of spawn ghc-mod ENOENT
-7.308s: Error: spawn ghc-mod ENOENT
-7.283s: Error: spawn ghc-mod ENOENT
-7.266s: Error: spawn ghc-mod ENOENT
-7.243s: Main updated
-4.37s: Main did-save triggered
-4.37s: Main updating
-4.369s: running ghc-mod browse,-d,--,Main with options.cwd = /Users/sgraf/Documents/code/haskell/feed-gipeda,options.env = [object Object],options.encoding = utf-8
-4.357s: running ghc-mod check,/Users/sgraf/Documents/code/haskell/feed-gipeda/src/Main.hs,-- with options.cwd = /Users/sgraf/Documents/code/haskell/feed-gipeda,options.env = [object Object],options.encoding = utf-8
-4.352s: running ghc-mod lint,/Users/sgraf/Documents/code/haskell/feed-gipeda/src/Main.hs,-- with options.cwd = /Users/sgraf/Documents/code/haskell/feed-gipeda,options.env = [object Object],options.encoding = utf-8
-4.338s: Using fallback child_process because of spawn ghc-mod ENOENT
-4.333s: Using fallback child_process because of spawn ghc-mod ENOENT
-4.33s: Using fallback child_process because of spawn ghc-mod ENOENT
-4.326s: Error: spawn ghc-mod ENOENT
-4.302s: Error: spawn ghc-mod ENOENT
-4.287s: Error: spawn ghc-mod ENOENT
-4.272s: Main updated
-0.028s: Main did-save triggered
-0.028s: Main updating
-0.028s: running ghc-mod browse,-d,--,Main with options.cwd = /Users/sgraf/Documents/code/haskell/feed-gipeda,options.env = [object Object],options.encoding = utf-8
-0.02s: running ghc-mod check,/Users/sgraf/Documents/code/haskell/feed-gipeda/src/Main.hs,-- with options.cwd = /Users/sgraf/Documents/code/haskell/feed-gipeda,options.env = [object Object],options.encoding = utf-8
-0.016s: running ghc-mod lint,/Users/sgraf/Documents/code/haskell/feed-gipeda/src/Main.hs,-- with options.cwd = /Users/sgraf/Documents/code/haskell/feed-gipeda,options.env = [object Object],options.encoding = utf-8
-0.01s: Using fallback child_process because of spawn ghc-mod ENOENT
-0.006s: Using fallback child_process because of spawn ghc-mod ENOENT
-0.003s: Using fallback child_process because of spawn ghc-mod ENOENT
0s: Error: spawn ghc-mod ENOENT

Error: spawn ghc-mod ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

### Commands

```
     -0:14.7.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:14 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:13.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:13 vim-mode:move-to-beginning-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:12.7.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:12.1.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:11.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:11.6.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:11.1.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:10.9.0 vim-mode:move-to-beginning-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:10.6.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:10 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:09.8.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -0:03.6.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:02.5.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.4.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 13,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.6.3
browser-plus, v0.0.54
ex-mode, v0.8.0
haskell-ghc-mod, v1.11.3
ide-haskell, v1.5.4
ide-haskell-cabal, v1.1.0
language-elm, v1.3.3
language-haskell, v1.7.5
language-idris, v0.4.4
language-latex, v0.6.1
language-purescript, v0.6.1
linter, v1.11.4
minimap, v4.21.0
sync-settings, v0.7.2
theme-switcher, v1.1.0
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by sgraf812** [comment]
I just realized that Atom suggested to create the issue in this repository instead of haskell-ghc-mod's. Is there some way to move or delete this?
