### ISSUE TITLE
Uncaught Error: Unable to watch path

### ISSUE THREAD

**Issue by aovchinn** [atom/atom#11288]
[Enter steps to reproduce below:]
1. open folder (path /home/alexzander/Dropbox/study/3year/2/optimize/first 5b)
2. Ctrl + N (new file)
3. copy-paste some text
4. Ctrl+A (select all)
5. enable soft-wrap
6. Ctrl+S (save)
7. error

7.1 when I hit ctrl+S (save) again  I get file named "<filename>(White Space Conflict)"

**Atom Version**: 1.6.0
**System**: Linux Mint
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: Unable to watch path

```
At /opt/atom/resources/app.asar/src/pane.js:896

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/opt/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:66:29)
    at new HandleWatcher (/opt/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:30:12)
    at new PathWatcher (/opt/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:120:30)
    at Object.exports.watch (/opt/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:179:12)
    at File.module.exports.File.subscribeToNativeChangeEvents (/opt/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:504:109)
    at File.module.exports.File.writeSync (/opt/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:359:14)
    at TextBuffer.module.exports.TextBuffer.saveAs (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1059:19)
    at TextEditor.module.exports.TextEditor.saveAs (/opt/atom/resources/app.asar/src/text-editor.js:635:26)
    at Pane.module.exports.Pane.saveItemAs (/opt/atom/resources/app.asar/src/pane.js:637:16)
    at Pane.module.exports.Pane.saveItem (/opt/atom/resources/app.asar/src/pane.js:621:21)
    at Pane.module.exports.Pane.saveActiveItem (/opt/atom/resources/app.asar/src/pane.js:596:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/opt/atom/resources/app.asar/src/workspace.js:673:35)
    at atom-workspace.commandRegistry.add.core:save (/opt/atom/resources/app.asar/src/register-default-commands.js:205:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:58.1.0 application:new-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:55.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:48.4.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:42 editor:toggle-soft-wrap (atom-text-editor.editor.is-focused)
     -0:25.9.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "wrap-guide"
    ],
    "packagesWithKeymapsDisabled": [
      "term3"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabType": "soft"
  }
}
```
### Installed Packages

``` coffee
# User
GAS-x86_64-highlighter, v0.1.0
atom-autocomplete-php, v0.18.7
atom-beautify, v0.28.27
atom-material-ui, v1.2.10
highlight-selected, v0.11.2
php-twig, v4.0.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@aovchinn can you reproduce this in safe mode (`atom --safe`)?  Thanks.

**Comment by aovchinn** [comment]
@50Wliu  (white space conflict) after filename but no error

**Comment by 50Wliu** [comment]
Ok, and does it happen with any open folder and text that you paste into the new file?

**Comment by aovchinn** [comment]
@50Wliu  no, only filename changes

**Comment by thedrow** [comment]
I see this in OSX El Capitan with Atom 1.6.1 as well. I deleted a file and it happened.

**Comment by alexrussell** [comment]
@thedrow I get this too but presumably it's a different issue entirely (though Atom thinks it's the same one as it's the same error): delete or rename a file you have open, the watching process can no longer see it and so you get the unable to watch error.

Presumably this exception should be caught and code should be used to determine if the file is still there - if not, silently ignore (maybe even close the active file tab if it's not dirty), if the file is still there then something else weird is going on, so rethrow maybe?

**Comment by thedrow** [comment]
@alexrussell Sounds about right.

**Comment by alexrussell** [comment]
@thedrow I think I've worked out what the exact issue is in my case - the files I rename/delete is a mounted network share (using smb on OSX). Presumably Atom is unable to watch these paths in the normal way (fsevents style watching probably doesn't work on mounted volumes) and so the file just disappears from beneath Atom and then we see this error.

@50Wliu this appears to be a separate issue (my specific issue is not related to whitespace stuff in filenames). However, I haven't explored this fully, so can't say it's definitely related to mounted volumes. Still, shall I raise a separate issue?

**Comment by thedrow** [comment]
@alexrussell My files are not mounted on a network drive but on an encrypted drive. Not sure if it matters.

**Comment by alexrussell** [comment]
@thedrow I imagine it might be similar - basically a filesystem that inotify/fsevents can't hook into the device driver or something. I mean I have literally no idea about how path watchers work, but at a guess they find a way to be performant (otherwise we're talking polling, right??) by hooking into the kernel drivers, etc. So presumably anything on a samba share or an encrypted volume can't go through the normal stuff and so the atom watcher fails. But I dunno.
