### ISSUE TITLE
gyp ERR!

### ISSUE THREAD

**Issue by lovebdsobuj** [atom/atom#11393]
```
$ script/build
Node: v5.4.1
npm: v2.13.3
Python: v2.7.3
Installing build modules...
gyp: C:\Users\Sobuj\.node-gyp\5.4.1\common.gypi not found (cwd: D:\GitHub\Windows\atom\build\node_modules\runas) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\GitHub\Windows\atom\build\node_modules\npm\node_modules\node-gyp\lib\configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\GitHub\\Windows\\atom\\build\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\GitHub\Windows\atom\build\node_modules\runas
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "D:\\GitHub\\Windows\\atom\\build\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=D:\\GitHub\\Windows\\atom\\build\\.npmrc" "install" "--loglevel" "error"
npm ERR! node v5.4.1
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\GitHub\Windows\atom\build\npm-debug.log

```
> Platform: Windows 10
MSBuild Path Location: C:\Program Files\MSBuild
Visual Studio Path Location: F:\Development\VisualStudio

**Comment by damieng** [comment]
I'm thinking this might be cause by Visual Studio being installed in a non-standard location and node-gyp being unable to find it.

**Comment by lovebdsobuj** [comment]
I think so,
Is it possible configure universally non-standard location as standard without reinstalling vs without configure node-gyp?

**Comment by damieng** [comment]
Actually this looks like a node-gyp error. Here are some threads that discuss it there:

https://github.com/nodejs/node-gyp/issues/313

https://github.com/nodejs/node-gyp/issues/376
