### ISSUE TITLE
Atom broke when opening file with sudo ubuntu 15.04

### ISSUE THREAD

**Issue by jQrgen** [atom/atom#11405]
Running this command in the terminal:
`jorgen@jorgen-pc:~/hadoop-2.7.0/etc/hadoop$ sudo atom hadoop-env.sh 
`

This error is displayed inside of the atom window (The web developer tools opens inside of atom and produces this message):

```
Error: EACCES: permission denied, open '/home/jorgen/.atom/compile-cache/less/df1b7fbc57dbeed23a8f1f8de95b4dfebcc06066/imports.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.writeFileSync (fs.js:1171:15)
    at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:155:17)
    at LessCache.module.exports.LessCache.setImportPaths (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:113:12)
    at new LessCache (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:32:12)
    at new LessCompileCache (/usr/share/atom/resources/app.asar/src/less-compile-cache.js:20:20)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/usr/share/atom/resources/app.asar/src/theme-manager.js:270:26)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/usr/share/atom/resources/app.asar/src/theme-manager.js:257:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (/usr/share/atom/resources/app.asar/src/theme-manager.js:174:24)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (/usr/share/atom/resources/app.asar/src/theme-manager.js:237:12)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (/usr/share/atom/resources/app.asar/src/theme-manager.js:232:19)
    at new AtomEnvironment (/usr/share/atom/resources/app.asar/src/atom-environment.js:250:19)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:19:19)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)
```

**Comment by ZombieHippie** [comment]
@jQrgen thank you for reporting, would you reproduce this and execute the `ls -lah <file permissions path>`? Where `<file path>` looks similar to your `/home/jorgen/.atom/compile-cache/less/df1b7fbc57dbeed23a8f1f8de95b4dfebcc06066/imports.json`

**Comment by 50Wliu** [comment]
I'm closing this in favor of #9822 - please report your findings in that issue.  Thanks!
