### ISSUE TITLE
Fails to build on Debian Sid

### ISSUE THREAD

**Issue by borisovg** [atom/atom#11435]
### Description

````
Node: v4.4.2
npm: v2.13.3
Installing build modules...
=> Took 4049ms.

Installing apm...
=> Took 56455ms.

Deleting old packages...
Removing diff ✓
=> Took 1060ms.

Installing modules ✗
> atom@1.7.0-beta5 preinstall /home/borisov/src/atom
> node -e 'process.exit(0)'


> pathwatcher@6.5.0 install /home/borisov/src/atom/node_modules/text-buffer/node_modules/pathwatcher
> node-gyp rebuild

make: Entering directory '/home/borisov/src/atom/node_modules/text-buffer/node_modules/pathwatcher/build'
  CXX(target) Release/obj.target/pathwatcher/src/main.o
  CXX(target) Release/obj.target/pathwatcher/src/common.o
  CXX(target) Release/obj.target/pathwatcher/src/handle_map.o
  CXX(target) Release/obj.target/pathwatcher/src/pathwatcher_linux.o
  SOLINK_MODULE(target) Release/obj.target/pathwatcher.node
  COPY Release/pathwatcher.node
make: Leaving directory '/home/borisov/src/atom/node_modules/text-buffer/node_modules/pathwatcher/build'

> marker-index@3.1.0 install /home/borisov/src/atom/node_modules/marker-index
> node-gyp rebuild

make: Entering directory '/home/borisov/src/atom/node_modules/marker-index/build'
  CXX(target) Release/obj.target/marker_index/src/native/iterator.o
  CXX(target) Release/obj.target/marker_index/src/native/marker-index-wrapper.o
  CXX(target) Release/obj.target/marker_index/src/native/marker-index.o
  CXX(target) Release/obj.target/marker_index/src/native/node.o
  CXX(target) Release/obj.target/marker_index/src/native/point.o
  SOLINK_MODULE(target) Release/obj.target/marker_index.node
  COPY Release/marker_index.node
make: Leaving directory '/home/borisov/src/atom/node_modules/marker-index/build'

> runas@2.0.0 install /home/borisov/src/atom/node_modules/snippets/node_modules/runas
> node-gyp rebuild

make: Entering directory '/home/borisov/src/atom/node_modules/snippets/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
runas.target.mk:90: recipe for target 'Release/obj.target/runas/src/main.o' failed
make: Leaving directory '/home/borisov/src/atom/node_modules/snippets/node_modules/runas/build'

In file included from ../src/main.cc:1:0:
../../nan/nan.h:260:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../../nan/nan.h:255:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../../nan/nan.h:660:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../../nan/nan.h:660:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../../nan/nan.h:664:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../../nan/nan.h:664:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../../nan/nan.h:671:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:25:0,
                 from ../src/main.cc:1:
/home/borisov/.atom/.node-gyp/.node-gyp/0.36.8/src/node_buffer.h:41:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/borisov/.atom/.node-gyp/.node-gyp/0.36.8/src/node_buffer.h:41:40: note:   conversion of argument 3 would be ill-formed:
In file included from ../src/main.cc:1:0:
../../nan/nan.h:671:67: error: invalid conversion from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:25:0,
                 from ../src/main.cc:1:
/home/borisov/.atom/.node-gyp/.node-gyp/0.36.8/src/node_buffer.h:53:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/borisov/.atom/.node-gyp/.node-gyp/0.36.8/src/node_buffer.h:53:40: note:   conversion of argument 2 would be ill-formed:
In file included from ../src/main.cc:1:0:
../../nan/nan.h:671:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../../nan/nan.h:675:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                             ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../../nan/nan.h:682:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/borisov/src/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.4.0-1-amd64
gyp ERR! command "node" "/home/borisov/src/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/borisov/src/atom/node_modules/snippets/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 

npm ERR! Linux 4.4.0-1-amd64
npm ERR! argv "/home/borisov/src/atom/apm/node_modules/atom-package-manager/bin/node" "/home/borisov/src/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/borisov/.atom/.apm/.apmrc" "--userconfig" "/home/borisov/.atom/.apmrc" "install" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/borisov/src/atom/npm-debug.log
````

### Steps to Reproduce

1. git fetch -p
2. git checkout $(git describe --tags \`git rev-list --tags --max-count=1\`)
3. script/build

**Comment by alexm** [comment]
I had a different issue with `runas@3.1.1` so I forced `"runas": "3.1.0",` instead of current `"runas": "^3.1",` in `package.json` from master branch, and now it's building atom.

**Comment by borisovg** [comment]
I resolved this issue with a `rm -r node_modules`. Probably there was something left from previous installation of `runas` that was causing a problem, but that is their bug not Atom's.
