### ISSUE TITLE
Launching atom -d hangs, apm test crashes

### ISSUE THREAD

**Issue by florianb** [atom/atom#11433]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

If i launch `atom -d` from command-line, Atom gets started (task-bar-item appears, menu changes name and items) but no window is created.

If i try to invoke any `apm test` i get this exception, which hangs at the end, creating full CPU usage:

```
2016-04-12 12:51:45.477 Atom[73566:7805158] Cannot find module 'underscore-plus'
2016-04-12 12:51:45.509 Atom[73566:7805158] Error: Cannot find module 'underscore-plus'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/florianbreisch/github/atom/src/browser/atom-window.coffee:7:5)
    at Object.<anonymous> (/Users/florianbreisch/github/atom/src/browser/atom-window.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/florianbreisch/github/atom/src/browser/atom-application.coffee:1:14)
    at Object.<anonymous> (/Users/florianbreisch/github/atom/src/browser/atom-application.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/main.js:54:25)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```

Launching Atom in normal- or safe-mode works fine - there are no unexpected error messages or warnings.

In order to fix that i unlinked all packages, completely rebuild any caches, deleted and reinstalled dedicated `node_modules/`. The dev-directory (`~/.atom/dev/packages`) is empty, i disabled all packages.

### Steps to Reproduce

I really don't know how this could happen and what i may have done to make this happen. I even don't know how to fix it.

### Versions

```
atom --version
1.6.2

apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.6.4

ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65
```

**Comment by florianb** [comment]
**** wrong repository.. 😞
