### ISSUE TITLE
Uncaught Error: Unable to watch path

### ISSUE THREAD

**Issue by patriceminside** [atom/atom#11443]
Hello, i have this 'unknowing' issue in atom when i press to save my changes.

cmd + s.

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Unable to watch path

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:896

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:66:29)
    at new HandleWatcher (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:30:12)
    at new PathWatcher (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:120:30)
    at Object.exports.watch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:179:12)
    at File.module.exports.File.subscribeToNativeChangeEvents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:504:109)
    at File.module.exports.File.writeSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:359:14)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1059:19)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1043:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:629:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:613:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:596:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:673:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:205:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:43.5.0 core:cancel (atom-text-editor.editor.is-focused)
  4x -0:43.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:41.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:41.9.0 core:cancel (atom-text-editor.editor.is-focused)
  3x -0:41.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:40.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:40.8.0 core:cancel (atom-text-editor.editor.is-focused)
 15x -0:40.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:37 core:backspace (atom-text-editor.editor.is-focused)
  9x -0:36.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:34.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:34.8.0 core:cancel (atom-text-editor.editor.is-focused)
  6x -0:03.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:01.1.0 core:cancel (atom-text-editor.editor.is-focused)
  4x -0:00.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "minimap",
      "symbols-tree-view",
      "highlight-line",
      "selection-highlight",
      "sort-lines"
    ],
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "._*",
      "Thumbs.db"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "tabLength": 4,
    "zoomFontWhenCtrlScrolling": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by magic53** [comment]
This error occurred for me when modifying a file in another editor while atom had the file open.

**Atom Version**: 1.7.1
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Unable to watch path

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:77

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:77:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:53:27
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -1:17.2.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:16.9.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -1:16.4.0 core:save (atom-text-editor.editor.is-focused)
  5x -1:12.6.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:11.4.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -1:11.1.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  2x -1:10.9.0 core:select-left (atom-text-editor.editor.is-focused)
     -1:08.8.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -1:07.4.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:07.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:54 core:backspace (atom-text-editor.editor.is-focused)
     -0:52.8.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:52.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:52.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:51.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:48.4.0 core:move-down (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 12,
    "invisibles": {},
    "preferredLineLength": 160
  }
}
```

### Installed Packages

```coffee
# User
language-babel, v2.17.2
react, v0.15.0

# Dev
No dev packages
```

**Comment by stugol** [comment]
This is happening for me as well. I have filenames with `-` in them.

**Comment by patriceminside** [comment]
I think the problem was caused by a package, but I’ve updated Atom and the problem seems to be gone. Thanks for your help :)

**Comment by lee-dohm** [comment]
I'm glad to hear that things are working for you @patriceminside. 

@stugol or @magic53 Can you give steps to reproduce this error when running Atom in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by stugol** [comment]
Probably not. But "it works when there are no other plugins" != "it works".

**Comment by lee-dohm** [comment]
No, but "it works when there are no other plugins" == "the problem is not in Atom" to a very high degree of confidence.

**Comment by lee-dohm** [comment]
Also, the first step in any troubleshooting effort is to narrow down the problem space so that you can find out what is causing the problem. Figuring out what is causing the problem is the first step towards fixing it. This is why Safe Mode is the first thing we ask people to do.

**Comment by neolectron** [comment]
It happens if I rename a file xxx in xxx.js through treeView, while this file is opened in a tab.

**Comment by awesomebing1** [comment]
This happened to me when I deleted a folder and had Atom in the background. Came back a couple hours later, had this error message displayed after a bit of SBBOD.

**Comment by yask123** [comment]
Faced a similar issue when I tried to save a text file which was earlier modified by a different programme

**Comment by lee-dohm** [comment]
Can anyone that is still having this problem reproduce it in Safe Mode and supply repro steps? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by Marvo2011** [comment]
Same Issue on OS X 10.11.5

`Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:77:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:53:27
    at FSReqWrap.oncomplete (fs.js:82:15)`

**Comment by lee-dohm** [comment]
Can anyone that is still having this problem reproduce it in Safe Mode and supply repro steps? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by lee-dohm** [comment]
Closing due to lack of response. If anyone has any more information on this, please let us know and we can reopen the Issue.

**Comment by stugol** [comment]
Ah. So if people aren't prepared to do your job for you, you're not prepared to fix the bug? Enough people have reported it, so it's a REAL BUG. You can't just close the fucking thing because people don't want to disable all their other add-ons for a week to see if the bug goes away. Try fixing the sodding thing, or put diagnostic logs in, or something. Don't just sit there in your ivory tower and disavow all knowledge of the problem.

**Comment by gieljnssns** [comment]
[Enter steps to reproduce below:]

1. I have a .json file open in atom the file is on another volume (raspberry pi)
2. i use atom beautify
3. sometimes i see the same file with temp in the name
4. I have this error:

**Atom Version**: 1.9.4
**System**: Mac OS X 10.11.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Unable to watch path

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:77

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:77:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:57:25
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -0:37.8.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "python-debugger",
      "atom-runner",
      "print-atom"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.10 (active)
atom-runner, v2.6.0 (inactive)
autocomplete-python, v1.8.5 (active)
linter, v1.11.14 (active)
linter-js-yaml, v1.2.5 (active)
linter-pep8, v1.3.0 (active)
print-atom, v0.1.1 (inactive)
python-debugger, v0.1.0 (inactive)
python-isort, v0.0.7 (active)
script, v3.8.3 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.2 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Flenz** [comment]
1. I just tried to save a file.

**Atom Version**: 1.9.8
**System**: DESKTOP-G61A0CB
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Unable to watch path

```
At D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\src\pane.js:1026

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\main.js:77:29)
    at new HandleWatcher (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\main.js:30:12)
    at new PathWatcher (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\main.js:131:30)
    at Object.exports.watch (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\main.js:190:12)
    at File.module.exports.File.subscribeToNativeChangeEvents (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:595:109)
    at File.module.exports.File.writeSync (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:384:14)
    at TextBuffer.module.exports.TextBuffer.saveAs (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1142:19)
    at TextBuffer.module.exports.TextBuffer.save (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1126:19)
    at TextEditor.module.exports.TextEditor.save (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor.js:743:26)
    at Pane.module.exports.Pane.saveItem (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\src\pane.js:734:18)
    at Pane.saveItem (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\src\pane.js:3:61)
    at Pane.module.exports.Pane.saveActiveItem (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\src\pane.js:717:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\src\workspace.js:699:35)
    at atom-workspace.commandRegistry.add.core:save (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\src\register-default-commands.js:220:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\src\command-registry.js:260:29)
    at D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (D:\Users\doubl\AppData\Local\atom\app-1.9.8\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -7:29.9.0 remote-ftp:toggle (atom-pane.pane.active)
  2x -6:59 core:backspace (atom-text-editor.editor.is-focused)
     -6:54.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -6:41.4.0 remote-ftp:disconnect (ul.list-inline.tab-bar.inset-panel)
  2x -5:36.9.0 core:delete (atom-text-editor.editor.is-focused)
     -5:35.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:51.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:51.4.0 core:copy (atom-text-editor.editor.is-focused)
     -0:49 core:paste (atom-text-editor.editor.is-focused)
     -0:47.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:46.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:44.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:43.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false
  },
  "editor": {
    "backUpBeforeSaving": true,
    "fontSize": 15,
    "invisibles": {},
    "softWrap": true,
    "tabLength": 4,
    "tabType": "hard"
  }
}
```

### Installed Packages

```coffee
# User
language-sql-mysql, v0.3.1 (active)
Remote-FTP, v0.8.3 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by fillarios** [comment]
This error is easy to reproduce using sshfs.

1. Mount sshfs volume (in my case with OSXFuse)
2. Add project folder from that volume
3. Open a file from this project
4. Rename the file

File is renamed but remains open by it's old name.

In this case inability to watch sshfs is expected since sshfs does not support inotify.

**Atom Version**: 1.9.9
**System**: Mac OS X 10.11.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Unable to watch path

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:77

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:77:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:53:27
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -4:12.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:41.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:40.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:33.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:32.7.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -3:30.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:26 core:save (atom-text-editor.editor.is-focused)
     -3:24.9.0 settings-view:open (atom-text-editor.editor.is-focused)
     -2:44.4.0 tree-view:move (span.name.icon.icon-file-text)
     -2:42.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:22.9.0 tree-view:move (span.name.icon.icon-file-text)
     -0:22.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:15.2.0 tree-view:remove (li.file.entry.list-item.selected)
     -0:02.3.0 tree-view:move (span.name.icon.icon-file-text)
  6x -0:01.9.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

**Comment by Elehisie** [comment]
I got this error every time when I "rename" any file by changing its extension inside atom.

**Comment by kresli** [comment]
Reproduce Error:
- mount folder by sshfs
- open file A (keep it open)
- drag & drop the file A somewhere else

**Comment by kamaradski** [comment]
confirming the same: **fillarios commented on Aug 19**

**Comment by ForeverWinter** [comment]
I'm also getting `Error: Unable to watch path` when trying to create a new file on a network drive letter that is mapped to a SharePoint location (Win 7).  File is created successfully but Atom throws the error.  Saving the file after it's created seems to work fine though (i.e. without errors).

**Comment by DoctorU** [comment]
FYI: This happens consistently for me when another program (e.g., in shell) moves the file that is open in the buffer. It's helpful when waiting for a cronjob process that moves a file! :)

**Comment by edwingustafson** [comment]
I got this message when saving a new file to a folder mounted over WebDAV in Windows 10. The file is editable and usable in Atom afterwards, and looks and works normally in Windows Explorer and other editors.

**Comment by bblincoe** [comment]
This issue occurs when mounting a shared windows folder (Windows 10) to my Mac OSX (El Capitan). I created a new file in Atom and then tried to rename the file. It doesn't appear to affect the way I can interact with the file. Also, the filename change was successful.

**Comment by smf0627** [comment]
I've been encountering this error as well.  But, it seems expected based on how I'm using Atom to get this message.  I'm working withing SharePoint 2013, and I get this message any time I directly save a file into the web server's file directory.  In SharePoint 2010, I used to have to Check Out files before saving over them, but in SharePoint 2013, I'm just able to save without the Check Out step.

**Comment by rmeleromira** [comment]
I'm getting this error using an sshfs mounted folder. I try to rename a file, and get this error. However, the file DOES change name on the filesystem, but isn't reflected in Atom. Folding and unfolding the folder where the the file resides refreshes Atom.

**Comment by qiangswa** [comment]
I'm getting this error with a nfs mounted folder. I moved the file to another folder, and this error shows up.  The moving actions itself was done correctly.

**Comment by samcv** [comment]
I just got this error and have **no** network or other types of drives mounted aside from the internal disks that mount at boot. Will update this post if it comes back.

Atom Version: 1.17.0-beta2 x64
System: Arch Linux

**Comment by SoCalBeachrunner** [comment]
Still happening in ATOM 1.25 x64 for Mac. 

Basically, while a file was open in ATOM I renamed the file's containing folder and the file itself via Finder, then edited & saved it in vim. Returned to ATOM, saw and clicked ATOM's red Unhandled Exception dialog to arrive to this issue. The ATOM tab still displayed the old file name. Hovering over the tab continued to display the obsolete path and filename. To survive this sort of abuse, ATOM needs to gracefully handle name changes in addition to file access/write operations by another app. ATOM did not crash and I saved the file just to see what would happen - ATOM recreated the folder and saved the file there with its old name. Nice, no work would have been lost. It's surprisingly robust considering the hoops I put it through.

**Comment by boriel** [comment]
Same here. It happened when I moved a file from cmdline while ATOM had it open for editing (.BAS file) O:)

**Comment by TallOrderDev** [comment]
Still alive Atom 1.27.2, Mac.  Effects were same as many above. All JS files.
