### ISSUE TITLE
Not starting: TypeError: Cannot read property 'fromFetchhead' of undefined

### ISSUE THREAD

**Issue by mkoskar** [atom/atom#11485]
### Description

Atom doesn't start properly providing Chrome's development tools instead.
STDOUT/ERR output follows:

```
[32209:0415/171027:ERROR:browser_main_loop.cc(203)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[32209:0415/171027:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[32209:0415/171027:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[32209:0415/171027:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[32209:0415/171027:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
App load time: 588ms
[32209:0415/171028:INFO:CONSOLE(62)] "TypeError: Cannot read property 'fromFetchhead' of undefined
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/nodegit/lib/nodegit.js:25:54)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/git-repository-async.js:25:16)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/git-repository.js:12:24)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/git-repository.js:428:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/git-repository-provider.js:8:19)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/git-repository-provider.js:83:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)", source: file:///usr/share/atom/resources/app.asar/static/index.js (62)
[32209:0415/171029:WARNING:CONSOLE(0)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.", source:  (0)
```

### Steps to Reproduce

    $ atom --safe -f

### Versions

    1.7.1

I've tried all binary releases downwards and **first that worked** was `1.5.4`.

```
$ atom --version
Atom    : 1.7.1
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

$ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.8.0
```

**Comment by AndrewKvalheim** [comment]
A screenshot in case it's useful:

![screenshot from 2016-04-27 19-19-57](https://cloud.githubusercontent.com/assets/1844746/14873666/bba3aaea-0cad-11e6-93e9-fad60926d1e3.png)

```console
$ atom --version
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
$ lsb_release --description
Description:    Ubuntu 16.04 LTS
```

**Comment by joshaber** [comment]
I can't reproduce this, and we don't call `fromFetchhead` anywhere that I can find.

**Comment by mkoskar** [comment]
Error is coming from `nodegit` itself, line `25` fails because `_AnnotatedCommit` is `undefined`.

```
 20 // Native methods do not return an identifiable function, so we                     
 21 // have to override them here                                                       
 22 /* jshint ignore:start */                                                           
 23 var _AnnotatedCommit = rawApi.AnnotatedCommit;                                      
 24                                                                                     
 25 var _AnnotatedCommit_fromFetchhead = _AnnotatedCommit.fromFetchhead;                
 26 _AnnotatedCommit.fromFetchhead = promisify(_AnnotatedCommit_fromFetchhead);         
```

**Comment by mkoskar** [comment]
Ok, so concentrating on `nodegit` which was clearly culprit here I went through the environment and realized that I have `LD_PRELOAD=/usr/lib/libstderred.so` set. It does `STDERR` coloring. So far I haven't had any issue with it and to be honest forgot about it. Removing it made `nodegit` and hence `atom` work again. I should have realized this earlier. Sorry about that.

Closing.

**Comment by joshaber** [comment]
Wow, nice detective work. Thanks for digging in, @mkoskar!
