### ISSUE TITLE
[linux] Atom 1.7.x fails on startup

### ISSUE THREAD

**Issue by michael-k** [atom/atom#11482]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

When starting atom (does not matter if with `atom` or with `atom --safe`) I get the following error message:
```
index.js:62
Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:170:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/…/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/…/share/atom/resources/app.asar/node_modules/nodegit/lib/nodegit.js:9:12)
    at Module._compile (/…/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/…/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/…/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/…/share/atom/resources/app.asar/src/git-repository-async.js:25:16)
    at Module._compile (/…/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/…/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/…/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/…/share/atom/resources/app.asar/src/git-repository.js:12:24)
    at Object.<anonymous> (/…/share/atom/resources/app.asar/src/git-repository.js:428:4)
    at Module._compile (/…/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/…/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/…/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
```

### Steps to Reproduce

1. Build atom:
    ```
    $ git fetch -p --all
    $ git checkout $(git tag --sort="version:refname" | grep -v -E "alpha|beta" | tail -n 1)
    $ script/build
    $ script/grunt install --install-dir /…/atom-install
    $ /…/atom-install/bin/apm update
    ```
    (/…/atom-install/ is empty before starting grunt)

2. Remove atom config from home:
    ```
    mv ~/.atom ~/.atom-backup
    ```

3. Start atom:
    ```
    atom --safe
    ```

4. Clean 
    ```
    rm -rf /…/atom-install/*
    ```

5. Repeat steps 1. to 3., but now checkout version 1.6.2 in step 1. → Atom starts as expected.

**Expected behavior:** Atom starts like in versions <= 1.6.x

**Actual behavior:** See Description (fails since 1.7.0)

### Versions

I'm running on Debian Stretch aka testing.  Here is some more detailed information:
```
$ atom --version
Atom    : 1.7.1
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

$ apm --version
apm  1.9.2                                                                                  
npm  2.13.3
node 0.10.40
python 3.5.1+
git 2.8.0.rc3

$ uname -a
Linux x250 4.4.0-1-amd64 #1 SMP Debian 4.4.6-1 (2016-03-17) x86_64 GNU/Linux
```

**Comment by 50Wliu** [comment]
Try `script/clean && script/build`.  Does that work?

**Comment by michael-k** [comment]
That worked.  Should have thought of cleaning the source repo, not just the install target, myself. Thanks!

**Comment by michael-k** [comment]
Btw. `script/clean` is not mentioned in [docs/build-instructions/linux.md](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md)
