### ISSUE TITLE
Atom 1.7.1 (since 1.5 or something): "Failed to activate the ConvertToUtf8Plus package"

### ISSUE THREAD

**Issue by actcontpr** [atom/atom#11512]
Red warning sign on launch from a mint 1.7.1 install (Mac OS X Yosemite, same problem was on Mavericks aswell): "Failed to activate the ConvertToUtf8Plus package"

This Problem persists for half a year now. Creating an issue for the package leads to a 404 on Github.
Perhaps fix the link to the packages Tracker first thing? ... Just sayin'. :-)

Error Dump:
```
TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/pr/.atom/packages/ConvertToUtf8Plus/lib/convert-to-utf8.coffee:14:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28
```

**Comment by 50Wliu** [comment]
The 404 is happening because the package's repo disabled issue creation.  As it hasn't been updated since November 7, **2014**, I would highly suggest uninstalling this and finding a different package.
