### ISSUE TITLE
Atom linux build from source 1.7.2 fails to run after build , having module mismatch.

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#11565]
Atom fails  to run, after building on Gentoo(Sabayon) Linux . 
Node: v5.8.0
npm: v2.13.3

``` 
Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:170:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/home/v3ss/github/atom-master-clean/atom-build/Atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/v3ss/github/atom-master-clean/atom-build/Atom/resources/app.asar/node_modules/nodegit/lib/nodegit.js:9:12)
    at Module._compile (/home/v3ss/github/atom-master-clean/atom-build/Atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/home/v3ss/github/atom-master-clean/atom-build/Atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/home/v3ss/github/atom-master-clean/atom-build/Atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/v3ss/github/atom-master-clean/atom-build/Atom/resources/app.asar/src/git-repository-async.js:25:16)
    at Module._compile (/home/v3ss/github/atom-master-clean/atom-build/Atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/home/v3ss/github/atom-master-clean/atom-build/Atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/home/v3ss/github/atom-master-clean/atom-build/Atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/v3ss/github/atom-master-clean/atom-build/Atom/resources/app.asar/src/git-repository.js:12:24)
    at Object.<anonymous> (/home/v3ss/github/atom-master-clean/atom-build/Atom/resources/app.asar/src/git-repository.js:428:4)
    at Module._compile (/home/v3ss/github/atom-master-clean/atom-build/Atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/home/v3ss/github/atom-master-clean/atom-build/Atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/home/v3ss/github/atom-master-clean/atom-build/Atom/resources/app.asar/src/native-compile-cache.js:50:27)handleSetupError @ index.js:62
```

**Comment by lee-dohm** [comment]
This can be resolved by running `script/clean` and `rm -rf node_modules` from the root of the Atom repository before building again.

**Comment by v3ss0n** [comment]
Thanks , i forgot that there is script/clean.
Should we add that into build instructions?

**Comment by lee-dohm** [comment]
I think it could be better documented, though I'm not sure it belongs in the build instructions. Maybe in the intro to the build documentation in the README.
