### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by supaiku-o** [atom/atom#11595]
Steps to reproduce:
No idea.

**Atom Version**: 1.7.2
**System**: linux 4.5.1-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as isFullScreen] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at ApplicationDelegate.module.exports.ApplicationDelegate.isWindowFullScreen (/usr/share/atom/resources/app.asar/src/application-delegate.js:103:40)
    at AtomEnvironment.module.exports.AtomEnvironment.isFullScreen (/usr/share/atom/resources/app.asar/src/atom-environment.js:588:39)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:775:26)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:984:27
```

### Commands

```
     -1:33.4.0 core:copy (atom-text-editor.editor.is-focused)
     -1:31.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:28.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:28.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -1:26.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  7x -1:26 core:page-down (atom-text-editor.editor.is-focused)
     -1:24.8.0 core:page-up (atom-text-editor.editor.is-focused)
  5x -1:24.3.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -1:23.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:22.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  5x -1:22.6.0 core:move-down (atom-text-editor.editor.is-focused)
  5x -1:21.6.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:17.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:01.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:01.7.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "spell-check"
    ]
  },
  "editor": {
    "fontFamily": "Source Code Pro",
    "fontSize": 15,
    "invisibles": {},
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.6
language-qml, v1.0.0
language-qtpro, v0.6.0
minimap, v4.22.1
release-notes, v0.53.0
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Closing in favor of #11692.
