### ISSUE TITLE
Uncaught TypeError: Header name must be a valid HTTP Token ["    "banddata""]

### ISSUE THREAD

**Issue by rayk** [atom/atom#11687]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Header name must be a valid HTTP Token ["    "banddata""]

```
At _http_outgoing.js:337

TypeError: Header name must be a valid HTTP Token ["    "banddata""]
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:337:11)
    at new ClientRequest (_http_client.js:86:14)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:173:15)
    at Request.start (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/node_modules/request/request.js:708:30)
    at Request.write (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/node_modules/request/request.js:1400:28)
    at end (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/node_modules/request/request.js:423:18)
    at /opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/node_modules/request/request.js:447:9
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
     -1:59.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:59.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:58.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:55.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:54.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:51.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:51.3.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -1:50.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:47.5.0 core:move-right (atom-text-editor.editor.is-focused)
  7x -1:47 core:backspace (atom-text-editor.editor.is-focused)
     -1:29 core:move-right (atom-text-editor.editor.is-focused)
     -1:26.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:19.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:11.7.0 core:copy (atom-text-editor.editor.is-focused)
  2x -1:08.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-firewatch-syntax.theme-atom-dark-ui)
  2x -1:04.0 core:paste (textarea.field.rest-client-payload)
```

### Config

```json
{
  "core": {
    "followSymlinks": false,
    "themes": [
      "atom-dark-ui",
      "firewatch-syntax"
    ]
  },
  "editor": {
    "fontFamily": "Source Code Pro for PowerLine",
    "fontSize": 13,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-toolbar, v0.1.6
dartlang, v0.6.13
file-icons, v1.7.8
firewatch-syntax, v1.0.1
flutter, v0.2.2
highlight-selected, v0.11.2
linter, v1.11.4
linter-dartanalyzer, v0.3.2
pretty-json, v1.0.3
rest-client, v1.1.0
synced-sidebar, v0.4.3
tablr, v1.2.3
tool-bar, v0.4.0
tool-bar-main, v0.0.9
wakatime, v5.0.8

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
This looks like an issue with https://github.com/ddavison/rest-client – mind reopening this there?
