### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by denysvitali** [atom/atom#11700]
Fired randomly today, don't really know why and cannot reproduce unfortunately
I was writing this string: `const sprintf = require('sprintf-js').sprintf;` and saved, probably my JS linter caused the editor to throw an error.

**Atom Version**: 1.7.3
**System**: linux 4.5.1-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as isFullScreen] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at ApplicationDelegate.module.exports.ApplicationDelegate.isWindowFullScreen (/usr/share/atom/resources/app.asar/src/application-delegate.js:103:40)
    at AtomEnvironment.module.exports.AtomEnvironment.isFullScreen (/usr/share/atom/resources/app.asar/src/atom-environment.js:588:39)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:775:26)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:984:27
```

### Commands

```
     -2:42.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:42.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:42.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:42.5.0 editor:indent (atom-text-editor.editor.is-focused)
  4x -2:39.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:34.5.0 core:paste (atom-text-editor.editor.is-focused)
  2x -2:33.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:32.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:31.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:29.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:29.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:55.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:44.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:13.4.0 editor:newline (atom-text-editor.editor.is-focused)
  9x -0:11.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:03.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ]
  },
  "editor": {
    "fontSize": 13,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
Quick-JavaScript, v0.15.0
atom-beautify, v0.29.7
atom-jade, v0.3.0
javascript-snippets, v1.2.1
jshint, v1.8.5
markdown-preview-plus, v2.4.0

# Dev
No dev packages
```

**Comment by denysvitali** [comment]
Nevermind, #11692 is the same issue as mine. Closing
