### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'add' on 'DOMTokenList': The token provided must not be e...

### ISSUE THREAD

**Issue by KurtRMueller** [atom/atom#11707]
[Enter steps to reproduce below:]
1. I copied and pasted a group a list of values from excel.
2. I was using `CMD-d`'s multiple cursors to format the list into Ruby syntax.

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core
### Stack Trace

Uncaught SyntaxError: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/highlights-component.js:64

Error: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
    at Error (native)
    at HighlightsComponent.module.exports.HighlightsComponent.updateHighlightNode (/Applications/Atom.app/Contents/Resources/app.asar/src/highlights-component.js:64:49)
    at HighlightsComponent.module.exports.HighlightsComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/highlights-component.js:44:14)
    at LinesTileComponent.module.exports.LinesTileComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/lines-tile-component.js:101:32)
    at LinesComponent.module.exports.TiledComponent.updateTileNodes (/Applications/Atom.app/Contents/Resources/app.asar/src/tiled-component.js:67:19)
    at LinesComponent.module.exports.TiledComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/tiled-component.js:30:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:244:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:221:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```
### Commands

```
     -0:29.3.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
 15x -0:28.7.0 core:select-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:26.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:26 core:paste (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:25.5.0 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:25.2.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:25 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:24.2.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:23.7.0 vim-mode:move-to-beginning-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:23.4.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
 14x -0:23 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:21.2.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:20.6.0 core:select-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 47x -0:19.9.0 find-and-replace:select-next (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:05.5.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:04.4.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "useReactEditor": true
  },
  "editor": {
    "fontSize": 15,
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.7
atom-pair, v2.0.10
ember-cli-helper, v0.9.0
ember-snippets, v1.4.0
ex-mode, v0.8.0
html2haml, v0.10.0
language-babel, vundefined
language-cfml, v0.12.0
language-cjsx, v0.3.0
language-docker, v1.1.6
language-elm, v1.3.4
language-ember-htmlbars, v0.3.0
language-emblem, v0.2.0
language-haml, v0.24.0
language-jade, v0.7.1
language-javascript-jsx, v0.3.7
language-puppet, v0.19.1
language-rspec, v0.5.0
linter, v1.11.4
linter-cflint, v0.9.2
linter-clojure, v1.1.2
linter-docker, v0.1.2
linter-ruby, v1.2.2
merge-conflicts, v1.4.2
react, v0.15.0
trailing-spaces, v0.3.2
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by KurtRMueller** [comment]
Unfortunately, this bug is a show stopper in Atom for this particular file. I can't edit the affected file but I still can edit other files in Atom.

**Comment by 50Wliu** [comment]
Can you reproduce this in safe mode (`atom --safe`)?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/11707#issuecomment-217548659. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
