### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by abe33** [atom/atom#11745]
This issue started to appear on master today (as far as I can tell), and was not occuring before so I guess it was introduced by a regression recently.

1. With pigments installed, open a big CSS/Less/Sass file (100+ lines)
2. Select a bug portion of text at the begin of the file (in my case it was around 20 lines, I found that below 5-6 lines the error started to occur randomly)
3. Try to cut/delete the selected code.

@as-cii Maybe it's me that is not doing things correctly given the recent change in the API, but since it was working before I think something must have changed in the TextEditorComponent/TxtEditorPresenter stuff.

**Atom Version**: 1.9.0-dev-e1a200a
**System**: Mac OS X 10.11.4
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.26.3

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:852

TypeError: Cannot read property 'id' of undefined
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLineNumbersState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:800:56)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateTilesState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:488:14)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:127:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:265:60)
    at TextEditorComponent.module.exports.TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:662:14)
    at atom-text-editor.TextEditorElement.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:336:29)
    at BackgroundRenderer.module.exports.RegionRenderer.createRegion (/Users/c.nehemie/.atom/packages/pigments/lib/renderers/region-renderer.coffee:78:39)
    at BackgroundRenderer.module.exports.RegionRenderer.renderRegions (/Users/c.nehemie/.atom/packages/pigments/lib/renderers/region-renderer.coffee:16:21)
    at BackgroundRenderer.module.exports.BackgroundRenderer.render (/Users/c.nehemie/.atom/packages/pigments/lib/renderers/background.coffee:11:16)
    at pigments-color-marker.ColorMarkerElement.render (/Users/c.nehemie/.atom/packages/pigments/lib/color-marker-element.coffee:66:45)
    at pigments-color-marker.ColorMarkerElement.checkScreenRange (/Users/c.nehemie/.atom/packages/pigments/lib/color-marker-element.coffee:89:8)
    at /Users/c.nehemie/.atom/packages/pigments/lib/color-buffer-element.coffee:56:16
    at Array.forEach (native)
    at /Users/c.nehemie/.atom/packages/pigments/lib/color-buffer-element.coffee:54:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:331:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at DisplayLayer.module.exports.DisplayLayer.bufferDidChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:397:27)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:711:27)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:621:12)
    at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:715:19)
    at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:586:37)
    at Selection.module.exports.Selection.backspace (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:511:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:951:26
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:967:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:847:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1384:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:961:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2359:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2325:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:959:19)
    at TextEditor.module.exports.TextEditor.backspace (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:950:19)
    at TextEditor.object.(anonymous function) [as backspace] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditor.commandRegistry.add.stopEventPropagationAndGroupUndo.core:backspace (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:420:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:661:34
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:847:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1384:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:660:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  4x -0:15.5.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:14.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:13.2.0 core:move-up (atom-text-editor.editor.is-focused)
  7x -0:12.9.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:11.6.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -0:10.5.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:09.5.0 core:backspace (atom-text-editor.editor.is-focused)
  7x -0:08.7.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:07.5.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:07.1.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -0:06.4.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:05.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.5.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:01.7.0 core:move-left (atom-text-editor.editor.is-focused)
  5x -0:01.3.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:00.4.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "coffee-lint",
      "emmet",
      "notebook",
      "rsense",
      "font-viewer",
      "react-minimap",
      "sample-minimap-plugin",
      "term2",
      "crosshairs",
      "enhanced-package-list",
      "themed-settings",
      "project-palette-finder",
      "atom-color-highlight",
      "view-tail-large-files",
      "minimap-color-highlight",
      "to-base64",
      "tree-view-open-files",
      "typewriter"
    ],
    "themes": [
      "one-dark-ui",
      "spacegray-dark-syntax"
    ]
  },
  "pigments": {
    "ignoredNames": [
      "node_modules/*"
    ],
    "ignoredScopes": [
      "\\.comment",
      "\\.source\\.gfm",
      "\\.scss.*\\.string"
    ],
    "mergeColorDuplicates": true
  }
}
```

### Installed Packages

```coffee
# User
about, v1.5.2 (active)
atom-color-highlight, v3.0.9 (inactive)
atom-eco, v0.2.0 (active)
bezier-curve-editor, v0.7.2 (active)
block-travel, v1.0.4 (active)
bug-report, v0.7.1 (active)
clipboard-plus, v0.5.1 (active)
color-picker, v2.1.1 (active)
docblockr, v0.7.3 (active)
enhanced-package-list, v1.0.3 (inactive)
expose, v0.11.1 (inactive)
figlet, v0.5.3 (active)
highlight-selected, v0.11.2 (active)
language-elixir, v0.12.3 (active)
language-elm, v1.3.4 (active)
language-generic-config, v1.1.0 (active)
language-haml, v0.24.0 (active)
language-haskell, v1.7.15 (active)
language-jade, v0.7.1 (active)
language-sass, v0.51.1 (active)
linter, v1.11.4 (active)
linter-js-standard, v3.3.2 (active)
minimap, v4.23.5 (active)
minimap-bookmarks, v0.3.1 (active)
minimap-codeglance, v0.4.5 (active)
minimap-color-highlight, v4.1.4 (inactive)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.1.1 (active)
minimap-pigments, v0.2.1 (active)
minimap-selection, v4.4.0 (active)
php-twig, v4.0.0 (active)
pigments, v0.26.3 (active)
process-palette, v0.8.1 (active)
project-manager, v2.9.7 (active)
project-palette-finder, v2.4.17 (inactive)
red-wavy-underline, v0.3.0 (active)
sort-lines, v0.14.0 (inactive)
spacegray-dark-syntax, v0.2.0 (active)
spacegray-dark-ui, v0.12.0 (inactive)
Stylus, v3.0.0 (active)
tabasco, v0.5.0 (active)
tablr, v1.3.0 (active)
tabs-to-spaces, v1.0.2 (active)
test-syntax, v2.4.0 (inactive)
themed-settings, v1.0.1 (inactive)
to-base64, v0.4.2 (inactive)
toggle-quotes, v1.0.0 (active)
travis-ci-status, v1.0.0 (active)
tree-view-breadcrumb, v0.8.1 (active)
tree-view-open-files, v0.3.0 (inactive)
twilight-syntax-spacegray-ui, v0.4.0 (inactive)
typewriter, v0.3.5 (inactive)
unfancy-file-icons, v0.6.0 (active)
white-cursor, v0.6.0 (active)
Zen, v0.16.4 (inactive)
zentabs, v0.8.7 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.1 (active)
one-light-ui, v1.3.1 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.30.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.57.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.0 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.236.1 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.2.6 (active)
styleguide, v0.45.2 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.93.2 (active)
timecop, v0.33.1 (active)
tree-view, v0.206.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.51.5 (active)
language-clojure, v0.20.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.1 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.18.0 (active)
language-javascript, v0.110.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.0 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.43.2 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.51.1 (active)
language-shellscript, v0.22.2 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.27.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.6 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by alice-em** [comment]
+1

This bug is interfering with a few packages I have.

**Comment by as-cii** [comment]
Thanks @abe33 and @alice-em for the report! This is most likely a regression, but from a quick glance it might not be related to the `DisplayLayer`, but rather to an issue with how we decide which lines to render in `TextEditorPresenter` (that piece of code changed in order to support and integrate the new spatial mapping).

I'll take a more detailed look at this on Monday, thanks! ✨
