### ISSUE TITLE
On windows can't save, when saving open file crash 

### ISSUE THREAD

**Issue by goelmo** [atom/atom#11764]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Microsoft Windows 10 Pro
**Thrown From**: [url-utils](https://github.com/danielbayley/atom-url-utils) package, v0.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'some' of undefined

```
At C:\Users\HaHa\AppData\Local\atom\app-1.0.15\resources\app.asar\src\pane.js:809

TypeError: Cannot read property 'some' of undefined
    at C:\Users\HaHa\.atom\packages\url-utils\index.coffee:39:29
    at Emitter.module.exports.Emitter.emit (C:\Users\HaHa\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\HaHa\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1010:20)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\HaHa\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1002:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\HaHa\AppData\Local\atom\app-1.0.15\resources\app.asar\src\text-editor.js:584:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\HaHa\AppData\Local\atom\app-1.0.15\resources\app.asar\src\pane.js:547:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\HaHa\AppData\Local\atom\app-1.0.15\resources\app.asar\src\pane.js:530:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\HaHa\AppData\Local\atom\app-1.0.15\resources\app.asar\src\workspace.js:609:35)
    at atom-workspace.atom.commands.add.core:save (C:\Users\HaHa\AppData\Local\atom\app-1.0.15\resources\app.asar\src\workspace-element.js:293:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\HaHa\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:245:29)
```

### Commands

```
     -2:37 core:paste (atom-text-editor.editor.is-focused)
  2x -2:25.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "wombat-light-syntax"
    ],
    "disabledPackages": [
      "atom-python-test",
      "autocomplete-python",
      "python-debugger",
      "python-indent",
      "python-tools"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-formatter-jsbeautify, v1.1.2
esformatter, v1.25.0
formatter-jsbeautify, v1.0.2
jsformat, v0.9.3
url-utils, v0.1.1
wombat-light-syntax, v1.1.0

# Dev
No dev packages
```

**Comment by damieng** [comment]
The latest version of Atom is 1.7.3 - can you try this version.  1.0.15 is very old.

**Comment by 50Wliu** [comment]
In addition, this exception was not because of Atom - the culprit is actually the url-utils package, so closing.
