### ISSUE TITLE
Uncaught Error: Cannot read property 'isFullScreen' of undefined

### ISSUE THREAD

**Issue by pleonex** [atom/atom#11774]
After running Atom for some hours, suddenly I see all the time this error message.

**Atom Version**: 1.8.0-beta3
**System**: "Fedora release
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'isFullScreen' of undefined
TypeError: Cannot read property 'isFullScreen' of undefined
    at EventEmitter.<anonymous> (/usr/local/share/atom-beta/resources/atom.asar/browser/lib/rpc-server.js:295:35)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/local/share/atom-beta/resources/atom.asar/browser/api/lib/web-contents.js:133:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/local/share/atom-beta/resources/atom.asar/renderer/api/lib/remote.js:113

Error: Cannot read property 'isFullScreen' of undefined
TypeError: Cannot read property 'isFullScreen' of undefined
    at EventEmitter.<anonymous> (/usr/local/share/atom-beta/resources/atom.asar/browser/lib/rpc-server.js:295:35)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/local/share/atom-beta/resources/atom.asar/browser/api/lib/web-contents.js:133:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/local/share/atom-beta/resources/atom.asar/renderer/api/lib/remote.js:113:13)
    at BrowserWindow.RemoteMemberFunction [as isFullScreen] (/usr/local/share/atom-beta/resources/atom.asar/renderer/api/lib/remote.js:204:16)
    at ApplicationDelegate.module.exports.ApplicationDelegate.isWindowFullScreen (/usr/local/share/atom-beta/resources/app.asar/src/application-delegate.js:103:40)
    at AtomEnvironment.module.exports.AtomEnvironment.isFullScreen (/usr/local/share/atom-beta/resources/app.asar/src/atom-environment.js:588:39)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/local/share/atom-beta/resources/app.asar/src/atom-environment.js:775:26)
    at /usr/local/share/atom-beta/resources/app.asar/src/atom-environment.js:984:27
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "rti-linter-code",
      "latex",
      "vim-mode",
      "linter-python-pep8",
      "nav-panel",
      "symbols-plus",
      "you-complete-me",
      "rainbow-tabs",
      "symbol-gen",
      "term3",
      "java-importer"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "genesis-ui",
      "genesis-syntax"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "fontSize": 13,
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "tabLength": 4,
    "tabType": "soft"
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
atom-cscope, v0.14.1
atom-gmail-checker, v0.12.1
autocomplete-clang, v0.9.3
autocomplete-python, v1.7.2
autocomplete-xml, v0.8.3
browser-plus, v0.0.60
docblockr, v0.7.3
file-icons, v1.7.11
genesis-syntax, v1.0.7
genesis-ui, v0.5.0
git-diff-details, v1.3.0
git-log, v0.4.1
highlight-selected, v0.11.2
hyperclick, v0.0.36
language-ada, v1.1.0
language-latex, v0.6.1
linter, v1.11.4
linter-alex, v2.0.0
linter-chktex, v1.3.0
linter-clang, v3.4.4
linter-javac, v1.9.1
linter-pep8, v1.3.0
linter-xmllint, v1.3.4
merge-conflicts, v1.4.2
minimap, v4.23.5
minimap-bookmarks, v0.3.1
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-selection, v4.4.0
package-cop, v0.2.10
package-sync, v1.1.0
pdf-view, v0.50.0
python-indent, v0.4.3
symbols-tree-view, v0.12.0
tool-bar, v0.4.0
tool-bar-almighty, v0.6.1

# Dev
autocomplete-xml, v0.8.3
```

**Comment by pleonex** [comment]
In case it helps, I am trying now to use the Full Screen mode but I can't, it doesn't work (I tried because it seems it's related but I wasn't using it when the error started to happen).

**Comment by 50Wliu** [comment]
This seems related to #11692, so I'm going to close this in favor of that one.
