### ISSUE TITLE
Error working with Gnome - Google Drive files

### ISSUE THREAD

**Issue by alvsanand** [atom/atom#11805]
[Enter steps to reproduce below:]
1. Install Ubuntu 16.04 with Gnome Desktop support (it also works with the [Unity version](http://www.webupd8.org/2016/03/use-gnome-318-google-drive-integration.html)).
2. Add Google account through gnome control center or `gnome-control-center online-accounts`. Then select to sync files.
3. Go to nautilus and select in the left panel your account
4. Select a file and try to open it (most of the times atom cannot open it and the process is blocked forever)
5. If atom opens, try to save the file.

**Atom Version**: 1.7.3
**System**: Ubuntu 16.04
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/run/user/1000/gvfs/0B_u4G3QlCSvVfmp2Snk0QUZjeXY5eFVDV09DYjNseHZpSlNJeVNScUhMQ2hyazRleWNZaVk'

```
At /opt/atom/resources/app.asar/src/pane.js:1002

Error: ENOENT: no such file or directory, open '/run/user/1000/gvfs/0B_u4G3QlCSvVfmp2Snk0QUZjeXY5eFVDV09DYjNseHZpSlNJeVNScUhMQ2hyazRleWNZaVk'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Object.fsPlus.writeFileSync (/opt/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/opt/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:282:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/opt/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:420:21)
    at File.module.exports.File.writeSync (/opt/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:377:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1099:19)
    at TextBuffer.module.exports.TextBuffer.save (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/opt/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/opt/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/opt/atom/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/opt/atom/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/opt/atom/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:36.4.0 core:undo (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:33.7.0 tree-view:toggle (atom-pane.pane.active)
  2x -0:17.5.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
highlight-selected, v0.11.2
open-recent, v5.0.0
pretty-json, v1.4.0

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
Do you have any steps to reproduce this problem?

**Comment by alvsanand** [comment]
Sure. Here it is what happens:

1. Install Ubuntu 16.04 with Gnome Desktop support (it also works with the [Unity version](http://www.webupd8.org/2016/03/use-gnome-318-google-drive-integration.html)).
2. Add Google account through gnome control center or `gnome-control-center online-accounts`. Then select to sync files.
3. Go to nautilus and select in the left panel your account
4. Select a file and try to open it (most of the times atom cannot open it and the process is blocked forever)
5. If atom opens, try to save the file.

For my small knowledge, I think atom does not work well [gvfs-google](https://wiki.gnome.org/Projects/gvfs) partitions.

**Comment by ferroao** [comment]
same happens to me

**Comment by 50Wliu** [comment]
👋 @alvsanand @ferroao can you please try updating to Atom 1.19.0 and see if the crash still happens? 1.19.0 includes some low-level changes that may have resolved this crash.
