### ISSUE TITLE
Switching between workspace on GNOME triggers sometimes Uncaught Error

### ISSUE THREAD

**Issue by louisbl** [atom/atom#11808]
1. Open Atom on a new Workspace in GNOME 3
2. Maximize Atom window
3. Switch to another workspace
4. Get back to Atom workspace
5. Sometimes it triggers this error

**Atom Version**: 1.7.3
**System**: linux 4.5.4-1-ARCH, GNOME 3.20.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as getPosition] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:626:29)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:660:36)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/usr/share/atom/resources/app.asar/src/window-event-handler.js:182:35)
    at /usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61
```

### Commands

```
     -2:44.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:44.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:42.7.0 core:save (atom-text-editor.editor.is-focused)
     -2:33.6.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -2:32.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:43.3.0 core:delete (atom-text-editor.editor.is-focused)
  2x -1:42.5.0 editor:move-line-up (atom-text-editor.editor.is-focused)
     -1:41.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:41.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:41.5.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -1:41.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:40.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:26.1.0 editor:duplicate-lines (atom-text-editor.editor.is-focused)
 11x -1:25.6.0 editor:move-line-down (atom-text-editor.editor.is-focused)
     -0:02.4.0 core:cut (atom-text-editor.editor.is-focused)
     -0:02.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "closeEmptyWindows": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "Remote-FTP",
      "spell-check"
    ],
    "packagesWithKeymapsDisabled": [
      "standard-formatter",
      "git-projects"
    ],
    "projectHome": "/home/louisbl/Dev",
    "themes": [
      "spacegray-eighties-ui",
      "base16-syntax"
    ]
  },
  "editor": {
    "fontFamily": "Input Mono Narrow",
    "fontSize": 16,
    "invisibles": {},
    "lineHeight": 1.2,
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "softWrapHangingIndent": 2
  }
}
```

### Installed Packages

```coffee
# User
atom-jinja2, v0.5.0
atom-ternjs, v0.14.1
autocomplete-modules, v1.4.1
base16-syntax, v1.7.0
docblockr, v0.7.3
esformatter, v1.25.0
file-icons, v1.7.12
highlight-line, v0.11.1
highlight-selected, v0.11.2
language-babel, v2.20.10
language-docker, v1.1.6
language-elixir, v0.12.3
language-glsl, v2.0.1
language-haxe, v0.4.3
language-vue, v0.12.0
linter, v1.11.4
linter-docker, v0.1.2
linter-elixirc, v1.1.8
linter-eslint, v7.2.2
linter-glsl, v2.0.2
linter-handlebars, v2.3.4
linter-js-yaml, v1.2.5
linter-jsonlint, v1.2.5
pigments, v0.26.3
pretty-json, v1.4.0
project-manager, v2.9.7
spacegray-eighties-ui, v1.2.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This seems similar enough to #11692 that I'm going to close this as a duplicate.  Thanks for the repro steps though!
