### ISSUE TITLE
directory.getRealPathSync is not a function

### ISSUE THREAD

**Issue by UziTech** [atom/atom#11832]
1. package calls atom.project.repositoryForDirectory()

**Atom Version**: 1.7.4
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: Atom Core

### Stack Trace

Context Git

```
At TypeError: directory.getRealPathSync is not a function
TypeError: directory.getRealPathSync is not a function
    at Project.module.exports.Project.repositoryForDirectory (C:\Users\tjbrix\AppData\Local\atom\app-1.7.4\resources\app.asar\src\project.js:169:36)
    at Object.refreshAtom (C:/Users/tjbrix/Documents/Projects/Github/context-git/lib/context-git.js:217:16)
    at C:/Users/tjbrix/Documents/Projects/Github/context-git/lib/context-git.js:116:10
    at process._tickCallback (node.js:392:9)

undefined
```

### Commands

```
     -1:16.1.0 context-git:commit (atom-text-editor.editor.power-mode.is-focused)
     -1:03.5.0 window:toggle-dev-tools (atom-text-editor.editor.power-mode)
     -0:23.9.0 context-git:commit (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "command-executor",
      "linter-tidy",
      "linter-csslint",
      "git-diff-details",
      "emmet-snippets-compatibility",
      "jsformat",
      "php-integrator-symbol-viewer",
      "semanticolor"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "git-time-machine",
      "atom-beautify",
      "sass-autocompile",
      "linter",
      "hyperclick",
      "git-control",
      "emmet",
      "git-diff-details",
      "keybinding-cheatsheet",
      "bottom-dock",
      "linter-manager",
      "php-cs-fixer",
      "split-diff",
      "activate-power-mode",
      "grammar-selector",
      "markdown-preview",
      "highlight-selected",
      "change-case"
    ]
  },
  "editor": {
    "autoIndentOnPaste": false,
    "fontSize": 12,
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "softTabs": false
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
atom-jasmine, v0.8.1
atomic-chrome, v0.3.0
auto-detect-indentation, v1.0.0
auto-indent, v0.5.0
autoclose-html, v0.23.0
autocomplete-html-entities, v0.1.0
autocomplete-json, v1.10.0
context-git, v0.2.1
cursor-history, v0.5.9
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.12
file-types, v0.5.1
flex-tool-bar, v0.10.0
highlight-selected, v0.11.2
hyperclick, v0.0.36
hyperclick-php, v0.2.1
hyperlink-hyperclick, v1.3.3
js-hyperclick, v1.4.2
language-babel, v2.22.0
language-batch, v0.3.3
language-ini, v1.16.0
line-diff-details, v1.3.5
line-ending-converter, v1.3.2
linter, v1.11.4
linter-coffeelint, v1.1.2
linter-eslint, v7.2.2
linter-htmlhint, v1.1.4
linter-js-yaml, v1.2.5
linter-markdown, v1.5.0
linter-phpcs, v1.4.0
linter-sass-lint, v1.5.0
merge-conflicts, v1.4.2
minimap, v4.24.0
minimap-bookmarks, v0.3.1
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-hide, v0.3.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.1
minimap-selection, v4.4.0
minimap-split-diff, v0.3.0
open_in_cmd, v0.6.1
php-debug, v0.2.3
php-integrator-annotations, v0.4.1
php-integrator-autocomplete-plus, v0.8.1
php-integrator-base, v0.9.3
php-integrator-call-tips, v0.2.4
php-integrator-linter, v0.3.0
php-integrator-navigation, v0.7.1
php-integrator-tooltips, v0.6.1
pigments, v0.26.3
platformio-ide-terminal, v2.0.10
process-palette, v0.8.1
project-manager, v2.9.7
react, v0.15.0
Remote-FTP, v0.8.3
rest-client, v1.1.0
sass-autocompile, v0.12.6
Sublime-Style-Column-Selection, v1.5.1
tabasco, v0.5.0
tabs-to-spaces, v1.0.2
text-manipulation, v0.6.0
tool-bar, v0.4.0
trailing-spaces, v0.3.2
tree-view-git-status, v0.2.3

# Dev
No dev packages
```

**Comment by UziTech** [comment]
my bad `repositoryForDirectory` requires a [Directory](https://atom.io/docs/api/v1.7.4/Directory) instead of a string
