### ISSUE TITLE
Uncaught TypeError: Illegal invocation

### ISSUE THREAD

**Issue by nobalmohan** [atom/atom#11845]
[Enter steps to reproduce below:]

**Atom Version**: 1.7.4
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Illegal invocation

```
At C:\Users\nobal\AppData\Local\atom\app-1.7.4\resources\app.asar\src\buffered-process.js:98

TypeError: Illegal invocation
    at Socket.<anonymous> (C:\Users\nobal\AppData\Local\atom\app-1.7.4\resources\app.asar\src\buffered-process.js:98:13)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -0:45.7.0 merge-conflicts:detect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jslint",
      "jshint"
    ]
  },
  "editor": {
    "fontSize": 18,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-beautify, v0.29.7
atom-jshint, v2.0.0
atom-react-native-autocomplete, v0.0.26
atom-react-native-css, v1.1.1
atom-typescript, v8.10.2
autocomplete-plus, v2.31.0
editorconfig, v1.4.1
file-icons, v1.7.12
language-javascript-jsx, v0.3.7
linter, v1.11.4
linter-csslint, v1.3.2
linter-eslint, v7.2.2
linter-jshint, v2.1.0
linter-tidy, v2.1.0
linter-tslint, v0.9.3
merge-conflicts, v1.4.3
nuclide-code-format, v0.0.22
nuclide-flow, v0.0.22
nuclide-installer, v0.0.22
nuclide-type-hint, v0.0.22
php-cs-fixer, v2.5.6
pigments, v0.27.0
react-es6-snippets, v0.3.0
solid-completions, v1.6.3

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @nobalmohan, what were you doing when this happened?

**Comment by nobalmohan** [comment]
I am using this plugin https://atom.io/packages/merge-conflicts, it happened after I resolved my merge conflict and saved the changes ( click of Stage button ).

**Comment by 50Wliu** [comment]
This issue was moved to smashwilson/merge-conflicts#238
