### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'contains' on 'DOMTokenList': The token provide...

### ISSUE THREAD

**Issue by smlombardi** [atom/atom#11850]
[Enter steps to reproduce below:]

1. Added new selector to scss file

**Atom Version**: 1.8.0-beta4
**System**: Mac OS X 10.11.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'contains' on 'DOMTokenList': The token provided ('pigments-gutter-marker in-selection') contains HTML space characters, which are not valid in tokens.

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/src/custom-gutter-component.js:99

Error: Failed to execute 'contains' on 'DOMTokenList': The token provided ('pigments-gutter-marker in-selection') contains HTML space characters, which are not valid in tokens.
    at Error (native)
    at CustomGutterComponent.module.exports.CustomGutterComponent.updateDecorationNode (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/custom-gutter-component.js:99:57)
    at CustomGutterComponent.module.exports.CustomGutterComponent.updateSync (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/custom-gutter-component.js:51:16)
    at GutterContainerComponent.module.exports.GutterContainerComponent.updateSync (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/gutter-container-component.js:79:25)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:234:39)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:221:9)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```

### Commands

```
     -2:11 core:backspace (atom-text-editor.editor.is-focused)
     -2:07.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:45 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:43.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:32.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:49 core:save (atom-text-editor.editor.is-focused)
     -0:26.9.0 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
     -0:23.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:22.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.9.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  2x -0:18.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:17.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:14.1.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -0:11.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:06.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.2.0 core:cut (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "preview-tabs",
      "autocomplete-snippets",
      "gulp-control",
      "deprecation-cop",
      "linter-markdown",
      "linter-jscs",
      "linter-jshint",
      "linter-js-standard",
      "autocomplete-paths",
      "livestyle-atom",
      "indent-guide-improved",
      "linter-htmlhint"
    ],
    "themes": [
      "one-dark-ui",
      "gruvbox-plus-syntax"
    ]
  },
  "editor": {
    "fontFamily": "OperatorMono-Light",
    "invisibles": {},
    "lineHeight": 1.7,
    "nonWordCharacters": "/\\\\()\\\"':,.;<>~!^

**Comment by 50Wliu** [comment]
This issue was moved to abe33/atom-pigments#193

**Comment by smlombardi** [comment]
Sorry, I just clicked "report issue" on the alert and it took me here.   ☺️

**Comment by 50Wliu** [comment]
No problem - we're still working on getting Notifications to always report the issue to the right repo :).
