### ISSUE TITLE
Atom opens with blank screen and Chrome developer tools

### ISSUE THREAD

**Issue by myou11** [atom/atom#11868]
* [ Y ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [ Y ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ Y ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ Y ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ Y ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ Y ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

OS: Windows 7
Atom: v1.7.4

I was using Atom just fine until today when I was messing around with my GitHub installation in my AppData folder. Then I go to open Atom and it doesn't display the workspace anymore. I have looked at various other threads with the blank screen problem, but mine seems to be different. I have pasted the error code that shows up in Atom when I open it.

Any help would be much appreciated, thanks!

```
Error: EPERM: operation not permitted, open 'C:\Users\***\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\imports.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Object.fsPlus.writeFileSync (C:\Users\***\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (C:\Users\***\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\less-cache\lib\less-cache.js:155:17)
    at LessCache.module.exports.LessCache.setImportPaths (C:\Users\***\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\less-cache\lib\less-cache.js:113:12)
    at new LessCache (C:\Users\***\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\less-cache\lib\less-cache.js:32:12)
    at new LessCompileCache (C:\Users\***\AppData\Local\atom\app-1.7.4\resources\app.asar\src\less-compile-cache.js:20:20)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\***\AppData\Local\atom\app-1.7.4\resources\app.asar\src\theme-manager.js:270:26)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (C:\Users\***\AppData\Local\atom\app-1.7.4\resources\app.asar\src\theme-manager.js:257:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (C:\Users\***\AppData\Local\atom\app-1.7.4\resources\app.asar\src\theme-manager.js:174:24)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (C:\Users\***\AppData\Local\atom\app-1.7.4\resources\app.asar\src\theme-manager.js:237:12)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (C:\Users\***\AppData\Local\atom\app-1.7.4\resources\app.asar\src\theme-manager.js:232:19)
    at new AtomEnvironment (C:\Users\***\AppData\Local\atom\app-1.7.4\resources\app.asar\src\atom-environment.js:269:19)
    at module.exports (C:\Users\***\AppData\Local\atom\app-1.7.4\resources\app.asar\src\initialize-application-window.js:23:19)
    at setupWindow (file:///C:/Users/***/AppData/Local/atom/app-1.7.4/resources/app.asar/static/index.js:87:12)
    at window.onload (file:///C:/Users/***/AppData/Local/atom/app-1.7.4/resources/app.asar/static/index.js:41:9)
```

**Comment by kmare** [comment]
Just got the very same problem. Simply updated a few modules/themes.

**Comment by myou11** [comment]
How do I update the modules and themes?

**Comment by kmare** [comment]
I'm sorry I wasn't clear. I simply meant that I updated a few modules/themes and THEN I got that problem.

**Comment by myou11** [comment]
Ahh, I see.

I think that I should also add that I am on Windows and using the latest version of Atom

**Comment by kmare** [comment]
I'm on linux (fedora) using atom 1.7.4. After removing the .atom directory it starts again a bit more normally (no dev tools) but I get the following error:

`Failed to activate the tree-view package
Path must be a string. Received undefined
Hide Stack Trace
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at Object.shouldAttach (/usr/lib64/atom/node_modules/tree-view/lib/main.js:114:23)
    at Object.activate (/usr/lib64/atom/node_modules/tree-view/lib/main.js:16:16)
    at Package.module.exports.Package.activateNow (/usr/lib64/atom/src/package.js:183:20)
    at /usr/lib64/atom/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/lib64/atom/src/package.js:92:15)
    at /usr/lib64/atom/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/lib64/atom/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib64/atom/src/package-manager.js:530:21)
    at /usr/lib64/atom/src/package-manager.js:511:29
    at Config.module.exports.Config.transactAsync (/usr/lib64/atom/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/lib64/atom/src/package-manager.js:506:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/lib64/atom/src/package-manager.js:489:46)
    at /usr/lib64/atom/src/atom-environment.js:754:28`

**Comment by 50Wliu** [comment]
If you remove the `%userprofile%\.atom\compile-cache` folder does that fix the issue?

**Comment by 50Wliu** [comment]
@kmare That's a weird error...can you try renaming your `.atom` directory to something like `.atom-backup` and see if that fixes your issue?

**Comment by kmare** [comment]
already did, but after removing the .atom directory completely, I get the error I mentioned above.
The original error I got in the beginning after the few updates (nothing major as far as I could tell) was:

`index.js:62 Error
  at new Parser (/usr/lib64/atom/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
  at LessCache.module.exports.LessCache.parseLess (/usr/lib64/atom/node_modules/less-cache/lib/less-cache.js:255:16)
  at LessCache.module.exports.LessCache.cssForFile (/usr/lib64/atom/node_modules/less-cache/lib/less-cache.js:286:20)
  at LessCache.module.exports.LessCache.readFileSync (/usr/lib64/atom/node_modules/less-cache/lib/less-cache.js:274:19)
  at LessCompileCache.module.exports.LessCompileCache.read (/usr/lib64/atom/src/less-compile-cache.js:36:25)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/usr/lib64/atom/src/theme-manager.js:281:33)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (/usr/lib64/atom/src/theme-manager.js:257:21)
  at ThemeManager.module.exports.ThemeManager.requireStylesheet (/usr/lib64/atom/src/theme-manager.js:174:24)
  at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (/usr/lib64/atom/src/theme-manager.js:237:12)
  at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (/usr/lib64/atom/src/theme-manager.js:232:19)
  at new AtomEnvironment (/usr/lib64/atom/src/atom-environment.js:269:19)
  at module.exports (/usr/lib64/atom/src/initialize-application-window.js:23:19)
  at setupWindow (file:///usr/lib64/atom/static/index.js:87:12)
  at window.onload (file:///usr/lib64/atom/static/index.js:41:9)
handleSetupError @ index.js:62`

**Comment by kmare** [comment]
List of packages I had installed:
`
atom-autocomplete-php       atom-material-ui  laravel-forms-bootstrap-snippets
atom-beautify               blade-snippets    laravel-snippets
atom-bootstrap3             color-picker      minimap
atom-material-syntax        file-icons        php-fmt
atom-material-syntax-dark   language-blade    threejs-snippets
atom-material-syntax-light  laravel`

**Comment by kmare** [comment]
I'm sorry, I just realized that's a different problem than the one OP reported. I'm so sorry for spamming! should I just delete my posts here?

**Comment by myou11** [comment]
For Windows, is the .atom folder @50Wliu mentioned, equivalent to the atom folder in User/***/Local/atom?

**Comment by myou11** [comment]
I think its fine to leave your posts here @kmare. If you want to open a new issue and post those, you can.

**Comment by kmare** [comment]
yeah, on linux the .atom folder is the same as User/***/Local/atom on windows. I'll leave my problem here for now unless someone needs me to move it elsewhere as I'm actually getting a blank screen and the chrome developer tools as you :-D

**Comment by 50Wliu** [comment]
@myou11 You should be able to paste in the directory that I typed out to get to your `.atom` folder.  The `%localappdata%/atom` folder **is not** equivalent to your `.atom` folder.

@kmare feel free to create a new issue :)

**Comment by myou11** [comment]
Thank you very much for that @50Wliu, deleting the compiling-cache folder seems to have worked!

**Comment by kmare** [comment]
I tracked my problem down and apparently it was a problem with a theme (material-ui). It's related to this problem. So no need to create a new issue.
https://github.com/atom-material/atom-material-ui/issues/268

Thank you anyway! and sorry again for the spamming :/

**Comment by myou11** [comment]
Glad you figured out the problem! I'm going to close this ticket now.

**Comment by latimeks** [comment]
Had the same issue, following the thread here. I went into my `Users` folder and removed the `.atom` directory. Rebooting it fixed the problem.
