### ISSUE TITLE
Uncaught Error: Invalid text decoration iterator position: (133, 122).Buffer row 133 has length ...

### ISSUE THREAD

**Issue by vegaskev** [atom/atom#11951]
[Enter steps to reproduce below:]

1. All I did was open my file from Transmit and the error appeared

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Invalid text decoration iterator position: (133, 122).
Buffer row 133 has length 733.

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1074

Error: Invalid text decoration iterator position: (133, 122).
Buffer row 133 has length 733.
    at DisplayLayer.module.exports.DisplayLayer.getScreenLines (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1074:19)
    at TextEditorPresenter.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1355:37)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLines (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1362:12)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:121:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:265:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:205:12)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:221:9)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-shade-ui",
      "gl-dark-syntax"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
adwaita-ui-dark, v0.1.2 (inactive)
aethusa, v1.0.0 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-ui, v1.2.10 (inactive)
atom-wordpress, v0.3.0 (active)
autocomplete-wordpress-hooks, v0.2.0 (active)
chrome-dark-syntax, v0.5.0 (inactive)
code-dark-ui, v0.6.0 (inactive)
cowabunga, v0.2.0 (inactive)
dark-flat-ui, v1.2.4 (inactive)
gl-dark-syntax, v2.2.0 (active)
glacier-dark-ui, v0.3.0 (inactive)
language-ejs, v0.2.0 (active)
newbound-dark-syntax, v1.0.1 (inactive)
northem-dark-atom-ui, v0.5.0 (inactive)
nucleus-dark-ui, v0.7.17 (inactive)
one-dark-shade-ui, v0.1.0 (active)
one-dark-vivid-syntax, v1.1.2 (inactive)
pacific-dark, v0.4.2 (inactive)
pink-fluffy-atom-dark-syntax, v1.0.0 (inactive)
snow-dark-material-syntax, v0.1.1 (inactive)
snow-dark-syntax, v0.1.1 (inactive)
spectrum-dark-syntax, v0.0.3 (inactive)
spring-dark-syntax, v0.0.4 (inactive)
titan-dark-syntax, v2.0.0 (inactive)
webbox-color, v0.5.9 (active)
wordpress-api, v1.2.2 (active)
wordpress-dictionary, v4.4.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by vegaskev** [comment]
For what it's worth, I get this about 5-10 times a day, pretty much every day since I posted this issue here on git

**Comment by 50Wliu** [comment]
@vegaskev Does it happen in safe mode (`atom --safe`)?

**Comment by lee-dohm** [comment]
I assume that this is related to https://github.com/atom/atom/issues/10271.

**Comment by 50Wliu** [comment]
Closing in favor of #12085 - feel free to subscribe there for updates.
