### ISSUE TITLE
field to load the my-package package

### ISSUE THREAD

**Issue by ming15** [atom/atom#12001]
when i open atom, it occurred . I pasted the exceptions.

```
Failed to load the my-package package
Cannot read property 'prototype' of undefined
Hide Stack Trace
TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (<anonymous>:1:17)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
    at /Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:743:28
The error was thrown from the my-package package.
Create issue on the my-package package
Close All
Uncaught TypeError: this.textEditor.displayBuffer.getMaxScrollTop is not a function
```

and

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.5
**Thrown From**: [my-package](https://github.com/atom/my-package) package, v0.0.0

### Stack Trace

Failed to load the my-package package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (<anonymous>:1:17)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
    at /Users/wangming/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:743:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.4
go-plus, v3.3.11
linter, v0.12.6
linter-javac, v0.1.4
minimap, v4.9.4
my-package, v0.0.0
project-manager, v1.15.10

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This is an issue with the package you are developing.
