### ISSUE TITLE
Uncaught Error: Can't create a backup file for C:\Users\Miguel\Dropbox\HKUST\curso2\week2\conFusi...

### ISSUE THREAD

**Issue by this-miguel** [atom/atom#12004]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: Can't create a backup file for C:\Users\Miguel\Dropbox\HKUST\curso2\week2\conFusion\index.html because files already exist at every candidate path.

```
At C:\Users\Miguel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:1002

Error: Can't create a backup file for C:\Users\Miguel\Dropbox\HKUST\curso2\week2\conFusion\index.html because files already exist at every candidate path.
    at TextBuffer.module.exports.TextBuffer.backUpFileContentsBeforeWriting (C:\Users\Miguel\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1169:17)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Miguel\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1096:31)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\Miguel\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\Miguel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\Miguel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\Miguel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Miguel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (C:\Users\Miguel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Miguel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Miguel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Miguel\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Miguel\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Miguel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\Miguel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
     -0:08.9.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "fontSize": 16,
    "invisibles": {},
    "scrollPastEnd": true,
    "showIndentGuide": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1
atom-bootstrap4, v1.4.0
atom-html-preview, v0.1.19
change-case, v0.6.0
color-picker, v2.1.1
emmet, v2.4.3
jshint, v1.8.5
minimap, v4.24.3
pigments, v0.29.1
preview-plus, v1.2.6

# Dev
No dev packages
```

**Comment by MiguelSalas1987** [comment]
I can't save the file
