### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/opt'

### ISSUE THREAD

**Issue by squishybanana04** [atom/atom#12025]
I'm sorry but I'm not sure how to reproduce it. I removed python2 which might have something to do with it, I also removed npm.

**Atom Version**: 1.8.0
**System**: linux 3.14.0
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/opt'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/opt'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:314:24)
    at toRealPath (module.js:113:13)
    at Function.Module._findPath (module.js:153:20)
    at Module._resolveFilename (module.js:336:25)
    at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/node_modules/cheerio/lib/parse.js:4:18)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
```

### Commands

```
     -7:42.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:41.8.0 core:save (atom-text-editor.editor.is-focused)
  6x -4:46 core:move-right (atom-text-editor.editor.is-focused)
     -4:43.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:39.3.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:30.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -0:23.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:19 core:move-left (atom-text-editor.editor.is-focused)
  7x -0:18.4.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:10.4.0 turbo-javascript:end-line-comma (atom-text-editor.editor.autocomplete-active.is-focused)
```

### Config

```json
{
  "editor": {
    "fontSize": 16,
    "showIndentGuide": true,
    "softWrap": true,
    "softWrapHangingIndent": 2,
    "tabLength": 4,
    "tabType": "hard"
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
Let us know if it reproduces.

**Comment by squishybanana04** [comment]
I think its something to do with running out of storage space. It turnes out my apt cache was 1gb, and because I'm running on a chromebook with crouton I only have 16gb. It's fixed now.

**Comment by lee-dohm** [comment]
Thanks for the update @squishybanana04. I'm glad to hear it is fixed for you.
