### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by trusktr** [atom/atom#12029]
[Enter steps to reproduce below:]

1. not sure

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of null

```
At /opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/block-decorations-component.js:111

TypeError: Cannot read property 'classList' of null
    at BlockDecorationsComponent.module.exports.BlockDecorationsComponent.updateBlockDecorationNode (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/block-decorations-component.js:111:44)
    at BlockDecorationsComponent.module.exports.BlockDecorationsComponent.updateSync (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/block-decorations-component.js:62:30)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:246:15)
    at /opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/view-registry.js:221:9)
    at /opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```

### Commands

```
  4x -2:14.7.0 blur (div.package-readme.native-key-bindings)
     -2:13.9.0 application:new-file (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -2:13.8.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:13.3.0 vim-mode:activate-blockwise-visual-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 16x -2:12.3.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -2:09.0 vim-mode:put-after (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -2:08.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -2:07.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:06.0 vim-mode:move-to-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -2:05.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -2:05.1.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:04.2.0 vim-mode:move-to-start-of-file (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:04.0 vim-mode:activate-linewise-visual-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:03.9.0 vim-mode:move-to-line (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -2:01.8.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
 36x -2:00.3.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "vim-mode-plus-move-to-symbols",
      "vim-mode-plus-move-selected-text",
      "vim-mode-plus-project-find-from-search",
      "todo-show",
      "language-yaml",
      "language-toml",
      "language-xml",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sql",
      "welcome",
      "archive-view",
      "vim-mode-plus-ex-mode",
      "vim-mode-plus",
      "pigments",
      "minimap-pigments"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "node_modules"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v1.1.0
autoclose-html, v0.23.0
bottom-dock, v0.4.4
clipboard-plus, v0.5.1
ex-mode, v0.10.0
ex-mode-sort, v1.0.0
file-icons, v1.7.14
floobits, v0.31.3
glsl-preview, v0.8.0
language-glsl, v2.0.1
linter, v1.11.8
linter-eslint, v7.2.2
minimap, v4.24.4
minimap-bookmarks, v0.3.1
minimap-codeglance, v0.4.5
minimap-cursorline, v0.2.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-linter, v1.1.1
minimap-split-diff, v0.3.1
nerd-treeview, v0.4.2
persistent-undo, v1.2.0
project-plus, v0.9.0
relative-numbers, v0.5.1
split-diff, v1.0.2
symbols-list, v2.3.0
term3, v0.22.1
terminal-plus, v0.14.5
todo-manager, v0.2.9
tool-bar, v0.4.0
tool-bar-main, v0.0.9
vim-mode, v0.65.1
vim-mode-clipboard-plus, v0.2.0
vim-mode-visual-block, v0.2.15
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
Has this problem reoccurred?

**Comment by trusktr** [comment]
@lee-dohm I'm not sure, I've been dismissing errors to get to work, as they don't ultimately prevent me from working. I'll pay attention, and if it says it's already been reported then I'll know and will update...

**Comment by RuralSpaceman** [comment]
I have just experienced this issue on my first use of the split-diff package, which I notice OP also had installed.  It also throws https://github.com/atom/atom/issues/11282

**Comment by Michael-Thibault** [comment]
Just like @RuralSpaceman , I'm getting these with split-diff, along with #12030. It would seem to be an issue with that package.

**Comment by 50Wliu** [comment]
Assuming that this only happens with split-diff, so please report this issue to that package.

**Comment by mda6** [comment]
It's not only with split-diff i just installed Hydrogen and i got this issue couple of times (i didn't catch some pattern yet)
