### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetTop' of null

### ISSUE THREAD

**Issue by trusktr** [atom/atom#12030]
[Enter steps to reproduce below:]

1. Not sure, but happened while using the diff view of split-diff v1.0.2. Same with https://github.com/atom/atom/issues/12029

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'offsetTop' of null

```
At /opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/block-decorations-component.js:82

TypeError: Cannot read property 'offsetTop' of null
    at BlockDecorationsComponent.module.exports.BlockDecorationsComponent.measureBlockDecorations (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/block-decorations-component.js:82:29)
    at TextEditorComponent.module.exports.TextEditorComponent.readAfterUpdateSync (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:274:73)
    at /opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/view-registry.js:225:9)
    at /opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```

### Commands

```
     -0:38.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  5x -0:38 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:36.5.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:35.8.0 vim-mode:move-to-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 13x -0:35.3.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 25x -0:34.2.0 vim-mode:scroll-half-screen-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  6x -0:26.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:19.2.0 vim-mode:scroll-half-screen-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:18.1.0 vim-mode:scroll-half-screen-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:16.3.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  9x -0:15.6.0 vim-mode:scroll-half-screen-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  8x -0:14.2.0 vim-mode:scroll-half-screen-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:12.8.0 vim-mode:scroll-half-screen-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:12.2.0 vim-mode:scroll-half-screen-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:11.5.0 vim-mode:scroll-half-screen-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:10.1.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "vim-mode-plus-move-to-symbols",
      "vim-mode-plus-move-selected-text",
      "vim-mode-plus-project-find-from-search",
      "todo-show",
      "language-yaml",
      "language-toml",
      "language-xml",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sql",
      "welcome",
      "archive-view",
      "vim-mode-plus-ex-mode",
      "vim-mode-plus",
      "pigments",
      "minimap-pigments"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "node_modules"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v1.1.0
autoclose-html, v0.23.0
bottom-dock, v0.4.4
clipboard-plus, v0.5.1
ex-mode, v0.10.0
ex-mode-sort, v1.0.0
file-icons, v1.7.14
floobits, v0.31.3
glsl-preview, v0.8.0
language-glsl, v2.0.1
linter, v1.11.8
linter-eslint, v7.2.2
minimap, v4.24.4
minimap-bookmarks, v0.3.1
minimap-codeglance, v0.4.5
minimap-cursorline, v0.2.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-linter, v1.1.1
minimap-split-diff, v0.3.1
nerd-treeview, v0.4.2
persistent-undo, v1.2.0
project-plus, v0.9.0
relative-numbers, v0.5.1
split-diff, v1.0.2
symbols-list, v2.3.0
term3, v0.22.1
terminal-plus, v0.14.5
todo-manager, v0.2.9
tool-bar, v0.4.0
tool-bar-main, v0.0.9
vim-mode, v0.65.1
vim-mode-clipboard-plus, v0.2.0
vim-mode-visual-block, v0.2.15
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
If this **only** happens while using split-diff it's probably a bug with that package.

**Comment by lee-dohm** [comment]
I agree. Let us know if this can be reproduced in Safe Mode and we'll be happy to reopen the Issue!

Thanks for reporting!

**Comment by nonameolsson** [comment]
I get this error also, but never in safe mode. Even though the error message says that this is likely a problem with Atom itself, I think it has something to do with plugins.
