### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parentElement' of null

### ISSUE THREAD

**Issue by tonybenoy** [atom/atom#12055]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.0-dev-3fd0d30
**Electron Version**: 0.37.8
**System**: linux 4.6.2-1-ARCH
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'parentElement' of null

```
At /usr/share/atom-git/resources/app.asar/src/lines-tile-component.js:282

TypeError: Cannot read property 'parentElement' of null
    at LinesTileComponent.module.exports.LinesTileComponent.buildLineNode (/usr/share/atom-git/resources/app.asar/src/lines-tile-component.js:282:42)
    at LinesTileComponent.module.exports.LinesTileComponent.updateLineNodes (/usr/share/atom-git/resources/app.asar/src/lines-tile-component.js:138:34)
    at LinesTileComponent.module.exports.LinesTileComponent.updateSync (/usr/share/atom-git/resources/app.asar/src/lines-tile-component.js:94:12)
    at LinesComponent.module.exports.TiledComponent.updateTileNodes (/usr/share/atom-git/resources/app.asar/src/tiled-component.js:67:19)
    at LinesComponent.module.exports.TiledComponent.updateSync (/usr/share/atom-git/resources/app.asar/src/tiled-component.js:30:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/usr/share/atom-git/resources/app.asar/src/text-editor-component.js:265:34)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/share/atom-git/resources/app.asar/src/text-editor-component.js:205:12)
    at /usr/share/atom-git/resources/app.asar/src/text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom-git/resources/app.asar/src/view-registry.js:221:9)
    at /usr/share/atom-git/resources/app.asar/src/view-registry.js:3:61
```
### Commands

```
     -1:34 core:save (atom-text-editor.editor.is-focused)
     -1:13.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:13 core:move-left (atom-text-editor.editor.is-focused)
     -1:11.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:11.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:09.5.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:09.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:06.1.0 core:move-down (atom-text-editor.editor.is-focused)
 27x -1:05.4.0 core:select-up (atom-text-editor.editor.is-focused)
  6x -0:58.5.0 core:select-down (atom-text-editor.editor.is-focused)
 50x -0:53.5.0 core:select-left (atom-text-editor.editor.is-focused)
  6x -0:51.1.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:49.9.0 core:select-down (atom-text-editor.editor.is-focused)
 28x -0:49.5.0 core:select-left (atom-text-editor.editor.is-focused)
  4x -0:47.7.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:45 core:copy (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.4.0 (active)
one-light-ui, v1.4.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about-arch, v1.5.18 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.200.0 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.1 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
notifications, v0.65.0 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.1 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.99.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.1 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.0 (active)
language-gfm2, v0.90.4 (active)
language-liquid, v0.5.1 (active)
language-git, v0.14.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.1 (active)
language-less, v0.29.4 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.1 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.6 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.55.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.22.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
Any indication of what you were doing at the time?

**Comment by tonybenoy** [comment]
Selecting multiple lines to edit

On 30 June 2016 at 02:06, Lee Dohm <notifications@github.com> wrote:

> Any indication of what you were doing at the time?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/atom/atom/issues/12055#issuecomment-229480055>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AIHFXfSWo-KEw3NPf9kUZUaHTe4g30YRks5qQtc3gaJpZM4I_aju>
> .
>



-- 
*Tony Benoy*

**Comment by nanovad** [comment]
I just got this same error, Atom's popup error message had a link to this issue - Same stack trace, but I was trying to roll up a Python class.

**Comment by albertstartup** [comment]
Happens when I try to "fold all"

**Comment by Jin-Whu** [comment]
@albertstartup ,same with you!

**Comment by albertstartup** [comment]
@Jin-Whu yes

"Fold All" was working before 1.9.0 update.

**Comment by 50Wliu** [comment]
Seems related to #10350.

**Comment by Scimonster** [comment]
I got this error when i opened the git diff using package git-plus@5.17.0.
