### ISSUE TITLE
Uncaught TypeError: Cannot read property 'selectRight' of undefined

### ISSUE THREAD

**Issue by hitobashira** [atom/atom#12051]
[Enter steps to reproduce below:]

same 12550

atom.commands.add 'atom-text-editor', 'custom:delete-one', ->
  editor = atom.workspace.getActiveTextEditor()
  editor.selectRight()
#  editor.selectLine()
  editor.cutSelectedText()

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'selectRight' of undefined

```
At /home/zish/.atom/init.coffee:19

TypeError: Cannot read property 'selectRight' of undefined
    at atom-text-editor.<anonymous> (/home/zish/.atom/init.coffee:19:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  8x -0:22.3.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:19.7.0 vz-char:vz-char-cut (atom-text-editor.editor.mini.is-focused)
     -0:07.8.0 atomic-emacs:kill-line (atom-text-editor.editor.mini.is-focused)
  4x -0:06.4.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:01.0 custom:cut-line2 (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "archive-view",
      "autoflow",
      "language-csharp",
      "language-gfm",
      "language-mustache",
      "language-objective-c",
      "language-sass",
      "language-sql",
      "language-toml",
      "language-yaml",
      "metrics",
      "text-pastry",
      "textmate-clipboard",
      "clip-history",
      "fuzzy-finder",
      "markdown-preview",
      "git-diff",
      "minimap-selection",
      "webbox-color",
      "joe-keybinds",
      "highlight-bad-chars",
      "bookmarks",
      "duplicate-line-or-selection",
      "autocomplete-bash-builtins",
      "atom-terminal",
      "emacs-core-keys",
      "remove-all-keybindings",
      "find-and-replace-fix",
      "revert-buffer",
      "command-executor",
      "smart-cutcopypaste",
      "copy-word",
      "copy-improved",
      "neon-cursor",
      "block-cursor",
      "maximize-panes",
      "reflow-japanese",
      "text-buffer",
      "paste-buffer",
      "atom-beautify",
      "run-command",
      "pigments"
    ],
    "followSymlinks": false,
    "packagesWithKeymapsDisabled": [
      "highlight-line",
      "disable-keybindings",
      "symbols-view",
      "atomic-emacs",
      "shell-it",
      "copy-word",
      "find-selection"
    ],
    "showInvisibles": true,
    "themes": [
      "kobalt-ui",
      "kobalt"
    ]
  },
  "editor": {
    "autoIndent": false,
    "backUpBeforeSaving": true,
    "confirmCheckoutHeadRevision": false,
    "fontFamily": "Ricty",
    "fontSize": 26,
    "invisibles": {
      "space": "⎕"
    },
    "lineHeight": 1.2,
    "nonWordCharacters": "/\\()\"':,.;<>~!$^%#

**Comment by lee-dohm** [comment]
Your sample code has a bug in it: `atom.workspace.getActiveTextEditor()` may return `undefined` when there is no active text editor. So unless you're seeing this in Atom somewhere without your custom code installed, this is the expected behavior.

If I'm misunderstanding something, please let me know and I'll reopen the Issue.

**Comment by hitobashira** [comment]
Thank you. I was hospitalized for emergency operation after this writing. Therefore, the reaction was delayed.
Again, I will think about this problem. Please tell me if you have a good, simple sample.
