### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/mhastie/.mackup.cfg'

### ISSUE THREAD

**Issue by inviqa-session** [atom/atom#12062]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.12
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/mhastie/.mackup.cfg'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

Error: ENOENT: no such file or directory, open '/Users/mhastie/.mackup.cfg'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:285:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:463:21)
    at File.module.exports.File.writeSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:380:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1099:19)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -5:18 core:paste (atom-text-editor.editor.is-focused)
  2x -5:11.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:52.9.0 core:paste (atom-text-editor.editor.is-focused)
  6x -1:50.2.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -1:32.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:32.2.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -1:32 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:19.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:18.1.0 core:close (atom-text-editor.editor.is-focused)
     -0:23 core:move-down (atom-text-editor.editor.is-focused)
     -0:15.4.0 core:paste (atom-text-editor.editor.is-focused)
     -0:14.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:06.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:03.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.1.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 15,
    "invisibles": {},
    "preferredLineLength": 250,
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
Any indication as to what you were doing at the time this happened?

**Comment by danielvoicu** [comment]
1. When trying to save a file located on a mounted SFTP drive, Atom throws this error. "Uncaught Error: ENOENT: no such file or directory, open ''[redacted]\header.phtml'"
2. This issue doesn't happen on local files.
3. The tool used for mounting the server as a SFTP drive is Mountain Duck 1.6.0 (4947)

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open ''[redacted]\header.phtml'

```
At /C:/projects/atom/out/app/src/pane.coffee:1030

Error: ENOENT: no such file or directory, open '[redacted]\header.phtml'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Object.fsPlus.writeFileSync ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:285:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:463:21)
    at File.module.exports.File.writeSync ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:380:12)
    at TextBuffer.module.exports.TextBuffer.saveAs ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1140:19)
    at TextBuffer.module.exports.TextBuffer.save ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1124:19)
    at TextEditor.module.exports.TextEditor.save ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\src\text-editor.js:866:26)
    at Pane.module.exports.Pane.saveItem ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\src\pane.js:738:18)
    at Pane.saveItem ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\src\pane.js:3:61)
    at Pane.module.exports.Pane.saveActiveItem ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\src\pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\src\workspace.js:694:35)
    at atom-workspace.commandRegistry.add.core:save ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\src\register-default-commands.js:220:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:260:29)
    at [redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\src\window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> ([redacted]\AppData\Local\atom\app-1.11.2\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -6:06.7.0 core:copy (atom-text-editor.editor.is-focused)
     -6:04.2.0 core:paste (atom-text-editor.editor.is-focused)
     -5:59.5.0 core:copy (atom-text-editor.editor.is-focused)
     -5:56.2.0 core:paste (atom-text-editor.editor.is-focused)
  4x -3:46.8.0 core:save (atom-text-editor.editor.is-focused)
     -2:48.4.0 core:copy (atom-text-editor.editor.is-focused)
     -2:47.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:46.9.0 core:paste (atom-text-editor.editor.is-focused)
     -2:34.3.0 core:copy (atom-text-editor.editor.is-focused)
     -2:31.1.0 core:paste (atom-text-editor.editor.is-focused)
     -2:04.8.0 core:copy (atom-text-editor.editor.is-focused)
     -2:03.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:03.2.0 core:paste (atom-text-editor.editor.is-focused)
     -1:56.7.0 core:copy (atom-text-editor.editor.is-focused)
     -1:52.1.0 core:paste (atom-text-editor.editor.is-focused)
  5x -1:46.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "sync-settings",
      "angularjs",
      "language-arduino",
      "language-rust",
      "preview-plus",
      "atom-html-preview",
      "build",
      "busy",
      "linter-rust",
      "racer",
      "tool-bar",
      "csslint",
      "emmet",
      "linter-tidy"
    ],
    "packagesWithKeymapsDisabled": [
      "language-babel"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "nucleus-dark-ui",
      "gruvbox-plus-syntax"
    ]
  },
  "editor": {
    "fontSize": 11,
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
adventurous-syntax, v0.2.0 (inactive)
angularjs, v0.3.5 (inactive)
ask-stack, v2.2.0 (inactive)
atom-beautify, v0.29.13 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-dark-fusion-syntax, v1.3.2 (inactive)
atom-gooey-syntax, v0.2.1 (inactive)
atom-html-preview, v0.1.22 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-minify, v0.7.5 (active)
atom-ternjs, v0.15.0 (active)
autoclose-html, v0.23.0 (active)
autocomplete-paths, v1.0.2 (active)
batman-syntax, v1.0.1 (inactive)
build, v0.65.0 (inactive)
busy, v0.7.0 (inactive)
code-peek, v1.4.12 (inactive)
color-picker, v2.2.2 (active)
compare-files, v0.8.0 (active)
csslint, v1.1.5 (inactive)
emmet, v2.4.3 (inactive)
file-icons, v1.7.22 (active)
firewatch-syntax, v1.0.1 (inactive)
genesis-syntax, v1.0.7 (inactive)
genesis-ui, v0.5.0 (inactive)
git-time-machine, v1.5.3 (inactive)
github-atom-dark-syntax, v0.2.0 (inactive)
gruvbox, v1.0.5 (inactive)
gruvbox-plus-syntax, v1.2.5 (active)
highlight-selected, v0.11.2 (active)
isotope-light-ui, v2.2.6 (inactive)
language-arduino, v0.4.1 (inactive)
language-babel, v2.45.0 (active)
language-rust, v0.4.8 (inactive)
linter, v1.11.18 (active)
linter-csslint, v1.3.3 (active)
linter-eslint, v8.0.0 (active)
linter-jshint, v3.0.1 (active)
linter-less, v2.6.0 (active)
linter-rust, v0.6.0 (inactive)
linter-sass-lint, v1.7.1 (active)
linter-tidy, v2.2.1 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.6 (active)
minimap-highlight-selected, v4.4.0 (active)
monokai-seti, v0.7.0 (inactive)
nucleus-dark-ui, v0.10.12 (active)
open-in-browser, v0.4.7 (inactive)
open-recent, v5.0.0 (active)
package-sync, v1.1.0 (active)
pigments, v0.37.0 (active)
preview, v0.17.0 (inactive)
preview-plus, v1.2.7 (inactive)
racer, v0.20.0 (inactive)
Remote-FTP, v0.9.0 (active)
seti-ui, v1.3.2 (inactive)
slack-ui, v0.7.0 (inactive)
smart-tab-name, v1.0.5 (active)
sync-settings, v0.7.2 (inactive)
todo-show, v1.7.0 (inactive)
tool-bar, v1.0.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```
