### ISSUE TITLE
Uncaught Error: Invalid text decoration iterator position

### ISSUE THREAD

**Issue by ozo2003** [atom/atom#12070]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.0-beta0
**System**: Ubuntu 14.04.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Invalid text decoration iterator position: (380, 114).
Buffer row 380 has length 162.

```
At /usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1074

Error: Invalid text decoration iterator position: (380, 114).
Buffer row 380 has length 162.
    at DisplayLayer.module.exports.DisplayLayer.getScreenLines (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1074:19)
    at TextEditorPresenter.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/text-editor-presenter.js:1355:37)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLines (/usr/share/atom-beta/resources/app.asar/src/text-editor-presenter.js:1362:12)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/usr/share/atom-beta/resources/app.asar/src/text-editor-presenter.js:121:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/usr/share/atom-beta/resources/app.asar/src/text-editor-component.js:265:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/share/atom-beta/resources/app.asar/src/text-editor-component.js:205:12)
    at /usr/share/atom-beta/resources/app.asar/src/text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom-beta/resources/app.asar/src/view-registry.js:221:9)
    at /usr/share/atom-beta/resources/app.asar/src/view-registry.js:3:61
```

### Commands

```
     -6:31.1.0 core:copy (atom-text-editor.editor.is-focused)
     -6:01.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -6:01.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:59.4.0 core:paste (atom-text-editor.editor.is-focused)
     -5:57.3.0 core:save (atom-text-editor.editor.is-focused)
     -5:25.1.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -5:24.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "file-type-icons",
      "file-icons",
      "archive-view",
      "background-tips",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-mustache",
      "language-objective-c",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-todo",
      "language-toml",
      "link",
      "metrics",
      "spell-check",
      "welcome",
      "tree-view-open-files",
      "color-picker",
      "docblockr",
      "hashrocket",
      "open-on-github",
      "styleguide",
      "php-debug"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "cache"
    ],
    "packagesWithKeymapsDisabled": [
      "tree-view-open-files",
      "opened-files",
      "pigments",
      "php-cs-fixer",
      "git-time-machine"
    ],
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  },
  "editor": {
    "fontSize": 11,
    "invisibles": {},
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true,
    "tabLength": 4,
    "tabType": "soft"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.9 (active)
autoclose-html, v0.23.0 (active)
autoprefixer, v3.2.0 (inactive)
color-picker, v2.1.1 (inactive)
docblockr, v0.7.3 (inactive)
emmet, v2.4.3 (active)
git-time-machine, v1.5.3 (inactive)
hashrocket, v0.4.10 (inactive)
highlight-selected, v0.11.2 (active)
language-smarty, v1.7.0 (active)
logo-file-icons, v1.1.6 (active)
opened-files, v0.3.6 (active)
php-cs-fixer, v2.5.6 (active)
php-twig, v4.0.0 (active)
pigments, v0.29.3 (active)
tabs-to-spaces, v1.0.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (active)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (active)
about, v1.5.2 (active)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (inactive)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
Any information you can share on what you were doing at the time?

**Comment by ozo2003** [comment]
trying to edit .php file, and this was only in one file. any other file was ok, just one file. everything above line 380 was perfectly fine but when i get to 380 it throws this exception and file becomes uneditable, unscrollable while editor itself is fine, all other files are perfectly editable

**Comment by lee-dohm** [comment]
Can you share the file that this reproduced in?

**Comment by ozo2003** [comment]
[BillGetTypeProcessorV2.php.zip](https://github.com/atom/atom/files/371153/BillGetTypeProcessorV2.php.zip)

**Comment by 50Wliu** [comment]
Closing in favor of #12085 - feel free to subscribe there for updates.
