### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/jasoncampbell/Downloads/Atom.app'

### ISSUE THREAD

**Issue by jasoncam** [atom/atom#12112]
[Enter steps to reproduce below:]

1. Open Program
2. Attempt to access Preferences

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/jasoncampbell/Downloads/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/jasoncampbell/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:314:24)
    at toRealPath (module.js:113:13)
    at Function.Module._findPath (module.js:153:20)
    at Module._resolveFilename (module.js:336:25)
    at Function.Module._resolveFilename (/Users/jasoncampbell/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Users/jasoncampbell/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jasoncampbell/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/jasoncampbell/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/jasoncampbell/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/jasoncampbell/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jasoncampbell/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/jasoncampbell/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/jasoncampbell/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/jasoncampbell/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jasoncampbell/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/jasoncampbell/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/jasoncampbell/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
It looks like you were executing Atom from the Downloads directory? Can you replicate this when Atom is being run from the `/Applications` directory?

**Comment by jasoncam** [comment]
All good now....guess I was too excited to open Atom on my new cpu. :)

Close this out!

On Wed, Jul 6, 2016 at 2:58 PM, Lee Dohm <notifications@github.com> wrote:

> It looks like you were executing Atom from the Downloads directory? Can
> you replicate this when Atom is being run from the /Applications
> directory?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/atom/atom/issues/12112#issuecomment-230919676>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ADuPrzt0M4_0Up2kmTZEx_55zbENz_99ks5qTCT2gaJpZM4JGYHW>
> .
>



-- 
Jason Campbell - Advertising + Technology + Strategic Partnerships

Green Wedding Shoes
greenweddingshoes.com <http://www.greenweddingshoes.com/>

facebook <http://facebook.com/greenweddingshoes> // pinterest
<http://www.pinterest.com/gws/> // instagram
<http://instagram.com/greenweddingshoes> // snapchat
<http://www.snapchat.com/add/grnweddingshoes> // twitter
<http://twitter.com/grnweddingshoes>

*Confidential: No part of this email may be shared, forwarded, blogged or
otherwise reproduced without express written permission from the sender.*

**Comment by lee-dohm** [comment]
Thanks for the update @jasoncam! Closing per request.

**Comment by Ben3eeE** [comment]
https://github.com/atom/atom/issues/10774?
