### ISSUE TITLE
Uncaught Error: EACCES: permission denied, open '/home/amorobert/Documents/DBC/Phase-1/Week_1/pig...

### ISSUE THREAD

**Issue by amorobert** [atom/atom#12128]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EACCES: permission denied, open '/home/amorobert/Documents/DBC/Phase-1/Week_1/pig-latin-challenge/pig_latin.rb'

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1108

Error: EACCES: permission denied, open '/home/amorobert/Documents/DBC/Phase-1/Week_1/pig-latin-challenge/pig_latin.rb'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:285:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:463:21)
    at File.module.exports.File.writeSync (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:380:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1099:19)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at /home/amorobert/.atom/init.coffee:16:14
    at /home/amorobert/.atom/init.coffee:14:5
    at CallbacksRegistry.apply (/usr/share/atom/resources/atom.asar/common/api/lib/callbacks-registry.js:58:39)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:236:28)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
     -9:49.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:44 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -9:44 snippets:expand (atom-text-editor.editor.is-focused)
     -9:44 editor:indent (atom-text-editor.editor.is-focused)
     -9:37.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -8:03.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:02.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -7:59.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -7:58.4.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v1.1.0
autoclose-html, v0.23.0
highlight-selected, v0.11.2
indent-guide-improved, v1.4.9
minimap, v4.24.7
minimap-highlight-selected, v4.4.0
open-recent, v5.0.0
pigments, v0.31.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
I think the error is pretty obvious, You tried to open a file in Atom that your user didn't have read permissions for, use `chmod` to fix the permissions and then retry opening the file

**Comment by 50Wliu** [comment]
Thanks @steelbrain.
