### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by HerCode** [atom/atom#12148]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, read

```
At fs.js:651

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:651:19)
    at Object.fs.readFileSync (fs.js:472:24)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:427:29)
    at File.module.exports.File.readSync (/Users/codeHer/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:269:36)
    at File.module.exports.File.getDigestSync (/Users/codeHer/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:170:14)
    at TextBuffer.module.exports.TextBuffer.serialize (/Users/codeHer/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:231:68)
    at /Users/codeHer/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:137:27
    at Array.map (native)
    at Project.module.exports.Project.serialize (/Users/codeHer/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:135:41)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/Users/codeHer/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:769:31)
    at /Users/codeHer/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:984:27
```
### Commands

```
     -8:50.1.0 window:save-all (atom-text-editor.editor.is-focused)
 22x -7:25.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -5:38.2.0 core:save (atom-text-editor.editor.is-focused)
     -4:51.5.0 core:save-as (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -3:47.5.0 tree-view:remove (span.name.icon.icon-file-directory)
     -2:39.4.0 core:save (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -2:27.4.0 core:save-as (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-jslint",
      "linter"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.9
file-icons, v1.7.16
jshint, v1.8.5
merge-conflicts, v1.4.4
minimap, v4.24.7
rest-client, v1.2.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
Any indication of what you were doing when you got this error?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/12148#issuecomment-231949968. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
