### ISSUE TITLE
Save of file truncated the file leaving it empty.

### ISSUE THREAD

**Issue by wraix** [atom/atom#12152]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Save of file truncated the file leaving it empty.
### Steps to Reproduce

Saving the file caused it to truncated it leaving the file empty.

I am editing a file mounted trough sshfs.

**Expected behavior:** [File gets save with content]

**Actual behavior:** [File got truncated]
### Error data reported by Atom. (Was unable to use build in submit feature, something about site not performing and a horse head. - copied it to clipboard before trying to create bug report.)

```
Error: EINVAL: invalid argument, write
    at Error (native)
    at Object.fs.writeSync (fs.js:706:20)
    at Object.fs.writeFileSync (fs.js:1244:24)
    at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:292:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:463:21)
    at File.module.exports.File.writeSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:380:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1099:19)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:46.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:41.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:40.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:39.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:33.2.0 core:move-right (atom-text-editor.editor.is-focused)
 11x -0:32.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:31 core:save (atom-text-editor.editor.is-focused)
  6x -0:30.3.0 core:move-down (atom-text-editor.editor.is-focused)
 11x -0:25.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:23.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.7.0 core:move-right (atom-text-editor.editor.is-focused)
 11x -0:06.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:04.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:02.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "fileEncoding": "iso88591"
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true,
    "tabType": "soft"
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.7.0
minimap, v4.24.7

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
* Which version of Atom were you using?
* What OS and version are you running?

**Comment by wraix** [comment]
Atom 1.8

osx 10.10.5 Yosemite

**Comment by iffy** [comment]
I think we may be running into this problem with files opened on a Samba share (from macOS).  I wish I could reproduce it :(  I'll see if I can.
