### ISSUE TITLE
Uncaught Error: EBADF: bad file descriptor, opening mounted folder

### ISSUE THREAD

**Issue by bitttttten** [atom/atom#12163]
This is thrown when I try and open a remote folder, mounted through Transmit, in Atom.

1. Mount a remote folder through SSH
1.b (I am using Transmit)
2. Open a directory from the mounted folder (in this case `/Volumes/mountedsite.com/domains/mountedsite.com/public_html/app`)
3. Atom hangs and throws this error

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EBADF: bad file descriptor, open '/Volumes/mountedsite.com/domains/mountedsite.com/public_html/app'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:522

Error: EBADF: bad file descriptor, open '/Volumes/mountedsite.com/domains/mountedsite.com/public_html/app'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Workspace.module.exports.Workspace.openTextFile (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:569:27)
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:496:23)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:424:19)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1125:19)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:244:18)
    at emitThree (events.js:102:20)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "terminal-plus",
      "tokamak-terminal",
      "platformio-ide-terminal"
    ],
    "themes": [
      "one-dark-ui",
      "fairyfloss"
    ]
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.4.3
fairyfloss, v0.2.0
language-babel, v2.31.0

# Dev
No dev packages
```

**Comment by bitttttten** [comment]
Fixed by using [FUSE for OS X](https://osxfuse.github.io/) and [SSHFS](https://github.com/osxfuse/sshfs) to mount the remote folder.
