### ISSUE TITLE
Uncaught TypeError: Cannot read property 'removeEventListener' of undefined

### ISSUE THREAD

**Issue by chrisjimallen** [atom/atom#12169]
1 - Opened Atom editor from CLI
2 - Clicked on a favicon.ico in tree view.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'removeEventListener' of undefined

```
At /Users/chrisallen/.atom/init.coffee:34

TypeError: Cannot read property 'removeEventListener' of undefined
    at /Users/chrisallen/.atom/init.coffee:34:25
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
     -8:50.5.0 core:save (atom-text-editor.editor.is-focused)
     -8:11.9.0 tree-view:copy-full-path (span.name.icon.icon-file-text)
     -6:10.6.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -6:10.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:10.5.0 core:paste (atom-text-editor.editor.is-focused)
     -5:59.9.0 core:copy (atom-text-editor.editor.is-focused)
  6x -5:48.4.0 core:undo (atom-text-editor.editor.is-focused)
     -5:43.8.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -5:43.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:43.4.0 core:paste (atom-text-editor.editor.is-focused)
     -5:42.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -5:39.8.0 core:save (atom-text-editor.editor.is-focused)
     -5:23.3.0 editor:duplicate-lines (atom-text-editor.editor.is-focused)
     -5:12.3.0 core:save (atom-text-editor.editor.is-focused)
     -4:21.5.0 core:paste (atom-text-editor.editor.is-focused)
  2x -4:20.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/chrisallen/Sites/",
    "themes": [
      "spacegray-dark-neue-ui",
      "base16-ocean-dark-spacegray"
    ]
  },
  "editor": {
    "fontFamily": "Hack",
    "scrollPastEnd": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
auto-update-packages, v1.0.1
base16-ocean-dark-spacegray, v0.12.0
custom-title, v1.0.1
docblockr, v0.7.3
emmet-simplified, v2.5.0
file-type-icons, v1.3.1
fonts, v1.5.0
google, v0.3.8
highlight-selected, v0.11.2
merge-conflicts, v1.4.4
spacegray-dark-neue-ui, v1.4.0
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This is an issue with the code in your custom `init.coffee` file.
