### ISSUE TITLE
double click around tabs space - editor crash after saving

### ISSUE THREAD

**Issue by camel-chased** [atom/atom#12174]
[Enter steps to reproduce below:]

1. double click on empty place around tabs to open new editor
2. write somethins
3. save it

**Atom Version**: 1.9.0-beta0
**System**: Microsoft Windows 8.1
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package, v1.2.23

### Stack Trace

Uncaught TypeError: Cannot read property 'text' of undefined

```
At C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\pane.js:1026

TypeError: Cannot read property 'text' of undefined
    at Object.module.exports.EditorBackground.drawLine (file:///C:/Users/neuronet/.atom/packages/editor-background/lib/editor-background.coffee:617:25)
    at Object.module.exports.EditorBackground.drawLines (file:///C:/Users/neuronet/.atom/packages/editor-background/lib/editor-background.coffee:732:16)
    at Object.module.exports.EditorBackground.drawBackground (file:///C:/Users/neuronet/.atom/packages/editor-background/lib/editor-background.coffee:793:18)
    at file:///C:/Users/neuronet/.atom/packages/editor-background/lib/editor-background.coffee:801:23
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\text-editor.js:334:32
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at DisplayLayer.module.exports.DisplayLayer.reset (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\text-buffer\lib\display-layer.js:228:20)
    at TextEditor.module.exports.TextEditor.resetDisplayLayer (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\text-editor.js:356:32)
    at TextEditor.module.exports.TextEditor.subscribeToScopedConfigSettings (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\text-editor.js:324:19)
    at C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\text-editor.js:3:61
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\tokenized-buffer.js:201:27)
    at TokenizedBuffer.module.exports.TokenizedBuffer.reloadGrammar (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\tokenized-buffer.js:211:21)
    at C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\tokenized-buffer.js:81:24
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.setPath (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:378:27)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1116:12)
    at TextEditor.module.exports.TextEditor.saveAs (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\text-editor.js:746:26)
    at Pane.module.exports.Pane.saveItemAs (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\pane.js:762:16)
    at Pane.saveItemAs (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\pane.js:3:61)
    at Pane.module.exports.Pane.saveItem (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\pane.js:746:21)
    at Pane.saveItem (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\pane.js:3:61)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\pane.js:717:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\workspace.js:690:35)
    at atom-workspace.commandRegistry.add.core:save (C:\Users\neuronet\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\register-default-commands.js:220:32)
```

### Commands

```
     -2:43.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:42.1.0 core:delete (atom-text-editor.editor.is-focused)
  3x -2:41.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:41.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -2:41.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -2:41.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:32.4.0 core:paste (atom-text-editor.editor.is-focused)
  3x -1:31.9.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -1:29.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:27.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
 11x -1:17.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:16 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:16 editor:newline (atom-text-editor.editor.is-focused)
     -1:15.7.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:18.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:17 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-csslint",
      "atom-typescript",
      "linter-tslint",
      "language-typescript-grammars-only",
      "sass-autocompile",
      "less-compiler",
      "linter-php"
    ],
    "packagesWithKeymapsDisabled": [
      "one-dark-ui"
    ],
    "themes": [
      "one-light-ui",
      "lazy-light-syntax"
    ]
  },
  "editor-background": {
    "blurRadius": 0,
    "box3d": {},
    "image": {
      "backgroundSize": "cover",
      "customOverlayColor": true,
      "opacity": 17,
      "overlayColor": {
        "red": 255,
        "green": 255,
        "blue": 255,
        "alpha": 1
      },
      "style": "background:radial-gradient(rgba(255,255,255,0) 30%,rgba(255,255,255,0.75));",
      "url": "C:/Users/neuronet/Pictures/porsche_991_carrera_s_vorsteiner_v_gt_aero_program-1920x1080.jpg"
    },
    "imageURL": "",
    "other": {
      "treeViewOpacity": 66
    },
    "text": {
      "blur": 8,
      "color": {
        "red": 255,
        "green": 255,
        "blue": 255,
        "alpha": 1
      },
      "expand": 10,
      "opacity": 74
    },
    "video": {
      "endTime": "21s",
      "opacity": 30,
      "youTubeURL": "https://youtu.be/TYdKWHpZZiA"
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-formatter-jsbeautify, v1.1.2 (active)
atom-typescript, v10.1.2 (inactive)
blade-snippets, v0.2.0 (inactive)
clipboard-plus, v0.5.1 (active)
docblockr, v0.7.3 (active)
editor-background, v1.2.23 (active)
file-icons, v1.7.17 (active)
formatter, v2.12.3 (active)
github-atom-light-syntax, v0.2.0 (inactive)
gl-light-syntax, v2.2.0 (inactive)
keyboard-localization, v1.4.18 (active)
language-ect, v0.4.0 (active)
language-smarty, v1.7.0 (active)
language-typescript-grammars-only, v1.5.0 (inactive)
lazy-light-syntax, v0.1.1 (active)
less-autocompile, v1.0.0 (active)
linter, v1.11.14 (active)
linter-csslint, v1.3.2 (inactive)
linter-jade, v0.3.2 (active)
linter-php, v1.2.0 (inactive)
linter-tidy, v2.1.1 (active)
linter-tslint, v0.10.0 (inactive)
minimap, v4.24.7 (active)
monokai, v0.18.0 (inactive)
monokai-dark, v1.3.0 (inactive)
monokai-seti, v0.7.0 (inactive)
monokai-slate, v0.5.0 (inactive)
navigation-history, v0.1.8 (active)
one-light-ui-adwaita, v0.10.1 (inactive)
pigments, v0.31.1 (active)
Remote-FTP, v0.8.3 (active)
sass-autocompile, v0.12.8 (inactive)
symbols-tree-view, v0.13.2 (active)
two-light-ui, v1.1.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (active)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by camel-chased** [comment]
sorry that is editor-background error :)
