### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [atom/atom#12181]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:121

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at MarkerLayer.module.exports.MarkerLayer.findMarkers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:121:20)
    at DisplayBuffer.module.exports.DisplayBuffer.findFoldMarkers (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1150:36)
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:803:29)
    at DisplayBuffer.module.exports.DisplayBuffer.screenRangeForBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:758:20)
    at TextEditorMarker.module.exports.TextEditorMarker.getScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:141:33)
    at DisplayBuffer.module.exports.DisplayBuffer.decorationsStateForScreenRowRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1026:32)
    at TextEditor.module.exports.TextEditor.decorationsStateForScreenRowRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1412:33)
    at TextEditorPresenter.module.exports.TextEditorPresenter.fetchDecorations (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1364:44)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:120:14)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:265:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:205:12)
    at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:304:21)
    at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:1028:16)
    at TextEditorComponent.module.exports.TextEditorComponent.pollDOM (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:1015:17)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61
    at ViewRegistry.module.exports.ViewRegistry.performDocumentPoll (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:265:9)
    at ViewRegistry.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:701:23)
    at ViewRegistry.module.exports.ViewRegistry.requestDocumentPoll (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:256:21)
    at MutationObserver.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "minimap",
      "seti-icons",
      "close-on-left",
      "auto-indent",
      "indent-guide-improved",
      "multi-cursor",
      "linter-ruby",
      "ruby-debugger",
      "linter-phpcs",
      "tree-view",
      "linter-phpmd",
      "Termrk"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "nucleus-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true,
    "tabType": "soft"
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
aligner, v0.22.0
aligner-css, v1.2.0
aligner-ruby, v1.4.0
aligner-scss, v1.1.0
angularjs, v0.3.4
atom-commander, v0.7.0
atom-html-preview, v0.1.21
atom-ternjs, v0.14.2
atom-typescript, v9.0.0
auto-detect-indentation, v1.1.0
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
color-picker, v2.2.1
cucumber, v0.5.0
editorconfig, v1.4.1
environment, v1.2.0
file-icons, v1.7.16
git-log, v0.4.1
hashrocket, v0.4.10
highlight-selected, v0.11.2
imdone-atom, v1.3.29
language-blade, v0.25.3
language-gherkin, v1.0.4
language-swift, v0.4.0
laravel, v0.7.0
linter, v1.11.14
linter-clang, v3.4.4
linter-csslint, v1.3.2
linter-htmlhint, v1.2.1
linter-js-yaml, v1.2.5
linter-jshint, v2.1.0
linter-less, v2.5.0
linter-rubocop, v0.4.7
linter-scss-lint, v3.0.4
linter-swiftc, v2.0.0
linter-tidy, v2.1.1
markdown-table-formatter, v2.8.3
merge-conflicts, v1.4.4
monokai, v0.18.0
nucleus-dark-ui, v0.9.0
project-manager, v2.9.7
pull-requests, v0.0.23
react, v0.15.0
red-wavy-underline, v0.3.0
sync-settings, v0.7.2
travis-ci-status, v1.1.1
tree-view-breadcrumb, v0.8.1
wrap-style, v0.3.1

# Dev
No dev packages
```

**Comment by eastwood** [comment]
Hi @Ashraf-Ali-aa can you replicate this functionality when running `atom --safe`

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/12181#issuecomment-234689965. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
