### ISSUE TITLE
linux ubuntu build failure on gyp_main.py no such option --no-parallel

### ISSUE THREAD

**Issue by darrenleeweber** [atom/atom#12195]
```sh
$ git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
Note: checking out 'v1.8.0'.
... snipped ...
HEAD is now at f89b273... Enable Windows codesigning via Squirrel for MSI

$ ./script/build
Node: v0.10.25
npm: v1.4.21
Installing build modules...
=> Took 105042ms.

Installing apm...
Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/data/src/atom/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-65-generic
gyp ERR! command "node" "/data/src/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/src/atom/apm/node_modules/atom-package-manager/node_modules/keytar
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
Usage: gyp_main.py [options ...] [build_file ...]
```

**Comment by damieng** [comment]
Your version of node-gyp might be too old - the no-parallel switch was added when parallel became the default.

To upgrade npm type `npm update -g node-gyp` (if it's installed globally, if locally remove the -g)

**Comment by darrenleeweber** [comment]
Thanks!  Until I want to develop something, I may not try to build atom again.  I'll keep an eye on the ubuntu-make progress on supporting atom releases, i.e.
  - https://github.com/ubuntu/ubuntu-make/issues/6
