### ISSUE TITLE
Uncaught TypeError: Header name must be a valid HTTP Token ["{"token""]

### ISSUE THREAD

**Issue by bmrinal** [atom/atom#12219]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Header name must be a valid HTTP Token ["{"token""]

```
At _http_outgoing.js:337

TypeError: Header name must be a valid HTTP Token ["{"token""]
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:337:11)
    at new ClientRequest (_http_client.js:86:14)
    at Object.exports.request (http.js:31:10)
    at Request.start (/Users/mrinal/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/request/request.js:708:30)
    at Request.end (/Users/mrinal/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/request/request.js:1405:28)
    at end (/Users/mrinal/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/request/request.js:433:16)
    at /Users/mrinal/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/request/request.js:447:9
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
     -1:33 core:focus-next (textarea.field.rest-client-payload)
  3x -0:35.2.0 core:copy (div.rest-client.native-key-bindings.padded.pane-item)
     -0:27.9.0 core:paste (textarea.field.rest-client-headers)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "editor": {
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.10
atom-formatter-jsbeautify, v1.1.2
formatter-jsbeautify, v1.0.2
rest-client, v1.2.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This looks like a bug with the rest-client package, so please report this issue over there instead.
