### ISSUE TITLE
Uncaught Error: dlopen(/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar.unpacke...

### ISSUE THREAD

**Issue by fujimo21** [atom/atom#12238]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: dlopen(/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/runas/build/Release/runas.node, 1): image not found

```
At /Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

Error: dlopen(/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/runas/build/Release/runas.node, 1): image not found
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:170:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/runas/lib/runas.js:4:11)
    at Object.<anonymous> (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/runas/lib/runas.js:47:4)
    at Module._compile (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:468:21)
    at File.module.exports.File.writeSync (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:380:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1099:19)
    at TextBuffer.module.exports.TextBuffer.save (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Users/fujimotoyuji/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  3x -2:09.2.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -2:08.5.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -2:07.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:03.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -1:56.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:38.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:38.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:34.2.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -1:31.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:27.4.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:20.3.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:46.2.0 core:move-right (atom-text-editor.editor.is-focused)
 28x -0:44.7.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:28.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:19.6.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:18.1.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "japanese-menu"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
Are you still able to reproduce this using the latest release of Atom, v1.10.2?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/12238#issuecomment-249508113. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
