### ISSUE TITLE
Uncaught Error: Timeout after 60000 for id: 5685, Calling remote method fetchBookmarks..

### ISSUE THREAD

**Issue by suryabhupa** [atom/atom#12256]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Timeout after 60000 for id: 5685, Calling remote method fetchBookmarks..

```
At /opt/facebook/nuclide/0.157.34360420/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:144

Error: Timeout after 60000 for id: 5685, Calling remote method fetchBookmarks..
  at Call._timeout (/opt/facebook/nuclide/0.157.34360420/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:164:22)
  at /opt/facebook/nuclide/0.157.34360420/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:129:13

```

### Commands

```
     -1:59.8.0 editor:consolidate-selections (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -1:59.8.0 core:cancel (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "TARGETS",
        "cconf",
        "cinc",
        "mcconf",
        "tw",
        "BUCK",
        "ctw"
      ]
    },
    "disabledPackages": [
      "metrics",
      "fuzzy-finder",
      "tree-view",
      "vim-mode",
      "vim-mode-plus",
      "vim-mode-plus-ex-mode",
      "ex-mode"
    ]
  },
  "editor": {
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.24.4
language-ini, v1.16.0
language-lua, v0.9.4
language-ocaml, v1.1.2
language-thrift, v1.0.2
linter, v1.11.14
linter-lua, v1.0.2
merge-conflicts, v1.4.4
nuclide, v0.158.34712877
tool-bar, v1.0.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
This looks like an issue with [Nuclide](https://github.com/facebook/nuclide) – feel free to reopen there.
