### ISSUE TITLE
Autocomplete php throws error saving jsx file

### ISSUE THREAD

**Issue by poci-hu** [atom/atom#12430]
[Enter steps to reproduce below:]

1. Save a jsx file

**Atom Version**: 1.9.8
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.9

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\decoration-manager.js:192

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\decoration-manager.js:192:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor.js:1528:37)
    at ClassProvider.module.exports.ClassProvider.addMarkerToCommentLine (file:///C:/Users/poci/.atom/packages/atom-autocomplete-php/lib/goto/class-provider.coffee:117:28)
    at ClassProvider.module.exports.ClassProvider.registerMarkers (file:///C:/Users/poci/.atom/packages/atom-autocomplete-php/lib/goto/class-provider.coffee:71:18)
    at ClassProvider.module.exports.AbstractProvider.rescanMarkers (file:///C:/Users/poci/.atom/packages/atom-autocomplete-php/lib/goto/abstract-provider.coffee:172:10)
    at file:///C:/Users/poci/.atom/packages/atom-autocomplete-php/lib/goto/abstract-provider.coffee:31:18
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1156:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1126:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor.js:743:26)
    at Object.module.exports.AtomSaveAll.saveAll (file:///C:/Users/poci/.atom/packages/atom-save-all/lib/atom-save-all.coffee:18:18)
    at atom-text-editor.<anonymous> (file:///C:/Users/poci/.atom/packages/atom-save-all/lib/atom-save-all.coffee:6:72)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:16.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:16.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:13.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:13 core:move-right (atom-text-editor.editor.is-focused)
     -0:12.6.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:12.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.4.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:12.4.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:10.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.9.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:08.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:07.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:05.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:04.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.8.0 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "atom-autocomplete-php": {
    "binComposer": "C:/ProgramData/ComposerSetup/bin/composer.bat"
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.9 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-save-all, v0.4.1 (active)
auto-detect-indentation, v1.1.0 (active)
auto-indent, v0.5.0 (active)
autoclose-html, v0.23.0 (active)
docblockr, v0.8.2 (active)
highlight-selected, v0.11.2 (active)
language-blade, v0.25.3 (active)
linter, v1.11.16 (active)
linter-php, v1.2.0 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.24.7 (active)
php-extract-method, v0.2.1 (active)
react, v0.16.0 (active)
Sublime-Style-Column-Selection, v1.7.2 (active)
todo-show, v1.7.0 (inactive)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
Please re-open this issue on the [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) repository.

**Comment by poci-hu** [comment]
oh well
