### ISSUE TITLE
Atom opening to dev tools screen

### ISSUE THREAD

**Issue by adidas791** [atom/atom#12459]
Hello, 

Atom is opening to the dev tools screen... This started happening after I installed the linter-pylint package. However, I don't know if it is directly related.

I reinstalled Atom but still getting the same error. 

Can you please help? 

Thank you.

PS: Below the error.

index.js:62 Error: EPERM: operation not permitted, open 'C:\Users\oscar.linares\\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\imports.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Object.fsPlus.writeFileSync (C:\Users\oscar.linares\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (C:\Users\oscar.linares\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\less-cache\lib\less-cache.js:155:17)
    at LessCache.module.exports.LessCache.setImportPaths (C:\Users\oscar.linares\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\less-cache\lib\less-cache.js:113:12)
    at new LessCache (C:\Users\oscar.linares\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\less-cache\lib\less-cache.js:32:12)
    at new LessCompileCache (C:\Users\oscar.linares\AppData\Local\atom\app-1.9.8\resources\app.asar\src\less-compile-cache.js:20:20)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\oscar.linares\AppData\Local\atom\app-1.9.8\resources\app.asar\src\theme-manager.js:270:26)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (C:\Users\oscar.linares\AppData\Local\atom\app-1.9.8\resources\app.asar\src\theme-manager.js:257:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (C:\Users\oscar.linares\AppData\Local\atom\app-1.9.8\resources\app.asar\src\theme-manager.js:174:24)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (C:\Users\oscar.linares\AppData\Local\atom\app-1.9.8\resources\app.asar\src\theme-manager.js:237:12)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (C:\Users\oscar.linares\AppData\Local\atom\app-1.9.8\resources\app.asar\src\theme-manager.js:232:19)
    at new AtomEnvironment (C:\Users\oscar.linares\AppData\Local\atom\app-1.9.8\resources\app.asar\src\atom-environment.js:270:19)
    at module.exports (C:\Users\oscar.linares\AppData\Local\atom\app-1.9.8\resources\app.asar\src\initialize-application-window.js:22:19)
    at setupWindow (file:///C:/Users/oscar.linares/AppData/Local/atom/app-1.9.8/resources/app.asar/static/index.js:87:12)
    at window.onload (file:///C:/Users/oscar.linares/AppData/Local/atom/app-1.9.8/resources/app.asar/static/index.js:41:9)handleSetupError @ index.js:62

**Comment by Nikki1993** [comment]
Hello,

Have you tried running atom in save mode see if the issue persists? `atom --safe`

Also, please next time fill out proper issue report template and try troubleshooting steps listed when you create the issue before posting. That eliminates the need to try simple steps and allows us to see how further we can assist you.

**Comment by 50Wliu** [comment]
Delete your `C:\Users\oscar.linares\.atom\compile-cache` folder and try again.
