### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by SzabZol** [atom/atom#12498]
**Atom Version**: 1.9.9
**System**: Ubuntu 16.04.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /usr/share/atom/resources/app.asar/src/pane.js:828

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app.asar/src/pane.js:828:15)
    at Pane.module.exports.Pane.focus (/usr/share/atom/resources/app.asar/src/pane.js:236:21)
    at atom-pane.<anonymous> (/usr/share/atom/resources/app.asar/src/pane-element.js:50:23)
```

**Comment by xenithorb** [comment]
This seemed to happen when I closed all tabs but had the settings window open

**Comment by jgrosso** [comment]
I split a pane left and then closed the one on the right, and, while there were no tabs in the pane on the right, it was still open (interacting with it threw this error).

**Comment by Ben3eeE** [comment]
### Description

> This seemed to happen when I closed all tabs but had the settings window open

This is possible to reproduce with the `settings-view` open and closing the pane. My reproduction is with Windows 7 Atom 1.9.9.

### Refs
There was a similar issue to this: https://github.com/atom/atom/issues/8652
Step 5-6 throws it's own error only in the console reported here: https://github.com/atom/atom/issues/11199

### Steps

1. Open Atom in safe mode in the `image-view` repository.
2. Open `coffeelint.json`.
3. `pane:split-right-and-copy-active-item`.
4. In the right pane open settings view.
5. In the left pane open settings view.
6. In the left pane open settings view.
7. Close the left pane.

Gif showing all steps up to exception:
![pane has been destroyed](https://cloud.githubusercontent.com/assets/1058982/18117906/ee6c50ba-6f51-11e6-9e2d-6b51aba9aded.gif)

**Atom Version**: 1.9.9
**System**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Pane has been destroyed

```
At C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane.js:828

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane.js:828:15)
    at Pane.module.exports.Pane.focus (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane.js:236:21)
    at atom-pane.<anonymous> (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane-element.js:50:23)
    at atom-pane.<anonymous> (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane-element.js:52:18)
    at atom-pane.PaneElement.activated (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.activate (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane.js:833:27)
    at PaneContainer.module.exports.PaneContainer.activateNextPane (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane-container.js:250:26)
    at Pane.module.exports.Pane.destroyed (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane.js:854:24)
    at Pane.module.exports.Model.destroy (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\model.js:31:58)
    at Pane.module.exports.Pane.destroy (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane.js:847:39)
    at Pane.module.exports.Pane.close (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane.js:986:21)
    at atom-pane.commandRegistry.add.pane:close (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\register-default-commands.js:288:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\atom-environment.js:1110:28)
    at EventEmitter.outerCallback (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\application-delegate.js:342:25)
    at emitThree (events.js:110:13)
    at EventEmitter.emit (events.js:188:7)
```

### Commands

```
     -0:23.1.0 tabs:split-right (div.title)
     -0:12.5.0 pane:close (div.title)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-no-tab-close-button",
      "simple-drag-drop-text",
      "clipboard-history",
      "highlight-line",
      "wrap-guide",
      "todo-show",
      "linter-xo",
      "browser-plus",
      "svn",
      "activate-power-mode"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "one-dark-ui",
      "atom-material-syntax"
    ]
  },
  "editor": {
    "atomicSoftTabs": false,
    "fontSize": 12,
    "invisibles": {},
    "scrollPastEnd": true,
    "scrollSensitivity": 60,
    "showIndentGuide": true,
    "softWrap": true,
    "tabLength": 4,
    "undoGroupingInterval": 400,
    "zoomFontWhenCtrlScrolling": false
  }
}
```

### Installed Packages

```coffee
# User
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.51.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lobobabysaurus** [comment]
I'm seeing this issue independent of the settings view being open.  I get two distinct stack traces
One is the following and is from the minimap package -

`TypeError: Cannot read property 'pixelPositionForScreenPosition' of null
    at atom-text-editor.TextEditorElement.pixelPositionForScreenPosition (/usr/share/atom/resources/app.asar/src/text-editor-element.js:336:28)
    at StableAdapter.computeScrollTop (/home/psimmons/.atom/packages/minimap/lib/adapters/stable-adapter.js:54:42)
    at StableAdapter.getScrollTop (/home/psimmons/.atom/packages/minimap/lib/adapters/stable-adapter.js:47:17)
    at Minimap.getTextEditorScrollRatio (/home/psimmons/.atom/packages/minimap/lib/minimap.js:521:25)
    at Minimap.getCapedTextEditorScrollRatio (/home/psimmons/.atom/packages/minimap/lib/minimap.js:533:29)
    at Minimap.getScrollTopFromEditor (/home/psimmons/.atom/packages/minimap/lib/minimap.js:854:12)
    at Minimap.getScrollTop (/home/psimmons/.atom/packages/minimap/lib/minimap.js:808:14)
    at Minimap.getLastVisibleScreenRow (/home/psimmons/.atom/packages/minimap/lib/minimap.js:786:13)
    at Minimap.emitRangeChanges (/home/psimmons/.atom/packages/minimap/lib/mixins/decoration-management.js:497:38)
    at Minimap.emitDecorationChanges (/home/psimmons/.atom/packages/minimap/lib/mixins/decoration-management.js:482:10)
    at Minimap.removeAllDecorationsForMarker (/home/psimmons/.atom/packages/minimap/lib/mixins/decoration-management.js:575:12)
    at /home/psimmons/.atom/packages/minimap/lib/mixins/decoration-management.js:349:14
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayMarker.module.exports.DisplayMarker.destroy (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/display-marker.js:29:20)
    at MinimapHighlightSelectedView.module.exports.HighlightedAreaView.removeMarkers (/home/psimmons/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:152:12)
    at MinimapHighlightSelectedView.removeMarkers (/home/psimmons/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at MinimapHighlightSelectedView.handleSelection (/home/psimmons/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:38:8)
    at MinimapHighlightSelectedView.handleSelection (/home/psimmons/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at MinimapHighlightSelectedView.subscribeToActiveTextEditor (/home/psimmons/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:96:8)
    at /home/psimmons/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:15:8
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:346:27
    at Pane.module.exports.Pane.observeActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:225:7)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:344:42
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.setActivePane (/usr/share/atom/resources/app.asar/src/pane-container.js:196:22)
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app.asar/src/pane.js:831:15)`

and the other is -
 `Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app.asar/src/pane.js:828:15)
    at atom-workspace.module.exports.WorkspaceElement.handleFocus (/usr/share/atom/resources/app.asar/src/workspace-element.js:127:41)`

**Comment by Ben3eeE** [comment]
@lobobabysaurus any steps to reproduce?

**Comment by UtamaruMonster** [comment]
Randomly happens on Atom 1.11.1, preferences not possible to open

**Comment by Ben3eeE** [comment]
@UtamaruMonster Please paste all the information from the error here. What are you doing when it happens?

**Comment by UtamaruMonster** [comment]
Sorry already closed. But basically some files on one pain and on another. Then when on teh second pane i pushed CMD + P, then started closing opened files on the second pane. After the last file was closed in teh second pane the error appear

**Comment by jimtahu** [comment]
I hit this by:
1. (Inadvertently)  open current file in new pane
2. Close newly opened tab
3. Encountered [atom-minimap issue 489](https://github.com/atom-minimap/minimap/issues/489)
4. Notice that empty pane is still open, and try to click it
5. Atom reports this bug

**Comment by Ben3eeE** [comment]
@jimtahu Thank you for the steps and the `minimap` issue reference 🙇. As I suspected there seems to be two different issues here. One of them reproduces with the `settings-view` and the other appears to be a bug in the `minimap` package.

I have attached steps to reproduce with `minimap` in that issue https://github.com/atom-minimap/minimap/issues/489#issuecomment-254057876 if you have this error and also have the `minimap` exception then subscribe to that issue for updates.
