### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError

### ISSUE THREAD

**Issue by kertz** [atom/atom#12517]
All I did was close my laptop, open it again and switch to Atom. I'm not able to reproduce this. I hope this is of some help.

`**Atom Version**: 1.9.9**System**: Mac OS X 10.11.6**`

```
Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:309:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:141:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:178:13)
    at undefined.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:112:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:631:29)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:665:36)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:182:35)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61
```

**Comment by Ben3eeE** [comment]
Looks like https://github.com/atom/atom/issues/11692

**Comment by kertz** [comment]
Looks like it. Closing this.
