### ISSUE TITLE
script/build  --install fails with "Cannot read property 'getCachePath' of undefined"

### ISSUE THREAD

**Issue by capouch** [atom/atom#12549]
The new build system, for me, eecf830, is acting up.

I can't get the build to complete.  I'm on Slackware, and have been happily building from sources for many months.  No more joy as of an hour or two ago.

getCachePath seems the guilty identifier that blows things up.

```javascript 
~/atom$ ./script/build --install                        
Cleaning /home/brianc/atom/out
Copying assets to /home/brianc/atom/out/app
Transpiling Babel paths in /home/brianc/atom/out/app
Transpiling CoffeeScript paths in /home/brianc/atom/out/app
Transpiling CSON paths in /home/brianc/atom/out/app
Transpiling PEG.js paths in /home/brianc/atom/out/app
Generating module cache for /home/brianc/atom/out/app
Generating pre-built less cache in /home/brianc/atom/out/app/less-compile-cache
Generating metadata for /home/brianc/atom/out/app/package.json
Generating API docs at /home/brianc/atom/docs/output/atom-api.json
Skipping Chromedriver download because it is used only on macOS
Dumping symbols in /home/brianc/atom/out/symbols
Running electron-packager on /home/brianc/atom/out/app with app name "atom"
Packaging app for platform linux x64 using electron v0.37.8
Changing permissions for node files in /home/brianc/atom/out/atom-1.11.0-dev-eecf830-amd64
Copying non-ASAR resources to /home/brianc/atom/out/atom-1.11.0-dev-eecf830-amd64/resources
Writing LICENSE.md to /home/brianc/atom/out/atom-1.11.0-dev-eecf830-amd64/resources
Application bundle created at /home/brianc/atom/out/atom-1.11.0-dev-eecf830-amd64
Skipping creating debian package. Specify the --create-debian-package option to create it.
Skipping creating rpm package. Specify the --create-rpm-package option to create it.
Skipping artifacts compression. Specify the --compress-artifacts option to compress Atom binaries (and symbols on macOS)
Error reading compiled file TypeError: Cannot read property 'getCachePath' of undefined
    at require.install.retrieveSourceMap (/home/brianc/atom/src/compile-cache.js:130:51)
    at mapSourcePosition (/home/brianc/atom/node_modules/source-map-support/source-map-support.js:140:21)
    at wrapCallSite (/home/brianc/atom/node_modules/source-map-support/source-map-support.js:303:20)
    at /home/brianc/atom/node_modules/source-map-support/source-map-support.js:338:26
    at Array.map (native)
    at prepareStackTrace (/home/brianc/atom/node_modules/source-map-support/source-map-support.js:337:24)
    at Function.prepareStackTraceWithRawStackAssignment (/home/brianc/atom/src/compile-cache.js:174:12)
    at Error.get stack (native)
    at process.<anonymous> (/home/brianc/atom/script/build:41:18)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:44:22)
    at runMicrotasksCallback (internal/process/next_tick.js:61:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Not implemented yet.
    at module.exports (/home/brianc/atom/script/lib/install-application.js:17:11)
    at dumpSymbols.then.then.then.packagedAppPath (/home/brianc/atom/script/build:95:7)
```

**Comment by nathansobo** [comment]
@capouch Can you try running `script/bootstrap`? We omitted running `bootstrap` from `build` on this new script, though I think I'm going to [change that](https://github.com/atom/atom/pull/12550).

**Comment by capouch** [comment]
Same result.

**Comment by 50Wliu** [comment]
I can confirm this on Windows 10, x64 actually:
```
C:\Users\USERNAME\Documents\GitHub\atom>script\build --install
Cleaning C:\Users\USERNAME\Documents\GitHub\atom\out
Copying assets to C:\Users\USERNAME\Documents\GitHub\atom\out\app
Transpiling Babel paths in C:\Users\USERNAME\Documents\GitHub\atom\out\app
Transpiling CoffeeScript paths in C:\Users\USERNAME\Documents\GitHub\atom\out\app
Transpiling CSON paths in C:\Users\USERNAME\Documents\GitHub\atom\out\app
Transpiling PEG.js paths in C:\Users\USERNAME\Documents\GitHub\atom\out\app
Generating module cache for C:\Users\USERNAME\Documents\GitHub\atom\out\app
Generating pre-built less cache in C:\Users\USERNAME\Documents\GitHub\atom\out\app\less-compile-cache
Generating metadata for C:\Users\USERNAME\Documents\GitHub\atom\out\app\package.json
Generating API docs at C:\Users\USERNAME\Documents\GitHub\atom\docs\output\atom-api.json
Skipping Chromedriver download because it is used only on macOS
Skipping symbol dumping because minidump is not supported on Windows
Running electron-packager on C:\Users\USERNAME\Documents\GitHub\atom\out\app with app name "atom"
Packaging app for platform win32 ia32 using electron v0.37.8
Copying non-ASAR resources to C:\Users\USERNAME\Documents\GitHub\atom\out\Atom\resources
Writing LICENSE.md to C:\Users\USERNAME\Documents\GitHub\atom\out\Atom\resources
Application bundle created at C:\Users\USERNAME\Documents\GitHub\atom\out\Atom
Skipping creating installer. Specify the --create-windows-installer option to create a Squirrel-based Windows installer. Code-signing was skipped too.
Skipping artifacts compression. Specify the --compress-artifacts option to compress Atom binaries (and symbols on macOS)
Error reading compiled file TypeError: Cannot read property 'getCachePath' of undefined
    at retrieveSourceMap (C:\Users\USERNAME\Documents\GitHub\atom\src\compile-cache.js:130:51)
    at mapSourcePosition (C:\Users\USERNAME\Documents\GitHub\atom\node_modules\source-map-support\source-map-support.js:140:21)
    at wrapCallSite (C:\Users\USERNAME\Documents\GitHub\atom\node_modules\source-map-support\source-map-support.js:303:20)
    at C:\Users\USERNAME\Documents\GitHub\atom\node_modules\source-map-support\source-map-support.js:338:26
    at Array.map (native)
    at prepareStackTrace (C:\Users\USERNAME\Documents\GitHub\atom\node_modules\source-map-support\source-map-support.js:337:24)
    at Function.prepareStackTraceWithRawStackAssignment (C:\Users\USERNAME\Documents\GitHub\atom\src\compile-cache.js:174:12)
    at Error.get stack [as stack] (native)
    at process.<anonymous> (C:\Users\USERNAME\Documents\GitHub\atom\script\build:41:18)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:44:22)
    at process._tickCallback (internal/process/next_tick.js:104:7)
Error: Not implemented yet.
    at module.exports (C:\Users\USERNAME\Documents\GitHub\atom\script\lib\install-application.js:17:11)
    at dumpSymbols.then.then.then.packagedAppPath (C:\Users\USERNAME\Documents\GitHub\atom\script\build:95:7)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by as-cii** [comment]
I think this problem is originating because you're supplying the `--install` flag, which is supported only on Mac. On Windows, for example, you should be able to use `--create-windows-installer` and simply launch the generated `.msi` or `.exe` to install Atom.

A similar solution applies to Linux too: passing `--create-rpm-package` or `--create-debian-package` and then installing the generated package should work fine. 

@capouch: I am little less clear on how to build on Slackware. http://docs.slackware.com/howtos:slackware_admin:how_to_use_slackware_installing_software mentions a couple of tools that you might be able to use to convert the generated rpm/deb package to `tgz`.

@nathansobo: I wonder if we should put the installation mechanism for other platforms back. When rewriting the build scripts, we though installing Atom via `script/build` was just a convenience offered for local development, but seems like people might rely on it for other reasons.

**Comment by capouch** [comment]
I just tried that solution--still no joy.  Even though this is mostly the same as in the OP, I include the build output below.

```javascript
$ ./script/build --create-debian-package
Node:	v6.3.1
Npm:	v3.10.5
Installing script dependencies
Installing apm
Installing modules â
Wrote Dependencies Fingerprint: /home/brianc/atom/node_modules/.dependencies-fingerprint 8d3ecfad1e34087adc70efaba1c7da515b5d26b0
Cleaning /home/brianc/atom/out
Copying assets to /home/brianc/atom/out/app
Transpiling Babel paths in /home/brianc/atom/out/app
Transpiling CoffeeScript paths in /home/brianc/atom/out/app
Transpiling CSON paths in /home/brianc/atom/out/app
Transpiling PEG.js paths in /home/brianc/atom/out/app
Generating module cache for /home/brianc/atom/out/app
Generating pre-built less cache in /home/brianc/atom/out/app/less-compile-cache
Generating metadata for /home/brianc/atom/out/app/package.json
Generating API docs at /home/brianc/atom/docs/output/atom-api.json
Skipping Chromedriver download because it is used only on macOS
Dumping symbols in /home/brianc/atom/out/symbols
Running electron-packager on /home/brianc/atom/out/app with app name "atom"
Packaging app for platform linux x64 using electron v0.37.8
Changing permissions for node files in /home/brianc/atom/out/atom-1.11.0-dev-42146d5-amd64
Copying non-ASAR resources to /home/brianc/atom/out/atom-1.11.0-dev-42146d5-amd64/resources
Writing LICENSE.md to /home/brianc/atom/out/atom-1.11.0-dev-42146d5-amd64/resources
Application bundle created at /home/brianc/atom/out/atom-1.11.0-dev-42146d5-amd64
Creating Debian package for "/home/brianc/atom/out/atom-1.11.0-dev-42146d5-amd64"
Creating Debian package directory structure at "/tmp/atom-1.11.0-dev-42146d5-amd64"
Copying "/home/brianc/atom/out/atom-1.11.0-dev-42146d5-amd64" to "/tmp/atom-1.11.0-dev-42146d5-amd64/usr/share/atom"
Copying binaries into "/tmp/atom-1.11.0-dev-42146d5-amd64/usr/bin"
Writing control file into "/tmp/atom-1.11.0-dev-42146d5-amd64/DEBIAN"
Writing desktop entry file into "/tmp/atom-1.11.0-dev-42146d5-amd64/usr/share/applications"
Copying icon into "/tmp/atom-1.11.0-dev-42146d5-amd64/usr/share/pixmaps"
Copying license into "/tmp/atom-1.11.0-dev-42146d5-amd64/usr/share/doc/atom"
Copying lintian overrides into "/tmp/atom-1.11.0-dev-42146d5-amd64/usr/share/lintian/overrides"
Generating .deb file from /tmp/atom-1.11.0-dev-42146d5-amd64
Error reading compiled file TypeError: Cannot read property 'getCachePath' of undefined
    at require.install.retrieveSourceMap (/home/brianc/atom/src/compile-cache.js:130:51)
    at mapSourcePosition (/home/brianc/atom/node_modules/source-map-support/source-map-support.js:140:21)
    at wrapCallSite (/home/brianc/atom/node_modules/source-map-support/source-map-support.js:303:20)
    at /home/brianc/atom/node_modules/source-map-support/source-map-support.js:338:26
    at Array.map (native)
    at prepareStackTrace (/home/brianc/atom/node_modules/source-map-support/source-map-support.js:337:24)
    at Function.prepareStackTraceWithRawStackAssignment (/home/brianc/atom/src/compile-cache.js:174:12)
    at Error.get stack (native)
    at process.<anonymous> (/home/brianc/atom/script/build:41:18)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:44:22)
    at runMicrotasksCallback (internal/process/next_tick.js:61:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: spawnSync fakeroot ENOENT
    at exports._errnoException (util.js:1012:11)
    at Object.spawnSync (child_process.js:453:20)
    at module.exports (/home/brianc/atom/script/lib/spawn-sync.js:10:41)
    at module.exports (/home/brianc/atom/script/lib/create-debian-package.js:110:3)
    at dumpSymbols.then.then.packagedAppPath (/home/brianc/atom/script/build:76:9)
```

**Comment by capouch** [comment]
OK here's an extremely heartening situation I just discovered: the error showing above must pertain ONLY to the final packaging step (and therefore may not show up if the Linux user is creating an RPM), because I was able to move into a directory that the build process created in /tmp, and there it was--although not wrapped in a .deb--the whole thing I needed, and after manually creating the .deb package I was able to install it just fine, and can confirm, as the version tag here matches the current one on master:

```javascript
$ atom --version
Atom    : 1.11.0-dev-42146d5
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by capouch** [comment]
```javascript
$ cd /tmp/atom-1.11.0-dev-42146d5-amd64/
brianc@bc-spring:/tmp/atom-1.11.0-dev-42146d5-amd64$ ls
DEBIAN	usr
```

**Comment by as-cii** [comment]
I think in your case the problem was that `fakeroot` was not available on your system:

```
Error: spawnSync fakeroot ENOENT
    at exports._errnoException (util.js:1012:11)
    at Object.spawnSync (child_process.js:453:20)
    at module.exports (/home/brianc/atom/script/lib/spawn-sync.js:10:41)
    at module.exports (/home/brianc/atom/script/lib/create-debian-package.js:110:3)
    at dumpSymbols.then.then.packagedAppPath (/home/brianc/atom/script/build:76:9)
```

And since we use it to create the Debian package, it made `script/build` fail. I am currently working on implementing the `--install` flag for all the platforms.

**Comment by 50Wliu** [comment]
> I think this problem is originating because you're supplying the --install flag, which is supported only on Mac.

This is confusing as if you run `script\build` without arguments the last output line is
```
Skipping installation. Specify the --install option to install Atom
```

**Comment by fusion809** [comment]
On Arch Linux with Atom 1.11.0-beta5 this error has re-reared its ugly face:

```bash
Transpiling Babel paths in /home/fusion809/GitHub/mine/packaging/atom-editor-beta-fusion/src/atom-1.11.0-beta5/out/app
Error reading compiled file TypeError: Cannot read property 'getCachePath' of undefined
    at retrieveSourceMap (/home/fusion809/GitHub/mine/packaging/atom-editor-beta-fusion/src/atom-1.11.0-beta5/src/compile-cache.js:130:51)
    at mapSourcePosition (/home/fusion809/GitHub/mine/packaging/atom-editor-beta-fusion/src/atom-1.11.0-beta5/node_modules/source-map-support/source-map-support.js:140:21)
    at wrapCallSite (/home/fusion809/GitHub/mine/packaging/atom-editor-beta-fusion/src/atom-1.11.0-beta5/node_modules/source-map-support/source-map-support.js:303:20)
    at /home/fusion809/GitHub/mine/packaging/atom-editor-beta-fusion/src/atom-1.11.0-beta5/node_modules/source-map-support/source-map-support.js:338:26
    at Array.map (native)
    at prepareStackTrace (/home/fusion809/GitHub/mine/packaging/atom-editor-beta-fusion/src/atom-1.11.0-beta5/node_modules/source-map-support/source-map-support.js:337:24)
    at Function.prepareStackTraceWithRawStackAssignment (/home/fusion809/GitHub/mine/packaging/atom-editor-beta-fusion/src/atom-1.11.0-beta5/src/compile-cache.js:174:12)
    at Error.get stack [as stack] (native)
fs.js:731
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EISDIR: illegal operation on a directory, read

    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at compileFileAtPath (/home/fusion809/GitHub/mine/packaging/atom-editor-beta-fusion/src/atom-1.11.0-beta5/src/compile-cache.js:69:23)
    at Object.exports.addPathToCache (/home/fusion809/GitHub/mine/packaging/atom-editor-beta-fusion/src/atom-1.11.0-beta5/src/compile-cache.js:50:14)
    at transpileBabelPath (/home/fusion809/GitHub/mine/packaging/atom-editor-beta-fusion/src/atom-1.11.0-beta5/script/lib/transpile-babel-paths.js:40:39)
    at module.exports (/home/fusion809/GitHub/mine/packaging/atom-editor-beta-fusion/src/atom-1.11.0-beta5/script/lib/transpile-babel-paths.js:22:5)
    at Object.<anonymous> (/home/fusion809/GitHub/mine/packaging/atom-editor-beta-fusion/src/atom-1.11.0-beta5/script/build:51:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
