### ISSUE TITLE
Cannot jump to functiion by using nav-panel

### ISSUE THREAD

**Issue by elasti-eduardm** [atom/atom#12557]
### Description
Cannot jump to functiion by using nav-panel. 

### Steps to Reproduce

1. Install last version of atom (1.9.9) or beta (1.10.0 beta 7)
2. Open file (go program) 
3. Click some fuinc on Nav panel

**Expected behavior:** 
Jump to proper function

**Actual behavior:** 
got error - 
Uncaught TypeError: Invalid Point: ((116, 0), 0)

**Atom Version**: 1.10.0-beta7
**Electron Version**: 0.37.8
**System**: "CentOS Linux
**Thrown From**: [nav-panel](https://github.com/Ziink/atom-nav-panel) package, v0.0.11

### Stack Trace

Uncaught TypeError: Invalid Point: ((116, 0), 0)

```
At /usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:35

TypeError: Invalid Point: ((116, 0), 0)
    at Function.module.exports.Point.assertValid (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1101:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1089:20)
    at DisplayLayer.module.exports.DisplayLayer.destroyFoldsIntersectingBufferRange (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/display-layer.js:325:33)
    at TextEditor.module.exports.TextEditor.unfoldBufferRow (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:2923:32)
    at NavView.module.exports.NavView.gotoMarker (/home/eduardm/.atom/packages/nav-panel/lib/nav-view.coffee:270:12)
    at HTMLLIElement.<anonymous> (/home/eduardm/.atom/packages/nav-panel/lib/nav-view.coffee:48:12)
    at HTMLDivElement.jQuery.event.dispatch (/home/eduardm/.atom/packages/nav-panel/node_modules/jquery/dist/jquery.js:4737:27)
    at HTMLDivElement.elemData.handle (/home/eduardm/.atom/packages/nav-panel/node_modules/jquery/dist/jquery.js:4549:28)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.5.0 (active)
autocomplete-go, v1.1.1 (active)
build, v0.65.0 (active)
builder-go, v1.0.1 (active)
busy, v0.6.0 (active)
cursor-history, v0.6.1 (active)
environment, v1.2.0 (active)
file-icons, v1.7.19 (active)
go-config, v1.2.3 (active)
go-debug, v0.1.22 (active)
go-find-references, v1.2.3 (active)
go-get, v1.0.4 (active)
go-oracle, v0.2.1 (inactive)
go-plus, v4.2.0 (active)
go-rename, v0.3.0 (active)
godoc, v0.4.0 (active)
gofmt, v1.1.8 (active)
gometalinter-linter, v1.1.1 (active)
gorename, v1.0.3 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
keybinding-cheatsheet, v0.1.0 (inactive)
language-docker, v1.1.7 (active)
language-protobuf, v0.7.0 (active)
linter, v1.11.16 (active)
linter-golinter, v1.2.0 (active)
minimap, v4.24.7 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.1.1 (active)
minimap-pigments, v0.2.1 (active)
minimap-selection, v4.4.0 (active)
monokai-seti, v0.7.0 (inactive)
nav-panel, v0.0.11 (active)
navigator-godef, v1.0.4 (active)
pigments, v0.34.0 (active)
pretty-json, v1.6.0 (active)
tester-go, v1.0.6 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (active)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (active)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

### Versions
Atom    : 1.10.0-beta7
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 50Wliu** [comment]
> Thrown From: nav-panel package, v0.0.11

Please report this to the nav-panel package instead.

**Comment by elasti-eduardm** [comment]
What is nav-panel package?

**Comment by 50Wliu** [comment]
The package that you installed...https://github.com/Ziink/atom-nav-panel.

**Comment by elasti-eduardm** [comment]
Installed package is 0.0.11
