### ISSUE TITLE
Help compiling on PowerPC linux?

### ISSUE THREAD

**Issue by ablakely** [atom/atom#12569]
I'm attempting to build atom for my powermac g5 running ubuntu mate and am getting this error.  I was able to compile nodejs from the source without issue although the build script is trying to download node for ppc?

OS
`Linux AaronG5 4.4.0-36-powerpc64-smp #55-Ubuntu SMP Thu Aug 11 18:23:55 UTC 2016 ppc64 ppc64 ppc64 GNU/Linux`

```
aaron@AaronG5:~/Build/atom$ ./script/build --create-debian-package
Node:	v4.5.0
Npm:	v3.10.6
Installing script dependencies
Installing apm
download not found: http://nodejs.org/dist/v4.4.5/node-v4.4.5-linux-ppc.tar.gz
/home/aaron/Build/atom/apm/node_modules/atom-package-manager/bin/apm: line 35: /home/aaron/Build/atom/apm/node_modules/atom-package-manager/bin/node: No such file or directory
child_process.js:488
    throw err;
    ^

Error: Command failed: /home/aaron/Build/atom/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:465:13)
    at Object.execFileSync (child_process.js:485:13)
    at module.exports (/home/aaron/Build/atom/script/lib/install-atom-dependencies.js:19:16)
    at Object.<anonymous> (/home/aaron/Build/atom/script/bootstrap:28:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

```

**Comment by ablakely** [comment]
Was able to get it to build by linking my node to apm/node_modules/atom-package-manager/bin/node and installing node-gyp manually to apm/node_modules/atom-package-manager/

Here's my .deb for anyone else interested.
https://www.dropbox.com/s/jjo7775jkjn3gvq/atom-ppc.deb?dl=0

**Comment by ablakely** [comment]
Still compiling atom binary for the wrong arch.

**Comment by paulcbetts** [comment]
Electron doesn't support PPC, sorry
