### ISSUE TITLE
Uncaught TypeError: Cannot read property 'screenExtent' of undefined

### ISSUE THREAD

**Issue by reznord** [atom/atom#12575]
System config:
OS           : Mac OS X El Capitan (Version: 10.11.4 (15E65))
Atom       : 1.11.0-beta0
Electron  : 0.37.8
Chrome   : 49.0.2623.75
Node       : 5.10.0

I am getting this error when I open Atom-beta editor with "Custom Title Bar" option checked from the Atom Settings -> Core

/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/display-index/dist/screen-line-iterator.js:184

`
TypeError: Cannot read property 'screenExtent' of undefined
  at ScreenLineIterator.getScreenPositionWithMaxLineLength (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/display-index/dist/screen-line-iterator.js:184:29)
  at DisplayIndex.getScreenPositionWithMaxLineLength (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/display-index/dist/display-index.js:141:32)
  at DisplayLayer.module.exports.DisplayLayer.getRightmostScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1508:32)
  at TextEditor.module.exports.TextEditor.getRightmostScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:991:32)
  at TextEditor.module.exports.TextEditor.getLongestScreenRow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:999:19)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getScreenRowsToRender (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:389:37)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getScreenRangesToRender (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:405:25)
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateLines (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1351:20)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:119:12)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:265:60)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:195:12)
  at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:304:21)
  at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:997:16)
  at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-element.js:85:22)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane-element.js:138:24)
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:288:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:437:21)
  at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/workspace.js:546:18
  at process._tickCallback (internal/process/next_tick.js:103:7)
`

**Comment by reznord** [comment]
I am getting this error every time I open a file.

**Comment by 50Wliu** [comment]
Is this reproducible in safe mode (`atom --safe`)?

In the future, please **completely** fill out the provided issue template.

**Comment by reznord** [comment]
@50Wliu sorry for that. From next time onwards, will follow the template. 

No, I am not getting the error when I run it in the `atom --safe` mode.

This is happening even when I try saving some new changes made in any file which is opened in a new pane.

**Comment by 50Wliu** [comment]
Ok, as this is not happening in safe mode, that means one of your installed packages is causing the issue.  You can find out which by using the [package-cop](https://atom.io/packages/package-cop) package.

**Comment by waxidiotic** [comment]
I was having the same issue and disabled some non-essentials packages and now its not happening for me anymore. Not sure what the exact offending package was, though.

**Comment by mgee** [comment]
For me it was happening when the package https://github.com/jtokoph/auto-detect-indentation was enabled. Disabling the package fixes it.

**Comment by reznord** [comment]
@mgee Same for me also, it is because of the auto-detect-indentation package only. Thanks for the solution

**Comment by jiku** [comment]
Experiencing this with `1.11.0-beta3` (and beta2). A few minutes into editing, the caret freezes and errors appear. Last time with two, one caused by `activate-power-mode`, and the other by it "likely being a bug in Atom".

```
Uncaught TypeError: Cannot read property 'screenExtent' of undefined
/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:871
Hide Stack Trace
TypeError: Cannot read property 'screenExtent' of undefined
    at ScreenLineIterator.getScreenPositionWithMaxLineLength (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/display-index/dist/screen-line-iterator.js:184:29)
    at DisplayIndex.getScreenPositionWithMaxLineLength (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/display-index/dist/display-index.js:141:32)
    at DisplayLayer.module.exports.DisplayLayer.getRightmostScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1508:32)
    at TextEditor.module.exports.TextEditor.getRightmostScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:991:32)
    at TextEditor.module.exports.TextEditor.getLongestScreenRow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:999:19)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getScreenRowsToRender (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:389:37)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getScreenRangesToRender (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:405:25)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLines (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1351:20)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:119:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:265:60)
    at TextEditorComponent.module.exports.TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:631:14)
    at atom-text-editor.TextEditorElement.pixelPositionForScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-element.js:288:29)
    at Object.module.exports.spawnParticles (/Users/jiku.dev/.atom/packages/activate-power-mode/lib/power-canvas.coffee:40:34)
    at invokeFunc (/Users/jiku.dev/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:160:19)
    at leadingEdge (/Users/jiku.dev/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:170:22)
    at Cursor.debounced [as throttleSpawnParticles] (/Users/jiku.dev/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:235:16)
    at Object.module.exports.onChange (/Users/jiku.dev/.atom/packages/activate-power-mode/lib/power-editor.coffee:57:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:727:20)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:712:19)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:622:12)
    at TextEditor.module.exports.TextEditor.setIndentationForBufferRow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:2751:26)
    at LanguageMode.module.exports.LanguageMode.autoIndentBufferRow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/language-mode.js:367:26)
    at TextEditor.module.exports.TextEditor.autoIndentBufferRow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:3550:32)
    at Selection.module.exports.Selection.insertText (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/selection.js:494:21)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1063:29
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1102:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1519:26)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1096:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:2497:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:2459:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1094:19)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1060:19)
    at TextEditor.object.(anonymous function) (/Users/jiku.dev/.atom/packages/language-babel/lib/insert-nl-jsx.coffee:31:18)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditor.module.exports.TextEditor.insertNewline (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1075:19)
    at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditor.commandRegistry.add.stopEventPropagationAndGroupUndo.editor:newline (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/register-default-commands.js:601:21)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/register-default-commands.js:661:34
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1519:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/register-default-commands.js:660:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
The error was thrown from the activate-power-mode package. ...
```

```
Uncaught TypeError: Cannot read property 'screenExtent' of undefined
/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/display-index/dist/screen-line-iterator.js:184
Hide Stack Trace
TypeError: Cannot read property 'screenExtent' of undefined
    at ScreenLineIterator.getScreenPositionWithMaxLineLength (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/display-index/dist/screen-line-iterator.js:184:29)
    at DisplayIndex.getScreenPositionWithMaxLineLength (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/display-index/dist/display-index.js:141:32)
    at DisplayLayer.module.exports.DisplayLayer.getRightmostScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1508:32)
    at TextEditor.module.exports.TextEditor.getRightmostScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:991:32)
    at TextEditor.module.exports.TextEditor.getLongestScreenRow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:999:19)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getScreenRowsToRender (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:389:37)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getScreenRangesToRender (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:405:25)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLines (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1351:20)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:119:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:265:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:195:12)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:221:9)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:3:61
This is likely a bug in Atom. ...
```

**Comment by sc0ttwad3** [comment]
@jiku +1 same type error (only when saving .less files in my case), same line number in the display-index module:
 
    AppData\Local\atom\app-1.11.0-beta3\resources\app.asar\node_modules\display-index\dist\screen-line-iterator.js:184

**Comment by int3h** [comment]
@50Wliu I've tracked down the trigger of this bug: calling `TextEditor::setTabLength(null)`. That seems to cause the exact exception listed here with 100% reproducibility.

Though I haven't tested it for sure, I'm willing to bet that commit c0cbb596662c6dd2f2293e76db83c54685c733ef introduced the bug. It changed `TokenizedBuffer::getTabLength()`'s implementation from `@tabLength ? @configSettings.tabLength` to just `@tabLength`. That's why `setTabLength(null)` wasn't throwing exceptions previously: `getTabLength()` would check if `@tabLength` was null, and return `@configSettings.tabLength` instead; now it will happily return `null`.

I haven't traced how the `null` flows back to `display-index`'s `ScreenLineIterator::getScreenPositionWithMaxLineLength()` (which is where the exception is actually thrown from), but hopefully this is enough to fix the immediate cause of the bug.

**Comment by 50Wliu** [comment]
Thanks for the detailed insight @int3h!  /cc @maxbrunsfeld

**Comment by Stanzilla** [comment]
This makes beta unusable, any updates here? @50Wliu

**Comment by AgentME** [comment]
I just ran into this in Atom v1.11.0

```
TypeError: Cannot read property 'screenExtent' of undefined
    at ScreenLineIterator.getScreenPositionWithMaxLineLength (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/display-index/dist/screen-line-iterator.js:184:29)
    at DisplayIndex.getScreenPositionWithMaxLineLength (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/display-index/dist/display-index.js:141:32)
    at DisplayLayer.module.exports.DisplayLayer.getRightmostScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1508:32)
    at TextEditor.module.exports.TextEditor.getRightmostScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:991:32)
    at TextEditor.module.exports.TextEditor.getLongestScreenRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:999:19)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getScreenRowsToRender (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:389:37)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getScreenRangesToRender (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:405:25)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLines (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1351:20)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:119:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:265:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:195:12)
    at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:304:21)
    at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:997:16)
    at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:85:22)
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:138:24)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:288:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:437:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:546:18
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by Alhadis** [comment]
Was having this issue with `auto-detect-indentation` too. Glad the breakage is fixed.

It strikes me as odd that something as simple and helpful as auto-detecting indent size isn't part of the core, to be honest. Having it as an editor setting would be very useful.
