### ISSUE TITLE
Beta 1.11.00 travis-ci build for Linux debian fails on executing atom-beta script

### ISSUE THREAD

**Issue by gandm** [atom/atom#12571]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Seems that atom beta 1.11.0 for debian has missing files? It fails to run `"$ATOM_SCRIPT_PATH" -v` and `"$APM_SCRIPT_PATH" -v` 

See my packages's travis-ci log [here](https://travis-ci.org/gandm/language-babel/jobs/156550748), it doesn't even start the atom install! The same batch of tests work on Linux Deb stable

### Steps to Reproduce

run a travis-ci 

**Expected behavior:** [What you expected to happen]

Atom to install and sepcs to run

**Actual behavior:** [What actually happened]

Errors

### Versions

1.11.0-beta

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by nathansobo** [comment]
@as-cii Maybe we could take a look at this tomorrow? Happy to pair on it.

**Comment by joefitzgerald** [comment]
This appears to be a packaging problem in the new release pipeline:

```
atom-amd64.deb = https://atom-installer.github.com/v1.10.0/atom-amd64.deb?s=1472580142&ext=.deb
atom-amd64.deb = https://atom-installer.github.com/v1.11.0-beta0/atom-amd64.deb?s=1472633594&ext=.deb
```

The MD5 for these two files are different, but the contents of the .deb files are identical. `stable` bits have been packaged up inside a file that is nominally a `beta` .deb, but actually isn't.

That the MD5's are different seems to indicate `./script/build` has been run twice, producing two separate .deb files in two separate paths, but using the same source path to do it. This would suggest that `CONFIG.channel` is not being set correctly for `https://github.com/atom/atom/blob/master/script/lib/create-debian-package.js` and potentially all of `./script/build`.

**Comment by as-cii** [comment]
Apologies to everyone for this. This is already fixed on master and we will release a hot fix later today that solves this problem.

**Comment by nathansobo** [comment]
Thanks to @as-cii and a streamlined release process, this is fixed in 1.11.0-beta1.

**Comment by gandm** [comment]
Still seem to have an issue. Travis-ci log gets
```
Running specs...
[2666:0901/134856:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Xlib:  extension "RANDR" missing on display ":99".
Xlib:  extension "RANDR" missing on display ":99".
[2666:0901/134858:INFO:CONSOLE(84)] "Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /home/travis/atom/usr/share/atom-beta/resources/app.asar.unpacked/node_modules/marker-index/build/Release/marker_index.node)
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/travis/atom/usr/share/atom-beta/resources/app.asar/node_modules/marker-index/dist/native/marker-index.js:9:33)
    at Module._compile (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/travis/atom/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:14:17)
    at Object.<anonymous> (/home/travis/atom/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:434:4)
    at Module._compile (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/travis/atom/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/history.js:6:17)
    at Object.<anonymous> (/home/travis/atom/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/history.js:450:4)
    at Module._compile (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)", source: /home/travis/build/atom/atom/out/app/src/initialize-test-window.coffee (84)
```

**Comment by Arcanemagus** [comment]
Filed #12587 since it looks like that's a new issue compared to the executable simply being renamed.
