### ISSUE TITLE
Atom v1.11.0-beta1 fails Linux CI builds

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#12587]
### Prerequisites

* [ ] ~~Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?~~ N/A
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] ~~Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?~~ N/A
* [ ] ~~Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?~~ N/A
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Atom v1.11.0-beta1 and -beta2 fail on Linux CI builds.

### Steps to Reproduce

1. Run a CI build (and most likely launch locally) on Linux.

**Expected behavior:** [What you expected to happen]

Build works as normal.

**Actual behavior:** [What actually happened]

Builds fail to run specs with the following message:

```text
[3391:0901/220443:INFO:CONSOLE(84)] "Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /home/travis/atom/usr/share/atom-beta/resources/app.asar.unpacked/node_modules/marker-index/build/Release/marker_index.node)
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/travis/atom/usr/share/atom-beta/resources/app.asar/node_modules/marker-index/dist/native/marker-index.js:9:33)
    at Module._compile (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/travis/atom/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:14:17)
    at Object.<anonymous> (/home/travis/atom/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:434:4)
    at Module._compile (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/travis/atom/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/history.js:6:17)
    at Object.<anonymous> (/home/travis/atom/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/history.js:450:4)
    at Module._compile (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)", source: /home/travis/build/atom/atom/out/app/src/initialize-test-window.coffee (84)
```

See https://travis-ci.org/AtomLinter/linter-reek/jobs/156574685 for an example.

### Versions

Atom v1.11.0-beta1 and Atomv1.11.0-beta2

_Note: First reported by @gandm here https://github.com/atom/atom/issues/12571#issuecomment-244084543_

**Comment by Arcanemagus** [comment]
Looks like it's not _all_ Linux beta builds. The following are all Atom v1.11.0-beta2 builds.

Breaking build:

* https://travis-ci.org/AtomLinter/linter-reek/jobs/156574685

Passing build:

* https://travis-ci.org/AtomLinter/linter-xmllint/jobs/156876526

**Comment by Arcanemagus** [comment]
Can't reproduce this in an Ubuntu 16.04 VM locally unfortunately.

**Comment by as-cii** [comment]
Apologies for this, we assumed using a newer version of gcc was okay, but it turns out we need to be backwards compatible with Ubuntu Precise's default stdlibc++.

I have fixed it in #12589 and the fix will go out with Atom 1.11-beta2. 🚀

**Comment by Arcanemagus** [comment]
Awesome, thanks! Finding stuff like that is what the beta channel is for after all 😉.

**Comment by Arcanemagus** [comment]
Confirmed that the failing builds are now passing on `-beta3`.
