### ISSUE TITLE
Unable to run Atom in dev mode on master

### ISSUE THREAD

**Issue by abe33** [atom/atom#12631]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Using the latest version of master (`1.11.0-dev-6d25cc6`) it is no longer possible to run Atom in dev mode or to run package's specs.

<details>
2016-09-08 14:13:46.048 Atom[53132:7021177] Module version mismatch. Expected 47, got 49.
2016-09-08 14:13:46.130 Atom[53132:7021177] Error: Module version mismatch. Expected 47, got 49.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/cedric/github/atom/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/Users/cedric/github/atom/node_modules/pathwatcher/lib/main.js:218:4)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/cedric/github/atom/out/app/src/config.coffee:7:15)
    at Object.<anonymous> (/Users/cedric/github/atom/out/app/src/config.coffee:1:1)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/cedric/github/atom/out/app/src/main-process/atom-application.coffee:6:10)
    at Object.<anonymous> (/Users/cedric/github/atom/out/app/src/main-process/atom-application.coffee:1:1)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
</details>

### Steps to Reproduce

1. Run `atom -d -f .` or use the `Run package specs` command 
2. Notice how nothing appears

**Expected behavior:** [What you expected to happen]

- With `atom -d` a new Atom window should open in dev mode.
- With `Run package specs`, a new window with the test runner should appear.

**Actual behavior:** [What actually happened]

Nothing happen at all. With `atom -d` the app starts (a new icon appears in the dock) but the window never appear. Only with the `-f` option the cause of the issue can be discovered.

### Versions

```
> atom --version
Atom    : 1.11.0-dev-6d25cc6
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

> apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.5.4
```

**Comment by as-cii** [comment]
@abe33 that's most likely related to the new Electron version. Can you try deleting the `.dependencies-fingerprint` within the `node_modules` directory and run `script/build --install` again?

**Comment by abe33** [comment]
Trying it now. 

For the record, I did try to `script/clean` then `script/build` without success.

**Comment by abe33** [comment]
Ok, it worked! 

Maybe removing the `.dependencies-fingerprint` file should be done in the `script/clean`?
