### ISSUE TITLE
Windows installer not setup the shell menu items.

### ISSUE THREAD

**Issue by xpol** [atom/atom#12667]
### Description

Windows installer **AtomSetup.exe** not setup the shell menu item (Open with Atom).

The installer log `SquirrelSetup.log`:

```
2016-09-12 13:51:11> Program: Starting Squirrel Updater: --install .
2016-09-12 13:51:11> Program: Starting install, writing to C:\Users\xxx\AppData\Local\SquirrelTemp
2016-09-12 13:51:11> Program: About to install to: C:\Users\xxx\AppData\Local\atom
2016-09-12 13:51:11> Program: Install path C:\Users\xxx\AppData\Local\atom already exists, burning it to the ground
2016-09-12 13:51:13> IEnableLogger: Failed to copy Update.exe to C:\Users\xxx\AppData\Local\atom\Update.exe: System.UnauthorizedAccessException: Access to the path 'C:\Users\xxx\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass36.<Install>b__2d()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
2016-09-12 13:51:13> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\xxx\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass36.<Install>b__2d()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__38.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\xxx\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass36.<Install>b__2d()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__38.MoveNext()<---

2016-09-12 13:51:44> Program: Starting Squirrel Updater: --install .
2016-09-12 13:51:44> Program: Starting install, writing to C:\Users\xxx\AppData\Local\SquirrelTemp
2016-09-12 13:51:44> Program: About to install to: C:\Users\xxx\AppData\Local\atom
2016-09-12 13:51:44> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\xxx\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
2016-09-12 13:51:44> CheckForUpdateImpl: Reading RELEASES file from C:\Users\xxx\AppData\Local\SquirrelTemp
2016-09-12 13:51:44> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-09-12 13:51:45> ApplyReleasesImpl: Writing files to app directory: C:\Users\xxx\AppData\Local\atom\app-1.10.2
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\content_resources_200_percent.pak to C:\Users\xxx\AppData\Local\atom\app-1.10.2\content_resources_200_percent.pak
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\d3dcompiler_47.dll to C:\Users\xxx\AppData\Local\atom\app-1.10.2\d3dcompiler_47.dll
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\content_shell.pak to C:\Users\xxx\AppData\Local\atom\app-1.10.2\content_shell.pak
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\atom.exe to C:\Users\xxx\AppData\Local\atom\app-1.10.2\atom.exe
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\ffmpeg.dll to C:\Users\xxx\AppData\Local\atom\app-1.10.2\ffmpeg.dll
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\icudtl.dat to C:\Users\xxx\AppData\Local\atom\app-1.10.2\icudtl.dat
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\libEGL.dll to C:\Users\xxx\AppData\Local\atom\app-1.10.2\libEGL.dll
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\libGLESv2.dll to C:\Users\xxx\AppData\Local\atom\app-1.10.2\libGLESv2.dll
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\LICENSE to C:\Users\xxx\AppData\Local\atom\app-1.10.2\LICENSE
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\msvcp120.dll to C:\Users\xxx\AppData\Local\atom\app-1.10.2\msvcp120.dll
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\msvcr120.dll to C:\Users\xxx\AppData\Local\atom\app-1.10.2\msvcr120.dll
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\natives_blob.bin to C:\Users\xxx\AppData\Local\atom\app-1.10.2\natives_blob.bin
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\snapshot_blob.bin to C:\Users\xxx\AppData\Local\atom\app-1.10.2\snapshot_blob.bin
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\ui_resources_200_percent.pak to C:\Users\xxx\AppData\Local\atom\app-1.10.2\ui_resources_200_percent.pak
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\vccorlib120.dll to C:\Users\xxx\AppData\Local\atom\app-1.10.2\vccorlib120.dll
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\node.dll to C:\Users\xxx\AppData\Local\atom\app-1.10.2\node.dll
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\squirrel.exe to C:\Users\xxx\AppData\Local\atom\app-1.10.2\squirrel.exe
2016-09-12 13:51:52> ApplyReleasesImpl: Moving file C:\Users\xxx\AppData\Local\atom\app-1.10.2\lib\net45\xinput1_3.dll to C:\Users\xxx\AppData\Local\atom\app-1.10.2\xinput1_3.dll
2016-09-12 13:51:52> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\xxx\AppData\Local\atom\app-1.10.2\atom.exe]
2016-09-12 13:51:56> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-09-12 13:51:56> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2016-09-12 13:51:56> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2016-09-12 13:51:56> ApplyReleasesImpl: Examining Pin: SourceTree.lnk
2016-09-12 13:51:56> ApplyReleasesImpl: Examining Pin: Visual Studio 2015.lnk
2016-09-12 13:51:56> ApplyReleasesImpl: Fixing up tray icons
2016-09-12 13:51:56> ApplyReleasesImpl: cleanDeadVersions: for version 1.10.2
2016-09-12 13:51:56> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.10.2
```

### Versions

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.9.2.windows.1
visual studio 2015

**Comment by xpol** [comment]
PS, My OS is Windows 10 RS1.

**Comment by damieng** [comment]
Open with Atom is not setup by default any more. You can turn it on in Atom
settings system tab.

**Comment by damieng** [comment]
Let me know if that setting doesn't work for you.  Once you turn it on future versions should also remember the state.
