### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by guyskk** [atom/atom#12766]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 1.4.0
**System**: linux 4.7.4-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

```
At /usr/lib/electron/resources/electron.asar/renderer/api/remote.js:98

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at setObjectMembers (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:98:22)
    at loadRemoteProperties (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:164:5)
    at Object.getOwnPropertyDescriptor (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:179:7)
    at undefined.descriptor.get (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:118:32)
    at metaToValue (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:241:32)
    at ApplicationDelegate.module.exports.ApplicationDelegate.getCurrentWindow (/usr/lib/atom/src/application-delegate.js:33:21)
    at AtomEnvironment.module.exports.AtomEnvironment.getCurrentWindow (/usr/lib/atom/src/atom-environment.js:565:39)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/usr/lib/atom/src/atom-environment.js:635:28)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/usr/lib/atom/src/atom-environment.js:670:36)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/usr/lib/atom/src/window-event-handler.js:182:35)
    at /usr/lib/atom/src/window-event-handler.js:3:61
```

### Commands

```
  2x -8:25.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:42.1.0 core:backspace (atom-text-editor.editor.is-focused)
  6x -2:31 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.dockerfile": [
        "dockerfile"
      ]
    },
    "disabledPackages": [
      "spell-check",
      "linter-eslint",
      "linter-less",
      "symbols-tree-view"
    ]
  },
  "editor": {
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.12 (active)
highlight-selected, v0.11.2 (active)
language-docker, v1.1.7 (active)
language-restructuredtext, v1.0.0 (active)
language-typescript-grammars-only, v1.5.0 (active)
language-vue, v0.17.0 (active)
linter, v1.11.16 (active)
linter-eslint, v7.3.2 (inactive)
linter-flake8, v1.13.4 (active)
linter-jshint, v2.1.0 (active)
linter-less, v2.6.0 (inactive)
minimap, v4.25.0 (active)
pigments, v0.35.0 (active)
project-plus, v0.9.0 (active)
symbols-tree-view, v0.13.2 (inactive)
toggle-quotes, v1.0.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
> Electron Version: 1.4.0

This is an unsupported Electron version.  Please uninstall Atom and redownload it from https://atom.io.

https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md

**Comment by viniciusarcanjo** [comment]
Hi guyskk, I've stumbled upon on the same issue, since I'm running Arch Linux and I've updated my packages recently. 

I downgraded to atom version 1.10.2-2 and electron 1.3.5-2 and I haven't seen this error anymore since then.

**Comment by janosimas** [comment]
I installed from atom.io and have the same problem

**Comment by 50Wliu** [comment]
@janosimas Sorry to hear that!  Can you please create a new issue so that we can track it separately?  Thanks!

**Comment by janosimas** [comment]
@50Wliu How can I create an issue with the atom information?
when I get the error atom gives me this link.

Is an intermittent error, most of the times I get when I reload the atom when I'm developing a package.

**Comment by 50Wliu** [comment]
There should be a "copy" icon next to the report button.

**Comment by Alhadis** [comment]
FWIW, I've been getting this a lot lately too. It only flashes extremely briefly in the dev-console when I'm reloading, but it's noticeable. I caught it on screen-capture:

<img src="https://cloud.githubusercontent.com/assets/2346707/20818022/37aad226-b87f-11e6-8629-d80bbebfbee7.png" width="756" alt="Figure 1" />

Deactivating the package doesn't reproduce the error, which proves it isn't stemming from my code.

@janosimas Would you happen to be running [`Task`](https://atom.io/docs/api/v1.12.6/Task) instances in your package, perchance? I'm wondering if this might be related to Electron's IPC-handling:

```js
// Populate object's members from descriptors.
// The |ref| will be kept referenced by |members|.
// This matches |getObjectMemebers| in rpc-server.
const setObjectMembers = function (ref, object, metaId, members) {
	for (let member of members) {
		if (object.hasOwnProperty(member.name)) continue
```

**Comment by 50Wliu** [comment]
Like I said above, if you're running into this please create a new issue.

**Comment by janosimas** [comment]
@Alhadis Create another issue where we can talk, I'm a little busy so didn't put time to reproduce the error.
I'm not using Task.
