### ISSUE TITLE
SyntaxError: Invalid regular expression: /^()|)\..*$/: Unmatched ')'    at RegExp (native)    a...

### ISSUE THREAD

**Issue by stuart-williams** [atom/atom#12764]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core

### Stack Trace

SyntaxError: Invalid regular expression: /^()|)\..*$/: Unmatched ')'
    at RegExp (native)
    at /Users/willis114/workspace/relative-require/lib/find-matching-modules.js:24:19
    at Function.promise (/Users/willis114/workspace/relative-require/node_modules/q/q.js:682:9)
    at module.exports (/Users/willis114/workspace/relative-require/lib/find-matching-modules.js:23:12)
    at loadProjectModules (/Users/willis114/workspace/relative-require/lib/text-editor-require.js:51:12)
    at _fulfilled (/Users/willis114/workspace/relative-require/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/willis114/workspace/relative-require/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/willis114/workspace/relative-require/node_modules/q/q.js:796:13)
    at /Users/willis114/workspace/relative-require/node_modules/q/q.js:604:44
    at runSingle (/Users/willis114/workspace/relative-require/node_modules/q/q.js:137:13)
    at flush (/Users/willis114/workspace/relative-require/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```
At undefined

undefined
```

### Commands

```
  5x -0:24.7.0 relative-require:require (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint",
      "linter-jshint",
      "typewriter-sounds",
      "project-manager"
    ]
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.12 (inactive)
atom-csscomb, v2.0.4 (inactive)
atom-ternjs, v0.15.0 (active)
emmet, v2.4.3 (active)
esformatter, v2.0.1 (inactive)
file-icons, v1.7.19 (active)
file-types, v0.5.4-p1 (active)
git-blame, v0.4.11 (inactive)
language-babel, v2.42.0 (active)
linter, v1.11.16 (active)
linter-eslint, v7.3.2 (active)
linter-jsonlint, v1.3.0 (active)
monokai-seti, v0.7.0 (inactive)
pigments, v0.35.0 (active)
split-diff, v1.0.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
eslint-tab-length, v0.3.14 (active)
relative-require, v1.6.11 (active)
eslint-tab-length, v0.3.14 (active)
relative-require, v1.6.11 (active)
```

**Comment by stuart-williams** [comment]
Sorry, didn't mean to raise here
