### ISSUE TITLE
Folding error in hjson file

### ISSUE THREAD

**Issue by akshatjain1995** [atom/atom#12918]
**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: empty char-class

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:12

Error: empty char-class
    at Error (native)
    at new OnigRegExp (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/oniguruma/lib/onig-reg-exp.js:9:22)
    at LanguageMode.module.exports.LanguageMode.getRegexForProperty (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:411:28)
    at LanguageMode.module.exports.LanguageMode.foldEndRegexForScopeDescriptor (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:430:19)
    at LanguageMode.module.exports.LanguageMode.rowRangeForCodeFoldAtBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:208:81)
    at LanguageMode.module.exports.LanguageMode.rowRangeForFoldAtBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:162:25)
    at LanguageMode.module.exports.LanguageMode.foldBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:148:30)
    at TextEditor.module.exports.TextEditor.foldBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2919:32)
    at LineNumberGutterComponent.module.exports.LineNumberGutterComponent.onClick (/Applications/Atom.app/Contents/Resources/app.asar/src/line-number-gutter-component.js:137:30)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/line-number-gutter-component.js:3:61)
```

### Commands

```
     -2:58.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:51.8.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -2:50.6.0 core:save (atom-text-editor.editor.is-focused)
  3x -2:20.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:17.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -2:17.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:17 core:move-right (atom-text-editor.editor.is-focused)
     -2:16.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:16 core:save (atom-text-editor.editor.is-focused)
 13x -2:04.5.0 core:undo (atom-text-editor.editor.is-focused)
     -2:02.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:46.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:46.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:46.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:44.3.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:38 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "themes": [
      "atom-material-ui",
      "monokai-seti"
    ]
  },
  "editor": {
    "fontFamily": "Monaco",
    "fontSize": 17,
    "invisibles": {},
    "scrollPastEnd": true,
    "tabLength": 4,
    "zoomFontWhenCtrlScrolling": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.2 (active)
coffee-compile, v0.21.1 (active)
emmet, v2.4.3 (active)
git-line, v0.5.0 (inactive)
language-hjson, v0.3.0 (active)
language-javascript-jsx, v0.3.7 (active)
less-autocompile, v1.0.0 (active)
linter, v1.11.14 (active)
linter-csslint, v1.3.2 (active)
linter-htmlhint, v1.2.1 (active)
linter-jshint, v2.1.0 (active)
linter-jsonlint, v0.1.4 (active)
linter-less, v2.5.0 (active)
linter-php, v1.0.3 (active)
linter-write-good, v0.6.1 (active)
monokai, v0.18.0 (inactive)
monokai-seti, v0.7.0 (active)
pigments, v0.29.2 (active)
python-indent, v0.4.3 (active)
python-snippets, v1.9.0 (active)
react, v0.16.0 (active)
react-snippets, v0.4.2 (active)
seti-ui, v1.3.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please report this to the language-hjson repository.
