### ISSUE TITLE
Atom 1.11.1 build fails on Arch Linux and Ubuntu 16.04, giving the same error message

### ISSUE THREAD

**Issue by fusion809** [atom/atom#12952]
Hi,

I have noticed that on Arch Linux and Ubuntu 16.04.1 building Atom 1.11.1 fails, although building Atom 1.10.2 went without a hitch. Specifically whenever I run `script/build --create-debian-package` on Ubuntu 16.04 I get the build error:

```bash
$ script/build --create-debian-package                   
Node:   v6.7.0
Npm:    v3.10.3
Installing script dependencies
make: execvp: /home/fusion809/Documents/CodeLite/CPP-Math-Projects: Permission denied
make: *** [Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/ia32_implicit.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-42-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fusion809/Programs/atom-1.11.1/script/node_modules/minidump
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 4.4.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "--loglevel=error" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minidump@0.9.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs minidump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fusion809/Programs/atom-1.11.1/script/npm-debug.log
child_process.js:506
    throw err;
    ^

Error: Command failed: npm --loglevel=error install
make: execvp: /home/fusion809/Documents/CodeLite/CPP-Math-Projects: Permission denied
make: *** [Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/ia32_implicit.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-42-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fusion809/Programs/atom-1.11.1/script/node_modules/minidump
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 4.4.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "--loglevel=error" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minidump@0.9.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs minidump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fusion809/Programs/atom-1.11.1/script/npm-debug.log

    at checkExecSyncError (child_process.js:483:13)
    at Object.execFileSync (child_process.js:503:13)
    at module.exports (/home/fusion809/Programs/atom-1.11.1/script/lib/install-script-dependencies.js:10:16)
    at Object.<anonymous> (/home/fusion809/Programs/atom-1.11.1/script/bootstrap:26:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
```

I have tried running this command on an Arch Linux installation, with dpkg, fakeroot and all other packages required to build a Debian package for Atom, but it too failed. My npm version is 3.10.7 ( know that 3.10.8 is out, but I have 3.10.7 installed because 3.10.8 causes build errors with Visual Studio Code) and my Node.js version is 6.7.0 on both my Linux workstations (i.e., my Ubuntu 16.04 install and my Arch Linux install are both using the same versions of npm and Node.js). If you are wondering why `~/Documents/CodeLite/CPP-Math-Projects/` appears in this build error, well I don't know but I have set some custom environment variables namely:

```bash
DC=/home/fusion809/Documents/CodeLite
CC=/home/fusion809/Documents/CodeLite/CPP-Math-Projects
CFE=/home/fusion809/Documents/CodeLite/CPP-Math-Projects/Simple-Pendulum
CFA=/home/fusion809/Documents/CodeLite/CPP-Math-Projects/Simple-Pendulum-Adjusted
CSP=/home/fusion809/Documents/CodeLite/C-Math-Projects
```

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
Oops never mind when I unset those environment variables the build goes fine, sorry I'm closing this issue.
