### ISSUE TITLE
Building Atom 1.12.0-beta1 on Arch Linux fails APM issues

### ISSUE THREAD

**Issue by fusion809** [atom/atom#12973]
Hi,

I've been trying to build Atom 1.12.0-beta1 on Arch Linux but it failed giving the error message:

``` bash
Installing script dependencies
Installing apm
/home/fusion809/GitHub/mine/packaging/atom-editor-beta/src/atom-1.12.0-beta1/apm/node_modules/atom-package-manager/bin/apm: line 35: /home/fusion809/GitHub/mine/packaging/atom-editor-beta/src/atom-1.12.0-beta1/apm/node_modules/atom-package-manager/bin/node: No such file or directory
child_process.js:506
    throw err;
    ^

Error: Command failed: /home/fusion809/GitHub/mine/packaging/atom-editor-beta/src/atom-1.12.0-beta1/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:483:13)
    at Object.execFileSync (child_process.js:503:13)
    at module.exports (/home/fusion809/GitHub/mine/packaging/atom-editor-beta/src/atom-1.12.0-beta1/script/lib/install-atom-dependencies.js:19:16)
    at Object.<anonymous> (/home/fusion809/GitHub/mine/packaging/atom-editor-beta/src/atom-1.12.0-beta1/script/bootstrap:28:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

Versions:

``` bash
$ node --version
v6.8.0
$ npm --version
3.10.7
```

Thanks for your time,
Brenton

**Comment by Costallat** [comment]
Same here, but for beta-4 and beta-5, don't know for the others "beta".

script/build
Node:   v7.0.0
Npm:    v3.10.5
Installing script dependencies
Installing apm
child_process.js:145
    throw new TypeError('Incorrect value of args option');
    ^

TypeError: Incorrect value of args option
    at Object.exports.execFile (child_process.js:145:11)
    at Object.exports.exec (child_process.js:108:18)
    at Object.<anonymous> (/home/renato/Downloads/atom-1.12.0-beta5/apm/node_modules/atom-package-manager/script/postinstall.js:10:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
npm ERR! Linux 4.4.21-gentoo
npm ERR! argv "/usr/bin/node" "/home/renato/Downloads/atom-1.12.0-beta5/script/node_modules/.bin/npm" "--global-style" "--loglevel=error" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-package-manager@1.12.5 install: `node script/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-package-manager@1.12.5 install script 'node script/postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-package-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-package-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-package-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/renato/Downloads/atom-1.12.0-beta5/apm/npm-debug.log
npm ERR! code 1
child_process.js:511
    throw err;
    ^

Error: Command failed: /home/renato/Downloads/atom-1.12.0-beta5/script/node_modules/.bin/npm --global-style --loglevel=error install
child_process.js:145
    throw new TypeError('Incorrect value of args option');
    ^

TypeError: Incorrect value of args option
    at Object.exports.execFile (child_process.js:145:11)
    at Object.exports.exec (child_process.js:108:18)
    at Object.<anonymous> (/home/renato/Downloads/atom-1.12.0-beta5/apm/node_modules/atom-package-manager/script/postinstall.js:10:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
npm ERR! Linux 4.4.21-gentoo
npm ERR! argv "/usr/bin/node" "/home/renato/Downloads/atom-1.12.0-beta5/script/node_modules/.bin/npm" "--global-style" "--loglevel=error" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-package-manager@1.12.5 install: `node script/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-package-manager@1.12.5 install script 'node script/postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-package-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-package-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-package-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/renato/Downloads/atom-1.12.0-beta5/apm/npm-debug.log
npm ERR! code 1

    at checkExecSyncError (child_process.js:488:13)
    at Object.execFileSync (child_process.js:508:13)
    at module.exports (/home/renato/Downloads/atom-1.12.0-beta5/script/lib/install-apm.js:10:16)
    at Object.<anonymous> (/home/renato/Downloads/atom-1.12.0-beta5/script/bootstrap:27:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)

**Comment by Costallat** [comment]
I found the problem, is on the file:
/atom-1.12.0-beta5/apm/node_modules/atom-package-manager/script/postinstall.js

you need to change line 10:

var child = cp.exec(script, [], {stdio: ['pipe', 'pipe', 'pipe']})

to

var child = cp.exec(script, {stdio: ['pipe', 'pipe', 'pipe']})

This happens because when you use "[]" this is an empty thing and not a "null" thing,
so in the nodejs - child_process.js( https://github.com/nodejs/node/blob/master/lib/child_process.js ), it will drop in this condition:
 
 if (pos < arguments.length && arguments[pos] != null) {
    if (typeof arguments[pos] !== 'object') {
      throw new TypeError('Incorrect value of args option');
    } else {
      options = util._extend({}, arguments[pos++]);
    }
}

Because it's not "null" and it is not an object!

I'm not an JS expert, so I don't know if this is right, but it make sense!


How to fix:

Start the installation process, and keep refreshing the /atom-1.12.0-beta5/apm/node_modules/ folder until you see the "atom-package-manager"

Open the script/postinstall.js and change line 10 from:

var child = cp.exec(script, [], {stdio: ['pipe', 'pipe', 'pipe']})

to

var child = cp.exec(script, {stdio: ['pipe', 'pipe', 'pipe']})

Done!

You need to do this "fast" because if the installation process get in this line before you, it will throw the error and remove this folder.

**Comment by mbellgb** [comment]
Can confirm that @Costallat's workaround worked for me.

**Comment by DanSGiesbrecht** [comment]
Can also confirm that @Costallat's workaround worked for me (Atom 1.14.0, Linux Mint)

**Comment by thomasjo** [comment]
Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).
