### ISSUE TITLE
Cant install atom

### ISSUE THREAD

**Issue by HeathAA** [atom/atom#12988]
[Cant install atom](https://discuss.atom.io/t/trying-to-install-atom-on-windows-10-get-nothing/34605/3)

SquirrelSetup.Log:

2016-07-20 20:53:39> Program: Starting Squirrel Updater: --install .
2016-07-20 20:53:39> Program: Starting install, writing to C:\Users\heath\AppData\Local\SquirrelTemp
2016-07-20 20:53:39> Program: About to install to: C:\Users\heath\AppData\Local\atom
2016-07-20 20:53:39> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\heath\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3d.MoveNext()
2016-07-20 20:53:39> CheckForUpdateImpl: Reading RELEASES file from C:\Users\heath\AppData\Local\SquirrelTemp
2016-07-20 20:53:39> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-07-20 20:53:39> ApplyReleasesImpl: Writing files to app directory: C:\Users\heath\AppData\Local\atom\app-1.5.3
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\content_shell.pak to C:\Users\heath\AppData\Local\atom\app-1.5.3\content_shell.pak
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\atom.exe to C:\Users\heath\AppData\Local\atom\app-1.5.3\atom.exe
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\content_resources_200_percent.pak to C:\Users\heath\AppData\Local\atom\app-1.5.3\content_resources_200_percent.pak
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\d3dcompiler_47.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\d3dcompiler_47.dll
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\icudtl.dat to C:\Users\heath\AppData\Local\atom\app-1.5.3\icudtl.dat
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\libEGL.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\libEGL.dll
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\libGLESv2.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\libGLESv2.dll
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\LICENSE to C:\Users\heath\AppData\Local\atom\app-1.5.3\LICENSE
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\msvcp120.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\msvcp120.dll
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\msvcr120.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\msvcr120.dll
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\natives_blob.bin to C:\Users\heath\AppData\Local\atom\app-1.5.3\natives_blob.bin
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\node.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\node.dll
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\pdf.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\pdf.dll
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\squirrel.exe to C:\Users\heath\AppData\Local\atom\app-1.5.3\squirrel.exe
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\vccorlib120.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\vccorlib120.dll
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\snapshot_blob.bin to C:\Users\heath\AppData\Local\atom\app-1.5.3\snapshot_blob.bin
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\ui_resources_200_percent.pak to C:\Users\heath\AppData\Local\atom\app-1.5.3\ui_resources_200_percent.pak
2016-07-20 20:53:46> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\xinput1_3.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\xinput1_3.dll
2016-07-20 20:53:46> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\heath\AppData\Local\atom\app-1.5.3\atom.exe]
2016-07-20 20:53:51> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-07-20 20:53:51> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
2016-07-20 20:53:51> ApplyReleasesImpl: Fixing up tray icons
2016-07-20 20:53:51> ApplyReleasesImpl: cleanDeadVersions: for version 1.5.3
2016-07-20 20:53:51> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.5.3
2016-07-20 20:55:41> Program: Starting Squirrel Updater: --install .
2016-07-20 20:55:41> Program: Starting install, writing to C:\Users\heath\AppData\Local\SquirrelTemp
2016-07-20 20:55:41> Program: About to install to: C:\Users\heath\AppData\Local\atom
2016-07-20 20:55:41> Program: Install path C:\Users\heath\AppData\Local\atom already exists, burning it to the ground
2016-07-20 20:55:41> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\heath\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3d.MoveNext()
2016-07-20 20:55:41> CheckForUpdateImpl: Reading RELEASES file from C:\Users\heath\AppData\Local\SquirrelTemp
2016-07-20 20:55:41> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-07-20 20:55:41> ApplyReleasesImpl: Writing files to app directory: C:\Users\heath\AppData\Local\atom\app-1.5.3
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\d3dcompiler_47.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\d3dcompiler_47.dll
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\content_shell.pak to C:\Users\heath\AppData\Local\atom\app-1.5.3\content_shell.pak
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\atom.exe to C:\Users\heath\AppData\Local\atom\app-1.5.3\atom.exe
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\content_resources_200_percent.pak to C:\Users\heath\AppData\Local\atom\app-1.5.3\content_resources_200_percent.pak
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\icudtl.dat to C:\Users\heath\AppData\Local\atom\app-1.5.3\icudtl.dat
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\libEGL.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\libEGL.dll
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\libGLESv2.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\libGLESv2.dll
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\LICENSE to C:\Users\heath\AppData\Local\atom\app-1.5.3\LICENSE
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\msvcp120.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\msvcp120.dll
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\msvcr120.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\msvcr120.dll
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\natives_blob.bin to C:\Users\heath\AppData\Local\atom\app-1.5.3\natives_blob.bin
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\node.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\node.dll
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\pdf.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\pdf.dll
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\squirrel.exe to C:\Users\heath\AppData\Local\atom\app-1.5.3\squirrel.exe
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\vccorlib120.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\vccorlib120.dll
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\snapshot_blob.bin to C:\Users\heath\AppData\Local\atom\app-1.5.3\snapshot_blob.bin
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\ui_resources_200_percent.pak to C:\Users\heath\AppData\Local\atom\app-1.5.3\ui_resources_200_percent.pak
2016-07-20 20:55:47> ApplyReleasesImpl: Moving file C:\Users\heath\AppData\Local\atom\app-1.5.3\lib\net45\xinput1_3.dll to C:\Users\heath\AppData\Local\atom\app-1.5.3\xinput1_3.dll
2016-07-20 20:55:48> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\heath\AppData\Local\atom\app-1.5.3\atom.exe]
2016-07-20 20:55:51> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-07-20 20:55:51> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
2016-07-20 20:55:51> ApplyReleasesImpl: Fixing up tray icons
2016-07-20 20:55:51> ApplyReleasesImpl: cleanDeadVersions: for version 1.5.3
2016-07-20 20:55:51> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.5.3
2016-09-21 12:32:26> Program: Starting Squirrel Updater: --install .
2016-09-21 12:32:26> Program: Starting install, writing to C:\Users\heath\AppData\Local\SquirrelTemp
2016-09-21 12:32:26> Program: About to install to: C:\Users\heath\AppData\Local\atom
2016-09-21 12:32:26> Program: Install path C:\Users\heath\AppData\Local\atom already exists, burning it to the ground
2016-09-21 12:32:28> IEnableLogger: Failed to copy Update.exe to C:\Users\heath\AppData\Local\atom\Update.exe: System.UnauthorizedAccessException: Access to the path 'C:\Users\heath\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass36.<Install>b__2d()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
2016-09-21 12:32:28> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\heath\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass36.<Install>b__2d()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__38.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\heath\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass36.<Install>b__2d()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__38.MoveNext()<---

**Comment by Zireael07** [comment]
> Access to the path 'C:\Users\heath\AppData\Local\atom\Update.exe' is denied.

That's your problem right here. Disable any AV software you're using. If no AV running, run Atom as administrator.

**Comment by HeathAA** [comment]
I disable  before but that didnt do anything

**Comment by HeathAA** [comment]
Ok after 2 restarts and disableing the AV its installed, but the net problem is that once the AV is active and i try to open Atom, it wont open, i have to disable the AV to run in.

**Comment by Zireael07** [comment]
Try excluding C:\Users\heath\AppData\Local\atom\

What is your AV?

**Comment by HeathAA** [comment]
Bit-defender

Also i excluded atom Update.exe atom.exe Squirrel.exe and add the folder, but it still wont launch unless i disable the AV.

**Comment by damieng** [comment]
We recently improved the code signing by upgrading to sha2 and timestamping the executable. This may relax BitDefender's aggressive policy towards our files.

If that doesn't work I'd recommend downloading the zip file version and manually extracting it.
