### ISSUE TITLE
Cannot build from source on macOS

### ISSUE THREAD

**Issue by akulbe** [atom/atom#12990]
I am attempting to build Atom from the latest git checkout.
commit 4852b5f42b526b74b2fa2dd7d47c272a74ebc56e

The error messages talks about not being able to find runas.node

Installing language-text@0.7.1 ✓
Installing language-todo@0.29.1 ✓
Installing language-toml@0.18.1 ✓
Installing language-xml@0.34.12 ✓
Installing language-yaml@0.27.1 ✓
Wrote Dependencies Fingerprint: /Users/aaron/Code/atom/node_modules/.dependencies-fingerprint 633079947f09a8e4714c852761f61a7a48fff4e4
module.js:471
    throw err;
    ^

Error: Cannot find module '../build/Release/runas.node'
  at Function.Module._resolveFilename (module.js:469:15)
  at Function.Module._load (module.js:417:25)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/aaron/Code/atom/script/node_modules/runas/lib/runas.js:4:11)
  at Object.<anonymous> (/Users/aaron/Code/atom/script/node_modules/runas/lib/runas.js:47:4)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (/Users/aaron/Code/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/aaron/Code/atom/script/lib/install-application.js:5:15)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (/Users/aaron/Code/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/aaron/Code/atom/script/build:38:28)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3

```
  637.09 real       364.84 user        98.01 sys
```

**Comment by thomasjo** [comment]
I ran into the same problem earlier myself. Problem seems to have been upstream, but resolved now. Try doing a `script/clean` first, then start a new build.

**Comment by akulbe** [comment]
I've tried that multiple times. I even tried removing the repo, and cloning it over again. Same results.

**Comment by Regaddi** [comment]
Getting the same error at the exact same position (right after language-yaml and dependencies fingerprint).
I am on latest master commit [b0ee989](https://github.com/atom/atom/commit/b0ee989996eb1e5bfd67aa863e45cdaae70abd19).

Running on a Nexus 5 with [MaruOS 0.3](http://maruos.com/) (Debian Jessie, ARMv7, Qualcomm Snapdragon S800).

Will try to run `script/clean` and repeat afterwards.
Building takes a while on this mobile device 😄

**Comment by Regaddi** [comment]
Worked after `script/clean`.

**Comment by gappleto97** [comment]
Getting same error on NVidia Shield Tablet (ARMv7 Ubuntu 14.04)

Built off of current master commit (3ca269e44d6abdc22deb4ebda87c65fe09ded90a).

Going to try `script/clean` followed by a rebuild. Please advise.

**Comment by diegonc** [comment]
Hello, I was having the same issue (but on Windows) and could resolve it by doing:
```
atom\atom> cd script
atom\atom\script> npm install runas
```
For some reason during the script dependencies installation triggered by `script\build` the runas native module was not compiled; but the script kept going and failed later.

**Comment by fyee** [comment]
@diegonc  use 
```
npm install runas 
```
solved the problem

**Comment by sme-gmbh** [comment]
Same problem on Fedora 25
```
uname -a
Linux jule 4.8.15-300.fc25.x86_64 #1 SMP Thu Dec 15 23:10:23 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
```
[pdiener@jule atom]$ ./script/build --create-rpm-package
Node:	v6.10.3
Npm:	v3.10.5
Installing script dependencies
Installing apm
Installing modules ✓
Wrote Dependencies Fingerprint: /home/pdiener/Projekte/Software/PC/atom/node_modules/.dependencies-fingerprint 6f9ab2110b7aebbd3dbc5a9618a11b5c91daba95
module.js:471
    throw err;
    ^

Error: Cannot find module '../build/Release/runas.node'
  at Function.Module._resolveFilename (module.js:469:15)
  ...
```

Executing 
`npm install runas`
in the root directory of atom did not solve the problem.

`atom\script> npm install runas`
solved the problem.
