### ISSUE TITLE
Uncaught Error: Position (36.2, Infinity) is less than the current token's start ((37, 0))

### ISSUE THREAD

**Issue by DeanmvSG** [atom/atom#13182]
1. Opened a file and this error was thrown.  

Have been using beta all day and this is the first time it did it upon opening a file.  Nothing different about this one file compared to other files I have been in and out of across the day.

**Atom Version**: 1.13.0-beta0
**Electron Version**: 1.3.6
**System**: Mac OS X 10.12.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Position (36.2, Infinity) is less than the current token's start ((37, 0))

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/display-index/dist/token-iterator.js:251

Error: Position (36.2, Infinity) is less than the current token's start ((37, 0))
    at TokenIterator.translateScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/display-index/dist/token-iterator.js:251:15)
    at DisplayLayer.module.exports.DisplayLayer.translateScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1491:52)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateToBufferMarkerLayerFindParams (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:220:46)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.findMarkers (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:133:21)
    at DecorationManager.module.exports.DecorationManager.decorationsStateForScreenRowRange (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/decoration-manager.js:151:21)
    at TextEditor.module.exports.TextEditor.decorationsStateForScreenRowRange (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1711:37)
    at TextEditorPresenter.module.exports.TextEditorPresenter.fetchDecorations (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1380:44)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:125:14)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:259:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:191:12)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:318:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:219:9)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:3:59
```

### Commands

```
     -3:50.6.0 find-and-replace:show (input.hidden-input)
     -3:49.7.0 core:confirm (input.hidden-input)
     -3:41.6.0 core:save (input.hidden-input)
  2x -3:41.5.0 core:backspace (input.hidden-input)
     -3:40.6.0 core:save (input.hidden-input)
     -3:39.9.0 core:move-right (input.hidden-input)
     -3:39.8.0 core:backspace (input.hidden-input)
  2x -3:39.6.0 core:save (input.hidden-input)
     -0:38.1.0 core:paste (input.hidden-input)
  2x -0:36.6.0 core:backspace (input.hidden-input)
     -0:34.4.0 core:save (input.hidden-input)
     -0:14.6.0 core:undo (input.hidden-input)
     -0:13.9.0 core:redo (input.hidden-input)
     -0:11.9.0 core:cut (input.hidden-input)
     -0:10.6.0 core:backspace (input.hidden-input)
     -0:10.2.0 core:save (input.hidden-input)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ],
      "text.html.liquid": [
        "inc",
        "tpl",
        "htm",
        "html"
      ]
    },
    "disabledPackages": [
      "wrap-guide",
      "htmlhint",
      "Remote-FTP"
    ],
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": false,
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "sass-autocompile",
      "highlight-selected",
      "highlight-line"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "genesis-ui",
      "one-dark-vivid-syntax"
    ],
    "useCustomTitleBar": true
  },
  "editor": {
    "invisibles": {},
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "showInvisibles": true,
    "softTabs": false,
    "softWrap": true,
    "tabLength": 4,
    "tabType": "hard"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (active)
atom-compile-less, v0.12.0 (active)
base16-ocean-dark-spacegray, v0.12.0 (inactive)
base64, v0.3.0 (inactive)
duotone-blue-dark-syntax, v1.4.0 (inactive)
duotone-dark-space-muted-syntax, v1.0.0 (inactive)
duotone-dark-space-syntax, v2.0.0 (inactive)
duotone-dark-syntax, v2.0.0 (inactive)
duotone-darksky, v1.1.5 (inactive)
duotone-snow, v2.0.2 (inactive)
ficus-dark-syntax, v1.1.0 (inactive)
file-icons, v1.7.24 (active)
genesis-syntax, v1.0.7 (inactive)
genesis-ui, v0.5.0 (active)
github-atom-dark-syntax, v0.2.0 (inactive)
github-atom-light-syntax, v0.2.0 (inactive)
grunt-runner, v0.14.0 (active)
hide-tree, v0.0.20 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
jshint, v1.8.6 (active)
language-liquid, v0.5.1 (active)
less-than-slash, v0.16.0 (active)
merge-conflicts, v1.4.4 (active)
one-dark-vivid-syntax, v1.6.0 (active)
pigments, v0.38.0 (active)
project-manager, v3.3.3 (active)
Remote-FTP, v0.9.4 (inactive)
sass-autocompile, v0.13.1 (active)
sort-lines, v0.14.0 (inactive)
spacegray-atom-dark-syntax, v1.2.0 (inactive)
spacegray-dark-ui, v0.12.0 (inactive)
tab-title, v0.3.3 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.3 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by tjgerot** [comment]
Same instance here. 

Added a line, saved file, closed file, used fuzzy finder to open another file when the exception occurred. I am able to repeat the error whenever I open the specific [file](https://github.com/ctfs/write-ups-2016/blob/274307f43140bb4a52e0729ecf1282628fb22f5b/hack-the-vote-ctf-2016/forensics/trump-likes-colors-250/README.md). File does not highlight syntax and is a few edits behind when the error occurs. When I click back into the editor contents, the syntax highlights (GFMD) and the edits I made a few minutes ago come back.

**Version**: Atom 1.13.0-beta1 ia32
**Operating System**: MS Windows 10 Home 10.0.14393
**Device**: Dell Inspiron 7559

## Error Report
**Atom Version**: 1.13.0-beta1 ia32
**Electron Version**: 1.3.6
**System**: Microsoft Windows 10 Home 10.0.14393
**Device**: Dell Inspiron 7559
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Position (25.833333333333332, Infinity) is less than the current token's start ((26, 0))

```
At C:\Users\tjger\AppData\Local\atom\app-1.13.0-beta1\resources\app.asar\node_modules\display-index\dist\token-iterator.js:251

Error: Position (25.833333333333332, Infinity) is less than the current token's start ((26, 0))
    at TokenIterator.translateScreenPosition (C:\Users\tjger\AppData\Local\atom\app-1.13.0-beta1\resources\app.asar\node_modules\display-index\dist\token-iterator.js:251:15)
    at DisplayLayer.module.exports.DisplayLayer.translateScreenPosition (C:\Users\tjger\AppData\Local\atom\app-1.13.0-beta1\resources\app.asar\node_modules\text-buffer\lib\display-layer.js:1491:52)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateToBufferMarkerLayerFindParams (C:\Users\tjger\AppData\Local\atom\app-1.13.0-beta1\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:220:46)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.findMarkers (C:\Users\tjger\AppData\Local\atom\app-1.13.0-beta1\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:133:21)
    at DecorationManager.module.exports.DecorationManager.decorationsStateForScreenRowRange (C:\Users\tjger\AppData\Local\atom\app-1.13.0-beta1\resources\app.asar\src\decoration-manager.js:151:21)
    at TextEditor.module.exports.TextEditor.decorationsStateForScreenRowRange (C:\Users\tjger\AppData\Local\atom\app-1.13.0-beta1\resources\app.asar\src\text-editor.js:1711:37)
    at TextEditorPresenter.module.exports.TextEditorPresenter.fetchDecorations (C:\Users\tjger\AppData\Local\atom\app-1.13.0-beta1\resources\app.asar\src\text-editor-presenter.js:1380:44)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (C:\Users\tjger\AppData\Local\atom\app-1.13.0-beta1\resources\app.asar\src\text-editor-presenter.js:125:14)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (C:\Users\tjger\AppData\Local\atom\app-1.13.0-beta1\resources\app.asar\src\text-editor-component.js:259:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (C:\Users\tjger\AppData\Local\atom\app-1.13.0-beta1\resources\app.asar\src\text-editor-component.js:191:12)
    at C:\Users\tjger\AppData\Local\atom\app-1.13.0-beta1\resources\app.asar\src\text-editor-component.js:318:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\tjger\AppData\Local\atom\app-1.13.0-beta1\resources\app.asar\src\view-registry.js:219:9)
    at C:\Users\tjger\AppData\Local\atom\app-1.13.0-beta1\resources\app.asar\src\view-registry.js:3:59
```

### Commands

```
     -0:27.9.0 core:cancel (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -0:27.2.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -0:25.1.0 core:move-down (input.hidden-input)
     -0:24.9.0 core:confirm (input.hidden-input)
     -0:15.9.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:11.1.0 core:backspace (input.hidden-input)
     -0:09.5.0 core:move-down (input.hidden-input)
     -0:09.2.0 core:confirm (input.hidden-input)
     -0:08.4.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:07.5.0 editor:consolidate-selections (input.hidden-input)
     -0:07.5.0 core:cancel (input.hidden-input)
     -0:07.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:06.8.0 core:close (input.hidden-input)
     -0:06.1.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:04.1.0 core:move-down (input.hidden-input)
     -0:03.9.0 core:confirm (input.hidden-input)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-pep8"
    ],
    "telemetryConsent": "limited"
  },
  "editor": {
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (active)
atom-python-test, v0.5.4 (active)
autoclose-html, v0.23.0 (active)
autocomplete-java, v1.2.5 (inactive)
autocomplete-python, v1.8.11 (active)
builder-go, v1.0.1 (active)
file-icons, v1.7.24 (active)
firepad, v0.8.0 (inactive)
gerot-word-count, v0.0.0 (inactive)
git-time-machine, v1.5.3 (inactive)
go-config, v1.2.4 (active)
highlight-selected, v0.11.2 (active)
linter, v1.11.18 (active)
linter-csslint, v1.3.3 (active)
linter-javac, v1.9.4 (active)
linter-pep8, v1.3.2 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.6 (active)
pretty-json, v1.6.1 (active)
wordcount, v2.8.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment]
I can reproduce this with the steps @tjgerot posted.

**Comment by Ben3eeE** [comment]
Can not reproduce it when trying on my home computer Windows 10 anniversary 64bit. So here is a retelling of what I did to reproduce this with the referenced file on my work computer.

Windows 7 64-bit, classic mode.

1. Atom `1.13.0-beta1` running in developer mode. I have `one-dark-ui` linked.
1. Opened a new window and pasted the contents of [this file](https://raw.githubusercontent.com/ctfs/write-ups-2016/274307f43140bb4a52e0729ecf1282628fb22f5b/hack-the-vote-ctf-2016/forensics/trump-likes-colors-250/README.md)
1. Saved the file on the desktop in a folder named `issues`. The filename was `README.md`
1. Everything worked fine, no issues at all
1. Closed the `README.md` file tab and reopened it with <kbd>Ctrl-Shift-T</kbd>
1. Issue appeared in console
1. Since this was out safe mode and in dev mode I closed all instances of Atom and launched in safe mode
1. Issue appeared. **NOTE:** The file was restored from previous session.

I can make further attempts to try and narrow this down on Monday. Right now I am unable to reproduce this.

/cc: @ungb

**Comment by DeanmvSG** [comment]
@Ben3eeE I can also reproduce with the file that @tjgerot provided and have made it so that I can reproduce it every time on open. 

Using the system mentioned in the first post on this issue I can replicate it by:

1. Opening Atom `1.13.0-beta1` in safe mode.
2. Copy the contents of [this file](https://raw.githubusercontent.com/ctfs/write-ups-2016/274307f43140bb4a52e0729ecf1282628fb22f5b/hack-the-vote-ctf-2016/forensics/trump-likes-colors-250/README.md) into the empty window and saving it somewhere.

This is then where it seems to become very specific!

3. Move place the cursor at position `8:244` (see screenshot attached).
4. Quit Atom
5. Re-open Atom in safe mode and error is thrown.

It seems that if you have the cursor anywhere else in the file then it places the cursor back at position `1:1` on opening the file again, but leaving it at position `8:244` (and maybe others), throws the error upon re-opening.

Hope that helps!

**Comment by maxbrunsfeld** [comment]
Sorry about this everyone. We'll release another beta hotfix shortly.
