### ISSUE TITLE
Uncaught Error: Invalid package /Applications/Atom%20Beta.app/Contents/Resources/app.asar

### ISSUE THREAD

**Issue by andrescarbo** [atom/atom#13209]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0-beta2
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Invalid package /Applications/Atom%20Beta.app/Contents/Resources/app.asar

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/src/workspace.js:534

Error: Invalid package /Applications/Atom%20Beta.app/Contents/Resources/app.asar
    at invalidArchiveError (ELECTRON_ASAR.js:149:19)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:9)
    at Workspace.module.exports.Workspace.openTextFile (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/workspace.js:581:27)
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/workspace.js:508:23)
    at Workspace.module.exports.Workspace.open (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/workspace.js:436:19)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/atom-environment.js:1200:18)
    at EventEmitter.outerCallback (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/application-delegate.js:236:18)
    at emitThree (events.js:121:20)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "markdown-preview"
    ],
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "useCustomTitleBar": true
  },
  "editor": {
    "fontSize": 12,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true
  }
}
```

### Installed Packages

```coffee
# User
ansible-vault, v0.3.1 (inactive)
atom-beautify, v0.29.13 (inactive)
atom-increment, v0.3.4 (inactive)
atom-terminal, v0.8.0 (inactive)
atom-trello, v0.5.1 (active)
autoclose-html, v0.23.0 (active)
autocomplete-ansible, v0.1.9 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-ruby, v0.2.2 (active)
compare-files, v0.8.0 (active)
dash, v1.7.0 (inactive)
diagrams, v0.23.2 (inactive)
floobits, v0.32.6 (active)
git-checkout, v0.3.2 (active)
git-control, v0.8.2 (inactive)
git-time-machine, v1.5.3 (inactive)
jira-issue-search, v1.0.3 (active)
language-ansible, v0.1.11 (inactive)
language-chef, v0.9.0 (inactive)
language-cisco, v1.4.0 (inactive)
language-markdown, v0.18.1 (inactive)
markdown-preview-plus, v2.4.0 (active)
merge-conflicts, v1.4.4 (active)
monokai-slate, v0.6.0 (inactive)
npm, v2.0.0 (active)
open-on-bitbucket, v0.4.0 (inactive)
pigments, v0.38.0 (active)
project-manager, v3.3.3 (active)
royal-syntax, v0.0.1 (inactive)
rubocop-auto-correct, v1.5.1 (inactive)
ruby-navigator, v0.5.0 (inactive)
ruby-syntax-replacer, v0.5.1 (active)
split-diff, v1.0.6 (inactive)
ssh-config, v0.10.1 (inactive)
vim-mode, v0.65.1 (active)
atom-dark-syntax, v0.28.0 (active)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (inactive)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by JayButani** [comment]
@andrescarbo Have you found the solution for this? I am facing the same problem.

> Uncaught Exception:
Error: Invalid package resources/app.asar
    at invalidArchiveError (ELECTRON_ASAR.js:159:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:515:9)
    at Object.<anonymous> (/Applications/CDSPathology.app/Contents/Resources/app.asar/lib/db.js:11:28)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)

**Comment by andrescarbo** [comment]
That was a red herring. One of your installed packages its misbehaving. In my case Atom was not inhering $ENV when launched from overview; calling the application for command line `fixed it`
