### ISSUE TITLE
build error: Error: BUG: Unsupported require structure: IdentifierLiteral

### ISSUE THREAD

**Issue by liudonghua123** [atom/atom#13217]
I build with the latest code. and the following error occured, I have used node v4.4.5 and npm v3.10.5 already.

```
liudonghua@LiudonghuaMacBook-Air:~/code/electron/atom$ script/build 
Node:	v4.4.5
Npm:	v3.10.5
Installing script dependencies
Installing apm
Installing modules ✓
Wrote Dependencies Fingerprint: /Users/liudonghua/code/electron/atom/node_modules/.dependencies-fingerprint fa75ad7b22823e4d2df78972602b82ae2b38a22c
Cleaning /Users/liudonghua/code/electron/atom/out
Copying assets to /Users/liudonghua/code/electron/atom/out/app
Transpiling Babel paths in /Users/liudonghua/code/electron/atom/out/app
Transpiling CoffeeScript paths in /Users/liudonghua/code/electron/atom/out/app
Transpiling CSON paths in /Users/liudonghua/code/electron/atom/out/app
Transpiling PEG.js paths in /Users/liudonghua/code/electron/atom/out/app
Generating module cache for /Users/liudonghua/code/electron/atom/out/app
Generating pre-built less cache in /Users/liudonghua/code/electron/atom/out/app/less-compile-cache
Generating metadata for /Users/liudonghua/code/electron/atom/out/app/package.json
Generating API docs at /Users/liudonghua/code/electron/atom/docs/output/atom-api.json
/Users/liudonghua/code/electron/atom/script/node_modules/donna/src/metadata.coffee:197
              throw new Error("BUG: Unsupported require structure: " + exp.variable.base.constructor.name);
              ^

Error: BUG: Unsupported require structure: IdentifierLiteral
  at Metadata.module.exports.Metadata.visitAssign (/Users/liudonghua/code/electron/atom/script/node_modules/donna/src/metadata.coffee:144:26)
  at Metadata.module.exports.Metadata.visit (/Users/liudonghua/code/electron/atom/script/node_modules/donna/src/metadata.coffee:21:5)
  at /Users/liudonghua/code/electron/atom/script/node_modules/donna/src/metadata.coffee:18:42
  at /Users/liudonghua/code/electron/atom/script/node_modules/coffee-script/lib/coffee-script/nodes.js:211:17
  at Block.exports.Base.Base.eachChild (/Users/liudonghua/code/electron/atom/script/node_modules/coffee-script/lib/coffee-script/nodes.js:199:17)
  at Block.exports.Base.Base.traverseChildren (/Users/liudonghua/code/electron/atom/script/node_modules/coffee-script/lib/coffee-script/nodes.js:209:19)
  at Metadata.module.exports.Metadata.generate (/Users/liudonghua/code/electron/atom/script/node_modules/donna/src/metadata.coffee:18:11)
  at generateMetadataSlug (/Users/liudonghua/code/electron/atom/script/node_modules/donna/src/donna.coffee:121:14)
  at Object.generateMetadata (/Users/liudonghua/code/electron/atom/script/node_modules/donna/src/donna.coffee:75:24)
  at module.exports (/Users/liudonghua/code/electron/atom/script/lib/generate-api-docs.js:21:32)
  at Object.<anonymous> (/Users/liudonghua/code/electron/atom/script/build:60:1)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3

liudonghua@LiudonghuaMacBook-Air:~/code/electron/atom$
```

**Comment by liudonghua123** [comment]
I could not find something related to this issue, so I posted my error here, hope someone could help me, thanks!

**Comment by nilseuropa** [comment]
Same here. npm v3.10.5
- with node v4.4.7 
`Error: Module version mismatch. Expected 46, got 51.
  at Error (native)
  at Object.Module._extensions..node (module.js:434:18)
  at Module.load (/home/nilseuropa/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:300:12)
 `
- with node v4.6.2
`Error: BUG: Unsupported require structure: IdentifierLiteral
  at Metadata.module.exports.Metadata.visitAssign (/home/nilseuropa/atom/script/node_modules/donna/src/metadata.coffee:144:26)
`

**Comment by JPRuehmann** [comment]
Same here. npm v2.14.20

```
Node:   v4.1.1
Npm:    v3.10.5
Installing script dependencies
Installing apm
Installing modules ✓
Wrote Dependencies Fingerprint: /home/ruehmann/atom/node_modules/.dependencies-fingerprint f39fc270fcd0c0e91f02be120fc85e5af149e13a
/home/ruehmann/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45
      Module._extensions[extension](this, filename);
                                   ^

Error: Module version mismatch. Expected 46, got 48.
  at Error (native)
  at Module.load (/home/ruehmann/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/home/ruehmann/atom/script/node_modules/runas/lib/runas.js:4:11)
  at Object.<anonymous> (/home/ruehmann/atom/script/node_modules/runas/lib/runas.js:47:4)
  at Module._compile (module.js:434:26)
  at Object.Module._extensions..js (module.js:452:10)
  at Module.load (/home/ruehmann/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/home/ruehmann/atom/script/lib/install-application.js:5:15)
  at Module._compile (module.js:434:26)
  at Object.Module._extensions..js (module.js:452:10)
  at Module.load (/home/ruehmann/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/home/ruehmann/atom/script/build:38:28)
  at Module._compile (module.js:434:26)
  at Object.Module._extensions..js (module.js:452:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:475:10)
  at startup (node.js:117:18)
  at node.js:951:3
```
```
Node:   v4.4.1
Npm:    v3.10.5
Installing script dependencies
Installing apm
Installing modules ✓
Installing notifications@0.66.2 ✓
Wrote Dependencies Fingerprint: /home/ruehmann/atom/node_modules/.dependencies-fingerprint af05fd84951902cce538b29f5976b2f6d7cee38d
Cleaning /home/ruehmann/atom/out
Copying assets to /home/ruehmann/atom/out/app
Transpiling Babel paths in /home/ruehmann/atom/out/app
Transpiling CoffeeScript paths in /home/ruehmann/atom/out/app
Transpiling CSON paths in /home/ruehmann/atom/out/app
Transpiling PEG.js paths in /home/ruehmann/atom/out/app
Generating module cache for /home/ruehmann/atom/out/app
Generating pre-built less cache in /home/ruehmann/atom/out/app/less-compile-cache
Generating metadata for /home/ruehmann/atom/out/app/package.json
Generating API docs at /home/ruehmann/atom/docs/output/atom-api.json
/home/ruehmann/atom/script/node_modules/donna/src/metadata.coffee:197
              throw new Error("BUG: Unsupported require structure: " + exp.variable.base.constructor.name);
              ^

Error: BUG: Unsupported require structure: IdentifierLiteral
  at Metadata.module.exports.Metadata.visitAssign (/home/ruehmann/atom/script/node_modules/donna/src/metadata.coffee:144:26)
  at Metadata.module.exports.Metadata.visit (/home/ruehmann/atom/script/node_modules/donna/src/metadata.coffee:21:5)
  at /home/ruehmann/atom/script/node_modules/donna/src/metadata.coffee:18:42
  at /home/ruehmann/atom/script/node_modules/donna/node_modules/coffee-script/lib/coffee-script/nodes.js:211:17
  at Block.exports.Base.Base.eachChild (/home/ruehmann/atom/script/node_modules/donna/node_modules/coffee-script/lib/coffee-script/nodes.js:199:17)
  at Block.exports.Base.Base.traverseChildren (/home/ruehmann/atom/script/node_modules/donna/node_modules/coffee-script/lib/coffee-script/nodes.js:209:19)
  at Metadata.module.exports.Metadata.generate (/home/ruehmann/atom/script/node_modules/donna/src/metadata.coffee:18:11)
  at generateMetadataSlug (/home/ruehmann/atom/script/node_modules/donna/src/donna.coffee:121:14)
  at Object.generateMetadata (/home/ruehmann/atom/script/node_modules/donna/src/donna.coffee:75:24)
  at module.exports (/home/ruehmann/atom/script/lib/generate-api-docs.js:21:32)
  at Object.<anonymous> (/home/ruehmann/atom/script/build:61:1)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3
```
