### ISSUE TITLE
Module version mismatch on script/build

### ISSUE THREAD

**Issue by QwertyZW** [atom/atom#13216]
Just attempting to build atom on Ubuntu 16.10

```
khishman@khishman-N53SV:~/dev/atom$ ./script/build 
Node:	v6.9.1
Npm:	v3.10.5
Installing script dependencies
Installing apm
Installing modules ✓
Wrote Dependencies Fingerprint: /home/khishman/dev/atom/node_modules/.dependencies-fingerprint 44caa49ec45323b3d14d0f7872194037bc45daaf
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 51.
  at Error (native)
  at Object.Module._extensions..node (module.js:597:18)
  at Module.load (/home/khishman/dev/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/khishman/dev/atom/script/node_modules/runas/lib/runas.js:4:11)
  at Object.<anonymous> (/home/khishman/dev/atom/script/node_modules/runas/lib/runas.js:47:4)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (/home/khishman/dev/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/khishman/dev/atom/script/lib/install-application.js:5:15)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (/home/khishman/dev/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/khishman/dev/atom/script/build:38:28)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3
```

I don't see any log files other than `./script/node_modules/electron-winstaller/vendor/SquirrelSetup.log`

**Comment by QwertyZW** [comment]
Worked with node 4.6.1 and npm 3.10.9

**Comment by damieng** [comment]
You'll need to run `script/clean` to wipe out the cached versions of the dependencies that are compiled for an older version of v8.

**Comment by AndreaGriffiths11** [comment]
Since we have not gotten a response back we assume that fixed it. Please let us know if you need more assistance.
