### ISSUE TITLE
Uncaught Error: hg error stderr: hg bookmarks: option -T not recognized

### ISSUE THREAD

**Issue by acenicks** [atom/atom#13231]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.2
**Electron Version**: 1.3.6
**System**: Ubuntu 14.04.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.182.0

### Stack Trace

Uncaught Error: hg error
stderr: hg bookmarks: option -T not recognized

stdout: hg bookmarks [OPTIONS]... [NAME]...

track a line of development with movable markers

options:

 -f --force       force
 -r --rev REV     revision
 -d --delete      delete a given bookmark
 -m --rename NAME rename a given bookmark
 -i --inactive    mark a bookmark inactive

use "hg help bookmarks" to show the full help text

```
At /home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:56

Error: hg error
stderr: hg bookmarks: option -T not recognized

stdout: hg bookmarks [OPTIONS]... [NAME]...

track a line of development with movable markers

options:

 -f --force       force
 -r --rev REV     revision
 -d --delete      delete a given bookmark
 -m --rename NAME rename a given bookmark
 -i --inactive    mark a bookmark inactive

use "hg help bookmarks" to show the full help text

    at logAndThrowHgError (/home/acenicks/.atom/packages/nuclide/pkg/nuclide-hg-rpc/lib/hg-utils.js:146:11)
    at /home/acenicks/.atom/packages/nuclide/pkg/nuclide-hg-rpc/lib/hg-utils.js:37:7
    at next (<anonymous>)
    at step (/home/acenicks/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at /home/acenicks/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:21:13
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "latex-plus",
      "atom-hg",
      "tree-view"
    ],
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "atom-material-syntax-dark"
    ]
  },
  "nuclide": {
    "nuclide-blame-provider-hg": {
      "showVerboseBlame": true
    },
    "nuclide-hg-repository": {
      "enableDiffStats": true
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-hg, v2.0.11 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (active)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.6 (inactive)
autocomplete-bibtex, v0.7.0 (active)
language-latex, v1.0.0 (inactive)
latex, v0.40.0 (inactive)
latex-plus, v0.9.1 (inactive)
latexer, v0.3.0 (active)
linter, v1.11.18 (active)
linter-chktex, v1.3.0 (active)
minimap, v4.25.6 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-selection, v4.4.0 (active)
nuclide, v0.182.0 (active)
pdf-view, v0.53.0 (active)
pigments, v0.38.0 (active)
project-manager, v3.3.3 (active)
terminal-plus, v0.14.5 (active)
wordcount, v2.8.0 (active)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This is a bug in the nuclide package.  Please report this issue there instead.  Thanks!
