### ISSUE TITLE
Installation using `sudo script/build` fails

### ISSUE THREAD

**Issue by paulmenzel** [atom/atom#13239]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

This issue is similar to #13220.

Running `sudo script/build` fails, as the credentials `SUDO_USER` is taken instead of `USER` causing access errors.

```
Node:   v6.9.1
Npm:    v3.10.8
Installing script dependencies
Installing apm
npm ERR! Linux 4.4.14
npm ERR! argv "/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/bin/node" "/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/node_modules/.bin/npm" "dedupe"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! path /tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/node_modules/npm/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/node_modules/npm/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/node_modules/npm/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/node_modules/npm/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/npm-debug.log
module.js:327
    throw err;
    ^

Error: Cannot find module 'node-gyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at new Install (/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/lib/install.js:53:38)
    at Object.module.exports.run (/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/lib/apm-cli.js:226:18)
    at Object.<anonymous> (/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/lib/cli.js:8:7)
    at Object.<anonymous> (/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/lib/cli.js:12:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
child_process.js:506
    throw err;
    ^

Error: Command failed: /tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:483:13)
    at Object.execFileSync (child_process.js:503:13)
    at module.exports (/tmp/SBo/atom-1.12.2/script/lib/install-atom-dependencies.js:19:16)
    at Object.<anonymous> (/tmp/SBo/atom-1.12.2/script/bootstrap:28:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

### Steps to Reproduce

1. Download Atom 1.12.2.
2. Run `sudo script/build`

**Expected behavior:** [What you expected to happen]

The build should succeed.

**Actual behavior:** [What actually happened]

The build aborts with the error pasted at the top.

### Versions

Reproduced with Atom 1.10.2 and 1.12.2.

It worked with Atom 1.9.0.

**Comment by paulmenzel** [comment]
So `script/bootstrap` – also included by `script/build` contains `const installApm = require('./lib/install-apm')`, which fails.

```
$ nl -ba script/lib/install-apm.js
     1  'use strict'
     2  
     3  const childProcess = require('child_process')
     4  const path = require('path')
     5  
     6  const CONFIG = require('../config')
     7  
     8  module.exports = function () {
     9    console.log('Installing apm')
    10    childProcess.execFileSync(
    11      CONFIG.getNpmBinPath(),
    12      ['--global-style', '--loglevel=error', 'install'],
    13      {env: process.env, cwd: CONFIG.apmRootPath}
    14    )
    15  }
```

**Comment by moyoteg** [comment]
@paulmenzel were you able to figure this out? =)

**Comment by richyarD** [comment]
What **start_cmd** stands for in this line?
> start_cmd script/build

**Comment by paulmenzel** [comment]
> What start_cmd stands for, in this line?
>
> >    start_cmd script/build

It’s just a wrapper to print the run command on the terminal in [Bee](http://www.beezinga.org/).

**Comment by richyarD** [comment]
If I don't have bee, how am I supposed to workout this problem, then?
After 
> unset SUDO_USER SUDO_UID SUDO_COMMAND SUDO_GID

I just typed

> sudo ./build --install

and still got the error:

> const yargs = require('yargs')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

What to do? How to live?

**Comment by richyarD** [comment]
If I don't have bee, how am I supposed to workout this problem, then?
After

> unset SUDO_USER SUDO_UID SUDO_COMMAND SUDO_GID

I just typed
> sudo ./build --install

and still got the error:

> const yargs = require('yargs')
^^^^^
SyntaxError: Use of const in strict mode.
at exports.runInThisContext (vm.js:73:16)
at Module._compile (module.js:443:25)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:501:10)
at startup (node.js:129:16)
at node.js:814:3

What to do? How to live?

**Comment by sliceofcode** [comment]
I'm also getting this.

```
dev/prg/atom% sudo script/build --install   
Node:	v6.9.5     
Npm:	v3.10.10
Installing script dependencies
Installing apm
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:25:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
../deps/libgit2/deps/zlib/inflate.c: In function ‘inflateMark’:
../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: left shift of negative value [-Wshift-negative-value]
     if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                             ^~
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:25:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
../deps/libgit2/deps/zlib/inflate.c: In function ‘inflateMark’:
../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: left shift of negative value [-Wshift-negative-value]
     if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                             ^~
npm ERR! Linux 4.9.6-1-ARCH
npm ERR! argv "/home/cheesy/dev/prg/atom/apm/node_modules/atom-package-manager/bin/node" "/home/cheesy/dev/prg/atom/apm/node_modules/atom-package-manager/node_modules/.bin/npm" "dedupe"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! path /home/cheesy/dev/prg/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/home/cheesy/dev/prg/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/home/cheesy/dev/prg/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/cheesy/dev/prg/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cheesy/dev/prg/atom/apm/node_modules/atom-package-manager/npm-debug.log
module.js:327
    throw err;
    ^

Error: Cannot find module 'node-gyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at Install.module.exports.Install.installNode (/home/cheesy/dev/prg/atom/apm/node_modules/atom-package-manager/lib/install.js:103:67)
    at /home/cheesy/dev/prg/atom/apm/node_modules/atom-package-manager/lib/install.js:3:59
    at fn (/home/cheesy/dev/prg/atom/apm/node_modules/atom-package-manager/node_modules/async/lib/async.js:582:34)
    at Immediate._onImmediate (/home/cheesy/dev/prg/atom/apm/node_modules/atom-package-manager/node_modules/async/lib/async.js:498:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
child_process.js:506
    throw err;
    ^

Error: Command failed: /home/cheesy/dev/prg/atom/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:483:13)
    at Object.execFileSync (child_process.js:503:13)
    at module.exports (/home/cheesy/dev/prg/atom/script/lib/install-atom-dependencies.js:15:16)
    at Object.<anonymous> (/home/cheesy/dev/prg/atom/script/bootstrap:28:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```
