### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by handicraftsman** [atom/atom#13235]
```
ancient@nickolaypc ~/load % git clone https://github.com/atom/atom.git
Cloning into 'atom'...
remote: Counting objects: 165240, done.
remote: Compressing objects: 100% (150/150), done.
remote: Total 165240 (delta 101), reused 10 (delta 10), pack-reused 165080
Receiving objects: 100% (165240/165240), 281.12 MiB | 6.66 MiB/s, done.
Resolving deltas: 100% (117457/117457), done.
git clone https://github.com/atom/atom.git  23.68s user 7.74s system 46% cpu 1:07.05 total
ancient@nickolaypc ~/load % cd atom 
ancient@nickolaypc ~/load/atom (git)-[master] % script/build 
Node:	v7.1.0
Npm:	v3.10.9
Installing script dependencies
Installing apm
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:25:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
../deps/libgit2/deps/zlib/inflate.c: In function ‘inflateMark’:
../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: left shift of negative value [-Wshift-negative-value]
     if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                             ^~
child_process.js:145
    throw new TypeError('Incorrect value of args option');
    ^

TypeError: Incorrect value of args option
    at Object.exports.execFile (child_process.js:145:11)
    at Object.exports.exec (child_process.js:108:18)
    at Object.<anonymous> (/home/ancient/load/atom/apm/node_modules/atom-package-manager/script/postinstall.js:10:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
npm ERR! Linux 4.8.7-1-MANJARO
npm ERR! argv "/usr/bin/node" "/home/ancient/load/atom/script/node_modules/.bin/npm" "--global-style" "--loglevel=error" "install"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-package-manager@1.15.1 install: `node script/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-package-manager@1.15.1 install script 'node script/postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-package-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-package-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-package-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ancient/load/atom/apm/npm-debug.log
npm ERR! code 1
child_process.js:511
    throw err;
    ^

Error: Command failed: /home/ancient/load/atom/script/node_modules/.bin/npm --global-style --loglevel=error install
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:25:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
../deps/libgit2/deps/zlib/inflate.c: In function ‘inflateMark’:
../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: left shift of negative value [-Wshift-negative-value]
     if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                             ^~
child_process.js:145
    throw new TypeError('Incorrect value of args option');
    ^

TypeError: Incorrect value of args option
    at Object.exports.execFile (child_process.js:145:11)
    at Object.exports.exec (child_process.js:108:18)
    at Object.<anonymous> (/home/ancient/load/atom/apm/node_modules/atom-package-manager/script/postinstall.js:10:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
npm ERR! Linux 4.8.7-1-MANJARO
npm ERR! argv "/usr/bin/node" "/home/ancient/load/atom/script/node_modules/.bin/npm" "--global-style" "--loglevel=error" "install"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-package-manager@1.15.1 install: `node script/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-package-manager@1.15.1 install script 'node script/postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-package-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-package-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-package-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ancient/load/atom/apm/npm-debug.log
npm ERR! code 1

    at checkExecSyncError (child_process.js:488:13)
    at Object.execFileSync (child_process.js:508:13)
    at module.exports (/home/ancient/load/atom/script/lib/install-apm.js:10:16)
    at Object.<anonymous> (/home/ancient/load/atom/script/bootstrap:27:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
script/build  200.41s user 16.72s system 81% cpu 4:26.86 total
1 ancient@nickolaypc ~/load/atom (git)-[master] %           
```

**Comment by handicraftsman** [comment]
Trying to build from AUR...

**Comment by handicraftsman** [comment]
```
../deps/v8/src/identity-map.cc:5:30: fatal error: src/identity-map.h: No such file or directory
 #include "src/identity-map.h"
                              ^
compilation terminated.
make[1]: *** [deps/v8/tools/gyp/v8_base.target.mk:486: /tmp/yaourt-tmp-ancient/aur-nodejs-lts-boron/src/node-v6.9.1/out/Release/obj.target/v8_base/deps/v8/src/identity-map.o] Error 1
make[1]: Leaving directory '/tmp/yaourt-tmp-ancient/aur-nodejs-lts-boron/src/node-v6.9.1/out'
make: *** [Makefile:67: node] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build nodejs-lts-boron.
==> Restart building nodejs-lts-boron ? [y/N]
==> -----------------------------------------
==> 

```

**Comment by handicraftsman** [comment]
@50Wliu @damieng

**Comment by thomasjo** [comment]
You need to build with Node v6 (or lower). We don't support v7 yet. 

You might want to subscribe to https://github.com/atom/apm/pull/637 for Node.js v7 support.

**Comment by handicraftsman** [comment]
Sorry, but how do i install node v6, if i am using pacman? I don't have any in official-repos nor AUR.

**Comment by thomasjo** [comment]
We don't officially support any Arch distributions of Atom, so I don't really know the exact answer to your question. For Arch we only really support building directly from official source distributions.

Regardless, check out [nvm](https://github.com/creationix/nvm), which is a Node.js version manager. You can trivially install for example Node.js v6.9.1 via `nvm install v6.9.1` (or similar).

**Comment by handicraftsman** [comment]
@thomasjo, ok (i did both `npm install` and `nvm install v6.9.1`):
```
Wrote Dependencies Fingerprint: /home/ancient/load/atom/node_modules/.dependencies-fingerprint a3bf8553578811f6377fa84b89d511b70c89dad0
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 51.
  at Error (native)
  at Object.Module._extensions..node (module.js:597:18)
  at Module.load (/home/ancient/load/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/ancient/load/atom/script/node_modules/runas/lib/runas.js:4:11)
  at Object.<anonymous> (/home/ancient/load/atom/script/node_modules/runas/lib/runas.js:47:4)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (/home/ancient/load/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/ancient/load/atom/script/lib/install-application.js:5:15)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (/home/ancient/load/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/ancient/load/atom/script/build:38:28)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3

script/build  14.51s user 0.74s system 109% cpu 13.915 total

```

**Comment by yitzchak** [comment]
@handicraftsman Atom just got accepted in the community repo in Arch. It is currently at v1.12.2 if you want to skip the AUR build.

https://www.archlinux.org/packages/community/x86_64/atom/

**Comment by damieng** [comment]
@yitzchak That package doesn't use the correct version of Electron and is a constant source of semi-random issues because of that.

**Comment by yitzchak** [comment]
@damieng That's too bad. Thanks for letting me know, though.

**Comment by handicraftsman** [comment]
1. This time it built.
2. I am using i686 system :wink:

**Comment by handicraftsman** [comment]
3. Gonna switch to XFCE soon
