### ISSUE TITLE
Node 7 support

### ISSUE THREAD

**Issue by mpkh** [atom/atom#13260]
```
Installing apm
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:25:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                                        ^
child_process.js:145
    throw new TypeError('Incorrect value of args option');
    ^

TypeError: Incorrect value of args option
    at Object.exports.execFile (child_process.js:145:11)
    at Object.exports.exec (child_process.js:108:18)
    at Object.<anonymous> (/var/tmp/portage/app-editors/atom-1.13.0_beta4/work/atom-1.13.0-beta4/apm/node_modules/atom-package-manager/script/postinstall.js:10:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
npm ERR! Linux 4.8.8-zen-gb9f2356-dirty

```

related: https://github.com/atom/atom/issues/13173

fails on 1.13 beta 4 after node 7 support fix was merged, maybe that issue is different

**Comment by JoshStrobl** [comment]
@mpkh It was merged into apm master, there hasn't been an apm release yet with the fix.

**Comment by mpkh** [comment]
@JoshStrobl but does error message even look related?

**Comment by JoshStrobl** [comment]
Yes, it is.

**Comment by mpkh** [comment]
@JoshStrobl in which release (or beta) it will be merged?

**Comment by JoshStrobl** [comment]
I have no idea, I am not an apm or Atom dev.
