### ISSUE TITLE
Brackets on the %USERPROFILE% path generate an error in package-manager.coffee

### ISSUE THREAD

**Issue by EGO7000** [atom/atom#13346]
Hello everyone,

_[Enter steps to reproduce below:]_

1. Create a new windows user profile with administrator rights and called it "USE(r)" to reproduced a bug.
2. Download from atom.io Windows Installer and launched it.
3. Open "Settings", go to "Install" and see this:

![atom](https://cloud.githubusercontent.com/assets/10194337/20670956/714fec1e-b58c-11e6-8183-744d87a95c85.PNG)

### Error in console:
<pre>
package-manager.coffee:68 Uncaught (in promise) Error: Fetching local packages failed.
    at C:\Users\USE(r)\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\settings-view\lib\package-manager.js:103:21
    at exit (C:\Users\USE(r)\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\USE(r)\AppData\Local\atom\app-1.12.5\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\USE(r)\AppData\Local\atom\app-1.12.5\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)(anonymous function) @ package-manager.coffee:68exit @ package-manager.coffee:50triggerExitCallback @ buffered-process.coffee:212(anonymous function) @ buffered-process.coffee:231emitTwo @ events.js:106emit @ events.js:191ChildProcess._handle.onexit @ internal/child_process.js:215
</pre>

Atom Version: 1.12.5
System: Microsoft Windows 7 x64

**Comment by Ben3eeE** [comment]
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13178. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by nixis** [comment]
Hi @damieng ,

is it possible to add the hash "#" to the escpaped chars? 
I do have the same problem to install packages.

Philipp

**Comment by EGO7000** [comment]
Hi!
I have reinstalled atom. Still have the same error.
Console log:
<pre>
internal/process/warning.js:24 (node:2564) Warning: Possible EventEmitter memory leak detected. 11 ipc-helpers-window-method-response listeners added. Use emitter.setMaxListeners() to increase limitprocess.on @ internal/process/warning.js:24emitOne @ events.js:96emit @ events.js:188process.nextTick @ internal/process/warning.js:47_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
task.coffee:84 spell-check:en-us Can't load en_US: Cannot find dictionary for en_US.
main.coffee:68 Fetching local packages failed. Error: Fetching local packages failed.
    at C:\Users\EGO(r)\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:103:21
    at exit (C:\Users\EGO(r)\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\EGO(r)\AppData\Local\atom\app-1.13.0\resources\app.asar\src\buffered-process.js:299:11)
    at C:\Users\EGO(r)\AppData\Local\atom\app-1.13.0\resources\app.asar\src\buffered-process.js:320:11
    at Socket.<anonymous> (C:\Users\EGO(r)\AppData\Local\atom\app-1.13.0\resources\app.asar\src\buffered-process.js:181:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
</pre>

**Comment by damieng** [comment]
@EGO7000 this fix went into 1.14-beta0 not 1.13.

**Comment by EGO7000** [comment]
Hello again!
I reinstalled to version 1.14.0-beta1 x64, but it still doesn't work :(
I have another error message:
![git](https://cloud.githubusercontent.com/assets/10194337/21979627/d058ab1c-dbf0-11e6-88f3-8e576981918a.PNG)

Console log:
<pre>C:\Users\EGO(r)\AppData\Local\atom\app-1.14.0-beta1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:176 Uncaught (in promise) Error: Fetching outdated packages and themes failed.
    at C:\Users\EGO(r)\AppData\Local\atom\app-1.14.0-beta1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:176:21
    at exit (C:\Users\EGO(r)\AppData\Local\atom\app-1.14.0-beta1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:69:16)
    at triggerExitCallback (C:\Users\EGO(r)\AppData\Local\atom\app-1.14.0-beta1\resources\app.asar\src\buffered-process.js:303:11)
    at C:\Users\EGO(r)\AppData\Local\atom\app-1.14.0-beta1\resources\app.asar\src\buffered-process.js:324:11
    at Socket.<anonymous> (C:\Users\EGO(r)\AppData\Local\atom\app-1.14.0-beta1\resources\app.asar\src\buffered-process.js:185:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
C:\Users\EGO(r)\AppData\Local\atom\app-1.14.0-beta1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:97 Uncaught (in promise) Error: Fetching local packages failed.
    at C:\Users\EGO(r)\AppData\Local\atom\app-1.14.0-beta1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:97:19
    at exit (C:\Users\EGO(r)\AppData\Local\atom\app-1.14.0-beta1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:69:16)
    at triggerExitCallback (C:\Users\EGO(r)\AppData\Local\atom\app-1.14.0-beta1\resources\app.asar\src\buffered-process.js:303:11)
    at C:\Users\EGO(r)\AppData\Local\atom\app-1.14.0-beta1\resources\app.asar\src\buffered-process.js:324:11
    at Socket.<anonymous> (C:\Users\EGO(r)\AppData\Local\atom\app-1.14.0-beta1\resources\app.asar\src\buffered-process.js:185:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
</pre>

**Comment by damieng** [comment]
@EGO7000 I think you are encountering a different problem.  Do you have autoscripts set to run for command prompts?   Can you open a command prompt and then copy and paste what your screen shows here?  e.g. on my system I get;

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\damie>
```

**Comment by EGO7000** [comment]
@damieng I have russian locale. So, this is my screen:
<pre>Microsoft Windows [Version 6.1.7601]
(c) Корпорация Майкрософт (Microsoft Corp.), 2009. Все права защищены.

C:\Users\EGO(r)></pre>
And yes, my username is **EGO(r)**.

**Comment by damieng** [comment]
I suspect it's to do with the non-ascii characters and how the response is parsed.  Going to require some more investigation - can you create a separate bug with the contents of your last two message in it so we can separately investigate? Thanks!

**Comment by EGO7000** [comment]
Not needed. I just installed 1.14.0-beta2 x64 and all errors has gone! Thanks! :)
