### ISSUE TITLE
macOs build failed

### ISSUE THREAD

**Issue by keifkeifki** [atom/atom#13374]
I'm building atom on mac but abort: node v7.1.0 npm  v3.10.5

child_process.js:145
    throw new TypeError('Incorrect value of args option');
    ^

TypeError: Incorrect value of args option
    at Object.exports.execFile (child_process.js:145:11)
    at Object.exports.exec (child_process.js:108:18)
    at Object.<anonymous> (/Users/home/Downloads/atom/apm/node_modules/atom-package-manager/script/postinstall.js:10:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/Users/home/Downloads/atom/script/node_modules/.bin/npm" "--global-style" "--loglevel=error" "install"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-package-manager@1.15.1 install: `node script/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atom-package-manager@1.15.1 install script 'node script/postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-package-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-package-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-package-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/home/Downloads/atom/apm/npm-debug.log
npm ERR! code 1

    at checkExecSyncError (child_process.js:488:13)
    at Object.execFileSync (child_process.js:508:13)
    at module.exports (/Users/home/Downloads/atom/script/lib/install-apm.js:10:16)
    at Object.<anonymous> (/Users/home/Downloads/atom/script/bootstrap:27:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)

**Comment by 50Wliu** [comment]
Use Node 6 for the time being.

**Comment by adamreisnz** [comment]
Also fails with Node 6.9.1:

```
./build  --install
Node:	v6.9.1
Npm:	v3.10.5
Installing script dependencies
Installing apm
Installing modules ✓
Wrote Dependencies Fingerprint: /atom/atom/node_modules/.dependencies-fingerprint 9a3efcb4debc951224ab524d4179af2c93d4396b
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 51.
  at Error (native)
  at Object.Module._extensions..node (module.js:597:18)
  at Module.load (/atom/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/atom/atom/script/node_modules/runas/lib/runas.js:4:11)
  at Object.<anonymous> (/atom/atom/script/node_modules/runas/lib/runas.js:47:4)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (/atom/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/atom/atom/script/lib/install-application.js:5:15)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (/atom/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/atom/atom/script/build:38:28)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3
```

**Comment by 50Wliu** [comment]
`script/clean` and try again.

**Comment by adamreisnz** [comment]
That seems to've done the trick, thanks 👍
