### ISSUE TITLE
Uncaught Error: Position (28.272727272727273, Infinity) is less than the current token's start ((...

### ISSUE THREAD

**Issue by contra-bit** [atom/atom#13406]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0-beta2
**Electron Version**: 1.3.6
**System**: Debian GNU/Linux
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Position (28.272727272727273, Infinity) is less than the current token's start ((29, 0))

```
At /usr/share/atom-beta/resources/app.asar/node_modules/display-index/dist/token-iterator.js:251

Error: Position (28.272727272727273, Infinity) is less than the current token's start ((29, 0))
    at TokenIterator.translateScreenPosition (/usr/share/atom-beta/resources/app.asar/node_modules/display-index/dist/token-iterator.js:251:15)
    at DisplayLayer.module.exports.DisplayLayer.translateScreenPosition (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1491:52)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateToBufferMarkerLayerFindParams (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:220:46)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.findMarkers (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:133:21)
    at TextEditor.module.exports.TextEditor.cursorsForScreenRowRange (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:2053:41)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateCursorsState (/usr/share/atom-beta/resources/app.asar/src/text-editor-presenter.js:554:25)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPostMeasurementState (/usr/share/atom-beta/resources/app.asar/src/text-editor-presenter.js:154:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/share/atom-beta/resources/app.asar/src/text-editor-component.js:202:38)
    at /usr/share/atom-beta/resources/app.asar/src/text-editor-component.js:323:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom-beta/resources/app.asar/src/view-registry.js:219:9)
    at /usr/share/atom-beta/resources/app.asar/src/view-registry.js:3:59
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-time-machine"
    ],
    "telemetryConsent": "no",
    "themes": [
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ariake-dark-syntax, v0.0.5 (inactive)
autocomplete-java, v1.2.5 (inactive)
autocomplete-python, v1.8.20 (active)
django-templates, v0.5.0 (active)
git-time-machine, v1.5.4 (inactive)
linter, v1.11.21 (active)
nord-atom-syntax, v0.4.0 (inactive)
nord-atom-ui, v0.9.0 (inactive)
atom-dark-syntax, v0.28.0 (active)
atom-dark-ui, v0.53.0 (active)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please update to the latest beta version, currently 1.13.0-beta6.  This has already been fixed.
