### ISSUE TITLE
RPM build does not respect existing RPM setup with custom topdir

### ISSUE THREAD

**Issue by philwyett-hemi** [atom/atom#13444]
RPM build does not respect existing RPM setup with custom topdir.

Reproducible: yes

Output of './build --create-rpm-package'

```
Creating rpm package for "/home/philwyett/Development/hemisphere/build/atom/out/atom-1.14.0-dev-ad77c31-amd64"
Creating rpm package directory structure at "/home/philwyett/rpmbuild"
Copying "/home/philwyett/Development/hemisphere/build/atom/out/atom-1.14.0-dev-ad77c31-amd64" to "/home/philwyett/rpmbuild/BUILD/Atom"
Copying icons into "/home/philwyett/rpmbuild/BUILD/icons"
Writing rpm package spec file into "/home/philwyett/rpmbuild/SPECS"
Writing desktop entry file into "/home/philwyett/rpmbuild/BUILD"
Copying atom.sh into "/home/philwyett/rpmbuild/BUILD"
Generating .rpm package from "/home/philwyett/rpmbuild"
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.iKpvKG


RPM build errors:

+ umask 022
+ cd /home/philwyett/Development/rpmbuild/BUILD
+ '[' /home/philwyett/Development/rpmbuild/BUILDROOT/atom-1.14.0.dev.ad77c31-0.1.el7.centos.x86_64 '!=' / ']'
+ rm -rf /home/philwyett/Development/rpmbuild/BUILDROOT/atom-1.14.0.dev.ad77c31-0.1.el7.centos.x86_64
++ dirname /home/philwyett/Development/rpmbuild/BUILDROOT/atom-1.14.0.dev.ad77c31-0.1.el7.centos.x86_64
+ mkdir -p /home/philwyett/Development/rpmbuild/BUILDROOT
+ mkdir /home/philwyett/Development/rpmbuild/BUILDROOT/atom-1.14.0.dev.ad77c31-0.1.el7.centos.x86_64
+ mkdir -p /home/philwyett/Development/rpmbuild/BUILDROOT/atom-1.14.0.dev.ad77c31-0.1.el7.centos.x86_64//usr/share/atom/
+ cp -r 'Atom/*' /home/philwyett/Development/rpmbuild/BUILDROOT/atom-1.14.0.dev.ad77c31-0.1.el7.centos.x86_64//usr/share/atom/
cp: cannot stat 'Atom/*': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.iKpvKG (%install)
    Bad exit status from /var/tmp/rpm-tmp.iKpvKG (%install)

Error: Command rpmbuild -ba --clean /home/philwyett/rpmbuild/SPECS/atom.spec exited with code "1"
    at module.exports (/home/philwyett/Development/hemisphere/build/atom/script/lib/spawn-sync.js:16:11)
    at module.exports (/home/philwyett/Development/hemisphere/build/atom/script/lib/create-rpm-package.js:74:3)
    at dumpSymbols.then.then.packagedAppPath (/home/philwyett/Development/hemisphere/build/atom/script/build:86:9)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Setting from my '.rpmmacos' file: %_topdir %(echo $HOME)/Development/rpmbuild

Workaround: Temporarily 'mv .rpmmacros .rpmmacros.orig' in $HOME.

**Comment by igavelyuk** [comment]
I'm have been triaged to this issue.
It seems to me that there should be no problem, except about the python version for CentOS and Fedora, if it is important, I can take and try to create a package from source code using one of the internet guides.
As we know atom uses `python version 2` and **CentOS** and **Fedora** by default uses `version 3`
So to able compile atom from source, first you need to install `python-universioned-command` for Fedora to install Python 2.7.16
So for Fedora 30 `python --version` is working, version Python 2.7.16
For CentOS `yum install python2` and `python --version` NOT working because in CentOS it install as Python2, so `python2 --version` Python 2.7.15
Theoreticaly you must deal with python depencies under CentOS

From log of @philwyett-hemi  we see as recursive copy from folder after un-archive is errored, for the reason, by default it unarchive inro `/atom` not `/Atom`

We can see after 3 years nobody comment this, I am in doubts about this is still relevant problem.
