### ISSUE TITLE
Windows 10 Build Error

### ISSUE THREAD

**Issue by MrSourabh** [atom/atom#13440]
My build is breaking with following error. Can anyone please suggest

```
C:\Users\sourabh\Documents\Projects\atom>script\build
Node:   v6.9.1
Npm:    v3.10.5
Python: v2.7.12
Installing script dependencies
Installing apm
Installing modules done
Wrote Dependencies Fingerprint: C:\Users\sourabh\Documents\Projects\atom\node_modules\.dependencies-fingerprint 45aae06da90caf0b42f82af4d690961dce9a9100
Cleaning C:\Users\sourabh\Documents\Projects\atom\out
Copying assets to C:\Users\sourabh\Documents\Projects\atom\out\app
Transpiling Babel paths in C:\Users\sourabh\Documents\Projects\atom\out\app
Transpiling CoffeeScript paths in C:\Users\sourabh\Documents\Projects\atom\out\app
Transpiling CSON paths in C:\Users\sourabh\Documents\Projects\atom\out\app
Transpiling PEG.js paths in C:\Users\sourabh\Documents\Projects\atom\out\app
Generating module cache for C:\Users\sourabh\Documents\Projects\atom\out\app
Generating pre-built less cache in C:\Users\sourabh\Documents\Projects\atom\out\app\less-compile-cache
Generating metadata for C:\Users\sourabh\Documents\Projects\atom\out\app\package.json
Generating API docs at C:\Users\sourabh\Documents\Projects\atom\docs\output\atom-api.json
Unzipping "C:\Users\sourabh\Documents\Projects\atom\electron\electron-1.3.0-chromedriver-v2.21-win32-x64.zip" to "C:\Users\sourabh\Documents\Projects\atom\electron\chromedriver"
C:\Users\sourabh\Documents\Projects\atom\script\lib\spawn-sync.js:12
    throw result.error
    ^

Error: spawnSync 7z ENOENT
  at exports._errnoException (util.js:1026:11)
  at Object.spawnSync (child_process.js:461:20)
  at module.exports (C:\Users\sourabh\Documents\Projects\atom\script\lib\spawn-sync.js:10:41)
  at unzipPath (C:\Users\sourabh\Documents\Projects\atom\script\lib\download-chromedriver.js:58:7)
  at module.exports (C:\Users\sourabh\Documents\Projects\atom\script\lib\download-chromedriver.js:30:3)
  at Object.<anonymous> (C:\Users\sourabh\Documents\Projects\atom\script\build:61:1)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3
```

Thanks

**Comment by 50Wliu** [comment]
Install [7-zip](http://www.7-zip.org/).

**Comment by MrSourabh** [comment]
@50Wliu I already have 7 Zip installed on my System.

**Comment by 50Wliu** [comment]
@damieng

**Comment by Ben3eeE** [comment]
Try pulling from master the `download-chromedriver.js` file was removed in https://github.com/atom/atom/commit/ad77c319ad4d9799294e08fe10c5b37aa782f1cd.

Also check if 7-zip is in your PATH variable.

**Comment by damieng** [comment]
Two options:

1. Ensure 7z.exe is in your path
2. sync with master - we're now pulling electron-chromedriver from npm so that dependency is gone
