### ISSUE TITLE
Atom displays crashed windows upon launch [Mac]

### ISSUE THREAD

**Issue by Down10** [atom/atom#13457]
### Description

Opening Atom from the app icon or from Terminal causes one or more blank windows to load with a misplaced sheet that says "the editor has crashed" (see screenshot).

![screenshot 2016-12-15 22 48 54](https://cloud.githubusercontent.com/assets/91656/21254639/7f60c264-c31b-11e6-95df-be0883e6840c.PNG)

Despite the crashed windows, a new and fully functional editor window will still open in the background.

This effect occurs with the latest version of Atom (including Safe mode), even after a fresh install with the previous user, support, and cache folders cleared.

Launching using `atom -f` gives the following output in the Terminal:

```
jesse@DOWNiMac ~ $ atom -f
[35612:1215/224810:INFO:CONSOLE(975)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source: /Applications/Development/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js (975)
[35612:1215/224810:INFO:CONSOLE(975)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source: /Applications/Development/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js (975)
2016-12-15 22:49:16.377 Atom[35612:453728] Cannot read property 'substr' of null
2016-12-15 22:49:16.384 Atom[35612:453728] TypeError: Cannot read property 'substr' of null
    at AtomWindow.module.exports.AtomWindow.getLoadSettings (/Applications/Development/Atom.app/Contents/Resources/app.asar/src/main-process/atom-window.js:149:71)
    at AtomApplication.module.exports.AtomApplication.saveState (/Applications/Development/Atom.app/Contents/Resources/app.asar/src/main-process/atom-application.js:920:37)
    at BrowserWindow.<anonymous> (/Applications/Development/Atom.app/Contents/Resources/app.asar/src/main-process/atom-window.js:206:35)
    at emitOne (events.js:96:13)
    at BrowserWindow.emit (events.js:188:7)
```

From system.log:
```
Dec 15 22:47:23 DOWNiMac kernel[0]: Sandbox: Atom(35612) System Policy: deny file-write-unlink /Users/jesse/Library/Saved Application State/com.github.atom.savedState/restorecount.plist
Dec 15 22:48:01 DOWNiMac kernel[0]: Atom (map: 0xffffff80472981e0) triggered DYLD shared region unnest for map: 0xffffff80472981e0, region 0x7fff8a600000->0x7fff8a800000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
Dec 15 22:49:16 DOWNiMac.local Atom[35612]: Cannot read property 'substr' of null
Dec 15 22:49:16 DOWNiMac.local Atom[35612]: TypeError: Cannot read property 'substr' of null
	    at AtomWindow.module.exports.AtomWindow.getLoadSettings (/Applications/Development/Atom.app/Contents/Resources/app.asar/src/main-process/atom-window.js:149:71)
	    at AtomApplication.module.exports.AtomApplication.saveState (/Applications/Development/Atom.app/Contents/Resources/app.asar/src/main-process/atom-application.js:920:37)
	    at BrowserWindow.<anonymous> (/Applications/Development/Atom.app/Contents/Resources/app.asar/src/main-process/atom-window.js:206:35)
	    at emitOne (events.js:96:13)
	    at BrowserWindow.emit (events.js:188:7)
```

### Versions

Mac OS X Yosemite 10.10.5
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.8
git 2.11.0

**Comment by apeltzer** [comment]
I can confirm this behaviour. Exactly the same here, OSX 10.12.2 (updated yesterday - maybe related to this ? )

**Comment by kaia9** [comment]
i'm experiencing the same issue - except i don't get a fully functioning editor in the background, i get nothing a white editor window. This is after coming back from updating installing the latest updates from AppStore, which was the safari 10.0.2 update.

running on OSX 10.11.6

**Comment by lacoperon** [comment]
I also get the same issue, running on macOS 10.11.6 as well

**Comment by apeltzer** [comment]
`➜  ~ atom -f
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`

Though exporting as suggested in the tmux thread to disable this didnt resolve the error (just this message is gone...) .

**Comment by apeltzer** [comment]
I was able to narrow things down to "rst-preview" - once removing that package from my .atom/packages/ folder, atom spun up perfectly fine. 

https://github.com/lsegal/atom-rst-preview/issues

**Comment by joewalker** [comment]
For me [atom-beautify](https://github.com/Glavin001/atom-beautify) caused this issue. When I removed that, Atom worked again.

**Comment by lee-dohm** [comment]
It sounds like this is fixed for everyone. If not, please try the instructions in the Debugging section of the [Atom Flight Manual](http://flight-manual.atom.io) under [Clearing Saved State](http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state) and see if that corrects the problem.

If that still doesn't fix it, let us know.

**Comment by johnryan** [comment]
@lee-dohm I'm seeing this issue all of a sudden, i've cleared saved state, and reset to factory defaults as well as tried safe mode. 

seeing:

```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
logout
```

**Comment by rsese** [comment]
What versions are you running @johnryan (`atom --version` and `apm --version` and what version of macOS)?    Also, are there any [crash logs](http://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs)?

Also, where are you seeing those error messages?  From running `atom -f`?

**Comment by rsese** [comment]
Thanks for the details :v:

> No crash logs but restarting the computer seems to have fixed it,

Huh, I wonder what the issue was (assuming it wasn't just a transient thing) - in any case, glad things are working for you but if you run into this again, please let us know.

**Comment by wilfordw** [comment]
@rsese 
I have the same warn with @jonrohan  
```
➜  Runner git:(master) ✗ atom .
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
```
only warn,not crash! I want to know what can I do to clear these warn
my version is 
```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by rsese** [comment]
Besides the warning messages, are you having any particular problems with Atom @wilfordw?  In any case, since Atom isn't crashing as described in this issue, I'd suggest opening a new issue and fully filling out the issue template.
