### ISSUE TITLE
Uncaught TypeError: Cannot set property 'className' of undefined

### ISSUE THREAD

**Issue by dontuse** [atom/atom#13464]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot set property 'className' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/line-numbers-tile-component.js:176

TypeError: Cannot set property 'className' of undefined
    at LineNumbersTileComponent.module.exports.LineNumbersTileComponent.updateLineNumberNode (/Applications/Atom.app/Contents/Resources/app.asar/src/line-numbers-tile-component.js:176:24)
    at LineNumbersTileComponent.module.exports.LineNumbersTileComponent.updateLineNumbers (/Applications/Atom.app/Contents/Resources/app.asar/src/line-numbers-tile-component.js:98:16)
    at LineNumbersTileComponent.module.exports.LineNumbersTileComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/line-numbers-tile-component.js:78:19)
    at LineNumberGutterComponent.module.exports.TiledComponent.updateTileNodes (/Applications/Atom.app/Contents/Resources/app.asar/src/tiled-component.js:67:19)
    at LineNumberGutterComponent.module.exports.TiledComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/tiled-component.js:30:12)
    at GutterContainerComponent.module.exports.GutterContainerComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container-component.js:79:25)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:232:39)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:323:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:219:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:59
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-javascript-jsx",
      "react",
      "linter-sass-lint"
    ],
    "telemetryConsent": "no"
  },
  "editor": {
    "fontSize": 11,
    "invisibles": {},
    "preferredLineLength": 100,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (inactive)
color-picker, v2.2.3 (active)
editorconfig, v2.0.5 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.25 (active)
git-plus, v5.29.1 (active)
highlight-selected, v0.11.2 (active)
language-babel, v2.48.5 (active)
language-docker, v1.1.7 (active)
language-haml, v0.24.1 (active)
language-smarty, v1.7.0 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
linter-htmlhint, v1.3.1 (active)
linter-sass-lint, v1.7.4 (inactive)
linter-scss-lint, v3.0.4 (active)
minimap, v4.25.7 (active)
pigments, v0.37.0 (active)
project-manager, v3.3.3 (active)
react-snippets, v0.5.0 (active)
svg-preview, v0.10.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @dontuse, what were you doing when this occurred?

**Comment by lee-dohm** [comment]
@dontuse Any other information you can share with us?

**Comment by lee-dohm** [comment]
Thanks for taking the time to contribute!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/13464#issuecomment-267772117. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by bbwstar** [comment]
Hi there

I am getting same error.

Dossier.js:710 Uncaught TypeError: Cannot set property 'className' of undefined
    at Dossier.checkRequire (Dossier.js:710)
    at Dossier.checkMoi (Dossier.js:1254)
    at Object.ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js:69)
    at executeDispatch (EventPluginUtils.js:85)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:108)
    at executeDispatchesAndRelease (EventPluginHub.js:43)
    at executeDispatchesAndReleaseTopLevel (EventPluginHub.js:54)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (forEachAccumulated.js:24)
    at Object.processEventQueue (EventPluginHub.js:254)

Could you help me?

Thanks
