### ISSUE TITLE
[BUG] When loading settings, Packages, Themes, Updates & Install wont load any content

### ISSUE THREAD

**Issue by clang676** [atom/atom#13470]
* [x] Can you reproduce the problem in [safe mode])? YES
* [x] Are you running the [latest version of Atom]? YES 1.12.7
* [x] Did you check the [debugging guide]? YED also cleared current state
* [x] Did you check the [FAQs on Discuss]? YES
* [x] Are you reporting to the [correct repository]? YES
* [x] Did you [perform a cursory search]to see if your bug or enhancement is already reported? YES

### Description

WHen heading to my atom settings. upon clicking on packages/themes/updates tabs they get stuck loading there respective items. Packages says "Loading packages..." and the search function does nothing. The themes is the same way stuck on "Loading Thmes..." and the search fucntion does nothing. Updates is stuck on "Checking for updates"

Install is also having the same issues, hower with the install tab content there is an error output: This error displays when looking for features packages and searching packages: 

ERROR:
```

module.js:327
    throw err;
    ^
Error: Cannot find module 'delegates'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Charles\AppData\Local\atom\app-1.12.7\resources\app\apm\node_modules\are-we-there-yet\tracker-stream.js:4:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

### Steps to Reproduce

1.Click on settings
2. click on each settings tab

**Expected behavior:** Upon clicking on each tab it should be finding my packages/themes and actually chekc for updates and allow me to browse packages

**Actual behavior:** throws error or nothing happens

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

ATOM: 1.12.7
Electron: 1.3.13
Chome: 52.0.2743.82
Node: 6.5.0

RUNNING apm --version' throws the same error as above: 

`module.js:327
    throw err;
    ^
Error: Cannot find module 'delegates'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Charles\AppData\Local\atom\app-1.12.7\resources\app\apm\node_modules\are-we-there-yet\tracker-stream.js:4:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)`

OS: Windows 10 Pro version 1607 OS Build 14393.576

**Comment by 50Wliu** [comment]
This belongs on the [atom/settings-view](https://github.com/atom/settings-view) repository - can you please move it there?

Also, this error looks like something is missing in your Atom installation.  Can you try uninstalling and reinstalling?  All your preferences will be kept.
