### ISSUE TITLE
Uncaught Error: Notification must be created with string message: undefined

### ISSUE THREAD

**Issue by sumits** [atom/atom#13511]
Steps to reproduce below

1. Right click on a variable and pick Rename Identifier
2. Enter the new name in text field, hit enter 

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Notification must be created with string message: undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:25

Error: Notification must be created with string message: undefined
    at Notification.module.exports.Notification.validate (/Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:25:15)
    at new Notification (/Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:20:12)
    at NotificationManager.module.exports.NotificationManager.addSuccess (/Applications/Atom.app/Contents/Resources/app.asar/src/notification-manager.js:29:35)
    at <anonymous>:59:30
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -8:11.9.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -8:11.5.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -8:09.7.0 editor:newline (atom-text-editor.editor.is-focused)
 71x -7:42.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:03.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -3:21.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -3:19.1.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:22.8.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:21.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:19.8.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:17.5.0 core:undo (atom-text-editor.editor.is-focused)
     -0:10 go-rename:toggle (atom-text-editor.editor.is-focused)
     -0:08.5.0 core:move-left (atom-text-editor.editor.mini.is-focused)
  3x -0:08.1.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  2x -0:07.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:05.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-csharp",
      "language-mustache",
      "language-php",
      "metrics"
    ],
    "telemetryConsent": "no",
    "themes": [
      "atom-material-ui",
      "atom-monokai"
    ]
  },
  "editor": {
    "fontSize": 15,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
go-rename, v0.3.0 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.8 (active)
atom-monokai, v0.10.4 (active)
dash, v1.7.0 (inactive)
file-icons, v1.7.25 (active)
go-debug, v1.0.0 (active)
go-plus, v5.0.7 (active)
go-signature-statusbar, v1.2.0 (active)
highlight-selected, v0.11.2 (active)
hyperclick, v0.0.39 (active)
language-docker, v1.1.7 (active)
linter, v1.11.18 (active)
merge-conflicts, v1.4.4 (active)
monokai, v0.18.0 (inactive)
monokai-seti, v0.7.0 (inactive)
navigator-godef, v1.0.3 (active)
sort-lines, v0.14.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (active)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment]
Thanks for contributing!

It appears that this is being caused by the [go-rename](https://atom.io/packages/go-rename), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
