### ISSUE TITLE
TypeError: Cannot read property 'lintHtmlFiles' of undefined

### ISSUE THREAD

**Issue by WanDoJoe** [atom/atom#13556]
TypeError: Cannot read property 'lintHtmlFiles' of undefined
  at Object.lint (C:\Users\Administrator\.atom\packages\linter-js-standard\lib\linter-js-standard.js:39:18)
  at promises.push.Promise.then._this.emitter.emit.linter (C:\Users\Administrator\.atom\packages\linter\lib\linter-registry.js:95:28)
  at C:\Users\Administrator\.atom\packages\linter\lib\linter-registry.js:94:25
  at Set.forEach (native)
  at LinterRegistry.lint (C:\Users\Administrator\.atom\packages\linter\lib\linter-registry.js:92:20)
  at C:\Users\Administrator\.atom\packages\linter\lib\linter.coffee:98:16
  at Function.module.exports.Emitter.simpleDispatch (C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
  at EditorLinter.lint (C:\Users\Administrator\.atom\packages\linter\lib\editor-linter.js:199:20)
  at Commands.lint (C:\Users\Administrator\.atom\packages\linter\lib\commands.coffee:60:40)
  at C:\Users\Administrator\.atom\packages\linter\lib\linter.coffee:46:17
  at Function.module.exports.Emitter.simpleDispatch (C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
  at Project.module.exports.Project.setPaths (C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\src\project.js:233:27)
  at C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\src\project.js:371:19
  at Provider.module.exports.Provider.provide (C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\service-hub\lib\provider.js:29:52)
  at ServiceHub.module.exports.ServiceHub.provide (C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\service-hub\lib\service-hub.js:30:20)
  at Package.module.exports.Package.activateServices (C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package.js:362:71)
  at Package.module.exports.Package.activateNow (C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package.js:187:16)
  at C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package.js:157:32
  at Package.module.exports.Package.measure (C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package.js:92:15)
  at C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package.js:150:26
  at Package.module.exports.Package.activate (C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package.js:147:34)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package-manager.js:550:34)
  at Object.keys.forEach.name (C:\Users\Administrator\.atom\packages\nuclide\lib\main.js:286:21)
  at Array.forEach (native)
  at Object.activate (C:\Users\Administrator\.atom\packages\nuclide\lib\main.js:283:25)
  at Package.module.exports.Package.activateNow (C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package.js:184:19)
  at C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package.js:157:32
  at Package.module.exports.Package.measure (C:\Users\Administrator\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package.js:92:15)

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [linter-js-standard](https://atom.io/packages/linter-js-standard) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
