### ISSUE TITLE
The entire editor breaks when a UI theme's ui-variables.less references an undefined variable

### ISSUE THREAD

**Issue by matthewlucock** [atom/atom#13555]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

The problem cannot be reproduced in safe mode, as safe mode does not load packages and themes. I recognise that the problem is caused by a package external to Atom. I believe that this is a valid issue despite this. I have met the other prerequisites.

### Description

When a UI theme is selected whose `styles/ui-variables.less` file references an undefined Less variable, and Atom is reloaded, the editor fails to load, and the window remains an empty white box.

### Steps to Reproduce

1. Clone [atom-community/ui-theme-template](https://github.com/atom-community/ui-theme-template).
2. Append `@foo: @bar;` on a new line to `styles/ui-variables.less`. The variable `@bar` is undefined.
3. Run `apm link --dev` in the root of the repository.
4. Open Atom in developer mode (`atom --dev`), navigate to the themes section of the settings screen, and select "Ui Theme Template" from the UI themes dropdown list.
5. Reload Atom in developer mode (I tried both `ctrl + alt + r`, and simply closing Atom and re-opening it with `atom --dev`).

I have only reproduced the problem in developer mode. I have not attempted to reproduce the problem in Atom's normal mode, as I fear being unable to reverse it.

**Expected behavior:** The editor loads.

**Actual behavior:** The editor does not load, and the window remains an empty white box. The Chromium developer tools automatically open to the console.

**Reproduces how often:** Every time.

### Versions

Atom    : 1.12.9
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.12.9
npm  3.10.5
node 4.4.5
python 3.6.0
git 2.11.0.windows.1
visual studio

Microsoft Windows [Version 10.0.14393]

### Additional Information

Here is the stack trace:

    index.js:61 Error
        at new Parser (C:\Users\Matt\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\less\lib\less\parser.js:333:27)
        at LessCache.module.exports.LessCache.parseLess (C:\Users\Matt\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\less-cache\lib\less-cache.js:255:16)
        at LessCache.module.exports.LessCache.cssForFile (C:\Users\Matt\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\less-cache\lib\less-cache.js:286:20)
        at LessCache.module.exports.LessCache.readFileSync (C:\Users\Matt\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\less-cache\lib\less-cache.js:274:19)
        at LessCompileCache.module.exports.LessCompileCache.read (C:\Users\Matt\AppData\Local\atom\app-1.12.9\resources\app.asar\src\less-compile-cache.js:36:25)
        at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\Matt\AppData\Local\atom\app-1.12.9\resources\app.asar\src\theme-manager.js:280:33)
        at ThemeManager.module.exports.ThemeManager.loadStylesheet (C:\Users\Matt\AppData\Local\atom\app-1.12.9\resources\app.asar\src\theme-manager.js:256:21)
        at ThemeManager.module.exports.ThemeManager.requireStylesheet (C:\Users\Matt\AppData\Local\atom\app-1.12.9\resources\app.asar\src\theme-manager.js:174:24)
        at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (C:\Users\Matt\AppData\Local\atom\app-1.12.9\resources\app.asar\src\theme-manager.js:236:12)
        at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (C:\Users\Matt\AppData\Local\atom\app-1.12.9\resources\app.asar\src\theme-manager.js:231:19)
        at new AtomEnvironment (C:\Users\Matt\AppData\Local\atom\app-1.12.9\resources\app.asar\src\atom-environment.js:272:19)
        at module.exports (C:\Users\Matt\AppData\Local\atom\app-1.12.9\resources\app.asar\src\initialize-application-window.js:26:19)
        at setupWindow (file:///C:/Users/Matt/AppData/Local/atom/app-1.12.9/resources/app.asar/static/index.js:81:12)
        at window.onload (file:///C:/Users/Matt/AppData/Local/atom/app-1.12.9/resources/app.asar/static/index.js:41:9)

**Comment by matthewlucock** [comment]
I've attempted to do some investigating and I think I have traced the error to [this line](https://github.com/atom/atom/blob/v1.12.9/src/theme-manager.coffee#L226). When a theme's Less file errors, the error is caught and a notification is given, but the error is re-thrown. I imagine when Atom is loaded and functional, this does not cause problems. However, Atom loads the selected UI theme's `ui-variables.less` to try and adapt its own styling to the selected theme, and it seems to do this as part of the start-up process. Here, the error halts the start-up process, and it remains uncaught until [the very top](https://github.com/atom/atom/blob/v1.12.9/static/index.js#L44).

The obvious fix would be to just not re-throw the error, but I'm not sure if there would be repercussions to that.

**Comment by matthewlucock** [comment]
This behaviour I identified of re-throwing the error is the source of an uncaught exception I was experiencing with [atom/dev-live-reload](https://github.com/atom/dev-live-reload), and trying to debug it made me realise what the problem is here: the selected theme's `ui-variables.less` is imported directly by [`static/atom.less`](https://github.com/atom/atom/blob/v1.12.9/static/atom.less#L7), so if `ui-variables.less` fails to parse, then `static/atom.less` fails to parse, leading to the behaviour this issue highlights.

I think the ideal fix would be an import option in Less that silently skips over the file if it fails to parse, but Less currently does not have such functionality.

**Comment by matthewlucock** [comment]
This behaviour is also experienced when the selected syntax theme's `syntax-variables.less` fails to parse. This makes sense as it is imported in the same manner as `ui-variables.less` in [`static/atom.less`](https://github.com/atom/atom/blob/v1.12.9/static/atom.less#L7).
