### ISSUE TITLE
Atom does not render environment

### ISSUE THREAD

**Issue by chrisgeo** [atom/atom#13560]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Upgraded Atom from 1.12.8 to 1.12.9 and restarted. The editor no longer will render any panes, opened files, etc

### Steps to Reproduce

1. Install 1.12.8 and open multiple files in two side by side panes.
2. Use auto-update to install 1.12.9
3. Reopen Atom

**Expected behavior:** [What you expect to happen]

To render an open file or empty pane

**Actual behavior:** [What actually happens]

Blank Editor:
![image](https://cloud.githubusercontent.com/assets/216250/21734053/4ec27222-d416-11e6-954f-756b4c7ddfe8.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]

All the time

### Versions
1.12.9

### Additional Information

```
/Applications/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11 Uncaught (in promise) Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11:15)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:389:25)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:368:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:95:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.didAddPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:308:27)
    at Pane.module.exports.Pane.setContainer (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:131:26)
    at PaneAxis.module.exports.PaneAxis.setContainer (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:88:30)
    at PaneContainer.module.exports.PaneContainer.setRoot (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:162:17)
    at PaneContainer.module.exports.PaneContainer.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:62:12)
    at Workspace.module.exports.Workspace.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:171:33)
    at AtomEnvironment.module.exports.AtomEnvironment.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1063:24)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:775:21
```

**Comment by chrisgeo** [comment]
Looks like it might be the same as this: https://github.com/atom/tabs/issues/234 

Please feel free to closed if that's the case

**Comment by morganick** [comment]
@chrisgeo I have the same issue but only in one of my EmberJS projects. My Ruby or Elm projects do not have this issue either. This only happened on upgrade to 1.12.8 and continued when updated to 1.12.9.

**Comment by damieng** [comment]
I would suggest starting Atom from the command line and using the --clear-window-state flag to reset the Window info for that project, e.g.

```bash
cd Source/myapp
atom --clear-window-state .
```

**Comment by lee-dohm** [comment]
This sounds like some state got corrupted. If `atom --clear-window-state` doesn't solve this for you, let us know and we'll reopen the issue to investigate more.
