### ISSUE TITLE
Atom prompts to upgrade from Beta to Stable channel, breaking install on Windows

### ISSUE THREAD

**Issue by ThiconZ** [atom/atom#13607]
### Description

After starting build 1.13.0-beta8 and clicking ```Restart and install``` to update to build 1.14.0-beta0 Atom restarted but prompted me to update again. Without checking the version number I clicked update again and just after doing so noticed I was on the version I intended to update to. The one listed that I was now going to update to was a lower version number. This resulted in the Atom shortcut in Windows being changed from ```AppData\Local\atom\Update.exe --processStart "atom.exe"``` to ```AppData\Local\atom\atom.exe``` and breaking the shortcut as that file does not exist.

To temporarily workaround this issue I had to restore both my Atom install folder and my desktop from a windows shadow copy created before the Atom update took place. Then disable the auto download and update within Atom to prevent it from entering the broken state again.

### Steps to Reproduce

1. Launch Atom 1.13.0-beta8
2. Select Restart & Install Update to update to Atom 1.14.0-beta0
3. Once Atom restarts observe it prompts a notification to update to a "newer" version again
4. Observe the "newer" version, which appears to be listed as the current stable branch version, is lower than currently installed version (if Atuomatically download updates is checked, in my case it is) observe that Atom will begin to download the "new update" automatically.
5. Select Restart and install
6. Once Atom restarts, exit it and observe the Windows shortcut is now directing to an invalid path
7. Go to where Atom's shortcut is now pointing to: ```AppData\Local\atom\atom.exe``` and observe that there is no atom.exe and both versions of Atom are listed in the directory.

**Expected behavior:** Atom does not incorrectly prompt to update to an older version of Atom that ends up breaking your install.

**Actual behavior:** Atom fails to install the older version and breaks the current install.

**Reproduces how often:** The initial issue happened once (unable to recreate the situation to do it again. However, selecting to "update" when prompted to after directly running Atom from ```AppData\Local\atom\app-1.14.0-beta0\atom.exe``` results in the same failed update and continues to keep the install broken.

### Versions
Atom    : 1.14.0-beta0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Windows 7 Ultimate 64bit

### Additional Information
Picture of About tab:
![image](https://cloud.githubusercontent.com/assets/6924950/21924615/ec9117de-d947-11e6-9c55-b20d3fae416f.png)

Relevant Squirrel Log Data:
```
2017-01-12 23:53:49> Program: Starting Squirrel Updater: --processStart atom.exe
2017-01-12 23:53:49> Program: Want to launch 'C:\Users\Xennma\AppData\Local\atom\app-1.13.0-beta8\atom.exe'
2017-01-12 23:53:49> Program: About to launch: 'C:\Users\Xennma\AppData\Local\atom\app-1.13.0-beta8\atom.exe': 
2017-01-12 23:53:57> Program: Starting Squirrel Updater: --download https://atom.io/api/updates?version=1.13.0-beta8
2017-01-12 23:53:57> Program: Fetching update information, downloading from https://atom.io/api/updates?version=1.13.0-beta8
2017-01-12 23:53:57> CheckForUpdateImpl: Using existing staging user ID: c72496bb-85b4-51b5-936a-ac7a60068ccb
2017-01-12 23:53:57> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates?version=1.13.0-beta8
2017-01-12 23:53:57> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES?version=1.13.0-beta8&id=atom&localVersion=1.13.0-beta8&arch=amd64
2017-01-12 23:54:08> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.14.0-beta0-delta.nupkg
2017-01-12 23:54:11> UpdateInfo: Couldn't get release notes for:atom-1.14.0-beta0-delta.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\Xennma\AppData\Local\atom\packages\atom-1.14.0-beta0-delta.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2017-01-12 23:54:11> Program: Starting Squirrel Updater: --update https://atom.io/api/updates?version=1.13.0-beta8
2017-01-12 23:54:11> Program: Starting update, downloading from https://atom.io/api/updates?version=1.13.0-beta8
2017-01-12 23:54:11> Program: About to update to: C:\Users\Xennma\AppData\Local\atom
2017-01-12 23:54:11> CheckForUpdateImpl: Using existing staging user ID: c72496bb-85b4-51b5-936a-ac7a60068ccb
2017-01-12 23:54:11> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates?version=1.13.0-beta8
2017-01-12 23:54:11> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES?version=1.13.0-beta8&id=atom&localVersion=1.13.0-beta8&arch=amd64
2017-01-12 23:54:11> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.14.0-beta0-delta.nupkg
2017-01-12 23:55:31> DeltaPackageBuilder: Applying BSDiff to lib\net45\atom.exe.bsdiff
2017-01-12 23:55:33> DeltaPackageBuilder: Patched file lib\net45\atom.exe.bsdiff has incorrect SHA1, expected 55791A2B9F4691E87372CA26584EA4920ED94493, got 5EE4428059FF5C7ECECF4812226FC918ED18C9E7
2017-01-12 23:55:39> Program: Failed to apply updates, falling back to full updates: Squirrel.ChecksumFailedException: Exception of type 'Squirrel.ChecksumFailedException' was thrown.
   at Squirrel.DeltaPackageBuilder.verifyPatchedFile(String relativeFilePath, String inputFile, String tempTargetFile)
   at Squirrel.DeltaPackageBuilder.applyDiffToFile(String deltaPath, String relativeFilePath, String workingDirectory)
   at Squirrel.DeltaPackageBuilder.<>c__DisplayClass3_1.<ApplyDeltaPackage>b__4(String file)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8_0.<createFullPackagesFromDeltas>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__5.MoveNext()
2017-01-12 23:55:39> CheckForUpdateImpl: Using existing staging user ID: c72496bb-85b4-51b5-936a-ac7a60068ccb
2017-01-12 23:55:39> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates?version=1.13.0-beta8
2017-01-12 23:55:39> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES?version=1.13.0-beta8&id=atom&localVersion=1.13.0-beta8&arch=amd64
2017-01-12 23:55:39> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.14.0-beta0-full.nupkg
2017-01-12 23:55:47> ApplyReleasesImpl: Writing files to app directory: C:\Users\Xennma\AppData\Local\atom\app-1.14.0-beta0
2017-01-12 23:55:57> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Xennma\AppData\Local\atom\app-1.14.0-beta0\atom.exe,C:\Users\Xennma\AppData\Local\atom\app-1.14.0-beta0\atom_ExecutionStub.exe]
2017-01-12 23:56:03> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-01-12 23:56:03> ApplyReleasesImpl: Examining Pin: Aurora.lnk
2017-01-12 23:56:03> ApplyReleasesImpl: Examining Pin: Google Chrome Canary.lnk
2017-01-12 23:56:03> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-01-12 23:56:03> ApplyReleasesImpl: Examining Pin: Windows Media Player.lnk
2017-01-12 23:56:03> ApplyReleasesImpl: Fixing up tray icons
2017-01-12 23:56:03> ApplyReleasesImpl: cleanDeadVersions: for version 1.14.0-beta0
2017-01-12 23:56:03> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.13.0-beta8
2017-01-12 23:56:03> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.14.0-beta0
 C:\Users\Xennma\AppData\Local\atom\Update.exe, workingDir C:\Users\Xennma\AppData\Local\atom\app-1.14.0-beta0, args --processStart "atom.exe")
2017-01-12 23:55:59> ApplyReleasesImpl: Examining Pin: Aurora.lnk
2017-01-12 23:55:59> ApplyReleasesImpl: Examining Pin: Google Chrome Canary.lnk
2017-01-12 23:55:59> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-01-12 23:55:59> ApplyReleasesImpl: Examining Pin: Windows Media Player.lnk
2017-01-13 01:12:35> Program: Starting Squirrel Updater: --download https://atom.io/api/updates
2017-01-13 01:12:35> Program: Fetching update information, downloading from https://atom.io/api/updates
2017-01-13 01:12:35> CheckForUpdateImpl: Using existing staging user ID: c72496bb-85b4-51b5-936a-ac7a60068ccb
2017-01-13 01:12:35> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
2017-01-13 01:12:35> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES?id=atom&localVersion=1.14.0-beta0&arch=amd64
2017-01-13 01:12:35> CheckForUpdateImpl: hwhat, local version is greater than remote version
2017-01-13 01:12:35> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.13.0-full.nupkg
2017-01-13 01:12:41> UpdateInfo: Couldn't get release notes for:atom-1.13.0-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\Xennma\AppData\Local\atom\packages\atom-1.13.0-full.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2017-01-13 01:12:41> Program: Starting Squirrel Updater: --update https://atom.io/api/updates
2017-01-13 01:12:41> Program: Starting update, downloading from https://atom.io/api/updates
2017-01-13 01:12:41> Program: About to update to: C:\Users\Xennma\AppData\Local\atom
2017-01-13 01:12:41> CheckForUpdateImpl: Using existing staging user ID: c72496bb-85b4-51b5-936a-ac7a60068ccb
2017-01-13 01:12:41> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
2017-01-13 01:12:41> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES?id=atom&localVersion=1.14.0-beta0&arch=amd64
2017-01-13 01:12:53> CheckForUpdateImpl: hwhat, local version is greater than remote version
2017-01-13 01:12:53> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.13.0-full.nupkg
2017-01-13 01:12:58> ApplyReleasesImpl: Writing files to app directory: C:\Users\Xennma\AppData\Local\atom\app-1.13.0
2017-01-13 01:13:02> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Xennma\AppData\Local\atom\app-1.14.0-beta0\atom.exe,C:\Users\Xennma\AppData\Local\atom\app-1.14.0-beta0\atom_ExecutionStub.exe]
2017-01-13 01:13:04> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-01-13 01:13:04> ApplyReleasesImpl: Examining Pin: Aurora.lnk
2017-01-13 01:13:04> ApplyReleasesImpl: Examining Pin: Google Chrome Canary.lnk
2017-01-13 01:13:04> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-01-13 01:13:04> ApplyReleasesImpl: Examining Pin: Windows Media Player.lnk
2017-01-13 01:13:04> ApplyReleasesImpl: Fixing up tray icons
2017-01-13 01:13:04> ApplyReleasesImpl: cleanDeadVersions: for version 1.14.0-beta0
2017-01-13 01:13:04> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.14.0-beta0
2017-01-13 01:13:04> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.14.0-beta0
2017-01-13 01:13:36> Program: Starting Squirrel Updater: --download https://atom.io/api/updates
2017-01-13 01:13:36> Program: Fetching update information, downloading from https://atom.io/api/updates
2017-01-13 01:13:36> CheckForUpdateImpl: Using existing staging user ID: c72496bb-85b4-51b5-936a-ac7a60068ccb
2017-01-13 01:13:36> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
2017-01-13 01:13:36> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES?id=atom&localVersion=1.14.0-beta0&arch=amd64
2017-01-13 01:13:36> CheckForUpdateImpl: hwhat, local version is greater than remote version
2017-01-13 01:13:36> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.13.0-full.nupkg
2017-01-13 01:13:42> UpdateInfo: Couldn't get release notes for:atom-1.13.0-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\Xennma\AppData\Local\atom\packages\atom-1.13.0-full.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2017-01-13 01:13:42> Program: Starting Squirrel Updater: --update https://atom.io/api/updates
2017-01-13 01:13:42> Program: Starting update, downloading from https://atom.io/api/updates
2017-01-13 01:13:42> Program: About to update to: C:\Users\Xennma\AppData\Local\atom
2017-01-13 01:13:42> CheckForUpdateImpl: Using existing staging user ID: c72496bb-85b4-51b5-936a-ac7a60068ccb
2017-01-13 01:13:42> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
2017-01-13 01:13:42> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES?id=atom&localVersion=1.14.0-beta0&arch=amd64
2017-01-13 01:13:42> CheckForUpdateImpl: hwhat, local version is greater than remote version
2017-01-13 01:13:42> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.13.0-full.nupkg
2017-01-13 01:13:48> ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\Xennma\AppData\Local\atom\app-1.13.0
2017-01-13 01:13:48> ApplyReleasesImpl: Writing files to app directory: C:\Users\Xennma\AppData\Local\atom\app-1.13.0
2017-01-13 01:13:53> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Xennma\AppData\Local\atom\app-1.14.0-beta0\atom.exe,C:\Users\Xennma\AppData\Local\atom\app-1.14.0-beta0\atom_ExecutionStub.exe]
2017-01-13 01:13:55> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-01-13 01:13:55> ApplyReleasesImpl: Examining Pin: Aurora.lnk
2017-01-13 01:13:55> ApplyReleasesImpl: Examining Pin: Google Chrome Canary.lnk
2017-01-13 01:13:55> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-01-13 01:13:55> ApplyReleasesImpl: Examining Pin: Windows Media Player.lnk
2017-01-13 01:13:55> ApplyReleasesImpl: Fixing up tray icons
2017-01-13 01:13:55> ApplyReleasesImpl: cleanDeadVersions: for version 1.14.0-beta0
2017-01-13 01:13:55> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.14.0-beta0
2017-01-13 01:13:55> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.14.0-beta0
2017-01-13 01:17:42> Program: Starting Squirrel Updater: --download https://atom.io/api/updates
2017-01-13 01:17:42> Program: Fetching update information, downloading from https://atom.io/api/updates
2017-01-13 01:17:42> CheckForUpdateImpl: Using existing staging user ID: c72496bb-85b4-51b5-936a-ac7a60068ccb
2017-01-13 01:17:42> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
2017-01-13 01:17:42> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES?id=atom&localVersion=1.14.0-beta0&arch=amd64
2017-01-13 01:17:53> CheckForUpdateImpl: hwhat, local version is greater than remote version
2017-01-13 01:17:53> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.13.0-full.nupkg
2017-01-13 01:17:59> UpdateInfo: Couldn't get release notes for:atom-1.13.0-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\Xennma\AppData\Local\atom\packages\atom-1.13.0-full.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2017-01-13 01:17:59> Program: Starting Squirrel Updater: --update https://atom.io/api/updates
2017-01-13 01:17:59> Program: Starting update, downloading from https://atom.io/api/updates
2017-01-13 01:17:59> Program: About to update to: C:\Users\Xennma\AppData\Local\atom
2017-01-13 01:17:59> CheckForUpdateImpl: Using existing staging user ID: c72496bb-85b4-51b5-936a-ac7a60068ccb
2017-01-13 01:17:59> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
2017-01-13 01:17:59> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES?id=atom&localVersion=1.14.0-beta0&arch=amd64
2017-01-13 01:17:59> CheckForUpdateImpl: hwhat, local version is greater than remote version
2017-01-13 01:17:59> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.13.0-full.nupkg
2017-01-13 01:18:05> ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\Xennma\AppData\Local\atom\app-1.13.0
2017-01-13 01:18:05> ApplyReleasesImpl: Writing files to app directory: C:\Users\Xennma\AppData\Local\atom\app-1.13.0
2017-01-13 01:18:09> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Xennma\AppData\Local\atom\app-1.14.0-beta0\atom.exe,C:\Users\Xennma\AppData\Local\atom\app-1.14.0-beta0\atom_ExecutionStub.exe]
2017-01-13 01:18:11> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-01-13 01:18:11> ApplyReleasesImpl: Examining Pin: Aurora.lnk
2017-01-13 01:18:11> ApplyReleasesImpl: Examining Pin: Google Chrome Canary.lnk
2017-01-13 01:18:11> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-01-13 01:18:11> ApplyReleasesImpl: Examining Pin: Windows Media Player.lnk
2017-01-13 01:18:11> ApplyReleasesImpl: Fixing up tray icons
2017-01-13 01:18:11> ApplyReleasesImpl: cleanDeadVersions: for version 1.14.0-beta0
2017-01-13 01:18:11> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.14.0-beta0
2017-01-13 01:18:11> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.14.0-beta0
2017-01-13 01:20:46> Program: Starting Squirrel Updater: --download https://atom.io/api/updates
2017-01-13 01:20:46> Program: Fetching update information, downloading from https://atom.io/api/updates
2017-01-13 01:20:46> CheckForUpdateImpl: Using existing staging user ID: c72496bb-85b4-51b5-936a-ac7a60068ccb
2017-01-13 01:20:46> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
2017-01-13 01:20:46> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES?id=atom&localVersion=1.14.0-beta0&arch=amd64
2017-01-13 01:20:46> CheckForUpdateImpl: hwhat, local version is greater than remote version
2017-01-13 01:20:46> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.13.0-full.nupkg
2017-01-13 01:20:52> UpdateInfo: Couldn't get release notes for:atom-1.13.0-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\Xennma\AppData\Local\atom\packages\atom-1.13.0-full.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2017-01-13 01:20:52> Program: Starting Squirrel Updater: --update https://atom.io/api/updates
2017-01-13 01:20:52> Program: Starting update, downloading from https://atom.io/api/updates
2017-01-13 01:20:52> Program: About to update to: C:\Users\Xennma\AppData\Local\atom
2017-01-13 01:20:52> CheckForUpdateImpl: Using existing staging user ID: c72496bb-85b4-51b5-936a-ac7a60068ccb
2017-01-13 01:20:52> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
2017-01-13 01:20:52> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES?id=atom&localVersion=1.14.0-beta0&arch=amd64
2017-01-13 01:20:52> CheckForUpdateImpl: hwhat, local version is greater than remote version
2017-01-13 01:20:52> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.13.0-full.nupkg
2017-01-13 01:20:58> ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\Xennma\AppData\Local\atom\app-1.13.0
2017-01-13 01:20:58> ApplyReleasesImpl: Writing files to app directory: C:\Users\Xennma\AppData\Local\atom\app-1.13.0
2017-01-13 01:21:05> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Xennma\AppData\Local\atom\app-1.14.0-beta0\atom.exe,C:\Users\Xennma\AppData\Local\atom\app-1.14.0-beta0\atom_ExecutionStub.exe]
2017-01-13 01:21:07> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-01-13 01:21:07> ApplyReleasesImpl: Examining Pin: Aurora.lnk
2017-01-13 01:21:07> ApplyReleasesImpl: Examining Pin: Google Chrome Canary.lnk
2017-01-13 01:21:07> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-01-13 01:21:07> ApplyReleasesImpl: Examining Pin: Windows Media Player.lnk
2017-01-13 01:21:07> ApplyReleasesImpl: Fixing up tray icons
2017-01-13 01:21:07> ApplyReleasesImpl: cleanDeadVersions: for version 1.14.0-beta0
2017-01-13 01:21:07> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.14.0-beta0
2017-01-13 01:21:07> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.14.0-beta0
2017-01-13 03:04:36> Program: Starting Squirrel Updater: --download https://atom.io/api/updates
2017-01-13 03:04:36> Program: Fetching update information, downloading from https://atom.io/api/updates
2017-01-13 03:04:36> CheckForUpdateImpl: Using existing staging user ID: c72496bb-85b4-51b5-936a-ac7a60068ccb
2017-01-13 03:04:36> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
2017-01-13 03:04:37> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES?id=atom&localVersion=1.14.0-beta0&arch=amd64
2017-01-13 03:04:37> CheckForUpdateImpl: hwhat, local version is greater than remote version
2017-01-13 03:04:37> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.13.0-full.nupkg
2017-01-13 03:04:44> UpdateInfo: Couldn't get release notes for:atom-1.13.0-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\Xennma\AppData\Local\atom\packages\atom-1.13.0-full.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
```

**Comment by dev169** [comment]
I've hit this exact issue as well.

**Comment by damieng** [comment]
We've identified the cause - looking at fixes right now.

**Comment by damieng** [comment]
Atom 1.14.0-beta1 is out which resolves this problem - you'll need to manually download and run AtomSetup.exe or AtomSetup64.exe to upgrade though as the updater in beta0 was broken.

**Comment by lee-dohm** [comment]
@stanzilla Reports this happening with v1.15.0-beta0 wanting to "upgrade" to v1.14.0. Unable to reproduce on macOS.

**Comment by pingshunhuangalex** [comment]
@50Wliu @damieng Same issue with Win10 laptop.

**Comment by Stanzilla** [comment]
At first I thought it was https://github.com/atom/about/issues/24 again, but nope :)

**Comment by peppy** [comment]
can reproduce. endless loop trying to update to stable:

![image](https://cloud.githubusercontent.com/assets/191335/22771069/ed473550-eed7-11e6-9a80-8bb776d4292b.png)

**Comment by damieng** [comment]
We have identified the problem and have a fix and are now looking at how to get it deployed efficiently.

In the mean time you can temporarily uncheck the Automatically download updates checkbox.

**Comment by damieng** [comment]
1.15.0-beta1 is now out that fixes this issue. 

You will unfortunately need to manually download an AtomSetup.exe (or AtomSetup64.exe for 64-bit users) to get from 1.15.0-beta0 to 1.15.0-beta1 as the auto-update is clearly broken in 1.15.0-beta0.

**Comment by pingshunhuangalex** [comment]
@damieng Do we need a clean installation or just simply running the installer on top of everything is fine? Thanks.

**Comment by damieng** [comment]
You can just run the installer over the top - no data or configuration will be affected and it should automatically deal with the previous version in add/remove programs etc.

**Comment by Stanzilla** [comment]
@damieng installed beta1 via the setup and it updated fine but the squirrel icon refuses to go away. it's still blue yet atom claims it is up to date (which is correct)

**Comment by 50Wliu** [comment]
Sounds like it's still caching an invalid Atom version.  What does `localStorage.getItem('about:update-available')` return?

**Comment by Stanzilla** [comment]
`1.14.1`

**Comment by jolsenmultiad** [comment]
Do you simply execute localStorage.getItem('about:update-available') in the console? If so, I got a 'null' response and I see the squirrel icon and "About Atom" reports "1.15.0-beta1 x64" with "Atom is up to date!"

**Comment by Stanzilla** [comment]
yeah just paste it or wrap into `console.log()` but it's `version-available` @50Wliu just typoed it :P

**Comment by jolsenmultiad** [comment]
Ok--thank you. I got the same results you did (1.14.1)

**Comment by Ben3eeE** [comment]
Thanks for the reports about the update squirrel staying even though you are on the latest version :bowing_man: 
I have reopened https://github.com/atom/about/issues/50 with steps to reproduce the issue. Please subscribe there for updates.
