### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by hucan7** [atom/atom#13620]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I want to install atom by building the source code in Linux environment, but get failed.

### Steps to Reproduce

1. git clone https://github.com/atom/atom.git
2. cd atom
3. npm config set python /.tool/bin/python -g
4. script/build
5. wait for a few minutes after printing "Installing apm" on the screen.
6. the error will be displayed.

**Expected behavior:** [What you expect to happen]
Install successfully

**Actual behavior:** [What actually happens]
The error info as following:
```
Node:   v6.9.4
Npm:    v4.1.1
Installing script dependencies
Installing apm
module.js:327
    throw err;
    ^

Error: Cannot find module '../build/Release/git.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/.tool/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/.tool/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
child_process.js:506
    throw err;
    ^

Error: Command failed: /.tool/atom/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:483:13)
    at Object.execFileSync (child_process.js:503:13)
    at module.exports (/.tool/atom/script/lib/install-atom-dependencies.js:15:16)
    at Object.<anonymous> (/.tool/atom/script/bootstrap:28:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
After getting the error, I run clear, and build again, still get the same error.

### Versions
OS: RHEL 5.7
Python version: v2.6.9
Node version: v6.9.4
Npm version: v4.1.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by lee-dohm** [comment]
Is the version of python you have installed at `/.tool/bin/python` v2 or v3?

**Comment by hucan7** [comment]
It's v2, v2.6.9
