### ISSUE TITLE
script/build failing on MacOSX: Access denied for atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules

### ISSUE THREAD

**Issue by doriable** [atom/atom#13699]
### Description

Having issues running `script/build`.
I'm currently on MacOSX 10.11.6. When I run `sudo script/build` it gives the following:

```
doriakeung @ ~/atom (master)$ sudo script/build
Node:	v4.4.5
Npm:	v3.10.10
Installing script dependencies
Installing apm
../src/onig-string.cc:25:40: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
  hasMultiByteChars = (value->Length() != utf8_length_);
                       ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
1 warning generated.
../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                        ~~~ ^
1 warning generated.
../src/onig-string.cc:25:40: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
  hasMultiByteChars = (value->Length() != utf8_length_);
                       ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
1 warning generated.
../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                        ~~~ ^
1 warning generated.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/doriakeung/atom/apm/node_modules/atom-package-manager/bin/node" "/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/.bin/npm" "dedupe"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! path /Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doriakeung/atom/apm/node_modules/atom-package-manager/npm-debug.log
module.js:327
    throw err;
    ^

Error: Cannot find module 'node-gyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at Install.module.exports.Install.installNode (/Users/doriakeung/atom/apm/node_modules/atom-package-manager/lib/install.js:103:67)
    at /Users/doriakeung/atom/apm/node_modules/atom-package-manager/lib/install.js:3:59
    at fn (/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/async/lib/async.js:582:34)
    at Immediate._onImmediate (/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/async/lib/async.js:498:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
child_process.js:487
    throw err;
    ^

Error: Command failed: /Users/doriakeung/atom/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:464:13)
    at Object.execFileSync (child_process.js:484:13)
    at module.exports (/Users/doriakeung/atom/script/lib/install-atom-dependencies.js:15:16)
    at Object.<anonymous> (/Users/doriakeung/atom/script/bootstrap:28:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

Output from the latter portion of the logs pertaining to the issue:

```
19 silly idealTree ├── y18n@3.2.1
19 silly idealTree └── yargs@3.32.0
20 silly generateActionsToTake Starting
21 silly dedupe generateActionsToTake
22 silly hoist Starting
23 silly hoist Finishing
24 silly sort-actions Starting
25 silly sort-actions Finishing
26 warn checkPermissions Missing write access to /Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules
27 warn checkPermissions Missing write access to /Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules
28 silly rollbackFailedOptional Starting
29 silly rollbackFailedOptional Finishing
30 silly runTopLevelLifecycles Starting
31 silly runTopLevelLifecycles Finishing
32 silly install printInstalled
33 verbose stack Error: EACCES: permission denied, access '/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules'
33 verbose stack     at Error (native)
34 verbose cwd /Users/doriakeung/atom/apm/node_modules/atom-package-manager
35 error Darwin 15.6.0
36 error argv "/Users/doriakeung/atom/apm/node_modules/atom-package-manager/bin/node" "/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/.bin/npm" "dedupe"
37 error node v4.4.5
38 error npm  v3.10.5
39 error path /Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules
40 error code EACCES
41 error errno -13
42 error syscall access
43 error Error: EACCES: permission denied, access '/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules'
43 error     at Error (native)
43 error  { [Error: EACCES: permission denied, access '/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules']
43 error   errno: -13,
43 error   code: 'EACCES',
43 error   syscall: 'access',
43 error   path: '/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules' }
44 error Please try running this command again as root/Administrator.
45 verbose exit [ -13, true ]
```

### Things I've tried

I did a `git pull` right before building, and I've also retried by first running `sudo script/clean` then rerunning the build. Xcode and command line tools are up-to-date also:

```
doriakeung @ ~$ xcode-select --version
xcode-select version 2343.
doriakeung @ ~$ which libtool
/opt/local/bin/libtool
doriakeung @ ~$ which xcode-select
/usr/bin/xcode-select
```

**Comment by doriable** [comment]
Just spotted this commit on the documentation:
https://github.com/atom/atom/commit/c7bc416ceaf4a585a56fb393c7e23ae4d0ca4bc7

I will upgrade my Node version and try the build again and close out the issue as needed! Thanks!

**Comment by doriable** [comment]
Nope, I upgraded both my Node version and NPM version, and looks like it still can't build:\

```
doriakeung @ ~/atom (master)$ sudo script/build
Node:	v6.6.0
Npm:	v4.1.2
Installing script dependencies
Installing apm
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:196:
../node_modules/nan/nan_maybe_43_inl.h:220:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/doriakeung/.node-gyp/6.6.0/include/node/v8.h:3032:36: note: 'CloneElementAt' has been explicitly marked deprecated here
                MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                   ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:202:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/doriakeung/.node-gyp/6.6.0/include/node/v8.h:4007:56: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                       ^
In file included from ../src/main.cc:1:
../node_modules/nan/nan.h:2017:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/doriakeung/.node-gyp/6.6.0/include/node/v8.h:2751:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<Name> name,
                     ^
3 warnings generated.
../src/onig-string.cc:25:40: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
  hasMultiByteChars = (value->Length() != utf8_length_);
                       ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
1 warning generated.
../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                        ~~~ ^
1 warning generated.
../src/onig-string.cc:25:40: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
  hasMultiByteChars = (value->Length() != utf8_length_);
                       ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
1 warning generated.
../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                        ~~~ ^
1 warning generated.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/doriakeung/atom/apm/node_modules/atom-package-manager/bin/node" "/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/.bin/npm" "dedupe"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! path /Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doriakeung/atom/apm/node_modules/atom-package-manager/npm-debug.log
module.js:327
    throw err;
    ^

Error: Cannot find module 'node-gyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at Install.module.exports.Install.installNode (/Users/doriakeung/atom/apm/node_modules/atom-package-manager/lib/install.js:103:67)
    at /Users/doriakeung/atom/apm/node_modules/atom-package-manager/lib/install.js:3:59
    at fn (/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/async/lib/async.js:582:34)
    at Immediate._onImmediate (/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/async/lib/async.js:498:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
child_process.js:506
    throw err;
    ^

Error: Command failed: /Users/doriakeung/atom/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:483:13)
    at Object.execFileSync (child_process.js:503:13)
    at module.exports (/Users/doriakeung/atom/script/lib/install-atom-dependencies.js:15:16)
    at Object.<anonymous> (/Users/doriakeung/atom/script/bootstrap:28:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
```

Output from NPM logs:

```
19 silly idealTree └── yargs@3.32.0
20 silly generateActionsToTake Starting
21 silly dedupe generateActionsToTake
22 silly hoist Starting
23 silly hoist Finishing
24 silly sort-actions Starting
25 silly sort-actions Finishing
26 warn checkPermissions Missing write access to /Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules
27 warn checkPermissions Missing write access to /Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules
28 silly rollbackFailedOptional Starting
29 silly rollbackFailedOptional Finishing
30 silly runTopLevelLifecycles Starting
31 silly runTopLevelLifecycles Finishing
32 silly install printInstalled
33 verbose stack Error: EACCES: permission denied, access '/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules'
33 verbose stack     at Error (native)
34 verbose cwd /Users/doriakeung/atom/apm/node_modules/atom-package-manager
35 error Darwin 15.6.0
36 error argv "/Users/doriakeung/atom/apm/node_modules/atom-package-manager/bin/node" "/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/.bin/npm" "dedupe"
37 error node v4.4.5
38 error npm  v3.10.5
39 error path /Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules
40 error code EACCES
41 error errno -13
42 error syscall access
43 error Error: EACCES: permission denied, access '/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules'
43 error     at Error (native)
43 error  { [Error: EACCES: permission denied, access '/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules']
43 error   errno: -13,
43 error   code: 'EACCES',
43 error   syscall: 'access',
43 error   path: '/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules' }
44 error Please try running this command again as root/Administrator.
45 verbose exit [ -13, true ]
```

**Comment by lee-dohm** [comment]
We don't build Atom using `sudo`. You may need to completely clean your repository because of the permissions that `sudo` will leave behind in order to fix this problem.

**Comment by doriable** [comment]
I deleted the repository and re-cloned it. Reran the build script and got the following:

```
doriakeung @ ~/atom (master)$ script/build
Node:	v6.6.0
Npm:	v4.1.2
Installing script dependencies
Installing apm
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:196:
../node_modules/nan/nan_maybe_43_inl.h:220:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/doriakeung/.node-gyp/6.6.0/include/node/v8.h:3032:36: note: 'CloneElementAt' has been explicitly marked deprecated here
                MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                   ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:202:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/doriakeung/.node-gyp/6.6.0/include/node/v8.h:4007:56: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                       ^
In file included from ../src/main.cc:1:
../node_modules/nan/nan.h:2017:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/doriakeung/.node-gyp/6.6.0/include/node/v8.h:2751:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<Name> name,
                     ^
3 warnings generated.
../src/onig-string.cc:25:40: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
  hasMultiByteChars = (value->Length() != utf8_length_);
                       ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
1 warning generated.
../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                        ~~~ ^
1 warning generated.
../src/onig-string.cc:25:40: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
  hasMultiByteChars = (value->Length() != utf8_length_);
                       ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
1 warning generated.
../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                        ~~~ ^
1 warning generated.
Installing modules ✗
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/doriakeung/atom/apm/node_modules/atom-package-manager/bin/node" "/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/doriakeung/.atom/.apm/.apmrc" "--userconfig" "/Users/doriakeung/.atom/.apmrc" "install" "--runtime=electron" "--target=1.3.13" "--arch=x64"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 151.101.40.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doriakeung/atom/npm-debug.log
child_process.js:506
    throw err;
    ^

Error: Command failed: /Users/doriakeung/atom/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:483:13)
    at Object.execFileSync (child_process.js:503:13)
    at module.exports (/Users/doriakeung/atom/script/lib/install-atom-dependencies.js:15:16)
    at Object.<anonymous> (/Users/doriakeung/atom/script/bootstrap:28:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
```

I have experienced some network issues recently, I will attempt to run the installation elsewhere, but I have been consistently running into the issue above after I re-cloned the repository and ran the build + clean scripts a couple of times.

**Comment by 50Wliu** [comment]
Are you behind a proxy?

**Comment by doriable** [comment]
Nope, I am not behind a proxy. I did have high latency issues this weekend, however my network is doing okay right now:

```
--- google.com ping statistics ---
22 packets transmitted, 22 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 7.889/13.465/25.595/5.141 ms
```

Still getting the same errors. Quick question regarding the errors I am seeing, I'm running npm v4.1.2

```
doriakeung @ ~/atom (master)$ npm --version
4.1.2
```

However, in the errors below (full stack trace available underneath), I am seeing the following:

```
Installing modules ✗
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/doriakeung/atom/apm/node_modules/atom-package-manager/bin/node" "/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/doriakeung/.atom/.apm/.apmrc" "--userconfig" "/Users/doriakeung/.atom/.apmrc" "install" "--runtime=electron" "--target=1.3.13" "--arch=x64"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
```

Why is the error showing npm v3.10.5? Should I downgrade my version to npm v3.10.5?

Full stack trace:

```
doriakeung @ ~/atom (master)$ script/build
Node:	v6.6.0
Npm:	v4.1.2
Installing script dependencies
Installing apm
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:196:
../node_modules/nan/nan_maybe_43_inl.h:220:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/doriakeung/.node-gyp/6.6.0/include/node/v8.h:3032:36: note: 'CloneElementAt' has been explicitly marked deprecated here
                MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                   ^
In file included from ../src/main.cc:1:
In file included from ../node_modules/nan/nan.h:202:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/doriakeung/.node-gyp/6.6.0/include/node/v8.h:4007:56: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                       ^
In file included from ../src/main.cc:1:
../node_modules/nan/nan.h:2017:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/doriakeung/.node-gyp/6.6.0/include/node/v8.h:2751:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<Name> name,
                     ^
3 warnings generated.
../src/onig-string.cc:25:40: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
  hasMultiByteChars = (value->Length() != utf8_length_);
                       ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
1 warning generated.
../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                        ~~~ ^
1 warning generated.
../src/onig-string.cc:25:40: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
  hasMultiByteChars = (value->Length() != utf8_length_);
                       ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
1 warning generated.
../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                        ~~~ ^
1 warning generated.
Installing modules ✗
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/doriakeung/atom/apm/node_modules/atom-package-manager/bin/node" "/Users/doriakeung/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/doriakeung/.atom/.apm/.apmrc" "--userconfig" "/Users/doriakeung/.atom/.apmrc" "install" "--runtime=electron" "--target=1.3.13" "--arch=x64"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 151.101.40.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doriakeung/atom/npm-debug.log
child_process.js:506
    throw err;
    ^

Error: Command failed: /Users/doriakeung/atom/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:483:13)
    at Object.execFileSync (child_process.js:503:13)
    at module.exports (/Users/doriakeung/atom/script/lib/install-atom-dependencies.js:15:16)
    at Object.<anonymous> (/Users/doriakeung/atom/script/bootstrap:28:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
```

**Comment by 50Wliu** [comment]
No, apm bundles its own version of node and npm.

**Comment by doriable** [comment]
I finally solved the issue, it was related to a firewall on my router, solution found here: https://github.com/npm/npm/issues/8293

Thanks for all the comments and support! :)

**Comment by acondiff** [comment]
Having the same issue. No proxy or firewall that I am aware of.

**Comment by acondiff** [comment]
Nevermind, my Mac firewall was on in System Preferences > Security & Privacy > Firewall.
