### ISSUE TITLE
Selecting Atom -> License produces error

### ISSUE THREAD

**Issue by mikeerickson** [atom/atom#13701]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Select Atom -> License causes an immediate timeout (see screenshot)

### Steps to Reproduce

1. Select Atom -> License
2. Dismiss Notification
3. See error message 

**Expected behavior:** [What you expect to happen]

It should display (or open LICENSE file)

**Actual behavior:** [What actually happens]

Produces an immediate timeout warning followed by error notification

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

1.13.1

![image](https://cloud.githubusercontent.com/assets/183153/22339021/97b2fa6a-e39d-11e6-813a-c7c64b777120.png)

Clicking Abort displays

![image](https://cloud.githubusercontent.com/assets/183153/22339091/bc2dc15e-e39d-11e6-811d-612d2e7916d5.png)

**Comment by damieng** [comment]
No repro on Windows/master.  Might be macOS or 1.13.1 specific.

**Comment by 50Wliu** [comment]
I was also unable to reproduce on Windows.  The warning dialog in question does not appear, and the warning message also doesn't appear anywhere in the codebase.

**Comment by lee-dohm** [comment]
I was also unable to reproduce on Atom v1.13.1 on Mac OS X 10.12.3. Please include the full output of `atom --version` in your reply.

**Comment by mikeerickson** [comment]
Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by mikeerickson** [comment]
@lee-dohm As an aside, I have tried with Atom Beta (version 1.14.0-beta3) and it produced the same error

![image](https://cloud.githubusercontent.com/assets/183153/22382523/e0096be0-e47a-11e6-9884-a69f85dab7cc.png)

**Comment by mikeerickson** [comment]
@lee-dohm error => warning :-)

**Comment by lee-dohm** [comment]
I was also unable to reproduce this using Atom v1.14.0-beta3 on Mac OS X 10.12.3. There seems to be something wrong with your installations. Any information you can give us on how you installed Atom or things that might be specific to your environment could help.

**Comment by damieng** [comment]
So what is displaying this error message?  As mentioned earlier in the
thread this isn't in our code.

https://github.com/search?utf8=%E2%9C%93&q=org%3Aatom+%22The+file+your+are+opening%22&type=Code&ref=searchresults

**Comment by mikeerickson** [comment]
@lee-dohm @50Wliu @damieng 

Well, I don't know what to tell you... I am surely seeing the error (based on my screenshot) and it happens within Atom (again, based on screenshot you can see the icon).

I can record a video to prove that Atom is generating the error if you wish, but seems like a wasted effort based on screenshots

**Comment by mikeerickson** [comment]
@damieng What more would you like from me to show you that it is indeed Atom producing this error?  I realize you all cant reproduce (we have all had this in our careers) but in this case, that doesn't "prove" that it is not happening.

**Comment by damieng** [comment]
@mikeerickson We're not disputing that you're getting the error.

Just wondering if that error message and subsequent crash are coming from an Atom extension.

Sorry for not making that clear.

**Comment by mikeerickson** [comment]
@damieng If I click the 'Abort' button, it produces the following error message 

![image](https://cloud.githubusercontent.com/assets/183153/22386750/560d308a-e48d-11e6-9616-fe9ff9aba030.png)

You can see at the bottom of message it says `This is likely a bug in Atom`and clicking view issue, it goes to the the following

`https://github.com/atom/atom/issues/7720`

**Comment by mikeerickson** [comment]
@damieng When I select THIS menu item (Atom -> View License) 

![image](https://cloud.githubusercontent.com/assets/183153/22386807/96d93870-e48d-11e6-9f3f-3fb00c00a230.png)

It produces the previously shown dialog

![image](https://cloud.githubusercontent.com/assets/183153/22386826/afec9726-e48d-11e6-8507-749dac75538a.png)

**Comment by mikeerickson** [comment]
@damieng And finally, trying another direction

![image](https://cloud.githubusercontent.com/assets/183153/22386893/f8652996-e48d-11e6-87cd-de60a22d468f.png)

clicking the `License` button produces the same results as described above.

**Comment by mikeerickson** [comment]
@damieng OK, I will play along... What other plugin would "interfere" with Atom -> License button?  I am stumped as you at this point.   

If you want to close this issue and stick with "doesnt happen here" then that is fine by me.  Surely not a show stopper and the only reason I produced this report was from request of @50Wliu

**Comment by mikeerickson** [comment]
@damieng so for posterity, I tried

$ atom --safe

and the error message does not display...  So, in this case, I can see where you would think it is not your error, but the fact of the matter is, it DOES happen. 

I can go through the pain of testing removing plugins until I can find culprit, but that is an exercise that could take quite some time.   

Time permitting, I may have time this weekend to give it a whirl.

In the meantime, if you have a better approach for tracking this down, I am all ears

**Comment by mikeerickson** [comment]
@damieng just an FYI 

![image](https://cloud.githubusercontent.com/assets/183153/22387143/0ecb8aa8-e48f-11e6-921d-5d15a05e4c45.png)

And

![image](https://cloud.githubusercontent.com/assets/183153/22387158/263e6dd6-e48f-11e6-9818-6a7d5999fff4.png)


Looks like it is indeed a plugin (prompt-big-file) based on second screen :-)

Removed the plugin in question and no more warning :-)

**Comment by mikeerickson** [comment]
@damieng Thank you ack!

**Comment by 50Wliu** [comment]
For future reference, this is why the first item on the prerequisites checklist is to make sure you can reproduce the problem in safe mode:
> Put an X between the brackets on this line if you have done all of the following:
Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

**Comment by damieng** [comment]
Thanks for finding the error Mike.  I agree finding out which exact plugin
causes behavior can be tricky. Any ideas on how to make tracking down such
issues easier would be welcome.

**Comment by mikeerickson** [comment]
In this case, if the plugin vendor would have identified itself when producing the dialog, that surely would have helped.  But that is a hard one to "enforce" 

Further, since the error message emitted states that "This is likely a bug in Atom" that really threw me for a loop.

Perhaps next time, I shall run Atom in debug mode and look at the associated stack trace and see if there is more information.

**Comment by mikeerickson** [comment]
@50Wliu My bad, I thought I already did that the first time I saw it (but clearly led us down the wrong path).

**Comment by damieng** [comment]
@mikeerickson Can you repro the error one more time and hit Show Stack Trace and put the contents in here?

I agree our detection code should be better and want to see if there is anything in the stack itself that we could have used to better identify the source.

**Comment by mikeerickson** [comment]
@damieng Sure thing, here you go...

```
Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (/private/var/folders/jp/x0bnmkpx4sx_k2wlb2drx0780000gn/T/AppTranslocation/76F07467-12F4-42FA-8E46-4FBAB7FC3839/d/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:77:15)
    at GutterContainer.module.exports.GutterContainer.onDidAddGutter (/private/var/folders/jp/x0bnmkpx4sx_k2wlb2drx0780000gn/T/AppTranslocation/76F07467-12F4-42FA-8E46-4FBAB7FC3839/d/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:81:27)
    at TextEditor.module.exports.TextEditor.onDidAddGutter (/private/var/folders/jp/x0bnmkpx4sx_k2wlb2drx0780000gn/T/AppTranslocation/76F07467-12F4-42FA-8E46-4FBAB7FC3839/d/Atom.app/Contents/Resources/app.asar/src/text-editor.js:789:35)
    at TextEditorPresenter.module.exports.TextEditorPresenter.observeModel (/private/var/folders/jp/x0bnmkpx4sx_k2wlb2drx0780000gn/T/AppTranslocation/76F07467-12F4-42FA-8E46-4FBAB7FC3839/d/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:225:39)
    at new TextEditorPresenter (/private/var/folders/jp/x0bnmkpx4sx_k2wlb2drx0780000gn/T/AppTranslocation/76F07467-12F4-42FA-8E46-4FBAB7FC3839/d/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:55:12)
    at new TextEditorComponent (/private/var/folders/jp/x0bnmkpx4sx_k2wlb2drx0780000gn/T/AppTranslocation/76F07467-12F4-42FA-8E46-4FBAB7FC3839/d/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:109:24)
    at atom-text-editor.TextEditorElement.mountComponent (/private/var/folders/jp/x0bnmkpx4sx_k2wlb2drx0780000gn/T/AppTranslocation/76F07467-12F4-42FA-8E46-4FBAB7FC3839/d/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:198:24)
    at atom-text-editor.TextEditorElement.attachedCallback (/private/var/folders/jp/x0bnmkpx4sx_k2wlb2drx0780000gn/T/AppTranslocation/76F07467-12F4-42FA-8E46-4FBAB7FC3839/d/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:84:14)
    at atom-pane.PaneElement.activeItemChanged (/private/var/folders/jp/x0bnmkpx4sx_k2wlb2drx0780000gn/T/AppTranslocation/76F07467-12F4-42FA-8E46-4FBAB7FC3839/d/Atom.app/Contents/Resources/app.asar/src/pane-element.js:138:24)
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/jp/x0bnmkpx4sx_k2wlb2drx0780000gn/T/AppTranslocation/76F07467-12F4-42FA-8E46-4FBAB7FC3839/d/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/jp/x0bnmkpx4sx_k2wlb2drx0780000gn/T/AppTranslocation/76F07467-12F4-42FA-8E46-4FBAB7FC3839/d/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/private/var/folders/jp/x0bnmkpx4sx_k2wlb2drx0780000gn/T/AppTranslocation/76F07467-12F4-42FA-8E46-4FBAB7FC3839/d/Atom.app/Contents/Resources/app.asar/src/pane.js:288:22)
    at Pane.module.exports.Pane.activateItem (/private/var/folders/jp/x0bnmkpx4sx_k2wlb2drx0780000gn/T/AppTranslocation/76F07467-12F4-42FA-8E46-4FBAB7FC3839/d/Atom.app/Contents/Resources/app.asar/src/pane.js:437:21)
    at /private/var/folders/jp/x0bnmkpx4sx_k2wlb2drx0780000gn/T/AppTranslocation/76F07467-12F4-42FA-8E46-4FBAB7FC3839/d/Atom.app/Contents/Resources/app.asar/src/workspace.js:545:18
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

I am going to open an issue with the author of this as I believe their threshold is too low since Atom supports opening of files @ 2g (the LICENSE.md file is 652030 bytes - kind of big :-)

```
-rw-r--r--@  1 mikee  staff    652030 Jan 24 04:54 LICENSE.md
```

**Comment by mikeerickson** [comment]
@damieng The following issue has been created as backup to this issue

https://github.com/ajuste/atom-prompt-big-file/issues/5

**Comment by damieng** [comment]
The stack trace is interesting - there is no sign of atom-prompt-big-file in there at all.

Normally when a package calls through to something incorrectly it will appear in the stack but there are unfortunately a whole bunch of scenarios like this one where there isn't a trace so we wouldn't be able to detect it.

Unfortunate side-effect of being such a hackable editor!

**Comment by mikeerickson** [comment]
@damieng Well, that is a sign of making it hard to track down :-)
