### ISSUE TITLE
Setting invisibles property "space" causes Atom error

### ISSUE THREAD

**Issue by adrian5** [atom/atom#13727]
Atom appears to not like the following setting in `config.cson`:
```
invisibles:
  space: false
```
The [other three](https://github.com/atom/atom/blob/master/src/config-schema.js#L456-L480) properties give me no problem.

The error might be a duplicate of #12294.

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Ubuntu 16.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.invisibles.space.repeat is not a function

```
At /opt/atom/resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1331

TypeError: this.invisibles.space.repeat is not a function
    at DisplayLayer.module.exports.DisplayLayer.buildTokenText (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1331:38)
    at DisplayLayer.module.exports.DisplayLayer.getScreenLines (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1224:37)
    at TextEditorPresenter.<anonymous> (/opt/atom/resources/app.asar/src/text-editor-presenter.js:1356:36)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLines (/opt/atom/resources/app.asar/src/text-editor-presenter.js:1363:12)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/opt/atom/resources/app.asar/src/text-editor-presenter.js:123:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/opt/atom/resources/app.asar/src/text-editor-component.js:264:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/opt/atom/resources/app.asar/src/text-editor-component.js:196:12)
    at /opt/atom/resources/app.asar/src/text-editor-component.js:323:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/opt/atom/resources/app.asar/src/view-registry.js:219:9)
    at /opt/atom/resources/app.asar/src/view-registry.js:3:59
```

**Comment by AndreaGriffiths11** [comment]
Thanks for reaching out!

Hand editing the `config.cson` allows you to put in whatever you want, including things that can break Atom. Because we offer the settings view package to guard against this, we don't do any stringent type checking on the configurations contents. If you want spaces to not display even when you enable "show invisibles", you can use the space character as the value for the space invisible.

**Comment by adrian5** [comment]
Understood, thanks for responding!
