### ISSUE TITLE
Uncaught Error: EMFILE: too many open files, scandir '$ATOM_HOME/.learn-ide/home/alexismmroman21-...

### ISSUE THREAD

**Issue by aroman2100** [atom/atom#13856]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 2.4.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EMFILE: too many open files, scandir '/Users/alexisroman/.atom/.learn-ide/home/alexismmroman21-9074/code'

```
At fs.js:951

Error: EMFILE: too many open files, scandir '/Users/alexisroman/.atom/.learn-ide/home/alexismmroman21-9074/code'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at traverse (/app.asar/node_modules/nsync-fs/node_modules/fs-plus/lib/fs-plus.js:404:19)
    at Object.traverseTreeSync (/app.asar/node_modules/nsync-fs/node_modules/fs-plus/lib/fs-plus.js:424:14)
    at Object.listTreeSync (/app.asar/node_modules/nsync-fs/node_modules/fs-plus/lib/fs-plus.js:235:14)
    at sync (/app.asar/node_modules/nsync-fs/lib/onmessage-strategies/sync.js:22:29)
    at onmessage (/app.asar/node_modules/nsync-fs/lib/onmessage.js:47:12)
    at /app.asar/node_modules/nsync-fs/lib/connection.js:24:16)
    at emitOne (events.js:96:13)
    at PageBus.emit (events.js:188:7)
    at /app.asar/node_modules/page-bus/index.js:21:44
```

### Commands

```
  7x -0:21.4.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
```

### Non-Core Packages

```
integrated-learn-environment 1.9.0 
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [learn-ide](https://atom.io/packages/learn-ide), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
