### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of null

### ISSUE THREAD

**Issue by myerandme** [atom/atom#13892]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'match' of null

```
At C:\Users\liuwenlong\AppData\Local\atom\app-1.14.4\resources\app.asar\src\reopen-project-menu-manager.js:181

TypeError: Cannot read property 'match' of null
    at betterBaseName (/app.asar/src/reopen-project-menu-manager.js:181:28)
    at Array.map (native)
    at Function.createLabel (/app.asar/src/reopen-project-menu-manager.js:175:76)
    at /app.asar/src/reopen-project-menu-manager.js:164:29
    at Array.map (native)
    at Function.createProjectsMenu (/app.asar/src/reopen-project-menu-manager.js:162:29)
    at ReopenProjectMenuManager.update (/app.asar/src/reopen-project-menu-manager.js:77:46)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at HistoryManager.didChangeProjects (/app.asar/src/history-manager.js:77:20)
    at HistoryManager.addProject (/app.asar/src/history-manager.js:95:12)
    at /app.asar/src/history-manager.js:36:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Project.module.exports.Project.addPath (/app.asar/src/project.js:277:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/app.asar/src/atom-environment.js:1180:26)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:237:18)
    at emitThree (events.js:121:20)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:59.6.0 application:open-folder (atom-pane.pane.active)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (`atom --safe`)?

**Comment by rsese** [comment]
Thank you for your issue!

We haven't received a response to our questions in our comment https://github.com/atom/atom/issues/13892#issuecomment-284065723. With only the information that's currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
