### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/private/var/folders/vw/_9zfhmgj7w7_qrv...

### ISSUE THREAD

**Issue by ahmadmayahi** [atom/atom#13904]
When trying to open the **Preferences** on Mac.

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/private/var/folders/vw/_9zfhmgj7w7_qrvc_p62z_9m0000gn/T/AppTranslocation/88E732E9-8D80-4E54-BD3A-E5710D7E6DAF/d/Atom.app'

```
At fs.js:982

Error: ENOENT: no such file or directory, lstat '/private/var/folders/vw/_9zfhmgj7w7_qrvc_p62z_9m0000gn/T/AppTranslocation/88E732E9-8D80-4E54-BD3A-E5710D7E6DAF/d/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at realpathSync (fs.js:1657:19)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:326:24)
    at Function.Module._findPath (module.js:167:25)
    at Module._resolveFilename (module.js:453:25)
    at Module._resolveFilename (/private/var/folders/vw/_9zfhmgj7w7_qrvc_p62z_9m0000gn/T/AppTranslocation/88E732E9-8D80-4E54-BD3A-E5710D7E6DAF/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
```

### Commands

```
     -0:22.9.0 application:add-project-folder (input.hidden-input)
  4x -0:10.2.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-autocomplete-php 0.21.0 
linter 1.11.18 
linter-phpmd 1.5.2 
php-composer-completion 0.3.4 
php-cs-fixer 4.1.0 
```

**Comment by rsese** [comment]
To confirm, is the error reproducible?  If so, is it reproducible in safe mode (`atom --safe`) as well?

**Comment by rsese** [comment]
Thank you for your issue!

We haven't received a response to our questions in our comment https://github.com/atom/atom/issues/13904#issuecomment-283420334. With only the information that's currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
