### ISSUE TITLE
Uncaught Error: Can't save destroyed buffer

### ISSUE THREAD

**Issue by BKagadey** [atom/atom#13911]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Can't save destroyed buffer

```
At C:\Users\User\AppData\Local\atom\app-1.14.4\resources\app.asar\src\pane.js:1045

Error: Can't save destroyed buffer
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1055:15)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1049:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:893:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:05.5.0 core:backspace (input.hidden-input)
     -0:44 core:move-left (input.hidden-input)
  2x -0:43.3.0 core:undo (input.hidden-input)
  2x -0:41.6.0 core:move-left (input.hidden-input)
     -0:41.2.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:40.9.0 core:move-up (input.hidden-input)
     -0:40.4.0 core:move-down (input.hidden-input)
     -0:38.3.0 autocomplete-plus:confirm (input.hidden-input)
     -0:38.3.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:34.8.0 core:backspace (input.hidden-input)
     -0:30.9.0 core:move-right (input.hidden-input)
     -0:30.7.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:30.7.0 editor:newline (input.hidden-input)
     -0:28 core:backspace (input.hidden-input)
     -0:27.5.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
  2x -0:21.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
atom-monokai 0.10.9 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-modules 1.6.7 
batman-syntax 1.1.0 
color-picker 2.2.5 
css-clean 2.19.0 
css-snippets 1.1.0 
emmet 2.4.3 
file-icons 2.0.16 
highlight-selected 0.12.0 
javascript-snippets 1.2.1 
jshint 1.8.6 
language-javascript-jsx 0.3.7 
linter 1.11.23 
linter-jshint 3.0.2 
material-syntax 0.6.1 
pigments 0.39.0 
ramda-syntax 0.12.0 
seti-ui 1.6.1 
turbo-javascript 1.4.0 
```

**Comment by 50Wliu** [comment]
Hi @BKagadey, what were you doing when this error occurred?

**Comment by BKagadey** [comment]
Hi. I try to save my code in index.html and take this error. After i
restart Atom. In editor was old version of this code.
Thank you.

P.S. It was very easy code. Cople line.
Before incedent i codinfg in brackets code editor. Maby was some conflict.

2017-03-01 23:47 GMT+02:00 Wliu <notifications@github.com>:

**Comment by ungb** [comment]
@BKagadey Are you still able to repro the issue?  If so, does it repro in when starting your project `atom --safe .` (in safe mode)?

**Comment by nieroda** [comment]
@ungb  Just got this error also. However it only has ever occured to me when I open a folder that is hosted on a server, not on my local machine

/private/var/folders/t5/b5fv_2q5379fr48mcgx5q40c0000gn/T/AppTranslocation/10DF64C2-EC8F-46EF-A06D-8A73DC24EED8/d/Atom.app/Contents/Resources/app.asar/src/pane.js:1045
Hide Stack Trace
Error: Can't save destroyed buffer
    at TextBuffer.module.exports.TextBuffer.saveAs (/private/var/folders/t5/b5fv_2q5379fr48mcgx5q40c0000gn/T/AppTranslocation/10DF64C2-EC8F-46EF-A06D-8A73DC24EED8/d/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1064:15)
    at TextBuffer.module.exports.TextBuffer.save (/private/var/folders/t5/b5fv_2q5379fr48mcgx5q40c0000gn/T/AppTranslocation/10DF64C2-EC8F-46EF-A06D-8A73DC24EED8/d/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1058:19)
    at TextEditor.module.exports.TextEditor.save (/private/var/folders/t5/b5fv_2q5379fr48mcgx5q40c0000gn/T/AppTranslocation/10DF64C2-EC8F-46EF-A06D-8A73DC24EED8/d/Atom.app/Contents/Resources/app.asar/src/text-editor.js:920:26)
    at Pane.module.exports.Pane.saveItem (/private/var/folders/t5/b5fv_2q5379fr48mcgx5q40c0000gn/T/AppTranslocation/10DF64C2-EC8F-46EF-A06D-8A73DC24EED8/d/Atom.app/Contents/Resources/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/private/var/folders/t5/b5fv_2q5379fr48mcgx5q40c0000gn/T/AppTranslocation/10DF64C2-EC8F-46EF-A06D-8A73DC24EED8/d/Atom.app/Contents/Resources/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/private/var/folders/t5/b5fv_2q5379fr48mcgx5q40c0000gn/T/AppTranslocation/10DF64C2-EC8F-46EF-A06D-8A73DC24EED8/d/Atom.app/Contents/Resources/app.asar/src/pane.js:736:19)
    at Workspace.saveActivePaneItem (/private/var/folders/t5/b5fv_2q5379fr48mcgx5q40c0000gn/T/AppTranslocation/10DF64C2-EC8F-46EF-A06D-8A73DC24EED8/d/Atom.app/Contents/Resources/app.asar/src/workspace.js:851:33)
    at atom-workspace.core:save (/private/var/folders/t5/b5fv_2q5379fr48mcgx5q40c0000gn/T/AppTranslocation/10DF64C2-EC8F-46EF-A06D-8A73DC24EED8/d/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/private/var/folders/t5/b5fv_2q5379fr48mcgx5q40c0000gn/T/AppTranslocation/10DF64C2-EC8F-46EF-A06D-8A73DC24EED8/d/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /private/var/folders/t5/b5fv_2q5379fr48mcgx5q40c0000gn/T/AppTranslocation/10DF64C2-EC8F-46EF-A06D-8A73DC24EED8/d/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/private/var/folders/t5/b5fv_2q5379fr48mcgx5q40c0000gn/T/AppTranslocation/10DF64C2-EC8F-46EF-A06D-8A73DC24EED8/d/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/t5/b5fv_2q5379fr48mcgx5q40c0000gn/T/AppTranslocation/10DF64C2-EC8F-46EF-A06D-8A73DC24EED8/d/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/t5/b5fv_2q5379fr48mcgx5q40c0000gn/T/AppTranslocation/10DF64C2-EC8F-46EF-A06D-8A73DC24EED8/d/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/private/var/folders/t5/b5fv_2q5379fr48mcgx5q40c0000gn/T/AppTranslocation/10DF64C2-EC8F-46EF-A06D-8A73DC24EED8/d/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
