### ISSUE TITLE
Uncaught Error: Unknown system error -69: Unknown system error -69, write

### ISSUE THREAD

**Issue by mimimomoc** [atom/atom#13923]
[Enter steps to reproduce:]

1. tried to save a CSS file
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Unknown system error -69: Unknown system error -69, write

```
At /Users/lisa/Downloads/Atom-3.app/Contents/Resources/app.asar/src/pane.js:1045

Error: Unknown system error -69: Unknown system error -69, write
    at Error (native)
    at Object.fs.writeSync (fs.js:786:20)
    at Object.fs.writeFileSync (fs.js:1353:24)
    at Object.writeFileSync (/app.asar/node_modules/fs-plus/lib/fs-plus.js:281:17)
    at File.module.exports.File.writeFileSync (/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:285:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:463:21)
    at File.module.exports.File.writeSync (/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:380:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1068:19)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1049:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:893:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:07.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Stack trace looks identical to https://github.com/atom/atom/issues/13906.

To confirm, is the error reproducible and do you see the error in safe mode (`atom --safe`)?

**Comment by mimimomoc** [comment]
@rsese yes it is reproducible, and I never tried safe mode to check for the error, but I will

**Comment by rsese** [comment]
> I never tried safe mode to check for the error, but I will

Thanks, let us know how it goes :v:

Can you also confirm if there's anything interesting about the file itself?  Is it just a local file on your computer?

**Comment by mimimomoc** [comment]
@rsese It's a file on a file server. I think my problem might be with the connection, but i'm not entirely sure.

**Comment by rsese** [comment]
Just for completeness, were you able to try it out in safe mode?

Also, is it just that particular file that generates the error or do you get the error trying to save any file on your file server?

**Comment by mimimomoc** [comment]
@rsese agh, I forgot. Actually, I'm not entirely sure how to set atom into safe mode (I don't use it that much). How do you do it? To answer your second question, I've mainly been making HTML and CSS files recently so those are the only ones I know about for sure, but it's generally any file and at random times.

**Comment by Ben3eeE** [comment]
> I'm not entirely sure how to set atom into safe mode (I don't use it that much). How do you do it?

Launch Atom using `atom --safe`. You can read about safe mode in the [Atom Flight Manual](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)
