### ISSUE TITLE
Did anyone meet this compile error on OSX

### ISSUE THREAD

**Issue by JetQin** [atom/atom#13930]
Hi,
I compile atom from source. but it thows some expection.

```
Node:	v6.10.0
Npm:	v3.10.5
Installing script dependencies
Installing apm
output configpath:/Users/jet/code/atom/apm/node_modules/atom-package-manager/bin/apm
/Users/jet/code/atom/apm/node_modules/atom-package-manager/bin/apm: line 37: /Users/jet/code/atom/apm/node_modules/atom-package-manager/bin/node: No such file or directory
child_process.js:506
    throw err;
    ^

Error: Command failed: /Users/jet/code/atom/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:483:13)
    at Object.execFileSync (child_process.js:503:13)
    at module.exports (/Users/jet/code/atom/script/lib/install-atom-dependencies.js:16:16)
    at Object.<anonymous> (/Users/jet/code/atom/script/bootstrap:28:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```
Does anyone know how to fix it?

**Comment by rsese** [comment]
Do you get the same error if you run `script/clean` and then run `script/build` again?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/13930#issuecomment-285254690. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by icetee** [comment]
Same here. But fixed `script/clean`, thanks!
I use versions:
```
MacOS:  v10.13.1
Node:	v9.2.0
Npm:	v5.5.1
```
