### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=write ECONNRESET

### ISSUE THREAD

**Issue by Andrew-Webb** [atom/atom#14001]
[Enter steps to reproduce:]

1. ... Open settings
2. ... Click on "Packages"

(I wouldn't call these "steps to reproduce" since it only happened once and I can't get it to happen again)

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=write ECONNRESET

```
At stream.js:74

Error: tunneling socket could not be established, cause=write ECONNRESET
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:319:10)
    at onwrite (_stream_writable.js:337:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:463:13)
    at Socket._destroy (net.js:504:3)
    at Socket._writeGeneric (net.js:706:17)
    at Socket.<anonymous> (net.js:663:12)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1068:10)
```

### Commands

```
```

### Non-Core Packages

```
ide-purescript 0.15.3 
language-purescript 0.8.2 
linter 1.11.23 
```

**Comment by rsese** [comment]
Thanks for the report!

> (I wouldn't call these "steps to reproduce" since it only happened once and I can't get it to happen again)

Since it's not reproducible, I wonder if this was just a temporary network issue?  I'll go ahead and close for now but if it ends up being a repeatable error for you, please let us know.
