### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.172.254.23:...

### ISSUE THREAD

**Issue by akshaybabloo** [atom/atom#14019]
I got this error out of the blue

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.172.254.23:3128

```
At stream.js:74

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.172.254.23:3128
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -1:18.9.0 markdown-toc:toggle (input.hidden-input)
  2x -0:57.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
flatten-json 0.1.5 
language-batch 0.4.0 
markdown-toc 0.4.2 
pretty-json 1.6.1 
```

**Comment by rsese** [comment]
Thanks for the report! Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you also see the error in safe mode (atom --safe)?

**Comment by akshaybabloo** [comment]
* I opened `settings -> install` to install a package, though I haven't installed any package, just out of the blue I got that error.
* I don't think so, I am not getting it now.

**Comment by rsese** [comment]
Thanks for details - since it's not reproducible, let's close for now.  If you're able to reproduce in the future though, please let us know.
