### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset -2 is larger than or e...

### ISSUE THREAD

**Issue by claudioarchi** [atom/atom#14013]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: Atom Core

### Stack Trace

Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset -2 is larger than or equal to the node's length (1).

```
At C:\Users\claudio\AppData\Local\atom\app-1.15.0\resources\app.asar\src\lines-yardstick.js:162

Error: Failed to execute 'setEnd' on 'Range': The offset -2 is larger than or equal to the node's length (1).
    at Error (native)
    at LinesYardstick.module.exports.LinesYardstick.clientRectForRange (/app.asar/src/lines-yardstick.js:162:32)
    at LinesYardstick.module.exports.LinesYardstick.leftPixelPositionForScreenPosition (/app.asar/src/lines-yardstick.js:142:40)
    at LinesYardstick.module.exports.LinesYardstick.pixelPositionForScreenPosition (/app.asar/src/lines-yardstick.js:107:19)
    at TextEditorPresenter.module.exports.TextEditorPresenter.pixelPositionForScreenPosition (/app.asar/src/text-editor-presenter.js:1301:38)
    at TextEditorPresenter.module.exports.TextEditorPresenter.buildHighlightRegions (/app.asar/src/text-editor-presenter.js:1639:33)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateHighlightState (/app.asar/src/text-editor-presenter.js:1599:39)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateHighlightDecorations (/app.asar/src/text-editor-presenter.js:1492:16)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPostMeasurementState (/app.asar/src/text-editor-presenter.js:151:14)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/app.asar/src/text-editor-component.js:202:38)
    at /app.asar/src/text-editor-component.js:323:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/app.asar/src/view-registry.js:219:9)
    at /app.asar/src/view-registry.js:3:59
```

### Commands

```
     -2:12.3.0 autocomplete-plus:confirm (input.hidden-input)
     -2:11.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -2:10.3.0 core:move-right (input.hidden-input)
     -2:09.9.0 editor:newline (input.hidden-input)
     -2:00.6.0 autocomplete-plus:confirm (input.hidden-input)
     -1:59.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:56.2.0 script:run (input.hidden-input)
     -1:39.8.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:35.6.0 autocomplete-plus:confirm (input.hidden-input)
     -1:32.5.0 intentions:highlight (input.hidden-input)
     -1:32.2.0 script:run (input.hidden-input)
     -0:34.6.0 intentions:highlight (input.hidden-input)
     -0:34.3.0 script:run (input.hidden-input)
     -0:20.5.0 core:move-right (input.hidden-input)
  2x -0:18.7.0 editor:newline (input.hidden-input)
  4x -0:16.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
autocomplete-python 1.8.60 
busy-signal 1.3.0 
file-icons 2.0.17 
highlight-selected 0.12.0 
intentions 1.1.2 
linter 2.1.0 
linter-flake8 2.1.4 
linter-ui-default 1.1.0 
platformio-ide-terminal 2.5.0 
python-autopep8 0.1.3 
python-tools 0.6.9 
script 3.14.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our questions in this comment https://github.com/atom/atom/issues/14013#issuecomment-286952462. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
