### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 0)

### ISSUE THREAD

**Issue by TheSeventhLion** [atom/atom#14034]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 0)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at DisplayLayer.translateScreenPosition (/app.asar/node_modules/text-buffer/lib/display-layer.js:326:11)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateScreenPosition (/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:163:32)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (/app.asar/node_modules/text-buffer/lib/display-marker.js:154:52)
    at /app.asar/src/cursor.js:72:31
    at Cursor.module.exports.Cursor.changePosition (/app.asar/src/cursor.js:684:7)
    at Cursor.module.exports.Cursor.setScreenPosition (/app.asar/src/cursor.js:70:19)
    at /app.asar/src/text-editor.js:1897:23
    at TextEditor.module.exports.TextEditor.moveCursors (/app.asar/src/text-editor.js:2120:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/app.asar/src/text-editor.js:1896:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/app.asar/src/text-editor-component.js:721:25)
    at /app.asar/src/text-editor-component.js:3:59)
```

### Commands

```
```

### Non-Core Packages

```
angularjs 0.4.0 
angularjs-boilerplate-snippets 0.3.1 
atom-beautify 0.29.17 
atom-bracket-highlight 0.3.2 
atom-brackets-glow 0.4.0 
atom-clock 0.1.6 
atom-html-templates 0.1.3 
atom-icons 0.2.2 
atom-live-server 2.1.2 
atom-monokai 0.10.9 
atomify 0.2.0 
aurora-theme 1.2.2 
auto-semicolon 1.1.0 
autoclose-html 0.23.0 
autocomplete-angular-material 0.4.0 
autocomplete-js-import 1.4.0 
autocomplete-json 5.3.0 
autohide-tree-view 0.25.1 
bracket-padder 0.4.1 
chrome-color-picker 0.8.0 
color-picker 2.2.5 
color-picker-service 0.0.1 
color-tabs 0.1.8 
comment 0.5.0 
duotone-dark-syntax 2.1.0 
emmet 2.4.3 
filecolor 0.4.0 
grammar-tab-colors 0.2.8 
highlight-selected 0.12.0 
minimap 4.26.8 
minimap-pigments 0.2.2 
monokai 0.22.0 
neon-color-scheme 1.0.0 
neon-syntax 0.3.7 
pigments 0.39.0 
platformio-ide-terminal 2.3.1 
platformio-ide-terminal 2.3.1 
robin-hood-syntax 1.0.0 
seti-icons 1.4.3 
swackets 0.26.0 
tron-theme 0.3.2 
```

**Comment by rsese** [comment]
Thanks for the report! Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you also see the error in safe mode (atom --safe)?

**Comment by jsolisu** [comment]
Maybe the same as #12081.

**Comment by rsese** [comment]
:+1: thinking the same thing , but was curious if the steps to reproduce are wildly different than what's discussed in #12081.  We'll go ahead and close as a duplicate for now so feel free to subscribe to #12081 for updates @TheSeventhLion.

But if you have steps to reproduce that don't involve pane splitting, please let us know :v:
