### ISSUE TITLE
Uncaught TypeError: Cannot read property 'has' of null

### ISSUE THREAD

**Issue by joscha** [atom/atom#14032]
0. Go to Atom package manager
1. Uninstall the platformio-ide-terminal
2. Uninstall the platformio package

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: 'platformio-ide' package vundefined

### Stack Trace

Uncaught TypeError: Cannot read property 'has' of null

```
At /Users/joscha/.atom/packages/platformio-ide/lib/init/command.js:185

TypeError: Cannot read property 'has' of null
    at intendToPerformIndexRebuild (/packages/platformio-ide/lib/init/command.js:185:26)
    at /packages/platformio-ide/lib/init/command.js:209:13
```

### Commands

```
  3x -4:37 core:move-down (input.hidden-input)
  3x -4:34 core:move-up (input.hidden-input)
     -4:33.1.0 core:move-left (input.hidden-input)
     -4:31.5.0 core:backspace (input.hidden-input)
     -4:31.1.0 core:move-up (input.hidden-input)
     -4:30.9.0 core:move-right (input.hidden-input)
     -4:30.6.0 core:backspace (input.hidden-input)
  2x -4:30 core:move-down (input.hidden-input)
     -4:27.7.0 core:save (input.hidden-input)
     -4:27.6.0 build:refresh-targets (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:14.5.0 platformio-ide:target:upload (input.hidden-input)
     -4:14.5.0 platformio-ide:target:upload-/Users/joscha/Development/wala/wala-sodaqone_3 (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:31.5.0 platformio-ide:target:clean (div.build.tool-panel.native-key-bindings)
     -3:31.5.0 platformio-ide:target:clean-/Users/joscha/Development/wala/wala-sodaqone_3 (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:24.3.0 platformio-ide:target:upload (input.hidden-input)
     -3:24.3.0 platformio-ide:target:upload-/Users/joscha/Development/wala/wala-sodaqone_3 (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-jasmine 0.8.1 
autocomplete-clang 0.10.0 
autocomplete-paths 1.0.5 
build 0.67.0 
busy 0.7.0 
busy-signal 1.3.0 
editorconfig 2.2.2 
file-icons 2.0.17 
intentions 1.1.2 
jsformat 0.9.3 
language-arduino 0.4.2 
language-docker 1.1.7 
language-gherkin 1.0.4 
language-ini 1.19.0 
language-lua 0.9.11 
language-protobuf 0.7.1 
language-scala 1.1.8 
linter 2.1.0 
linter-coffeelint 1.2.1 
linter-docker 0.1.4 
linter-eslint 8.1.4 
linter-gcc 0.7.1 
linter-javac 1.9.4 
linter-jsonlint 1.3.0 
linter-jsxhint 0.1.2 
linter-php 1.3.2 
linter-ui-default 1.2.1 
merge-conflicts 1.4.4 
minimap 4.26.8 
react 0.16.2 
tool-bar 1.1.0 
travis-ci-status 1.3.1 
visual-bell 1.0.0 
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [platformio-ide](https://atom.io/packages/platformio-ide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
