### ISSUE TITLE
Uncaught TypeError: Cannot read property 'alias' of undefined

### ISSUE THREAD

**Issue by SilvaCesar** [atom/atom#14052]
The error occurs when I am registering a new host in plugin remote-edit2

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Windows 10
**Thrown From**: [remote-edit2](https://github.com/duxet/remote-edit2) package 3.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'alias' of undefined

```
At C:\Users\cesar\.atom\packages\remote-edit2\lib\model\host.coffee:34

TypeError: Cannot read property 'alias' of undefined
    at FtpHost.module.exports.Host.getSearchKey (/packages/remote-edit/lib/model/host.coffee:34:63)
    at /packages/remote-edit/lib/model/host.coffee:18:9
    at Config.module.exports.Config.observeKeyPath (/app.asar/src/config.js:616:7)
    at Config.module.exports.Config.observe (/app.asar/src/config.js:141:21)
    at FtpHost.Host (/packages/remote-edit/lib/model/host.coffee:17:19)
    at /packages/remote-edit2/lib/model/ftp-host.coffee:32:7)
    at Object.newHostFtp (/packages/remote-edit2/lib/main.coffee:116:16)
    at /packages/remote-edit2/lib/main.coffee:95:73)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at Object.didConfirmSelection (/app.asar/node_modules/command-palette/lib/command-palette-view.js:106:29)
    at SelectListView.confirmSelection (/app.asar/node_modules/atom-select-list/src/select-list-view.js:301:20)
    at HTMLDivElement.coreConfirm (/app.asar/node_modules/atom-select-list/src/select-list-view.js:67:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:20.6.0 command-palette:toggle (div.package-detail.panels-item)
  2x -0:15.7.0 core:backspace (input.hidden-input)
  2x -0:12.7.0 core:move-down (input.hidden-input)
     -0:12 core:confirm (input.hidden-input)
     -0:12 remote-edit:new-host-ftp (div.package-detail.panels-item)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
language-vue 0.21.2 
remote-edit2 3.0.0 
remote-sync 4.1.5 
```

**Comment by 50Wliu** [comment]
> Thrown From: remote-edit2 package 3.0.0

Please report this on the remote-edit2 package repository instead.  Thanks!

**Comment by SilvaCesar** [comment]
@50Wliu Oks
