### ISSUE TITLE
Emmett text entry bar will not disappear when pressing esc

### ISSUE THREAD

**Issue by clintonbeattie** [atom/atom#14051]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.1
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package 2.4.3

### Stack Trace

Uncaught Error: Setting active pane that is not present in pane container

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane-container.js:195

Error: Setting active pane that is not present in pane container
    at PaneContainer.module.exports.PaneContainer.setActivePane (/app.asar/src/pane-container.js:195:17)
    at Pane.module.exports.Pane.activate (/app.asar/src/pane.js:850:14)
    at PromptView.module.exports.PromptView.detach (/packages/emmet/lib/prompt.coffee:62:14)
    at PromptView.module.exports.PromptView.cancel (/packages/emmet/lib/prompt.coffee:57:4)
    at /packages/emmet/lib/prompt.coffee:23:61)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -5:43.4.0 core:backspace (input.hidden-input)
     -5:42.9.0 core:save (input.hidden-input)
     -0:14.9.0 editor:consolidate-selections (input.hidden-input)
     -0:14.9.0 core:cancel (input.hidden-input)
     -0:14.8.0 editor:consolidate-selections (input.hidden-input)
     -0:14.8.0 core:cancel (input.hidden-input)
     -0:13.8.0 editor:consolidate-selections (input.hidden-input)
     -0:13.8.0 core:cancel (input.hidden-input)
     -0:13.4.0 editor:consolidate-selections (input.hidden-input)
     -0:13.4.0 core:cancel (input.hidden-input)
     -0:11.9.0 editor:consolidate-selections (input.hidden-input)
     -0:11.9.0 core:cancel (input.hidden-input)
     -0:11.4.0 editor:consolidate-selections (input.hidden-input)
     -0:11.4.0 core:cancel (input.hidden-input)
     -0:07.1.0 editor:consolidate-selections (input.hidden-input)
     -0:07.1.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.12.1 
atom-beautify 0.29.17 
atom-terminal 0.8.0 
atom-ternjs 0.18.2 
docblockr 0.9.3 
emmet 2.4.3 
language-htaccess 0.1.1 
minimap 4.26.8 
open-recent 5.0.0 
project-manager 3.3.3 
project-plus 0.9.0 
save-session 0.15.7 
```

Happens in non-beta version of Atom editor too

**Comment by lee-dohm** [comment]
Thanks for contributing!

It appears that this is being caused by the [emmet package](https://atom.io/packages/emmet), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by clintonbeattie** [comment]
Thanks very much Lee
