### ISSUE TITLE
Uncaught AssertionError: 2337 == 0

### ISSUE THREAD

**Issue by ndeniche** [atom/atom#14074]
[Enter steps to reproduce:]

1. It occurs randomly while using atom. It first happened when looking for a package.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Windows 7
**Thrown From**: Atom Core

### Stack Trace

Uncaught AssertionError: 2337 == 0

```
At assert.js:85

AssertionError: 2337 == 0
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:159:14)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-minify 0.8.0 
```

**Comment by Ryan1729** [comment]
Just looking at the top line of the stack trace, it might be related to [this issue](https://github.com/request/tunnel-agent/issues/20) on the tunnel-agent package.

**Comment by rsese** [comment]
Nice find @Ryan1729 :v:  It does seem to be related if not the same issue.

**Comment by rsese** [comment]
@ndeniche - just to confirm, did this just start happening recently?  Also, I think it's what you meant but can you also confirm if you've only seen this error when searching for a package?

**Comment by rsese** [comment]
From https://github.com/atom/atom/issues/16790, also happened while doing a package search:

> Open Install packages
> Searched for "base64"
