### ISSUE TITLE
Uncaught TypeError: Cannot set property 'isDirty' of undefined

### ISSUE THREAD

**Issue by RainKolwa** [atom/atom#14085]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot set property 'isDirty' of undefined

```
At /private/var/folders/qs/95962mzd24ncfxyr8tldzwjh0000gn/T/AppTranslocation/25D98952-97D3-4908-9520-313AA21007E4/d/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:833

TypeError: Cannot set property 'isDirty' of undefined
    at disposables.push.editor.getBuffer.onDidChange.e (atom-ternjs-manager.js:262:9)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/app.asar/node_modules/text-buffer/lib/text-buffer.js:680:20)
    at TextBuffer.module.exports.TextBuffer.applyChange (/app.asar/node_modules/text-buffer/lib/text-buffer.js:664:12)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/app.asar/node_modules/text-buffer/lib/text-buffer.js:877:16)
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:831:14)
    at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1594:26)
    at /app.asar/src/text-editor.js:1155:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/app.asar/src/text-editor.js:2568:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/app.asar/src/text-editor.js:2534:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/app.asar/src/text-editor.js:1153:19)
    at TextEditor.module.exports.TextEditor.backspace (/app.asar/src/text-editor.js:1144:19)
    at /app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at /app.asar/src/register-default-commands.js:425:21)
    at /app.asar/src/register-default-commands.js:666:34
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1594:26)
    at /app.asar/src/register-default-commands.js:665:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:23 vim-mode-plus:activate-insert-mode (input.hidden-input)
  4x -0:22.5.0 core:move-left (input.hidden-input)
  5x -0:21.8.0 core:select-right (input.hidden-input)
     -0:18.9.0 core:save (input.hidden-input)
     -0:17.7.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:17.5.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
  4x -0:16.7.0 vim-mode-plus:move-left (input.hidden-input)
     -0:15.7.0 vim-mode-plus:insert-after (input.hidden-input)
     -0:15.2.0 core:move-left (input.hidden-input)
  5x -0:15 core:select-right (input.hidden-input)
  2x -0:13.9.0 core:backspace (input.hidden-input)
     -0:08.1.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
  2x -0:07.8.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:05.6.0 dblclick (div.line)
     -0:05.5.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
  3x -0:05.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.13 
atom-fuzzy-grep 0.16.0 
atom-ternjs 0.18.2 
autocomplete-css-with-stylus-support 1.0.0 
autocomplete-paths 1.0.5 
block-comment 0.4.3 
emmet 2.4.3 
file-icons 1.7.25 
flatwhite-syntax 0.6.0 
git-time-machine 1.5.3 
hyperclick 0.0.40 
js-hyperclick 1.10.1 
language-pug 0.0.21 
language-vue 0.21.2 
language-vue-component 0.5.0 
last-buffer 3.0.0 
linter 1.11.21 
linter-eslint 8.0.0 
linter-stylint 2.2.5 
linter-stylint-h 0.0.12 
markdown-preview-plus 2.4.1 
narrow 0.37.1 
open-neue 1.0.1 
pigments 0.38.0 
project-manager 3.3.3 
react 0.16.0 
react-es6-snippets 0.3.0 
recent-files-fuzzy-finder 0.3.0 
Stylus 3.1.0 
vim-mode-plus 0.84.1 
vim-mode-plus-keymaps-for-surround 0.2.1 
vue-hyperclick 0.2.0 
```

**Comment by 50Wliu** [comment]
> atom-ternjs-manager

Thanks for contributing!

It appears that this is being caused by the [atom-ternjs](https://atom.io/packages/atom-ternjs) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
