### ISSUE TITLE
Uncaught Error: Could not call remote function 'bound '. Check that the function signature is cor...

### ISSUE THREAD

**Issue by MOIS3S** [atom/atom#14094]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Could not call remote function 'bound '. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: window-event-handler.js:46:21.
Error: Could not call remote function 'bound '. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: window-event-handler.js:46:21.
    at callFunction (/opt/atom/resources/electron.asar/browser/rpc-server.js:226:11)
    at EventEmitter.<anonymous> (/opt/atom/resources/electron.asar/browser/rpc-server.js:307:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/opt/atom/resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /opt/atom/resources/electron.asar/renderer/api/remote.js:210

Error: Could not call remote function 'bound '. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: window-event-handler.js:46:21.
Error: Could not call remote function 'bound '. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: window-event-handler.js:46:21.
    at callFunction (/opt/atom/resources/electron.asar/browser/rpc-server.js:226:11)
    at EventEmitter.<anonymous> (/opt/atom/resources/electron.asar/browser/rpc-server.js:307:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/opt/atom/resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/opt/atom/resources/electron.asar/renderer/api/remote.js:210:13)
    at undefined.remoteMemberFunction (/opt/atom/resources/electron.asar/renderer/api/remote.js:111:18)
    at ApplicationDelegate.module.exports.ApplicationDelegate.showSaveDialog (/app.asar/src/application-delegate.js:218:38)
    at Pane.module.exports.Pane.saveItemAs (/app.asar/src/pane.js:778:46)
    at Pane.saveItemAs (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:765:21)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:31.5.0 intentions:highlight (input.hidden-input)
     -1:30.7.0 core:save (input.hidden-input)
     -1:28.8.0 intentions:highlight (input.hidden-input)
     -1:28.3.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -1:25.4.0 run:file (input.hidden-input)
     -0:49.9.0 intentions:highlight (input.hidden-input)
     -0:49.6.0 core:save (input.hidden-input)
     -0:25 intentions:highlight (input.hidden-input)
     -0:24.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
autocomplete-python 1.8.62 
busy-signal 1.3.0 
file-icons 2.1.1 
intentions 1.1.2 
linter 2.1.2 
linter-ui-default 1.2.1 
platformio-ide-terminal 2.5.0 
python-tools 0.6.9 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/14094#issuecomment-290485091. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
