### ISSUE TITLE
Uncaught Error: empty char-class

### ISSUE THREAD

**Issue by Mizzlr** [atom/atom#14099]
[Enter steps to reproduce:]

1. Create a file with .hjson extension (Human JSON file) and try editing it.
2. And then, Click on the small down arrow `v` to collapse/fold the json object, to single line.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: empty char-class

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/oniguruma/lib/onig-reg-exp.js:9

Error: empty char-class
    at Error (native)
    at /app.asar/node_modules/oniguruma/lib/onig-reg-exp.js:9:22)
    at LanguageMode.module.exports.LanguageMode.cacheRegex (/app.asar/src/language-mode.js:411:98)
    at LanguageMode.module.exports.LanguageMode.foldEndRegexForScopeDescriptor (/app.asar/src/language-mode.js:428:19)
    at LanguageMode.module.exports.LanguageMode.rowRangeForCodeFoldAtBufferRow (/app.asar/src/language-mode.js:210:80)
    at LanguageMode.module.exports.LanguageMode.rowRangeForFoldAtBufferRow (/app.asar/src/language-mode.js:164:25)
    at LanguageMode.module.exports.LanguageMode.foldBufferRow (/app.asar/src/language-mode.js:150:29)
    at TextEditor.module.exports.TextEditor.foldBufferRow (/app.asar/src/text-editor.js:3065:32)
    at LineNumberGutterComponent.module.exports.LineNumberGutterComponent.onClick (/app.asar/src/line-number-gutter-component.js:133:30)
    at /app.asar/src/line-number-gutter-component.js:3:59)
```

### Commands

```
     -3:39.3.0 core:copy (input.hidden-input)
     -3:38.9.0 core:move-down (input.hidden-input)
     -3:38.2.0 core:paste (input.hidden-input)
 15x -3:37.6.0 core:move-down (input.hidden-input)
  7x -3:34 core:move-up (input.hidden-input)
     -3:22.7.0 core:backspace (input.hidden-input)
     -3:19.4.0 core:copy (input.hidden-input)
     -3:15.6.0 core:backspace (input.hidden-input)
  2x -3:15.4.0 core:move-right (input.hidden-input)
     -3:14.9.0 core:backspace (input.hidden-input)
  2x -3:13.6.0 core:save (input.hidden-input)
     -2:59.9.0 core:copy (input.hidden-input)
  2x -2:40 core:backspace (input.hidden-input)
     -2:28.8.0 core:copy (input.hidden-input)
     -2:27 core:paste (input.hidden-input)
  2x -2:18.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.2.0 
ask-stack 2.2.0 
atom-beautify 0.29.13 
atom-jq 0.6.1 
atom-json-editor 0.4.1 
atom-monokai 0.10.7 
atomic-chrome 0.3.0 
autoclose-html 0.23.0 
autocomplete-elixir 1.5.14 
autocomplete-erlang 1.1.2 
autocomplete-go 1.3.0 
autocomplete-haskell 0.7.1 
autocomplete-html-entities 0.1.0 
autocomplete-python 1.8.40 
block-cursor 0.13.1 
builder-go 1.0.1 
climate-syntax 5.0.0 
cute-cursor 0.3.0 
file-types 0.5.5 
firacode 0.2.0 
firewatch-hot-syntax 1.3.0 
firewatch-syntax 1.1.1 
fonts 2.0.0 
genesis-ui 0.5.0 
git-time-machine 1.5.4 
glowing-cursor 0.1.2 
go-config 1.2.4 
go-debug 0.1.22 
go-get 2.1.1 
go-guru 0.2.0 
go-plus 4.3.2 
godoc 1.1.1 
gofmt 1.2.0 
gometalinter-linter 1.2.2 
gorename 1.1.0 
goto-definition 1.1.19 
haskell-ghc-mod 1.19.2 
haskell-grammar 0.4.0 
ide-haskell 1.9.2 
ide-haskell-cabal 1.7.4 
ide-haskell-repl 0.5.1 
language-cypher 0.3.0 
language-docker 1.1.7 
language-elixir 0.16.0 
language-erlang 3.0.0 
language-groovy 0.6.0 
language-haskell 1.12.1 
language-hjson 0.3.0 
language-matlab 0.2.1 
linter 1.11.21 
linter-docker 0.1.4 
linter-pep8 1.3.2 
linter-pycodestyle 2.0.0 
minimap 4.26.8 
multi-cursor-plus 1.0.3 
navigator-go 1.1.3 
neon-cursor 1.6.0 
p5xjs-autocomplete 0.11.0 
processing 0.13.0 
pulsing-cursor 0.3.1 
python-debugger 0.2.0 
python-indent 1.0.0 
qolor 0.4.1 
seti-ui 1.6.0 
sourcerer 2.0.0 
svg-preview 0.11.0 
tablr 1.8.1 
tabularize 0.2.5 
tester-go 2.0.2 
wakatime 6.0.12 
```

**Comment by rsese** [comment]
Sounds similar to https://github.com/atom/atom/issues/12918, but as mentioned in that issue, can you please re-open in https://github.com/hjson/atom-hjson?  It doesn't look like https://github.com/atom/atom/issues/12918 was opened there so you can create a new issue.
