### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:6660

### ISSUE THREAD

**Issue by MCSophie** [atom/atom#14115]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:6660

```
At stream.js:74

Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:6660
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -4:16.3.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-chs-menu 1.0.0 
simplified-chinese-menu 3.5.0 
```

**Comment by damieng** [comment]
Atom is detecting you have a proxy server setup on your localhost on port 6660. This is normally a setting in Windows. Does your web browser go through a proxy server?
