### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scrollPastEnd' of undefined

### ISSUE THREAD

**Issue by USI-Carbol** [atom/atom#14118]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: 'overscroll' package vundefined

### Stack Trace

Uncaught TypeError: Cannot read property 'scrollPastEnd' of undefined

```
At /Users/lodovicocarbone/.atom/packages/overscroll/lib/overscroll.coffee:15

TypeError: Cannot read property 'scrollPastEnd' of undefined
    at TextEditor.editor.displayBuffer.getScrollHeight (/packages/overscroll/lib/overscroll.coffee:15:40)
    at /packages/scroll-percentage/lib/scroll-percentage.coffee:26:33
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/text-editor-element.js:105:46
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateScrollTop (/app.asar/src/text-editor-presenter.js:932:29)
    at TextEditorPresenter.module.exports.TextEditorPresenter.restoreScrollTopIfNeeded (/app.asar/src/text-editor-presenter.js:1977:21)
    at TextEditorPresenter.module.exports.TextEditorPresenter.setLineHeight (/app.asar/src/text-editor-presenter.js:1263:14)
    at LinesComponent.module.exports.LinesComponent.measureLineHeightAndDefaultCharWidth (/app.asar/src/lines-component.js:132:22)
    at TextEditorComponent.module.exports.TextEditorComponent.measureLineHeightAndDefaultCharWidth (/app.asar/src/text-editor-component.js:1070:36)
    at TextEditorComponent.module.exports.TextEditorComponent.sampleFontStyling (/app.asar/src/text-editor-component.js:1051:14)
    at TextEditorComponent.sampleFontStyling (/app.asar/src/text-editor-component.js:3:59)
    at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/app.asar/src/text-editor-component.js:292:12)
    at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/app.asar/src/text-editor-component.js:994:16)
    at /app.asar/src/text-editor-element.js:87:22)
    at /app.asar/src/pane-container-element.js:42:14)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.setRoot (/app.asar/src/pane-container.js:163:20)
    at PaneContainer.module.exports.PaneContainer.replaceChild (/app.asar/src/pane-container.js:173:19)
    at Pane.module.exports.Pane.split (/app.asar/src/pane.js:919:21)
    at Pane.module.exports.Pane.splitRight (/app.asar/src/pane.js:899:19)
    at Pane.module.exports.Pane.findOrCreateRightmostSibling (/app.asar/src/pane.js:971:21)
    at /app.asar/src/workspace.js:426:43)
    at Workspace.module.exports.Workspace.open (/app.asar/src/workspace.js:434:12)
    at WelcomePackage.show (/app.asar/node_modules/welcome/lib/welcome-package.js:79:95)
    at /app.asar/node_modules/welcome/lib/welcome-package.js:72:20)
    at next (<anonymous>)
```

### Commands

```
```

### Non-Core Packages

```
pigments 0.39.1 
python-indent 1.0.2 
scroll-percentage 1.2.1 
```

**Comment by 50Wliu** [comment]
Looks like your overscroll package has been corrupted.  Try uninstalling and reinstalling it.
