### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stdout' of null

### ISSUE THREAD

**Issue by usemodj** [atom/atom#14149]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: elementary OS
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'stdout' of null

```
At events.js:160

TypeError: Cannot read property 'stdout' of null
  at Object.user.git.name (/usr/local/lib/node_modules/generator-angular2-webpack-class/node_modules/yeoman-generator/lib/actions/user.js:30:70)
  at constructor.prompting (/usr/local/lib/node_modules/generator-angular2-webpack-class/app/index.js:94:32)
  at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular2-webpack-class/node_modules/yeoman-generator/lib/base.js:439:23)
  at /usr/local/lib/node_modules/generator-angular2-webpack-class/node_modules/run-async/index.js:25:25
  at /usr/local/lib/node_modules/generator-angular2-webpack-class/node_modules/run-async/index.js:24:19
  at /usr/local/lib/node_modules/generator-angular2-webpack-class/node_modules/yeoman-generator/lib/base.js:440:9
  at runCallback (timers.js:574:20)
  at tryOnImmediate (timers.js:554:5)
  at processImmediate [as _immediateCallback] (timers.js:533:5)

```

### Commands

```
     -3:11.7.0 intentions:highlight (input.hidden-input)
     -3:09.8.0 yo:yeoman (input.hidden-input)
     -3:07.7.0 core:confirm (input.hidden-input)
     -1:02.2.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
  3x -1:01.7.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:28.5.0 yo:yeoman (div.nuclide-file-tree.focusable-panel.tree-view)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
advanced-open-file 0.16.6 
angular-2-typeScript-snippets 0.6.3 
angular2-webpack-class-meanstack 0.0.0 
angularjs 0.4.0 
atom-beautify 0.29.17 
atom-html-preview 0.1.22 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-terminal 0.8.0 
atom-ternjs 0.18.2 
atom-typescript 11.0.1 
atom-yeoman 0.3.15 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
bottom-dock 0.4.4 
busy-signal 1.3.0 
color-picker 2.2.5 
dalek 0.2.1 
docblockr 0.9.4 
eclipse-keybindings 0.9.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.2 
fonts 2.0.0 
git-clone 0.2.0 
git-control 0.9.0 
git-diff-details 1.4.0 
git-log 0.4.1 
git-plus 7.3.3 
git-projects 1.17.0 
git-status 0.3.4 
git-time-machine 1.5.9 
gitignore-snippets 0.2.5 
gulp-manager 0.2.19 
highlight-selected 0.13.1 
indent-guide-improved 1.4.12 
intentions 1.1.2 
javascript-snippets 1.2.1 
language-apache 1.7.0 
language-babel 2.57.2 
language-docker 1.1.7 
language-log 1.8.0 
linter 2.1.2 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-jsonlint 1.3.0 
linter-sass-lint 1.7.4 
linter-scss-lint 3.1.0 
linter-tslint 0.15.0 
linter-ui-default 1.2.2 
linter-write-good 0.9.0 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.4 
minimap 4.27.1 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
node-debugger 1.10.1 
nord-atom-syntax 0.7.0 
nord-atom-ui 0.11.0 
nuclide 0.216.0 
open-in-browser 0.5.0 
pdf-view 0.57.0 
php-twig 4.0.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
pretty-json 1.6.3 
project-manager 3.3.4 
remote-edit 1.9.0 
Remote-FTP 0.10.7 
sass-autocompile 0.13.3 
script 3.14.1 
split-diff 1.3.0 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.1 
todo-show 1.11.0 
tomorrow-night-eighties-syntax 1.0.2 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.3.1 
vim-mode-plus 0.87.0 
zentabs 0.8.8 
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [yeoman](https://atom.io/packages/atom-yeoman) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
