### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tiles' of undefined

### ISSUE THREAD

**Issue by tlystad24** [atom/atom#14158]
[Enter steps to reproduce:]

1. Launch Atom (empty projects also trigger this error)

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'tiles' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/line-numbers-tile-component.js:43

TypeError: Cannot read property 'tiles' of undefined
    at LineNumbersTileComponent.module.exports.LineNumbersTileComponent.updateSync (/app.asar/src/line-numbers-tile-component.js:43:40)
    at LineNumberGutterComponent.module.exports.TiledComponent.updateTileNodes (/app.asar/src/tiled-component.js:55:19)
    at LineNumberGutterComponent.module.exports.TiledComponent.updateSync (/app.asar/src/tiled-component.js:18:12)
    at GutterContainerComponent.module.exports.GutterContainerComponent.updateSync (/app.asar/src/gutter-container-component.js:79:25)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/app.asar/src/text-editor-component.js:235:39)
    at /app.asar/src/text-editor-component.js:323:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/app.asar/src/view-registry.js:219:9)
    at /app.asar/src/view-registry.js:3:59
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
emmet 2.4.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible and if so, is it reproducible in safe mode (`atom --safe`)?

**Comment by tlystad24** [comment]
The error occurs every time I launch Atom. It also occurs in safe mode.

**Comment by rsese** [comment]
Do you happen to remember if anything interesting/weird happened before Atom starting throwing this error?   Or did it seem to just start happening at some point recently?

**Comment by tlystad24** [comment]
It started happening at some point. It has been a couple of weeks since the issue last occured, so it is no longer an issue on my end.

**Comment by rsese** [comment]
Thanks for letting us know, glad you're not seeing this anymore - we'll go ahead and close for now but if you see it again and can reproduce, please let us know :v:
