### ISSUE TITLE
Cannot launch portable atom on WIN10 x 64

### ISSUE THREAD

**Issue by tinymins** [atom/atom#14150]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I tried to follow the step to [launch a portable atom](http://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode), but a got a crash report.

### Steps to Reproduce

1. Download and extract zip file to `D:\Program Files\Atom\app-1.15.0-x64`.
2. Create `D:\Program Files\Atom\.atom\`
3. Create `D:\Program Files\Atom\.atom\electronUserData\`
4. Startup `atom.exe`

**Expected behavior:** Startup a portable version.

**Actual behavior:** Crashed.

**Reproduces how often:** 100%

### Versions
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information
```
D:\Program Files\Atom\app-1.15.0-x64>echo %ATOM_HOME%
%ATOM_HOME%

D:\Program Files\Atom\app-1.15.0-x64>ls ../
app-1.11.0-dev-7404b9b  app.ico   bin       SquirrelSetup.log
app-1.15.0-x64          atom.bat  packages  Update.exe

D:\Program Files\Atom\app-1.15.0-x64>atom.exe

D:\Program Files\Atom\app-1.15.0-x64>
Cannot read property 'setPath' of undefined
TypeError: Cannot read property 'setPath' of undefined
    at Object.setUserData (D:\Program Files\Atom\app-1.15.0-x64\resources\app.asar\src\atom-paths.js:53:12)
    at start (D:\Program Files\Atom\app-1.15.0-x64\resources\app.asar\src\main-process\start.js:27:13)
    at Object.<anonymous> (D:\Program Files\Atom\app-1.15.0-x64\resources\app.asar\src\main-process\main.js:36:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Object.<anonymous> (D:\Program Files\Atom\app-1.15.0-x64\resources\electron.asar\browser\init.js:166:8)
    at Module._compile (module.js:556:32)

D:\Program Files\Atom\app-1.15.0-x64>atom.exe -v

D:\Program Files\Atom\app-1.15.0-x64>
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

D:\Program Files\Atom\app-1.15.0-x64>ls ../.atom/
blob-store     electronUserData  kite-config.json  snippets.cson
compile-cache  init.coffee       packages          storage
config.cson    keymap.cson       recovery          styles.less

D:\Program Files\Atom\app-1.15.0-x64>atom.exe --safe

D:\Program Files\Atom\app-1.15.0-x64>
Cannot read property 'setPath' of undefined
TypeError: Cannot read property 'setPath' of undefined
    at Object.setUserData (D:\Program Files\Atom\app-1.15.0-x64\resources\app.asar\src\atom-paths.js:53:12)
    at start (D:\Program Files\Atom\app-1.15.0-x64\resources\app.asar\src\main-process\start.js:27:13)
    at Object.<anonymous> (D:\Program Files\Atom\app-1.15.0-x64\resources\app.asar\src\main-process\main.js:36:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Object.<anonymous> (D:\Program Files\Atom\app-1.15.0-x64\resources\electron.asar\browser\init.js:166:8)
    at Module._compile (module.js:556:32)

D:\Program Files\Atom\app-1.15.0-x64>atom --clear-window-state

D:\Program Files\Atom\app-1.15.0-x64>
Cannot read property 'setPath' of undefined
TypeError: Cannot read property 'setPath' of undefined
    at Object.setUserData (D:\Program Files\Atom\app-1.15.0-x64\resources\app.asar\src\atom-paths.js:53:12)
    at start (D:\Program Files\Atom\app-1.15.0-x64\resources\app.asar\src\main-process\start.js:27:13)
    at Object.<anonymous> (D:\Program Files\Atom\app-1.15.0-x64\resources\app.asar\src\main-process\main.js:36:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Object.<anonymous> (D:\Program Files\Atom\app-1.15.0-x64\resources\electron.asar\browser\init.js:166:8)
    at Module._compile (module.js:556:32)

D:\Program Files\Atom\app-1.15.0-x64>
```

**Comment by damieng** [comment]
It appears there is a bug in the electronUserData portable handling. I'd recommend removing that folder until the fix ships.

**Comment by tinymins** [comment]
I tried to start a portable version of atom without that folder but failed. Seems that user folders always been created under `C:\Users\root\AppData\Roaming\Atom`.  @damieng

**Comment by damieng** [comment]
Yes, it will create that folder there but it contains nothing useful - it's stuff like the chromium debug inspector state etc. You can be portable without it.

**Comment by tinymins** [comment]
Thanks, it works well now.

**Comment by jsolisu** [comment]
#13813
