### ISSUE TITLE
"element.getModel" is not a function when no view has been opened yet.

### ISSUE THREAD

**Issue by phyllisstein** [atom/atom#14193]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Hey Atomizers! I just upgraded my version of Atom to 1.17.0-beta0, and I'm having a little trouble with several packages. Since I'm not sure if the behavior reflects an intentional change to Atom's API or not, I wanted to confirm before filing issues with the individual developers.

The issue seems to be that before an editor view has been opened, the function `getModel` is not defined on editor elements. This causes crashes in a number of packages that rely on `atom-space-pen-views` (I think [`text-editor-view.coffee:24`](https://github.com/atom/atom-space-pen-views/blob/master/src/text-editor-view.coffee#L24) is the problem line), and at least one ([`foldingtext-for-atom`](https://github.com/FoldingText/foldingtext-for-atom)) that does not. For example, I normally open a fresh window with "Empty Editor On Start" disabled, invoke the Project Manager package, pick a project, and do my business; now, since I haven't opened a tab yet, pulling up Project Manager throws an error like this one:

```
At /Users/daniel/.atom/packages/project-manager/node_modules/atom-space-pen-views/lib/text-editor-view.js:40

TypeError: this.element.getModel is not a function
    at /packages/project-manager/node_modules/atom-space-pen-views/lib/text-editor-view.js:40:34)
    at Object.content (/packages/project-manager/node_modules/atom-space-pen-views/lib/select-list-view.js:26:45)
    at Builder.tag (/packages/project-manager/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/project-manager/node_modules/space-pen/lib/space-pen.js:83:49)
    at Function.module.exports.SelectListView.content (/packages/project-manager/node_modules/atom-space-pen-views/lib/select-list-view.js:22:19)
    at /packages/project-manager/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/packages/project-manager/node_modules/space-pen/lib/space-pen.js:123:10)
    at /packages/project-manager/node_modules/space-pen/lib/space-pen.js:155:33)
    at /packages/project-manager/node_modules/atom-space-pen-views/lib/select-list-view.js:18:51)
    at /packages/project-manager/lib/views/projects-list-view.js:10:38)
    at /packages/project-manager/lib/project-manager.js:34:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

With FoldingText installed at all, opening a new Atom window throws this:

```
At /Users/daniel/.atom/packages/foldingtext-for-atom/lib/extensions/ui/text-input-element.coffee:19

TypeError: this.textEditorElement.getModel is not a function
    at /packages/foldingtext-for-atom/lib/extensions/ui/text-input-element.coffee:19:38)
    at Object.exports.consumeStatusBarService (/packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:9:28)
    at Object.addStatusBarItemsIfReady (/packages/foldingtext-for-atom/lib/foldingtext.coffee:139:53)
    at Object.consumeStatusBarService (/packages/foldingtext-for-atom/lib/foldingtext.coffee:130:6)
    at Provider.module.exports.Provider.provide (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:1)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:1)
    at Package.module.exports.Package.activateServices (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:446:1)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:256:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:99:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:642:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:623:1
    at Config.module.exports.Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:346:1)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:618:1)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:600:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:831:1
```

For the moment, uninstalling FoldingText and reenabling "Empty Editor On Start" seems to be a serviceable workaround. It'd be great to see an actual fix for this, though.

![screenflow](https://cloud.githubusercontent.com/assets/2207980/24997961/7f29a002-2006-11e7-9110-9b9527e995b9.gif)

### Steps to Reproduce

1. Install any package that depends on `atom-space-pen-views`---try e.g. Project Manager, it's lovely.
2. With "Open Empty Editor On Start" disabled, open a new Atom window.
3. Run your sample package before opening an editor view.
4. 💥 

**Expected behavior:** The package should run without crashing.

**Actual behavior:** The package crashes.

**Reproduces how often:** 100% of the time before an editor view has been created.

### Versions

**Atom**: 1.17.0-beta0 x64
**Electron**: 1.3.14
**OS**: Mac OS X 10.12.4

### Additional Information

💖

**Comment by as-cii** [comment]
Apologies for this issue, @phyllisstein and thank you so much for the detailed and clear report!

I have just created a pull request that fixes this problem: as soon as it gets merged, we will cherry pick it to the beta branch and release it in the next hotfix. ⚡️

**Comment by phyllisstein** [comment]
That's amazing! Thanks so much for your speedy response, and for knocking it out so quickly.

**Comment by as-cii** [comment]
Atom 1.17.0-beta1 has just been released! ✨
