### ISSUE TITLE
Installing apm : node: No such file or directory

### ISSUE THREAD

**Issue by roobinmason** [atom/atom#14259]
err during Installing apm:
>/home/ycl/Project/atom/atom/apm/node_modules/atom-package-manager/bin/apm: line 37: /home/ycl/Project/atom/atom/apm/node_modules/atom-package-manager/bin/node: No such file or directory
child_process.js:504
    throw err;
    ^

>Error: Command failed: /home/ycl/Project/atom/atom/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:481:13)
    at Object.execFileSync (child_process.js:501:13)
    at module.exports (/home/ycl/Project/atom/atom/script/lib/install-atom-dependencies.js:15:16)
    at Object.<anonymous> (/home/ycl/Project/atom/atom/script/bootstrap:28:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

can not find node under atom directory

**Comment by thomasjo** [comment]
Make sure to fulfill the prerequisites listed in the [build instructions](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md). Also, please fill in the issue template next time — we require _all_ issues to have a filled in issue template.
