### ISSUE TITLE
Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element ...

### ISSUE THREAD

**Issue by hailedangGT** [atom/atom#14268]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.

```
At /private/var/folders/8h/y6c3_pz963vbljztph4cf3rw0000gp/T/AppTranslocation/021ED26E-4DE5-49BB-A000-23CAA16A7B79/d/Atom.app/Contents/Resources/app.asar/src/line-numbers-tile-component.js:168

Error: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at Error (native)
    at LineNumbersTileComponent.module.exports.LineNumbersTileComponent.setLineNumberInnerNodes (/app.asar/src/line-numbers-tile-component.js:168:29)
    at LineNumbersTileComponent.module.exports.LineNumbersTileComponent.updateLineNumberNode (/app.asar/src/line-numbers-tile-component.js:181:14)
    at LineNumbersTileComponent.module.exports.LineNumbersTileComponent.updateLineNumbers (/app.asar/src/line-numbers-tile-component.js:98:16)
    at LineNumbersTileComponent.module.exports.LineNumbersTileComponent.updateSync (/app.asar/src/line-numbers-tile-component.js:78:19)
    at LineNumberGutterComponent.module.exports.TiledComponent.updateTileNodes (/app.asar/src/tiled-component.js:55:19)
    at LineNumberGutterComponent.module.exports.TiledComponent.updateSync (/app.asar/src/tiled-component.js:18:12)
    at GutterContainerComponent.module.exports.GutterContainerComponent.updateSync (/app.asar/src/gutter-container-component.js:79:25)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/app.asar/src/text-editor-component.js:235:39)
    at /app.asar/src/text-editor-component.js:323:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/app.asar/src/view-registry.js:219:9)
    at /app.asar/src/view-registry.js:3:59
```

### Commands

```
     -2:33.6.0 core:backspace (input.hidden-input)
     -2:32.6.0 core:save (input.hidden-input)
     -2:28.1.0 core:copy (input.hidden-input)
     -2:23.8.0 core:move-up (input.hidden-input)
     -2:23.5.0 editor:newline (input.hidden-input)
  3x -2:21.9.0 core:backspace (input.hidden-input)
     -2:07.2.0 editor:newline (input.hidden-input)
  7x -1:55.4.0 core:backspace (input.hidden-input)
     -1:50.5.0 core:copy (input.hidden-input)
     -1:49.3.0 core:paste (input.hidden-input)
     -1:33.6.0 core:copy (input.hidden-input)
     -1:32.3.0 core:paste (input.hidden-input)
  2x -1:31.8.0 core:save (input.hidden-input)
  3x -0:10.4.0 core:backspace (input.hidden-input)
  2x -0:01.9.0 editor:newline (input.hidden-input)
     -0:01.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
delete-lines 0.5.0 
isotope-ui 2.8.0 
```

**Comment by shanept** [comment]
@hailedangGT Could you please add steps to reproduce this?

**Comment by rsese** [comment]
Oh also, if you can reproduce can you let us know if you can also reproduce in safe mode (`atom --safe`)?

**Comment by hailedangGT** [comment]
I cannot reproduce the issue. It just happened one time.
