### ISSUE TITLE
Uncaught Error: Cannot find module '../src/safe-clipboard.js'

### ISSUE THREAD

**Issue by ClockworkSquirrel** [atom/atom#14260]
[Enter steps to reproduce:]

1. CTRL+A
2. CTRL+V

**Atom**: 1.17.0-beta0 x64
**Electron**: 1.3.14
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module '../src/safe-clipboard.js'

```
At C:\Users\celli\AppData\Local\atom\app-1.17.0-beta0\resources\app\node_modules\text-buffer\lib\text-buffer.js:854

Error: Cannot find module '../src/safe-clipboard.js'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.0-beta0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/static/<embedded>:73:1)
    at get__safeClipboard (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/clipboard.js:28:1)
    at get__safeClipboard2 (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/clipboard.js:34:1)
    at Clipboard.read (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/clipboard.js:95:1)
    at Clipboard.readWithMetadata (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/clipboard.js:107:1)
    at TextEditor.module.exports.TextEditor.pasteText (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/text-editor.js:3000:1)
    at TextEditor.core:paste (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/register-default-commands.js:448:1)
    at ~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/register-default-commands.js:677:1
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/node_modules/text-buffer/lib/text-buffer.js:849:1)
    at TextEditor.module.exports.TextEditor.transact (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/text-editor.js:1599:1)
    at atom-text-editor.newCommandListeners.(anonymous function) (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/register-default-commands.js:676:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:22.6.0 core:select-all (input.hidden-input)
     -0:22.3.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.6 
atom-monokai 0.10.9 
busy-signal 1.3.0 
emmet 2.4.3 
go-debug 1.2.0 
go-plus 5.4.0 
go-signature-statusbar 1.2.0 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.2.3 
Remote-FTP 0.10.7 
```

**Comment by rsese** [comment]
Thanks for the report!  I just installed 1.17.0-beta3 on Windows 10 and couldn't reproduce - can you confirm a few things for us?

* Do you have something on your clipboard before you select all and then paste?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (atom --safe)?

**Comment by ColeTheKing** [comment]
Just had this happen to me, happens when I've done CTRL + C on highlighted text.

This was the error it gave me:
`C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\node_modules\text-buffer\lib\text-buffer.js:854
Hide Stack Trace
Error: Cannot find module '../src/safe-clipboard.js'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\src\module-cache.js:354:1)
    at Module.require (file:///C:/Users/Owner/AppData/Local/atom/app-1.17.0-beta2/resources/app/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\static\<embedded>:73:1)
    at get__safeClipboard (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\src\clipboard.js:28:1)
    at get__safeClipboard2 (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\src\clipboard.js:34:1)
    at Clipboard.write (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\src\clipboard.js:86:1)
    at Selection.module.exports.Selection.copy (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\src\selection.js:748:1)
    at TextEditor.module.exports.TextEditor.copySelectedText (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\src\text-editor.js:2962:1)
    at TextEditor.core:copy (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\src\register-default-commands.js:445:1)
    at C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\src\register-default-commands.js:677:1
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\node_modules\text-buffer\lib\text-buffer.js:849:1)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\src\text-editor.js:1599:1)
    at atom-text-editor.newCommandListeners.(anonymous function) (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\src\register-default-commands.js:676:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\src\command-registry.js:265:1)
    at C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\src\command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\src\window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (C:\Users\Owner\AppData\Local\atom\app-1.17.0-beta2\resources\app\src\window-event-handler.js:3:1)`

**Comment by ColeTheKing** [comment]
And with that, updating seems to have corrected it.

**Comment by rsese** [comment]
Thanks @ColeTheKing :v:  @ClockworkSquirrel can you update to beta3 and let us know if you can still reproduce the error?

**Comment by maksugr** [comment]
Any news? I have the same bug. v.1.17.2 macOS

**Comment by maksugr** [comment]
Reload Atom fixed it.

**Comment by rsese** [comment]
Huh so `Window: Reload` fixed it for you @maksugr?  That's interesting, thanks for letting us know.

@ClockworkSquirrel - I'll go ahead and close this for now since we haven't heard back about our [questions](https://github.com/atom/atom/issues/14260#issuecomment-295401077), but if you still have trouble after updating the beta version you're running, please let us know and we'll reopen.

**Comment by zircuitz** [comment]
I am now also receiving this message. On version 1.18.0 (x64) of Atom.

OS running is Mac OS Sierra (10.12.2)

`Uncaught Error: Cannot find module '../src/safe-clipboard.js'`

`Error: Cannot find module '../src/safe-clipboard.js'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/private/var/folders/v1/qlhxd_dd7jv7kr85x6164s9h0000gq/T/AppTranslocation/A67F7077-6C7F-4BD6-A91B-67D842AA17F6/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/private/var/folders/v1/qlhxd_dd7jv7kr85x6164s9h0000gq/T/AppTranslocation/A67F7077-6C7F-4BD6-A91B-67D842AA17F6/d/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///private/var/folders/v1/qlhxd_dd7jv7kr85x6164s9h0000gq/T/AppTranslocation/A67F7077-6C7F-4BD6-A91B-67D842AA17F6/d/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (/private/var/folders/v1/qlhxd_dd7jv7kr85x6164s9h0000gq/T/AppTranslocation/A67F7077-6C7F-4BD6-A91B-67D842AA17F6/d/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at get__safeClipboard (/private/var/folders/v1/qlhxd_dd7jv7kr85x6164s9h0000gq/T/AppTranslocation/A67F7077-6C7F-4BD6-A91B-67D842AA17F6/d/Atom.app/Contents/Resources/app/src/clipboard.js:28:51)
    at get__safeClipboard2 (/private/var/folders/v1/qlhxd_dd7jv7kr85x6164s9h0000gq/T/AppTranslocation/A67F7077-6C7F-4BD6-A91B-67D842AA17F6/d/Atom.app/Contents/Resources/app/src/clipboard.js:34:76)
    at Clipboard.write (/private/var/folders/v1/qlhxd_dd7jv7kr85x6164s9h0000gq/T/AppTranslocation/A67F7077-6C7F-4BD6-A91B-67D842AA17F6/d/Atom.app/Contents/Resources/app/src/clipboard.js:86:13)
    at AboutView.handleVersionClick (/private/var/folders/v1/qlhxd_dd7jv7kr85x6164s9h0000gq/T/AppTranslocation/A67F7077-6C7F-4BD6-A91B-67D842AA17F6/d/Atom.app/Contents/Resources/app/node_modules/about/lib/components/about-view.js:66:28)`

**Comment by Deanveloper** [comment]
I am also receiving the issue. Version 1.20.0 on Windows 10 x64.

```Error: Cannot find module '../src/safe-clipboard.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\src\module-cache.js:354:58)
    at Module.require (file:///C:/Users/Dean/AppData/Local/atom/app-1.20.0/resources/app/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\static\<embedded>:96:26)
    at get__safeClipboard (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\src\clipboard.js:28:51)
    at get__safeClipboard2 (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\src\clipboard.js:34:76)
    at Clipboard.read (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\src\clipboard.js:95:20)
    at Clipboard.readWithMetadata (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\src\clipboard.js:107:29)
    at TextEditor.module.exports.TextEditor.pasteText (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\src\text-editor.js:3048:47)
    at TextEditor.core:paste (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\src\register-default-commands.js:448:27)
    at C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\src\register-default-commands.js:677:40
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:894:24)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\src\text-editor.js:1673:32)
    at HTMLElement.newCommandListeners.(anonymous function) (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\src\register-default-commands.js:676:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\src\command-registry.js:265:35)
    at C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\src\command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\src\window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (C:\Users\Dean\AppData\Local\atom\app-1.20.0\resources\app\src\window-event-handler.js:3:65)```

**Comment by Deanveloper** [comment]
Reinstalling fixed the issue

**Comment by rsese** [comment]
Thanks for confirming that reinstalling fixed things for you @Deanveloper :+1:

@zircuitz - are you still hitting this error and if so, did you try reinstalling?

**Comment by Lomzy66** [comment]
Hi @rsese 

2017-09-20

I highlighted text, copied and then tried to paste in another .php file when I got this error.
I'm going to re-install atom since it doesn't want to open up at all anymore.

I didn't save the error because it's already been reported but I'll give more feedback when I've finished re-installing atom.
