### ISSUE TITLE
Uncaught ReferenceError: functions is not defined

### ISSUE THREAD

**Issue by ericsonluciano** [atom/atom#14295]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught ReferenceError: functions is not defined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1045

ReferenceError: functions is not defined
    at /Users/thousandminds/.atom/init.coffee:15:5
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1092:27)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1058:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:920:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.saveActivePaneItem (/app.asar/src/workspace.js:851:33)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
atom-wordpress 0.3.0 
atomic-chrome 0.3.0 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.0 
css-snippets 1.1.0 
emmet 2.4.3 
intentions 1.1.2 
linter 2.1.4 
linter-scss-lint 3.1.0 
linter-ui-default 1.2.3 
livestyle-atom 0.2.9 
material 2.2.0 
material-syntax 0.6.1 
material-ui 1.0.10 
pigments 0.39.1 
space-tab 0.4.2 
tab-switcher 1.5.4 
wordpress 0.2.0 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
```

not sure why this always happen when i saving my work

**Comment by 50Wliu** [comment]
> at /Users/thousandminds/.atom/init.coffee:15:5

Please check your `init.coffee`.
