### ISSUE TITLE
32 bit debian build error during snapshot generation

### ISSUE THREAD

**Issue by RequiemGhost** [atom/atom#14301]
### Description

I'm trying to build the 32 bits .deb package.
And I get an error during the snapshot generation using Electron.
(1260)Error: /home/ghost/Temp/atom/out/app/node_modules/rimraf/node_modules/glob/glob.js
Cannot replace with lazy function because the supplied node does not belong to an assignment

Here is the output of the build/script  
```
Packaging app for platform linux ia32 using electron v1.3.14
Changing permissions for node files in /home/ghost/Temp/atom/out/atom-1.18.0-dev-f4a83b2-i386
Copying non-ASAR resources to /home/ghost/Temp/atom/out/atom-1.18.0-dev-f4a83b2-i386/resources
Writing LICENSE.md to /home/ghost/Temp/atom/out/atom-1.18.0-dev-f4a83b2-i386/resources
Application bundle created at /home/ghost/Temp/atom/out/atom-1.18.0-dev-f4a83b2-i386
Generating snapshot script at "/home/ghost/Temp/atom/out/startup.js" (1260)Error: /home/ghost/Temp/atom/out/app/node_modules/rimraf/node_modules/glob/glob.js
Cannot replace with lazy function because the supplied node does not belong to an assignment expression or a variable declaration!
  at FileRequireTransform.replaceAssignmentOrDeclarationWithLazyFunction (/home/ghost/Temp/atom/script/node_modules/electron-link/lib/file-require-transform.js:180:11)
  at Context.visitIdentifier (/home/ghost/Temp/atom/script/node_modules/electron-link/lib/file-require-transform.js:72:18)
  at Context.invokeVisitorMethod (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:344:49)
  at Visitor.PVp.visitWithoutReset (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:196:32)
  at NodePath.each (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path.js:101:26)
  at visitChildren (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:219:18)
  at Visitor.PVp.visitWithoutReset (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:204:20)
  at NodePath.each (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path.js:101:26)
  at visitChildren (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:219:18)
  at Visitor.PVp.visitWithoutReset (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:204:20)
  at Visitor.PVp.visit (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:133:29)
  at Object.visit (/home/ghost/Temp/atom/script/node_modules/ast-types/lib/path-visitor.js:101:55)
  at FileRequireTransform.replaceDeferredRequiresWithLazyFunctions (/home/ghost/Temp/atom/script/node_modules/electron-link/lib/file-require-transform.js:68:20)
  at FileRequireTransform.apply (/home/ghost/Temp/atom/script/node_modules/electron-link/lib/file-require-transform.js:25:10)
  at /home/ghost/Temp/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:54:54
  at undefined.next (native)
  at step (/home/ghost/Temp/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:191)
  at /home/ghost/Temp/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:361
```

### Steps to Reproduce

**Expected behavior:** generating the snapshot, then the .deb package

**Actual behavior:** Error when generating snapshot

**Reproduces how often:** Everytime !

### Versions

atom : v1.18.0
node : v6.10.2
npm: v4.5.0
node-gyp: v3.6.0

### Additional Information

Yes, I'm trying to build the 32bit package.
I still have an old eeePC that works under debian and, while it's not a race computer, I'still using it to write some code...

**Comment by BinaryMuse** [comment]
Hey, @RequiemGhost,

What's the out put of `node --version` and `npm --version` from the shell where you're trying to build?

**Comment by RequiemGhost** [comment]
node : 6.10.2
npm : 4.5.0

**Comment by BinaryMuse** [comment]
Hm, @as-cii do you think this may have to do with some difference in the way modules are being flattened?

**Comment by as-cii** [comment]
Yeah, it is possible. @RequiemGhost: have you tried running `script/clean` first and then run again `script/build` again?

**Comment by RequiemGhost** [comment]
Yes.

I tried script/clean  then script/build, but the result is the same.
I tried completely emptying the directory and getting the sources again from  GIT before building. 
Also tried on a different distro (latest 32 bits debian and latest 32 bits ubuntu), but always get the same error...

**Comment by tbrockman** [comment]
Having the same issue building on 64-bit Windows as well.

python: 2.7.13 (using PYTHON environment variable)
node: 6.11.1
npm: 3.10.10

error output:

```sh
Generating snapshot script at "F:\Workspace\atom\out\startup.js" (8)Error: F:\Workspace\atom\out\app\node_modules\rimraf\node_modules\glob\glob.js
Cannot replace with lazy function because the supplied node does not belong to an assignment expression or a variable declaration!
  at FileRequireTransform.replaceAssignmentOrDeclarationWithLazyFunction (F:\Workspace\atom\script\node_modules\electron-link\lib\file-require-transform.js:180:11)
  at Context.visitIdentifier (F:\Workspace\atom\script\node_modules\electron-link\lib\file-require-transform.js:72:18)
  at Context.invokeVisitorMethod (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:344:49)
  at Visitor.PVp.visitWithoutReset (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:196:32)
  at NodePath.each (F:\Workspace\atom\script\node_modules\ast-types\lib\path.js:101:26)
  at visitChildren (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:219:18)
  at Visitor.PVp.visitWithoutReset (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:204:20)
  at visitChildren (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:204:20)
  at visitChildren (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:204:20)
  at NodePath.each (F:\Workspace\atom\script\node_modules\ast-types\lib\path.js:101:26)
  at visitChildren (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:219:18)
  at Visitor.PVp.visitWithoutReset (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:204:20)
  at visitChildren (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:204:20)
  at visitChildren (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:204:20)
  at Visitor.PVp.visit (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:133:29)
  at Object.visit (F:\Workspace\atom\script\node_modules\ast-types\lib\path-visitor.js:101:55)
  at FileRequireTransform.replaceDeferredRequiresWithLazyFunctions (F:\Workspace\atom\script\node_modules\electron-link\lib\file-require-transform.js:68:20)
  at FileRequireTransform.apply (F:\Workspace\atom\script\node_modules\electron-link\lib\file-require-transform.js:25:10)
  at F:\Workspace\atom\script\node_modules\electron-link\lib\generate-snapshot-script.js:52:54
  at undefined.next (native)
  at step (F:\Workspace\atom\script\node_modules\electron-link\lib\generate-snapshot-script.js:3:191)
  at F:\Workspace\atom\script\node_modules\electron-link\lib\generate-snapshot-script.js:3:361
```

**Comment by artynet** [comment]
@tbrockman have you spotted the exact commit by any chance ? I still have the same issue when using : 

node: 6.11.3
npm: 5.4.1
python : 2.7.6

Best, Arturo

**Comment by artynet** [comment]
@tbrockman just found the fix. Change the npm version here :

```patch
diff --git a/script/package.json b/script/package.json
index e5c09c286..350fc2b0e 100644
--- a/script/package.json
+++ b/script/package.json
@@ -22,7 +22,7 @@
     "minidump": "0.9.0",
     "mkdirp": "0.5.1",
     "normalize-package-data": "2.3.5",
-    "npm": "3.10.5",
+    "npm": "5.3.0",
     "passwd-user": "2.1.0",
     "pegjs": "0.9.0",
     "runas": "3.1.1",
```
and then launch the build with :

`CC=clang CXX=clang++ ./script/build --create-debian-package`

and you're done. Tested with atom v1.19.7

Best, Arturo.

**Comment by hypersad** [comment]
Also encountered with this.

**Comment by bosspan** [comment]
Also encountered with this.

**Comment by bosspan** [comment]
Also encountered with this.

apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.36.1
python 2.7.16

**Comment by 50Wliu** [comment]
@bosspan please open a new issue, thanks.
