### ISSUE TITLE
Failed to load the git-grep package

### ISSUE THREAD

**Issue by sshnaidm** [atom/atom#14321]
Just try to install git-grep package.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: "Red Hat
**Thrown From**: 'git-grep' package vundefined

### Stack Trace

Failed to load the git-grep package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (/packages/git-grep/lib/git-grep-view.coffee:1:1)
    at /packages/git-grep/lib/git-grep-view.coffee:7:7
    at /packages/git-grep/lib/git-grep-view.coffee:43:12)
    at /packages/git-grep/lib/git-grep-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/git-grep/lib/git-grep.coffee:1:15)
    at /packages/git-grep/lib/git-grep.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:548:30)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -2:19.3.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:12.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
ansible-snippets 0.2.0 
atom-django 0.3.2 
atom-jinja2 0.6.0 
atom-monokai 0.10.9 
autocomplete-ansible 0.1.11 
autocomplete-python 1.8.63 
busy-signal 1.3.0 
docker 0.7.0 
dockerletion 0.2.0 
git-plus 7.4.0 
git-time-machine 1.5.9 
Hydrogen 1.11.2 
intentions 1.1.2 
language-ansible 0.2.1 
language-docker 1.1.7 
language-ini 1.19.0 
language-nginx 0.7.2 
language-sphinx 0.1.6 
linter 2.1.4 
linter-ansible-linting 1.2.3 
linter-ansible-syntax 1.1.3 
linter-docker 0.2.0 
linter-ui-default 1.2.3 
local-history 4.0.1 
minimap 4.27.1 
monokai 0.22.0 
platformio-ide-terminal 2.5.0 
project-manager 3.3.4 
python-indent 1.0.2 
python-tools 0.6.9 
run-command 0.3.2 
set-syntax 0.3.2 
terminal-plus 0.14.5 
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [git-grep](atom.io/packages/git-grep) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
