### ISSUE TITLE
Module version mismatch expected 49, got 48

### ISSUE THREAD

**Issue by xmonader** [atom/atom#14329]
I'm trying to develop some features for language-capnproto package. and I added `bignum` node module as a dependency.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04
**Thrown From**: [language-capnproto](https://github.com/tekacs/language-capnproto) package 0.3.0

### Stack Trace

Failed to activate the language-capnproto package

```
At Module version mismatch. Expected 49, got 48.

Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) (ELECTRON_ASAR.js:168:20)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/language-capnproto/node_modules/bignum/index.js:4:11)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/language-capnproto/lib/capnp.coffee:2:27)
    at /packages/language-capnproto/lib/capnp.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-material-ui 1.3.9 
autocomplete-python 1.8.12 
git-plus 7.0.7 
hyperclick 0.0.40 
language-capnproto 0.3.0 
linter 1.11.18 
linter-flake8 2.1.3 
linter-python 3.0.5 
linter-python-pyflakes 0.1.0 
markdown-preview-plus 2.4.0 
python-indent 1.0.2 
python-tools 0.6.9 
terminal-fusion 2.4.2 
```

**Comment by 50Wliu** [comment]
You need to `apm install`, not `npm install`.
