### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset -1 is larger than or e...

### ISSUE THREAD

**Issue by marclundgren** [atom/atom#14335]
[Enter steps to reproduce:]

1. copy this block, paste it into a new atom tab
```
Log: |
           { type: 'warn',
             text: '\'DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]\\n    raiseOnDeprecation@http://localhost:7357/assets/vendor.js:19977:17\\n    http://localhost:7357/assets/vendor.js:20067:15\\n    invoke@http://localhost:7357/assets/vendor.js:20083:21\\n    deprecate@http://localhost:7357/assets/vendor.js:20036:37\\n    deprecate@http://localhost:7357/assets/vendor.js:30047:42\\n    http://localhost:7357/assets/vendor.js:122510:30\\n    exports@http://localhost:7357/assets/vendor.js:123:37\\n    _reify@http://localhost:7357/assets/vendor.js:157:66\\n    reify@http://localhost:7357/assets/vendor.js:144:33\\n    exports@http://localhost:7357/assets/vendor.js:121:15\\n    _reify@http://localhost:7357/assets/vendor.js:157:66\\n    reify@http://localhost:7357/assets/vendor.js:144:33\\n    exports@http://localhost:7357/assets/vendor.js:121:15\\n    _reify@http://localhost:7357/assets/vendor.js:157:66\\n    reify@http://localhost:7357/assets/vendor.js:144:33\\n    exports@http://localhost:7357/assets/vendor.js:121:15\\n    requireModule@http://localhost:7357/assets/vendor.js:38:25\\n    http://localhost:7357/assets/vendor.js:123070:27\\n    forEach@[native code]\\n    http://localhost:7357/assets/vendor.js:123067:15\\n    http://localhost:7357/assets/revv.js:218:41\\n    exports@http://localhost:7357/assets/vendor.js:123:37\\n    _reify@http://localhost:7357/assets/vendor.js:157:66\\n    reify@http://localhost:7357/assets/vendor.js:144:33\\n    exports@http://localhost:7357/assets/vendor.js:121:15\\n    _reify@http://localhost:7357/assets/vendor.js:157:66\\n    reify@http://localhost:7357/assets/vendor.js:144:33\\n    exports@http://localhost:7357/assets/vendor.js:121:15\\n    _reify@http://localhost:7357/assets/vendor.js:157:66\\n    reify@http://localhost:7357/assets/vendor.js:144:33\\n    exports@http://localhost:7357/assets/vendor.js:121:15\\n    requireModule@http://localhost:7357/assets/vendor.js:38:25\\n    require@http://localhost:7357/assets/test-support.js:21566:14\\n    loadModules@http://localhost:7357/assets/test-support.js:21558:21\\n    load@http://localhost:7357/assets/test-support.js:21588:33\\n    http://localhost:7357/assets/test-support.js:21476:20\'\n' }
```

2. Highlight all `\\n` (Hint: highlight one of them, then press `cmd+d` until all are highlighted.
3. Press `enter` (to replace the `newline` characters with an actual new line)
4. Assert the error in the title

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset -1 is larger than or equal to the node's length (2).

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/lines-yardstick.js:162

Error: Failed to execute 'setEnd' on 'Range': The offset -1 is larger than or equal to the node's length (2).
    at Error (native)
    at LinesYardstick.module.exports.LinesYardstick.clientRectForRange (/app.asar/src/lines-yardstick.js:162:32)
    at LinesYardstick.module.exports.LinesYardstick.leftPixelPositionForScreenPosition (/app.asar/src/lines-yardstick.js:142:40)
    at LinesYardstick.module.exports.LinesYardstick.pixelPositionForScreenPosition (/app.asar/src/lines-yardstick.js:107:19)
    at TextEditorPresenter.module.exports.TextEditorPresenter.absolutePixelRectForScreenRange (/app.asar/src/text-editor-presenter.js:1338:36)
    at TextEditorPresenter.module.exports.TextEditorPresenter.pixelRectForScreenRange (/app.asar/src/text-editor-presenter.js:1352:19)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateCursorsState (/app.asar/src/text-editor-presenter.js:560:26)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPostMeasurementState (/app.asar/src/text-editor-presenter.js:154:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/app.asar/src/text-editor-component.js:202:38)
    at /app.asar/src/text-editor-component.js:323:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/app.asar/src/view-registry.js:219:9)
    at /app.asar/src/view-registry.js:3:59
```

### Commands

```
     -0:36.1.0 editor:select-to-end-of-line (input.hidden-input)
  4x -0:35.6.0 core:select-left (input.hidden-input)
     -0:34.8.0 core:select-right (input.hidden-input)
 40x -0:34.6.0 find-and-replace:select-next (input.hidden-input)
     -0:32.5.0 editor:newline (input.hidden-input)
  2x -0:29.9.0 core:undo (input.hidden-input)
     -0:22.9.0 core:select-all (input.hidden-input)
     -0:21.1.0 core:close (input.hidden-input)
     -0:19.7.0 application:new-file (div.results-view.focusable-panel)
     -0:19.5.0 core:paste (input.hidden-input)
  5x -0:18 core:move-left (input.hidden-input)
  2x -0:17.1.0 core:select-right (input.hidden-input)
 41x -0:16.7.0 find-and-replace:select-next (input.hidden-input)
     -0:14.5.0 core:backspace (input.hidden-input)
     -0:13.8.0 editor:newline (input.hidden-input)
     -0:12.6.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
aligner 0.22.3 
atom-beautify 0.29.23 
atom-handlebars 1.3.0 
atom-jade 0.3.0 
atom-material-syntax 1.0.2 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.10 
atom-pair 2.0.10 
atom-space-pen-views 2.2.0 
atomic-chrome 0.3.0 
atomify 0.3.0 
autocomplete-flow 1.6.0 
busy-signal 1.4.1 
clipboard-plus 0.5.1 
dracula-theme 2.0.3 
editorconfig 2.2.2 
emmet 2.4.3 
es6-javascript 1.0.0 
eslint-fixer 1.3.0 
fast-eslint 3.13.0 
file-icons 2.1.4 
file-type-icons 1.3.3 
git-time-machine 1.5.9 
gloom 0.4.13 
highlight-selected 0.13.1 
intentions 1.1.2 
javascript-snippets 1.2.1 
kite 0.22.0 
language-babel 2.57.7 
language-handlebars 0.2.0 
linter 2.1.4 
linter-eslint 8.1.7 
linter-handlebars 2.3.4 
linter-htmlhint 1.3.3 
linter-scss-lint 3.1.0 
linter-ui-default 1.2.3 
linter-write-good 0.9.0 
my-package 0.0.0 
native-ui 0.20.6 
new-era-light-syntax 0.3.1 
nord-atom-ui 0.11.0 
nucleus-dark-ui 0.12.1 
nuclide 0.220.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
react 0.16.2 
redux-snippets 0.2.2 
scratch 1.2.0 
script 3.14.1 
scroll-through-time 0.2.0 
set-syntax 0.3.2 
sort-lines 0.14.0 
terminal-plus 0.14.5 
transform 0.4.0 
word-count 0.0.0 
zentabs 0.8.8 
```

**Comment by marclundgren** [comment]
hmm, i'm closing this as I can no longer reproduce the problem

**Comment by rsese** [comment]
Hmmm, I wasn't able to reproduce with 1.16.0 on macOS 10.12.4 (I tried both with and without safe mode).  Can you reproduce in safe mode (`atom --safe`) consistently?

**Comment by marclundgren** [comment]
@rsese hmm, you're right - `safe` mode had no problem accomplishing this multi-replace task.
