### ISSUE TITLE
Build and install locally does not work. Ubuntu 16.04

### ISSUE THREAD

**Issue by anriseth** [atom/atom#14343]
When I try to build and install atom locally (from git 1.16-releases branch), I get an error due to the script trying to install something to `/usr/local/share/applications`:
```
✔ ~/local/source/atom [1.16-releases|✔] 
13:49 $ script/build --install=$HOME/local
Node:	v6.10.2
Npm:	v3.10.5
Installing script dependencies
Installing apm
Installing modules ✓
Wrote Dependencies Fingerprint: /home/riseth/local/source/atom/node_modules/.dependencies-fingerprint 46f185902ac9d9fc349caa5538dc482fa1f21be5
Cleaning /home/riseth/local/source/atom/out
Copying assets to /home/riseth/local/source/atom/out/app
Transpiling Babel paths in /home/riseth/local/source/atom/out/app
Transpiling CoffeeScript paths in /home/riseth/local/source/atom/out/app
Transpiling CSON paths in /home/riseth/local/source/atom/out/app
Transpiling PEG.js paths in /home/riseth/local/source/atom/out/app
Generating module cache for /home/riseth/local/source/atom/out/app
Generating pre-built less cache in /home/riseth/local/source/atom/out/app/less-compile-cache
Generating metadata for /home/riseth/local/source/atom/out/app/package.json
Generating API docs at /home/riseth/local/source/atom/docs/output/atom-api.json
Dumping symbols in /home/riseth/local/source/atom/out/symbols
Running electron-packager on /home/riseth/local/source/atom/out/app with app name "atom"
Packaging app for platform linux x64 using electron v1.3.13
Changing permissions for node files in /home/riseth/local/source/atom/out/atom-1.16.0-amd64
Copying non-ASAR resources to /home/riseth/local/source/atom/out/atom-1.16.0-amd64/resources
Writing LICENSE.md to /home/riseth/local/source/atom/out/atom-1.16.0-amd64/resources
Application bundle created at /home/riseth/local/source/atom/out/atom-1.16.0-amd64
Skipping creating debian package. Specify the --create-debian-package option to create it.
Skipping creating rpm package. Specify the --create-rpm-package option to create it.
Skipping artifacts compression. Specify the --compress-artifacts option to compress Atom binaries (and symbols on macOS)
Error: EACCES: permission denied, mkdir '/usr/local/share/applications'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at Object.mkdirsSync (/home/riseth/local/source/atom/script/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:29:9)
    at module.exports (/home/riseth/local/source/atom/script/lib/install-application.js:51:8)
    at dumpSymbols.then.then.then.packagedAppPath (/home/riseth/local/source/atom/script/build:101:7)
```

I have installed Node.js locally from `git` as well.

**Comment by anriseth** [comment]
I have now tried with Node.js and npm installed via `nvm`, with the same result
Node:	v6.10.3
Npm:	v4.5.0

Note that `/usr/local/share/applications` does not exist on my system, and I have not got sudo rights.

**Comment by ungb** [comment]
Hey @anriseth, does this work off master?  I'm currently trying it out now on ubuntu 16.04.2.  

Are you running `script/build --install`?

**Comment by anriseth** [comment]
Installing from master works. Thank you @ungb

**Comment by Adam-Morris** [comment]
```
$ script/build --install

Node:	v6.0.0
Npm:	v3.10.5
Installing script dependencies
Installing apm
Installing modules ✓
Wrote Dependencies Fingerprint: /home/amorris/programs/atom/node_modules/.dependencies-fingerprint 2b1eddd0d1f28b80e1dec6efb728d47c6193c00d
Cleaning /home/amorris/programs/atom/out
Copying assets to /home/amorris/programs/atom/out/app
Transpiling packages with custom transpiler configurations in /home/amorris/programs/atom/out/app
 transpiling for package github
Installing modules ✓
Transpiling Babel paths in /home/amorris/programs/atom/out/app
Transpiling CoffeeScript paths in /home/amorris/programs/atom/out/app
Transpiling CSON paths in /home/amorris/programs/atom/out/app
Transpiling PEG.js paths in /home/amorris/programs/atom/out/app
Generating module cache for /home/amorris/programs/atom/out/app
Generating pre-built less cache in /home/amorris/programs/atom/out/app/less-compile-cache
Generating metadata for /home/amorris/programs/atom/out/app/package.json
Generating API docs at /home/amorris/programs/atom/docs/output/atom-api.json
Dumping symbols in /home/amorris/programs/atom/out/symbols
Running electron-packager on /home/amorris/programs/atom/out/app with app name "atom"
Packaging app for platform linux x64 using electron v1.6.9
Changing permissions for node files in /home/amorris/programs/atom/out/atom-1.19.0-dev-c6bf86c-amd64
Copying non-ASAR resources to /home/amorris/programs/atom/out/atom-1.19.0-dev-c6bf86c-amd64/resources
Writing LICENSE.md to /home/amorris/programs/atom/out/atom-1.19.0-dev-c6bf86c-amd64/resources
Application bundle created at /home/amorris/programs/atom/out/atom-1.19.0-dev-c6bf86c-amd64

Verifying if snapshot can be executed via `mksnapshot`
Generating startup blob at "/home/amorris/programs/atom/out/snapshot_blob.bin"
Moving generated startup blob into "/home/amorris/programs/atom/out/atom-1.19.0-dev-c6bf86c-amd64/snapshot_blob.bin"
Skipping creating debian package. Specify the --create-debian-package option to create it.
Skipping creating rpm package. Specify the --create-rpm-package option to create it.
Skipping artifacts compression. Specify the --compress-artifacts option to compress Atom binaries (and symbols on macOS)
Error: EACCES: permission denied, mkdir '/usr/local/share/applications'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:916:18)
  at Object.mkdirsSync (/home/amorris/programs/atom/script/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:29:9)
  at module.exports (/home/amorris/programs/atom/script/lib/install-application.js:54:8)
  at dumpSymbols.then.then.then.then.packagedAppPath (/home/amorris/programs/atom/script/build:111:7)
```

Having same issue, I am not sure what you meant when you say to install it from master. I am executing the command whilst in the top directory of the repository.

**Comment by jlvivero** [comment]
This is still an issue if you want to build from source and don't have the permissions. Any workaround?

**Comment by rsese** [comment]
Have you tried the `--install` flag [1] to set a different directory @jlvivero?

[1]: https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#scriptbuild-options

**Comment by jlvivero** [comment]
oh, wow I can't believe I missed that... I'll try it once I get home and edit this comment to say if it worked or not so that people don't get double notifications. 
Thanks @rsese !
