### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 0)

### ISSUE THREAD

**Issue by matthewdias** [atom/atom#14356]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: 
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

For some files the text doesn't even load. For others it loads but gives the error below when steps below are followed. Files where the text doesn't load also do this. If the file is closed and reopened without loading the window it works fine. On reload it always happens again. I couldn't reproduce in safe mode.

```
TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at DisplayLayer.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:326:11)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:163:32)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:154:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:72:31
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:684:7)
    at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:70:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1902:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2125:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1901:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:721:25)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:59)
```

### Steps to Reproduce

1. Reload the window with an affected file open (I haven't figured out which files are affected)
2. Click anywhere in the editor
3. error pops up

### Versions

```
~ ❯ atom -v 
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
~ ❯ apm -v
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.11.0
```

**Comment by maxbrunsfeld** [comment]
Can you report whether this happens in safe mode?

**Comment by matthewdias** [comment]
It doesn't happen in safe mode

**Comment by 50Wliu** [comment]
Thank you for reaching out!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
