### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.177.38.133:80

### ISSUE THREAD

**Issue by gauravSinghKushwaha** [atom/atom#14353]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.177.38.133:80

```
At stream.js:74

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.177.38.133:80
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  3x -8:31.3.0 core:confirm (input.hidden-input)
 10x -8:00.8.0 core:backspace (input.hidden-input)
     -7:00.8.0 core:confirm (input.hidden-input)
  9x -6:21.3.0 core:paste (input.hidden-input)
     -2:40.1.0 fuzzy-finder:toggle-buffer-finder (input.hidden-input)
     -2:39.7.0 core:paste (input.hidden-input)
     -2:38.3.0 core:confirm (input.hidden-input)
     -1:54.8.0 core:paste (input.hidden-input)
     -1:53.9.0 core:confirm (input.hidden-input)
     -1:29.8.0 core:paste (input.hidden-input)
     -1:21.8.0 core:backspace (input.hidden-input)
     -1:21.1.0 core:confirm (input.hidden-input)
  3x -1:19.9.0 core:backspace (input.hidden-input)
     -1:19.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
file-icons 2.1.4 
git-clone 0.2.0 
git-plus 7.8.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
open-in-browser 0.5.0 
pretty-json 1.6.3 
rest-client 1.3.1 
set-syntax 0.3.2 
sync-settings 0.8.1 
turbo-javascript 1.4.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?
