### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=504

### ISSUE THREAD

**Issue by RedBlackTreei** [atom/atom#14360]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=504

```
At stream.js:74

Error: tunneling socket could not be established, statusCode=504
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:165:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -5:37.2.0 core:cancel (input.hidden-input)
     -5:36.4.0 editor:consolidate-selections (input.hidden-input)
     -5:36.4.0 core:cancel (input.hidden-input)
     -5:36 editor:consolidate-selections (input.hidden-input)
     -5:36 core:cancel (input.hidden-input)
     -5:35.8.0 editor:consolidate-selections (input.hidden-input)
     -5:35.8.0 core:cancel (input.hidden-input)
     -5:10 command-palette:toggle (input.hidden-input)
  4x -5:05.8.0 core:backspace (input.hidden-input)
     -5:03.8.0 editor:consolidate-selections (input.hidden-input)
     -5:03.8.0 core:cancel (input.hidden-input)
     -4:59.6.0 command-palette:toggle (input.hidden-input)
     -4:55.8.0 core:move-down (input.hidden-input)
     -4:53.6.0 core:confirm (input.hidden-input)
     -4:53.6.0 settings-view:install-packages-and-themes (input.hidden-input)
  2x -4:46.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
language-todotxt 0.6.1 
markdown-table-editor 0.5.1 
markdown-writer 2.6.4 
pretty-json 1.6.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?
