### ISSUE TITLE
Uncaught Error: target of repeat operator is not specified

### ISSUE THREAD

**Issue by Intipablo** [atom/atom#14378]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: target of repeat operator is not specified

```
At C:\Users\inti\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\first-mate\lib\scanner.js:31

Error: target of repeat operator is not specified
    at Error (native)
    at Scanner.module.exports.Scanner.createScanner (/app.asar/node_modules/first-mate/lib/scanner.js:31:24)
    at Scanner.module.exports.Scanner.getScanner (/app.asar/node_modules/first-mate/lib/scanner.js:37:31)
    at Scanner.module.exports.Scanner.findNextMatch (/app.asar/node_modules/first-mate/lib/scanner.js:56:22)
    at Rule.module.exports.Rule.findNextMatch (/app.asar/node_modules/first-mate/lib/rule.js:99:28)
    at Rule.module.exports.Rule.getNextTags (/app.asar/node_modules/first-mate/lib/rule.js:155:21)
    at Grammar.module.exports.Grammar.tokenizeLine (/app.asar/node_modules/first-mate/lib/grammar.js:148:44)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/app.asar/src/tokenized-buffer.js:359:27)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/app.asar/src/tokenized-buffer.js:347:19)
    at /app.asar/src/tokenized-buffer.js:329:34)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLinesForRows (/app.asar/src/tokenized-buffer.js:338:10)
    at TokenizedBuffer.module.exports.TokenizedBuffer.bufferDidChange (/app.asar/src/tokenized-buffer.js:280:34)
    at /app.asar/node_modules/text-buffer/lib/text-buffer.js:671:36
    at Set.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/app.asar/node_modules/text-buffer/lib/text-buffer.js:670:33)
    at TextBuffer.module.exports.TextBuffer.applyChange (/app.asar/node_modules/text-buffer/lib/text-buffer.js:664:12)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/app.asar/node_modules/text-buffer/lib/text-buffer.js:877:16)
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:831:14)
    at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1594:26)
    at /app.asar/src/text-editor.js:1155:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/app.asar/src/text-editor.js:2568:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/app.asar/src/text-editor.js:2534:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/app.asar/src/text-editor.js:1153:19)
    at TextEditor.module.exports.TextEditor.insertText (/app.asar/src/text-editor.js:1119:19)
    at /app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/app.asar/src/text-editor-component.js:478:26)
    at /app.asar/src/text-editor-component.js:3:59)
```

### Commands

```
```

### Non-Core Packages

```
centurion-ui 0.5.0 
command-syntax 0.1.4 
language-generic-config 1.3.0 
language-pccminecraft 0.0.0 
```

**Comment by 50Wliu** [comment]
Looking at your package list, this is most likely an issue with language-pccminecraft.  Double-check your regexes because it looks like you have an invalid `?`, `*`, or `+` in one of them.

**Comment by ajwsert** [comment]
I have also been getting this error (The warning popup even took me to this page). It happens when I select Wordpress as file syntax while having the `atom-wordpress-api` package enabled. I reported it to that package's repo at https://github.com/azizur/atom-wordpress-api/issues/16 but the author says the issue isn't with their package.

My report there was for an older version of Atom, but the issue still occurs with v1.19.2. Here is the stack trace:
```
Uncaught Error: target of repeat operator is not specified
D:\PortableApps\Atom\resources\app\node_modules\first-mate\lib\scanner.js:33

Error: target of repeat operator is not specified
    at Scanner.module.exports.Scanner.createScanner (D:\PortableApps\Atom\resources\app\node_modules\first-mate\lib\scanner.js:33:30)
    at Scanner.module.exports.Scanner.getScanner (D:\PortableApps\Atom\resources\app\node_modules\first-mate\lib\scanner.js:39:37)
    at Scanner.module.exports.Scanner.findNextMatch (D:\PortableApps\Atom\resources\app\node_modules\first-mate\lib\scanner.js:58:28)
    at Rule.module.exports.Rule.findNextMatch (D:\PortableApps\Atom\resources\app\node_modules\first-mate\lib\rule.js:98:34)
    at Rule.module.exports.Rule.getNextTags (D:\PortableApps\Atom\resources\app\node_modules\first-mate\lib\rule.js:154:27)
    at Grammar.module.exports.Grammar.tokenizeLine (D:\PortableApps\Atom\resources\app\node_modules\first-mate\lib\grammar.js:164:50)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (D:\PortableApps\Atom\resources\app\src\tokenized-buffer.js:380:33)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (D:\PortableApps\Atom\resources\app\src\tokenized-buffer.js:368:25)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (D:\PortableApps\Atom\resources\app\src\tokenized-buffer.js:224:49)
    at D:\PortableApps\Atom\resources\app\src\tokenized-buffer.js:206:32
    at D:\PortableApps\Atom\resources\app\node_modules\underscore\underscore.js:666:53
```

**Comment by I-am-io** [comment]
Like @ajwsert I also get this error when selecting wordpress syntax provided by the `atom-wordpress-api` package

**Comment by Ben3eeE** [comment]
@I-am-io This is an issue with the `atom-wordpress-api` package. /cc: https://github.com/azizur/atom-wordpress-api/issues/16#issuecomment-324121691

**Comment by tobiasvl** [comment]
I also ended up here, but after an error in my own grammar which I'm developing.

Is there really no way to test a grammar or get a better stacktrace which shows what part of the CSON Atom is having problems with? I have tested all my separate regexes.

**Comment by davidfx** [comment]
Hello, I have this problem right now. Does anyone have a solution?
