### ISSUE TITLE
Uncaught Error: kill EAGAIN

### ISSUE THREAD

**Issue by moseschrist** [atom/atom#14377]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Linux Mint
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: kill EAGAIN

```
At events.js:160

Error: kill EAGAIN
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.kill (internal/child_process.js:392:26)
    at Task.module.exports.Task.terminate (/app.asar/src/task.js:152:25)
    at /app.asar/src/task.js:19:21
    at /app.asar/src/task.js:136:25
    at /app.asar/src/task.js:126:25
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/task.js:78:34)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -1:45.8.0 core:select-up (input.hidden-input)
     -1:45.6.0 core:backspace (input.hidden-input)
     -1:45.4.0 core:save (input.hidden-input)
  2x -1:16.5.0 core:undo (input.hidden-input)
     -1:13.8.0 core:backspace (input.hidden-input)
     -1:13.4.0 core:save (input.hidden-input)
     -1:10.2.0 core:undo (input.hidden-input)
  2x -1:09.0 core:redo (input.hidden-input)
     -1:07.3.0 core:save (input.hidden-input)
     -1:05.8.0 core:undo (input.hidden-input)
     -1:05.1.0 core:save (input.hidden-input)
     -1:03.9.0 find-and-replace:show (input.hidden-input)
     -1:03.3.0 core:confirm (input.hidden-input)
     -1:02.6.0 editor:consolidate-selections (input.hidden-input)
     -1:02.6.0 core:cancel (input.hidden-input)
undefined -0:59 core:move-up (input.hidden-input)
```

### Non-Core Packages

```
ambiance-pro-ui 0.4.1 
atom-beautify 0.29.24 
git-history 3.3.0 
git-plus 7.8.0 
git-time-machine 1.5.9 
line-ending-converter 1.3.2 
merge-conflicts 1.4.4 
split-diff 1.3.0 
symbols-tree-view 0.14.0 
```

**Comment by rsese** [comment]
The stack trace looks identical to the one in https://github.com/atom/atom/issues/14374 so I'm going to close this as a dupe @moseschrist.  If you can answer the questions I asked in https://github.com/atom/atom/issues/14374#issuecomment-300280275, that would be super helpful :bow:
