### ISSUE TITLE
Uncaught TypeError: decorationIterator.getCloseScopeIds is not a function

### ISSUE THREAD

**Issue by smashwilson** [atom/atom#14381]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom is failing to launch and leaving the following stack in the console:

```
<embedded>:112032 Uncaught (in promise) TypeError: decorationIterator.getCloseScopeIds is not a function
    at ScreenLineBuilder.emitDecorationBoundaries (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:213:1)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:121:1)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:630:1)
    at TextEditorPresenter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:1371:1)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLines (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:1378:1)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:123:1)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:266:1)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:198:1)
    at new TextEditorComponent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:172:1)
    at atom-text-editor.TextEditorElement.mountComponent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:203:24)
    at atom-text-editor.TextEditorElement.setModel (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:147:12)
    at atom-text-editor.TextEditorElement.initialize (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:133:12)
    at TextEditor.module.exports.TextEditor.getElement (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3332:1)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:100:1)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:88:1)
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:136:29)
    at Pane.module.exports.Pane.observeActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:259:1)
    at atom-pane.PaneElement.initialize (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:103:41)
    at Pane.module.exports.Pane.getElement (/Applications/Atom.app/Contents/Resources/app/src/pane.js:94:1)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:100:1)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:88:1)
    at atom-pane-container.module.exports.PaneContainerElement.rootChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-container-element.js:41:27)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at PaneContainer.setRoot (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:135:1)
    at PaneContainer.deserialize (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:55:1)
    at WorkspaceCenter.deserialize (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:30:1)
    at Workspace.deserialize (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:414:1)
    at AtomEnvironment.module.exports.AtomEnvironment.deserialize (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1227:1)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:815:1
```

### Steps to Reproduce

Open Atom on a project directory that contains saved state:

```
$ atom .
```

The problem also occurs in safe mode. Using `--clear-window-state` suppresses it for that run, but it reappears immediately afterward.

**Expected behavior:** Atom should launch successfully and display the tree view and background tips, restore saved state, and so on.

**Actual behavior:** Window remains blank and there's an exception in the console.

**Reproduces how often:** 100% on workspaces that were serialized recently (within the last day or so), never on workspaces that I haven't opened for a while.

### Versions

MacOS Sierra, 10.12.4

```
$ atom --version
Atom    : 1.18.0-dev-5d57ecb8c
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
$ apm --version
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.12.2
```

### Additional Information

I'd guess that this is just an incompatible change in the way that editor state is serialized to IndexDB, but I'm suspicious because it reoccurs after a `--clear-window-state`.

**Comment by 50Wliu** [comment]
Renamed the title so that Notifications can detect this as a duplicate.
