### ISSUE TITLE
Uncaught Error: ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by tynarbekov** [atom/atom#14418]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOSPC: no space left on device, write

```
At fs.js:786

Error: ENOSPC: no space left on device, write
    at Error (native)
    at Object.fs.writeSync (fs.js:786:20)
    at Object.fs.writeFileSync (fs.js:1353:24)
    at Object.writeFileSync (/app.asar/node_modules/fs-plus/lib/fs-plus.js:288:17)
    at StyleManager.addStyleSheet (/app.asar/src/style-manager.js:149:12)
    at /app.asar/src/workspace-element.js:62:17)
    at /app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/app.asar/src/config.js:227:14)
    at Workspace.increaseFontSize (/app.asar/src/workspace.js:939:17)
    at /app.asar/src/workspace-element.js:119:20)
```

### Commands

```
  3x -6:39.8.0 core:close (atom-pane.pane.active)
     -5:40.3.0 pane:show-next-recently-used-item (input.hidden-input)
     -5:40.2.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
  4x -3:35.9.0 core:close (input.hidden-input)
     -2:47.2.0 pane:show-next-recently-used-item (input.hidden-input)
     -2:47.1.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -2:43.1.0 pane:show-next-recently-used-item (input.hidden-input)
     -2:42.9.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
  4x -0:58.7.0 core:close (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by jabisr** [comment]
your emulator memory might be full ,Delete data from your emulator audio,video or any huge files, later restart and run.

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/14418#issuecomment-301592437. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
