### ISSUE TITLE
Uncaught error in app/src/item-registry:11 can halt atom loading core components

### ISSUE THREAD

**Issue by RachelScodes** [atom/atom#14454]
Not so much a bug as a suggestion:

line 11 of src/item-registry is the following:
```
 throw new Error("The workspace can only contain one instance of item " + item);
```

If this error is triggered during startup, Atom stops loading core packages and just renders a blank screen. Opening up the console to see an error that just says `"can't have more than one instance of item [object Object]"` isn't really that helpful.

Would it be poor style to console the offending `item` itself, since it is an object? Maybe log the class, or what it is an instance of? Furthermore, why structure the error message this way; when would the `item` *not* be an object? Why have a dynamic error message that will always compile the same, since an object can't be interpolated into the string? 

I added a `console.log(item)` to the compiled .js version of my app, and Atom was able to load, but this would have been easier to debug if I knew what the offending object was in the first place.

**Comment by RachelScodes** [comment]
I was able to follow the stacktrace and figure it out (and get rid of the offending object) eventually

<img width="1280" alt="screen shot 2017-05-17 at 11 30 46 am" src="https://cloud.githubusercontent.com/assets/13145686/26163704/6761a1f6-3af8-11e7-834e-368f50777cbe.png">

I think it came from my autosave script in init.coffee:
```
atom.getCurrentWindow().on 'blur', ->
  @promptForUntitled = atom.config.settings.saveOnBlur.promptForUntitled
  for pane in atom.workspace.getPanes()
    if @promptForUntitled
      pane.saveAllItems()
    else
      for item in pane.items
        if item.buffer
          if item.buffer.file
            pane.saveItem(item)
```

**Comment by ungb** [comment]
I was able to get a repro for the scenario

Repro steps:
1. Open Atom with a project.
2. Rlight Click `Close pane` in the tree-view,  Notice nothing happens
3. right click and remove the project.
4. Tree-view disappears,  Toggle it back open
5. right click and click add folder back
6. Tree view remains empty and if you open dev tools you see:

```
Uncaught (in promise) Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (C:\Users\bryan\AppData\Local\atom\app-1.19.2\resources\app\src\item-registry.js:11:21)
    at PaneContainer.didAddPaneItem (C:\Users\bryan\AppData\Local\atom\app-1.19.2\resources\app\src\pane-container.js:269:29)
    at PaneContainer.didAddPane (C:\Users\bryan\AppData\Local\atom\app-1.19.2\resources\app\src\pane-container.js:242:18)
    at Pane.module.exports.Pane.setContainer (C:\Users\bryan\AppData\Local\atom\app-1.19.2\resources\app\src\pane.js:162:32)
    at PaneContainer.setRoot (C:\Users\bryan\AppData\Local\atom\app-1.19.2\resources\app\src\pane-container.js:137:21)
    at PaneContainer.deserialize (C:\Users\bryan\AppData\Local\atom\app-1.19.2\resources\app\src\pane-container.js:58:16)
    at Dock.deserialize (C:\Users\bryan\AppData\Local\atom\app-1.19.2\resources\app\src\dock.js:374:30)
    at Workspace.deserialize (C:\Users\bryan\AppData\Local\atom\app-1.19.2\resources\app\src\workspace.js:417:40)
    at C:\Users\bryan\AppData\Local\atom\app-1.19.2\resources\app\src\atom-environment.js:1263:35

```
