### ISSUE TITLE
Calling atom via cmd broken with 1.18

### ISSUE THREAD

**Issue by Stanzilla** [atom/atom#14463]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1a. Run atom with `atom --safe`
2a. Observe
1b. Run atom with `atom`
2b. Observe

**Expected behavior:** [What you expect to happen]
Atom in safe mode
**Actual behavior:** [What actually happens]
An empty view and devtools
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions 

Atom    : 1.18.0-beta0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

![atom_2017-05-18_00-40-43](https://cloud.githubusercontent.com/assets/75278/26179315/4c4bf414-3b63-11e7-9337-052bd9db93a6.png)

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

Error log:

```
Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
Error: Cannot find module '../../modules/es6.object.to-string'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (c:\Users\Benjamin\AppData\Local\atom\app-1.18.0-beta0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\Benjamin\AppData\Local\atom\app-1.18.0-beta0\resources\app\src\module-cache.js:350:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\Benjamin\AppData\Local\atom\app-1.18.0-beta0\resources\app\src\native-compile-cache.js:47:27)
    at Object.<anonymous> (C:\Users\Benjamin\AppData\Local\atom\app-1.18.0-beta0\resources\app\node_modules\babel-runtime\node_modules\core-js\library\fn\symbol\index.js:2:1)
    at Module._compile (C:\Users\Benjamin\AppData\Local\atom\app-1.18.0-beta0\resources\app\src\native-compile-cache.js:87:30)
    at Object.value [as .js] (C:\Users\Benjamin\AppData\Local\atom\app-1.18.0-beta0\resources\app\src\compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\Benjamin\AppData\Local\atom\app-1.18.0-beta0\resources\app\src\native-compile-cache.js:47:27)
    at Object.<anonymous> (C:\Users\Benjamin\AppData\Local\atom\app-1.18.0-beta0\resources\app\node_modules\babel-runtime\core-js\symbol.js:1:110)
    at Module._compile (C:\Users\Benjamin\AppData\Local\atom\app-1.18.0-beta0\resources\app\src\native-compile-cache.js:87:30)
    at Object.value [as .js] (C:\Users\Benjamin\AppData\Local\atom\app-1.18.0-beta0\resources\app\src\compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\Benjamin\AppData\Local\atom\app-1.18.0-beta0\resources\app\src\native-compile-cache.js:47:27)
    at Object.<anonymous> (C:\Users\Benjamin\AppData\Local\atom\app-1.18.0-beta0\resources\app\node_modules\babel-runtime\helpers\typeof.js:9:15)
    at Module._compile (C:\Users\Benjamin\AppData\Local\atom\app-1.18.0-beta0\resources\app\src\native-compile-cache.js:87:30)
    at Object.value [as .js] (C:\Users\Benjamin\AppData\Local\atom\app-1.18.0-beta0\resources\app\src\compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\Benjamin\AppData\Local\atom\app-1.18.0-beta0\resources\app\src\native-compile-cache.js:47:27)
```

Launching via the Desktop/Startmenu shortcut works fine and does not cause that error

**Comment by rsese** [comment]
Weird, I just setup a new Windows 10 VM and installed 1.18.0-beta0 and can't reproduce - both `atom` and `atom --safe` work ok for me (in addition to starting them both as you described in your steps to reproduce).

**Comment by Stanzilla** [comment]
Reinstalled via the setup exe and it works again.  ¯\_(ツ)_/¯
