### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by joegreen2** [atom/atom#14494]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:217

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:217:13)
    at undefined.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:113:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:663:1)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:697:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:184:1)
    at /Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1
```

### Commands

```
     -3:57.9.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -3:57.9.0 editor:newline (input.hidden-input)
     -3:57.9.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -3:57.9.0 editor:newline (input.hidden-input)
     -3:57.8.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -3:57.8.0 editor:newline (input.hidden-input)
  2x -3:57.6.0 core:move-up (input.hidden-input)
     -3:56.9.0 core:paste (input.hidden-input)
  6x -3:53.9.0 core:backspace (input.hidden-input)
     -3:43.5.0 core:move-down (input.hidden-input)
     -3:43.1.0 core:backspace (input.hidden-input)
     -3:41.8.0 core:save (input.hidden-input)
  5x -2:39.8.0 core:backspace (input.hidden-input)
     -2:19.9.0 core:save (input.hidden-input)
     -2:01.1.0 core:backspace (input.hidden-input)
     -1:58.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
emmet 2.4.3 
npm-install 4.0.4 
```

**Comment by ungb** [comment]
Hi,  I'm currently trying to get a working repro so we can investigate further.   Are you able to provide any info on repro steps? or any more info on what you were doing when you saw this error?
