### ISSUE TITLE
70410 Uncaught (in promise) Error: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by garygreen** [atom/atom#14509]
On version: 1.17.0 - Windows 10.

I can't seem to click on anything, open projects or style sheet, nothing happens.

This started happening when I added a project and it was taking too long to open so I closed atom, upon reopening this started happening.

Opening atom in safe mode still has the same problem.

```
<embedded>:70410 Uncaught (in promise) Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (C:\Users\garyh\AppData\Local\atom\app-1.17.0\resources\app\src\item-registry.js:11:1)
    at PaneContainer.didAddPaneItem (C:\Users\garyh\AppData\Local\atom\app-1.17.0\resources\app\src\pane-container.js:265:1)
    at PaneContainer.didAddPane (C:\Users\garyh\AppData\Local\atom\app-1.17.0\resources\app\src\pane-container.js:238:1)
    at Pane.module.exports.Pane.setContainer (C:\Users\garyh\AppData\Local\atom\app-1.17.0\resources\app\src\pane.js:149:1)
    at PaneAxis.module.exports.PaneAxis.setContainer (C:\Users\garyh\AppData\Local\atom\app-1.17.0\resources\app\src\pane-axis.js:97:1)
    at PaneContainer.setRoot (C:\Users\garyh\AppData\Local\atom\app-1.17.0\resources\app\src\pane-container.js:134:1)
    at PaneContainer.deserialize (C:\Users\garyh\AppData\Local\atom\app-1.17.0\resources\app\src\pane-container.js:55:1)
    at Dock.deserialize (C:\Users\garyh\AppData\Local\atom\app-1.17.0\resources\app\src\dock.js:373:1)
    at Workspace.deserialize (C:\Users\garyh\AppData\Local\atom\app-1.17.0\resources\app\src\workspace.js:415:1)
    at AtomEnvironment.module.exports.AtomEnvironment.deserialize (C:\Users\garyh\AppData\Local\atom\app-1.17.0\resources\app\src\atom-environment.js:1213:1)
    at C:\Users\garyh\AppData\Local\atom\app-1.17.0\resources\app\src\atom-environment.js:801:1
```

**Comment by garygreen** [comment]
Seems to be related to https://github.com/atom/settings-view/issues/723

**Comment by danigb** [comment]
I know this is related to #723, but I can't find information to solve my issue (and I think @garygreen's too). The problem is that, even in safe mode, I can't open any window. I've tried to disable some plugins using `apm`, but it doesn't work either. So currently I have an editor completely unusable :-(

Any ideas?

Thanks in advance...

**Comment by garygreen** [comment]
If you click 'project' title from the left hand side panel I think it fixes it. I dunno, it's really strange.

**Comment by danigb** [comment]
Thanks @garygreen, but I don't have any left-hand side panel... I don't have any panels, just a black Atom window with the name of the path at the top of the window...

**Comment by faheemmughal** [comment]
Same issue here. Lost work and now it just presents me with blank window
<img width="1292" alt="screen shot 2017-06-16 at 12 04 21" src="https://user-images.githubusercontent.com/5362631/27224243-fa4b92a6-528b-11e7-9de6-1735d2a1f097.png">

Error in developer console is,
<img width="549" alt="screen shot 2017-06-16 at 12 05 21" src="https://user-images.githubusercontent.com/5362631/27224274-203e7ff0-528c-11e7-8608-743c32d8b498.png">

I can open other directories/projects but get stuck on the one I was working on.

**Comment by danigb** [comment]
For me, the source of the problem was that I couldn't install updates. I had to remove seti-syntax/seti-ui package, update atom, and problems solved. Take a look to: https://github.com/atom/atom/issues/13804

Hope it helps.

**Comment by xi-ao** [comment]
@danigb Still having this issue? Try to remove (or rename) your `~/.atom/storage` folder and restart Atom.
It fixed the issue for me. Seems like the problem lies in the session data which gets corrupted somehow.

**Comment by AEgan** [comment]
I just ran into this issue after updating to atom `1.21.0-beta1` and updating some packages I had installed. I resolved the issue by opening atom with the `--clear-window-state` option

**Comment by danigb** [comment]
Thanks @xi-ao for asking, but as I said, I solved it by removing the seti-ui package (with the information from #13804).
