### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Applications/Atom.app/Contents/Resource...

### ISSUE THREAD

**Issue by RmondJone** [atom/atom#14500]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Applications/Atom.app/Contents/Resources/app/Applications/Atom.app/Contents/Resources/app/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/styles/tree-view.less'

```
At /Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:323

Error: ENOENT: no such file or directory, open '/Applications/Atom.app/Contents/Resources/app/Applications/Atom.app/Contents/Resources/app/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/styles/tree-view.less'
  at Error (native)
  at Object.fs.openSync (fs.js:640:18)
  at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
  at Proxy.fs.readFileSync (fs.js:508:33)
  at Proxy.fs.readFileSync (ELECTRON_ASAR.js:501:29)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (<embedded>:20945:56)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (<embedded>:20917:27)
  at <embedded>:68571:60
  at Array.map (native)
  at Package.module.exports.Package.loadStylesheets (<embedded>:68569:65)
  at <embedded>:68163:23
  at Package.module.exports.Package.measure (<embedded>:68125:21)
  at Package.module.exports.Package.finishLoading (<embedded>:68159:25)
  at PackageManager.module.exports.PackageManager.loadAvailablePackage (<embedded>:20302:38)
  at PackageManager.module.exports.PackageManager.loadPackage (<embedded>:20276:27)
  at PackageManager.module.exports.PackageManager.enablePackage (<embedded>:19967:25)
  at HTMLButtonElement.enablementButtonClickHandler (<embedded>:164111:31)

```

### Commands

```
     -3:07.3.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-html-preview 0.1.22 
atom-ternjs 0.18.3 
autocomplete-paths 1.0.5 
autoprefixer 3.7.0 
busy-signal 1.4.1 
color-picker 2.2.5 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.61.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.8.0 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.1.4 
linter-htmlhint 1.3.3 
linter-jshint 3.1.2 
linter-ui-default 1.5.4 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
nuclide 0.228.0 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by stevemao** [comment]
I had the same problem. After I did `apm update` the problem is gone. If you see `undefined`, uninstall [seti](https://github.com/jesseweed/seti-syntax/issues/145) then `apm update` again and reinstall seti.

**Comment by rsese** [comment]
Interesting, so you got the same stack trace @stevemao?  @RmondJone, it looks like you don't have seti-syntax installed but if you run `apm update`, does that fix things up for you?

**Comment by stevemao** [comment]
@rsese yes

**Comment by pgonzalez-santiago** [comment]
Same here

**Comment by stevemao** [comment]
@pgonzalez-santiago does my solution work for you?

**Comment by Heedster** [comment]
Same here, apm update does not seems to work.

**Comment by rsese** [comment]
@pgonzalez-santiago @Heedster - can you try re-installing and see if that helps?

**Comment by Heedster** [comment]
@rsese I did, did not help.

**Comment by rsese** [comment]
Hmm, do you have the same path as reported in the OP @Heedster?  I.e.:

> Uncaught Error: ENOENT: no such file or directory, open '/Applications/Atom.app/Contents/Resources/app/Applications/Atom.app/Contents/Resources/app/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/styles/tree-view.less'

Wondering if you have that same repeating part where there's another "Applications/Atom.app/Contents/Resources/app"?  I just checked my install and the path is:

> /Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/styles/tree-view.less

**Comment by marcos-muniz** [comment]
I have the same problem with the repeated path 
/Applications/Atom.app/Contents/Resources/app/Applications/Atom.app/Contents/Resources/app/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/styles/tree-view.less

**Comment by Heedster** [comment]
> Hmm, do you have the same path as reported in the OP @Heedster? I.e.:

@rsese Yes. Exact same path

**Comment by Heedster** [comment]
<img width="1280" alt="screen shot 2017-06-07 at 9 55 13 am" src="https://user-images.githubusercontent.com/3810492/26862275-8151d2b4-4b67-11e7-96eb-6f2d28ecbf45.png">
If you see the top bar, you can see untitled written twice, i think there is an additional window open there inside atom browser. I am not sure, but I think they are somehow related to this issue. @rsese

**Comment by rsese** [comment]
Though that does look a bit odd (it almost looks like macOS native tabs with only a single tab?), I'm not sure if it's related either.  But can you do me a favor and try temporarily resetting to [factory defaults](http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults) @Heedster (or anyone else hitting this error) and let me know if you still get the error after that?

```
mv ~/.atom ~/.atom-backup
```

**Comment by Heedster** [comment]
@rsese 
Tried that, an error popup does not seem to come after resetting to factory settings, but when I installed nuclide, I saw that tree-view is in disabledPackages in config.cson (as earlier) and removing it from there shows the above error either immediately or on next restart.

This is what my config looks like
```
"*":
  core:
    customFileTypes:
      "source.ini": [
        ".buckconfig"
        ".flowconfig"
        ".hgrc"
      ]
      "source.json": [
        "BUCK.autodeps"
      ]
      "source.python": [
        "BUCK"
      ]
    disabledPackages: [
      "tree-view"
    ]
    telemetryConsent: "limited"
  "exception-reporting":
    userId: "7daf6f39-4db8-4581-84d1-c2cdf3b9cad2"

```

**Comment by stevemao** [comment]
I use nuclide but after `apm update` the error's gone.

**Comment by rsese** [comment]
> but when I installed nuclide, I saw that tree-view is in disabledPackages in config.cson (as earlier) and removing it from there shows the above error either immediately or on next restart.

I haven't played with Nuclide much but I've seen issues that mention it specifically disables tree-view?  Seems to also be mentioned in the documentation:

https://nuclide.io/docs/editor/uninstall/#re-activate-disabled-core-packages

So it seems like tree-view should be disabled if you use Nuclide?

**Comment by ajaysaini-sgvu** [comment]
+1000

**Comment by rsese** [comment]
tree-view is getting disabled automatically if Nuclide is enabeld @ajaysaini-sgvu?   My guess would be that Nuclide is doing that?  

Can I ask why you want tree-view enabled if you're using Nuclide?  I haven't used Nuclide beyond just installing and enabling it, but from poking around it looks like Nuclide replaces the tree-view so I'm not sure why you would want tree-view enabled if you're using Nuclide (let me know if I mis-understood what you were asking though)?

**Comment by ajaysaini-sgvu** [comment]
@rsese Things are getting difficult when I navigate to different file., as there is no project structure or tree-view is there.

**Comment by rsese** [comment]
Sorry I missed your followup @ajaysaini-sgvu - if you have Nuclide enabled and there's no tree view or project view, that sounds like something to ask the Nuclide folks about (again though, I might just be mis-understanding because I don't have much experience using Nuclide).  The message board might be another good place to ask about that too: https://discuss.atom.io/.

For anyone else still seeing this, can you confirm if tree-view is not listed in the `disabledPackages` section of your config.cson file but you have Nuclide enabled?

**Comment by ajaysaini-sgvu** [comment]
@rsese I don't remember how exactly I resolved it. Anyways, I think that I updated Nuclide and Atom then it worked for me.
