### ISSUE TITLE
Uncaught Error: Cannot find module '../node_modules/atom-keymap/lib/command-event.js'

### ISSUE THREAD

**Issue by Pitbullrace** [atom/atom#14528]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module '../node_modules/atom-keymap/lib/command-event.js'

```
At module.js:457

Error: Cannot find module '../node_modules/atom-keymap/lib/command-event.js'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.0/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.0/resources/app/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.17.0/resources/app/static/<embedded>:73:1)
    at get_CommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:22:1)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:607:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -4:25.7.0 core:copy (span.syntax--text.syntax--html.syntax--php)
     -4:18.3.0 project-find:show-in-current-directory (div.header.list-item.project-root-header)
     -4:15.2.0 core:paste (div.line)
     -0:31.7.0 project-find:show-in-current-directory (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```

```

**Comment by Stanzilla** [comment]
try reinstalling, fixed it for me.

**Comment by rsese** [comment]
Thanks @Stanzilla - it looks like some files aren't getting installed in some cases (/cc https://github.com/atom/atom/issues/14461) so let us know if re-installing doesn't fix things for you @Pitbullrace.
