### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by itmozok** [atom/atom#14545]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (C:\Users\Admin\AppData\Local\Atom\app-1.17.0\resources\electron.asar\browser\objects-registry.js:41:28)
    at EventEmitter.<anonymous> (C:\Users\Admin\AppData\Local\Atom\app-1.17.0\resources\electron.asar\browser\rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\Admin\AppData\Local\Atom\app-1.17.0\resources\electron.asar\browser\api\web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At C:\Users\Admin\AppData\Local\Atom\app-1.17.0\resources\electron.asar\renderer\api\remote.js:217

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (~/AppData/Local/Atom/app-1.17.0/resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (~/AppData/Local/Atom/app-1.17.0/resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (~/AppData/Local/Atom/app-1.17.0/resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (~/AppData/Local/Atom/app-1.17.0/resources/electron.asar/renderer/api/remote.js:217:13)
    at undefined.remoteMemberFunction (~/AppData/Local/Atom/app-1.17.0/resources/electron.asar/renderer/api/remote.js:113:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (~/AppData/Local/Atom/app-1.17.0/resources/app/src/atom-environment.js:663:1)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (~/AppData/Local/Atom/app-1.17.0/resources/app/src/atom-environment.js:697:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (~/AppData/Local/Atom/app-1.17.0/resources/app/src/window-event-handler.js:184:1)
    at ~/AppData/Local/Atom/app-1.17.0/resources/app/src/window-event-handler.js:3:1
```

### Commands

```
     -1:28.8.0 intentions:highlight (input.hidden-input)
     -1:28.4.0 core:copy (input.hidden-input)
     -1:28 core:cut (input.hidden-input)
undefined -1:26.6.0 core:move-up (input.hidden-input)
 12x -1:20.1.0 core:move-down (input.hidden-input)
  7x -1:18.2.0 core:move-up (input.hidden-input)
     -1:17 core:move-down (input.hidden-input)
     -1:16.7.0 intentions:highlight (input.hidden-input)
     -1:16.3.0 core:paste (input.hidden-input)
     -1:15.1.0 editor:newline (input.hidden-input)
     -1:14.5.0 core:move-up (input.hidden-input)
     -1:14.3.0 intentions:highlight (input.hidden-input)
     -1:14.1.0 core:save (input.hidden-input)
 11x -1:05.2.0 core:move-up (input.hidden-input)
     -1:02.6.0 intentions:highlight (input.hidden-input)
     -1:02.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
angular-2-typeScript-snippets 0.6.3 
angular-bootstrap 1.0.1 
angularjs 0.4.0 
angularjs-helper 0.10.2 
angularjs-snippets 0.10.18 
autocomplete-angular-material 0.4.0 
autocomplete-js-import 1.4.0 
busy-signal 1.4.1 
intentions 1.1.2 
linter 2.1.4 
linter-htmlhint 1.3.3 
linter-jshint 3.0.3 
linter-ui-default 1.2.4 
minimap 4.28.1 
node-debugger undefined 
pigments 0.39.1 
sync-settings 0.8.1 
```

**Comment by itmozok** [comment]
Too much similar ISSUES.
Closed it.
