### ISSUE TITLE
Uncaught Error: Replacing non-existent child

### ISSUE THREAD

**Issue by kibs** [atom/atom#14616]
[Enter steps to reproduce:]

1. Split pane

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Replacing non-existent child

```
At /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:142

Error: Replacing non-existent child
    at PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:142:1)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app/src/pane.js:948:1)
    at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app/src/pane.js:928:1)
    at atom-pane.pane:split-right (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:255:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:31.3.0 find-and-replace:select-next (input.hidden-input)
     -0:29.6.0 autocomplete-plus:confirm (input.hidden-input)
     -0:28.8.0 core:move-down (input.hidden-input)
     -0:28.5.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:27.9.0 core:copy (input.hidden-input)
     -0:27.5.0 core:move-right (input.hidden-input)
     -0:27.1.0 editor:newline (input.hidden-input)
     -0:26.8.0 core:paste (input.hidden-input)
     -0:26.3.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -0:26.1.0 core:move-right (input.hidden-input)
  2x -0:25.8.0 find-and-replace:select-next (input.hidden-input)
     -0:24.6.0 autocomplete-plus:cancel (input.hidden-input)
  2x -0:24.4.0 editor:consolidate-selections (input.hidden-input)
     -0:24.2.0 core:cancel (input.hidden-input)
     -0:23.6.0 core:save (input.hidden-input)
     -0:04.6.0 pane:split-right (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.24 
atom-soda-dark-ui 1.1.0 
autocomplete-elixir 1.5.14 
autocomplete-paths 1.0.5 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.6 
graphite-ui 0.15.1 
hey-pane 1.0.0 
jumpy 3.1.3 
language-babel 2.62.0 
language-elixir 0.18.0 
language-haml 0.24.4 
language-slim 0.5.0 
language-vue 0.21.2 
monokai 0.24.0 
move-panes 0.2.0 
oceanic-next 1.0.0 
pain-split 1.4.0 
pigments 0.39.1 
prettier-atom 0.31.1 
qolor 0.4.1 
regex-railroad-diagram 0.17.0 
seti-icons 1.5.1 
seti-syntax 1.1.3 
seti-ui 1.8.0 
todo-show 1.11.0 
word-jumper 0.3.0 
```

**Comment by kibs** [comment]
Hmm.. seems like some panes in a project was hidden somehow after upgrading from 1.16 to 1.17, somehow uncovered them, and closed them. Not split pane works again.

**Comment by flxsource** [comment]
@kibs Any information on how you "somehow" uncovered them? I have the same issue that appeared in 1.19

**Comment by kibs** [comment]
@flxsource I think i hit the key shortcuts for closing panes randomly, and then restarted, but can't really remember

**Comment by flxsource** [comment]
@kibs Thanks. Unfortunately that hasn't worked for me.

**Comment by flxsource** [comment]
This problem is recurring for me. Happens whenever I try and split a pane after adding a folder to an empty project.

**Comment by flxsource** [comment]
[Enter steps to reproduce:]

1. Add a folder to the project
2. Split the pane

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Replacing non-existent child

```
At /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:145

Error: Replacing non-existent child
    at PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:145:47)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app/src/pane.js:984:27)
    at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app/src/pane.js:964:25)
    at HTMLElement.pane:split-right (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:255:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:09.0 tree-view:toggle (input.hidden-input)
     -0:06.0 application:add-project-folder (ol.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:02.1.0 pane:split-right (atom-pane.pane.active)
```

### Non-Core Packages

```
busy-signal 1.4.3 
highlight-selected 0.13.1 
intentions 1.1.5 
language-blade 0.34.0 
language-docker 1.1.8 
language-vue 0.23.1 
linter 2.2.0 
linter-php 1.4.0 
linter-phpcs 1.6.7 
linter-sass-lint 1.7.6 
linter-ui-default 1.6.8 
minimap 4.29.6 
minimap-cursorline 0.2.0 
minimap-highlight-selected 4.6.1 
```

**Comment by lzkelley** [comment]
**This is definitely still happening on 1.19.6!**


**Atom**: 1.19.6 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Replacing non-existent child

```
At /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:145

Error: Replacing non-existent child
    at PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:145:47)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app/src/pane.js:984:27)
    at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app/src/pane.js:964:25)
    at HTMLElement.pane:split-right-and-copy-active-item (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:269:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  2x -1:17.4.0 tree-view:toggle (atom-pane.pane.active)
     -1:12.8.0 project-manager:list-projects (atom-pane.pane.active)
     -1:08.2.0 core:move-down (input.hidden-input)
     -1:07.9.0 core:confirm (input.hidden-input)
  2x -1:07.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:37.7.0 pane:split-right-and-copy-active-item (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.5 
atom-html-preview 0.2.2 
atomic-emacs 0.12.1 
bug-report 0.7.1 
busy-signal 1.4.3 
color-picker 2.2.5 
counter 0.3.5 
emmet 2.4.3 
file-icons 2.1.11 
file-watcher 1.2.6 
git-time-machine 1.5.9 
goto-definition 1.3.4 
intentions 1.1.5 
language-cython 0.3.0 
language-latex 1.1.1 
language-restructuredtext 1.1.0 
latex 0.46.0 
linter 2.2.0 
linter-chktex 1.3.1 
linter-flake8 2.2.1 
linter-markdown 5.2.0 
linter-ui-default 1.6.8 
MagicPython 1.0.12 
markdown-scroll-sync 2.1.2 
markdown-writer 2.7.2 
merge-conflicts 1.4.5 
minimap 4.29.6 
minimap-cursorline 0.2.0 
pdf-view 0.59.0 
pretty-json 1.6.4 
project-manager 3.3.5 
python-indent 1.1.0 
rst-preview-pandoc 0.1.12 
Sublime-Style-Column-Selection 1.7.4 
symbols-tree-view 0.14.0 
```

**Comment by rsese** [comment]
@flxsource - `@julian-carpenter` tracked down the issue to the minimap-cursorline package which it looks like you have installed, see https://github.com/atom/atom/issues/15587#issuecomment-328504139 for more details.
