### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 30Error: Cannot call...

### ISSUE THREAD

**Issue by mjarkk** [atom/atom#14612]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.4.16
**OS**: "Arch Linux"
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 30
Error: Cannot call function 'getPosition' on missing remote object 30
    at throwRPCError (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:339:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /usr/lib/electron/resources/electron.asar/renderer/api/remote.js:217

Error: Cannot call function 'getPosition' on missing remote object 30
Error: Cannot call function 'getPosition' on missing remote object 30
    at throwRPCError (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:339:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:217:13)
    at undefined.remoteMemberFunction (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:113:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/usr/lib/atom/src/atom-environment.js:657:28)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/usr/lib/atom/src/atom-environment.js:691:36)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/usr/lib/atom/src/window-event-handler.js:184:35)
    at /usr/lib/atom/src/window-event-handler.js:3:59
```

### Commands

```
  2x -0:23.4.0 core:move-down (input.hidden-input)
     -0:22.9.0 autocomplete-plus:confirm (input.hidden-input)
     -0:22.9.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:21.9.0 autocomplete-plus:confirm (input.hidden-input)
     -0:21.4.0 core:save (input.hidden-input)
  2x -0:17.9.0 core:move-up (input.hidden-input)
     -0:17.5.0 core:move-down (input.hidden-input)
     -0:17.2.0 core:move-up (input.hidden-input)
  2x -0:17 core:move-left (input.hidden-input)
     -0:16.6.0 core:move-up (input.hidden-input)
  2x -0:16.6.0 core:move-left (input.hidden-input)
     -0:16 core:move-right (input.hidden-input)
     -0:15.8.0 core:backspace (input.hidden-input)
     -0:15.3.0 core:save (input.hidden-input)
     -0:13.6.0 core:move-up (input.hidden-input)
     -0:10.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-ui 1.3.10 
aurora-theme 1.2.2 
color-picker 2.2.5 
dark-flat-ui 1.2.4 
gloom 0.4.13 
gruvbox-plus-syntax 1.3.1 
monokai-flat 1.0.1 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
ramda-syntax 1.0.3 
sass-autocompile 0.13.3 
```

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).
