### ISSUE TITLE
Uncaught Error: Could not call remote function 'show'. Check that the function signature is corre...

### ISSUE THREAD

**Issue by Cloner2014** [atom/atom#14658]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 2.4.2 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Could not call remote function 'show'. Check that the function signature is correct. Underlying error: Object has been destroyed
Error: Could not call remote function 'show'. Check that the function signature is correct. Underlying error: Object has been destroyed
    at callFunction (/private/var/folders/qj/9jvhqzh50s72jwbj582fhdl00000gn/T/AppTranslocation/9F47494F-80A9-4EF6-B585-F30F0864F256/d/Learn IDE.app/Contents/Resources/electron.asar/browser/rpc-server.js:226:11)
    at EventEmitter.<anonymous> (/private/var/folders/qj/9jvhqzh50s72jwbj582fhdl00000gn/T/AppTranslocation/9F47494F-80A9-4EF6-B585-F30F0864F256/d/Learn IDE.app/Contents/Resources/electron.asar/browser/rpc-server.js:307:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/private/var/folders/qj/9jvhqzh50s72jwbj582fhdl00000gn/T/AppTranslocation/9F47494F-80A9-4EF6-B585-F30F0864F256/d/Learn IDE.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /private/var/folders/qj/9jvhqzh50s72jwbj582fhdl00000gn/T/AppTranslocation/9F47494F-80A9-4EF6-B585-F30F0864F256/d/Learn IDE.app/Contents/Resources/electron.asar/renderer/api/remote.js:210

Error: Could not call remote function 'show'. Check that the function signature is correct. Underlying error: Object has been destroyed
Error: Could not call remote function 'show'. Check that the function signature is correct. Underlying error: Object has been destroyed
    at callFunction (/private/var/folders/qj/9jvhqzh50s72jwbj582fhdl00000gn/T/AppTranslocation/9F47494F-80A9-4EF6-B585-F30F0864F256/d/Learn IDE.app/Contents/Resources/electron.asar/browser/rpc-server.js:226:11)
    at EventEmitter.<anonymous> (/private/var/folders/qj/9jvhqzh50s72jwbj582fhdl00000gn/T/AppTranslocation/9F47494F-80A9-4EF6-B585-F30F0864F256/d/Learn IDE.app/Contents/Resources/electron.asar/browser/rpc-server.js:307:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/private/var/folders/qj/9jvhqzh50s72jwbj582fhdl00000gn/T/AppTranslocation/9F47494F-80A9-4EF6-B585-F30F0864F256/d/Learn IDE.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/private/var/folders/qj/9jvhqzh50s72jwbj582fhdl00000gn/T/AppTranslocation/9F47494F-80A9-4EF6-B585-F30F0864F256/d/Learn IDE.app/Contents/Resources/electron.asar/renderer/api/remote.js:210:13)
    at undefined.remoteMemberFunction (/private/var/folders/qj/9jvhqzh50s72jwbj582fhdl00000gn/T/AppTranslocation/9F47494F-80A9-4EF6-B585-F30F0864F256/d/Learn IDE.app/Contents/Resources/electron.asar/renderer/api/remote.js:111:18)
    at /app.asar/node_modules/learn-ide/lib/auth.js:119:20
    at CallbacksRegistry.apply (/private/var/folders/qj/9jvhqzh50s72jwbj582fhdl00000gn/T/AppTranslocation/9F47494F-80A9-4EF6-B585-F30F0864F256/d/Learn IDE.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:48:25)
    at EventEmitter.<anonymous> (/private/var/folders/qj/9jvhqzh50s72jwbj582fhdl00000gn/T/AppTranslocation/9F47494F-80A9-4EF6-B585-F30F0864F256/d/Learn IDE.app/Contents/Resources/electron.asar/renderer/api/remote.js:275:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -2:13.3.0 editor:toggle-line-comments (atom-pane.pane.active)
```

### Non-Core Packages

```

```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [learn-ide](https://atom.io/packages/learn-ide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
