### ISSUE TITLE
Uncaught SyntaxError: missing ) after argument list --- resources\app\node_modules\fbjs\lib\resolveImmediate.js

### ISSUE THREAD

**Issue by happycollision** [atom/atom#14678]
1. Launch Atom on my computer.
2. ...
3. Profit!

Seriously, I do not know if this is a "real" issue or not, but the message that popped up said that this was "likely a bug in Atom" and that I could help by reporting it. It did really occur on launch. Here is some additional information that may (or may not) have contributed to it:

I had previously closed Atom with an open window into a .NET solution. So when it opened again, it restored that window and ran Omnisharp and Linter. No files were open on launch.

If I continue to experience this error, I ~will add~ have added more information in the comments below.

I hope this issue is not just garbage, but I did try to search for 'fbjs' and 'resolveImmediate' in your issue tracker, so I hope this is not a dupe.

~Don

**Atom**: 1.18.0-beta2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught SyntaxError: missing ) after argument list

```
At C:\Users\FP_production\AppData\Local\atom\app-1.18.0-beta2\resources\app\node_modules\fbjs\lib\resolveImmediate.js:27

SyntaxError: missing ) after argument list
    at customRequire (~/AppData/Local/atom/app-1.18.0-beta2/resources/app/static/<embedded>:94:47)
    at Object.../node_modules/react-relay/lib/printRelayQuery.js (~/AppData/Local/atom/app-1.18.0-beta2/resources/app/static/<embedded>:321768:24)
    at customRequire (~/AppData/Local/atom/app-1.18.0-beta2/resources/app/static/<embedded>:94:47)
    at RelayQueryRequest.getQueryString (~/AppData/Local/atom/app-1.18.0-beta2/resources/app/node_modules/react-relay/lib/RelayQueryRequest.js:93:28)
    at RelayDefaultNetworkLayer._sendQuery (~/AppData/Local/atom/app-1.18.0-beta2/resources/app/node_modules/react-relay/lib/RelayDefaultNetworkLayer.js:131:30)
    at ~/AppData/Local/atom/app-1.18.0-beta2/resources/app/node_modules/react-relay/lib/RelayDefaultNetworkLayer.js:59:26
    at Array.map (native)
    at RelayDefaultNetworkLayer.sendQueries (~/AppData/Local/atom/app-1.18.0-beta2/resources/app/node_modules/react-relay/lib/RelayDefaultNetworkLayer.js:58:52)
    at RelayNetworkLayer.sendQueries (~/AppData/Local/atom/app-1.18.0-beta2/resources/app/node_modules/react-relay/lib/RelayNetworkLayer.js:93:40)
    at RelayNetworkLayer.instrumentedCallback [as sendQueries] (~/AppData/Local/atom/app-1.18.0-beta2/resources/app/node_modules/react-relay/lib/RelayProfiler.js:130:46)
    at ~/AppData/Local/atom/app-1.18.0-beta2/resources/app/node_modules/react-relay/lib/RelayNetworkLayer.js:128:22
    at tryCallOne (~/AppData/Local/atom/app-1.18.0-beta2/resources/app/node_modules/promise/lib/core.js:37:18)
    at ~/AppData/Local/atom/app-1.18.0-beta2/resources/app/node_modules/promise/lib/core.js:123:21
    at flush (~/AppData/Local/atom/app-1.18.0-beta2/resources/app/node_modules/asap/raw.js:50:35)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-jasmine 0.8.1 
atom-wrap-in-tag 0.6.0 
atom-yeoman 0.3.15 
busy-signal 1.4.1 
change-case 0.6.5 
color-picker 2.2.5 
editorconfig 2.2.2 
emmet 2.4.3 
highlight-selected 0.13.1 
intentions 1.1.2 
language-asp-html 0.3.0 
language-aspx 0.5.0 
language-javascript-jsx 0.3.7 
language-liquid 0.5.1 
language-rspec 0.6.2 
linter 2.1.4 
linter-eslint 8.2.1 
linter-jsonlint 1.3.0 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.0 
markdown-writer 2.6.5 
merge-conflicts 1.4.5 
omnisharp-atom 0.31.2 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
project-manager 3.3.5 
rails-rspec 0.3.2 
react 0.16.2 
rspec 0.3.2 
ruby-test 1.0.2 
split-diff 1.4.0 
sublime-panes 0.2.5 
sync-settings 0.8.1 
tabs-to-spaces 1.0.3 
trailing-spaces 0.4.0 
```

**Comment by happycollision** [comment]
Immediately after writing this issue up, I tried to Pull using the new Git integration and I got a similar error pointing to the exact same file, and same line, but with this message:

Uncaught TypeError: require(...) is not a function

**Comment by happycollision** [comment]
Closing and re-launching seems to have cleared up messages for now. I will leave this issue open in case someone on the team sees it and realizes some sort of problem.

**Comment by rsese** [comment]
Thanks for the report!  And thanks for keeping it updated with your findings, much appreciated.

If it pops up again for you, would be great to know if it's reproducible in safe mode (`atom --safe`).

**Comment by happycollision** [comment]
It didn't the rest of the day. I'll close this issue tomorrow if it doesn't happen again.
