### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 273Error: Cannot cal...

### ISSUE THREAD

**Issue by RenaKunisaki** [atom/atom#14689]
This pops up periodically when I switch focus to another window.

**Atom**: 1.17.2 x64
**Electron**: 1.4.16
**OS**: linux 4.9.30-1-lts
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 273
Error: Cannot call function 'getPosition' on missing remote object 273
    at throwRPCError (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:339:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /usr/lib/electron/resources/electron.asar/renderer/api/remote.js:217

Error: Cannot call function 'getPosition' on missing remote object 273
Error: Cannot call function 'getPosition' on missing remote object 273
    at throwRPCError (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:339:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:217:13)
    at undefined.remoteMemberFunction (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:113:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/usr/lib/atom/src/atom-environment.js:657:28)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/usr/lib/atom/src/atom-environment.js:691:36)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/usr/lib/atom/src/window-event-handler.js:184:35)
    at /usr/lib/atom/src/window-event-handler.js:3:59
```

### Commands

```
     -2:07.0 editor:select-to-end-of-line (input.hidden-input)
     -2:06.3.0 intentions:highlight (input.hidden-input)
     -2:06.2.0 core:copy (input.hidden-input)
     -2:03.6.0 core:move-up (input.hidden-input)
     -2:03.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -2:03.0 intentions:highlight (input.hidden-input)
     -2:03.0 core:paste (input.hidden-input)
  2x -2:02.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -2:01.2.0 intentions:highlight (input.hidden-input)
     -2:01.0 core:save (input.hidden-input)
  2x -2:00.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:39.9.0 editor:newline (input.hidden-input)
     -0:39.6.0 core:backspace (input.hidden-input)
     -0:39.2.0 intentions:highlight (input.hidden-input)
     -0:39.1.0 core:paste (input.hidden-input)
     -0:38.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
autocomplete-glsl 0.2.3 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.63 
autoreload-package-service 0.0.4 
busy-signal 1.4.1 
copy-filename 1.1.0 
flex-tool-bar 0.12.0 
git-history 3.3.0 
git-plus 7.9.2 
git-time-machine 1.5.9 
highlight-selected 0.11.2 
intentions 1.1.2 
language-glsl 2.0.1 
language-lua 0.9.11 
language-mips 0.3.0 
language-opencl 0.1.1 
linter 2.1.4 
linter-glsl 2.1.3 
linter-lua 1.0.4 
linter-opencl 1.0.2 
linter-python 3.1.2 
linter-ui-default 1.6.0 
project-manager 3.3.5 
python-tools 0.6.9 
run 0.0.1 
script-runner 1.8.5 
smart-tab-names 0.3.0 
tab-title 0.3.3 
tool-bar 1.1.0 
tree-view-git-status 1.4.0 
```

**Comment by 50Wliu** [comment]
> Electron: 1.4.16

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

**Comment by RenaKunisaki** [comment]
I'm pretty sure this was installed from the official Arch repository. Or is that an unofficial build?

**Comment by 50Wliu** [comment]
Yep, that's an unofficial build that often mismatches components and is known for causing bugs that do not occur when using an official distribution (see https://bugs.archlinux.org/task/50357 for a discussion on the issue).
