### ISSUE TITLE
Missing bottom bar and no linting, typescript checking

### ISSUE THREAD

**Issue by pete-hotchkiss** [atom/atom#14699]
### Description

I'm no longer seeing a bottom bar at all in Atom - so there is no visible means to see things like branch name, updates etc.

Additionally atom is no longer linting any files, or transpiling the typescript - nor am I able to hit f12 to hot link to a linked file

### Versions

Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

I've treid re-starting atom
cleaning out .atom/storage
rebooting entire machine

**Comment by ungb** [comment]
Hey @pete-hotchkiss, what OS are you running?  can you give us a list of community packages you have installed (run `apm list` in terminal) or any errors you see in dev tools? 

Also a screenshot would be helpful here.

**Comment by pete-hotchkiss** [comment]
of course - this is on Windows 7.

packages listed are

```
├── advanced-open-file@0.16.6
├── atom-beautify@0.29.26
├── atom-import-sort@2.4.0
├── atom-jade@0.3.0
├── atom-jasmine@0.8.1
├── atom-sort-sass@0.2.1
├── atom-typescript@11.0.3
├── atom-wallaby@1.0.17
├── autoclose-html@0.23.0
├── autocomplete-modules@1.6.10
├── better-handlebars@0.1.1
├── busy-signal@1.4.1
├── change-case@0.6.5
├── chester-atom-syntax@0.1.1
├── close-tags@0.6.0
├── colorful-json@1.1.0
├── cssnano@1.1.0
├── cucumber@0.6.0
├── expose@0.14.0
├── file-types@0.5.5
├── git-authors@0.1.0
├── git-control@0.9.0
├── git-line@0.6.0
├── git-log@0.4.1
├── git-plus@7.9.2
├── git-time-machine@1.5.9
├── gulp-control@0.5.0
├── hey-pane@1.0.0
├── hyperclick@0.0.40
├── intentions@1.1.2
├── js-refactor@0.7.5
├── language-html-swig@2.0.1
├── language-nunjucks@4.1.0
├── linter@2.1.4
├── linter-handlebars@2.3.4
├── linter-json-lint@0.1.2
├── linter-sass-lint@1.7.4
├── linter-tslint@1.5.0
├── linter-ui-default@1.6.0
├── logo-file-icons@1.11.0
├── minimap@4.28.2
├── navigate@0.1.17
├── project-viewer@1.1.2
├── refactor@0.11.4
├── svg-preview@0.11.0
├── sync-settings@0.8.1
├── todo-show@1.11.0
└── tree-view-git-status@1.4.0
```

Its literally happened this afternoon - which is bizzare

**Comment by sebilasse** [comment]
@pete-hotchkiss 
All I can say is. it is exactly the same here.

> Additionally atom is no longer linting any files, or transpiling the typescript

**Comment by pete-hotchkiss** [comment]
@sebilasse gremlins in the works ;-)

**Comment by maxbrunsfeld** [comment]
Can you try updating to Atom 1.18? Is this happening in safe mode (`atom --safe`)?

**Comment by sebilasse** [comment]
@maxbrunsfeld Not in Atom (says 1.17.2 is latest). Do I need a `next` flag or so ?

**Comment by nin-jin** [comment]
Same issue:

![](https://habrastorage.org/web/2f4/858/cbc/2f4858cbc3b942f4b7786b46f4a3a925.png)

In console only:

```
~\.atom\packages\atom-typescript\dist\main\typescriptEditorPane.js:86 TypescriptEditorPane.onOpened false
```

tsconfig:

```
{
	"compilerOptions": {
		"target": "ES5",
		"jsx": "react",
		"jsxFactory": "$mol_dom_jsx",
		"experimentalDecorators": true,
		"noImplicitAny": true,
		"suppressImplicitAnyIndexErrors": true,
		"removeComments" : true ,
		"sourceMap" : true ,
		"inlineSources" : true ,
		"declaration" : true
	},
	"include": [
		"**/*.ts"
	],
	"exclude": [
		"node_modules",
		"**/-/*"
	],
	"atom": {
		"rewriteTsconfig": false
	},
	"compileOnSave": false
}
```

**Comment by nin-jin** [comment]
Sometimes Atom crashes and/or freezes.

**Comment by nin-jin** [comment]
While editing, TypescriptServiceClient emits:
```
{"seq":0,"type":"response","command":"occurrences","request_seq":15,"success":false,"message":"No content available."}
```

**Comment by nin-jin** [comment]
Strange path for tsserver:

```
VM822:1 Uncaught Error: ENOENT: no such file or directory, stat 'C:\proj\mam\mol\list\node_modules\typescript\bin\tsserver'
    at Error (native)
    at eval (eval at evaluate (unknown source), <anonymous>:1:9)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at isFile (C:\Users\jin\.atom\packages\atom-typescript\node_modules\resolve\lib\sync.js:10:29)
    at loadAsFileSync (C:\Users\jin\.atom\packages\atom-typescript\node_modules\resolve\lib\sync.js:36:13)
    at loadNodeModulesSync (C:\Users\jin\.atom\packages\atom-typescript\node_modules\resolve\lib\sync.js:75:21)
    at Function.module.exports [as sync] (C:\Users\jin\.atom\packages\atom-typescript\node_modules\resolve\lib\sync.js:27:17)
    at Promise.resolve.then (C:\Users\jin\.atom\packages\atom-typescript\dist\client\clientResolver.js:62:40)
```

Project root: ```C:\proj\mam\```
Editing file: ```C:\proj\mam\mol\list\list.view.ts```

**Comment by thomasfrobieter** [comment]
@pete-hotchkiss Have you solved this meanwhile? 
Same here.. worked yesterday -_-
