### ISSUE TITLE
Uncaught Error: Cannot find module '../node_modules/oniguruma/lib/oniguruma.js'

### ISSUE THREAD

**Issue by nuncio-bitis** [atom/atom#14708]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module '../node_modules/oniguruma/lib/oniguruma.js'

```
At module.js:457

Error: Cannot find module '../node_modules/oniguruma/lib/oniguruma.js'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Users/jparziale/Library/Caches/com.github.atom.ShipIt/update.AUEp9CU/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Users/jparziale/Library/Caches/com.github.atom.ShipIt/update.AUEp9CU/Atom.app/Contents/Resources/app/src/module-cache.js:354:1)
    at Module.require (Users/jparziale/Library/Caches/com.github.atom.ShipIt/update.AUEp9CU/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (/Users/jparziale/Library/Caches/com.github.atom.ShipIt/update.AUEp9CU/Atom.app/Contents/Resources/app/static/<embedded>:73:1)
    at get_OnigRegExp (/Users/jparziale/Library/Caches/com.github.atom.ShipIt/update.AUEp9CU/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:13:1)
    at new Grammar (/Users/jparziale/Library/Caches/com.github.atom.ShipIt/update.AUEp9CU/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:50:1)
    at GrammarRegistry.module.exports.GrammarRegistry.createGrammar (/Users/jparziale/Library/Caches/com.github.atom.ShipIt/update.AUEp9CU/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:202:1)
    at /Users/jparziale/Library/Caches/com.github.atom.ShipIt/update.AUEp9CU/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:121:1
    at parseContents (/Users/jparziale/Library/Caches/com.github.atom.ShipIt/update.AUEp9CU/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:123:1)
    at /Users/jparziale/Library/Caches/com.github.atom.ShipIt/update.AUEp9CU/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:212:1
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-runner 2.7.1 
edm-light-syntax 0.1.2 
gl-dark-syntax 2.2.0 
gl-light-syntax 2.2.0 
highlight-selected 0.13.1 
iplastic-syntax 0.6.0 
language-applescript 0.3.0 
language-arm 1.2.2 
language-assembly 0.7.2 
minimap 4.28.2 
rad-syntax 0.4.0 
run-in-atom 1.0.5 
sepia-light-ui 0.5.0 
sepia-syntax 1.1.0 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.1 
```

**Comment by rsese** [comment]
We've had a few reports of this recently, can you try re-installing and let us know if you still get the same error?

**Comment by bdsexton** [comment]
This just started for me after the Atom 1.18.0 update became available when Atom restarted to finish updating some packages before applying said Atom update. After applying the 1.18.0 update, things seem to have returned to normal.

**Comment by 50Wliu** [comment]
Thanks for the info @bdsexton.  Here's my theory on what's happening: when you restarted Atom, that triggered both the package updates _and_ the Atom update.  That causes a race condition as Atom reopens while the upgrade process hasn't finished yet (you can see in this in the stack trace above as it's showing Squirrel paths instead of the usual Applications path).  To tie everything together, there's a [Squirrel.Mac bug](https://github.com/Squirrel/Squirrel.Mac/issues/124) where things tend to go kaboom when starting the program before the update completes.

Thoughts @rsese?

**Comment by rsese** [comment]
You have a way deeper understanding of Atom than me @50Wliu but beyond that, the pieces of your theory seem to fit?  @nuncio-bitis do you happen to remember if Atom was updating when you hit the error?

**Comment by tschf** [comment]
Just had this error prop up in the following situation:

Had Atom open

Ran the update through [umake](https://github.com/ubuntu/ubuntu-make) (I'm on Ubuntu x64)

```
$ umake ide atom
Atom is already installed on your system, do you want to reinstall it anyway? [Yes (y)/No (N)] y
Choose installation path: /home/trent/.local/share/umake/ide/atom
Downloading and installing requirements                                        |
100% |#########################################################################|
Installing Atom
|##############################################################################|
Installation done
```

Reloaded the window (View -> Developer -> Reload Window)

(error appears now).

Version before upgrade: 1.17.2
Version after upgrade: 1.18.0

Closed Atom completely and re-opened Atom, the issue was gone.

Hope it helps.
