### ISSUE TITLE
Not able to install Atom

### ISSUE THREAD

**Issue by nkafle89** [atom/atom#14717]
While installing the atom following error occurs. How can this be fixed?

index.js:87 Error: EPERM: operation not permitted, open 'C:\Users\nk28828\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\imports.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Proxy.writeFileSync (C:\Users\nk28828\AppData\Local\atom\app-1.17.2\resources\app\node_modules\fs-plus\lib\fs-plus.js:295:1)
    at LessCache.module.exports.LessCache.writeJson (C:\Users\nk28828\AppData\Local\atom\app-1.17.2\resources\app\node_modules\less-cache\lib\less-cache.js:212:1)
    at LessCache.module.exports.LessCache.setImportPaths (C:\Users\nk28828\AppData\Local\atom\app-1.17.2\resources\app\node_modules\less-cache\lib\less-cache.js:161:1)
    at new LessCache (C:\Users\nk28828\AppData\Local\atom\app-1.17.2\resources\app\node_modules\less-cache\lib\less-cache.js:68:1)
    at new LessCompileCache (C:\Users\nk28828\AppData\Local\atom\app-1.17.2\resources\app\src\less-compile-cache.js:21:1)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\nk28828\AppData\Local\atom\app-1.17.2\resources\app\src\theme-manager.js:283:1)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (C:\Users\nk28828\AppData\Local\atom\app-1.17.2\resources\app\src\theme-manager.js:271:1)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (C:\Users\nk28828\AppData\Local\atom\app-1.17.2\resources\app\src\theme-manager.js:191:1)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (C:\Users\nk28828\AppData\Local\atom\app-1.17.2\resources\app\src\theme-manager.js:252:1)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (C:\Users\nk28828\AppData\Local\atom\app-1.17.2\resources\app\src\theme-manager.js:248:1)
    at AtomEnvironment.module.exports.AtomEnvironment.initialize (C:\Users\nk28828\AppData\Local\atom\app-1.17.2\resources\app\src\atom-environment.js:336:1)
    at module.exports (C:\Users\nk28828\AppData\Local\atom\app-1.17.2\resources\app\src\initialize-application-window.js:144:1)
    at setupWindow (file:///C:/Users/nk28828/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:106:12)
    at window.onload (file:///C:/Users/nk28828/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:67:9)

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Remove the `C:\Users\nk28828\.atom` folder and try again.
