### ISSUE TITLE
Uncaught TypeError: Cannot read property 'update' of undefined

### ISSUE THREAD

**Issue by mitzkia** [atom/atom#14715]
I got this issue while trying to reproduce the following issues
* #14714 
* https://github.com/steelbrain/linter-ui-default/issues/345

[Enter steps to reproduce:]

1. There was opened several tabs
2. Used the "Close all tabs" option to close all of the tabs.

**Atom**: 1.19.0-dev-60c1b85ed x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'update' of undefined

```
At /home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:3434

TypeError: Cannot read property 'update' of undefined
    at LinesTileComponent.updateLines (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:3434:28)
    at LinesTileComponent.update (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:3314:20)
    at updateComponent (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/node_modules/etch/lib/patch.js:52:19)
    at patch (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/node_modules/etch/lib/patch.js:16:25)
    at updateChildren (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/node_modules/etch/lib/patch.js:18:15)
    at Object.updateSync (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/node_modules/etch/lib/component-helpers.js:108:26)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:354:16)
    at TextEditorComponent.updateSync (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:256:16)
    at etch.getScheduler.updateDocument (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:209:46)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/view-registry.js:187:15)
    at /home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -1:36.3.0 core:copy (div.line.highlight-line-multi-line-solid-top)
     -1:28.8.0 tabs:close-all-tabs (div.title)
     -0:44.5.0 core:paste (div.lines)
     -0:41.9.0 tabs:close-all-tabs (div.title)
     -0:29.7.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:27.6.0 core:paste (div.lines)
```

### Non-Core Packages

```
atom-ctags 5.1.0 
atom-material-syntax 1.0.6 
busy-signal 1.4.1 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-syslog-ng 0.0.6 
linter 2.1.4 
linter-pylama 0.8.20 
linter-ui-default 1.6.0 
python-isort 0.0.7 
seti-ui 1.8.0 
sort-lines 0.14.0 
split-diff 1.4.0 
symbols-tree-view 0.14.0 
```

**Comment by mitzkia** [comment]
Ok, I think I have a fix reproduction, but can not reproduce with --safe mode.

```
Atom    : 1.19.0-dev-60c1b85ed
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

1, atom was started from command line: `./atom`
2, create a new empty page with: File -> New file
3, From the following website [https://syslog-ng.gitbooks.io/getting-started/content/chapters/chapter_5/section_2.html](url) I copied the following snippet (from "Example: Java file" section):
```
Javaimport org.syslog_ng.*;

import java.io.*;
```
4, Pasted the snippet into the empty page with right menu (using the mouse)

With this reproduction steps, I can reproduce it in every time.

I hope it helps

**Comment by rsese** [comment]
Thanks again for reporting but similarly to https://github.com/atom/atom/issues/14714, since this isn't reproducible in safe mode, it's likely that the issue is caused by a community package.  If you disable all your community packages and then re-enable them 1 at a time, that should help pinpoint which package is causing the error.  

Since you hit these errors while investigating a linter-related issue, I might even start by disabling those packages first and then see if you can still reproduce.

**Comment by mitzkia** [comment]
Thanks for the help. For now, I tried to enable community packages one by one, and it seem the "linter-ui-default" cause the problem. I will report it there. Thanks again.
