### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 4Error: Cannot call ...

### ISSUE THREAD

**Issue by flycal6** [atom/atom#14723]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.4.16
**OS**: linux 4.11.3-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 4
Error: Cannot call function 'getPosition' on missing remote object 4
    at throwRPCError (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:339:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /usr/lib/electron/resources/electron.asar/renderer/api/remote.js:217

Error: Cannot call function 'getPosition' on missing remote object 4
Error: Cannot call function 'getPosition' on missing remote object 4
    at throwRPCError (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:339:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:217:13)
    at undefined.remoteMemberFunction (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:113:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/usr/lib/atom/src/atom-environment.js:657:28)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/usr/lib/atom/src/atom-environment.js:691:36)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/usr/lib/atom/src/window-event-handler.js:184:35)
    at /usr/lib/atom/src/window-event-handler.js:3:59
```

### Commands

```
     -1:08.0 autoclose-html:close-and-complete (input.hidden-input)
  4x -1:06.1.0 core:select-right (input.hidden-input)
     -1:04.6.0 intentions:highlight (input.hidden-input)
     -1:04.4.0 core:cut (input.hidden-input)
     -1:03.7.0 core:move-down (input.hidden-input)
     -1:02.7.0 editor:move-to-first-character-of-line (input.hidden-input)
     -1:01.6.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -1:00.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:59.9.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:59.9.0 editor:newline (input.hidden-input)
     -0:59.2.0 intentions:highlight (input.hidden-input)
     -0:58.4.0 core:paste (input.hidden-input)
     -0:56.2.0 snippets:previous-tab-stop (input.hidden-input)
     -0:56.2.0 editor:outdent-selected-rows (input.hidden-input)
     -0:55.2.0 intentions:highlight (input.hidden-input)
     -0:55 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-django 0.3.2 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
aurora-theme 1.2.2 
autoclose-html 0.23.0 
autocomplete-java 1.2.7 
busy-signal 1.4.1 
colorblind-wombat-dark-syntax 0.6.0 
emmet 2.4.3 
file-icons 2.1.7 
intentions 1.1.2 
linter 2.1.4 
linter-bootlint 1.0.4 
linter-htmlhint 1.3.3 
linter-javac 1.9.4 
linter-python-pep8 0.2.0 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.0 
nord-atom-ui 0.11.0 
orbit-syntax 0.1.1 
paper-flat-ui 1.3.6 
python-indent 1.0.3 
ramda-syntax 1.0.4 
```

**Comment by 50Wliu** [comment]
> Electron: 1.4.16

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).
