### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'remove' on 'Element': The node to be removed is no lon...

### ISSUE THREAD

**Issue by mabels** [atom/atom#14744]
[Enter steps to reproduce:]

1. vim mode cw

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught NotFoundError: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:854

Error: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at Error (native)
    at vim-normal-mode-input.VimNormalModeInputElement.removePanel (<anonymous>:60:12)
    at vim-normal-mode-input.VimNormalModeInputElement.confirm (<anonymous>:46:6)
    at <anonymous>:33:10
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:701:1)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:685:1)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:574:1)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:480:1)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1127:1
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1166:1
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:849:1)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1599:1)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1160:1
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2577:1)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2539:1)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1158:1)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1124:1)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:480:1)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:3:1)
```

### Commands

```
  2x -0:40.3.0 blur (input.hidden-input)
     -0:40.1.0 core:confirm (input.hidden-input)
  9x -0:40.1.0 blur (input.hidden-input)
     -0:34.6.0 find-and-replace:show (input.hidden-input)
  3x -0:34.6.0 blur (input.hidden-input)
     -0:32.3.0 core:confirm (input.hidden-input)
  2x -0:32.3.0 blur (input.hidden-input)
     -0:31.4.0 editor:consolidate-selections (input.hidden-input)
     -0:31.4.0 core:cancel (input.hidden-input)
  5x -0:31.4.0 blur (input.hidden-input)
  6x -0:31.2.0 vim-mode:move-left (input.hidden-input)
     -0:06.2.0 vim-mode:delete (input.hidden-input)
     -0:06.0 vim-mode:find (input.hidden-input)
  6x -0:06.0 blur (input.hidden-input)
     -0:05.2.0 vim-mode:reset-normal-mode (input.hidden-input)
  2x -0:00.0 blur (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-typescript 11.0.3 
build-cargo 2.0.0 
busy-signal 1.4.1 
console-panel 0.2.1 
ex-mode 0.15.0 
git-control 0.9.0 
git-plus 7.9.2 
git-status 0.3.4 
hex 0.6.2 
intentions 1.1.2 
language-rust 0.4.10 
linter 2.1.4 
linter-rubocop 2.1.1 
linter-ui-default 1.6.0 
nucleus-dark-ui 0.12.3 
nuclide 0.230.0 
particle-dev-exception-reporting 0.36.1 
particle-dev-profiles 0.1.15 
particle-dev-release-notes 0.53.2 
particle-offline-compiler 0.1.3 
platomformio 0.7.1 
racer 0.20.0 
rubocop-auto-correct 1.5.1 
ruby-block 0.3.6 
tool-bar 1.1.0 
vim-mode 0.66.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [vim-mode](https://github.com/atom/vim-mode) package, not Atom itself.  Additionally, the vim-mode package is [deprecated](https://github.com/atom/vim-mode/tree/7b9c7d4553fbb2213c601fc08ee528ab67b5de08#current-status---deprecated-in-favor-of-vim-mode-plus) in favor of [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) so you may want to check out that package.
