### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.44.105.53:80

### ISSUE THREAD

**Issue by monicasenapati** [atom/atom#14741]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.44.105.53:80

```
At stream.js:74

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.44.105.53:80
    at ClientRequest.onError (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/tunnel-agent/index.js:177:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -7:56.5.0 core:save (input.hidden-input)
  2x -4:18.3.0 autocomplete-plus:activate (input.hidden-input)
     -3:55.6.0 find-and-replace:show (input.hidden-input)
     -3:50.1.0 core:confirm (input.hidden-input)
 17x -3:48.9.0 core:backspace (input.hidden-input)
     -3:41.4.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -2:41.9.0 command-palette:toggle (input.hidden-input)
     -2:34.7.0 core:confirm (input.hidden-input)
 24x -2:34 core:backspace (input.hidden-input)
     -1:49.7.0 settings-view:install-packages-and-themes (input.hidden-input)
     -1:44.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
refactor 0.11.4 
```

**Comment by rsese** [comment]
Thanks for the report!  Based on other reports, this seems like a transient networking issue - I'll go ahead and close as a dupe for now (/cc https://github.com/atom/atom/issues/14019) but if you get this error consistently and can reproduce, please let us know @monicasenapati :v:
