### ISSUE TITLE
Uncaught Error: EMFILE: too many open files, open '~/Desktop/rocketchat/Rocket.Chat.Federation/ts...

### ISSUE THREAD

**Issue by madguy02** [atom/atom#14775]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EMFILE: too many open files, open '/home/madguy02/Desktop/rocketchat/Rocket.Chat.Federation/tsmatrixserverlib/resolve.ts'

```
At /home/andrei/atom-1.11.1/out/app/node_modules/tree-view/lib/file.coffee:26539

Error: EMFILE: too many open files, open '/home/madguy02/Desktop/rocketchat/Rocket.Chat.Federation/tsmatrixserverlib/resolve.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Proxy.writeFileSync (/opt/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:295:1)
    at File.module.exports.File.writeFileSync (/opt/atom/resources/app/node_modules/pathwatcher/lib/file.js:289:1)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/opt/atom/resources/app/node_modules/pathwatcher/lib/file.js:467:1)
    at File.module.exports.File.writeSync (/opt/atom/resources/app/node_modules/pathwatcher/lib/file.js:384:1)
    at TextBuffer.module.exports.TextBuffer.saveAs (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1127:1)
    at TextBuffer.module.exports.TextBuffer.save (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:1)
    at TextEditor.module.exports.TextEditor.save (/opt/atom/resources/app/src/text-editor.js:925:1)
    at Pane.module.exports.Pane.saveItem (/opt/atom/resources/app/src/pane.js:780:1)
    at Pane.saveItem (/opt/atom/resources/app/src/pane.js:3:1)
    at Pane.module.exports.Pane.saveActiveItem (/opt/atom/resources/app/src/pane.js:763:1)
    at Workspace.saveActivePaneItem (/opt/atom/resources/app/src/workspace.js:1498:1)
    at atom-workspace.core:save (/opt/atom/resources/app/src/register-default-commands.js:236:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:265:1)
    at /opt/atom/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
 21x -7:24.9.0 core:backspace (input.hidden-input)
     -7:20.7.0 editor:newline (input.hidden-input)
  7x -7:17.2.0 core:backspace (input.hidden-input)
     -6:30.2.0 editor:newline (input.hidden-input)
  2x -6:05.1.0 core:backspace (input.hidden-input)
 12x -5:59.6.0 core:move-left (input.hidden-input)
 13x -5:55.8.0 core:move-right (input.hidden-input)
  5x -4:46 core:backspace (input.hidden-input)
  2x -4:42.4.0 autocomplete-plus:confirm (input.hidden-input)
     -0:53 core:move-right (input.hidden-input)
  4x -0:43.8.0 core:move-left (input.hidden-input)
     -0:39.5.0 core:backspace (input.hidden-input)
     -0:37 core:move-right (input.hidden-input)
     -0:36.4.0 core:backspace (input.hidden-input)
  2x -0:31.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-typescript 11.0.3 
linter 1.11.18 
linter-gcc 0.7.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

Also, do you remember about how many files you had opened when you saw the error?

**Comment by madguy02** [comment]
using the atom text-editor(reading some code)
no,the error is not reproducible right now,it appeared as a pop up on the screen.

around 6-7 files were open from a project.

**Comment by madguy02** [comment]
@rsese

**Comment by rsese** [comment]
Thanks for confirming @madguy02 - I haven't seen any other reports recently so we'll go ahead and close for now but if you or anyone else hits this again we can re-open.
