### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 0)

### ISSUE THREAD

**Issue by jcfuhrmann** [atom/atom#14774]
[Enter steps to reproduce:]

1. ...opened Atom, first use after installation with several packages: { highlight-selected, file-icons, babel, autocomplete modules, emmet, swackets, git-plus, remote-edit }
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 0)

```
At /home/andrei/atom-1.11.1/out/app/node_modules/tree-view/lib/file.coffee:70727

TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (/opt/atom/resources/app/node_modules/text-buffer/lib/point.js:63:1)
    at DisplayLayer.translateScreenPosition (/opt/atom/resources/app/node_modules/text-buffer/lib/display-layer.js:331:1)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateScreenPosition (/opt/atom/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:163:1)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (/opt/atom/resources/app/node_modules/text-buffer/lib/display-marker.js:154:1)
    at /opt/atom/resources/app/src/cursor.js:72:1
    at Cursor.module.exports.Cursor.changePosition (/opt/atom/resources/app/src/cursor.js:684:1)
    at Cursor.module.exports.Cursor.setScreenPosition (/opt/atom/resources/app/src/cursor.js:70:1)
    at /opt/atom/resources/app/src/text-editor.js:1907:1
    at TextEditor.module.exports.TextEditor.moveCursors (/opt/atom/resources/app/src/text-editor.js:2130:1)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/opt/atom/resources/app/src/text-editor.js:1906:1)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/opt/atom/resources/app/src/text-editor-component.js:733:1)
    at HTMLDivElement.<anonymous> (/opt/atom/resources/app/src/text-editor-component.js:3:1)
```

### Commands

```
```

### Non-Core Packages

```
an-old-hope-syntax 1.0.4 
autocomplete-modules 1.6.10 
emmet 2.4.3 
file-icons 2.1.7 
git-plus 7.9.3 
highlight-selected 0.13.1 
language-babel 2.65.1 
remote-edit 1.9.0 
robin-hood-syntax 1.0.0 
swackets 0.26.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Just to confirm since you hit the error initially after installing those packages, you no longer see the error now when starting Atom?

**Comment by jcfuhrmann** [comment]
After the first instance, closed and reopened, it seems to be working alright.

**Comment by rsese** [comment]
Thanks for confirming @jcfuhrmann - I have a 16.04 Ubuntu VM so I'll try to reproduce by installing the packages you mentioned when I get a chance.

**Comment by ScorpIan555** [comment]
I am also running Ubuntu 16.04 (still new to Linux so apologies for my imprecision):

Did my periodic apt update && apt upgrade -y && apt autremove -y 


Uncaught TypeError: Invalid Point: (NaN, 0)
/home/andrei/atom-1.11.1/out/app/node_modules/tree-view/lib/file.coffee:70727

Hide Stack Trace
```
TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (/opt/atom/resources/app/node_modules/text-buffer/lib/point.js:63:1)
    at DisplayLayer.translateScreenPosition (/opt/atom/resources/app/node_modules/text-buffer/lib/display-layer.js:331:1)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateScreenPosition (/opt/atom/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:163:1)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (/opt/atom/resources/app/node_modules/text-buffer/lib/display-marker.js:154:1)
    at /opt/atom/resources/app/src/cursor.js:72:1
    at Cursor.module.exports.Cursor.changePosition (/opt/atom/resources/app/src/cursor.js:684:1)
    at Cursor.module.exports.Cursor.setScreenPosition (/opt/atom/resources/app/src/cursor.js:70:1)
    at /opt/atom/resources/app/src/text-editor.js:1907:1
    at TextEditor.module.exports.TextEditor.moveCursors (/opt/atom/resources/app/src/text-editor.js:2130:1)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/opt/atom/resources/app/src/text-editor.js:1906:1)
```
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/opt/atom/resources/app/src/text-editor-component.js:733:1)
    at HTMLDivElement.<anonymous> (/opt/atom/resources/app/src/text-editor-component.js:3:1)
This is likely a bug in Atom. This issue has already been reported.
View Issue

**Comment by ScorpIan555** [comment]
Also, closing/re-opening did the trick, the only "surprise" was that it did not reopen the files I was working with (no big deal, no data loss, etc).

I'd also point out, in defense of Atom (which I love), this was probably my fault for being a jackass and running update/upgrade/autoremove with programs and files open (in my defense: 1st thing in the AM, total impulse move).

**Comment by rsu611** [comment]
Hi, im on windows 7 here, since the problem persisted throw variuos atom restarts and, each time i tried to select an opened file (.js) through the tab the file was empty and i received another cascade of errors, i fix everything by closing the command prompt i started atom from, reopen it and start with "atom .", so there were no tab nor projects, i readded project folder and   reopened my .js file (the one that shouldn't be empty) and the file and all lines were ok, plus i got no error messages.

**Comment by jmurowaniecki** [comment]
1. Cloning client repository;
2. Opening Atom from console `atom .`;
3. Disabling `Exclude VCS Ignore Paths` option and restart Atom;
4. :boom:;

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 0)

```
At /usr/share/atom/resources/app/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (/usr/share/atom/resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at DisplayLayer.translateScreenPosition (/usr/share/atom/resources/app/node_modules/text-buffer/lib/display-layer.js:331:17)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateScreenPosition (/usr/share/atom/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:163:38)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (/usr/share/atom/resources/app/node_modules/text-buffer/lib/display-marker.js:154:58)
    at /usr/share/atom/resources/app/src/cursor.js:72:37
    at Cursor.module.exports.Cursor.changePosition (/usr/share/atom/resources/app/src/cursor.js:684:13)
    at Cursor.module.exports.Cursor.setScreenPosition (/usr/share/atom/resources/app/src/cursor.js:70:25)
    at /usr/share/atom/resources/app/src/text-editor.js:1907:29
    at TextEditor.module.exports.TextEditor.moveCursors (/usr/share/atom/resources/app/src/text-editor.js:2130:15)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/usr/share/atom/resources/app/src/text-editor.js:1906:25)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/usr/share/atom/resources/app/src/text-editor-component.js:733:31)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/src/text-editor-component.js:3:65)
```

### Commands

```
     -0:58.2.0 core:close (atom-pane.pane.active)
```

### Non-Core Packages

```
aligner 1.2.3 
aligner-javascript 1.2.0 
aligner-php 1.1.1 
busy-signal 1.4.3 
intentions 1.1.2 
linter 2.0.0 
linter-phpcs 1.6.7 
linter-ui-default 1.6.2 
```

**Comment by shellbryson** [comment]
Atom just reported this for me too. Occurred when trying to drag an already open document to create a new "split". On dragging, rather than the usual visual highlight to indicate where the document could be dropped, Atom appeared to stutter then threw the attached errors.

![screen shot 2017-07-27 at 17 26 27](https://user-images.githubusercontent.com/1268036/28681341-0f4084e8-72f1-11e7-8a3a-f8470b9abc8d.png)

**Comment by binarykitchen** [comment]
Think cause is the minimap plugin

**Comment by desmondw** [comment]
I saw this error occur when I used the cmd-p project search as a 'go to line' function but accidentally typed two colons instead of one (::1186 instead of :1186). Able to duplicate consistently.

@binarykitchen I disabled the minimap extension and was still able to produce the error. I didn't uninstall it or restart atom

**Comment by rsese** [comment]
> I saw this error occur when I used the cmd-p project search as a 'go to line' function but accidentally typed two colons instead of one (::1186 instead of :1186). Able to duplicate consistently

Thanks a lot @desmondw, I can reproduce with these steps - I'll update the issue body.

**Comment by rsese** [comment]
> I saw this error occur when I used the cmd-p project search as a 'go to line' function but accidentally typed two colons instead of one (::1186 instead of :1186). Able to duplicate consistently

Oh it looks like this is already reported in the fuzzy finder repo:

https://github.com/atom/fuzzy-finder/issues/308

Not sure if it's the same underlying problem as the error in this issue since https://github.com/atom/fuzzy-finder/issues/308 is reproducible, I'll ask the team to take a look at that one.

**Comment by rsese** [comment]
Copying over from https://github.com/atom/atom/issues/16674 -

---

Sorry I didn't follow all the steps in the guide, but I'm working and cannot make much debug.

It's a week or so I'm getting this kind of error:
`Uncaught TypeError: Invalid Point: (?, NaN)`

I'm moving cursor in a PHP file, after a global search (not immediately after), and in **some** files the found words are not correctly highlited (1 to 8 char BEFORE the actual occurrence, with much variance), and the cursor position on **some** lines (not only those with results) is ugly: moving to first char of line gets the cursor "inside" the first tab (i'm using 4 char, HARD tab), moving to last char of line gets the cursor somewhere but NOT on last char.

In the following screenshot, you can see the cursor in both first and last char on line 18: the real char are "18:2" and "18:45", while they should be "18:1" and "18:48", so it looks like the "hard tab" are lost:
![atom_editor_2018-02-02](https://user-images.githubusercontent.com/3191008/35750706-3281ca2a-0856-11e8-9776-3afd8914db33.jpg)

After some cursor moves on those buffers, I get the "Invalid Point" error.
No other messages in the dev tools.

I think that the only "non standard" thing to underline is that the project I'm workin now is in "latin1" using .editorconfig
```
root = true
[*]
end_of_line = crlf
charset = latin1

```
Default "File Encoding" is now set to "UTF-8" but I had same problem when set to ISO-8859-1, and I'm quite sure I had same issue while working on a complete UTF-8 project.

"php-integrator" is linting with last php7.2 binaries on Windows

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version [Actually "Windows 10 Pro x64 build 1709"]
**Thrown From**: Atom Core

### Stack Trace 1

Uncaught TypeError: Invalid Point: (581, NaN)

```
At C:\Program Files\Atom x64\resources\app\node_modules\text-buffer\lib\text-buffer.js:948

TypeError: Invalid Point: (581, NaN)
    at Function.module.exports.Point.assertValid (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at DisplayLayer.translateScreenPosition (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/display-layer.js:347:17)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateScreenPosition (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:163:38)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/display-marker.js:154:58)
    at changePosition (C:/Program Files/Atom x64/resources/app/src/cursor.js:68:25)
    at Cursor.changePosition (C:/Program Files/Atom x64/resources/app/src/cursor.js:713:11)
    at Cursor.setScreenPosition (C:/Program Files/Atom x64/resources/app/src/cursor.js:67:16)
    at Cursor.moveLeft (C:/Program Files/Atom x64/resources/app/src/cursor.js:288:18)
    at moveCursors.cursor (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2539:52)
    at Array.forEach (native)
    at transact (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2681:31)
    at TextBuffer.module.exports.TextBuffer.transact (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/text-buffer.js:941:24)
    at TextEditor.transact (C:/Program Files/Atom x64/resources/app/src/text-editor.js:1811:30)
    at TextEditor.moveCursors (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2680:23)
    at TextEditor.moveLeft (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2539:23)
    at TextEditor.core:move-left (C:/Program Files/Atom x64/resources/app/src/register-default-commands.js:324:27)
    at HTMLElement.newCommandListeners.(anonymous function) (C:/Program Files/Atom x64/resources/app/src/register-default-commands.js:665:38)
    at CommandRegistry.handleCommandEvent (C:/Program Files/Atom x64/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:/Program Files/Atom x64/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:/Program Files/Atom x64/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (C:/Program Files/Atom x64/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:26.8.0 core:paste (input.hidden-input)
  3x -0:25.7.0 intentions:highlight (input.hidden-input)
  2x -0:25.4.0 core:undo (input.hidden-input)
     -0:23.6.0 intentions:highlight (input.hidden-input)
     -0:23.4.0 core:undo (input.hidden-input)
     -0:20.2.0 editor:move-to-first-character-of-line (input.hidden-input)
  3x -0:19.8.0 core:move-up (input.hidden-input)
     -0:19 core:move-right (input.hidden-input)
     -0:18.6.0 core:select-down (input.hidden-input)
     -0:17.6.0 core:move-up (input.hidden-input)
     -0:17.2.0 core:move-right (input.hidden-input)
     -0:16.8.0 core:move-down (input.hidden-input)
 10x -0:16.1.0 core:move-right (input.hidden-input)
     -0:13.2.0 core:move-left (input.hidden-input)
  4x -0:12.8.0 core:move-right (input.hidden-input)
  2x -0:11.2.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.7.2 
atom-minify 0.8.0 
autoclose-html 0.23.0 
autocomplete-ionic2-framework 0.3.2 
busy-signal 1.4.3 
config-import-export 0.3.1 
custom-title 1.0.1 
docblockr 0.13.6 
double-click-tree-view 1.1.0 
editor-settings 1.1.3 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.16 
git-plus 7.10.0 
grammar-token-limit 0.1.1 
hyperclick 0.0.0 
intentions 1.1.5 
linter 2.2.0 
linter-htmlhint 1.4.0 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
minimap 4.29.7 
php-debug 0.2.6 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.2 
php-integrator-base 3.1.0 
php-integrator-call-tips-legacy-php56 1.2.3 
php-integrator-linter-legacy-php56 1.3.1 
php-integrator-navigation 1.2.1 
php-integrator-refactoring 1.4.1 
php-integrator-tooltips-legacy-php56 1.1.6 
php-light-syntax 1.0.2 
pigments 0.40.2 
project-manager 3.3.5 
project-plus 1.0.0 
project-sidebar 1.3.0 
remote-sync 4.1.8 
tabs-to-spaces 1.0.3 
tree-view-autoresize 2.3.0 
tree-view-git-status 1.4.0 
```

-----

### Stack Trace 2

Uncaught TypeError: Invalid Point: (17, NaN)

```
At C:\Program Files\Atom x64\resources\app\node_modules\text-buffer\lib\point.js:63

TypeError: Invalid Point: (17, NaN)
    at Function.module.exports.Point.assertValid (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at DisplayLayer.translateScreenPosition (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/display-layer.js:347:17)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateScreenPosition (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:163:38)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/display-marker.js:154:58)
    at changePosition (C:/Program Files/Atom x64/resources/app/src/cursor.js:68:25)
    at Cursor.changePosition (C:/Program Files/Atom x64/resources/app/src/cursor.js:713:11)
    at Cursor.setScreenPosition (C:/Program Files/Atom x64/resources/app/src/cursor.js:67:16)
    at Cursor.moveLeft (C:/Program Files/Atom x64/resources/app/src/cursor.js:288:18)
    at moveCursors.cursor (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2539:52)
    at Array.forEach (native)
    at transact (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2681:31)
    at TextBuffer.module.exports.TextBuffer.transact (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/text-buffer.js:941:24)
    at TextEditor.transact (C:/Program Files/Atom x64/resources/app/src/text-editor.js:1811:30)
    at TextEditor.moveCursors (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2680:23)
    at TextEditor.moveLeft (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2539:23)
    at TextEditor.core:move-left (C:/Program Files/Atom x64/resources/app/src/register-default-commands.js:324:27)
    at HTMLElement.newCommandListeners.(anonymous function) (C:/Program Files/Atom x64/resources/app/src/register-default-commands.js:665:38)
    at CommandRegistry.handleCommandEvent (C:/Program Files/Atom x64/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:/Program Files/Atom x64/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:/Program Files/Atom x64/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (C:/Program Files/Atom x64/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -5:40.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -5:19.6.0 project-find:show (input.hidden-input)
     -5:18.6.0 find-and-replace:show (input.hidden-input)
     -5:17.6.0 core:confirm (input.hidden-input)
     -0:27 core:backspace (input.hidden-input)
  3x -0:25.8.0 core:move-left (input.hidden-input)
     -0:24.9.0 core:delete (input.hidden-input)
     -0:24.3.0 core:move-right (input.hidden-input)
     -0:24 core:delete (input.hidden-input)
     -0:22.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:22.6.0 core:move-right (input.hidden-input)
  7x -0:21.3.0 intentions:highlight (input.hidden-input)
     -0:20.9.0 core:save (input.hidden-input)
     -0:13.8.0 core:confirm (input.hidden-input)
  3x -0:10 core:move-left (input.hidden-input)
 20x -0:08.8.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.7.2 
atom-minify 0.8.0 
autoclose-html 0.23.0 
autocomplete-ionic2-framework 0.3.2 
busy-signal 1.4.3 
config-import-export 0.3.1 
custom-title 1.0.1 
docblockr 0.13.6 
double-click-tree-view 1.1.0 
editor-settings 1.1.3 
editorconfig 2.2.2 
file-icons 2.1.16 
git-plus 7.10.0 
grammar-token-limit 0.1.1 
hyperclick 0.0.0 
intentions 1.1.5 
linter 2.2.0 
linter-htmlhint 1.4.0 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
minimap 4.29.7 
multirow-tabs 0.3.3 
php-debug 0.2.6 
php-integrator-annotations 1.2.0 
php-integrator-base 3.2.0 
php-integrator-call-tips-legacy-php56 1.2.3 
php-integrator-linter-legacy-php56 1.3.1 
php-integrator-refactoring 1.4.1 
php-integrator-tooltips-legacy-php56 1.1.6 
php-light-syntax 1.0.2 
pigments 0.40.2 
project-manager 3.3.5 
project-plus 1.0.0 
project-sidebar 1.3.0 
remote-sync 4.1.8 
tabs-to-spaces 1.0.3 
tree-view-autoresize 2.3.0 
tree-view-git-status 1.4.0 
```

**Comment by bp274** [comment]
#### Uncaught TypeError: Invalid Point: (21, NaN)

I am on windows 10 and this error occured for me while editing a file.
I was removing some lines from a file with backspace and then i saw this and thought i should report it.

![screenshot 8](https://user-images.githubusercontent.com/32530527/36642376-9bffa902-1a64-11e8-99f6-6509a61f12c7.png)

#### Stack Trace
```at Function.module.exports.Point.assertValid (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\node_modules\text-buffer\lib\point.js:63:21)
    at DisplayLayer.translateScreenPosition (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\node_modules\text-buffer\lib\display-layer.js:345:17)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateScreenPosition (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\node_modules\text-buffer\lib\display-marker-layer.js:163:38)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\node_modules\text-buffer\lib\display-marker.js:154:58)
    at changePosition (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\cursor.js:68:25)
    at Cursor.changePosition (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\cursor.js:713:11)
    at Cursor.setScreenPosition (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\cursor.js:67:16)
    at Cursor.moveLeft (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\cursor.js:288:18)
    at modifySelection (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\selection.js:252:50)
    at Selection.modifySelection (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\selection.js:975:11)
    at Selection.selectLeft (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\selection.js:252:16)
    at Selection.backspace (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\selection.js:496:36)
    at mutateSelectedText.selection (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor.js:1359:65)
    at getSelectionsOrderedByBufferPosition.map (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor.js:1373:92)
    at Array.map (native)
    at transact (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor.js:1373:66)
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:943:24)
    at TextEditor.transact (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor.js:1825:30)
    at mergeIntersectingSelections (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor.js:1372:25)
    at TextEditor.mergeSelections (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor.js:3208:26)
    at TextEditor.mergeIntersectingSelections (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor.js:3179:42)
    at TextEditor.mutateSelectedText (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor.js:1371:23)
    at TextEditor.backspace (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor.js:1359:23)
    at TextEditor.object.(anonymous function) [as backspace] (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\node_modules\underscore-plus\lib\underscore-plus.js:77:33)
    at TextEditor.core:backspace (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\register-default-commands.js:436:27)
    at C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\register-default-commands.js:695:40
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:943:24)
    at TextEditor.transact (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor.js:1825:30)
    at HTMLElement.newCommandListeners.(anonymous function) (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\register-default-commands.js:694:28)
    at CommandRegistry.handleCommandEvent (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (C:\Users\Bhaavik Pratyush\AppData\Local\atom\app-1.24.0\resources\app\src\window-event-handler.js:108:40)
```
This error seems to have been caused due to the community package 'platformio-ide-terminal' as i was not able to reproduce this error when the terminal was not open and i don't have any other packages installed.

I am new to git and open source, so forgive me if i did something wrong.

**Comment by rsese** [comment]
From https://github.com/atom/atom/issues/16905:

> Steps to reproduce:

> Open a .php document.
> Try to type
> ???
> I don't really know why or how this happened, it just did.

And:

> It seemed there was a hidden character after a closing tag (>).

> Backspacing the line before resolved the issue some how. Possibly a false character created by changing the default mode to open files from UTF-8 to ISO-8859-1.

> File was previously opened and saved in UTF-8.

**Comment by Ben3eeE** [comment]
I have seen this exception a couple of times the last week on the latest nightly releases (1.33.0-nightly9 and 1.34.0-nightly2). Always when working in a php file with Windows 1252 encoding located on a network drive. Seems like what everyone else is saying 😅 

I have not been able to reliably reproduce the issue.

**Comment by finnbear** [comment]
Just got this error when editing a freemarker (.ftl) file with an plugin installed for syntax coloring.
