### ISSUE TITLE
Uncaught TypeError: Cannot read property '__reactInternalInstance$kgfabg7md9v397kyu05tawcdi' of null

### ISSUE THREAD

**Issue by marlonmleite** [atom/atom#14770]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0-beta3 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property '__reactInternalInstance$kgfabg7md9v397kyu05tawcdi' of null

```
At /usr/share/atom-beta/resources/app/node_modules/react-dom/lib/ReactDOMComponentTree.js:113

TypeError: Cannot read property '__reactInternalInstance$kgfabg7md9v397kyu05tawcdi' of null
    at Object.getClosestInstanceFromNode (/usr/share/atom-beta/resources/app/node_modules/react-dom/lib/ReactDOMComponentTree.js:113:17)
    at findParent (/usr/share/atom-beta/resources/app/node_modules/react-dom/lib/ReactEventListener.js:38:38)
    at handleTopLevelImpl (/usr/share/atom-beta/resources/app/node_modules/react-dom/lib/ReactEventListener.js:67:34)
    at ReactDefaultBatchingStrategyTransaction.perform (/usr/share/atom-beta/resources/app/node_modules/react-dom/lib/Transaction.js:140:26)
    at Object.batchedUpdates (/usr/share/atom-beta/resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:32)
    at Object.batchedUpdates (/usr/share/atom-beta/resources/app/node_modules/react-dom/lib/ReactUpdates.js:97:33)
    at dispatchEvent (/usr/share/atom-beta/resources/app/node_modules/react-dom/lib/ReactEventListener.js:147:26)
```

### Commands

```
     -0:24 core:paste (atom-pane.pane)
```

### Non-Core Packages

```
atom-jest-snippets 1.1.1 
atom-monokai 0.10.9 
autocomplete-js-import 1.4.0 
busy-signal 1.4.3 
color-picker 2.2.5 
eclipse-keybindings 0.9.0 
go-to-file 0.2.0 
graphql-autocomplete 1.0.3 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.65.1 
language-graphql 0.9.0 
linter 2.1.4 
linter-eslint 8.2.1 
linter-ui-default 1.6.1 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
monokai 0.24.0 
monokai-blackboard 0.3.0 
seti-icons 1.5.3 
```

**Comment by 50Wliu** [comment]
:wave: @marlonmleite could you please share what you were doing when this exception occurred?  Thanks!

**Comment by marlonmleite** [comment]
I could not reproduce anymore.
