### ISSUE TITLE
Uncaught Error: EINVAL: invalid argument, open '~/Dropbox/FEND Arcade/js/app.js'

### ISSUE THREAD

**Issue by monkeyshoulders** [atom/atom#14771]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EINVAL: invalid argument, open '/Users/Matt/Dropbox/FEND Arcade/js/app.js'

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:1095

Error: EINVAL: invalid argument, open '/Users/Matt/Dropbox/FEND Arcade/js/app.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Proxy.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:295:1)
    at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:289:1)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:467:1)
    at File.module.exports.File.writeSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:384:1)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1127:1)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:1)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:925:1)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:780:1)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:3:1)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:763:1)
    at Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1498:1)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:236:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
  4x -1:16.1.0 core:backspace (input.hidden-input)
     -1:03.8.0 core:move-left (input.hidden-input)
     -1:03.4.0 core:backspace (input.hidden-input)
     -0:58.5.0 core:save (input.hidden-input)
     -0:15.8.0 core:backspace (input.hidden-input)
     -0:02.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
color-picker 2.2.5 
css-snippets 1.1.0 
emmet 2.4.3 
file-icons 2.1.4 
git-plus 7.8.0 
javascript-snippets 1.2.1 
minimap 4.28.2 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by monkeyshoulders** [comment]
It was actually a mechanical hardrive failure☹️ but that's fixed now. Thanks for responding. I absolutely love atom.

**Comment by rsese** [comment]
> It was actually a mechanical hardrive failure☹️ but that's fixed now. Thanks for responding. I absolutely love atom.

Oh wow, glad your hard drive is fixed and thanks for letting us know what the issue was :v:
