### ISSUE TITLE
Dev Mode Crash on Windows (64-bit)

### ISSUE THREAD

**Issue by GlenCFL** [atom/atom#14789]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom 1.18 seems to have broken the Developer Mode on Windows, at least for me on x64.

### Steps to Reproduce

Attempting to open developer mode in any way results in an exception being thrown, whether using --dev from the command line or using "Open in Dev Mode.." from the menu.

**Expected behavior:**

I expect the editor to open in development mode, as it had in previous versions.

**Actual behavior:**

An exception is thrown and displayed in the Atom console, resulting in Atom failing to initialize.

**Reproduces how often:**

100%, every single time Atom is launched in dev mode.

### Versions

Atom: 1.18.0
Electron: 1.3.15
Chrome: 52.0.2743.82
Node : 6.5.0

### Additional Information

Here is the exception output on the Atom console:
```
Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
Error: Cannot find module '../../modules/es6.object.to-string'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\GlenCFL\AppData\Local\atom\app-1.18.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\GlenCFL\AppData\Local\atom\app-1.18.0\resources\app\src\module-cache.js:350:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\GlenCFL\AppData\Local\atom\app-1.18.0\resources\app\src\native-compile-cache.js:47:27)
    at Object.<anonymous> (C:\Users\GlenCFL\AppData\Local\atom\app-1.18.0\resources\app\node_modules\babel-runtime\node_modules\core-js\library\fn\symbol\index.js:2:1)
    at Module._compile (C:\Users\GlenCFL\AppData\Local\atom\app-1.18.0\resources\app\src\native-compile-cache.js:87:30)
    at Object.value [as .js] (C:\Users\GlenCFL\AppData\Local\atom\app-1.18.0\resources\app\src\compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\GlenCFL\AppData\Local\atom\app-1.18.0\resources\app\src\native-compile-cache.js:47:27)
    at Object.<anonymous> (C:\Users\GlenCFL\AppData\Local\atom\app-1.18.0\resources\app\node_modules\babel-runtime\core-js\symbol.js:1:110)
    at Module._compile (C:\Users\GlenCFL\AppData\Local\atom\app-1.18.0\resources\app\src\native-compile-cache.js:87:30)
    at Object.value [as .js] (C:\Users\GlenCFL\AppData\Local\atom\app-1.18.0\resources\app\src\compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\GlenCFL\AppData\Local\atom\app-1.18.0\resources\app\src\native-compile-cache.js:47:27)
    at Object.<anonymous> (C:\Users\GlenCFL\AppData\Local\atom\app-1.18.0\resources\app\node_modules\babel-runtime\helpers\typeof.js:9:15)
    at Module._compile (C:\Users\GlenCFL\AppData\Local\atom\app-1.18.0\resources\app\src\native-compile-cache.js:87:30)
    at Object.value [as .js] (C:\Users\GlenCFL\AppData\Local\atom\app-1.18.0\resources\app\src\compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\GlenCFL\AppData\Local\atom\app-1.18.0\resources\app\src\native-compile-cache.js:47:27)
```

**Comment by GlenCFL** [comment]
It seems like this was some kind of issue caused by the automatic upgrade from Atom 1.17.2 to 1.18.0. Downloading the 1.18.0 installer and just installing it over top of the faulty 1.18.0 seems to have fixed it.
