### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by Kkthnx** [atom/atom#14794]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At C:\Users\kkthn\AppData\Local\atom\app-1.19.0-beta0\resources\app\src\text-editor-component.js:2132

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/text-editor-component.js:2132:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/text-editor-component.js:2128:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/text-editor-component.js:373:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/text-editor-component.js:263:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/view-registry.js:191:15)
    at ~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -1:41.9.0 intentions:highlight (input.hidden-input)
     -1:41.7.0 core:save (input.hidden-input)
     -1:18.4.0 intentions:highlight (input.hidden-input)
undefined -1:18.2.0 core:undo (input.hidden-input)
  3x -1:11.5.0 intentions:highlight (input.hidden-input)
 42x -1:11 core:redo (input.hidden-input)
  5x -1:08.4.0 core:undo (input.hidden-input)
 11x -1:06.8.0 core:redo (input.hidden-input)
     -1:04.6.0 core:undo (input.hidden-input)
 74x -1:04.1.0 core:redo (input.hidden-input)
 15x -0:59.4.0 core:undo (input.hidden-input)
  3x -0:50 core:redo (input.hidden-input)
     -0:48.2.0 core:undo (input.hidden-input)
     -0:47.6.0 core:save (input.hidden-input)
     -0:45.2.0 intentions:highlight (input.hidden-input)
     -0:45.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.2 
language-lua-wow 0.2.0 
language-toc-wow 0.2.0 
linter 2.1.4 
linter-lua-findglobals 1.2.0 
linter-ui-default 1.6.1 
sort-lines 0.14.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by Arcanemagus** [comment]
Had this happen to me just now, it started after this error got thrown:
```
Uncaught Error: Requested measurement of a line that is not currently rendered
    at horizontalPositionsToMeasure.forEach (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta0\resources\app\src\text-editor-component.js:2135:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta0\resources\app\src\text-editor-component.js:2128:45)
    at TextEditorComponent.measureContentDuringUpdateSync (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta0\resources\app\src\text-editor-component.js:373:16)
    at TextEditorComponent.screenPositionForPixelPosition (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta0\resources\app\src\text-editor-component.js:2239:18)
    at getBufferPositionFromMouseEvent (file:///C:/Users/Landon Abney/.atom/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at HTMLElement.<anonymous> (file:///C:/Users/Landon Abney/.atom/packages/linter-ui-default/lib/editor/index.js:163:29)
    at later (C:\Users\Landon Abney\.atom\packages\linter\node_modules\sb-debounce\index.js:9:14)
```

The error reported in https://github.com/steelbrain/linter-ui-default/issues/357 also was mixed in.

I'm unsure of how to trigger this, however once it _starts_ triggering almost all mouse interactions will throw an error: movement and left clicking (not right clicking). I _believe_ I was dragging the minimap "scrollbar" when this started triggering.

This is possibly a Windows specific issue as @Kkthnx and myself are both on Windows 10 x64.

**Comment by TomYeoman** [comment]
I'm also getting this issue..

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (C:\Users\Thomas Yeoman\AppData\Local\atom\app-1.19.0-beta0\resources\app\src\text-editor-component.js:2132:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (C:\Users\Thomas Yeoman\AppData\Local\atom\app-1.19.0-beta0\resources\app\src\text-editor-component.js:2128:45)
    at TextEditorComponent.measureContentDuringUpdateSync (C:\Users\Thomas Yeoman\AppData\Local\atom\app-1.19.0-beta0\resources\app\src\text-editor-component.js:373:16)
    at TextEditorComponent.updateSync (C:\Users\Thomas Yeoman\AppData\Local\atom\app-1.19.0-beta0\resources\app\src\text-editor-component.js:270:18)
    at didStopDragging (C:\Users\Thomas Yeoman\AppData\Local\atom\app-1.19.0-beta0\resources\app\src\text-editor-component.js:1705:20)
    at didMouseUp (C:\Users\Thomas Yeoman\AppData\Local\atom\app-1.19.0-beta0\resources\app\src\text-editor-component.js:1794:15)

If it helps these errors seem to happen on larger files only after linting has finished (Maybe it's a marker bug? ).

If I open one of my JS files (3000 lines) it's fine, I have another which is 7k lines (I know massive..) I start getting spammed these errors instantly (All I have to do is click on the tab for the errors to begin)

**Comment by rsese** [comment]
Looks like you're also on Windows @TomYeoman - curious since it sounds like you can reproduce consistently with that larger file, do you see the errors in safe mode (`atom --safe`)?  Also, would you be able to share that file by any chance?

@Arcanemagus - do you happen to remember if you saw the errors while working on a large file as well?

**Comment by Arcanemagus** [comment]
@rsese Semi-large, it's 1.3k lines of Perl code currently. While scrolling down to check that (again, using minimap) I actually reproduced again around the 1k line mark, but was unable to do so after restarting Atom.

**Comment by Kkthnx** [comment]
Sorry for the late reply @rsese I have been busy! I got then when I would paste entire replacement of new .Lua code into my editor and then hit ctrl-s to save it. That's when this would popup. I reverted to a stable build and haven't had it since.

**Comment by TomYeoman** [comment]
```
TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (C:\Users\Thomas Yeoman\AppData\Local\atom\app-1.19.0-beta1\resources\app\src\text-editor-component.js:2132:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (C:\Users\Thomas Yeoman\AppData\Local\atom\app-1.19.0-beta1\resources\app\src\text-editor-component.js:2128:45)
    at TextEditorComponent.measureContentDuringUpdateSync (C:\Users\Thomas Yeoman\AppData\Local\atom\app-1.19.0-beta1\resources\app\src\text-editor-component.js:373:16)
    at scheduler.readDocument (C:\Users\Thomas Yeoman\AppData\Local\atom\app-1.19.0-beta1\resources\app\src\text-editor-component.js:263:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\Thomas Yeoman\AppData\Local\atom\app-1.19.0-beta1\resources\app\src\view-registry.js:191:15)
    at C:\Users\Thomas Yeoman\AppData\Local\atom\app-1.19.0-beta1\resources\app\src\view-registry.js:3:65
```

@rsese That's correct i'm on windows :) 

So I've got a new situation where this occurs

I've got a file of only 1k lines open (This time with a small amount of linting errors, 50 or so). It seems fine at first but once it's been loaded for a minute and I quickly scroll up / down using the codes minimap this error seems to start spamming

**Comment by Arcanemagus** [comment]
> I'm assuming then that the error isn't reproducible for you in safe mode

I've yet to find a way to reliably reproduce this, but it hasn't happened in safe mode the times I've tried. It's possible this really is something `linter-ui-default` is doing... or it's just that that is the most common bottom dock content out right now and is triggering it there.

**Comment by lexicalunit** [comment]
Getting the same error whenever the cursor moves at all. I'm on macOS and Atom 1.19.0-beta3.
