### ISSUE TITLE
Failed to activate the node-resolver package

### ISSUE THREAD

**Issue by tx3d** [atom/atom#14828]
[Enter steps to reproduce:]

1. Just try to install. Error will be shown after installation.
**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: 'node-resolver' package vundefined

### Stack Trace

Failed to activate the node-resolver package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.exports.activate (/packages/node-resolver/index.js:12:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:519:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -3:36.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.editor-background)
     -2:36.9.0 core:paste (input.form-control.input-text)
     -2:23.7.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.editor-background.theme-duotone-dark-space-syntax.theme-one-dark-ui)
     -1:38.9.0 editor-background:toggle (input.hidden-input)
     -0:52 core:save (input.hidden-input)
     -0:49.9.0 platformio-ide-terminal:new (input.hidden-input)
     -0:44.4.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.editor-background.theme-duotone-dark-sea-syntax.theme-one-dark-ui)
     -0:27.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
build 0.68.0 
busy 0.7.0 
duotone-dark-sea-syntax 2.1.0 
duotone-dark-space-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
editor-background 1.2.38 
file-icons 2.1.7 
highlight-selected 0.13.1 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-perl 0.8.0 
linter-ui-default 1.6.1 
minimap 4.28.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
platformio-ide 2.0.0-beta.6 
platformio-ide-debugger 1.2.2 
platformio-ide-terminal 2.5.1 
tool-bar 1.1.0 
```

**Comment by 50Wliu** [comment]
It looks like the node-resolver package has not been updated for Atom's 1.0 APIs, and as such will not work.  You may want to look for an alternative package.
