### ISSUE TITLE
atom 1.9.0-beta0 fails due to GLIBC Major version difference.

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#14827]
```
Uncaught (in promise) Error: /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /opt/atom/resources/app/node_modules/superstring/build/Release/superstring.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///opt/atom/resources/app/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/opt/atom/resources/app/node_modules/superstring/index.js:35:15)
    at Object.<anonymous> (/opt/atom/resources/app/node_modules/superstring/index.js:164:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///opt/atom/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/opt/atom/resources/app/static/<embedded>:96:26)
    at get_ref1 (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:27:33)
    at get_NativeTextBuffer (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:39:57)
    at new TextBuffer (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:172:32)
    at Function.module.exports.TextBuffer.load (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:213:22)
    at Function.module.exports.TextBuffer.deserialize (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:244:30)
    at Project.module.exports.Project.deserialize (/opt/atom/resources/app/src/project.js:124:46)
    at AtomEnvironment.module.exports.AtomEnvironment.deserialize (/opt/atom/resources/app/src/atom-environment.js:1251:45)
    at /opt/atom/resources/app/src/atom-environment.js:812:32
```
### Description

Latest atom fails due to mission C++ library

### Steps to Reproduce

1. Download latest atom beta 1.19.0-beta0  atom-amd64.tar.gz from github release page 
2. Run
3. Fails

**Expected behavior:** [What you expect to happen]

Open atom with document

**Actual behavior:** [What actually happens]
Open atom but problem with Superstring library

**Reproduces how often:** [What percentage of the time does it reproduce?]
always
### Versions
Atom    : 1.19.0-beta0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

.

### Additional Information

Linux kernel 4.10.0
Sabayon Linux (latest) : Gentoo variant .

**Comment by v3ss0n** [comment]
I recommend building atom with low GLIBC version so it works across different Linuxes. 
my linux ship with 2.2.3 version of GLIBC.

**Comment by Arcanemagus** [comment]
`GLIBC` and `GLIBCXX` are two entirely different things @v3ss0n. (C and C++ support respectively)

It [looks like](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html) `GLIBCXX_3.4.21` corresponds to G++ v5.1.0 released on 2015-04-22, while `GLIBC_2.23.?` corresponds to a [release date](https://sourceware.org/glibc/wiki/Glibc%20Timeline) of 2016-02-19, so for some bizarre reason whatever your distro is they decided to include a rather old `GLIBCXX` with a newer `GLIBC`.

I'll leave it to the Atom maintainers to discuss the merits of whether to put in the effort to support old systems though 😉.

**Comment by maxbrunsfeld** [comment]
Thanks for the report @v3ss0n. I would like to support as many systems as possible. The only reason that I started building with a newer version of `libstdc++` was because I wanted to use the 
`std::codecvt_utf8_utf16` class from the `<codecvt>` header. It probably wouldn't be too hard to drop this dependency. We could probably just borrow [the implementations from libc++](https://github.com/llvm-mirror/libcxx/blob/c3589a8305a317cfa0757bc5f4136a7b93684d23/src/locale.cpp#L1723-L1875).

**Comment by maxbrunsfeld** [comment]
Fixing this now. Sorry for breaking compatibility w/ your system @v3ss0n.

**Comment by maxbrunsfeld** [comment]
This fix will go out in Atom 1.19.0-beta2. We'll probably publish that within a few days.

**Comment by Arcanemagus** [comment]
This will likely mean the recent changes in `atom/ci` can be reverted, will re-check that when this gets released.

**Comment by v3ss0n** [comment]
@maxbrunsfeld  Awesome!! i had build myself and build is a success. I am going to test now.

**Comment by v3ss0n** [comment]
build is a success , but when running it cause this error :

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '../build/Release/nslog.node'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/atom/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/atom/share/atom/resources/app/node_modules/nslog/lib/nslog.js:5:11)
    at Object.<anonymous> (/opt/atom/share/atom/resources/app/node_modules/nslog/lib/nslog.js:15:4)
    at Object.<anonymous> (/opt/atom/share/atom/resources/app/node_modules/nslog/lib/nslog.js:17:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

**Comment by maxbrunsfeld** [comment]
@v3ss0n Try running `script/clean && script/build`.

**Comment by v3ss0n** [comment]
checking it out now , gonna try building from scratch.

**Comment by Arcanemagus** [comment]
Example CI configuration update up in https://github.com/atom/ci/pull/74.
