### ISSUE TITLE
 atom-1.20.0-dev-df7f72a3b  -   Error: Cannot find module '../build/Release/nslog.node'

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#14843]
### Description

Building and running latest master atom-1.20.0-dev-df7f72a3b crashes with Javascript error

### Steps to Reproduce

1.  Build latest master  df7f72a3b
2.  Run
3.  JS Error missing 

**Expected behavior:** [What you expect to happen]
Runs
**Actual behavior:** [What actually happens]

```
Uncaught Exception:
Error: Cannot find module '../build/Release/nslog.node'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/nslog/lib/nslog.js:5:11)
    at Object.<anonymous> (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/nslog/lib/nslog.js:15:4)
    at Object.<anonymous> (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/nslog/lib/nslog.js:17:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```
**Reproduces how often:** [What percentage of the time does it reproduce?]
always
### Versions

can't run atom --version
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
@v3ss0n Did you try `script/clean` before `script/build`?

**Comment by v3ss0n** [comment]
i did and rebuild , atom is launching now but with new error.

```
Uncaught Error: Cannot find module '../build/Release/keyboard-layout-manager.node'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:456:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:336:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/src/window-event-handler.js:3:65)
```
i ran with `atom --safe`

```
Atom    : 1.20.0-dev-df7f72a3b
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by rsese** [comment]
Oh sorry, just saw this last comment of yours now before I replied to you in https://github.com/atom/atom/issues/14859.   So it looks like you had already ran `script/clean` and `script/build` and it got you past your initial error but then you hit this new one.

I guess I'm curious if you do a clean and build again if you get the same or another different error?

**Comment by rsese** [comment]
For folks that come across this issue or folks that I pointed to this issue, just mentioning here that @v3ss0n confirmed that after building a few more times they got past the error /cc https://github.com/atom/atom/issues/14859#issuecomment-310345354:

> more related here since i am building from master.
> I tried 3rd rebuild and now it is working fine.

So if y'all could also try building again and let us know if that gets you past the error, that would be great :v:
