### ISSUE TITLE
Atom opens without any panes.

### ISSUE THREAD

**Issue by romainmenke** [atom/atom#14841]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Opening atom after updating to 1.18 results in a window without any panes or the dir tree. It is not a new window, it was opened with `atom .` with `pwd` set to a project dir.

### Steps to Reproduce

- update to 1.18.0
- `atom .` in project dir

**Expected behavior:** 

- i'd expect a usable code editor with panes.

**Actual behavior:** 

- no panes or dir tree

**Reproduces how often:**

100%

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.1

OSX 10.11.6

**Comment by rsese** [comment]
Thanks for the report!  Can you share a screenshot of what you see?  And just to confirm, can you do anything after Atom starts like open a project or file?

Lastly, was there any difference in behavior running in safe mode (`atom --safe .`)?

**Comment by romainmenke** [comment]
Will add a screenshot tomorrow when back at work.

I also don't really know if the issue is related to the update or another random thing happened around the same time.

I tried `atom --safe` with no improvement.

Is there a file which stores which panes are open for a certain dir? Might be fixed by resetting that.

**Comment by rsese** [comment]
> Is there a file which stores which panes are open for a certain dir? Might be fixed by resetting that.

If you still have trouble in safe mode then clearing saved state is another option to try - you can clear saved state as detailed in our docs:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

But note that you'll lose any unsaved data across all projects in the process and it clears all saved state - the command doesn't have fine grained controls to only clear some saved state like the state of 1 particular project.

**Comment by romainmenke** [comment]
`atom --clear-window-state` fixed it and I was able to reproduce the error from a working state now.

Focus is on Tree View
View -> Panes -> Split

This will split the Tree View. If you now close the Tree View tab, close and open atom it will be stuck in a paneless state.

Thanks for the help!

**Comment by rsese** [comment]
Glad that got you past the state you were in 🙌 

To clarify the steps you mentioned, can you confirm if this is correct?

1. Start Atom with some project `atom .`
2. Click the tree view to focus it
3. Choose `View > Panes > Split Right`
4. Click the pane with the tree view again to focus it
5. Right click and `Close Pane`
6. Quit Atom with <kbd>cmd-q</kbd>
7. Restart Atom with just `atom`

At this point, Atom restarts with the tree view is open with the project's tree there.

**Comment by romainmenke** [comment]
Just tried it again here at home, so different mac with, but same issue.

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

1. Start Atom with some project `atom .`
2. Click the tree view to focus it
3. Choose `View > Panes > Split Right`
4. Click the pane with the tree view again to focus it
5. `cmd-w` to close pane
6. Quit Atom with `cmd-q`
7. Restart Atom with `atom .` in the same project.

**Comment by bennypowers** [comment]
I have a similar problem.

```
atom .
```
I don't get the cwd as project dir, it opens a blank window 100% of the time, also after `--clear-window-state` and after deactivating all packages. `atom --safe-mode .` does open the cwd as project dir, though.

**Comment by jnmandal** [comment]
This also happened to me. I was using emacs keys and accidentally closed the tree view instead of a tab. IMHO there should be something that prevents you from closing tree view tab and getting into this state. At least a dialog asking if you really want to close it?

**Comment by daT4v1s** [comment]
same problem here (blank window) but since the menu-bar was enabled before it 
became stuck in this state, i get consistently stuck at startup:
![Screenshot from 2019-07-20 22-03-54 atom blank ](https://user-images.githubusercontent.com/47403824/61586120-88051c80-ab3a-11e9-9076-6b68a5e45ade.png)

from menuBar	〉view	〉developer tools
![Screenshot from 2019-07-20 22-07-28 atom developer tools ](https://user-images.githubusercontent.com/47403824/61586135-e3370f00-ab3a-11e9-8a8a-f776b139fc27.png)


```
Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at TextEditor.usesSoftTabs (/usr/share/atom/resources/app/static/<embedded>:11:41805)
    at shouldEditorUseSoftTabs (/usr/share/atom/resources/app/static/<embedded>:11:508072)
    at o (/usr/share/atom/resources/app/static/<embedded>:11:509774)
    at TextEditorRegistry.maintainConfig (/usr/share/atom/resources/app/static/<embedded>:11:509876)
    at onDidAddPaneItem (/usr/share/atom/resources/app/static/<embedded>:11:424880)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1206820)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1208261)
    at PaneContainer.didAddPaneItem (/usr/share/atom/resources/app/static/<embedded>:11:445279)
    at PaneContainer.didAddPane (/usr/share/atom/resources/app/static/<embedded>:11:444681)
    at Pane.setContainer (/usr/share/atom/resources/app/static/<embedded>:11:452141)
    at e.container.children.forEach.t (/usr/share/atom/resources/app/static/<embedded>:11:447386)
    at Array.forEach (<anonymous>)
    at PaneAxis.setContainer (/usr/share/atom/resources/app/static/<embedded>:11:447373)
    at PaneContainer.setRoot (/usr/share/atom/resources/app/static/<embedded>:11:443124)
    at PaneContainer.deserialize (/usr/share/atom/resources/app/static/<embedded>:11:441616)
    at WorkspaceCenter.deserialize (/usr/share/atom/resources/app/static/<embedded>:14:39582)
    at Workspace.deserialize (/usr/share/atom/resources/app/static/<embedded>:11:421699)
    at AtomEnvironment.deserialize (/usr/share/atom/resources/app/static/<embedded>:1:715452)
    at <anonymous>
```

**Comment by daT4v1s** [comment]
running atom in safe-mode still result in problem
but adding `-d` to command-line (dev mode)
![Screenshot from 2019-07-20 22-15-35 atom dev mode ](https://user-images.githubusercontent.com/47403824/61586187-04e4c600-ab3c-11e9-8e22-dbf13cd1f2da.png)

```
Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at TextEditor.usesSoftTabs (/usr/share/atom/resources/app.asar/src/text-editor.js:3614:15)
    at shouldEditorUseSoftTabs (/usr/share/atom/resources/app.asar/src/text-editor-registry.js:305:22)
    at updateTabTypes (/usr/share/atom/resources/app.asar/src/text-editor-registry.js:159:26)
    at TextEditorRegistry.maintainConfig (/usr/share/atom/resources/app.asar/src/text-editor-registry.js:166:5)
    at onDidAddPaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:500:35)
    at Function.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/dist/emitter.js:257:28)
    at PaneContainer.didAddPaneItem (/usr/share/atom/resources/app.asar/src/pane-container.js:267:18)
    at PaneContainer.didAddPane (/usr/share/atom/resources/app.asar/src/pane-container.js:239:12)
    at Pane.setContainer (/usr/share/atom/resources/app.asar/src/pane.js:133:17)
    at children.forEach.child (/usr/share/atom/resources/app.asar/src/pane-axis.js:72:44)
    at Array.forEach (<anonymous>)
    at PaneAxis.setContainer (/usr/share/atom/resources/app.asar/src/pane-axis.js:72:21)
    at PaneContainer.setRoot (/usr/share/atom/resources/app.asar/src/pane-container.js:134:15)
    at PaneContainer.deserialize (/usr/share/atom/resources/app.asar/src/pane-container.js:55:10)
    at WorkspaceCenter.deserialize (/usr/share/atom/resources/app.asar/src/workspace-center.js:31:24)
    at Workspace.deserialize (/usr/share/atom/resources/app.asar/src/workspace.js:369:34)
    at AtomEnvironment.deserialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:1289:41)
    at <anonymous>
```

![Screenshot from 2019-07-20 22-17-11 atom dev mode details ](https://user-images.githubusercontent.com/47403824/61586203-4b3a2500-ab3c-11e9-9e39-f518a2f0d0e8.png)

```javascript
 doesShowIndentGuide () { return this.showIndentGuide && !this.mini }

  getSoftWrapHangingIndentLength () { return this.displayLayer.softWrapHangingIndent }

  // Extended: Determine if the buffer uses hard or soft tabs.
  //
  // Returns `true` if the first non-comment line with leading whitespace starts
  // with a space character. Returns `false` if it starts with a hard tab (`\t`).
  //
  // Returns a {Boolean} or undefined if no non-comment lines had leading
  // whitespace.
  usesSoftTabs () {
    const languageMode = this.buffer.getLanguageMode()
    const hasIsRowCommented = languageMode.isRowCommented
    for (let bufferRow = 0, end = Math.min(1000, this.buffer.getLastRow()); bufferRow <= end; bufferRow++) {
      if (hasIsRowCommented && languageMode.isRowCommented(bufferRow)) continue
      const line = this.buffer.lineForRow(bufferRow)
      if (line[0] === ' ') return true
      if (line[0] === '\t') return false
    }
  }
```
