### ISSUE TITLE
iojs dependancy access error followed by 404 during install

### ISSUE THREAD

**Issue by anomaly256** [atom/atom#14855]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

During `sudo build/script --install` when building and installing from source, apm throws a EACCES for root on `/root/.atom/.node-gyp/.node-gyp/iojs-1.3.15` despite this directory existing, being owned by root, and being writeable.  After this, it tries to fetch the tar.gz for it and receives a 404 from iojs.org and errors out.

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/iojs-1.3.15"                
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/anomaly/src/atom/node_modules/github/node_modules/keytar/.node-gyp"                                                                                                                                      
gyp WARN install got an error, rolling back install                                                                                     
gyp WARN install got an error, rolling back install                                                                                     
gyp ERR! configure error                                                                                                                
gyp ERR! stack Error: 404 response downloading https://iojs.org/download/release/v1.3.15/iojs-v1.3.15.tar.gz                            
gyp ERR! stack     at Request.<anonymous> (/home/anomaly/src/atom/apm/node_modules/atom-package-manager/node_modules/node-gyp/lib/install.js:210:14)                                                                                                                            
gyp ERR! stack     at emitOne (events.js:101:20)                                                                                        
gyp ERR! stack     at Request.emit (events.js:188:7)                                                                                    
gyp ERR! stack     at Request.onRequestResponse (/home/anomaly/src/atom/apm/node_modules/atom-package-manager/node_modules/request/request.js:1074:10)                                                                                                                          
gyp ERR! stack     at emitOne (events.js:96:13)                                                                                         
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)                                                                              
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)                                                        
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)                                                        
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)                                                                   
gyp ERR! stack     at emitOne (events.js:96:13)                                                                                         
gyp ERR! System Linux 4.11.6-gentoo                                                                                                     
gyp ERR! command "/home/anomaly/src/atom/apm/node_modules/atom-package-manager/bin/node" "/home/anomaly/src/atom/apm/node_modules/atom-package-manager/node_modules/.bin/node-gyp" "rebuild"                                                                                    
gyp ERR! cwd /home/anomaly/src/atom/node_modules/github/node_modules/keytar                                                             
gyp ERR! node -v v6.9.5                                                                                                                 
gyp ERR! node-gyp -v v3.4.0                                                                                                             
gyp ERR! not ok                                                                                                                         
npm ERR! Linux 4.11.6-gentoo                                                                                                            
npm ERR! argv "/home/anomaly/src/atom/apm/node_modules/atom-package-manager/bin/node" "/home/anomaly/src/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/root/.atom/.apm/.apmrc" "--userconfig" "/root/.atom/.apmrc" "install" "--runtime=electron" "--target=1.3.15" "--arch=x64"                                                                                       
npm ERR! node v6.9.5                                                                                                                    
npm ERR! npm  v3.10.10                                                                                                                  
npm ERR! code ELIFECYCLE      
```                                                                                                          

### Steps to Reproduce

1. Clone atom git repo and checkout v1.18.0
2. execute `script/build` in atom src dir
3. execute `sudo script/build install` in atom src dir

**Expected behavior:** 
Previously, atom would install at this point and everything would be well

**Actual behavior:**
Install fails prematurely

**Reproduces how often:**
Always

### Versions

At least v1.18.0 possibly others

### Additional Information

**Comment by 50Wliu** [comment]
I see a bigger problem here which is that it's trying to download iojs, not Electron.  Can you please try `script/clean`, followed by a `script/build --install`?

**Comment by anomaly256** [comment]
I just tried with --install realizing I had typoed, exact same result:

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/iojs-1.3.15"                
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/anomaly/src/atom/node_modules/github/node_modules/keytar/.node-gyp"                                                                                                                                      
gyp WARN install got an error, rolling back install                                                                                     
gyp WARN install got an error, rolling back install                                                                                     
gyp ERR! configure error                                                                                                                
gyp ERR! stack Error: 404 response downloading https://iojs.org/download/release/v1.3.15/iojs-v1.3.15.tar.gz                            
gyp ERR! stack     at Request.<anonymous> (/home/anomaly/src/atom/apm/node_modules/atom-package-manager/node_modules/node-gyp/lib/install.js:210:14)                                                                                                                            
gyp ERR! stack     at emitOne (events.js:101:20)                                                                                        
gyp ERR! stack     at Request.emit (events.js:188:7)                                                                                    
gyp ERR! stack     at Request.onRequestResponse (/home/anomaly/src/atom/apm/node_modules/atom-package-manager/node_modules/request/request.js:1074:10)                                                                                                                          
gyp ERR! stack     at emitOne (events.js:96:13)                                                                                         
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)                                                                              
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)                                                        
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)                                                        
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)                                                                   
gyp ERR! stack     at emitOne (events.js:96:13)                                                                                         
gyp ERR! System Linux 4.11.6-gentoo                                                                                                     
gyp ERR! command "/home/anomaly/src/atom/apm/node_modules/atom-package-manager/bin/node" "/home/anomaly/src/atom/apm/node_modules/atom-package-manager/node_modules/.bin/node-gyp" "rebuild"                                                                                    
gyp ERR! cwd /home/anomaly/src/atom/node_modules/github/node_modules/keytar                                                             
gyp ERR! node -v v6.9.5                                                                                                                 
gyp ERR! node-gyp -v v3.4.0                                                                                                             
gyp ERR! not ok                                                                                                                         
npm ERR! Linux 4.11.6-gentoo                                                                                                            
npm ERR! argv "/home/anomaly/src/atom/apm/node_modules/atom-package-manager/bin/node" "/home/anomaly/src/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/root/.atom/.apm/.apmrc" "--userconfig" "/root/.atom/.apmrc" "install" "--runtime=electron" "--target=1.3.15" "--arch=x64"                                                                                       
npm ERR! node v6.9.5                                                                                                                    
npm ERR! npm  v3.10.10                                                                                                                  
npm ERR! code ELIFECYCLE                                                                                                                
```

**Comment by anomaly256** [comment]
Is it possible this is due to my version of nodejs?  I pinned it to <7.0.0 after some problems building earlier version of atom on 7+ but it looks like it's not using my system version anyway which is 6.11.0.  This build output says it's using 6.9.5 somehow

**Comment by 50Wliu** [comment]
Shouldn't be - apm bundles its own version of node.

**Comment by ungb** [comment]
@anomaly256 it looks like you're using linux.  any way you can provide which version of linux you're using?  I've seen issues with ubuntu 17.04 a while back I think.

**Comment by ungb** [comment]
Also, I don't think `sudo script/build install` does anything.  Have you tried running `sudo script/build --install` ?  Also, you can provide a path where you want atom to install 

example:
`script/build --install=/home/<USERNAME>/bin/atom'  

You would also need to add w.e directory to your path or install it to a directory that is already in your path.

**Comment by anomaly256** [comment]
Hi @ungb , as stated in an earlier comment on this ticket I did try with --install after realizing the typo, with the same result.  It's Gentoo linux, and I've built every prior version of Atom since it was open sourced without issue except for the occasional issue with fetching nodejs packages  v1.17.x builds and installs fine, v1.18.0+ does not

**Comment by anomaly256** [comment]
`gyp ERR! stack Error: 404 response downloading https://iojs.org/download/release/v1.3.15/iojs-v1.3.15.tar.gz                            
`

Surely this is going to be an issue regardless of specifying an install path?

**Comment by ungb** [comment]
yes, this seems unrelated as it fails to download.  thanks for the additional info, I'll try to spin up a gentoo vm in the next few days and see if I can get a steady repro for someone to take a look at.

**Comment by 50Wliu** [comment]
I've seen this error before.  It occurs when the download URL isn't set correctly.  The following is off of personal experience and not any documentation that I read somewhere, so proceed with caution.
* node-gyp by default tries to install versions from https://iojs.org (maybe only if the version number starts with 1, 2, or 3)
* You can override this behavior by setting the download URL (https://github.com/atom/apm/blob/05748001705c8b3a3febd610d5df1fe826c89949/src/apm.coffee#L53)

So the override isn't working in this case for whatever reason.  @anomaly256 is `$ATOM_ELECTRON_URL` set by any chance?

**Comment by anomaly256** [comment]
@ungb thanks.
@50Wliu, no it's not set.  The odd thing is if I checkout v1.17.2, run script/build + sudo script/build --install, it succeeds fine.  If I checkout v1.18.0 it fails as above.  What's different about this version's install phase?  Is this due to pulling in different node deps?

**Comment by anomaly256** [comment]
@50Wliu earlier you stated:

> I see a bigger problem here which is that it's trying to download iojs, not Electron

What would cause this?  Is there a way I can override it as a test?  The link you pasted for the apm.coffee blob throws a HTTP 500 error for me

**Comment by anomaly256** [comment]
@50Wliu earlier you stated:

> I see a bigger problem here which is that it's trying to download iojs, not Electron

What would cause this?  Is there a way I can override it as a test?  The link you pasted for the apm.coffee blob throws a HTTP 500 error for me.. I think github is experiencing some hiccups just now :)

**Comment by anomaly256** [comment]
@50Wliu earlier you stated:

> I see a bigger problem here which is that it's trying to download iojs, not Electron

What would cause this?  Is there a way I can override it as a test?  The link you pasted for the apm.coffee blob throws a HTTP 500 error for me.. I think github is experiencing some hiccups just now :)

**Comment by anomaly256** [comment]
Same error with ATOM_ELECTRON_URL manually set:
```
gyp ERR! configure error                                                                                                                
gyp ERR! stack Error: 404 response downloading https://iojs.org/download/release/v1.3.15/iojs-v1.3.15.tar.gz                            
gyp ERR! stack     at Request.<anonymous> (/home/anomaly/src/atom/apm/node_modules/atom-package-manager/node_modules/node-gyp/lib/install.js:210:14)                 
```

**Comment by anomaly256** [comment]
By the way, here's the output from --install on v1.17.2 just now.  No 404 error, no permission warning..

```
anomaly@scorched ~/src/atom $ sudo script/build --install
Password: 
Node:   v6.11.1
Npm:    v3.10.5
Installing script dependencies
Installing apm
Installing modules ✓
Wrote Dependencies Fingerprint: /home/anomaly/src/atom/node_modules/.dependencies-fingerprint 7bce5d94af6bf8b51b208ae7aa469d4befe37f5a
Cleaning /home/anomaly/src/atom/out
Copying assets to /home/anomaly/src/atom/out/app
Transpiling packages with custom transpiler configurations in /home/anomaly/src/atom/out/app
Transpiling Babel paths in /home/anomaly/src/atom/out/app
Transpiling CoffeeScript paths in /home/anomaly/src/atom/out/app
Transpiling CSON paths in /home/anomaly/src/atom/out/app
Transpiling PEG.js paths in /home/anomaly/src/atom/out/app
Generating module cache for /home/anomaly/src/atom/out/app
Generating pre-built less cache in /home/anomaly/src/atom/out/app/less-compile-cache
Generating metadata for /home/anomaly/src/atom/out/app/package.json
Generating API docs at /home/anomaly/src/atom/docs/output/atom-api.json
Dumping symbols in /home/anomaly/src/atom/out/symbols
Running electron-packager on /home/anomaly/src/atom/out/app with app name "atom"
Packaging app for platform linux x64 using electron v1.3.15
Changing permissions for node files in /home/anomaly/src/atom/out/atom-1.17.2-amd64
Copying non-ASAR resources to /home/anomaly/src/atom/out/atom-1.17.2-amd64/resources
Writing LICENSE.md to /home/anomaly/src/atom/out/atom-1.17.2-amd64/resources
Application bundle created at /home/anomaly/src/atom/out/atom-1.17.2-amd64
Generating snapshot script at "/home/anomaly/src/atom/out/startup.js" (2218)
Verifying if snapshot can be executed via `mksnapshot`
Generating startup blob at "/home/anomaly/src/atom/out/snapshot_blob.bin"
Moving generated startup blob into "/home/anomaly/src/atom/out/atom-1.17.2-amd64/snapshot_blob.bin"
Skipping creating debian package. Specify the --create-debian-package option to create it.
Skipping creating rpm package. Specify the --create-rpm-package option to create it.
Skipping artifacts compression. Specify the --compress-artifacts option to compress Atom binaries (and symbols on macOS)
Removing previously installed "atom-1.17.2-amd64" at "/usr/local/share/atom"
Installing "atom-1.17.2-amd64" at "/usr/local/share/atom"
Removing existing desktop entry file at "/usr/local/share/applications/atom.desktop"
Writing desktop entry file at "/usr/local/share/applications/atom.desktop"
Removing existing executable at "/usr/local/bin/atom"
Copying atom.sh to "/usr/local/bin/atom"
Removing existing executable at "/usr/local/bin/apm"
Symlinking apm to "/usr/local/bin/apm"
Changing permissions to 755 for "/usr/local/share/atom"

```

**Comment by anomaly256** [comment]
I notice this is still tagged 'more information needed' - what information do you need?

**Comment by anomaly256** [comment]
Still seeing this on 1.19.3 today.  Seems to build fine as my normal user, tries to fetch iojs and errors when installing as root via sudo.  I've tested running script/build --install=/home/<my user>/test and it works fine as long as it's not running under sudo if this gives any further clues as to what could be going wrong

**Comment by deprint** [comment]
Try `IOJS_ORG_MIRROR` instead of `ATOM_ELECTRON_URL`.

`IOJS_ORG_MIRROR=https://atom.io/download/electron script/build --install`

**Comment by anomaly256** [comment]
why would this fail when run under sudo but not fail when run as a normal user though (when installing to a non-system path)?  Shoving package sources into the environment doesn't seem to actually explain or address the root of the problem.  I can give this a go later to test but I don't think it's a solution
