### ISSUE TITLE
Uncaught Error: Cannot find pane for item in `PaneItem#activate`

### ISSUE THREAD

**Issue by nicholaswjr** [atom/atom#14876]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find pane for item in `PaneItem#activate`

```
At /home/andrei/atom-1.11.1/out/app/node_modules/tree-view/lib/file.coffee:171521

Error: Cannot find pane for item in `PaneItem#activate`
  at setTimeout (<embedded>:171521:21)

```

### Commands

```
     -2:47.1.0 core:undo (input.hidden-input)
     -2:45.9.0 intentions:highlight (input.hidden-input)
     -2:45 core:paste (input.hidden-input)
     -2:44.5.0 core:save (input.hidden-input)
     -1:59.8.0 core:backspace (input.hidden-input)
     -1:59.6.0 core:delete (input.hidden-input)
     -1:58.3.0 intentions:highlight (input.hidden-input)
     -1:58.2.0 core:save (input.hidden-input)
 26x -1:48.8.0 core:backspace (input.hidden-input)
     -1:37.8.0 intentions:highlight (input.hidden-input)
  2x -1:37.7.0 editor:move-to-beginning-of-word (input.hidden-input)
     -1:33.6.0 core:move-right (input.hidden-input)
     -1:32.7.0 core:backspace (input.hidden-input)
     -1:01.7.0 intentions:highlight (input.hidden-input)
     -1:01.4.0 editor:move-to-beginning-of-word (input.hidden-input)
  9x -0:22.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
busy-signal 1.4.3 
editorconfig 2.2.2 
go-debug 1.4.3 
go-plus 5.5.5 
go-signature-statusbar 1.2.0 
intentions 1.1.2 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.2 
minimap 4.28.2 
nuclide 0.232.0 
pigments 0.39.1 
react 0.16.2 
```

**Comment by rsese** [comment]
> At /home/andrei/atom-1.11.1/out/app/node_modules/tree-view/lib/file.coffee:171521

Hmmm, seems like it's coming from tree-view?  Can you re-open this in https://github.com/atom/tree-view/ @nicholaswjr and answer a few questions there so we can take a look?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by poddardelhi** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.30.4


### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module './winston/transports/transport'

Error: Cannot find module './winston/transports/transport'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/opt/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/opt/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (opt/atom/resources/app/static/index.js:40:43)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-beautify/node_modules/winston/lib/winston.js:37:26)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (opt/atom/resources/app/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-beautify/src/logger.coffee:10:13
    at /packages/atom-beautify/src/logger.coffee:4:18)
    at /packages/atom-beautify/src/logger.coffee:1:1)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (opt/atom/resources/app/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-beautify/src/beautifiers/index.coffee:6:10)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (opt/atom/resources/app/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-beautify/src/beautify.coffee:9:15)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/opt/atom/resources/app/src/compile-cache.js:239:29)
```

### Commands

```
     -0:35.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-beautify 0.30.4 
atom-html-preview 0.1.22 
atom-live-server 2.1.2 
atom-ternjs 0.18.3 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.9 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.2.0 
linter-php 1.3.2 
linter-ui-default 1.6.2 
minimap 4.28.3 
project-manager 3.3.5 
terminal-plus 0.14.5 
todo 0.6.0 
```
