### ISSUE TITLE
Uncaught TypeError: Cannot read property 'begin' of undefined

### ISSUE THREAD

**Issue by tedca886** [atom/atom#14972]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'begin' of undefined

```
At /Users/Terri/Downloads/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:286

TypeError: Cannot read property 'begin' of undefined
    at /Users/Terri/Downloads/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:286:28
    at Grammar.module.exports.Grammar.getRepository (/Users/Terri/Downloads/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:296:21)
    at Pattern.module.exports.Pattern.ruleForInclude (/Users/Terri/Downloads/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/pattern.js:157:35)
    at Pattern.module.exports.Pattern.getIncludedPatterns (/Users/Terri/Downloads/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/pattern.js:176:27)
    at Rule.module.exports.Rule.getIncludedPatterns (/Users/Terri/Downloads/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/rule.js:48:59)
    at Rule.module.exports.Rule.getScanner (/Users/Terri/Downloads/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/rule.js:62:29)
    at Rule.module.exports.Rule.findNextMatch (/Users/Terri/Downloads/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/rule.js:97:28)
    at Rule.module.exports.Rule.getNextTags (/Users/Terri/Downloads/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/rule.js:154:27)
    at Grammar.module.exports.Grammar.tokenizeLine (/Users/Terri/Downloads/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:164:50)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/Users/Terri/Downloads/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:359:33)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/Users/Terri/Downloads/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:347:25)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Users/Terri/Downloads/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:203:49)
    at /Users/Terri/Downloads/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:185:32
    at /Users/Terri/Downloads/Atom.app/Contents/Resources/app/node_modules/underscore/underscore.js:666:53
```

### Commands

```
     -3:25.6.0 markdown-preview:toggle (div.tool-panel.tree-view)
     -2:44.7.0 settings-view:install-packages-and-themes (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.19.4 
atom-runner 2.7.1 
css-spy 0.6.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/14972#issuecomment-314559109. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
