### ISSUE TITLE
Getting error "Uncaught TypeError: Cannot read property '_currentElement' of null" after updating Atom

### ISSUE THREAD

**Issue by TJDoesCode** [atom/atom#14970]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On Linux, I keep getting an error pop up. It happens after start up when trying to do anything. I updated from Atom 1.16 to 1.18 yesterday without any issues, and today this started being a thing.

### Steps to Reproduce

1. Open Atom
2. Start editing
3. Error pops up
4. Save
5. Error pops up again

**Expected behavior:** [What you expect to happen]

Honestly, nothing. This shouldn't be happening.

**Actual behavior:** [What actually happens]

Atom has a stroke with an error constantly popping up no matter how many times I close it.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% afaik

### Versions

Ubuntu 14.04 LTS
Atom 1.18.0 x64
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.6
git 1.9.1

### Additional Information

`
Uncaught TypeError: Cannot read property '_currentElement' of null
/usr/share/atom/resources/app/node_modules/fbjs/lib/resolveImmediate.js:27`

Stack trace:

`
TypeError: Cannot read property '_currentElement' of null
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:745:58)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:724:16)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:645:18)
    at ReactCompositeComponentWrapper.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:547:16)
    at Object.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:125:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:754:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:724:16)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:645:18)
    at ReactCompositeComponentWrapper.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:547:16)
    at Object.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:125:28)
    at Object.updateChildren (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactChildReconciler.js:109:31)
    at ReactDOMComponent._reconcilerUpdateChildren (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:213:34)
    at ReactDOMComponent._updateChildren (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:312:37)
    at ReactDOMComponent.updateChildren (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:299:18)
    at ReactDOMComponent._updateDOMChildren (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:936:18)
    at ReactDOMComponent.updateComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:754:16)
    at ReactDOMComponent.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:716:16)
    at Object.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:125:28)
    at Object.updateChildren (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactChildReconciler.js:109:31)
    at ReactDOMComponent._reconcilerUpdateChildren (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:213:34)
    at ReactDOMComponent._updateChildren (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:312:37)
    at ReactDOMComponent.updateChildren (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:299:18)
    at ReactDOMComponent._updateDOMChildren (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:936:18)
    at ReactDOMComponent.updateComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:754:16)
    at ReactDOMComponent.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:716:16)
    at Object.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:125:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:754:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:724:16)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:645:18)
    at ReactCompositeComponentWrapper.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:547:16)
    at Object.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:125:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:754:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:724:16)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:645:18)
    at ReactCompositeComponentWrapper.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:547:16)
    at Object.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:125:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:754:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:724:16)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:645:18)
    at ReactCompositeComponentWrapper.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:547:16)
    at Object.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:125:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:754:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:724:16)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:645:18)
    at ReactCompositeComponentWrapper.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:547:16)
    at Object.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:125:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:754:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:724:16)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:645:18)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:561:18)
    at Object.performUpdateIfNecessary (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:157:28)
    at runBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:150:27)
    at ReactReconcileTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:140:26)
    at ReactUpdatesFlushTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:140:26)
    at ReactUpdatesFlushTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:89:38)
    at Object.flushBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:172:25)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:206:31)
    at ReactDefaultBatchingStrategyTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:153:22)
    at Object.batchedUpdates (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:32)
    at Object.enqueueUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:200:28)
    at enqueueUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:24:22)
    at Object.enqueueSetState (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:219:11)
    at RelayRenderer.ReactComponent.setState (/usr/share/atom/resources/app/node_modules/react/lib/ReactComponent.js:63:22)
    at RelayReadyState.onReadyStateChange [as _onReadyStateChange] (/usr/share/atom/resources/app/node_modules/react-relay/lib/RelayRenderer.js:152:20)
    at /usr/share/atom/resources/app/node_modules/react-relay/lib/RelayReadyState.js:73:19
    at tryCallOne (/usr/share/atom/resources/app/node_modules/promise/lib/core.js:37:18)
    at /usr/share/atom/resources/app/node_modules/promise/lib/core.js:123:21
    at flush (/usr/share/atom/resources/app/node_modules/asap/raw.js:50:35)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

Additionally, on start up I get this error once:
`
Uncaught TypeError: Cannot read property 'url' of null
/usr/share/atom/resources/app/node_modules/fbjs/lib/resolveImmediate.js:27```

Stack trace: 

`
TypeError: Cannot read property 'url' of null
    at PrInfo.render (/usr/share/atom/resources/app/node_modules/github/lib/containers/pr-info-container.js:115:67)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:799:36)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:822:38)
    at ReactCompositeComponentWrapper.performInitialMount (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:362:36)
    at ReactCompositeComponentWrapper.mountComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:258:27)
    at Object.mountComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:46:41)
    at ReactCompositeComponentWrapper.performInitialMount (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:371:40)
    at ReactCompositeComponentWrapper.mountComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:258:27)
    at Object.mountComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:46:41)
    at ReactDOMComponent.mountChildren (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:238:50)
    at ReactDOMComponent._createInitialChildren (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:697:38)
    at ReactDOMComponent.mountComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:516:18)
    at Object.mountComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:46:41)
    at ReactDOMComponent.mountChildren (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:238:50)
    at ReactDOMComponent._createInitialChildren (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:697:38)
    at ReactDOMComponent.mountComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:516:18)
    at Object.mountComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:46:41)
    at ReactCompositeComponentWrapper.performInitialMount (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:371:40)
    at ReactCompositeComponentWrapper.mountComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:258:27)
    at Object.mountComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:46:41)
    at ReactCompositeComponentWrapper.performInitialMount (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:371:40)
    at ReactCompositeComponentWrapper.mountComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:258:27)
    at Object.mountComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:46:41)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:765:46)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:724:16)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:645:18)
    at ReactCompositeComponentWrapper.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:547:16)
    at Object.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:125:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:754:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:724:16)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:645:18)
    at ReactCompositeComponentWrapper.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:547:16)
    at Object.receiveComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:125:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:754:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:724:16)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:645:18)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:561:18)
    at Object.performUpdateIfNecessary (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:157:28)
    at runBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:150:27)
    at ReactReconcileTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:140:26)
    at ReactUpdatesFlushTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:140:26)
    at ReactUpdatesFlushTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:89:38)
    at Object.flushBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:172:25)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:206:31)
    at ReactDefaultBatchingStrategyTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:153:22)
    at Object.batchedUpdates (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:32)
    at Object.enqueueUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:200:28)
    at enqueueUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:24:22)
    at Object.enqueueSetState (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:219:11)
    at RelayRenderer.ReactComponent.setState (/usr/share/atom/resources/app/node_modules/react/lib/ReactComponent.js:63:22)
    at RelayReadyState.onReadyStateChange [as _onReadyStateChange] (/usr/share/atom/resources/app/node_modules/react-relay/lib/RelayRenderer.js:152:20)
    at /usr/share/atom/resources/app/node_modules/react-relay/lib/RelayReadyState.js:73:19
    at tryCallOne (/usr/share/atom/resources/app/node_modules/promise/lib/core.js:37:18)
    at /usr/share/atom/resources/app/node_modules/promise/lib/core.js:123:21
    at flush (/usr/share/atom/resources/app/node_modules/asap/raw.js:50:35)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

That error is telling me that it was thrown from the github package.

The error I mentioned before the one above is persistent and after dismissing it, it will pop up over and over again.

**Comment by TJDoesCode** [comment]
Update: This was being caused by the PR tab of the new GitHub integration failing to load or something? I closed that tab and the error went away. It was only happening for one project, and I'm not sure why, but closing the "GitHub (preview)" tab appeared to fix it, at least temporarily.

**Comment by rsese** [comment]
Thanks for the report!

> Update: This was being caused by the PR tab of the new GitHub integration failing to load or something? I closed that tab and the error went away. It was only happening for one project, and I'm not sure why, but closing the "GitHub (preview)" tab appeared to fix it, at least temporarily.

Just to confirm, have you hit this error again?  If so, is the error still tied to having the GitHub package open?  Just checking so we can move this over to https://github.com/atom/github if it is specific to that package.

**Comment by mickaelpham** [comment]
@rsese I can confirm that closing the GitHub PR tab fixes the issue for me, so please go ahead and move it to https://github.com/atom/github

**Comment by rsese** [comment]
@mickaelpham - with the GitHub PR tab open, is the error reproducible for you in safe mode?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our questions in https://github.com/atom/atom/issues/14970#issuecomment-316860331 and https://github.com/atom/atom/issues/15092#issuecomment-318189598.  With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
