### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by tsuie** [atom/atom#14990]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught SyntaxError: Invalid or unexpected token

```
At /home/andrei/atom-1.11.1/out/app/node_modules/tree-view/lib/file.coffee:7391

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (opt/atom/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/opt/atom/resources/app/static/<embedded>:96:26)
    at get_CommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:22:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:607:38)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  2x -0:45.8.0 core:close (atom-pane.pane.active)
  4x -0:17.9.0 editor:consolidate-selections (input.hidden-input)
```

### Non-Core Packages

```
tree-view-git-status 1.4.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our questions in this comment https://github.com/atom/atom/issues/14990#issuecomment-315287796. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by vasconce7os** [comment]
**I have a same problem**
## 
**Uncaught SyntaxError: Invalid or unexpected token**

/usr/share/atom/resources/app/node_modules/first-mate/lib/pattern.js:264

## 
**Stack Trace**

SyntaxError: Invalid or unexpected token
    at Pattern.module.exports.Pattern.tagsForCaptureIndices (/usr/share/atom/resources/app/node_modules/first-mate/lib/pattern.js:296:34)
    at Pattern.module.exports.Pattern.tagsForCaptureIndices (/usr/share/atom/resources/app/node_modules/first-mate/lib/pattern.js:314:36)
    at Pattern.module.exports.Pattern.handleMatch (/usr/share/atom/resources/app/node_modules/first-mate/lib/pattern.js:224:42)
    at Scanner.module.exports.Scanner.handleMatch (/usr/share/atom/resources/app/node_modules/first-mate/lib/scanner.js:69:28)
    at Rule.module.exports.Rule.getNextTags (/usr/share/atom/resources/app/node_modules/first-mate/lib/rule.js:161:36)
    at Grammar.module.exports.Grammar.tokenizeLine (/usr/share/atom/resources/app/node_modules/first-mate/lib/grammar.js:164:50)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/usr/share/atom/resources/app/src/tokenized-buffer.js:380:33)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/usr/share/atom/resources/app/src/tokenized-buffer.js:368:25)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/usr/share/atom/resources/app/src/tokenized-buffer.js:224:49)
    at /usr/share/atom/resources/app/src/tokenized-buffer.js:206:32
    at /usr/share/atom/resources/app/node_modules/underscore/underscore.js:666:53

##
**the button "View Issue" threw me here**

**Comment by rsese** [comment]
Can you reproduce in safe mode @vasconce7os (`atom --safe`)?

**Comment by vasconce7os** [comment]
@rsese, I think that no

**Comment by rsese** [comment]
Ahhh ok @vasconce7os - in that case it's likely an issue with one of your community packages.  One way to narrow things down is to disable all installed packages and then enable them one-by-one until you can reproduce. Or if you have a lot of installed packages, https://atom.io/packages/package-cop might be helpful too.
