### ISSUE TITLE
Build fails on 64-bit Slackware during snapshot generation ASSERTION error

### ISSUE THREAD

**Issue by capouch** [atom/atom#15016]
### Description
Build process fails on Slackware64 Linux during snapshot generation: 

### Steps to Reproduce

1. clone atom repo
2. ./scripts/build --install
3. Fails during generation of snapshot with ASSERTION error

**Expected behavior:** [What you expect to happen]
Clean build

**Actual behavior:** [What actually happens]
Crashes, output below

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Additional Information
Node v8.1.3 NPM 3.10.5

Build system output:

`Application bundle created at /home/brianc/atom/out/atom-1.20.0-dev-9be492fcb-amd64
Generating snapshot script at "/home/brianc/atom/out/startup.js" (71)AssertionError [ERR_ASSERTION]: /home/brianc/atom/out/app/node_modules/github/node_modules/temp/lib/temp.js
Assigning a deferred module to a variable that was not declared in this scope is not supported!`

 ` at FileRequireTransform.replaceAssignmentOrDeclarationWithLazyFunction (/home/brianc/atom/script/node_modules/electron-link/lib/file-require-transform.js:124:9)`

  `at Context.visitIdentifier (/home/brianc/atom/script/node_modules/electron-link/lib/file-require-transform.js:72:18)
  at Context.invokeVisitorMethod (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:344:49)
  at Visitor.PVp.visitWithoutReset (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:196:32)
  at visitChildren (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:204:20)
  at NodePath.each (/home/brianc/atom/script/node_modules/ast-types/lib/path.js:101:26)
  at visitChildren (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:219:18)
  at Visitor.PVp.visitWithoutReset (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:204:20)
  at Visitor.PVp.visit (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:133:29)
  at Object.visit (/home/brianc/atom/script/node_modules/ast-types/lib/path-visitor.js:101:55)
  at FileRequireTransform.replaceDeferredRequiresWithLazyFunctions (/home/brianc/atom/script/node_modules/electron-link/lib/file-require-transform.js:68:20)
  at FileRequireTransform.apply (/home/brianc/atom/script/node_modules/electron-link/lib/file-require-transform.js:25:10)
  at /home/brianc/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:52:54
  at Generator.next (<anonymous>:null:null)
  at step (/home/brianc/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:191)
  at /home/brianc/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:361
  at <anonymous>:null:null
`

**Comment by capouch** [comment]
Build proceeds fine now with latest pull from git master.
