### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'nuclide:/our.hakobyant.sb.facebook.com/d...

### ISSUE THREAD

**Issue by hakobyant** [atom/atom#15020]
[Enter steps to reproduce:]

1. Create a png file, let's say using python matplotlib.pyplot.plot.
2. Try opening the png file.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'nuclide:/our.hakobyant.sb.facebook.com/data/users/hakobyant/fbsource/fbcode/experimental/hakobyant/cxlab/catalina/0% coverage.png'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat 'nuclide:/our.hakobyant.sb.facebook.com/data/users/hakobyant/fbsource/fbcode/experimental/hakobyant/cxlab/catalina/0% coverage.png'
  at Error (native)
  at fs.statSync (fs.js:992:18)
  at Proxy.fs.statSync (ELECTRON_ASAR.js:275:16)
  at new ImageEditorView (<embedded>:94758:48)
  at ImageEditor.get (<embedded>:49092:33)
  at ImageEditor.get (<embedded>:49086:24)
  at ViewRegistry.module.exports.ViewRegistry.createView (<embedded>:16995:41)
  at ViewRegistry.module.exports.ViewRegistry.getView (<embedded>:16978:27)
  at atom-pane.PaneElement.itemRemoved (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:186:37)
  at Function.module.exports.Emitter.simpleDispatch (<embedded>:63093:20)
  at Emitter.module.exports.Emitter.emit (<embedded>:63209:34)
  at Pane.module.exports.Pane.removeItem (<embedded>:26175:26)
  at Pane.module.exports.Pane.destroyItem (<embedded>:26247:22)
  at TabBarView.module.exports.TabBarView.closeTab (<embedded>:59806:32)
  at HTMLDivElement.TabView.didClickCloseIcon (<embedded>:59694:25)

```

### Commands

```
  2x -3:52.4.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling)
  4x -1:54.6.0 nuclide-remote-projects:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:32 nuclide-file-tree:set-current-working-root (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-directory.name.nuclide-file-tree-path.icon-nuclicon-file-directory)
```

### Non-Core Packages

```
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.65.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.3 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
nuclide 0.239.64922622 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by lee-dohm** [comment]
Given the file path, this appears to be a problem with Nuclide. You should probably refer to the Nuclide support resources https://nuclide.io/support/.
