### ISSUE TITLE
Building on Mac OS X with Node v8.1.4 fails

### ISSUE THREAD

**Issue by wvanlint** [atom/atom#15037]
Running `script/build` from a clean client on Mac OS X with Node v8.1.4 and npm v5.0.3 seems to result in build errors. @lee-dohm was able to reproduce this on his end too.

The errors:
```
Error: Module version mismatch. Expected 48, got 57.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willem/dev/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/Users/willem/dev/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:570:32)
child_process.js:611
    throw err;
    ^

Error: Command failed: /Users/willem/dev/atom/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:588:13)
    at Object.execFileSync (child_process.js:608:13)
    at module.exports (/Users/willem/dev/atom/script/lib/run-apm-install.js:14:16)
    at Object.<anonymous> (/Users/willem/dev/atom/script/bootstrap:29:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

FYI, the line in `git-utils/lib/git.js:8` is `Repository = require('../build/Release/git.node').Repository;`.

**Comment by kevinchau321** [comment]
I'm getting this issue as well! I believe it has to do with the fact that you can't build apm with node 8.1.4, someone correct me if I'm wrong about this.

**Comment by lee-dohm** [comment]
It sounds like #15041 should fix this.
