### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by VladimirHumeniuk** [atom/atom#15042]
**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Linux Mint
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'firstChild' of undefined

```
At /usr/share/atom-beta/resources/app/src/text-editor-component.js:2110

TypeError: Cannot read property 'firstChild' of undefined
    at TextEditorComponent.measureLongestLineWidth (/usr/share/atom-beta/resources/app/src/text-editor-component.js:2110:112)
    at TextEditorComponent.measureContentDuringUpdateSync (/usr/share/atom-beta/resources/app/src/text-editor-component.js:381:16)
    at scheduler.readDocument (/usr/share/atom-beta/resources/app/src/text-editor-component.js:266:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom-beta/resources/app/src/view-registry.js:191:15)
    at /usr/share/atom-beta/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -0:43 core:select-all (input.hidden-input)
     -0:41.6.0 core:paste (input.hidden-input)
     -0:39 core:backspace (input.hidden-input)
     -0:35 core:save (input.hidden-input)
     -0:33.3.0 intentions:highlight (input.hidden-input)
     -0:33.2.0 core:save (input.hidden-input)
     -0:32.5.0 intentions:highlight (input.hidden-input)
     -0:32.4.0 core:undo (input.hidden-input)
     -0:32.1.0 intentions:highlight (input.hidden-input)
     -0:32 core:save (input.hidden-input)
     -0:31.7.0 intentions:highlight (input.hidden-input)
     -0:16.5.0 core:select-all (input.hidden-input)
     -0:16.2.0 core:cut (input.hidden-input)
  2x -0:15.9.0 core:save (input.hidden-input)
     -0:10.3.0 intentions:highlight (input.hidden-input)
     -0:10.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.1.0 
aligner 1.2.3 
aligner-javascript 1.2.0 
apex-syntax 0.1.0 
apex-ui 0.2.1 
atom-beautify 0.30.3 
atom-clock 0.1.13 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
atom-monokai 0.10.9 
atom-typescript 11.0.6 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
busy-signal 1.4.3 
css-comb 2.5.0 
dash-syntax 0.3.0 
dash-ui 0.4.0 
dimmed-monokai 0.1.0 
emmet 2.4.3 
find-trailing-whitespace 0.1.0 
git-time-machine 1.5.9 
gruvbox-plus-syntax 1.3.1 
Hydrogen 1.19.0 
intentions 1.1.2 
language-babel 2.67.0 
language-markdown 0.25.1 
language-postcss 1.3.1 
language-pug 0.0.21 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.2 
linter-write-good 0.9.0 
markdown-preview-plus 2.4.10 
markdown-writer 2.6.5 
material-monokai-syntax 1.0.1 
material-ui 1.0.10 
matte-black-ui 0.2.0 
monokai-blackboard 0.3.0 
monokai-dark 1.3.0 
monokai-pro 0.1.0 
monokai-seti 0.9.0 
now-syntax 0.2.4 
pigments 0.39.1 
platformio-ide-terminal 2.5.3 
postcss-sorting 2.10.0 
pristine-ui 1.1.0 
pure-syntax 0.2.1 
seti-classic 0.10.3 
seti-syntax 1.1.3 
seti-ui 1.9.0 
seti-ui-red 0.13.0 
tabs-to-spaces 1.0.3 
terminal-plus 0.14.5 
toggle-quotes 1.0.1 
Untitled Folder undefined 
wakatime 7.0.3 
```

**Comment by maxbrunsfeld** [comment]
/cc @nathansobo Here's another issue we should close when that TextEditorComponent bug is fixed.

Thanks for the report @VladimirHumeniuk, we're working on a fix!

**Comment by pietrodn** [comment]
I still get this error on Atom 1.19.1.
I just opened a project, opened a file and changed the font size with Command-Minus.

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'firstChild' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2171

TypeError: Cannot read property 'firstChild' of undefined
    at TextEditorComponent.measureLongestLineWidth (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2171:112)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:383:16)
    at scheduler.readDocument (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:270:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
     -1:00.9.0 application:reopen-project (atom-pane.pane.active)
     -0:56.3.0 window:decrease-font-size (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
autocomplete-python 1.10.1 
build 0.68.0 
build-make 0.13.0 
busy 0.7.0 
busy-signal 1.4.3 
dash 1.7.1 
docblockr 0.11.0 
intentions 1.1.5 
language-apache 1.7.0 
language-latex 1.1.0 
language-x86-64-assembly 2.2.11 
latexer 0.3.0 
linter 2.2.0 
linter-flake8 2.2.1 
linter-ui-default 1.6.5 
native-ui 0.22.0 
platformio-ide-terminal 2.5.5 
pretty-json 1.6.4 
python-indent 1.1.0 
python-tools 0.6.9 
sort-lines 0.14.0 
sourcerer 2.0.0 
split-diff 1.4.3 
```

**Comment by Ben3eeE** [comment]
@pietrodn Thank you for the report 🙇 We just got another report of this issue in https://github.com/atom/atom/issues/15311 so we are tracking it there.

**Comment by Arima-P** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'firstChild' of undefined

```
At C:\Users\pigle\AppData\Local\atom\app-1.19.1\resources\app\src\text-editor-component.js:2171

TypeError: Cannot read property 'firstChild' of undefined
    at TextEditorComponent.measureLongestLineWidth (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:2171:112)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:383:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:270:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.19.1/resources/app/src/view-registry.js:191:15)
    at ~/AppData/Local/atom/app-1.19.1/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -0:38.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:33.4.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.2.0 
atom-beautify 0.30.5 
emmet 2.4.3 
file-icons 2.1.10 
jshint 1.8.6 
pigments 0.40.2 
seti-syntax 1.1.3 
seti-ui 1.9.0 
``
