### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by umpirsky** [atom/atom#15055]
Added code like this:

```php
use Foo\Bar;
use Yay;
use Foo\Baz;
```

Where `Yay` is not defined.

**Atom**: 1.19.0-beta4 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At /usr/share/atom-beta/resources/app/src/text-editor-component.js:2148

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (/usr/share/atom-beta/resources/app/src/text-editor-component.js:2148:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/usr/share/atom-beta/resources/app/src/text-editor-component.js:2144:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/usr/share/atom-beta/resources/app/src/text-editor-component.js:380:16)
    at scheduler.readDocument (/usr/share/atom-beta/resources/app/src/text-editor-component.js:264:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom-beta/resources/app/src/view-registry.js:191:15)
    at /usr/share/atom-beta/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -0:43.8.0 core:save (input.hidden-input)
     -0:43 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:40.7.0 intentions:highlight (input.hidden-input)
     -0:40.7.0 core:save (input.hidden-input)
     -0:39.3.0 intentions:highlight (input.hidden-input)
     -0:38.4.0 core:move-to-top (input.hidden-input)
  3x -0:32.5.0 core:move-down (input.hidden-input)
     -0:31.8.0 docblockr:parse-enter (input.hidden-input)
     -0:31.8.0 editor:newline (input.hidden-input)
     -0:31.7.0 intentions:highlight (input.hidden-input)
     -0:31.6.0 core:paste (input.hidden-input)
     -0:30.2.0 intentions:highlight (input.hidden-input)
  3x -0:30.1.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:27.8.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:26.3.0 intentions:highlight (input.hidden-input)
     -0:26.3.0 core:move-to-top (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.4 
busy-signal 1.4.3 
change-case 0.6.5 
docblockr 0.11.0 
hyperclick 0.1.2 
intentions 1.1.2 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-jshint 3.1.5 
linter-php 1.3.2 
linter-ui-default 1.6.2 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.0 
php-integrator-base 3.0.1 
php-integrator-navigation 1.2.1 
php-integrator-refactoring 1.4.0 
php-twig 4.0.0 
project-manager 3.3.5 
```

**Comment by 50Wliu** [comment]
This has been fixed and will be released in the next Atom 1.19.0-beta hotfix.
