### ISSUE TITLE
Trouble building Atom on Windows 10

### ISSUE THREAD

**Issue by KvalheimRacing** [atom/atom#15061]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Tried for a while now to build atom on W10. Looked at every other isue relating, but with no luck.

Here is my error log; [raw_file](https://github.com/KvalheimRacing/atom-transparency/blob/master/npm-debug.log)

tried script/clean, and script/bootstrap, also, aswell as  ./script/build --create-windows-installer. No luck. I have another version of atom some place else, but that should not be a problem right? Tried, npm2, npm3 and now on npm5. 

did a `npm install -g node-gyp-install`, but no luck.

Here is the console output/build log:

```
21:53:04 Wed Jul 19 $ ./script/build
Node:   v6.11.1
Npm:    v5.3.0
Python: v2.7.13
Installing script dependencies
prebuild-install info begin Prebuild-install version 2.2.0
prebuild-install info looking for local prebuild @ prebuilds\leveldown-v1.7.2-node-v48-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\eirik\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v48-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\eirik\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v48-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\atom\script\node_modules\leveldown\build\Release\leveldown.node
prebuild-install info unpack required C:\atom\script\node_modules\leveldown\build\Release\leveldown.node successfully
prebuild-install info install Prebuild successfully installed!
Installing apm
(node:15288) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\atom\script\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\atom\\script\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\atom\apm\node_modules\atom-package-manager\node_modules\keytar
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\atom\script\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\atom\\script\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\atom\apm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\oniguruma
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\atom\script\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\atom\\script\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\atom\apm\node_modules\atom-package-manager\node_modules\git-utils
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\atom\\script\\node_modules\\npm\\bin\\npm-cli.js" "--global-style" "--loglevel=error" "install"
npm ERR! node v6.11.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! keytar@4.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@4.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\atom\apm\npm-debug.log
child_process.js:504
    throw err;
    ^

Error: Command failed: C:\atom\script\node_modules\.bin\npm.cmd --global-style --loglevel=error install
(node:15288) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\atom\script\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\atom\\script\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\atom\apm\node_modules\atom-package-manager\node_modules\keytar
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\atom\script\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\atom\\script\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\atom\apm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\oniguruma
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\atom\script\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\atom\\script\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\atom\apm\node_modules\atom-package-manager\node_modules\git-utils
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\atom\\script\\node_modules\\npm\\bin\\npm-cli.js" "--global-style" "--loglevel=error" "install"
npm ERR! node v6.11.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! keytar@4.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@4.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\atom\apm\npm-debug.log

    at checkExecSyncError (child_process.js:481:13)
    at Object.execFileSync (child_process.js:501:13)
    at module.exports (C:\atom\script\lib\install-apm.js:9:16)
    at Object.<anonymous> (C:\atom\script\bootstrap:29:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

### Versions

- OS: Win 10 64 bit
- Node:   v6.11.1 (64 bit)
- Npm:    v5.3.0
- Python: v2.7.13
- 7-Zip [64] 16.04
- git version 2.10.2.windows.1
- PYTHON=C:\Python27\python.exe
- node-gyp@3.6.2

**Comment by KvalheimRacing** [comment]
Maybe worth mentioning that using apm gives me this;

```
22:37:06 Wed Jul 19 $ apm

apm - Atom Package Manager powered by https://atom.io

Usage: apm <command>

where <command> is one of:
    clean, config, dedupe, deinstall, delete, dev, develop, disable, docs,
    enable, erase, featured, home, i, init, install, link, linked, links, list,
    ln, lns, login, ls, open, outdated, publish, rebuild, rebuild-module-cache,
    remove, rm, search, show, star, starred, stars, test, uninstall, unlink,
    unpublish, unstar, update, upgrade, view.

Run `apm help <command>` to see the more details about a specific command.

Options:
  --color        Enable colored output                                     [boolean] [default: true]
  -v, --version  Print the apm version
  -h, --help     Print this usage message

  Prefix an option with `no-` to set it to false such as --no-color to disable
  colored output.
```

and then;

```
22:37:11 Wed Jul 19 $ apm -v
internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at EventEmitter.<anonymous> (C:\Users\eirik\AppData\Local\atom\app-1.18.0\resources\app\apm\lib\apm-cli.js:150:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

problems with apm here @damieng, what do you think ?

**Comment by damieng** [comment]
What version of Visual Studio or the Microsoft C++ build tools do you have installed?

**Comment by KvalheimRacing** [comment]
VS community 2017. I am using git bash to build the script though. Is there a way in VS?

**Comment by damieng** [comment]
VS 2017 isn't supported for building Atom yet. The underlying tool npm uses to build native modules (nodegyp) only got updated to support 2017 last month.

In the mean time you can install just the VS2015 C++ Build tools to get going.  https://www.npmjs.com/package/windows-build-tools makes it easy to install those directly from npm.

Full details of what is required and supported to build Atom on Windows can be found in our documentation at https://github.com/atom/atom/blob/master/docs/build-instructions/windows.md
