### ISSUE TITLE
Uncaught Error: Cannot find module 'is-finite'

### ISSUE THREAD

**Issue by Freivincampbell** [atom/atom#15063]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module 'is-finite'

```
At module.js:457

Error: Cannot find module 'is-finite'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (usr/share/atom/resources/app/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/repeating/index.js:2:16)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/babel-core/lib/traversal/scope/index.js:24:18)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/babel-core/lib/traversal/path/index.js:28:14)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/babel-core/lib/traversal/context.js:16:13)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/babel-core/lib/traversal/index.js:13:16)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

### Commands

```
     -0:26 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-material-ui 2.0.4 
auto-indent 0.5.0 
autocomplete-ruby 0.2.8 
busy-signal 1.4.3 
chester-atom-syntax 0.2.0 
execute-as-ruby 0.2.1 
file-icons 2.1.9 
gloom 0.6.4 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.2.0 
linter-rubocop 2.1.1 
linter-ruby 1.2.5 
linter-ui-default 1.6.3 
loved-syntax 1.0.2 
minimap 4.29.0 
minimap-highlight-selected 4.6.1 
nord-atom-ui 0.11.0 
pristine-ui 1.1.0 
pure-syntax 0.3.0 
ramda-syntax 1.0.4 
ruby-block 0.3.6 
```

**Comment by rsese** [comment]
Thanks for the report!  There's been a few of this type of issue since `1.17.0` e.g. https://github.com/atom/atom/issues/14708 and https://github.com/atom/atom/issues/14461.  I'll go ahead and close as dupe for now and ask the team to take a look.
