### ISSUE TITLE
Uncaught Error: Requested measurement of a line that is not currently rendered

### ISSUE THREAD

**Issue by PipC** [atom/atom#15068]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta4 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line that is not currently rendered

```
At C:\Users\pipch\AppData\Local\atom\app-1.19.0-beta4\resources\app\src\text-editor-component.js:2153

Error: Requested measurement of a line that is not currently rendered
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.19.0-beta4/resources/app/src/text-editor-component.js:2151:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.19.0-beta4/resources/app/src/text-editor-component.js:2144:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.0-beta4/resources/app/src/text-editor-component.js:380:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.19.0-beta4/resources/app/src/text-editor-component.js:264:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.19.0-beta4/resources/app/src/view-registry.js:191:15)
    at ~/AppData/Local/atom/app-1.19.0-beta4/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -4:42.4.0 tree-view:remove (li.file.entry.list-item.selected)
     -4:36.8.0 intentions:highlight (input.hidden-input)
     -4:36.4.0 core:copy (input.hidden-input)
     -1:32.7.0 intentions:highlight (input.hidden-input)
     -1:32.6.0 core:select-all (input.hidden-input)
     -1:32.3.0 intentions:highlight (input.hidden-input)
     -1:32.2.0 core:paste (input.hidden-input)
     -1:19.7.0 intentions:highlight (input.hidden-input)
     -1:19.6.0 core:paste (input.hidden-input)
     -1:17.3.0 intentions:highlight (input.hidden-input)
     -1:16.9.0 core:save (input.hidden-input)
     -0:30.7.0 intentions:highlight (input.hidden-input)
     -0:30.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
Atom-Bash-Snippets 0.0.3 
atom-beautify 0.30.4 
atom-grails 1.0.1 
atom-material-ui 2.0.4 
atom-shell-commands 1.5.0 
busy-signal 1.4.3 
file-types 0.5.5 
fold-functions 0.5.0 
format-sql 0.3.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
incremental-search 5.2.2 
intentions 1.1.2 
language-apache 1.7.0 
language-awk 0.1.12 
language-batch 0.4.0 
language-generic-config 1.3.0 
language-groovy 0.7.0 
language-tsql 0.19.0 
language-vb 0.1.0-pre1 
language-vba 0.2.5 
language-vue 0.23.0 
language-vue-component 0.5.0 
linter 2.2.0 
linter-ui-default 1.6.3 
minimap 4.29.0 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
quick-query-mssql 0.1.4 
split-diff 1.4.3 
Sublime-Style-Column-Selection 1.7.4 
tree-view-filter 0.5.3 
vue-autocomplete 0.1.1 
vue-format 0.4.0 
vue-snippets 0.6.0 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by 50Wliu** [comment]
This will be fixed in the next Atom 1.19.0-beta.
