### ISSUE TITLE
Uncaught TypeError: validateEventDispatches is not a function

### ISSUE THREAD

**Issue by technomage** [atom/atom#15093]
[Enter steps to reproduce:]

1. Restarted Atom after mouse scrolling got jumpy.  Using Elixir language plugins primarily.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: validateEventDispatches is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginUtils.js:97

TypeError: validateEventDispatches is not a function
    at Object.executeDispatchesInOrder (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginUtils.js:97:11)
    at executeDispatchesAndRelease (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginHub.js:43:28)
    at executeDispatchesAndReleaseTopLevel (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginHub.js:54:16)
    at Array.forEach (native)
    at forEachAccumulated (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/forEachAccumulated.js:24:15)
    at Object.processEventQueue (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginHub.js:257:13)
    at runEventQueueInBatch (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventEmitterMixin.js:17:24)
    at Object.handleTopLevel [as _handleTopLevel] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventEmitterMixin.js:28:11)
    at handleTopLevelImpl (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventListener.js:72:30)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/Transaction.js:140:26)
    at Object.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:32)
    at Object.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactUpdates.js:97:33)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventListener.js:147:26)
```

### Commands

```
```

### Non-Core Packages

```
atom-elixir 0.2.3 
autocomplete-elixir 1.5.14 
busy-signal 1.4.1 
intentions 1.1.2 
language-babel 2.65.0 
language-elixir 0.17.0 
language-plantuml 0.2.0 
linter 2.1.4 
linter-csslint 1.3.4 
linter-elixirc 1.6.0 
linter-eslint 8.2.1 
linter-htmlhint 1.3.3 
linter-jshint 3.1.2 
linter-ui-default 1.6.0 
open-recent 5.0.0 
pigments 0.39.1 
plantuml-preview 0.12.9 
pretty-json 1.6.3 
project-manager 3.3.4 
```

**Comment by technomage** [comment]
This error is repeating on very mouse click, and requires two clicks on a file to get it to open.

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible in safe mode (atom --safe)?

**Comment by JSmith2412** [comment]
Hi there - I'm also having this problem (Win. 10 64 bit) I noticed it after installing meteor-helper. In safe mode I am not able to reproduce the problem, neither am I able to to start meteor-helper (might be expected, I'm new to Atom :) ).

**Comment by 50Wliu** [comment]
Unfortunately it looks like notifications is truncating the stack trace before the actual package is revealed.

**Comment by rhyeal** [comment]
I just went through my atom packages one by one. The package it seems that generates these errors is `atom-elixir 0.2.3` for me. I'm getting the same error message on every mouse click within the Atom window.

**Comment by rsese** [comment]
From https://github.com/atom/atom/issues/15256:

> 1. Click anywhere on the Atom window
> 2. 2 notifications pop up
> 3. Closing the notifications with Close All shows 2 new notifications, one saying it is a bug in Atom, one saying it is coming from linter-ui-default

**Comment by abate** [comment]
Same problem here installing the meteor-helper package with the latest atom-beta package

**Comment by jastorgalj** [comment]
Same problem

**Comment by timkelty** [comment]
I get this error when using AtomLinter w/ stylelint-linter.

It happens when I have a `.stylelintrc.js` like so, which is getting the config obj from an api:
```js
const {Neutrino} = require('neutrino');
const {resolve} = require('path');

module.exports = Neutrino()
  .use(resolve(__dirname, '.neutrinorc.js'))
  .call('stylelintrc');
```

If I instead copy the returned object and export that, it works fine.

**Comment by timkelty** [comment]
As noted above, I was having this issue with `linter` `linter-stylelint`

I managed to track it down to a small repro-case…in my case it appears to be related to having code that sets `process.env.NODE_ENV = 'development'`.

## Steps to reproduce:
1. `apm install linter linter-stylelint`
2. create a `.stylelintrc.js` file containing:
```
  process.env.NODE_ENV = 'development';

  module.exports = {
    rules: {}
  };
```
3. every click now triggers this error


/cc @rsese

**Comment by rsese** [comment]
Thanks so much @timkelty - looks like I can reproduce with just this:

1. Start Atom in safe mode `atom --safe`
2. In devtools console run `process.env.NODE_ENV="development"`
3. Click anywhere within the Atom window

Not sure if it's the exact same issue as https://github.com/atom/github/issues/833 but seems related at the least?

**Comment by nwaywood** [comment]
Not sure if this helps or not but I am having the same issue with eslint.

I get the error when I have this as my `.eslintrc.js`:

```js
const { Neutrino } = require('neutrino');

module.exports = Neutrino()
  .use('.neutrinorc.js')
  .call('eslintrc');
```

But if I copy the returned object and return that instead then it works fine. 

Please let me know if I can provide any more information to help with the issue

**Comment by timkelty** [comment]
@nwaywood. I’m sure it’s the same issue I’m seeing (with neutrino as well).

Hopefully we can get it sorted!

**Comment by mic-rigaud** [comment]
Same error when I start meteor-helper package.
