### ISSUE TITLE
Uncaught TypeError: Cannot read property '__reactInternalInstance$g4cwg2iovuf1pbydj3bzw7b9' of null

### ISSUE THREAD

**Issue by UnicornsOnLSD** [atom/atom#15099]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property '__reactInternalInstance$g4cwg2iovuf1pbydj3bzw7b9' of null

```
At C:\Users\James\AppData\Local\atom\app-1.18.0\resources\app\node_modules\react-dom\lib\ReactDOMComponentTree.js:113

TypeError: Cannot read property '__reactInternalInstance$g4cwg2iovuf1pbydj3bzw7b9' of null
    at Object.getClosestInstanceFromNode (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/ReactDOMComponentTree.js:113:17)
    at findParent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/ReactEventListener.js:38:38)
    at handleTopLevelImpl (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/ReactEventListener.js:67:34)
    at ReactDefaultBatchingStrategyTransaction.perform (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/Transaction.js:143:26)
    at Object.batchedUpdates (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:32)
    at Object.batchedUpdates (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/ReactUpdates.js:97:33)
    at dispatchEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/ReactEventListener.js:147:26)
```

### Commands

```
     -2:13.6.0 welcome:show (input.hidden-input)
     -2:09.1.0 github:toggle-git-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
git-plus 7.9.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by UnicornsOnLSD** [comment]
- I was opening the Github panel via the options menu

- Tried it again with the same package installed, didn't happen. May have just been a flook.

**Comment by rsese** [comment]
> Tried it again with the same package installed, didn't happen. May have just been a flook.

👍 - since it's not reproducible, we'll go ahead and close for now but please let us know if you run into it again.  And since it sounds related to the GitHub package, if you do see the error again, feel free to open an issue in the package repository:

https://github.com/atom/github
