### ISSUE TITLE
Uncaught Error: Unknown system error -122: Unknown system error -122, close

### ISSUE THREAD

**Issue by t-eckert** [atom/atom#15092]
Working in dir with python and large text files. Using python to read the files. Issue when saving the python doc that reads and plots the large text files. Unsure of exact steps. 

**Issue due to exceeding memory on hard drive.**

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: "Red Hat
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Unknown system error -122: Unknown system error -122, close

```
At /usr/share/atom/resources/app/src/pane.js:1095

Error: Unknown system error -122: Unknown system error -122, close
    at Error (native)
    at Object.fs.closeSync (fs.js:609:18)
    at Object.closeSync (/usr/share/atom/resources/app/node_modules/graceful-fs/graceful-fs.js:51:27)
    at Object.fs.writeFileSync (fs.js:1361:23)
    at Proxy.writeFileSync (/usr/share/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:295:29)
    at File.module.exports.File.writeFileSync (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:289:25)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:467:27)
    at File.module.exports.File.writeSync (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:384:18)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1127:25)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app/src/text-editor.js:925:32)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:780:24)
    at Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app/src/pane.js:763:25)
    at Workspace.saveActivePaneItem (/usr/share/atom/resources/app/src/workspace.js:1548:46)
    at atom-workspace.core:save (/usr/share/atom/resources/app/src/register-default-commands.js:236:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -2:06.6.0 core:move-up (input.hidden-input)
     -2:06.3.0 core:move-right (input.hidden-input)
  2x -2:04.2.0 core:backspace (input.hidden-input)
     -2:01.3.0 core:move-right (input.hidden-input)
     -1:36 core:backspace (input.hidden-input)
     -1:24.9.0 core:copy (input.hidden-input)
     -1:23.5.0 core:paste (input.hidden-input)
     -1:21.6.0 core:backspace (input.hidden-input)
     -1:20.5.0 core:save (input.hidden-input)
     -1:18.7.0 editor:newline (input.hidden-input)
     -1:14.5.0 snippets:next-tab-stop (input.hidden-input)
     -1:14.5.0 snippets:expand (input.hidden-input)
     -1:14.5.0 editor:indent (input.hidden-input)
  4x -1:13.9.0 core:backspace (input.hidden-input)
     -1:11.7.0 autocomplete-plus:confirm (input.hidden-input)
  4x -1:11.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.13 
atom-html-preview 0.1.22 
atom-latex 0.7.11 
git-plus 7.9.3 
language-matlab 0.2.1 
minimap 4.28.3 
minimap-pigments 0.2.2 
nebula-syntax 0.4.4 
nebula-ui 0.6.0 
pigments 0.39.1 
split-diff 1.4.3 
zentabs 0.8.8 
```

**Comment by rsese** [comment]
Thanks for the report!  It sounds like there are no specific steps to reproduce but just to confirm, does the process you described  involve using a community package?

> Working in dir with python and large text files. Using python to read the files. Issue when saving the python doc that reads and plots the large text files.

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15092#issuecomment-318189598. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
