### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'nuclide:/our.vinceo.sb.facebook.com/data...

### ISSUE THREAD

**Issue by Vince0613** [atom/atom#15094]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'nuclide:/our.vinceo.sb.facebook.com/data/users/vinceo/www-hg/html/images/ads/components/previews_v2/an-banner.png'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat 'nuclide:/our.vinceo.sb.facebook.com/data/users/vinceo/www-hg/html/images/ads/components/previews_v2/an-banner.png'
  at Error (native)
  at fs.statSync (fs.js:992:18)
  at Proxy.fs.statSync (ELECTRON_ASAR.js:275:16)
  at new ImageEditorView (<embedded>:94758:48)
  at ImageEditor.get (<embedded>:49092:33)
  at ImageEditor.get (<embedded>:49086:24)
  at ViewRegistry.module.exports.ViewRegistry.createView (<embedded>:16995:41)
  at ViewRegistry.module.exports.ViewRegistry.getView (<embedded>:16978:27)
  at atom-pane.PaneElement.getActiveView (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:200:25)
  at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:53:55)
  at atom-pane.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:117:14)
  at Function.module.exports.Emitter.simpleDispatch (<embedded>:63093:20)
  at Emitter.module.exports.Emitter.emit (<embedded>:63209:34)
  at Pane.module.exports.Pane.activate (<embedded>:26439:33)
  at NotificationElement.module.exports.NotificationElement.removeNotificationAfterTimeout (<embedded>:52039:46)
  at NotificationElement.module.exports.NotificationElement.removeNotification (<embedded>:51997:25)
  at <embedded>:51799:32
  at Function.module.exports.Emitter.simpleDispatch (<embedded>:63093:20)
  at Emitter.module.exports.Emitter.emit (<embedded>:63209:34)
  at Notification.module.exports.Notification.dismiss (<embedded>:65257:33)
  at NotificationElement.module.exports.NotificationElement.handleRemoveNotificationClick (<embedded>:52001:31)
  at HTMLDivElement.<anonymous> (<embedded>:51890:32)

```

### Commands

```
     -6:45.1.0 pane:show-next-item (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -6:42.9.0 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -6:42.4.0 pane:show-previous-item (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -6:42.1.0 pane:show-next-item (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -6:34.6.0 find-and-replace:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -6:33.6.0 core:confirm (input.hidden-input)
     -6:32.9.0 editor:consolidate-selections (input.hidden-input)
     -6:32.9.0 core:cancel (input.hidden-input)
 30x -6:01.7.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -5:31.8.0 core:copy (input.hidden-input)
     -5:31.8.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -5:31.6.0 nuclide-quick-open:find-anything-via-omni-search (input.hidden-input)
     -5:31.3.0 core:paste (input.hidden-input)
  3x -5:22.9.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:09.4.0 core:close (input.hidden-input)
     -0:08.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.68.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.11 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.11 
merge-conflicts 1.4.5 
nuclide 0.241.65704266 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this might be caused by the [Nuclide](https://atom.io/packages/nuclide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
