### ISSUE TITLE
Uncaught Error: Cannot find module './commands/edit-line'

### ISSUE THREAD

**Issue by quackingduck** [atom/atom#15102]
[Enter steps to reproduce:]

1. open new buffer
2. type `"foo"`
3. place cursor inside string and attempt to activate "toggle quotes"

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './commands/edit-line'

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1

Error: Cannot find module './commands/edit-line'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/markdown-writer/lib/markdown-writer.coffee:132:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -2:05.4.0 settings-view:open (input.hidden-input)
  7x -1:16.7.0 core:backspace (input.hidden-input)
     -0:39.1.0 pane:show-previous-item (input.hidden-input)
  6x -0:35.9.0 toggle-quotes:toggle (input.hidden-input)
     -0:30.3.0 pane:show-next-item (input.hidden-input)
     -0:20.1.0 pane:show-previous-item (div.package-detail.panels-item)
  2x -0:17.8.0 toggle-quotes:toggle (input.hidden-input)
     -0:14.9.0 command-palette:toggle (input.hidden-input)
     -0:13 core:backspace (input.hidden-input)
  3x -0:10.1.0 core:move-down (input.hidden-input)
     -0:09.4.0 core:move-up (input.hidden-input)
     -0:08.9.0 core:confirm (input.hidden-input)
     -0:08.9.0 toggle-quotes:toggle (input.hidden-input)
     -0:08.1.0 markdown-writer:insert-new-line (input.hidden-input)
```

### Non-Core Packages

```
apex-syntax 0.1.0 
apex-ui 0.2.1 
atom-bracket-highlight 0.3.2 
atom-format-lua 0.1.5 
auto-fold 0.4.0 
autocomplete-swift 1.0.3 
build 0.68.0 
build-make 0.13.0 
build-xcodebuild 0.2.0 
busy 0.7.0 
busy-signal 1.4.3 
change-case 0.6.5 
clang-format 1.29.0 
custom-folds 1.9.4 
date 1.2.2 
fancy-bracket-matcher 1.0.1 
git-time-machine 1.5.9 
github-atom-light-syntax 0.5.0 
goto 1.8.3 
hey-pane 1.0.0 
hs1-atom 0.0.0 
intentions 1.1.2 
jsformat 0.9.3 
language-llvm 0.1.1 
language-lua 0.9.11 
language-markdown 0.25.1 
language-mips 0.3.0 
language-ocaml 1.9.5 
language-swift 0.5.0 
language-terra 0.1.0 
linter 2.2.0 
linter-clang 4.1.1 
linter-eastwood 1.1.0 
linter-eslint 8.2.1 
linter-js-standard 3.9.1 
linter-lua 1.0.4 
linter-rubocop 2.1.1 
linter-ruby 1.2.5 
linter-shellcheck 1.4.4 
linter-swiftc 2.0.0 
linter-ui-default 1.6.3 
linter-write-good 0.9.0 
lisp-paredit 0.5.5 
markdown-folder 0.5.0 
minimap 4.29.2 
minimap-autohider 1.5.3 
minimap-linter 2.0.2 
ocaml-indent 0.6.0 
ocaml-merlin 0.14.4 
Parinfer 1.18.0 
prettier-atom 0.37.0 
script 3.15.0 
Sublime-Style-Column-Selection 1.7.4 
swift-debugger 0.1.2 
symbols-view-plus 0.117.0-plus 
title-case 0.4.0 
toggle-quotes 1.0.1 
tool-bar 1.1.0 
vim-mode-plus 0.93.0 
Zen 0.18.0 
zentabs 0.8.8 
```

**Comment by rsese** [comment]
Thanks for the report!  There's been a few of this type of issue since `1.17.0` e.g. https://github.com/atom/atom/issues/14708 and https://github.com/atom/atom/issues/14461 but we haven't been able to reproduce.  We'll go ahead and close as a dupe for now but one thing you could try is re-installing toggle quotes?
