### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by actini** [atom/atom#15115]
**Atom**: 1.19.0-beta2 x64
**Electron**: 1.6.9
**OS**: "CentOS Linux
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At /usr/share/atom-beta/resources/app/src/text-editor-component.js:2138

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (/usr/share/atom-beta/resources/app/src/text-editor-component.js:2138:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/usr/share/atom-beta/resources/app/src/text-editor-component.js:2134:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/usr/share/atom-beta/resources/app/src/text-editor-component.js:378:16)
    at scheduler.readDocument (/usr/share/atom-beta/resources/app/src/text-editor-component.js:263:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom-beta/resources/app/src/view-registry.js:191:15)
    at /usr/share/atom-beta/resources/app/src/view-registry.js:3:65
```

### Commands

```
 50x -3:48.9.0 core:undo (input.hidden-input)
 28x -3:45.7.0 core:move-up (input.hidden-input)
     -3:38.1.0 core:save (input.hidden-input)
  2x -0:25.1.0 core:backspace (input.hidden-input)
  8x -0:24.3.0 core:page-up (input.hidden-input)
     -0:22.5.0 core:page-down (input.hidden-input)
  2x -0:22 core:move-left (input.hidden-input)
     -0:21.6.0 core:backspace (input.hidden-input)
     -0:21.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:20.9.0 editor:newline (input.hidden-input)
     -0:19.1.0 core:select-all (input.hidden-input)
     -0:18.7.0 core:copy (input.hidden-input)
     -0:17.6.0 core:paste (input.hidden-input)
     -0:14.9.0 core:undo (input.hidden-input)
     -0:04.2.0 editor:consolidate-selections (input.hidden-input)
     -0:04.2.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.18 
css-snippets 1.1.0 
emmet 2.4.3 
jquery-snippets 11.0.0 
meteor-api 2.20.0 
meteor-helper 0.29.0 
nuclide 0.236.0 
open-in-browser 0.5.0 
script 3.15.0 
tree-view-git-status 1.3.1 
```

**Comment by rsese** [comment]
I believe this was fixed in `1.19.0-beta5` - if you still get an error after upgrading, please let us know.

**Comment by ylavoie** [comment]
It is still present

**Comment by rsese** [comment]
@ylavoie can you share your version details (`atom -v`, operating system) and your steps to reproduce?  Can you also confirm if you get the error in safe mode (`atom --safe`)?
