### ISSUE TITLE
Installing “atom-typescript@11.0.6” failed.Hide output…

### ISSUE THREAD

**Issue by liangzeng** [atom/atom#15126]
I think update electron-mksnapshot to 1.7.1 is ok.

### Description

```
Installing “atom-typescript@11.0.6” failed.Hide output…

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | darwin | x64
gyp http GET https://atom.io/download/electron/v1.3.15/iojs-v1.3.15.tar.gz
gyp http 200 https://atom.io/download/electron/v1.3.15/iojs-v1.3.15.tar.gz
gyp http GET https://atom.io/download/electron/v1.3.15/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: connect ETIMEDOUT 52.216.65.0:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/liangzeng/Documents/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/liangzeng/Documents/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=1.3.15" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/liangzeng/.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by 50Wliu** [comment]
> Error: connect ETIMEDOUT 52.216.65.0:443

This signifies a internet connectivity issue.  Check your internet connection and try again.
