### ISSUE TITLE
Flaky test - it blinks cursors when the editor is focused and the cursors are not moving

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#15122]
https://ci.appveyor.com/project/Atom/atom/build/7387/job/usobg8qq24sqtjdy

```
TextEditorComponent
  rendering
    it blinks cursors when the editor is focused and the cursors are not moving
      Expected '0' to be '1'.
        at it (C:\projects\atom\spec\text-editor-component-spec.js:414:49)
      Expected '0' to be '1'.
        at it (C:\projects\atom\spec\text-editor-component-spec.js:415:49)
```

**Comment by maxbrunsfeld** [comment]
This failed on appveyor on this PR: https://github.com/atom/atom/issues/15122

**Comment by jasonrudolph** [comment]
Failed again in https://ci.appveyor.com/project/Atom/atom/build/7422/job/xousrcu8ao5dixns.

**Comment by maxbrunsfeld** [comment]
🚀
