### ISSUE TITLE
Uncaught Error: Module version mismatch. Expected 49, got 48.

### ISSUE THREAD

**Issue by kuboosoft** [atom/atom#15120]
[Enter steps to reproduce:]

1. ... Open Atom

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: "Fedora release
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module version mismatch. Expected 49, got 48.

```
At ELECTRON_ASAR.js:168

Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (var/lib/mock/fedora-26-x86_64/root/builddir/build/BUILD/atom-783cda8642e42e842a7aac761f267e151f3db324/out/atom-1.18.0-amd64/resources/app/static/index.js:47:45)
    at require (/var/lib/mock/fedora-26-x86_64/root/builddir/build/BUILD/atom-783cda8642e42e842a7aac761f267e151f3db324/out/atom-1.18.0-amd64/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/oniguruma/src/oniguruma.js:1:114)
    at Module.get_Module._compile (/var/lib/mock/fedora-26-x86_64/root/builddir/build/BUILD/atom-783cda8642e42e842a7aac761f267e151f3db324/out/atom-1.18.0-amd64/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/var/lib/mock/fedora-26-x86_64/root/builddir/build/BUILD/atom-783cda8642e42e842a7aac761f267e151f3db324/out/atom-1.18.0-amd64/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (var/lib/mock/fedora-26-x86_64/root/builddir/build/BUILD/atom-783cda8642e42e842a7aac761f267e151f3db324/out/atom-1.18.0-amd64/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/var/lib/mock/fedora-26-x86_64/root/builddir/build/BUILD/atom-783cda8642e42e842a7aac761f267e151f3db324/out/atom-1.18.0-amd64/resources/app/static/<embedded>:96:26)
    at get__ref (/var/lib/mock/fedora-26-x86_64/root/builddir/build/BUILD/atom-783cda8642e42e842a7aac761f267e151f3db324/out/atom-1.18.0-amd64/resources/app/node_modules/first-mate/lib/grammar.js:13:33)
    at get_OnigRegExp (/var/lib/mock/fedora-26-x86_64/root/builddir/build/BUILD/atom-783cda8642e42e842a7aac761f267e151f3db324/out/atom-1.18.0-amd64/resources/app/node_modules/first-mate/lib/grammar.js:17:45)
    at new Grammar (/var/lib/mock/fedora-26-x86_64/root/builddir/build/BUILD/atom-783cda8642e42e842a7aac761f267e151f3db324/out/atom-1.18.0-amd64/resources/app/node_modules/first-mate/lib/grammar.js:58:42)
    at GrammarRegistry.module.exports.GrammarRegistry.createGrammar (/var/lib/mock/fedora-26-x86_64/root/builddir/build/BUILD/atom-783cda8642e42e842a7aac761f267e151f3db324/out/atom-1.18.0-amd64/resources/app/node_modules/first-mate/lib/grammar-registry.js:202:23)
    at /var/lib/mock/fedora-26-x86_64/root/builddir/build/BUILD/atom-783cda8642e42e842a7aac761f267e151f3db324/out/atom-1.18.0-amd64/resources/app/node_modules/first-mate/lib/grammar-registry.js:121:82
    at parseContents (/var/lib/mock/fedora-26-x86_64/root/builddir/build/BUILD/atom-783cda8642e42e842a7aac761f267e151f3db324/out/atom-1.18.0-amd64/resources/app/node_modules/season/lib/cson.js:123:13)
    at /var/lib/mock/fedora-26-x86_64/root/builddir/build/BUILD/atom-783cda8642e42e842a7aac761f267e151f3db324/out/atom-1.18.0-amd64/resources/app/node_modules/season/lib/cson.js:212:26
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by damieng** [comment]
You should see a red bug icon in the status-bar when you launch atom, click that and then "Rebuild package".

This normally happens if you have an older version of apm in your path and you used it to install a package that has native dependencies (it got compiles for v48 but your atom is v49 Chrome based)

**Comment by frederik-sevenval** [comment]
I got the same issue and I do not have a red bug icon or a Rebuild package option anywhere.

**Comment by kuboosoft** [comment]
@damieng I used the native/used apm of atom source... I don't touch here nothing. You can see the ".spec" file here https://github.com/UnitedRPMs/atom/blob/master/atom.spec#L121

**Comment by damieng** [comment]
Atom 1.18.x is v49 based as reported by `process.versions.modules`

Something native library on your system must still be compiled for v48 somewhere.  Sorry the error message doesn't specifically say which one - I think it's deep in the depths of chromium/node/electron and we can't pull out the name.

**Comment by kuboosoft** [comment]
@damieng I will check; the strange, I do not install npm or electron in the system. I am using the electron required by atom; same npm, and my guide is the travis.yml and circle.yml
