### ISSUE TITLE
Uncaught Error: EINVAL: invalid argument, open '/Volumes/My Passport for Mac/Interactivity/wallys...

### ISSUE THREAD

**Issue by jennawsmith** [atom/atom#15125]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EINVAL: invalid argument, open '/Volumes/My Passport for Mac/Interactivity/wallys_wp/wp-content/themes/wallys/header.php'

```
At /Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/src/pane.js:1095

Error: EINVAL: invalid argument, open '/Volumes/My Passport for Mac/Interactivity/wallys_wp/wp-content/themes/wallys/header.php'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Proxy.writeFileSync (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:295:29)
    at File.module.exports.File.writeFileSync (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:289:25)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:467:27)
    at File.module.exports.File.writeSync (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:384:18)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1127:25)
    at TextBuffer.module.exports.TextBuffer.save (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:925:32)
    at Pane.module.exports.Pane.saveItem (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/src/pane.js:780:24)
    at Pane.saveItem (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveActiveItem (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/src/pane.js:763:25)
    at Workspace.saveActivePaneItem (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/src/workspace.js:1548:46)
    at atom-workspace.core:save (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/src/register-default-commands.js:236:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Users/jennasmith/Downloads/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -9:55.9.0 editor:newline (input.hidden-input)
     -9:55.2.0 snippets:next-tab-stop (input.hidden-input)
     -9:55.2.0 snippets:expand (input.hidden-input)
     -9:55.2.0 editor:indent (input.hidden-input)
     -8:53.5.0 core:paste (input.hidden-input)
  3x -8:49 core:backspace (input.hidden-input)
     -8:41.9.0 core:move-left (input.hidden-input)
     -7:36.1.0 core:backspace (input.hidden-input)
     -7:34.1.0 core:move-left (input.hidden-input)
  3x -7:32.9.0 core:backspace (input.hidden-input)
     -7:20 core:save (input.hidden-input)
     -0:39.7.0 core:backspace (input.hidden-input)
     -0:38.7.0 core:move-right (input.hidden-input)
 10x -0:38.4.0 core:backspace (input.hidden-input)
  2x -0:30.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.1 
intentions 1.1.2 
linter 2.1.4 
linter-eslint 8.1.7 
linter-htmlhint 1.3.3 
linter-stylelint 3.10.0 
linter-ui-default 1.2.4 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

/cc https://github.com/atom/atom/issues/4820

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15125#issuecomment-319473008. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
