### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by TorquilChapman** [atom/atom#15168]
[Enter steps to reproduce:]

1. Selecting a large block of text from a JSON file (file has sensitive info so can't supply)
2. Working dir is a git repo. 

**Atom**: 1.19.0-beta7 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At C:\Users\chapmt01.TDL\AppData\Local\atom\app-1.19.0-beta7\resources\app\src\text-editor-component.js:2148

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/text-editor-component.js:2148:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/text-editor-component.js:2144:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/text-editor-component.js:378:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/text-editor-component.js:263:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/view-registry.js:191:15)
    at ~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/view-registry.js:3:65
```

### Commands

```
  3x -5:33.9.0 core:move-up (input.hidden-input)
     -5:28.2.0 core:move-right (input.hidden-input)
  2x -5:24.6.0 core:backspace (input.hidden-input)
     -5:22.2.0 core:move-right (input.hidden-input)
  2x -5:21.7.0 core:backspace (input.hidden-input)
  6x -5:18.3.0 core:move-left (input.hidden-input)
  7x -5:16.5.0 core:backspace (input.hidden-input)
     -5:04.9.0 core:move-right (input.hidden-input)
     -5:03.7.0 core:delete (input.hidden-input)
  2x -4:05.9.0 core:backspace (input.hidden-input)
     -2:29.1.0 core:copy (span.syntax--string.syntax--quoted.syntax--double.syntax--json)
     -2:23.4.0 intentions:highlight (input.hidden-input)
     -2:23 core:paste (input.hidden-input)
     -2:18.5.0 core:delete (input.hidden-input)
undefined -0:48.3.0 core:select-down (input.hidden-input)
     -0:31.9.0 core:select-up (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
atom-typescript 11.0.6 
atomic-chrome 0.3.2 
busy-signal 1.4.3 
color-picker 2.2.5 
column-select 0.2.0 
intentions 1.1.5 
json-converter 0.2.4 
language-batch 0.4.0 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-jshint 3.1.5 
linter-ui-default 1.6.3 
markdown-preview-plus 2.4.10 
markdown-themeable-pdf 1.2.0 
markdown-writer 2.6.5 
minimap 4.29.3 
open_in_cmd 0.6.1 
open-in-browser 0.5.2 
pdf-view 0.59.0 
pigments 0.40.1 
platformio-ide-terminal 2.5.4 
pretty-json 1.6.4 
project-manager 3.3.5 
quick-query 0.10.2 
quick-query-mssql 0.1.4 
sort-lines 0.14.0 
Sublime-Style-Column-Selection 1.7.4 
tabs-to-spaces 1.0.3 
```

**Comment by 50Wliu** [comment]
@TorquilChapman is this consistently reproducible?  If so, can you please try in safe mode (`atom --safe`)?

**Comment by Ben3eeE** [comment]
I can consistently reproduce this out of safe mode with `atom-ide-ui` as my only enabled package. It also throws an exception from `atom-ide-ui` included below.

1. Disable all packages except `atom-ide-ui` and restart Atom
1. Open a file, I used `atom-environment.coffee` from the `atom/atom` repository
1. Hold <kbd>Page Down</kbd> for a while and then switch to holding <kbd>Page Up</kbd> for a while. The keys are bound to `core:page-down` and `core:page-up`
1. Repeat this for a couple of scrolls through the file. I did not scroll to the end before changing direction.

**Gif of Reproduction**
![issue](https://user-images.githubusercontent.com/1058982/29065234-bcef5e64-7c2b-11e7-8806-7db7b7cf0c05.gif)

**Atom**: 1.19.0-beta7 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-ide-ui](https://github.com/facebooknuclide/atom-ide-ui) package 0.1.10


### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At C:\Users\lineri\.atom\packages\atom-ide-ui\node_modules\rxjs\bundles\Rx.min.js:43

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/text-editor-component.js:2148:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/text-editor-component.js:2144:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/text-editor-component.js:378:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/text-editor-component.js:269:18)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/text-editor-component.js:195:18)
    at getBufferPosition (/packages/atom-ide-ui/node_modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:186:48)
    at DatatipManagerForEditor._hideOrCancel (/packages/atom-ide-ui/node_modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:528:35)
    at /packages/atom-ide-ui/node_modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:325:14)
    at a.__tryOrUnsub (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:43:337)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:42:227)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:393)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at /packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:81:365)
```

### Commands

```
 19x -2:34.1.0 core:page-up (input.hidden-input)
 12x -2:33 core:page-down (input.hidden-input)
 16x -2:30.4.0 core:page-up (input.hidden-input)
 18x -2:29.4.0 core:page-down (input.hidden-input)
     -2:28.4.0 core:page-up (input.hidden-input)
     -1:35.3.0 intentions:highlight (input.hidden-input)
     -1:34.9.0 application:new-file (input.hidden-input)
     -1:34.4.0 core:paste (input.hidden-input)
     -1:33.9.0 intentions:highlight (input.hidden-input)
     -1:33.6.0 core:undo (input.hidden-input)
     -1:09.4.0 intentions:highlight (input.hidden-input)
     -1:09.3.0 core:paste (input.hidden-input)
     -1:08.7.0 core:undo (input.hidden-input)
     -1:06.3.0 intentions:highlight (input.hidden-input)
     -1:06.1.0 core:paste (input.hidden-input)
     -1:05.6.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.4 
atom-clock 0.1.13 
atom-ide-ui 0.1.10 
atom-material-syntax 1.0.6 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
atom-typescript 11.0.6 
autocomplete-emojis 2.5.0 
busy-signal 1.4.3 
column-select 0.2.0 
copy-paste 0.6.0 
dark-side-of-the-moon-syntax 0.6.35 
file-icons 2.1.10 
git-pear 1.2.1 
highlight-selected 0.13.1 
honor-altgraph 0.1.0 
ink 0.7.4 
intentions 1.1.5 
jshint 1.8.6 
language-markdown 0.25.1 
language-pegjs 0.5.0 
less-than-slash 0.17.0 
linter 2.2.0 
linter-js-standard 3.9.3 
linter-php 1.3.2 
linter-ui-default 1.6.3 
markdown-pdf 1.5.4 
merge-conflicts 1.4.5 
minimap 4.29.3 
minimap-autohider 1.5.3 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-plus 4.29.2 
nebula-syntax 0.4.4 
nebula-ui 0.6.0 
nvatom 0.11.0 
pigments 0.40.1 
seti-syntax 1.1.3 
seti-ui 1.9.0 
stacktrace 0.0.2 
Sublime-Style-Column-Selection 1.7.4 
svn 0.0.13 
symbol-gen 1.3.1 
tabs-to-spaces 1.0.3 
toggler 0.3.0 
tortoise-svn 0.5.1 
vim-mode-plus 0.96.2 
zentabs 0.8.8 
```

**Comment by OmgImAlexis** [comment]
[Enter steps to reproduce:]

Randomly started getting this today. Going to update extensions and atom and see if that fixes it.

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2168

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2168:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2164:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:385:16)
    at scheduler.readDocument (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:270:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
     -4:15.1.0 intentions:highlight (input.hidden-input)
     -4:14.5.0 editor:move-to-beginning-of-word (input.hidden-input)
```

### Non-Core Packages

```
autohide-tree-view 0.25.1 
busy-signal 1.4.3 
duplicate-removal 0.1.3 
editorconfig 2.2.2 
file-icons 2.1.11 
git-status 0.3.4 
intentions 1.1.5 
language-docker 1.1.8 
language-mako 0.6.0 
language-nginx 0.8.0 
language-pug 0.0.21 
language-vue 0.23.1 
linter 2.2.0 
linter-pycodestyle 2.1.1 
linter-stylelint 4.0.1 
linter-swagger 0.4.1 
linter-ui-default 1.6.7 
linter-xo 0.23.1 
multi-cursor 2.1.5 
seti-syntax 1.1.3 
seti-ui 1.9.0 
sort-lines 0.14.0 
tree-view-autoresize 2.2.0 
tree-view-git-status 1.4.0 
```

**Comment by Ben3eeE** [comment]
@OmgImAlexis The fix for this has been released in one of the hotfix releases for 1.19. I recommend you update Atom to the latest version.

**Comment by OmgImAlexis** [comment]
I'm on `1.19.0` and there's no updates?

**Comment by Ben3eeE** [comment]
@OmgImAlexis The latest version is `1.19.2` https://atom.io/releases
