### ISSUE TITLE
Mac OS X: Installer Unable To Find File "ansicolors"

### ISSUE THREAD

**Issue by BobCochran** [atom/atom#15173]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
On Mac OS X 10.11.6, when compiling Atom from source code, I receive an apparently file not found type of error:

`Error: Command failed: /Users/gbwk/Downloads/atom/script/node_modules/.bin/npm --global-style --loglevel=error install
npm ERR! path /Users/gbwk/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/gbwk/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors' -> '/Users/gbwk/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/.ansicolors.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gbwk/.npm/_logs/2017-08-05T15_18_03_934Z-debug.log

    at checkExecSyncError (child_process.js:591:13)
    at Object.execFileSync (child_process.js:611:13)
    at module.exports (/Users/gbwk/Downloads/atom/script/lib/install-apm.js:9:16)
    at Object.<anonymous> (/Users/gbwk/Downloads/atom/script/bootstrap:29:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
`

### Steps to Reproduce

1. Download Atom as instructed for building from source code:

`git clone https://github.com/atom/atom.git` 
(as of 2017-08-05 approximately 10:30 a.m. Eastern time)

2. Build Atom:

`./script/build --install-dir /Users/gbwk/local/bin/Atom.app
atom gbwk$ ./script/build --install-dir ~/local/bin/Atom.app
Node:	v8.2.1
Npm:	v5.3.0
`

This step appeared to complete normally.
3. Noticed this message upon completion of the build:

`Skipping installation. Specify the --install option to install Atom`

So I ran this:

`deaf57:atom gbwk$ ./script/build --install
Node:	v8.2.1
Npm:	v5.3.0
Installing script dependencies
Installing apm
npm ERR! path /Users/gbwk/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/gbwk/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors' -> '/Users/gbwk/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/.ansicolors.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gbwk/.npm/_logs/2017-08-05T15_16_43_256Z-debug.log
child_process.js:614
    throw err;
    ^

Error: Command failed: /Users/gbwk/Downloads/atom/script/node_modules/.bin/npm --global-style --loglevel=error install
npm ERR! path /Users/gbwk/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/gbwk/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors' -> '/Users/gbwk/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/.ansicolors.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gbwk/.npm/_logs/2017-08-05T15_16_43_256Z-debug.log

    at checkExecSyncError (child_process.js:591:13)
    at Object.execFileSync (child_process.js:611:13)
    at module.exports (/Users/gbwk/Downloads/atom/script/lib/install-apm.js:9:16)
    at Object.<anonymous> (/Users/gbwk/Downloads/atom/script/bootstrap:29:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
`
I thought perhaps the installer needed my --install-dir, so I reran with this:

`deaf57:atom gbwk$ ./script/build --install --install-dir ~/local/bin/Atom.app
Node:	v8.2.1
Npm:	v5.3.0
Installing script dependencies
Installing apm
npm ERR! path /Users/gbwk/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/gbwk/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors' -> '/Users/gbwk/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/.ansicolors.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gbwk/.npm/_logs/2017-08-05T15_18_03_934Z-debug.log
child_process.js:614
    throw err;
    ^

Error: Command failed: /Users/gbwk/Downloads/atom/script/node_modules/.bin/npm --global-style --loglevel=error install
npm ERR! path /Users/gbwk/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/gbwk/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors' -> '/Users/gbwk/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/.ansicolors.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gbwk/.npm/_logs/2017-08-05T15_18_03_934Z-debug.log

    at checkExecSyncError (child_process.js:591:13)
    at Object.execFileSync (child_process.js:611:13)
    at module.exports (/Users/gbwk/Downloads/atom/script/lib/install-apm.js:9:16)
    at Object.<anonymous> (/Users/gbwk/Downloads/atom/script/bootstrap:29:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
`
**Expected behavior:** 

I expected Atom to install normally, without error, in the --install-dir that I specified.

**Actual behavior:** 

Installation fails, apparently due to a file not found.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

`atom gbwk$ atom --version
atom gbwk$ apm -version
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.11.0.22.g8d7a455
`
Mac OS X 10.11.6

Note that I actually have a fresh install of node:

`atom gbwk$ node --version
v8.2.1
`

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
My installation log should be attached.

[2017-08-05T15_18_03_934Z-debug.log.txt](https://github.com/atom/atom/files/1202490/2017-08-05T15_18_03_934Z-debug.log.txt)

**Comment by BobCochran** [comment]
I was able to fix this with a little more effort at researching. 

Removed apm/package-lock.json, changed 
`./script/build --install --install-dir ~/local/bin/Atom.app`

to

`./script/build --install=/Users/gbwk/local/bin`

..and Atom installed to my local directory.
