### ISSUE TITLE
Uncaught TypeError: this.promptToSaveItem(...).then is not a function

### ISSUE THREAD

**Issue by masajene** [atom/atom#15205]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.promptToSaveItem(...).then is not a function

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:709

TypeError: this.promptToSaveItem(...).then is not a function
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:709:52)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:683:18)
    at Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1703:48)
    at HTMLElement.core:close (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:233:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:02.1.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-html-preview 0.1.22 
atom-jade 0.3.0 
atom-jshint 2.0.0 
atom-terminal-panel 4.4.4 
atom-typescript 11.0.6 
autocomplete-paths 1.0.5 
build 0.68.0 
busy 0.7.0 
busy-signal 1.4.3 
coffee-compile 0.26.0 
color-picker 2.2.5 
docblockr 0.11.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.10 
goto-definition 1.3.4 
highlight-selected 0.13.1 
intentions 1.1.5 
japanese-menu 1.13.0 
japanese-wrap 0.2.7 
linter 2.2.0 
linter-coffeelint 1.2.1 
linter-jshint 3.1.5 
linter-php 1.3.2 
linter-phpmd 1.5.3 
linter-ui-default 1.6.3 
markdown-scroll-sync 2.1.2 
markdown-writer 2.6.5 
merge-conflicts 1.4.5 
minimap 4.29.3 
minimap-autohide 0.10.1 
pretty-json 1.6.4 
project-manager 3.3.5 
sass-autocompile 0.13.3 
save-session 0.16.0 
tag 0.5.0 
terminal-plus 0.14.5 
tool-bar 1.1.0 
tool-bar-main 0.0.10 
tool-bar-markdown-writer 0.3.0 
```

**Comment by 50Wliu** [comment]
@masajene What were you doing when this error occurred?

**Comment by Creky** [comment]
@50Wliu I got the same issue when I try to close a edited and unsaved tab, I can not close any unsaved tabs now!!!

**Comment by karlhorky** [comment]
I'm also having this issue when I try to close unsaved buffers.

Atom: 1.19.0 x64
OS: macOS Sierra 10.12.6

Packages:

```
atom-alignment@0.13.0
atom-no-tab-close-button@1.0.0
atom-typescript@11.0.6
busy-signal@1.4.3
easy-motion-redux@1.1.1
editorconfig@2.2.2
highlight-line@0.12.0
intentions@1.1.5
language-docker@1.1.8
language-groovy@0.7.0
language-reason@0.0.3
layout-control@0.1.5
linter@2.2.0
linter-eslint@8.2.1
linter-flow@5.6.0
linter-ui-default@1.6.4
prettier-atom@0.37.0
save-session@0.15.7
sort-lines@0.14.0
vim-mode-plus@0.96.2
```

**Comment by Ben3eeE** [comment]
Thanks for contributing!

It appears that this is being caused by the [save-session package](https://atom.io/packages/save-session), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by karlhorky** [comment]
Thanks @Ben3eeE! I've opened https://github.com/mpeterson2/save-session/issues/163 for this.

**Comment by uchuugaka** [comment]
Is there an alternative package to use? This is really persistent.

**Comment by uchuugaka** [comment]
Unfortunately that package seems fairly abandoned. It hasn't had updates in years. :(

**Comment by amlcreative** [comment]
@uchuugaka According to Save Session's page, "All of Save Session's functionality is now included in Atom core." I uninstalled Save Session and tested closing Atom with several sessions opened and can confirm that Atom core reopened them.
