### ISSUE TITLE
1.19.0 fails to build on Ubuntu 14.04 32 & 64 bit (failed at superstring@2.0.10 install script 'node-gyp rebuild')

### ISSUE THREAD

**Issue by hotice** [atom/atom#15203]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Not applicable - Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Not applicable - Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Not applicable - Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Not applicable - Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Trying to build Atom 1.19.0 on Linux (tested on Ubuntu 14.04 32bit and 64bit) using ``script/build``, the following error is displayed:
```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN prefer global typescript@1.4.1 should be installed with -g
npm WARN prefer global jasmine-node@1.10.2 should be installed with -g
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:30:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                                           ^
../src/core/text-buffer.cc: In constructor ‘TextBuffer::Snapshot::Snapshot(TextBuffer&, TextBuffer::Layer&, TextBuffer::Layer&)’:
../src/core/text-buffer.cc:748:56: error: invalid initialization of non-const reference of type ‘TextBuffer&’ from an rvalue of type ‘<brace-enclosed initializer list>’
   : buffer{buffer}, layer{layer}, base_layer{base_layer} {}
                                                        ^
../src/core/text-buffer.cc:748:56: error: invalid initialization of non-const reference of type ‘TextBuffer::Layer&’ from an rvalue of type ‘<brace-enclosed initializer list>’
../src/core/text-buffer.cc:748:56: error: invalid initialization of non-const reference of type ‘TextBuffer::Layer&’ from an rvalue of type ‘<brace-enclosed initializer list>’
make: *** [Release/obj.target/superstring_core/src/core/text-buffer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/andrei/atom/atom-1.19.0/apm/node_modules/atom-package-manager/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.16.0-69-generic
gyp ERR! command "/home/andrei/atom/atom-1.19.0/apm/node_modules/atom-package-manager/bin/node" "/home/andrei/atom/atom-1.19.0/apm/node_modules/atom-package-manager/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/andrei/atom/atom-1.19.0/node_modules/superstring
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 3.16.0-69-generic
npm ERR! argv "/home/andrei/atom/atom-1.19.0/apm/node_modules/atom-package-manager/bin/node" "/home/andrei/atom/atom-1.19.0/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/andrei/.atom/.apm/.apmrc" "--userconfig" "/home/andrei/.atom/.apmrc" "install" "--runtime=electron" "--target=1.6.9" "--arch=ia32"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! superstring@2.0.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the superstring@2.0.10 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the superstring package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs superstring
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls superstring
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/andrei/atom/atom-1.19.0/npm-debug.log
```

### Versions

Tested using Ubuntu 14.04 (both 32bit and 64bit), using nodejs installed from the official node Ubuntu repository (package version  6.11.2-1nodesource1~trusty1).

```
$ apm --version
apm  1.18.1
npm  3.10.10
node 6.9.5 ia32
python 2.7.6
git 1.9.1
```

The complete npm-debug.log is available here: https://paste.ubuntu.com/25275549/

**Comment by maxbrunsfeld** [comment]
It looks like you're using a C++ compiler that doesn't support some C++11 features that superstring currently uses. Could you report your clang or gcc version?

On [superstring's linux CI build](https://github.com/atom/superstring/blob/9d00dd2a53d94be58f6d6abf857335dd2f2cbec2/.travis.yml#L32-L33), we test against gcc 4.9. [Atom's linux CI](https://github.com/atom/atom/blob/4876ae07e1e791a392013ab41901f001cf8d0f96/.travis.yml#L56) uses clang-3.3.

**Comment by hotice** [comment]
I'm using the default Ubuntu 14.04 gcc (4.8.2) and clang (3.4). I guess Ubuntu 14.04 shouldn't be recommended any more on the Atom Linux building page unless this is a bug.

**Comment by maxbrunsfeld** [comment]
Hmm, I think clang 3.4 should work. Is the output you posted from gcc or clang?

**Comment by hotice** [comment]
It's gcc. I'm not sure how to switch to clang for building Atom, I was just searching for that.

**Comment by maxbrunsfeld** [comment]
In any case, you can definitely build Atom on Ubuntu 14.04 (we do just that on our CI). You may just need to install the `clang-3.3` package. In order to use clang instead of gcc, I think you just need to [set the `CC` and `CXX` environment variables](https://github.com/atom/atom/blob/4876ae07e1e791a392013ab41901f001cf8d0f96/.travis.yml#L13).

**Comment by hotice** [comment]
Thanks!

**Comment by maxbrunsfeld** [comment]
Ok, I'm going to close this out. Let me know if you have any other questions.
