### ISSUE TITLE
Can't reinstall Atom

### ISSUE THREAD

**Issue by Thromshall** [atom/atom#15306]
Would love to use Atom (specifically Nuclide) to develop a react native app, but so far I'm unable to even get started doing so. I installed Atom, installed the Nuclide package, and then I couldn't launch Atom anymore. So I uninstalled it and I cannot reinstall.

Here is the setup log.

2017-08-14 20:59:13> Program: Starting Squirrel Updater: --install .
2017-08-14 20:59:14> Program: Starting install, writing to C:\Users\Daniel\AppData\Local\SquirrelTemp
2017-08-14 20:59:14> Program: About to install to: C:\Users\Daniel\AppData\Local\atom
2017-08-14 20:59:14> Program: Install path C:\Users\Daniel\AppData\Local\atom already exists, burning it to the ground
2017-08-14 20:59:14> IEnableLogger: Failed to copy Update.exe to C:\Users\Daniel\AppData\Local\atom\Update.exe: System.UnauthorizedAccessException: Access to the path 'C:\Users\Daniel\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__5()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
2017-08-14 20:59:14> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Daniel\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__5()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\Daniel\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__5()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

**Comment by Thromshall** [comment]
Just had to disable avast.
