### ISSUE TITLE
control-mousewheel to zoom font may throw uncaught type error

### ISSUE THREAD

**Issue by slawo-ch** [atom/atom#15311]
Version: 1.19.1 x64 on mac

Steps to reproduce:
Start atom in safe mode: `atom --safe`

Download and open this markdown file: https://raw.githubusercontent.com/twineworks/tweakflow/master/site/content/reference.md

Scroll down to about line 200.

Press ctrl and use your mouse wheel to zoom the font.

An exception appears:
```
/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2171
Hide Stack Trace
TypeError: Cannot read property 'firstChild' of undefined
    at TextEditorComponent.measureLongestLineWidth (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2171:112)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:383:16)
    at scheduler.readDocument (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:270:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:191:15)
```

After that atom becomes unstable and many actions generate follow up errors.

Thanks to @Ben3eeE for helping to find a usable repro path!

**Comment by Ben3eeE** [comment]
It seems to only happen for markdown files? Zooming markdown files is not working well at all on `Atom 1.20.0-beta2`. It sometimes throws this exception.

**Comment by pietrodn** [comment]
It also happens for .tex files. See [my comment](https://github.com/atom/atom/issues/15042#issuecomment-322503988) in another issue.

**Comment by tjsize** [comment]
Ctrl + Mouse scroll wheel to change the font size, same problem :(

**Comment by pietrodn** [comment]
Everything is fine for me now in Atom 1.19.2.

**Comment by Ben3eeE** [comment]
@pietrodn Thanks for reporting back that it is working for you now :bowing_man:
