### ISSUE TITLE
Uncaught Error: Couldn't convert text to a String

### ISSUE THREAD

**Issue by jacobpearson** [atom/atom#15325]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Couldn't convert text to a String

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:532

Error: Couldn't convert text to a String
    at TextBuffer.module.exports.TextBuffer.getText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:532:94)
    at new BackwardsMultiLine (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/match-iterator.js:312:37)
    at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1028:28)
    at TextBuffer.module.exports.TextBuffer.backwardsScanInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1044:25)
    at TextEditor.module.exports.TextEditor.backwardsScanInBufferRange (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2740:32)
    at Cursor.module.exports.Cursor.getBeginningOfCurrentWordBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/cursor.js:484:25)
    at Cursor.module.exports.Cursor.getCurrentWordBufferRange (/Applications/Atom.app/Contents/Resources/app/src/cursor.js:560:35)
    at Selection.module.exports.Selection.selectWord (/Applications/Atom.app/Contents/Resources/app/src/selection.js:401:45)
    at TextEditorComponent.didMouseDownOnContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1761:40)
    at DummyScrollbarComponent.didMousedown (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2942:47)
```

### Commands

```
     -1:06.8.0 core:backspace (input.hidden-input)
  2x -0:47.8.0 core:undo (input.hidden-input)
  8x -0:18.5.0 core:select-down (input.hidden-input)
```

### Non-Core Packages

```
autoprefixer 3.7.0 
pristine-ui 1.0.15 
```

**Comment by Ben3eeE** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by jacobpearson** [comment]
Hiya,
I encountered the the error a few times yesterday but can't reproduce now. Seems to be working, if slow (my fault, see below). I don't need to run the task so I don't anticipate encountering it again.

I was editing a CSV file, 1.2m rows and around 400mb. (Fringe case?)
Had the cursor half way through the file, navigated to the end, tried to select essentially half the file to delete it... 

If I encounter the problem again I'll update this ticket or create a new with the atom --safe info too

**Comment by Ben3eeE** [comment]
Thank you for the additional information 🙇 

/cc: @maxbrunsfeld and https://github.com/atom/git-diff/issues/138

**Comment by Pathel** [comment]
Got this on a 290 MB .impex file (admittedly huge, lol) as soon as I clicked into it.

**Comment by DanielWatsonPM** [comment]
I can recreate this issue on a Mac OSX, with a large SQL dump (448MB), after trying to double-click select a word in the file.

**Comment by vesak** [comment]
I have on macOS a 400M file with section of tab-delimited data (pg_dump output). One row was missing trailing tab, trying to add that caused this error. Recreatable.

**Comment by kjk** [comment]
I have the same problem. I generated a large file by running `git log >out.txt` on chromium checkout (https://chromium.googlesource.com/chromium/src.git) and then opened it atom on mac with `atom out.txt`.

It's a 450 MB file.

I got a lot of those messages just by opening the file.

![screen shot 2017-12-24 at 8 44 30 pm](https://user-images.githubusercontent.com/7935/34332917-43bf07f6-e8eb-11e7-8d13-6ef146c6ecd3.png)

I'm sure it's just some text inside the file that causes it so the test case could be much simplified, but I don't know what text.

**Comment by cyrielo** [comment]
I am not in any way dealing with a large file, just editing a react component and I get this exact red pop up randomly. Although I do have large files in my directory structure which I don't bother opening in atom because they are zip files.
