### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by dreamflyer** [atom/atom#15348]
1. calling of Pane.splitRight()/Pane.splitLeft()/Pane.splitDown()/Pane.splitUp().
can not provide more detailed reproduction sequence, since issue appears rarely and randomly and too difficult to debug it. Only can say that issue appears on startup and pane fetched by atom.workspace.getActivePane()

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.10.5
**Thrown From**: 'api-workbench' package v0.8.46

### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of null

```
At /Applications/Atom.app/Contents/Resources/app/src/pane-resize-handle-element.js:25

TypeError: Cannot read property 'classList' of null
    at HTMLElement.PaneResizeHandleElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app/src/pane-resize-handle-element.js:25:45)
    at HTMLElement.PaneAxisElement.childRemoved (/Applications/Atom.app/Contents/Resources/app/src/pane-axis-element.js:111:21)
    at HTMLElement.PaneAxisElement.childReplaced (/Applications/Atom.app/Contents/Resources/app/src/pane-axis-element.js:122:12)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneAxis.module.exports.PaneAxis.replaceChild (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:209:33)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app/src/pane.js:984:27)
    at Pane.module.exports.Pane.splitDown (/Applications/Atom.app/Contents/Resources/app/src/pane.js:972:25)
```

### Non-Core Packages

```
api-workbench 0.8.46 
atom-editor-logger 0.0.4 
busy-signal 1.3.0 
file-icons 1.7.14 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.5.4 
```

**Comment by rsese** [comment]
Thanks for the report!  It looks like this was also reported in api-workbench [1] and you closed the issue from https://github.com/mulesoft/api-workbench/commit/0178038a6c7abaf09526f70fe0532bcda01369a2?

Just to clarify, do you think there's still a bug on the Aton side?

[1]: https://github.com/mulesoft/api-workbench/issues/511

**Comment by dreamflyer** [comment]
@rsese, yes i thing there is still Atom's bug, my fix is just workaround until u fix it on your side(i hope), of course may be we doing something wrong with Panes, but i can't see how, currently

**Comment by Ben3eeE** [comment]
I can reproduce this rarely using the steps in https://github.com/mulesoft/api-workbench/issues/511. I did the steps 10 times and saw the exception once.

/cc: @as-cii @nathansobo Can this be an editor regression? From what I see the latest version of api-workbench was published on June 14th https://github.com/mulesoft/api-workbench/commit/a28459a954bce38c024a4a875c560bbbbe0a6d29 and it was not until Atom 1.19 was in stable that the first report appeared.

/cc: @ungb Can you look at this and see if you can narrow down the repro steps?

**Comment by nathansobo** [comment]
@Ben3eeE This doesn't look related to the editor at all, but it could be related to the Electron upgrade. The timings of custom element lifecycle callbacks may have changed slightly. If you look at the stack it looks like we're firing an `attachedCallback` due to the *removal* of a child. It doesn't make much sense to me. It also doesn't make sense that an `attachedCallback` would be fired when an element isn't actually attached (as in, has no parent element). I wonder if we could just null guard this situation and move on.
