### ISSUE TITLE
Uncaught Error: Cannot find module '../build/Release/onig_scanner.node'

### ISSUE THREAD

**Issue by GittyCamilla** [atom/atom#15356]
1.Open the program

1. Also crashed mid use when I had a few files (3 or 4) open and was trying to open another

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module '../build/Release/onig_scanner.node'

```
At module.js:472

Error: Cannot find module '../build/Release/onig_scanner.node'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.2/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.19.2/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.19.2/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/oniguruma/src/oniguruma.js:1:190)
    at Object.<anonymous> (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/oniguruma/src/oniguruma.js:105:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.2/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.2/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.19.2/resources/app/static/<embedded>:96:26)
    at get__ref (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/first-mate/lib/grammar.js:13:33)
    at get_OnigRegExp (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/first-mate/lib/grammar.js:17:45)
    at new Grammar (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/first-mate/lib/grammar.js:58:42)
    at GrammarRegistry.module.exports.GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/first-mate/lib/grammar-registry.js:202:23)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/first-mate/lib/grammar-registry.js:121:82
    at parseContents (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/season/lib/cson.js:123:13)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/season/lib/cson.js:212:26
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report - did you remember if Atom was updated right before you started seeing the error?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15356#issuecomment-323149034. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
