### ISSUE TITLE
Cannot read property 'getDomNode' of undefined

### ISSUE THREAD

**Issue by jessicafndez** [atom/atom#15361]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [hyperclick](https://github.com/facebooknuclide/hyperclick) package 0.0.40

### Stack Trace

Failed to activate the hyperclick package

```
At Cannot read property 'getDomNode' of undefined

TypeError: Cannot read property 'getDomNode' of undefined
    at getLinesDomNode (/packages/hyperclick/lib/HyperclickForTextEditor.js:99:40)
    at addMouseListeners (/packages/hyperclick/lib/HyperclickForTextEditor.js:109:9)
    at HyperclickForTextEditor._setupMouseListeners (/packages/hyperclick/lib/HyperclickForTextEditor.js:115:7)
    at /packages/hyperclick/lib/HyperclickForTextEditor.js:60:10)
    at Hyperclick.observeTextEditor (/packages/hyperclick/lib/Hyperclick.js:85:37)
    at /packages/hyperclick/lib/Hyperclick.js:74:20
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.19.2/resources/app/src/workspace.js:717:15)
    at /packages/hyperclick/lib/Hyperclick.js:62:51)
    at Object.activate (/packages/hyperclick/lib/main.js:55:16)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.2/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.2/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.2/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.2/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.19.2/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.19.2/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.19.2/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.0 
atom-typescript 11.0.6 
autoclose-html 0.23.0 
busy-signal 1.4.3 
git-plus 7.3.3 
hyperclick 0.0.40 
intentions 1.1.2 
linter 2.2.0 
linter-ui-default 1.6.3 
nuclide 0.229.0 
php-integrator-annotations 1.1.1 
php-integrator-autocomplete-plus 1.2.0 
php-integrator-base 2.1.7 
php-integrator-call-tips 1.2.1 
php-integrator-core 2.0.2 
php-integrator-linter 1.3.0 
php-integrator-navigation 1.1.1 
php-integrator-symbol-viewer 0.6.4 
php-integrator-tooltips 1.1.3 
pigments 0.39.1 
platformio-ide-terminal 2.3.1 
project-manager 3.3.3 
Remote-FTP 0.10.7 
terminal-plus 0.14.5 
todo-show 1.11.0 
```

**Comment by Ben3eeE** [comment]
Thanks for contributing!

It appears that this is being caused by the [hyperclick package](https://github.com/facebooknuclide/hyperclick/issues/32), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
