### ISSUE TITLE
Latest Atom release fails to build correctly

### ISSUE THREAD

**Issue by benjamenhogben** [atom/atom#15362]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Latest update fails to build itself after newest release - 1.2 is not installed and trying to open 1.19.xx throws error:
The code execution cannot proceed because node.dll was not found. Reinstalling the program may fix this problem.

### Steps to Reproduce

1. Install Atom 1.19xx on Windows 7, Windows 10
2. Check for updates
3. Close Atom
4. Try to re open atom from shortcut

**Expected behavior:** Opens newest atom version

**Actual behavior:** Atom.exe has been moved, and atom 1.20 has not been installed

**Reproduces how often:** Tried on two machines, one windows 7 and one windows 10 happened 100% of the time

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

C:\>atom --version

C:\>apm --version
module.js:471
    throw err;
    ^

Error: Cannot find module '../build/Release/git.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\SQ-47\AppData\Local\atom\app-1.19.2\resources\app\apm\node_modules\git-utils\lib\git.js:8:16)
    at Object.<anonymous> (C:\Users\SQ-47\AppData\Local\atom\app-1.19.2\resources\app\apm\node_modules\git-utils\lib\git.js:371:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by benjamenhogben** [comment]
Looks like 1.20 is a beta and shouldn't have been released?

Closing Issue as the release is no longer in the stream
