### ISSUE TITLE
Clean Atom install crashes on startup

### ISSUE THREAD

**Issue by 0alpha** [atom/atom#15371]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom crashes on startup, even after a clean install.

### Steps to Reproduce

1. Open Atom

**Expected behavior:** Atom starts.

**Actual behavior:** Atom crashes

**Reproduces how often:** Every time.

### Versions

`atom --version` returns:
```
Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

OS version: Mac OS X 10.10.5 Yosemite

### Additional Information

Process sample:
https://gist.github.com/SV-AlphaDelta/231da5bc791c7137dfaa12c2a1ecf050

**Comment by rsese** [comment]
Thanks for the report - was there any difference at all when trying in safe mode?  Also, can you try temporarily resetting to factory defaults and see if that helps?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

Lastly, can you share any crash logs?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs

**Comment by SV-AlphaDelta** [comment]
Ran Atom again from safe mode, with $ATOM_HOME unset.

Crash log:
```
8/17/17 11:08:27.682 PM Atom[5672]: Error: EACCES: permission denied, mkdir '/$HOME'
    at Object.fs.mkdirSync (fs.js:855:18)
    at sync (/Users/Shared/Applications/Atom.app/Contents/Resources/app/node_modules/mkdirp/index.js:71:13)
    at sync (/Users/Shared/Applications/Atom.app/Contents/Resources/app/node_modules/mkdirp/index.js:77:24)
    at Function.sync (/Users/Shared/Applications/Atom.app/Contents/Resources/app/node_modules/mkdirp/index.js:77:24)
    at Proxy.makeTreeSync (/Users/Shared/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at Config.module.exports.Config.initializeConfigDirectory (/Users/Shared/Applications/Atom.app/Contents/Resources/app/src/config.js:438:10)
    at Config.module.exports.Config.load (/Users/Shared/Applications/Atom.app/Contents/Resources/app/src/config.js:423:12)
    at new AtomApplication (/Users/Shared/Applications/Atom.app/Contents/Resources/app/src/main-process/atom-application.js:117:19)
    at Function.module.exports.AtomApplication.open (/Users/Shared/Applications/Atom.app/Contents/Resources/app/src/main-process/atom-application.js:61:9)
    at App.<anonymous> (/Users/Shared/Applications/Atom.app/Contents/Resources/app/src/main-process/start.js:71:21)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

**Comment by 50Wliu** [comment]
Woah.  That looks like your `HOME` environment variable isn't set.  What happens when you do `echo $HOME` in the terminal?

**Comment by SV-AlphaDelta** [comment]
`echo $HOME` prints `/Users/USERNAME`.
