### ISSUE TITLE
Uncaught TypeError: Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by leon740727** [atom/atom#15391]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'props' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:161

TypeError: Cannot read property 'props' of undefined
    at getKey (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:161:27)
    at mapOldKeysToIndices (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:166:23)
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:102:15)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:108:26)
    at LinesTileComponent.update (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:3504:18)
    at updateComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:52:19)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:16:25)
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:108:26)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:379:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:273:16)
    at etch.getScheduler.updateDocument (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:224:46)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:187:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
     -2:25 core:backspace (input.hidden-input)
     -2:24.3.0 core:paste (input.hidden-input)
 11x -2:23.9.0 core:move-left (input.hidden-input)
  8x -2:22 core:select-left (input.hidden-input)
     -2:20.2.0 core:cut (input.hidden-input)
     -2:19.7.0 core:backspace (input.hidden-input)
     -2:18.3.0 core:paste (input.hidden-input)
     -2:16.9.0 intentions:highlight (input.hidden-input)
     -2:16.7.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -2:16.4.0 core:backspace (input.hidden-input)
     -2:16 core:paste (input.hidden-input)
     -2:15 core:save (input.hidden-input)
     -0:54.1.0 snippets:next-tab-stop (input.hidden-input)
     -0:54.1.0 snippets:expand (input.hidden-input)
     -0:54.1.0 editor:indent (input.hidden-input)
     -0:52.9.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
atom-easy-jsdoc 4.12.1 
atom-typescript 11.0.7 
auto-detect-indentation 1.3.0 
banana-js 0.2.5 
busy-signal 1.4.3 
intentions 1.1.5 
language-lua 0.9.11 
linter 2.2.0 
```

**Comment by Ben3eeE** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by nathansobo** [comment]
All similar exceptions reported in BugSnag were preceded by an exception `Cannot read property 'domNode' of undefined' from within Etch code, which leads me to believe we are somewhere calling `etch.updateSync` with an uninitialized component. I've added some exceptions upstream from that error that name the constructor of the component in question so we can hopefully get some more insight.

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15391#issuecomment-323662550. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
