### ISSUE TITLE
TypeError, Atom crashed and now will not work despite reinstall

### ISSUE THREAD

**Issue by de-Vere** [atom/atom#15462]
G'day everyone,

Was doing an assignment in Atom and all of a sudden it crashed, everything went blank and it opened up what appeared to be Chrome Dev Tools or something similar, with the console log and this big long error (copied below).

I tried exiting out of dev tools and it did nothing, Atom just remained with a completely blank white screen and the title bar up the top, there was no menu folders or anything. I did have third party (downloaded through Atom) themes and have never performed any of my own editing on any of the config files (because I do not know how to/don't have the requisite experience etc).

After removing all files in AppData\Local and AppData\Roaming, uninstalling and reinstalling three times, following the given solutions bother here (https://github.com/atom/atom/issues/14085) and here (https://github.com/atom/atom/issues/5389) and here (https://github.com/atom/atom/issues/11868) but unfortunately none of these have worked.

Could any of you wonderful individuals shed some light on this?

Kind regards,
Paul

TypeError: Cannot set property 'important' of undefined
    at Array.<anonymous> (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\variable.js:31:42)
    at Variable.find (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\variable.js:48:17)
    at Variable.eval (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\variable.js:26:21)
    at Expression.eval (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\expression.js:31:37)
    at Value.eval (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\value.js:18:30)
    at Array.<anonymous> (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\variable.js:33:28)
    at Variable.find (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\variable.js:48:17)
    at Variable.eval (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\variable.js:26:21)
    at Expression.eval (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\expression.js:31:37)
    at Value.eval (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\value.js:18:30)
    at Array.<anonymous> (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\variable.js:33:28)
    at Variable.find (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\variable.js:48:17)
    at Variable.eval (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\variable.js:26:21)
    at C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\call.js:31:54
    at Array.map (native)
    at Call.eval (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\call.js:31:26)
    at Expression.eval (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\expression.js:31:37)
    at Value.eval (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\value.js:18:30)
    at Array.<anonymous> (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\variable.js:33:28)
    at Variable.find (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\variable.js:48:17)
    at Variable.eval (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\variable.js:26:21)
    at Condition.eval (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\condition.js:33:29)
    at Definition.matchCondition (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\mixin-definition.js:156:43)
    at calcDefGroup (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\mixin-call.js:43:66)
    at MixinCall.eval (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\mixin-call.js:96:55)
    at Ruleset.eval (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\tree\ruleset.js:116:32)
    at module.exports (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\transform-tree.js:67:22)
    at ParseTree.toCSS (C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\parse-tree.js:14:25)
    at C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\render.js:31:40
    at C:\Users\paulr\AppData\Local\atom\app-1.19.3\resources\app\node_modules\less\lib\less\parse.js:63:17
handleSetupError @ index.js:87

**Comment by Ben3eeE** [comment]
Have you tried any of the steps in the flight manual which is linked in the issue template?
https://flight-manual.atom.io/hacking-atom/sections/debugging/

---

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by de-Vere** [comment]
Hey Ben, thanks for the fast response,

Got it started in safe mode, ran the "clear-window-state" and ".atom-backup" scripts and it is working now.

Not too sure what could have been left behind somewhere causing it to crash like that after completely erasing and reinstalling the program? Any ideas?

**Comment by Ben3eeE** [comment]
> Not too sure what could have been left behind somewhere causing it to crash like that after completely erasing and reinstalling the program? Any ideas?

`~/.atom`

**Comment by de-Vere** [comment]
So I just must have missed  ".atom" when clearing out program files etc?
I'll definitely remember that for the future.
Thanks heaps mate!!

**Comment by de-Vere** [comment]
Actually before I lose you to more pressing concerns,

What is the full file directory for the `~\.atom` file?

I've deleted the backup from the command line just in case it ever rears it's head to wreak havoc on me, this is more just an exercise in curiosity now.

**Comment by Ben3eeE** [comment]
On Windows it is `%USERPROFILE%\.atom`
