### ISSUE TITLE
livestyle-atom package error

### ISSUE THREAD

**Issue by seyedabbasseyedi** [atom/atom#15461]
**Atom**: 1.19.3 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [livestyle-atom](https://github.com/livestyle/atom) package 0.2.9

### Stack Trace

Failed to activate the livestyle-atom package

```
At Cannot read property 'getDomNode' of undefined

TypeError: Cannot read property 'getDomNode' of undefined
    at getLinesDomNode (/packages/livestyle-atom/lib/analyzer/hyperlink.js:101:58)
    at module.exports (/packages/livestyle-atom/lib/analyzer/hyperlink.js:85:5)
    at atom.workspace.observeTextEditors.editor (/packages/livestyle-atom/lib/analyzer/decorator.js:28:13)
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.19.3/resources/app/src/workspace.js:717:15)
    at module.exports (/packages/livestyle-atom/lib/analyzer/decorator.js:21:37)
    at module.exports (/packages/livestyle-atom/lib/analyzer/index.js:36:21)
    at analyzer.add.atom.config.observe.enabled (/packages/livestyle-atom/index.js:235:25)
    at Config.module.exports.Config.observeKeyPath (~/AppData/Local/atom/app-1.19.3/resources/app/src/config.js:625:13)
    at Config.module.exports.Config.observe (~/AppData/Local/atom/app-1.19.3/resources/app/src/config.js:150:27)
    at setupAnalyzer (/packages/livestyle-atom/index.js:233:16)
    at Object.module.exports.activate (/packages/livestyle-atom/index.js:20:2)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.3/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.3/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.3/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.3/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.3/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.3/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.3/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.19.3/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.19.3/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.19.3/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.19.3/resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
atom-live-server 2.1.2 
auto-indent 0.5.0 
autoclose-html 0.23.0 
color-picker 2.2.5 
drag-relative-path 1.1.3 
emmet 2.4.3 
indent-guide-improved 1.4.13 
javascript-snippets 1.2.1 
livestyle-atom 0.2.9 
minimap 4.29.3 
rest-client 1.3.1 
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [livestyle-atom](https://atom.io/packages/livestyle-atom) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
