### ISSUE TITLE
Uninstalling any package failed

### ISSUE THREAD

**Issue by GrimDev** [atom/atom#15485]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Hi !
Since i upgraded my atom to 1.9.3, I have the following error when I try to uninstall any package.
This is minor because the package is finally removed and disappears from the package list if I restart atom and it seems to not appear when I disable the package before.

```
/usr/share/atom/resources/app/apm/lib/auth.js:22
      return keytar.findPassword(tokenName).then(function(token) {
                                           ^

TypeError: Cannot read property 'then' of undefined
    at Object.getToken (/usr/share/atom/resources/app/apm/lib/auth.js:22:44)
    at Uninstall.module.exports.Uninstall.registerUninstall (/usr/share/atom/resources/app/apm/lib/uninstall.js:58:19)
    at iterate (/usr/share/atom/resources/app/apm/node_modules/async/lib/async.js:134:13)
    at Object.async.eachSeries (/usr/share/atom/resources/app/apm/node_modules/async/lib/async.js:150:9)
    at Uninstall.module.exports.Uninstall.run (/usr/share/atom/resources/app/apm/lib/uninstall.js:124:20)
    at Object.run (/usr/share/atom/resources/app/apm/lib/apm-cli.js:227:32)
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/lib/cli.js:8:7)
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/lib/cli.js:12:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

### Steps to Reproduce

1. Go to Settings/Packages
2. Uninstall a package without disabling it before by clicking "Uninstall"

**Expected behavior:** 
Package removed with success

**Actual behavior:** 
Package removed but still in the package list, and the error in the description appears.

**Reproduces how often:** 
100%

### Versions
On Debian Jessie 8.9

Atom --version:
Atom    : 1.19.3
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version:
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.9
git 2.1.4

Thanks you.

**Comment by rsese** [comment]
Hmmm, I wonder if this is related /cc https://github.com/atom/apm/pull/731?

**Comment by GrimDev** [comment]
I don't know if it is related, but it seems to be.
In any case, keytar.findPassword should return a promise.

**Comment by GrimDev** [comment]
Update : I have the same error in the shell when I run the `apm rm` command.
