### ISSUE TITLE
Uncaught Error: Cannot find module 'ajv'

### ISSUE THREAD

**Issue by ChicagoBoom** [atom/atom#15491]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module 'ajv'

```
At C:\Users\k2a\AppData\Local\atom\app-1.19.4\resources\app\static\<embedded>:1

Error: Cannot find module 'ajv'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.4/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.4/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.19.4/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.19.4/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/har-validator/lib/node4/promise.js:30:12)
    at Object.<anonymous> (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/har-validator/lib/node4/promise.js:133:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.4/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.4/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.4/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.4/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/request/lib/har.js:5:16)
    at Object.<anonymous> (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/request/lib/har.js:217:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.4/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.4/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.4/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.4/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/request/request.js:25:11)
    at Object.<anonymous> (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/request/request.js:1567:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.4/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.4/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

### Commands

```
     -6:47.8.0 incompatible-packages:view (div.incompatible-packages-status.inline-block.text.text-error)
```

### Non-Core Packages

```
css-snippets 1.1.0 
jslint 1.5.1 
linter-ansible-linting 1.3.0 
platformio-ide-terminal 2.5.4 
pure-syntax 0.3.0 
```

**Comment by rsese** [comment]
Thanks for the report - can you confirm if you got this error right after installing Atom or right after updating?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15491#issuecomment-325881726. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
