### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy-dr.r...

### ISSUE THREAD

**Issue by TradingAlgoritmico** [atom/atom#15502]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy-dr.reply.it proxy-dr.reply.it:8080

```
At stream.js:74

Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy-dr.reply.it proxy-dr.reply.it:8080
    at ClientRequest.onError (/Applications/Atom.app/Contents/Resources/app/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1025:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -1:58.1.0 github:toggle-git-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -1:51.7.0 github:toggle-github-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -0:38.1.0 core:backspace (input.hidden-input)
     -0:35.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report - the error seems like a networking/DNS issue?  Is the error reproducible for you?

**Comment by TradingAlgoritmico** [comment]
Hi,

in my office I'm behind a proxy.

I tryied at home and works fine.

Thanks Alex.



2017-08-30 19:21 GMT+02:00 Robert Sese <notifications@github.com>:
