### ISSUE TITLE
Uncaught Error: Assertion failed: groupChangesSinceCheckpoint() returned false.

### ISSUE THREAD

**Issue by brandonkrull** [atom/atom#15521]
[Enter steps to reproduce:]

Using forward/backward find in normal mode with vim-mode-plus throws error

e.g.

fX (next X)
FX (previous X)
tX (before next X)
TX (before previous X)

**Atom**: 1.21.0-dev-d3a8fe693 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Assertion failed: groupChangesSinceCheckpoint() returned false.

```
At /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1053

Error: Assertion failed: groupChangesSinceCheckpoint() returned false.
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:908:20)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1234:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2621:24)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2583:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1232:25)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1198:25)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1633:28)
```

### Commands

```
     -2:34.3.0 vim-mode-plus:find (input.hidden-input)
  6x -2:34.3.0 blur (input.hidden-input)
  3x -2:32.6.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -2:20.7.0 window:toggle-dev-tools (input.hidden-input)
 20x -2:20.2.0 blur (input.hidden-input)
     -1:38.1.0 core:backspace (input.hidden-input)
     -1:37.5.0 editor:consolidate-selections (input.hidden-input)
     -1:37.5.0 core:cancel (input.hidden-input)
     -1:37.2.0 editor:consolidate-selections (input.hidden-input)
     -1:37.2.0 core:cancel (input.hidden-input)
  2x -1:36.3.0 core:backspace (input.hidden-input)
     -1:36 editor:consolidate-selections (input.hidden-input)
     -1:36 core:cancel (input.hidden-input)
 15x -1:34.6.0 blur (input.hidden-input)
     -0:09.6.0 vim-mode-plus:find (input.hidden-input)
  9x -0:09.6.0 blur (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.5 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
busy-signal 1.4.3 
ex-mode 0.18.0 
git-plus 7.9.3 
intentions 1.1.5 
language-latex 1.1.1 
latex 0.46.0 
linter 2.2.0 
linter-bootlint 1.1.0 
linter-csslint 2.0.0 
linter-flake8 2.2.1 
linter-htmlhint 1.3.3 
linter-ui-default 1.6.8 
split-diff 1.5.1 
vim-mode-plus 1.0.0 
```

**Comment by brandonkrull** [comment]
Yessssssssssssssssssss. My poor Atom was basically unusable without vim motions. Thanks @Ben3eeE !
