### ISSUE TITLE
Uncaught TypeError: Cannot read property '__reactInternalInstance$ct3ksqiu5dy54zl2szkf0f6r' of null

### ISSUE THREAD

**Issue by jamesleesaunders** [atom/atom#15541]
Steps to reproduce:
1. Added Repo https://github.com/jamesleesaunders/d3.ez to Atom
2. View 'GitHub Tab'
3. There are strangely 4 Pull requests displayed which are already Closed. I don't know why these 4 PRs are listed. It will not let them be un-pinned either.
4. Click on PR#11
5. Click 'View Conversation' 
It then errors as below...

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property '__reactInternalInstance$ct3ksqiu5dy54zl2szkf0f6r' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDOMComponentTree.js:113

TypeError: Cannot read property '__reactInternalInstance$ct3ksqiu5dy54zl2szkf0f6r' of null
    at Object.getClosestInstanceFromNode (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDOMComponentTree.js:113:17)
    at findParent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventListener.js:38:38)
    at handleTopLevelImpl (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventListener.js:67:34)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/Transaction.js:143:26)
    at Object.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:32)
    at Object.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactUpdates.js:97:33)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventListener.js:147:26)
```

### Commands

```
     -8:56.9.0 core:paste (input.input-text.native-key-bindings)
     -1:53.4.0 core:focus-next (input.input-text.github-CredentialDialog-Username)
     -1:20.7.0 github:toggle-github-tab (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
```

**Comment by BinaryMuse** [comment]
This is happening because that PR was merged into a branch that has since been deleted, so `mergeRef` is coming back null on the `MergedEvent`. https://github.com/atom/github/pull/1151 has the fix.

**Comment by BinaryMuse** [comment]
@jamesleesaunders Regarding the four PRs that are listed, that's because you're on the `master` branch, and Atom is trying to figure out what PR is associated with your branch. Those four PRs were cut from `master`, so it lists them as possibilities for you to select.

**Comment by jamesleesaunders** [comment]
@BinaryMuse Wow! Thank you for looking into this and the PR fix! Amazing support!

**Comment by BinaryMuse** [comment]
@jamesleesaunders You're welcome! ^_^ Thanks for the catch!
