### ISSUE TITLE
Uncaught Error: Replacing non-existent child when trying to split panes

### ISSUE THREAD

**Issue by lzkelley** [atom/atom#15587]
Possibly related to https://github.com/atom/atom/issues/14616

1. `view > panes > split right`

None of the splits work, neither from the view-menu nor keyboard shortcuts.

**Atom**: 1.19.6 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Replacing non-existent child

```
At /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:145

Error: Replacing non-existent child
    at PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:145:47)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app/src/pane.js:984:27)
    at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app/src/pane.js:964:25)
    at HTMLElement.pane:split-right-and-copy-active-item (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:269:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:43.5.0 project-manager:list-projects (atom-pane.pane.active)
     -0:41.5.0 core:move-down (input.hidden-input)
     -0:41.1.0 core:confirm (input.hidden-input)
  2x -0:41 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:24.2.0 editor:fold-at-indent-level-1 (input.hidden-input)
     -0:13.2.0 pane:split-right-and-copy-active-item (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.5 
atom-html-preview 0.2.2 
atomic-emacs 0.12.1 
bug-report 0.7.1 
busy-signal 1.4.3 
color-picker 2.2.5 
counter 0.3.5 
emmet 2.4.3 
file-icons 2.1.11 
file-watcher 1.2.6 
git-time-machine 1.5.9 
goto-definition 1.3.4 
intentions 1.1.5 
language-cython 0.3.0 
language-latex 1.1.1 
language-restructuredtext 1.1.0 
latex 0.46.0 
linter 2.2.0 
linter-chktex 1.3.1 
linter-flake8 2.2.1 
linter-markdown 5.2.0 
linter-ui-default 1.6.8 
MagicPython 1.0.12 
markdown-scroll-sync 2.1.2 
markdown-writer 2.7.2 
merge-conflicts 1.4.5 
minimap 4.29.6 
minimap-cursorline 0.2.0 
pdf-view 0.59.0 
pretty-json 1.6.4 
project-manager 3.3.5 
python-indent 1.1.0 
rst-preview-pandoc 0.1.12 
Sublime-Style-Column-Selection 1.7.4 
symbols-tree-view 0.14.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you reproduce in safe mode (`atom --safe`)?  Also, are your steps to reproduce the same as https://github.com/atom/atom/issues/14616#issuecomment-325599119?  I.e. do you have to start an empty window, add a project, open a file, then split?  Or is any attempt at splitting generating an error for you?

After making sure to save any unsaved work, does clearing saved state clear things up for you?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

**Comment by lzkelley** [comment]
Hmm.  I haven't been able to reproduce the problem which first occurred after a (hard) reboot.  Normal restarts since then also haven't reproduced the problem.  It's probably safe to assume that something got corrupted at the time, but there isn't a general issue.  Sorry I didn't confirm before posting, but I'll close this for now --- and update if the issue returns!

**Comment by julian-carpenter** [comment]
Well, with me the error seems to persist even after a hard reboot.
It works well when i start Atom with the safe flag though.
Will try to narrow down a possible plugin incompatibility 
____________________________________

1. ... Open Atom
2. ... Try to split Editor

**Atom**: 1.19.7 x64
**Electron**: 1.6.11
**OS**: linux 4.12.12-1-ARCH
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Replacing non-existent child

```
At /usr/lib/atom/src/pane-container.js:141

Error: Replacing non-existent child
    at PaneContainer.replaceChild (/usr/lib/atom/src/pane-container.js:141:41)
    at Pane.module.exports.Pane.split (/usr/lib/atom/src/pane.js:982:21)
    at Pane.module.exports.Pane.splitRight (/usr/lib/atom/src/pane.js:962:19)
    at HTMLElement.pane:split-right-and-copy-active-item (/usr/lib/atom/src/register-default-commands.js:267:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:265:29)
    at /usr/lib/atom/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:606:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:397:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:100:36)
    at HTMLDocument.<anonymous> (/usr/lib/atom/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:40.9.0 application:reopen-project (input.hidden-input)
     -0:35.3.0 intentions:highlight (input.hidden-input)
     -0:35.1.0 pane:split-right-and-copy-active-item (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
autocomplete-fortran 0.9.5 
autocomplete-python 1.10.2 
autocomplete-R 0.6.0 
busy-signal 1.4.3 
color-picker 2.2.5 
ctrl-dir-scroll 0.2.5 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.5 
intentions-colorpicker 1.0.1 
kite 0.41.0 
language-latex 1.1.1 
language-markdown 0.25.1 
language-matlab 0.2.1 
latex 0.46.0 
latextools 0.8.5 
linter 2.2.0 
linter-docker 0.2.1 
linter-matlab 1.1.0 
linter-pylint 2.1.0 
linter-sass-lint 1.7.6 
linter-scss-lint 3.1.1 
linter-spell 0.15.0 
linter-spell-latex 0.10.0 
linter-ui-default 1.6.8 
markdown-writer 2.7.2 
minimap 4.29.6 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.2 
script 3.15.0 
sync-settings 0.8.3 
```

**Comment by rsese** [comment]
> it's the minimap-cursorline package. don't know why, but disabling
> the package solves the error. It is already reported here: Issue 3 ... or rather here

Ahhh, awesome thanks for dropping that note @julian-carpenter :+1:

**Comment by difelice** [comment]
[Enter steps to reproduce:]

1. Open
2. Try to split

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Replacing non-existent child

```
At /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:145

Error: Replacing non-existent child
    at PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:145:47)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app/src/pane.js:998:27)
    at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app/src/pane.js:978:25)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/layout.js:50:33)
    at Object.end (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/layout.js:56:16)
    at HTMLLIElement.TabView.element.ondragend (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-view.js:62:29)
```

### Commands

```
     -0:59.5.0 intentions:highlight (input.hidden-input)
     -0:55.6.0 application:add-project-folder (input.hidden-input)
  2x -0:44.9.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:11.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-jest-snippets 1.1.1 
atom-jinja2 0.6.0 
atom-material-syntax-dark 1.0.0 
atom-monokai 0.10.9 
browser-plus 0.0.98 
busy-signal 1.4.3 
change-case 0.6.5 
codemods 0.0.4 
color-picker 2.2.5 
dash-ui 0.4.3 
docblockr 0.11.0 
editorconfig 2.2.2 
flow-ide 1.8.1 
git-blame 1.3.1 
git-plus 7.10.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-babel 2.75.1 
language-hugo 0.3.1 
language-ini 1.19.0 
language-markdown 0.25.1 
language-swift 0.5.0 
lcov-info 0.12.0 
linter 2.2.0 
linter-eslint 8.3.2 
linter-flake8 2.2.1 
linter-flow 5.6.1 
linter-ui-default 1.6.10 
loved-syntax 1.0.2 
monokai-seti 0.9.0 
node-debugger 1.10.1 
pigments 0.40.2 
prettier-atom 0.40.0 
react-snippets 1.0.0 
sort-lines 0.18.0 
spacegray-atom-dark-syntax 1.3.2 
sublime-block-comment 0.5.1 
```

**Comment by Recmo** [comment]
I'm having this issue regularly (v. 1.23.3).

**Comment by rsese** [comment]
@Recmo if you can reproduce in safe mode (`atom --safe`) and after clearing saved state [1] (make sure to save any unsaved work first), go ahead and open a new issue with the issue template filled out and we'll take a look.

[1]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state
