### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=503

### ISSUE THREAD

**Issue by alexmeooow** [atom/atom#15610]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=503

```
At stream.js:74

Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (/Applications/Atom.app/Contents/Resources/app/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:290:19)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:394:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -0:30 core:backspace (input.hidden-input)
     -0:23.6.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.5.0 
atom-ternjs 0.18.3 
color-picker 2.2.5 
emmet 2.4.3 
javascript-snippets 1.2.1 
jshint 1.8.6 
language-babel 2.74.1 
minimap 4.29.6 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm what were you doing at the time of the error and if it's reproducible?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15610#issuecomment-328735294. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
