### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.rd.f...

### ISSUE THREAD

**Issue by henry63** [atom/atom#15679]
[Enter steps to reproduce:]

1. ... accessing behind a corporate firewall
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.rd.xxxxxxxx.fr proxy.rd.xxxxxxxx.fr:8080

```
At stream.js:74

Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.rd.xxxxxxxx.fr proxy.rd.xxxxxxxx.fr:8080
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1025:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.3.1 
ide-json 0.1.0 
ide-python 0.1.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm what you were you doing at the time of the error and if the error is reproducible?

Does your proxy work with other applications on your computer like your web browser?

**Comment by henry63** [comment]
(Late reply) yes the proxy work with http / https
