### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by ivdekov** [atom/atom#15682]
[Enter steps to reproduce:]

1. Start deleting a line.

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2391

TypeError: Cannot match against 'undefined' or 'null'.
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2391:65)
    at TextEditorComponent.screenPositionForMouseEvent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1972:23)
    at didDrag (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1822:43)
    at get_window.requestAnimationFrame (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1900:17)
```

### Commands

```
     -2:08.4.0 core:save (input.hidden-input)
     -2:08.3.0 linter:lint (atom-text-editor.editor.is-focused)
  3x -1:02.0 core:undo (input.hidden-input)
     -0:59.2.0 core:save (input.hidden-input)
     -0:36.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:34.9.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:34.2.0 core:backspace (input.hidden-input)
  2x -0:32.6.0 core:undo (input.hidden-input)
     -0:15.7.0 core:close (input.hidden-input)
     -0:09.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:08.1.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:07.5.0 core:backspace (input.hidden-input)
  2x -0:06.5.0 core:undo (input.hidden-input)
     -0:04.3.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -0:04.0 core:move-down (input.hidden-input)
  4x -0:03.5.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-html-entities 0.1.0 
block-comment 0.4.3 
busy-signal 1.4.3 
docblockr 0.11.0 
intentions 1.1.5 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-eslint 8.2.1 
linter-jscs 4.1.2 
linter-phpcs 1.6.7 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.5 
prettier-atom 0.37.0 
remote-atom 1.3.11 
remote-edit 1.9.0 
sublime-block-comment 0.5.1 
```

**Comment by zenopopovici** [comment]
Happens to me too. While editing PHP files.

1. Editing a document

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.5.1


### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At /Users/Zeno/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:43

TypeError: Cannot match against 'undefined' or 'null'.
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2387:65)
    at TextEditorComponent.screenPositionForMouseEvent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1952:23)
    at getBufferPosition (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:186:31)
    at DatatipManagerForEditor._hideOrCancel (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:544:35)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:337:14)
    at a.__tryOrUnsub (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:43:337)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:42:227)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:393)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at /packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:81:365)
```

### Commands

```
  8x -4:42.4.0 core:move-down (input.hidden-input)
     -4:41.3.0 core:save (input.hidden-input)
     -4:21.3.0 core:copy (input.hidden-input)
     -4:18.4.0 core:paste (input.hidden-input)
     -4:17.5.0 core:save (input.hidden-input)
 13x -2:23 core:close (input.hidden-input)
     -1:30.9.0 go-to-line:toggle (input.hidden-input)
     -1:26.5.0 core:confirm (input.hidden-input)
     -1:22.4.0 core:copy (input.hidden-input)
     -1:21.5.0 core:paste (input.hidden-input)
 13x -1:20.4.0 core:move-left (input.hidden-input)
  2x -1:19.3.0 core:move-right (input.hidden-input)
  2x -1:18.3.0 core:save (input.hidden-input)
  5x -0:07.1.0 core:backspace (input.hidden-input)
     -0:04.9.0 core:move-up (input.hidden-input)
     -0:04.9.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
aligner 1.2.4 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-php 1.2.0 
aligner-stylus 1.1.0 
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-cursor-indent 0.1.2 
atom-ide-ui 0.5.1 
atom-vim-keymap 1.0.1 
atom-wrap-in-tag 0.6.0 
autocomplete-nunjucks 0.5.0 
autocomplete-php 0.3.7 
blame 0.12.0 
busy-signal 1.4.3 
change-case 0.6.5 
copy-filename 1.1.0 
docblockr 0.11.0 
double-tag 0.9.0 
editorconfig 2.2.2 
emmet 2.4.3 
es-identifier-highlight 0.4.3 
escape-utils 0.5.3 
file-type-icons 1.3.4 
filesize 3.0.0 
fold-comments 0.6.0 
git-blame 1.3.1 
git-history 3.3.0 
highlight-column 0.5.4 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-css 0.2.0 
ide-html 0.3.0 
ide-json 0.1.0 
ide-php 0.6.9 
ide-typescript 0.6.2 
ide-vue 0.1.7 
indent-toggle-on-paste 0.1.3 
intentions 1.1.5 
keybinding-cheatsheet 0.1.1 
language-babel 2.75.1 
language-gitignore 0.3.0 
language-nunjucks 4.1.0 
language-svg 0.9.2 
language-vue 0.23.1 
less-than-slash 0.17.0 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-htmlhint 1.3.4 
linter-jsonlint 1.3.0 
linter-php 1.5.1 
linter-stylint 2.2.8 
linter-ui-default 1.6.10 
linter-xo 0.23.1 
markdown-table-editor 0.6.4 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.1 
minimap-selection 4.5.0 
npm-outdated 0.6.0 
pathr 1.0.1 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.0 
php-integrator-base 3.0.1 
php-integrator-navigation 1.2.1 
php-integrator-refactoring 1.4.1 
php-integrator-symbol-viewer 0.6.4 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
qolor 0.4.2 
regex-railroad-diagram 0.19.4 
remember-file-positions 0.2.3 
remember-folds 0.3.0 
Remote-FTP 1.2.5 
resize-indent 0.3.0 
snippets-editor 1.0.0 
Stylus 3.1.1 
Sublime-Style-Column-Selection 1.7.4 
svg-preview 0.11.0 
sync-settings 0.8.3 
tab-numbers 0.6.1 
tabs-to-spaces 1.0.3 
todo-show 2.1.0 
toggle-quotes 1.0.1 
vim-mode-plus 1.9.1 
w3c-validation 0.4.0 
zentabs 0.8.8 
```
