### ISSUE TITLE
Uncaught TypeError: fileType.toLowerCase is not a function

### ISSUE THREAD

**Issue by worbit** [atom/atom#15690]
[Enter steps to reproduce:]

1. just open atom
2. ...but after modifying the config file in probably an inadequate fashion. can't open it anymore...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: fileType.toLowerCase is not a function

```
At /Applications/Atom.app/Contents/Resources/app/src/grammar-registry.js:90

TypeError: fileType.toLowerCase is not a function
    at GrammarRegistry.module.exports.GrammarRegistry.getGrammarPathScore (/Applications/Atom.app/Contents/Resources/app/src/grammar-registry.js:90:45)
    at GrammarRegistry.module.exports.GrammarRegistry.getGrammarScore (/Applications/Atom.app/Contents/Resources/app/src/grammar-registry.js:64:26)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:321:52
    at Set.forEach (native)
    at TextEditorRegistry.grammarAddedOrUpdated (/Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:307:47)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:76:26)
    at Grammar.module.exports.Grammar.activate (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:254:54)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:686:31
    at /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:121:61
    at parseContents (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:123:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:212:26
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
```

### Commands

```
     -0:22.8.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:19.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.3 
compare-files 0.8.1 
emmet 2.4.3 
file-types 0.5.5 
git-clone 0.2.0 
git-plus 7.9.3 
highlight-selected 0.13.1 
python-tools 0.6.9 
rhino-python 0.8.4 
script 3.15.0 
```

**Comment by rsese** [comment]
> ...but after modifying the config file in probably an inadequate fashion. can't open it anymore...

What modification did you make?  Also, can you share your config file so we can take a look?

**Comment by worbit** [comment]
i wanted to add another entry to customFileTypes and just messed up the brackets. i had a bit a hard time finding it to reverse the change. all is back to normal again! but with the error in it, atom didn't let me edit it anymore and did no syntax-highlighting on any of the files anymore.

**Comment by rsese** [comment]
Glad you have things resolved :+1:




> but with the error in it, atom didn't let me edit it anymore and did no syntax-highlighting on any of the files anymore.
