### ISSUE TITLE
Uncaught Error: error: 126/\?\~\AppData\Local\atom\app-1.20.1\resources\app\node_modules\keyboard...

### ISSUE THREAD

**Issue by theDyingMountain** [atom/atom#15719]
[Enter steps to reproduce:]

1. Open File in Atom Editor
2. Press CTRL + S to save file

**Atom**: 1.20.1 ia32
**Electron**: 1.6.9
**OS**: MARIO-PC
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: error: 126\\?\C:\Users\Mario\AppData\Local\atom\app-1.20.1\resources\app\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: error: 126\\?\C:\Users\Mario\AppData\Local\atom\app-1.20.1\resources\app\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.20.1/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.20.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.20.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:56.9.0 intentions:highlight (input.hidden-input)
     -0:56.7.0 find-and-replace:show (input.hidden-input)
     -0:54.3.0 core:confirm (input.hidden-input)
     -0:38.9.0 editor:newline (input.hidden-input)
  2x -0:36 intentions:highlight (input.hidden-input)
     -0:31.6.0 core:delete (input.hidden-input)
     -0:30.6.0 core:move-right (input.hidden-input)
     -0:30 core:backspace (input.hidden-input)
 11x -0:29.8.0 core:move-right (input.hidden-input)
     -0:28.1.0 core:move-left (input.hidden-input)
     -0:22.2.0 core:move-right (input.hidden-input)
  8x -0:18.7.0 intentions:highlight (input.hidden-input)
     -0:05.9.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
autoprefixer 3.7.1 
busy-signal 1.4.3 
css-snippets 1.1.0 
intentions 1.1.5 
javascript-snippets 1.2.1 
linter 2.0.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.7 
php-cs-fixer 4.1.0 
pigments 0.40.2 
split-diff 1.5.0 
twilight 0.3.0 
```

**Comment by Rafa0729** [comment]
I really don´t understand what happened right after I installed Atom-Live-Sever package. My Antivirus is saying this package contains a virus

**Comment by rsese** [comment]
We've seen reports starting the last day or so with keytar and keyboard-layout-manager (https://github.com/atom/atom/issues/14461#issuecomment-331346393, https://github.com/atom/node-keytar/issues/75#issuecomment-330392387) - if you can report this to your anti-virus provider so they can update their definitions, that would be helpful.
