### ISSUE TITLE
node resolver package

### ISSUE THREAD

**Issue by Tikam02** [atom/atom#15714]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [node-resolver](git://github.com/hughsk/atom-node-resolver) package 1.0.1

### Stack Trace

Failed to activate the node-resolver package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.exports.activate (/packages/node-resolver/index.js:12:21)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.5/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.5/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.5/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.5/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.5/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.5/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.5/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.19.5/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.19.5/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.19.5/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.19.5/resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
apex-ui 1.0.1 
atom-clock 0.1.15 
atom-nodejs-snippets 2.0.0 
atom-terminal 0.8.0 
Hydrogen 1.20.0 
node-debugger 1.10.1 
node-resolver 1.0.1 
platformio-ide-terminal 2.6.0 
scroll-through-time 0.2.0 
terminal-plus 0.14.5 
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [node-resolver](https://atom.io/packages/node-resolver) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
