### ISSUE TITLE
Uncaught TypeError: item.serialize is not a function

### ISSUE THREAD

**Issue by GinoHereIam** [atom/atom#15718]
1. Open references of a typescrript function (Symbol references tab)
2. Right click
3. split to right

**Atom**: 1.21.0-beta1 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: item.serialize is not a function

```
At /usr/share/atom-beta/resources/app/node_modules/tabs/lib/tab-bar-view.js:389

TypeError: item.serialize is not a function
    at TabBarView.module.exports.TabBarView.copyItem (/usr/share/atom-beta/resources/app/node_modules/tabs/lib/tab-bar-view.js:389:135)
    at TabBarView.module.exports.TabBarView.splitTab (/usr/share/atom-beta/resources/app/node_modules/tabs/lib/tab-bar-view.js:379:37)
    at Object.TabBarView.addElementCommands.tabs:split-right (/usr/share/atom-beta/resources/app/node_modules/tabs/lib/tab-bar-view.js:137:32)
    at HTMLUListElement.commandsWithPropagationStopped.(anonymous function) (/usr/share/atom-beta/resources/app/node_modules/tabs/lib/tab-bar-view.js:83:42)
    at CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/usr/share/atom-beta/resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom-beta/resources/app/src/atom-environment.js:1354:34)
    at EventEmitter.outerCallback (/usr/share/atom-beta/resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  3x -2:10.4.0 intentions:highlight (input.hidden-input)
     -1:58 github:view-staged-changes-for-current-file (span.syntax--meta.syntax--definition.syntax--function.syntax--ts.entity.syntax--name.syntax--function.syntax--ts)
     -1:49.6.0 find-references:activate (span.syntax--meta.syntax--definition.syntax--function.syntax--ts.entity.syntax--name.syntax--function.syntax--ts)
     -0:12.1.0 tabs:split-right (div.title.icon.icon-telescope)
```

### Non-Core Packages

```
atom-ide-ui 0.3.3 
atom-material-ui 2.0.4 
busy-signal 1.4.3 
flow-ide 1.8.1 
hyperclick 0.0.0 
ide-json 0.1.0 
ide-python 0.1.1 
ide-typescript 0.6.1 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
livereload 0.4.4 
```

**Comment by damieng** [comment]
https://github.com/atom/tabs/pull/522 should stop the error but will do so by not letting you split the references pane at all.

If we want to support splitting pane references we should create an issue for that over at https://github.com/facebook-atom/atom-ide-ui
