### ISSUE TITLE
Atom is unable to open folder with cmd line tool

### ISSUE THREAD

**Issue by mahirk** [atom/atom#15715]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On the command line `atom .` is unable to open the project folder in atom successfully. 

### Steps to Reproduce

1. Open Terminal
2. cd into project folder
3. `atom .` and press enter

**Expected behavior:** Atom opens up in a new window (or tab) and loads the project folder as the active folder

**Actual behavior:** atom attempts to open a new window, but stays in this state:
<img width="1440" alt="screenshot 2017-09-21 16 30 41" src="https://user-images.githubusercontent.com/5751414/30723144-3bff6b14-9eea-11e7-8887-0da1057f600d.png">

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.21.0-beta1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

and 

```
Atom    : 1.20
```

**Comment by alexshk** [comment]
Can't reproduce. Maybe problems in packages? Have you tried remove/rename folder `~/.atom` and run Atom again?

**Comment by BekoBou** [comment]
Nope. I renamed directory but never happened.

```
Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by BekoBou** [comment]
- Directory`~/.atom` renamed
- Run `atom .`
- Developer Console output:

```
Uncaught (in promise) Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/Applications/Atom.app/Contents/Resources/app/src/item-registry.js:11:21)
    at PaneContainer.didAddPaneItem (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:269:29)
    at PaneContainer.didAddPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:242:18)
    at Pane.module.exports.Pane.setContainer (/Applications/Atom.app/Contents/Resources/app/src/pane.js:162:32)
    at PaneAxis.module.exports.PaneAxis.setContainer (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:97:36)
    at PaneContainer.setRoot (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:137:21)
    at PaneContainer.deserialize (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:58:16)
    at WorkspaceCenter.deserialize (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:31:30)
    at Workspace.deserialize (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:415:42)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1263:35
```

**Comment by ffurrer** [comment]
I had the same issue, to resolve I moved the .atom directory started atom in that directory and moved the .atom directory back:

```
mv ~/.atom ~/.atom_old
atom .  # in the folder that would freeze
# Close atom
mv ~/.atom ~/.atom_new_but_not_required
mv ~/.atom_old ~/.atom
```
And then
```
atom .
```
would just work fine.
I didn't really understand what changed in the mean time, also tried to use diff, for intermediate steps, but then as mentioned above copying the whole config folder back just worked fine.

**Comment by mahirk** [comment]
thanks @ffurrer that worked perfectly, looks like it just needed to be shifted refreshed. Closing.
