### ISSUE TITLE
Uncaught Error: Accès refusé./\?\~\AppData\Local\atom\app-1.20.1\resources\app\node_modules\key...

### ISSUE THREAD

**Issue by phbernard** [atom/atom#15717]
The following error just happened at Atom startup. It worked great yesterday, with no apparent change that could justify the new behavior.

A few minutes later, I also experienced #14461 while typing.

What is special on my station? BitDefender blocks apps when they try to access files in "protected" directories. However, this feature is designed to handle white listing nicely: when an app is blocked, BitDefender displays a notification and you can unblock the app. I already unblocked Atom a few days ago. And this time Atom does not display anything about a "fraudulent" access from Atom. So I just mention this point to be comprehensive.

**Atom**: 1.20.1 ia32
**Electron**: 1.6.9
**OS**: Up-to-date Windows 10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Accès refusé.
\\?\C:\Users\me\AppData\Local\atom\app-1.20.1\resources\app\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: Accès refusé.
\\?\C:\Users\me\AppData\Local\atom\app-1.20.1\resources\app\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.20.1/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/helpers.js:244:117)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.20.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.20.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:23.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
react 0.16.2 
```

**Comment by rsese** [comment]
> However, this feature is designed to handle white listing nicely: when an app is blocked, BitDefender displays a notification and you can unblock the app. I already unblocked Atom a few days ago. And this time Atom does not display anything about a "fraudulent" access from Atom. So I just mention this point to be comprehensive.

Thanks for the details @phbernard - we've seen reports starting the last day or so with keytar and keyboard-layout-manager (https://github.com/atom/atom/issues/14461#issuecomment-331346393, https://github.com/atom/node-keytar/issues/75#issuecomment-330392387) and if you can report this to BitDefender, that would be helpful.
