### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.20.1\res...

### ISSUE THREAD

**Issue by AkashPatelUAlberta** [atom/atom#15722]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\apate\AppData\Local\atom\app-1.20.1\resources\app\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: The specified module could not be found.
\\?\C:\Users\apate\AppData\Local\atom\app-1.20.1\resources\app\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.20.1/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.20.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.20.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
 20x -0:48.1.0 core:backspace (input.hidden-input)
     -0:28.2.0 editor:newline (input.hidden-input)
     -0:25.9.0 core:move-up (input.hidden-input)
  9x -0:25.8.0 core:move-right (input.hidden-input)
  3x -0:23.8.0 core:move-up (input.hidden-input)
  2x -0:22.7.0 editor:move-to-beginning-of-word (input.hidden-input)
     -0:21.8.0 core:move-left (input.hidden-input)
 11x -0:21.3.0 editor:select-to-end-of-word (input.hidden-input)
     -0:18.8.0 core:select-right (input.hidden-input)
     -0:17.6.0 core:move-down (input.hidden-input)
     -0:17.5.0 core:move-left (input.hidden-input)
     -0:17.1.0 core:move-down (input.hidden-input)
     -0:17 core:move-left (input.hidden-input)
     -0:16.5.0 core:move-down (input.hidden-input)
  3x -0:16.2.0 core:move-right (input.hidden-input)
  2x -0:14.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
apex-ui-personalize 0.1.0 
editor-background 1.2.41 
minimap 4.29.7 
```

**Comment by shahejad** [comment]
I also has the same issue.
Looks like the antiviruses are considering this module as malware and removing them from the system.

**Comment by Altaraxia** [comment]
Just experienced the same thing. It was labeled as malware and quarantined by Avast, but Atom also stated in its bug statement that the file contained a virus. Guess it's just a bug or false alarm.

**Comment by steveangstrom** [comment]
I also experience this.
Any keyboard interaction with Atom triggers around 3 errors

**Comment by rsese** [comment]
Yes if you have anti-virus software on your computer @AkashPatelUAlberta then that may be the issue, we've seen reports starting the last day or so with keytar and keyboard-layout-manager (https://github.com/atom/atom/issues/14461#issuecomment-331346393, https://github.com/atom/node-keytar/issues/75#issuecomment-330392387).  If you have anti-virus software, please report this to your anti-virus vendor so they can update their definitions  (@shahejad and @Altaraxia if you can do the same that would be great).

If you don't have anti-virus software, then re-installing may help.
