### ISSUE TITLE
Uncaught Error: error: 225\\?\C:\Users\Pierre\AppData\Local\atom\app-1.20.1\resources\app\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

### ISSUE THREAD

**Issue by pistou** [atom/atom#15723]
I had a first error message in french that basically says "Unable to complete the operation because the file contains a virus or a potentially unwanted software."

I ran AVG Free, Malwarebyte and ADWCleaner, everything appears to be clear.

Then this happens everytime I make a keyboard shortcut

[Enter steps to reproduce:]

1. Open Atom
2. Make a shortcut (Ctrl + N for instance)

**Atom**: 1.20.1 ia32
**Electron**: 1.6.9
**OS**: Windows 10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: error: 225\\?\C:\Users\Pierre\AppData\Local\atom\app-1.20.1\resources\app\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: error: 225\\?\C:\Users\Pierre\AppData\Local\atom\app-1.20.1\resources\app\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.20.1/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.20.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.20.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.5 
busy-signal 1.4.3 
color-picker 2.2.5 
column-select 0.2.0 
file-icons 2.1.12 
flatland-dark-ui 0.2.5 
highlight-selected 0.13.1 
intentions 1.1.5 
language-liquid 0.6.0 
language-sql-mysql 0.3.1 
linter 2.2.0 
linter-eslint 8.3.2 
linter-htmlhint 1.3.3 
linter-php 1.5.0 
linter-ui-default 1.6.10 
markdown-table-formatter 2.9.0 
minimap 4.29.7 
minimap-split-diff 0.3.7 
new-moon-atom-syntax 2.0.9 
pigments 0.40.2 
pretty-json 1.6.4 
project-manager 3.3.5 
react 0.16.2 
split-diff 1.5.1 
tomorrow-night-eighties-syntax 1.0.2 
```

**Comment by rsese** [comment]
@pistou can you disable your anti-virus and then reinstall Atom?  I think your anti-virus software might have quarantined `keyboard-layout-manager.node`, I think re-installing should get it back for you.

If you can also report this false positive to your anti-virus vendor so they can update, that would be helpful too.

**Comment by pistou** [comment]
@rsese You were right, AVG put `keytar.node` in quarantine.
I restored the file and reported it as a false-positive.
