### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.21.0-bet...

### ISSUE THREAD

**Issue by kimfrellsen** [atom/atom#15720]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\frellsen01\AppData\Local\atom\app-1.21.0-beta1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: The specified module could not be found.
\\?\C:\Users\frellsen01\AppData\Local\atom\app-1.21.0-beta1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
```

### Non-Core Packages

```
language-cisco 1.4.0 
language-tcl 0.1.2 
language-tcltk 0.1.5 
minimap 4.29.7 
split-diff 1.5.1 
text-pastry 0.6.1 
```

**Comment by rsese** [comment]
Based on recent reports (e.g. https://github.com/atom/atom/issues/14461#issuecomment-331346393), this could be an issue with your anti-virus software.  If you don't have any anti-virus software running, can you try re-installing and see if that helps?

**Comment by kimfrellsen** [comment]
Reinstall helped. The installer Antivirus is Cylance.

/Kim

Den 22. sep. 2017 kl. 19.30 skrev Robert Sese <notifications@github.com>:

Based on recent reports (e.g. #14461 (comment)
<https://github.com/atom/atom/issues/14461#issuecomment-331346393>), this
could be an issue with your anti-virus software. If you don't have any
anti-virus software running, can you try re-installing and see if that
helps?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/atom/atom/issues/15720#issuecomment-331510333>, or mute
the thread
