### ISSUE TITLE
Uncaught Error: invalid backref number/name

### ISSUE THREAD

**Issue by FiW** [atom/atom#15738]
[Enter steps to reproduce:]

1. edit any .marko file
2. write 'h1 --'

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: invalid backref number/name

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:33

Error: invalid backref number/name
    at Scanner.module.exports.Scanner.createScanner (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:33:30)
    at Scanner.module.exports.Scanner.getScanner (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:39:37)
    at Scanner.module.exports.Scanner.findNextMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:58:28)
    at Rule.module.exports.Rule.findNextMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/rule.js:98:34)
    at Rule.module.exports.Rule.getNextTags (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/rule.js:154:27)
    at Grammar.module.exports.Grammar.tokenizeLine (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:164:50)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:380:33)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:368:25)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:224:49)
    at /Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:206:32
    at /Applications/Atom.app/Contents/Resources/app/node_modules/underscore/underscore.js:666:53
```

### Commands

```
     -2:52.2.0 core:paste (input.hidden-input)
     -2:50.8.0 editor:newline (input.hidden-input)
     -2:50.2.0 core:move-left (input.hidden-input)
     -2:49.9.0 core:backspace (input.hidden-input)
     -2:49.6.0 core:move-up (input.hidden-input)
     -2:49.4.0 core:backspace (input.hidden-input)
     -2:48.1.0 core:save (input.hidden-input)
     -2:36.5.0 pane:show-next-recently-used-item (input.hidden-input)
     -2:36.4.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
  2x -2:35.2.0 core:move-up (input.hidden-input)
     -2:34.7.0 core:move-left (input.hidden-input)
     -2:34.2.0 core:backspace (input.hidden-input)
     -2:33.7.0 core:save (input.hidden-input)
     -2:33.4.0 snippets:next-tab-stop (input.hidden-input)
     -2:33.4.0 snippets:expand (input.hidden-input)
     -2:33.4.0 editor:indent (input.hidden-input)
```

### Non-Core Packages

```
atom-yarn 0.6.0 
hyperclick 0.1.5 
language-marko 2.9.4 
nuclide 0.256.0 
platformio-ide-terminal 2.6.0 
```

**Comment by Ben3eeE** [comment]
Thanks for contributing!

It appears that this is being caused by the [language-marko package](https://atom.io/packages/language-marko), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
