### ISSUE TITLE
ubuntu 17.04 come across npm ERR

### ISSUE THREAD

**Issue by ComplicatedPhenomenon** [atom/atom#15745]
```
[x] sudo apt-get install build-essential git libsecret-1-dev fakeroot rpm libx11-dev libxkbfile-dev
[x] sudo add-apt-repository ppa:ubuntu-toolchain-r/test
[x] sudo apt-get update
[x] sudo apt-get install gcc-5 g++-5
[x] sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 80 --slave /usr/bin/g++ g++ /usr/bin/g++-5
```
no problem with step above.
```
[x] sudo update-alternatives --config gcc 
```
outcome is`There is only one alternative in link group gcc (providing /usr/bin/gcc): /usr/bin/gcc-5
Nothing to configure.`
 
It fails at the step `script/build`. the out come is as follow
```
Node:	v8.5.0
Npm:	v5.3.0
Installing script dependencies
prebuild-install info begin Prebuild-install version 2.2.2
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v1.8.0-node-v57-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/wm/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.8.0-leveldown-v1.8.0-node-v57-linux-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v1.8.0/leveldown-v1.8.0-node-v57-linux-x64.tar.gz
prebuild-install http 200 https://github.com/level/leveldown/releases/download/v1.8.0/leveldown-v1.8.0-node-v57-linux-x64.tar.gz
prebuild-install info downloading to @ /home/wm/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.8.0-leveldown-v1.8.0-node-v57-linux-x64.tar.gz.19438-59eee208a4f0d.tmp
prebuild-install info renaming to @ /home/wm/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.8.0-leveldown-v1.8.0-node-v57-linux-x64.tar.gz
prebuild-install info unpacking @ /home/wm/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.8.0-leveldown-v1.8.0-node-v57-linux-x64.tar.gz
prebuild-install info unpack resolved to /home/wm/softwares/atom/script/node_modules/leveldown/build/Release/leveldown.node
prebuild-install info unpack required /home/wm/softwares/atom/script/node_modules/leveldown/build/Release/leveldown.node successfully
prebuild-install info install Successfully installed prebuilt binary!
Installing apm

../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:30:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                                        ^
(node:25431) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:30:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                                        ^
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.11.0
Installing modules ✓
Installing atom-dark-syntax@0.28.0 ✓
Installing atom-dark-ui@0.53.0 ✓
Installing atom-light-syntax@0.29.0 ✓
Installing atom-light-ui@0.46.0 ✓
Installing base16-tomorrow-dark-theme@1.5.0 ✓
Installing base16-tomorrow-light-theme@1.5.0 ✓
Installing one-dark-ui@1.10.8 ✓
Installing one-light-ui@1.10.8 ✓
Installing one-dark-syntax@1.8.0 ✓
Installing one-light-syntax@1.8.0 ✓
Installing solarized-dark-syntax@1.1.2 ✓
Installing solarized-light-syntax@1.1.2 ✓
Installing about@1.7.8 ✓
Installing archive-view@0.63.4 ✓
Installing autocomplete-atom-api@0.10.3 ✓
Installing autocomplete-css@0.17.3 ✓
Installing autocomplete-html@0.8.2 ✓
Installing autocomplete-plus@2.35.11 ✓
Installing autocomplete-snippets@1.11.1 ✓
Installing autoflow@0.29.0 ✓
Installing autosave@0.24.5 ✓
Installing background-tips@0.27.1 ✓
Installing bookmarks@0.44.4 ✓
Installing bracket-matcher@0.88.0 ✓
Installing command-palette@0.41.1 ✓
Installing dalek@0.2.1 ✓
Installing deprecation-cop@0.56.9 ✓
Installing dev-live-reload@0.47.1 ✓
Installing encoding-selector@0.23.6 ✓
Installing exception-reporting@0.41.4 ✓
Installing find-and-replace@0.212.3 ✓
Installing fuzzy-finder@1.6.0 ✓
Installing github@0.6.2 


✗

> keytar@4.0.4 install /home/wm/softwares/atom/node_modules/keytar
> node-gyp rebuild

make: Entering directory '/home/wm/softwares/atom/node_modules/keytar/build'
  CXX(target) Release/obj.target/keytar/src/async.o
  CXX(target) Release/obj.target/keytar/src/main.o
  CXX(target) Release/obj.target/keytar/src/keytar_posix.o
  SOLINK_MODULE(target) Release/obj.target/keytar.node
  COPY Release/keytar.node
make: Leaving directory '/home/wm/softwares/atom/node_modules/keytar/build'

> dugite@1.44.0 postinstall /home/wm/softwares/atom/node_modules/dugite
> node ./script/download-git.js

Downloading Git from: https://github.com/desktop/dugite-native/releases/download/v2.14.1-rc3/dugite-native-v2.14.1-ubuntu-13.tar.gz

Error raised while downloading https://github.com/desktop/dugite-native/releases/download/v2.14.1-rc3/dugite-native-v2.14.1-ubuntu-13.tar.gz { Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
atom@1.22.0-dev /home/wm/softwares/atom
├── @binarymuse/relay-compiler@1.2.0  extraneous
├── atom-babel6-transpiler@1.1.1  extraneous
├── babel-plugin-chai-assert-async@0.1.0  extraneous
├── babel-plugin-relay@1.4.0  extraneous
├── babel-plugin-transform-async-to-generator@6.24.1  extraneous
├── babel-plugin-transform-class-properties@6.24.1  extraneous
├── babel-plugin-transform-decorators-legacy@1.3.4  extraneous
├── babel-plugin-transform-es2015-destructuring@6.23.0  extraneous
├── babel-plugin-transform-es2015-modules-commonjs@6.26.0  extraneous
├── babel-plugin-transform-es2015-parameters@6.24.1  extraneous
├── babel-plugin-transform-object-rest-spread@6.26.0  extraneous
├── babel-preset-react@6.24.1  extraneous
├── classnames@2.2.5  extraneous
├── compare-sets@1.0.1  extraneous
├── core-decorators@0.19.0  extraneous
├── hoist-non-react-statics@1.2.0  extraneous
├── keytar@4.0.4  extraneous
├── lodash.isequal@4.5.0  extraneous
├── lodash.memoize@4.1.2  extraneous
├── multi-list-selection@0.1.1  extraneous
├── ncp@2.0.0  extraneous
├── react@15.6.2  extraneous
├── react-dom@15.6.2  extraneous
├── react-relay@1.4.0  extraneous
├── tinycolor2@1.4.1  extraneous
├── tree-kill@1.2.0  extraneous
├── what-the-diff@0.3.0  extraneous
├── what-the-status@1.0.2  extraneous
└── yubikiri@1.0.0  extraneous


npm WARN relay-runtime@1.4.0 requires a peer of relay-compiler@1.4.0 but none was installed.
npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/home/wm/softwares/atom/apm/node_modules/atom-package-manager/bin/node" "/home/wm/softwares/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/wm/.atom/.apm/.apmrc" "--userconfig" "/home/wm/.atom/.apmrc" "install" "/tmp/d-117826-29801-6i7v5z.cvy9dd9529/package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! dugite@1.44.0 postinstall: `node ./script/download-git.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dugite@1.44.0 postinstall script 'node ./script/download-git.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dugite package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/download-git.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dugite
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dugite
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wm/softwares/atom/npm-debug.log

child_process.js:614
    throw err;
    ^

Error: Command failed: /home/wm/softwares/atom/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:591:13)
    at Object.execFileSync (child_process.js:611:13)
    at module.exports (/home/wm/softwares/atom/script/lib/run-apm-install.js:14:16)
    at Object.<anonymous> (/home/wm/softwares/atom/script/bootstrap:35:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)

)
```

**Comment by 50Wliu** [comment]
Looks like a temporary internet issue (ECONNRESET).  Try again later.

**Comment by ComplicatedPhenomenon** [comment]
I tried lots of times. It still didn't work, the outcome after `script/build` is
```
Node:	v8.5.0
Npm:	v5.3.0
Installing script dependencies
Installing apm
npm ERR! path /home/wm/softwares/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/wm/softwares/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors' -> '/home/wm/softwares/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/.ansicolors.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wm/.npm/_logs/2017-09-27T00_13_24_870Z-debug.log
child_process.js:614
    throw err;
    ^

Error: Command failed: /home/wm/softwares/atom/script/node_modules/.bin/npm --global-style --loglevel=error install
npm ERR! path /home/wm/softwares/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/wm/softwares/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors' -> '/home/wm/softwares/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/.ansicolors.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wm/.npm/_logs/2017-09-27T00_13_24_870Z-debug.log

    at checkExecSyncError (child_process.js:591:13)
    at Object.execFileSync (child_process.js:611:13)
    at module.exports (/home/wm/softwares/atom/script/lib/install-apm.js:9:16)
    at Object.<anonymous> (/home/wm/softwares/atom/script/bootstrap:29:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
```

**Comment by 50Wliu** [comment]
Delete any `package-lock.json` files that have been generated by npm and try again.

**Comment by ComplicatedPhenomenon** [comment]
Thanks, @50Wliu . It helps.  After solving several little problems,  there comes a difficult one for me.
```
Application bundle created at /home/wm/softwares/atom/out/atom-1.22.0-dev-1880e1401-amd64
Generating snapshot script at "/home/wm/softwares/atom/out/startup.js" (2)Unable to transform source code for module /home/wm/softwares/atom/out/app/node_modules/github/node_modules/temp/lib/temp.js.
AssertionError [ERR_ASSERTION]: /home/wm/softwares/atom/out/app/node_modules/github/node_modules/temp/lib/temp.js
Assigning a deferred module to a variable that was not declared in this scope is not supported!
  at FileRequireTransform.replaceAssignmentOrDeclarationWithLazyFunction (/home/wm/softwares/atom/script/node_modules/electron-link/lib/file-require-transform.js:124:9)
  at Context.visitIdentifier (/home/wm/softwares/atom/script/node_modules/electron-link/lib/file-require-transform.js:72:18)
  at Context.invokeVisitorMethod (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:344:49)
  at Visitor.PVp.visitWithoutReset (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:196:32)
  at visitChildren (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at NodePath.each (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path.js:101:26)
  at visitChildren (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:219:18)
  at Visitor.PVp.visitWithoutReset (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at Visitor.PVp.visit (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:133:29)
  at Object.visit (/home/wm/softwares/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:101:55)
  at FileRequireTransform.replaceDeferredRequiresWithLazyFunctions (/home/wm/softwares/atom/script/node_modules/electron-link/lib/file-require-transform.js:68:20)
  at FileRequireTransform.apply (/home/wm/softwares/atom/script/node_modules/electron-link/lib/file-require-transform.js:25:10)
  at /home/wm/softwares/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:53:56
  at Generator.next (<anonymous>:null:null)
  at step (/home/wm/softwares/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:191)
  at /home/wm/softwares/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:361
  at <anonymous>:null:null
```

**Comment by 50Wliu** [comment]
Hmm, it seems like you've managed to run into all the possible problems when building Atom :/.  Ok, try: `script/clean`, followed by another `script/build --install`.  Sorry for all the trouble!

**Comment by ComplicatedPhenomenon** [comment]
It's okay, thank you anyway. Could you tell me what caused all these problems?

**Comment by 50Wliu** [comment]
Yeah, definitely.  Your first ECONNRESET issue was just a temporary problem with your internet connection.  Then the ansicolors issue is (I think) a bug with `npm`'s new package-lock files.  They're still fixing bugs with the implementation, and Atom will fail to build if they're present.  Finally, I'm not too sure about the snapshot script error, but I've ran into that a few times and each time it's been fixed by running script/clean.
