### ISSUE TITLE
Failed to activate the node-resolver package

### ISSUE THREAD

**Issue by shekohex** [atom/atom#15743]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows Server 2008 R2 Datacenter 
**Thrown From**: 'node-resolver' package vundefined

### Stack Trace

Failed to activate the node-resolver package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.exports.activate (/packages/node-resolver/index.js:12:21)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.20.1/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.20.1/resources/app/src/buffered-process.js:338:17)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (~/AppData/Local/atom/app-1.20.1/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -6:09.9.0 diagnostics:fix-all-in-current-file (input.hidden-input)
  2x -5:25.5.0 tree-view:remove (span.name.icon.icon-file-directory)
     -2:59.5.0 core:confirm (input.hidden-input)
     -2:39.2.0 core:backspace (input.hidden-input)
     -2:36.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.4.0 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
atom-typescript 11.0.9 
busy-signal 1.4.3 
ide-typescript 0.1.6 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
mac-os-ui 0.3.0 
node-resolver 1.0.1 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [node-resolver](https://atom.io/packages/node-resolver) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
