### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '../node_modules/highlights/gen/grammars....

### ISSUE THREAD

**Issue by Jaroslav-Lesiv** [atom/atom#15852]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '../node_modules/highlights/gen/grammars.json'

```
At fs.js:558

Error: ENOENT: no such file or directory, open '../node_modules/highlights/gen/grammars.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Proxy.fs.readFileSync (fs.js:468:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Highlights.module.exports.Highlights.loadGrammarsSync (/usr/share/atom/resources/app/node_modules/highlights/lib/highlights.js:238:34)
    at Highlights.module.exports.Highlights.highlightSync (/usr/share/atom/resources/app/node_modules/highlights/lib/highlights.js:40:18)
    at CodeBlock.update (/usr/share/atom/resources/app/node_modules/styleguide/lib/code-block.js:33:62)
    at new CodeBlock (/usr/share/atom/resources/app/node_modules/styleguide/lib/code-block.js:23:16)
    at render (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:17:31)
    at addChildren (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:39:30)
    at render (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:29:27)
    at addChildren (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:39:30)
    at render (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:29:27)
    at updateChildren (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/patch.js:109:40)
    at patch (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/patch.js:15:15)
    at updateSync (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/component-helpers.js:108:26)
    at /usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/component-helpers.js:72:13
    at DefaultScheduler.performUpdates (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/default-scheduler.js:48:40)
```

### Commands

```
```

### Non-Core Packages

```
emmet 2.4.3 
hyperclick 0.1.5 
nuclide 0.259.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm what were you doing at the time of the error and if the error is reproducible?

**Comment by SchnWalter** [comment]
I realized that this error is shown whenever a "Styleguide" tab (`Styleguide: Show` from the command pallet) is opened when starting Atom. If I close that tab and restart the editor, the error goes away, but the error comes back if I open the tab again and I restart Atom.

This happens with Atom `v1.21.1 x64` on a fresh install of openSUSE 42.3 with minimal additions. 

Installed extensions:
 * atom-beautify
 * busy-signal
 * editorconfig
 * emmet
 * intentions
 * linter
 * linter-ui-default
 * polymer-atom
 * polymer-ide
 * sort-lines

**Comment by 50Wliu** [comment]
Unable to reproduce on Atom 1.23.0-dev-83cb0b9a1, Windows 10 x64.  @SchnWalter can you please try the same steps in safe mode (`atom --safe`)?

**Comment by EvilEpicCoder** [comment]
I can reproduce (linux mint 18.2)
Push `Package -> Styleguide -> Show `
Then black window, no components, just header and menu.
Push `Package -> Styleguide -> Show ` one more time, nothing happen, close Atom window
Open Atom, shows an error
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Linux Mint
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '../node_modules/highlights/gen/grammars.json'

```
At fs.js:558

Error: ENOENT: no such file or directory, open '../node_modules/highlights/gen/grammars.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Proxy.fs.readFileSync (fs.js:468:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Highlights.module.exports.Highlights.loadGrammarsSync (/opt/atom/resources/app/node_modules/highlights/lib/highlights.js:238:34)
    at Highlights.module.exports.Highlights.highlightSync (/opt/atom/resources/app/node_modules/highlights/lib/highlights.js:40:18)
    at CodeBlock.update (/opt/atom/resources/app/node_modules/styleguide/lib/code-block.js:33:62)
    at new CodeBlock (/opt/atom/resources/app/node_modules/styleguide/lib/code-block.js:23:16)
    at render (/opt/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:17:31)
    at addChildren (/opt/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:39:30)
    at render (/opt/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:29:27)
    at addChildren (/opt/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:39:30)
    at render (/opt/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:29:27)
    at updateChildren (/opt/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/patch.js:109:40)
    at patch (/opt/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/patch.js:15:15)
    at updateSync (/opt/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/component-helpers.js:108:26)
    at /opt/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/component-helpers.js:72:13
    at DefaultScheduler.performUpdates (/opt/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/default-scheduler.js:48:40)
```

### Commands

```
     -0:11.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-terminal-panel 4.4.4 
busy-signal 1.4.3 
city-lights-ui 1.2.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.14 
file-type-icons 1.3.4 
Hydrogen 2.0.1 
hyperclick 0.1.5 
intentions 1.1.5 
jackhammer-syntax 1.1.0 
js-hyperclick 1.12.2 
language-vue 0.23.1 
language-vue-component 0.5.0 
lint 0.0.1 
linter 2.0.0 
linter-csslint 2.0.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.10 
now-syntax 0.2.4 
open-terminal-here 2.3.1 
rad-syntax 0.4.0 
styri-syntax 0.1.1 
vue-hyperclick 0.2.0 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 0.14.0 
woolgathering-light-syntax 1.9.0 
```

**Comment by EvilEpicCoder** [comment]
# Solved!
You need install highlights module
`npm install highlights`
then this module is missing it gives an error and black blank screen
