### ISSUE TITLE
Chrome dev tools opens, can't open any project

### ISSUE THREAD

**Issue by db1996** [atom/atom#15854]
When i open Atom it has a white screen with chrome dev tools on the right side. I can't seem to open any projects right now.

The error in chrome dev tools says this:

> Error: EPERM: operation not permitted, open 'C:\Users\Old-PC1\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\imports.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Proxy.writeFileSync (C:\Users\Old-PC1\AppData\Local\atom\app-1.21.0\resources\app\node_modules\fs-plus\lib\fs-plus.js:298:29)
    at LessCache.module.exports.LessCache.writeJson (C:\Users\Old-PC1\AppData\Local\atom\app-1.21.0\resources\app\node_modules\less-cache\lib\less-cache.js:212:23)
    at LessCache.module.exports.LessCache.setImportPaths (C:\Users\Old-PC1\AppData\Local\atom\app-1.21.0\resources\app\node_modules\less-cache\lib\less-cache.js:161:18)
    at new LessCache (C:\Users\Old-PC1\AppData\Local\atom\app-1.21.0\resources\app\node_modules\less-cache\lib\less-cache.js:68:18)
    at new LessCompileCache (C:\Users\Old-PC1\AppData\Local\atom\app-1.21.0\resources\app\src\less-compile-cache.js:21:26)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\Old-PC1\AppData\Local\atom\app-1.21.0\resources\app\src\theme-manager.js:283:32)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (C:\Users\Old-PC1\AppData\Local\atom\app-1.21.0\resources\app\src\theme-manager.js:271:27)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (C:\Users\Old-PC1\AppData\Local\atom\app-1.21.0\resources\app\src\theme-manager.js:191:30)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (C:\Users\Old-PC1\AppData\Local\atom\app-1.21.0\resources\app\src\theme-manager.js:252:25)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (C:\Users\Old-PC1\AppData\Local\atom\app-1.21.0\resources\app\src\theme-manager.js:248:25)
    at AtomEnvironment.module.exports.AtomEnvironment.initialize (C:\Users\Old-PC1\AppData\Local\atom\app-1.21.0\resources\app\src\atom-environment.js:339:25)
    at module.exports (C:\Users\Old-PC1\AppData\Local\atom\app-1.21.0\resources\app\src\initialize-application-window.js:106:29)
    at setupWindow (file:///C:/Users/Old-PC1/AppData/Local/atom/app-1.21.0/resources/app.asar/static/index.js:106:12)
    at window.onload (file:///C:/Users/Old-PC1/AppData/Local/atom/app-1.21.0/resources/app.asar/static/index.js:67:9)

**Comment by db1996** [comment]
Sorry i fixed it,  i had accidentally assigned the "hidden"property  on my user. I unhid it and it works now.
