### ISSUE TITLE
Packages with js error causes Atom to be partially non-functional with no error msg.

### ISSUE THREAD

**Issue by ungb** [atom/atom#15863]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Packages with js error during activation causes Atom to be unusable
### Steps to Reproduce

1. Install Atom from master.  
2. Install the react package example:`apm install react@0.16.2`
3. open a empty atom window.  Go to file and try to add a folder.  

**Expected behavior:** [What you expect to happen]
Error should be surfaced to user. 

**Actual behavior:** [What actually happens]
Atom partially works but a lot of things don't.  There's a error in console but error isn't surfaced to user which is an issue.  

Seeing the following error:
```
Uncaught (in promise) TypeError: Cannot read property 'jsxPatch' of undefined
    at AtomReact.patchEditorLangModeAutoDecreaseIndentForBufferRow (/Users/bungdonuts/.atom/packages/react/lib/atom-react.coffee:41:17)
    at AtomReact.patchEditorLangMode (/Users/bungdonuts/.atom/packages/react/lib/atom-react.coffee:107:73)
    at AtomReact.processEditor (/Users/bungdonuts/.atom/packages/react/lib/atom-react.coffee:308:6)
    at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:729:22
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:583:34
    at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:584:19
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didAddPaneItem (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:270:24)
    at Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:632:48)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:574:18)
    at Workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1175:20)
    at Generator.next (<anonymous>)
    at step (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:279)
```

Although this can happen to any 3rd party package that has error occurring.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

```
Atom    : 1.23.0-dev-52873ef3b
Electron: 1.6.14
Chrome  : 56.0.2924.87
Node    : 7.4.0

```

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information
![consoleerror](https://user-images.githubusercontent.com/5624870/31411503-bbab1abc-adc6-11e7-8007-4329f7d0f0e0.gif)

/cc @Ben3eeE

**Comment by chrisjones-brack3t** [comment]
Same issue for me but it only started happening with the v1.22.0 version of Atom. If I back down to v1.21.2, everything starts working again.

**Comment by chrisjones-brack3t** [comment]
Looks like this may be an issues with the React package: https://github.com/orktes/atom-react/issues/248

**Comment by ungb** [comment]
closing this as it's related to the atom-react package which is also now fixed.
