### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/pv/l1yv2ctj0yb1h62nm6pv9vsm0000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by louisgrnr** [atom/atom#15861]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/pv/l1yv2ctj0yb1h62nm6pv9vsm0000gn/T/AppTranslocation/2053F3BD-F18A-4CA9-88BA-AD1060D147B8/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At ELECTRON_ASAR.js:173

Error: dlopen(/private/var/folders/pv/l1yv2ctj0yb1h62nm6pv9vsm0000gn/T/AppTranslocation/2053F3BD-F18A-4CA9-88BA-AD1060D147B8/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/private/var/folders/pv/l1yv2ctj0yb1h62nm6pv9vsm0000gn/T/AppTranslocation/2053F3BD-F18A-4CA9-88BA-AD1060D147B8/d/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (/private/var/folders/pv/l1yv2ctj0yb1h62nm6pv9vsm0000gn/T/AppTranslocation/2053F3BD-F18A-4CA9-88BA-AD1060D147B8/d/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (/private/var/folders/pv/l1yv2ctj0yb1h62nm6pv9vsm0000gn/T/AppTranslocation/2053F3BD-F18A-4CA9-88BA-AD1060D147B8/d/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (/private/var/folders/pv/l1yv2ctj0yb1h62nm6pv9vsm0000gn/T/AppTranslocation/2053F3BD-F18A-4CA9-88BA-AD1060D147B8/d/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (/private/var/folders/pv/l1yv2ctj0yb1h62nm6pv9vsm0000gn/T/AppTranslocation/2053F3BD-F18A-4CA9-88BA-AD1060D147B8/d/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (/private/var/folders/pv/l1yv2ctj0yb1h62nm6pv9vsm0000gn/T/AppTranslocation/2053F3BD-F18A-4CA9-88BA-AD1060D147B8/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/pv/l1yv2ctj0yb1h62nm6pv9vsm0000gn/T/AppTranslocation/2053F3BD-F18A-4CA9-88BA-AD1060D147B8/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/pv/l1yv2ctj0yb1h62nm6pv9vsm0000gn/T/AppTranslocation/2053F3BD-F18A-4CA9-88BA-AD1060D147B8/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/pv/l1yv2ctj0yb1h62nm6pv9vsm0000gn/T/AppTranslocation/2053F3BD-F18A-4CA9-88BA-AD1060D147B8/d/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/private/var/folders/pv/l1yv2ctj0yb1h62nm6pv9vsm0000gn/T/AppTranslocation/2053F3BD-F18A-4CA9-88BA-AD1060D147B8/d/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -3:01.7.0 github:toggle-github-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:49.2.0 pane:split-up-and-copy-active-item (div.github-StubItem-github-tab-controller)
     -2:36 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:10 pane:split-up-and-copy-active-item (div.welcome-container)
  2x -1:54 core:paste (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/15861#issuecomment-335557169. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
