### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Applications/Atom.app/Contents/Resour...

### ISSUE THREAD

**Issue by mike3run** [atom/atom#15878]
[Enter steps to reproduce:]

1. `atom .` on the terminal

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Volumes/Seagate/mike3run/Applications/Atom.app/Contents/Resources'

```
At fs.js:902

Error: ENOENT: no such file or directory, lstat '/Volumes/Seagate/mike3run/Applications/Atom.app/Contents/Resources'
    at fs.lstatSync (fs.js:902:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at realpathSync (fs.js:1542:21)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:331:24)
    at toRealPath (module.js:130:13)
    at Function.Module._findPath (module.js:178:22)
    at Module._resolveFilename (module.js:468:25)
    at Module._resolveFilename (/Volumes/Seagate/mike3run/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Volumes/Seagate/mike3run/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (/Volumes/Seagate/mike3run/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (/Volumes/Seagate/mike3run/Applications/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (/Volumes/Seagate/mike3run/Applications/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (/Volumes/Seagate/mike3run/Applications/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (/Volumes/Seagate/mike3run/Applications/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (/Volumes/Seagate/mike3run/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (/Volumes/Seagate/mike3run/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Volumes/Seagate/mike3run/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Volumes/Seagate/mike3run/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Volumes/Seagate/mike3run/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:24.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-easy-jsdoc 4.12.4 
atom-liquid-snippets 0.3.0 
atom-ternjs 0.18.3 
autoclose 0.0.2 
autocomplete-modules 1.7.2 
autocomplete-paths 2.12.0 
busy-signal 1.4.3 
double-tag 0.9.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.13 
gruvbox 1.0.7 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.75.1 
language-liquid 0.6.0 
language-pug 0.0.21 
language-viml 1.1.6 
linter 2.2.0 
linter-js-standard 4.0.2 
linter-stylelint 4.0.2 
linter-ui-default 1.6.10 
no-title-bar 1.11.3 
persistent-undo 1.3.0 
pigments 0.40.2 
project-manager 3.3.5 
relative-numbers 0.8.0 
standard-formatter 2.8.0 
termination 0.6.1 
vim-mode-plus 1.9.1 
vim-mode-plus-keymaps-for-surround 0.2.1 
warn-before-quitting 0.1.7 
Zen 0.18.0 
```

**Comment by rsese** [comment]
Thanks for the report - can you confirm if this is a fresh install or if you hit this error after updating?

Also, it looks like you've installed Atom on a external drive?   Does `/Volumes/Seagate/mike3run/Applications/Atom.app/Contents/` exist?

**Comment by mike3run** [comment]
@rsese this was after an update, it hasn't happened after that time.

I do have my home folder in a separate HDD although is internal as well so that path is correct.

**Comment by mike3run** [comment]
My computer is a Hackintosh I built with 1 SSD and 2 HDDs all internal.

Just to clarify the whole multiple drives situation 😄

**Comment by rsese** [comment]
> My computer is a Hackintosh I built with 1 SSD and 2 HDDs all internal.
> 
> Just to clarify the whole multiple drives situation 😄

lol thanks for clarifying :v:

> I do have my home folder in a separate HDD although is internal as well so that path is correct.

Hmmm, I'm confused why we're getting a path not found error if `Volumes/Seagate/mike3run/Applications/Atom.app/Contents/Resources` exists.

> @rsese this was after an update, it hasn't happened after that time.

Oh sorry just to clarify this part, do you mean you see the error once after an update but haven't seen it since then?

**Comment by mike3run** [comment]
> Oh sorry just to clarify this part, do you mean you see the error once after an update but haven't seen it since then?

That is correct, after the update Atom restarted but didn't showed up so I did `atom .` on a folder and the error popped right up, I rebooted and that error has not happened ever again
