### ISSUE TITLE
Failed to activate the node-resolver package

### ISSUE THREAD

**Issue by sijpkes** [atom/atom#15880]
[Enter steps to reproduce:]

1. Click install from node-resolver entry under +Install menu.

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.2
**Thrown From**: 'node-resolver' package vundefined

### Stack Trace

Failed to activate the node-resolver package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.exports.activate (/packages/node-resolver/index.js:12:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -0:21.3.0 core:backspace (input.hidden-input)
     -0:20.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
autocomplete-python 1.10.3 
autocomplete-python-jedi 1.10.3-0 
git-plus 7.9.3 
node-debugger 1.10.1 
python-tools 0.6.9 
remote-atom 1.3.11 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [node-resolver](https://atom.io/packages/node-resolver) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
