### ISSUE TITLE
Failed to load the recent-projects package

### ISSUE THREAD

**Issue by alexandraharet** [atom/atom#15908]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: 'recent-projects' package vundefined

### Stack Trace

Failed to load the recent-projects package

```
At Cannot find module 'space-pen'

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.21.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.21.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.21.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/webbox-color/node_modules/atom-space-pen-views/lib/main.js:4:10)
    at /packages/webbox-color/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at /packages/webbox-color/node_modules/atom-space-pen-views/lib/main.js:24:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.21.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.21.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.21.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/recent-projects/lib/recent-projects-view.js:6:12)
    at /packages/recent-projects/lib/recent-projects-view.js:504:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.21.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.21.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.21.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/recent-projects/lib/main.js:8:26)
    at /packages/recent-projects/lib/main.js:144:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.21.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.21.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

### Commands

```
  2x -1:07.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-minify 0.8.0 
autocomplete-modules 1.7.3 
bottom-dock 0.4.4 
busy-signal 1.4.3 
emmet 2.4.3 
intentions 1.1.5 
less-than-slash 0.17.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-jslint 11.1.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-cursorline 0.2.0 
open-recent 5.0.0 
pigments 0.40.2 
project-manager 3.3.5 
sync-settings 0.8.3 
tabs-to-spaces 1.0.3 
todo-manager 0.2.10 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [recent projects](https://github.com/EXSyst/recent-projects) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
