### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#15932]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When the File System Watcher is set to be `Emulated with Atom events` and a new empty tab is opened an error is thrown to the Console.

### Steps to Reproduce

1. Set the File System Watcher to use emulated events
2. Open a new blank tab

**Expected behavior:**

No errors reported to the Console.

**Actual behavior:**

The following error is reported 2-3 times to the Console:
```
Uncaught (in promise) TypeError: Cannot read property 'toString' of undefined
    at Object.realpath (fs.js:1585:8)
    at Object.fs.realpath (ELECTRON_ASAR.js:338:25)
    at C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\src\path-watcher.js:63:26
    at getRealPath (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\src\path-watcher.js:62:22)
    at C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\src\path-watcher.js:72:36
    at Generator.next (<anonymous>)
    at step (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\src\path-watcher.js:5:279)
    at C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\src\path-watcher.js:5:449
    at C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\src\path-watcher.js:5:105
    at C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\src\workspace.js:729:22
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\src\workspace.js:583:34
    at C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\src\workspace.js:584:19
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at PaneContainer.didAddPaneItem (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\src\pane-container.js:270:24)
    at Pane.addItem (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\src\pane.js:632:48)
    at Pane.activateItem (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\src\pane.js:574:18)
    at Workspace.<anonymous> (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\src\workspace.js:1175:20)
    at Generator.next (<anonymous>)
    at step (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta1\resources\app\src\workspace.js:11:279)
```

Note that on initially opening Atom it was only reported 2 times, switching the watcher to `native` events and then back to `emulated` causes it to be reported 3 times on each open.

**Reproduces how often:**

100% of the time.

### Versions

```
Atom    : 1.22.0-beta1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.14.2.windows.3
visual studio
```

OS: Windows 10 x64

### Additional Information

When the File System Watcher is set to use `Native operating system APIs` no errors are thrown to the Console.

**Comment by Arcanemagus** [comment]
Still happening in Atom v1.25.0-beta0 (only commenting because I almost filed it again before finding this).

**Comment by smashwilson** [comment]
Ahhh thanks. Just a bad assumption on my part. Good catch and the fix will be in shortly 🙇
