### ISSUE TITLE
Uncaught Error: EACCES: permission denied, scandir '$ATOM_HOME/packages/file-icons'

### ISSUE THREAD

**Issue by FXschwartz** [atom/atom#15952]
[Enter steps to reproduce:]

1. Anytime i try to update it 
2. Anytime i try to click on file-icons settings button.

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EACCES: permission denied, scandir '/home/preston/.atom/packages/file-icons'

```
At fs.js:871

Error: EACCES: permission denied, scandir '/home/preston/.atom/packages/file-icons'
    at Object.fs.readdirSync (fs.js:871:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:576:28)
    at Proxy.listSync (/opt/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:190:30)
    at PackageDetailView.updateFileButtons (/opt/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:588:51)
    at PackageDetailView.updateInstalledState (/opt/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:484:18)
    at PackageDetailView.populate (/opt/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:454:18)
    at PackageDetailView.completeInitialization (/opt/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:214:18)
    at PackageDetailView.loadPackage (/opt/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:225:20)
    at new PackageDetailView (/opt/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:100:16)
    at callback (/opt/atom/resources/app/node_modules/settings-view/lib/settings-view.js:356:26)
    at SettingsView.getOrCreatePanel (/opt/atom/resources/app/node_modules/settings-view/lib/settings-view.js:361:25)
    at SettingsView.showPanel (/opt/atom/resources/app/node_modules/settings-view/lib/settings-view.js:419:30)
    at HTMLButtonElement.clickHandler (/opt/atom/resources/app/node_modules/settings-view/lib/package-card.js:285:39)
```

### Commands

```
     -3:07.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-material-syntax 1.0.7 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.6 
atom-monokai 0.10.9 
atom-monokai-dark 0.4.0 
atom-music 0.7.0 
atom-quokka 1.0.24 
atom-ternjs 0.18.3 
atom-typescript 11.0.10 
aurora-theme 1.2.2 
brogrammer-syntax 1.0.0 
brogrammer-ui 1.0.0 
busy-signal 1.4.3 
code-peek 1.4.21 
color-picker 2.2.5 
docblockr 0.11.0 
file-icons 2.1.12 
git-plus 7.10.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
imdone-atom 2.2.7 
intentions 1.1.5 
katana-syntax 0.1.0 
language-squarespace 0.4.0 
linter 2.2.0 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
material-syntax 0.6.1 
merge-conflicts 1.4.5 
native-ui 0.24.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
ocean-dark-syntax 0.2.3 
pigments 0.40.2 
ramda-syntax 1.0.4 
RebelChat 0.8.1 
robin-hood-syntax 1.0.0 
skye-light-syntax 0.1.1 
squarespace-syntax-highlighting 0.1.2 
swackets 0.35.0 
tabs-to-spaces 1.0.3 
unity-dark-ui 2.0.9 
unity-ui 2.1.11 
```

**Comment by rsese** [comment]
What do the permissions on `/home/preston/.atom/packages/file-icons` look like?

```
ls -ld /home/preston/.atom/packages/file-icons
```

**Comment by FXschwartz** [comment]
Sorry for the late reply. It's owned by my user.

```d-wx--x--x 7 preston preston 4096 Sep 22 08:52 /home/preston/.atom/packages/file-icons```

**Comment by rsese** [comment]
Oh huh, wonder how it got in that state 🤔 

Glad you have it fixed up but if things somehow gets back in that state, let us know.
