### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 165.225.76.41:80

### ISSUE THREAD

**Issue by neilmatillano** [atom/atom#15971]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 165.225.76.41:80

```
At stream.js:74

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 165.225.76.41:80
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report - it seems like you're having trouble connecting to a proxy?  Are you getting this error specifically when trying to install a package?  If so, have you configured apm to work with your proxy?

https://github.com/atom/apm#using-a-proxy

**Comment by neilmatillano** [comment]
This issue is already. @rsese , yes it was a proxy issue. Thanks!
