### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by yo2seol** [atom/atom#15982]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/partial-keyup-matcher.js:57

TypeError: Cannot read property '0' of undefined
    at PartialKeyupMatcher.getMatches (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/partial-keyup-matcher.js:42:105)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:375:91)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  2x -0:38 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:37.4.0 vim-mode-plus:search (input.hidden-input)
     -0:36.2.0 core:confirm (input.hidden-input)
     -0:35.2.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:25.8.0 vim-mode-plus:delete (input.hidden-input)
     -0:25.2.0 core:save (input.hidden-input)
     -0:17.8.0 vim-mode-plus:delete-right (input.hidden-input)
     -0:16.7.0 vim-mode-plus:move-left (input.hidden-input)
     -0:16.4.0 vim-mode-plus:move-down (input.hidden-input)
     -0:16.1.0 vim-mode-plus:move-to-beginning-of-line (input.hidden-input)
  4x -0:15.8.0 vim-mode-plus:move-right (input.hidden-input)
  2x -0:15 core:move-left (input.hidden-input)
  2x -0:14.4.0 vim-mode-plus:move-right (input.hidden-input)
     -0:13.5.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
  5x -0:13.4.0 core:backspace (input.hidden-input)
  2x -0:11.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.13 
goto-definition 1.3.4 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.76.1 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
last-cursor-position 0.9.2 
MagicPython 1.0.12 
nuclide 0.262.76064527 
nuclide-format-js 0.0.41 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.0 
vim-mode-plus 1.11.6 
```

**Comment by Ben3eeE** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/atom-keymap/pull/221. It is currently scheduled for release when Atom 1.22 reaches Stable.
