### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by peterbe** [atom/atom#15992]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

```
<embedded>:25444 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at Project.module.exports.Project.setPaths (/Applications/Atom.app/Contents/Resources/app/src/project.js:271:44)
    at /Applications/Atom.app/Contents/Resources/app/src/project.js:143:30
```
![screen shot 2017-10-25 at 1 34 06 pm](https://user-images.githubusercontent.com/26739/32013452-30cb0f8c-b989-11e7-80ff-c763783d62ba.png)

Happens with or without `atom --safe .` 

### Steps to Reproduce

1. `git clone git@github.com:mozilla/balrog.git`
2. `cd balrog`
3. `docker-compose up`
3. `atom .`

Note. The `docker-compose up` creates a bunch of files in `.cache` and a bunch of files in `ui/node_modules`

**Expected behavior:** [What you expect to happen]
That it opens without errors and that I can open files.

**Actual behavior:** [What actually happens]
It never opens properly. No side-pane. See screenshot. 

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time. 

### Versions

```
▶ atom --version
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
▶ apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.11
git 2.9.0
```

I'm on macOS Sierra, 10.12.6

### Additional Information

I don't know how to debug (or even share) what extensions I have installed that might affect this. 

Note that the error only happens *after* you've run `docker-compose up` which creates a bunch of files. But it's nevertheless reproducible. The files that are created should all be in `.gitignore`.

**Comment by piersg** [comment]
FWIW I just got this error under the following circumstances:

- Before the weekend, have /tmp/Untitled.txt open in Atom
- shut down for the weekend
- start up on monday, start Atom, and click in the /tmp/Untitled.txt window to edit the now-nonexistent file
- error message results

**Comment by peterbe** [comment]
This is getting frustrating. I still can't open the project I'm working on. Bugs happen but it's getting quite frustrating. 

If I could get some attention on this: https://discuss.atom.io/t/how-to-debug-what-file-in-a-directory-breaks-atom/49072 

Basically, can someone help me get myself unstuck. Right now I can't work on this project with Atom because I can't open any of its files :(

**Comment by leroix** [comment]
I'm unable to reproduce this bug. I did run `docker-compose up`.

```
~/balrog (master)$ apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 3.6.1
git 2.8.1
~/balrog (master)$ atom --version
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0```

OS X El Capitan 10.11.6

**Comment by betawaffle** [comment]
I had this same problem but was able to fix it with `atom --clear-window-state`. It would be nice if you could clear the state for a specific directory.

**Comment by peterbe** [comment]
Super Hooooray! I can open the project now. 
`atom --clear-window-state .` worked.

**Comment by peterbe** [comment]
Perhaps a resolution here is to somehow combine errors in `project.js` with either expanding the error message to tell the user to use `--create-window-state` or just do it for the user automatically.

**Comment by DarkNami** [comment]
I had similar problem (can't open specific project or folder), but I got "Cannot read property 'catch' of undefined" error.
Finally, I fix it with **atom --clear-window-state**
Thanks.

Atom    : 1.22.0

![project](https://user-images.githubusercontent.com/5100919/32657173-ba301d4e-c64f-11e7-8189-67d4016d5f67.png)

**Comment by jmanuel1** [comment]
I had the same issue as @DarkNami on Atom 1.21.2 and 1.22.0 and `atom --clear-window-state` worked.

**Comment by mahirk** [comment]
Reproduced on attempt to autocomplete text. Doesn't happen on every attempt but does happen intermittently:

**Atom**: 1.24.0-beta1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:950

TypeError: Cannot read property 'length' of undefined
    at editor.transact (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:596:108)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:943:24)
    at TextEditor.transact (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1825:30)
    at AutocompleteManager.replaceTextWithMatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:592:30)
    at AutocompleteManager.confirm (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:532:16)
    at subscriptions.add.suggestionList.onDidConfirm (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:227:81)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at SuggestionList.confirm (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list.js:141:31)
    at SuggestionListElement.confirmSelection (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:258:31)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at SuggestionList.confirmSelection (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list.js:145:31)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -2:50.5.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -2:48.9.0 core:save (input.hidden-input)
     -2:36.6.0 editor:newline (input.hidden-input)
     -2:29.8.0 core:move-right (input.hidden-input)
     -2:28.9.0 editor:newline (input.hidden-input)
     -2:24.1.0 core:backspace (input.hidden-input)
     -2:16.3.0 core:move-right (input.hidden-input)
     -2:15.8.0 editor:newline (input.hidden-input)
  4x -2:14.8.0 core:backspace (input.hidden-input)
     -2:12.3.0 autocomplete-plus:confirm (input.hidden-input)
     -2:07.1.0 editor:newline (input.hidden-input)
  2x -2:04.4.0 core:backspace (input.hidden-input)
     -2:01.5.0 core:save (input.hidden-input)
     -1:59.4.0 editor:select-to-end-of-line (input.hidden-input)
     -1:59 core:backspace (input.hidden-input)
     -1:57.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.6.0 
atom-ship 0.0.0 
atom-terminal 0.8.0 
goto-definition 1.3.4 
ide-typescript 0.7.1 
jshint 1.8.6 
jslint 1.5.1 
markdown-pdf 2.1.0 
markdown-toc 0.4.2 
react 0.17.0 
Stylus 3.1.1 
todo-show 2.1.0 
```

**Comment by johanneskoester** [comment]
I have the same issue in combination with atom-ide-rust:

[Enter steps to reproduce:]

1. Modify rust code in a way that leads to an error in the diagnostics panel.
2. The failure occurs.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: "Fedora release
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:535

TypeError: Cannot read property 'length' of undefined
    at SuggestionListElement.getDisplayFragment (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:535:54)
    at SuggestionListElement.renderItem (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:479:18)
    at ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app/src/view-registry.js:238:13)
```

### Commands

```
     -0:47.8.0 editor:newline (input.hidden-input)
     -0:41.7.0 core:backspace (input.hidden-input)
     -0:34.1.0 core:move-right (input.hidden-input)
     -0:33.5.0 intentions:highlight (input.hidden-input)
     -0:33.4.0 core:save (input.hidden-input)
     -0:32.9.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:32.5.0 intentions:highlight (input.hidden-input)
     -0:32.4.0 core:copy (input.hidden-input)
     -0:32.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:31.8.0 editor:newline (input.hidden-input)
     -0:31.5.0 intentions:highlight (input.hidden-input)
     -0:31.3.0 core:paste (input.hidden-input)
     -0:27.7.0 intentions:highlight (input.hidden-input)
     -0:27.6.0 core:save (input.hidden-input)
     -0:26.6.0 intentions:highlight (input.hidden-input)
     -0:26.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.7.1 
busy-signal 1.4.3 
hard-wrap 1.1.0 
ide-python 0.5.0 
ide-rust 0.9.0 
intentions 1.1.5 
language-r 0.4.2 
language-rust 0.4.12 
linter 2.2.0 
linter-rust 0.8.4 
linter-ui-default 1.6.10 
magic-reflow 0.3.0 
tabular 0.1.0 
```
