### ISSUE TITLE
atom opening in chrome developer tools with console log message

### ISSUE THREAD

**Issue by MichaelLSmith** [atom/atom#16014]
Whenever I open atom on a Windows 7, it opens with chrome developer tools with the following errors in the console: 

I have not changed any settings in Atom or on my computer since the last time it worked.

Error: EPERM: operation not permitted, open 'C:\Users\wProject\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\imports.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Proxy.writeFileSync (C:\Users\wProject\AppData\Local\atom\app-1.21.1\resources\app\node_modules\fs-plus\lib\fs-plus.js:298:29)
    at LessCache.module.exports.LessCache.writeJson (C:\Users\wProject\AppData\Local\atom\app-1.21.1\resources\app\node_modules\less-cache\lib\less-cache.js:212:23)
    at LessCache.module.exports.LessCache.setImportPaths (C:\Users\wProject\AppData\Local\atom\app-1.21.1\resources\app\node_modules\less-cache\lib\less-cache.js:161:18)
    at new LessCache (C:\Users\wProject\AppData\Local\atom\app-1.21.1\resources\app\node_modules\less-cache\lib\less-cache.js:68:18)
    at new LessCompileCache (C:\Users\wProject\AppData\Local\atom\app-1.21.1\resources\app\src\less-compile-cache.js:21:26)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\wProject\AppData\Local\atom\app-1.21.1\resources\app\src\theme-manager.js:283:32)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (C:\Users\wProject\AppData\Local\atom\app-1.21.1\resources\app\src\theme-manager.js:271:27)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (C:\Users\wProject\AppData\Local\atom\app-1.21.1\resources\app\src\theme-manager.js:191:30)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (C:\Users\wProject\AppData\Local\atom\app-1.21.1\resources\app\src\theme-manager.js:252:25)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (C:\Users\wProject\AppData\Local\atom\app-1.21.1\resources\app\src\theme-manager.js:248:25)
    at AtomEnvironment.module.exports.AtomEnvironment.initialize (C:\Users\wProject\AppData\Local\atom\app-1.21.1\resources\app\src\atom-environment.js:339:25)
    at module.exports (C:\Users\wProject\AppData\Local\atom\app-1.21.1\resources\app\src\initialize-application-window.js:106:29)
    at setupWindow (file:///C:/Users/wProject/AppData/Local/atom/app-1.21.1/resources/app.asar/static/index.js:106:12)

**Comment by 50Wliu** [comment]
Remove `C:\Users\wProject\.atom\compile-cache\` and try again.
