### ISSUE TITLE
Uncaught Error: missing terminating ] for character class

### ISSUE THREAD

**Issue by wimueller** [atom/atom#16040]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.0-dev-4eea63c50 ia32
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: missing terminating ] for character class

```
At /usr/share/atom/resources/app.asar/node_modules/superstring/index.js:221

Error: missing terminating ] for character class
    at TextBuffer.findAllInRangeSync (/app.asar/node_modules/superstring/index.js:221:44)
    at TextBuffer.module.exports.TextBuffer.findAllInRangeSync (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1142:32)
    at Cursor.getBeginningOfCurrentWordBufferPosition (/usr/share/atom/resources/app/src/cursor.js:523:45)
    at Object.getPrefixText (/usr/share/atom/resources/app/node_modules/snippets/lib/snippets.js:417:36)
    at Object.snippetToExpandUnderCursor (/usr/share/atom/resources/app/node_modules/snippets/lib/snippets.js:474:35)
    at HTMLElement.snippets:expand (/usr/share/atom/resources/app/node_modules/snippets/lib/snippets.js:72:30)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
  2x -4:47.6.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -4:33.1.0 snippets:next-tab-stop (input.hidden-input)
     -4:33.1.0 snippets:expand (input.hidden-input)
     -4:33.1.0 editor:indent (input.hidden-input)
     -4:30.7.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -3:51.2.0 autocomplete-plus:confirm (input.hidden-input)
     -3:41.7.0 core:save (input.hidden-input)
 13x -2:01.6.0 core:move-right (input.hidden-input)
  4x -2:00.0 core:move-left (input.hidden-input)
     -1:58.9.0 core:move-right (input.hidden-input)
 10x -1:58.7.0 core:move-left (input.hidden-input)
     -1:49.1.0 core:backspace (input.hidden-input)
     -1:47.6.0 snippets:next-tab-stop (input.hidden-input)
     -1:47.6.0 snippets:expand (input.hidden-input)
     -0:39.7.0 snippets:next-tab-stop (input.hidden-input)
     -0:39.7.0 snippets:expand (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by 50Wliu** [comment]
@wimueller What were you doing when this occurred?

**Comment by wimueller** [comment]
@50Wliu I was writing a makefile and the error occured when inserting a tab.

**Comment by 50Wliu** [comment]
Ok, thanks.

**Comment by thomasjo** [comment]
I just encountered this issue myself. Haven't got time right now to produce a MWE, but the following will trivially reproduce the issue;

1. Install `language-docker`
2. Create a file called `Dockerfile` with the following contents below.
3. Place the text cursor on the blank line below `RUN ...`, then press <kbd>TAB</kbd> to trigger the error.

``` docker
FROM ubuntu

RUN apt update && apt upgrade -y && \

```

If the blank line is not blank (e.g. contains some text), then indenting works as expected.

**Comment by thomasjo** [comment]
Actually, this seems to happen for a blank `Dockerfile` as well.

**Comment by nathansobo** [comment]
This reproduces for me on master, but not on stable. We should make sure this isn't on beta once we get to the bottom of it.

/cc @maxbrunsfeld @leroix

**Comment by iolsen** [comment]
From @Ben3eeE in Slack:
> I also verified quickly that it's caused by a change in the snippets by linking an older version that does not include this change. Then it didn't reproduce on master.
