### ISSUE TITLE
Console error opening git project

### ISSUE THREAD

**Issue by ungb** [atom/atom#16051]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Console Error opening git project
### Steps to Reproduce

1. Open atom off master (cbc2bdb20)
1. Open a git project.
1. Open Dev tools and go to console to see logs

**Expected behavior:** [What you expect to happen]
No error in console

**Actual behavior:** [What actually happens]
Get the following stack trace in dev tools

```javascript
Uncaught (in promise) Error: Cannot find module '../../build/Release/nsfw.node'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at get__require (/Applications/Atom.app/Contents/Resources/app/node_modules/nsfw/lib/src/index.js:11:39)
    at get_NSFW (/Applications/Atom.app/Contents/Resources/app/node_modules/nsfw/lib/src/index.js:7:31)
    at new nsfw (/Applications/Atom.app/Contents/Resources/app/node_modules/nsfw/lib/src/index.js:36:56)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/nsfw/lib/src/index.js:90:20
    at tryCallOne (/Applications/Atom.app/Contents/Resources/app/node_modules/nodegit-promise/lib/core.js:37:18)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/nodegit-promise/lib/core.js:103:21
    at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/asap/raw.js:50:35)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
**Reproduces how often:** [What percentage of the time does it reproduce?]
100% 

## NOTE:  I believe this is caused by https://github.com/atom/atom/commit/02d348e56ed98f67b0ab7483d2444d6854f878ae.

/cc @Ben3eeE @nathansobo after locally bumping the version back down to 1.0.17 and doing a clean install atom works fine.   

### Versions

Atom    : 1.23.0-dev-cbc2bdb20
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by thomasjo** [comment]
I am unable to reproduce this on Ubuntu 17.04 using `cbc2bdb`. Did a build on macOS two days ago, which is after the `nsfw` commit referenced above, and I am not seeing the error there either.

@ungb Did you try doing a clean build from `HEAD`? The downgrade and clean might be a "red herring".

**Comment by Ben3eeE** [comment]
I am unable to reproduce this on Windows 7 using `cbc2bdb`.

**Comment by ungb** [comment]
I did a clean build and it works now... Unsure what I did wrong before, I'm pretty sure I did I clean build but maybe something weird happened.  I can't repro any more.
