### ISSUE TITLE
electron-packager fails with error (1.22.0 beta2)

### ISSUE THREAD

**Issue by mpkh** [atom/atom#16050]
```
Running electron-packager on /var/tmp/portage/app-editors/atom-1.22.0_beta2/work/atom-1.22.0-beta2/out/app with app name "atom"

... and 1 more
/var/tmp/portage/app-editors/atom-1.22.0_beta2/work/atom-1.22.0-beta2/script/lib/package-application.js:141
        throw new Error(err)
        ^

Error: Error: read ECONNRESET
  at electronPackager (/var/tmp/portage/app-editors/atom-1.22.0_beta2/work/atom-1.22.0-beta2/script/lib/package-application.js:141:15)
  at /var/tmp/portage/app-editors/atom-1.22.0_beta2/work/atom-1.22.0-beta2/script/node_modules/electron-packager/index.js:211:23
  at end (/var/tmp/portage/app-editors/atom-1.22.0_beta2/work/atom-1.22.0-beta2/script/node_modules/run-series/index.js:8:15)
  at done (/var/tmp/portage/app-editors/atom-1.22.0_beta2/work/atom-1.22.0-beta2/script/node_modules/run-series/index.js:11:10)
  at each (/var/tmp/portage/app-editors/atom-1.22.0_beta2/work/atom-1.22.0-beta2/script/node_modules/run-series/index.js:16:43)
  at /var/tmp/portage/app-editors/atom-1.22.0_beta2/work/atom-1.22.0-beta2/script/node_modules/electron-packager/index.js:114:25
  at /var/tmp/portage/app-editors/atom-1.22.0_beta2/work/atom-1.22.0-beta2/script/node_modules/electron-packager/node_modules/electron-download/index.js:61:61
  at Request.done (/var/tmp/portage/app-editors/atom-1.22.0_beta2/work/atom-1.22.0-beta2/script/node_modules/electron-packager/node_modules/nugget/index.js:58:9)
  at emitOne (events.js:115:13)
  at Request.emit (events.js:210:7)
  at Request.onRequestError (/var/tmp/portage/app-editors/atom-1.22.0_beta2/work/atom-1.22.0-beta2/script/node_modules/request/request.js:878:8)
  at emitOne (events.js:115:13)
  at ClientRequest.emit (events.js:210:7)
  at TLSSocket.socketErrorListener (_http_client.js:385:9)
  at emitOne (events.js:115:13)
  at TLSSocket.emit (events.js:210:7)
  at emitErrorNT (internal/streams/destroy.js:64:8)
  at _combinedTickCallback (internal/process/next_tick.js:138:11)
  at process._tickCallback (internal/process/next_tick.js:180:9)


```

**Comment by 50Wliu** [comment]
ECONNRESET indicates a network error.  Try again later.

**Comment by mpkh** [comment]
@50Wliu is it possible to bundle all needed sources together to avoid such errors during the building process?

**Comment by 50Wliu** [comment]
Possible, yes.  Whether it's feasible or not is an entirely different question - Atom currently comes with 92 different core packages, all of which have their own npm dependencies.  That is not to mention Atom's own npm dependencies and its dependency on apm and Electron (which have their own dependencies, and so on).  Therefore there would be an incredible amount of churn if everything was to be bundled together, and is also why `node_modules` is almost universally git-ignored.

**Comment by mpkh** [comment]
ended with success on second run
