### ISSUE TITLE
Uncaught TypeError: this.resultsLayerDecoration.destroy is not a function

### ISSUE THREAD

**Issue by husencd** [atom/atom#16069]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.resultsLayerDecoration.destroy is not a function

```
At /usr/share/atom/resources/app/node_modules/find-and-replace/lib/buffer-search.js:70

TypeError: this.resultsLayerDecoration.destroy is not a function
    at BufferSearch.setEditor (/usr/share/atom/resources/app/node_modules/find-and-replace/lib/buffer-search.js:70:74)
    at /usr/share/atom/resources/app/node_modules/find-and-replace/lib/find.js:61:42
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/usr/share/atom/resources/app/src/pane-container.js:284:26)
    at PaneContainer.didActivatePane (/usr/share/atom/resources/app/src/pane-container.js:262:18)
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app/src/pane.js:925:20)
    at Pane.module.exports.Pane.focus (/usr/share/atom/resources/app/src/pane.js:290:25)
    at /app.asar/src/pane-element.js:51:25)
```

### Commands

```
     -1:23.1.0 editor:toggle-line-comments (input.hidden-input)
     -1:22.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16069#issuecomment-341510543. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
