### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND bluecoat-p...

### ISSUE THREAD

**Issue by aksaha2311** [atom/atom#16125]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND bluecoat-proxy bluecoat-proxy:8080

```
At stream.js:74

Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND bluecoat-proxy bluecoat-proxy:8080
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1025:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:15.8.0 core:paste (input.hidden-input)
     -0:15.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report - this looks like an error related to the proxy you're using.  If the error is intermittent, then there might be an issue with your proxy and retrying might help.  If the error is consistently reproducible and you've [configured Atom to work with your proxy](http://flight-manual.atom.io/getting-started/sections/installing-atom/#proxy-and-firewall-settings), then a good place to get help is our [official message board](https://discuss.atom.io/).  People in the community that have configured Atom to work with their proxies can chime to share what worked for them and provide suggestions.
