### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.1.77.254:3128

### ISSUE THREAD

**Issue by x5440** [atom/atom#16136]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.1.77.254:3128

```
At stream.js:74

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.1.77.254:3128
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  2x -0:44.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-julia-run 1.0.5 
busy-signal 1.4.3 
indent-detective 0.1.1 
ink 0.7.7 
intentions 1.1.5 
julia-client 0.6.4 
language-julia 0.13.0 
latex-completions 0.3.3 
linter 2.2.0 
linter-julia 0.7.2 
linter-ui-default 1.6.10 
tool-bar 1.1.0 
uber-juno 0.1.2 
```

**Comment by rsese** [comment]
Thanks for the report - this is most likely a temporary issue with your internet connection. Please try again later and see if it works.
