### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND webproxy.a...

### ISSUE THREAD

**Issue by fabzzap** [atom/atom#16132]
[Enter steps to reproduce:]

1. Disable one installed package

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND webproxy.ams4.corp.booking.com webproxy.ams4.corp.booking.com:3128

```
At stream.js:74

Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.local proxy.local:3128
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1025:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
file-watcher 1.2.6 
git-plus 7.10.0 
sort-lines 0.18.0 
```

**Comment by rsese** [comment]
Thanks for the report - this looks like an error related to the proxy you're using.  If the error is intermittent or only happened once, then there might be a temporary issue with your network or proxy and retrying might help.  If the error is consistently reproducible and you've [configured Atom to work with your proxy](http://flight-manual.atom.io/getting-started/sections/installing-atom/#proxy-and-firewall-settings), then a good place to get help is our [official message board](https://discuss.atom.io/).  People in the community that have configured Atom to work with their proxies can chime to share what worked for them and provide suggestions.
