### ISSUE TITLE
Uncaught TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by cdaguerre** [atom/atom#16147]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'startsWith' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:187

TypeError: Cannot read property 'startsWith' of undefined
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:187:41
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at atom.confirm.buttons.Move to Trash (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1226:37)
    at ApplicationDelegate.module.exports.ApplicationDelegate.confirm (/Applications/Atom Beta.app/Contents/Resources/app/src/application-delegate.js:229:55)
    at AtomEnvironment.module.exports.AtomEnvironment.confirm (/Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:1031:45)
    at TreeView.module.exports.TreeView.removeSelectedEntries (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1213:25)
    at HTMLElement.tree-view:remove (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view-package.js:32:66)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:1399:34)
    at EventEmitter.outerCallback (/Applications/Atom Beta.app/Contents/Resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:39.6.0 core:move-down (input.hidden-input)
     -0:38.6.0 docblockr:parse-enter (input.hidden-input)
     -0:38.6.0 editor:newline (input.hidden-input)
     -0:32.7.0 core:save (input.hidden-input)
     -0:29.3.0 core:copy (input.hidden-input)
     -0:28.1.0 core:paste (input.hidden-input)
     -0:27.7.0 core:backspace (input.hidden-input)
     -0:26.3.0 autocomplete-plus:confirm (input.hidden-input)
  2x -0:25.3.0 core:move-down (input.hidden-input)
     -0:24.6.0 core:move-left (input.hidden-input)
     -0:24.3.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:24.2.0 datatip:toggle (input.hidden-input)
     -0:24.1.0 core:select-right (input.hidden-input)
     -0:22 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:21.9.0 core:save (input.hidden-input)
     -0:04.6.0 tree-view:remove (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-ide-ui 0.5.4 
blame 0.12.0 
busy-signal 1.4.3 
docblockr 0.13.2 
editorconfig 2.2.2 
file-icons 2.1.13 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-flowtype 0.17.4 
ide-php 0.6.10 
intentions 1.1.5 
language-babel 2.78.0 
language-docker 1.1.8 
language-gherkin 1.0.4 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-nginx 0.8.0 
language-pug 0.0.21 
language-rust 0.4.12 
language-swift 0.5.0 
language-terraform 0.8.1 
language-thrift 1.0.2 
language-vue 0.23.1 
linter-php 1.5.1 
linter-phpcs 1.6.8 
linter-phpmd 2.0.0 
MagicPython 1.0.12 
php-cs-fixer 4.1.1 
php-debug 0.2.5 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.1 
php-integrator-base 3.1.0 
php-integrator-refactoring 1.4.1 
php-integrator-symbol-viewer 0.6.4 
php-twig 4.0.0 
project-manager 3.3.5 
set-syntax 0.4.0 
sort-lines 0.18.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by poacher2k** [comment]
Just got this on Win7 when trying to delete a folder from the tree view. 

Not sure if relevant, but I did have the file inside (`index.js`) opened in Atom the first time I tried to delete it. This beautiful GIF is from the consecutive tries, after closing the file:


![41c2da1198974091801137cb8b98f041](https://user-images.githubusercontent.com/2255960/32688259-de13a540-c6cd-11e7-9e0f-d5b46430a723.gif)

**Comment by 50Wliu** [comment]
Whoops.  `getPath()` can return undefined on Untitled editors.  Working on a fix now.
