### ISSUE TITLE
bug suggested from atom itself

### ISSUE THREAD

**Issue by paolobenve** [atom/atom#16146]
(please specify bug title better, I haven't the know-how to write the bug title)

[Enter steps to reproduce:]

I was working with a js file with unstaged commands, I got the error when I requested staged/unstaged changes

I was offered to automatically open this bug, but I got an error with the url shortner

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'isChanged' of undefined

```
At /usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-selection.js:34

TypeError: Cannot read property 'isChanged' of undefined
    at Object.isItemSelectable (/usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-selection.js:34:45)
    at ListSelection.isItemSelectable (/usr/share/atom/resources/app/node_modules/github/lib/views/list-selection.js:80:31)
    at ListSelection.getSelectedItems (/usr/share/atom/resources/app/node_modules/github/lib/views/list-selection.js:278:24)
    at FilePatchSelection.getSelectedLines (/usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-selection.js:338:40)
    at FilePatchSelection.getSelectedHunks (/usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-selection.js:262:40)
    at FilePatchView.renderHunks (/usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-view.js:151:54)
    at FilePatchView.render (/usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-view.js:221:89)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:796:36)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:819:38)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:743:42)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:721:16)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:642:18)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:558:18)
    at Object.performUpdateIfNecessary (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:154:28)
    at runBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:148:27)
    at ReactReconcileTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:141:26)
    at ReactUpdatesFlushTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:141:26)
    at ReactUpdatesFlushTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:87:38)
    at Object.flushBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:170:25)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:207:31)
    at ReactDefaultBatchingStrategyTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:154:22)
    at Object.batchedUpdates (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:32)
    at Object.enqueueUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:198:28)
    at enqueueUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:22:22)
    at Object.enqueueSetState (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:216:11)
    at FilePatchView.ReactComponent.setState (/usr/share/atom/resources/app/node_modules/react/lib/ReactBaseClasses.js:62:22)
    at FilePatchView.mouseup (/usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-view.js:436:16)
```

### Commands

```
     -8:03.1.0 github:open-file (span.github-FilePatchListView-path)
     -7:49.1.0 github:view-staged-changes-for-current-file (span.syntax--meta.syntax--arguments.syntax--js)
  7x -7:04.6.0 core:backspace (input.hidden-input)
  2x -6:57.8.0 core:move-left (input.hidden-input)
     -6:57.3.0 core:backspace (input.hidden-input)
  3x -6:54.9.0 core:move-left (input.hidden-input)
     -6:54.1.0 core:backspace (input.hidden-input)
     -6:45.5.0 github:view-unstaged-changes-for-current-file (div.line)
  6x -6:19.4.0 core:confirm (div.github-FilePatchView.is-unstaged)
  9x -0:46.6.0 core:backspace (input.hidden-input)
     -0:12.2.0 github:view-unstaged-changes-for-current-file (div.line)
```

### Non-Core Packages

```
autocomplete-python 1.10.3 
busy-signal 1.4.3 
github-plus 1.0.0 
Hydrogen 1.23.0 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 2.0.0 
linter-js-standard 4.0.2 
linter-jshint 3.1.6 
linter-php 1.5.1 
linter-python 3.1.2 
linter-ui-default 1.6.10 
```

**Comment by rsese** [comment]
Thanks for the report @paolobenve 👍 

Hmmm, this looks like https://github.com/atom/github/issues/885 but the fix for that went out already yeah @BinaryMuse @kuychaco?   They're on `1.22.0`.
