### ISSUE TITLE
Tree-view empty when reopen folder

### ISSUE THREAD

**Issue by ccqgithub** [atom/atom#16166]
### Description

Tree-view empty when reopen folder

### Steps to Reproduce

1. Start atom, open a new window, add a project folder
2. Close the window, open a new window, add the same project folder, then the tree view is empty, and the console log: 
```
Uncaught (in promise) Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/Applications/Atom.app/Contents/Resources/app/src/item-registry.js:11:21)
    at PaneContainer.didAddPaneItem (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:269:29)
    at PaneContainer.didAddPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:242:18)
    at Pane.setContainer (/Applications/Atom.app/Contents/Resources/app/src/pane.js:137:23)
    at PaneContainer.setRoot (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:137:21)
    at PaneContainer.deserialize (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:58:16)
    at Dock.deserialize (/Applications/Atom.app/Contents/Resources/app/src/dock.js:378:30)
    at Workspace.deserialize (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:416:40)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1286:35
```
3. close the window, run `atom -clear-window-state` in shell, and reopen the same folder, it is  OK. (or restart atom, it is OK)
4. close the window, open a new window, add the same project folder, the issue appear agin..

### Versions

mac: atom 1.22.0, the previous versions has the same issues

**Comment by ccqgithub** [comment]
It is caused by `tree-view-git-status`, close this..
