### ISSUE TITLE
Uncaught TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by chetanpl** [atom/atom#16169]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At C:\Users\Harshi\AppData\Local\atom\app-1.22.0\resources\app\src\text-editor-component.js:2225

TypeError: Cannot read property 'element' of undefined
    at TextEditorComponent.measureLongestLineWidth (~/AppData/Local/atom/app-1.22.0/resources/app/src/text-editor-component.js:2225:63)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.22.0/resources/app/src/text-editor-component.js:399:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.22.0/resources/app/src/text-editor-component.js:278:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.22.0/resources/app/src/view-registry.js:191:15)
    at ~/AppData/Local/atom/app-1.22.0/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -1:46.8.0 core:cut (input.hidden-input)
     -1:45.1.0 intentions:highlight (input.hidden-input)
     -1:44.9.0 core:save (input.hidden-input)
     -1:37.6.0 intentions:highlight (input.hidden-input)
     -1:37.5.0 core:save (input.hidden-input)
  5x -1:26 core:delete (input.hidden-input)
     -1:21.8.0 intentions:highlight (input.hidden-input)
  7x -1:21.6.0 core:undo (input.hidden-input)
     -1:17.4.0 intentions:highlight (input.hidden-input)
     -1:16.9.0 core:redo (input.hidden-input)
     -1:16 intentions:highlight (input.hidden-input)
     -0:56.4.0 editor:select-to-end-of-line (input.hidden-input)
     -0:55.7.0 intentions:highlight (input.hidden-input)
     -0:55.2.0 core:cut (input.hidden-input)
     -0:54.3.0 core:save (input.hidden-input)
     -0:14.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-typescript 11.0.7 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.8 
npm-install 4.0.4 
symbol-gen 1.3.1 
symbols-tree-view 0.14.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16169#issuecomment-344020542. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
