### ISSUE TITLE
Uncaught Error: The module '/\?\~\AppData\Local\atom\app-1.22.0\resources\app.asar.unpacked\node_...

### ISSUE THREAD

**Issue by skywalker212** [atom/atom#16168]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The module '\\?\C:\Users\Skywalker\AppData\Local\atom\app-1.22.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 49. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

```
At ELECTRON_ASAR.js:173

Error: The module '\\?\C:\Users\Skywalker\AppData\Local\atom\app-1.22.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 49. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.22.0/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.22.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.22.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.22.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.22.0/resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.22.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.22.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.22.0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.22.0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -1:02.2.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-one-dark-ui)
     -1:02.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-one-dark-ui)
     -0:55 application:add-project-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:51.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-one-dark-ui)
  2x -0:39.1.0 tree-view:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.6 
atom-clock 0.1.15 
atom-html-preview 0.2.2 
atom-htmltidy 5.1.0 
atom-material-syntax 1.0.7 
atom-material-ui 2.0.6 
atomic-chrome 0.3.3 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autoprefixer 3.7.1 
busy-signal 1.4.3 
color-picker 2.2.5 
css-snippets 1.1.0 
emmet 2.4.3 
file-icons 2.1.13 
git-plus 7.10.0 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 2.0.0 
linter-php 1.5.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
nuclide 0.264.0 
open-html-in-browser 0.2.0 
php-cs-fixer undefined 
sync-settings 0.8.3 
```

**Comment by rsese** [comment]
Thanks for the report - if you re-install Atom does that clear things up for you?

**Comment by skywalker212** [comment]
yes!
reinstalling atom fixes the problem.
but can you tell me what causes this problem?
