### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('"...

### ISSUE THREAD

**Issue by doemse** [atom/atom#16164]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('"
\tThe') contains HTML space characters, which are not valid in tokens.

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:401

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('"
\tThe') contains HTML space characters, which are not valid in tokens.
    at SuggestionListElement.addClassToElement (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:401:50)
    at SuggestionListElement.renderItem (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:453:30)
    at SuggestionListElement.renderItems (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:275:18)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:187:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
     -0:55.9.0 editor:newline (input.hidden-input)
     -0:44.3.0 core:move-down (input.hidden-input)
     -0:43.9.0 autocomplete-plus:confirm (input.hidden-input)
     -0:42.6.0 core:move-right (input.hidden-input)
  3x -0:42.5.0 editor:newline (input.hidden-input)
  4x -0:22.9.0 core:backspace (input.hidden-input)
     -0:15.2.0 editor:newline (input.hidden-input)
     -0:03.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dracula-theme.theme-atom-dark-ui)
```

### Non-Core Packages

```
autocomplete-python 1.10.3 
dracula-syntax 2.0.5 
dracula-theme 2.0.3 
kite 0.54.0 
markdown-themeable-pdf 1.2.0 
rhino-python 0.8.4 
```

**Comment by rsese** [comment]
Thanks for the report! Can you confirm if the error is reproducible in safe mode (`atom --safe`)?

**Comment by brityank** [comment]
I can confirm that it is not reproducible in safe mode. Likely an issue with autocomplete-python or kite.

**Comment by 50Wliu** [comment]
Thanks for the update @brityank.  You can try using the [package-cop](https://atom.io/packages/package-cop) package to determine which community package is causing the issue.
