### ISSUE TITLE
Uncaught Error: Cannot find module '@shd101wyy/mume'

### ISSUE THREAD

**Issue by mcondarelli** [atom/atom#16175]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module '@shd101wyy/mume'

```
At /usr/share/atom/resources/electron.asar/common/reset-search-paths.js:0

Error: Cannot find module '@shd101wyy/mume'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/mcon/projects/markdown-preview-enhanced/out/src/extension.js:14:14)
    at Object.<anonymous> (/home/mcon/projects/markdown-preview-enhanced/out/src/extension.js:512:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:903:35)
    at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app/src/package.js:301:18)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:793:40)
    at PackageCard.updateSettingsState (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:438:22)
    at PackageCard.updateInterfaceState (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:430:18)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:727:22
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:810:17
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:703:33)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:542:32
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -4:26.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
markdown-preview-enhanced 0.15.0 
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [markdown-preview-enhanced](https://atom.io/packages/markdown-preview-enhanced) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by msnvnkmr** [comment]
Unistall. That will fix the issue.

Sent from my BlackBerry 10 smartphone.
From: Wliu
Sent: Monday 13 November 2017 21:58
To: atom/atom
Reply To: atom/atom
Cc: Subscribed
Subject: Re: [atom/atom] Uncaught Error: Cannot find module '@shd101wyy/mume' (#16175)



Thanks for contributing!

It appears that this is being caused by the markdown-preview-enhanced<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fatom.io%2Fpackages%2Fmarkdown-preview-enhanced&data=02%7C01%7Cnaveen_kumar01123%40hotmail.com%7Cb631afb2b7cc4722fd1208d52ab3879b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636461872915358951&sdata=u82qRhvT0qGWYUQmtoG3ICmWfSwcuWHy6IXmFsznaS0%3D&reserved=0> package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The Atom FAQ<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdiscuss.atom.io%2Fc%2Ffaq&data=02%7C01%7Cnaveen_kumar01123%40hotmail.com%7Cb631afb2b7cc4722fd1208d52ab3879b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636461872915358951&sdata=F%2BqlcF0MRCt9igjG2B%2BgWggrAaQOKdT76N4edoOJbOU%3D&reserved=0> has information on how to contact the maintainers of any Atom community package or theme<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdiscuss.atom.io%2Ft%2Fi-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it%2F25581&data=02%7C01%7Cnaveen_kumar01123%40hotmail.com%7Cb631afb2b7cc4722fd1208d52ab3879b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636461872915358951&sdata=BP7nkW3z3cU7bLvP9FVo6LutPm2Nefw%2Bd15Rc4Dw5CQ%3D&reserved=0>.

**Comment by mcondarelli** [comment]
FYI: I reported the bug [here](https://github.com/shd101wyy/markdown-preview-enhanced/issues/687).
