### ISSUE TITLE
Uncaught Error: Cannot find module './view/open-files-view'

### ISSUE THREAD

**Issue by langchenglc** [atom/atom#16171]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './view/open-files-view'

```
At C:\Users\liang\AppData\Local\atom\app-1.22.0\resources\app\static\<embedded>:1

Error: Cannot find module './view/open-files-view'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.22.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.22.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.22.0/resources/app/src/native-compile-cache.js:66:33)
    at Object.showOpenFiles (/packages/remote-edit2/lib/main.coffee:126:22)
    at /packages/remote-edit2/lib/main.coffee:92:76)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.22.0/resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.22.0/resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.22.0/resources/app/src/atom-environment.js:1382:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.22.0/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -8:11.2.0 remote-edit:new-host-sftp (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -7:58.7.0 tree-view:toggle (input.hidden-input)
     -7:57.1.0 settings-view:open (div.tool-panel.tree-view)
     -7:46.4.0 core:paste (input.hidden-input)
     -7:28.8.0 remote-edit:new-host-sftp (input#remote-edit2.filterHostsUsing.alias.input-checkbox)
     -6:44.9.0 core:backspace (input.hidden-input)
     -6:44.8.0 core:confirm (input.hidden-input)
     -2:48.5.0 remote-edit:new-host-sftp (input#toggleKeybindings.input-checkbox)
 13x -2:40.4.0 core:backspace (input.hidden-input)
     -1:40 core:confirm (input.hidden-input)
     -1:18.6.0 remote-edit:browse (div.package-detail.panels-item)
     -1:12.8.0 remote-edit:new-host-sftp (input.hidden-input)
 12x -0:58.5.0 core:backspace (input.hidden-input)
     -0:27.8.0 remote-edit:browse (input.hidden-input)
     -0:25.4.0 core:confirm (input.hidden-input)
     -0:19 remote-edit:show-open-files (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
remote-edit 1.9.0 
SquirrelTemp undefined 
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [remote-edit2](https://atom.io/packages/remote-edit2) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
