### ISSUE TITLE
When I search for some installation package, make a mistake

### ISSUE THREAD

**Issue by Homin818** [atom/atom#16182]
### Description

When running Atom on MacOS High Sierra  searching for packages in the Setting->Install->Install Packages pane, the following error occurs: 'Searching for 'terminal' failed. Unexpected end of JSON input:'.

``` 
Searching for “ terminal” failed.Hide output…
/Applications/Atom.app/Contents/Resources/app/apm/lib/search.js:62
          packages = body.filter(function(pack) {
                          ^

TypeError: body.filter is not a function
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/search.js:62:27
    at Request._callback (/Applications/Atom.app/Contents/Resources/app/apm/lib/request.js:56:22)
    at Request.self.callback (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)
```

### Steps to Reproduce

1、Run Atom 
2、Open settings and go to install.
3、Search for a package the name is terminal.
4、error

Reproduces how often: 100%

### Versions

Atom : 1.22.0
Electron: 1.6.15
Chrome : 56.0.2924.87
Node : 7.4.0

MacOS: 10.13.1

**Comment by rsese** [comment]
Thanks for reaching out!  The information in the issue template is super helpful for us when looking at issues - can you update the issue body with the issue template filled out?  For example, it would be really helpful to know what operating system you're running, if the error is reproducible in safe mode, etc.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by Homin818** [comment]
I update issue

**Comment by rsese** [comment]
Thanks - can you confirm if you had previous versions of Atom that worked ok?  Or is this a fresh install?

**Comment by akanimax** [comment]
I had the same issue! I solved it by deleting the '.atom' cache in my '~' directory. This caused atom to update itself and run normally.

**Comment by rsese** [comment]
Thanks @akanimax :+1:  @Homin818 does temporarily resetting to factory defaults resolve the error?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

**Comment by akhileshsiddhanti23** [comment]
I am having the same error, but for all packages i.e. I cannot install any package. I also tried [http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults](url) but it doesn't help.
```
Searching for “jupyter” failed.Hide output…
/usr/share/atom/resources/app/apm/lib/search.js:62
          packages = body.filter(function(pack) {
                          ^

TypeError: body.filter is not a function
    at /usr/share/atom/resources/app/apm/lib/search.js:62:27
    at Request._callback (/usr/share/atom/resources/app/apm/lib/request.js:56:22)
    at Request.self.callback (/usr/share/atom/resources/app/apm/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)
```

**Comment by prijeshm** [comment]
Same Issue here: unable to install any new packages. Also tried [](http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults). Still problem persist.
```
Fetching featured packages failed.Hide output…
C:\Users\Prijesh\AppData\Local\atom\app-1.23.3\resources\app\apm\lib\featured.js:59
          packages = body.filter(function(pack) {
                          ^

TypeError: body.filter is not a function
    at C:\Users\Prijesh\AppData\Local\atom\app-1.23.3\resources\app\apm\lib\featured.js:59:27
    at Request._callback (C:\Users\Prijesh\AppData\Local\atom\app-1.23.3\resources\app\apm\lib\request.js:56:22)
    at Request.self.callback (C:\Users\Prijesh\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\Prijesh\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\Prijesh\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)
```

**Comment by rsese** [comment]
@akhileshsiddhanti23 what version of Atom and operating system are you running?  And do you see the same error when installing from the command line with `apm`?

**Comment by rsese** [comment]
Oh sorry, I see you're on 1.23.3 from your output - in addition to my other question above, did this problem just start for you on 1.23.3 and worked fine before?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16182#issuecomment-346992596. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
