### ISSUE TITLE
atom/nuclide nuclide-file-tree Uncaught TypeError: (0 , (_observable || _load_observable(...)).fastDebounce) is not a function

### ISSUE THREAD

**Issue by Mullazman** [atom/atom#16203]
### Description

Nuclide-file-tree can't package can't initialize, can't view file trees.

Have reset windows, run in safemode (moot, disables the affected plugin..), reset atom preferences (removed app data) reinstalled, upgraded to recent beta, same errors.

`
TypeError: (0 , (_observable || _load_observable(...)).fastDebounce) is not a function
    at a.switchMap.editor [as project] (C:\Users\acaso_000\.atom\packages\nuclide\modules\atom-ide-ui\pkg\atom-ide-code-highlight\lib\CodeHighlightManager.js:90:98)
    at a._next (C:\Users\acaso_000\.atom\packages\nuclide\node_modules\rxjs\bundles\Rx.min.js:238:504)
    at a.next (C:\Users\acaso_000\.atom\packages\nuclide\node_modules\rxjs\bundles\Rx.min.js:40:64)
    at a._next (C:\Users\acaso_000\.atom\packages\nuclide\node_modules\rxjs\bundles\Rx.min.js:106:294)
    at a.next (C:\Users\acaso_000\.atom\packages\nuclide\node_modules\rxjs\bundles\Rx.min.js:40:64)
    at a.debouncedNext (C:\Users\acaso_000\.atom\packages\nuclide\node_modules\rxjs\bundles\Rx.min.js:148:434)
    at a.Eb (C:\Users\acaso_000\.atom\packages\nuclide\node_modules\rxjs\bundles\Rx.min.js:30:148)
    at a._execute (C:\Users\acaso_000\.atom\packages\nuclide\node_modules\rxjs\bundles\Rx.min.js:88:309)
    at a.execute (C:\Users\acaso_000\.atom\packages\nuclide\node_modules\rxjs\bundles\Rx.min.js:88:130)
    at a.flush (C:\Users\acaso_000\.atom\packages\nuclide\node_modules\rxjs\bundles\Rx.min.js:89:465)
`

### Steps to Reproduce

1. Install Nuclide
2. Attempt to open a file tree with Ctrl+B
3. Bombs out with error "Uncaught TypeError: (0 , (_observable || _load_observable(...)).fastDebounce) is not a function"

**Expected behavior:** See a file tree..

**Actual behavior:** spawns error

**Reproduces how often:** Consistent, unless loading in safe mode with Nuclide disabled

### Versions

1.22 but also:
Atom    : 1.23.0-beta1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

A few other Nuclide packages also fail to initialize with generic errors like "b is not a function"
Including nuclide-bookshelf, nuclide-type-coverage, nuclide-working-sets and separately atom-ide-diagnostics

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [nuclide](https://atom.io/packages/nuclide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
