### ISSUE TITLE
Uncaught TypeError: Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by LeiHen** [atom/atom#16252]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.0-beta1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Parameter "url" must be a string, not undefined

```
At url.js:95

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:95:11)
    at urlParse (url.js:89:5)
    at GitHubFile.isGistURL (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/node_modules/open-on-github/lib/github-file.js:372:52)
    at new GitHubFile (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/node_modules/open-on-github/lib/github-file.js:73:31)
    at Function.fromPath (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/node_modules/open-on-github/lib/github-file.js:51:20)
    at HTMLElement.open-on-github:repository (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/node_modules/open-on-github/lib/main.js:97:28)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -7:28.8.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -7:28.7.0 docblockr:parse-enter (input.hidden-input)
     -7:28.7.0 editor:newline (input.hidden-input)
  4x -7:27 core:backspace (input.hidden-input)
     -7:25.8.0 intentions:highlight (input.hidden-input)
     -7:25.4.0 editor:toggle-line-comments (input.hidden-input)
 31x -7:21.6.0 intentions:highlight (input.hidden-input)
     -7:18.2.0 core:save (input.hidden-input)
  4x -7:06.7.0 core:backspace (input.hidden-input)
  2x -7:06.2.0 intentions:highlight (input.hidden-input)
     -3:46.2.0 core:save (input.hidden-input)
  4x -1:32.8.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:26 editor:paste-without-reformatting (input.hidden-input)
     -0:34.1.0 git-diff:toggle-diff-list (div.editor-stats-wrapper)
     -0:20.7.0 markdown-preview:toggle-github-style (input.hidden-input)
     -0:07.7.0 open-on-github:repository (input.hidden-input)
```

### Non-Core Packages

```
advanced-new-file 0.5.0 
advanced-open-file 0.16.7 
api-docs 0.0.6 
atom-beautify 0.30.6 
atom-clock 0.1.15 
atom-css-comb 3.3.1 
atom-html-preview 0.2.5 
atom-ide-ui 0.6.0 
atom-languageclient 1.0.7 
atom-minify 0.8.0 
atom-ternjs 0.18.3 
atom-typescript 11.0.10 
atomic-chrome 0.3.3 
autoclose-html 0.23.0 
autocomplete-modules 1.8.0 
autocomplete-paths 2.12.1 
autoprefixer 3.7.1 
busy-signal 1.4.3 
color-picker 2.2.5 
context-menu-manager 0.2.0 
css-snippets 1.1.0 
csscomb 0.3.1 
docblockr 0.13.2 
editor-stats 0.17.0 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.14 
file-types 0.5.5 
git-log 0.4.1 
git-plus 7.10.0 
git-time-machine 1.5.9 
grunt-runner 0.14.0 
hey-pane 1.1.0 
Hydrogen 2.1.0 
hyperclick 0.0.0 
ide-html 0.4.1 
ide-java 0.6.8 
ide-json 0.1.0 
ide-php 0.6.10 
ide-typescript 0.7.0 
intentions 1.1.5 
jade-beautify 0.1.5 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
js-hyperclick 1.12.2 
jsformat 0.9.3 
jshint 1.8.6 
language-babel 2.79.0 
language-cshtml 0.3.0 
language-jade 0.7.2 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-csslint 2.0.0 
linter-jshint 3.1.6 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
markdown-format 2.5.1 
markdown-preview-plus 2.4.16 
markdown-toc 0.4.2 
minimap 4.29.7 
minimap-pigments 0.2.2 
pigments 0.40.2 
pretty-json 1.6.4 
project-manager 3.3.5 
project-viewer 1.2.5 
px2rem-plus 0.3.1 
react-snippets 1.0.1 
regex-railroad-diagram 0.19.4 
release-notes 0.53.0 
script 3.17.3 
seti-ui 1.9.0 
simplified-chinese-menu 5.3.5 
sort-lines 0.18.0 
sync-settings 0.8.3 
tab-switcher 1.5.6 
tool-bar 1.1.0 
tool-bar-main 0.0.10 
tree-view-finder 0.2.1 
tree-view-git-status 1.4.0 
wordpress-api 1.2.2 
```

**Comment by 50Wliu** [comment]
@LeiHen what were you doing when this happened?  What GitHub repository or file were you trying to open?
