### ISSUE TITLE
Uncaught TypeError: this.pack.activateConfig is not a function

### ISSUE THREAD

**Issue by collins73** [atom/atom#16270]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.pack.activateConfig is not a function

```
At C:\Users\Demayne Collins\AppData\Local\atom\app-1.22.1\resources\app\node_modules\settings-view\lib\package-detail-view.js:279

TypeError: this.pack.activateConfig is not a function
    at PackageDetailView.activateConfig (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-detail-view.js:279:25)
    at PackageDetailView.updateInstalledState (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-detail-view.js:485:18)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-detail-view.js:557:31
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-manager.js:703:33)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-manager.js:583:32
    at exit (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.22.1/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.22.1/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -5:06.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-django 0.3.2 
atom-terminal 0.8.0 
atom-terminal-powershell 1.1.0 
autocomplete-python 1.10.5 
django-templates 0.5.0 
file-icons 2.1.14 
kite 0.55.2 
minimap 4.29.7 
platformio-ide-terminal 2.7.0 
predawn-syntax 1.0.4 
predawn-ui 1.0.7 
python-autopep8 0.1.3 
python-debugger 0.2.0 
python-indent 1.1.4 
python-terminal 0.2.0 
script 3.17.3 
```

**Comment by collins73** [comment]
This is related to the platform IO IDE that is not working properly.

**Comment by rsese** [comment]
> This is related to the platform IO IDE that is not working properly.

Thanks for the details - if this is the case,  you should file this issue on https://github.com/platformio/platformio-atom-ide-terminal so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
