### ISSUE TITLE
Uncaught TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by peterecho** [atom/atom#16307]
1. Using Hydrogen with Python within a Markdown file
2. Have Markdown preview open. Getting this error repeatedly. Every time I close the error a new one pops up. Have 6 instances of the error on my screen at one time.
3. The same issue comes up when the Hydrogen output area is toggled and the Markdown preview is closed. 
4. It seems to be related to the Output area sizing. If I start with the Hydrogen output area closed>then run a line, the output will open. If I let it sit I will not see the error. If I try to resize the pane the error shows up almost immediately (that may be a coincidence).

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At C:\Users\pney\AppData\Local\atom\app-1.22.1\resources\app\src\text-editor-component.js:2225

TypeError: Cannot read property 'element' of undefined
    at TextEditorComponent.measureLongestLineWidth (~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor-component.js:2225:63)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor-component.js:399:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor-component.js:278:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.22.1/resources/app/src/view-registry.js:191:15)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/view-registry.js:3:65
```

### Commands

```
  2x -6:04.1.0 core:move-down (input.hidden-input)
     -6:03.2.0 intentions:highlight (input.hidden-input)
     -6:02.8.0 editor:delete-line (input.hidden-input)
     -6:00.6.0 editor:newline (input.hidden-input)
     -6:00.3.0 core:move-up (input.hidden-input)
  5x -5:55.8.0 core:backspace (input.hidden-input)
  7x -5:53.2.0 core:move-down (input.hidden-input)
  6x -5:46.1.0 core:move-up (input.hidden-input)
  5x -5:44.1.0 hydrogen:run-and-move-down (input.hidden-input)
     -4:13.1.0 intentions:highlight (input.hidden-input)
     -4:12.6.0 command-palette:toggle (input.hidden-input)
  3x -4:10.7.0 core:backspace (input.hidden-input)
  4x -4:06.6.0 core:move-down (input.hidden-input)
     -4:05.6.0 core:move-up (input.hidden-input)
     -4:05.3.0 core:confirm (input.hidden-input)
     -4:05.3.0 hydrogen:toggle-output-area (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.5 
busy-signal 1.4.3 
file-icons 2.1.14 
highlight-selected 0.13.1 
Hydrogen 2.1.1 
intentions 1.1.5 
language-vue 0.23.1 
linter 2.2.0 
linter-flake8 2.2.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
python-autopep8 0.1.3 
script 3.17.3 
```

**Comment by Baptiste-Garcin** [comment]
Same here using atom with nodejs

1. Opening atom

(Closing the error message and everything seems to work fine)

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1581

TypeError: Cannot read property 'element' of undefined
    at TextEditorComponent.didScrollDummyScrollbar (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1581:77)
```

### Commands

```
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-ide-ui 0.7.1 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.0 
autosave-onchange 1.5.1 
busy-signal 1.4.3 
clipboard-plus 0.5.1 
file-icons 2.1.15 
git-blame 1.4.0 
git-diff-details 1.4.0 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-typescript 0.7.2 
indent-guide-improved 1.4.13 
intentions 1.1.5 
js-hyperclick 1.12.2 
linter 2.2.0 
linter-eslint 8.4.0 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
todo-show 2.1.0 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
```

**Comment by DanielTamkin** [comment]
Getting the exact same issue, started after pasting some CSS.

[Enter steps to reproduce:]

1. Go to a `.scss` file
2. Paste this css gradient code. 
```
background: -moz-linear-gradient(-45deg, rgba(255,255,255,1) 4%, rgba(125,185,232,0) 49%);
background: -webkit-linear-gradient(-45deg, rgba(255,255,255,1) 4%,rgba(125,185,232,0) 49%);
background: linear-gradient(135deg, rgba(255,255,255,1) 4%,rgba(125,185,232,0) 49%);
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#007db9e8',GradientType=1 );
```
3. Receive cryptic error

**Atom**: 1.23.2 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At C:\Users\Daniel\AppData\Local\atom\app-1.23.2\resources\app\src\text-editor-component.js:3805

TypeError: Cannot read property 'element' of undefined
    at LinesTileComponent.getFirstElementForScreenLine (~/AppData/Local/atom/app-1.23.2/resources/app/src/text-editor-component.js:3805:74)
    at LinesTileComponent.updateLines (~/AppData/Local/atom/app-1.23.2/resources/app/src/text-editor-component.js:3746:82)
    at LinesTileComponent.update (~/AppData/Local/atom/app-1.23.2/resources/app/src/text-editor-component.js:3628:20)
    at updateComponent (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/etch/lib/patch.js:52:19)
    at patch (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/etch/lib/patch.js:16:25)
    at updateChildren (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/etch/lib/patch.js:18:15)
    at Object.updateSync (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/etch/lib/component-helpers.js:116:26)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.23.2/resources/app/src/text-editor-component.js:383:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.23.2/resources/app/src/text-editor-component.js:274:16)
    at etch.getScheduler.updateDocument (~/AppData/Local/atom/app-1.23.2/resources/app/src/text-editor-component.js:224:46)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.23.2/resources/app/src/view-registry.js:238:13)
```

### Commands

```
     -2:24.1.0 core:save (input.hidden-input)
  2x -2:03.0 core:undo (input.hidden-input)
     -2:01.6.0 core:paste (input.hidden-input)
     -2:00.1.0 editor:toggle-line-comments (input.hidden-input)
     -1:59.8.0 core:save (input.hidden-input)
  2x -1:07.0 core:undo (input.hidden-input)
     -1:05.6.0 core:paste (input.hidden-input)
     -1:04.0 editor:toggle-line-comments (input.hidden-input)
     -1:03.7.0 core:save (input.hidden-input)
  2x -0:37.8.0 core:undo (input.hidden-input)
     -0:36.6.0 core:paste (input.hidden-input)
     -0:31.6.0 core:undo (input.hidden-input)
     -0:27.3.0 core:paste (input.hidden-input)
  2x -0:22.7.0 core:undo (input.hidden-input)
     -0:15 docblockr:parse-enter (input.hidden-input)
     -0:15 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
apex-syntax 0.2.0 
api-workbench 0.8.47 
ariake-dark-syntax 0.1.3 
atom-clock 0.1.15 
atom-idiomatic-comments-css-snippets 0.1.0 
atom-liquid-snippets 0.3.0 
atom-windows-titlebar 0.14.0 
base16-ocean-dark-spacegray 0.13.0 
busy-signal 1.4.3 
color-picker 2.2.5 
css-edit-groups 0.4.2 
docblockr 0.13.4 
duotone-dark-forest-syntax 2.1.0 
duotone-dark-space-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
filesize 3.0.0 
firewatch-green-syntax 1.1.0 
firewatch-syntax 1.1.1 
flatwhite-syntax 0.8.1 
flexible-ui 0.10.7 
fold-comments 0.6.0 
git-diff-details 1.4.0 
git-log 0.4.1 
git-status 0.3.4 
intentions 1.1.5 
language-liquid 0.6.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.4.0 
linter-sass-lint 1.8.3 
linter-scss-lint 3.1.1 
linter-ui-default 1.6.10 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
nucleus-dark-ui 0.12.3 
pigments 0.40.2 
pristine-ui 1.1.11 
split-diff 1.5.1 
tree-view-git-status 1.4.0 
unity-ui 2.1.11 
```

**Comment by rsese** [comment]
I wasn't able to reproduce with your steps @DanielTamkin - can you reproduce in safe mode (`atom --safe`)?

**Comment by clojj** [comment]
Same error here, after doing a 'shift-tab' (= un-indenting a line of code)

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0-beta2 x64
**Electron**: 1.7.11
**OS**: "Fedora release
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At /usr/share/atom-beta/resources/app/src/text-editor-component.js:2236

TypeError: Cannot read property 'element' of undefined
    at TextEditorComponent.measureLongestLineWidth (/usr/share/atom-beta/resources/app/src/text-editor-component.js:2236:63)
    at TextEditorComponent.measureContentDuringUpdateSync (/usr/share/atom-beta/resources/app/src/text-editor-component.js:400:16)
    at scheduler.readDocument (/usr/share/atom-beta/resources/app/src/text-editor-component.js:279:20)
    at ViewRegistry.performDocumentUpdate (/usr/share/atom-beta/resources/app/src/view-registry.js:245:13)
```

### Commands

```
     -1:20.1.0 core:delete (input.hidden-input)
     -1:18.8.0 core:backspace (input.hidden-input)
     -1:16.2.0 core:save (input.hidden-input)
  3x -1:13 core:move-right (input.hidden-input)
     -1:10.7.0 core:move-up (input.hidden-input)
     -1:10 core:move-right (input.hidden-input)
     -1:07.3.0 core:move-left (input.hidden-input)
     -1:05.6.0 snippets:next-tab-stop (input.hidden-input)
     -1:05.6.0 snippets:expand (input.hidden-input)
     -1:05.6.0 editor:indent (input.hidden-input)
     -0:58.1.0 core:save (atom-pane.pane)
     -0:54.9.0 core:move-up (input.hidden-input)
     -0:54.3.0 core:move-down (input.hidden-input)
     -0:54 core:move-left (input.hidden-input)
     -0:52.2.0 snippets:previous-tab-stop (input.hidden-input)
     -0:52.2.0 editor:outdent-selected-rows (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.9.2 
atom-typescript 12.2.0 
git-plus 7.10.0 
language-elm 1.5.0 
language-haskell 1.17.3 
quick-highlight 0.12.0 
tree-sitter-syntax-visualizer 0.0.2 
```

**Comment by DanielTamkin** [comment]
Sorry @rsese I didn't get a notification for that comment. I'm not able to reproduce in safe mode either. Might have been a problem with pigments? I've had Atom crash/errors thrown before when pasting in color codes for pigments to parse; However never an error thrown from the Atom core.

**Comment by rsese** [comment]
@clojj I was unable to reproduce with your steps on Fedora 26 with 1.25.0-beta2 - you can reproduce consistently with those steps?

@DanielTamkin no problem - I installed pigments but still wasn't able to repro with your steps on Window 10 and 1.24.0.  Can you still repro on 1.24.0?

**Comment by clojj** [comment]
@rsese yes, I can reproduce it consistently

**Comment by rsese** [comment]
@clojj can you disable all your community packages except for `language-haskell` and see if you can reproduce?  If you can't, can you enable `tree-sitter-syntax-visualizer` and try again?    It looks like it hasn't been recently updated while some changes have been made on our end.

**Comment by wolfy1339** [comment]
Not exactly sure how to reproduce, but it only happens when I am resolving Git merge conflicts

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro (1710)
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At C:\Users\<user>\AppData\Local\atom\app-1.25.0\resources\app\src\text-editor-component.js:2236

TypeError: Cannot read property 'element' of undefined
    at TextEditorComponent.measureLongestLineWidth (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:2236:63)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:400:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:279:20)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.25.0/resources/app/src/view-registry.js:245:13)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-html-preview 0.2.5 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-rst-preview-docutils 1.0.0 
busy-signal 1.4.3 
code-peek 1.4.21 
dockerletion 0.2.0 
editorconfig 2.2.2 
intentions 1.1.5 
language-apache 1.8.0 
language-batchfile 0.7.3 
language-diff 0.7.0 
language-docker 1.1.8 
language-ignore 1.7.4 
language-lua 0.9.11 
language-restructuredtext 1.1.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
preview 0.17.0 
svg-preview 0.12.1 
teletype 0.10.0 
wakatime 7.0.4 
```

**Comment by datitisev** [comment]
Same here.
Occurred after moving line with Cmd+Ctrl up and down through a multi-line function argument
Doesn't always occur, though. And it's very specific. Had the one argument which was an object, with one of the values a string with a number. After repeating, didn't error again. In Javascript.

**Atom**: 1.26.0-beta0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2243

TypeError: Cannot read property 'element' of undefined
    at TextEditorComponent.measureLongestLineWidth (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2243:63)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:408:16)
    at scheduler.readDocument (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:279:41)
    at ViewRegistry.performDocumentUpdate (/Applications/Atom Beta.app/Contents/Resources/app/src/view-registry.js:245:13)
```

### Commands

```
  9x -0:40.4.0 core:move-down (input.hidden-input)
  9x -0:39 editor:move-line-up (input.hidden-input)
 10x -0:37.5.0 editor:move-line-down (input.hidden-input)
     -0:33.9.0 core:move-up (input.hidden-input)
     -0:33.6.0 core:backspace (input.hidden-input)
     -0:32.9.0 core:save (input.hidden-input)
     -0:30.4.0 atom-minify:close-panel (a.btn-issue.btn.btn-error)
     -0:30.4.0 core:cancel (a.btn-issue.btn.btn-error)
     -0:09.1.0 core:move-down (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-city-lights-ui)
     -0:08.6.0 atom-minify:close-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-city-lights-ui)
     -0:08.6.0 core:cancel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-city-lights-ui)
     -0:08.4.0 core:move-up (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-city-lights-ui)
     -0:06.7.0 core:move-down (input.hidden-input)
     -0:06.4.0 core:move-up (input.hidden-input)
  9x -0:06.2.0 editor:move-line-up (input.hidden-input)
  9x -0:03.8.0 editor:move-line-down (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-handlebars 1.3.0 
atom-icons 0.2.2 
atom-ide-ui 0.9.4 
atom-minify 0.8.0 
atom-monokai 0.10.9 
atom-ternjs 0.18.3 
atom-typescript 12.3.8 
atom-uikit 1.2.2 
atom-visual-studio-code-ui 1.3.4 
auto-indent 0.5.0 
auto-indent-file 0.2.0 
autocomplete-modules 1.12.0 
autocomplete-paths 2.12.2 
autocomplete-python 1.10.5 
autoprefixer 3.7.1 
ava 0.11.0 
better-handlebars 0.1.1 
busy 0.7.0 
busy-signal 1.4.3 
carbon-now-sh 2.0.3 
city-lights-ui 1.3.3 
color-picker 2.2.5 
dash 1.7.1 
docblockr 0.13.7 
docker 0.8.0 
dockerletion 0.2.0 
docs-snippets 0.8.0 
emmet 2.4.3 
es6-javascript 1.0.0 
guess-indent 0.1.0 
Handlebars 1.8.0 
hyperclick 0.0.0 
ide-java 0.8.2 
ide-json 0.2.1 
indent-detective 0.2.0 
indent-guide-improved 1.4.13 
intentions 1.1.5 
intentions-colorpicker 1.0.1 
jade 1.2.0 
javascript-snippets 1.2.1 
js-hyperclick 1.13.0 
language-docker 1.1.8 
language-javascript-jsx 0.3.7 
language-lua 0.9.11 
language-nginx 0.8.0 
language-pug 0.0.22 
language-source-cfg 0.3.1 
language-vue 0.23.1 
linter 2.2.0 
linter-docker 0.3.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
material-ui 1.0.10 
nms-color-bracket 0.1.0 
php-twig 4.0.0 
pigments 0.40.2 
prettier-atom 0.53.0 
pristine-ui 1.1.11 
Quick-JavaScript 2.2.0 
quick-scroll 2.1.3 
rainbow-tabs 2.5.1 
react-es6-snippets 0.3.0 
react-snippets 1.1.0 
seti-ui 1.10.0 
solarized-seti-ui 0.8.6 
spacegray-atom-dark-syntax 1.3.2 
split-diff 1.5.2 
sync-settings 0.8.3 
teletype 0.8.0 
travis-ci-status 1.3.1 
tree-view-git-branch 0.1.2 
vue2-autocomplete 0.1.0-alpha.4 
wakatime 7.0.4 
```

**Comment by Ben3eeE** [comment]
1. Open a new untitled buffer and paste the following contents
```js
const Something = require('something').A

Something.load('something').then(result => {
  console.log(result.something)
})
```
2. Change the language mode to JavaScript
3. Place the cursor at the end of the last line
4. Run `editor:toggle-line-comments`

**Atom**: 1.26.0-beta1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At C:\Users\bene\AppData\Local\atom\app-1.26.0-beta1\resources\app\src\text-editor-component.js:2243

TypeError: Cannot read property 'element' of undefined
    at TextEditorComponent.measureLongestLineWidth (~/AppData/Local/atom/app-1.26.0-beta1/resources/app/src/text-editor-component.js:2243:63)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.26.0-beta1/resources/app/src/text-editor-component.js:408:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.26.0-beta1/resources/app/src/text-editor-component.js:279:41)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.26.0-beta1/resources/app/src/view-registry.js:245:13)
```

### Commands

```
     -3:46.8.0 core:move-right (input.hidden-input)
     -3:44.4.0 core:save (input.hidden-input)
     -1:44.8.0 core:backspace (input.hidden-input)
  2x -1:44.3.0 core:delete (input.hidden-input)
  2x -1:43.1.0 core:save (input.hidden-input)
     -0:20.3.0 editor:toggle-line-comments (input.hidden-input)
     -0:01.6.0 application:new-file (input.hidden-input)
     -0:01.3.0 core:paste (input.hidden-input)
     -0:00.6.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
highlight-selected 0.13.1 
language-latex 1.1.1 
latex 0.49.0 
teletype 0.12.0 
```

**Comment by rsese** [comment]
Thanks as always @Ben3eeE :v:  I can reproduce with those steps on macOS and Atom `1.27.0-dev-aa469d5e1`.

**Comment by Ben3eeE** [comment]
This issue only occurs when tree-sitter is enabled with the current steps to reproduce. When toggling line comments the longest line changes and gets a new id which causes the update to want to remeasure the longest line. But the old line with the old id is cached and never updated.
