### ISSUE TITLE
Flakey test - launch reopens any previously opened windows when launched with no path

### ISSUE THREAD

**Issue by leroix** [atom/atom#16301]
```
1) AtomApplication launch reopens any previously opened windows when launched with no path:
      AssertionError: expected [ Array(1) ] to deeply equal [ Array(1) ]
      + expected - actual
       [
      -  "/tmp/d-1171030-31484-kl4lp1.wuv6mndn29"
      +  "/tmp/d-1171030-31484-1ykiq5v.m6j013v7vi"
       ]
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:216:32)
      at Context.<anonymous> (spec/main-process/atom-application.test.js:373:14)
      at Generator.next (<anonymous>)
      at step (spec/main-process/atom-application.test.js:7:273)
```

**Comment by 50Wliu** [comment]
@leroix I believe this was fixed by #16174.  What build did you see it on?

**Comment by leroix** [comment]
I thought it was supposed to have been fixed as well, but I encountered it in Travis.

**Comment by leroix** [comment]
Oh, actually, now that I think about it. I think I encountered it on the `1.23-releases` branch. It looks like @smashwilson's fix wasn't applied there.
