### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'replaceChild' on 'Node': The node to be replaced is no...

### ISSUE THREAD

**Issue by Cazei** [atom/atom#16316]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught NotFoundError: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.

```
At C:\Users\Nyx\AppData\Local\atom\app-1.22.1\resources\app\node_modules\autocomplete-plus\lib\suggestion-list-element.js:464

Error: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at SuggestionListElement.renderItem (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:464:14)
    at SuggestionListElement.renderItems (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:275:18)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.22.1/resources/app/src/view-registry.js:187:15)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -2:04.1.0 core:move-right (input.hidden-input)
     -2:03.8.0 core:backspace (input.hidden-input)
     -2:03.3.0 core:move-left (input.hidden-input)
     -2:01.0 core:save (input.hidden-input)
  2x -1:59.7.0 core:backspace (input.hidden-input)
  2x -1:57 core:move-left (input.hidden-input)
  3x -1:56.7.0 core:move-right (input.hidden-input)
     -1:55.3.0 core:save (input.hidden-input)
     -1:33.3.0 core:move-right (input.hidden-input)
     -0:19.9.0 editor:newline (input.hidden-input)
     -0:19.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  6x -0:18.4.0 core:backspace (input.hidden-input)
     -0:14.9.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  4x -0:09.6.0 core:move-down (input.hidden-input)
     -0:08.9.0 autocomplete-plus:confirm (input.hidden-input)
 17x -0:08.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.5 
git-time-machine 1.5.3 
kite 0.57.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16316#issuecomment-349071717. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
