### ISSUE TITLE
Atom opening into Web Developer Tools

### ISSUE THREAD

**Issue by sevku** [atom/atom#16327]
When I start Atom, the following window appears:

![bildschirmfoto vom 2017-12-05 23-21-09](https://user-images.githubusercontent.com/23403917/33634063-276efc3c-da13-11e7-81e8-fc8508a71c58.png)

Ubuntu 16.04 LTS

**Comment by 50Wliu** [comment]
Please click the red X icon with the `1` next to it and tell us what the error is.

**Comment by sevku** [comment]
```
Error: EACCES: permission denied, open '/home/kunzseverin/.atom/compile-cache/less/df1b7fbc57dbeed23a8f1f8de95b4dfebcc06066/imports.json'
  at Object.fs.openSync (fs.js:558:18)
  at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
  at Object.fs.writeFileSync (fs.js:1233:33)
  at Proxy.writeFileSync (<embedded>:17433:29)
  at LessCache.module.exports.LessCache.writeJson (<embedded>:129818:23)
  at LessCache.module.exports.LessCache.setImportPaths (<embedded>:129767:18)
  at new LessCache (<embedded>:129674:18)
  at new LessCompileCache (<embedded>:72289:26)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (<embedded>:24608:32)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (<embedded>:24596:27)
  at ThemeManager.module.exports.ThemeManager.requireStylesheet (<embedded>:24516:30)
  at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (<embedded>:24577:25)
  at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (<embedded>:24573:25)
  at AtomEnvironment.module.exports.AtomEnvironment.initialize (<embedded>:577:25)
  at module.exports (<embedded>:211:29)
  at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:106:12)
  at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:67:9)
```

**Comment by 50Wliu** [comment]
Thanks!  You should be able to fix this by removing the `~/.atom/compile-cache` folder and trying again.  Did you perhaps run Atom using `sudo atom` before this error occurred?

**Comment by sevku** [comment]
I deleted that folder and it still won't work.
Yes I had to open a file with su rights and therefore I open atom with sudo.

**Comment by 50Wliu** [comment]
@sevku thanks for the extra info.  Are you still receiving an error in the dev tools?

**Comment by sevku** [comment]
Alright I had to delete the whole `.atom` folder. Now it works again. Thanks for your patience.
