### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by mattazend** [atom/atom#16345]
[Enter steps to reproduce:]

Sorry, I don't remember.

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of null

```
At /opt/atom/resources/app/node_modules/atom-keymap/lib/helpers.js:263

TypeError: Cannot read property 'indexOf' of null
    at exports.keystrokeForKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/helpers.js:263:115)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
> [Enter steps to reproduce:]
> 
> Sorry, I don't remember.

No problem, thanks for reporting - we'll go ahead and close for now but if you remember anything about reproducing or if you/anyone else hits the error again, please let us know and we can re-open.
