### ISSUE TITLE
Unable to install on windows 10

### ISSUE THREAD

**Issue by lanigan23** [atom/atom#16359]
2017-05-10 15:46:30> Program: Starting Squirrel Updater: --install .
2017-05-10 15:46:30> Program: Starting install, writing to C:\Users\Killian\AppData\Local\SquirrelTemp
2017-05-10 15:46:31> Program: About to install to: C:\Users\Killian\AppData\Local\atom
2017-05-10 15:46:32> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Killian\AppData\Local\atom\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-05-10 15:46:32> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Killian\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2017-05-10 15:46:32> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Killian\AppData\Local\SquirrelTemp
2017-05-10 15:46:32> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-05-10 15:46:32> ApplyReleasesImpl: Writing files to app directory: C:\Users\Killian\AppData\Local\atom\app-1.16.0
2017-05-10 15:46:32> LogHost: Rigging execution stub for lib/net45/atom_ExecutionStub.exe to C:\Users\Killian\AppData\Local\atom\atom.exe
2017-05-10 15:47:01> LogHost: Rigging execution stub for lib/net45/resources/app/apm/bin/node_ExecutionStub.exe to C:\Users\Killian\AppData\Local\atom\app-1.16.0\resources\app\apm\node.exe
2017-05-10 15:47:52> LogHost: Rigging execution stub for lib/net45/resources/app.asar.unpacked/node_modules/symbols-view/vendor/ctags-win32_ExecutionStub.exe to C:\Users\Killian\AppData\Local\atom\app-1.16.0\resources\app.asar.unpacked\node_modules\symbols-view\ctags-win32.exe
2017-05-10 15:47:56> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Killian\AppData\Local\atom\app-1.16.0\atom.exe]
2017-05-10 15:48:12> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\Killian\AppData\Local\atom\app-1.16.0\atom.exe: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Squirrel.Utility.<>c__DisplayClass11_0.<InvokeProcessAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
2017-05-10 15:48:12> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-05-10 15:48:12> ApplyReleasesImpl: Examining Pin: AmazonShopping.lnk
2017-05-10 15:48:12> ApplyReleasesImpl: Examining Pin: Android Studio.lnk
2017-05-10 15:48:12> ApplyReleasesImpl: Examining Pin: Dropbox 25 GB.lnk
2017-05-10 15:48:12> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-05-10 15:48:12> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-05-10 15:48:12> ApplyReleasesImpl: Examining Pin: Spotify.lnk
2017-05-10 15:48:12> ApplyReleasesImpl: Examining Pin: Steam.lnk
2017-05-10 15:48:12> ApplyReleasesImpl: Examining Pin: TripAdvisor.lnk
2017-05-10 15:48:12> ApplyReleasesImpl: Fixing up tray icons
2017-05-10 15:48:13> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-05-10 15:48:13> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-05-10 15:48:13> ApplyReleasesImpl: cleanDeadVersions: for version 1.16.0
2017-05-10 15:48:13> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.16.0
11280> 2017-05-18 21:14:00> Program: Starting Squirrel Updater: --install .
11280> 2017-05-18 21:14:01> Program: Starting install, writing to C:\Users\Killian\AppData\Local\SquirrelTemp
11280> 2017-05-18 21:14:02> Program: About to install to: C:\Users\Killian\AppData\Local\Discord
11280> 2017-05-18 21:14:02> SingleGlobalInstance: Grabbing lockfile with timeout of 00:00:10
11280> 2017-05-18 21:14:02> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Killian\AppData\Local\SquirrelTemp
11280> 2017-05-18 21:14:03> CheckForUpdateImpl: Remote version 0.0.297 differs from local 
11280> 2017-05-18 21:14:03> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
11280> 2017-05-18 21:14:04> ApplyReleasesImpl: Writing files to app directory: C:\Users\Killian\AppData\Local\Discord\app-0.0.297
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\blink_image_resources_200_percent.pak to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\blink_image_resources_200_percent.pak
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\app.ico to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\app.ico
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\content_resources_200_percent.pak to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\content_resources_200_percent.pak
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\content_shell.pak to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\content_shell.pak
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\d3dcompiler_47.dll to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\d3dcompiler_47.dll
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\Discord.exe to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\Discord.exe
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\ffmpeg.dll to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\ffmpeg.dll
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\icudtl.dat to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\icudtl.dat
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\libEGL.dll to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\libEGL.dll
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\libGLESv2.dll to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\libGLESv2.dll
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\Squirrel.exe to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\Squirrel.exe
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\node.dll to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\node.dll
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\ui_resources_200_percent.pak to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\ui_resources_200_percent.pak
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\natives_blob.bin to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\natives_blob.bin
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\snapshot_blob.bin to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\snapshot_blob.bin
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\views_resources_200_percent.pak to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\views_resources_200_percent.pak
11280> 2017-05-18 21:14:30> ApplyReleasesImpl: Moving file C:\Users\Killian\AppData\Local\Discord\app-0.0.297\lib\net45\xinput1_3.dll to C:\Users\Killian\AppData\Local\Discord\app-0.0.297\xinput1_3.dll
11280> 2017-05-18 21:14:33> ApplyReleasesImpl: Started updateSelf pid 10584
11280> 2017-05-18 21:14:34> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Killian\AppData\Local\Discord\app-0.0.297\Discord.exe]
11280> 2017-05-18 21:14:34> Utility: Process Started: C:\Users\Killian\AppData\Local\Discord\app-0.0.297\Discord.exe --squirrel-install 0.0.297, pid 5360
11280> 2017-05-18 21:15:02> Utility: Received exitcode 0 from process C:\Users\Killian\AppData\Local\Discord\app-0.0.297\Discord.exe
11280> 2017-05-18 21:15:02> ApplyReleasesImpl: ran C:\Users\Killian\AppData\Local\Discord\app-0.0.297\Discord.exe, pid 9400
11280> 2017-05-18 21:15:02> ApplyReleasesImpl: Starting fixPinnedExecutables
11280> 2017-05-18 21:15:02> ApplyReleasesImpl: fixPinnedExecutables: newCurrentFolder: app-0.0.297
11280> 2017-05-18 21:15:03> ApplyReleasesImpl: File 'C:\Users\Killian\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\Narrator.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__ec(FileInfo file)
11280> 2017-05-18 21:15:04> ApplyReleasesImpl: Updating shortcut C:\Users\Killian\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Hammer & Chisel, Inc\Discord.lnk
11280> 2017-05-18 21:15:04> ApplyReleasesImpl: Updating shortcut C:\Users\Killian\Desktop\Discord.lnk
11280> 2017-05-18 21:15:04> ApplyReleasesImpl: Fixing up tray icons
11280> 2017-05-18 21:15:04> ApplyReleasesImpl: cleanDeadVersions: for version 0.0.297
11280> 2017-05-18 21:15:04> ApplyReleasesImpl: cleanDeadVersions: exclude current version folder app-0.0.297
2017-10-02 15:30:39> Program: Starting Squirrel Updater: --install .
2017-10-02 15:30:40> Program: Starting install, writing to C:\Users\Killian\AppData\Local\SquirrelTemp
2017-10-02 15:30:40> Program: About to install to: C:\Users\Killian\AppData\Local\atom
2017-10-02 15:30:40> Program: Install path C:\Users\Killian\AppData\Local\atom already exists, burning it to the ground
2017-10-02 15:30:41> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Killian\AppData\Local\atom\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-10-02 15:30:41> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Killian\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2017-10-02 15:30:41> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Killian\AppData\Local\SquirrelTemp
2017-10-02 15:30:41> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-10-02 15:30:41> ApplyReleasesImpl: Writing files to app directory: C:\Users\Killian\AppData\Local\atom\app-1.16.0
2017-10-02 15:30:41> LogHost: Rigging execution stub for lib/net45/atom_ExecutionStub.exe to C:\Users\Killian\AppData\Local\atom\atom.exe
2017-10-02 15:30:42> LogHost: Rigging execution stub for lib/net45/resources/app/apm/bin/node_ExecutionStub.exe to C:\Users\Killian\AppData\Local\atom\app-1.16.0\resources\app\apm\node.exe
2017-10-02 15:31:55> LogHost: Rigging execution stub for lib/net45/resources/app.asar.unpacked/node_modules/symbols-view/vendor/ctags-win32_ExecutionStub.exe to C:\Users\Killian\AppData\Local\atom\app-1.16.0\resources\app.asar.unpacked\node_modules\symbols-view\ctags-win32.exe
2017-10-02 15:31:58> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Killian\AppData\Local\atom\app-1.16.0\atom.exe]
2017-10-02 15:32:04> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-10-02 15:32:04> ApplyReleasesImpl: Examining Pin: AmazonShopping.lnk
2017-10-02 15:32:04> ApplyReleasesImpl: Examining Pin: Android Studio.lnk
2017-10-02 15:32:04> ApplyReleasesImpl: Examining Pin: Dropbox 25 GB.lnk
2017-10-02 15:32:04> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-10-02 15:32:04> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-10-02 15:32:04> ApplyReleasesImpl: Examining Pin: Spotify.lnk
2017-10-02 15:32:04> ApplyReleasesImpl: Examining Pin: Steam.lnk
2017-10-02 15:32:04> ApplyReleasesImpl: Examining Pin: TripAdvisor.lnk
2017-10-02 15:32:04> ApplyReleasesImpl: Fixing up tray icons
2017-10-02 15:32:04> ApplyReleasesImpl: cleanDeadVersions: for version 1.16.0
2017-10-02 15:32:04> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.16.0
2017-12-12 19:04:23> Program: Starting Squirrel Updater: --install .
2017-12-12 19:04:23> Program: Starting install, writing to C:\Users\Killian\AppData\Local\SquirrelTemp
2017-12-12 19:04:23> Program: About to install to: C:\Users\Killian\AppData\Local\atom
2017-12-12 19:04:24> IEnableLogger: Failed to copy Update.exe to C:\Users\Killian\AppData\Local\atom\Update.exe: System.UnauthorizedAccessException: Access to the path 'C:\Users\Killian\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__5()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
2017-12-12 19:04:24> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Killian\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__5()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\Killian\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__5()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

2017-12-12 19:04:47> Program: Starting Squirrel Updater: --install .
2017-12-12 19:04:47> Program: Starting install, writing to C:\Users\Killian\AppData\Local\SquirrelTemp
2017-12-12 19:04:47> Program: About to install to: C:\Users\Killian\AppData\Local\atom
2017-12-12 19:04:47> Program: Install path C:\Users\Killian\AppData\Local\atom already exists, burning it to the ground
2017-12-12 19:04:48> IEnableLogger: Failed to copy Update.exe to C:\Users\Killian\AppData\Local\atom\Update.exe: System.UnauthorizedAccessException: Access to the path 'C:\Users\Killian\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__5()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
2017-12-12 19:04:48> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Killian\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__5()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\Killian\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__5()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

2017-12-12 19:09:07> Program: Starting Squirrel Updater: --install .
2017-12-12 19:09:08> Program: Starting install, writing to C:\Users\Killian\AppData\Local\SquirrelTemp
2017-12-12 19:09:08> Program: About to install to: C:\Users\Killian\AppData\Local\atom
2017-12-12 19:09:08> Program: Install path C:\Users\Killian\AppData\Local\atom already exists, burning it to the ground
2017-12-12 19:09:08> IEnableLogger: Failed to copy Update.exe to C:\Users\Killian\AppData\Local\atom\Update.exe: System.UnauthorizedAccessException: Access to the path 'C:\Users\Killian\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__5()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
2017-12-12 19:09:09> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Killian\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__5()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\Killian\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__5()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

**Comment by ungb** [comment]
Hi @lanigan23,

what version of Atom were you trying to install?  Also, did you already have atom previously install and performing a upgrade?

**Comment by devvartpoddar** [comment]
+1 On upgrading atom, it suddenly stopped and I cannot install or reinstall it anymore. The .atom folder remained, but all folders from the program files were removed

**Comment by ungb** [comment]
What version of windows/atom were you running?  if you try downloading and installing from https://atom.io/ does that work?

**Comment by devvartpoddar** [comment]
Windows 10 with the fall creators update. I am not sure of the atom version though. Sorry for that! But unfortunately no! I get the same Installation error

**Comment by lanigan23** [comment]
I was trying to install the latest version, I couldn’t uninstall or install for a while. I got it installed there after deleting every possible atom folder but now when I reinstalled my packages they don’t work, is it a bug with the latest update?

**Comment by ungb** [comment]
@lanigan23 I haven't seen any issues when I tried it on my VM, but I had a clean VM.  What are you seeing when you reinstalled packages?  Does anything in dev consoles come up?


@devvartpoddar - When you go to System settings and into applications to uninstall do you see atom as an option?
Also, are you seeing the same errors when trying to upgrade/install atom?

**Comment by devvartpoddar** [comment]
Yes. It was present earlier, but when I tried to uninstall it after I encountered the issue, I got a prompt stating that atom was already uninstalled.

**Comment by ungb** [comment]
@devvartpoddar  Can you try installing an older version of atom and see if you see any issues?  (https://github.com/atom/atom/releases/tag/v1.22.1) Download the `AtomSetup-x64.exe`

@lanigan23 when you open dev tools do you see any errors? `ctrl+shift+i`?

**Comment by rsese** [comment]
I had 1.22.1 installed on a Windows 10 computer and it updated to 1.23 ok.

> 2017-12-12 19:04:24> IEnableLogger: Failed to copy Update.exe to C:\Users\Killian\AppData\Local\atom\Update.exe: System.UnauthorizedAccessException: Access to the path 'C:\Users\Killian\AppData\Local\atom\Update.exe' is denied.

Do you have any anti-virus running @lanigan23 (and anyone else that sees a similar error in their install log)?  If so, can you try disabling anti-virus and try installing again?

**Comment by devvartpoddar** [comment]
@ungb @rsese It was a problem with my antivirus. The installation of the older version worked, but the update got stuck up again. Once I blocked my antivirus though, it worked like a charm. Thanks loads!

**Comment by lanigan23** [comment]
I disabled my anti virus and istalled the older version and that seemed to do the job thanks guys!

**Comment by rsese** [comment]
Going to go ahead and close, looks like temporarily disabling anti-virus sorted things out :+1:
