### ISSUE TITLE
[BUILD][Fedora][script/build] Module version mismatch. Expected 48, got 57

### ISSUE THREAD

**Issue by elegos** [atom/atom#16358]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I'm trying to build Atom on a Fedora box. I thus clone the repository, checkout the v1.22.1 branch and run `./script/build --install=${my prefix here}`. I'd expect to run in no issues, but the `Module version mismatch. Expected 48, got 57` error is thrown.

### Steps to Reproduce
Via docker (suggested):

P.S. commands list is under the `./spec&atom/1.22.1/atom.spec` file of the project.

1. `git clone https://github.com/elegos/fedora-atom.git`
2. `git checkout feature/atom`
3. `./build.sh --external-src --no-erase --target atom --version 1.22.1`

On a Fedora box:

1. clone the repo
2. checkout the v1.22.1 branch
3. `./script/build --install=/whatever/you/like/usr`

**Expected behavior:**

To build atom without any issue

**Actual behavior:** [What actually happens]

```
+ ./script/build --install=/home/makerpm/rpmbuild/BUILDROOT/atom-package-manager-1.22.1-1.fc27.x86_64/usr
Node:	v8.9.1
Npm:	v5.3.0
Installing script dependencies
Installing apm
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 57.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/makerpm/rpmbuild/BUILD/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/home/makerpm/rpmbuild/BUILD/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:570:32)
child_process.js:624
    throw err;
    ^

Error: Command failed: /home/makerpm/rpmbuild/BUILD/atom/apm/node_modules/atom-package-manager/bin/apm --version
    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at Object.<anonymous> (/home/makerpm/rpmbuild/BUILD/atom/script/bootstrap:30:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Atom to build: 1.22.1

### Additional Information

n/a

**Comment by Sneha-Watharkar** [comment]
I am facing the same issue. Any solution?

**Comment by elegos** [comment]
Hello @Sneha-Watharkar no solution so far - I suspect it's the Electron version, but I've got problems compiling the older ones... I've frozen my project for now, waiting to have more time to continue debugging.

**Comment by louisgv** [comment]
Also got the same problem on Ubuntu. My env:
```
 ./script/build --install=/home/jojo/bin/atom
Node:	v9.8.0
Npm:	v5.3.0
Installing script dependencies
Installing apm
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 59.
```
