### ISSUE TITLE
Update flow on mac poor ux

### ISSUE THREAD

**Issue by ismay** [atom/atom#16385]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Updating atom (installed with brew) has been broken on mac for a while now (currently on high sierra, but same for sierra). 

### Steps to Reproduce

1. Click the blue squirrel
2. Click restart and install
3. Atom closes but doesn't quit
4. Wait for a while
5. What's going on? Is it stuck?
5. Force quit
6. Start atom
7. Update failed
8. Repeat

**Expected behavior:**
As a user I expect the update process to work as follows:

1. Click the blue squirrel
2. Click restart and install
3. Atom immediately restarts and shows me a progress bar of the new version downloading and then installing
4. Done

**Actual behavior:**

See step to reproduce.

**Reproduces how often:**

All the time so far.

### Versions

```
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.1
python 2.7.10
git 2.15.1
macos high sierra 10.13.1
```

### Additional Information

I understand that I shouldn't force quit atom while updating, but as a user it's frustrating to not know if it's hanging or actually doing something. Plus, besides that, I've also gotten [this error](https://discuss.atom.io/t/i-am-unable-to-update-to-the-latest-version-of-atom-on-macos-how-do-i-fix-this/40054) and encountered other snags while updating.

It seems like the update flow needs some attention. The current flow feels broken, even though it might be working well, as a user you just don't know because there's no indication of what's happening.

**Comment by 50Wliu** [comment]
Is the account that you use Atom under an administrator?

**Comment by ismay** [comment]
Yes it is.

**Comment by itsmeduncan** [comment]
This is currently happening for me while upgrading from 1.23.2 to 1.23.3. I hit restart and install, and it closed all of the windows but Atom is still running. [Here is a sampling from Activity Monitor.txt](https://github.com/atom/atom/files/1620618/Sample.of.Atom.txt)


<img width="912" alt="screen shot 2018-01-10 at 5 13 39 pm" src="https://user-images.githubusercontent.com/11707/34798331-a27e6b1a-f629-11e7-95cc-711b666da715.png">

**Comment by jsejcksn** [comment]
This has also been my experience for the last 3+ updates and has become expected behavior. 😕

**When updating from 1.23.2 to 1.23.3:**
After finishing a session of work and ready for a context switch, I clicked Restart, and Atom closed all windows (and stayed open). After 2–3 hours and forgetting about updating earlier, I opened a directory in Atom via Terminal (`open -a Atom <directory>`), which opened a new window in Atom having the blue squirrel icon. I clicked it and, noting that the update had not taken place, clicked Restart again, which closed that window and, after a moment, actually quit Atom. When Atom restarted, my original windows reopened, but not the one I had opened from Terminal. This was preferable to losing all of my other windows, but I'm not sure what that says about the state management during updates.

**Comment by romainmenke** [comment]
Same here. Came here looking for a fix and got all the time in the world to type this as the update won't come through. To make matters worse `$ atom .` spawns extra atom processes when an update has been auto-downloaded. That is actually how I know to update Atom. Not the blue squirrel, but the multitude of atom processes suddenly showing up.

Please fix this.

**Comment by agraubert** [comment]
I have been having the same issue, and followed some tips from #2860 which lead me to the ShipIt framework. Looking at the logs, I found that ShipIt was failing to copy a file nested deep in `apm`'s dependency tree:
```
2018-02-15 12:00:07.445 ShipIt[7179:74364] Resuming installation attempt 3
2018-02-15 12:00:10.497 ShipIt[7179:74367] Installation error: Error Domain=SQRLInstallerErrorDomain Code=-1 "Failed to copy bundle file:///Users/aarong/Library/Caches/com.github.atom.ShipIt/update.9yVgqZT/Atom.app/ to directory file:///var/folders/7y/hvrzyxts3xg74r3m2jbq0kc0zt3g3z/T/com.github.atom.ShipIt.9mot6n8f/Atom.app" UserInfo={NSSourceFilePathErrorKey=/Users/aarong/Library/Caches/com.github.atom.ShipIt/update.9yVgqZT/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/es6-symbol/node_modules/es5-ext/test/math/hypot, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/folders/7y/hvrzyxts3xg74r3m2jbq0kc0zt3g3z/T/com.github.atom.ShipIt.9mot6n8f/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/es6-symbol/node_modules/es5-ext/test/math/hypot, NSFilePath=/Users/aarong/Library/Caches/com.github.atom.ShipIt/update.9yVgqZT/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/es6-symbol/node_modules/es5-ext/test/math/hypot, NSUnderlyingError=0x7ff61be1bf40 {Error Domain=NSCocoaErrorDomain Code=4 "The file “hypot” doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/Users/aarong/Library/Caches/com.github.atom.ShipIt/update.9yVgqZT/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/es6-symbol/node_modules/es5-ext/test/math/hypot, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/folders/7y/hvrzyxts3xg74r3m2jbq0kc0zt3g3z/T/com.github.atom.ShipIt.9mot6n8f/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/es6-symbol/node_modules/es5-ext/test/math/hypot, NSFilePath=/Users/aarong/Library/Caches/com.github.atom.ShipIt/update.9yVgqZT/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/es6-symbol/node_modules/es5-ext/test/math/hypot, NSUnderlyingError=0x7ff61be23780 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}, NSLocalizedDescription=Failed to copy bundle file:///Users/aarong/Library/Caches/com.github.atom.ShipIt/update.9yVgqZT/Atom.app/ to directory file:///var/folders/7y/hvrzyxts3xg74r3m2jbq0kc0zt3g3z/T/com.github.atom.ShipIt.9mot6n8f/Atom.app}
2018-02-15 12:00:10.497 ShipIt[7179:74367] ShipIt quitting
2018-02-15 12:04:36.857 ShipIt[7658:77806] Too many attempts to install, aborting update
```

In the end, I manually updated Atom by downloading the new binary and copying it on top of the original install

**Comment by jsejcksn** [comment]
Update: The experience updating to 1.24.0 and 1.24.1 have both been this:

1. Menubar > Atom > Restart and Install
  _Atom closes all windows; app stays open indefinitely_
2. Focus app and Quit using <kbd>cmd</kbd>+<kbd>q</kbd>
3. Launch Atom via Dock shortcut or Launchpad
  _Two Atom apps open (not updated version and updated version)_
4. Repeat step 2 for both apps
5. Repeat step 3
  _Everything seems ok now_

Very frustrating; definitely not a working "auto-updater"
___

I realize there may not be resources to assign to this presently, but can we get an acknowledgement of this issue?

**Comment by revelt** [comment]
Personally, since the last year I haven't been able to update Atom properly. Either the issue described above happens or nothing happens at all (like now, when I tried to check for updates a second ago).

For example, at this moment, Atom beta 1.25.0-beta3 has been released. I click blue squirrel, "check now" button, it says it's up to date:

<img width="895" alt="screen shot 2018-03-09 at 07 40 47" src="https://user-images.githubusercontent.com/8344688/37196061-3539812c-236d-11e8-87ca-dbd2d33b6f62.png">

But it's not up to date!

These days I resort to obsessively check atom.io/releases page n-times a day and manually download/install latest Atom beta.

**Comment by jsejcksn** [comment]
Now getting error messages after update:

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: The module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

```
At ELECTRON_ASAR.js:173

Error: The module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

**Comment by ismay** [comment]
@jsejcksn That seems like a different issue. This issue is purely about the ux of the update experience. If you're encountering errors I'd open a separate issue for that, to prevent muddling this issue with unrelated reports.

**Comment by revelt** [comment]
For example, Sublime Text uses dedicated modals, themed:
<img width="483" alt="sublime" src="https://user-images.githubusercontent.com/8344688/37555749-545459a6-29e4-11e8-98f0-c5de96eb7e59.png">

We need something like that, with "loading" indicator bar.

**Comment by jsejcksn** [comment]
@ismay The errors were only being thrown in the not updated version, during step 3 of my [previous post](https://github.com/atom/atom/issues/16385#issuecomment-371668928):

> 3. Launch Atom via Dock shortcut or Launchpad
_Two Atom apps open (not updated version and updated version)_

No errors before update or after completion of update. Definitely related.

**Comment by ismay** [comment]
Ah ok. Hope this gets some attention. Seems like the atom team is quite busy.

For me un- and reinstalling with brew is a good temporary workaround btw.

**Comment by itsmeduncan** [comment]
When attempting to upgrade to `1.26.0` from `1.25.1` it hung and I ended up with a weird copy of Atom running:

<img width="213" alt="screen shot 2018-04-20 at 5 07 55 pm" src="https://user-images.githubusercontent.com/11707/39074508-b256af72-44bf-11e8-8aea-5891ad6f1559.png">

**Comment by joachim-n** [comment]
> More info on the post by @itsmeduncan: It not only happened to me during the update, but also happens every time I reboot my Mac (macOS reopens all previously open apps/windows after reboot). This is new behavior in Atom 1.26.

That's probably a separate problem though. I saw this too with 1.26, but the most recent version of Atom has fixed it for me.

**Comment by jsejcksn** [comment]
It was resolved for me in 1.26.1, and now it's just back to the base issue. @joachim-n

**Comment by evjan** [comment]
I have the same issue and as far as I can remember it's been like this for many months

**Comment by joshpuetz** [comment]
Greetings from May 2019 and Atom 1.36.x, where this is STILL happening. I hate that damned blue squirrel icon so much.

**Comment by w01fgang** [comment]
Experiencing this issue on 1.47.0-nightly2 and Mac OS 10.15.3
This happens only if Atom was opened for a while. Never happens when just opened.
My workaround is closing all Atom windows once I see that there is an update. Then open a new empty window and then select Restart and install.

**Comment by boptilop** [comment]
For me Atom does seem to quit, but never relaunches. Once I start it from the dock, it starts downloading the update _again_ ☹️.

**Comment by DeeDeeG** [comment]
The buggy "Atom never quits/need to Force Quit" situation described in steps to reproduce should be solved now with #21847.

_(But this issue is about a nicer update UX, beyond being bug-free. So I think this issue stays open for now.)_
