### ISSUE TITLE
can't build 1.24.0-beta0: package-application.js:141 throw new Error(err)

### ISSUE THREAD

**Issue by mpkh** [atom/atom#16381]
```
Running electron-packager on /var/tmp/portage/app-editors/atom-1.24.0_beta0/work/atom-1.24.0-beta0/out/app with app name "atom"

... and 1 more
/var/tmp/portage/app-editors/atom-1.24.0_beta0/work/atom-1.24.0-beta0/script/lib/package-application.js:141
        throw new Error(err)
        ^

Error: Error: read ECONNRESET
  at electronPackager (/var/tmp/portage/app-editors/atom-1.24.0_beta0/work/atom-1.24.0-beta0/script/lib/package-application.js:141:15)
  at /var/tmp/portage/app-editors/atom-1.24.0_beta0/work/atom-1.24.0-beta0/script/node_modules/electron-packager/index.js:211:23
  at end (/var/tmp/portage/app-editors/atom-1.24.0_beta0/work/atom-1.24.0-beta0/script/node_modules/run-series/index.js:8:15)
  at done (/var/tmp/portage/app-editors/atom-1.24.0_beta0/work/atom-1.24.0-beta0/script/node_modules/run-series/index.js:11:10)
  at each (/var/tmp/portage/app-editors/atom-1.24.0_beta0/work/atom-1.24.0-beta0/script/node_modules/run-series/index.js:16:43)
  at /var/tmp/portage/app-editors/atom-1.24.0_beta0/work/atom-1.24.0-beta0/script/node_modules/electron-packager/index.js:114:25
  at /var/tmp/portage/app-editors/atom-1.24.0_beta0/work/atom-1.24.0-beta0/script/node_modules/electron-packager/node_modules/electron-download/index.js:61:61
  at Request.done (/var/tmp/portage/app-editors/atom-1.24.0_beta0/work/atom-1.24.0-beta0/script/node_modules/electron-packager/node_modules/nugget/index.js:58:9)
  at emitOne (events.js:116:13)
  at Request.emit (events.js:211:7)
  at Request.onRequestError (/var/tmp/portage/app-editors/atom-1.24.0_beta0/work/atom-1.24.0-beta0/script/node_modules/request/request.js:878:8)
  at emitOne (events.js:116:13)
  at ClientRequest.emit (events.js:211:7)
  at TLSSocket.socketErrorListener (_http_client.js:387:9)
  at emitOne (events.js:116:13)
  at TLSSocket.emit (events.js:211:7)
  at emitErrorNT (internal/streams/destroy.js:64:8)
  at _combinedTickCallback (internal/process/next_tick.js:138:11)
  at process._tickCallback (internal/process/next_tick.js:180:9)


```

**Comment by mpkh** [comment]
seems like network errors :(
