### ISSUE TITLE
Snippet extension not working: Uncaught Error: PCRE does not support \L, \l, \N{name}, \U, or \u

### ISSUE THREAD

**Issue by occloxium** [atom/atom#16395]
Updated to 1.23.1 yesterday, since that I have experienced problems with snippet extension.
Whenever I hit Tab to extend the selected snippet, this error below pops up.

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Windows 10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: PCRE does not support \L, \l, \N{name}, \U, or \u

```
At C:\Users\Occloxium\AppData\Local\atom\app-1.23.1\resources\app\static\<embedded>:1

Error: PCRE does not support \L, \l, \N{name}, \U, or \u
    at TextBuffer.findAllInRangeSync (/app.asar/node_modules/superstring/index.js:221:44)
    at TextBuffer.module.exports.TextBuffer.findAllInRangeSync (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1147:32)
    at Cursor.getBeginningOfCurrentWordBufferPosition (~/AppData/Local/atom/app-1.23.1/resources/app/src/cursor.js:526:45)
    at Object.getPrefixText (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/snippets/lib/snippets.js:417:36)
    at Object.snippetToExpandUnderCursor (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/snippets/lib/snippets.js:474:35)
    at HTMLElement.snippets:expand (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/snippets/lib/snippets.js:72:30)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:273:23)
    at SnippetsProvider.onDidInsertSuggestion (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/autocomplete-snippets/lib/snippets-provider.js:56:32)
    at AutocompleteManager.confirm (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:528:35)
    at subscriptions.add.suggestionList.onDidConfirm (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:227:81)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at SuggestionList.confirm (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/autocomplete-plus/lib/suggestion-list.js:141:31)
    at SuggestionListElement.confirmSelection (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:249:31)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at SuggestionList.confirmSelection (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/autocomplete-plus/lib/suggestion-list.js:145:31)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -4:04.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:03.3.0 editor:consolidate-selections (input.hidden-input)
     -4:03.3.0 core:cancel (input.hidden-input)
     -4:01.9.0 core:move-down (input.hidden-input)
     -4:01.7.0 core:move-up (input.hidden-input)
     -4:01.4.0 editor:newline (input.hidden-input)
  3x -4:00.6.0 core:backspace (input.hidden-input)
     -3:59.1.0 autocomplete-plus:confirm (input.hidden-input)
     -3:59.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:04.4.0 core:backspace (input.hidden-input)
     -2:03.9.0 autocomplete-plus:confirm (input.hidden-input)
     -2:03.9.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
 13x -2:02.5.0 core:backspace (input.hidden-input)
     -0:05.0 core:move-up (input.hidden-input)
     -0:04.1.0 autocomplete-plus:confirm (input.hidden-input)
     -0:04.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Non-Core Packages

```
antialiased 0.1.0 
atom-autocomplete-php 0.25.6 
atom-html-preview 0.2.5 
atom-ide-ui 0.7.0 
atom-latex 0.8.2 
atom-material-syntax 1.0.7 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.6 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
busy-signal 1.4.3 
color-picker 2.2.5 
highlight-selected 0.13.1 
ide-java 0.7.0 
ide-php 0.7.4 
ide-typescript 0.7.2 
intentions 1.1.5 
language-latex 1.1.1 
language-markdown 0.25.1 
language-pfm 0.82.0 
latex 0.49.0 
latex-autocomplete 1.1.1 
linter 2.2.0 
linter-php 1.5.1 
linter-sass-lint 1.8.3 
linter-spell 0.15.0 
linter-spell-latex 0.10.0 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
markdown-pdf 2.1.0 
markdown-preview-plus 2.4.16 
markdown-writer 2.7.3 
pdf-view 0.61.0 
preview-inline 1.5.1 
sass-autocompile 0.13.3 
sass-compiler 0.0.0 
typewriter 0.7.0 
```

**Comment by rsese** [comment]
Thanks for the report - does this happen with any snippet or just a particular snippet?  Which snippet generated the error for you in this case?

Lastly, can you confirm if you updated from 1.23.0 to 1.23.1 when you started seeing this error or from an earlier version?

**Comment by occloxium** [comment]
Thanks for the reply. As it seems, this issue seems to have been solved by either updating to 1.23.1 or any package updates. I'm gonna close the issue right away.

As for the last question, I am not certain, but I suppose the issue occured right after updating. 
Nevertheless, as snippets seem to work again, I consider this closed.

**Comment by occloxium** [comment]
Previous comment needs to be corrected, problem still exists when trying to extend ANY snippet in ANY grammar with using the TAB key. On the other hand, when using the command palette and selecting the snippet via "Snippets: Available", it works fine (even though this is not practical for fast usage)

Updating to 1.23.1 revealed the issue.
Error happens with any snippet and in any grammar when trying to extend with TAB.

**Comment by occloxium** [comment]
Testing this issue with several versions of Atom, the issue seems to appear even with Atom 1.23.0, hence I've downgraded even further to 1.22.1, which seems to be the last version working properly

**Comment by Ingramz** [comment]
Try running Atom in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) to see, if the issue is caused in combination with a Community Package that you might have installed. If the issue disappears, then it would be helpful if it can be pinpointed to a specific package you have installed.

If the issue persists, it is likely caused by a snippet in `File->Snippets`, which you should try commenting out temporarily. In that case it would be useful to know what do the snippets' prefixes contain.

**Comment by lee-dohm** [comment]
I just tried to reproduce this using Atom v1.23.1 and could not. Here is what I tried:

1. Launch Atom in Safe Mode using `atom --safe .`
1. Open a new file using <kbd>Cmd+N</kbd>
1. Set the language of the file to HTML by clicking the language-selector and selecting HTML from the list
1. Type `html` in the new file and press <kbd>Tab</kbd>

**Expected and Actual:** The `html` snippet expands properly without an error message

Given that there hasn't been any effort to attempt to reproduce this issue in Safe Mode, we have to assume that this is being caused by one of the packages you have installed. If you can reproduce the problem in Safe Mode, please let us know and we'll investigate further.
