### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isVisible' of null

### ISSUE THREAD

**Issue by skratchdot** [atom/atom#16419]
[Enter steps to reproduce:]

1. cmd+shift+p
2. click `Status Bar: Toggle` to get the status bar to show up
3. error occurs

**Atom**: 1.24.0-beta1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'isVisible' of null

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/status-bar/lib/main.js:51

TypeError: Cannot read property 'isVisible' of null
    at HTMLElement.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/status-bar/lib/main.js:51:41)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:165:35)
    at SelectListView.confirmSelection (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at SelectListView.didClickItem (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:287:16)
    at ListItemView.onclick (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:222:37)
    at ListItemView.didClick (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:449:16)
```

### Commands

```
  8x -0:40.9.0 fuzzy-finder:toggle-file-finder (div.panels-item)
  2x -0:30.1.0 core:move-up (div.panels-item)
     -0:20.8.0 command-palette:toggle (div.panels-item)
     -0:17.5.0 status-bar:toggle (div.panels-item)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-ternjs 0.18.3 
atom-typescript 11.0.10 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.13.4 
editorconfig 2.2.2 
file-icons 2.1.15 
git-time-machine 1.5.9 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.12.2 
language-babel 2.81.1 
language-pegjs 0.5.0 
language-rust 0.4.12 
linter 2.2.0 
linter-eslint 8.4.0 
linter-flow 5.6.1 
linter-rust 0.8.4 
linter-tslint 1.9.0 
linter-ui-default 1.6.10 
local-history 4.3.1 
minimap 4.29.7 
platformio-ide-terminal 2.7.0 
prettier-atom 0.43.1 
project-viewer 1.2.5 
sort-lines 0.18.0 
```

**Comment by skratchdot** [comment]
Restarting Atom fixed this for me, so feel free to close this out.  I'm not sure I have good reproducible steps.

**Comment by rsese** [comment]
> Restarting Atom fixed this for me, so feel free to close this out. I'm not sure I have good reproducible steps.

Glad restarting fixed things for you :+1:   x-ref an issue with a similar stack trace: https://github.com/atom/status-bar/issues/199.

**Comment by ineiti** [comment]
Getting the same error here:

[Enter steps to reproduce:]

1. CMD+SHIFT+A
2. status
3. Chose "Status Bar: toggle"

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'isVisible' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/main.js:51

TypeError: Cannot read property 'isVisible' of null
    at HTMLElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/main.js:51:41)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:143:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:58.6.0 tree-view:toggle-focus (input.hidden-input)
     -0:36.5.0 find-and-replace:show (input.hidden-input)
     -0:33.7.0 core:select-all (input.hidden-input)
     -0:33.1.0 core:backspace (input.hidden-input)
     -0:32.4.0 atom-ctags:toggle-file-symbols (input.hidden-input)
     -0:29.9.0 editor:consolidate-selections (input.hidden-input)
     -0:29.9.0 core:cancel (input.hidden-input)
     -0:29.6.0 editor:consolidate-selections (input.hidden-input)
     -0:29.6.0 core:cancel (input.hidden-input)
     -0:27.4.0 command-palette:toggle (input.hidden-input)
  3x -0:20.2.0 core:move-down (input.hidden-input)
     -0:18 core:confirm (input.hidden-input)
     -0:18 atom-ctags:rebuild (input.hidden-input)
     -0:15.1.0 command-palette:toggle (input.hidden-input)
     -0:13.2.0 core:confirm (input.hidden-input)
     -0:13.2.0 status-bar:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-ctags 5.1.2 
atom-latex 0.8.2 
autocomplete-awk 0.1.2 
block-travel 1.0.5 
busy-signal 1.4.3 
ctags-status 1.3.7 
go-debug 1.5.3 
go-find-references 1.2.3 
go-plus 5.7.2 
go-rename 0.3.0 
go-signature-statusbar 1.2.3 
go-tip 2.4.0 
godef 0.2.5 
hey-pane 1.1.0 
hyperclick 0.1.5 
intellij-idea-keymap 0.2.3 
intentions 1.1.5 
language-awk 0.1.12 
language-latex 1.1.1 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-golinter 1.2.2 
linter-shellcheck 1.4.6 
linter-ui-default 1.6.10 
nerd-treeview 0.5.4 
project-viewer 1.2.5 
react 0.17.0 
status-bar-blame 2.0.1 
symbol-gen 1.3.1 
tablr 1.8.3 
```

**Comment by rsese** [comment]
@ineiti can you reproduce with those steps?  Also can you clarify your step 2 what `status` means?  Are you toggling the status like in step 3?
