### ISSUE TITLE
Uncaught TypeError: Cannot read property '10' of null

### ISSUE THREAD

**Issue by tuomashatakka** [atom/atom#16429]
The error is thrown every time I do the following:

1. Open the command palette
2. Type multiple letters in a rapid succession

The error seems to occur when a new letter is inserted while the command palette hasn't finished the search for the previous query yet.

**Atom**: 1.24.0-beta1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property '10' of null

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:330

TypeError: Cannot read property '10' of null
    at SelectListView.renderItemAtIndex (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:330:43)
    at IntersectionObserver.visibilityObserver.changes (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:59:22)
```

### Commands

```
     -9:30.5.0 core:undo (input.hidden-input)
     -9:16.2.0 core:move-left (input.hidden-input)
     -9:15 core:undo (input.hidden-input)
     -3:53.2.0 core:move-right (input.hidden-input)
     -3:52.9.0 core:move-left (input.hidden-input)
     -1:22.2.0 pane:show-next-recently-used-item (input.hidden-input)
     -1:22 pane:move-active-item-to-top-of-stack (div.panels-item)
     -1:10.7.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:39 command-palette:toggle (input.hidden-input)
     -0:29.4.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:29.2.0 pane:move-active-item-to-top-of-stack (div.package-detail.panels-item)
     -0:21.9.0 window:toggle-dev-tools (div.package-detail.panels-item)
```

### Non-Core Packages

```
apex-ui 1.0.1 
atom-beautify 0.30.6 
atom-clock 0.1.15 
atom-ide-ui 0.7.0 
atom-jump-block 0.5.4 
atom-ternjs 0.18.3 
atom-typing-speedometer 0.3.1 
autocomplete-javascript 0.0.2 
autocomplete-js-import 1.4.0 
autocomplete-json 5.5.2 
autocomplete-modules 1.8.0 
autocomplete-python 1.10.5 
autumn-highlighter-syntax 1.13.0 
block-travel 1.0.5 
city-lights-syntax 1.1.2 
color-picker 2.2.5 
context-menu-plus 0.0.0 
dash-ui 0.4.3 
declarations 1.1.3 
declarations-js 1.0.2 
docblockr 0.13.4 
dockerletion 0.2.0 
editorconfig 2.2.2 
eq-ui 0.0.0 
file-templates 0.0.0 
file-type-icons 1.3.4 
flow-ide 1.9.0 
fold-comments 0.6.0 
font-preview 0.1.1 
front-icons 1.15.0 
git-blame 1.4.0 
git-change-marker 0.16.0 
git-diff-details 1.4.0 
git-history 3.3.0 
git-line 0.6.0 
git-plus 7.10.0 
git-time-machine 1.5.9 
goto 1.8.3 
history-tracker 0.1.0 
hyperclick 0.0.0 
hyperlink-hyperclick 1.3.4 
ide-css 0.2.0 
ide-python 0.3.0 
intentions 1.1.5 
intentions-colorpicker 1.0.1 
jackhammer-syntax 1.1.0 
javascript-snippets 1.2.1 
js-hyperclick 1.12.2 
jsdoc-preview 1.2.1 
jumpy 4.2.0 
kite 0.58.0 
language-babel 2.80.3 
language-docker 1.1.8 
language-documentation 2.0.1 
language-gradle 0.0.3 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-annotations 1.0.2 
linter-eslint 8.4.0 
linter-flow 5.6.1 
linter-python 3.1.2 
linter-ui-docks 0.0.0 
linter-ui-hinted 0.0.5 
linter-ui-plus 0.3.2 
merge-conflicts 1.4.5 
midi-controlled 0.0.0 
nuclide 0.270.0 
nuclide-format-js 0.0.41 
path-hyperclick 0.3.0 
pinned-tabs 1.3.0 
point-black-syntax 0.0.0 
power-bar 0.1.0 
process-palette 0.15.2 
python-indent 1.1.4 
python-tools 0.6.9 
quicknote 0.1.1 
react-snippets 1.0.0 
redux-devtools 0.5.1 
slides-preview 0.3.1 
styri-syntax 0.1.1 
symbol-gen 1.3.1 
todo-show 2.1.0 
token-navigation 1.5.3 
tool-bar 1.1.0 
tool-bar-gui 0.1.2 
word-art-comments 0.4.0 
zentabs 0.8.9 
```

**Comment by rsese** [comment]
Thanks for the report!  Do you see the error in safe mode (atom --safe) as well?  I was unable to reproduce with 1.24.0-beta1 on macOS 10.12.6.

**Comment by Ben3eeE** [comment]
@daviwil Do you think this can be related to https://github.com/atom/atom/issues/16622?

**Comment by maccuaa** [comment]
I'm getting the same error but for different reasons.  For me this error seems to be stopping the Git pane from working, it shows no diffs and doesn't recognize that there's a git repo.  I open Atom in safe mode (`$ atom --safe .`) and the error occurs immediately.

OS - Mac OSX 10.13.4
Atom - 1.27.0

```
Uncaught (in promise) TypeError: Cannot read property '10' of null
    at parseUnmergedEntry (/Applications/Atom.app/Contents/Resources/app/node_modules/what-the-status/index.js:195:26)
    at parseLine (/Applications/Atom.app/Contents/Resources/app/node_modules/what-the-status/index.js:78:13)
    at Stream.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/what-the-status/index.js:41:37)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:191:7)
    at drain (/Applications/Atom.app/Contents/Resources/app/node_modules/through/index.js:40:22)
    at Stream.stream.queue.stream.push (/Applications/Atom.app/Contents/Resources/app/node_modules/through/index.js:49:11)
    at emit (/Applications/Atom.app/Contents/Resources/app/node_modules/split/index.js:41:20)
    at next (/Applications/Atom.app/Contents/Resources/app/node_modules/split/index.js:53:13)
    at Stream.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/split/index.js:58:11)
    at Stream.stream.write (/Applications/Atom.app/Contents/Resources/app/node_modules/through/index.js:30:17)
    at Readable.ondata (_stream_readable.js:557:20)
    at emitOne (events.js:96:13)
    at Readable.emit (events.js:191:7)
    at Readable.read (_stream_readable.js:383:10)
    at flow (_stream_readable.js:763:34)
    at emitReadable_ (_stream_readable.js:435:3)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by rsese** [comment]
Thanks @maccuaa - though the error message is the same, the stack trace looks pretty different.

If you're still getting this error, go ahead and open a new issue and fill out the issue template and we'll take a look (please try the suggestions from https://flight-manual.atom.io/hacking-atom/sections/debugging/ as mentioned in the issue template).

**Comment by devey** [comment]
Had same issue as @maccuaa, `atom --clear-window-state` fixed it.

**Comment by Mhs-220** [comment]
i just check solutions and still see this error in developer console.
it's happen when i click on git button in bottom bar. it is suddenly happened and git is not working after that.

OS         : Ubuntu 18.04
Atom     : 1.34.0
Electron : 2.0.16
Chrome : 61.0.3163.100
Node     : 8.9.3

```
VM22 <embedded>:14 Uncaught (in promise) TypeError: Cannot read property '10' of null
    at parseUnmergedEntry (/usr/share/atom/resources/app/static/<embedded>:14:3416691)
    at parseLine (/usr/share/atom/resources/app/static/<embedded>:14:3417101)
    at Stream.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:3417490)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at drain (/usr/share/atom/resources/app/static/<embedded>:14:3820037)
    at Stream.d.queue.d.push (/usr/share/atom/resources/app/static/<embedded>:14:3820255)
    at emit (/usr/share/atom/resources/app/static/<embedded>:14:3793022)
    at next (/usr/share/atom/resources/app/static/<embedded>:14:3793209)
    at Stream.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:3793241)
    at Stream.d.write (/usr/share/atom/resources/app/static/<embedded>:14:3820165)
    at Readable.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Readable.emit (events.js:211:7)
    at Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at emitReadable_ (_stream_readable.js:514:3)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
parseUnmergedEntry @ VM22 <embedded>:14
parseLine @ VM22 <embedded>:14
(anonymous) @ VM22 <embedded>:14
emitOne @ events.js:116
emit @ events.js:211
drain @ VM22 <embedded>:14
d.queue.d.push @ VM22 <embedded>:14
emit @ VM22 <embedded>:14
next @ VM22 <embedded>:14
(anonymous) @ VM22 <embedded>:14
d.write @ VM22 <embedded>:14
ondata @ _stream_readable.js:639
emitOne @ events.js:116
emit @ events.js:211
Readable.read @ _stream_readable.js:475
flow @ _stream_readable.js:846
emitReadable_ @ _stream_readable.js:514
_combinedTickCallback @ internal/process/next_tick.js:135
_tickCallback @ internal/process/next_tick.js:180
async function (async)
_refreshModelData @ VM22 <embedded>:14
refreshModelData @ VM22 <embedded>:14
e.activeModel.activeModelUpdateSubscription.e.onDidUpdate @ VM22 <embedded>:14
simpleDispatch @ VM22 <embedded>:14
emit @ VM22 <embedded>:14
didUpdate @ VM22 <embedded>:14
invalidateCacheAfterFilesystemChange @ VM22 <embedded>:14
observeFilesystemChange @ VM22 <embedded>:14
Repository.(anonymous function) @ VM22 <embedded>:14
WorkdirContext.subs.add.observer.onDidChange.e @ VM22 <embedded>:14
simpleDispatch @ VM22 <embedded>:14
emit @ VM22 <embedded>:14
didChange @ VM22 <embedded>:14
e @ VM22 <embedded>:14
```

**Comment by rsese** [comment]
@Mhs-220 - go ahead and open a new issue and fill out the issue template and we'll take a look.
