### ISSUE TITLE
apm install crashes on non-lowercase package names

### ISSUE THREAD

**Issue by elprans** [atom/atom#16478]
### Description

```
$ apm install MagicPython
(node:12659) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Installing MagicPython to /home/elvis/.atom/packages ✓
fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/elvis/.atom/packages/MagicPython/package.json'
    at Object.fs.openSync (fs.js:558:18)
    at Proxy.fs.readFileSync (fs.js:468:33)
    at Proxy.fs.readFileSync (/usr/lib64/atom/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /usr/lib64/atom/app/apm/lib/install.js:476:42
    at fn (/usr/lib64/atom/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/usr/lib64/atom/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

See also: https://github.com/MagicStack/MagicPython/issues/115

**Comment by 50Wliu** [comment]
We are hoping to release a hotfix shortly that will resolve this.  See https://github.com/atom/settings-view/issues/1018#issuecomment-354846305.
