### ISSUE TITLE
Uncaught ReferenceError: core is not defined

### ISSUE THREAD

**Issue by popolok11** [atom/atom#16523]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught ReferenceError: core is not defined

```
At C:\Users\subyp\.atom\init.coffee:14

ReferenceError: core is not defined
    at HTMLElement.<anonymous> (~/.atom/init.coffee:14:3)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.2/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.23.2/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:24 custom:auto-format (input.hidden-input)
```

### Non-Core Packages

```
fonts 3.0.3 
hex-editor 0.1.1 
language-robotc 0.3.4 
```

**Comment by maxbrunsfeld** [comment]
This looks like an error in your own `init.coffee`. Try looking at line 14 of that file. Is there a usage of an undefined variable `core`?
