### ISSUE TITLE
Recent changes cause error in popular atom-beautify package

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#16540]
### Description

After building Atom from master (1.25.0-dev-dced608f4) earlier this week, I started seeing a console error at startup related to the [popular atom-beautify package](https://atom.io/packages/atom-beautify):

```
~/atom/packages/atom-beautify/src/beautifiers/index.coffee:135 Error loading options TypeError: Cannot read property 'includes' of undefined
    at ScopeDescriptor.module.exports.ScopeDescriptor.getScopeChain (/Applications/Atom.app/Contents/Resources/app/src/scope-descriptor.js:30:31)
    at Config.module.exports.Config.getRawScopedValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:940:80)
    at Config.module.exports.Config.get (/Applications/Atom.app/Contents/Resources/app/src/config.js:193:28)
    at ~/atom/packages/atom-beautify/src/beautifiers/index.coffee:123:9
    at ~/atom/packages/standard-formatter/node_modules/lodash/lodash.js:13379:38
    at ~/atom/packages/standard-formatter/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (~/atom/packages/standard-formatter/node_modules/lodash/lodash.js:3001:24)
    at Function.mapValues (~/atom/packages/standard-formatter/node_modules/lodash/lodash.js:13378:7)
    at Beautifiers.module.exports.Beautifiers.loadOptions (~/atom/packages/atom-beautify/src/beautifiers/index.coffee:121:19)
    at new Beautifiers (~/atom/packages/atom-beautify/src/beautifiers/index.coffee:116:17)
    at Object.<anonymous> (~/atom/packages/atom-beautify/src/beautify.coffee:10:14)
    at Object.<anonymous> (~/atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Object.<anonymous> (~/atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:220:40)
    at activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/Applications/Atom.app/Contents/Resources/app/src/package.js:901:81)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.triggerDeferredActivationHooks (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:717:40)
    at Promise.all.then (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:650:18)
    at <anonymous>
```

### Steps to Reproduce

1. Build atom from source
2. Install [atom-beautify](https://atom.io/packages/atom-beautify) 0.30.9
3. Reload Atom

**Expected behavior:** No errors in console

**Actual behavior:** The error above appears in the console

**Reproduces how often:** 100%

### Versions

One macOS 10.13.2...

```
$ atom --version
Atom    : 1.25.0-dev-dced608f4
Electron: 1.7.10
Chrome  : 58.0.3029.110
Node    : 7.9.0

$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0-dev-b5c939d5c
python 2.7.10
git 2.15.1
```

### Additional Information

Using `git bisect` and running Atom in dev mode, it appears that 4adfba47cca5c4aef147918f33a6b2ffb51e6a4a (added in https://github.com/atom/atom/pull/16299) introduced the change that causes this error.

@maxbrunsfeld @nathansobo: Would you consider this a regression, or does this error represent a change that we need to ask package authors to make in their packages?

**Comment by nathansobo** [comment]
Have a fix for this building now.
