### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by nicahdemarco** [atom/atom#16578]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At C:\Users\morta\AppData\Local\atom\app-1.23.3\resources\app\src\tokenized-buffer.js:517

TypeError: Cannot match against 'undefined' or 'null'.
    at TokenizedBuffer.indentLevelForLine (~/AppData/Local/atom/app-1.23.3/resources/app/src/tokenized-buffer.js:517:38)
    at TokenizedBuffer.endRowForCodeFoldAtRow (~/AppData/Local/atom/app-1.23.3/resources/app/src/tokenized-buffer.js:701:41)
    at TokenizedBuffer.endRowForFoldAtRow (~/AppData/Local/atom/app-1.23.3/resources/app/src/tokenized-buffer.js:680:25)
    at TokenizedBuffer.isFoldableAtRow (~/AppData/Local/atom/app-1.23.3/resources/app/src/tokenized-buffer.js:392:23)
    at TextEditor.isFoldableAtBufferRow (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:3842:39)
    at TextEditorComponent.queryLineNumbersToRender (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor-component.js:927:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor-component.js:378:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor-component.js:274:16)
    at didDrag (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor-component.js:1829:20)
    at get_window.requestAnimationFrame (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor-component.js:1904:17)
```

### Commands

```
     -1:38.3.0 intentions:highlight (input.hidden-input)
     -1:38 find-and-replace:show (input.hidden-input)
  3x -1:35.8.0 core:backspace (input.hidden-input)
     -1:31.4.0 core:confirm (input.hidden-input)
     -0:56.2.0 intentions:highlight (input.hidden-input)
     -0:56 core:copy (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
color-picker 2.2.5 
double-tag 1.1.0 
emmet 2.4.3 
file-icons 2.1.15 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-htmlhint 1.4.0 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
minimap 4.29.7 
pigments 0.40.2 
sass-autocompile 0.13.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by talkingbeast** [comment]
same error on linux mint 18.

> Failed to load the tool-bar package
Cannot match against 'undefined' or 'null'.
Hide Stack Trace
TypeError: Cannot match against 'undefined' or 'null'.
    at Object.<anonymous> (/home/talkingbeast/.atom/packages/tool-bar/lib/touch-bar-manager.js:2:26)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/talkingbeast/.atom/packages/tool-bar/lib/tool-bar.js:3:25)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:887:35)
    at /usr/share/atom/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/src/package-manager.js:565:22)
    at /usr/share/atom/resources/app/src/package-manager.js:479:25
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app/src/config.js:321:22)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app/src/package-manager.js:473:25)
    at /usr/share/atom/resources/app/src/atom-environment.js:812:34
The error was thrown from the tool-bar package. This issue has already been reported.

**Comment by rsese** [comment]
> same error on linux mint 18.
> Atom 1.18.0 x64
> i try run atom on safe mode,same error:

Can you install the latest release version of Atom (currently 1.23.3) and let us know if you still see the error?  From the stack trace, it looks like an issue with the tool-bar package (https://github.com/suda/tool-bar/issues/214) so it's odd you see the error in safe mode 🤔

**Comment by ashthespy** [comment]
[Enter steps to reproduce:]

1. Everyday work
2. 

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At C:\Users\Ash\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor-component.js:2409

TypeError: Cannot match against 'undefined' or 'null'.
    at TextEditorComponent.screenPositionForPixelPosition (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:2409:65)
    at TextEditorComponent.screenPositionForMouseEvent (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:1974:23)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:1773:39)
```

### Commands

```
  2x -0:39.2.0 core:move-up (input.hidden-input)
     -0:38.3.0 core:move-down (input.hidden-input)
     -0:37.8.0 editor:consolidate-selections (input.hidden-input)
     -0:37.8.0 core:cancel (input.hidden-input)
     -0:37.5.0 editor:consolidate-selections (input.hidden-input)
     -0:37.5.0 core:cancel (input.hidden-input)
     -0:37.4.0 editor:consolidate-selections (input.hidden-input)
     -0:37.4.0 core:cancel (input.hidden-input)
  2x -0:37 core:move-up (input.hidden-input)
     -0:36.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:35.6.0 editor:newline (input.hidden-input)
     -0:35.1.0 core:save (input.hidden-input)
     -0:34.8.0 core:delete (input.hidden-input)
     -0:33.8.0 core:save (input.hidden-input)
     -0:30.9.0 core:delete (input.hidden-input)
     -0:29.6.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-latex 0.8.4 
atom-live-server 2.2.0 
atom-typescript 12.2.0 
file-icons 2.1.17 
git-plus 7.10.0 
highlight-selected 0.13.1 
language-batchfile 0.7.3 
language-docker 1.1.8 
language-matlab 0.2.1 
language-rust 0.4.12 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
node-debugger 1.10.1 
pdf-view 0.65.0 
remote-ftp 2.1.4 
script 3.17.3 
split-diff 1.5.2 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by rsese** [comment]
@ashthespy the stack trace from your error looks more like https://github.com/atom/atom/issues/15682 if you want to subscribe there for updates.  If you can reproduce in safe mode (`atom --safe`), feel free to let us know in https://github.com/atom/atom/issues/15682.

**Comment by cblp** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Ubuntu 17.10
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At /usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:367

TypeError: Cannot match against 'undefined' or 'null'.
    at SuggestionListElement.scrollSelectedItemIntoView (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:367:38)
    at SuggestionListElement.renderSelectedItem (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:352:18)
    at ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app/src/view-registry.js:238:13)
```

### Commands

```
 10x -0:12.4.0 core:move-down (input.hidden-input)
     -0:10.2.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -0:09.8.0 core:move-up (input.hidden-input)
  3x -0:09.3.0 core:select-left (input.hidden-input)
  2x -0:07.5.0 core:move-down (input.hidden-input)
     -0:06.6.0 autocomplete-haskell:conceal-hint-panel (input.hidden-input)
     -0:06.6.0 autocomplete-plus:cancel (input.hidden-input)
  2x -0:06.3.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -0:05.8.0 core:move-down (input.hidden-input)
     -0:05.4.0 core:select-down (input.hidden-input)
     -0:05.2.0 core:delete (input.hidden-input)
     -0:05.1.0 intentions:highlight (input.hidden-input)
     -0:05.0 core:save (input.hidden-input)
     -0:04.6.0 core:move-up (input.hidden-input)
     -0:04.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -0:04.1.0 core:move-up (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.0 
autocomplete-haskell 1.0.1 
busy-signal 1.4.3 
date 2.1.0 
haskell-ghc-mod 2.2.3 
haskell-scry 1.0.7 
highlight-selected 0.13.1 
ide-haskell 2.3.0 
ide-haskell-cabal 2.1.2 
ide-haskell-hasktags 0.0.14 
ide-haskell-hoogle 0.1.2 
ide-haskell-repl 0.7.15 
intentions 1.1.5 
language-haskell 1.17.3 
linter 2.2.0 
linter-ui-default 1.7.1 
semanticolor 3.6.0 
sort-lines 0.18.0 
tab-smart-sort 0.3.0 
teletype 0.9.0 
```

**Comment by daviwil** [comment]
Every stack trace reported in this issue comes from a different place in the code (and @talkingbeast's comes from the `touch-bar-manager` package.  I'll focus on the original stack trace reported in this issue since it's more clear where that's coming from.
