### ISSUE TITLE
Cannot call function 'getPosition' on missing remote object

### ISSUE THREAD

**Issue by leotada** [atom/atom#16576]
[Enter steps to reproduce:]

1. I don't know

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: "Fedora release 27 x64
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 44
Error: Cannot call function 'getPosition' on missing remote object 44
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 44
Error: Cannot call function 'getPosition' on missing remote object 44
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app/src/atom-environment.js:691:34)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app/src/atom-environment.js:725:42)
    at WindowEventHandler.handleWindowBlur (/usr/share/atom/resources/app/src/window-event-handler.js:189:32)
```

### Commands

```
  2x -2:37.2.0 core:backspace (input.hidden-input)
     -2:33.9.0 core:confirm (input.hidden-input)
     -2:30.9.0 intentions:highlight (input.hidden-input)
     -2:30.7.0 go-to-line:toggle (input.hidden-input)
     -2:29.5.0 core:confirm (input.hidden-input)
     -2:04.2.0 intentions:highlight (input.hidden-input)
     -2:04.1.0 core:paste (input.hidden-input)
     -2:01.0 intentions:highlight (input.hidden-input)
     -2:00.9.0 core:save (input.hidden-input)
     -1:17.1.0 intentions:highlight (input.hidden-input)
     -1:17 core:save (input.hidden-input)
     -0:24.1.0 intentions:highlight (input.hidden-input)
     -0:24 fuzzy-finder:toggle-file-finder (input.hidden-input)
  3x -0:21.4.0 core:move-down (input.hidden-input)
     -0:20.9.0 core:move-up (input.hidden-input)
     -0:20.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-monokai 0.10.9 
autoclose-html 0.23.0 
autocomplete-dcd 1.8.0 
autocomplete-python-jedi 1.10.3-0 
base64 0.3.0 
behave-theme 1.7.0 
busy-signal 1.4.3 
city-lights-syntax 1.1.6 
city-lights-ui 1.3.1 
ide-python 0.5.0 
indent-guide-improved 1.4.13 
intentions 1.1.5 
isotope-ui 2.8.5 
language-d 3.3.1 
linter 2.2.0 
linter-pyflakes 0.3.2 
linter-ui-default 1.6.10 
MagicPython 1.0.12 
minimap 4.29.7 
minimap-split-diff 0.3.7 
nucleus-dark-ui 0.12.3 
split-diff 1.5.2 
styri-syntax 0.2.0 
unity-ui 2.1.11 
```

**Comment by leotada** [comment]
Duplicated with #16460
Can close, or use to more info.

**Comment by rsese** [comment]
Thanks @leotada :+1:

If you end up running into the issue again or recalling any details about triggering the error, please let us know in #16460.
