### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

### ISSUE THREAD

**Issue by susanschen** [atom/atom#16587]
[Enter steps to reproduce:]

1. Ctrl-F to open find
2. Type a word and error message shows after 4th character

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At C:\Users\susan\AppData\Local\atom\app-1.23.3\resources\app\node_modules\autocomplete-plus\lib\subsequence-provider.js:149

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
    at SubsequenceProvider.bufferToSubsequenceMatches (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/subsequence-provider.js:149:59)
    at Array.map (native)
    at SubsequenceProvider.getSuggestions (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/subsequence-provider.js:271:18)
    at providers.forEach.provider (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:300:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:271:21)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:263:23)
```

### Commands

```
     -0:40.4.0 find-and-replace:show (input.hidden-input)
```

### Non-Core Packages

```
emmet 2.4.3 
language-babel 2.81.1 
oceanic-next 1.0.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if you the error is reproducible and if it's reproducible in safe mode (`atom --safe`)?

**Comment by susanschen** [comment]
It's fixed -- I have unchecked 'Include Completions From All Buffers' in autocomplete-plus settings, which is causing the error each time I use 'find'   Checking it fixes the problem.

**Comment by dariusv5** [comment]
Issue still exists when not using the 'Include Completions From All Buffers' option.
