### ISSUE TITLE
Uncaught Error: read ENOTCONN

### ISSUE THREAD

**Issue by jabbo126** [atom/atom#16615]
- Downloaded new update
- Clicked settings
- Clicked system
that's all

1. ...
2. ...

**Atom**: 1.23.3 ia32
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: read ENOTCONN

```
At events.js:160

Error: read ENOTCONN
    at exports._errnoException (util.js:1022:11)
    at Socket._read (net.js:425:21)
    at Socket.Readable.read (_stream_readable.js:348:10)
    at Socket.read (net.js:308:43)
    at new Socket (net.js:188:12)
    at createSocket (internal/child_process.js:243:11)
    at internal/child_process.js:329:22
    at Array.forEach (native)
    at ChildProcess.spawn (internal/child_process.js:318:9)
    at exports.spawn (child_process.js:399:9)
    at Registry.get (/app.asar/node_modules/winreg/lib/registry.js:616:14)
    at ShellOption.isRegistered (/app.asar/src/main-process/win-shell.js:40:91)
    at new SystemPanel (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/settings-view/lib/system-windows-panel.js:53:44)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/settings-view/lib/settings-view.js:230:26
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/settings-view/lib/settings-view.js:371:25)
    at SettingsView.showPanel (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/settings-view/lib/settings-view.js:429:30)
    at HTMLDivElement.clickHandler (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/settings-view/lib/settings-view.js:190:24)
```

### Commands

```
     -7:00.3.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -6:40.9.0 tree-view:collapse-all (span.name.icon.icon-file-directory)
     -5:06.7.0 github:toggle-github-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:00.4.0 github:toggle-git-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
uss-file-sync 0.5.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Is the error reproducible for you every time you go to `Settings > System`?

Also, did this used to work for you but you only started to see this error as of 1.23.3?

**Comment by rsese** [comment]
Ohhh also I just found https://github.com/atom/settings-view/issues/960, looks like a duplicate based on the stack trace.   The issue author mentioned how they resolved the error in https://github.com/atom/settings-view/issues/960#issuecomment-308011109, can you check if that works for you on your system?
