### ISSUE TITLE
Uncaught Error: No segment found

### ISSUE THREAD

**Issue by vigneshsankar07** [atom/atom#16664]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: No segment found

```
At /home/teletype/node_modules/@atom/teletype-crdt/lib/document-tree.js:77

Error: No segment found
    at DocumentTree.findSegmentContainingPosition (/home/teletype/node_modules/@atom/teletype-crdt/lib/document-tree.js:77:11)
    at Document.findSegment (/home/teletype/node_modules/@atom/teletype-crdt/lib/document.js:1061:51)
    at Document.getLogicalRange (/home/teletype/node_modules/@atom/teletype-crdt/lib/document.js:1006:78)
    at Document.snapshotFromMarkers (/home/teletype/node_modules/@atom/teletype-crdt/lib/document.js:934:37)
    at Document.createCheckpoint (/home/teletype/node_modules/@atom/teletype-crdt/lib/document.js:291:23)
    at BufferProxy.createCheckpoint (/home/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:125:26)
    at BufferBinding.createCheckpoint (/home/teletype/lib/buffer-binding.js:116:29)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:935:53)
    at TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1811:30)
    at TextEditor.moveCursors (/usr/share/atom/resources/app/src/text-editor.js:2680:23)
    at TextEditor.setCursorScreenPosition (/usr/share/atom/resources/app/src/text-editor.js:2491:23)
    at TextEditorComponent.didMouseDownOnContent (/usr/share/atom/resources/app/src/text-editor-component.js:1810:25)
```

### Commands

```
```

### Non-Core Packages

```
atom-pair 2.0.13 
teletype 0.6.0 
```

**Comment by rsese** [comment]
Thanks for the report!  It looks like this was reported here though:

https://github.com/atom/teletype/issues/215

I'll go ahead and close as a duplicate - do you remember what you were doing at the time of the error?

**Comment by vigneshsankar07** [comment]
Robert Sese,
Thanks for your reply.
I think that problem here, I'm installing 2 type atom once i clear that one atom easily works with us teletype.
