### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 658Error: Cannot cal...

### ISSUE THREAD

**Issue by espriu** [atom/atom#16672]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 658
Error: Cannot call function 'getPosition' on missing remote object 658
    at throwRPCError (C:\Users\PmA\AppData\Local\atom\app-1.23.3\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\PmA\AppData\Local\atom\app-1.23.3\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\PmA\AppData\Local\atom\app-1.23.3\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At C:\Users\PmA\AppData\Local\atom\app-1.23.3\resources\electron.asar\renderer\api\remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 658
Error: Cannot call function 'getPosition' on missing remote object 658
    at throwRPCError (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.23.3/resources/app/src/atom-environment.js:691:34)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.23.3/resources/app/src/atom-environment.js:725:42)
    at WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.23.3/resources/app/src/window-event-handler.js:189:32)
```

### Commands

```
 27x -1:44.7.0 core:backspace (input.hidden-input)
     -1:16.4.0 project-find:show (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.7.0 
autocomplete 0.47.0 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
drag-drop-text 0.1.4 
hyperclick 0.0.0 
ide-php 0.7.4 
intentions 1.1.5 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.6.10 
php-debug 0.2.6 
php-integrator-annotations 1.2.0 
php-integrator-base 3.1.0 
php-integrator-navigation 1.2.1 
project-manager 3.3.5 
remote-atom 1.3.11 
remote-ftp 2.1.2 
simple-drag-drop-text 0.3.6 
```

**Comment by cleanenergyjoy** [comment]
3.3.5
