### ISSUE TITLE
Uncaught TypeError: Cannot read property 'command' of undefined

### ISSUE THREAD

**Issue by FishyFing** [atom/atom#16676]
1. Right click on file or directory in the project pane when working on a git project

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Kali GNU/Linux
**Thrown From**: Atom Core
**User**: root

### Stack Trace

Uncaught TypeError: Cannot read property 'command' of undefined

```
At /usr/share/atom/resources/app/src/context-menu-manager.js:122

TypeError: Cannot read property 'command' of undefined
    at ContextMenuManager.module.exports.ContextMenuManager.addAccelerators (/usr/share/atom/resources/app/src/context-menu-manager.js:122:23)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/usr/share/atom/resources/app/src/context-menu-manager.js:113:18)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app/src/context-menu-manager.js:189:33)
    at WindowEventHandler.handleDocumentContextmenu (/usr/share/atom/resources/app/src/window-event-handler.js:251:44)
```

### Commands

```
     -1:51.4.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:42.3.0 core:move-left (input.hidden-input)
  2x -1:41.7.0 core:move-right (input.hidden-input)
  8x -1:41 core:backspace (input.hidden-input)
  2x -1:26.1.0 core:move-right (input.hidden-input)
 31x -1:23.9.0 core:move-left (input.hidden-input)
 31x -1:19.2.0 core:move-right (input.hidden-input)
 26x -1:16.7.0 core:move-left (input.hidden-input)
 12x -1:14.9.0 core:backspace (input.hidden-input)
 27x -1:12.5.0 core:move-right (input.hidden-input)
     -1:07.8.0 core:move-left (input.hidden-input)
     -1:05.4.0 core:backspace (input.hidden-input)
     -1:03.9.0 editor:newline (input.hidden-input)
     -0:58.9.0 core:move-right (input.hidden-input)
  5x -0:53.6.0 core:backspace (input.hidden-input)
     -0:49.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
highlight-selected 0.13.1 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
preview 0.17.0 
python-autopep8 0.1.3 
rst-preview 1.3.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm the error is reproducible and if so, can you reproduce in safe mode (atom --safe)?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16676#issuecomment-363257598. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
