### ISSUE TITLE
Failed to activate the node-resolver package

### ISSUE THREAD

**Issue by nileshchakraborty** [atom/atom#16684]
1. Installed Atom 
2. Tried to install node-resolver

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: 'node-resolver' package vundefined

### Stack Trace

Failed to activate the node-resolver package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.exports.activate (/packages/node-resolver/index.js:12:21)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:255:25)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:695:42)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.23.3/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.23.3/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
  3x -4:53.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
angularjs 0.5.3 
angularjs-snippets 0.10.18 
atom-nodejs-snippets 2.0.0 
autocomplete-angular-material 0.4.0 
Hydrogen 2.2.2 
node-resolver 1.0.1 
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [node-resolver](https://atom.io/packages/node-resolver) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
