### ISSUE TITLE
Uncaught URIError: URI malformed

### ISSUE THREAD

**Issue by magnipopam** [atom/atom#16687]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught URIError: URI malformed

```
At url.js:283

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Url.parse (url.js:283:19)
    at Object.urlParse [as parse] (url.js:89:5)
    at CloneDialog.didChangeRemoteUrl (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/github/lib/views/clone-dialog.js:196:76)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at disposables.add.displayLayer.onDidChange.changes (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:588:26)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDeferredChangeEvents (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/display-layer.js:833:26)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:1682:30)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:964:18)
    at TextEditor.transact (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1811:30)
    at mergeIntersectingSelections (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1358:25)
    at TextEditor.mergeSelections (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:3194:26)
    at TextEditor.mergeIntersectingSelections (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:3165:42)
    at TextEditor.mutateSelectedText (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1357:23)
    at TextEditor.insertText (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1323:23)
    at TextEditorComponent.didTextInput (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor-component.js:1647:30)
```

### Commands

```
     -3:08.3.0 application:open-file (atom-pane.pane.active)
     -2:47.3.0 command-palette:toggle (atom-pane.pane.active)
     -2:42.8.0 core:confirm (input.hidden-input)
     -2:42.8.0 github:clone (atom-pane.pane.active)
  2x -1:47.3.0 core:paste (input.hidden-input)
     -0:26.6.0 core:undo (input.hidden-input)
     -0:25.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/16687#issuecomment-364218800. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
