### ISSUE TITLE
Uncaught Error: target of repeat operator is invalid

### ISSUE THREAD

**Issue by MBillhardt** [atom/atom#16699]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: target of repeat operator is invalid

```
At /opt/atom/resources/app/node_modules/first-mate/lib/scanner.js:33

Error: target of repeat operator is invalid
    at Scanner.module.exports.Scanner.createScanner (/opt/atom/resources/app/node_modules/first-mate/lib/scanner.js:33:30)
    at Scanner.module.exports.Scanner.getScanner (/opt/atom/resources/app/node_modules/first-mate/lib/scanner.js:39:37)
    at Scanner.module.exports.Scanner.findNextMatch (/opt/atom/resources/app/node_modules/first-mate/lib/scanner.js:58:28)
    at Rule.module.exports.Rule.findNextMatch (/opt/atom/resources/app/node_modules/first-mate/lib/rule.js:98:34)
    at Rule.module.exports.Rule.getNextTags (/opt/atom/resources/app/node_modules/first-mate/lib/rule.js:154:27)
    at Grammar.module.exports.Grammar.tokenizeLine (/opt/atom/resources/app/node_modules/first-mate/lib/grammar.js:169:50)
    at TokenizedBuffer.buildTokenizedLineForRowWithText (/opt/atom/resources/app/src/tokenized-buffer.js:424:50)
    at TokenizedBuffer.buildTokenizedLineForRow (/opt/atom/resources/app/src/tokenized-buffer.js:419:23)
    at TokenizedBuffer.tokenizeNextChunk (/opt/atom/resources/app/src/tokenized-buffer.js:307:47)
    at _.defer (/opt/atom/resources/app/src/tokenized-buffer.js:291:63)
    at /opt/atom/resources/app/node_modules/underscore/underscore.js:666:53
```

### Commands

```
  2x -0:36.1.0 pane:reopen-closed-item (atom-pane.pane)
```

### Non-Core Packages

```
atom-commander 0.10.3 
atom-live-grammar-reload 0.8.0 
ftp-remote-edit 0.12.9 
language-rwriter 0.0.1 
```

I was trying to create an own language grammar.
The language uses the * for comments.
When I try to the following pattern i get the error above when i open a file:

patterns: [
  {
  comment: 'Comment'
  name: 'comment.line.rwriter'
  match: '^\*.*$'
  }

When i replace the first * with an #, there is no error ...

Thank you for your help.
Billy

**Comment by MBillhardt** [comment]
Sorry ... I got it.
It has to be:

match: '^[\*].*$'

Greetings,
Billy

**Comment by 50Wliu** [comment]
`*` means "repeat the previous character 0 or more times".  You can't repeat `^`, the start-of-line indicator.  If you need to match a literal `*`, use `\\*`.
