### ISSUE TITLE
`script/bootstrap` fails on fedora 27

### ISSUE THREAD

**Issue by TARPTAEYA** [atom/atom#16694]
### Description

I am building atom on fedora via `script/bootstrap` but it ends up with the following error

```
Installing modules ✗
> atom@1.25.0-dev preinstall /home/tarptaeya/atom
> node -e 'process.exit(0)'


> keyboard-layout@2.0.13 install /home/tarptaeya/atom/node_modules/keyboard-layout
> node-gyp rebuild

make: Entering directory '/home/tarptaeya/atom/node_modules/keyboard-layout/build'
  CXX(target) Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o
make: Leaving directory '/home/tarptaeya/atom/node_modules/keyboard-layout/build'
atom@1.25.0-dev /home/tarptaeya/atom

...

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated coffee-script@1.8.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN prefer global typescript@1.4.1 should be installed with -g
npm WARN prefer global jasmine-node@1.10.2 should be installed with -g
In file included from ../src/keyboard-layout-manager-linux.cc:1:0:
../src/keyboard-layout-manager.h:7:10: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [keyboard-layout-manager.target.mk:96: Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/tarptaeya/atom/apm/node_modules/atom-package-manager/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.13.9-300.fc27.x86_64
gyp ERR! command "/home/tarptaeya/atom/apm/node_modules/atom-package-manager/bin/node" "/home/tarptaeya/atom/apm/node_modules/atom-package-manager/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/tarptaeya/atom/node_modules/keyboard-layout
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.13.9-300.fc27.x86_64
npm ERR! argv "/home/tarptaeya/atom/apm/node_modules/atom-package-manager/bin/node" "/home/tarptaeya/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/tarptaeya/.atom/.apm/.apmrc" "--userconfig" "/home/tarptaeya/.atom/.apmrc" "install" "--runtime=electron" "--target=1.7.11" "--arch=x64"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! keyboard-layout@2.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keyboard-layout@2.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keyboard-layout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keyboard-layout
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keyboard-layout
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tarptaeya/atom/npm-debug.log
child_process.js:624
    throw err;
    ^

Error: Command failed: /home/tarptaeya/atom/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at module.exports (/home/tarptaeya/atom/script/lib/run-apm-install.js:14:16)
    at Object.<anonymous> (/home/tarptaeya/atom/script/bootstrap:35:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)

```
I also tried `script/clean` but it also didnt work.

### Steps to Reproduce

1. run `script/bootstrap`

**Comment by Ben3eeE** [comment]
> ../src/keyboard-layout-manager.h:7:10: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>

It looks like you have not installed the required dependencies to build Atom. See http://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#fedora-22
