### ISSUE TITLE
Uncaught Error: Transport unexpectedly closed

### ISSUE THREAD

**Issue by dollymsq** [atom/atom#16702]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Transport unexpectedly closed

```
At /opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:93

Error: Transport unexpectedly closed
    at IpcClientTransport.send (/opt/facebook/nuclide/0.272.84970322/nuclide/pkg/nuclide-remote-connection/lib/IpcTransports.js:113:13)
    at sendSubscribe (/opt/facebook/nuclide/0.277.88025270/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:371:29)
    at b._rxjsBundlesRxMinJs.Observable.create.observer [as _subscribe] (/opt/facebook/nuclide/0.277.88025270/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:390:13)
    at b._trySubscribe (/opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:73:217)
    at b.subscribe (/opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:73:43)
    at r (/opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:33:305)
    at a._innerSub (/opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:262:1)
    at a._next (/opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:261:375)
    at a.next (/opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at /opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:93:343
```

### Commands

```
     -0:13.2.0 fb-on-demand:www (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-light-syntax.theme-atom-light-ui)
```

### Non-Core Packages

```
auto-detect-indentation 1.3.0 
file-icons 2.1.16 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.81.1 
language-graphql 0.9.0 
language-haskell 1.16.2 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
merge-conflicts 1.4.5 
nuclide 0.282.91025252 
nuclide-format-js 0.0.43 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.4 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [nuclide](https://atom.io/packages/nuclide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
