### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by mvdesired** [atom/atom#16710]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line component that is not currently rendered

```
At C:\Users\musta_000\AppData\Local\atom\app-1.23.3\resources\app\src\text-editor-component.js:2289

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor-component.js:2278:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor-component.js:2271:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor-component.js:400:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor-component.js:278:20)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.23.3/resources/app/src/view-registry.js:245:13)
```

### Commands

```
     -2:38.2.0 snippets:next-tab-stop (input.hidden-input)
     -2:38.2.0 snippets:expand (input.hidden-input)
     -2:38.2.0 editor:indent (input.hidden-input)
     -2:37.6.0 core:save (input.hidden-input)
     -2:30.4.0 snippets:next-tab-stop (input.hidden-input)
     -2:30.4.0 snippets:expand (input.hidden-input)
     -2:30.4.0 editor:indent (input.hidden-input)
  2x -2:29.9.0 core:save (input.hidden-input)
     -1:54.2.0 core:backspace (input.hidden-input)
     -1:53.5.0 core:undo (input.hidden-input)
     -1:53 core:save (input.hidden-input)
     -1:48.6.0 snippets:next-tab-stop (input.hidden-input)
     -1:48.6.0 snippets:expand (input.hidden-input)
     -1:48.6.0 editor:indent (input.hidden-input)
     -1:47.7.0 core:undo (input.hidden-input)
     -1:03.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-javascript 0.0.2 
javascript-snippets 1.2.1 
jQuery 1.2.5 
jquery-snippets 11.0.0 
minimap 4.29.7 
teletype 0.7.0 
```

**Comment by lee-dohm** [comment]
Do you have any indication as to what you were doing when the error occurred? Any steps to reproduce the problem?
