### ISSUE TITLE
Failed to activate the status-bar package (1.25.0-beta0)

### ISSUE THREAD

**Issue by bjmiller** [atom/atom#16729]
### Description

Error reported after updating to atom-beta 1.25.0-beta0

To reproduce: Open any project after update.

**Atom**: 1.25.0-beta0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package 1.8.15

### Stack Trace

Failed to activate the status-bar package

```
At Cannot find module 'undefined/node_modules/first-mate/lib/grammar'

Error: Cannot find module 'undefined/node_modules/first-mate/lib/grammar'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee:6:11)
    at /packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee:3:1)
    at /packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee:3:1)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:6:19)
    at /packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:3:1)
    at /packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:3:1)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.addStatusBarItemsIfReady (/packages/foldingtext-for-atom/lib/foldingtext.coffee:137:29)
    at Object.consumeStatusBarService (/packages/foldingtext-for-atom/lib/foldingtext.coffee:130:6)
    at Provider.module.exports.Provider.provide (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.activateServices (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:397:75)
```

### Commands

```
     -1:22.2.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-easy-jsdoc 4.12.5 
atom-ide-ui 0.8.1 
atom-ternjs 0.18.3 
atom-typescript 12.1.2 
atom-wrap-in-tag 0.6.0 
autocomplete-modules 1.10.0 
autocomplete-paths 2.12.2 
blame 1.0.1 
brian1 0.0.0 
busy-signal 1.4.3 
change-case 0.6.5 
color-picker 2.2.5 
copy-path 0.4.2 
diagrams 0.28.4 
editorconfig 2.2.2 
file-icons 2.1.16 
foldingtext-for-atom 0.9.2 
font-preview 0.1.1 
hey-pane 1.1.0 
ide-typescript 0.7.2 
intentions 1.1.5 
language-babel 2.83.1 
language-docker 1.1.8 
language-groovy 0.7.0 
language-ini 1.19.0 
language-jade 0.7.2 
language-kotlin 0.5.0 
language-scala 1.1.9 
language-tla-pluscal 0.2.0 
line-count 0.5.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-lesshint 4.0.1 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
local-history 4.3.1 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-pigments 0.2.2 
pigments 0.40.2 
platformio-ide-terminal 2.8.0 
preview 0.17.0 
project-quick-open 0.5.0 
regex-railroad-diagram 0.19.4 
resize-indent 0.3.0 
shell-it 0.2.1 
single-click-open 0.2.2 
sloc 1.1.0 
smarter-tab-key 0.0.0 
sort-lines 0.18.0 
Sublime-Style-Column-Selection 1.7.4 
tabs-to-spaces 1.0.3 
to-base64 0.5.2 
toggle-quotes 1.1.0 
trailing-semicolon 1.1.0 
tree-view-copy-relative-path 1.2.0 
turbo-javascript 1.4.0 
valign 1.1.3 
```

**Comment by rsese** [comment]
Thanks for contributing!

I'm unable to reproduce in 1.25.0-beta0 - based on the stack trace, it appears that this is being caused by the [foldingtext-for-atom](https://atom.io/packages/foldingtext-for-atom) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
