### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by byzyk** [atom/atom#16732]
[Enter steps to reproduce:]

1. Occurs only when trying to open `html` files. Started to happen after running this command `apm install prettier-atom@0.49.0`

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:324

TypeError: undefined is not a function
    at Grammar.module.exports.Grammar.startIdForScope (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:324:34)
    at TextMateLanguageMode.tokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:428:30)
    at TextMateHighlightIterator.seek (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:746:49)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:83:58)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:867:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:376:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:274:16)
    at TextEditorComponent.didShow (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1457:18)
    at TextEditorComponent.didAttach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1424:20)
    at HTMLElement.attachedCallback (/app.asar/src/text-editor-element.js:41:25)
    at HTMLElement.PaneElement.activeItemChanged (/app.asar/src/pane-element.js:156:24)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:435:26)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:575:18)
    at TabBarView.module.exports.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:721:25)
```

### Commands

```
     -4:49.3.0 intentions:highlight (input.hidden-input)
     -2:43.8.0 editor:newline (input.hidden-input)
     -2:43.2.0 snippets:next-tab-stop (input.hidden-input)
     -2:43.2.0 snippets:expand (input.hidden-input)
     -2:39.1.0 core:copy (input.hidden-input)
     -2:37.4.0 core:paste (input.hidden-input)
     -2:34.6.0 core:move-down (input.hidden-input)
     -2:34.3.0 autocomplete-plus:confirm (input.hidden-input)
     -2:34.3.0 snippets:expand (atom-text-editor.editor.linter-tslint-compatible-editor.typescript-editor.is-focused.autocomplete-active)
     -2:33.1.0 core:undo (input.hidden-input)
     -2:22.3.0 intentions:highlight (input.hidden-input)
     -2:22.1.0 editor:move-to-end-of-word (input.hidden-input)
  2x -2:06.7.0 core:cut (input.hidden-input)
     -2:01.4.0 window:save-all (input.hidden-input)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
angular-bootstrap 1.0.1 
atom-beautify 0.30.9 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.1 
atom-runner 2.7.1 
atom-typescript 12.1.2 
atom-underscore 0.1.3 
autocomplete-angular-material 0.4.0 
busy-signal 1.4.3 
caniuse 0.9.2 
emmet 2.4.3 
file-icons 2.1.16 
font-viewer 0.3.1 
hey-pane 1.1.0 
hyperclick 0.1.5 
intentions 1.1.5 
language-babel 2.83.4 
language-groovy 0.7.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.4.1 
linter-flow 5.6.1 
linter-htmlhint 1.4.0 
linter-jsonlint 1.3.0 
linter-python 3.1.2 
linter-scss-lint 3.1.1 
linter-tslint 1.9.0 
linter-ui-default 1.6.10 
linter-write-good 0.9.0 
minimap 4.29.7 
multi-cursor 2.1.5 
open-terminal-here 2.3.1 
pigments 0.40.2 
prettier-atom 0.50.0 
script-runner 2.2.2 
tree-ignore 0.6.2 
```

**Comment by rsese** [comment]
> Occurs only when trying to open html files. Started to happen after running this command apm install prettier-atom@0.49.0

Thanks for the report - just to confirm, if you uninstall/disable prettier-atom you can no longer reproduce the error?

**Comment by byzyk** [comment]
I guess the issue was related to third-party packages. After removing `atom-underscore` and `prettier-atom`, re-installing `atom` and another version of prettier like this `apm prettier-atom@0.49.2` the issue seems to be gone.

**Comment by adamzerner** [comment]
I'm having the same issue. It seems to only happen when I open up my `shit.todo` file, not files with other extensions.



`/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:324`

```
TypeError: undefined is not a function
    at Grammar.module.exports.Grammar.startIdForScope (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:324:34)
    at TextMateLanguageMode.tokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:428:30)
    at TextMateHighlightIterator.seek (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:746:49)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:83:58)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:867:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:376:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:274:16)
    at TextEditorComponent.didShow (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1457:18)
    at TextEditorComponent.didAttach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1424:20)
    at HTMLElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:41:25)
    at HTMLElement.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:156:24)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:435:26)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:575:18)
    at TabBarView.module.exports.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:721:25)
```

Mac OSX 10.13.3
Atom 1.24.0

Atom is up to date, and all of my packages are also up to date.
