### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 135.28.13.11:8080

### ISSUE THREAD

**Issue by rf2533** [atom/atom#16762]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 135.28.13.11:8080

```
At stream.js:74

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 135.28.13.11:8080
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  2x -6:27.4.0 core:save-as (input.hidden-input)
     -1:03.7.0 core:paste (input.hidden-input)
     -0:55.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by lee-dohm** [comment]
What were you doing when this exception occurred? Did you try with [Safe Mode?](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16762#issuecomment-369382922. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
