### ISSUE TITLE
Uncaught TypeError: this.registry.startIdForScope is not a function

### ISSUE THREAD

**Issue by yuhei159** [atom/atom#16788]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.registry.startIdForScope is not a function

```
At C:\Users\SCI01726\AppData\Local\atom\app-1.24.0\resources\app\node_modules\first-mate\lib\grammar.js:324

TypeError: this.registry.startIdForScope is not a function
    at Grammar.module.exports.Grammar.startIdForScope (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/first-mate/lib/grammar.js:324:34)
    at TextMateLanguageMode.tokenizedLineForRow (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-mate-language-mode.js:428:30)
    at TextMateHighlightIterator.seek (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-mate-language-mode.js:746:49)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:83:58)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at DisplayLayer.getScreenLine (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-layer.js:639:60)
    at TextEditor.screenLineForScreenRow (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor.js:1243:36)
    at TextEditorComponent.requestHorizontalMeasurement (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:2258:47)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:372:18)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:274:16)
    at TextEditorComponent.didShow (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:1457:18)
    at TextEditorComponent.didFocus (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:1481:35)
    at HTMLElement.addEventListener (/app.asar/src/text-editor-element.js:36:67)
    at HTMLElement.PaneElement.activeItemChanged (/app.asar/src/pane-element.js:170:25)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.24.0/resources/app/src/pane.js:435:26)
    at Pane.activateItem (~/AppData/Local/atom/app-1.24.0/resources/app/src/pane.js:575:18)
    at TabBarView.module.exports.TabBarView.onClick (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:721:25)
```

### Commands

```
     -1:10 intentions:highlight (input.hidden-input)
     -1:09.9.0 core:undo (input.hidden-input)
     -0:40.4.0 intentions:highlight (input.hidden-input)
  3x -0:40.2.0 core:undo (input.hidden-input)
  5x -0:39.5.0 core:redo (input.hidden-input)
     -0:07.1.0 intentions:highlight (input.hidden-input)
     -0:07.0 core:paste (input.hidden-input)
     -0:05.6.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
atom-monokai 0.10.9 
busy-signal 1.4.3 
dark-flat-ui 1.2.4 
file-icons 2.1.16 
go-debug 1.6.0 
go-plus 5.6.0 
go-signature-statusbar 1.2.3 
hyperclick 0.1.5 
intentions 1.1.5 
language-textile 0.2.0 
linter 2.2.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
monokai 0.24.0 
platformio-ide-terminal 2.8.0 
pristine-ui 1.1.11 
tasks 2.9.1 
```

**Comment by njakobsen** [comment]
Seems like this only happens to me when I open an html file that doesn't have a `<body>` node.

**Comment by njakobsen** [comment]
@yuhei159 I don't know that this should be closed. I have several HTML fragment files that serve as templates. I can't open them in atom without the workaround above, or by renaming them to `.txt` while I edit them. I think this is still a bug.

**Comment by Arcanemagus** [comment]
@njakobsen Since they have `tasks` installed, I'm assuming their issue is a duplicate of #16741 and should stay closed. If you _also_ have `tasks` installed updating to the latest version should fix this. If you _don't_ have `tasks` installed and can reproduce this issue please file a new issue with how the Atom team can reproduce it so it can be looked into.

**Comment by njakobsen** [comment]
@Arcanemagus I don't have tasks installed so I've filed https://github.com/atom/atom/issues/16820
