### ISSUE TITLE
Uncaught SyntaxError: file:///C:/Users/ivancica/.atom/packages/Hydrogen/lib/main.js: Unexpected t...

### ISSUE THREAD

**Issue by vidosrd1** [atom/atom#16783]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught SyntaxError: file:///C:/Users/ivancica/.atom/packages/Hydrogen/lib/main.js: Unexpected token (56:18)

```
At C:\Users\ivancica\AppData\Local\atom\app-1.23.3\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:671

SyntaxError: file:///C:/Users/ivancica/.atom/packages/Hydrogen/lib/main.js: Unexpected token (56:18)
[0m[32m}[39m from [31m"./utils"[39m[1m;[22m

[36mimport[39m type Kernel[1m;[22m from[1m;[22m [31m"./kernel"[39m[1m;[22m

[36mimport[39m exportNotebook from [31m"./export-notebook"[39m[1m;[22m
[0m
    at Parser.pp.raise (/app.asar/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/app.asar/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.expectContextual (/app.asar/node_modules/babylon/lib/parser/util.js:56:39)
    at Parser.pp.parseImport (/app.asar/node_modules/babylon/lib/parser/statement.js:797:10)
    at Parser.pp.parseStatement (/app.asar/node_modules/babylon/lib/parser/statement.js:115:65)
    at Parser.parseStatement (/app.asar/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseTopLevel (/app.asar/node_modules/babylon/lib/parser/statement.js:30:21)
    at Parser.parse (/app.asar/node_modules/babylon/lib/parser/index.js:70:17)
    at Object.parse (/app.asar/node_modules/babylon/lib/index.js:45:50)
    at Object.exports.default (/app.asar/node_modules/babel-core/lib/helpers/parse.js:36:18)
    at File.parse (/app.asar/node_modules/babel-core/lib/transformation/file/index.js:574:40)
    at File.parseCode (/app.asar/node_modules/babel-core/lib/transformation/file/index.js:691:20)
    at /app.asar/node_modules/babel-core/lib/transformation/pipeline.js:167:12
    at File.wrap (/app.asar/node_modules/babel-core/lib/transformation/file/index.js:639:16)
    at Pipeline.transform (/app.asar/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
    at Object.exports.compile (~/AppData/Local/atom/app-1.24.0/resources/app/src/babel.js:70:22)
    at Object.compile (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-transpilation-registry.js:79:33)
    at compileFileAtPath (~/AppData/Local/atom/app-1.24.0/resources/app/src/compile-cache.js:97:37)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.24.0/resources/app/src/compile-cache.js:238:26)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.24.0/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:782:33)
    at Package.activateConfig (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:267:16)
    at PackageDetailView.activateConfig (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-detail-view.js:279:25)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-detail-view.js:213:18)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-detail-view.js:225:20)
```

### Commands

```
```

### Non-Core Packages

```
Hydrogen 2.2.2 
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [Hydrogen](https://atom.io/packages/Hydrogen) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
