### ISSUE TITLE
Uncaught Error: Tried to unload active package 'linter'

### ISSUE THREAD

**Issue by kenigbolo** [atom/atom#16795]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Tried to unload active package 'linter'

```
At /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:630

Error: Tried to unload active package 'linter'
    at PackageManager.unloadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:630:19)
    at PackageManager.module.exports.PackageManager.unload (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:502:36)
    at PackageManager.module.exports.PackageManager.install (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:512:18)
    at PackageCard.install (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:824:33)
    at HTMLButtonElement.installButtonClickHandler (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:302:22)
```

### Commands

```
     -1:32 core:confirm (input.hidden-input)
  2x -1:30.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
jslint 1.5.1 
linter 2.0.0 
linter-csslint 2.0.0 
linter-eslint 8.4.1 
linter-ui-default 1.6.10 
```

**Comment by rsese** [comment]
Thanks for the report - looks like https://github.com/atom/atom/issues/16795 so we'll go ahead and close as a duplicate for now - if you can share what you were doing when you saw the error and if it's reproducible, please let us know in https://github.com/atom/atom/issues/16795.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by rsese** [comment]
> looks like #16795

Sorry meant https://github.com/atom/atom/issues/16793.
