### ISSUE TITLE
Uncaught Error: Tried to unload active package 'julia-client'

### ISSUE THREAD

**Issue by coolestname** [atom/atom#16793]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Tried to unload active package 'julia-client'

```
At C:\Users\jeguti29\AppData\Local\atom\app-1.24.0\resources\app\src\package-manager.js:630

Error: Tried to unload active package 'julia-client'
    at PackageManager.unloadPackage (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:630:19)
    at PackageManager.module.exports.PackageManager.unload (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-manager.js:502:36)
    at PackageManager.module.exports.PackageManager.install (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-manager.js:512:18)
    at PackageCard.install (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-card.js:824:33)
    at HTMLButtonElement.installButtonClickHandler (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-card.js:302:22)
```

### Commands

```
  3x -3:08.9.0 core:backspace (input.hidden-input)
     -3:02.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
indent-detective 0.2.0 
ink 0.8.2 
julia-client 0.6.8 
language-julia 0.15.0 
latex-completions 0.3.3 
tool-bar 1.1.6 
uber-juno 0.1.2 
```

**Comment by rsese** [comment]
Thanks for the report - do you remember what you were you doing at the time of the error?  Also, is the error reproducible?

**Comment by lee-dohm** [comment]
Thanks for contributing!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/16793#issuecomment-367123012. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by CBongiova** [comment]
Hello, 

I got the same error while initialising Atom (after trying to download the uber-juno package). 
<img width="463" alt="screen shot 2018-04-04 at 10 33 41" src="https://user-images.githubusercontent.com/24223801/38297117-b5909d48-37f3-11e8-83b3-9b1f5f8c6231.png">
Is there any solution for this bug?

**Comment by lee-dohm** [comment]
@CBongiova I'm not even sure this is a bug in Atom. Please open a new issue and fill in all of the information in the issue template so that we can get a full picture of what is happening here.
