### ISSUE TITLE
Uncaught TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by trackoverxc** [atom/atom#16815]
[Enter steps to reproduce:]

1. Have 3 files open in atom
2. Open OneNote
3. Move OneNote to toolbar view
4. Use windows key + arrow key to resize Atom window to the remaining right half of the screen (portion of which is now taken by OneNote)
5. Receive endless stream of this error

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At C:\Users\drose\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor-component.js:2246

TypeError: Cannot read property 'element' of undefined
    at TextEditorComponent.measureLongestLineWidth (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:2246:63)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:399:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:278:20)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.24.0/resources/app/src/view-registry.js:245:13)
```

### Commands

```
  2x -3:12.1.0 core:backspace (input.hidden-input)
  2x -2:47.6.0 core:move-right (input.hidden-input)
     -2:47 editor:newline (input.hidden-input)
  2x -2:45.7.0 core:backspace (input.hidden-input)
     -2:44.8.0 core:move-right (input.hidden-input)
     -2:44.6.0 editor:newline (input.hidden-input)
     -2:35.6.0 core:move-right (input.hidden-input)
  2x -2:34.8.0 editor:newline (input.hidden-input)
     -2:34.1.0 snippets:previous-tab-stop (input.hidden-input)
     -2:34.1.0 editor:outdent-selected-rows (input.hidden-input)
     -2:27.4.0 editor:newline (input.hidden-input)
  5x -2:23 core:backspace (input.hidden-input)
     -2:17.7.0 editor:newline (input.hidden-input)
  2x -2:15.2.0 core:backspace (input.hidden-input)
     -2:07.1.0 editor:newline (input.hidden-input)
     -2:00.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
browser-plus 0.0.98 
Hydrogen 2.2.2 
kite 0.61.0 
open-in-browser 0.5.2 
teletype 0.7.0 
```

**Comment by trackoverxc** [comment]
Found duplicate issues

**Comment by Arcanemagus** [comment]
For reference: From the stack trace this is a duplicate of https://github.com/atom/atom/issues/16307.
