### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 192.102.224.14...

### ISSUE THREAD

**Issue by IBRAHIMDANS** [atom/atom#16818]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Debian GNU/Linux
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 192.102.224.14:3128

```
At stream.js:74

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 192.102.224.14:3128
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -5:08.8.0 tabs:close-tab (div.title)
     -5:05.5.0 pane:close (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:53.2.0 command-palette:toggle (div.tool-panel.tree-view)
     -4:50 application:about (div.tool-panel.tree-view)
     -4:45.9.0 core:select-all (input.hidden-input)
     -4:24.2.0 package-generator:generate-package (input.hidden-input)
     -4:21.9.0 core:confirm (input.hidden-input)
     -4:20.8.0 editor:newline (input.hidden-input)
     -4:14.5.0 core:undo (input.hidden-input)
     -4:08.4.0 editor:select-line (input.hidden-input)
     -3:52.3.0 window:run-package-specs (input.hidden-input)
     -3:32.6.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -2:36.2.0 core:backspace (input.hidden-input)
  2x -2:36 core:confirm (input.hidden-input)
     -1:56.8.0 core:backspace (input.hidden-input)
     -0:56.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
console-panel 0.3.0 
french-menu 0.2.2 
my-package 0.0.0 
```

**Comment by rsese** [comment]
Thanks for the report - based on the error, this is likely a temporary issue with your internet connection. Please try again later and see if it works.
