### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.repl...

### ISSUE THREAD

**Issue by mfcava** [atom/atom#16816]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.reply.it proxy.reply.it:8080

```
At stream.js:74

Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.reply.it proxy.reply.it:8080
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1025:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -2:24 core:save (input.hidden-input)
  2x -1:55.1.0 core:backspace (input.hidden-input)
  2x -1:53.9.0 core:confirm (input.hidden-input)
  2x -1:47.8.0 core:backspace (input.hidden-input)
  2x -1:46.9.0 core:confirm (input.hidden-input)
  2x -0:53.6.0 core:backspace (input.hidden-input)
  2x -0:52.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-jade 0.3.0 
busy-signal 1.4.3 
intentions 1.1.5 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-js-standard 4.2.0 
linter-jsonlint 1.3.0 
linter-ui-default 1.6.10 
pigments 0.40.2 
project-manager 3.3.5 
```

**Comment by rsese** [comment]
Thanks for the report - the error seems like a networking/DNS issue rather than an issue with Atom so we'll go ahead and close the issue. 

Is the error reproducible for you?
