### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, scandir 'C:/WINDOWS\system32\tasks'

### ISSUE THREAD

**Issue by Itz-Mattmatt** [atom/atom#16829]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM: operation not permitted, scandir 'C:\WINDOWS\system32\tasks'

```
At fs.js:871

Error: EPERM: operation not permitted, scandir 'C:\WINDOWS\system32\tasks'
    at Object.fs.readdirSync (fs.js:871:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:576:28)
    at Proxy.listSync (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/fs-plus/lib/fs-plus.js:190:30)
    at PackageDetailView.updateFileButtons (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-detail-view.js:603:51)
    at PackageDetailView.updateInstalledState (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-detail-view.js:484:18)
    at PackageDetailView.populate (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-detail-view.js:454:18)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-detail-view.js:214:18)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-detail-view.js:225:20)
    at new PackageDetailView (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-detail-view.js:100:16)
    at callback (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/settings-view.js:366:26)
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/settings-view.js:371:25)
    at SettingsView.showPanel (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/settings-view.js:429:30)
    at HTMLDivElement.clickHandler (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-card.js:285:39)
```

### Commands

```
  9x -4:38.5.0 core:backspace (input.hidden-input)
     -4:21 editor:newline (input.hidden-input)
  5x -4:15.7.0 core:backspace (input.hidden-input)
     -4:09.6.0 editor:newline (input.hidden-input)
     -4:02.6.0 snippets:next-tab-stop (input.hidden-input)
     -4:02.6.0 snippets:expand (input.hidden-input)
     -4:02.6.0 editor:indent (input.hidden-input)
 39x -3:59.3.0 core:backspace (input.hidden-input)
     -3:36.3.0 editor:newline (input.hidden-input)
     -3:35.1.0 core:backspace (input.hidden-input)
     -2:26.4.0 core:confirm (input.hidden-input)
     -0:49.6.0 core:select-all (input.hidden-input)
     -0:37.3.0 editor:newline-below (input.hidden-input)
  4x -0:34.7.0 core:backspace (input.hidden-input)
     -0:33.1.0 core:save (input.hidden-input)
     -0:15 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.5 
tasks undefined 
```

**Comment by Arcanemagus** [comment]
This looks like it might be an issue with the `tasks` package, which seems to have some issues in your installation as the version couldn't be determined. You might try re-installing it.

**Comment by rsese** [comment]
> This looks like it might be an issue with the tasks package, which seems to have some issues in your installation as the version couldn't be determined. You might try re-installing it.

:+1:

We'll go ahead and close for now but if reinstalling doesn't help let us know.
