### ISSUE TITLE
Atom v1.25.0-beta0 requires $USER environment variable

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#16821]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It seems that Atom now _requires_ the `USER` environment variable to be specified as of Atom v1.25.0-beta0, causing _all_ builds on CircleCI to fail since it runs commands in a non-`login` shell ([ref](https://circleci.com/docs/2.0/configuration-reference/#default-shell-options)).

### Steps to Reproduce

1. `unset USER` to simulate a non-`login` shell
2. Attempt to run specs for a package, or anything else that would initialize an Atom window
2. Whatch it lock up

_Note: It seems that `--version` doesn't initialize the Atom application fully, so you need to do something more complex such as attempting to run specs._

**Expected behavior:**

Atom handles the missing `USER` environment variable.

```ShellSession
> docker run --rm -it arcanemagus/atom-docker-ci:v1.24.0 bash
atom@9eaf72f92636:~$ ${ATOM_SCRIPT_PATH} --version
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
atom@9eaf72f92636:~$ git clone https://github.com/AtomLinter/linter-docker.git
Cloning into 'linter-docker'...
remote: Counting objects: 210, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 210 (delta 12), reused 0 (delta 0), pack-reused 195
Receiving objects: 100% (210/210), 43.81 KiB | 0 bytes/s, done.
Resolving deltas: 100% (101/101), done.
Checking connectivity... done.
atom@9eaf72f92636:~$ cd linter-docker
atom@9eaf72f92636:~/linter-docker$ ${APM_SCRIPT_PATH} install
Installing modules ✓
atom@9eaf72f92636:~/linter-docker$ ${ATOM_SCRIPT_PATH} --test spec
.......

Finished in 1.545 seconds
7 tests, 23 assertions, 0 failures, 0 skipped

atom@9eaf72f92636:~/linter-docker$
```

_Note: I'm using a Docker image, and `linter-docker` (purely a coincidence), to demonstrate this, but any non-`login` shell _should_ show this issue._

**Actual behavior:**

Atom locks up 
```ShellSession
> docker run --rm -it arcanemagus/atom-docker-ci:v1.25.0-beta2 bash
atom@eadb6a239320:~$ ${ATOM_SCRIPT_PATH} --version
Atom    : 1.25.0-beta2
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
atom@eadb6a239320:~$ git clone https://github.com/AtomLinter/linter-docker.git
Cloning into 'linter-docker'...
remote: Counting objects: 210, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 210 (delta 12), reused 0 (delta 0), pack-reused 195
Receiving objects: 100% (210/210), 43.81 KiB | 0 bytes/s, done.
Resolving deltas: 100% (101/101), done.
Checking connectivity... done.
atom@eadb6a239320:~$ cd linter-docker
atom@eadb6a239320:~/linter-docker$ ${APM_SCRIPT_PATH} install
Installing modules ✓
atom@eadb6a239320:~/linter-docker$ ${ATOM_SCRIPT_PATH} --test spec
Data must be a string or a buffer
TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:74:16)
    at Function.open (/usr/share/atom-beta/resources/app.asar/src/main-process/atom-application.js:47:10)
    at App.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/main-process/start.js:81:21)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
^Catom@eadb6a239320:~/linter-docker$
atom@eadb6a239320:~/linter-docker$
```

**Reproduces how often:**

100% of the time.

### Versions

See above, this started with the following version though:
```
Atom    : 1.25.0-beta0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

### Additional Information

This was introduced during the Decaffeinate process in https://github.com/atom/atom/pull/16495 (@maxbrunsfeld), and is caused by `username` being `undefined` here:
https://github.com/atom/atom/blob/fa9c8d1aceb813af6a0100648bdd650f67be0c56/src/main-process/atom-application.js#L47

Failing builds:
* [linter-docker](https://circleci.com/gh/AtomLinter/linter-docker/103): "Regular" build using `atom/ci` script on CircleCI's Docker images
* [atom-minimap-linter](https://circleci.com/gh/AtomLinter/atom-minimap-linter/171): Using the same Docker image as above

**Comment by maxbrunsfeld** [comment]
> This was introduced during the Decaffeinate process in #16495

I believe it was actually introduced in #16458, which began using a hash of the username in the socket file path.
