### ISSUE TITLE
Atom and Apm commands not being initialized by script/build --install

### ISSUE THREAD

**Issue by CaptainJohnyAppleSeed** [atom/atom#16853]
**Description**
The build process on Linux for atom v1.26.0-dev is terminating prematurely due to a permissions error:
```
Error: EACCES: permission denied, mkdir '/usr/share/icons/hicolor/1024x1024'
```
This results in the commands apm and atom not being created.

**Steps to Reproduce**
Follow the following instructions for making a clean Linux build
We used a clean Linux Virtual Box (Ubuntu 16.04.3)
```
$wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
--reopen terminal
$nvm install v8.9.0
$npm install -g npm
$npm config set python /usr/bin/python2 –g
$sudo apt-get install build-essential git libsecret-1-dev fakeroot rpm libx11-dev libxkbfile-dev
$git clone https://github.com/odoyle71/atom.git
$cd atom
$script/bootstrap
$script/clean
$script/build --install ~
```

**Expected behavior:** 
The build completes with the following terminal messages:
```
Installing "atom-1.26.0-dev-75ba994-amd64" at "/home/atom/share/atom-dev"
Installing icons at "/usr/share/icons/hicolor"
Updating icon cache for "/usr/share/icons/hicolor"
gtk-update-icon-cache: Cache file created successfully.
Writing desktop entry file at "/home/atom/share/applications/atom-dev.desktop"
Copying atom.sh to "/home/atom/bin/atom-dev"
Symlinking apm to "/home/atom/bin/apm-dev"
Changing permissions to 755 for "/home/atom/share/atom-dev"
```

**Actual behavior:** 
The build terminates with the following terminal messages:
```
Installing "atom-1.26.0-dev-75ba994-amd64" at "/home/atom/share/atom-dev"
Installing icons at "/usr/share/icons/hicolor"
Error: EACCES: permission denied, mkdir '/usr/share/icons/hicolor/1024x1024'
     at Object.fs.mkdirSync (fs.js:885:18)
     at mkdirsSync (/home/atom/atom/script/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:29:9)
     at Object.mkdirsSync (/home/atom/atom/script/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:35:16)
     at Object.copySync (/home/atom/atom/script/node_modules/fs-extra/lib/copy-sync/copy-sync.js:31:36)
     at fs.readdirSync.forEach.imageName (/home/atom/atom/script/lib/install-application.js:103:14)
     at Array.forEach (<anonymous>:null:null)
     at module.exports (/home/atom/atom/script/lib/install-application.js:99:36)
     at binariesPromise.then.then.then.then.packagedAppPath (/home/atom/atom/script/build:132:7)
     at <anonymous>:null:null
```

**Reproduces how often:** 100% of the time

**Versions**
```
atom@atom-VirtualBox:~$ atom-dev -v
Atom    : 1.26.0-dev-75ba994
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
atom@atom-VirtualBox:~$ apm-dev -v
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0-dev-75ba994
python 2.7.12
git 2.7.4
```

**Additional Information**
This issue has to do with the fact that the installer is trying to copy icons into the `/usr/share/icons/hicolor` directory. The installer runs with user privilleges, but modifications to this directory requires root privilleges. 

This issue is a result of code added to install-application.js in PR [15498](https://github.com/atom/atom/pull/15498)

The error has to do with the following code in `atom/script/lib/install-application.js`:
```
const baseIconThemeDirPath = findBaseIconThemeDirPath()
const fullIconName = atomExecutableName + '.png'
let existingIconsFound = false
fs.readdirSync(baseIconThemeDirPath).forEach(size => {
     const iconPath = path.join(baseIconThemeDirPath, size, 'apps', fullIconName)
     if (fs.existsSync(iconPath)) {
          if (!existingIconsFound) {
               console.log(`Removing existing icons from "${baseIconThemeDirPath}"`)
          }
          existingIconsFound = true
          fs.removeSync(iconPath)
     }
})
```
Since `baseIconThemeDirPath` is set by the following
```
function findBaseIconThemeDirPath () {
     const defaultBaseIconThemeDir = '/usr/share/icons/hicolor'
     const dataDirsString = process.env.XDG_DATA_DIRS
     if (dataDirsString) {
          const dataDirs = dataDirsString.split(path.delimiter)
          if (dataDirs.includes('/usr/share/') || dataDirs.includes('/usr/share')) {
               return defaultBaseIconThemeDir
          } else {
               return path.join(dataDirs[0], 'icons', 'hicolor')
          }
     } else {
          return defaultBaseIconThemeDir
     }
}
```
In particular, since our  `$XDG_DATA_DIRS` is:
```
 /usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
```
A  workaround suggested by Spotter (Slack name) which was to change `$XDR_DATA_DIRS` to `~/local/share`. However, this will mess up other applications using this environment variable.

**Comment by CaptainJohnyAppleSeed** [comment]
I also noticed the following [PR 16528](https://github.com/atom/atom/pull/16528), where @MoritzKn  and @daviwil were discussing the creation of `script/install` and its elevation to `sudo`.

**Comment by MoritzKn** [comment]
I think this was already a problem before #15498 since install also copies the binaries to `/usr/local/bin`. However #14848 should indeed fix this.

**Comment by CaptainJohnyAppleSeed** [comment]
Interesting, I never had an issue with `/usr/local/bin` in v1.24.0-Stable back in December, had the change not gone to the atom/atom master by then?

**Comment by MoritzKn** [comment]
The PR was only meged at the 10th January

**Comment by lee-dohm** [comment]
@daviwil Can you take a look here?

**Comment by RJVB** [comment]
> script/install and its elevation to sudo, and that may solve this issue...

Only if the files in question have to the path in question. That is not the case for instance when installing to a "destroot" (see #17584) and/or to a different $prefix (FreeBSD comes to mind which would probably want to put everything under /usr/local)

**Comment by Natronium** [comment]
> However #16528 should indeed fix this.

Unfortunately, elevating to root seems more like a "fix by accident", which also isn't really a fix, as RJVB pointed out. The solution for this issue seems like it'd be to install the icons under the prefix, as is already done with the `.desktop` shortcut

Ignoring the now-unused `findBaseIconThemeDirPath` function, this would be a one line change:
```diff
diff --git a/script/lib/install-application.js b/script/lib/install-application.js
index 8a29372cd..fbaf9e099 100644
--- a/script/lib/install-application.js
+++ b/script/lib/install-application.js
@@ -79,7 +79,7 @@ module.exports = function (packagedAppPath, installDir) {
     install(installationDirPath, packagedAppFileName, packagedAppPath)
 
     { // Install icons
-      const baseIconThemeDirPath = findBaseIconThemeDirPath()
+      const baseIconThemeDirPath = path.join(applicationsDirPath, 'share/icons/hicolor/')
       const fullIconName = atomExecutableName + '.png'
 
       let existingIconsFound = false
```
