### ISSUE TITLE
Uncaught Error: The module '/Applications/Atom Beta.app/Contents/Resources/app.asar.unpacked/node...

### ISSUE THREAD

**Issue by jbrooksuk** [atom/atom#16866]
1. I upgraded packages
2. Start typing

**Atom**: 1.24.0-beta3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The module '/Applications/Atom Beta.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

```
At ELECTRON_ASAR.js:173

Error: The module '/Applications/Atom Beta.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:19.2.0 core:close (div.panels-item)
     -0:05.1.0 core:copy (input.hidden-input)
     -0:03.5.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
aligner-php 1.2.0 
atom-ide-ui 0.9.2 
php-namespace-monkey 0.1.0 
calamity-syntax 1.2.3 
docblockr 0.13.7 
ide-json 0.2.1 
ide-php 0.7.7 
ide-vue 0.1.8 
language-blade 0.38.0 
language-vue 0.23.1 
project-manager 3.3.5 
sort-lines 0.18.0 
teletype 0.9.0 
```

**Comment by rsese** [comment]
Thanks for the report @jbrooksuk - can you try reinstalling and see if that clears things up?

**Comment by toby-griffiths** [comment]
This bug appeared for me this morning, but it's gone away after updating the nuclide package and re-starting.  Not sure if they're related, but thought I'd share.

**Comment by Awilum** [comment]
The same issue I have today

**Comment by jbrooksuk** [comment]
Sorry, I've not had chance to try this again.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/16866#issuecomment-369745860. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
