### ISSUE TITLE
Uncaught Error: Tried to unload active package 'highlight-selected'

### ISSUE THREAD

**Issue by karlwbaker** [atom/atom#16873]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Tried to unload active package 'highlight-selected'

```
At C:\Users\karls\AppData\Local\atom\app-1.24.0\resources\app\src\package-manager.js:630

Error: Tried to unload active package 'highlight-selected'
    at PackageManager.unloadPackage (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:630:19)
    at PackageManager.module.exports.PackageManager.unload (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-manager.js:502:36)
    at PackageManager.module.exports.PackageManager.install (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-manager.js:512:18)
    at PackageCard.install (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-card.js:824:33)
    at HTMLButtonElement.installButtonClickHandler (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/settings-view/lib/package-card.js:302:22)
```

### Commands

```
 17x -3:44.2.0 core:backspace (input.hidden-input)
     -3:41.7.0 core:confirm (input.hidden-input)
     -2:37.5.0 core:select-all (input.hidden-input)
     -2:37.1.0 core:paste (input.hidden-input)
     -2:36 core:confirm (input.hidden-input)
     -1:42.2.0 core:select-all (input.hidden-input)
     -1:41.8.0 core:paste (input.hidden-input)
     -1:40.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.0 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
file-icons 2.1.17 
git-plus 7.10.0 
highlight-selected 0.13.1 
Hydrogen 2.2.3 
intentions 1.1.5 
k-b-word-count 0.0.0 
kite 0.70.0 
linter 2.2.0 
linter-ui-default 1.7.0 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
python-autopep8 0.1.3 
python-isort 0.0.7 
script 3.17.3 
```

**Comment by rsese** [comment]
Thanks for the report - do you remember what you were you doing at the time of the error? Also, is the error reproducible?

x-ref: https://github.com/atom/atom/issues/16793, https://github.com/atom/atom/issues/16795

**Comment by rsese** [comment]
Going to re-open for now since folks are still hitting thee error and all the dupes have been linked back here.

**Comment by rsese** [comment]
Re-opening again, still getting recent reports though looks like it's not reproducible so far.

**Comment by rsese** [comment]
From https://github.com/atom/atom/issues/18564#issuecomment-446178302:

> Hi! The issue showed up when installing one of the Julia packages of JunoLab (either uber-juno or julia-client, don't recall which one exactly). ink was a dependent package, so it tried to install it as part of the JunoLab package. Then, it failed to install correctly. But what I did right after I got the issue was to uninstall atom and reinstall it again. Then, I installed ink package first (this time it was installed ok) and then all the JunoLab packages I needed. Everything is now working perfectly.
