### ISSUE TITLE
Failed to activate the atom-beautify package

### ISSUE THREAD

**Issue by musiyenko** [atom/atom#16880]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.8.2
**OS**: linux 4.15.6-1-ARCH
**Thrown From**: [atom-beautify](ssh://git@github.com/Glavin001/atom-beautify) package 0.32.0

### Stack Trace

Failed to activate the atom-beautify package

```
At l19 is not defined

ReferenceError: l19 is not defined
    at /packages/beautify/src/languages/xtemplate.coffee:1:1)
    at /packages/beautify/src/languages/xtemplate.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/atom-beautify/src/languages/index.coffee:102:7
    at arrayMap (/packages/atom-beautify/node_modules/lodash/lodash.js:631:23)
    at Function.map (/packages/atom-beautify/node_modules/lodash/lodash.js:9546:14)
    at /packages/atom-beautify/src/languages/index.coffee:101:20)
    at /packages/atom-beautify/src/beautifiers/index.coffee:109:15
    at /packages/atom-beautify/src/beautifiers/index.coffee:678:16)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/atom-beautify/src/beautify.coffee:9:15)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Package.requireMainModule (/usr/lib/atom/src/package.js:777:27)
    at Package.activateNow (/usr/lib/atom/src/package.js:215:34)
    at activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/usr/lib/atom/src/package.js:896:75)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at triggeredActivationHooks.forEach.hook (/usr/lib/atom/src/package-manager.js:694:80)
    at Set.forEach (native)
    at PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:694:37)
    at /usr/lib/atom/node_modules/settings-view/lib/package-manager.js:521:29
    at exit (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:114:16)
    at triggerExitCallback (/usr/lib/atom/src/buffered-process.js:322:11)
    at /usr/lib/atom/src/buffered-process.js:343:11
    at Socket.<anonymous> (/usr/lib/atom/src/buffered-process.js:204:9)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
```

### Commands

```
  4x -2:20.9.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -2:01.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.0 
autocomplete-html-entities 0.2.0 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.17 
git-plus 7.10.0 
git-time-machine 1.5.9 
goto-definition 1.3.4 
gulp-control 0.5.0 
highlight-selected 0.13.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
linter 2.2.0 
linter-csslint 2.0.0 
linter-gcc 0.7.1 
linter-htmlhint 1.4.0 
linter-jshint 3.1.6 
linter-php 1.5.1 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
open-recent 5.0.0 
pigments 0.40.2 
remote-edit 1.9.0 
svg-preview 0.12.1 
sync-settings 0.8.5 
todo-show 2.2.0 
w3c-validation 0.4.0 
webbox-color 0.5.9 
```

**Comment by Arcanemagus** [comment]
I would first try re-installing the package, if that doesn't fix this though you should file this on the [atom-beautify](https://github.com/Glavin001/atom-beautify/issues) package.

**Comment by musiyenko** [comment]
Thank you, I was able to [fix it.](https://github.com/Glavin001/atom-beautify/issues/2067)
