### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of null

### ISSUE THREAD

**Issue by joshvera** [atom/atom#16898]
[Enter steps to reproduce:]

1. Start a project search in a very large repository.
2. Start another project search while that project search is running.

**Atom**: 1.25.0-beta2 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of null

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:101

TypeError: Cannot read property 'getSelectedBufferRange' of null
    at BufferSearch.search (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:101:76)
    at FindView.liveSearch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:356:31)
    at findEditor.onDidStopChanging (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:291:56)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1773:26)
    at later (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -0:25.4.0 core:copy (input.hidden-input)
     -0:25.1.0 project-find:show (input.hidden-input)
     -0:24.8.0 core:paste (input.hidden-input)
     -0:24.3.0 core:confirm (input.hidden-input)
     -0:21 core:copy (input.hidden-input)
     -0:20.7.0 project-find:show (input.hidden-input)
     -0:20.6.0 core:paste (input.hidden-input)
     -0:20.3.0 core:confirm (input.hidden-input)
     -0:14.7.0 core:copy (input.hidden-input)
     -0:14.4.0 project-find:show (input.hidden-input)
     -0:14.2.0 core:paste (input.hidden-input)
     -0:13.9.0 core:confirm (input.hidden-input)
     -0:07.1.0 core:copy (input.hidden-input)
     -0:06.8.0 find-and-replace:show (input.hidden-input)
     -0:06.6.0 core:paste (input.hidden-input)
     -0:06.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

This happens in safe mode.

**Comment by rsese** [comment]
This issue was moved to atom/find-and-replace#998

**Comment by fatg3erman** [comment]
I'm getting this too, I don't even need to do two searches, just one and it throws it every time.

[Enter steps to reproduce:]

1. cmd-shift-f
2. type something to search for
3. hit Enter

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core


```
### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:101

TypeError: Cannot read property 'getSelectedBufferRange' of null
    at BufferSearch.search (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:101:76)
    at FindView.liveSearch (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:356:31)
    at findEditor.onDidStopChanging (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:291:56)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1817:26)
    at later (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -2:36.9.0 snippets:expand (input.hidden-input)
     -2:36.9.0 editor:indent (input.hidden-input)
     -2:26 core:backspace (input.hidden-input)
     -2:13.5.0 editor:newline (input.hidden-input)
 23x -2:11 core:backspace (input.hidden-input)
     -2:02.7.0 editor:newline (input.hidden-input)
     -1:48.1.0 core:move-up (input.hidden-input)
  2x -1:47.8.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -1:47.2.0 core:select-down (input.hidden-input)
     -1:46.3.0 core:copy (input.hidden-input)
     -1:43.9.0 editor:newline (input.hidden-input)
     -1:43.7.0 core:paste (input.hidden-input)
     -1:42.2.0 window:save-all (input.hidden-input)
     -1:24.8.0 project-find:show (input.hidden-input)
     -1:18.8.0 core:confirm (input.hidden-input)
     -0:02.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
bobalophagus-syntax 0.1.0 
hey-pane 1.1.0 
revert-buffer 0.6.0 
```


```

**Comment by sunnysideup** [comment]
+1

**Comment by davidgross** [comment]
I'm getting this on every search. Every time. Both global and file-specific searches.

```
$ atom -v
Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by kharthigeyan** [comment]
+1 

Atom    : 1.33.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by jamieorc** [comment]
**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.2
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of null

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Cannot read property 'getSelectedBufferRange' of null
    at BufferSearch.search (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:724388)
    at FindView.liveSearch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:744367)
    at findEditor.onDidStopChanging (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:740297)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1173759)
    at TextBuffer.emitDidStopChangingEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:504567)
    at later (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:98353)
```

### Commands

```
     -2:46.6.0 core:save (input.hidden-input)
  2x -2:09.8.0 editor:toggle-line-comments (input.hidden-input)
     -2:07.6.0 core:save (input.hidden-input)
  5x -2:01.1.0 editor:delete-line (input.hidden-input)
     -1:59.5.0 core:save (input.hidden-input)
  5x -1:54.6.0 core:undo (input.hidden-input)
  6x -0:53.2.0 core:backspace (input.hidden-input)
     -0:48.6.0 editor:newline (input.hidden-input)
     -0:40.1.0 core:save (input.hidden-input)
     -0:36.8.0 find-and-replace:use-selection-as-find-pattern (input.hidden-input)
     -0:36.2.0 project-find:show (input.hidden-input)
     -0:34.5.0 find-and-replace:focus-next (input.hidden-input)
     -0:34.1.0 core:backspace (input.hidden-input)
     -0:31.3.0 core:confirm (input.hidden-input)
     -0:22.6.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:21.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-ruby 1.7.0 
aligner-scss 1.3.1 
atom-backbone 0.6.1 
atom-beautify 0.33.4 
atom-coda 0.3.0 
atom-ctags 5.1.2 
atom-elixir 0.2.3 
atom-everydayrails-rspec 0.5.0 
atom-html-preview 0.2.6 
atom-light-ui-slim 0.25.1 
atomic-ui 1.5.2 
autocomplete-erlang 1.1.2 
base16-ocean-light-syntax 0.3.0 
borealis-syntax 0.6.0 
center-line 1.4.0 
clipboard-plus 0.5.1 
demo-package 0.0.0 
elementary-light-ui 0.26.2 
elixir-cmd 0.2.9 
elixir-pry 1.0.0 
erb-snippets 1.1.0 
file-watcher 2.0.0 
foobar 0.0.0 
github-2014 3.17.0 
github-atom-light-syntax 0.5.0 
github-web 1.1.0 
gl-light-syntax 3.0.0 
goto-definition 1.3.4 
highlight-selected 0.14.0 
iex 0.10.0 
ink 0.9.14 
language-diff 0.7.0 
language-elixir 0.22.1 
language-erlang 3.2.0 
language-haml 0.32.1 
language-markdown 0.29.0 
language-rspec 0.12.1 
language-vue 0.24.0 
language-vue-component 0.5.0 
lipsum 0.1.0 
lisp-paredit 0.6.0 
mac-classic 0.5.0 
mac-github-syntax 1.3.9 
octocat-syntax 2.2.7 
one-light-ui-adwaita 0.10.1 
open-git-modified-files 0.2.4 
open-recent 5.0.0 
parinfer 1.23.0 
piatto-light 2.0.2 
pigments 0.40.2 
platformio-ide-terminal 2.9.0 
pretty-json 2.0.3 
print-code 0.7.1 
project-manager 3.3.6 
proto-repl 1.4.24 
proto-repl-charts 0.4.1 
proton-framer 0.11.0 
quiet-light-atom 1.5.0 
rad-syntax 0.4.0 
rails-snippets 2.21.0 
rails-transporter 1.7.1 
recent-files-fuzzy-finder 0.6.1 
remember-file-positions 0.2.3 
ruby-block 0.3.6 
ruby-block-converter 4.1.1 
ruby-test 1.0.2 
ruby-test-switcher 1.2.3 
serious-business 0.4.0 
set-syntax 0.4.0 
single-click-open 0.2.2 
split-diff 1.6.0 
todo-show 2.3.2 
toggle-quotes 1.1.3 
tomorrow 1.0.0 
tool-bar 1.1.11 
```

**Comment by jdahiyajd** [comment]
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
![screenshot 2019-02-16 at 12 16 59 pm](https://user-images.githubusercontent.com/20186345/52895770-e1140180-31e4-11e9-9aa2-ab4949d3646b.png)

Every time I search I found this issue 
I dont know the functionality SO just a Heads Up

**Comment by kharthigeyan** [comment]
+1

**Comment by jm3** [comment]
[Enter steps to reproduce:]

1. Search in project
2. Click into search field

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of null

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Cannot read property 'getSelectedBufferRange' of null
    at BufferSearch.search (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:747025)
    at FindView.liveSearch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:767247)
    at findEditor.onDidStopChanging (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:762966)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1206583)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1208024)
    at TextBuffer.emitDidStopChangingEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:503304)
    at later (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:99017)
```

### Commands

```
     -1:39.5.0 editor:newline (input.hidden-input)
     -1:39.3.0 core:paste (input.hidden-input)
     -1:38.8.0 editor:newline (input.hidden-input)
     -1:38 core:save (input.hidden-input)
     -1:37.3.0 core:move-up (input.hidden-input)
     -1:37 editor:move-to-end-of-screen-line (input.hidden-input)
  8x -1:36.6.0 core:select-up (input.hidden-input)
     -1:35.3.0 editor:select-to-first-character-of-line (input.hidden-input)
     -1:34.8.0 editor:toggle-line-comments (input.hidden-input)
  2x -1:34.3.0 core:save (input.hidden-input)
     -0:46.5.0 editor:newline (input.hidden-input)
  2x -0:44.5.0 core:backspace (input.hidden-input)
     -0:42.9.0 editor:newline (input.hidden-input)
  2x -0:39.3.0 core:save (input.hidden-input)
     -0:24.4.0 project-find:show-in-current-directory (span.name.icon.icon-file-directory)
     -0:22.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
busy-signal 2.0.0 
compare-files 0.8.1 
date 2.6.0 
html-entitize 1.1.0 
intentions 1.1.5 
linter 2.0.0 
linter-rubocop 2.2.3 
linter-ui-default 1.7.1 
open-recent 5.0.0 
pigments 0.40.2 
sort-lines 0.18.0 
Sublime-Style-Column-Selection 1.7.5 
Wild-Cherry 0.10.0 
```
