### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by HaullingLlama** [atom/atom#16946]
[Enter steps to reproduce:]

1. I restarted Atom after installing the atom-beautify package
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80

```
At stream.js:74

Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.2 
auto-update-packages 1.0.1 
better-git-blame 0.4.0 
busy-signal 1.4.3 
file-icons 2.1.17 
git-blame 1.6.0 
git-plus 7.10.0 
git-time-machine 1.5.9 
gitlab 0.1.3-7 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-scss-lint 3.1.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
open-recent 5.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.0 
split-diff 1.5.2 
```

**Comment by InsertPunHere1** [comment]
lmao

**Comment by lee-dohm** [comment]
@InsertPunHere1 your comment was deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory.

**Comment by HaullingLlama** [comment]
It only happened the one time. It just seemed like an odd thing to happen.

**Comment by rsese** [comment]
Yeah it could have just been a temporary network issue - thanks for confirming it happened the one time only.  We'll go ahead and close since it's not a reproducible issue.
