### ISSUE TITLE
Git tab and github tabs no longer open

### ISSUE THREAD

**Issue by happycollision** [atom/atom#16962]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On both Windows and macOS, the Git Tab and the Github Tab are no longer opening. I have been expecting to find an issue with this bug, but I can't. So I am assuming that not very many people are affected by it. This is of particular note because I am experiencing it on both my Windows machine at work and my Mac at home.

### Steps to Reproduce

1. Open Atom in Safe Mode
2. Invoke the Git Tab or Github Tab through the menu or keyboard shortcut

**Expected behavior:** The tab opens

**Actual behavior:** Nothing

**Reproduces how often:** Every time.

### Versions

Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.3
git 2.16.1.windows.4
visual studio 2015

OS versions:
Windows 7 Pro SP 1
macOS 10.13.3

### Additional Information

This has been going on for quite some time now. In versions prior to Atom 1.25 I could open the console and see an error message when I tried to open either tab. The error message was the same as one that I would get when I started Atom. I have tried uninstalling and reinstalling. Interestingly, this works, but only temporarily. This made me think that the issue was with some of my packages, but once the tabs stopped appearing, even opening in Safe Mode did not bring them back. Maybe one of my packages is doing some kind of permanent damage.

I use sync-settings, so you can reproduce my environment for a while if that is helpful.
Gist ID: 771a29283ca1a5f3f6ad6ac0d741cf42

The error message I mentioned above still occurs every time I start Atom. Either in Safe Mode or not. Like I said, in previous versions that error would also be logged again when I tried to open either tab. Since 1.25, it only logs at startup. Here is the output of my last Safe Mode startup, showing the same error logged twice:

```
[Violation] 'requestAnimationFrame' handler took 51ms
<embedded>:273520 Uncaught (in promise) TypeError: validateDOMNesting.updatedAncestorInfo is not a function
    at ReactDOMContainerInfo (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactDOMContainerInfo.js:25:58)
    at mountComponentIntoNode (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactMount.js:102:89)
    at ReactReconcileTransaction.perform (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\Transaction.js:141:26)
    at batchedMountComponentIntoNode (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactMount.js:124:21)
    at ReactDefaultBatchingStrategyTransaction.perform (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\Transaction.js:141:26)
    at Object.batchedUpdates (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactDefaultBatchingStrategy.js:60:32)
    at Object.batchedUpdates (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactUpdates.js:95:33)
    at Object._renderNewRootComponent (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactMount.js:317:24)
    at Object._renderSubtreeIntoContainer (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactMount.js:399:38)
    at Object.render (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactMount.js:420:29)
    at GithubPackage.rerender (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\github\lib\github-package.js:355:30)
    at C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\github\lib\github-package.js:324:19
    at Generator.next (<anonymous>)
    at step (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\github\lib\github-package.js:100:197)
    at C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\github\lib\github-package.js:100:367
    at <anonymous>
ReactDOMContainerInfo @ <embedded>:273520
mountComponentIntoNode @ <embedded>:226711
perform @ <embedded>:274617
batchedMountComponentIntoNode @ <embedded>:226733
perform @ <embedded>:274617
batchedUpdates @ <embedded>:271971
batchedUpdates @ <embedded>:227406
_renderNewRootComponent @ <embedded>:226926
_renderSubtreeIntoContainer @ <embedded>:227008
render @ <embedded>:227029
rerender @ <embedded>:50449
(anonymous) @ <embedded>:50418
step @ <embedded>:50194
(anonymous) @ <embedded>:50194
<embedded>:65439 [Violation] 'setTimeout' handler took 69ms
[Violation] Forced reflow while executing JavaScript took 69ms
<embedded>:273520 Uncaught (in promise) TypeError: validateDOMNesting.updatedAncestorInfo is not a function
    at ReactDOMContainerInfo (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactDOMContainerInfo.js:25:58)
    at mountComponentIntoNode (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactMount.js:102:89)
    at ReactReconcileTransaction.perform (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\Transaction.js:141:26)
    at batchedMountComponentIntoNode (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactMount.js:124:21)
    at ReactDefaultBatchingStrategyTransaction.perform (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\Transaction.js:141:26)
    at Object.batchedUpdates (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactDefaultBatchingStrategy.js:60:32)
    at Object.batchedUpdates (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactUpdates.js:95:33)
    at Object._renderNewRootComponent (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactMount.js:317:24)
    at Object._renderSubtreeIntoContainer (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactMount.js:399:38)
    at Object.render (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\react-dom\lib\ReactMount.js:420:29)
    at GithubPackage.rerender (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\github\lib\github-package.js:355:30)
    at GithubPackage.setActiveContext (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\github\lib\github-package.js:660:18)
    at C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\github\lib\github-package.js:681:20
    at Generator.next (<anonymous>)
    at step (C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\github\lib\github-package.js:100:197)
    at C:\Users\FP_production\AppData\Local\atom\app-1.25.0\resources\app\node_modules\github\lib\github-package.js:100:367
    at <anonymous>
ReactDOMContainerInfo @ <embedded>:273520
mountComponentIntoNode @ <embedded>:226711
perform @ <embedded>:274617
batchedMountComponentIntoNode @ <embedded>:226733
perform @ <embedded>:274617
batchedUpdates @ <embedded>:271971
batchedUpdates @ <embedded>:227406
_renderNewRootComponent @ <embedded>:226926
_renderSubtreeIntoContainer @ <embedded>:227008
render @ <embedded>:227029
rerender @ <embedded>:50449
setActiveContext @ <embedded>:50754
(anonymous) @ <embedded>:50775
step @ <embedded>:50194
(anonymous) @ <embedded>:50194

```

**Comment by lee-dohm** [comment]
This issue was moved to atom/github#1356
