### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('<...

### ISSUE THREAD

**Issue by nonpolitical** [atom/atom#16978]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('</users>
</stuff>"') contains HTML space characters, which are not valid in tokens.

```
At C:\Users\Mike Robinson\AppData\Local\atom\app-1.25.0\resources\app\node_modules\autocomplete-plus\lib\suggestion-list-element.js:419

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('</users>
</stuff>"') contains HTML space characters, which are not valid in tokens.
    at SuggestionListElement.addClassToElement (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:419:50)
    at SuggestionListElement.renderItem (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:471:30)
    at SuggestionListElement.renderItems (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:293:18)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.25.0/resources/app/src/view-registry.js:238:13)
```

### Commands

```
     -1:39.8.0 core:backspace (input.hidden-input)
     -1:28.5.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:28 editor:newline (input.hidden-input)
  3x -1:22.6.0 core:backspace (input.hidden-input)
     -1:13.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -1:12.6.0 editor:newline (input.hidden-input)
     -1:04.9.0 autocomplete-plus:confirm (input.hidden-input)
  2x -1:01.6.0 core:backspace (input.hidden-input)
     -0:58.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:58 core:move-left (input.hidden-input)
     -0:56.1.0 core:backspace (input.hidden-input)
     -0:53 autocomplete-plus:activate (atom-text-editor.editor)
     -0:52.4.0 core:backspace (input.hidden-input)
     -0:27.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:17.7.0 editor:newline (input.hidden-input)
     -0:14.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.5 
export-html 3.1.0 
kite 0.74.0 
markdown-themeable-pdf 1.2.0 
```

**Comment by nonpolitical** [comment]
Duplicate issue.. Most likely a problem with autocomplete-python.
