### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by suzurose** [atom/atom#16975]
[Enter steps to reproduce:]

Input any character in .tex file

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /((?<=[clr])([ |]*(c|l|r)))|./: Invalid group

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-body.js:86

SyntaxError: Invalid regular expression: /((?<=[clr])([ |]*(c|l|r)))|./: Invalid group
    at RegExp (<anonymous>)
    at peg$c34 (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-body.js:86:30)
    at peg$parsetransformationSubstitution (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-body.js:1086:30)
    at peg$parsetabStopWithTransformation (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-body.js:654:22)
    at peg$parsetabStop (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-body.js:413:18)
    at peg$parsebodyContent (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-body.js:297:20)
    at Object.peg$parse [as parse] (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-body.js:1254:24)
    at Object.parsedSnippetsForScopes (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:391:51)
    at SnippetsProvider.getSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-snippets/lib/snippets-provider.js:25:53)
    at providers.forEach.provider (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:300:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:271:21)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:263:23)
    at AutocompleteManager.requestNewSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1748:32)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:975:18)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1839:30)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1386:25)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3249:53)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3223:42)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1385:23)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1349:31)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1654:30)
```

### Commands

```
  3x -2:23.7.0 core:undo (input.hidden-input)
  3x -2:21.3.0 editor:log-cursor-scope (input.hidden-input)
     -2:16.6.0 command-palette:toggle (input.hidden-input)
     -2:14.9.0 core:confirm (input.hidden-input)
     -2:14.9.0 settings-view:open (input.hidden-input)
     -2:11.4.0 core:confirm (input.hidden-input)
     -2:09.4.0 editor:consolidate-selections (input.hidden-input)
     -2:09.4.0 core:cancel (input.hidden-input)
     -1:43.2.0 processing:run (input.hidden-input)
  3x -1:36.8.0 latex:clean (input.hidden-input)
  6x -1:35.1.0 processing:run (input.hidden-input)
     -0:41.3.0 latex:build (input.hidden-input)
     -0:19.7.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:19.7.0 editor:newline (input.hidden-input)
  2x -0:17.5.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:16.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-language-latex 0.1.2 
atom-monokai 0.10.9 
atom-processing 0.1.2 
autoclose-html 0.23.0 
autocomplete-json 5.5.2 
autocomplete-python 1.10.5 
build-processing 0.1.2 
colorful-json 1.1.0 
essence-dark-syntax 0.2.1 
flatwhite-syntax 0.8.1 
fold-functions 0.5.0 
goto-definition 1.3.4 
json-colorer 1.0.0 
json-schema 0.1.15 
language-babel 2.84.0 
language-cmake 1.1.0 
language-lua 0.9.11 
language-pug 0.0.22 
language-rust 0.4.12 
language-vue 0.23.1 
latex 0.49.0 
markdown-preview-plus 2.5.5 
markdown-writer 2.7.3 
monokai 0.24.0 
monokai-tweaked-ui 0.3.1 
pdf-view 0.65.0 
platformio-ide-terminal 2.8.1 
pretty-json 2.0.0 
processing 0.13.0 
processing-autocomplete 0.2.0 
processing-language 0.2.0 
processing-syntax 0.1.3 
python-autopep8 0.1.3 
python-indent 1.1.4 
python-tools 0.6.9 
resize-indent 0.3.0 
wombat-dark-syntax 1.2.0 
wordcount 2.10.4 
```

**Comment by lee-dohm** [comment]
I was unable to reproduce this using Atom v1.25.0 on Mac OS X 10.13.3. I suspect this is being caused by a community package you have installed. This is why we require attempting to reproduce the problem in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) in our issue template.

Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
