### ISSUE TITLE
Uncaught TypeError: Cannot read property 'markBufferRange' of undefined

### ISSUE THREAD

**Issue by yeti-detective** [atom/atom#16997]
[Enter steps to reproduce:]

1. Create file 'index.html'
2. type html onto first line & press Tab

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'markBufferRange' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:959

TypeError: Cannot read property 'markBufferRange' of undefined
    at SnippetExpansion.module.exports.SnippetExpansion.placeTabStopMarkers (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-expansion.js:176:67)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-expansion.js:61:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1839:30)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-expansion.js:49:39
    at SnippetExpansion.module.exports.SnippetExpansion.ignoringBufferChanges (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-expansion.js:109:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-expansion.js:48:30
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1839:30)
    at new SnippetExpansion (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-expansion.js:46:25)
    at Object.insert (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:625:20)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:516:25
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1839:30)
    at Object.expandSnippetsUnderCursors (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:507:20)
    at HTMLElement.snippets:expand (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:77:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -1:01.6.0 application:new-file (atom-pane.pane.active)
     -0:42.5.0 snippets:next-tab-stop (input.hidden-input)
     -0:42.5.0 snippets:expand (input.hidden-input)
     -0:42.5.0 editor:indent (input.hidden-input)
  7x -0:35.9.0 core:backspace (input.hidden-input)
     -0:27.6.0 find-and-replace:show (input.hidden-input)
     -0:27.4.0 core:select-all (input.hidden-input)
     -0:24.2.0 core:save-as (input.hidden-input)
     -0:11.1.0 autocomplete-plus:confirm (input.hidden-input)
     -0:11.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:03.1.0 snippets:next-tab-stop (input.hidden-input)
     -0:03.1.0 snippets:expand (input.hidden-input)
```

### Non-Core Packages

```
jshint 1.8.6 
react 0.16.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you reproduce in safe mode (`atom --safe`)?  I'm unable to reproduce on macOS 10.12.6 with Atom 1.25.

**Comment by yeti-detective** [comment]
I haven't been able to reproduce it since this morning. Restarting Atom
(from the terminal, not spotlight) seems to fix everything.

**Comment by ben-pritchard** [comment]
+1. I also get the error if I don't open atom via command line with the --safe tag.

**Comment by rsese** [comment]
Thanks @yeti-detective :+1:  Since it's not reproducible right now we'll go ahead and close for now - if you end up with steps to reproduce in safe mode however, please let us know and we can re-open :+1:

@ben-pritchard because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) for you, the error is likely caused by a community package you have installed. There may still be a bug in Atom and if so, we'll need the maintainer of the package that is causing the problem to help track that down.


One way to narrow things down is to disable all installed packages and then enable one-by-one. Or if you have a lot of installed packages, https://atom.io/packages/package-cop might be helpful too.  Once you determine what package is causing the problem, the [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file an issue there.
