### ISSUE TITLE
Uncaught TypeError: this.editor.transact is not a function

### ISSUE THREAD

**Issue by yusuken-freee** [atom/atom#16994]
[Enter steps to reproduce:]

1. while the error in #16993 is occuring,  replace a phrase with other phrase with `cmd + f` (= default search/replace function on Atom)
(If this error comes up, the phrase replacement doesn't work properly)

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.editor.transact is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:111

TypeError: this.editor.transact is not a function
    at BufferSearch.replace (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:111:23)
    at FindView.replaceAll (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:434:24)
```

### Commands

```
     -0:37.4.0 core:move-down (input.hidden-input)
     -0:37.1.0 autocomplete-plus:confirm (input.hidden-input)
     -0:34.7.0 core:save (input.hidden-input)
     -0:33.7.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:33.6.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
 10x -0:25.5.0 vim-mode-plus:move-left (input.hidden-input)
     -0:24.3.0 vim-mode-plus:activate-characterwise-visual-mode (input.hidden-input)
  5x -0:23.9.0 vim-mode-plus:move-to-next-word (input.hidden-input)
     -0:23 vim-mode-plus:move-right (input.hidden-input)
     -0:22.7.0 vim-mode-plus:move-left (input.hidden-input)
     -0:22.6.0 vim-mode-plus:delete (input.hidden-input)
  3x -0:21.8.0 core:save (input.hidden-input)
  2x -0:20.8.0 vim-mode-plus:move-down (input.hidden-input)
  4x -0:19.9.0 vim-mode-plus:move-up (input.hidden-input)
     -0:18.4.0 find-and-replace:show (input.hidden-input)
     -0:16.9.0 find-and-replace:focus-next (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
auto-indent 0.5.0 
autocomplete-paths 2.12.2 
autocomplete-ruby 0.2.8 
autocomplete-sql 0.5.0 
color-picker 2.2.5 
custom-title 1.0.1 
file-icons 2.1.15 
git-status 0.3.4 
highlight-selected 0.13.1 
language-digdag 0.0.2 
language-pgsql 0.2.3 
language-plantuml 0.2.0 
minimap 4.29.7 
minimap-autohide 0.10.1 
minimap-highlight-selected 4.6.1 
php-integrator-autocomplete-plus 1.6.2 
plantuml-viewer 0.7.2 
pretty-json 2.0.0 
Sublime-Style-Column-Selection 1.7.4 
vim-mode-plus 1.25.1 
```

**Comment by Aerijo** [comment]
Hi 👋 
I'm interesting in finding the cause of this issue, but I need help reproducing it. Could you please provide a step by step guide on how to reproduce this in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? It seems another issue you raised was closed because it couldn't be reproduced in safe mode with the instructions you provided.

I also notice one of the issues you reference refers to an external program. I don't know much about it, so would (probably) need extra help if it's necessary to reproduce the issue.
