### ISSUE TITLE
Uncaught TypeError: this.editor.getSelectedBufferRange is not a function

### ISSUE THREAD

**Issue by yusuken-freee** [atom/atom#16993]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.editor.getSelectedBufferRange is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:159

TypeError: this.editor.getSelectedBufferRange is not a function
    at BufferSearch.createMarkers (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:159:46)
    at BufferSearch.recreateMarkers (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:149:32)
    at BufferSearch.search (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:102:20)
    at FindView.liveSearch (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:356:31)
    at findEditor.onDidStopChanging (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:291:56)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1773:26)
    at later (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
 14x -0:32.7.0 vim-mode-plus:move-left (input.hidden-input)
     -0:30.1.0 vim-mode-plus:activate-characterwise-visual-mode (input.hidden-input)
 10x -0:29.9.0 vim-mode-plus:move-right (input.hidden-input)
     -0:28.3.0 vim-mode-plus:delete (input.hidden-input)
  2x -0:28.1.0 vim-mode-plus:move-left (input.hidden-input)
     -0:27.7.0 vim-mode-plus:move-right (input.hidden-input)
     -0:27.6.0 vim-mode-plus:delete-right (input.hidden-input)
  2x -0:27.2.0 vim-mode-plus:move-down (input.hidden-input)
     -0:26.6.0 vim-mode-plus:move-up (input.hidden-input)
     -0:26.4.0 vim-mode-plus:move-down (input.hidden-input)
  2x -0:25.8.0 core:save (input.hidden-input)
     -0:14.9.0 vim-mode-plus:move-down (input.hidden-input)
  3x -0:14.2.0 vim-mode-plus:move-left (input.hidden-input)
     -0:13 find-and-replace:show (input.hidden-input)
     -0:11.1.0 core:backspace (input.hidden-input)
     -0:10.7.0 find-and-replace:focus-next (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
auto-indent 0.5.0 
autocomplete-paths 2.12.2 
autocomplete-ruby 0.2.8 
autocomplete-sql 0.5.0 
color-picker 2.2.5 
custom-title 1.0.1 
file-icons 2.1.15 
git-status 0.3.4 
highlight-selected 0.13.1 
language-digdag 0.0.2 
language-pgsql 0.2.3 
language-plantuml 0.2.0 
minimap 4.29.7 
minimap-autohide 0.10.1 
minimap-highlight-selected 4.6.1 
php-integrator-autocomplete-plus 1.6.2 
plantuml-viewer 0.7.2 
pretty-json 2.0.0 
Sublime-Style-Column-Selection 1.7.4 
vim-mode-plus 1.25.1 
```

**Comment by yusuken-freee** [comment]
It seems there was a similar issue in the past.
https://github.com/atom/find-and-replace/issues/815

**Comment by Arcanemagus** [comment]
Are you able to reproduce this in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
