### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tags' of undefined

### ISSUE THREAD

**Issue by ChenXiyu** [atom/atom#17010]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'tags' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:752

TypeError: Cannot read property 'tags' of undefined
    at TextMateHighlightIterator.seek (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:752:45)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:83:58)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at DisplayLayer.getScreenLine (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:639:60)
    at TextEditor.screenLineForScreenRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1248:36)
    at TextEditorComponent.requestHorizontalMeasurement (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2248:47)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:373:18)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:275:16)
    at etch.getScheduler.updateDocument (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:225:46)
    at ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:238:13)
```

### Commands

```
  3x -0:30.9.0 vim-mode-plus:move-down (input.hidden-input)
  2x -0:30.4.0 vim-mode-plus:move-up (input.hidden-input)
     -0:23.7.0 vim-mode-plus:move-down (input.hidden-input)
     -0:23.6.0 vim-mode-plus:move-up (input.hidden-input)
     -0:23.4.0 vim-mode-plus:move-down (input.hidden-input)
  3x -0:23.3.0 vim-mode-plus:move-up (input.hidden-input)
     -0:22.9.0 vim-mode-plus:move-down (input.hidden-input)
     -0:22.7.0 vim-mode-plus:move-up (input.hidden-input)
     -0:22.7.0 vim-mode-plus:move-down (input.hidden-input)
     -0:22.2.0 datatip:toggle (input.hidden-input)
     -0:21.8.0 split-diff:toggle (input.hidden-input)
  2x -0:21.3.0 datatip:toggle (input.hidden-input)
     -0:11.9.0 split-diff:toggle (input.hidden-input)
  2x -0:11.7.0 datatip:toggle (input.hidden-input)
     -0:10.8.0 split-diff:toggle (input.hidden-input)
     -0:10.5.0 datatip:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.9.4 
better-git-blame 0.4.1 
cursor-history 0.13.1 
dash 1.7.1 
emmet 2.4.3 
file-icons 2.1.18 
git-plus 7.10.2 
go-plus 5.8.2 
gruvbox-plus-syntax 1.3.1 
highlight-selected 0.13.1 
ide-flowtype 0.22.1 
ide-go 0.7.0 
ide-ruby 0.1.10 
ide-typescript 0.7.6 
language-babel 2.84.0 
language-docker 1.1.8 
minimap 4.29.8 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
open-this 0.5.0 
split-diff 1.5.2 
sync-settings 0.8.5 
vim-mode-plus 1.31.1 
vim-mode-plus-keymaps-for-surround 0.2.1 
```

**Comment by ChenXiyu** [comment]
Thank you for your reply,
I’m toggling the split-diff(split-diff:toggle),
and this can’t reproduce now.

**Comment by rsese** [comment]
Thanks for the followup :+1:   We'll go ahead and close for now since it's not reproducible but we can definitely re-open if you come across repro steps.

**Comment by ChenXiyu** [comment]
Thanks for your time.
