### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 104.129.196.38...

### ISSUE THREAD

**Issue by courtneyburas** [atom/atom#17045]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 104.129.196.38:10364

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 104.129.196.38:10364
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
     -7:53.8.0 editor:newline (input.hidden-input)
     -6:56.4.0 symbols-view:go-to-declaration (span.syntax--source.syntax--sql)
 11x -6:08.9.0 core:backspace (input.hidden-input)
     -4:40 editor:newline (input.hidden-input)
     -4:36.7.0 snippets:next-tab-stop (input.hidden-input)
     -4:36.7.0 snippets:expand (input.hidden-input)
     -4:36.6.0 editor:indent (input.hidden-input)
  2x -4:19.8.0 core:backspace (input.hidden-input)
     -4:18.5.0 core:move-right (input.hidden-input)
     -4:17.7.0 editor:newline (input.hidden-input)
     -4:16.5.0 core:backspace (input.hidden-input)
  3x -4:16.3.0 editor:newline (input.hidden-input)
     -3:46 encoding-selector:show (span.syntax--source.syntax--sql)
     -2:49.8.0 command-palette:toggle (input.hidden-input)
     -2:25.5.0 styleguide:show (input.hidden-input)
     -1:03.7.0 settings-view:uninstall-packages (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
```

**Comment by rsese** [comment]
Thanks for the report - based on the error, this is maybe a temporary issue with your internet connection?  Please try again later and see if it works.
