### ISSUE TITLE
Uncaught TypeError: repoUrl.replace is not a function

### ISSUE THREAD

**Issue by ramsuraparaju** [atom/atom#17062]
Hi,
I am trying to build my own package in atom and get this attached error.
I just follow the tutorial at:
[https://github.com/blog/2231-building-your-first-atom-plugin](url)
My code that calls atom notifications looks like this:

```javascript
    if (editor = atom.workspace.getActiveTextEditor()) {
      let query = editor.getSelectedText()
      let language = editor.getGrammar().name    

      self.search(query, language).then((url) => {
        atom.notifications.addSuccess('Found google results!')
        return self.download(url)
      }).then((html) => {
        let answer = self.scrape(html)
        if (answer === '') {
          atom.notifications.addWarning('No answer found :(')
        } else {
          atom.notifications.addSuccess('Found snippet!')
          editor.insertText(answer)
        }
      }).catch((error) => {
        atom.notifications.addWarning(error.reason)
      })
```

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: repoUrl.replace is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-issue.js:184

TypeError: repoUrl.replace is not a function
    at NotificationIssue.module.exports.NotificationIssue.getRepoUrl (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-issue.js:184:46)
    at NotificationElement.module.exports.NotificationElement.renderFatalError (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:167:34)
    at NotificationElement.module.exports.NotificationElement.render (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:159:27)
    at new NotificationElement (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:49:39)
    at Object.createView (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/main.js:132:22)
    at ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:160:57)
    at ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:127:25)
    at Object.addNotificationView (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/main.js:184:64)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/main.js:41:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NotificationManager.addNotification (/Applications/Atom.app/Contents/Resources/app/src/notification-manager.js:193:24)
    at NotificationManager.addFatalError (/Applications/Atom.app/Contents/Resources/app/src/notification-manager.js:184:23)
    at Package.handleError (/Applications/Atom.app/Contents/Resources/app/src/package.js:1108:36)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:238:18)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (/Applications/Atom.app/Contents/Resources/app/src/package.js:865:28)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:360:24)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:346:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
     -0:33.9.0 application:new-file (input.hidden-input)
     -0:27.3.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:22.9.0 sourcefetch:fetch (div.line.highlight-line)
```

### Non-Core Packages

```
atom-ide-ui 0.9.4 
atom-json-color 0.6.0 
atom-json-editor 0.4.1 
atom-solidity-linter 0.0.11 
atom-terminal 0.8.0 
autocomplete-solidity 0.3.4 
busy-signal 1.4.3 
colorful-json 1.1.0 
dash 1.7.1 
file-icons 2.1.18 
formatter-json 1.0.1 
git-plus 7.10.2 
go-debug 1.6.0 
go-plus 5.8.2 
go-rename 0.3.0 
highlight-line 0.12.0 
ide-json 0.2.1 
intentions 1.1.5 
json-colorer 1.0.0 
language-ethereum 0.3.9 
language-markdown 0.25.1 
language-solidity 0.1.0 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-solidity 0.5.0 
linter-ui-default 1.7.1 
monokai-seti 0.9.0 
open-terminal-here 2.3.1 
platformio-ide-terminal 2.8.1 
pretty-json 2.0.0 
sourcefetch 0.0.0 
term 0.2.4 
web3js-snippets 0.1.0 
```

**Comment by Arcanemagus** [comment]
Can you share your code and provide steps to reproduce this? I'm unable to replicate with the final version of that code found [here](https://github.com/NickTikhonov/sourcefetch-tutorial).

**Comment by ramsuraparaju** [comment]
Sorry for wasting your time, it was a beginner's mistake I suppose.
I must have definitely missed an `apm install` somewhere.
when I followed the tutorial steps once again and it worked, so I am closing this.
