### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat '/\mydatanee\user$\'

### ISSUE THREAD

**Issue by nosubstitute959** [atom/atom#17093]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat '\\mydatanee\user$\'

```
At fs.js:961

Error: EPERM: operation not permitted, lstat '\\mydatanee\user$\'
    at fs.lstatSync (fs.js:961:11)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at start (fs.js:1614:10)
    at Proxy.realpathSync (fs.js:1602:3)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at atom.project.getPaths.map (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:73)
    at Array.map (native)
    at Object.startTask (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:56)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/fuzzy-finder/lib/main.js:109:43)
    at get_process.nextTick (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/fuzzy-finder/lib/main.js:25:45)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
```

### Non-Core Packages

```
autoclose-html 0.23.0 
```

**Comment by lee-dohm** [comment]
It looks like you didn't have access to the path at `\\mydatanee\user$`, sorry for the spurious dialog.
