### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=503

### ISSUE THREAD

**Issue by duanguanjun** [atom/atom#17154]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core
**User**: root

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=503

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:293:19)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:197:7)
    at Socket.socketOnData (_http_client.js:443:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

### Commands

```
     -8:52.4.0 core:backspace (input.hidden-input)
     -8:49.4.0 snippets:next-tab-stop (input.hidden-input)
     -8:49.4.0 snippets:expand (input.hidden-input)
  5x -8:48.1.0 core:backspace (input.hidden-input)
     -8:39.2.0 core:save (input.hidden-input)
     -8:31.4.0 run:file (input.hidden-input)
     -7:49.5.0 core:save (input.hidden-input)
  2x -7:49 run:file (input.hidden-input)
     -5:22.6.0 settings-view:open (input.hidden-input)
     -4:28.8.0 core:delete (input.hidden-input)
     -1:21.2.0 core:copy (span.syntax--text.syntax--plain.syntax--null-grammar)
     -1:17.5.0 core:paste (input.hidden-input)
 13x -1:15.8.0 core:move-left (input.hidden-input)
  2x -1:13.7.0 core:delete (input.hidden-input)
     -1:07.7.0 core:save (input.hidden-input)
     -0:16.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-monokai 0.10.9 
autocomplete-python 1.10.5 
monokai-seti 0.9.0 
script 3.17.3 
seti-ui 1.10.0 
```

**Comment by rsese** [comment]
Thanks for the report - based on the error, this is maybe a temporary issue? Please try again later and see if it works.
