### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by Gorotto** [atom/atom#17155]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At C:\Users\yastr\AppData\Local\atom\app-1.25.1\resources\app\src\text-mate-language-mode.js:493

TypeError: Cannot match against 'undefined' or 'null'.
    at TextMateLanguageMode.indentLevelForLine (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-mate-language-mode.js:493:38)
    at TextMateLanguageMode.endRowForCodeFoldAtRow (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-mate-language-mode.js:677:41)
    at TextMateLanguageMode.endRowForFoldAtRow (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-mate-language-mode.js:656:25)
    at TextMateLanguageMode.isFoldableAtRow (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-mate-language-mode.js:380:23)
    at TextEditor.isFoldableAtBufferRow (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-editor.js:3933:63)
    at TextEditorComponent.queryLineNumbersToRender (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-editor-component.js:934:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-editor-component.js:379:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didShow (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-editor-component.js:1460:18)
    at TextEditorComponent.didFocus (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-editor-component.js:1484:35)
    at HTMLElement.addEventListener (/app.asar/src/text-editor-element.js:36:67)
    at HTMLElement.PaneElement.activeItemChanged (/app.asar/src/pane-element.js:170:25)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.25.1/resources/app/src/pane.js:435:26)
    at Pane.activateItemAtIndex (~/AppData/Local/atom/app-1.25.1/resources/app/src/pane.js:558:23)
    at Pane.activatePreviousItem (~/AppData/Local/atom/app-1.25.1/resources/app/src/pane.js:522:18)
    at Pane.removeItem (~/AppData/Local/atom/app-1.25.1/resources/app/src/pane.js:694:20)
    at Pane.destroyItem (~/AppData/Local/atom/app-1.25.1/resources/app/src/pane.js:775:16)
    at <anonymous>
```

### Commands

```
     -1:54.8.0 intentions:highlight (input.hidden-input)
     -1:54.5.0 editor:duplicate-lines (input.hidden-input)
     -1:46.1.0 intentions:highlight (input.hidden-input)
     -1:45.7.0 editor:duplicate-lines (input.hidden-input)
     -1:43.7.0 editor:consolidate-selections (input.hidden-input)
  2x -1:43.7.0 core:cancel (input.hidden-input)
     -0:06.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-jade 0.3.0 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
busy-signal 1.4.3 
emmet 2.4.3 
intentions 1.1.5 
language-pug 0.0.22 
linter 2.2.0 
linter-htmlhint 1.4.0 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
minimap 4.29.8 
one-dark-material-syntax 1.0.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by Gorotto** [comment]
Hello.
During the error, I duplicated a couple of lines of code (ctrl+shift+d).
The error was faked, to eliminate it was necessary to put the beta atom.
p.s. since mid-March, the atom's settings have been reset(auto save,soft wrap, etc).

**Comment by Joe-TheBro** [comment]
In the bottom of my editor it was display ]); so I hit the space key, then I saved the document and </script> popped up and I did the same as before and this error showed up.

**Comment by rsese** [comment]
> The error was faked, to eliminate it was necessary to put the beta atom.

Just to clarify @Gorotto, does this mean you haven't seen the error since installing the beta?

> p.s. since mid-March, the atom's settings have been reset(auto save,soft wrap, etc).

Sorry, the team has shipped some updates to help prevent this from happening - since you have linter-ui-default installed, you may have hit https://github.com/atom/atom/issues/17060.

**Comment by Gorotto** [comment]
@rsese After installation beta, no errors, and the settings are not reset.
