### ISSUE TITLE
Uncaught Error: PCRE does not support /L, \l, \N{name}, \U, or \u

### ISSUE THREAD

**Issue by daanhaitsma** [atom/atom#17167]
All I did was open a file and save it. The information below has been automatically collected.

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: PCRE does not support \L, \l, \N{name}, \U, or \u

```
At C:\Users\Daan\AppData\Local\atom\app-1.25.1\resources\app.asar\node_modules\superstring\index.js:246

Error: PCRE does not support \L, \l, \N{name}, \U, or \u
    at TextBuffer.findAllInRangeSync (/app.asar/node_modules/superstring/index.js:246:44)
    at TextBuffer.module.exports.TextBuffer.findAllInRangeSync (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1167:32)
    at TextBuffer.module.exports.TextBuffer.scanInRange (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1080:32)
    at TextBuffer.module.exports.TextBuffer.scan (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1052:25)
    at TextEditor.scan (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-editor.js:3363:30)
    at ResultsModel.onContentsModified (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/find-and-replace/lib/project/results-model.js:336:18)
    at item.onDidStopChanging (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/find-and-replace/lib/project/results-model.js:50:49)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1773:26)
    at later (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -1:15.7.0 core:paste (input.hidden-input)
     -1:11.2.0 editor:newline (input.hidden-input)
  2x -1:11 core:paste (input.hidden-input)
  2x -1:07.1.0 editor:move-line-up (input.hidden-input)
     -1:03.0 core:save (input.hidden-input)
     -0:18.9.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:17.7.0 core:confirm (input.hidden-input)
     -0:14 find-and-replace:show (input.hidden-input)
     -0:13 editor:consolidate-selections (input.hidden-input)
     -0:13 core:cancel (input.hidden-input)
     -0:11.1.0 editor:newline (input.hidden-input)
     -0:10.9.0 core:paste (input.hidden-input)
     -0:10.4.0 core:save (input.hidden-input)
     -0:05.2.0 snippets:next-tab-stop (input.hidden-input)
     -0:05.2.0 snippets:expand (input.hidden-input)
     -0:05.2.0 editor:indent (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
atom-phpunit 1.2.4 
copy-find-results 0.1.0 
editorconfig 2.2.2 
git-blame 1.3.1 
git-control 0.9.0 
goto-definition 1.3.4 
language-vue 0.23.1 
obsidian-syntax 0.2.0 
php-cs-fixer 4.1.1 
remote-edit 1.9.0 
sync-settings 0.8.3 
wakatime 7.0.4 
```

**Comment by lee-dohm** [comment]
Thank you for contributing!

I notice that you didn't fill out the part of the template that asks if you can reproduce the error in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode). I suspect that this is caused by some on-save functionality in one of your installed packages.

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
