### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isChanged' of undefined

### ISSUE THREAD

**Issue by avigloz** [atom/atom#17189]
[Enter steps to reproduce:]

1. Open a file whose staged/unstaged changes you want to see (by right-clicking in the source of the file and selecting "View (Un)Staged Changes."
2. Click anywhere at all in the editor.

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'isChanged' of undefined

```
At C:\Users\MyUsername\AppData\Local\atom\app-1.26.0\resources\app\node_modules\github\lib\views\file-patch-selection.js:34

TypeError: Cannot read property 'isChanged' of undefined
    at Object.isItemSelectable (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/github/lib/views/file-patch-selection.js:34:45)
    at ListSelection.isItemSelectable (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/github/lib/views/list-selection.js:80:31)
    at ListSelection.getSelectedItems (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/github/lib/views/list-selection.js:278:24)
    at FilePatchSelection.getSelectedLines (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/github/lib/views/file-patch-selection.js:338:40)
    at FilePatchSelection.getSelectedHunks (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/github/lib/views/file-patch-selection.js:262:40)
    at FilePatchView.renderHunks (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/github/lib/views/file-patch-view.js:205:54)
    at FilePatchView.render (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/github/lib/views/file-patch-view.js:277:89)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:796:36)
    at ReactCompositeComponentWrapper._renderValidatedComponent (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:819:38)
    at ReactCompositeComponentWrapper._updateRenderedComponent (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:743:42)
    at ReactCompositeComponentWrapper._performComponentUpdate (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:721:16)
    at ReactCompositeComponentWrapper.updateComponent (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:642:18)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:558:18)
    at Object.performUpdateIfNecessary (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/ReactReconciler.js:154:28)
    at runBatchedUpdates (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/ReactUpdates.js:148:27)
    at ReactReconcileTransaction.perform (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/Transaction.js:141:26)
    at ReactUpdatesFlushTransaction.perform (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/Transaction.js:141:26)
    at ReactUpdatesFlushTransaction.perform (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/ReactUpdates.js:87:38)
    at Object.flushBatchedUpdates (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/ReactUpdates.js:170:25)
    at ReactDefaultBatchingStrategyTransaction.closeAll (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/Transaction.js:207:31)
    at ReactDefaultBatchingStrategyTransaction.perform (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/Transaction.js:154:22)
    at Object.batchedUpdates (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:32)
    at Object.enqueueUpdate (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/ReactUpdates.js:198:28)
    at enqueueUpdate (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:22:22)
    at Object.enqueueSetState (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:216:11)
    at FilePatchView.ReactComponent.setState (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/react/lib/ReactBaseClasses.js:62:22)
    at FilePatchView.mouseup (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/github/lib/views/file-patch-view.js:698:16)
```

### Commands

```
     -0:26.7.0 github:view-unstaged-changes-for-current-file (span.syntax--source.syntax--gfm)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
This issue was moved to atom/github#1408
