### ISSUE TITLE
Uncaught Error: Could not call remote function 'showMessageBox'. Check that the function signatur...

### ISSUE THREAD

**Issue by fi8on** [atom/atom#17204]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Could not call remote function 'showMessageBox'. Check that the function signature is correct. Underlying error: Error processing argument at index 11, conversion failure from undefined
Error: Could not call remote function 'showMessageBox'. Check that the function signature is correct. Underlying error: Error processing argument at index 11, conversion failure from undefined
    at callFunction (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234

Error: Could not call remote function 'showMessageBox'. Check that the function signature is correct. Underlying error: Error processing argument at index 11, conversion failure from undefined
Error: Could not call remote function 'showMessageBox'. Check that the function signature is correct. Underlying error: Error processing argument at index 11, conversion failure from undefined
    at callFunction (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:118:18)
    at ApplicationDelegate.confirm (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:240:48)
    at AtomEnvironment.confirm (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1050:45)
    at TreeView.module.exports.TreeView.removeSelectedEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1215:25)
    at HTMLElement.tree-view:remove (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view-package.js:32:66)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1351:25)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:346:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
  4x -8:49.6.0 core:confirm (input.hidden-input)
  3x -8:48.3.0 core:backspace (input.hidden-input)
     -8:41.1.0 find-and-replace:show (div.tool-panel.tree-view)
 31x -8:39.2.0 core:confirm (input.hidden-input)
     -6:33.3.0 project-find:show-in-current-directory (span.name.icon.icon-repo)
     -6:32.1.0 core:paste (input.hidden-input)
     -6:31.3.0 core:confirm (input.hidden-input)
  2x -5:56.7.0 find-and-replace:show (input.hidden-input)
  9x -5:46 core:confirm (input.hidden-input)
  2x -5:21.5.0 core:save (input.hidden-input)
     -0:55.7.0 project-find:show-in-current-directory (span.name.icon.icon-repo)
     -0:54.5.0 core:paste (input.hidden-input)
     -0:53.7.0 core:confirm (input.hidden-input)
     -0:34.4.0 core:select-up (div.tool-panel.tree-view)
     -0:11.1.0 core:select-down (div.tool-panel.tree-view)
     -0:06.3.0 tree-view:remove (span.name.icon.icon-file-text)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report! Can you confirm a few things for us?

what were you doing at the time of the error?
is the error is reproducible?
if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by fi8on** [comment]
I am sorry Robert, i kinda don't remember exact situation that caused it. I
was making quite a few changes that day, and trying out Atom when i came
across the error. It might be me monkeying around things.

- Shri

**Comment by rsese** [comment]
No problem @fi8on :+1:  We'll go ahead and close for now since we don't have repro steps but we can re-open if you run into it again.  Thanks for reporting!

**Comment by hussfelt** [comment]
@rsese I got directed here from Atom just now.
Tried to delete a file called ```terraform.rfstate.backup``` in one of my project folders.

[Enter steps to reproduce:]

1. Right click on file in editor
2. Choose "Delete" on file

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Could not call remote function 'showMessageBox'. Check that the function signature is correct. Underlying error: Error processing argument at index 11, conversion failure from undefined
Error: Could not call remote function 'showMessageBox'. Check that the function signature is correct. Underlying error: Error processing argument at index 11, conversion failure from undefined
    at callFunction (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234

Error: Could not call remote function 'showMessageBox'. Check that the function signature is correct. Underlying error: Error processing argument at index 11, conversion failure from undefined
Error: Could not call remote function 'showMessageBox'. Check that the function signature is correct. Underlying error: Error processing argument at index 11, conversion failure from undefined
    at callFunction (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:118:18)
    at ApplicationDelegate.confirm (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:240:48)
    at AtomEnvironment.confirm (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1050:45)
    at TreeView.module.exports.TreeView.removeSelectedEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1215:25)
    at HTMLElement.tree-view:remove (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view-package.js:32:66)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1351:25)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:346:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
  7x -1:30.2.0 core:move-left (input.hidden-input)
     -1:29.3.0 core:backspace (input.hidden-input)
     -1:28.6.0 autocomplete-plus:cancel (input.hidden-input)
     -1:22.2.0 core:paste (input.hidden-input)
     -1:21.3.0 core:backspace (input.hidden-input)
     -1:17.9.0 core:move-left (input.hidden-input)
     -1:17.6.0 editor:select-to-end-of-line (input.hidden-input)
  2x -1:17.5.0 core:select-left (input.hidden-input)
     -1:16.8.0 core:paste (input.hidden-input)
  7x -1:16.6.0 core:move-left (input.hidden-input)
     -1:15.5.0 core:backspace (input.hidden-input)
     -1:14.9.0 autocomplete-plus:cancel (input.hidden-input)
     -1:14.6.0 editor:consolidate-selections (input.hidden-input)
     -1:14.6.0 core:cancel (input.hidden-input)
     -1:13.8.0 core:save (input.hidden-input)
     -0:32.1.0 tree-view:remove (span.name.icon.terraform-icon.medium-cyan)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
file-icons 2.1.19 
highlight-selected 0.13.1 
intentions 1.1.5 
language-docker 1.1.8 
language-pgsql 0.2.3 
language-terraform 0.8.1 
linter 2.2.0 
linter-docker 0.3.2 
linter-golinter 1.2.2 
linter-pycodestyle 2.1.3 
linter-python 3.1.2 
linter-shellcheck 1.4.7 
linter-terraform-syntax 1.2.3 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-linter 2.1.3 
nucleus-dark-ui 0.12.3 
project-manager 3.3.5 
script 3.17.3 
split-diff 1.5.2 
sublime-ui-dark 0.0.7 
terraform-fmt 0.3.0 
```

**Comment by rsese** [comment]
Thanks @hussfelt - is this reproducible for you or did it just happen the one time with that particular file?

**Comment by hussfelt** [comment]
@rsese no, only once. But it was the "delete" that triggered it.
