### ISSUE TITLE
Uncaught TypeError: Bad arguments

### ISSUE THREAD

**Issue by sopig** [atom/atom#17265]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0-dev-db36ca059 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Bad arguments

```
At ELECTRON_ASAR.js:468

TypeError: Bad arguments
    at fs.readFile (ELECTRON_ASAR.js:468:15)
    at /app.asar/node_modules/graceful-fs/graceful-fs.js:73:14)
    at Object.readFile (/app.asar/node_modules/graceful-fs/graceful-fs.js:70:12)
    at Storage.provide (/app.asar/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:56:2)
    at CachedInputFileSystem.readFile (/app.asar/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:140:24)
    at /app.asar/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:20:6)
    at Resolver.applyPluginsParallelBailResult (/app.asar/node_modules/tapable/lib/Tapable.js:139:14)
    at /app.asar/node_modules/enhanced-resolve/lib/Resolver.js:103:8)
    at Resolver.forEachBail (/app.asar/node_modules/enhanced-resolve/lib/Resolver.js:196:3)
    at Resolver.doResolve (/app.asar/node_modules/enhanced-resolve/lib/Resolver.js:102:7)
    at Resolver.resolve (/app.asar/node_modules/enhanced-resolve/lib/Resolver.js:45:14)
    at Resolver.resolve (/app.asar/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:23:14)
    at /app.asar/node_modules/webpack/lib/NormalModuleFactory.js:169:12
    at /app.asar/node_modules/webpack/node_modules/async/lib/async.js:356:13
    at async.forEachOf.async.eachOf (/app.asar/node_modules/webpack/node_modules/async/lib/async.js:233:13)
    at _asyncMap (/app.asar/node_modules/webpack/node_modules/async/lib/async.js:355:9)
    at Object.map (/app.asar/node_modules/webpack/node_modules/async/lib/async.js:337:20)
    at NormalModuleFactory.resolveRequestArray (/app.asar/node_modules/webpack/lib/NormalModuleFactory.js:166:8)
    at /app.asar/node_modules/webpack/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/app.asar/node_modules/webpack/node_modules/async/lib/async.js:233:13)
    at _parallel (/app.asar/node_modules/webpack/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/app.asar/node_modules/webpack/node_modules/async/lib/async.js:731:9)
    at /app.asar/node_modules/webpack/lib/NormalModuleFactory.js:109:12
    at /app.asar/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /app.asar/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/app.asar/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /app.asar/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /app.asar/node_modules/webpack/node_modules/async/lib/async.js:723:17
    at /app.asar/node_modules/webpack/node_modules/async/lib/async.js:167:37
    at /app.asar/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:29:4
```

### Commands

```
  2x -0:22.9.0 mf-runner:runTask (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```

```

**Comment by steveward** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by steveward** [comment]
Thanks for taking the time to contribute!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/17265#issuecomment-386347004. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
