### ISSUE TITLE
Uncaught Error: Got unexpected null or undefined

### ISSUE THREAD

**Issue by alsun2001** [atom/atom#17274]
[Enter steps to reproduce:]

1. Ctrl-0 to put focus on Project Explorer
2. Cmd-K,<left arrow>

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Got unexpected null or undefined

```
At /opt/facebook/nuclide/0.290.98502521/nuclide/node_modules/nullthrows/nullthrows.js:9

Error: Got unexpected null or undefined
    at nullthrows (/opt/facebook/nuclide/0.290.98502521/nuclide/node_modules/nullthrows/nullthrows.js:9:9)
    at FileTreeController._collapseSelection (/opt/facebook/nuclide/0.300.105091723/nuclide/pkg/nuclide-file-tree/lib/FileTreeController.js:445:79)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
  4x -0:57 nuclide-file-tree:toggle (atom-pane.pane)
     -0:52.9.0 nuclide-quick-open:find-anything-via-omni-search (atom-pane.pane)
     -0:51.1.0 editor:consolidate-selections (input.hidden-input)
  2x -0:51.1.0 core:cancel (input.hidden-input)
  5x -0:45.8.0 window:reset-font-size (atom-pane.pane)
  7x -0:42.5.0 nuclide-file-tree:toggle-focus (atom-pane.pane)
     -0:31.1.0 nuclide-file-tree:open-selected-entry-right (div.list-tree.has-collapsable-children.file-tree-scroller.nuclide-file-tree.focusable-panel.tree-view)
     -0:30.5.0 nuclide-file-tree:collapse-directory (div.list-tree.has-collapsable-children.file-tree-scroller.nuclide-file-tree.focusable-panel.tree-view)
     -0:15.1.0 pane:split-right-and-move-active-item (input.hidden-input)
     -0:12.6.0 core:close (input.hidden-input)
     -0:07.2.0 nuclide-file-tree:toggle-focus (atom-pane.pane.active)
     -0:04.9.0 nuclide-file-tree:open-selected-entry-right (div.list-tree.has-collapsable-children.file-tree-scroller.nuclide-file-tree.focusable-panel.tree-view)
     -0:03.7.0 nuclide-file-tree:collapse-directory (div.list-tree.has-collapsable-children.file-tree-scroller.nuclide-file-tree.focusable-panel.tree-view)
```

### Non-Core Packages

```
file-icons 2.1.17 
haskell-grammar 0.4.0 
highlight-selected 0.11.2 
language-babel 2.48.5 
language-graphql 0.8.0 
language-haskell 1.17.3 
language-ini 1.17.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
merge-conflicts 1.4.4 
nuclide 0.301.105841753 
nuclide-format-js 0.0.44 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.6 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [nuclide](https://atom.io/packages/nuclide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
