### ISSUE TITLE
Cannot call function 'getPosition' on missing remote object 18.

### ISSUE THREAD

**Issue by nvkepler** [atom/atom#17283]
Uncaught Error: Cannot call function 'getPosition' on missing remote object 18 Error: Cannot call function 'getPosition' on missing remote object 18 at throwRPCError (/snap/atom/150/usr/share/atom/resources/electron.asar/browser/rpc-server.js:143:17) at EventEmitter. (/snap/atom/150/usr/share/atom/resources/electron.asar/browser/rpc-server.js:354:7) at emitMany (events.js:127:13) at EventEmitter.emit (events.js:204:7) at WebContents. (/snap/atom/150/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:256:13) at emitTwo (events.js:106:13) at WebContents.emit (events.js:194:7)

/snap/atom/150/usr/share/atom/resources/electron.asar/renderer/api/remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 18
Error: Cannot call function 'getPosition' on missing remote object 18
    at throwRPCError (/snap/atom/150/usr/share/atom/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/snap/atom/150/usr/share/atom/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/snap/atom/150/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (/snap/atom/150/usr/share/atom/resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (/snap/atom/150/usr/share/atom/resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.getWindowDimensions (/snap/atom/150/usr/share/atom/resources/app/src/atom-environment.js:694:40)
    at AtomEnvironment.storeWindowDimensions (/snap/atom/150/usr/share/atom/resources/app/src/atom-environment.js:731:40)
    at WindowEventHandler.handleWindowResize (/snap/atom/150/usr/share/atom/resources/app/src/window-event-handler.js:195:32)
    at WebViewImpl.dispatchEvent (/snap/atom/150/usr/share/atom/resources/electron.asar/renderer/web-view/web-view.js:175:22)
    at WebViewImpl.onElementResize (/snap/atom/150/usr/share/atom/resources/electron.asar/renderer/web-view/web-view.js:159:10)

This is likely a bug in Atom.

**Comment by rsese** [comment]
Thanks for the report!

This looks like a duplicate of #16630 so you can subscribe there if you'd like. 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
