### ISSUE TITLE
Uncaught TypeError: this.file.createReadStream is not a function

### ISSUE THREAD

**Issue by alequadro** [atom/atom#17292]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.file.createReadStream is not a function

```
At C:\ProgramData\a33758\atom\app-1.26.1\resources\app\node_modules\text-buffer\lib\text-buffer.js:1473

TypeError: this.file.createReadStream is not a function
    at TextBuffer.module.exports.TextBuffer.load (C:/ProgramData/a33758/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1473:82)
    at TextBuffer.module.exports.TextBuffer.setEncoding (C:/ProgramData/a33758/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:496:22)
    at TextEditor.setEncoding (C:/ProgramData/a33758/atom/app-1.26.1/resources/app/src/text-editor.js:1133:46)
    at Object.didConfirmSelection (C:/ProgramData/a33758/atom/app-1.26.1/resources/app/node_modules/encoding-selector/lib/encoding-list-view.js:38:54)
    at SelectListView.confirmSelection (C:/ProgramData/a33758/atom/app-1.26.1/resources/app/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at SelectListView.didClickItem (C:/ProgramData/a33758/atom/app-1.26.1/resources/app/node_modules/atom-select-list/src/select-list-view.js:287:16)
    at ListItemView.onclick (C:/ProgramData/a33758/atom/app-1.26.1/resources/app/node_modules/atom-select-list/src/select-list-view.js:222:37)
    at ListItemView.didClick (C:/ProgramData/a33758/atom/app-1.26.1/resources/app/node_modules/atom-select-list/src/select-list-view.js:449:16)
```

### Commands

```
  2x -7:57.3.0 core:paste (input.hidden-input)
     -7:45.5.0 core:confirm (input.hidden-input)
     -3:56.7.0 core:paste (input.hidden-input)
     -3:22.5.0 editor:newline (input.hidden-input)
     -3:12.6.0 core:move-up (input.hidden-input)
 10x -3:12.1.0 core:move-right (input.hidden-input)
     -2:54.1.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -2:50.8.0 core:confirm (input.hidden-input)
     -2:18.3.0 tree-view:remove (span.name.icon.icon-file-text)
 11x -0:22.6.0 core:backspace (input.hidden-input)
     -0:15.7.0 encoding-selector:show (atom-text-editor.editor.teletype-RemotePaneItem.is-focused)
```

### Non-Core Packages

```
teletype 0.13.2 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error? 
* Were you using Teletype at the time of the error?
* Is the error is reproducible?
* Ff reproducible, do you see the error in safe mode (atom --safe)?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/17292#issuecomment-387558021. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
