### ISSUE TITLE
Flaky tests: line ending selector Status bar tile ...

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#17326]
We've seen the line-ending-selector tests below fail twice in the past week:

https://circleci.com/gh/atom/atom/7475
https://circleci.com/gh/atom/atom/7499

Rebuilding can resolve the failures:

<img width="1065" alt="circleci" src="https://user-images.githubusercontent.com/2988/40060813-7467c768-5825-11e8-8bad-0836c878e6b5.png">

These recent failures are correlated with the recent Electron 2.0 upgrade (#17273), although we've seen these failures before (e.g., https://circleci.com/gh/atom/atom/7267).

### Failures

```
Package tests failed for line-ending-selector:
..........FFF.

line ending selector
  Status bar tile
    clicking the tile
      when selecting a different line ending for the file
        it changes the line endings in the buffer
          timeout: timed out after 60000 msec waiting for something to happen
      when modal is exited
        it leaves the tile selection as-is
          Expected 'CRLF' to be ''.
            at jasmine.Spec.runs (/Users/distiller/atom/node_modules/line-ending-selector/spec/line-ending-selector-spec.js:24:50)
          timeout: timed out after 60000 msec waiting for something to happen
    closing the last text editor
      it displays no line ending in the status bar
        Expected 'CRLF' to be ''.
          at jasmine.Spec.runs (/Users/distiller/atom/node_modules/line-ending-selector/spec/line-ending-selector-spec.js:24:50)
        Expected '' to be 'CRLF'.
          at lineEndingTile.onDidChange (/Users/distiller/atom/node_modules/line-ending-selector/spec/line-ending-selector-spec.js:232:58)
          at Function.module.exports.Emitter.simpleDispatch (/Users/distiller/atom/node_modules/event-kit/lib/emitter.js:25:14)
          at Emitter.module.exports.Emitter.emit (/Users/distiller/atom/node_modules/event-kit/lib/emitter.js:141:28)
          at StatusBarItem.setLineEndings (/Users/distiller/atom/node_modules/line-ending-selector/lib/status-bar-item.js:15:18)
          at /Users/distiller/atom/out/app/node_modules/line-ending-selector/lib/main.js:104:21
          at Function.module.exports.Emitter.simpleDispatch (/Users/distiller/atom/node_modules/event-kit/lib/emitter.js:25:14)
          at Emitter.module.exports.Emitter.emit (/Users/distiller/atom/node_modules/event-kit/lib/emitter.js:141:28)
          at Workspace.didChangeActivePaneItemOnPaneContainer (/Users/distiller/atom/src/workspace.js:438:22)
          at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Users/distiller/atom/src/workspace-center.js:17:14)
          at Function.module.exports.Emitter.simpleDispatch (/Users/distiller/atom/node_modules/event-kit/lib/emitter.js:25:14)
          at Emitter.module.exports.Emitter.emit (/Users/distiller/atom/node_modules/event-kit/lib/emitter.js:141:28)
          at PaneContainer.didChangeActiveItemOnPane (/Users/distiller/atom/src/pane-container.js:281:20)
          at Pane.setActiveItem (/Users/distiller/atom/src/pane.js:440:42)
          at Pane.removeItem (/Users/distiller/atom/src/pane.js:694:14)
          at Pane.destroyItem (/Users/distiller/atom/src/pane.js:779:10)
          at Promise.all.getItems.map.item (/Users/distiller/atom/src/pane.js:787:40)
          at Array.map (<anonymous>)
          at Pane.destroyItems (/Users/distiller/atom/src/pane.js:787:23)
          at Pane.destroy (/Users/distiller/atom/src/pane.js:1024:19)
          at atom.workspace.open.then (/Users/distiller/atom/node_modules/line-ending-selector/spec/line-ending-selector-spec.js:258:44)
          at <anonymous>

Finished in 121.406 seconds
14 tests, 70 assertions, 5 failures, 0 skipped
```

**Comment by jasonrudolph** [comment]
Observed again in https://circleci.com/gh/atom/atom/7532
