### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, open '$ATOM_HOME/packages\script\lib\script.js'

### ISSUE THREAD

**Issue by th3sha10wbr04rs** [atom/atom#17322]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM: operation not permitted, open 'C:\Users\The Shadow Brokers\.atom\packages\script\lib\script.js'

```
At fs.js:584

Error: EPERM: operation not permitted, open 'C:\Users\The Shadow Brokers\.atom\packages\script\lib\script.js'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Proxy.fs.readFileSync (fs.js:491:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at compileFileAtPath (~/AppData/Local/atom/app-1.26.1/resources/app/src/compile-cache.js:90:29)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.26.1/resources/app/src/compile-cache.js:239:26)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.26.1/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.26.1/resources/app/src/package.js:782:33)
    at Package.activateConfig (~/AppData/Local/atom/app-1.26.1/resources/app/src/package.js:267:16)
    at PackageManager.module.exports.PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/settings-view/lib/package-card.js:794:40)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/settings-view/lib/package-card.js:439:22)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/settings-view/lib/package-card.js:431:18)
    at ~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/settings-view/lib/package-card.js:728:22
    at ~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/settings-view/lib/package-card.js:811:17
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/settings-view/lib/package-manager.js:659:33)
    at ~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/settings-view/lib/package-manager.js:498:32
    at exit (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.26.1/resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (~/AppData/Local/atom/app-1.26.1/resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
```

### Non-Core Packages

```
script 3.17.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/17322#issuecomment-388946413. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
