### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 104.129.194.36:80

### ISSUE THREAD

**Issue by satssin** [atom/atom#17336]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 104.129.194.36:80

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 104.129.194.36:80
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-ide-ui 0.11.2 
city-lights-ui 1.3.3 
sonarlint 1.1.0 
```

**Comment by damieng** [comment]
This IP address is not one Atom uses - it looks like it's part of a corporate security service.  Are you on a corporate network or using a proxy server?
