### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by KX95** [atom/atom#17343]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At C:\Users\24195\AppData\Local\atom\app-1.27.0\resources\app\node_modules\settings-view\lib\atom-io-client.js:121

TypeError: Cannot convert undefined or null to object
    at Request._callback (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/atom-io-client.js:121:24)
    at Request.self.callback (/app.asar/node_modules/settings-view/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.32.2 
atom-html-preview 0.2.5 
autocomplete-modules 2.0.0 
autocomplete-paths 2.12.2 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
color-picker 2.3.0 
docblockr 0.13.7 
emmet 2.4.3 
file-icons 2.1.20 
git-plus 7.10.2 
intentions 1.1.5 
language-babel 2.85.0 
language-postcss 1.3.1 
linter 2.2.0 
linter-jshint 3.1.8 
linter-ui-default 1.7.1 
minimap 4.29.8 
simplified-chinese-menu 5.3.5 
sync-settings 0.8.6 
```

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/17343#issuecomment-389926031. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
