### ISSUE TITLE
Atom not starting correctly (console javascript error)

### ISSUE THREAD

**Issue by FelixB91** [atom/atom#17348]
When I start the Atom Editor I get a console window with errors (which looks quite similiar to the chrome console window) instead of the actual editor. I tried to re-install and re-start the editor and system a few times with no change of the problem.

That's how it looks:
![atom_error](https://user-images.githubusercontent.com/13133015/40192867-df640cb6-5a05-11e8-9ef5-86874b24f54e.PNG)

Works fine on any other system so far. That's the complete error log:

```
index.js:87 Error: EPERM: operation not permitted, open 'C:\Users\bockemuf\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\imports.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at Proxy.writeFileSync (C:\Users\bockemuf\AppData\Local\atom\app-1.27.0\resources\app\node_modules\fs-plus\lib\fs-plus.js:298:29)
    at LessCache.module.exports.LessCache.writeJson (C:\Users\bockemuf\AppData\Local\atom\app-1.27.0\resources\app\node_modules\less-cache\lib\less-cache.js:212:23)
    at LessCache.module.exports.LessCache.setImportPaths (C:\Users\bockemuf\AppData\Local\atom\app-1.27.0\resources\app\node_modules\less-cache\lib\less-cache.js:161:18)
    at new LessCache (C:\Users\bockemuf\AppData\Local\atom\app-1.27.0\resources\app\node_modules\less-cache\lib\less-cache.js:68:18)
    at new LessCompileCache (C:\Users\bockemuf\AppData\Local\atom\app-1.27.0\resources\app\src\less-compile-cache.js:21:26)
    at ThemeManager.loadLessStylesheet (C:\Users\bockemuf\AppData\Local\atom\app-1.27.0\resources\app\src\theme-manager.js:256:30)
    at ThemeManager.loadStylesheet (C:\Users\bockemuf\AppData\Local\atom\app-1.27.0\resources\app\src\theme-manager.js:248:25)
    at ThemeManager.requireStylesheet (C:\Users\bockemuf\AppData\Local\atom\app-1.27.0\resources\app\src\theme-manager.js:175:34)
    at ThemeManager.reloadBaseStylesheets (C:\Users\bockemuf\AppData\Local\atom\app-1.27.0\resources\app\src\theme-manager.js:230:16)
    at ThemeManager.loadBaseStylesheets (C:\Users\bockemuf\AppData\Local\atom\app-1.27.0\resources\app\src\theme-manager.js:226:16)
    at AtomEnvironment.initialize (C:\Users\bockemuf\AppData\Local\atom\app-1.27.0\resources\app\src\atom-environment.js:266:23)
    at module.exports (C:\Users\bockemuf\AppData\Local\atom\app-1.27.0\resources\app\src\initialize-application-window.js:108:29)
    at setupWindow (file:///C:/Users/bockemuf/AppData/Local/atom/app-1.27.0/resources/app.asar/static/index.js:106:12)
    at window.onload (file:///C:/Users/bockemuf/AppData/Local/atom/app-1.27.0/resources/app.asar/static/index.js:67:9)
handleSetupError @ index.js:87
```

**Comment by rsese** [comment]
Thanks for the report -

> index.js:87 Error: EPERM: operation not permitted, open 'C:\Users\bockemuf\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\imports.json'

Can you try deleting `C:\Users\bockemuf\.atom\compile-cache` and then restart Atom again?

Also, please fill out the issue template when opening an issue - the information in the template is helpful for us when triaging issues.

**Comment by FelixB91** [comment]
Hey, thank you very much, that resolved my problem perfectly! And sorry for not filling out the issue template, will do that next time.
