### ISSUE TITLE
Uncaught SyntaxError: Unexpected token r in JSON at position 2104

### ISSUE THREAD

**Issue by shipanmazumder** [atom/atom#17357]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught SyntaxError: Unexpected token r in JSON at position 2104

```
At file:///C:/Users/SM/AppData/Local/atom/app-1.27.0/resources/app.asar/static/index.html:1

SyntaxError: Unexpected token r in JSON at position 2104
    at JSON.parse (<anonymous>)
    at AtomIoClient.module.exports.AtomIoClient.fetchFromCache (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/atom-io-client.js:150:36)
    at AtomIoClient.module.exports.AtomIoClient.package (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/atom-io-client.js:53:25)
    at PackageCard.loadCachedMetadata (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/package-card.js:404:35)
    at new PackageCard (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/package-card.js:74:16)
    at InstallPanel.getPackageCardView (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/install-panel.js:400:20)
    at InstallPanel.addPackageViews (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/install-panel.js:386:55)
    at ~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/install-panel.js:456:26
    at ~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/atom-io-client.js:68:26
    at AtomIoClient.module.exports.AtomIoClient.fetchFromCache (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/atom-io-client.js:157:22)
    at AtomIoClient.module.exports.AtomIoClient.featuredPackages (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/atom-io-client.js:65:25)
    at InstallPanel.loadFeaturedPackages (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/install-panel.js:450:27)
    at new InstallPanel (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/install-panel.js:124:16)
    at ~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/settings-view.js:247:22
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/settings-view.js:371:25)
    at SettingsView.showPanel (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/settings-view.js:429:30)
    at SettingsView.showDeferredPanel (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/settings-view.js:416:20)
    at SettingsView.addPanel (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/settings-view.js:345:20)
    at SettingsView.addCorePanel (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/settings-view.js:335:18)
    at SettingsView.initializePanels (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/settings-view.js:246:18)
    at ~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/settings-view/lib/settings-view.js:122:26
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
codeigniter 0.3.2 
open-in-browser 0.5.2 
open-on-bitbucket 0.5.0 
teletype 0.13.2 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by shipanmazumder** [comment]
when i install a package then see this error

**Comment by rsese** [comment]
> when i install a package then see this error

Just to clarify, this error reproduces for you consistently when you try to install any package?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/17357#issuecomment-394034767. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
