### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 85Error: Cannot call...

### ISSUE THREAD

**Issue by massic80** [atom/atom#17358]
I came back from lunch break and when I woke up my PC from lock screen I found that error.
I'm working with JS, EJS, SASS, Gulp.

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Windows 10 64bit
**Thrown From**: Atom Core
**NodeJS**: 10

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 85
Error: Cannot call function 'getPosition' on missing remote object 85
    at throwRPCError (C:\Users\m.caniparoli\AppData\Local\atom\app-1.27.0\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\m.caniparoli\AppData\Local\atom\app-1.27.0\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (C:\Users\m.caniparoli\AppData\Local\atom\app-1.27.0\resources\electron.asar\browser\api\web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

```
At C:\Users\m.caniparoli\AppData\Local\atom\app-1.27.0\resources\electron.asar\renderer\api\remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 85
Error: Cannot call function 'getPosition' on missing remote object 85
    at throwRPCError (~/AppData/Local/atom/app-1.27.0/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.27.0/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.27.0/resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (~/AppData/Local/atom/app-1.27.0/resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.27.0/resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.27.0/resources/app/src/atom-environment.js:694:40)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.27.0/resources/app/src/atom-environment.js:731:40)
    at WindowEventHandler.handleWindowResize (~/AppData/Local/atom/app-1.27.0/resources/app/src/window-event-handler.js:195:32)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.4 
atom-ide-ui 0.11.2 
atom-live-server 2.2.0 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.20 
git-time-machine 2.0.1 
ide-css 0.3.0 
ide-html 0.4.2 
ide-json 0.2.1 
ide-typescript 0.7.6 
intentions 1.1.5 
jshint 1.8.6 
language-ejs 0.4.0 
linter 2.2.0 
linter-package-json-validator 2.0.0 
linter-sass-lint 1.8.3 
linter-scss-lint 3.1.1 
linter-ui-default 1.7.1 
local-history 4.3.1 
prettier-atom 0.53.0 
react 0.18.0 
tasks 2.10.1 
teletype 0.13.2 
todo-show 2.3.0 
w3c-validation 0.4.0 
```

**Comment by massic80** [comment]
Looks like this is a duplicate of #16630
