### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.27.1\res...

### ISSUE THREAD

**Issue by webstuff56** [atom/atom#17384]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\David\AppData\Local\atom\app-1.27.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: The specified module could not be found.
\\?\C:\Users\David\AppData\Local\atom\app-1.27.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.27.1/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.27.1/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -3:30.4.0 core:save (input.hidden-input)
     -2:04.5.0 application:add-project-folder (div.tool-panel.tree-view)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.30.9 
atom-live-server 2.2.0 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.16 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-jscs 4.1.3 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
mdn-doc 0.3.0 
minimap 4.29.7 
minimap-pigments 0.2.2 
pigments 0.40.2 
todo 0.6.0 
```

**Comment by webstuff56** [comment]
Thank you, but I git it resolved.  I had to reinstall Atom and do something smart with my directory folder--it was out of control
    On Tuesday, May 22, 2018, 10:24:39 AM PDT, Robert Sese <notifications@github.com> wrote:  
 
 
Closed #17384.
