### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBuffer' of null

### ISSUE THREAD

**Issue by mikebronner** [atom/atom#17404]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getBuffer' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/symbol-provider.js:369

TypeError: Cannot read property 'getBuffer' of null
    at SymbolProvider.getSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/symbol-provider.js:369:86)
    at providers.forEach.provider (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:300:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:271:21)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:263:23)
    at AutocompleteManager.requestNewSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1792:32)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:996:18)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2002:30)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1429:25)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3419:26)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3390:42)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1428:23)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1381:31)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1661:30)
```

### Commands

```
     -0:29 tree-view:move (span.name.icon.php-icon.dark-blue)
     -0:28.7.0 core:move-right (input.hidden-input)
 10x -0:28.3.0 core:backspace (input.hidden-input)
     -0:26.4.0 core:confirm (input.hidden-input)
     -0:20.5.0 find-and-replace:show (div.tool-panel.tree-view)
  2x -0:16.4.0 core:backspace (input.hidden-input)
     -0:15 core:confirm (input.hidden-input)
     -0:10.6.0 core:move-left (input.hidden-input)
     -0:10.2.0 editor:select-to-end-of-word (input.hidden-input)
     -0:09.9.0 core:delete (input.hidden-input)
     -0:09.4.0 core:move-up (input.hidden-input)
  9x -0:09.0 core:move-right (input.hidden-input)
     -0:07.5.0 intentions:highlight (input.hidden-input)
     -0:07.3.0 editor:select-to-end-of-word (input.hidden-input)
     -0:07.0 core:delete (input.hidden-input)
     -0:02.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
autocomplete-js-import 1.4.0 
busy-signal 1.4.3 
chestnut-light-atom-syntax 0.2.1 
close-on-left 0.9.2 
dash 1.7.1 
double-tag 1.5.0 
duotone-light-syntax 2.1.0 
file-icons 2.1.21 
highlight-selected 0.13.1 
intentions 1.1.5 
language-blade 0.40.0 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-jsonlint 1.3.0 
linter-php 1.5.1 
linter-phpcs 1.6.8 
linter-phpmd 2.0.0 
linter-sass-lint 1.8.3 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
pen-paper-coffee-syntax 0.14.9 
php-hyperclick 1.2.1 
platformio-ide-terminal 2.8.1 
pretty-json 2.0.0 
recent-files-fuzzy-finder 0.6.1 
sort-lines 0.18.0 
symbols-navigator 1.4.0 
sync-settings 0.8.6 
tag 0.5.0 
tester 1.4.0 
tester-phpunit 1.0.6 
wakatime 7.0.4 
zentabs 0.8.9 
```

**Comment by mikebronner** [comment]
Sorry, I don't remember the exact sequence of events, but it happened while editing a file, doing something in the file tree view, possible copy/pasting a file, and editing a file after that.  I have only seen the error once so far.

**Comment by mikebronner** [comment]
I had this happen again when searching the current file. I changed the default find-and-replace package settings to turn autocomplete on. The error does not appear if I have search autocomplete disabled.

**Comment by rsese** [comment]
Thanks @mikebronner - I wasn't able to reproduce with that setting on, do you happen to have repro steps using that setting?

**Comment by mikebronner** [comment]
It hasn't occurred since, will open a new ticket if it happens again.
