### ISSUE TITLE
ERROR when try open Command Panel

### ISSUE THREAD

**Issue by dc-avasilev** [atom/atom#17443]
[Enter steps to reproduce:]

1. edit json schema
2. when finish, press ctrl+shift+P

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/dom.js:64

RangeError: Maximum call stack size exceeded
    at Function.dom.(anonymous function).children [as ol] (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/dom.js:64:18)
    at SelectListView.renderItems (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:226:22)
    at SelectListView.render (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:200:18)
    at updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:107:40)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:72:13
    at ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:238:13)
```

### Commands

```
     -1:54.7.0 autocomplete-plus:confirm (input.hidden-input)
  3x -1:51 core:move-down (input.hidden-input)
     -1:50.3.0 autocomplete-plus:confirm (input.hidden-input)
     -1:41.1.0 autocomplete-plus:cancel (input.hidden-input)
     -1:40.7.0 editor:newline (input.hidden-input)
  3x -1:38.1.0 autocomplete-plus:confirm (input.hidden-input)
     -1:29.5.0 autocomplete-plus:cancel (input.hidden-input)
     -1:29.2.0 editor:newline (input.hidden-input)
  7x -1:16.5.0 autocomplete-plus:confirm (input.hidden-input)
  2x -0:36.3.0 core:move-down (input.hidden-input)
  2x -0:27.6.0 core:backspace (input.hidden-input)
  2x -0:26.1.0 core:move-down (input.hidden-input)
     -0:25.6.0 autocomplete-plus:confirm (input.hidden-input)
  9x -0:24.4.0 core:move-left (input.hidden-input)
     -0:22.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:17.7.0 command-palette:toggle (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
align-regexp 0.4.0 
api-docs 0.0.6 
api-workbench 0.8.48 
atom-alignment 0.13.0 
atom-autocomplete-php 0.25.6 
Atom-Bash-Snippets 0.0.3 
atom-beautify 0.32.5 
atom-bracket-highlight 0.3.2 
atom-cform-yaml 0.5.1-0 
atom-clock 0.1.16 
atom-csv-markdown 1.0.2 
atom-ctags 5.1.2 
atom-doxit 0.2.0 
atom-ide-debugger-node 0.7.1 
atom-ide-debugger-python 0.7.1 
atom-ide-ui 0.12.0 
atom-json 0.6.0 
atom-json-color 0.6.0 
atom-json-editor 0.4.1 
atom-material-dark-minor-change 1.1.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
atom-monokai 0.10.9 
atom-pastebin 0.2.0 
atom-python-debugger 0.3.4 
atom-python-package 0.7.1 
atom-python-run 0.9.6 
atom-python-test 0.9.0 
atom-python-virtualenv 1.0.2 
atom-runner 2.7.1 
atom-save-all 0.4.1 
atom-shell-commands 1.5.0 
atom-sublime-monokai-syntax 0.4.4 
atom-tag-wrapper 0.2.0 
atom-terminal 0.8.0 
atom-terminal-panel 4.4.4 
atom-touch-events 0.23.0 
atom-typescript 12.5.1 
atom-unsaved-changes 0.4.0 
atom-wrap-in-tag 0.6.0 
atom-yamljson 0.2.4 
atomic-chrome 0.3.3 
auto-update-plus 0.5.8 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-bash-builtins 0.3.5 
autocomplete-clang 0.11.4 
autocomplete-json 5.5.2 
autocomplete-meteor-packages 1.3.0 
autocomplete-modules 2.0.0 
autocomplete-php 0.3.7 
autocomplete-python 1.10.5 
autocomplete-python-jedi 1.10.3-0 
autocomplete-sql 0.5.0 
autocomplete-xml 0.9.4 
autohide-tree-view 0.25.1 
autoupdate-packages 1.3.1 
autumn-highlighter-syntax 1.13.0 
block-comment-plus 0.5.1 
bottom-dock 0.4.4 
boxy-yesterday 0.1.0 
browse 1.10.8 
browser-plus 0.0.98 
build 0.70.0 
build-python 0.9.3 
build-tools 4.5.12 
busy 0.7.0 
busy-signal 1.4.3 
calc 0.4.0 
change-case 0.6.5 
character-table 0.4.3 
charcode-display 0.2.1 
code-annotations 2.2.0 
code-peek 1.4.21 
codelf 11.6.0 
coffee-refactor 0.7.0 
color-picker 2.3.0 
colorblind-wombat-dark-syntax 0.6.0 
column-select 1.0.1 
composer 0.5.0 
ctags-status 1.3.7 
cucumber 0.6.0 
cucumber-step 0.2.0 
darker-obsidian-syntax 1.0.2 
date 2.1.0 
delete-lines 0.5.0 
devdocs 0.2.1 
disable-keybindings 0.6.0 
docblockr 0.13.7 
docker 0.8.0 
double-brackets-with-spaces 2.1.0 
doxygen-snippets 0.1.1 
dracula-syntax 2.0.7 
dracula-ui 0.6.0 
drag-drop-text 0.1.4 
draw-centered 1.0.6 
easy-motion-redux 1.1.1 
editorconfig 2.2.2 
Ensime 0.41.0 
escape-utils 0.5.3 
expand-selection-to-quotes 0.11.0 
extract-usages 0.3.0 
file-header 1.13.9 
file-icons 2.1.21 
file-types 0.5.5 
find-selection 0.16.0 
fold-lines 0.2.2 
fold-navigator 0.0.622 
gherkin-autocomplete 2.0.0 
gherkin-snippets 0.3.0 
gherkin-table-formatter 0.1.0 
git-control 0.9.0 
git-log 0.4.1 
git-plus 7.10.2 
git-tools 0.5.0 
go-debug 1.6.2 
go-plus 5.8.3 
go-signature-statusbar 1.2.3 
goto 1.8.3 
goto-definition 1.3.4 
hacker-typer 0.4.0 
hard-wrap 1.7.1 
haskell-grammar 0.4.0 
hey-pane 1.1.0 
highlight-column 0.5.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
Hydrogen 2.5.0 
hyperclick 0.0.0 
hyperclick-markdown 0.2.2 
hyperclick-php 0.2.1 
hyperlink-hyperclick 2.0.0 
ide-go 0.7.0 
ide-json 0.2.1 
ide-python 0.9.2 
ide-scala 0.7.0 
ide-yaml 0.4.3 
increment-selection 0.3.0 
indentation-indicator 1.1.0 
inspect-python 0.1.0 
intentions 1.1.5 
jira-issue-search 1.0.3 
jira-timesheet 0.2.0 
js-hyperclick 1.13.0 
js-refactor 0.8.1 
json-colorer 1.0.0 
json-converter 0.2.4 
json-generator 0.1.15 
json-path-finder 0.1.9 
json-refs 0.1.3 
json-schema 0.1.15 
json-to-go-struct 0.0.5 
jsonlint 1.1.4 
jumpy 4.2.0 
key-peek 0.2.12 
keybinding-cheatsheet 0.1.1 
language-ansi 1.1.1 
language-awk 0.1.12 
language-confluence-wiki 0.2.0 
language-csv 1.1.2 
language-docker 1.1.8 
language-doxygen 0.7.0 
language-emacs-lisp 1.2.0 
language-fish-shell 1.1.0 
language-generic-config 1.4.0 
language-gherkin 1.0.4 
language-gherkin-i18n 1.3.4 
language-graphql 0.10.1 
language-hosts 0.1.2 
language-ini 1.20.0 
language-lisp 0.2.0 
language-log 1.10.1 
language-logstash 0.1.7 
language-lua 0.9.11 
language-markdown 0.25.1 
language-nginx 0.8.0 
language-ocaml 1.9.5 
language-pgsql 0.2.3 
language-powershell 4.0.1 
language-regexp 1.0.1 
language-restructuredtext 1.1.2 
language-rust 0.4.12 
language-scala 1.1.9 
language-scala-plus 1.2.2 
language-scheme 1.4.0 
language-sql-mysql 0.3.1 
language-swift 0.5.0 
language-thrift 1.0.2 
language-unix-shell 0.40.1 
language-vbscript 0.9.0 
language-viml 1.1.8 
last-cursor-position 0.9.2 
latex-hyperclick 0.2.0 
lines 0.13.1 
linter 2.2.0 
linter-flake8 2.3.0 
linter-gcc 0.7.1 
linter-js-yaml 1.3.0 
linter-json-lint 0.1.3 
linter-jsonlint 1.3.0 
linter-manager 0.2.12 
linter-php 1.5.1 
linter-phpcs 1.6.8 
linter-phpmd 2.0.0 
linter-pyflakes 0.3.2 
linter-python 3.1.2 
linter-python-pep8 0.2.0 
linter-scalac 1.4.4 
linter-scspell 2.3.0 
linter-shellcheck 1.4.7 
linter-spell 0.15.0 
linter-swagger 0.4.2 
linter-swagger-improved 0.2.2 
linter-ui-default 1.7.1 
live-doc-viewer 1.0.6 
MagicPython 1.0.12 
make-executable 1.0.0 
markdown-image-helper 1.0.4 
markdown-preview-enhanced 0.15.6 
markdown-preview-plus 3.2.2 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.1 
markdown-table-formatter 2.9.2 
markdown-toc 0.4.2 
markdown-writer 2.7.3 
material-syntax 0.6.1 
material-ui 1.0.10 
merge-conflicts 1.4.5 
minimap 4.29.8 
minimap-autohide 0.10.1 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-hide 0.3.0 
minimap-highlight-selected 4.6.1 
minimap-split-diff 0.3.7 
minimap-titles 1.15.0 
monokai 0.24.0 
monokai-darker 1.3.2 
move-cursor-improved 0.3.4 
multi-cursor 2.1.5 
multi-cursor-plus 1.2.0 
multi-highlight-selected 2.0.0 
multi-wrap-guide 1.1.5 
multiline-select 1.8.2 
navigate 0.1.20 
node-debugger 1.10.1 
npm-docs 0.2.0 
npm-helper 0.8.9 
nuclide-format-js 0.0.45 
nuclide-test-runner-pytest 0.1.1 
one-o-eight-syntax 0.35.2 
open-html-in-browser 0.2.1 
open-in-browser 0.5.2 
open-recent 5.0.0 
package-cop 0.2.10 
path-hyperclick 0.3.0 
php-composer-completion 0.3.4 
php-cs-fixer 4.1.1 
php-debug 0.3.5 
php-getters-setters 0.5.5 
php-hyperclick 1.2.1 
php-twig 4.0.0 
pigments 0.40.2 
pipe 0.4.0 
platformio-ide 2.1.4 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.1 
pomodoro 1.2.0 
pretty-json 2.0.0 
print-code 0.7.1 
project-manager 3.3.6 
project-view 0.6.2 
project-viewer 1.3.1 
pubster-syntax 3.0.2 
purl 1.0.0 
python-autopep8 0.1.3 
python-debugger 0.2.0 
python-import-magic 2.0.0 
python-indent 1.1.5 
python-iresolve 0.0.3 
python-isort 0.0.7 
python-snippets 1.9.0 
python-tools 0.6.9 
qolor 0.4.2 
quick-highlight 0.13.0 
quick-query-mssql 0.1.5 
quick-query-sqlite 0.3.1 
raml 0.2.0 
react 0.18.0 
readme 2.0.0 
refactor 0.11.5 
regex-comments 2.0.0 
regex-filter-and-generator 1.4.2 
regex-railroad-diagram 0.19.4 
regex-tester 0.2.0 
remote-atom 1.3.12 
remote-edit 1.9.0 
remote-ftp 2.2.0 
remote-sync 4.1.8 
rest-client 1.3.1 
rst-preview-pandoc 0.1.12 
run-in-terminal 1.0.1 
save-session 0.15.7 
scala-format 0.1.8 
script 3.18.1 
scroll-sync 0.2.4 
scroll-through-time 0.3.0 
selection-highlight 0.1.6 
set-syntax 0.4.0 
simple-drag-drop-text 0.4.0 
slickedit-select 1.6.2 
snippet-generator 0.3.2 
soft-wrap-indicator 1.1.0 
sort-lines 0.18.0 
split-diff 1.5.2 
ssh-config 0.13.0 
string-encoder 0.2.0 
styri-syntax 0.2.0 
Sublime-Style-Column-Selection 1.7.4 
sublimify 0.10.0 
susave 0.4.0 
swackets 0.35.0 
swap-selection 0.4.0 
symbols-tree-view 0.14.0 
sync-settings 0.8.6 
table-editor 0.2.2 
tableau-rest-api-snippets 0.5.0 
tabletopsimulator-lua 10.6.2 
tablr 1.8.3 
tabular 0.1.0 
tag 0.5.0 
tail 0.1.0 
tasks 2.10.1 
Tech-Writer-IDE 0.2.0 
teletype 0.13.3 
temporary-root 1.0.2 
terminal-plus 0.14.5 
text-manipulation 0.6.0 
text-pastry 0.6.1 
todo-manager 0.2.10 
todo-show 2.3.0 
toggler 0.3.1 
tool-bar 1.1.7 
trailing-spaces 0.4.0 
translator 0.3.0 
tree-view-open-files 0.3.0 
tsv-to-md 0.1.2 
unsaved-changes 0.1.0 
up2date 0.1.2 
url-encode 0.5.0 
vim-mode 0.66.0 
webbox-color 0.5.9 
wrap 0.1.0 
xml-decoder 1.1.0 
xml-formatter 0.11.0 
xml-tools 0.2.1 
yaml-helper 0.4.0 
yaml-path 0.1.1 
yaml-path-copy 2.1.6 
yaml-sortkey 0.1.0 
Zen 0.18.0 
zentabs 0.8.9 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible and if so, is it reproducible in safe mode (atom --safe)?

**Comment by dc-avasilev** [comment]
No, after relanch app is not reproduce

**Comment by rsese** [comment]
Thanks @dc-avasilev - since we don't have repro steps and no one else has reported this recently, we'll go ahead and close for now.
