### ISSUE TITLE
Uncaught TypeError: Cannot destructure property `length` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by SaberAlpha** [atom/atom#17482]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0-beta2 x64
**Electron**: 2.0.1
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot destructure property `length` of 'undefined' or 'null'.

```
At C:\Users\Administrator\AppData\Local\atom\app-1.28.0-beta2\resources\app\src\text-mate-language-mode.js:493

TypeError: Cannot destructure property `length` of 'undefined' or 'null'.
    at TextMateLanguageMode.indentLevelForLine (~/AppData/Local/atom/app-1.28.0-beta2/resources/app/src/text-mate-language-mode.js:493:38)
    at TextMateLanguageMode.endRowForCodeFoldAtRow (~/AppData/Local/atom/app-1.28.0-beta2/resources/app/src/text-mate-language-mode.js:677:41)
    at TextMateLanguageMode.endRowForFoldAtRow (~/AppData/Local/atom/app-1.28.0-beta2/resources/app/src/text-mate-language-mode.js:656:25)
    at TextMateLanguageMode.isFoldableAtRow (~/AppData/Local/atom/app-1.28.0-beta2/resources/app/src/text-mate-language-mode.js:380:23)
    at TextEditor.isFoldableAtBufferRow (~/AppData/Local/atom/app-1.28.0-beta2/resources/app/src/text-editor.js:4129:63)
    at TextEditorComponent.queryLineNumbersToRender (~/AppData/Local/atom/app-1.28.0-beta2/resources/app/src/text-editor-component.js:945:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.28.0-beta2/resources/app/src/text-editor-component.js:387:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.28.0-beta2/resources/app/src/text-editor-component.js:275:16)
    at etch.getScheduler.updateDocument (~/AppData/Local/atom/app-1.28.0-beta2/resources/app/src/text-editor-component.js:225:46)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.28.0-beta2/resources/app/src/view-registry.js:238:13)
```

### Commands

```
     -0:35.6.0 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.5.3 
atom-beautify 0.32.2 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.19 
language-vue 0.23.1 
linter 2.2.0 
minimap 4.29.8 
open-in-browser 0.5.2 
react 0.18.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (atom --safe)?

**Comment by AaronStackBarnes** [comment]
Hey I know what caused it for me:

```
...document.getElementsByTagName(selector)

```

**Comment by supremacy2k** [comment]
I get this error as well.
Typically when i try to collapse my css code (atm 780l lines), to save space.
It starts to lag a lot before it does it.

Havent tried safe mode.

**Comment by Ben3eeE** [comment]
https://github.com/atom/atom/issues/17643 mentions this happening when collapsing code in a javascript file in safe mode. Along with the exception reported in https://github.com/atom/atom/issues/17643

**Comment by codemaker4** [comment]
When this bug happened to me, i was collapsing JS code (the last lines in the code to be specific). Just before it happened collapsing got glitchy:
some lines where duplicated. (ghost-lines?)
I think this has to do with atom trying to read some duplicated lines, wish it is unable to do because these lines don't exesit.

**Comment by s2t2** [comment]
Started seeing this error when I open after I updated to High Sierra 10.13.6. Might be a coincidence, but I thought it might be helpful info.

Trace:

```sh
/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:497
Hide Stack Trace
TypeError: Cannot destructure property `length` of 'undefined' or 'null'.
    at TextMateLanguageMode.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:497:38)
    at TextMateLanguageMode.endRowForCodeFoldAtRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:681:41)
    at TextMateLanguageMode.endRowForFoldAtRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:660:25)
    at TextMateLanguageMode.isFoldableAtRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:384:23)
    at TextEditor.isFoldableAtBufferRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:4129:63)
    at TextEditorComponent.queryLineNumbersToRender (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:934:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:387:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didMouseWheel (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1549:59)
```
