### ISSUE TITLE
Failed to build Atom v1.27.2

### ISSUE THREAD

**Issue by lierdakil** [atom/atom#17484]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Building Atom v1.27.2 from git source failed with the following trace:

```
Generating snapshot script at "/home/livid/atom/out/startup.js" (2)Unable to transform source code for module /home/livid/atom/out/app/node_modules/yauzl/index.js.
Error: /home/livid/atom/out/app/node_modules/yauzl/index.js
Cannot replace with lazy function because the supplied node does not belong to an assignment expression or a variable declaration!
  at FileRequireTransform.replaceAssignmentOrDeclarationWithLazyFunction (/home/livid/atom/script/node_modules/electron-link/lib/file-require-transform.js:180:11)
  at Context.visitIdentifier (/home/livid/atom/script/node_modules/electron-link/lib/file-require-transform.js:72:18)
  at Context.invokeVisitorMethod (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:344:49)
  at Visitor.PVp.visitWithoutReset (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:196:32)
  at visitChildren (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at NodePath.each (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path.js:101:26)
  at visitChildren (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:219:18)
  at Visitor.PVp.visitWithoutReset (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at Visitor.PVp.visit (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:133:29)
  at Object.visit (/home/livid/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:101:55)
  at FileRequireTransform.replaceDeferredRequiresWithLazyFunctions (/home/livid/atom/script/node_modules/electron-link/lib/file-require-transform.js:68:20)
  at FileRequireTransform.apply (/home/livid/atom/script/node_modules/electron-link/lib/file-require-transform.js:25:10)
  at /home/livid/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:55:56
  at Generator.next (<anonymous>:null:null)
  at step (/home/livid/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:191)
  at /home/livid/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:361
  at <anonymous>:null:null
```

### Steps to Reproduce

1. `git clone https://github.com/atom/atom && cd atom && git checkout v1.27.2`
2. `scripts/build`

**Expected behavior:** Atom builds

**Actual behavior:** Build fails with the message above

**Reproduces how often:** 100%

### Versions

Linux 4.16.5-gentoo SMP x86_64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz GenuineIntel GNU/Linux

### Additional Information

Cursory search came up with #17481. Applying fcb8ca7441a200cad3d09cf430307966bda5f573 solved the issue for me. Probably a good idea to backport it?

**Comment by lee-dohm** [comment]
This has been fixed and backported to the `v1.27-releases` branch and shouldn't be an issue going forward. Let us know if you have any other questions.
