### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Lionclaw49** [atom/atom#17495]
[Enter steps to reproduce:]

1. Do nothing. Wait for it to happen.
2. It could be about my lists:
`list1 = "Bob",
          "Bob2",
          "Bob3"`

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/griffin/Desktop/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Users/griffin/Desktop/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (/Users/griffin/Desktop/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (/Users/griffin/Desktop/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/Users/griffin/Desktop/Atom.app/Contents/Resources/app/src/text-editor-component.js:881:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Users/griffin/Desktop/Atom.app/Contents/Resources/app/src/text-editor-component.js:385:16)
    at TextEditorComponent.updateSync (/Users/griffin/Desktop/Atom.app/Contents/Resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didMouseWheel (/Users/griffin/Desktop/Atom.app/Contents/Resources/app/src/text-editor-component.js:1560:59)
```

### Commands

```
  2x -0:21.6.0 editor:newline (input.hidden-input)
  3x -0:19.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
clear-night-syntax 1.3.17 
clear-night-ui 1.4.2 
no-caffeine-syntax 0.18.1 
teletype 0.13.2 
```

**Comment by Lionclaw49** [comment]
I restarted atom, it's now fixed.

**Comment by Lionclaw49** [comment]
how do i close this

**Comment by Lionclaw49** [comment]
oh nvm
