### ISSUE TITLE
Fetching featured packages failed

### ISSUE THREAD

**Issue by GrigorijSchleifer** [atom/atom#17525]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Fetching featured packages failed.Hide output…
module.js:471
    throw err;
    ^

Error: Cannot find module 'tmp'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/schleifergrigorij/Library/Mobile Documents/com~apple~CloudDocs/Atom.app/Contents/Resources/app/apm/node_modules/asar/lib/filesystem.js:8:9)
    at Object.<anonymous> (/Users/schleifergrigorij/Library/Mobile Documents/com~apple~CloudDocs/Atom.app/Contents/Resources/app/apm/node_modules/asar/lib/filesystem.js:168:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

### Steps to Reproduce

1. Safe mode shows the same behavior
2. googline the error message showed no helpful results 

I use Macbook Pro. 

Any ideas?

Thank you

**Comment by rsese** [comment]
Thanks for the report!

Are you also having trouble installing packages or can you just not see the featured packages?  

Similar issue x-ref: https://github.com/atom/settings-view/issues/1041
