### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/64/68tq26b90mx9hhf66y15ym_w0000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by Letina3** [atom/atom#17542]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/64/68tq26b90mx9hhf66y15ym_w0000gn/T/AppTranslocation/085E8434-6069-49DF-BF6D-A0062694060F/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At ELECTRON_ASAR.js:173

Error: dlopen(/private/var/folders/64/68tq26b90mx9hhf66y15ym_w0000gn/T/AppTranslocation/085E8434-6069-49DF-BF6D-A0062694060F/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/private/var/folders/64/68tq26b90mx9hhf66y15ym_w0000gn/T/AppTranslocation/085E8434-6069-49DF-BF6D-A0062694060F/d/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (/private/var/folders/64/68tq26b90mx9hhf66y15ym_w0000gn/T/AppTranslocation/085E8434-6069-49DF-BF6D-A0062694060F/d/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (/private/var/folders/64/68tq26b90mx9hhf66y15ym_w0000gn/T/AppTranslocation/085E8434-6069-49DF-BF6D-A0062694060F/d/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (/private/var/folders/64/68tq26b90mx9hhf66y15ym_w0000gn/T/AppTranslocation/085E8434-6069-49DF-BF6D-A0062694060F/d/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (/private/var/folders/64/68tq26b90mx9hhf66y15ym_w0000gn/T/AppTranslocation/085E8434-6069-49DF-BF6D-A0062694060F/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/64/68tq26b90mx9hhf66y15ym_w0000gn/T/AppTranslocation/085E8434-6069-49DF-BF6D-A0062694060F/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/64/68tq26b90mx9hhf66y15ym_w0000gn/T/AppTranslocation/085E8434-6069-49DF-BF6D-A0062694060F/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/64/68tq26b90mx9hhf66y15ym_w0000gn/T/AppTranslocation/085E8434-6069-49DF-BF6D-A0062694060F/d/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

Reported before but we didn't hear back from the reporters e.g. x-ref: https://github.com/atom/atom/issues/15861
