### ISSUE TITLE
Uncaught TypeError: Cannot set property 'result' of undefined

### ISSUE THREAD

**Issue by moyang** [atom/atom#17605]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot set property 'result' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project/results-view.js:282

TypeError: Cannot set property 'result' of undefined
    at ResultsView.didSetResult (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project/results-view.js:282:27)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at ResultsModel.setResult (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project/results-model.js:304:24)
    at ResultsModel.onContentsModified (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project/results-model.js:340:16)
    at item.onDidStopChanging (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project/results-model.js:50:49)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1817:26)
    at later (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
 27x -4:40.7.0 core:move-down (input.hidden-input)
 65x -4:39.1.0 core:move-up (input.hidden-input)
 28x -4:36.5.0 core:move-down (input.hidden-input)
 22x -4:35.2.0 core:move-up (input.hidden-input)
     -4:33.8.0 core:move-down (input.hidden-input)
     -4:33.6.0 core:delete (input.hidden-input)
  5x -4:33.2.0 core:move-down (input.hidden-input)
     -4:32.3.0 core:save (input.hidden-input)
 89x -4:31.5.0 core:move-down (input.hidden-input)
     -0:03.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atomic-emacs 0.12.1 
clipboard-plus 0.5.1 
disable-keybindings 0.6.0 
emacs-plus 0.12.0 
file-icons 2.1.21 
highlight-selected 0.13.1 
language-babel 2.85.0 
language-graphql 0.10.1 
language-haskell 1.17.8 
language-ini 1.20.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
nuclide 0.319.115253428 
nuclide-format-js 0.0.46 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.7 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (`atom --safe`)?
