### ISSUE TITLE
Uncaught TypeError: Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by nattzkungz** [atom/atom#17622]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'emit' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:46

TypeError: Cannot read property 'emit' of undefined
    at HTMLElement.detachedCallback (/app.asar/src/text-editor-element.js:46:18)
    at Tooltip.hide (/Applications/Atom.app/Contents/Resources/app/src/tooltip.js:365:60)
    at hideOnClickOutsideOfTooltip (/Applications/Atom.app/Contents/Resources/app/src/tooltip.js:77:20)
```

### Commands

```
     -5:53.3.0 core:backspace (input.hidden-input)
     -5:49 core:save (input.hidden-input)
     -5:37.5.0 core:move-left (input.hidden-input)
     -5:36.8.0 core:move-right (input.hidden-input)
     -5:35.3.0 core:move-left (input.hidden-input)
     -2:47.5.0 command-palette:toggle (atom-pane.pane)
  2x -2:44.6.0 core:move-down (input.hidden-input)
     -2:43.9.0 core:confirm (input.hidden-input)
     -2:43.9.0 github:clone (atom-pane.pane)
     -2:42.5.0 core:paste (input.hidden-input)
     -2:31.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-atom-material-ui)
     -1:30.8.0 command-palette:toggle (div.tool-panel.tree-view)
     -1:28.2.0 core:confirm (input.hidden-input)
     -1:28.2.0 github:clone (div.tool-panel.tree-view)
     -1:27.1.0 core:paste (input.hidden-input)
     -1:12 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-runner 2.7.1 
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 1.4.3 
docker 0.8.0 
file-icons 2.1.21 
gpp-compiler 3.0.7 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.7 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.3 
platomformio 0.7.1 
script 3.18.1 
sync-settings 0.8.6 
tool-bar 1.1.7 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?
