### ISSUE TITLE
Uncaught Error: EACCES: permission denied, scandir 'gitlab'

### ISSUE THREAD

**Issue by xenithorb** [atom/atom#17634]
This happens when I go to the install settings tab and click on this package as if I were to look at its settings, but it's not installed (on purpose) - this error is then thrown. 

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: "Fedora release
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EACCES: permission denied, scandir 'gitlab'

```
At fs.js:904

Error: EACCES: permission denied, scandir 'gitlab'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:580:28)
    at Proxy.listSync (/usr/share/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:190:30)
    at PackageDetailView.updateFileButtons (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:603:51)
    at PackageDetailView.updateInstalledState (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:484:18)
    at PackageDetailView.populate (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:454:18)
    at PackageDetailView.completeInitialization (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:214:18)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:250:24
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:56:26
    at AtomIoClient.module.exports.AtomIoClient.fetchFromCache (/usr/share/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:157:22)
    at AtomIoClient.module.exports.AtomIoClient.package (/usr/share/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:53:25)
    at PackageDetailView.fetchPackage (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:241:55)
    at PackageDetailView.loadPackage (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:229:22)
    at new PackageDetailView (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:100:16)
    at callback (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:366:26)
    at SettingsView.getOrCreatePanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:371:25)
    at SettingsView.showPanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:429:30)
    at HTMLDivElement.clickHandler (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:285:39)
```

### Commands

```
     -2:25.9.0 github:toggle-github-tab (ul.list-inline.tab-bar.inset-panel)
     -2:07.9.0 platformio-ide-terminal:toggle (div.tool-panel.tree-view)
     -1:46.5.0 key-binding-resolver:toggle (div.tool-panel.tree-view)
     -1:46.5.0 settings-view:open (div.tool-panel.tree-view)
  2x -1:42 core:cancel (div.package-detail.panels-item)
     -1:29.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
ansible-galaxy 0.2.1 
ansible-vault 0.6.16 
arc-ui 0.1.7 
atom-beautify 0.32.5 
atom-clock 0.1.16 
atom-ide-ui 0.12.0 
atom-jinja2 0.6.0 
atom-mermaid 3.3.1 
autocomplete-ansible 0.1.22 
build 0.70.0 
build-dockerfile 1.0.1 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.5 
docker 0.8.0 
dockerletion 0.2.0 
file-icons 2.1.22 
file-types 0.5.5 
git-plus 7.12.0 
gitlab-integration 0.4.7 
hey-pane 1.1.0 
ide-css 0.3.0 
ide-docker 0.0.2 
ide-html 0.4.2 
ide-json 0.2.1 
ide-python 1.0.0 
ide-yaml 0.4.3 
intentions 1.1.5 
jslint 1.5.1 
json-path-finder 0.1.9 
language-ansible 0.2.2 
language-asp 1.1.1 
language-cisco 1.4.0 
language-docker 1.1.8 
language-dotfiles 1.1.0 
language-ini 1.20.0 
language-markdown 0.26.0 
language-mermaid 0.6.0 
language-nginx 0.8.0 
language-powershell 4.0.1 
language-rpm-spec 0.16.0 
linter 2.2.0 
linter-ansible-linting 1.3.2 
linter-ansible-syntax 1.2.0 
linter-docker 0.3.2 
linter-haproxy 0.2.2 
linter-js-yaml 1.3.0 
linter-jsonlint 1.3.0 
linter-markdown 5.2.2 
linter-ruby 1.2.6 
linter-shellcheck 1.4.7 
linter-ui-default 1.7.1 
markdown-preview-enhanced 0.15.6 
markdown-themeable-pdf 1.2.1 
markdown-writer 2.7.4 
merge-conflicts 1.4.5 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-linter 2.1.3 
minimap-split-diff 0.3.7 
pandoc-convert 1.1.1 
pdf-view 0.70.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.3 
project-manager 3.3.6 
project-sidebar 1.3.0 
script 3.18.1 
split-diff 1.5.2 
sync-settings 0.8.6 
tree-view-autoresize 2.3.0 
tree-view-git-status 1.5.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Just to clarify, is the error reproducible or did you just see it once?  I was unable to reproduce on macOS 10.12.6 with Atom 1.30.0-dev-ea9b7cee4 with these steps:

1. Go to `Settings > Install`
2. Type `gitlab` in the search box
3. Click on the package card for the gitlab package

The package README is shown at this point for me, no error.

**Comment by xenithorb** [comment]
Yes it's reproducible in exactly the way you outlined. For other cards it works fine, and I'm unsure of whether I can find another one that causes this. Perhaps I had installed it and it was removed badly. 

Does the stack trace reveal any specifics about what it's trying to do? Maybe I can go look at filesystem permissions; I already checked SELinux and there were not AVCs

**Comment by rsese** [comment]
Maybe check if you have this directory and see if your user account owns it?

```
ls -ld ~/.atom/packages/gitlab
```

**Comment by xenithorb** [comment]
```
$ pwd ; find . -mindepth 1 -maxdepth 1 -type d | grep gitlab
/home/xenith/.atom/packages
./gitlab-integration

**Comment by rsese** [comment]
Hmmm so it's just the gitlab package giving you trouble and no other packages behave this way?  If you scan through the directory permissions in `~/.atom/packages`, is everything owned by your user account?

**Comment by xenithorb** [comment]
```
$ find ~/.atom ! -user $USER | wc -l
0
```

**Comment by rsese** [comment]
Thanks :+1:  And about my other question?

> Hmmm so it's just the gitlab package giving you trouble and no other packages behave this way?

**Comment by xenithorb** [comment]
I did a test of a handful of other searches and click a first not-installed package and it went to the README

**Comment by rsese** [comment]
One more a bit more extreme test - if you close Atom and then temporarily reset to factory defaults (so you'll have an empty `~/.atom/packages` directory now), does that make any difference when you try clicking on the gitlab package card from the install view?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults
