### ISSUE TITLE
package is not iterable

### ISSUE THREAD

**Issue by AjjuSingh** [atom/atom#17658]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Ubuntu 18.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: packages is not iterable

```
At /home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/install-panel.js:385

TypeError: packages is not iterable
    at InstallPanel.addPackageViews (/home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/install-panel.js:385:30)
    at /home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/install-panel.js:456:26
    at /home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:68:26
    at AtomIoClient.module.exports.AtomIoClient.fetchFromCache (/home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:159:22)
    at AtomIoClient.module.exports.AtomIoClient.featuredPackages (/home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:65:25)
    at InstallPanel.loadFeaturedPackages (/home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/install-panel.js:450:27)
    at new InstallPanel (/home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/install-panel.js:124:16)
    at /home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/settings-view.js:247:22
    at SettingsView.getOrCreatePanel (/home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/settings-view.js:371:25)
    at SettingsView.showPanel (/home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/settings-view.js:429:30)
    at SettingsView.showDeferredPanel (/home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/settings-view.js:416:20)
    at SettingsView.addPanel (/home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/settings-view.js:345:20)
    at SettingsView.addCorePanel (/home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/settings-view.js:335:18)
    at SettingsView.initializePanels (/home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/settings-view.js:246:18)
    at /home/cloudamx/.local/share/umake/ide/atom/resources/app/node_modules/settings-view/lib/settings-view.js:122:26
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -0:58.1.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Can you some things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?
* did you install Atom using one of the documented install methods (https://flight-manual.atom.io/getting-started/sections/installing-atom/)?

**Comment by jeffatwork** [comment]
I was having the same problem, but only when I install on Ubuntu 18.04 in Windows 10 WSL. For work I must use windows 10, so I really want it running under WSL and not DOS. 
To resolve the issue I modified the file install-panel.js and changed the method addPackageViews to add an if to ensure packages is an iterable object:

```
  addPackageViews (container, packages) {
    _if (packages == null || typeof packages[Symbol.iterator] !== 'function') {
      return
    }_
    for (const pack of packages) {
      this.addPackageCardView(container, this.getPackageCardView(pack))
    }
  }

```
