### ISSUE TITLE
Uncaught Error: Repository has been destroyed

### ISSUE THREAD

**Issue by cheduo** [atom/atom#17703]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 ia32
**Electron**: 2.0.5
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Repository has been destroyed

```
At C:\ProgramData\chenduo\atom\app-1.28.2\resources\app\src\git-repository.js:537

Error: Repository has been destroyed
    at GitRepository.getRepo (C:/ProgramData/chenduo/atom/app-1.28.2/resources/app/src/git-repository.js:537:19)
    at GitRepository.getLineDiffs (C:/ProgramData/chenduo/atom/app-1.28.2/resources/app/src/git-repository.js:460:29)
    at GitDiffView.module.exports.GitDiffView.updateDiffs (C:/ProgramData/chenduo/atom/app-1.28.2/resources/app/node_modules/git-diff/lib/git-diff-view.js:166:70)
    at C:/ProgramData/chenduo/atom/app-1.28.2/resources/app/node_modules/git-diff/lib/git-diff-view.js:3:65
    at Function.module.exports.Emitter.simpleDispatch (C:/ProgramData/chenduo/atom/app-1.28.2/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (C:/ProgramData/chenduo/atom/app-1.28.2/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (C:/ProgramData/chenduo/atom/app-1.28.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:1817:26)
    at later (C:/ProgramData/chenduo/atom/app-1.28.2/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -0:17.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:15.5.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:15.1.0 core:copy (input.hidden-input)
     -0:15 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:14.7.0 editor:newline (input.hidden-input)
     -0:14 core:undo (input.hidden-input)
     -0:13.2.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:13 core:copy (input.hidden-input)
  5x -0:12.7.0 core:move-down (input.hidden-input)
     -0:12 core:move-up (input.hidden-input)
     -0:11.1.0 core:paste (input.hidden-input)
     -0:10.5.0 core:move-left (input.hidden-input)
 11x -0:10.2.0 core:select-left (input.hidden-input)
     -0:08.9.0 connect-kdb-q:exec-selection (input.hidden-input)
     -0:06.7.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:06.3.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.32.5 
atom-charts 0.0.0 
atom-clock 0.1.16 
atom-focus-mode 1.0.0 
atom-notes 1.19.3 
atom-visual-studio-code-ui 1.3.4 
auto-indent 0.5.0 
autocomplete 0.47.0 
autocomplete-java 1.2.7 
autocomplete-kdb-q 0.5.10 
busy-signal 1.4.3 
codealike 0.0.11 
comment 0.6.1 
connect-kdb-q 0.4.12 
cursor-history 0.13.1 
default-language 0.3.1 
ex-mode 0.18.0 
file-icons 2.1.22 
git-plus 8.0.0 
goto-definition 1.3.4 
gpp-compiler 3.0.7 
highlight-selected 0.14.0 
Hydrogen 2.5.1 
hyperclick 0.1.5 
ide-json 0.2.1 
jarle-active-editor-info 0.1.2 
javascript-snippets 1.2.1 
language-babel 2.85.0 
language-cmake 1.1.0 
language-cython 0.3.0 
language-graphql 0.10.1 
language-haskell 1.17.8 
language-ini 1.20.0 
language-kdb-q 0.3.1 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-matlab 0.2.1 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
last-cursor-position 0.9.2 
minimap 4.29.8 
multi-cursor 2.1.5 
nuclide 0.323.0 
nuclide-format-js 0.0.46 
pdf-view 0.70.0 
set-syntax 0.4.0 
sort-lines 0.18.0 
split-diff 1.5.2 
switch-header-source 0.32.0 
terminal-plus 0.14.5 
tomatimer 1.2.3 
tool-bar 1.1.7 
tree-view-git-status 1.5.0 
vim-mode-plus 1.34.0 
Zen 0.18.0 
```

**Comment by cheduo** [comment]
seems the problem disappears when I disable codealike 0.0.11 package

**Comment by the-j0k3r** [comment]
> seems the problem disappears when I disable codealike 0.0.11 package

Good hunting :)

You discovered this bug report belongs in codealike repo ;) not here :)

**Comment by rsese** [comment]
> seems the problem disappears when I disable codealike 0.0.11 package

Thanks for tracking that down:+1:  

It may be that there is still a bug in Atom but if so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by xixxi** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Ubuntu 18.04.1
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Repository has been destroyed

```
At /usr/share/atom/resources/app/src/git-repository.js:537

Error: Repository has been destroyed
    at GitRepository.getRepo (/usr/share/atom/resources/app/src/git-repository.js:537:19)
    at GitRepository.getLineDiffs (/usr/share/atom/resources/app/src/git-repository.js:460:29)
    at GitDiffView.module.exports.GitDiffView.updateDiffs (/usr/share/atom/resources/app/node_modules/git-diff/lib/git-diff-view.js:166:70)
    at /usr/share/atom/resources/app/node_modules/git-diff/lib/git-diff-view.js:3:65
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1819:26)
    at later (/usr/share/atom/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -0:48.9.0 snippets:next-tab-stop (input.hidden-input)
     -0:48.9.0 snippets:expand (input.hidden-input)
     -0:48.9.0 editor:indent (input.hidden-input)
     -0:48.7.0 core:move-down (input.hidden-input)
  5x -0:48.6.0 core:move-left (input.hidden-input)
     -0:47.9.0 snippets:next-tab-stop (input.hidden-input)
     -0:47.9.0 snippets:expand (input.hidden-input)
     -0:47.9.0 editor:indent (input.hidden-input)
     -0:47.6.0 snippets:next-tab-stop (input.hidden-input)
     -0:47.6.0 snippets:expand (input.hidden-input)
     -0:47.6.0 editor:indent (input.hidden-input)
     -0:47.2.0 snippets:next-tab-stop (input.hidden-input)
     -0:47.2.0 snippets:expand (input.hidden-input)
     -0:47.2.0 editor:indent (input.hidden-input)
     -0:46.7.0 intentions:highlight (input.hidden-input)
     -0:46.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.5 
atom-ide-ui 0.13.0 
autocomplete-clang 0.11.5 
black-sun-syntax 1.0.0 
brogrammer-harder-syntax 1.3.0 
brogrammer-syntax 1.0.0 
brogrammer-v2-syntax 0.3.0 
build 0.70.0 
busy-signal 1.4.3 
CP-syntax 0.6.0 
earthsung-by-jackson-syntax 0.3.0 
emmet 2.4.3 
file-icons 2.1.26 
framer-syntax 1.1.0 
gamma-ray-syntax 0.3.0 
gamma-syntax 0.1.0 
highlight-selected 0.14.0 
ide-csharp 0.6.2 
ide-flowtype 0.23.1 
ide-java 0.8.3 
ide-json 0.2.1 
ide-php 0.7.15 
ide-typescript 0.7.9 
intentions 1.1.5 
ir-black-k-syntax 0.2.3 
jackhammer-syntax 1.1.0 
language-babel 2.85.0 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-jscs 4.1.3 
linter-jshint 3.1.9 
linter-ui-default 1.7.1 
Lux-Syntax 2.0.0 
min-syntax 1.1.0 
minimap 4.29.9 
minimap-pigments 0.2.2 
nuclide 0.362.0 
nue-syntax 0.0.2 
one-black-syntax 1.14.0 
pigments 0.40.2 
platformio-ide 2.2.3 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.4 
pretty-json 2.0.3 
styri-syntax 0.2.0 
summerino-syntax 0.2.4 
tool-bar 1.1.10 
two-syntax 0.2.0 
ubik-gotham-syntax 1.2.0 
vue-syntax 2.0.0 
```

**Comment by rsese** [comment]
@xixxi: if you can reproduce in safe mode, please open a new issue and fill out the issue template so we can take a look.

Also:

> Atom: 1.30.0 x64

The current release version of Atom is 1.32.0, please update and see if that makes any difference.
