### ISSUE TITLE
Cannot read property 'getScopeChain' of undefined

### ISSUE THREAD

**Issue by queerviolet** [atom/atom#17707]
This just happened when I opened a portal. Non-fatal.

```
/Users/queerviolet/github/atom/src/text-editor-registry.js:251 Uncaught (in promise) TypeError: Cannot read property 'getScopeChain' of undefined
    at TextEditorRegistry.subscribeToSettingsForEditorScope (/Users/queerviolet/github/atom/src/text-editor-registry.js:251)
    at TextEditorRegistry.updateAndMonitorEditorSettings (/Users/queerviolet/github/atom/src/text-editor-registry.js:221)
    at <anonymous>
    at resolve (/Users/queerviolet/github/node-tree-sitter/index.js:296)
    at new Promise (<anonymous>)
    at Parser.parseTextBuffer (/Users/queerviolet/github/node-tree-sitter/index.js:295)
    at TreeSitterLanguageMode.parse (/Users/queerviolet/github/atom/src/tree-sitter-language-mode.js:87)
    at LanguageLayer._performUpdate (/Users/queerviolet/github/atom/src/tree-sitter-language-mode.js:543)
    at LanguageLayer.update (/Users/queerviolet/github/atom/src/tree-sitter-language-mode.js:512)
    at new TreeSitterLanguageMode (/Users/queerviolet/github/atom/src/tree-sitter-language-mode.js:59)
    at GrammarRegistry.languageModeForGrammarAndBuffer (/Users/queerviolet/github/atom/src/grammar-registry.js:172)
    at GrammarRegistry.autoAssignLanguageMode (/Users/queerviolet/github/atom/src/grammar-registry.js:166)
    at GrammarRegistry.maintainLanguageMode (/Users/queerviolet/github/atom/src/grammar-registry.js:86)
    at Project.addBuffer (/Users/queerviolet/github/atom/src/project.js:695)
    at onDidAddPaneItem (/Users/queerviolet/github/atom/src/workspace.js:503)
    at Function.module.exports.Emitter.simpleDispatch (/Users/queerviolet/github/atom/node_modules/event-kit/lib/emitter.js:27)
    at Emitter.module.exports.Emitter.emit (/Users/queerviolet/github/atom/node_modules/event-kit/lib/emitter.js:156)
    at PaneContainer.didAddPaneItem (/Users/queerviolet/github/atom/src/pane-container.js:267)
    at Pane.addItem (/Users/queerviolet/github/atom/src/pane.js:636)
    at Pane.activateItem (/Users/queerviolet/github/atom/src/pane.js:578)
    at Workspace.open (/Users/queerviolet/github/atom/src/workspace.js:1049)
    at <anonymous>
```

**Comment by maxbrunsfeld** [comment]
@Ben3eeE found that he could reproduce this using `atom-ide-ui` when hovering on variables to see their types. The error occurs when the pop-up disappears.

**Comment by Ben3eeE** [comment]
> The error occurs when the pop-up disappears.

When it appears. Not disappears.

See this gif. If I disable tree-sitter I get a warning instead when the pop-up appears. With tree-sitter I get the exception.

![ide-ui exception](https://user-images.githubusercontent.com/1058982/43975095-c6e45f46-9cdc-11e8-9577-27b569ac97fd.gif)

The exception is slightly different:

```
Uncaught (in promise) TypeError: Cannot read property 'getScopeChain' of undefined
    at TextEditorRegistry.subscribeToSettingsForEditorScope (C:\Users\bene\AppData\Local\atom\app-1.31.0-nightly6\resources\app\src\text-editor-registry.js:251:46)
    at TextEditorRegistry.updateAndMonitorEditorSettings (C:\Users\bene\AppData\Local\atom\app-1.31.0-nightly6\resources\app\src\text-editor-registry.js:221:22)
    at <anonymous>
    at resolve (C:\Users\bene\AppData\Local\atom\app-1.31.0-nightly6\resources\app.asar\node_modules\tree-sitter\index.js:320:21)
    at new Promise (<anonymous>)
    at Parser.parseTextBuffer (C:\Users\bene\AppData\Local\atom\app-1.31.0-nightly6\resources\app.asar\node_modules\tree-sitter\index.js:319:10)
    at TreeSitterLanguageMode.parse (C:\Users\bene\AppData\Local\atom\app-1.31.0-nightly6\resources\app\src\tree-sitter-language-mode.js:106:40)
    at LanguageLayer._performUpdate (C:\Users\bene\AppData\Local\atom\app-1.31.0-nightly6\resources\app\src\tree-sitter-language-mode.js:570:48)
    at LanguageLayer.update (C:\Users\bene\AppData\Local\atom\app-1.31.0-nightly6\resources\app\src\tree-sitter-language-mode.js:539:47)
    at new TreeSitterLanguageMode (C:\Users\bene\AppData\Local\atom\app-1.31.0-nightly6\resources\app\src\tree-sitter-language-mode.js:76:34)
    at GrammarRegistry.languageModeForGrammarAndBuffer (C:\Users\bene\AppData\Local\atom\app-1.31.0-nightly6\resources\app\src\grammar-registry.js:172:20)
    at TextEditor.setGrammar (C:\Users\bene\AppData\Local\atom\app-1.31.0-nightly6\resources\app\src\text-editor.js:3816:48)
    at setupTextEditor (C:\Users\bene\.atom\packages\atom-ide-ui\modules\nuclide-commons-ui\AtomTextEditor.js:82:16)
    at AtomTextEditor.componentDidMount (C:\Users\bene\.atom\packages\atom-ide-ui\modules\nuclide-commons-ui\AtomTextEditor.js:113:28)
    at ai (C:\Users\bene\.atom\packages\atom-ide-ui\node_modules\react-dom\cjs\react-dom.production.min.js:219:412)
    at Vh (C:\Users\bene\.atom\packages\atom-ide-ui\node_modules\react-dom\cjs\react-dom.production.min.js:212:374)
    at Yh (C:\Users\bene\.atom\packages\atom-ide-ui\node_modules\react-dom\cjs\react-dom.production.min.js:211:278)
    at Wh (C:\Users\bene\.atom\packages\atom-ide-ui\node_modules\react-dom\cjs\react-dom.production.min.js:211:113)
    at Ah (C:\Users\bene\.atom\packages\atom-ide-ui\node_modules\react-dom\cjs\react-dom.production.min.js:209:281)
    at og (C:\Users\bene\.atom\packages\atom-ide-ui\node_modules\react-dom\cjs\react-dom.production.min.js:207:333)
    at gi (C:\Users\bene\.atom\packages\atom-ide-ui\node_modules\react-dom\cjs\react-dom.production.min.js:224:426)
    at ii (C:\Users\bene\.atom\packages\atom-ide-ui\node_modules\react-dom\cjs\react-dom.production.min.js:225:222)
    at qi.render (C:\Users\bene\.atom\packages\atom-ide-ui\node_modules\react-dom\cjs\react-dom.production.min.js:232:351)
    at C:\Users\bene\.atom\packages\atom-ide-ui\node_modules\react-dom\cjs\react-dom.production.min.js:236:417
    at ci (C:\Users\bene\.atom\packages\atom-ide-ui\node_modules\react-dom\cjs\react-dom.production.min.js:222:296)
    at ti (C:\Users\bene\.atom\packages\atom-ide-ui\node_modules\react-dom\cjs\react-dom.production.min.js:236:350)
    at Object.render (C:\Users\bene\.atom\packages\atom-ide-ui\node_modules\react-dom\cjs\react-dom.production.min.js:238:173)
    at a._RxMin.Observable.from.subscribe [as _next] (C:\Users\bene\.atom\packages\atom-ide-ui\modules\atom-ide-ui\pkg\atom-ide-datatip\lib\DatatipManager.js:279:23)
    at a.__tryOrUnsub (C:\Users\bene\.atom\packages\atom-ide-ui\node_modules\rxjs\bundles\Rx.min.js:71:208)
    at a.next (C:\Users\bene\.atom\packages\atom-ide-ui\node_modules\rxjs\bundles\Rx.min.js:70:63)
```

**Comment by maxbrunsfeld** [comment]
This was a very strange one. It turned out we were using a deprecated API on the [`Nan::Callback`](https://github.com/nodejs/nan/blob/master/doc/callback.md#nancallback-1) class for calling an async JavaScript callback from C++. Using the deprecated API appears to have caused total nonsense on the JavaScript side. The stack trace above would normally be impossible: there is no code path from `Parser.parseTextBuffer` to `TextEditorRegistry.updateAndMonitorEditorSettings`!
