### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by PedroRuiz** [atom/atom#17715]
```Path must be a string. Received undefined
Hide Stack Trace
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1186:7)
    at Object.<anonymous> (/home/pedro/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:7:36)
    at Object.<anonymous> (/home/pedro/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Object.<anonymous> (/home/pedro/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/pedro/.atom/packages/remote-edit/lib/main.coffee:3:20)
    at Object.<anonymous> (/home/pedro/.atom/packages/remote-edit/lib/main.coffee:1:1)
    at Object.<anonymous> (/home/pedro/.atom/packages/remote-edit/lib/main.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:782:33)
    at measure (/usr/share/atom/resources/app/src/package.js:143:22)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at Package.load (/usr/share/atom/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/src/package-manager.js:618:16)
    at config.transact (/usr/share/atom/resources/app/src/package-manager.js:531:20)
    at Config.transact (/usr/share/atom/resources/app/src/config.js:819:20)```

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [remote-edit](https://atom.io/packages/remote-edit) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
