### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by vpmartins** [atom/atom#17732]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Linux Mint
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /opt/atom/resources/app/node_modules/settings-view/lib/install-panel.js:385

TypeError: undefined is not a function
    at InstallPanel.addPackageViews (/opt/atom/resources/app/node_modules/settings-view/lib/install-panel.js:385:30)
    at /opt/atom/resources/app/node_modules/settings-view/lib/install-panel.js:456:26
    at /opt/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:68:26
    at AtomIoClient.module.exports.AtomIoClient.fetchFromCache (/opt/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:159:22)
    at AtomIoClient.module.exports.AtomIoClient.featuredPackages (/opt/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:65:25)
    at InstallPanel.loadFeaturedPackages (/opt/atom/resources/app/node_modules/settings-view/lib/install-panel.js:450:27)
    at new InstallPanel (/opt/atom/resources/app/node_modules/settings-view/lib/install-panel.js:124:16)
    at /opt/atom/resources/app/node_modules/settings-view/lib/settings-view.js:247:22
    at SettingsView.getOrCreatePanel (/opt/atom/resources/app/node_modules/settings-view/lib/settings-view.js:371:25)
    at SettingsView.showPanel (/opt/atom/resources/app/node_modules/settings-view/lib/settings-view.js:429:30)
    at SettingsView.showDeferredPanel (/opt/atom/resources/app/node_modules/settings-view/lib/settings-view.js:416:20)
    at SettingsView.addPanel (/opt/atom/resources/app/node_modules/settings-view/lib/settings-view.js:345:20)
    at SettingsView.addCorePanel (/opt/atom/resources/app/node_modules/settings-view/lib/settings-view.js:335:18)
    at SettingsView.initializePanels (/opt/atom/resources/app/node_modules/settings-view/lib/settings-view.js:246:18)
    at /opt/atom/resources/app/node_modules/settings-view/lib/settings-view.js:122:26
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
