### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=socket hang up

### ISSUE THREAD

**Issue by 53tang** [atom/atom#17735]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=socket hang up

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, cause=socket hang up
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketOnEnd (_http_client.js:423:9)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.2.5 
emmet 2.4.3 
language-jsx 0.1.1 
linter 2.2.0 
linter-ui-default 1.6.10 
```

**Comment by rsese** [comment]
Thanks for the report - not sure if this is a temporary network issue (you're using a proxy?), are you getting this error continuously or just once?
