### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/mx/h_kx94kn18q81cdqrvsdgsx40000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by aryairani** [atom/atom#17751]
I just opened Atom and am trying to navigate a file with arrow keys

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/mx/h_kx94kn18q81cdqrvsdgsx40000gn/T/AppTranslocation/2DE632AC-1D26-4B2B-AA90-DA99F8DEB334/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At ELECTRON_ASAR.js:172

Error: dlopen(/private/var/folders/mx/h_kx94kn18q81cdqrvsdgsx40000gn/T/AppTranslocation/2DE632AC-1D26-4B2B-AA90-DA99F8DEB334/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/private/var/folders/mx/h_kx94kn18q81cdqrvsdgsx40000gn/T/AppTranslocation/2DE632AC-1D26-4B2B-AA90-DA99F8DEB334/d/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (/private/var/folders/mx/h_kx94kn18q81cdqrvsdgsx40000gn/T/AppTranslocation/2DE632AC-1D26-4B2B-AA90-DA99F8DEB334/d/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (/private/var/folders/mx/h_kx94kn18q81cdqrvsdgsx40000gn/T/AppTranslocation/2DE632AC-1D26-4B2B-AA90-DA99F8DEB334/d/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (/private/var/folders/mx/h_kx94kn18q81cdqrvsdgsx40000gn/T/AppTranslocation/2DE632AC-1D26-4B2B-AA90-DA99F8DEB334/d/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (/private/var/folders/mx/h_kx94kn18q81cdqrvsdgsx40000gn/T/AppTranslocation/2DE632AC-1D26-4B2B-AA90-DA99F8DEB334/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/mx/h_kx94kn18q81cdqrvsdgsx40000gn/T/AppTranslocation/2DE632AC-1D26-4B2B-AA90-DA99F8DEB334/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/mx/h_kx94kn18q81cdqrvsdgsx40000gn/T/AppTranslocation/2DE632AC-1D26-4B2B-AA90-DA99F8DEB334/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/mx/h_kx94kn18q81cdqrvsdgsx40000gn/T/AppTranslocation/2DE632AC-1D26-4B2B-AA90-DA99F8DEB334/d/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:34.9.0 ide-haskell-cabal:build (input.hidden-input)
  4x -0:33.7.0 editor:consolidate-selections (input.hidden-input)
     -0:28.9.0 ide-haskell-cabal:build (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
haskell-ghc-mod 2.2.4 
ide-haskell 2.3.1 
ide-haskell-cabal 2.2.0 
language-haskell 1.17.8 
language-scala 1.1.9 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if you still see the error after reinstalling?

x-ref: https://github.com/atom/atom/issues/15861

**Comment by aryairani** [comment]
Sorry, I don't think I can reproduce it.

**Comment by rsese** [comment]
No problem and thanks for confirming - we'll go ahead and close for now but if you can reproduce in the future, please let us know :v:
