### ISSUE TITLE
Uncaught Error: spawn E2BIG

### ISSUE THREAD

**Issue by bhartvigsen** [atom/atom#17768]
[Enter steps to reproduce:]

This happens every time I open Atom and it reopens my notes files (plaintext). It happened on the last version and it happens on this version.

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn E2BIG

```
At internal/child_process.js:323

Error: spawn E2BIG
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:514:9)
    at Object.exports.fork (child_process.js:115:10)
    at new Task (/Applications/Atom.app/Contents/Resources/app/src/task.js:37:52)
    at Function.module.exports.Task.once (/Applications/Atom.app/Contents/Resources/app/src/task.js:19:20)
    at Object.startTask (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/path-loader.js:18:35)
    at Object.startLoadPathsTask (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/main.js:129:43)
    at get_process.nextTick (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/main.js:31:45)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

?

### Non-Core Packages

None

**Comment by daviwil** [comment]
What OS are you on?  Are your files paths in the project really long?  (200+ characters)

**Comment by 50Wliu** [comment]
In addition, how large is the file that Atom is trying to open?
In the meantime, you should be able to get around this using `atom --clear-window-state`, but as a word of caution, you'll lose any unsaved changes in your projects.

**Comment by bhartvigsen** [comment]
OS is OSX 10.13.4.

Paths are very short ~/Documents/NOTES for example.  
  
I can't actually find any issues caused from this error, it appears spurious.

**Comment by bhartvigsen** [comment]
Also,

> how large is the file that Atom is trying to open?

Tiny, we're talking less than 10k probably for all my notes. These are like todo lists and stuff.

**Comment by rsese** [comment]
> In the meantime, you should be able to get around this using atom --clear-window-state, but as a word of caution, you'll lose any unsaved changes in your projects.

Did you give this a try @bhartvigsen (or did you not want to risk losing unsaved changes)?

**Comment by bhartvigsen** [comment]
I tried it and the error goes away and I'm left with a blank Atom. So really all this tells us is that the error is triggered when re-opening a handful of tabs of plaintext files, not a whole lot of insight I think that can be drawn from that.

**Comment by bhartvigsen** [comment]
This issue still exists in 1.40.1 which I believe is the latest version. This occurs on OSX 10.13.6.

I can reproduce it by closing Atom and then reopening it. Here is the stack trace:

Error: spawn E2BIG
    at ChildProcess.spawn (internal/child_process.js:357:11)
    at spawn (child_process.js:540:9)
    at Object.fork (child_process.js:121:10)
    at new Task (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:41354)
    at Function.Task.once (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:42100)
    at Object.startTask (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:816751)
    at Object.startLoadPathsTask (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:189167)
    at get_process.nextTick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:187131)
    at process._tickCallback (internal/process/next_tick.js:61:11)
