### ISSUE TITLE
Uncaught Error: URIHandlerRegistry#handleURI asked to handle an invalid URI: atom:%20command%20no...

### ISSUE THREAD

**Issue by jonathangrove3** [atom/atom#17764]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: URIHandlerRegistry#handleURI asked to handle an invalid URI: atom:%20command%20not%20found

```
At /private/var/folders/81/5p2s32ks7ws03jgvrq4blynh0000gn/T/AppTranslocation/85C29F40-D723-47DB-93C9-2B0CAD7E727C/d/Atom.app/Contents/Resources/app/src/uri-handler-registry.js:101

Error: URIHandlerRegistry#handleURI asked to handle an invalid URI: atom:%20command%20not%20found
    at URIHandlerRegistry.handleURI (/private/var/folders/81/5p2s32ks7ws03jgvrq4blynh0000gn/T/AppTranslocation/85C29F40-D723-47DB-93C9-2B0CAD7E727C/d/Atom.app/Contents/Resources/app/src/uri-handler-registry.js:101:19)
    at AtomEnvironment.dispatchURIMessage (/private/var/folders/81/5p2s32ks7ws03jgvrq4blynh0000gn/T/AppTranslocation/85C29F40-D723-47DB-93C9-2B0CAD7E727C/d/Atom.app/Contents/Resources/app/src/atom-environment.js:1356:37)
    at EventEmitter.outerCallback (/private/var/folders/81/5p2s32ks7ws03jgvrq4blynh0000gn/T/AppTranslocation/85C29F40-D723-47DB-93C9-2B0CAD7E727C/d/Atom.app/Contents/Resources/app/src/application-delegate.js:353:53)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?
