### ISSUE TITLE
Uncaught SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by Vallezockt** [atom/atom#17817]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: AMD-RYZEN
**Thrown From**: Atom Core

### Stack Trace

Uncaught SyntaxError: Unexpected strict mode reserved word

```
At C:\Users\ASUS GAMER\AppData\Local\atom\app-1.29.0\resources\app\node_modules\text-buffer\lib\screen-line-builder.js:257

SyntaxError: Unexpected strict mode reserved word
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:124:22)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.29.0/resources/app/src/text-editor-component.js:873:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.29.0/resources/app/src/text-editor-component.js:385:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.29.0/resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didShow (~/AppData/Local/atom/app-1.29.0/resources/app/src/text-editor-component.js:1463:18)
    at TextEditorComponent.didAttach (~/AppData/Local/atom/app-1.29.0/resources/app/src/text-editor-component.js:1430:20)
    at HTMLElement.attachedCallback (/app.asar/src/text-editor-element.js:41:25)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:152:22)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane.js:443:26)
    at Pane.addItem (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane.js:644:43)
    at Pane.activateItem (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane.js:582:18)
    at Workspace.open (~/AppData/Local/atom/app-1.29.0/resources/app/src/workspace.js:1063:20)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-clock 0.1.16 
autocomplete-wordpress-hooks 0.2.3 
busy-signal 1.4.3 
color-picker 2.3.0 
file-icons 2.1.22 
Hydrogen 2.5.1 
intentions 1.1.5 
minimap 4.29.8 
pigments 0.40.2 
teletype 0.13.3 
todo-show 2.3.0 
```

**Comment by maxbrunsfeld** [comment]
It looks like you built Atom from source, and you may have ended up with the wrong version of electron. Can you describe the process you used to build Atom, especially any changes from the instructions?
