### ISSUE TITLE
left-pad error

### ISSUE THREAD

**Issue by Axe-Usa** [atom/atom#17857]
Error: Cannot find module 'leftpad'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/omar/Descargas/bitconyellow-token-master/test/solidity-helper.js:3:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/omar/Descargas/bitconyellow-token-master/test/0xBitcoinToken.js:5:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /usr/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/usr/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:536:10)
    at /usr/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/test.js:125:1
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
truffle(develop)>

**Comment by 50Wliu** [comment]
Unrelated to Atom.
