### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND isatproxy ...

### ISSUE THREAD

**Issue by adhiyoko** [atom/atom#17888]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND isatproxy isatproxy:8080

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND isatproxy isatproxy:8080
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
  3x -3:26.6.0 core:backspace (input.hidden-input)
     -0:37.4.0 core:select-all (input.hidden-input)
  7x -0:34.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-bootstrap3 1.2.12 
atom-bootstrap4 1.4.0 
atom-html-preview 0.2.5 
atom-wordpress 0.3.0 
autocomplete-wordpress-hooks 0.2.3 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
emmet-snippets-compatibility 1.0.6 
v-bootstrap4 0.2.2 
wordpress-api 1.2.2 
wordpress-autocomplete 1.5.0 
wordpress-dictionary 4.4.0 
wordpress-suite 1.3.0 
```

**Comment by rsese** [comment]
Thanks for the report - it looks like you're using a proxy and hitting a DNS issue?   `isatproxy` is also repeated in the error message, maybe double check that you have the [config set](https://github.com/atom/apm/#using-a-proxy) correctly?

Since this seems like a proxy/DNS issue I'm going to close for now but we can re-open if necessary.
