### ISSUE TITLE
Uncaught ReferenceError: newline is not defined

### ISSUE THREAD

**Issue by Shibzbik** [atom/atom#17929]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught ReferenceError: newline is not defined

```
At C:\Users\Shibzbik\.atom\init.coffee:17

ReferenceError: newline is not defined
    at HTMLElement.custom:insert-params (~/.atom/init.coffee:17:12)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.29.0/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.29.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:52.8.0 custom:insert-params (input.hidden-input)
```

### Non-Core Packages

```
teletype 0.13.3 
```

**Comment by maxbrunsfeld** [comment]
It looks like this is an error in your `~/.atom/init.coffee` file.
