### ISSUE TITLE
Atom throws a "Object #<Object> has no method 'union'" error when opening some folders

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1792]
Reported in Halp:
* support/380d2e14ad8b11e390069849e7249ea1

> Attempts to open a folder I was working in just a little while ago are suddenly causing the editor to not work properly. I can open other folders, and even that one if I do it by opening the folder it is contained in. The folder in question is a package I was working on, if that matters.
> When I attempt to open it, and I have tried but from the command line and from Atom's menu, it opens a window which remains entirely white, except the devtools which pop open with this error:

```
TypeError: Object #<Object> has no method 'union'
at Selection.module.exports.Selection.merge (/Applications/Atom.app/Contents/Resources/app/src/selection.js:689:53)
at reducer (/Applications/Atom.app/Contents/Resources/app/src/editor.js:1732:33)
at Array.reduce (native)
at Object._.reduce._.foldl._.inject (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/node_modules/underscore/underscore.js:113:28)
at Editor.module.exports.Editor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/editor.js:1738:16)
at Editor.module.exports.Editor.addSelection (/Applications/Atom.app/Contents/Resources/app/src/editor.js:1121:12)
at new Editor (/Applications/Atom.app/Contents/Resources/app/src/editor.js:87:14)
at Function.module.exports.Serializable.deserialize (/Applications/Atom.app/Contents/Resources/app/node_modules/serializable/lib/serializable.js:72:22)
at DeserializerManager.module.exports.DeserializerManager.deserialize (/Applications/Atom.app/Contents/Resources/app/src/deserializer-manager.js:42:29)
at /Applications/Atom.app/Contents/Resources/app/src/pane.js:86:35
at Array.map (native)
at Pane.module.exports.Pane.deserializeParams (/Applications/Atom.app/Contents/Resources/app/src/pane.js:85:36)
at Function.module.exports.Serializable.deserialize (/Applications/Atom.app/Contents/Resources/app/node_modules/serializable/lib/serializable.js:58:25)
at DeserializerManager.module.exports.DeserializerManager.deserialize (/Applications/Atom.app/Contents/Resources/app/src/deserializer-manager.js:42:29)
at PaneContainer.module.exports.PaneContainer.deserializeParams (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:47:40)
at Function.module.exports.Serializable.deserialize (/Applications/Atom.app/Contents/Resources/app/node_modules/serializable/lib/serializable.js:58:25)
at Workspace.module.exports.Workspace.deserializeParams (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:65:44)
at Function.module.exports.Serializable.deserialize (/Applications/Atom.app/Contents/Resources/app/node_modules/serializable/lib/serializable.js:58:25)
at Atom.module.exports.Atom.deserializeWorkspaceView (/Applications/Atom.app/Contents/Resources/app/src/atom.js:273:42)
at Atom.module.exports.Atom.deserializeEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:287:19)
at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:311:12)
at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:14:8)
at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:20:4)
at Module._compile (module.js:455:26)
at Object.Module._extensions..js (module.js:473:10)
at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
at Function.Module._load (module.js:311:12)
at Module.require (module.js:363:17)
at require (module.js:379:17)
at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:20:5)
index.js:29
```

EDIT: followup from user:

> Ivan, as I mentioned , this was a plugin I was working on. Finding the file in `.atom/storage' that held its state and deleting that file caused the problem to go away

**Comment by izuzak** [comment]
I haven't seen this happen again for almost a year (no mention on discuss either). Also, just had a look at [the code](https://github.com/atom/atom/blob/2dac7fd18eb3607ba0fab8a4d2393934dc6afa5d/src/selection.coffee#L698-L706) and I don't see an obvious way this could happen now. From what I can tell -- `union` should always be called on `Range` objects which [have a `union` method defined](https://github.com/atom/text-buffer/blob/dd765be8242e7d4635b5dce34c9622c94852074a/src/range.coffee#L169). 

@nathansobo do you see anything here perhaps (I remember that you poked at this code at some point) or could we close this and wait for someone to report again with steps to reproduce? The stack trace includes the DeserializerManager, so maybe something :stuck_out_tongue_winking_eye: is going on with that?

**Comment by nathansobo** [comment]
I vaguely remember looking at this, but not much in the way of details. Let's just close it out maybe. I'll let you decide.

**Comment by izuzak** [comment]
Cool, gonna close and see if we can get more information if someone reports this again.
