### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.30.0\res...

### ISSUE THREAD

**Issue by bhupalasuresh** [atom/atom#17943]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\nsbbh\AppData\Local\atom\app-1.30.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:172

Error: The specified module could not be found.
\\?\C:\Users\nsbbh\AppData\Local\atom\app-1.30.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.30.0/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.30.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -2:23.1.0 application:open-folder (atom-pane.pane.active)
  2x -0:49.3.0 find-and-replace:show (input.hidden-input)
     -0:09.8.0 project-find:show (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.0 
atom-ide-ui 0.13.0 
atom-typescript 12.6.3 
compare-files 0.8.1 
line-count 0.5.0 
remote-ftp 2.2.0 
teletype 0.13.3 
```

**Comment by qimuxi1990** [comment]
I downloaded the installer and run it (version 1.30.0 stable). Now atom works fine. I am guessing it lost some packages during updating itself.
