### ISSUE TITLE
Uncaught TypeError: item.getTitle is not a function

### ISSUE THREAD

**Issue by Guar1** [atom/atom#18008]
[Enter steps to reproduce:]
After EDIT AND COMMIT throws this error

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: item.getTitle is not a function

```
At C:\Users\Guar\AppData\Local\atom\app-1.30.0\resources\app\node_modules\tabs\lib\mru-item-view.js:69

TypeError: item.getTitle is not a function
    at MRUItemView.initialize (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/tabs/lib/mru-item-view.js:69:62)
    at MRUListView.buildListView (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/tabs/lib/mru-list-view.js:200:24)
    at ~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/tabs/lib/mru-list-view.js:121:46
```

### Commands

```
     -3:03.9.0 github:toggle-git-tab (input.hidden-input)
     -3:02.9.0 github:toggle-github-tab (input.hidden-input)
  2x -1:56.1.0 core:backspace (input.hidden-input)
  3x -1:52.8.0 editor:move-to-beginning-of-word (input.hidden-input)
  2x -1:51.8.0 editor:move-to-end-of-word (input.hidden-input)
     -1:50.6.0 core:delete (input.hidden-input)
  4x -1:48.6.0 editor:move-to-beginning-of-word (input.hidden-input)
     -1:46.2.0 core:move-up (input.hidden-input)
     -1:45.8.0 core:move-left (input.hidden-input)
  6x -1:44.8.0 editor:move-to-end-of-word (input.hidden-input)
     -1:42.8.0 core:move-left (input.hidden-input)
     -1:41.4.0 core:move-up (input.hidden-input)
     -0:22.2.0 core:save (input.hidden-input)
  2x -0:20 core:close (input.hidden-input)
     -0:16.5.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:15.6.0 pane:move-active-item-to-top-of-stack (div.)
```

### Non-Core Packages

```
autocomplete-python 1.10.11 
darkpython-syntax 0.5.0 
ide-python 1.0.0 
teletype 0.13.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible and if it's reproducible in safe mode (`atom --safe`)?

**Comment by rsese** [comment]
Just so I'm on the same page, this is reproducible in safe mode (`atom --safe`)?  Also, can you clarify the steps to reproduce and share step-by-step instructions to generate the error?
