### ISSUE TITLE
Uncaught TypeError: this.item.getTitle is not a function

### ISSUE THREAD

**Issue by mtriggiano** [atom/atom#18011]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.item.getTitle is not a function

```
At C:\Users\migue\AppData\Local\atom\app-1.30.0\resources\app\node_modules\tabs\lib\tab-view.js:329

TypeError: this.item.getTitle is not a function
    at TabView.module.exports.TabView.updateTitle (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/tabs/lib/tab-view.js:329:33)
    at TabBarView.module.exports.TabBarView.insertTabAtIndex (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:271:17)
    at TabBarView.module.exports.TabBarView.moveItemTabToIndex (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:255:27)
    at ~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:170:30
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Pane.moveItem (~/AppData/Local/atom/app-1.30.0/resources/app/src/pane.js:728:24)
    at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:780:24)
    at TabBarView.module.exports.TabBarView.onDrop (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:660:29)
```

### Commands

```
     -8:52.2.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:49.3.0 github:clone (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -8:41.6.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

x-ref: https://github.com/atom/atom/issues/18008 - same error message but different stack trace.
