### ISSUE TITLE
Uncaught TypeError: text.split is not a function

### ISSUE THREAD

**Issue by baggepinnen** [atom/atom#18046]
I put this in my init.coffee

```coffeescript
atom.commands.add 'atom-text-editor', 'custom:docstring', ->
  editor = atom.workspace.getActiveTextEditor()
  editor.selectLinesContainingCursors()
  text = editor.getSelectedText()
  text = text.replace /function /, ""
  functionname = text.match(/\w+/)
  editor.insertText(functionname)
  docstring = "\"\"\"\n    #{text}\n\"\"\""
  editor.moveUp()
  editor.insertText(docstring)
  editor.moveUp(2)
  editor.moveToBeginningOfLine()
```

The offending line seems to be `  functionname = text.match(/\w+/)`
Then I execute the command from an editor

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: "Fedora release
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: text.split is not a function

```
At /usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:982

TypeError: text.split is not a function
    at Selection.insertText (/usr/share/atom/resources/app/src/selection.js:461:39)
    at result.mutateSelectedText.selection (/usr/share/atom/resources/app/src/text-editor.js:1382:37)
    at getSelectionsOrderedByBufferPosition.map (/usr/share/atom/resources/app/src/text-editor.js:1430:92)
    at Array.map (<anonymous>)
    at transact (/usr/share/atom/resources/app/src/text-editor.js:1430:66)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:975:24)
    at TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:2002:30)
    at mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:1429:25)
    at TextEditor.mergeSelections (/usr/share/atom/resources/app/src/text-editor.js:3419:26)
    at TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:3390:42)
    at TextEditor.mutateSelectedText (/usr/share/atom/resources/app/src/text-editor.js:1428:23)
    at TextEditor.insertText (/usr/share/atom/resources/app/src/text-editor.js:1381:31)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at HTMLElement.<anonymous> (/local/home/fredrikb/.atom/init.coffee:26:10)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:17.4.0 core:move-up (input.hidden-input)
     -0:16.8.0 core:move-down (input.hidden-input)
  4x -0:16.6.0 editor:move-to-end-of-word (input.hidden-input)
  2x -0:15.7.0 core:move-left (input.hidden-input)
     -0:14.7.0 custom:docstring (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
auto-indent 0.5.0 
document-outline 2.1.2 
file-icons 2.1.24 
highlight-selected 0.14.0 
indent-detective 0.2.2 
ink 0.9.6 
julia-client 0.7.6 
language-julia 0.17.0 
language-latex 1.1.1 
language-stan 1.2.0 
language-weave 0.4.3 
latex 0.50.0 
latex-completions 0.3.5 
markdown-pdf 2.2.0 
markdown-preview-plus 3.6.3 
open-in-browser 0.5.2 
pdf-view 0.71.0 
project-manager 3.3.6 
todo-show 2.3.2 
```

**Comment by maxbrunsfeld** [comment]
Yeah, this is an error in your init script. [`String.match`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) returns an `Array`, so the `functionname` variable will be an Array, not a string.

**Comment by baggepinnen** [comment]
Thanks! I figured it might be my fault, but the flashy error pop-up pursuaded me to submit an issue, saying "it is likely a bug in atom" 😜
