### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=503

### ISSUE THREAD

**Issue by nimingqigithub** [atom/atom#18057]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=503

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at Socket.socketOnData (_http_client.js:472:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -4:57.4.0 window:install-shell-commands (div.package-detail.panels-item)
 14x -3:02.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-chs-menu 1.0.0 
atom-simplified-chinese-menu 0.6.5 
simplified-chinese-menu 5.3.5 
```

**Comment by rsese** [comment]
Thanks for the report! Are you using a network proxy?  This seems like it could be a temporary network issue, please try again later and see if you continue getting the same error.
