### ISSUE TITLE
Crash in directories with invalid package.json

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#18058]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If you attempt to open Atom in a directory containing a `package.json` that has invalid syntax it will crash with an error about a JavaScript error in the main process when calling this line:
https://github.com/atom/atom/blob/e6507c59cb846cd02b84f4a3b10dd43b2572a939/src/main-process/main.js#L23

### Steps to Reproduce

1. Save a `package.json` with invalid syntax (for example, a trailing `,`)
3. Open an Atom window in the directory containing the invalid `package.json`

#### Expected behavior:
No error is thrown.

#### Actual behavior:
The following error is thrown:
![image](https://user-images.githubusercontent.com/427137/45584137-a13a9e00-b883-11e8-9323-cbd11cab2912.png)

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
SyntaxError: Unexpected token } in JSON at position 2838
    at JSON.parse (<anonymous>)
    at parseObject (C:\Users\Lando\AppData\Local\atom\app-1.32.0-nightly9\resources\app.asar\node_modules\season\lib\cson.js:54:19)
    at parseContentsSync (C:\Users\Lando\AppData\Local\atom\app-1.32.0-nightly9\resources\app.asar\node_modules\season\lib\cson.js:68:16)
    at Object.readFileSync (C:\Users\Lando\AppData\Local\atom\app-1.32.0-nightly9\resources\app.asar\node_modules\season\lib\cson.js:180:14)
    at isAtomRepoPath (C:\Users\Lando\AppData\Local\atom\app-1.32.0-nightly9\resources\app.asar\src\main-process\main.js:23:28)
    at Object.<anonymous> (C:\Users\Lando\AppData\Local\atom\app-1.32.0-nightly9\resources\app.asar\src\main-process\main.js:42:14)
    at Object.<anonymous> (C:\Users\Lando\AppData\Local\atom\app-1.32.0-nightly9\resources\app.asar\src\main-process\main.js:60:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)

[OK]
```

**Reproduces how often:**
100% of the time.

### Versions

OS: Windows 10 Professional
```
Atom    : 1.32.0-nightly9
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.0-nightly9
python
git 2.18.0.windows.1
visual studio
```

### Additional Information

This bug was introduced in https://github.com/atom/atom/pull/17892.

**Comment by daviwil** [comment]
One other thing to note is that you have to make sure no `ATOM_DEV_RESOURCE_PATH` environment variable is set when you open Atom in a folder with a bad `package.json` file.  I was wondering why it didn't repro for me until I realized I had that set :)
