### ISSUE TITLE
Editor unusable with custom tree-sitter grammar

### ISSUE THREAD

**Issue by th-we** [atom/atom#18098]
With my custom Tree-sitter grammar enabled, I can not edit the properly highlighted files because I constantly get errors. This is how to reproduce the problem on Ubuntu 18.04.1 with Atom 1.30.0.

The following describes the installation of the grammar and the corresponding atom package. The language-manuscript package in its current form assumes that `npm install -g` installs to `/usr/local/lib/node_modules`

1. Activate Tree-sitter in the core settings
1. `git clone https://github.com/notengrafik/tree-sitter-manuscript`
1. `cd tree-sitter-manuscript`
1. `npm install tree-sitter-cli`
1. `node_modules/.bin/tree-sitter generate`
1. `sudo npm install -g`
1. `cd ..`
1. `git clone https://github.com/notengrafik/language-manuscript`
1. `cd language-manuscript`
1. `sudo npm install -g`
1. `cd ..`
1. Create the directory `~/.atom/packages` if it's not there yet
1. `ln -s /usr/local/lib/node_modules/language-manuscript ~/.atom/packages`
1. `wget https://raw.githubusercontent.com/music-encoding/sibmei/master/src/Run.mss`
1. Close running atom or reload the packages
1. `atom Run.mss`
1. Edit the file in Atom
1. Receive errors

The errors can differ, but they are always of the form "Uncaught TypeError: Cannot read property '*' of undefined".

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Ubuntu 18.04.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /usr/share/atom/resources/app/node_modules/snippets/lib/snippets.js:337

TypeError: Cannot read property '0' of undefined
    at /usr/share/atom/resources/app/node_modules/snippets/lib/snippets.js:337:24
    at Array.map (<anonymous>)
    at Object.getScopeChain (/usr/share/atom/resources/app/node_modules/snippets/lib/snippets.js:336:32)
    at Object.parsedSnippetsForScopes (/usr/share/atom/resources/app/node_modules/snippets/lib/snippets.js:366:87)
    at SnippetsProvider.getSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-snippets/lib/snippets-provider.js:25:53)
    at providers.forEach.provider (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:58)
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:280:21)
    at AutocompleteManager.findSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:272:23)
    at AutocompleteManager.requestNewSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:719:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:785:18)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1794:32)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:998:18)
    at TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:2002:30)
    at mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:1429:25)
    at TextEditor.mergeSelections (/usr/share/atom/resources/app/src/text-editor.js:3419:26)
    at TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:3390:42)
    at TextEditor.mutateSelectedText (/usr/share/atom/resources/app/src/text-editor.js:1428:23)
    at TextEditor.insertText (/usr/share/atom/resources/app/src/text-editor.js:1381:31)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/usr/share/atom/resources/app/src/text-editor-component.js:1650:30)
```

### Commands

```
  6x -2:19.1.0 core:undo (input.hidden-input)
     -0:12.2.0 core:move-up (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.0 
atom-ide-ui 0.5.3 
atom-typescript 12.5.3 
language-manuscript 0.0.0 
```

**Comment by th-we** [comment]
O.K., I updated to 1.31 and the problem went away. Should it re-occur, I'll re-open this issue.
