### ISSUE TITLE
WSL Ubuntu aliases stop working after update to 1.31

### ISSUE THREAD

**Issue by chanleyou** [atom/atom#18126]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

My aliases to open Atom in Ubuntu Windows Subsystem for Linux stop working after updating from 1.30 to 1.31. Using commands like "atom ." instead give me the following error:
`
net.js:200
    this._handle.open(options.fd);
                 ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:200:18)
    at createWritableStdioStream (internal/process/stdio.js:164:16)
    at process.getStdout [as stdout] (internal/process/stdio.js:14:14)
    at console.js:246:38
    at NativeModule.compile (bootstrap_node.js:596:7)
    at Function.NativeModule.require (bootstrap_node.js:541:18)
    at setupGlobalConsole (bootstrap_node.js:310:41)
    at startup (bootstrap_node.js:70:7)
    at bootstrap_node.js:608:3
`

my alias for opening atom in WSL Ubuntu is: `alias atom='/mnt/c/Windows/System32/cmd.exe /c "atom"'`. 

### Steps to Reproduce

Updating to 1.31 produces this issue. Rolling back to 1.30 resolves this until atom updates to 1.31.

### Versions

Atom    : 1.31.0
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

I'm running Windows 10.

**Comment by rsese** [comment]
Thanks for the report - confirming that I can reproduce with 1.31.0 and 1.32.0-beta0 , and the error isn't present in 1.30.

**Comment by JacobDB** [comment]
Glad this isn't just me, been pulling my hair out all day trying to figure out what was going on.

I'm seeing this too, although it only appears to be occurring in 16.04, not 18.04.

**Comment by Tekki** [comment]
The same for WSL Debian.

**Comment by start0821** [comment]
I also have this error. Thank you for reporting

**Comment by lululuchi** [comment]
Ditto.
Ubuntu 16.04.5 LTS.

**Comment by thomasmarkrea** [comment]
Also getting this error.
Atom: 1.31
Ubuntu: 16.04.3 LTS

If you still have version 1.30.0 on your machine, you can roll back the `atom` command with this:
`%LocalAppData%\atom\app-1.30.0\atom.exe --squirrel-install 1.30.0`

It will point the command back to your old version so long as you still have it installed in the default location.

**Comment by seano424** [comment]
When I run this: 
%LocalAppData%\atom\app-1.30.0\atom.exe --squirrel-install 1.30.0
I get:
-bash: fg: %LocalAppData%atomapp-1.30.0atom.exe: no such job
Any ideas on what I can do?

**Comment by start0821** [comment]
> When I run this:
> %LocalAppData%\atom\app-1.30.0\atom.exe --squirrel-install 1.30.0
> I get:
> -bash: fg: %LocalAppData%atomapp-1.30.0atom.exe: no such job
> Any ideas on what I can do?

If you use cmd, it will work. And before enter the command `%LocalAppData%\atom\app-1.30.0\atom.exe --squirrel-install 1.30.0` which @thomasmarkrea said, check where %LocalAppData%\atom\app-1.30.0\atom.exe exactly locate.
"%LocalAppData%" usually means `C:\\users\\username\\AppData\\Local\\`   .

**Comment by seano424** [comment]
So I should run cmd %LocalAppData%\atom\app-1.30.0\atom.exe --squirrel-install 1.30.0 
?

**Comment by Tekki** [comment]
@seano424 You should open the Windows command line ("DOS Prompt") and enter this command. Or in PowerShell use `& "$env:LocalAppData\atom\app-1.30.0\atom.exe" --squirrel-install 1.30.0`. By the way, I notice that on my machine the folder for 1.30.0 has disappeared.

**Comment by JacobDB** [comment]
This appears to be *kind of* fixed in Atom 1.31.2, but now when I run my `atom` alias it hangs and forces me to close out of the terminal and open a new one (ctrl+c doesn't even work)

**Comment by ConnorIngold** [comment]
Also sure to turn off automatic updates by clicking on the squirrel icon in the bottom right-hand corner and then unselecting the automatic updates box.

**Comment by JacobDB** [comment]
Any status update on this? Been over a month at this point.

**Comment by HRussell63250** [comment]
Adding this to the bash rc file is a very simple workaround:
alias atom='powershell.exe start atom'

**Comment by francisli** [comment]
> 
> 
> This appears to be _kind of_ fixed in Atom 1.31.2, but now when I run my `atom` alias it hangs and forces me to close out of the terminal and open a new one (ctrl+c doesn't even work)

I'm having this issue with Atom 1.34 in Ubuntu 1804 LTS WSL in Windows 10 1809 as well. Note that once you close atom, the command line returns. CTRL-Z to stop and background the app does NOT work. Also, running atom & results in the crash above and it doesn't launch.

This was reported to WSL in this issue (https://github.com/Microsoft/WSL/issues/3769) but it seems to be more of an Atom issue...?

**Comment by JacobDB** [comment]
@francisli I seem to be having trouble with my alias for VS Code as well, which makes me think it may be more on Microsoft's side

**Comment by GuttermanA** [comment]
@JacobDB 

Your solution Microsoft/wsl#1832 under WSL is a good work around still. This can also work with any problem opening apm under WSL which I've had trouble with as well.

Copied here:

> I figured this out :) Here's a guide:
> 
> 1. Open `~/.bashrc` in a text editor
> 2. At the bottom, add a new function:
>    ```
>    function atom() {
>         /mnt/c/System32/cmd.exe /C atom.cmd $1
>     }
>    ```
> 3. Save the file and exit the text editor
> 4. Run `. ~/.bashrc`
> 
> The command `atom` will now work properly!

**Comment by JacobDB** [comment]
@GuttermanA I just did some experimentation and came up with a solution for the second half. If you run the program in the background, it works correctly. Like so:

```
atom() {
    target_path=$(wslpath -a -w $(readlink -f $1)) # resolve the path
    (/mnt/c/Windows/System32/cmd.exe /C "atom.cmd $target_path" &) # open the path
}
```

**Comment by ask03** [comment]
> Adding this to the bash rc file is a very simple workaround:
> alias atom='powershell.exe start atom'

confirmed this method works, but you have to bear with looking at powershell window for a split second.
