### ISSUE TITLE
Uncaught TypeError: this.grammar.onDidUpdate is not a function

### ISSUE THREAD

**Issue by willsolarski** [atom/atom#18133]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.0 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.grammar.onDidUpdate is not a function

```
At C:\Users\will\AppData\Local\atom\app-1.31.0\resources\app\src\text-mate-language-mode.js:41

TypeError: this.grammar.onDidUpdate is not a function
    at new TextMateLanguageMode (~/AppData/Local/atom/app-1.31.0/resources/app/src/text-mate-language-mode.js:41:45)
    at GrammarRegistry.languageModeForGrammarAndBuffer (~/AppData/Local/atom/app-1.31.0/resources/app/src/grammar-registry.js:173:20)
    at GrammarRegistry.assignLanguageMode (~/AppData/Local/atom/app-1.31.0/resources/app/src/grammar-registry.js:138:41)
    at new CodeBlock (~/AppData/Local/atom/app-1.31.0/resources/app/node_modules/styleguide/lib/code-block.js:13:25)
    at render (~/AppData/Local/atom/app-1.31.0/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:17:31)
    at addChildren (~/AppData/Local/atom/app-1.31.0/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:39:30)
    at render (~/AppData/Local/atom/app-1.31.0/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:29:27)
    at addChildren (~/AppData/Local/atom/app-1.31.0/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:39:30)
    at render (~/AppData/Local/atom/app-1.31.0/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:29:27)
    at updateChildren (~/AppData/Local/atom/app-1.31.0/resources/app/node_modules/styleguide/node_modules/etch/lib/patch.js:109:40)
    at patch (~/AppData/Local/atom/app-1.31.0/resources/app/node_modules/styleguide/node_modules/etch/lib/patch.js:15:15)
    at updateSync (~/AppData/Local/atom/app-1.31.0/resources/app/node_modules/styleguide/node_modules/etch/lib/component-helpers.js:108:26)
    at ~/AppData/Local/atom/app-1.31.0/resources/app/node_modules/styleguide/node_modules/etch/lib/component-helpers.js:72:13
    at DefaultScheduler.performUpdates (~/AppData/Local/atom/app-1.31.0/resources/app/node_modules/styleguide/node_modules/etch/lib/default-scheduler.js:48:40)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.2 
autocomplete-python 1.10.12 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
emmet 2.4.3 
file-icons 2.1.25 
fonts 3.1.0 
Hydrogen 2.6.0 
intentions 1.1.5 
linter 2.2.0 
linter-flake8 2.3.0 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
minimap 4.29.9 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
python-autopep8 0.1.3 
script 3.18.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

**Comment by willsolarski** [comment]
I was trying to run flask8 in conjunction with a python script. It was recurring so my solution was to uninstall linter flask 8 and the  corresponding software.

**Comment by wdhongtw** [comment]
Hi Maintainers.

I have same issue here, and is reproducible in safe mode.
This exception is thrown every time I open Atom.

[Enter steps to reproduce:]

1. Install Atom from official apt repo
    ```
    > cat /etc/apt/sources.list.d/atom.list 
    deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
    > apt show atom
    Package: atom
    Version: 1.31.2
    ```
2. open Atom in safe mode `atom --safe`

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Ubuntu 18.04.1
**Thrown From**: Atom Core
**User**: root

### Stack Trace

Uncaught TypeError: this.grammar.onDidUpdate is not a function

```
At /usr/share/atom/resources/app/src/text-mate-language-mode.js:41

TypeError: this.grammar.onDidUpdate is not a function
    at new TextMateLanguageMode (/usr/share/atom/resources/app/src/text-mate-language-mode.js:41:45)
    at GrammarRegistry.languageModeForGrammarAndBuffer (/usr/share/atom/resources/app/src/grammar-registry.js:173:20)
    at GrammarRegistry.assignLanguageMode (/usr/share/atom/resources/app/src/grammar-registry.js:138:41)
    at new CodeBlock (/usr/share/atom/resources/app/node_modules/styleguide/lib/code-block.js:13:25)
    at render (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:17:31)
    at addChildren (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:39:30)
    at render (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:29:27)
    at addChildren (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:39:30)
    at render (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:29:27)
    at updateChildren (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/patch.js:109:40)
    at patch (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/patch.js:15:15)
    at updateSync (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/component-helpers.js:108:26)
    at /usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/component-helpers.js:72:13
    at DefaultScheduler.performUpdates (/usr/share/atom/resources/app/node_modules/styleguide/node_modules/etch/lib/default-scheduler.js:48:40)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by diomark** [comment]
I had the exact same problem. Issue was with 'fuzzy grep' combined with 'git' command line tool installed and in path in windows. I disabled 'fuzzy grep' and the issue disappeared. ( atom-fuzzy-grep)

**Comment by wdhongtw** [comment]
Hi @rsese 

I tried to figure out which file triggered the exception (yes, Atom did open my existing project in safe mode), but fail to reproduce this bug now. The environment seems been destroyed.

Here are some details I remember, just for your information.

- I can reproduce every time when opening atom (first instance) even after apt remove atom and reinstall atom.
- I opened another atom instance for other project, no exception was thrown.
- I closed all atom instance and reopen atom, and no exception was thrown. Fail to reproduce this bug since then.
- In the project mentioned above that trigger the exception, I have about 5 markdown file open in one pane at startup, and 2 markdown preview opened in another pane (also at startup).

**Comment by rsese** [comment]
@bdanny2 - do you have specific steps to reproduce in safe mode?

@willsolarski - just to clarify, you're no longer seeing this error after uninstalling a particular community package?

**Comment by bdanny2** [comment]
The error occurred again until I disabled the grammar-selector package.
After disabling the grammar package the error stopped. Thank you

**Comment by Michael-Ludgate** [comment]
1. View Style Guide, access from menu or shortcut CTRL+SHIFT+G.
2. Leaving Style Guide open, close Atom.
3. Restart Atom, error raised as below.
4. Closing style guide before closing Atom resolved issue, found to be replicable.

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: this.grammar.onDidUpdate is not a function

```
At C:\Users\Michael\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:11

TypeError: this.grammar.onDidUpdate is not a function
    at new TextMateLanguageMode (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:546335)
    at GrammarRegistry.languageModeForGrammarAndBuffer (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:353181)
    at GrammarRegistry.assignLanguageMode (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:352642)
    at new CodeBlock (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:846362)
    at render (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:3026889)
    at addChildren (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:3027243)
    at render (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:3027116)
    at addChildren (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:3027243)
    at render (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:3027116)
    at updateChildren (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:3557379)
    at patch (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:3557474)
    at updateSync (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:3027932)
    at ~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:3029137
    at DefaultScheduler.performUpdates (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:3559091)
```

### Commands

```
```

### Non-Core Packages

```
language-markdown 0.26.0 
```

**Comment by rsese** [comment]
Awesome, thanks @Michael-Ludgate :bow:  Updated the issue body with your repro steps.

**Comment by willsolarski** [comment]
Hey Robert,

Thanks for getting back, I'll tell you what I know:

I received the error when I first logged on.
I haven't gotten the error since so I wasn't able to see if it happened in
safe mode.

That's all I got, I hope that helps.

Thanks,
Will Solarski

**Comment by dyslab** [comment]
Same issue as above. 

Atom: 1.34.0 x64
OS: Ubuntu 18.10
![screenshot from 2019-02-11 03-35-24](https://user-images.githubusercontent.com/45236395/52538504-7ad74b00-2dae-11e9-8ad3-588de4df3846.png)

**Comment by pkwak1** [comment]
Hi, I don't know if this is an issue in terms of being able to publish a theme in Atom's web page for theme packages, but I also ran into this issue when trying to update a new theme I'm making for Atom.

Atom: 1.35.1 x64
Electron: 2.0.18
Chrome: 61.0.3163.100
Node: v8.9.3
OS: MacOS Mojave 10.14.3

/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11
Hide Stack Trace
TypeError: this.grammar.onDidUpdate is not a function
    at new TextMateLanguageMode (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:549212)
    at GrammarRegistry.languageModeForGrammarAndBuffer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:355871)
    at GrammarRegistry.assignLanguageMode (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:355332)
    at new CodeBlock (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:843176)
    at render (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3018016)
    at addChildren (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3018370)
    at render (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3018243)
    at addChildren (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3018370)
    at render (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3018243)
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3582432)
    at patch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3582527)
    at updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3019059)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3020264
    at DefaultScheduler.performUpdates (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3584144)

Which also lead to when running apm publish minor in the terminal the following error messages:
npm ERR! Git working directory not clean.
npm ERR! M package.json
npm ERR! M styles/ui-variables.less

**Comment by ferenczy** [comment]
The issue is still present in the version 1.34.0 x64 on Windows 7 Ultimate 64-bit.

**Comment by BenRussert** [comment]
> when you exit with the styleguide enabled, the next restart of atom tries to load a resource from the ...**/static**

@JassMan23 I wonder if this would be an easy PR since you've found the issue? Otherwise, anyone else looking into this, [see JassMan's on-point comment above](https://github.com/atom/atom/issues/18133#issuecomment-440848187)

**Comment by JassMan23** [comment]
Sorry but I am an almost total noob and wouldn't want to destroy something that works reasonably well other than for the minor niggles like this one. BTW what is a PR? [showing my noobiness]

**Comment by BenRussert** [comment]
I meant maybe you could fix the issue in atom or the styleguide package and send a "pull request". Might be more difficult that I hoped, maybe not worth the time, but it seemed like you had a head start 🤷‍♂️

**Comment by bdanny2** [comment]
Thanks for responding.  I have to try and reproduce it.
Andrew

**Comment by allefeld** [comment]
For me this error popped up when I added "!important" to a CSS/LESS property. The styling works though.

**Comment by WilSnoop** [comment]
@allefeld - 
- Would you mind being specific by giving an extract / example? 
- When does this error come up - once after saving the file or each time the style is applied?
- Confirm please: the behaviour is not there if the `!important` is not there?

**Comment by bdanny2** [comment]
Thanks for replying,
I'll try to reproduce it again.

**Comment by allefeld** [comment]
@WilSnoop, I now believe I was wrong, the error just happened to pop up when I did that CSS modification. Sorry.

I did have the Styleguide open in a tab though, so I can support it seems to be related to that.
I also think that it happened when I reloaded Atom ("Window Reload", Ctrl-Shift-F5).

Unfortunately, I wasn't able to reproduce the problem.

**Comment by bdanny2** [comment]
I am wondering if it is my distribution. Linux Debian Buster

**Comment by allefeld** [comment]
@WilSnoop, I was able to reproduce the problem:

1) Start Atom on a folder that hasn't been used before, e.g. `atom new-folder`.
2) Open the Styleguide tab (Ctrl-Shift-G).
3) Exit Atom
4) Start Atom again on the same folder: The error "Uncaught TypeError: this.grammar.onDidUpdate is not a function" pops up.
5) Close the Styleguide tab.
6) Exit Atom
4) Start Atom again on the same folder: no error.

Instead of exiting and starting again one can also use "Window Reload" (Ctrl-Shift-F5).
The situation is the same with `--safe`.

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Debian GNU/Linux 10.2
**Thrown From**: Atom Core


### Stack Trace

```
At /usr/share/atom/resources/app/static/<embedded>:11

TypeError: this.grammar.onDidUpdate is not a function
    at new TextMateLanguageMode (/usr/share/atom/resources/app/static/<embedded>:11:549968)
    at GrammarRegistry.languageModeForGrammarAndBuffer (/usr/share/atom/resources/app/static/<embedded>:11:355518)
    at GrammarRegistry.assignLanguageMode (/usr/share/atom/resources/app/static/<embedded>:11:354719)
    at new CodeBlock (/usr/share/atom/resources/app/static/<embedded>:14:939384)
    at render (/usr/share/atom/resources/app/static/<embedded>:14:2697548)
    at addChildren (/usr/share/atom/resources/app/static/<embedded>:14:2697902)
    at render (/usr/share/atom/resources/app/static/<embedded>:14:2697775)
    at addChildren (/usr/share/atom/resources/app/static/<embedded>:14:2697902)
    at render (/usr/share/atom/resources/app/static/<embedded>:14:2697775)
    at updateChildren (/usr/share/atom/resources/app/static/<embedded>:14:3172361)
    at patch (/usr/share/atom/resources/app/static/<embedded>:14:3172456)
    at updateSync (/usr/share/atom/resources/app/static/<embedded>:14:2698591)
    at /usr/share/atom/resources/app/static/<embedded>:14:2699796
    at DefaultScheduler.performUpdates (/usr/share/atom/resources/app/static/<embedded>:14:3174073)
```

**Comment by WilSnoop** [comment]
@allefeld - 
I can reproduce the behaviour from the steps you have given. 
Atom V1.40 on Windows 10 Pro.

I am assuming that the grammar update check is done on a pane that does not contain an editor. I have observed that events may trigger on startup of Atom without the precondition being made properly. My own scripts now check that the event is legal (as far as it is viable).

Thank you for producing a concrete method for the guys to use.

**Comment by WilSnoop** [comment]
An earlier & important message that was hidden for some reason..
From @rsese 
> We already have repro steps so no need for more details but thanks for the offer @Sai-Tumuluri ⚡️ The maintainers just haven't been able to prioritize this with the work they have on their plate but we're always open to well-written pull requests.
