### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\linter-clang\README.md'

### ISSUE THREAD

**Issue by cspartho** [atom/atom#18151]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Education
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Haloom\.atom\packages\linter-clang\README.md'

```
At fs.js:646

Error: ENOENT: no such file or directory, open 'C:\Users\Haloom\.atom\packages\linter-clang\README.md'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Proxy.fs.readFileSync (fs.js:551:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:545:29)
    at PackageDetailView.renderReadme (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/settings-view/lib/package-detail-view.js:527:44)
    at PackageDetailView.updateInstalledState (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/settings-view/lib/package-detail-view.js:514:18)
    at ~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/settings-view/lib/package-detail-view.js:564:24
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/settings-view/lib/package-manager.js:659:33)
    at ~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/settings-view/lib/package-manager.js:498:32
    at exit (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.31.1/resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (~/AppData/Local/atom/app-1.31.1/resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -9:48 encoding-selector:show (div.line)
     -9:46.5.0 editor:consolidate-selections (input.hidden-input)
     -9:46.5.0 core:cancel (input.hidden-input)
     -9:44.8.0 github:view-unstaged-changes-for-current-file (div.line)
     -9:40.2.0 symbols-view:go-to-declaration (div.line)
     -9:02.8.0 core:confirm (input.hidden-input)
     -5:06.9.0 pane:split-up-and-copy-active-item (code.lang-bash)
  2x -5:03.7.0 core:cancel (atom-pane.pane.active)
     -4:59.8.0 pane:close (div.package-readme.native-key-bindings)
     -3:53.6.0 core:paste (input.hidden-input)
     -3:49.1.0 core:confirm (input.hidden-input)
     -1:34.2.0 core:backspace (input.hidden-input)
     -1:24.2.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.5 
gpp-compiler 3.0.7 
linter-clang 4.1.2 
```

**Comment by jurra** [comment]
I have the same problem when running. I checked the path of the file and it is there.
![problem](https://user-images.githubusercontent.com/18581201/47642143-2c3bd300-db68-11e8-836f-a2d1fcc76e88.png)
 atom-jscad package

The console throws also js 646
![image](https://user-images.githubusercontent.com/18581201/47642224-62795280-db68-11e8-929f-d334c3859c8a.png)

When I click on js 646, it takes me here: 
![image](https://user-images.githubusercontent.com/18581201/47642252-7ae96d00-db68-11e8-943b-35337f10a8dd.png)

Any ideas of what is going on?

**Comment by rsese** [comment]
@jurra: can you open a new issue with the issue template filled out so we can take a look?  Please also confirm in the issue if you can reproduce in safe mode.

**Comment by jurra** [comment]
@rsese, if I run it on safe mode I will not be able to use a package. I am currently trying to use atom-jscad, and it is throwing this error. Can you point me to the issue template please?

**Comment by Aerijo** [comment]
@jurra If the issue is caused by a package, please raise it on that packages repo. The maintainers can then track it down and decide if it’s still a bug in Atom, in which case they can raise the necessary issue.

**Comment by jurra** [comment]
@Aerijo Thanks I will do that

**Comment by rsese** [comment]
Ahh sorry, missed that you referenced that package in your comment @jurra :+1:   But like @Aerijo mentioned, if you're seeing an error specifically with a community package, the best place to report that issue to the package maintainers in their repository (if it ends up being an Atom issue they can let us know).

About the issue template, when you create an issue in an Atom repository, the template will pre-populate the issue body e.g. https://github.com/atom/atom/issues/new?template=bug_report.md.
