### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:1080

### ISSUE THREAD

**Issue by jarvisAitake** [atom/atom#18155]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:1080

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:1080
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -4:07.1.0 core:cut (input.hidden-input)
     -4:05.1.0 core:paste (input.hidden-input)
  2x -4:04.6.0 core:move-right (input.hidden-input)
     -4:03.7.0 core:backspace (input.hidden-input)
     -4:02.6.0 core:save (input.hidden-input)
  7x -2:29.4.0 core:backspace (input.hidden-input)
     -2:27.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.2 
atom-runner 2.7.1 
autocomplete-paths 2.12.2 
docblockr 0.13.7 
emmet 2.4.3 
file-icons 2.1.25 
minimap 4.29.9 
platformio-ide-terminal 2.8.4 
simplified-chinese-menu 5.3.5 
```

**Comment by rsese** [comment]
Thanks for the report! Are you using a network proxy? This seems like it could be a temporary network issue, please try again later and see if you continue getting the same error.
