### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by ferrucc-io** [atom/atom#18160]
Opening proto-repl and clicking to write some code next to "user=> " I get this error

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/selection.js:506

TypeError: Cannot read property 'start' of undefined
    at Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:506:71)
    at result.mutateSelectedText.selection (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1387:37)
    at getSelectionsOrderedByBufferPosition.map (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1435:92)
    at Array.map (<anonymous>)
    at transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1435:66)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:975:24)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2007:30)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1434:25)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3421:53)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3395:42)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1433:23)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1386:31)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher.js:111:25
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:975:24)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2007:30)
    at BracketMatcher.module.exports.BracketMatcher.insertText (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher.js:109:27)
    at TextEditor.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher.js:3:65)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:76:26)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1661:30)
```

### Commands

```
     -4:06.5.0 core:backspace (input.hidden-input)
  2x -4:05.6.0 editor:newline (input.hidden-input)
  2x -4:04.7.0 core:backspace (input.hidden-input)
  2x -4:03.9.0 proto-repl:execute-text-entered-in-repl (input.hidden-input)
     -3:49.4.0 core:move-left (input.hidden-input)
     -3:48.9.0 core:backspace (input.hidden-input)
  3x -3:47.1.0 intentions:show (input.hidden-input)
     -3:45.9.0 core:move-right (input.hidden-input)
     -3:45.5.0 intentions:show (input.hidden-input)
     -3:29.3.0 proto-repl:toggle-auto-scroll (input.hidden-input)
     -3:25.4.0 proto-repl:toggle (input.hidden-input)
     -3:11.7.0 core:copy (input.hidden-input)
     -2:52.3.0 window:toggle-dev-tools (input.hidden-input)
     -0:18.7.0 editor:consolidate-selections (input.hidden-input)
     -0:18.7.0 core:cancel (input.hidden-input)
  8x -0:11.2.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-joker 0.1.4 
linter-ui-default 1.7.1 
parinfer 1.23.0 
proto-repl 1.4.24 
```

**Comment by rsese** [comment]
Thanks for contributing!

Since this seems specific to using proto-repl and there doesn't seem to be any similar issues in atom/atom that I could find, for now we recommend that you file this issue on their repository so they can either fix the problem or tell us where the problem is coming from.  It may be that there is still a bug in Atom but if so, we'll need the proto-repl maintainers to help track that down. 

The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

Also, based on a quick look through the package issues, this report looks pretty similar:

https://github.com/jasongilman/proto-repl/issues/286

**Comment by alenahall105** [comment]
TypeError: Cannot read property 'start' of undefined

who can explain this?

**Comment by PhotonicTransmission** [comment]
I got it too, using no fancy IDE packages or anything like that, on save:

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Education
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At D:\Atom x64\resources\app\static\<embedded>:14

TypeError: Cannot read property 'start' of undefined
    at TagFinder.isTagRange (D:/Atom x64/resources/app/static/<embedded>:14:508858)
    at TagFinder.findEnclosingTags (D:/Atom x64/resources/app/static/<embedded>:14:510725)
    at BracketMatcherView.gotoPrecedingStartBracket (D:/Atom x64/resources/app/static/<embedded>:11:665488)
    at BracketMatcherView.goToMatchingBracket (D:/Atom x64/resources/app/static/<embedded>:11:664094)
    at HTMLElement.BracketMatcherView.subscriptions.add.atom.commands.add (D:/Atom x64/resources/app/static/<embedded>:11:656178)
    at CommandRegistry.handleCommandEvent (D:/Atom x64/resources/app/static/<embedded>:11:350017)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (D:/Atom x64/resources/app/static/<embedded>:11:1212945)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (D:/Atom x64/resources/app/static/<embedded>:11:1209079)
    at WindowEventHandler.handleDocumentKeyEvent (D:/Atom x64/resources/app/static/<embedded>:11:285196)
```

### Commands

```
  2x -2:29 core:save (input.hidden-input)
     -1:39.3.0 editor:newline (input.hidden-input)
     -1:39.2.0 core:paste (input.hidden-input)
     -1:36.4.0 core:copy (input.hidden-input)
     -1:32.4.0 core:paste (input.hidden-input)
     -1:31.2.0 core:backspace (input.hidden-input)
     -1:30.2.0 core:save (input.hidden-input)
  2x -1:26.3.0 editor:newline (input.hidden-input)
  3x -1:24.1.0 core:backspace (input.hidden-input)
     -1:15.9.0 core:move-up (input.hidden-input)
 11x -1:15.5.0 core:move-right (input.hidden-input)
     -1:14.2.0 core:move-left (input.hidden-input)
     -1:02.9.0 core:copy (input.hidden-input)
     -0:55.5.0 core:paste (input.hidden-input)
     -0:55 core:save (input.hidden-input)
     -0:51.4.0 bracket-matcher:go-to-matching-bracket (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
gruvbox-plus-syntax 1.3.1 
language-haml 0.32.1 
language-powershell 5.0.0 
open-in-browsers 0.0.30 
pigments 0.40.2 
stylus-language 2.6.0 
todo-show 2.3.2 
```

I did this by hitting Ctrl+M (accidentally). It's the bracket matcher function, as displayed in the keybinds. Bracket matching clearly isn't supported by the package I use to add Stylus syntax support.

This error is thrown anywhere where there is no bracket to match from the cursor position, or if the cursor is not within a function. Ctrl+M does not work if you're not in a file.

**Comment by mbpscruise** [comment]
@rsese - I believe this issue is editor-wide, in the context of the reply above?

**Comment by rsese** [comment]
Sorry I missed your comment @mbpscruise - the stack trace in your error is different than the original report, the issue you're describing was reported in https://github.com/atom/bracket-matcher/issues/380.  That issue has been fixed and the fix will be available in an upcoming release.

**Comment by richardsidler** [comment]
...this is a thing.

**Comment by HaoyangFan** [comment]
I got the same error today when I hardcode a JSON-like string in a Java program and use Ctrl+M to jump to the matching curly brackets

here is the error stack:
```
/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14
TypeError: Cannot read property 'start' of undefined
    at TagFinder.isTagRange (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:508902)
    at TagFinder.findEnclosingTags (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:510769)
    at BracketMatcherView.gotoPrecedingStartBracket (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:665492)
    at BracketMatcherView.goToMatchingBracket (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:664098)
    at HTMLElement.BracketMatcherView.subscriptions.add.atom.commands.add (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:656182)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350017)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1212981)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209115)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285196)
```

I hope this would be fixed in the next release (is it going to be 1.35.2)?

**Comment by fltha** [comment]
Hello,
I have got a similar error just now. I was writing simple text. There are two brackets (..) in my file but I was in a different line not trying to match anything. After reading these posts though, maybe I hit `M` by accident because when I try it anywhere NOT between two brackets, the same error occurs.


**atom** 1.36.0 x64
**electron**   2.0.18
**chrome**  61.0.3163.100
**node**    v8.9.3
**OS** windows 7 enterprise

` C:\Users\***\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:14
Hide Stack Trace
TypeError: Cannot read property 'start' of undefined
    at TagFinder.isTagRange (C:\Users\***\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:14:508911)
    at TagFinder.findEnclosingTags (C:\Users\***\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:14:510778)
    at BracketMatcherView.gotoPrecedingStartBracket (C:\Users\\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:665720)
    at BracketMatcherView.goToMatchingBracket (C:\Users\***\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:664326)
    at HTMLElement.BracketMatcherView.subscriptions.add.atom.commands.add (C:\Users\***\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:656410)
    at CommandRegistry.handleCommandEvent (C:\Users\***\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:350121)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (C:\Users\***\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:1212648)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (C:\Users\***\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:1208782)
    at WindowEventHandler.handleDocumentKeyEvent (C:\Users\***\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:285300)
`

I am quite new to this, but this is a case of 'I cannot find, what is not there', isn't it?

**Comment by rsese** [comment]
@HaoyangFan @fltha - hmmm, looks like that same issue still (https://github.com/atom/bracket-matcher/issues/380https://github.com/atom/bracket-matcher/issues/380).   @50Wliu did your fix (https://github.com/atom/bracket-matcher/pull/381) make it into atom/atom?

**Comment by ashthespy** [comment]
FWIW, also just ran into this.

**Atom**: 1.37.0-beta0 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
TypeError: Cannot read property 'start' of undefined
    at TagFinder.isTagRange (C:/Program Files/PlatformIO/Atom Beta x64/resources/app/static/<embedded>:14:509534)
    at TagFinder.findEnclosingTags (C:/Program Files/PlatformIO/Atom Beta x64/resources/app/static/<embedded>:14:511401)
    at BracketMatcherView.gotoPrecedingStartBracket (C:/Program Files/PlatformIO/Atom Beta x64/resources/app/static/<embedded>:11:665588)
    at BracketMatcherView.goToMatchingBracket (C:/Program Files/PlatformIO/Atom Beta x64/resources/app/static/<embedded>:11:664194)
    at HTMLElement.BracketMatcherView.subscriptions.add.atom.commands.add (C:/Program Files/PlatformIO/Atom Beta x64/resources/app/static/<embedded>:11:656278)
    at CommandRegistry.handleCommandEvent (C:/Program Files/PlatformIO/Atom Beta x64/resources/app/static/<embedded>:11:349975)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (C:/Program Files/PlatformIO/Atom Beta x64/resources/app/static/<embedded>:11:1214785)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (C:/Program Files/PlatformIO/Atom Beta x64/resources/app/static/<embedded>:11:1210919)
    at WindowEventHandler.handleDocumentKeyEvent (C:/Program Files/PlatformIO/Atom Beta x64/resources/app/static/<embedded>:11:285125)
```

### Commands

```
       -0:49 bracket-matcher:go-to-matching-bracket (input.hidden-input)
```

**Comment by alexchandel** [comment]
Same exact issue, Ctrl+M to bracket match, with the Core Package `language-json`.

@rsese Please reopen.

**Comment by macdonaldtomw** [comment]
Same issue here:

```C:\Users\Boompy\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:14
Hide Stack Trace
TypeError: Cannot read property 'start' of undefined
    at TagFinder.isTagRange (C:\Users\Boompy\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:14:508911)
    at TagFinder.findEnclosingTags (C:\Users\Boompy\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:14:510778)
    at BracketMatcherView.gotoPrecedingStartBracket (C:\Users\Boompy\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:665720)
    at BracketMatcherView.goToMatchingBracket (C:\Users\Boompy\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:664326)
    at HTMLElement.BracketMatcherView.subscriptions.add.atom.commands.add (C:\Users\Boompy\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:656410)
    at CommandRegistry.handleCommandEvent (C:\Users\Boompy\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:350121)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (C:\Users\Boompy\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:1212648)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (C:\Users\Boompy\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:1208782)
    at KeymapManager.t.exports.KeymapManager.terminatePendingState (C:\Users\Boompy\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:1212213)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (C:\Users\Boompy\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:1209631)
    at WindowEventHandler.handleDocumentKeyEvent (C:\Users\Boompy\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:285300)```

**Comment by MickROTH** [comment]
Wanted to preview my markdown file, using ctrl+M as per usual.



**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At /private/var/folders/4b/_f1699ss5k70cvkb19986dk00000gr/T/AppTranslocation/03B9797E-D4A8-40C1-808C-2930AD4BECCF/d/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: Cannot read property 'start' of undefined
    at TagFinder.isTagRange (/private/var/folders/4b/_f1699ss5k70cvkb19986dk00000gr/T/AppTranslocation/03B9797E-D4A8-40C1-808C-2930AD4BECCF/d/Atom.app/Contents/Resources/app/static/<embedded>:14:508975)
    at TagFinder.findEnclosingTags (/private/var/folders/4b/_f1699ss5k70cvkb19986dk00000gr/T/AppTranslocation/03B9797E-D4A8-40C1-808C-2930AD4BECCF/d/Atom.app/Contents/Resources/app/static/<embedded>:14:510842)
    at BracketMatcherView.gotoPrecedingStartBracket (/private/var/folders/4b/_f1699ss5k70cvkb19986dk00000gr/T/AppTranslocation/03B9797E-D4A8-40C1-808C-2930AD4BECCF/d/Atom.app/Contents/Resources/app/static/<embedded>:11:665720)
    at BracketMatcherView.goToMatchingBracket (/private/var/folders/4b/_f1699ss5k70cvkb19986dk00000gr/T/AppTranslocation/03B9797E-D4A8-40C1-808C-2930AD4BECCF/d/Atom.app/Contents/Resources/app/static/<embedded>:11:664326)
    at HTMLElement.BracketMatcherView.subscriptions.add.atom.commands.add (/private/var/folders/4b/_f1699ss5k70cvkb19986dk00000gr/T/AppTranslocation/03B9797E-D4A8-40C1-808C-2930AD4BECCF/d/Atom.app/Contents/Resources/app/static/<embedded>:11:656410)
    at CommandRegistry.handleCommandEvent (/private/var/folders/4b/_f1699ss5k70cvkb19986dk00000gr/T/AppTranslocation/03B9797E-D4A8-40C1-808C-2930AD4BECCF/d/Atom.app/Contents/Resources/app/static/<embedded>:11:350121)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/private/var/folders/4b/_f1699ss5k70cvkb19986dk00000gr/T/AppTranslocation/03B9797E-D4A8-40C1-808C-2930AD4BECCF/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1212648)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/4b/_f1699ss5k70cvkb19986dk00000gr/T/AppTranslocation/03B9797E-D4A8-40C1-808C-2930AD4BECCF/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1208782)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/4b/_f1699ss5k70cvkb19986dk00000gr/T/AppTranslocation/03B9797E-D4A8-40C1-808C-2930AD4BECCF/d/Atom.app/Contents/Resources/app/static/<embedded>:11:285300)
```

### Commands

```
     -3:45.2.0 application:add-project-folder (atom-pane.pane.active)
     -3:15 bracket-matcher:go-to-matching-bracket (input.hidden-input)
  5x -3:07.0 core:move-up (input.hidden-input)
     -3:04.3.0 core:save (input.hidden-input)
 13x -3:03.5.0 bracket-matcher:go-to-matching-bracket (input.hidden-input)
     -0:28.1.0 tree-view:remove-project-folder (div.header.list-item.project-root-header)
     -0:23.3.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:08.6.0 bracket-matcher:go-to-matching-bracket (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
This has been fixed as of 1.38 which is currently in beta.

**Comment by elhuemul** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: Cannot read property 'start' of undefined
    at TagFinder.isTagRange (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:509598)
    at TagFinder.findEnclosingTags (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:511465)
    at BracketMatcherView.gotoPrecedingStartBracket (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:665720)
    at BracketMatcherView.goToMatchingBracket (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:664326)
    at HTMLElement.BracketMatcherView.subscriptions.add.atom.commands.add (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:656410)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349922)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214917)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1211051)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285128)
```

### Commands

```
     -0:22.3.0 bracket-matcher:go-to-matching-bracket (input.hidden-input)
     -0:19 application:minimize (input.hidden-input)
     -0:11.3.0 bracket-matcher:go-to-matching-bracket (input.hidden-input)
```

### Non-Core Packages

```
auto-detect-indentation 1.3.0 
busy-signal 2.0.1 
intentions 1.1.5 
linter 2.3.0 
linter-swagger 0.6.1 
linter-ui-default 1.7.1 
raml 0.2.0 
source-preview 0.5.3 
```

**Comment by NicoWeio** [comment]
I got this error when trying to jump to a non-existent matching bracket.
