### ISSUE TITLE
Starting Atom from a folder containing a directory named 'package.json' causes a crash

### ISSUE THREAD

**Issue by building39** [atom/atom#18186]
I've just installed the latest update, which came to me via an alert in atom. When I restarted atom, I got no window. Running `atom -f` renders this:

```
$ atom -f
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Proxy.fs.readFileSync (fs.js:583:19)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:545:29)
    at Object.readFileSync (/usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:168:21)
    at isAtomRepoPath (/usr/share/atom/resources/app.asar/src/main-process/main.js:23:28)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/main-process/main.js:42:14)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/main-process/main.js:60:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
```

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by daviwil** [comment]
Hi @building39, could you give some more details on your system and how you installed Atom?  It'd be helpful if you filled in at least the Versions section of the template.  Thanks!

**Comment by building39** [comment]
Ubuntu 16.04 with latest updates. Here's my latest stab at getting atom running again - removed atom with `dpkg` - deleted the `~/.atom` directory - reinstalled `atom` - ran `atom --version` - ran `atom --safe` - ran `atom -f`:

```mmartin@devcat:~$ ps aux |grep atom
mmartin   4969  0.0  0.0  14228   960 pts/2    S+   10:05   0:00 grep --color=auto atom
mmartin@devcat:~$ sudo dpkg -r atom
[sudo] password for mmartin: 
(Reading database ... 256116 files and directories currently installed.)
Removing atom (1.31.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.2) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20180209-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
mmartin@devcat:~$ clear

mmartin@devcat:~$ which atom
mmartin@devcat:~$ ls -la .atom
total 12
drwxrwxr-x   2 mmartin mmartin 4096 Oct  3 10:02 .
drwxr-xr-x 134 mmartin mmartin 4096 Oct  3 10:02 ..
-rw-rw-r--   1 mmartin mmartin  797 Oct  3 10:02 nohup.out
mmartin@devcat:~$ rm -rf .atom
mmartin@devcat:~$ cd Downloads/
mmartin@devcat:~/Downloads$ sudo dpkg -i atom-amd64.deb 
Selecting previously unselected package atom.
(Reading database ... 246645 files and directories currently installed.)
Preparing to unpack atom-amd64.deb ...
Unpacking atom (1.31.1) ...
Setting up atom (1.31.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.2) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20180209-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
mmartin@devcat:~/Downloads$ which atom
/usr/bin/atom
mmartin@devcat:~/Downloads$ atom --version
Atom    : 1.31.1
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3
mmartin@devcat:~/Downloads$ cd ..
mmartin@devcat:~$ ls -la .atom
total 8
drwxrwxr-x   2 mmartin mmartin 4096 Oct  3 10:07 .
drwxr-xr-x 134 mmartin mmartin 4096 Oct  3 10:07 ..
mmartin@devcat:~$ cd .atom
mmartin@devcat:~/.atom$ ls -la
total 8
drwxrwxr-x   2 mmartin mmartin 4096 Oct  3 10:07 .
drwxr-xr-x 134 mmartin mmartin 4096 Oct  3 10:07 ..
mmartin@devcat:~/.atom$ cd
mmartin@devcat:~$ atom --safe
mmartin@devcat:~$ ps aux |grep atom
mmartin   5197  0.0  0.0  12588  1684 pts/2    S    10:07   0:00 /bin/bash /usr/bin/atom --safe
mmartin   5199  2.1  1.3 1466100 226140 pts/2  Sl   10:07   0:00 /usr/share/atom/atom --executed-from=/home/mmartin --pid=5186 --safe
mmartin   5204  0.0  0.2 425644 42132 pts/2    S    10:07   0:00 /usr/share/atom/atom --type=zygote --no-sandbox
mmartin   5234  0.3  0.4 521884 73672 pts/2    Sl   10:07   0:00 /usr/share/atom/atom --type=gpu-process --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=9,27,84 --disable-gl-extensions=GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent --disable-accelerated-video-decode --gpu-vendor-id=0x10de --gpu-device-id=0x0fd1 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-secondary-vendor-ids=0x10de --gpu-secondary-device-ids=0x0fd1 --service-request-channel-token=4A5EDD5946516F131879B51F38BFDBF2
mmartin   5244  0.0  0.0  14228  1092 pts/2    S+   10:08   0:00 grep --color=auto atom
mmartin@devcat:~$ atom -f
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Proxy.fs.readFileSync (fs.js:583:19)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:545:29)
    at Object.readFileSync (/usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:168:21)
    at isAtomRepoPath (/usr/share/atom/resources/app.asar/src/main-process/main.js:23:28)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/main-process/main.js:42:14)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/main-process/main.js:60:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)```

**Comment by daviwil** [comment]
Thanks!  Do you happen to have a directory or file called `package.json` in your home directory?

**Comment by building39** [comment]
Yes, a directory

**Comment by daviwil** [comment]
Is it there on purpose?  A quick fix would be to delete the directory or rename it to something else.  We'll definitely need to check for this possibility, though.  Thanks for finding this bug!

**Comment by building39** [comment]
Removing it did the trick.
Thanks!

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by Alkohost** [comment]
I am not sure should I write about it here.
I faced with crash when I press Show Console button and Font Size in editor settings is 1
Windows 7 x64 
Atom 1.31.2

**Comment by rsese** [comment]
That sounds like a different issue @Alkohost - if you can reproduce in safe mode, please open a new issue and fill out the issue template so we can take a look.

**Comment by sadick254** [comment]
This no longer seems to be an issue on the latest atom version `v1.50`.
