### ISSUE TITLE
Installing “teletype@0.13.3” failed.

### ISSUE THREAD

**Issue by Cr1stalz** [atom/atom#18184]
```
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
npm ERR! errno SELF_SIGNED_CERT_IN_CHAIN
npm ERR! request to https://codeload.github.com/atom/teletype/legacy.tar.gz/v0.13.3 failed, reason: self signed certificate in certificate chain

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\.atom\.apm\_logs\2018-10-03T08_51_33_621Z-debug.log
```

In file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\User\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\User\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\User\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\User\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/teletype/versions/0.13.3/tarball',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=2.0.7',
1 verbose cli   '--dist-url=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v8.9.3
4 verbose npm-session 72406f5f6338974d
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for https://www.atom.io/api/packages/teletype/versions/0.13.3/tarball request to https://codeload.github.com/atom/teletype/legacy.tar.gz/v0.13.3 failed, reason: self signed certificate in certificate chain
8 timing stage:rollbackFailedOptional Completed in 2ms
9 timing stage:runTopLevelLifecycles Completed in 7310ms
10 verbose type system
11 verbose stack FetchError: request to https://codeload.github.com/atom/teletype/legacy.tar.gz/v0.13.3 failed, reason: self signed certificate in certificate chain
11 verbose stack     at ClientRequest.req.on.err (C:\Users\User\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
11 verbose stack     at emitOne (events.js:116:13)
11 verbose stack     at ClientRequest.emit (events.js:211:7)
11 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)
11 verbose stack     at emitOne (events.js:116:13)
11 verbose stack     at TLSSocket.emit (events.js:211:7)
11 verbose stack     at emitErrorNT (internal/streams/destroy.js:64:8)
11 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
12 verbose cwd C:\Users\3C9B~1\AppData\Local\Temp\apm-install-dir-11893-4340-f89v1u.n0cqu
13 verbose Windows_NT 6.1.7600
14 verbose argv "C:\\Users\\User\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\User\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\User\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\User\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/teletype/versions/0.13.3/tarball" "--runtime=electron" "--target=2.0.7" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style"
15 verbose node v8.9.3
16 verbose npm  v6.2.0
17 error code SELF_SIGNED_CERT_IN_CHAIN
18 error errno SELF_SIGNED_CERT_IN_CHAIN
19 error request to https://codeload.github.com/atom/teletype/legacy.tar.gz/v0.13.3 failed, reason: self signed certificate in certificate chain
20 verbose exit [ 1, true ]
```

**Comment by rsese** [comment]
Thanks for reaching out!  We have a FAQ item for issues with self-signed certificates here:

https://discuss.atom.io/t/im-getting-an-error-about-a-self-signed-certificate-what-do-i-do/39040

If you still have trouble, feel free to reach out on our [official message board](https://discuss.atom.io).

Also, for future issues it would be helpful if you can fill out the issue template as much as possible.
