### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/ and Interchange Format.pdf'

### ISSUE THREAD

**Issue by undergroundquizscene** [atom/atom#18192]
Steps to reproduce:

1. Name a file "The SmOKE Music Representation, Description Language, and Interchange Format.pdf"
2. Move this file into another folder in the tree view

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/ and Interchange Format.pdf'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/ and Interchange Format.pdf'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:343:29)
    at TreeView.module.exports.TreeView.moveEntry (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1544:34)
    at TreeView.module.exports.TreeView.onDrop (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1844:37)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:389:30)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-material-syntax-light 0.4.6 
build 0.70.0 
busy-signal 1.4.3 
choose-pane 0.8.0 
direction 0.0.0 
docblockr 0.13.7 
editor-settings 1.1.3 
file-icons 2.1.24 
ide-scala 0.7.0 
intentions 1.1.5 
jslint 1.5.1 
language-arduino 0.4.3 
language-babel 2.85.0 
language-emacs-lisp 1.3.0 
language-fish-shell 1.1.0 
language-gradle 0.0.5 
language-groovy 0.7.0 
language-haskell 1.17.8 
language-latex 1.1.1 
language-lisp 0.2.0 
language-markdown 0.26.0 
language-pfm 0.82.0 
language-restructuredtext 1.1.2 
language-scala 1.1.9 
language-scheme 1.4.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-javac 1.9.4 
linter-python 3.1.2 
linter-ui-default 1.7.1 
long-lines 0.0.0 
mark-long-lines 0.0.0 
markdown-preview-enhanced 0.15.6 
markdown-preview-plus 3.6.3 
markdown-table-editor 1.1.1 
pandoc-table-editor 0.0.0 
platformio-ide-terminal 2.8.4 
plist-converter 0.2.0 
project-manager 3.3.6 
react 0.18.0 
relative-numbers 0.9.0 
remote-ftp 2.2.0 
rst-preview 1.3.1 
sonarlint 1.1.0 
split-diff 1.5.2 
tab-numbers 0.6.1 
testing! 0.0.1-SNAPSHOT 
vim-mode-plus 1.34.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vis 0.0.0 
```

**Comment by undergroundquizscene** [comment]
Verified with atom in safe mode as well.

**Comment by undergroundquizscene** [comment]
This is the same as https://github.com/atom/tree-view/issues/1282, so I’ll close this.
