### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=read ECONNRESET

### ISSUE THREAD

**Issue by rg665n** [atom/atom#18210]
[Enter steps to reproduce:]

1. Go to Settings.
2. Choose Install.
3. Type Package name you want to install.
Issue- ATOM will throw Exception.

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=read ECONNRESET

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, cause=read ECONNRESET
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
  7x -0:31.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report! Are you using a network proxy? This seems like it could be a temporary network issue, please try again later and see if you continue getting the same error.
