### ISSUE TITLE
Uncaught TypeError: Cannot read property 'update' of undefined

### ISSUE THREAD

**Issue by sanderbockstaele** [atom/atom#18215]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'update' of undefined

```
At C:\Users\Gebruiker\AppData\Local\atom\app-1.31.2\resources\app\src\text-editor-component.js:3768

TypeError: Cannot read property 'update' of undefined
    at LinesTileComponent.updateLines (~/AppData/Local/atom/app-1.31.2/resources/app/src/text-editor-component.js:3768:29)
    at LinesTileComponent.update (~/AppData/Local/atom/app-1.31.2/resources/app/src/text-editor-component.js:3674:20)
    at updateComponent (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/etch/lib/patch.js:52:19)
    at patch (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/etch/lib/patch.js:16:25)
    at updateChildren (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/etch/lib/patch.js:18:15)
    at Object.updateSync (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/etch/lib/component-helpers.js:116:26)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.31.2/resources/app/src/text-editor-component.js:393:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.31.2/resources/app/src/text-editor-component.js:276:16)
    at etch.getScheduler.updateDocument (~/AppData/Local/atom/app-1.31.2/resources/app/src/text-editor-component.js:226:46)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.31.2/resources/app/src/view-registry.js:238:13)
```

### Commands

```
     -2:13.3.0 snippets:expand (input.hidden-input)
     -2:13.3.0 editor:indent (input.hidden-input)
     -1:49 core:backspace (input.hidden-input)
     -1:45.3.0 autocomplete-plus:confirm (input.hidden-input)
     -1:45.3.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:40.8.0 core:backspace (input.hidden-input)
     -1:35.8.0 core:move-right (input.hidden-input)
  2x -1:35.1.0 core:move-left (input.hidden-input)
  2x -1:33.5.0 core:undo (input.hidden-input)
     -1:31.2.0 editor:newline (input.hidden-input)
     -1:29 core:move-right (input.hidden-input)
     -1:28.3.0 core:move-left (input.hidden-input)
     -1:27.5.0 core:move-down (input.hidden-input)
     -1:24.6.0 core:save (input.hidden-input)
undefined -1:07.5.0 core:undo (input.hidden-input)
  4x -0:33 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
language-vb 0.1.0-pre1 
language-vue 0.23.1 
language-x86-64-assembly 2.2.11 
react 0.18.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?
