### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by tayyabsayyad** [atom/atom#18293]
**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Ubuntu 18.04.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At /usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:248

TypeError: Cannot read property 'version' of undefined
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:248:41
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:333:24
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:267:15)
    at bufferStream (/usr/share/atom/resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (/usr/share/atom/resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -8:27.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
hugofy 2.0.0 
language-hugo 0.5.1 
language-markdown 0.26.0 
markdown-toc 0.4.2 
markdown-writer 2.9.0 
```

**Comment by antoinemcabee** [comment]
Just trying to install python and run a Hello World program. Completely new to this and completely lost.
