### ISSUE TITLE
Uncaught TypeError: oldState.range.compare is not a function

### ISSUE THREAD

**Issue by narang-amit** [atom/atom#18296]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: oldState.range.compare is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:423

TypeError: oldState.range.compare is not a function
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:423:162)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:348:31
    at Set.forEach (<anonymous>)
    at MarkerLayer.module.exports.MarkerLayer.emitChangeEvents (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:345:52)
    at TextBuffer.module.exports.TextBuffer.emitMarkerChangeEvents (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1774:40)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:999:18)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2007:30)
    at TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2880:23)
    at TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2691:23)
    at TextEditorComponent.didMouseDownOnContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1808:25)
```

### Commands

```
     -6:55 core:backspace (input.hidden-input)
  4x -6:54.3.0 core:undo (input.hidden-input)
     -6:49.6.0 snippets:next-tab-stop (input.hidden-input)
     -6:49.6.0 snippets:expand (input.hidden-input)
     -6:49.6.0 editor:indent (input.hidden-input)
     -6:49.2.0 snippets:next-tab-stop (input.hidden-input)
     -6:49.2.0 snippets:expand (input.hidden-input)
     -6:49.2.0 editor:indent (input.hidden-input)
     -6:48.4.0 core:undo (input.hidden-input)
     -6:43.7.0 core:backspace (input.hidden-input)
  3x -6:33.6.0 core:save (input.hidden-input)
     -0:11.4.0 pane:split-left-and-copy-active-item (div.line)
  2x -0:09.9.0 core:undo (input.hidden-input)
     -0:08.1.0 core:backspace (input.hidden-input)
     -0:02.5.0 editor:consolidate-selections (input.hidden-input)
     -0:02.5.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
teletype 0.13.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?
