### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Isaque-mb** [atom/atom#18343]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\Isaque\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:75360)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:75292)
    at TextEditorComponent.renderContent (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:73818)
    at TextEditorComponent.renderScrollContainer (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:73278)
    at TextEditorComponent.render (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:72057)
    at Object.updateSync (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:14:126499)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:69915)
    at TextEditorComponent.screenPositionForPixelPosition (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:107027)
    at TextEditorComponent.screenPositionForMouseEvent (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:98286)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:94846)
```

### Commands

```
  2x -5:33.7.0 core:move-right (input.hidden-input)
     -5:32.9.0 core:backspace (input.hidden-input)
     -5:31.8.0 core:move-left (input.hidden-input)
  2x -5:31 core:move-right (input.hidden-input)
 11x -5:30.2.0 core:backspace (input.hidden-input)
     -4:33.1.0 autoclose-html:close-and-complete (input.hidden-input)
     -4:31 core:save (input.hidden-input)
     -4:20.5.0 core:copy (input.hidden-input)
     -4:14.7.0 core:paste (input.hidden-input)
     -4:13.7.0 core:save (input.hidden-input)
  7x -4:09.6.0 core:undo (input.hidden-input)
  2x -3:54.6.0 core:paste (input.hidden-input)
     -3:49.8.0 core:save (input.hidden-input)
  3x -3:02.4.0 core:backspace (input.hidden-input)
  2x -2:55.9.0 core:undo (input.hidden-input)
     -2:53.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-live-server 2.3.0 
atom-material-ui 2.1.3 
autoclose-html 0.23.0 
city-lights-syntax 1.1.8 
dracula-syntax 2.0.7 
emmet 2.4.3 
file-icons 2.1.26 
git-plus 8.1.0 
pigments 0.40.2 
```

**Comment by clair513** [comment]
I have same error in my Atom.

Stack Trace:
```
TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (C:\Users\Alok\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:75360)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (C:\Users\Alok\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:75292)
    at TextEditorComponent.renderContent (C:\Users\Alok\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:73818)
    at TextEditorComponent.renderScrollContainer (C:\Users\Alok\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:73278)
    at TextEditorComponent.render (C:\Users\Alok\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:72057)
    at Object.updateSync (C:\Users\Alok\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:14:126499)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (C:\Users\Alok\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:69915)
    at TextEditorComponent.updateSync (C:\Users\Alok\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:67302)
    at TextEditorComponent.didShow (C:\Users\Alok\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:90932)
    at TextEditorComponent.didFocus (C:\Users\Alok\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:91123)
    at HTMLElement.addEventListener (C:\Users\Alok\AppData\Local\atom\app-1.29.0\resources\app.asar\src\text-editor-element.js:36:67)
    at HTMLElement.activeItemChanged (C:\Users\Alok\AppData\Local\atom\app-1.29.0\resources\app.asar\src\pane-element.js:164:16)
    at Function.simpleDispatch (C:\Users\Alok\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:1185469)
    at Emitter.emit (C:\Users\Alok\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:1186910)
    at Pane.setActiveItem (C:\Users\Alok\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:451221)
    at Pane.activateItem (C:\Users\Alok\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:453469)
    at TabBarView.t.exports.TabBarView.onClick (C:\Users\Alok\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:1135974)
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

**Comment by clair513** [comment]
Thanks for reverting @rsese!

- In my scenario, at the time of this error I was just trying to copy-paste a container from one to another HTML within my Flask application. So the moment I highlighted that container (had copied same content earlier as well from that HTML with no issues), back-to-back multiple pop-ups on bottom right of my screen started appearing. First indicated core Atom and then rest indicated _linter-ui-default_ error. 
-  Checked other open `.html` and `.py` tabs and just clicking on those scripts immediately fetched again similar series of error prompts. Disabling just _linter-ui-default_ didn't help, so to continue, I disabled remaining two (_linter_ and _linter-python-pep8_) external packages as well. Restarted Atom and since then everything has been running fine, with those 3 packages disabled.

- Unfortunately, I don't think this is reproducible in my scenario, unless am wrong and you may kindly guide accordingly for me to furnish more information.

- Just now enabled above mentioned external packages and restarted Atom in Safe mode, but in there everything sailed smoothly. 

I've been using Atom with same packages for over an year now & never really faced even a single issue, so currently little puzzled. Further input will be highly appreciated and thanks for your time.

**Comment by fxmountain** [comment]
I can confirm that it was about the package Pigments. This one can not handle compressed css style very wenn.

**Comment by rsese** [comment]
Thanks @clair513 and @fxmountain - it looks like the issue author also has pigments installed.  Since this appears be caused by https://atom.io/packages/pigments, you should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. It may be that there is still a bug in Atom and if so, we'll need the maintainer pigments to help track that down.
