### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tree' of null

### ISSUE THREAD

**Issue by NeNpO** [atom/atom#18358]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.12
**OS**: "Antergos Linux"
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'tree' of null

```
At /usr/lib/atom/src/tree-sitter-language-mode.js:111

TypeError: Cannot read property 'tree' of null
    at TreeSitterLanguageMode.get tree [as tree] (/usr/lib/atom/src/tree-sitter-language-mode.js:111:35)
    at TreeSitterLanguageMode.getFoldableRangeContainingPoint (/usr/lib/atom/src/tree-sitter-language-mode.js:266:15)
    at TreeSitterLanguageMode.isFoldableAtRow (/usr/lib/atom/src/tree-sitter-language-mode.js:207:25)
    at TextEditor.isFoldableAtBufferRow (/usr/lib/atom/src/text-editor.js:4129:57)
    at TextEditorComponent.queryLineNumbersToRender (/usr/lib/atom/src/text-editor-component.js:926:34)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/lib/atom/src/text-editor-component.js:378:10)
    at TextEditorComponent.updateSync (/usr/lib/atom/src/text-editor-component.js:266:10)
    at TextEditorComponent.didMouseWheel (/usr/lib/atom/src/text-editor-component.js:1551:53)
```

### Commands

```
     -3:13 github:fetch (span.)
     -2:43.5.0 split-diff:toggle (div.line)
  2x -2:32 core:delete (input.hidden-input)
  8x -2:16.5.0 core:backspace (input.hidden-input)
  7x -2:09.7.0 core:delete (input.hidden-input)
     -1:16.2.0 intentions:highlight (input.hidden-input)
     -1:15.6.0 core:save (input.hidden-input)
     -0:49.2.0 remote-ftp:upload-active (div.line)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-debug-ui 1.0.4 
atom-ide-ui 0.13.0 
atom-live-server 2.3.0 
atom-sync 0.7.3 
autocomplete 0.47.0 
autocomplete-paths 2.12.2 
browser-refresh 0.9.0 
busy-signal 1.4.3 
color-picker 2.3.0 
Delete-Whitelines 0.6.4 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.26 
file-watcher 2.0.0 
highlight-selected 0.14.0 
ide-php 0.7.15 
intentions 1.1.5 
language-batch 0.4.0 
language-powershell 5.0.0 
language-vb 0.1.0-pre1 
linter 2.2.0 
linter-htmlhint 1.5.1 
linter-jscs 4.1.3 
linter-jshint 3.1.9 
linter-jsonlint 1.3.0 
linter-php 1.5.1 
linter-pylint 2.1.1 
linter-sass-lint 1.8.3 
linter-scss-lint 3.1.1 
linter-shellcheck 1.5.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-pigments 0.2.2 
php-cs-fixer 4.1.1 
php-debug 0.3.5 
pigments 0.40.2 
project-manager 3.3.6 
remote-ftp 2.2.0 
spacegray-atom-dark-syntax 1.3.2 
split-diff 1.5.3 
sync-settings 0.8.6 
todo-show 2.3.2 
trailing-spaces 0.4.0 
tree-view-git-status 1.5.2 
```

**Comment by rsese** [comment]
Thanks for the report!

> Atom: 1.32.0 x64
> Electron: 2.0.12

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
