### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by JimmyTarr** [atom/atom#18378]
1. Add source.python, string.quoted to spell-check Grammars
2. Open long python script? Might also be due to folded functions.
3. Warning appears when scrolling.

**Atom**: 1.33.0-beta0 x64
**Electron**: 2.0.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Jimmy Tarr\AppData\Local\atom\app-1.33.0-beta0\resources\app\static\<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.33.0-beta0/resources/app/static/<embedded>:14:1108762)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.33.0-beta0/resources/app/static/<embedded>:14:1104472)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.33.0-beta0/resources/app/static/<embedded>:14:89276)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.33.0-beta0/resources/app/static/<embedded>:11:79320)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.33.0-beta0/resources/app/static/<embedded>:11:69973)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.33.0-beta0/resources/app/static/<embedded>:11:67601)
    at TextEditorComponent.didShow (~/AppData/Local/atom/app-1.33.0-beta0/resources/app/static/<embedded>:11:91231)
    at TextEd

**Comment by JihedC** [comment]
I have got the same here when opening a long Snakemake (python) script. The warning appears when I click on any part of the script.

*Atom*: 1.31.2
*OS* : MacOS 10.14 Mojave

'''
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.14
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:328

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:328:31)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:140:22)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:871:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:386:16)
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2399:18)
    at TextEditorComponent.screenPositionForMouseEvent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1971:23)
    at TextEditorComponent.didMouseDownOnContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1770:39)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-bash-builtins 0.3.5 
Hydrogen 2.6.0 
language-markdown 0.27.0 
language-r 0.4.2 
language-unix-shell 0.40.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible in safe mode (`atom --safe`)?

Also, can you share a specific file we can use to test with?

x-ref: https://github.com/atom/atom/issues/16892

**Comment by fabianelima** [comment]
Same issue here:

`[Enter steps to reproduce:]

1. Just opened an old project

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\fabianelima\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:1108088)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:1103798)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:89276)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:79025)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:69678)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:67306)
    at TextEditorComponent.didShow (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:90936)
    at TextEditorComponent.didFocus (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:91127)
    at HTMLElement.addEventListener (/app.asar/src/text-editor-element.js:36:67)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:164:16)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:1186953)
    at Emitter.emit (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:1188394)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:452700)
    at Pane.activateItem (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:454948)
    at TabBarView.t.exports.TabBarView.onClick (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:1137458)
```

### Commands

```
     -0:13.7.0 pane:reopen-closed-item (a.btn-issue.btn.btn-error.opening)
     -0:12.3.0 core:cancel (div.settings-view.pane-item)
```

### Non-Core Packages

```

```

`

**Comment by rsese** [comment]
@JihedC @fabianelima - is the error reproducible in safe mode and can either of you share a file where the error reproduces?

**Comment by alexanderabramov** [comment]
Same error, reproducible in in atom --safe, but only when I reopen a previously opened folder and some files are automatically opened on startup.

If I delete those files, reopen the folder (so the files cannot be automatically reopened), the error is gone, and does not happen anymore when I restore exactly the same files.

**Comment by iFA88** [comment]
Issue are 24 days old, there is any solution?

**Comment by rsese** [comment]
@iFA88 - sorry the issue is still open so no resolution.   We need specific steps to reproduce the problem before the team can take a look.
