### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=503

### ISSUE THREAD

**Issue by GAOZipeng** [atom/atom#18370]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=503

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at Socket.socketOnData (_http_client.js:472:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -1:07.3.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
simplified-chinese-menu 5.3.5 
```

**Comment by rsese** [comment]
Thanks for the report! Are you using a network proxy? This seems like it could be a temporary network issue or an issue with authenticating to your proxy based on the error code?  Please try again later and see if you continue getting the same error.

**Comment by zhangzhijing1995** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.14
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=503

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at Socket.socketOnData (_http_client.js:472:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -5:37.6.0 editor:newline (input.hidden-input)
     -5:37.1.0 core:paste (input.hidden-input)
 67x -5:35.6.0 core:undo (input.hidden-input)
     -5:11.1.0 core:backspace (input.hidden-input)
     -5:08.8.0 markdown-writer:insert-new-line (input.hidden-input)
     -5:08.8.0 autocomplete-plus:confirm (input.hidden-input)
     -5:08.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:50.3.0 command-palette:toggle (input.hidden-input)
     -2:47.9.0 editor:consolidate-selections (input.hidden-input)
     -2:47.9.0 core:cancel (input.hidden-input)
     -2:42.7.0 command-palette:toggle (input.hidden-input)
     -2:24.1.0 about:clear-update-state (input.hidden-input)
     -2:13.3.0 command-palette:toggle (input.hidden-input)
     -2:02.4.0 core:confirm (input.hidden-input)
     -2:02.4.0 about:clear-update-state (input.hidden-input)
     -1:59.5.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-markdown 5.2.2 
linter-ui-default 1.7.1 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
markdown-writer 2.10.0 
platformio-ide-terminal 2.8.4 
ruby-block 0.3.6 
```
