### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages/platformio-ide-termi...

### ISSUE THREAD

**Issue by shreyansdjp** [atom/atom#18381]
[Enter steps to reproduce:]

1. open the platform-ide-terminal readme page
2. click install

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Ubuntu 18.04.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/shreyans/.atom/packages/platformio-ide-terminal/README.md'

```
At fs.js:646

Error: ENOENT: no such file or directory, open '/home/shreyans/.atom/packages/platformio-ide-terminal/README.md'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Proxy.fs.readFileSync (fs.js:551:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at PackageDetailView.renderReadme (/snap/atom/205/usr/share/atom/resources/app/static/<embedded>:14:733886)
    at PackageDetailView.updateInstalledState (/snap/atom/205/usr/share/atom/resources/app/static/<embedded>:14:733646)
    at /snap/atom/205/usr/share/atom/resources/app/static/<embedded>:14:734517
    at Function.simpleDispatch (/snap/atom/205/usr/share/atom/resources/app/static/<embedded>:11:1186142)
    at Emitter.emit (/snap/atom/205/usr/share/atom/resources/app/static/<embedded>:11:1187583)
    at PackageManager.t.exports.PackageManager.emitPackageEvent (/snap/atom/205/usr/share/atom/resources/app/static/<embedded>:11:915770)
    at /snap/atom/205/usr/share/atom/resources/app/static/<embedded>:11:913179
    at r (/snap/atom/205/usr/share/atom/resources/app/static/<embedded>:11:907709)
    at o (/snap/atom/205/usr/share/atom/resources/app/static/<embedded>:14:1035482)
    at t.bufferStream (/snap/atom/205/usr/share/atom/resources/app/static/<embedded>:14:1035636)
    at Socket.e.on (/snap/atom/205/usr/share/atom/resources/app/static/<embedded>:14:1034238)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -1:49.6.0 settings-view:open (input.hidden-input)
     -1:44.5.0 core:confirm (input.hidden-input)
     -1:34.3.0 core:close (input.hidden-input)
     -1:31.2.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
platformio-ide-terminal 2.8.4 
```

**Comment by rsese** [comment]
Thanks for the report!

It appears that this is being caused by the [PlatformIO IDE Terminal](https://github.com/platformio/platformio-atom-ide-terminal) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
