### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 134.214.188.16...

### ISSUE THREAD

**Issue by LinkJerome** [atom/atom#18449]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 134.214.188.160:3128

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 134.214.188.160:3128
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -9:07.9.0 core:save (input.hidden-input)
     -2:36.5.0 find-and-replace:show (input.hidden-input)
     -2:35.3.0 core:backspace (input.hidden-input)
     -2:34.4.0 core:confirm (input.hidden-input)
  2x -2:26 core:move-down (input.hidden-input)
  2x -2:25.1.0 core:move-up (input.hidden-input)
     -2:24.3.0 core:move-down (input.hidden-input)
     -0:59.7.0 core:backspace (input.hidden-input)
  2x -0:59.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
language-haml 0.31.1 
```

**Comment by rsese** [comment]
Thanks for the report - based on the error, this is maybe a temporary issue with your internet connection or proxy? Please try again later and see if it works.
