### ISSUE TITLE
Overlapping text in editor

### ISSUE THREAD

**Issue by kuychaco** [atom/atom#18451]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

We're noticing funky text overlapping...

![image 5](https://user-images.githubusercontent.com/7910250/48657039-6834bc00-e9e1-11e8-9b85-130ba6cc4075.png)
![pasted_image_at_2018-11-16__10_54_pm](https://user-images.githubusercontent.com/7910250/48657040-6a971600-e9e1-11e8-8a6b-0c69da7ba0d9.png)

This might have to do with the fact that we are heavily using block decorations... we might be hitting some kind of line measurement race condition?

### Steps to Reproduce

Haven't found a way to reproduce this consistently. @vanessayuenn seems to see it a lot.

apm dev-link the github package and check out the `commit-preview` branch (currently head is at https://github.com/atom/github/pull/1767/commits/d33f3e945030a013db972fae4f4f75d70d354281), view a changed file with multiple changed lines, and try staging/unstaging lines a bunch.

**Expected behavior:** [What you expect to happen]

No funky text overlapping

**Actual behavior:** [What actually happens]

Text overlapping

**Reproduces how often:** [What percentage of the time does it reproduce?]

@vanessayuenn seems to get it fairly frequently. Maybe 25% of the time?

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

@vanessayuenn can you update this issue with the versions you're on?

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

/cc @maxbrunsfeld any thoughts? 💭 Does this look familiar to you at all?

**Comment by Ben3eeE** [comment]
https://github.com/atom/github/commit/d33f3e945030a013db972fae4f4f75d70d354281 throws an exception for me when opening the unstaged changes.

```
I:\atom_master\atom\node_modules\text-buffer\lib\text-buffer.js:1319 Uncaught Error: Expected 1 marker to be found at buffer row 7, but found 0
    at MultiFilePatch.getFilePatchAt (I:/atom_master/github/lib/models/patch/multi-file-patch.js:91:13)
    at MultiFilePatch.spansMultipleFiles (I:/atom_master/github/lib/models/patch/multi-file-patch.js:324:30)
    at MultiFilePatchView.didChangeSelectedRows (I:/atom_master/github/lib/views/multi-file-patch-view.js:963:65)
    at MultiFilePatchView.didChangeSelectionRange (I:/atom_master/github/lib/views/multi-file-patch-view.js:947:12)
    at Function.simpleDispatch (I:\atom_master\atom\node_modules\event-kit\dist\emitter.js:64:14)
    at Emitter.emit (I:\atom_master\atom\node_modules\event-kit\dist\emitter.js:257:28)
    at Selection.markerDidChange (I:\atom_master\atom\src\selection.js:1047:18)
    at Selection.marker.onDidChange.e (I:\atom_master\atom\src\selection.js:21:39)
    at Function.simpleDispatch (I:\atom_master\atom\node_modules\event-kit\dist\emitter.js:64:14)
    at Emitter.emit (I:\atom_master\atom\node_modules\event-kit\dist\emitter.js:257:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (I:\atom_master\atom\node_modules\text-buffer\lib\display-marker.js:248:27)
    at I:\atom_master\atom\node_modules\text-buffer\lib\display-marker.js:53:26
    at Function.simpleDispatch (I:\atom_master\atom\node_modules\event-kit\dist\emitter.js:64:14)
    at Emitter.emit (I:\atom_master\atom\node_modules\event-kit\dist\emitter.js:257:28)
    at Marker.module.exports.Marker.emitChangeEvent (I:\atom_master\atom\node_modules\text-buffer\lib\marker.js:441:20)
    at Marker.module.exports.Marker.update (I:\atom_master\atom\node_modules\text-buffer\lib\marker.js:374:12)
    at Marker.module.exports.Marker.setHeadPosition (I:\atom_master\atom\node_modules\text-buffer\lib\marker.js:149:19)
    at DisplayMarker.module.exports.DisplayMarker.setHeadBufferPosition (I:\atom_master\atom\node_modules\text-buffer\lib\display-marker.js:146:32)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (I:\atom_master\atom\node_modules\text-buffer\lib\display-marker.js:154:19)
    at changePosition (I:\atom_master\atom\src\cursor.js:68:19)
    at Cursor.changePosition (I:\atom_master\atom\src\cursor.js:722:5)
    at Cursor.setScreenPosition (I:\atom_master\atom\src\cursor.js:67:10)
    at moveCursors.cursor (I:\atom_master\atom\src\text-editor.js:2686:46)
    at Array.forEach (<anonymous>)
    at transact (I:\atom_master\atom\src\text-editor.js:2876:25)
    at TextBuffer.transact (I:\atom_master\atom\node_modules\text-buffer\lib\text-buffer.js:1316:16)
    at TextEditor.transact (I:\atom_master\atom\src\text-editor.js:2002:24)
    at TextEditor.moveCursors (I:\atom_master\atom\src\text-editor.js:2875:17)
    at TextEditor.setCursorScreenPosition (I:\atom_master\atom\src\text-editor.js:2686:17)
    at TextEditorComponent.didMouseDownOnContent (I:\atom_master\atom\src\text-editor-component.js:1799:19)
```
