### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect EACCES 10.239.4.160:913

### ISSUE THREAD

**Issue by ITchaoge** [atom/atom#18495]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect EACCES 10.239.4.160:913

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, cause=connect EACCES 10.239.4.160:913
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
  7x -7:06.4.0 core:backspace (input.hidden-input)
     -6:18.8.0 core:paste (div.line)
  8x -6:17.4.0 core:backspace (input.hidden-input)
     -3:20.8.0 github:toggle-git-tab (div.package-detail.panels-item)
  2x -3:06.7.0 github:toggle-github-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:32.6.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -2:27.9.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -2:27.9.0 symbols-view:toggle-project-symbols (input.hidden-input)
  5x -2:23.4.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -2:22.8.0 core:undo (input.hidden-input)
  3x -0:18.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-java-snippets 0.5.1 
atom-terminal-panel 4.4.4 
autocomplete-ansible 0.1.24 
autocomplete-java 1.2.7 
autocomplete-json 5.5.2 
autocomplete-paths 2.12.2 
autocomplete-python 1.11.0 
autocomplete-python-jedi 1.10.3-0 
docblockr 0.13.7 
ex-mode 0.18.0 
file-icons 2.1.26 
language-ansible 0.2.2 
minimap 4.29.9 
python-snippets 1.9.0 
relative-numbers 0.9.0 
script 3.18.1 
sublime-block-comment 0.5.1 
vim-mode 0.66.0 
```

**Comment by rsese** [comment]
Thanks for the report! Are you using a network proxy? In case this is a temporary network or proxy issue, please try again later and see if you continue getting the same error.
