### ISSUE TITLE
Uncaught TypeError: Cannot read property 'collapsed' of null

### ISSUE THREAD

**Issue by jonsterling** [atom/atom#18526]
[Enter steps to reproduce:]

1. Install the `ide-reason` package while having the folder of an OCaml project open

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Ubuntu 18.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'collapsed' of null

```
At /usr/share/atom/resources/app/static/<embedded>:14

TypeError: Cannot read property 'collapsed' of null
    at elementForObject (/usr/share/atom/resources/app/static/<embedded>:14:2921783)
    at elementForSetting (/usr/share/atom/resources/app/static/<embedded>:14:2922228)
    at elementForObject (/usr/share/atom/resources/app/static/<embedded>:14:2922167)
    at elementForSetting (/usr/share/atom/resources/app/static/<embedded>:14:2922228)
    at SettingsPanel.elementForSettings (/usr/share/atom/resources/app/static/<embedded>:14:2913082)
    at new SettingsPanel (/usr/share/atom/resources/app/static/<embedded>:14:2911604)
    at PackageDetailView.updateInstalledState (/usr/share/atom/resources/app/static/<embedded>:14:733821)
    at PackageDetailView.populate (/usr/share/atom/resources/app/static/<embedded>:14:733172)
    at PackageDetailView.completeInitialization (/usr/share/atom/resources/app/static/<embedded>:14:728547)
    at PackageDetailView.loadPackage (/usr/share/atom/resources/app/static/<embedded>:14:728759)
    at /usr/share/atom/resources/app/static/<embedded>:14:735475
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1189772)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191213)
    at PackageManager.t.exports.PackageManager.emitPackageEvent (/usr/share/atom/resources/app/static/<embedded>:11:919306)
    at /usr/share/atom/resources/app/static/<embedded>:11:916715
    at r (/usr/share/atom/resources/app/static/<embedded>:11:911245)
    at o (/usr/share/atom/resources/app/static/<embedded>:14:1036521)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1036675)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1035277)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
```

### Non-Core Packages

```
ide-reason 1.1.1 
language-ocaml 1.9.5 
language-reason 0.0.4 
ocaml-merlin 0.14.7 
```

**Comment by rsese** [comment]
Thanks for the report!

> 1. Install the `ide-reason` package while having the folder of an OCaml project open

Since the error is specific to using `ide-reason`, we suggest opening the issue in that [package repository](https://atom.io/packages/ide-reason) to start.  It may be that there is still a bug in Atom and if so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
