### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tags' of undefined

### ISSUE THREAD

**Issue by peter92427** [atom/atom#18590]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

This bug was reported before but was not solved and is locked.
https://github.com/atom/atom/issues/17010

### Description

Uncaught TypeError: Cannot read property 'tags' of undefined

### Steps to Reproduce

1. Toggle Split Diff from Packages
2. Paste in the left tab
3. Paste in the right tab

**Expected behavior:** Diff of contents

**Actual behavior:** Uncaught TypeError

**Reproduces how often:** Every time

### Versions

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Mac OS X 10.14.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'tags' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Cannot read property 'tags' of undefined
    at TextMateHighlightIterator.seek (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:559985)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1102867)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:89306)
    at DisplayLayer.getScreenLine (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:89203)
    at TextEditor.screenLineForScreenRow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:13891)
    at TextEditorComponent.requestHorizontalMeasurement (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:104697)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:69772)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:67605)
    at TextEditorComponent.didShow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:91235)
    at TextEditorComponent.didFocus (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:91426)
    at HTMLElement.addEventListener (/app.asar/src/text-editor-element.js:36:67)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:164:16)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190583)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1192024)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:455231)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:457479)
    at TabBarView.t.exports.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1141088)
```

### Commands

```
```

### Non-Core Packages

```
split-diff 1.5.3 
```

**Comment by rsese** [comment]
Thanks for opening another issue for this - looks like I missed the fact that they mentioned the split-diff community package.  Since the errors sounds specific to using split-diff, we recommend contacting the maintainers of that package but it looks like this has been reported already:

https://github.com/mupchrch/split-diff/issues/151

It may be that there is a bug in Atom but if so, we'll need the split-diff maintainers to help track that down so they can either fix the problem or tell us where the problem is coming from.
