### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=503

### ISSUE THREAD

**Issue by MATE10** [atom/atom#18632]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=503

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at Socket.socketOnData (_http_client.js:472:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -3:06.3.0 core:paste (input.hidden-input)
     -1:58.1.0 core:select-all (input.hidden-input)
     -1:57.7.0 core:backspace (input.hidden-input)
     -1:57.6.0 core:paste (input.hidden-input)
     -1:30.8.0 core:select-all (input.hidden-input)
     -1:30.6.0 core:backspace (input.hidden-input)
     -1:30.3.0 core:paste (input.hidden-input)
     -1:09.7.0 core:select-all (input.hidden-input)
     -1:09.4.0 core:backspace (input.hidden-input)
     -1:04.3.0 core:paste (input.hidden-input)
     -1:01.6.0 core:backspace (input.hidden-input)
     -0:47.7.0 core:select-all (input.hidden-input)
     -0:47.2.0 core:backspace (input.hidden-input)
     -0:47 core:paste (input.hidden-input)
     -0:44.9.0 core:backspace (input.hidden-input)
     -0:10.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
autocomplete-paths 2.12.2 
autocomplete-python 1.11.0 
busy-signal 1.4.3 
hydrogen-python 0.0.8 
intentions 1.1.5 
kite 0.131.0 
last-cursor-position 0.9.3 
linter 2.2.0 
linter-pylama 0.10.1 
linter-python-pep8 0.2.0 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
platformio-ide-terminal 2.8.4 
python-debugger 0.2.0 
python-tools 0.6.9 
simplified-chinese-menu 5.3.5 
sync-settings 0.8.6 
```

**Comment by rsese** [comment]
Thanks for the report! Are you using a network proxy? This seems like it could be a temporary network issue or an issue with authenticating to your proxy based on the error code? Please try again later and see if you continue getting the same error.
