### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\atom-beautify\README...

### ISSUE THREAD

**Issue by m-petrosyan** [atom/atom#18633]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Pc\.atom\packages\atom-beautify\README.md'

```
At fs.js:646

Error: ENOENT: no such file or directory, open 'C:\Users\Pc\.atom\packages\atom-beautify\README.md'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Proxy.fs.readFileSync (fs.js:551:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at PackageDetailView.renderReadme (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:735758)
    at PackageDetailView.updateInstalledState (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:735518)
    at PackageDetailView.populate (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:734070)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:729445)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:729657)
    at ~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:736373
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:1190759)
    at Emitter.emit (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:1192200)
    at PackageManager.t.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:920293)
    at ~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:917702
    at r (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:912232)
    at o (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:1037419)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:1037625)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -5:53.7.0 core:confirm (input.hidden-input)
     -5:51.2.0 core:select-all (input.hidden-input)
     -5:51 core:backspace (input.hidden-input)
     -5:46.9.0 core:select-all (input.hidden-input)
     -5:39.8.0 core:confirm (input.hidden-input)
     -5:33.3.0 core:select-all (input.hidden-input)
     -5:33.1.0 core:paste (input.hidden-input)
     -5:32.9.0 core:confirm (input.hidden-input)
     -5:21.5.0 core:select-all (input.hidden-input)
     -5:21.2.0 core:paste (input.hidden-input)
  2x -5:21.1.0 core:confirm (input.hidden-input)
     -3:26 find-and-replace:show (div.package-detail.panels-item)
     -3:23.2.0 core:confirm (input.hidden-input)
     -0:24.2.0 core:select-all (input.hidden-input)
     -0:23.9.0 core:backspace (input.hidden-input)
     -0:13 atom-beautify:beautify-editor (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
emmet 2.4.3 
file-icons 2.1.27 
local-history 4.3.1 
minimap 4.29.9 
```

**Comment by rsese** [comment]
Thanks for the report! Did you have any trouble or errors when installing atom-beautify?  If you uninstall/reinstall does that help?  

x-ref: https://github.com/atom/atom/issues/18151
