### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\simplified-chinese-m...

### ISSUE THREAD

**Issue by yunsonshu** [atom/atom#18656]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\SHU00\.atom\packages\simplified-chinese-menu\README.md'

```
At fs.js:646

Error: ENOENT: no such file or directory, open 'C:\Users\SHU00\.atom\packages\simplified-chinese-menu\README.md'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Proxy.fs.readFileSync (fs.js:551:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at PackageDetailView.renderReadme (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:735758)
    at PackageDetailView.updateInstalledState (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:735518)
    at PackageDetailView.populate (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:734070)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:729445)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:729657)
    at ~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:736373
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:1190759)
    at Emitter.emit (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:1192200)
    at PackageManager.t.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:920293)
    at ~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:917702
    at r (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:912232)
    at o (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:1037419)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:1037625)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
```

### Non-Core Packages

```
simplified-chinese-menu 5.3.5 
```

**Comment by rsese** [comment]
Thanks for the report! Did you have any trouble or errors when installing simplified-chinese-menu?  If you uninstall/reinstall does that help?  

x-ref: https://github.com/atom/atom/issues/18151, https://github.com/atom/atom/issues/18633
