### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/c6/8hc5m2bd1r3cc25tpn0b6p5r0000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by taoistbear** [atom/atom#18655]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/c6/8hc5m2bd1r3cc25tpn0b6p5r0000gn/T/AppTranslocation/5F2D6B2B-8B0D-48C2-96AD-59791CB56DC3/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At ELECTRON_ASAR.js:166

Error: dlopen(/private/var/folders/c6/8hc5m2bd1r3cc25tpn0b6p5r0000gn/T/AppTranslocation/5F2D6B2B-8B0D-48C2-96AD-59791CB56DC3/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/private/var/folders/c6/8hc5m2bd1r3cc25tpn0b6p5r0000gn/T/AppTranslocation/5F2D6B2B-8B0D-48C2-96AD-59791CB56DC3/d/Atom.app/Contents/Resources/app/static/<embedded>:1:637522)
    at get_KeyboardLayoutManager (/private/var/folders/c6/8hc5m2bd1r3cc25tpn0b6p5r0000gn/T/AppTranslocation/5F2D6B2B-8B0D-48C2-96AD-59791CB56DC3/d/Atom.app/Contents/Resources/app/static/<embedded>:14:3076896)
    at get_manager (/private/var/folders/c6/8hc5m2bd1r3cc25tpn0b6p5r0000gn/T/AppTranslocation/5F2D6B2B-8B0D-48C2-96AD-59791CB56DC3/d/Atom.app/Contents/Resources/app/static/<embedded>:14:3076976)
    at Object.getCurrentKeyboardLayout (/private/var/folders/c6/8hc5m2bd1r3cc25tpn0b6p5r0000gn/T/AppTranslocation/5F2D6B2B-8B0D-48C2-96AD-59791CB56DC3/d/Atom.app/Contents/Resources/app/static/<embedded>:14:3077102)
    at e.keystrokeForKeyboardEvent (/private/var/folders/c6/8hc5m2bd1r3cc25tpn0b6p5r0000gn/T/AppTranslocation/5F2D6B2B-8B0D-48C2-96AD-59791CB56DC3/d/Atom.app/Contents/Resources/app/static/<embedded>:14:996456)
    at KeymapManager.t.exports.KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/c6/8hc5m2bd1r3cc25tpn0b6p5r0000gn/T/AppTranslocation/5F2D6B2B-8B0D-48C2-96AD-59791CB56DC3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1228483)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/c6/8hc5m2bd1r3cc25tpn0b6p5r0000gn/T/AppTranslocation/5F2D6B2B-8B0D-48C2-96AD-59791CB56DC3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1226468)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/c6/8hc5m2bd1r3cc25tpn0b6p5r0000gn/T/AppTranslocation/5F2D6B2B-8B0D-48C2-96AD-59791CB56DC3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:285213)
```

### Commands

```
     -1:01.1.0 core:copy (div.package-readme.native-key-bindings)
```

### Non-Core Packages

```
emmet 2.4.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

x-ref: https://github.com/atom/atom/issues/15861
