### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by zubize** [atom/atom#18696]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At C:\Users\User-Kalpa\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:14

TypeError: Cannot read property 'version' of undefined
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:2917806
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:896785
    at r (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:893791)
    at o (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032547)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032753)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by t-rop** [comment]
while i dont know what @zubize did, i just had the same error:
C:\Users\myUser\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:14
Hide Stack Trace
TypeError: Cannot read property 'version' of undefined
    at C:\Users\myUser\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:14:2917806
    at C:\Users\myUser\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:896785
    at r (C:\Users\myUser\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:893791)
    at o (C:\Users\myUser\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:14:1032547)
    at ChildProcess.n.process.on.e (C:\myUser\Thomas\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:14:1032753)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

this error occured when i installed packages.
since i installed multiple at once, i cannot simply pinpoint it. If it helps, this is the list i went by:
    atom-beautify
    atom-html-preview
    document-outline
    git-plus
    language-knitr
    language-latex
    latex
    language-markdown
    merge-conflicts
    minimap-split-diff

**Comment by fohuhu** [comment]
I had the same error:
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: Cannot read property 'version' of undefined
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2917238
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:896785
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:893791)
    at o (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1032609)
    at e.bufferStream (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1032697)
    at Socket.e.on (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1031365)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
@fohuhu - if you have steps to reproduce the error, please open a new issue with the template filled out and we'll take a look.
