### ISSUE TITLE
Uncaught AssertionError [ERR_ASSERTION]: 5389 == 0

### ISSUE THREAD

**Issue by jeftejb** [atom/atom#18706]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught AssertionError [ERR_ASSERTION]: 5389 == 0

```
At assert.js:42

AssertionError [ERR_ASSERTION]: 5389 == 0
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:160:14)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at Socket.socketOnData (_http_client.js:472:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
```

### Non-Core Packages

```
git-clone 0.2.0 
teletype 0.13.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error (were you using Teletype)?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

**Comment by rsese** [comment]
Just found https://github.com/atom/atom/issues/14074, going to go ahead and close in favor of that issue if you want to subscribe there.  So if you have specific steps to reproduce, please let us know in https://github.com/atom/atom/issues/14074, thanks again for reporting :v:
