### ISSUE TITLE
Build on linux fails with SyntaxError

### ISSUE THREAD

**Issue by MarrekNozka** [atom/atom#18713]
I am using Devuan Linux (Ascii, 64-bit machine). I am getting the following error while running
`script/build`:

```
/home/marek/src/atom-1.35.0-beta0/script/config.js:79
function getNpmBinPath (external = false) {
                                 ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/marek/src/atom-1.35.0-beta0/script/bootstrap:6:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by rsese** [comment]
Thanks for reaching out!

None of us uses Devuan so I'm not sure how much help we can be but since it's seems to be Debian based, did you follow all the requirements mentioned in the Flight Manual before building?

https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#requirements-1

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by MarrekNozka** [comment]
Thanks... and .. sorry.

**Comment by Aerijo** [comment]
@MarrekNozka What node version was it using? It looks like it's tripping on default argument syntax, so it may be outdated. For best results, try building Atom with NodeJS v8.9.3

**Comment by MarrekNozka** [comment]
@Aerijo Thanks. I upgrade Node from backports to version 8.11.1 and error message different now :-)
I must check requirements better.

```
Node:	v8.11.1
child_process.js:624
    throw err;
    ^

Error: spawnSync npm ENOENT
    at _errnoException (util.js:1022:11)
    at spawnSync (child_process.js:579:20)
    at Object.execFileSync (child_process.js:616:13)
    at verifyNpm (/home/marek/src/atom-1.35.0-beta0/script/lib/verify-machine-requirements.js:31:31)
    at module.exports (/home/marek/src/atom-1.35.0-beta0/script/lib/verify-machine-requirements.js:11:3)
    at Object.<anonymous> (/home/marek/src/atom-1.35.0-beta0/script/bootstrap:29:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

However after upgrade node official debian package works well.

**Comment by Aerijo** [comment]
@MarrekNozka Did you manage to build it?

**Comment by rsese** [comment]
If you didn't manage to build successfully, maybe try running `./script/clean` and then try building again?

**Comment by MarrekNozka** [comment]
@Aerijo @rsese Yes! I did it! :grinning: 

I have upgraded Node to v8.11.1 and Npm to v5.8.0 from backports repository. I ran `script/build --create-debian-package ` and have got this Error:

```
Node:	v8.11.1
child_process.js:624
    throw err;
    ^

Error: spawnSync npm ENOENT
    at _errnoException (util.js:1022:11)
    at spawnSync (child_process.js:579:20)
    at Object.execFileSync (child_process.js:616:13)
    at verifyNpm (/root/src/atom-1.35.0-beta0/script/lib/verify-machine-requirements.js:31:31)
    at module.exports (/root/src/atom-1.35.0-beta0/script/lib/verify-machine-requirements.js:11:3)
    at Object.<anonymous> (/root/src/atom-1.35.0-beta0/script/bootstrap:29:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

After this I ran 

    npm install npm && script/build --create-debian-package 

and it has managed to build successfully. Key is clearly **upgrade Npm**.
