### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\php-getters-setters\...

### ISSUE THREAD

**Issue by emilioOP** [atom/atom#18726]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Emilio\.atom\packages\php-getters-setters\README.md'

```
At fs.js:646

Error: ENOENT: no such file or directory, open 'C:\Users\Emilio\.atom\packages\php-getters-setters\README.md'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Proxy.fs.readFileSync (fs.js:551:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at PackageDetailView.renderReadme (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:731640)
    at PackageDetailView.updateInstalledState (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:731400)
    at PackageDetailView.populate (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:729952)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:725327)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:725539)
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:732255
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1173759)
    at PackageManager.t.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:901852)
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:899261
    at r (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:893791)
    at o (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032547)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032753)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -1:15.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
php-getters-setters 0.5.5 
```

**Comment by Aerijo** [comment]
And is the file actually there?

**Comment by emilioOP** [comment]
I fixed it. I don't know how, but it's working now.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by rsese** [comment]
> I fixed it. I don't know how, but it's working now.

:+1:

We'll go ahead and close in favor of https://github.com/atom/atom/issues/18656.
