### ISSUE TITLE
Uncaught TypeError: Parameter "url" must be a string, not boolean

### ISSUE THREAD

**Issue by dte005** [atom/atom#18767]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Parameter "url" must be a string, not boolean

```
At url.js:103

TypeError: Parameter "url" must be a string, not boolean
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at URIPattern.matches (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:3339398)
    at ItemWatcher.itemMatches.e [as itemMatches] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:4341360)
    at ItemWatcher.isActiveItem (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:4341638)
    at ItemWatcher.updateActiveState (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:4341110)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1173759)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:446615)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:446092)
    at Pane.activate (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:463512)
    at Pane.focus (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:454965)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
  2x -0:33.5.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
  2x -0:22.4.0 browser-plus:open (div.panels-item)
```

### Non-Core Packages

```
atom-bootstrap4 1.4.0 
atom-django 0.3.2 
atom-python-package 0.7.1 
atomic-design-ui 1.2.1 
autoclose-html 0.23.0 
autocomplete-python 1.12.0 
browser-plus 0.0.98 
file-icons 2.1.29 
MagicPython 1.1.1 
python-debugger 0.2.0 
python-indent 1.1.6 
script 3.18.1 
todo 0.6.0 
tool-bar 1.1.11 
tool-bar-main 0.0.11 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the https://atom.io/packages/browser-plus package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

---

Also, looks like this has been reported already here:

https://github.com/skandasoft/browser-plus/issues/187
