### ISSUE TITLE
MacOS installation using port fails on TypeError

### ISSUE THREAD

**Issue by habernal** [atom/atom#18811]
### Description

Installing atom using port on MacOS fails with the following error:

```
:info:build Traceback (most recent call last):
:info:build   File "./gyp-mac-tool", line 611, in <module>
:info:build     sys.exit(main(sys.argv[1:]))
:info:build   File "./gyp-mac-tool", line 28, in main
:info:build     exit_code = executor.Dispatch(args)
:info:build   File "./gyp-mac-tool", line 43, in Dispatch
:info:build     return getattr(self, method)(*args[1:])
:info:build   File "./gyp-mac-tool", line 246, in ExecFilterLibtool
:info:build     if not libtool_re.match(line) and not libtool_re5.match(line):
:info:build TypeError: cannot use a string pattern on a bytes-like object
:info:build make: *** [Release/git2.a] Error 1
:info:build gyp ERR! build error 
:info:build gyp ERR! stack Error: `make` failed with exit code: 2
:info:build gyp ERR! stack     at ChildProcess.onExit (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_atom/atom/work/atom-1.34.0/script/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
:info:build gyp ERR! stack     at emitTwo (events.js:126:13)
:info:build gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
:info:build gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
:info:build gyp ERR! System Darwin 18.2.0
:info:build gyp ERR! command "/opt/local/bin/node" "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_atom/atom/work/atom-1.34.0/script/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
:info:build gyp ERR! cwd /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_atom/atom/work/atom-1.34.0/apm/node_modules/atom-package-manager/node_modules/git-utils
:info:build gyp ERR! node -v v8.15.0
:info:build gyp ERR! node-gyp -v v3.7.0
:info:build gyp ERR! not ok 
:info:build npm ERR! code ELIFECYCLE
:info:build npm ERR! errno 1
:info:build npm ERR! git-utils@4.1.4 install: `node-gyp rebuild`
:info:build npm ERR! Exit status 1
:info:build npm ERR! 
:info:build npm ERR! Failed at the git-utils@4.1.4 install script.
:info:build npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
:info:build npm ERR! A complete log of this run can be found in:
:info:build npm ERR!     /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_atom/atom/work/.home/.npm/_logs/2019-02-07T08_24_12_925Z-debug.log
:info:build child_process.js:630
:info:build     throw err;
:info:build     ^
:info:build Error: Command failed: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_atom/atom/work/atom-1.34.0/script/node_modules/.bin/npm --global-style --loglevel=error install
```

### Steps to Reproduce

```
port install atom
```

### Versions

```
bash-3.2$ port
MacPorts 2.5.4
```

```
MacOS Mojave 10.14.2
```

**Comment by lee-dohm** [comment]
We don't maintain the port installer of Atom. You'll have to contact the maintainers of it and report the issue to them.

If you'd like to install a version of Atom that we do support, you can download it from https://atom.io.
