### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.34.0\ Stoneh...

### ISSUE THREAD

**Issue by avdean** [atom/atom#18817]
[Enter steps to reproduce:]

1. Moved file in Project sub-folder to another sub-folder

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\antvi\AppData\Local\atom\app-1.34.0\ Stonehenge

**Comment by avdean** [comment]
Stack Trace says this> 

Error: ENOENT: no such file or directory, lstat 'C:\Users\antvi\AppData\Local\atom\app-1.34.0\ Stonehenge & Oxford Tour.html'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at TreeView.t.exports.TreeView.moveEntry (C:\Users\antvi\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:14:911621)
    at TreeView.t.exports.TreeView.onDrop (C:\Users\antvi\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:14:917375)
    at HTMLDivElement.<anonymous> (C:\Users\antvi\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:14:892215)
