### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getState' of undefined

### ISSUE THREAD

**Issue by ty-everett** [atom/atom#18843]
[Enter steps to reproduce:]

- I held down control and scrolled up to increase the font size

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Ubuntu 18.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getState' of undefined

```
At /snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11

TypeError: Cannot read property 'getState' of undefined
    at subscriptions.add.c.onDidChange (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:156792)
    at Function.simpleDispatch (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:1190133)
    at Emitter.emit (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:1191574)
    at UpdateManager.emitDidChange (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:612493)
    at subscriptions.add.atom.config.observe.e (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:612352)
    at onDidChangeKeyPath.e (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:335237)
    at emitter.on (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:335418)
    at Function.simpleDispatch (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:1190133)
    at Emitter.emit (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:1191574)
    at Config.emitChangeEvent (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:337906)
    at Config.endTransaction (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:332677)
    at Config.transact (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:332296)
    at Config._resetSettings (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:333929)
    at Config.resetUserSettings (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:333696)
    at disposables.add.applicationDelegate.onDidChangeUserSettings.e (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:1:658784)
    at ipcMessageEmitter.on.t (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:1:675116)
    at Function.simpleDispatch (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:1190133)
    at Emitter.emit (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:1191574)
    at EventEmitter._ipcMessageEmitter.get_ipcRenderer.on (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:1:671740)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -0:51.8.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:42.5.0 core:confirm (input.hidden-input)
     -0:37.2.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:34.6.0 core:confirm (input.hidden-input)
  2x -0:25.4.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
atom-save-all 0.4.1 
busy-signal 2.0.0 
intentions 1.1.5 
linter 2.3.0 
linter-eslint 8.5.2 
linter-spell 0.15.0 
linter-spell-javascript 0.9.0 
linter-ui-default 1.7.1 
multi-cursor 2.1.5 
```

**Comment by rsese** [comment]
Thanks for the report!

> At /snap/atom/

Looks like you're using the Snap install?  The Snap install is unofficial, if you can reproduce with a supported installation method (https://flight-manual.atom.io/getting-started/sections/installing-atom/), please let us know and we can reopen.
