### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\go-plus\README.md'

### ISSUE THREAD

**Issue by DongwonTTuna** [atom/atom#18890]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Dongwon\.atom\packages\go-plus\README.md'

```
At fs.js:646

Error: ENOENT: no such file or directory, open 'C:\Users\Dongwon\.atom\packages\go-plus\README.md'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Proxy.fs.readFileSync (fs.js:551:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at PackageDetailView.renderReadme (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:731640)
    at PackageDetailView.updateInstalledState (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:731400)
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:732271
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1173759)
    at PackageManager.t.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:901852)
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:899261
    at r (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:893791)
    at o (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032547)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032753)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
  3x -3:48.9.0 pane:reopen-closed-item (input.hidden-input)
     -2:49 core:paste (input.hidden-input)
     -2:08.7.0 atom-terminal:open-project-root (input.hidden-input)
     -2:00.5.0 atom-terminal:open (input.hidden-input)
     -1:41.8.0 core:paste (input.hidden-input)
     -0:15.2.0 golang:update-tools (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-terminal 0.8.0 
go-plus 6.1.0 
```

**Comment by rsese** [comment]
Thanks for the report! Did you have any trouble or errors when installing go-plus?  If you uninstall/reinstall does that help?

x-ref: #18151, #18633
