### ISSUE TITLE
Uncaught Error: libxkbfile.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by OfficialThing** [atom/atom#18945]
[Enter steps to reproduce:]

1. Edit a file.
2. Press Ctrl + V

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Debian GNU/Linux
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: libxkbfile.so.1: cannot open shared object file: No such file or directory

```
At ELECTRON_ASAR.js:166

Error: libxkbfile.so.1: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/home/chronos/renpy-7.2.0-sdk/atom/atom-linux-x86_64/resources/app/static/<embedded>:1:639511)
    at get_KeyboardLayoutManager (/home/chronos/renpy-7.2.0-sdk/atom/atom-linux-x86_64/resources/app/static/<embedded>:14:3078116)
    at get_manager (/home/chronos/renpy-7.2.0-sdk/atom/atom-linux-x86_64/resources/app/static/<embedded>:14:3078196)
    at Object.getCurrentKeyboardLayout (/home/chronos/renpy-7.2.0-sdk/atom/atom-linux-x86_64/resources/app/static/<embedded>:14:3078322)
    at e.keystrokeForKeyboardEvent (/home/chronos/renpy-7.2.0-sdk/atom/atom-linux-x86_64/resources/app/static/<embedded>:14:996699)
    at KeymapManager.t.exports.KeymapManager.keystrokeForKeyboardEvent (/home/chronos/renpy-7.2.0-sdk/atom/atom-linux-x86_64/resources/app/static/<embedded>:11:1227857)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/home/chronos/renpy-7.2.0-sdk/atom/atom-linux-x86_64/resources/app/static/<embedded>:11:1225842)
    at WindowEventHandler.handleDocumentKeyEvent (/home/chronos/renpy-7.2.0-sdk/atom/atom-linux-x86_64/resources/app/static/<embedded>:11:285234)
```

### Commands

```
```

### Non-Core Packages

```
language-renpy 2.5.0 
renpy-dark-syntax 1.2.0 
renpy-light-syntax 1.2.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if you installed Atom with one of the [supported installation methods](https://flight-manual.atom.io/getting-started/sections/installing-atom/)?

Manually installing `libxkbfile1` might clear up the error, x-ref: https://github.com/atom/atom/issues/13591
