### ISSUE TITLE
Uncaught Error: URIHandlerRegistry#handleURI asked to handle an invalid URI: atom://192.168.7.143...

### ISSUE THREAD

**Issue by guardianf** [atom/atom#18956]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: URIHandlerRegistry#handleURI asked to handle an invalid URI: atom://192.168.7.143:8080/ms_fyb/index.html

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

Error: URIHandlerRegistry#handleURI asked to handle an invalid URI: atom://192.168.7.143:8080/ms_fyb/index.html
    at URIHandlerRegistry.handleURI (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:351817)
    at AtomEnvironment.dispatchURIMessage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:669384)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:676872)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
```

### Commands

```
     -5:27 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
emmet 2.4.3 
language-vue 0.24.0 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 1.1.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?
