### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buffer' of null on macOS 10.14

### ISSUE THREAD

**Issue by charonferry** [atom/atom#18969]
[Enter steps to reproduce:]

1. Open the Terminal in Atom
2. Press ^D (control + D) key to exit
3. Be thrown this 

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.3
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.13.0

### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of null

```
At /Users/Xxxxx/.atom/packages/atom-ide-ui/node_modules/xterm/lib/InputHandler.js:183

TypeError: Cannot read property 'buffer' of null
    at InputHandler.parse (/packages/atom-ide-ui/node_modules/xterm/lib/InputHandler.js:183:37)
    at Terminal._innerWrite (/packages/atom-ide-ui/node_modules/xterm/lib/Terminal.js:841:32)
    at /packages/atom-ide-ui/node_modules/xterm/lib/Terminal.js:826:23
```

### Commands

```
     -9:01.1.0 core:copy (input.hidden-input)
     -8:58.6.0 find-and-replace:show (input.hidden-input)
     -8:57.7.0 core:backspace (input.hidden-input)
     -8:27.8.0 core:paste (input.hidden-input)
     -8:23.8.0 find-and-replace:show (input.hidden-input)
     -8:23.1.0 core:backspace (input.hidden-input)
     -8:04.4.0 core:paste (input.hidden-input)
  3x -7:43.1.0 core:backspace (input.hidden-input)
  2x -7:32.9.0 core:paste (input.hidden-input)
     -7:25.7.0 core:save (input.hidden-input)
     -6:46.8.0 core:paste (input.hidden-input)
  3x -6:29.7.0 core:backspace (input.hidden-input)
     -6:27.8.0 core:confirm (input.hidden-input)
  2x -5:52.8.0 core:paste (input.hidden-input)
     -5:36.8.0 core:save (input.hidden-input)
     -0:16 atom-ide-terminal:new-terminal (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-java 1.2.7 
autocomplete-paths 2.12.2 
emmet 2.4.3 
file-icons 2.1.30 
highlight-selected 0.14.0 
ide-java 0.8.3 
ide-scala 0.8.2 
ide-typescript 0.8.0 
language-scala 1.1.9 
language-swift 0.5.0 
language-vue 0.24.0 
minimap 4.29.9 
project-manager 3.3.6 
show-ideographic-space 1.0.2 
split-diff 1.6.0 
```

**Comment by rsese** [comment]
Thanks for the report!

> **Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.13.0

This error is coming from atom-ide-ui, please see this blog post for more details about the package:

https://blog.atom.io/2018/12/12/facebook-retires-nuclide-extension.html

And you may want to follow along with this community effort to provide IDE functionality:

https://atom-ide-community.github.io/

**Comment by charonferry** [comment]
Thanks for replay!
I was misunderstood.
