### ISSUE TITLE
HELP !!! Fetching featured packages 

### ISSUE THREAD

**Issue by miggymiggoi** [atom/atom#19008]
![image](https://user-images.githubusercontent.com/48637634/54585359-16c02c00-49d7-11e9-83e2-39c79c34dfd3.png)

Uncaught (in promise) Error: Fetching local packages failed.
    at l (C:\Users\Parallax\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:902206)
    at C:\Users\Parallax\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:902348
    at Function.simpleDispatch (C:\Users\Parallax\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:1172354)
    at Emitter.emit (C:\Users\Parallax\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:1173795)
    at BufferedProcess.handleError (C:\Users\Parallax\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:1033733)
    at ChildProcess.process.on.e (C:\Users\Parallax\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:1033676)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
<embedded>:11 Uncaught (in promise) Error: Fetching outdated packages and themes failed.
    at l (C:\Users\Parallax\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:902206)
    at C:\Users\Parallax\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:902348
    at Function.simpleDispatch (C:\Users\Parallax\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:1172354)
    at Emitter.emit (C:\Users\Parallax\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:1173795)
    at BufferedProcess.handleError (C:\Users\Parallax\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:1033733)
    at ChildProcess.process.on.e (C:\Users\Parallax\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:1033676)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by miggymiggoi** [comment]
I'm totally new in programming especially in using atom. I heard this is a great community so, I gave it a shot. thanks i tried changing path nothing happens or there's something i did wrong

**Comment by miggymiggoi** [comment]
![image](https://user-images.githubusercontent.com/48637634/54585601-be3d5e80-49d7-11e9-93a2-b9b8d7f7f63e.png)

**Comment by miggymiggoi** [comment]
![image](https://user-images.githubusercontent.com/48637634/54585629-d6ad7900-49d7-11e9-93fe-616e084cccd6.png)
Guys Please take a look at my PATH

**Comment by lee-dohm** [comment]
Thanks for reaching out.

If you're looking for assistance in fixing a problem that you're having and not reporting a bug, you should refer to the [support resources](https://github.com/atom/atom/blob/master/SUPPORT.md) that were pointed to in both the header of the new issue form and in the issue template itself.

If you're reporting a bug, we require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
