### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.35.1\res...

### ISSUE THREAD

**Issue by saifuldhaka** [atom/atom#19018]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\User\AppData\Local\atom\app-1.35.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:166

Error: The specified module could not be found.
\\?\C:\Users\User\AppData\Local\atom\app-1.35.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:1:666612)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:14:3064744)
    at get_manager (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:14:3064824)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:14:3064950)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:14:992405)
    at KeymapManager.t.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:1210078)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:1208063)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:285196)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.0 
autoclose-html 0.23.0 
autocomplete-json 5.5.2 
autocomplete-xml 0.10.1 
busy-signal 1.4.3 
emmet 2.4.3 
git-log 0.4.1 
highlight-selected 0.14.0 
hyperclick 0.1.5 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-blade 0.41.2 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
php-integrator-autocomplete-plus 1.6.2 
php-integrator-navigation 1.2.1 
pigments 0.40.2 
simple-drag-drop-text 0.4.0 
Sublime-Style-Column-Selection 1.7.4 
ui 0.2.0 
vue-autocomplete 0.1.1 
```

**Comment by PrimerMediaGroup** [comment]
Bible vest Stone
