### ISSUE TITLE
NPM Unexpected end of JSON

### ISSUE THREAD

**Issue by IIPoliII** [atom/atom#19056]
Hello,
So i tried to install an atom package named "ftp-remote-edit" on my pc.
I installed it on my work pc yesterday it's perfectly working but on this pc i get this error and i can't found any information on the web any ideas ?

```
C:\Users\raimu>apm install ftp-remote-edit
Installing ftp-remote-edit to C:\Users\raimu\.atom\packages failed

npm ERR! Unexpected end of JSON input while parsing near '...ist":{"shasum":"aea74'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\raimu\.atom\.apm\_logs\2019-03-26T15_02_31_207Z-debug.log


```

thanks Poli

**Comment by IIPoliII** [comment]
Oh and of course the log file
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\raimu\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\raimu\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\raimu\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\raimu\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/ftp-remote-edit/versions/0.14.1/tarball',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=2.0.18',
1 verbose cli   '--dist-url=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v8.9.3
4 verbose npm-session 14682039abfab2b7
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://www.atom.io/api/packages/ftp-remote-edit/versions/0.14.1/tarball 3367ms
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/ftp-remote-edit/versions/0.14.1/tarball fetched in 3388ms
9 timing stage:loadCurrentTree Completed in 3591ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule ftp-remote-edit@0.14.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/atom-select-list 240ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/atom-space-pen-views 243ms (from cache)
19 silly pacote range manifest for atom-select-list@^0.3.0 fetched in 247ms
20 silly resolveWithNewModule atom-select-list@0.3.2 checking installable status
21 http fetch GET 304 https://registry.npmjs.org/fs-plus 247ms (from cache)
22 silly pacote range manifest for atom-space-pen-views@^2.2.0 fetched in 249ms
23 silly resolveWithNewModule atom-space-pen-views@2.2.0 checking installable status
24 http fetch GET 304 https://registry.npmjs.org/md5 249ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/p-queue 246ms (from cache)
26 http fetch GET 304 https://registry.npmjs.org/fuzzaldrin-plus 251ms (from cache)
27 silly pacote range manifest for fs-plus@^3.1.1 fetched in 252ms
28 silly resolveWithNewModule fs-plus@3.1.1 checking installable status
29 silly pacote range manifest for md5@^2.2.1 fetched in 254ms
30 silly resolveWithNewModule md5@2.2.1 checking installable status
31 silly pacote range manifest for p-queue@^3.0.0 fetched in 254ms
32 silly resolveWithNewModule p-queue@3.2.0 checking installable status
33 silly pacote range manifest for fuzzaldrin-plus@^0.5.0 fetched in 258ms
34 silly resolveWithNewModule fuzzaldrin-plus@0.5.0 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/fuzzaldrin 261ms (from cache)
36 silly pacote range manifest for fuzzaldrin@^2.1.0 fetched in 262ms
37 silly resolveWithNewModule fuzzaldrin@2.1.0 checking installable status
38 http fetch GET 304 https://registry.npmjs.org/progress-stream 262ms (from cache)
39 silly pacote range manifest for progress-stream@^2.0.0 fetched in 263ms
40 silly resolveWithNewModule progress-stream@2.0.0 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/minimatch 266ms (from cache)
42 silly pacote range manifest for minimatch@^3.0.2 fetched in 267ms
43 silly resolveWithNewModule minimatch@3.0.4 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/ssh2 53ms (from cache)
45 silly pacote range manifest for ssh2@^0.8.2 fetched in 54ms
46 silly resolveWithNewModule ssh2@0.8.2 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/short-hash 387ms (from cache)
48 silly pacote range manifest for short-hash@^1.0.0 fetched in 389ms
49 silly resolveWithNewModule short-hash@1.0.0 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/@icetee%2fftp 1986ms (from cache)
51 silly pacote version manifest for @icetee/ftp@0.3.11 fetched in 1989ms
52 silly resolveWithNewModule @icetee/ftp@0.3.11 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/xregexp 93ms (from cache)
54 silly pacote version manifest for xregexp@2.0.0 fetched in 95ms
55 silly resolveWithNewModule xregexp@2.0.0 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/readable-stream 96ms (from cache)
57 silly pacote range manifest for readable-stream@1.1.x fetched in 101ms
58 silly resolveWithNewModule readable-stream@1.1.14 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/inherits 66ms (from cache)
60 http fetch GET 304 https://registry.npmjs.org/core-util-is 70ms (from cache)
61 silly pacote range manifest for inherits@~2.0.1 fetched in 69ms
62 silly resolveWithNewModule inherits@2.0.3 checking installable status
63 silly pacote range manifest for core-util-is@~1.0.0 fetched in 73ms
64 silly resolveWithNewModule core-util-is@1.0.2 checking installable status
65 http fetch GET 304 https://registry.npmjs.org/isarray 72ms (from cache)
66 http fetch GET 304 https://registry.npmjs.org/string_decoder 73ms (from cache)
67 silly pacote version manifest for isarray@0.0.1 fetched in 74ms
68 silly resolveWithNewModule isarray@0.0.1 checking installable status
69 silly pacote range manifest for string_decoder@~0.10.x fetched in 75ms
70 silly resolveWithNewModule string_decoder@0.10.31 checking installable status
71 http fetch GET 304 https://registry.npmjs.org/etch 91ms (from cache)
72 silly pacote range manifest for etch@^0.12.6 fetched in 93ms
73 silly resolveWithNewModule etch@0.12.8 checking installable status
74 http fetch GET 304 https://registry.npmjs.org/space-pen 49ms (from cache)
75 silly pacote range manifest for space-pen@^5.1.2 fetched in 50ms
76 silly resolveWithNewModule space-pen@5.1.2 checking installable status
77 http fetch GET 304 https://registry.npmjs.org/jquery 60ms (from cache)
78 silly pacote version manifest for jquery@2.1.4 fetched in 61ms
79 silly resolveWithNewModule jquery@2.1.4 checking installable status
80 http fetch GET 304 https://registry.npmjs.org/grim 70ms (from cache)
81 silly pacote range manifest for grim@^1.0.0 fetched in 72ms
82 silly resolveWithNewModule grim@1.5.0 checking installable status
83 http fetch GET 304 https://registry.npmjs.org/underscore-plus 72ms (from cache)
84 silly pacote range manifest for underscore-plus@1.x fetched in 73ms
85 silly resolveWithNewModule underscore-plus@1.6.8 checking installable status
86 http fetch GET 304 https://registry.npmjs.org/emissary 78ms (from cache)
87 silly pacote range manifest for emissary@^1.2.0 fetched in 80ms
88 silly resolveWithNewModule emissary@1.3.3 checking installable status
89 http fetch GET 304 https://registry.npmjs.org/es6-weak-map 91ms (from cache)
90 http fetch GET 304 https://registry.npmjs.org/property-accessors 92ms (from cache)
91 http fetch GET 304 https://registry.npmjs.org/mixto 94ms (from cache)
92 silly pacote range manifest for es6-weak-map@^0.1.2 fetched in 95ms
93 silly resolveWithNewModule es6-weak-map@0.1.4 checking installable status
94 silly pacote range manifest for property-accessors@^1.1 fetched in 96ms
95 silly resolveWithNewModule property-accessors@1.1.3 checking installable status
96 silly pacote range manifest for mixto@1.x fetched in 98ms
97 silly resolveWithNewModule mixto@1.0.0 checking installable status
98 http fetch GET 304 https://registry.npmjs.org/es6-iterator 67ms (from cache)
99 silly pacote range manifest for es6-iterator@~0.1.3 fetched in 68ms
100 silly resolveWithNewModule es6-iterator@0.1.3 checking installable status
101 http fetch GET 304 https://registry.npmjs.org/d 73ms (from cache)
102 silly pacote range manifest for d@~0.1.1 fetched in 75ms
103 silly resolveWithNewModule d@0.1.1 checking installable status
104 http fetch GET 304 https://registry.npmjs.org/es5-ext 76ms (from cache)
105 http fetch GET 304 https://registry.npmjs.org/es6-symbol 77ms (from cache)
106 silly pacote range manifest for es5-ext@~0.10.6 fetched in 79ms
107 silly resolveWithNewModule es5-ext@0.10.49 checking installable status
108 silly pacote range manifest for es6-symbol@~2.0.1 fetched in 79ms
109 silly resolveWithNewModule es6-symbol@2.0.1 checking installable status
110 silly pacote range manifest for es6-iterator@~2.0.3 fetched in 2ms
111 silly resolveWithNewModule es6-iterator@2.0.3 checking installable status
112 silly pacote range manifest for es6-symbol@~3.1.1 fetched in 3ms
113 silly resolveWithNewModule es6-symbol@3.1.1 checking installable status
114 http fetch GET 304 https://registry.npmjs.org/next-tick 51ms (from cache)
115 silly pacote range manifest for next-tick@^1.0.0 fetched in 53ms
116 silly resolveWithNewModule next-tick@1.0.0 checking installable status
117 silly pacote range manifest for d@1 fetched in 0ms
118 silly resolveWithNewModule d@1.0.0 checking installable status
119 http fetch GET 304 https://registry.npmjs.org/underscore 54ms (from cache)
120 silly pacote range manifest for underscore@~1.8.3 fetched in 55ms
121 silly resolveWithNewModule underscore@1.8.3 checking installable status
122 http fetch GET 304 https://registry.npmjs.org/async 71ms (from cache)
123 silly fetchPackageMetaData error for async@^1.5.2 Unexpected end of JSON input while parsing near '...ist":{"shasum":"aea74'
124 http fetch GET 304 https://registry.npmjs.org/mkdirp 74ms (from cache)
125 http fetch GET 304 https://registry.npmjs.org/rimraf 78ms (from cache)
126 silly pacote range manifest for mkdirp@^0.5.1 fetched in 81ms
127 silly resolveWithNewModule mkdirp@0.5.1 checking installable status
128 silly pacote range manifest for rimraf@^2.5.2 fetched in 83ms
129 silly resolveWithNewModule rimraf@2.6.3 checking installable status
130 timing stage:rollbackFailedOptional Completed in 2ms
131 timing stage:runTopLevelLifecycles Completed in 6487ms
132 silly saveTree apm-install-dir-119226-14020-1mzs3i9.0sepj
132 silly saveTree `-- ftp-remote-edit@0.14.1
132 silly saveTree   +-- @icetee/ftp@0.3.11
132 silly saveTree   | +-- readable-stream@1.1.14
132 silly saveTree   | | +-- core-util-is@1.0.2
132 silly saveTree   | | +-- inherits@2.0.3
132 silly saveTree   | | +-- isarray@0.0.1
132 silly saveTree   | | `-- string_decoder@0.10.31
132 silly saveTree   | `-- xregexp@2.0.0
132 silly saveTree   +-- atom-select-list@0.3.2
132 silly saveTree   | +-- etch@0.12.8
132 silly saveTree   | `-- fuzzaldrin@2.1.0
132 silly saveTree   +-- atom-space-pen-views@2.2.0
132 silly saveTree   | `-- space-pen@5.1.2
132 silly saveTree   |   +-- grim@1.5.0
132 silly saveTree   |   | `-- emissary@1.3.3
132 silly saveTree   |   |   +-- es6-weak-map@0.1.4
132 silly saveTree   |   |   | +-- d@0.1.1
132 silly saveTree   |   |   | | `-- es5-ext@0.10.49
132 silly saveTree   |   |   | |   +-- es6-iterator@2.0.3
132 silly saveTree   |   |   | |   | +-- d@1.0.0
132 silly saveTree   |   |   | |   | `-- es6-symbol@3.1.1
132 silly saveTree   |   |   | |   +-- es6-symbol@3.1.1
132 silly saveTree   |   |   | |   `-- next-tick@1.0.0
132 silly saveTree   |   |   | +-- es5-ext@0.10.49
132 silly saveTree   |   |   | +-- es6-iterator@0.1.3
132 silly saveTree   |   |   | | `-- es6-symbol@2.0.1
132 silly saveTree   |   |   | `-- es6-symbol@2.0.1
132 silly saveTree   |   |   +-- mixto@1.0.0
132 silly saveTree   |   |   +-- property-accessors@1.1.3
132 silly saveTree   |   |   `-- underscore-plus@1.6.8
132 silly saveTree   |   |     `-- underscore@1.8.3
132 silly saveTree   |   +-- jquery@2.1.4
132 silly saveTree   |   `-- underscore-plus@1.6.8
132 silly saveTree   +-- fs-plus@3.1.1
132 silly saveTree   | +-- mkdirp@0.5.1
132 silly saveTree   | `-- rimraf@2.6.3
132 silly saveTree   +-- fuzzaldrin-plus@0.5.0
132 silly saveTree   +-- fuzzaldrin@2.1.0
132 silly saveTree   +-- md5@2.2.1
132 silly saveTree   +-- minimatch@3.0.4
132 silly saveTree   +-- p-queue@3.2.0
132 silly saveTree   +-- progress-stream@2.0.0
132 silly saveTree   +-- short-hash@1.0.0
132 silly saveTree   `-- ssh2@0.8.2
133 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...ist":{"shasum":"aea74'
133 verbose stack     at JSON.parse (<anonymous>)
133 verbose stack     at parseJson (C:\Users\raimu\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
133 verbose stack     at consumeBody.call.then.buffer (C:\Users\raimu\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
133 verbose stack     at <anonymous>
133 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
134 verbose cwd C:\Users\raimu\AppData\Local\Temp\apm-install-dir-119226-14020-1mzs3i9.0sepj
135 verbose Windows_NT 10.0.17763
136 verbose argv "C:\\Users\\raimu\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\raimu\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\raimu\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\raimu\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/ftp-remote-edit/versions/0.14.1/tarball" "--runtime=electron" "--target=2.0.18" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style"
137 verbose node v8.9.3
138 verbose npm  v6.2.0
139 error Unexpected end of JSON input while parsing near '...ist":{"shasum":"aea74'
140 verbose exit [ 1, true ]

```

**Comment by rsese** [comment]
Thanks for reaching out!  Can you fill out the issue template?  The information in the template is super helpful for us when triaging issues.  Can you also mention if you have trouble with any packages or just `ftp-remote-edit`?

Just to note, I was able to install `ftp-remote-edit` with 1.35.1 on Windows 10 just now.

---

We require the template to be filled out on all new issues and pull requests.. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
