### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/t5/kqbyc3g97t1_m743pddp7ydc0000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by Vladislavrakicki** [atom/atom#19064]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/t5/kqbyc3g97t1_m743pddp7ydc0000gn/T/AppTranslocation/D606112A-8C1B-4393-856E-39F765BCB54B/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): no suitable image found.  Did find:
	/private/var/folders/t5/kqbyc3g97t1_m743pddp7ydc0000gn/T/AppTranslocation/D606112A-8C1B-4393-856E-39F765BCB54B/d/Atom.app/Contents: not a file

```
At ELECTRON_ASAR.js:166

Error: dlopen(/private/var/folders/t5/kqbyc3g97t1_m743pddp7ydc0000gn/T/AppTranslocation/D606112A-8C1B-4393-856E-39F765BCB54B/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): no suitable image found.  Did find:
	/private/var/folders/t5/kqbyc3g97t1_m743pddp7ydc0000gn/T/AppTranslocation/D606112A-8C1B-4393-856E-39F765BCB54B/d/Atom.app/Contents: not a file
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/private/var/folders/t5/kqbyc3g97t1_m743pddp7ydc0000gn/T/AppTranslocation/D606112A-8C1B-4393-856E-39F765BCB54B/d/Atom.app/Contents/Resources/app/static/<embedded>:1:664624)
    at get_KeyboardLayoutManager (/private/var/folders/t5/kqbyc3g97t1_m743pddp7ydc0000gn/T/AppTranslocation/D606112A-8C1B-4393-856E-39F765BCB54B/d/Atom.app/Contents/Resources/app/static/<embedded>:14:3064159)
    at get_manager (/private/var/folders/t5/kqbyc3g97t1_m743pddp7ydc0000gn/T/AppTranslocation/D606112A-8C1B-4393-856E-39F765BCB54B/d/Atom.app/Contents/Resources/app/static/<embedded>:14:3064239)
    at Object.getCurrentKeyboardLayout (/private/var/folders/t5/kqbyc3g97t1_m743pddp7ydc0000gn/T/AppTranslocation/D606112A-8C1B-4393-856E-39F765BCB54B/d/Atom.app/Contents/Resources/app/static/<embedded>:14:3064365)
    at e.keystrokeForKeyboardEvent (/private/var/folders/t5/kqbyc3g97t1_m743pddp7ydc0000gn/T/AppTranslocation/D606112A-8C1B-4393-856E-39F765BCB54B/d/Atom.app/Contents/Resources/app/static/<embedded>:14:992467)
    at KeymapManager.t.exports.KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/t5/kqbyc3g97t1_m743pddp7ydc0000gn/T/AppTranslocation/D606112A-8C1B-4393-856E-39F765BCB54B/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1210078)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/t5/kqbyc3g97t1_m743pddp7ydc0000gn/T/AppTranslocation/D606112A-8C1B-4393-856E-39F765BCB54B/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1208063)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/t5/kqbyc3g97t1_m743pddp7ydc0000gn/T/AppTranslocation/D606112A-8C1B-4393-856E-39F765BCB54B/d/Atom.app/Contents/Resources/app/static/<embedded>:11:285196)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?
* If you quit and reinstall Atom, does that clear things up for you?

x-ref: https://github.com/atom/atom/issues/15861
