### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.utam...

### ISSUE THREAD

**Issue by kezyandrew** [atom/atom#19087]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Kali GNU/Linux
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.utamu.ac.ug proxy.utamu.ac.ug:3128

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.utamu.ac.ug proxy.utamu.ac.ug:3128
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report - the ENOTFOUND error seems like a networking/DNS issue rather than an issue with Atom?  We'll go ahead and close but suggest double checking your proxy settings?
