### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=write EPIPE

### ISSUE THREAD

**Issue by kmcdk** [atom/atom#19086]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=write EPIPE

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, cause=write EPIPE
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at onwriteError (_stream_writable.js:408:12)
    at onwrite (_stream_writable.js:430:5)
    at _destroy (internal/streams/destroy.js:39:7)
    at Socket._destroy (net.js:561:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite (net.js:869:10)
```

### Commands

```
  2x -0:27.6.0 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-material-contrast-syntax 0.3.1 
atom-terminal 0.8.0 
autocomplete-paths 2.12.2 
busy-signal 2.0.1 
emmet 2.4.3 
expose 0.15.0 
git-plus 8.6.2 
intentions 1.1.5 
linter 2.3.0 
linter-ui-default 1.7.1 
open-recent 5.0.0 
pane-layout-plus 0.7.4 
pigments 0.40.2 
prettier-atom 0.56.4 
python-indent 1.1.7 
```

**Comment by rsese** [comment]
Thanks for the report - can you confirm if you're using a proxy and what steps cause the error?
