### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Marekdg** [atom/atom#19108]
[Enter steps to reproduce:]

1. ... scrolling in a php file.
2. ... When it hits a specific point the message of the bug appears

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1104184)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1099890)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:89305)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:79324)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:69977)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:67605)
    at TextEditorComponent.didMouseWheel (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:92354)
```

### Commands

```
     -1:42.7.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
busy-signal 2.0.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
less-than-slash 0.19.0 
linter 2.3.0 
linter-eslint 8.5.2 
linter-ui-default 1.7.1 
open-in-browser 0.5.2 
pigments 0.40.2 
prettier-atom 0.56.4 
status-bar-blame 2.0.3 
```

**Comment by rsese** [comment]
Thanks for the report!  We've had a number of reports of this error but no specific steps to reproduce or more specifically, steps to reproduce that work anywhere x-ref: https://github.com/atom/atom/issues/16892.

Can you reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?  Also, can you reproduce after restarting Atom?

**Comment by Marekdg** [comment]
So what worked for me: closing the file that the error occurred in, after that I opened de file again. (Without restarting atom)
I haven’t had any errors after that

**Comment by TraceyC77** [comment]
I specifically saw this error repeatedly while scrolling down in a perl file that had a merge conflict. The conflict was at the bottom of the viewable area of the editor. After resolving the conflict, whenever I scrolled down in this file this error still appeared over and over.

The issue happened with Atom version 1.28.0 x64. 
After updating Atom to 1.30.6 I can no longer reproduce the problem.

Original error:
```
/usr/share/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:328

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/usr/share/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:328:31)
    at ScreenLineBuilder.buildScreenLines (/usr/share/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:140:22)
    at DisplayLayer.getScreenLines (/usr/share/atom/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/usr/share/atom/resources/app/src/text-editor-component.js:881:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/share/atom/resources/app/src/text-editor-component.js:385:16)
    at TextEditorComponent.updateSync (/usr/share/atom/resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didMouseWheel (/usr/share/atom/resources/app/src/text-editor-component.js:1560:59)
```

Original versions of Atom and related components:
These had been installed via the default Ubuntu repos. I added the Atom repo and ran apt update && apt upgrade to get the latest stable versions.

```
Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.0
python 2.7.15rc1
git 2.17.1
```

Updated versions:

```
Atom    : 1.36.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.0
python 2.7.15rc1
git 2.17.1
```

**Comment by jm3** [comment]
Hit this error today when opening a folder to add it to a new project.

**Comment by roskelld** [comment]
Upon opening my project today I got this error. 

Project including ~6 files were opened previously, so opening Atom automatically reopened these files. The error popped up right away. I tried opening another existing project in a new window and did not get the error. I then closed and reopened Atom a few times with the same original project and again the error appeared. 
Finally I closed all the files such that it was just the main project window open. Closed Atom and reopened. No error. Reopened the code files, and the error has not returned. 

Could this be related to some sort of caching error that's not cleared until the files have been closed? One thing of note is that some of my project files were updated outside of this instance of Atom as i'd been working on another PC, so pulled latest before opening my session.

**Comment by JackSzwergold** [comment]
Hit this today as well. I am on macOS 10.14.5 (18F132) and using Atom 1.38.2. Never seen this before and have been working daily on this setup.

The only thing I can describe is I was working on a PHP class this past Friday from home. It’s all self-contained in its own file under `lib/myCoolPHPClass.class.php`. I also updated some deployment code (Capistrano) in other branches as well and merged into my development branch.

At work this morning (Monday) I went into my project directory and did some `git pull`’s on the three humble branches of my project to get updated files locally: `master`, `js_develop` and `acceptance`. The code is all good and loads fine.

Then I launched Atom and it tried to load `lib/myCoolPHPClass.class.php` and that is when I got the same `At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14` as others describe.

The only other thing I can note is I made some comment changes before I left the office on Friday, but didn’t commit them. When I got home and noticed those changes were not committed, I committed them and pushed them to origin. Local code was not updated until I did those `git pull`’s.

So this might be a cached content issue? When I closed Atom and restarted again via `atom .` in my project I was able to get up and running again.

**Comment by SupraLP** [comment]
i have gotten this error too while editing a html file.
I was just scrolling through it and a thousand of theese errors appeared.

I'm using version 1.39.1 on windows without any plugins whatsoever.

reopening the file fixes the issue temporarily, but it will reappear eventually from my experience.

**Comment by Sai-Tumuluri** [comment]
Got the error while scrolling through large py file with GitHub integration
===============================================

C:\Users\stumuluri\AppData\Local\atom\app-1.39.1\resources\app\static\<embedded>:14
Hide Stack Trace
TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (C:\Users\stumuluri\AppData\Local\atom\app-1.39.1\resources\app\static\<embedded>:14:1198159)
    at ScreenLineBuilder.buildScreenLines (C:\Users\stumuluri\AppData\Local\atom\app-1.39.1\resources\app\static\<embedded>:14:1193829)
    at DisplayLayer.getScreenLines (C:\Users\stumuluri\AppData\Local\atom\app-1.39.1\resources\app\static\<embedded>:14:94192)
    at TextEditorComponent.queryScreenLinesToRender (C:\Users\stumuluri\AppData\Local\atom\app-1.39.1\resources\app\static\<embedded>:11:79712)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (C:\Users\stumuluri\AppData\Local\atom\app-1.39.1\resources\app\static\<embedded>:11:70365)
    at TextEditorComponent.updateSync (C:\Users\stumuluri\AppData\Local\atom\app-1.39.1\resources\app\static\<embedded>:11:67993)
    at TextEditorComponent.didMouseWheel (C:\Users\stumuluri\AppData\Local\atom\app-1.39.1\resources\app\static\<embedded>:11:92801)

**Comment by rsese** [comment]
@SupraLP @Sai-Tumuluri - is the error consistently reproducible for you with a specific file?  If so, do the files happen to be public so we can use them to try and reproduce?

**Comment by wjuniorw** [comment]
i open the project with ``` atom . --safe ```, the same error ocurred, but when i close end open again with 
``` atom . ```
everything works

**Comment by MarkDVerhagen** [comment]
Same issue at: 
**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at SuggestionListElement.getDisplayFragment (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1489474)
    at SuggestionListElement.renderItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1488744)
    at ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:325843)
```

### Commands

```
     -1:20.2.0 hydrogen:run-and-move-down (input.hidden-input)
     -1:20.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:00.2.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
  4x -0:59.2.0 core:backspace (input.hidden-input)
     -0:42.4.0 core:move-right (input.hidden-input)
  3x -0:38.5.0 core:backspace (input.hidden-input)
     -0:36.8.0 core:move-right (input.hidden-input)
     -0:36.6.0 core:move-up (input.hidden-input)
     -0:36.4.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:36.1.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:36.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:23.3.0 intentions:highlight (input.hidden-input)
     -0:23.3.0 editor:move-to-beginning-of-word (input.hidden-input)
     -0:22.8.0 editor:select-to-end-of-word (input.hidden-input)
  2x -0:14.4.0 core:backspace (input.hidden-input)
     -0:13.2.0 autocomplete-plus:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-language-r 1.4.8 
atom-latex 0.8.11 
autocomplete-latex 0.9.2 
autocomplete-paths 2.12.2 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
file-icons 2.1.37 
highlight-selected 0.16.0 
Hydrogen 2.13.1 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.8 
ide-python 1.5.0 
ide-r 0.1.8 
indent-guide-improved 1.4.13 
intentions 1.1.5 
kite 0.178.0 
language-latex 1.2.0 
language-r 0.4.2 
latex 0.50.2 
latex-autocomplete 1.1.1 
latex-tree 0.5.0 
latex-wordcount 0.6.0 
linter 2.3.1 
linter-chktex 1.4.0 
linter-flake8 2.4.0 
linter-lintr 1.2.0 
linter-pylint 2.1.1 
linter-ui-default 1.8.1 
markdown-preview-enhanced 0.17.3 
minimap 4.29.9 
pdf-view 0.72.0 
platformio-ide-terminal 2.10.0 
python-indent 1.2.5 
python-tools 0.6.9 
typewriter 0.8.0 
```

Perhaps importantly: only happens to me when opening .r files, have never encountered this problem with .py or .md (which are the other filetypes I frequently use)

**Comment by dariushhacker** [comment]
> 
> 
> [Enter steps to reproduce:]
> 
>     1. ... scrolling in a php file.
> 
>     2. ... When it hits a specific point the message of the bug appears
> 
> 
> **Atom**: 1.35.1 x64
> **Electron**: 2.0.18
> **OS**: Mac OS X 10.14.4
> **Thrown From**: Atom Core
> ### Stack Trace
> 
> Uncaught TypeError: Cannot read property 'length' of undefined
> 
> ```
> At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14
> 
> TypeError: Cannot read property 'length' of undefined
>     at ScreenLineBuilder.emitText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1104184)
>     at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1099890)
>     at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:89305)
>     at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:79324)
>     at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:69977)
>     at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:67605)
>     at TextEditorComponent.didMouseWheel (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:92354)
> ```
> 
> ### Commands
> 
> ```
>      -1:42.7.0 intentions:highlight (input.hidden-input)
> ```
> 
> ### Non-Core Packages
> 
> ```
> autoclose-html 0.23.0 
> busy-signal 2.0.1 
> indent-guide-improved 1.4.13 
> intentions 1.1.5 
> less-than-slash 0.19.0 
> linter 2.3.0 
> linter-eslint 8.5.2 
> linter-ui-default 1.7.1 
> open-in-browser 0.5.2 
> pigments 0.40.2 
> prettier-atom 0.56.4 
> status-bar-blame 2.0.3 
> ```

https://github.com/Airrocket/TildAI-DiscordBot.git

**Comment by givemethevin** [comment]
I get this same error just by opening up a project that has files open. It is only one project. I can open up other without issues. However, the project wit the error is locked and nothing is clickable, so I can't even close those files.

Mac OS 10.5
ATOM 1.45

Does anyone know how I can close these files? Or dump the project and start over? I literally can not work on this project right now.
