### ISSUE TITLE
Uncaught AssertionError [ERR_ASSERTION]: 9015 == 0

### ISSUE THREAD

**Issue by tocka9** [atom/atom#19115]
[Enter steps to reproduce:]

1. I was installing packages while running Astrill VPN in "Open Web" mode

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught AssertionError [ERR_ASSERTION]: 9015 == 0

```
At assert.js:42

AssertionError [ERR_ASSERTION]: 9015 == 0
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:160:14)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at Socket.socketOnData (_http_client.js:472:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
  2x -7:03.5.0 core:select-all (input.hidden-input)
     -1:54.2.0 core:confirm (input.hidden-input)
  2x -1:46.2.0 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
pigments 0.40.2 
```

**Comment by rsese** [comment]
Thanks for the report!  Just to clarify:

> I was installing packages while running Astrill VPN in "Open Web" mode

Can you consistently reproduce when using that VPN?  And you don't see the same error otherwise?
