### ISSUE TITLE
Failed to activate the navigation-history package

### ISSUE THREAD

**Issue by kindlychung** [atom/atom#19125]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.10
**Thrown From**: 'navigation-history' package vundefined

### Stack Trace

Failed to activate the navigation-history package

```
At editor is not defined

ReferenceError: editor is not defined
    at /packages/navigation-history/lib/cursor-watcher.coffee:4:5)
    at /packages/navigation-history/lib/main.coffee:22:23
    at Workspace.observeTextEditors (/usr/share/atom/resources/app/static/<embedded>:11:428089)
    at Object.activate (/packages/navigation-history/lib/main.coffee:21:20)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:2921510)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:2920922)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:2918553)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:2920782)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:2920725)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:382681)
    at /usr/share/atom/resources/app/static/<embedded>:11:916963
    at r (/usr/share/atom/resources/app/static/<embedded>:11:911569)
    at o (/usr/share/atom/resources/app/static/<embedded>:14:1038607)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1038761)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1037363)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -8:39.1.0 application:open-file (input.hidden-input)
     -8:34.5.0 settings-view:open (input.hidden-input)
     -8:33.3.0 core:cancel (div.panels-item)
  2x -4:19.5.0 julia-client:copy-or-interrupt (textarea.xterm-helper-textarea)
     -1:51.6.0 find-and-replace:toggle (input.hidden-input)
     -1:49.3.0 core:confirm (input.hidden-input)
     -1:48.3.0 editor:consolidate-selections (input.hidden-input)
     -1:48.3.0 core:cancel (input.hidden-input)
     -1:47.8.0 vim-mode-plus:search (input.hidden-input)
     -1:46.5.0 core:confirm (input.hidden-input)
  2x -1:44.9.0 vim-mode-plus:repeat-search (input.hidden-input)
     -1:41.8.0 vim-mode-plus:repeat-search-reverse (input.hidden-input)
  7x -1:40 vim-mode-plus:repeat-search (input.hidden-input)
     -1:33.7.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -1:23.8.0 command-palette:toggle (input.hidden-input)
     -1:20.5.0 settings-view:install-packages-and-themes (input.hidden-input)
```

### Non-Core Packages

```
back-jumpy 0.2.0 
indent-detective 0.3.2 
ink 0.10.3 
julia-client 0.8.2 
jumpy 5.0.2 
jumpy-beacon 0.2.0 
language-julia 0.18.0 
latex-completions 0.3.6 
navigate 0.1.20 
tool-bar 1.1.11 
uber-juno 0.2.0 
vim-mode-plus 1.36.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the https://atom.io/packages/navigation-history package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by rsese** [comment]
FYI I took a quick peek at the [package repository page](https://github.com/Tyriar/atom-navigation-history) and it looks like it's no longer maintained.
