### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.36.1\res...

### ISSUE THREAD

**Issue by CaptanHamm** [atom/atom#19217]
[Enter steps to reproduce:]

1. open atom
2. start typing.

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\user\AppData\Local\atom\app-1.36.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:166

Error: The specified module could not be found.
\\?\C:\Users\user\AppData\Local\atom\app-1.36.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:1:674931)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:3159422)
    at get_manager (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:3159502)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:3159628)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:991806)
    at KeymapManager.t.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:1209888)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:1207873)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:285300)
```

### Commands

```
```

### Non-Core Packages

```
git-plus 8.6.2 
```

**Comment by CaptanHamm** [comment]
it seems to affect backspace and delete keys primarily
I can highlight text and type to replace, the error still comes up, but the edit happens. 
but when i press backspace, or delete, the error comes up, but no change in the text that i had highlighted.

**Comment by CaptanHamm** [comment]
Return key also does nothing

**Comment by CaptanHamm** [comment]
arrow keys also do not do anything.

**Comment by CaptanHamm** [comment]
launched atom --safe, and recovered saved state, resolved issue.

**Comment by christronyxyocum** [comment]
Experiencing the same issue and using --safe did nothing for me.

**Comment by evinjaff** [comment]
Experienced the same issue as well. Relaunched using --safe and issue resolved itself.
