### ISSUE TITLE
Flaky build: AppVeyor builds frequently fail due to network error

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#19253]
Many of our flaky build results on AppVeyor are due to failed network requests when setting up the build (e.g., downloading dependencies) or uploading artifacts. (I've included a handful of recent examples below.) Rebuilding usually resolves the errors.

## Early thoughts

A few early thoughts regarding these errors:
- When these network errors occur, it would be nice if we could retry the network request (possibly multiple times) before terminating the build.
- Since these problems aren't representative of an issue with Atom (e.g., a failing test identifying a regression), it seems like these problems should produce an `error` result, not a `failure` result.
- I wonder if something about AppVeyor's network setup is more fragile than the network setup on Travis CI and Azure DevOps. We don't see nearly as many builds fail due to network issues on those other providers. 🤔
- Since we're only a few steps away from migrating off of AppVeyor entirely, it might make more sense to complete that migration instead of trying to make the AppVeyor builds more resilient to network errors.

## Examples

https://ci.appveyor.com/project/Atom/atom/builds/24174630/job/dq34sos89h84f7b1#L56

```
Installing node  (x86)...
npm install --global npm@6.2.0
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/npm failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
```

---

https://ci.appveyor.com/project/Atom/atom/builds/23872521/job/1cu4d1jt9d3kye4k#L85

```
Uploading artifacts...
Error uploading artifact the storage: The remote name could not be resolved: 'appveyorcidatav2.blob.core.windows.net'
```

---

https://ci.appveyor.com/project/Atom/atom/builds/24130603/job/8514xejym64eench#L40
https://ci.appveyor.com/project/Atom/atom/builds/23620160/job/sqn2bmw3tqg1m20d#L37

```
gyp http GET https://atom.io/download/electron/v2.0.18/iojs-v2.0.18.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (C:\projects\atom\apm\node_modules\atom-package-manager\node_modules\node-gyp\lib\install.js:193:21)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestError (C:\projects\atom\apm\node_modules\atom-package-manager\node_modules\request\request.js:881:8)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at TLSSocket.emit (events.js:211:7)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:64:8)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\projects\\atom\\apm\\node_modules\\atom-package-manager\\bin\\node.exe" "C:\\projects\\atom\\apm\\node_modules\\atom-package-manager\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=2.0.18" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
```

---

https://ci.appveyor.com/project/Atom/atom/builds/24134686/job/p1jtk3y0b6wkf8cu#L33

```
gyp ERR! stack Error: connect ETIMEDOUT 104.20.23.46:443
gyp ERR! stack     at Object._errnoException (util.js:1024:11)
gyp ERR! stack     at _exceptionWithHostPort (util.js:1046:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\appveyor\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\atom\script\node_modules\minidump
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the minidump@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by rafeca** [comment]
Another one: https://ci.appveyor.com/project/Atom/atom/builds/24306890/job/p7oxor2fmuilmg8p

```
Build started
git clone -q --depth=10 --branch=master https://github.com/atom/atom.git c:\projects\atom
fatal: unable to access 'https://github.com/atom/atom.git/': Could not resolve host: github.com
Command exited with code 128
```
