### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by 6skov** [atom/atom#19304]
[Enter steps to reproduce:]

First time running atom

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At C:\Users\olivi\AppData\Local\atom\app-1.36.1\resources\app\static\<embedded>:14

TypeError: Cannot read property 'version' of undefined
    at ~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:3013654
    at ~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:896755
    at r (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:893761)
    at o (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:1032937)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:1033143)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
  6x -0:49.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Do you see this error every time you start Atom or just the first time you started Atom after installing it?

**Comment by siklosipeter** [comment]
Encountered the same error. 
* not first time user
* happens multiple time
* might be unrelated but can't install new packages from the GUI
* apm install from CMD does not work
* apm install from Git BASH works

[Enter steps to reproduce:]

1. Tried to install Linter / MarkDown related packages
2. Went to Settings \ Install packages
3. Featured list not appearing: ```
Fetching featured packages failed.Hide output…
Unexpected end of JSON input:
``` 
4. Searching for markdown
5. Search result appears
6. Error message on the right appears


**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At C:\Users\USERNAME\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:14

TypeError: Cannot read property 'version' of undefined
    at ~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:14:3054872
    at ~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:898816
    at r (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:895887)
    at n (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:14:1043822)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:14:1044028)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -8:46.4.0 core:confirm (input.hidden-input)
     -8:33.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
  2x -8:23.1.0 core:confirm (input.hidden-input)
     -4:30.7.0 editor:select-to-first-character-of-line (input.hidden-input)
     -4:29.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
auto-indent 0.5.0 
clipboard-plus 0.5.1 
find-scroll-marker 0.1.3 
ftp-remote-edit 0.16.0 
git-plus 8.6.2 
git-time-machine 2.1.0 
highlight-column 0.5.4 
highlight-selected 0.16.0 
indent-guide-improved 1.4.13 
language-twiki 0.4.0 
lint-scroll-marker 0.3.0 
linter 2.3.0 
linter-markdown 5.2.7 
markdown-pdf 2.2.0 
markdown-writer 2.11.5 
remote-sync 4.1.8 
scroll-marker 0.3.2 
split-diff 1.6.0 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by Yingzhong262526** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 16.04.5
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At /opt/atom/resources/app/node_modules/settings-view/lib/package-card.js:248

TypeError: Cannot read property 'version' of undefined
    at /opt/atom/resources/app/node_modules/settings-view/lib/package-card.js:248:40
    at /opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:333:24
    at exit (/opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/opt/atom/resources/app/src/buffered-process.js:267:15)
    at bufferStream (/opt/atom/resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (/opt/atom/resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

### Commands

```
```

### Non-Core Packages

```

```
