### ISSUE TITLE
mac build error during snapshot generation (Cannot replace with lazy function...)

### ISSUE THREAD

**Issue by bosspan** [atom/atom#19328]
### Description
Get an error when building in mac.
```
Packaging app for platform darwin x64 using electron v2.0.18
Setting Atom Helper Version for /Users/github/atom/out/Atom Dev.app/Contents/Frameworks/Atom Helper.app/Contents/Info.plist
Copying non-ASAR resources to /Users/github/atom/out/Atom Dev.app/Contents/Resources
Writing LICENSE.md to /Users/github/atom/out/Atom Dev.app/Contents/Resources
Application bundle created at /Users/github/atom/out/Atom Dev.app
Generating snapshot script at "/Users/github/atom/out/startup.js" (2673)Unable to transform source code for module /Users/github/atom/out/app/node_modules/parse5/lib/parser/parser_stream.js.
Error: /Users/github/atom/out/app/node_modules/parse5/lib/parser/parser_stream.js
Cannot replace with lazy function because the supplied node does not belong to an assignment expression or a variable declaration!
  at FileRequireTransform.replaceAssignmentOrDeclarationWithLazyFunction (/Users/github/atom/script/node_modules/electron-link/lib/file-require-transform.js:189:11)
  at Context.visitIdentifier (/Users/github/atom/script/node_modules/electron-link/lib/file-require-transform.js:81:18)
  at Context.invokeVisitorMethod (/Users/github/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:284:51)
  at Visitor.PVp.visitWithoutReset (/Users/github/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:159:32)
  at visitChildren (/Users/github/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:205:25)
  at Visitor.PVp.visitWithoutReset (/Users/github/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:168:20)
  at visitChildren (/Users/github/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:205:25)
  at Visitor.PVp.visitWithoutReset (/Users/github/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:168:20)
  at NodePath.each (/Users/github/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path.js:89:26)
  at visitChildren (/Users/github/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:180:18)
  at Visitor.PVp.visitWithoutReset (/Users/github/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:168:20)
  at visitChildren (/Users/github/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:205:25)
  at Visitor.PVp.visitWithoutReset (/Users/github/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:168:20)
  at visitChildren (/Users/github/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:205:25)
  at Visitor.PVp.visitWithoutReset (/Users/github/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:168:20)
  at Visitor.PVp.visit (/Users/github/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:106:29)
  at Object.visit (/Users/github/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:82:55)
  at FileRequireTransform.replaceDeferredRequiresWithLazyFunctions (/Users/github/atom/script/node_modules/electron-link/lib/file-require-transform.js:77:20)
  at FileRequireTransform.apply (/Users/github/atom/script/node_modules/electron-link/lib/file-require-transform.js:34:10)
  at /Users/github/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:55:56
  at Generator.next (<anonymous>:null:null)
  at step (/Users/github/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:191)
  at /Users/github/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:361
```

### Steps to Reproduce

1. git clone 
2. node ./script/build

**Expected behavior:**
build success

**Actual behavior:**
throw an error

**Reproduces how often:** 
always

### Versions

```
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.1
python 2.7.16
git 2.15.2
```

**Comment by rsese** [comment]
What commit are you on?  I have a clone of atom/atom at da8b1a1a4 and the build ran ok for me with `./script/build` on macOS 10.12.6 with Node v8.1.4.
