### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.anan...

### ISSUE THREAD

**Issue by Alminium-Fairy** [atom/atom#19332]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.anan-nct.ac.jp proxy.anan-nct.ac.jp:8080

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.anan-nct.ac.jp proxy.anan-nct.ac.jp:8080
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-java 1.2.7 
color-picker 2.3.0 
file-icons 2.1.32 
highlight-line 0.12.0 
highlight-selected 0.16.0 
html-tab 1.0.2 
japanese-menu 1.14.0 
language-tex 0.4.0 
platformio-ide-terminal 2.9.1 
tag 0.5.0 
```

**Comment by rsese** [comment]
Thanks for the report - the ENOTFOUND error seems like a networking/DNS issue rather than an issue with Atom? We'll go ahead and close but suggest double checking your proxy settings?
