### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by alrahimi** [atom/atom#19351]
[Enter steps to reproduce:]

*Edit by @rsese to add Winston's repro steps and links to his notes*

1. Create a new file and paste:

```txt
\begin{enumerate}
\end{enumerate}
```

2. Select all
3. `Autoflow: Reflow Selection`

Also see notes in https://github.com/atom/atom/issues/19351#issuecomment-494016195 and https://github.com/atom/atom/issues/19351#issuecomment-494017797.

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At C:\Users\alrah\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'match' of undefined
    at Object.reflow (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:163671)
    at Object.reflowSelection (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:163090)
    at HTMLElement.commandDisposable.atom.commands.add.autoflow:reflow-selection (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:162704)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:349922)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:348397)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:1:718183)
    at EventEmitter.t (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:1:726106)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
  2x -1:00.3.0 core:select-to-bottom (input.hidden-input)
     -0:35.1.0 core:select-all (input.hidden-input)
     -0:20.1.0 autoflow:reflow-selection (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

**Comment by 50Wliu** [comment]
One of the `match`s [in this method](https://github.com/atom/atom/blob/dc39210cc2c8e2453f756263257fb57f039838cd/packages/autoflow/lib/autoflow.coffee#L30) are operating on something that should exist, but doesn't.

It can't be the first two on L35 or L41 as then the `replace` on L33 would be throwing instead...

The `split` on L54 should return _at least_ an empty array, which rules out the matches on L63/64.
That would leave https://github.com/atom/atom/blob/dc39210cc2c8e2453f756263257fb57f039838cd/packages/autoflow/lib/autoflow.coffee#L74 as the most likely culprit, especially as I see some shifts and pops of `blockLines` on the lines above. It's possible that the two while loops got out of sync? Anyway, if that is the line, then it looks like it has something to do with LaTeX files.

**Comment by 50Wliu** [comment]
Yeah, got it. Here's a very simple repro case:
```latex
\begin{enumerate}
\end{enumerate}
```
Select all, then try to reflow. One shift for the begin tag and one shift for the end tag = an empty array, so `blockLines[0]` would be undefined.

**Comment by rsese** [comment]
✨ @50Wliu - reproduced with 1.39.0-nightly8 on macOS 10.12.6.  Updated the issue body ✏️
