### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.37.0\res...

### ISSUE THREAD

**Issue by jutamaneeang** [atom/atom#19399]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 ia32
**Electron**: 2.0.18
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\Admin\AppData\Local\atom\app-1.37.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:166

Error: The specified module could not be found.
\\?\C:\Users\Admin\AppData\Local\atom\app-1.37.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:1:688410)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:14:3200640)
    at get_manager (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:14:3200720)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:14:3200846)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:14:1002691)
    at KeymapManager.t.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:1212014)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:1209999)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:285128)
```

### Commands

```
  2x -8:11.9.0 core:delete (span.syntax--source.syntax--php)
     -8:05.6.0 core:save (input.hidden-input)
     -6:26.3.0 core:paste (div.highlights)
     -6:20.2.0 core:cut (span.syntax--text.syntax--html.syntax--php)
     -6:10.7.0 core:paste (span.syntax--variable.syntax--other.syntax--php)
     -6:06.0 core:save (input.hidden-input)
     -2:47.1.0 core:cut (span.syntax--constant.syntax--other.syntax--php)
  7x -2:40.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
https://github.com/atom/atom/issues/19398
