### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/usr/share/atom'

### ISSUE THREAD

**Issue by winter-code** [atom/atom#19390]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Ubuntu 19.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/usr/share/atom'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/usr/share/atom'
    at realpathSync (fs.js:1661:15)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:346:24)
    at toRealPath (module.js:163:13)
    at Function.Module._findPath (module.js:212:22)
    at Module._resolveFilename (module.js:541:25)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:154765)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (internal/module.js:11:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:686403)
    at get_KeyboardLayoutManager (/usr/share/atom/resources/app/static/<embedded>:14:3213747)
    at get_manager (/usr/share/atom/resources/app/static/<embedded>:14:3213827)
    at Object.getCurrentKeyboardLayout (/usr/share/atom/resources/app/static/<embedded>:14:3213953)
    at e.keystrokeForKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:14:1007868)
    at KeymapManager.t.exports.KeymapManager.keystrokeForKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1229829)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1227814)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:285166)
```

### Commands

```
     -1:08.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Seems like an issue with the install if `/usr/share/atom` doesn't exist?  Can you confirm how you installed Atom?  And have you already tried installing again?
