### ISSUE TITLE
Uncaught AssertionError [ERR_ASSERTION]: 6122 == 0

### ISSUE THREAD

**Issue by Abdul007Malik** [atom/atom#19407]
[Enter steps to reproduce:]

1. Click on package update icon
2. Settings section opened and also this error comes up.

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught AssertionError [ERR_ASSERTION]: 6122 == 0

```
At assert.js:42

AssertionError [ERR_ASSERTION]: 6122 == 0
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:160:14)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at Socket.socketOnData (_http_client.js:472:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -1:01.0 intentions:highlight (input.hidden-input)
     -1:00.9.0 core:close (input.hidden-input)
  2x -0:58.3.0 intentions:highlight (input.hidden-input)
     -0:57.6.0 core:close (input.hidden-input)
     -0:57.2.0 intentions:highlight (input.hidden-input)
     -0:57.1.0 core:close (input.hidden-input)
     -0:39.2.0 tree-view:remove-project-folder (div.header.list-item.project-root-header)
     -0:34.8.0 application:reopen-project (atom-pane.pane)
     -0:25.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
intentions 1.1.5 
linter 2.3.0 
linter-ui-default 1.7.1 
prettier-atom 0.56.4 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible in safe mode (`atom --safe`)?  Also, are you connecting to the internet through a proxy?
