### ISSUE TITLE
Git push fails with pre-push Husky hook

### ISSUE THREAD

**Issue by uyouthe** [atom/atom#19410]
### Description

Git Push hook works flawlessly when I just type `git push` in console but fails with no useful output when I try to push via Atom.

I'm using Husky and gh-pages. Here's [my package.json](https://github.com/uyouthe/noo/blob/master/package.json).

Here's the Atom output:
```
19:18:31.406189 git.c:418               trace: built-in: git push origin master
19:18:31.408457 run-command.c:643       trace: run_command: unset GIT_CONFIG_PARAMETERS GIT_PREFIX; ssh git@github.com 'git-receive-pack '\''uyouthe/noo.git'\'''
19:18:33.229843 run-command.c:643       trace: run_command: .git/hooks/pre-push origin git@github.com:uyouthe/noo.git
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! noo@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the noo@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/uyouthe/.npm/_logs/2019-05-27T16_18_40_098Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! noo@0.1.0 predeploy: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the noo@0.1.0 predeploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/uyouthe/.npm/_logs/2019-05-27T16_18_40_125Z-debug.log
error: failed to push some refs to 'git@github.com:uyouthe/noo.git'
```

Here's the log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'deploy' ]
2 info using npm@6.7.0
3 info using node@v11.1.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle noo@0.1.0~predeploy: noo@0.1.0
6 verbose lifecycle noo@0.1.0~predeploy: unsafe-perm in lifecycle true
7 verbose lifecycle noo@0.1.0~predeploy: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/uyouthe/repos/noo/node_modules/.bin:/Users/uyouthe/repos/noo/node_modules/.bin:/Users/uyouthe/repos/node_modules/.bin:/Users/uyouthe/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/bin:/Applications/Atom Beta.app/Contents/Resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core:/Users/uyouthe/.npm-global/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/010 Editor.app/Contents/CmdLine:/Library/Developer/CommandLineTools/usr/libexec/git-core
8 verbose lifecycle noo@0.1.0~predeploy: CWD: /Users/uyouthe/repos/noo
9 silly lifecycle noo@0.1.0~predeploy: Args: [ '-c', 'npm run build' ]
10 silly lifecycle noo@0.1.0~predeploy: Returned: code: 1  signal: null
11 info lifecycle noo@0.1.0~predeploy: Failed to exec predeploy script
12 verbose stack Error: noo@0.1.0 predeploy: `npm run build`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
12 verbose stack     at EventEmitter.emit (events.js:182:13)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:970:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)
13 verbose pkgid noo@0.1.0
14 verbose cwd /Users/uyouthe/repos/noo
15 verbose Darwin 18.6.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
17 verbose node v11.1.0
18 verbose npm  v6.7.0
19 error code ELIFECYCLE
20 error errno 1
21 error noo@0.1.0 predeploy: `npm run build`
21 error Exit status 1
22 error Failed at the noo@0.1.0 predeploy script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]
```

### Steps to Reproduce

1. Create a repository with `package.json` in it.
2. Install Husky and define a pre-push hook. Make sure it works via console.
3. Try pushing via Atom.

**Expected behavior:** I want it to build and deploy seamlessly.

**Actual behavior:** It fails via atom while working just fine via console.

**Reproduces how often:** Every time I try to push.

### Versions

I'm using Atom 1.36.0-beta1 on macOS 10.14.5.

**Comment by Arcanemagus** [comment]
This doesn't appear to have anything to do with Atom _or_ Husky, it looks like your `npm run build` step is failing:
```
npm ERR! noo@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
```

Make sure that that is working correctly in the Atom environment, my _guess_ is that `react-scripts` is making an assumption about the environment that holds true in your CLI environment, but isn't true inside Atom.

If you exit Atom entirely and launch it from the CLI environment with `atom .` does your hook work?
