### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Desktop\protecosssss'

### ISSUE THREAD

**Issue by Mickymi1** [atom/atom#19434]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\TOSHIBA\Desktop\protecosssss'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'C:\Users\TOSHIBA\Desktop\protecosssss'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at atom.project.getPaths.map.e (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:791546)
    at Array.map (<anonymous>)
    at Object.startTask (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:791537)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:188199)
    at get_process.nextTick (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:186163)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-live-server 2.3.0 
emmet 2.4.3 
file-icons 2.1.33 
highlight-selected 0.16.0 
ide-css 0.3.2 
ide-html 0.5.0 
ide-php 0.7.18 
ide-typescript 0.9.1 
minimap 4.29.9 
platformio-ide-terminal 2.9.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?
