### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat '/\afndc1.afnsolutions.local\users$\'

### ISSUE THREAD

**Issue by serialk111er** [atom/atom#19433]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat '\\afndc1.afnsolutions.local\users$\'

```
At fs.js:1621

Error: EPERM: operation not permitted, lstat '\\afndc1.afnsolutions.local\users$\'
    at Proxy.realpathSync (fs.js:1621:13)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at atom.project.getPaths.map.e (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:791546)
    at Array.map (<anonymous>)
    at Object.startTask (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:791537)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:188199)
    at get_process.nextTick (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:186163)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.14.0 
kite 0.164.0 
script 3.18.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?
