### ISSUE TITLE
Uncaught Error: The module '/usr/share/atom/resources/app.asar.unpacked/node_modules/keyboard-lay...

### ISSUE THREAD

**Issue by MinasY** [atom/atom#19472]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Linux Mint
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The module '/usr/share/atom/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 49. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

```
At ELECTRON_ASAR.js:166

Error: The module '/usr/share/atom/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 49. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:686403)
    at get_KeyboardLayoutManager (/usr/share/atom/resources/app/static/<embedded>:14:3213747)
    at get_manager (/usr/share/atom/resources/app/static/<embedded>:14:3213827)
    at Object.getCurrentKeyboardLayout (/usr/share/atom/resources/app/static/<embedded>:14:3213953)
    at e.keystrokeForKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:14:1007868)
    at KeymapManager.t.exports.KeymapManager.keystrokeForKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1229829)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1227814)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:285166)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm how you installed Atom?  Did you use one of the supported installation methods (https://flight-manual.atom.io/getting-started/sections/installing-atom/)?  If so, can you try installing again and see if that clears things up?
