### ISSUE TITLE
Flaky test: Provider API test on autocomplete-plus failing

### ISSUE THREAD

**Issue by rafeca** [atom/atom#19478]
Sometimes builds end up failing with a test failure on the `autocomplete-plus` package:

```
Provider API
  Provider API v2.0.0
    it Provider API Provider API v2.0.0 correctly displays the suggestion options
      Expected null to have html '<span style="color: red">ohai'.
        at jasmine.Spec.<anonymous> (/Users/vsts/agent/2.152.1/work/1/s/node_modules/autocomplete-plus/spec/provider-api-spec.js:134:77)
        at Immediate.setImmediate (/Users/vsts/agent/2.152.1/work/1/s/node_modules/autocomplete-plus/spec/spec-helper.js:45:9)
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)
      Expected null to have text 'ohai'.
        at jasmine.Spec.<anonymous> (/Users/vsts/agent/2.152.1/work/1/s/node_modules/autocomplete-plus/spec/provider-api-spec.js:135:67)
        at Immediate.setImmediate (/Users/vsts/agent/2.152.1/work/1/s/node_modules/autocomplete-plus/spec/spec-helper.js:45:9)
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)
      Expected '<span class="suggestion-description-content">' to have text 'There be documentation'.
        at jasmine.Spec.<anonymous> (/Users/vsts/agent/2.152.1/work/1/s/node_modules/autocomplete-plus/spec/provider-api-spec.js:136:93)
        at Immediate.setImmediate (/Users/vsts/agent/2.152.1/work/1/s/node_modules/autocomplete-plus/spec/spec-helper.js:45:9)
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)
      Expected '' to be 'none'.
        at jasmine.Spec.<anonymous> (/Users/vsts/agent/2.152.1/work/1/s/node_modules/autocomplete-plus/spec/provider-api-spec.js:137:109)
        at Immediate.setImmediate (/Users/vsts/agent/2.152.1/work/1/s/node_modules/autocomplete-plus/spec/spec-helper.js:45:9)
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)
```

Rebuilding can sometimes resolve the failure.

---

**Affected CI provider(s)**: Azure DevOps

**Affected platform(s)**: macOS

**Example commit experiencing flakiness**: https://github.com/atom/atom/commit/a42a2eb22547bd965f46e9597f1caf8d2c57b2a4

**Example failing build at that commit**: https://github.visualstudio.com/Atom/_build/results?buildId=42651
**Example passing build at that commit**: https://github.visualstudio.com/Atom/_build/results?buildId=42649

**Comment by rafeca** [comment]
This issue may have some relation to https://github.com/atom/atom/issues/19475 but should be fixed separately
