### ISSUE TITLE
autocomplete-plus test failing most of the times

### ISSUE THREAD

**Issue by rafeca** [atom/atom#19475]
Sometimes builds end up failing with a test failure on the `autocomplete-plus` package:

```
Autocomplete Manager
  when watching an external text editor for a given set of provider labels
    it Autocomplete Manager when watching an external text editor for a given set of provider labels provides appropriate autocompletions when each editor is focused.
      Expected 0 to equal 1.
        at jasmine.Spec.runs (/Users/vsts/agent/2.152.1/work/1/s/node_modules/autocomplete-plus/spec/autocomplete-manager-integration-spec.js:2581:30)
        at Immediate.setImmediate (/Users/vsts/agent/2.152.1/work/1/s/node_modules/autocomplete-plus/spec/spec-helper.js:30:9)
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)
      TypeError: Cannot read property 'innerText' of undefined
        at jasmine.Spec.runs (/Users/vsts/agent/2.152.1/work/1/s/node_modules/autocomplete-plus/spec/autocomplete-manager-integration-spec.js:2582:25)
        at Immediate.setImmediate (/Users/vsts/agent/2.152.1/work/1/s/node_modules/autocomplete-plus/spec/spec-helper.js:30:9)
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)
```

Rebuilding can sometimes resolve the failure.

---

**Affected CI provider(s)**: Azure DevOps

**Affected platform(s)**: macOS

**Example commit experiencing flakiness**: https://github.com/atom/atom/commit/faa36949d94ad919364f852faf1cb9d9464c10f9

**Example failing build at that commit**: https://dev.azure.com/github/Atom/_build/results?buildId=42640
**Example passing build at that commit**: https://github.visualstudio.com/Atom/_build/results?buildId=42644

**Comment by rafeca** [comment]
First instance of this test failure that I've found was on May 20th ([link](https://dev.azure.com/github/Atom/_build/results?buildId=40878&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=8b9bff53-2841-58c7-68fc-e30c30330fc3&lineStart=1737&lineEnd=1748&colStart=1&colEnd=44)), but until June 6th the failures were really rare (in 16 days only 1 failure).

Since June 6th the failures caused by this test have been much more common (8 failures out of 17 builds). The source of the increase on flakiness seems to be https://github.com/atom/atom/pull/19446.

There's been an attempt to fix the flakiness in https://github.com/atom/atom/pull/19457, but it does not seem to have fixed completely the issue
