### ISSUE TITLE
Fail to generate an Atom build in Ubuntu 19.04 64bit

### ISSUE THREAD

**Issue by xrgranados** [atom/atom#19563]
I have created a new fork of the repository for Atom 1.40.0-dev. Following these [instructions](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#platform-linux) for generating an Atom build, I have run “script/bootstrap” in order to install all required dependencies.

When trying to generate the Atom build using a Linux 19.04 64bit enabled computer by executing the “script/build”, I am getting an error message in the terminal when the building process stops. The error message is the following:

```
Node:	v10.16.0
Npm:	v6.2.0
Installing script dependencies
Installing apm
apm  2.3.1
npm  6.2.0
node 10.2.1 x64
atom unknown
python 2.7.16
git 2.20.1
Installing modules ✓
Wrote Dependencies Fingerprint: /home/dev-xr/gitprojects/atom/node_modules/.dependencies-fingerprint cbfce05d767b0c926487b711109ed54461b24ed0
Cleaning /home/dev-xr/gitprojects/atom/out
Copying assets to /home/dev-xr/gitprojects/atom/out/app
Transpiling packages with custom transpiler configurations in /home/dev-xr/gitprojects/atom/out/app
 transpiling for package github
Installing modules ✗
> superstring@2.3.6 install /home/dev-xr/gitprojects/atom/node_modules/github/node_modules/superstring
> node-gyp rebuild


Aborted (core dumped)
gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/dev-xr/gitprojects/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 5.0.0-17-generic
gyp ERR! command "/home/dev-xr/gitprojects/atom/apm/node_modules/atom-package-manager/bin/node" "/home/dev-xr/gitprojects/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dev-xr/gitprojects/atom/node_modules/github/node_modules/superstring
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! superstring@2.3.6 install: `node-gyp rebuild`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the superstring@2.3.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev-xr/.atom/.apm/_logs/2019-06-18T20_30_29_748Z-debug.log
child_process.js:650
    throw err;
    ^

Error: Command failed: /home/dev-xr/gitprojects/atom/apm/node_modules/atom-package-manager/bin/apm install
  at checkExecSyncError (child_process.js:629:11)
  at Object.execFileSync (child_process.js:647:13)
  at module.exports (/home/dev-xr/gitprojects/atom/script/lib/run-apm-install.js:14:16)
  at module.exports (/home/dev-xr/gitprojects/atom/script/lib/transpile-packages-with-custom-transpiler-paths.js:44:7)
  at Object.<anonymous> (/home/dev-xr/gitprojects/atom/script/build:74:3)
  at Module._compile (internal/modules/cjs/loader.js:776:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
  at Module.load (internal/modules/cjs/loader.js:653:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
  at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
  at startup (internal/bootstrap/node.js:283:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```
I have been doing research about this issue and found this issue [#15203](https://github.com/atom/atom/issues/15203), where a very similar problem is described.

The issue got comments suggesting that the clang-3.3 package should be installed in order to fix the issue, nevertheless, because of the Ubuntu version I am using didn’t allow me to install that clang version so I had to install the clang-8.0 package. The clang package version (8.0)  was updated in the .travis.yml file in the local Atom project.

The build generation process was run again with the above-mentioned changes applied, but the error persists.

Alternatively, before running the building process I manually, and separately, installed the nodejs *superstring* package, which is described in the previously shared error message I got. For this, I executed `npm install superstring@2.3.6`. I did this in order to define if the dependency installed separately works when running the building process. But the results were also unsuccessful.

Would anyone have experienced a problem similar to this and has suggestions on how to solve it?

**Comment by rsese** [comment]
I setup a fresh 19.04 Ubuntu vm and was unable to reproduce - I installed Node 10.16.0, Python 2.17.6, and the prerequisites mentioned in https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#ubuntu--debian.  After that, `./script/bootstrap` completed without error.

What commit SHA are you at?  I cloned at 4027b0b6.

**Comment by xrgranados** [comment]
Thank you for your answer.

Actually, I can also complete `"script/bootstrap"` without errors. My issue comes when running `"script/build"`. 

I cloned from commit SHA [`9406934`](https://github.com/atom/atom/commit/940693458f2e8fee8e1813eb74400f5bf5872a5c).

I was also checking the prerequisites mentioned in the link you shared and I happen to have everything ok, but `gcc` and `g++`. They suggest to install version 5 and I have installed version 8.3 in both cases

**Comment by rsese** [comment]
> I was also checking the prerequisites mentioned in the link you shared and I happen to have everything ok, but `gcc` and `g++`. They suggest to install version 5 and I have installed version 8.3 in both cases

Hmm, I didn't need to run through that second part of the section, I only had to run through the "Install GNOME headers and other basic prerequisites:" part.

Did you already try running `./script/clean` before `./script/build` again?

**Comment by xrgranados** [comment]
I ran the `./script/clean` script before executing `./script/build`. The process failed again in the same point, when trying to load `binding.gyp`. Since that doesn' work, the installation of the `superstring` dependency fails and the whole building process fails.

The whole error message as follows:
```
transpiling for package github
Installing modules ✗
> superstring@2.3.6 install /home/dev-xr/gitprojects/atom/node_modules/github/node_modules/superstring
> node-gyp rebuild


Aborted (core dumped)
gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/dev-xr/gitprojects/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 5.0.0-17-generic
gyp ERR! command "/home/dev-xr/gitprojects/atom/apm/node_modules/atom-package-manager/bin/node" "/home/dev-xr/gitprojects/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dev-xr/gitprojects/atom/node_modules/github/node_modules/superstring
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! superstring@2.3.6 install: `node-gyp rebuild`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the superstring@2.3.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev-xr/.atom/.apm/_logs/2019-06-20T21_51_14_041Z-debug.log
child_process.js:650
    throw err;
    ^

Error: Command failed: /home/dev-xr/gitprojects/atom/apm/node_modules/atom-package-manager/bin/apm install
  at checkExecSyncError (child_process.js:629:11)
  at Object.execFileSync (child_process.js:647:13)
  at module.exports (/home/dev-xr/gitprojects/atom/script/lib/run-apm-install.js:14:16)
  at module.exports (/home/dev-xr/gitprojects/atom/script/lib/transpile-packages-with-custom-transpiler-paths.js:44:7)
  at Object.<anonymous> (/home/dev-xr/gitprojects/atom/script/build:74:3)
  at Module._compile (internal/modules/cjs/loader.js:776:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
  at Module.load (internal/modules/cjs/loader.js:653:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
  at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
  at startup (internal/bootstrap/node.js:283:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

At this point I have no idea what can be causing the errors.
I wonder if the `gcc` & `g++` version could be causing the issue? (I have installed v8.3 and the https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#ubuntu--debian suggest v5)

I appreciate your help.

**Comment by rsese** [comment]
> At this point I have no idea what can be causing the errors.
> I wonder if the `gcc` & `g++` version could be causing the issue? (I have installed v8.3 and the https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#ubuntu--debian suggest v5)

Looks like I have the same version:

```
gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1) 
```

I installed Node v10.16.0, what version do you have?

**Comment by xrgranados** [comment]
I have the same, Node v10.16.0.
I am really out of ideas here. Anything that comes to your mind will be greatly appreciated. Thanks!

**Comment by jwoehr** [comment]
Having the same problem on Ubuntu 19.04

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/jwoehr/work/Atom/atom/apm/node_modules/atom-package-manager/bin/node',
1 verbose cli   '/home/jwoehr/work/Atom/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/home/jwoehr/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/home/jwoehr/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   '--target=4.2.7',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64' ]
2 info using npm@6.2.0
3 info using node@v10.2.1
4 verbose npm-session 079b8ee4c8ae8784
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall atom@1.42.0-dev
7 info lifecycle atom@1.42.0-dev~preinstall: atom@1.42.0-dev
8 verbose lifecycle atom@1.42.0-dev~preinstall: unsafe-perm in lifecycle true
9 verbose lifecycle atom@1.42.0-dev~preinstall: PATH: /home/jwoehr/work/Atom/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/jwoehr/work/Atom/atom/node_modules/.bin:/home/jwoehr/work/Atom/atom/apm/node_modules/atom-package-manager/bin:/home/jwoehr/.local/bin:/home/jwoehr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle atom@1.42.0-dev~preinstall: CWD: /home/jwoehr/work/Atom/atom
11 silly lifecycle atom@1.42.0-dev~preinstall: Args: [ '-c', 'node -e \'process.exit(0)\'' ]
12 silly lifecycle atom@1.42.0-dev~preinstall: Returned: code: 134  signal: null
13 info lifecycle atom@1.42.0-dev~preinstall: Failed to exec preinstall script
14 timing stage:rollbackFailedOptional Completed in 1ms
15 timing stage:runTopLevelLifecycles Completed in 465ms
16 verbose stack Error: atom@1.42.0-dev preinstall: `node -e 'process.exit(0)'`
16 verbose stack Exit status 134
16 verbose stack     at EventEmitter.<anonymous> (/home/jwoehr/work/Atom/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
16 verbose stack     at EventEmitter.emit (events.js:182:13)
16 verbose stack     at ChildProcess.<anonymous> (/home/jwoehr/work/Atom/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
16 verbose stack     at ChildProcess.emit (events.js:182:13)
16 verbose stack     at maybeClose (internal/child_process.js:961:16)
16 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
17 verbose pkgid atom@1.42.0-dev
18 verbose cwd /home/jwoehr/work/Atom/atom
19 verbose Linux 5.0.0-25-generic
20 verbose argv "/home/jwoehr/work/Atom/atom/apm/node_modules/atom-package-manager/bin/node" "/home/jwoehr/work/Atom/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/jwoehr/.atom/.apm/.apmrc" "--userconfig" "/home/jwoehr/.atom/.apmrc" "install" "--target=4.2.7" "--disturl=https://atom.io/download/electron" "--arch=x64"
21 verbose node v10.2.1
22 verbose npm  v6.2.0
23 error code ELIFECYCLE
24 error errno 134
25 error atom@1.42.0-dev preinstall: `node -e 'process.exit(0)'`
25 error Exit status 134
26 error Failed at the atom@1.42.0-dev preinstall script.
26 error This is probably not a problem with npm. There is likely additional logging output above.
27 verbose exit [ 134, true ]
```

**Comment by ericcornelissen** [comment]
> Having the same problem on Ubuntu 19.04

I get the same log when running `script/bootstrap` (after running `script/clean`) at commit 4027b0b and ef80c4d43 on Ubuntu 19.04 64-bits. Here are my versions of the requirements:

```
~ » node --version
v10.15.2
--------------------------------------------------------------------------------
~ » npm --version
p6.11.2
--------------------------------------------------------------------------------
~ » python --version
Python 2.7.16
--------------------------------------------------------------------------------
~ » gcc --version
gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
--------------------------------------------------------------------------------
~ » g++ --version
g++ (Ubuntu 8.3.0-6ubuntu1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Aerijo** [comment]
#15203 is a very different error. I’ve seen this one when NodeJS is installed using apt. Could you try with it installed using nvm instead?

**Comment by ericcornelissen** [comment]
@Aerijo I'm still getting the same error log when installing Node (v10.16.3) via nvm instead. When using Node v12.10 some `make` script is failing (see [this error log](https://gist.github.com/ericcornelissen/6da75596050b1821fde6f9c7d1dd3022#file-build-error-atom-boostrap-script-ubuntu-19-04-node-v12-10-commit-4027b0b65-log)) and with Node v6.17.1 it seems the Node version is too low, even thought [the instructions](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#platform-linux) say Node v6.x is the minimum requirement? (see [this error log](https://gist.github.com/ericcornelissen/6da75596050b1821fde6f9c7d1dd3022#file-build-error-atom-boostrap-script-ubuntu-19-04-node-v6-17-1-commit-4027b0b65-log)).
