### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by LiCarry** [atom/atom#19574]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At C:\Users\C#\AppData\Local\atom\app-1.38.2\resources\app\static\<embedded>:14

TypeError: Cannot read property 'version' of undefined
    at ~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:2547007
    at ~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:932278
    at r (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:929284)
    at n (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1119384)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1119590)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

**Comment by Hoiyeuhng** [comment]
I try to install script packages.
and the error occurred.
<img width="1701" alt="Screen Shot 2019-07-15 at 2 12 35 PM" src="https://user-images.githubusercontent.com/41023868/61238453-a9b16e80-a70a-11e9-9964-6bfdf0454b16.png">




[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.14.5
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At /Users/haiyangluo/Desktop/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:248

TypeError: Cannot read property 'version' of undefined
    at /Users/haiyangluo/Desktop/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:248:41
    at /Users/haiyangluo/Desktop/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:333:24
    at exit (/Users/haiyangluo/Desktop/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Users/haiyangluo/Desktop/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (/Users/haiyangluo/Desktop/Atom.app/Contents/Resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
  3x -1:47.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by eslam-reda-5434556** [comment]
iam have a proplem the atom mave relod evry time
