### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.ffyb...

### ISSUE THREAD

**Issue by juanjosecas** [atom/atom#19595]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.ffyb.uba.ar proxy.ffyb.uba.ar:8080

```
At events.js:183

Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.ffyb.uba.ar proxy.ffyb.uba.ar:8080
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -0:54.3.0 pane:reopen-closed-item (div.panels-item)
```

### Non-Core Packages

```
atom-bash 1.1.1 
Atom-Bash-Snippets 0.0.3 
autocomplete-bash-builtins 0.3.5 
minimap 4.29.9 
pigments 0.40.2 
```

**Comment by rsese** [comment]
Thanks for the report - the ENOTFOUND error seems like a networking/DNS issue rather than an issue with Atom? We'll go ahead and close but suggest double checking your proxy settings?
