### ISSUE TITLE
Failed to activate the format package

### ISSUE THREAD

**Issue by yanellyjimenez** [atom/atom#19632]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.04.2
**Thrown From**: 'format' package vundefined

### Stack Trace

Failed to activate the format package

```
At Cannot register a command with a null listener.

Error: Cannot register a command with a null listener.
    at CommandRegistry.add (/snap/atom/232/usr/share/atom/resources/app/static/<embedded>:11:345262)
    at Object.activate (/packages/format/src/main.js:11:35)
    at Package.activateNow (/snap/atom/232/usr/share/atom/resources/app/static/<embedded>:11:3416677)
    at measure (/snap/atom/232/usr/share/atom/resources/app/static/<embedded>:11:3416089)
    at Package.measure (/snap/atom/232/usr/share/atom/resources/app/static/<embedded>:11:3413720)
    at activationPromise.activationPromise.Promise (/snap/atom/232/usr/share/atom/resources/app/static/<embedded>:11:3415949)
    at new Promise (<anonymous>)
    at Package.activate (/snap/atom/232/usr/share/atom/resources/app/static/<embedded>:11:3415892)
    at PackageManager.activatePackage (/snap/atom/232/usr/share/atom/resources/app/static/<embedded>:11:381112)
    at /snap/atom/232/usr/share/atom/resources/app/static/<embedded>:11:934678
    at r (/snap/atom/232/usr/share/atom/resources/app/static/<embedded>:11:929284)
    at n (/snap/atom/232/usr/share/atom/resources/app/static/<embedded>:14:1119363)
    at t.bufferStream (/snap/atom/232/usr/share/atom/resources/app/static/<embedded>:14:1119517)
    at Socket.e.on (/snap/atom/232/usr/share/atom/resources/app/static/<embedded>:14:1118119)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.17 
esformatter 3.0.0 
formatter 2.12.4 
formatter-json 1.0.1 
Hydrogen 2.10.3 
language-terra 0.1.0 
language-terraform 0.8.1 
linter-terraform-syntax 1.3.1 
terraform-fmt 0.3.0 
terraform-lookup 1.0.0 
xml-formatter 0.13.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the https://atom.io/packages/format package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

Additionally, it looks like you're using the Snap install of Atom - the Snap install is unofficial and not supported by us; we recommend using an official installation method: https://flight-manual.atom.io/getting-started/sections/installing-atom/
