### ISSUE TITLE
Uncaught Error: EACCES: permission denied, scandir '$ATOM_HOME/packages/platformio-ide'

### ISSUE THREAD

**Issue by smallman33** [atom/atom#19695]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EACCES: permission denied, scandir '/Users/smallman33/.atom/packages/platformio-ide'

```
At fs.js:143

Error: EACCES: permission denied, scandir '/Users/smallman33/.atom/packages/platformio-ide'
    at Object.fs.readdirSync (fs.js:893:3)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:633:28)
    at Proxy.listSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:267421)
    at PackageDetailView.updateFileButtons (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:829618)
    at PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:826939)
    at PackageDetailView.populate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:826492)
    at PackageDetailView.completeInitialization (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:821832)
    at PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:822044)
    at new PackageDetailView (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:818630)
    at SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:951189)
    at SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:951910)
    at HTMLDivElement.clickHandler (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2553838)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.12.0 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.33 
intentions 1.1.5 
language-ini 1.21.0 
linter 2.3.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide undefined 
platformio-ide-debugger 1.2.6 
tool-bar 1.1.12 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error (looks like you're trying to install platformio-ide)?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

**Comment by linjialiang** [comment]
@rsese https://github.com/platformio/platformio-atom-ide-terminal/issues/720#issuecomment-514855874
