### ISSUE TITLE
Uncaught The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by KAMINJIN** [atom/atom#19717]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught The "path" argument must be of type string. Received type object

```
At path.js:39

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.join (path.js:434:7)
    at MoveDialog.onConfirm (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:14:2662680)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:14:3150060)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:348736)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:1248155)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:1244289)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:283942)
```

### Commands

```
     -1:27 editor:newline (input.hidden-input)
     -0:55.5.0 core:save (input.hidden-input)
     -0:50.6.0 tree-view:rename (div.title)
 66x -0:49.2.0 core:backspace (input.hidden-input)
  3x -0:44.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
script 3.18.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

**Comment by TTcheng** [comment]
This same issue accurred when i attempt to rename a file in atom. My OS is Archlinux , and the software package named atom-editor-bin is from community build from deb package. However the another package (named atom from community)  directly running on electron does not have the problem.

**Comment by wildoracle** [comment]
I also was renaming a file in Atom. My OS is Windows 10.

**Comment by misterdaan** [comment]
This issue occured when I renamed a file or created a file on my share, mapped as a network drive in Windows 10 (1903). The file is not renamed or created if this error occures. The problem lies in the fact that a '\' is missing in the path. When the backslash is added manually, there is no error.

![afbeelding](https://user-images.githubusercontent.com/38474167/73592820-ab078480-44fe-11ea-937d-42fc2ab880ae.png)
