### ISSUE TITLE
Atom transpile option ignores node_modules

### ISSUE THREAD

**Issue by dempfi** [atom/atom#19733]
### Description

It seems atom transpiles dependencies of the packages (code in `node_modules`) even if they are not used. However, atom transpile option explicitly [ignores `node_modules`](https://github.com/atom/atom/blob/1d9a4cafcf6cc288d675512db8fd984e13aab869/src/package-transpilation-registry.js#L99-L100).

In my case I have a dependency containing typescript code which is not properly transpiled due to a broken built-in typescript transpiler and I can't use `atom-ts-transpiler` either since it's not applied to `node_modules`, so I end up with 

```
Error: ENOENT, node_modules/typescript/bin/lib.d.ts not found in /Applications/Atom.app/Contents/Resources/app.asar
    at notFoundError (ELECTRON_ASAR.js:108:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:571:9)
    at TypeScriptSimple.createService (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/typescript-simple/index.js:56:61)
    at TypeScriptSimple.compile (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/typescript-simple/index.js:45:37)
    at Object.e.compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:577328)
    at Object.compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:573106)
    at compileFileAtPath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:148526)
    at Object.value [as .ts] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150924)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:71:46)
. . .
```
 

### Steps to Reproduce

1. Setup a package with `atomTranspilers` option set to `atom-ts-transpiler`
2. Have a dependency containing a `.ts` file
3. Try to load the package in atom

**Expected behavior:**

- Respect `atomTranspilers` glob pattern and use it to transpile even the code in `node_modules`;
- Don't transpile the code in `node_modules` at all;

**Actual behavior:**

Transpilation error due to a broken built-in typescript transpiler.

**Reproduces how often:**

100%

### Versions

```
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

**Comment by rsese** [comment]
Sorry for the delay and thanks for the report -

> * Setup a package with `atomTranspilers` option set to `atom-ts-transpiler`

Are you able to share an example package already setup for testing?

Also, can you still reproduce with latest stable version of Atom (currently 1.41.0)?
