### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 1283Error: Cannot ca...

### ISSUE THREAD

**Issue by hehnope** [atom/atom#19737]
Apologies if this issue already exists. I'm just following crash report after using atom. I'm not entirely sure how to reproduce this.

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Linux Mint
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 1283
Error: Cannot call function 'getPosition' on missing remote object 1283
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 1283
Error: Cannot call function 'getPosition' on missing remote object 1283
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app/static/<embedded>:1:703887)
    at AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app/static/<embedded>:1:704302)
    at WindowEventHandler.handleWindowBlur (/usr/share/atom/resources/app/static/<embedded>:11:284967)
```

### Commands

```
     -2:49.3.0 core:confirm (input.hidden-input)
     -2:46.7.0 tree-view:add-file (div.header.list-item)
     -2:44.9.0 core:confirm (input.hidden-input)
  2x -2:42.2.0 core:backspace (input.hidden-input)
  5x -2:40.9.0 editor:newline (input.hidden-input)
  4x -1:21.9.0 core:backspace (input.hidden-input)
     -1:15.4.0 editor:newline (input.hidden-input)
     -1:13.7.0 core:copy (input.hidden-input)
     -1:12.2.0 editor:newline (input.hidden-input)
     -1:11.6.0 core:paste (input.hidden-input)
     -0:58.3.0 core:save (input.hidden-input)
     -0:55.4.0 core:copy (input.hidden-input)
     -0:53.7.0 editor:newline (input.hidden-input)
     -0:53.1.0 core:paste (input.hidden-input)
     -0:51 core:save (input.hidden-input)
     -0:20.7.0 application:add-project-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
autocomplete-python 1.14.1 
go-debug 1.6.2 
go-plus 6.1.0 
go-signature-statusbar 1.2.3 
language-terraform 0.8.1 
platformio-ide-terminal 2.9.1 
```

**Comment by hehnope** [comment]
Duplicate of https://github.com/atom/atom/issues/16630, @rsese figured I'd loop you in and close.

**Comment by rsese** [comment]
Thanks @hehnope :+1:  If you end up coming across specific repro steps, please let us know.
