### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/private/var/folders/x6/wd7sd8vx1td3138...

### ISSUE THREAD

**Issue by filippomaffei** [atom/atom#19749]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents'

```
At fs.js:143

Error: ENOENT: no such file or directory, lstat '/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents'
    at realpathSync (fs.js:1744:7)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:343:24)
    at toRealPath (internal/modules/cjs/loader.js:210:13)
    at Function.Module._findPath (internal/modules/cjs/loader.js:263:24)
    at Module._resolveFilename (internal/modules/cjs/loader.js:599:25)
    at Module._resolveFilename (/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents/Resources/app/static/<embedded>:11:155394)
    at Module.require (/app.asar/static/index.js:60:43)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents/Resources/app/static/<embedded>:1:686763)
    at get_Parser (/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents/Resources/app/static/<embedded>:11:3322545)
    at Function._patchSyntaxNode (/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents/Resources/app/static/<embedded>:11:3323053)
    at new TreeSitterLanguageMode (/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents/Resources/app/static/<embedded>:11:3323309)
    at GrammarRegistry.languageModeForGrammarAndBuffer (/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents/Resources/app/static/<embedded>:11:354541)
    at GrammarRegistry.assignLanguageMode (/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents/Resources/app/static/<embedded>:11:354063)
    at TextEditorRegistry.setGrammarOverride (/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents/Resources/app/static/<embedded>:11:510602)
    at Object.didConfirmSelection (/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents/Resources/app/static/<embedded>:11:835445)
    at SelectListView.confirmSelection (/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents/Resources/app/static/<embedded>:11:872494)
    at SelectListView.didClickItem (/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents/Resources/app/static/<embedded>:11:870436)
    at ListItemView.onclick (/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents/Resources/app/static/<embedded>:11:869426)
    at ListItemView.didClick (/private/var/folders/x6/wd7sd8vx1td3138_8b537_km0000gp/T/AppTranslocation/92BB61FD-4C48-46E1-90C1-DE59F233C673/d/Atom.app/Contents/Resources/app/static/<embedded>:11:873514)
```

### Commands

```
  2x -0:23.5.0 grammar-selector:show (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Looks like maybe a problem with the install?   Can you run through the [installation](https://flight-manual.atom.io/getting-started/sections/installing-atom/) again and let me know if you still have trouble?
