### ISSUE TITLE
Uncaught TypeError: Bind must be called on a function

### ISSUE THREAD

**Issue by badalrai** [atom/atom#19747]
**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: "Fedora release
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Bind must be called on a function

```
At events.js:187

TypeError: Bind must be called on a function
    at NativeConnection.bind (<anonymous>)
    at NativeConnection.emit (events.js:187:15)
    at NativeConnection.EventEmitter.emit (domain.js:442:20)
    at process.nextTick (/home/Elefind/Projects/FullStack/node_modules/mongoose/lib/connection.js:683:37)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

### Commands

```
     -2:06.5.0 editor:newline (input.hidden-input)
     -2:04.4.0 core:undo (input.hidden-input)
     -2:03.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -2:02.8.0 editor:newline (input.hidden-input)
  2x -1:49.1.0 core:move-down (input.hidden-input)
  2x -1:48.6.0 autocomplete-plus:confirm (input.hidden-input)
 12x -1:39.5.0 core:backspace (input.hidden-input)
     -1:37.8.0 editor:newline (input.hidden-input)
  3x -1:16.6.0 core:backspace (input.hidden-input)
     -1:10.5.0 autocomplete-plus:confirm (input.hidden-input)
     -1:10.4.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:07.9.0 core:undo (input.hidden-input)
     -1:03.8.0 autocomplete-plus:confirm (input.hidden-input)
 21x -0:20.3.0 core:backspace (input.hidden-input)
 81x -0:15.9.0 core:delete (input.hidden-input)
     -0:09.1.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.5.3 
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-nodejs-snippets 2.1.1 
autocomplete-java 1.2.7 
expressjs 2.2.0 
file-type-icons 1.3.4 
git-plus 8.7.1 
Hydrogen 2.10.3 
language-dotenv 1.2.0 
language-mongodb 0.3.1 
less-than-slash 0.19.0 
minimap 4.29.9 
node-repl 0.5.0 
node-repl-online 0.0.1 
node-require 1.0.0 
node-requirer 0.1.12 
pane-layout-plus 0.7.4 
pigments 0.40.2 
teletype 0.13.4 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?
