### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=503

### ISSUE THREAD

**Issue by mehdihz** [atom/atom#19762]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=503

```
At internal/streams/legacy.js:57

Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketOnData (_http_client.js:465:11)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
```

### Commands

```
  7x -0:52.7.0 core:close (atom-pane.pane.active)
     -0:15.2.0 core:confirm (input.hidden-input)
     -0:13.9.0 core:select-all (input.hidden-input)
     -0:12.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.33 
language-babel 2.85.0 
```

**Comment by rsese** [comment]
Thanks for the report! Are you using a network proxy? This seems like it could be a temporary network issue or an issue with authenticating to your proxy based on the error code? Please double check your proxy settings and try again later and see if you continue getting the same error.
