### ISSUE TITLE
Failed to activate the autocomplete-plus package error

### ISSUE THREAD

**Issue by cameleater** [atom/atom#19793]
[Enter steps to reproduce:]

Haven't used Atom in a few days, am now getting uncaught errors trying to open files, search folders, open settings etc.

1. Opened Atom
2. Get uncaught errors

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the autocomplete-plus package

\\?\C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app.asar.unpacked\node_modules\text-buffer\node_modules\superstring\build\Release\superstring.node is not a valid Win32 application.
\\?\C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app.asar.unpacked\node_modules\text-buffer\node_modules\superstring\build\Release\superstring.node
```
Error: \\?\C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app.asar.unpacked\node_modules\text-buffer\node_modules\superstring\build\Release\superstring.node is not a valid Win32 application.
\\?\C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app.asar.unpacked\node_modules\text-buffer\node_modules\superstring\build\Release\superstring.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (file:///C:/Users/jordan/AppData/Local/atom/app-1.40.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app.asar\node_modules\text-buffer\node_modules\superstring\index.js:118:15)
    at Object.<anonymous> (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app.asar\node_modules\text-buffer\node_modules\superstring\index.js:357:3)
    at Module.get_Module._compile (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .js] (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (file:///C:/Users/jordan/AppData/Local/atom/app-1.40.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:1:727319)
    at get_superstring (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:479274)
    at get_NativeTextBuffer (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:479385)
    at new TextBuffer (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:480466)
    at new SubsequenceProvider (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:14:1476871)
    at ProviderManager.toggleDefaultProvider (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:14:493541)
    at subscriptions.add.atom.config.observe.e (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:14:491706)
    at Config.observeKeyPath (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:334261)
    at Config.observe (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:328743)
    at ProviderManager.initialize (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:14:491648)
    at AutocompleteManager.initialize (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:641421)
    at Object.activate (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:161679)
    at Package.activateNow (C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:3406284)
```

Uncaught Error: \\?\C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app.asar.unpacked\node_modules\text-buffer\node_modules\superstring\build\Release\superstring.node is not a valid Win32 application.
\\?\C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app.asar.unpacked\node_modules\text-buffer\node_modules\superstring\build\Release\superstring.node

```
At C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app.asar\node_modules\text-buffer\node_modules\superstring\index.js:123

Error: \\?\C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app.asar.unpacked\node_modules\text-buffer\node_modules\superstring\build\Release\superstring.node is not a valid Win32 application.
\\?\C:\Users\jordan\AppData\Local\atom\app-1.40.0\resources\app.asar.unpacked\node_modules\text-buffer\node_modules\superstring\build\Release\superstring.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:146745)
    at /app.asar/node_modules/text-buffer/node_modules/superstring/index.js:118:15)
    at /app.asar/node_modules/text-buffer/node_modules/superstring/index.js:357:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:1:727319)
    at get_superstring (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:479274)
    at get_NativeTextBuffer (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:479385)
    at new TextBuffer (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:480466)
    at new TextEditor (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:1:772702)
    at elementForArray (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:14:2593418)
    at elementForSetting (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:14:2593579)
    at SettingsPanel.elementForSettings (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:14:2584608)
    at new SettingsPanel (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:14:2583130)
    at render (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:14:2578099)
    at addChildren (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:14:2578453)
    at render (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:14:2578326)
    at Object.initialize (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:14:2580153)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
react 0.18.0 
```

**Comment by rsese** [comment]
Thanks for the report!  I wonder if there was an issue updating to 1.40.0 - can you quit Atom and then manually install Atom again with the installer from https://atom.io/ and let me know if you still see the same error?

**Comment by cameleater** [comment]
> Thanks for the report! I wonder if there was an issue updating to 1.40.0 - can you quit Atom and then manually install Atom again with the installer from https://atom.io/ and let me know if you still see the same error?

This has resolved the errors, cheers

**Comment by rsese** [comment]
Thanks for confirming, glad you have things sorted out now :v:
