### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/1w/28stldw55t31sntlxjdvdng80000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by corbein** [atom/atom#19850]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/1w/28stldw55t31sntlxjdvdng80000gn/T/AppTranslocation/8E6D25D0-FCF4-4A66-A548-5CFF7935F2A9/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): no suitable image found.  Did find:
	/private/var/folders/1w/28stldw55t31sntlxjdvdng80000gn/T/AppTranslocation/8E6D25D0-FCF4-4A66-A548-5CFF7935F2A9/d/Atom.app/Contents: not a file

```
At ELECTRON_ASAR.js:166

Error: dlopen(/private/var/folders/1w/28stldw55t31sntlxjdvdng80000gn/T/AppTranslocation/8E6D25D0-FCF4-4A66-A548-5CFF7935F2A9/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): no suitable image found.  Did find:
	/private/var/folders/1w/28stldw55t31sntlxjdvdng80000gn/T/AppTranslocation/8E6D25D0-FCF4-4A66-A548-5CFF7935F2A9/d/Atom.app/Contents: not a file
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/private/var/folders/1w/28stldw55t31sntlxjdvdng80000gn/T/AppTranslocation/8E6D25D0-FCF4-4A66-A548-5CFF7935F2A9/d/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
    at get_KeyboardLayoutManager (/private/var/folders/1w/28stldw55t31sntlxjdvdng80000gn/T/AppTranslocation/8E6D25D0-FCF4-4A66-A548-5CFF7935F2A9/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2744622)
    at get_manager (/private/var/folders/1w/28stldw55t31sntlxjdvdng80000gn/T/AppTranslocation/8E6D25D0-FCF4-4A66-A548-5CFF7935F2A9/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2744724)
    at Object.getCurrentKeyboardLayout (/private/var/folders/1w/28stldw55t31sntlxjdvdng80000gn/T/AppTranslocation/8E6D25D0-FCF4-4A66-A548-5CFF7935F2A9/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2744850)
    at e.keystrokeForKeyboardEvent (/private/var/folders/1w/28stldw55t31sntlxjdvdng80000gn/T/AppTranslocation/8E6D25D0-FCF4-4A66-A548-5CFF7935F2A9/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1087821)
    at KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/1w/28stldw55t31sntlxjdvdng80000gn/T/AppTranslocation/8E6D25D0-FCF4-4A66-A548-5CFF7935F2A9/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1246932)
    at KeymapManager.handleKeyboardEvent (/private/var/folders/1w/28stldw55t31sntlxjdvdng80000gn/T/AppTranslocation/8E6D25D0-FCF4-4A66-A548-5CFF7935F2A9/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1244917)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/1w/28stldw55t31sntlxjdvdng80000gn/T/AppTranslocation/8E6D25D0-FCF4-4A66-A548-5CFF7935F2A9/d/Atom.app/Contents/Resources/app/static/<embedded>:11:284329)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  If you quit and reinstall Atom, does that clear things up for you?

**Comment by hector-cmd** [comment]
Está el payasito que fue el que agarró el dinero y ahí dice cuánto dice un
dinero que se alegra eso díselo a Godoy saludos soy el gris.

**Comment by corbein** [comment]
No entendí nada

**Comment by rsese** [comment]
@corbein did you try quitting and then reinstalling Atom?

https://flight-manual.atom.io/getting-started/sections/installing-atom/

**Comment by corbein** [comment]
Yes, now it works perfectly
Thank you

**Comment by rsese** [comment]
Great thanks for confirming, I'll go ahead and close this out.
