### ISSUE TITLE
Uncaught Error when put text on new file

### ISSUE THREAD

**Issue by thinkaboutcsharp** [atom/atom#19856]
[Enter steps to reproduce:]

1. Create new file (Ctrl+N)
2. Copy text from chrome browser (below)
3. Past text on Atom

text is...
```
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8"/>
  <link rel="stylesheet" href="styles.css" type="text/css"/>
  <meta name="robots" content="index,noarchive,noimageindex"/>
  <meta name="viewport" content="width=device-width,maximum-scale=1,initial-scale=1,user-scalable=no"/>
</head>
<body>

```
**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: \\?\C:\Users\user\AppData\Local\atom\app-1.40.1\resources\app.asar.unpacked\node_modules\oniguruma\build\Release\onig_scanner.node is not a valid Win32 application.
\\?\C:\Users\user\AppData\Local\atom\app-1.40.1\resources\app.asar.unpacked\node_modules\oniguruma\build\Release\onig_scanner.node

```
At C:\Users\user\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11

Error: \\?\C:\Users\user\AppData\Local\atom\app-1.40.1\resources\app.asar.unpacked\node_modules\oniguruma\build\Release\onig_scanner.node is not a valid Win32 application.
\\?\C:\Users\user\AppData\Local\atom\app-1.40.1\resources\app.asar.unpacked\node_modules\oniguruma\build\Release\onig_scanner.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /app.asar/node_modules/oniguruma/src/oniguruma.js:3:21)
    at /app.asar/node_modules/oniguruma/src/oniguruma.js:116:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:1:714332)
    at get__ref (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:125632)
    at get_OnigString (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:125778)
    at NullGrammar.Grammar.tokenizeLine (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:127647)
    at TextMateLanguageMode.buildTokenizedLineForRowWithText (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:555503)
    at TextMateLanguageMode.suggestedIndentForLineAtBufferRow (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:550395)
    at Selection.insertText (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:538561)
    at mutateSelectedText (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:46458)
    at getSelectionsOrderedByBufferPosition.map (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:16220)
    at Array.map (<anonymous>)
    at transact (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:16209)
    at TextBuffer.transact (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:492111)
    at TextEditor.transact (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:24215)
```

### Commands

```
     -7:45.6.0 settings-view:install-packages-and-themes (input.hidden-input)
     -6:45.1.0 application:new-window (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -6:39.8.0 application:open-folder (div.package-detail)
     -1:19.7.0 application:open-file (atom-pane.pane.active)
     -1:15.5.0 application:new-file (atom-pane.pane.active)
  2x -0:33.6.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
file-type-icons 1.3.4 
line-ending-converter 1.3.2 
preview-in-chrome 1.0.0 
```

**Comment by thinkaboutcsharp** [comment]
It seems that error occur when paste html(tagged) text including EOL. I paste html text without EOL, no error occur.

**Comment by rsese** [comment]
Thanks for the report!  Can you reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by thinkaboutcsharp** [comment]
I got additional information.
when I execute from shortcut on quickbar error occurs, but I execute from command line "atom" don't occurs. So I try to execue full path "c:\～\atom.exe" error occurs.

I belated find missing information about OS, using Windows 10 Pro 1903.

When executing by full path I got same error as follows;

[Enter steps to reproduce:]

1. execute atom by full path from command line with "safe" option
2. same action

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: \\?\C:\Users\user\AppData\Local\atom\app-1.40.1\resources\app.asar.unpacked\node_modules\oniguruma\build\Release\onig_scanner.node is not a valid Win32 application.
\\?\C:\Users\user\AppData\Local\atom\app-1.40.1\resources\app.asar.unpacked\node_modules\oniguruma\build\Release\onig_scanner.node

```
At C:\Users\user\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11

Error: \\?\C:\Users\user\AppData\Local\atom\app-1.40.1\resources\app.asar.unpacked\node_modules\oniguruma\build\Release\onig_scanner.node is not a valid Win32 application.
\\?\C:\Users\user\AppData\Local\atom\app-1.40.1\resources\app.asar.unpacked\node_modules\oniguruma\build\Release\onig_scanner.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /app.asar/node_modules/oniguruma/src/oniguruma.js:3:21)
    at /app.asar/node_modules/oniguruma/src/oniguruma.js:116:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:1:714332)
    at get__ref (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:125632)
    at get_OnigString (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:125778)
    at NullGrammar.Grammar.tokenizeLine (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:127647)
    at TextMateLanguageMode.buildTokenizedLineForRowWithText (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:555503)
    at TextMateLanguageMode.suggestedIndentForLineAtBufferRow (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:550395)
    at Selection.insertText (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:538561)
    at mutateSelectedText (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:46458)
    at getSelectionsOrderedByBufferPosition.map (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:16220)
    at Array.map (<anonymous>)
    at transact (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:16209)
    at TextBuffer.transact (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:492111)
    at TextEditor.transact (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:24215)
```

### Commands

```
     -0:12.3.0 application:new-file (div.tool-panel.tree-view)
     -0:10.4.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by thinkaboutcsharp** [comment]
I found four "atom"s...

C:\ProgramData\user\atom\bin\atom
C:\ProgramData\user\atom\bin\atom.cmd
C:\Users\user\AppData\Local\atom\bin\atom
C:\Users\user\AppData\Local\atom\bin\atom.cmd
