### ISSUE TITLE
Uncaught Error: The module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modu...

### ISSUE THREAD

**Issue by jacobrienstra** [atom/atom#19882]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

```
At ELECTRON_ASAR.js:166

Error: The module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744622)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744724)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744850)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1087821)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1246932)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1244917)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284329)
```

### Commands

```
     -4:34.9.0 command-palette:toggle (atom-pane.pane.active)
     -4:25.3.0 tool-bar:position-top (atom-pane.pane.active)
  2x -4:18.2.0 command-palette:toggle (atom-pane.pane.active)
     -2:34.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:23.6.0 nuclide-settings:toggle (atom-pane.pane.active)
     -1:15.6.0 find-and-replace:show (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.35 
language-babel 2.85.0 
language-capirca 0.2.0 
language-graphql 1.0.0 
language-haskell 1.19.1 
language-ini 1.21.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.10 
language-swift 0.5.0 
language-thrift 1.0.2 
nuclide 0.498.170655729 
set-syntax 0.4.0 
sort-lines 0.19.0 
tool-bar 1.1.12 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you quit Atom and reinstall to see if that helps?

**Comment by Krinkle** [comment]
I've got the same today. Restarting Atom did not fix the issue.

**Comment by elliotaplant** [comment]
I have  encountered this problem on two different machines on Atom recently (One on Nov 12, 2019, the other on Nov 16, 2019). Both happened after updating packages, but not Atom itself. I was able to get around the issue by clearing the window cache:
```
atom --clear-window-cache
```
Clearing the window cache has the added benefit of significantly speeding up atom if the cache has not been cleared in a while. Hope that helps!
