### ISSUE TITLE
Getting errors in installing any package from atom 

### ISSUE THREAD

**Issue by Kuljeet-123** [atom/atom#19929]
### Description

I  had latest version of atom but can't install any package and getting errors  for installing package

**Actual behavior:**

```
Installing “gpp-compiler@3.0.7” failed.Hide output…
fs.js:143
    throw err;
    ^

Error: ENOENT: no such file or directory, mkdir 'C:\Users\kulje\OneDrive\DOCUME~1\temp\DRAGON~1\DCUPDA~1.XML\apm-install-dir-119819-11836-19ukv3l.1g3'
    at Object.fs.mkdirSync (fs.js:872:3)
    at Object.mkdirSync (C:\Users\kulje\AppData\Local\atom\app-1.40.1\resources\app\apm\node_modules\temp\lib\temp.js:238:6)
    at Install.installModule (C:\Users\kulje\AppData\Local\atom\app-1.40.1\resources\app\apm\lib\install.js:96:35)
    at commands.push (C:\Users\kulje\AppData\Local\atom\app-1.40.1\resources\app\apm\lib\install.js:314:27)
    at fn (C:\Users\kulje\AppData\Local\atom\app-1.40.1\resources\app\apm\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (C:\Users\kulje\AppData\Local\atom\app-1.40.1\resources\app\apm\node_modules\async\lib\async.js:498:34)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)

```
### Versions
Atom:1.40.1

**Comment by rsese** [comment]
Thanks for contributing!

Looks like you're getting the same error as described in https://github.com/atom/apm/issues/866 so you can subscribe there if you'd like.  I'd suggest checking if the linked message board post in https://github.com/atom/apm/issues/866#issuecomment-530260903 helps.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
