### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ZhangKejun** [atom/atom#19944]
1、git clone
2、npm install 、npm audit fix
3、script/bootstrap success
4、script/build failed

error log:

zkjMAC:Atom zkj$ script/build --compress-artifacts
Node:	v10.16.2
Npm:	v6.2.0
Installing script dependencies
Installing apm
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom unknown
python 2.7.10
git 2.20.1
Installing modules ✓
Wrote Dependencies Fingerprint: /Users/zkj/Github/Atom/node_modules/.dependencies-fingerprint f17e743ddcf6d4c8a722d8e7495a4810c48caed7
Cleaning /Users/zkj/Github/Atom/out
Copying assets to /Users/zkj/Github/Atom/out/app
Transpiling packages with custom transpiler configurations in /Users/zkj/Github/Atom/out/app
 transpiling for package github
Installing modules ✗
> superstring@2.3.6 install /Users/zkj/Github/Atom/node_modules/github/node_modules/superstring
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at TLSWrap.onread (net.js:657:25)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/zkj/Github/Atom/apm/node_modules/atom-package-manager/bin/node" "/Users/zkj/Github/Atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/zkj/Github/Atom/node_modules/github/node_modules/superstring
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superstring@2.3.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the superstring@2.3.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zkj/.atom/.apm/_logs/2019-09-23T12_39_39_340Z-debug.log
child_process.js:650
    throw err;
    ^

Error: Command failed: /Users/zkj/Github/Atom/apm/node_modules/atom-package-manager/bin/apm install
  at checkExecSyncError (child_process.js:629:11)
  at Object.execFileSync (child_process.js:647:13)
  at module.exports (/Users/zkj/Github/Atom/script/lib/run-apm-install.js:14:16)
  at module.exports (/Users/zkj/Github/Atom/script/lib/transpile-packages-with-custom-transpiler-paths.js:44:7)
  at Object.<anonymous> (/Users/zkj/Github/Atom/script/build:74:3)
  at Module._compile (internal/modules/cjs/loader.js:778:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
  at Module.load (internal/modules/cjs/loader.js:653:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
  at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
  at startup (internal/bootstrap/node.js:283:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

can you help me? thanks!

**Comment by Arcanemagus** [comment]
You appear to have added several steps of your own to the build process, you should be able to simply follow the [build instructions](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#instructions).

The error you show is coming from a (potentially temporary?) networking issue.

----

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by ZhangKejun** [comment]
1、delete atom 
2、clone again
3、script/bootstrap

error logs:
bash-3.2$ script/bootstrap
Node: v10.16.2
Npm:  v6.11.3
Installing script dependencies
/Users/01388087/ZKJ/Github/Atom/script/node_modules/electron-mksnapshot/download-mksnapshot.js:19
  if (err != null) throw err
                   ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-mksnapshot@4.2.0 install: `node ./download-mksnapshot.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-mksnapshot@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/01388087/.npm/_logs/2019-09-24T01_15_14_984Z-debug.log
child_process.js:650
    throw err;
    ^

Error: Command failed: npm --loglevel=error install
/Users/01388087/ZKJ/Github/Atom/script/node_modules/electron-mksnapshot/download-mksnapshot.js:19
  if (err != null) throw err
                   ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-mksnapshot@4.2.0 install: `node ./download-mksnapshot.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-mksnapshot@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/01388087/.npm/_logs/2019-09-24T01_15_14_984Z-debug.log

    at checkExecSyncError (child_process.js:629:11)
    at Object.execFileSync (child_process.js:647:13)
    at module.exports (/Users/01388087/ZKJ/Github/Atom/script/lib/install-script-dependencies.js:9:16)
    at Object.<anonymous> (/Users/01388087/ZKJ/Github/Atom/script/bootstrap:37:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

what's the problem?
