### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=read ECONNRESET

### ISSUE THREAD

**Issue by Thtuy** [atom/atom#19979]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=read ECONNRESET

```
At internal/streams/legacy.js:57

Error: tunneling socket could not be established, cause=read ECONNRESET
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
```

### Non-Core Packages

```
language-latex 1.2.0 
latex 0.50.2 
pdf-view 0.71.0 
```

**Comment by rsese** [comment]
Thanks for the report! Are you using a network proxy? This seems like it could be a temporary network issue, please try again later and let us know if you continue getting the same error.
