### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.158.100.6:8080

### ISSUE THREAD

**Issue by nitin3685** [atom/atom#20027]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.158.100.6:8080

```
At internal/streams/legacy.js:57

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.158.100.6:8080
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
     -9:03.7.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-python-run 0.9.7 
ide-golang 0.0.5 
ide-python 1.4.2 
remote-atom 1.3.12 
script 3.18.1 
```

**Comment by rsese** [comment]
Thanks for the report - based on the error, maybe this is a temporary issue with your internet connection or proxy? Have you tried again to see if you still get the error?
