### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by matthiasulrich** [atom/atom#20049]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown macOS version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:166

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744622)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744724)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744850)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1087821)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1246932)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1244917)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284329)
```

### Commands

```
  2x -3:27.7.0 multiple-remote-ftp:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:20.5.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:48.7.0 find-and-replace:show (input.hidden-input)
     -0:40.7.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
```

### Non-Core Packages

```
acf-snippets 0.6.2 
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-wordpress 0.3.0 
autoclose-html 0.23.0 
autocomplete-wordpress-hooks 0.2.3 
highlight-selected 0.16.0 
linter 2.3.1 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
multiple-remote-ftp 1.1.0 
print-atom 0.1.1 
remote-ftp 2.2.2 
wordpress-autocomplete 1.5.0 
wordpress-dictionary 4.4.0 
```

**Comment by fallengravity** [comment]
Having the same issue on macOS 10.15

**Comment by rsese** [comment]
Looks like a number of reports recently - it seemed at first to be all people on Catalina (macOS 10.15) but looking again I saw there were a number of reports from people on 10.14.6 e.g. https://github.com/atom/atom/issues/20051 and https://github.com/atom/atom/issues/20066.

For anyone seeing this error, have you seen the error just once or multiple times?  The errors popped up around when 1.41.0 was released so I wonder if it's related to Atom updating.  If you quit and restart Atom, do you still see the error?

If you see the error consistently, can you reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by shockzp** [comment]
After quitting and restarting, the issue doesn't exist on 10.14.6

**Comment by fallengravity** [comment]
Same here it happened whilst downloading the update once it updated & restarted the error stopped happening.

**Comment by Geoyi** [comment]
I saw the same error, and I was about to create an issue but decided to search past issues here. Restart `atom` and the problem seems solved. Thank all.
