### ISSUE TITLE
Uncaught Error: The module '/usr/share/atom/resources/app.asar.unpacked/node_modules/@atom/fuzzy-...

### ISSUE THREAD

**Issue by Foggalong** [atom/atom#20063]
1. Have open a file.
2. Press CTRL+T

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The module '/usr/share/atom/resources/app.asar.unpacked/node_modules/@atom/fuzzy-native/build/Release/fuzzy-native.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

```
At ELECTRON_ASAR.js:166

Error: The module '/usr/share/atom/resources/app.asar.unpacked/node_modules/@atom/fuzzy-native/build/Release/fuzzy-native.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /app.asar/node_modules/@atom/fuzzy-native/lib/main.js:1:173)
    at /app.asar/node_modules/@atom/fuzzy-native/lib/main.js:3:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:688157)
    at get_NativeFuzzy (/usr/share/atom/resources/app/static/<embedded>:14:593455)
    at FuzzyFinderView.subscriptions.add.atom.config.observe.e (/usr/share/atom/resources/app/static/<embedded>:14:597479)
    at Config.observeKeyPath (/usr/share/atom/resources/app/static/<embedded>:11:334261)
    at Config.observe (/usr/share/atom/resources/app/static/<embedded>:11:328743)
    at new FuzzyFinderView (/usr/share/atom/resources/app/static/<embedded>:14:597274)
    at new ProjectView (/usr/share/atom/resources/app/static/<embedded>:11:810942)
    at Object.createProjectView (/usr/share/atom/resources/app/static/<embedded>:11:188411)
    at HTMLElement.fuzzy-finder:toggle-file-finder (/usr/share/atom/resources/app/static/<embedded>:11:186909)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349123)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1249835)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1245969)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:284329)
```

### Commands

```
  2x -9:51.7.0 editor:newline (input.hidden-input)
     -9:51.4.0 core:move-up (input.hidden-input)
     -9:47.3.0 intentions:highlight (input.hidden-input)
     -9:47.1.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -9:46.7.0 editor:select-line (input.hidden-input)
     -9:46.4.0 core:backspace (input.hidden-input)
     -9:46 intentions:highlight (input.hidden-input)
     -9:45.9.0 core:save (input.hidden-input)
     -2:26.8.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
```

### Non-Core Packages

```
atom-language-r 1.4.8 
busy-signal 2.0.1 
intentions 1.1.5 
language-latex 1.2.0 
language-matlab 0.2.1 
latex 0.50.2 
latex-wordcount 0.6.0 
linter 2.3.1 
linter-chktex 1.4.0 
linter-gcc 0.7.1 
linter-pycodestyle 2.1.3 
linter-shellcheck 1.6.0 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-ui-default 1.8.0 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-linter 2.2.1 
pdf-view 0.72.0 
todo-show 2.3.2 
wordcount 3.1.0 
```

**Comment by sbrl** [comment]
For anyone encountering this issue, you probably want to close and open Atom. It should prompt with a red bug icon on the button status bar for you to rebuild.
