### ISSUE TITLE
Uncaught Error: Invalid guestInstanceId: null

### ISSUE THREAD

**Issue by cokar** [atom/atom#20106]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Invalid guestInstanceId: null

```
At C:\Users\Administrator\AppData\Local\atom\app-1.41.0\resources\electron.asar\renderer\api\remote.js:222

Error: Invalid guestInstanceId: null
    at Object.getGuestForWebContents (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/guest-view-manager.js:425:11)
    at ~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/rpc-server.js:444:34
    at EventEmitter.ipcMain.on.args (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
     -2:13.4.0 core:paste (input.hidden-input)
     -2:12.4.0 core:save (input.hidden-input)
 11x -1:59.9.0 core:move-right (input.hidden-input)
  3x -1:57.4.0 core:move-down (input.hidden-input)
  2x -1:56.6.0 core:move-left (input.hidden-input)
     -1:55.9.0 core:move-down (input.hidden-input)
  4x -1:55.7.0 core:move-left (input.hidden-input)
     -1:55 core:move-up (input.hidden-input)
  8x -1:54.8.0 core:move-left (input.hidden-input)
  9x -1:52.2.0 core:save (input.hidden-input)
     -0:53.5.0 atom-browser:preview (span.name.icon.icon-file-text)
     -0:16.3.0 core:backspace (input.hidden-input)
 13x -0:14.8.0 core:move-right (input.hidden-input)
     -0:13.4.0 core:move-left (input.hidden-input)
     -0:12.5.0 core:backspace (input.hidden-input)
     -0:11.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-browser 1.2.0 
atom-simplified-chinese-menu 0.6.5 
emmet 2.4.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

**Comment by vivi90** [comment]
@rsese Here the same issue.
It happens, when i use "ctrl+alt+b".

```
Uncaught Error: Invalid guestInstanceId: null

/usr/lib/electron4/resources/electron.asar/renderer/api/remote.js:222

Error: Invalid guestInstanceId: null
    at Object.getGuestForWebContents (/usr/lib/electron4/resources/electron.asar/browser/guest-view-manager.js:425:11)
    at /usr/lib/electron4/resources/electron.asar/browser/rpc-server.js:444:34
    at EventEmitter.ipcMain.on.args (/usr/lib/electron4/resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/lib/electron4/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)
```

```
[vivien@vivien-nb 4]$ apm --version
apm  2.4.5
npm  6.14.4
node 14.1.0 x64
atom 1.45.0
python 3.8.2
git 2.26.2
[vivien@vivien-nb 4]$ uname -a
Linux vivien-nb 5.6.8-1-MANJARO #1 SMP PREEMPT Wed Apr 29 19:05:17 UTC 2020 x86_64 GNU/Linux
```
