### ISSUE TITLE
Uncaught The "url" argument must be of type string. Received type boolean

### ISSUE THREAD

**Issue by Robocop79** [atom/atom#20150]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught The "url" argument must be of type string. Received type boolean

```
At url.js:150

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type boolean
    at Url.parse (url.js:150:11)
    at Object.urlParse [as parse] (url.js:144:13)
    at URIPattern.matches (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:3000621)
    at RecentCommitsController._defineProperty (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:4086774)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1213350)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:424688)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem.t (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:44396)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1213350)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:447021)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:455865)
    at Pane.activateItem (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:458035)
    at TabBarView.onClick (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1162996)
```

### Commands

```
     -2:07.0 github:toggle-github-tab (ul.list-inline.tab-bar.inset-panel)
     -0:19.5.0 browser-plus:open (div.package-detail)
```

### Non-Core Packages

```
atom-clock 0.1.17 
atom-live-server 2.3.0 
atom-live-server-plus 3.0.1 
browser-plus 0.0.98 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the https://github.com/skandasoft/browser-plus package, not Atom itself (/cc https://github.com/skandasoft/browser-plus/issues/187). It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
