### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by cjwelle** [atom/atom#20158]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.15.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:166

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744622)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744724)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744850)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1087821)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1246932)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1244917)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284329)
```

### Commands

```
  2x -0:05.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
ansible-galaxy 0.2.1 
ansible-snippets 0.2.0 
ansible-vault 0.7.8 
asciidoc-assistant 0.2.3 
asciidoc-image-helper 1.0.1 
asciidoc-preview 2.13.1 
atom-beautify 0.33.4 
atom-cform 0.6.0 
atom-cform-yaml 0.5.1-0 
atom-cli-diff 1.9.0 
atom-debugger 0.1.6 
atom-ide-debugger-node 0.7.3 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-json-color 0.6.0 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-node-debugger 2.1.2 
atom-yamljson 0.2.4 
atomic-chrome 0.3.3 
autocomplete-ansible 0.1.24 
autocomplete-asciidoc 0.1.2 
autocomplete-json 5.5.2 
autocomplete-modules 2.3.0 
autocomplete-python 1.16.0 
autocomplete-xml 0.11.0 
bottom-dock 0.4.4 
busy-signal 2.0.1 
color-picker 2.3.0 
debugger 0.0.1 
editor-stats 0.17.0 
environment 1.3.1 
git-control 0.9.0 
git-controlhub 0.4.0 
git-diff-details 1.4.0 
git-plus 8.7.1 
git-status 0.3.4 
git-time-machine 2.1.0 
github-plus 1.0.0 
ide-yaml 0.5.1 
intentions 1.1.5 
language-ansible 0.2.2 
language-asciidoc 1.11.0 
language-json-comments 0.16.3 
language-yaml-cloudformation 0.3.1 
linter 2.3.1 
linter-js-yaml 1.4.6 
linter-ui-default 1.8.0 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-git-diff 4.3.1 
platformio-ide-terminal 2.10.0 
pretty-json 2.1.2 
project-plus 1.0.0 
project-view 0.6.5 
project-viewer 1.4.0 
ramda-syntax 1.0.4 
sort-lines 0.19.0 
sort-selected-elements 0.1.0 
split-diff 1.6.1 
Sublime-Style-Column-Selection 1.7.5 
sync-settings 0.8.6 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.5.2 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
