### ISSUE TITLE
Uncaught Error: Cannot call function 'setTouchBar' on missing remote object 179

### ISSUE THREAD

**Issue by shinsyotta** [atom/atom#20162]
[Enter steps to reproduce:]

1. ... Open a folder containing https://github.com/ConnextProject's Indra and card repos
2. ... See the issue unfold.

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'setTouchBar' on missing remote object 179

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call function 'setTouchBar' on missing remote object 179
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:148:17)
    at /Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-file-icons 0.7.1 
atom-solidity-linter 0.0.11 
autocomplete-clang 0.12.1 
build 0.70.0 
busy-signal 2.0.1 
clojure-party-repl 1.1.0 
console-panel 0.3.1 
file-icons 2.1.36 
hasklig 0.4.0 
ink 0.11.6 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc 0.7.1 
linter-gcc2 0.8.7 
linter-joker 4.1.0 
linter-ui-default 1.8.0 
lisp-paredit 0.6.0 
monokai 0.24.0 
parinfer 1.23.0 
platformio-ide 2.5.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
proto-repl 1.4.24 
proto-repl-charts 0.4.1 
rainbow-delimiters 2.1.2 
teletype 0.13.4 
tool-bar 1.2.0 
```

**Comment by lkashef** [comment]
Just to confirm my understanding for the reproduction steps, you create a folder and clone `Indra` and `card` repos from [ConnextProject](https://github.com/ConnextProject), then we open that folder in Atom it throws that exception?
