### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.41.0\res...

### ISSUE THREAD

**Issue by rianstephens** [atom/atom#20167]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\Rian Stephens\AppData\Local\atom\app-1.41.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:160

Error: The specified module could not be found.
\\?\C:\Users\Rian Stephens\AppData\Local\atom\app-1.41.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:1:727373)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:2746273)
    at get_manager (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:2746375)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:2746501)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1087039)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1249633)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1247618)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:284598)
```

### Commands

```
```

### Non-Core Packages

```
tidalcycles 3.8.1 
```

**Comment by WilSnoop** [comment]
Hi Rian. 
I am an Atom user attempting to help you conversation move forward.

Have you been using Atom for long? 
Which version did you install originally?

Could you check - Do you have the file `keyboard-layout-manager.node` as specified by your message?

I have seen some issues come up for Windows users that has a user name with the {space} in the user name. Consider using a portable installation as described here:
 https://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode

Make VERY sure that you have the full ZIP file. Sorry, I do not have a file hash to give you for verification.

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
