### ISSUE TITLE
Uncaught AssertionError [ERR_ASSERTION]: 5532 == 0

### ISSUE THREAD

**Issue by a-dera** [atom/atom#20163]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 ia32
**Electron**: 4.2.7
**OS**:  Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught AssertionError [ERR_ASSERTION]: 5532 == 0

```
At assert.js:83

AssertionError [ERR_ASSERTION]: 5532 == 0
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:160:14)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketOnData (_http_client.js:474:11)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Commands

```
     -0:35.4.0 application:add-project-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-runner 2.7.1 
ide-python 1.5.0 
language-rivescript 1.0.0 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
