### ISSUE TITLE
Uncaught TypeError: d.item.getTitle is not a function

### ISSUE THREAD

**Issue by AntonAdigamov** [atom/atom#20179]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: d.item.getTitle is not a function

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: d.item.getTitle is not a function
    at TabView.updateTitle (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:964221)
    at TabBarView.removeTabForItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1154320)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1151774
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1213350)
    at Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:460117)
    at function.e.onDidDestroy.r.add.e.onDidDestroy (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:458742)
    at wrapped (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1212918)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1213350)
    at TextEditor.destroy (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:7180)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:985747
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1213350)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1002885
    at CallbacksRegistry.apply (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/callbacks-registry.js:47:25)
    at handleMessage (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:285:21)
    at EventEmitter.ipcRenderer.on.args (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:275:7)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -9:37.1.0 core:copy (input.hidden-input)
     -9:36.2.0 core:paste (input.hidden-input)
     -9:35.3.0 core:save (input.hidden-input)
  6x -9:04.7.0 core:backspace (input.hidden-input)
     -8:49.3.0 core:confirm (input.input-text.github-CredentialDialog-Password)
     -8:42.1.0 github:pull (span.)
  2x -8:36.4.0 core:confirm (input.input-text.github-CredentialDialog-Password)
     -5:00.5.0 core:copy (input.hidden-input)
  2x -1:11.3.0 core:confirm (input.input-text.github-CredentialDialog-Password)
     -0:12.9.0 tree-view:remove (li.file.entry.list-item.selected)
```

### Non-Core Packages

```
atom-meld 0.3.5 
better-git-blame 0.4.7 
busy-signal 2.0.1 
compare-files 0.8.1 
highlight-selected 0.16.0 
intentions 1.1.5 
language-rspec 0.12.1 
linter 2.3.1 
linter-rubocop 2.5.3 
linter-ruby 1.3.1 
linter-spell-ruby 0.4.0 
linter-swagger 0.6.1 
linter-ui-default 1.8.0 
merge-conflicts 1.4.5 
platformio-ide-terminal 2.10.0 
rubocop-auto-correct 1.5.1 
ruby-block 0.3.6 
teletype 0.13.4 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
