### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 5666Error: Cannot ca...

### ISSUE THREAD

**Issue by taoualiw** [atom/atom#20193]
[Enter steps to reproduce:]

1. installed git-merge add-on
2. tried to merge a local branch into another

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 5666
Error: Cannot call function 'getPosition' on missing remote object 5666
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 5666
Error: Cannot call function 'getPosition' on missing remote object 5666
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:705396)
    at AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:705811)
    at WindowEventHandler.handleWindowResize (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285420)
    at l (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1197399)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.14.1 
busy-signal 2.0.1 
compare-files 0.8.1 
django-templates 0.5.0 
docblock-python 0.15.0 
file-icons 2.1.33 
git-merge 0.4.1 
git-time-machine 2.1.0 
highlight-selected 0.16.0 
intentions 1.1.5 
language-restructuredtext 1.1.2 
linter 2.3.0 
linter-flake8 2.4.0 
linter-python-pep8 0.2.0 
linter-ui-default 1.7.1 
material-colors 0.1.0 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
pandoc 0.2.2 
python-autopep8 0.1.3 
python-debugger 0.2.0 
python-indent 1.2.3 
python-tools 0.6.9 
script 3.18.1 
split-diff 1.6.0 
terminal-plus 0.14.5 
```

**Comment by sadick254** [comment]
Thank you for opening this issue. This was issue present in electron versions 4 and below. The latest atom version `v1.51.0` uses electron version `5.0.3`. The issue was fixed on this commit https://github.com/electron/electron/commit/a8f2646ba682d65f94ea628ac11b1a5521bcedcd. The fix has been available from electron version `5.0.0`. I would advice you to upgrade to the latest atom version. I am closing this for now but happy to reopen if you still experience the issue.
