### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/ MD 21046'

### ISSUE THREAD

**Issue by YoungSwiftling** [atom/atom#20192]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/ MD 21046'

```
At fs.js:143

Error: ENOENT: no such file or directory, lstat '/ MD 21046'
    at Proxy.realpathSync (fs.js:1744:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:335:40)
    at TreeView.moveEntry (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1009292)
    at TreeView.onDrop (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1016221)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:989852)
```

### Commands

```
  5x -6:42.3.0 core:backspace (input.hidden-input)
     -1:51.9.0 core:copy (input.hidden-input)
     -1:43.8.0 tree-view:move (span.name.icon.icon-file-text)
     -1:42.9.0 core:paste (input.hidden-input)
     -1:35.9.0 core:confirm (input.hidden-input)
     -1:26.6.0 core:move-up (input.hidden-input)
     -1:14.3.0 core:delete (input.hidden-input)
     -1:13 core:save (input.hidden-input)
     -1:07.9.0 tree-view:add-folder (div.tool-panel.tree-view)
     -0:59.9.0 core:confirm (input.hidden-input)
     -0:53.5.0 tree-view:remove (span.name.icon.icon-file-directory)
     -0:42.6.0 tree-view:add-file (div.header.list-item)
     -0:29.8.0 core:confirm (input.hidden-input)
     -0:12.3.0 core:save (div.tool-panel.tree-view)
```

### Non-Core Packages

```
git-plus 8.7.1 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
