### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 737Error: Cannot cal...

### ISSUE THREAD

**Issue by tealikes** [atom/atom#20205]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 737
Error: Cannot call function 'getPosition' on missing remote object 737
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 737
Error: Cannot call function 'getPosition' on missing remote object 737
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app/static/<embedded>:1:705395)
    at AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app/static/<embedded>:1:705810)
    at WindowEventHandler.handleWindowBlur (/usr/share/atom/resources/app/static/<embedded>:11:285354)
```

### Commands

```
  2x -6:47.6.0 editor:newline (input.hidden-input)
     -6:43.8.0 core:backspace (input.hidden-input)
     -6:42.3.0 core:paste (div.line.cursor-line)
  5x -6:38.3.0 core:undo (input.hidden-input)
     -6:31.4.0 core:redo (input.hidden-input)
 10x -6:30.4.0 core:undo (input.hidden-input)
     -4:08.6.0 core:copy (span.syntax--entity.syntax--other.syntax--attribute-name)
  2x -3:56.7.0 editor:newline (input.hidden-input)
     -3:51 core:paste (div.line.cursor-line)
     -3:24.7.0 editor:indent-selected-rows (input.hidden-input)
  9x -2:54.3.0 core:backspace (input.hidden-input)
     -2:05.6.0 core:move-left (input.hidden-input)
     -1:47.8.0 core:backspace (input.hidden-input)
     -1:12.4.0 core:cut (span.syntax--support.syntax--type.syntax--property-name.syntax--css)
     -1:08.9.0 tree-view:remove (span.name.icon.icon-file-text)
     -0:56.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autocomplete 0.47.0 
autocomplete-modules 2.3.0 
autocomplete-paths 2.12.2 
autosave-onchange 1.5.1 
busy-signal 2.0.1 
double-tag 1.7.0 
emmet 2.4.3 
goto-definition 1.3.4 
highlight-selected 0.16.0 
intentions 1.1.5 
language-babel 2.85.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.0 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
prettier-atom 0.58.2 
```

**Comment by sadick254** [comment]
Thank you for opening this issue. This was issue present in electron versions 4 and below. The latest atom version `v1.51.0` uses electron version `5.0.3`. The issue was fixed on this commit https://github.com/electron/electron/commit/a8f2646ba682d65f94ea628ac11b1a5521bcedcd. The fix has been available from electron version `5.0.0`. I would advice you to upgrade to the latest atom version. I am closing this for now but happy to reopen if you still experience the issue.
