### ISSUE TITLE
Failed to load the remote-edit2 package

### ISSUE THREAD

**Issue by elaubmey** [atom/atom#20209]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: K142N104
**Thrown From**: 'remote-edit2' package vundefined

### Stack Trace

Failed to load the remote-edit2 package

```
At The "path" argument must be of type string. Received type undefined

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:166:7)
    at /packages/remote-edit2/lib/model/remote-edit-editor.coffee:7:36)
    at /packages/remote-edit2/lib/model/remote-edit-editor.coffee:1:1)
    at /packages/remote-edit2/lib/model/remote-edit-editor.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/remote-edit2/lib/main.coffee:3:20)
    at /packages/remote-edit2/lib/main.coffee:1:1)
    at /packages/remote-edit2/lib/main.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:1:727373)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3325206)
    at measure (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3311746)
    at Package.measure (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3310578)
    at Package.load (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3311319)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:381128)
    at config.transact (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:379551)
    at Config.transact (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:331616)
```

### Commands

```
     -0:06.5.0 ftp-remote-edit:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
Atom-SFTP-sync 2.0.1 
hyperclick 0.0.0 
ide-html 0.6.0 
intentions 1.1.5 
php-ide-serenata 5.1.0 
remote-edit2 3.0.0 
```

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [remote-edit2](https://atom.io/packages/remote-edit2) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
