### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by alexmantovani** [atom/atom#20222]
[Enter steps to reproduce:]

1. Open a .blade.php file
2. Error appears and is not possible write any text

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:166

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744622)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744724)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744850)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1087821)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1246932)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1244917)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284329)
```

### Commands

```
```

### Non-Core Packages

```
atom-commander 0.12.0 
atom-ide-ui 0.13.0 
atom-typescript 13.4.0 
blade-snippets 0.2.0 
blade-spacer 0.4.2 
editorconfig 2.5.0 
language-blade 0.44.0 
laravel 0.7.1 
laravel-5-snippets 0.19.0 
laravel-snippets 2.1.0 
remote-ftp 2.2.2 
```

**Comment by Hashfyre** [comment]
[Enter steps to reproduce:]

1. Update go-plus
2. Restart atom

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:166

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744622)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744724)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744850)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1087821)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1246932)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1244917)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284329)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
busy-signal 2.0.1 
file-icons 2.1.36 
firewatch-syntax 1.1.1 
go-debug 1.7.0 
go-plus 6.1.0 
go-signature-statusbar 1.2.3 
intentions 1.1.5 
language-docker 1.1.8 
language-jsonnet 0.1.0 
language-terraform 0.8.1 
linter 2.3.1 
linter-ansible-linting 1.5.0 
linter-ui-default 1.8.0 
nms-color-bracket 0.1.0 
rainbow-delimiters 2.1.2 
release-notes 0.53.0 
sync-settings 0.8.6 
terraform-fmt 0.3.0 
todo-show 2.3.2 
tool-bar 1.2.0 
tree-view-git-status 1.5.2 
```

**Comment by axelpale** [comment]
Same happened to me while creating a new folder in tree view. After that the error reappeared every time I pressed CMD-button. However, I cannot reproduce this after restarting Atom.

**Atom:** 1.42.0 x64
**Electron:** 4.2.7
**OS:** MacOS 10.14.6

**Comment by ThatXliner** [comment]
And..... after all the duplicates.... does it still reproduce?

**Comment by icecream17** [comment]
I wonder if this issue happens with several different modules or just one module
It would be easier to debug if the error message was better - maybe `Module <name> did not self-register`
Relevant stackoverflow post: https://stackoverflow.com/questions/28486891/uncaught-error-module-did-not-self-register
Maybe this is about n-api: https://stackoverflow.com/questions/47675931/nodejs-and-n-api

Also there are so many duplicates. Maybe there should be a "duplicate" tag
Duplicate finder: https://github.com/atom/atom/issues?q=is%3Aissue+is%3Aopen+Module+did+not+self+register
