### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 103

### ISSUE THREAD

**Issue by yujfujita** [atom/atom#20220]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 103

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 103
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:148:17)
    at /Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
     -8:11.3.0 tree-view:remove (span.name.icon.icon-file-directory)
     -7:56.5.0 tree-view:copy-project-path (span.name.icon.icon-file-directory)
     -7:46.9.0 core:paste (input.hidden-input)
     -7:31.4.0 tree-view:copy-project-path (span.name.icon.icon-file-text)
     -6:57.1.0 core:paste (input.hidden-input)
 26x -6:52.7.0 core:backspace (input.hidden-input)
     -6:46.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
busy-signal 2.0.1 
intentions 1.1.5 
language-restructuredtext 1.1.2 
linter 2.3.1 
linter-ui-default 1.8.0 
pandoc-convert 1.1.1 
platformio-ide-terminal 2.10.0 
rst-preview-pandoc 0.1.12 
rubocop-auto-correct 1.5.1 
ruby-block 0.3.6 
```

**Comment by sadick254** [comment]
Thank you for opening this issue. This was issue present in electron versions 4 and below. The latest atom version `v1.51.0` uses electron version `5.0.3`. The issue was fixed on this commit https://github.com/electron/electron/commit/a8f2646ba682d65f94ea628ac11b1a5521bcedcd. The fix has been available from electron version `5.0.0`. I would advice you to upgrade to the latest atom version. I am closing this for now but happy to reopen if you still experience the issue.
