### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Desktop/Login System (Node, MySQL)/ M...

### ISSUE THREAD

**Issue by Artideusz** [atom/atom#20225]
[Enter steps to reproduce:]

1. Create a folder inside a folder in atom.
2. Try to move it a level down.

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Linux Mint
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/artideusz/Desktop/Login System (Node, MySQL)/ MySQL)'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat '/home/artideusz/Desktop/Login System (Node, MySQL)/ MySQL)'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (/usr/share/atom/resources/app/static/<embedded>:14:1008489)
    at TreeView.onDrop (/usr/share/atom/resources/app/static/<embedded>:14:1015418)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:989049)
```

### Commands

```
     -2:37.6.0 snippets:next-tab-stop (input.hidden-input)
     -2:37.6.0 snippets:expand (input.hidden-input)
     -2:37.6.0 editor:indent (input.hidden-input)
  2x -2:37.1.0 core:backspace (input.hidden-input)
     -2:36.7.0 snippets:next-tab-stop (input.hidden-input)
     -2:36.6.0 snippets:expand (input.hidden-input)
     -2:36.6.0 editor:indent (input.hidden-input)
     -2:36.5.0 snippets:next-tab-stop (input.hidden-input)
     -2:36.5.0 snippets:expand (input.hidden-input)
     -2:36.5.0 editor:indent (input.hidden-input)
 19x -2:36.3.0 core:backspace (input.hidden-input)
     -2:31.6.0 tree-view:remove (div.tool-panel.tree-view)
     -1:52.9.0 core:save (div.tool-panel.tree-view)
  4x -0:51.3.0 core:backspace (input.hidden-input)
     -0:19.4.0 tree-view:add-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:17.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ternjs 0.20.0 
emmet 2.4.3 
hyperclick 0.1.5 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
