### ISSUE TITLE
Unable to transform source code for module 

### ISSUE THREAD

**Issue by darangi** [atom/atom#20236]
### Description
I am currently working on https://github.com/atom/atom/pull/20172, when I  execute `script/build` I get the following errors.
```
 (91)Unable to transform source code for module /Users/musaibrahim/Projects/github/atom20034/atom/out/app/node_modules/parse5/lib/parser/parser_stream.js.
Error: /Users/musaibrahim/Projects/github/atom20034/atom/out/app/node_modules/parse5/lib/parser/parser_stream.js
Cannot replace with lazy function because the supplied node does not belong to an assignment expression or a variable declaration!
  at FileRequireTransform.replaceAssignmentOrDeclarationWithLazyFunction (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/lib/file-require-transform.js:189:11)
  at Context.visitIdentifier (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/lib/file-require-transform.js:81:18)
  at Context.invokeVisitorMethod (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:284:51)
  at Visitor.PVp.visitWithoutReset (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:159:32)
  at visitChildren (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:205:25)
  at Visitor.PVp.visitWithoutReset (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:168:20)
  at visitChildren (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:205:25)
  at Visitor.PVp.visitWithoutReset (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:168:20)
  at NodePath.each (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path.js:89:26)
  at visitChildren (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:180:18)
  at Visitor.PVp.visitWithoutReset (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:168:20)
  at visitChildren (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:205:25)
  at Visitor.PVp.visitWithoutReset (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:168:20)
  at visitChildren (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:205:25)
  at Visitor.PVp.visitWithoutReset (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:168:20)
  at Visitor.PVp.visit (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:106:29)
  at Object.visit (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:82:55)
  at FileRequireTransform.replaceDeferredRequiresWithLazyFunctions (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/lib/file-require-transform.js:77:20)
  at FileRequireTransform.apply (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/lib/file-require-transform.js:34:10)
  at /Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:55:56
  at Generator.next (<anonymous>:null:null)
  at step (/Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:191)
  at /Users/musaibrahim/Projects/github/atom20034/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:361
```
I believe something similar was reported early this year here https://github.com/atom/atom/issues/19328

**Comment by darangi** [comment]
@lee-dohm, @jasonrudolph have you seen this one before?

**Comment by jasonrudolph** [comment]
@darangi: I don't recall running into anything like this before. Sorry, man. 😬

**Comment by darangi** [comment]
@jasonrudolph Thanks! 😅

**Comment by smashwilson** [comment]
This is likely caused by an npm dependency that can't be included directly in the v8 snapshot:

```
Error: /Users/musaibrahim/Projects/github/atom20034/atom/out/app/node_modules/parse5/lib/parser/parser_stream.js
```

The easiest fix is to exclude `parse5` from the snapshot script by adding a pattern to the list here: 

https://github.com/atom/atom/blob/25015f1cc03a2aad600f8245c0329d37107e52a1/script/lib/generate-startup-snapshot.js#L47-L238

**Comment by smashwilson** [comment]
It would also be interesting to know how and why this dependency was added or updated in the course of the Electron upgrade. It would be odd if it was present before and electron-link was able to snapshot it.

**Comment by smashwilson** [comment]
Oh, you already have `index.js` excluded here:

https://github.com/atom/atom/blob/3bf17ac0045ce0bd462b63816cebab4a229e6623/script/lib/generate-startup-snapshot.js#L122

Looks like you'd need to add the `parse5/lib/parser/parser_stream.js` entrypoint as well.

**Comment by darangi** [comment]
Let me add that and see 👍

**Comment by darangi** [comment]
I added it to the list, I get the following error after executing `script/build --compress-artifacts`
```
Compressing "/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app" to "/Users/musaibrahim/Projects/github/atom20034/atom/out/atom-mac.zip"
Error: spawnSync zip ENOBUFS
  at Object.spawnSync (internal/child_process.js:1041:20)
  at Object.spawnSync (child_process.js:607:24)
  at module.exports (/Users/musaibrahim/Projects/github/atom20034/atom/script/lib/spawn-sync.js:10:41)
  at compress (/Users/musaibrahim/Projects/github/atom20034/atom/script/lib/compress-artifacts.js:64:3)
  at module.exports (/Users/musaibrahim/Projects/github/atom20034/atom/script/lib/compress-artifacts.js:12:3)
  at /Users/musaibrahim/Projects/github/atom20034/atom/script/build:148:9

Musa-Ibrahims-MacBook-Pro:atom musaibrahim$ 
```
This same error happens on the CI too

**Comment by darangi** [comment]
https://github.visualstudio.com/Atom/_build/results?buildId=56356&view=results

**Comment by smashwilson** [comment]
That's a different problem. Looks like the `childProcess.spawn` call used to call `zip` can't allocate enough memory?

**Comment by darangi** [comment]
I will try to increase the maxBuffer and see if that solves the problem

**Comment by darangi** [comment]
@smashwilson, increasing the maxBuffer fixed that the problem 😄  . I will go ahead and close this issue
