### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 140Error: Cannot cal...

### ISSUE THREAD

**Issue by TexterX** [atom/atom#20231]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Linux Mint
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 140
Error: Cannot call function 'getPosition' on missing remote object 140
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 140
Error: Cannot call function 'getPosition' on missing remote object 140
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app/static/<embedded>:1:705395)
    at AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app/static/<embedded>:1:705810)
    at WindowEventHandler.handleWindowBlur (/usr/share/atom/resources/app/static/<embedded>:11:285354)
```

### Commands

```
     -7:24.4.0 intentions:highlight (input.hidden-input)
     -7:24.2.0 core:paste (input.hidden-input)
 11x -7:15 core:backspace (input.hidden-input)
  2x -1:10.5.0 intentions:highlight (input.hidden-input)
     -1:10 core:copy (input.hidden-input)
     -1:09.1.0 intentions:highlight (input.hidden-input)
     -1:08.8.0 core:cut (input.hidden-input)
  2x -1:07.6.0 editor:newline (input.hidden-input)
     -1:06.0 intentions:highlight (input.hidden-input)
     -1:05.9.0 core:paste (input.hidden-input)
  9x -1:02.1.0 core:backspace (input.hidden-input)
  2x -0:27.5.0 core:move-right (input.hidden-input)
     -0:21.8.0 autocomplete-plus:confirm (input.hidden-input)
     -0:21 core:backspace (input.hidden-input)
     -0:18.4.0 intentions:highlight (input.hidden-input)
     -0:18.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-file-icons 0.7.1 
atom-python-run 0.9.7 
atom-python-virtualenv 1.0.4 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
click-link 1.0.11 
color-picker 2.3.0 
goto-definition 1.3.4 
Hydrogen 2.13.1 
ide-vue 0.1.9 
indent-guide-improved 1.4.13 
intentions 1.1.5 
kite 0.175.0 
language-vue 0.25.0 
linter 2.3.1 
linter-python 3.1.2 
linter-ui-default 1.8.0 
minimap-split-diff 0.3.7 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
script 3.25.0 
split-diff 1.6.1 
```

**Comment by sadick254** [comment]
Thank you for opening this issue. This was issue present in electron versions 4 and below. The latest atom version `v1.51.0` uses electron version `5.0.3`. The issue was fixed on this commit https://github.com/electron/electron/commit/a8f2646ba682d65f94ea628ac11b1a5521bcedcd. The fix has been available from electron version `5.0.0`. I would advice you to upgrade to the latest atom version. I am closing this for now but happy to reopen if you still experience the issue.
