### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\csslint\README.md'

### ISSUE THREAD

**Issue by gargeesuresh** [atom/atom#20230]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\gargi\.atom\packages\csslint\README.md'

```
At fs.js:115

Error: ENOENT: no such file or directory, open 'C:\Users\gargi\.atom\packages\csslint\README.md'
    at Object.openSync (fs.js:436:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
    at Proxy.readFileSync (fs.js:341:35)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:580:40)
    at PackageDetailView.renderReadme (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:829164)
    at PackageDetailView.updateInstalledState (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:828924)
    at PackageDetailView.populate (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:827476)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:822816)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:823028)
    at ~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:829779
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1213350)
    at PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:942948)
    at ~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:940080
    at r (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:934610)
    at n (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1128190)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1128396)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
     -6:21 command-palette:toggle (div.panels-item)
     -5:52.4.0 core:paste (input.hidden-input)
     -5:51.1.0 atom-beautify:help-debug-editor (div.panels-item)
     -4:49 core:backspace (input.hidden-input)
     -1:13.1.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
```

**Comment by darangi** [comment]
Thanks for reporting this!

This has already been fixed on `master`. It is currently scheduled for release when `v1.53.0` reaches Stable.
