### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 812

### ISSUE THREAD

**Issue by rd3v** [atom/atom#20240]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 812

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 812
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:148:17)
    at /usr/share/atom/resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
  5x -0:58.3.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:56.8.0 core:backspace (input.hidden-input)
     -0:56.4.0 core:move-down (input.hidden-input)
     -0:55.7.0 core:save (input.hidden-input)
     -0:55.2.0 editor:move-to-end-of-word (input.hidden-input)
     -0:33.4.0 core:move-left (input.hidden-input)
 11x -0:33.2.0 core:move-right (input.hidden-input)
     -0:32.3.0 core:move-down (input.hidden-input)
  2x -0:32.2.0 core:move-left (input.hidden-input)
     -0:31.7.0 editor:select-to-beginning-of-word (input.hidden-input)
  3x -0:27.4.0 core:save (input.hidden-input)
     -0:13.6.0 editor:move-to-beginning-of-word (input.hidden-input)
     -0:13.3.0 core:move-up (input.hidden-input)
  4x -0:13.1.0 editor:move-to-end-of-word (input.hidden-input)
     -0:12.1.0 find-and-replace:select-next (input.hidden-input)
     -0:11 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-xterm 6.5.0 
emmet 2.4.3 
```

**Comment by sadick254** [comment]
Thank you for opening this issue. This was issue present in electron versions 4 and below. The latest atom version `v1.51.0` uses electron version `5.0.3`. The issue was fixed on this commit https://github.com/electron/electron/commit/a8f2646ba682d65f94ea628ac11b1a5521bcedcd. The fix has been available from electron version `5.0.0`. I would advice you to upgrade to the latest atom version. I am closing this for now but happy to reopen if you still experience the issue.
