### ISSUE TITLE
Multiple install issues on 1.41.0 (Linux 64bit).

### ISSUE THREAD

**Issue by aaj1** [atom/atom#20251]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Install issues with multiple APM packages. Please see the below for detail:
https://github.com/platformio/platformio-atom-ide-terminal/issues/812

Occurs also with terminal-plus 0.14.5 (but missing module is different):
```
Installing “terminal-plus@0.14.5” failed.Hide output…

> pty.js@0.3.0 install /tmp/apm-install-dir-1191117-6697-1ckqoxj.7grd/node_modules/terminal-plus/node_modules/pty.js
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> pty.js@0.3.0 postinstall /tmp/apm-install-dir-1191117-6697-1ckqoxj.7grd/node_modules/terminal-plus/node_modules/pty.js
> node scripts/post-install.js


sh: builderror.log: Brak dostępu
internal/modules/cjs/loader.js:964
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-1191117-6697-1ckqoxj.7grd/node_modules/terminal-plus/node_modules/pty.js/scripts/post-install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-1191117-6697-1ckqoxj.7grd/package.json'
npm WARN apm-install-dir-1191117-6697-1ckqoxj.7grd No description
npm WARN apm-install-dir-1191117-6697-1ckqoxj.7grd No repository field.
npm WARN apm-install-dir-1191117-6697-1ckqoxj.7grd No README data
npm WARN apm-install-dir-1191117-6697-1ckqoxj.7grd No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pty.js@0.3.0 postinstall: `node scripts/post-install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /aaj/.atom/.apm/_logs/2019-12-17T16_48_00_745Z-debug.log
```
and atom-ide-terminal 5.0.1 doesn't install either:
```
Installing “atom-ide-terminal@5.0.1” failed.Hide output…

> node-pty-prebuilt@0.7.6 install /tmp/apm-install-dir-1191117-7201-cbdps2.8pfxd/node_modules/atom-ide-terminal/node_modules/node-pty-prebuilt
> prebuild-install || node scripts/install.js


internal/modules/cjs/loader.js:964
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-1191117-7201-cbdps2.8pfxd/node_modules/atom-ide-terminal/node_modules/node-pty-prebuilt/package.json'
Require stack:
- /usr/lib64/node_modules/prebuild-install/node_modules/napi-build-utils/index.js
- /usr/lib64/node_modules/prebuild-install/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib64/node_modules/prebuild-install/node_modules/napi-build-utils/index.js:5:11)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib64/node_modules/prebuild-install/node_modules/napi-build-utils/index.js',
    '/usr/lib64/node_modules/prebuild-install/bin.js'
  ]
}
internal/modules/cjs/loader.js:964
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-1191117-7201-cbdps2.8pfxd/node_modules/atom-ide-terminal/node_modules/node-pty-prebuilt/scripts/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-1191117-7201-cbdps2.8pfxd/package.json'
npm WARN apm-install-dir-1191117-7201-cbdps2.8pfxd No description
npm WARN apm-install-dir-1191117-7201-cbdps2.8pfxd No repository field.
npm WARN apm-install-dir-1191117-7201-cbdps2.8pfxd No README data
npm WARN apm-install-dir-1191117-7201-cbdps2.8pfxd No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /aaj/.atom/.apm/_logs/2019-12-17T16_53_48_536Z-debug.log
```
### Steps to Reproduce

Listed here:
https://github.com/platformio/platformio-atom-ide-terminal/issues/812

**Expected behavior:**
Package should install without issues.

**Actual behavior:**
Package throws an error claiming a module cannot be found.

**Reproduces how often:**
Always.

### Versions
```
> atom --version
Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```
```
> apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0
python 2.7.17
git 2.24.1
```

**Comment by aaj1** [comment]
Hi, you need to be cautious on the permissions of atom files/dirs. I extracted those from root and the permissions were as in the tarball. The following fixed the described issue.
```
cd $HOME/atom
sudo chown -R $USER:$USER .
```
