### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/ JIRA - Original'

### ISSUE THREAD

**Issue by marcelomrwin** [atom/atom#20262]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/ JIRA - Original'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat '/ JIRA - Original'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1005252)
    at TreeView.onDrop (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1012181)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:985812)
```

### Commands

```
     -6:39.7.0 editor:move-to-first-character-of-line (input.hidden-input)
     -6:39.5.0 core:backspace (input.hidden-input)
  4x -6:39.2.0 core:move-up (input.hidden-input)
     -6:38.5.0 core:move-down (input.hidden-input)
     -6:38.2.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -6:37.9.0 core:select-down (input.hidden-input)
     -6:37.4.0 core:select-up (input.hidden-input)
     -6:37 editor:select-to-end-of-line (input.hidden-input)
     -6:36.7.0 core:delete (input.hidden-input)
     -6:36.5.0 editor:move-to-first-character-of-line (input.hidden-input)
     -6:36.2.0 core:backspace (input.hidden-input)
     -6:26.3.0 core:save (input.hidden-input)
     -0:29.6.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:24 core:confirm (input.hidden-input)
     -0:19.1.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:16.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.3.0 
formatter-json 1.0.1 
ide-json 0.2.1 
ide-vue 0.1.9 
language-ansible 0.2.2 
language-docker 1.1.8 
language-groovy 0.7.0 
language-jenkinsfile 0.1.1 
language-vue-component 0.5.0 
pretty-json 2.1.2 
tabs-to-spaces 1.0.5 
xml-formatter 0.13.0 
```

**Comment by darangi** [comment]
Thanks for reporting this!

This has already been fixed on `master`. It is currently scheduled for release when `v1.53.0` reaches Stable.
