### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 5332

### ISSUE THREAD

**Issue by dpew** [atom/atom#20272]
[Enter steps to reproduce:]

Not sure ...
1. Saved file (ctrl-s)
2. Changed focus to my terminal
3. Error appeared

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 16.04.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 5332

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 5332
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:148:17)
    at /usr/share/atom/resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
     -0:35.9.0 editor:indent (input.hidden-input)
     -0:34.5.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:34 editor:newline (input.hidden-input)
     -0:32 editor:consolidate-selections (input.hidden-input)
     -0:32 core:cancel (input.hidden-input)
     -0:31.8.0 core:move-down (input.hidden-input)
     -0:30.5.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:30 core:backspace (input.hidden-input)
     -0:29.1.0 core:save (input.hidden-input)
  7x -0:28.6.0 core:move-up (input.hidden-input)
  8x -0:27.3.0 core:move-down (input.hidden-input)
  3x -0:25.8.0 core:move-up (input.hidden-input)
     -0:24.5.0 core:save (input.hidden-input)
  2x -0:24.1.0 core:move-up (input.hidden-input)
 13x -0:22.5.0 core:move-down (input.hidden-input)
  4x -0:21.2.0 core:move-up (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by sadick254** [comment]
Thank you for opening this issue. This was issue present in electron versions 4 and below. The latest atom version `v1.51.0` uses electron version `5.0.3`. The issue was fixed on this commit https://github.com/electron/electron/commit/a8f2646ba682d65f94ea628ac11b1a5521bcedcd. The fix has been available from electron version `5.0.0`. I would advice you to upgrade to the latest atom version. I am closing this for now but happy to reopen if you still experience the issue.
