### ISSUE TITLE
Uncaught Error: Cannot call function 'emit' on missing remote object 524

### ISSUE THREAD

**Issue by ferenczAndras** [atom/atom#20295]
1. Right Click -> Rename Xml File
2. Rename & Hit Enter

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'emit' on missing remote object 524

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call function 'emit' on missing remote object 524
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:148:17)
    at /Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
     -9:36.7.0 editor:newline (input.hidden-input)
     -9:36.3.0 core:move-up (input.hidden-input)
     -9:35.9.0 editor:newline (input.hidden-input)
     -9:35.8.0 core:paste (input.hidden-input)
     -9:35.3.0 core:save (input.hidden-input)
 10x -1:31.2.0 core:copy (input.hidden-input)
  2x -1:21.2.0 editor:newline (input.hidden-input)
     -1:20.7.0 core:paste (input.hidden-input)
     -1:20.2.0 core:save (input.hidden-input)
     -1:18.5.0 core:backspace (input.hidden-input)
     -1:18.2.0 core:save (input.hidden-input)
     -0:15.2.0 tree-view:move (span.name.icon.icon-file-text)
     -0:14.2.0 core:move-right (input.hidden-input)
     -0:11.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by lkashef** [comment]
Hey @ferenczAndras, thanks for the report.

Could you please elaborate more on the steps to reproduce?

Also if you are working on an existing project, are you able to reproduce on a new clean project or a single file open?
