### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined 

### ISSUE THREAD

**Issue by divyanshk7** [atom/atom#20291]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Parrot GNU/Linux
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At /usr/share/atom/resources/app/static/<embedded>:14

TypeError: Cannot read property 'version' of undefined
    at /usr/share/atom/resources/app/static/<embedded>:14:2932564
    at /usr/share/atom/resources/app/static/<embedded>:11:914600
    at r (/usr/share/atom/resources/app/static/<embedded>:11:911606)
    at o (/usr/share/atom/resources/app/static/<embedded>:14:1037724)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1037878)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1036480)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-runner 2.7.1 
platformio-ide-terminal 2.10.0 
```

**Comment by klester89** [comment]
at /usr/share/atom/resources/app/static/<embedded>:11:914600

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
