### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 133

### ISSUE THREAD

**Issue by hemanthsunny** [atom/atom#20303]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 133

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 133
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:148:17)
    at /usr/share/atom/resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
     -2:06.1.0 core:confirm (input.hidden-input)
     -2:03.9.0 editor:consolidate-selections (input.hidden-input)
     -2:03.9.0 core:cancel (input.hidden-input)
     -2:02.6.0 core:move-right (input.hidden-input)
  9x -2:02.4.0 core:move-down (input.hidden-input)
 25x -1:59.7.0 core:move-left (input.hidden-input)
     -1:58.1.0 intentions:highlight (input.hidden-input)
     -1:58 find-and-replace:select-next (input.hidden-input)
     -1:54.8.0 core:move-right (input.hidden-input)
     -1:52.1.0 core:backspace (input.hidden-input)
 10x -1:47.6.0 core:move-right (input.hidden-input)
 10x -1:46.2.0 core:move-left (input.hidden-input)
  4x -1:44.6.0 core:select-left (input.hidden-input)
 11x -1:42.2.0 core:move-right (input.hidden-input)
     -1:09.7.0 intentions:highlight (input.hidden-input)
     -1:09.5.0 core:move-to-bottom (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 2.0.1 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.8.0 
platformio-ide-terminal 2.10.0 
prettier-atom 0.58.2 
```

**Comment by sadick254** [comment]
Thank you for opening this issue. This was issue present in electron versions 4 and below. The latest atom version `v1.51.0` uses electron version `5.0.3`. The issue was fixed on this commit https://github.com/electron/electron/commit/a8f2646ba682d65f94ea628ac11b1a5521bcedcd. The fix has been available from electron version `5.0.0`. I would advice you to upgrade to the latest atom version. I am closing this for now but happy to reopen if you still experience the issue.
