### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 178

### ISSUE THREAD

**Issue by andrew-davie** [atom/atom#20316]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 178

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 178
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:148:17)
    at /Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
     -6:54.7.0 core:move-down (input.hidden-input)
     -6:54.5.0 core:move-left (input.hidden-input)
 11x -6:54.1.0 core:move-down (input.hidden-input)
     -6:52.8.0 core:move-left (input.hidden-input)
     -6:52.2.0 core:move-down (input.hidden-input)
     -6:52.2.0 core:move-left (input.hidden-input)
     -6:50.5.0 intentions:highlight (input.hidden-input)
     -6:50.3.0 build:trigger (input.hidden-input)
  4x -5:50.3.0 core:undo (input.hidden-input)
     -4:00.8.0 intentions:highlight (input.hidden-input)
     -4:00.5.0 build:trigger (input.hidden-input)
     -1:54.4.0 core:move-right (input.hidden-input)
     -1:53.8.0 core:select-down (input.hidden-input)
     -1:53.5.0 core:backspace (input.hidden-input)
     -1:52.3.0 intentions:highlight (input.hidden-input)
     -1:52 build:trigger (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.12.1 
build 0.70.0 
build-make 0.13.0 
busy-signal 2.0.1 
file-icons 2.1.37 
intentions 1.1.5 
language-65asm 10.3.0 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc2 0.8.8 
linter-ui-default 1.8.0 
platformio-ide 2.6.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
tool-bar 1.2.0 
```

**Comment by sadick254** [comment]
Thank you for opening this issue. This was issue present in electron versions 4 and below. The latest atom version `v1.51.0` uses electron version `5.0.3`. The issue was fixed on this commit https://github.com/electron/electron/commit/a8f2646ba682d65f94ea628ac11b1a5521bcedcd. The fix has been available from electron version `5.0.0`. I would advice you to upgrade to the latest atom version. I am closing this for now but happy to reopen if you still experience the issue.
