### ISSUE TITLE
Uncaught Error: error: 126/\?\~\AppData\Local\atom\app-1.42.0\resources\app.asar.unpacked\node_mo...

### ISSUE THREAD

**Issue by Carrybooo** [atom/atom#20310]
[Enter steps to reproduce:]

1. just press Ctrl
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: error: 126\\?\C:\Users\Root\AppData\Local\atom\app-1.42.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:160

Error: error: 126\\?\C:\Users\Root\AppData\Local\atom\app-1.42.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:1:728962)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:14:2779770)
    at get_manager (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:14:2779872)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:14:2779998)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:14:1083872)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:1249484)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:1247469)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:284591)
```

### Commands

```
     -0:36.4.0 settings-view:open (atom-pane.pane.active)
     -0:13.5.0 core:redo (div.panels-item)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-css-comb 3.5.1 
atom-html-preview 0.2.6 
atom-ide-ui 0.13.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.37 
git-plus 8.7.1 
highlight-selected 0.16.0 
ide-java 0.9.0 
ide-rust 0.21.2 
intentions 1.1.5 
linter 2.3.1 
linter-csslint 2.0.6 
linter-javac 1.10.0 
linter-rust 1.0.1 
linter-tidy 2.4.0 
linter-ui-default 1.8.1 
open_in_cmd 0.6.1 
pigments 0.40.2 
teletype 0.13.4 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
