### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 960Error: Cannot cal...

### ISSUE THREAD

**Issue by onurmert24** [atom/atom#20317]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Pardus GNU/Linux
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 960
Error: Cannot call function 'getPosition' on missing remote object 960
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 960
Error: Cannot call function 'getPosition' on missing remote object 960
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app/static/<embedded>:1:705395)
    at AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app/static/<embedded>:1:705810)
    at WindowEventHandler.handleWindowBlur (/usr/share/atom/resources/app/static/<embedded>:11:285354)
```

### Commands

```
     -2:54.2.0 core:move-right (input.hidden-input)
     -2:53.8.0 core:backspace (input.hidden-input)
     -2:52.4.0 core:move-right (input.hidden-input)
     -2:51.8.0 editor:newline (input.hidden-input)
     -2:32.2.0 core:paste (input.hidden-input)
  2x -2:29.1.0 editor:newline (input.hidden-input)
  2x -2:22.1.0 core:backspace (input.hidden-input)
  4x -2:12.5.0 core:move-left (input.hidden-input)
  4x -2:10 core:move-right (input.hidden-input)
     -2:08.5.0 editor:newline (input.hidden-input)
     -2:02.2.0 core:copy (input.hidden-input)
     -1:59.6.0 core:paste (input.hidden-input)
 26x -1:52.1.0 core:backspace (input.hidden-input)
 64x -1:14.7.0 core:move-right (input.hidden-input)
  6x -1:10.1.0 core:backspace (input.hidden-input)
     -0:42.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by sadick254** [comment]
Thank you for opening this issue. This was issue present in electron versions 4 and below. The latest atom version `v1.51.0` uses electron version `5.0.3`. The issue was fixed on this commit https://github.com/electron/electron/commit/a8f2646ba682d65f94ea628ac11b1a5521bcedcd. The fix has been available from electron version `5.0.0`. I would advice you to upgrade to the latest atom version. I am closing this for now but happy to reopen if you still experience the issue.
