### ISSUE TITLE
Uncaught Error: /\?\~\AppData\Local\atom\app-1.43.0\resources\app.asar.unpacked\node_modules\keyb...

### ISSUE THREAD

**Issue by Serina-zuna** [atom/atom#20328]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: \\?\C:\Users\Serina\AppData\Local\atom\app-1.43.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node is not a valid Win32 application.
\\?\C:\Users\Serina\AppData\Local\atom\app-1.43.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:160

Error: \\?\C:\Users\Serina\AppData\Local\atom\app-1.43.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node is not a valid Win32 application.
\\?\C:\Users\Serina\AppData\Local\atom\app-1.43.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:1:732429)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:14:2788664)
    at get_manager (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:14:2788766)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:14:2788892)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:14:1083406)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:11:1250646)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:11:1248631)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:11:284496)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
