### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.43.0\res...

### ISSUE THREAD

**Issue by enuenan** [atom/atom#20327]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\emoam\AppData\Local\atom\app-1.43.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:160

Error: The specified module could not be found.
\\?\C:\Users\emoam\AppData\Local\atom\app-1.43.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:1:732429)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:14:2788664)
    at get_manager (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:14:2788766)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:14:2788892)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:14:1083406)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:11:1250646)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:11:1248631)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:11:284496)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
emmet 2.4.3 
file-icons 2.1.38 
Hydrogen 2.13.1 
intentions 1.1.5 
laravel 0.7.1 
linter 2.3.1 
linter-csslint 2.0.6 
linter-eslint 8.5.5 
linter-htmlhint 1.6.3 
linter-jscs 4.2.3 
linter-jshint 3.1.18 
linter-ui-default 1.8.1 
minimap 4.29.9 
minimap-lens 0.3.0 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
turbo-javascript 1.4.0 
```

**Comment by collinscangarella** [comment]
Same issue here. Something must have failed during an automatic update; reinstalling atom fixed the issue.

**Comment by colbster** [comment]
Same error. Reinstalling atom seemed to fix the problem.
