### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat '/\Pence\Stab$\'

### ISSUE THREAD

**Issue by sulsaker** [atom/atom#20329]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat '\\Pence\Stab$\'

```
At fs.js:115

Error: EPERM: operation not permitted, lstat '\\Pence\Stab$\'
    at Proxy.realpathSync (fs.js:1393:5)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at atom.project.getPaths.map.e (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:816894)
    at Array.map (<anonymous>)
    at Object.startTask (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:816885)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:189146)
    at get_process.nextTick (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:187110)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
