### ISSUE TITLE
mk

### ISSUE THREAD

**Issue by mkinty** [atom/atom#20339]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:166

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744622)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744724)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744850)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1087821)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1246932)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1244917)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284329)
```

### Commands

```
     -2:20 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by mkinty** [comment]
> [Enter steps to reproduce:]
> 
>     1. ...
> 
>     2. ...
> 
> 
> **Atom**: 1.40.1 x64
> **Electron**: 3.1.10
> **OS**: Mac OS X 10.14.6
> **Thrown From**: Atom Core
> ### Stack Trace
> 
> Uncaught Error: Module did not self-register.
> 
> ```
> At ELECTRON_ASAR.js:166
> 
> Error: Module did not self-register.
>     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
>     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:551:3)
>     at Module.require (/app.asar/static/index.js:72:46)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
>     at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744622)
>     at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744724)
>     at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744850)
>     at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1087821)
>     at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1246932)
>     at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1244917)
>     at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284329)
> ```
> 
> ### Commands
> 
> ```
>      -2:20 core:save (input.hidden-input)
> ```
> 
> ### Non-Core Packages
> 
> ```
> 
> ```
