### ISSUE TITLE
Failed to load a language-shellscript package grammar

### ISSUE THREAD

**Issue by darangi** [atom/atom#20353]
**Atom**: 1.43.0-dev-1bc06505d x64
**Electron**: 5.0.12
**OS**: Mac OS X 10.15.2
**Thrown From**: [language-shellscript](https://github.com/atom/language-shellscript) package 0.28.0

### Stack Trace

Failed to load a language-shellscript package grammar

```
At The module '/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app.asar.unpacked/node_modules/tree-sitter-bash/build/Release/tree_sitter_bash_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 47. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app.asar/node_modules/language-shellscript/grammars/tree-sitter-bash.json

Error: The module '/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app.asar.unpacked/node_modules/tree-sitter-bash/build/Release/tree_sitter_bash_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 47. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /app.asar/node_modules/tree-sitter-bash/index.js:2:20)
    at /app.asar/node_modules/tree-sitter-bash/index.js:15:3)
    at Module.get_Module._compile (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:1:694511)
    at new TreeSitterGrammar (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:3108820)
    at GrammarRegistry.createGrammar (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:359833)
    at /Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:359674
    at u (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:580342)
    at /Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:581595
    at electron/js2c/asar.js:571:9
    at FSReqCallback.wrapper [as oncomplete] (fs.js:483:5)
  at /app.asar/node_modules/language-shellscript/grammars/tree-sitter-bash.json:1:1
```

### Commands

```
     -0:42.9.0 window:toggle-dev-tools (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-menu-patch-for-catalina 0.3.0 
teletype 0.13.4 
```

**Comment by darangi** [comment]
This no longer happens on the CI but showed up after atom (running electron 5) was lunched
