### ISSUE TITLE
Failed to load a language-typescript package grammar

### ISSUE THREAD

**Issue by darangi** [atom/atom#20355]
**Atom**: 1.43.0-dev-f473a9aab x64
**Electron**: 5.0.12
**OS**: Mac OS X 10.15.2
**Thrown From**: [language-typescript](https://github.com/atom/language-typescript) package 0.6.1

### Stack Trace

Failed to load a language-typescript package grammar

```
At Cannot find module './build/Release/tree_sitter_typescript_binding'
Require stack:
- /Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app.asar/node_modules/tree-sitter-typescript/typescript/index.js
- /Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app.asar/static/index.html in /Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app.asar/node_modules/language-typescript/grammars/tree-sitter-typescript.json

Error: Cannot find module './build/Release/tree_sitter_typescript_binding'
Require stack:
- /Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app.asar/node_modules/tree-sitter-typescript/typescript/index.js
- /Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /app.asar/node_modules/tree-sitter-typescript/typescript/index.js:2:20)
    at /app.asar/node_modules/tree-sitter-typescript/typescript/index.js:15:3)
    at Module.get_Module._compile (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:1:694511)
    at new TreeSitterGrammar (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:3109367)
    at GrammarRegistry.createGrammar (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:359833)
    at /Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:359674
    at u (/Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:580342)
    at /Users/musaibrahim/Projects/github/atom20034/atom/out/Atom Dev.app/Contents/Resources/app/static/<embedded>:11:581595
    at electron/js2c/asar.js:571:9
    at FSReqCallback.wrapper [as oncomplete] (fs.js:483:5)
  at /app.asar/node_modules/language-typescript/grammars/tree-sitter-typescript.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
atom-menu-patch-for-catalina 0.3.0 
teletype 0.13.4 
```

**Comment by darangi** [comment]
Publishing a new version of `language-typescript` and bumping the version in atom/atom (https://github.com/atom/atom/issues/20355) solved the problem.
