### ISSUE TITLE
Failing tests in Find and replace package

### ISSUE THREAD

**Issue by darangi** [atom/atom#20376]
```
 it ProjectFindView (ripgrep=true) panel focus focuses the find editor when the panel gets focus
      Expected element '[object HTMLElement]' or its descendants to have focus.
        at jasmine.Spec.<anonymous> (/Users/runner/runners/2.164.6/work/1/s/node_modules/find-and-replace/spec/project-find-view-spec.js:1526:55)
        at jasmine.Spec.args.(anonymous function) (/Users/runner/runners/2.164.6/work/1/s/spec/jasmine-test-runner.coffee:88:27)
    it ProjectFindView (ripgrep=true) panel focus moves focus between editors with find-and-replace:focus-next
      Expected element '[object HTMLElement]' or its descendants to have focus.
        at jasmine.Spec.<anonymous> (/Users/runner/runners/2.164.6/work/1/s/node_modules/find-and-replace/spec/project-find-view-spec.js:1534:53)
        at jasmine.Spec.args.(anonymous function) (/Users/runner/runners/2.164.6/work/1/s/spec/jasmine-test-runner.coffee:88:27)
      Expected element '[object HTMLElement]' or its descendants to have focus.
        at jasmine.Spec.<anonymous> (/Users/runner/runners/2.164.6/work/1/s/node_modules/find-and-replace/spec/project-find-view-spec.js:1537:51)
        at jasmine.Spec.args.(anonymous function) (/Users/runner/runners/2.164.6/work/1/s/spec/jasmine-test-runner.coffee:88:27)
      Expected element '[object HTMLElement]' or its descendants to have focus.
        at jasmine.Spec.<anonymous> (/Users/runner/runners/2.164.6/work/1/s/node_modules/find-and-replace/spec/project-find-view-spec.js:1546:53)
        at jasmine.Spec.args.(anonymous function) (/Users/runner/runners/2.164.6/work/1/s/spec/jasmine-test-runner.coffee:88:27)
ResultsView
  core:move-to-top and core:move-to-bottom
    it ResultsView core:move-to-top and core:move-to-bottom selects the first/last item when core:move-to-top/move-to-bottom is triggered
      Expected undefined to have class 'selected'.
        at jasmine.Spec.<anonymous> (/Users/runner/runners/2.164.6/work/1/s/node_modules/find-and-replace/spec/results-view-spec.js:307:71)
        at Generator.next (<anonymous>)
        at step (/Users/runner/runners/2.164.6/work/1/s/node_modules/find-and-replace/spec/results-view-spec.js:1:428)
    it ResultsView core:move-to-top and core:move-to-bottom selects the path when when core:move-to-bottom is triggered and last item is collapsed
      TypeError: Cannot read property 'parentElement' of undefined
        at jasmine.Spec.<anonymous> (/Users/runner/runners/2.164.6/work/1/s/node_modules/find-and-replace/spec/results-view-spec.js:320:85)
        at Generator.next (<anonymous>)
        at step (/Users/runner/runners/2.164.6/work/1/s/node_modules/find-and-replace/spec/results-view-spec.js:1:428)

```

**Comment by darangi** [comment]
https://github.com/atom/atom/issues/20375

**Comment by darangi** [comment]
Bumping `electron 5.0.12` to `electron 5.0.13` cleared the issue
