### ISSUE TITLE
Ubuntu  give err when I type (code --version)

### ISSUE THREAD

**Issue by Balqeesqasem** [atom/atom#20381]
net.js:282
    err = this._handle.open(fd);
                       ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:282:24)
    at createWritableStdioStream (internal/process/stdio.js:179:18)
    at process.getStderr [as stderr] (internal/process/stdio.js:40:14)
    at Object.get (internal/console/constructor.js:158:40)
    at Object.Console.<computed> (internal/console/constructor.js:276:46)
    at Object.warn (internal/console/constructor.js:287:61)
    at writeOut (internal/process/warning.js:27:3)
    at process.onWarning (internal/process/warning.js:79:3)
    at process.emit (events.js:205:15)
    at internal/process/warning.js:52:24
    at processTicksAndRejections (internal/process/task_queues.js:82:9) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'uv_pipe_open'
}

**Comment by lee-dohm** [comment]
If you're suggesting that you are entering `code --version` on the command line, then I suspect you're attempting to get support for [VSCode](https://github.com/microsoft/vscode). You may want to open an issue on their repository instead.

-----

Thank you for contributing!

We require the [appropriate issue template](https://github.com/atom/.github/tree/master/.github/ISSUE_TEMPLATE) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
