### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by kehlert72** [atom/atom#20388]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
D:\CS\cs4540_sp2020_g10>script\build
D:\CS\cs4540_sp2020_g10\script\build:93
    .then(async packagedAppPath => {
          ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)

D:\CS\cs4540_sp2020_g10>atom --safe

D:\CS\cs4540_sp2020_g10>script\build
D:\CS\cs4540_sp2020_g10\script\build:93
    .then(async packagedAppPath => {
          ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)

### Steps to Reproduce

1. Downloaded atom from Git
2. Downloaded Node.js
3. Set Node.js to version 6.10.3
4. script\bootstrap
5. atom --test spec
6. script\build

**Expected behavior:**
The project to build.

**Actual behavior:**
There was an error always thrown when I enter script\build.

### Versions
I got atom off of Git's master branch on February 3.

Node:   v6.10.3
Npm:    v3.10.10
Python: v2.7.17

### Additional Information

Atom beautify is included

**Comment by Aerijo** [comment]
> Node: v6.10.3

Try using Node 10+. Versions 8 and below are end of life.

**Comment by kehlert72** [comment]
I tried this and this is what I got.

Wrote Dependencies Fingerprint: D:\CS\cs4540_sp2020_g10\node_modules\.dependencies-fingerprint 3eddd39e10a8b19519d75eeabb973414669246d3
D:\CS\cs4540_sp2020_g10\script\node_modules\bindings\bindings.js:91
        throw e
        ^

Error: The module '\\?\D:\CS\cs4540_sp2020_g10\script\node_modules\leveldown\build\Release\leveldown.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
  at Object.Module._extensions..node (internal/modules/cjs/loader.js:707:18)
  at Module.load (D:\CS\cs4540_sp2020_g10\script\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
  at Function.Module._load (internal/modules/cjs/loader.js:520:3)
  at Module.require (internal/modules/cjs/loader.js:626:17)
  at require (internal/modules/cjs/helpers.js:20:18)
  at bindings (D:\CS\cs4540_sp2020_g10\script\node_modules\bindings\bindings.js:84:48)
  at Object.<anonymous> (D:\CS\cs4540_sp2020_g10\script\node_modules\leveldown\leveldown.js:3:36)
  at Module._compile (internal/modules/cjs/loader.js:678:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
  at Module.load (D:\CS\cs4540_sp2020_g10\script\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
  at Function.Module._load (internal/modules/cjs/loader.js:520:3)
  at Module.require (internal/modules/cjs/loader.js:626:17)
  at require (internal/modules/cjs/helpers.js:20:18)
  at Object.<anonymous> (D:\CS\cs4540_sp2020_g10\script\node_modules\electron-link\lib\transform-cache.js:6:19)
  at Module._compile (internal/modules/cjs/loader.js:678:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
  at Module.load (D:\CS\cs4540_sp2020_g10\script\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
  at Function.Module._load (internal/modules/cjs/loader.js:520:3)
  at Module.require (internal/modules/cjs/loader.js:626:17)
  at require (internal/modules/cjs/helpers.js:20:18)
  at Object.<anonymous> (D:\CS\cs4540_sp2020_g10\script\node_modules\electron-link\lib\index.js:3:24)
  at Module._compile (internal/modules/cjs/loader.js:678:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
  at Module.load (D:\CS\cs4540_sp2020_g10\script\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
  at Function.Module._load (internal/modules/cjs/loader.js:520:3)
  at Module.require (internal/modules/cjs/loader.js:626:17)
  at require (internal/modules/cjs/helpers.js:20:18)
  at Object.<anonymous> (D:\CS\cs4540_sp2020_g10\script\lib\generate-startup-snapshot.js:4:22)
  at Module._compile (internal/modules/cjs/loader.js:678:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
  at Module.load (D:\CS\cs4540_sp2020_g10\script\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
  at Function.Module._load (internal/modules/cjs/loader.js:520:3)
  at Module.require (internal/modules/cjs/loader.js:626:17)
  at require (internal/modules/cjs/helpers.js:20:18)
  at Object.<anonymous> (D:\CS\cs4540_sp2020_g10\script\build:50:33)
  at Module._compile (internal/modules/cjs/loader.js:678:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
  at Module.load (internal/modules/cjs/loader.js:589:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
  at Function.Module._load (internal/modules/cjs/loader.js:520:3)
  at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
  at startup (internal/bootstrap/node.js:228:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)

**Comment by kehlert72** [comment]
I fixed it, so thanks for the help
