### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.43.0\Gerekli...

### ISSUE THREAD

**Issue by KorayReiz** [atom/atom#20395]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\alire\AppData\Local\atom\app-1.43.0\Gerekli Dosyalar'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\alire\AppData\Local\atom\app-1.43.0\Gerekli Dosyalar'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:14:1004807)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:14:1011980)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:14:985367)
```

### Commands

```
 13x -7:17.1.0 core:backspace (input.hidden-input)
     -6:59.9.0 core:move-down (input.hidden-input)
  7x -6:59.1.0 core:backspace (input.hidden-input)
     -4:48.8.0 tree-view:add-folder (div.header.list-item.project-root-header)
     -4:43.1.0 core:confirm (input.hidden-input)
     -4:30.2.0 tree-view:add-file (div.header.list-item)
     -4:28.5.0 core:backspace (input.hidden-input)
     -4:19.6.0 core:confirm (input.hidden-input)
  2x -4:18.7.0 core:paste (input.hidden-input)
 59x -2:17.3.0 core:backspace (input.hidden-input)
  2x -2:10.9.0 core:paste (input.hidden-input)
 18x -2:02.1.0 core:backspace (input.hidden-input)
     -1:51.6.0 core:paste (input.hidden-input)
     -0:18.6.0 tree-view:add-folder (div.header.list-item.project-root-header)
  2x -0:14.1.0 core:backspace (input.hidden-input)
     -0:12.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
