### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.44.0\res...

### ISSUE THREAD

**Issue by rorkyendo** [atom/atom#20401]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\taufi\AppData\Local\atom\app-1.44.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:160

Error: The specified module could not be found.
\\?\C:\Users\taufi\AppData\Local\atom\app-1.44.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:1:734076)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:2805937)
    at get_manager (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:2806039)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:2806165)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:1083662)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1250710)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1248695)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:284496)
```

### Commands

```
     -9:06.1.0 application:add-project-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
platformio-ide-terminal 2.10.0 
```

**Comment by Legaci91** [comment]
Same issue! Actually editor is complete unusable.

**Comment by Legaci91** [comment]
> [Enter steps to reproduce:]
> 
> 1. ...
> 2. ...
> 
> **Atom**: 1.44.0 x64
> **Electron**: 4.2.7
> **OS**: Microsoft Windows 10 Home Single Language
> **Thrown From**: Atom Core
> 
> ### Stack Trace
> Uncaught Error: The specified module could not be found.
> \?\C:\Users\taufi\AppData\Local\atom\app-1.44.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
> 
> ```
> At ELECTRON_ASAR.js:160
> 
> Error: The specified module could not be found.
> \\?\C:\Users\taufi\AppData\Local\atom\app-1.44.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
>     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
>     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
>     at Module.load (internal/modules/cjs/loader.js:602:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:533:3)
>     at Module.require (/app.asar/static/index.js:72:46)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at customRequire (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:1:734076)
>     at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:2805937)
>     at get_manager (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:2806039)
>     at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:2806165)
>     at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:1083662)
>     at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1250710)
>     at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1248695)
>     at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:284496)
> ```
> 
> ### Commands
> ```
>      -9:06.1.0 application:add-project-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
> ```
> 
> ### Non-Core Packages
> ```
> platformio-ide-terminal 2.10.0 
> ```

I uninstalled, and re-installed, and is now running smooth again!

**Comment by Valdnieks** [comment]
Had same error. Reinstalling helped.

What was interesting was that system said it was 1.43.0 but tried to find stuff from 1.44.0. After reinstalling everything shows correctly.

**Comment by rorkyendo** [comment]
Thankyou everyone after i reinstall it the problem was solved.

**Comment by Akposieyefa** [comment]
how can one resolve this issue
