### ISSUE TITLE
Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM ob...

### ISSUE THREAD

**Issue by PioArchiver** [atom/atom#20410]
[Enter steps to reproduce:]

1. I used the script below ... I'm new to atom development and I was checking to see if using custom elements in the init.coffee script worked. Below in step 2 is the code I have in the file.
2. 
```
class MyElement extends HTMLElement
  constructor: () ->
    super;
    this.style.position = "fixed";
    this.style.zIndex = "100";
    this.style.width = "50px";
    this.style.height = "50px";
    this.style.margin = "50px";
    this.style.padding = "10px";
    this.style.borderRadius = "100%";
    this.style.backgroundColor = "red";
  connectedCallback: () ->
    console.log(this);

customElements.define("pio-game", MyElement);

atom = document.querySelector("atom-workspace");
myCE = document.createElement("pio-game");

atom.appendChild(myCE);

```
I ran the above code and the error prompt asked me to send this your way ... so I did.

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

```
At C:\Users\steve\.atom\init.coffee:3

TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at new pioGame (~/.atom/init.coffee:3:5)
    at Object.<anonymous> (~/.atom/init.coffee:18:19)
    at Object.<anonymous> (~/.atom/init.coffee:1:1)
    at Object.<anonymous> (~/.atom/init.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:1:734076)
    at AtomEnvironment.requireUserInitScript (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:1:763912)
    at t.loadState.then (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:1:756320)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
```

**Comment by PioArchiver** [comment]
I don't think it was my code, although it isn't exactly correctly formatted coffee script 🥇 ...
I did go ahead and rewrite the code so it looks like this now...am I just missing something?

```
class MyElement extends HTMLElement
  constructor: ->
    super()
    @ready = true;

customElements.define("pio-game", MyElement);

atom = document.querySelector("atom-workspace");
myCE = document.createElement("pio-game");

atom.appendChild(myCE);

```
