### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 1751

### ISSUE THREAD

**Issue by irishakarpova** [atom/atom#20429]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 1751

```
At /Users/irisha/soft/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 1751
    at throwRPCError (/Users/irisha/soft/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:148:17)
    at /Users/irisha/soft/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (/Users/irisha/soft/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Users/irisha/soft/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
     -7:44.9.0 core:save (input.hidden-input)
  6x -7:34.9.0 core:backspace (input.hidden-input)
     -7:16.7.0 core:move-left (input.hidden-input)
     -7:13.3.0 core:save (input.hidden-input)
     -6:28.6.0 core:copy (input.hidden-input)
  2x -4:56.2.0 core:paste (input.hidden-input)
  2x -4:22.2.0 core:save (input.hidden-input)
  4x -4:08.5.0 core:undo (input.hidden-input)
     -4:06.3.0 core:save (input.hidden-input)
     -4:03.3.0 core:backspace (input.hidden-input)
     -4:02.4.0 core:save (input.hidden-input)
  2x -3:30.5.0 core:copy (input.hidden-input)
     -1:11.4.0 core:move-left (input.hidden-input)
     -1:09.7.0 core:paste (input.hidden-input)
     -1:09.0 core:save (input.hidden-input)
     -0:35.9.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax-dark 1.0.0 
color-picker 2.3.0 
comment 0.6.1 
php-twig 4.0.0 
platformio-ide-terminal 2.10.0 
random 1.4.1 
react 0.18.0 
```

**Comment by sadick254** [comment]
Thank you for opening this issue. This was issue present in electron versions 4 and below. The latest atom version `v1.51.0` uses electron version `5.0.3`. The issue was fixed on this commit https://github.com/electron/electron/commit/a8f2646ba682d65f94ea628ac11b1a5521bcedcd. The fix has been available from electron version `5.0.0`. I would advice you to upgrade to the latest atom version. I am closing this for now but happy to reopen if you still experience the issue.
