### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND adc-proxy....

### ISSUE THREAD

**Issue by LeeDoty** [atom/atom#20436]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND adc-proxy.oracle.com adc-proxy.oracle.com:80

```
At internal/streams/legacy.js:57

Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND adc-proxy.oracle.com adc-proxy.oracle.com:80
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:391:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
```

### Non-Core Packages

```
compare-files 0.8.1 
highlight-line 0.12.0 
pretty-json 2.1.2 
split-diff 1.6.1 
state-machine-cat-preview 4.6.9 
Sublime-Style-Column-Selection 1.7.5 
xml-formatter 0.13.0 
```

**Comment by juliuscrn** [comment]
apm does not work behind most corporate proxies. It has been this way for years now and devs said they don't have the resources to fix it, rendering apm completely useless. Curiously, as you will see, Atom *is* able to update itself even behind a proxy.
