### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by sky-labs-237** [atom/atom#20467]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown macOS version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:166

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744622)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744724)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744850)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1087821)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1246932)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1244917)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284329)
```

### Commands

```
  6x -3:50.1.0 command-palette:toggle (div.tool-panel.tree-view)
     -3:45.4.0 editor:consolidate-selections (input.hidden-input)
     -0:18 core:save (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-file-icons 0.7.1 
atom-visual-studio-code-ui 2.1.0 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
docker 0.8.0 
file-icons 2.1.39 
flex-tool-bar 2.1.4 
git-plus 8.7.1 
github-atom-light-syntax 0.5.0 
hasklig 0.4.0 
ink 0.11.8 
intentions 1.1.5 
kite 0.178.0 
language-babel 2.85.0 
language-docker 1.1.8 
language-vue 0.26.0 
lint-sass-vue 1.0.5 
linter 2.3.1 
linter-docker 0.3.2 
linter-flake8 2.4.0 
linter-joker 4.1.0 
linter-ui-default 1.8.1 
lisp-paredit 0.6.0 
minimap 4.29.9 
parinfer 1.23.0 
platformio-ide-terminal 2.10.0 
predawn-syntax 1.0.4 
proto-repl 1.4.24 
python-autopep8 0.1.3 
rainbow-delimiters 2.1.2 
script 3.25.0 
spacegray-atom-dark-syntax 1.3.2 
spacegray-atom-dark-ui 1.0.2 
spacegray-dark-ui 0.13.0 
teletype 0.13.4 
tool-bar 1.2.0 
vim-mode-plus 1.36.4 
vue-fmt 0.1.1 
vue-template-beautify 0.1.2 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 1.1.0 
```

**Comment by lkashef** [comment]
Hey @sky-labs-237, thanks for the report.

I noticed that you are running on an old version of Atom and also have a lot of community packages installed.

Do you mind trying to run atom in safe mode? Also updating or a fresh install of Atom might help.

Let me know if you are able to get Atom running again.
