### ISSUE TITLE
Atom packages with native dependencies fail to load when notarized

### ISSUE THREAD

**Issue by smashwilson** [atom/atom#20465]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Now that Atom's builds are notarized, user packages that have native dependencies fail to load with the following error:

![error screenshot](https://user-images.githubusercontent.com/17565/75710218-c4305c00-5c89-11ea-9f67-e211b8586e91.png)

<details>
### Stack Trace

Failed to activate the github package

```
At dlopen(/Users/smashwilson/.atom/packages/github/node_modules/superstring/build/Release/superstring.node, 1): no suitable image found.  Did find:
	/Users/smashwilson/.atom/packages/github/node_modules/superstring/build/Release/superstring.node: code signature in (/Users/smashwilson/.atom/packages/github/node_modules/superstring/build/Release/superstring.node) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

Error: dlopen(/Users/smashwilson/.atom/packages/github/node_modules/superstring/build/Release/superstring.node, 1): no suitable image found.  Did find:
	/Users/smashwilson/.atom/packages/github/node_modules/superstring/build/Release/superstring.node: code signature in (/Users/smashwilson/.atom/packages/github/node_modules/superstring/build/Release/superstring.node) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /app.asar/node_modules/text-buffer/node_modules/superstring/index.js:118:15)
    at /app.asar/node_modules/text-buffer/node_modules/superstring/index.js:357:3)
    at Module.get_Module._compile (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/github/node_modules/whats-my-line/dist/index.js:4:23)
    at /packages/github/node_modules/whats-my-line/dist/index.js:114:3)
    at Module.get_Module._compile (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/github/comment-positioning-container.js:6:1)
    at /packages/github/comment-positioning-container.js:117:23)
    at Module.get_Module._compile (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:150977)
```

</details>

Note that this doesn't happen in safe mode because, by definition, safe mode doesn't load user packages 🙃 

### Steps to Reproduce

1. Install the GitHub package from master: `apm install atom/github`
2. Launch Atom

**Expected behavior:**

Atom to launch and the GitHub package to initialize successfully.

**Actual behavior:**

The stack trace I see above :point_up:

**Reproduces how often:**

100%

### Versions

**Atom**: 1.46.0-nightly5 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: [github](https://github.com/atom/github) package 0.34.2

```
$ apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.46.0-nightly5
python 2.7.16
git 2.21.1
$ atom --version
Atom    : 1.46.0-nightly5
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

### Additional Information

I _suspect_ this will happen when any user package attempts to load a native module, but I haven't actually tested any others yet. It would be good to verify that with another.

**Comment by lkashef** [comment]
Thanks @smashwilson, can you confirm where do you run `apm install atom/github`?

**Comment by smashwilson** [comment]
I think I ran it from my home directory. (It shouldn't matter; `apm install` doesn't use your current directory.)

**Comment by lkashef** [comment]
That's exactly what I wanted to confirm, thanks
