### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/td/qkqx3fls37b91bmm1wlxb7zm0000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by emmarose898** [atom/atom#20466]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/td/qkqx3fls37b91bmm1wlxb7zm0000gn/T/AppTranslocation/B6B61C5F-CC47-4F70-A959-135F831876A3/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At ELECTRON_ASAR.js:160

Error: dlopen(/private/var/folders/td/qkqx3fls37b91bmm1wlxb7zm0000gn/T/AppTranslocation/B6B61C5F-CC47-4F70-A959-135F831876A3/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/private/var/folders/td/qkqx3fls37b91bmm1wlxb7zm0000gn/T/AppTranslocation/B6B61C5F-CC47-4F70-A959-135F831876A3/d/Atom.app/Contents/Resources/app/static/<embedded>:1:694511)
    at get_KeyboardLayoutManager (/private/var/folders/td/qkqx3fls37b91bmm1wlxb7zm0000gn/T/AppTranslocation/B6B61C5F-CC47-4F70-A959-135F831876A3/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2803410)
    at get_manager (/private/var/folders/td/qkqx3fls37b91bmm1wlxb7zm0000gn/T/AppTranslocation/B6B61C5F-CC47-4F70-A959-135F831876A3/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2803512)
    at Object.getCurrentKeyboardLayout (/private/var/folders/td/qkqx3fls37b91bmm1wlxb7zm0000gn/T/AppTranslocation/B6B61C5F-CC47-4F70-A959-135F831876A3/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2803638)
    at e.keystrokeForKeyboardEvent (/private/var/folders/td/qkqx3fls37b91bmm1wlxb7zm0000gn/T/AppTranslocation/B6B61C5F-CC47-4F70-A959-135F831876A3/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1083641)
    at KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/td/qkqx3fls37b91bmm1wlxb7zm0000gn/T/AppTranslocation/B6B61C5F-CC47-4F70-A959-135F831876A3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1250710)
    at KeymapManager.handleKeyboardEvent (/private/var/folders/td/qkqx3fls37b91bmm1wlxb7zm0000gn/T/AppTranslocation/B6B61C5F-CC47-4F70-A959-135F831876A3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1248695)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/td/qkqx3fls37b91bmm1wlxb7zm0000gn/T/AppTranslocation/B6B61C5F-CC47-4F70-A959-135F831876A3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:284496)
```

### Commands

```
     -0:36.8.0 core:paste (input.hidden-input)
  2x -0:24.4.0 atom-live-server:start-server (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server-plus 3.0.1 
auto-indent 0.5.0 
teletype 0.13.4 
```

**Comment by lkashef** [comment]
Hello @emmarose898, thanks for the report.

Since the reproduction steps are not clear, I can assume similar scenarios take place at startup.

If that's the case please try running atom in safe mode, re-installing might help as well.

If that's not the case please provide us with more information.
