### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/\xdcfiles\Public\christian_projekte\HT...

### ISSUE THREAD

**Issue by wiemaier** [atom/atom#20476]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: XDCMEDIA-PC
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '\\xdcfiles\Public\christian_projekte\HTML_CSS\swiper-4.5.0'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat '\\xdcfiles\Public\christian_projekte\HTML_CSS\swiper-4.5.0'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:1005063)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:1012236)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:985623)
```

### Commands

```
     -6:05.9.0 core:move-down (input.hidden-input)
     -6:05.7.0 autocomplete-plus:confirm (input.hidden-input)
     -6:02.6.0 editor:newline (input.hidden-input)
  6x -6:00.5.0 core:backspace (input.hidden-input)
  2x -5:51.5.0 core:move-down (input.hidden-input)
     -5:50.9.0 autocomplete-plus:confirm (input.hidden-input)
     -5:50.8.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -5:37.2.0 core:backspace (input.hidden-input)
     -5:26.6.0 editor:newline (input.hidden-input)
     -5:23.1.0 autocomplete-plus:confirm (input.hidden-input)
     -5:23.1.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -5:09.2.0 editor:newline (input.hidden-input)
  3x -5:04.3.0 core:move-down (input.hidden-input)
     -5:03.4.0 autocomplete-plus:confirm (input.hidden-input)
     -5:03.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -4:55.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-material-syntax 1.0.8 
browser-plus 0.0.98 
ide-html 0.6.0 
open-in-browsers 0.0.30 
teletype 0.13.4 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
