### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by NikolaTesla13** [atom/atom#20496]
I have an error when I'm trying to build:
```
user@user-HP:~/Downloads/atom$ script/build

fatal: not a git repository (or any of the parent directories): .git

/home/user/Downloads/atom/script/lib/spawn-sync.js:17
      `Command ${result.args.join(' ')} exited with code "${result.status}"`
                             ^

TypeError: Cannot read property 'join' of undefined
    at module.exports (/home/user/Downloads/atom/script/lib/spawn-sync.js:17:30)
    at computeAppVersion (/home/user/Downloads/atom/script/config.js:89:20)
    at Object.<anonymous> (/home/user/Downloads/atom/script/config.js:24:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```
I just download it from Github. I didn't make any change to the project, locally.

**Comment by li328250157** [comment]
me too

**Comment by li328250157** [comment]
@mojombo @NikolaTesla13 @defunkt @caged
