### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/vq/k44b3x7x0c946xg9mb0ms5380000gq/T/AppTranslocation/...

### ISSUE THREAD

**Issue by neffp** [atom/atom#20507]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/vq/k44b3x7x0c946xg9mb0ms5380000gq/T/AppTranslocation/E4911D02-D074-4A0B-A6C1-F2091A98117E/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/fs-admin/build/Release/fs_admin.node, 1): no suitable image found.  Did find:
	/private/var/folders/vq/k44b3x7x0c946xg9mb0ms5380000gq/T/AppTranslocation/E4911D02-D074-4A0B-A6C1-F2091A98117E/d/Atom.app/Contents/Resources/app.asar.unpacked: not a file

```
At ELECTRON_ASAR.js:160

Error: dlopen(/private/var/folders/vq/k44b3x7x0c946xg9mb0ms5380000gq/T/AppTranslocation/E4911D02-D074-4A0B-A6C1-F2091A98117E/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/fs-admin/build/Release/fs_admin.node, 1): no suitable image found.  Did find:
	/private/var/folders/vq/k44b3x7x0c946xg9mb0ms5380000gq/T/AppTranslocation/E4911D02-D074-4A0B-A6C1-F2091A98117E/d/Atom.app/Contents/Resources/app.asar.unpacked: not a file
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/private/var/folders/vq/k44b3x7x0c946xg9mb0ms5380000gq/T/AppTranslocation/E4911D02-D074-4A0B-A6C1-F2091A98117E/d/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at get_binding (/private/var/folders/vq/k44b3x7x0c946xg9mb0ms5380000gq/T/AppTranslocation/E4911D02-D074-4A0B-A6C1-F2091A98117E/d/Atom.app/Contents/Resources/app/static/<embedded>:14:18000)
    at Object.unlink (/private/var/folders/vq/k44b3x7x0c946xg9mb0ms5380000gq/T/AppTranslocation/E4911D02-D074-4A0B-A6C1-F2091A98117E/d/Atom.app/Contents/Resources/app/static/<embedded>:14:18967)
    at CommandInstaller.createSymlink (/private/var/folders/vq/k44b3x7x0c946xg9mb0ms5380000gq/T/AppTranslocation/E4911D02-D074-4A0B-A6C1-F2091A98117E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:403014)
    at i.ENOENT.i.code.e.createSymlink.i (/private/var/folders/vq/k44b3x7x0c946xg9mb0ms5380000gq/T/AppTranslocation/E4911D02-D074-4A0B-A6C1-F2091A98117E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:402943)
    at FSReqWrap.oncomplete (fs.js:141:20)
```

### Commands

```
     -0:02.2.0 window:install-shell-commands (input.hidden-input)
```

### Non-Core Packages

```
atom-material-ui 2.1.3 
futurism-ui 2.0.0 
herald-atom 0.0.2 
kitura 0.2.0 
language-natural 0.1.1 
natural-autoflow 0.2.3 
natural-syntax 1.2.0 
one-coral-light-syntax 0.1.0 
turbo-c-syntax 0.3.5 
```

**Comment by lkashef** [comment]
Hey @neffp, thanks for the report!

This looks like an installation problem, did you try re-installing Atom?
You could also try running atom using `safe-mode` in case community packages are causing conflicts!
