### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'C:/ProgramData\User\atom\app-1.45.0\1.py'

### ISSUE THREAD

**Issue by 4renginy** [atom/atom#20537]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\ProgramData\User\atom\app-1.45.0\1.py'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\ProgramData\User\atom\app-1.45.0\1.py'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (C:/ProgramData/User/atom/app-1.45.0/resources/app/static/<embedded>:14:1005297)
    at TreeView.onDrop (C:/ProgramData/User/atom/app-1.45.0/resources/app/static/<embedded>:14:1012226)
    at HTMLDivElement.<anonymous> (C:/ProgramData/User/atom/app-1.45.0/resources/app/static/<embedded>:14:985857)
```

### Commands

```
  3x -9:37.8.0 tree-view:remove (span.name.icon.icon-file-text)
     -7:21.8.0 tree-view:cut (span.name.icon.icon-file-text)
     -7:14.3.0 tree-view:paste (span.name.icon.icon-file-directory)
     -3:18.6.0 tree-view:cut (span.name.icon.icon-file-text)
     -3:11.6.0 tree-view:paste (span.name.icon.icon-file-directory)
     -2:42.7.0 tree-view:cut (li.file.entry.list-item.selected)
     -2:37.4.0 tree-view:paste (span.name.icon.icon-file-directory)
     -1:13.2.0 tree-view:remove (span.name.icon.icon-file-text)
```

### Non-Core Packages

```

```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
