### ISSUE TITLE
Atom throwing error when attempting to view a package's settings and README

### ISSUE THREAD

**Issue by pranavchary** [atom/atom#20548]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode> _(Author's note: was unable to reproduce in safe mode, but caused a separate issue there. Please see description for more details.)_
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When I install a particular Atom package and try to open the settings to view the README, I get the following error:
```
Uncaught NodeError: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.isAbsolute (path.js:1144:5)
    at sanitize (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2663474)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2663633
    at t.exports (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3267594)
    at new PackageReadmeView (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2663041)
    at PackageDetailView.renderReadme (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:826124)
    at PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:825697)
    at PackageDetailView.populate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:824249)
    at PackageDetailView.completeInitialization (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:819589)
    at PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:819801)
    at new PackageDetailView (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:816387)
    at SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:957781)
    at SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:958502)
    at HTMLDivElement.clickHandler (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2636770)
```

This issue only occurs with this particular package. I am not able to reproduce this issue in safe mode, however. When I run Atom in safe mode, it shows the settings screen fine but says there is no README file. I have tried all of the other steps in the Prerequisites section, but haven't been able to find an existing solution that works for me.

### Steps to Reproduce

1. Install react-rnative-snippets via Install window (Atom -> Preferences -> Install)
2. Click on the package to view the settings and README
3. Error message appears

**Expected behavior:**

I should be able to view the settings and README for this package.

**Actual behavior:**

I receive the error mentioned above.

**Reproduces how often:**

Every time

### Versions

0.1.3

### Additional Information

OS: macOS Catalina 10.15.3
Atom version: 1.45.0

**Comment by pranavchary** [comment]
I can confirm that this issue is also occurring on another Atom user's system. I know they have macOS but do not know the version or the version of Atom they used either. If this could help solve the issue, please let me know and I will find out from them.

**Comment by pranavchary** [comment]
Issue was solved. It was being caused by the presence of the word Image in the read me without being wrapped by backticks. Settings panel was trying to parse it as an actual image.
