### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages/atom-typescript/READ...

### ISSUE THREAD

**Issue by vedantatrivedi** [atom/atom#20540]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/vedanta/.atom/packages/atom-typescript/README.md'

```
At fs.js:115

Error: ENOENT: no such file or directory, open '/home/vedanta/.atom/packages/atom-typescript/README.md'
    at Object.openSync (fs.js:436:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
    at Proxy.readFileSync (fs.js:341:35)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:580:40)
    at PackageDetailView.renderReadme (<embedded>:14:825937)
    at PackageDetailView.updateInstalledState (<embedded>:14:825697)
    at PackageDetailView.populate (<embedded>:14:824249)
    at PackageDetailView.completeInitialization (<embedded>:14:819589)
    at PackageDetailView.loadPackage (<embedded>:14:819801)
    at <embedded>:14:826552
    at Function.simpleDispatch (<embedded>:11:1214120)
    at Emitter.emit (<embedded>:11:1215561)
    at PackageManager.emitPackageEvent (<embedded>:11:945159)
    at <embedded>:11:942291
    at r (<embedded>:11:936821)
    at n (<embedded>:14:1125033)
    at t.bufferStream (<embedded>:14:1125187)
    at Socket.e.on (<embedded>:14:1123789)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)

```

### Commands

```
     -5:54.8.0 core:move-right (input.hidden-input)
     -5:46.7.0 core:move-down (input.hidden-input)
     -5:45.3.0 editor:newline (input.hidden-input)
 11x -5:28.1.0 core:backspace (input.hidden-input)
     -5:21.7.0 editor:newline (input.hidden-input)
     -5:21.2.0 hydrogen:run-and-move-down (input.hidden-input)
     -5:21.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -5:21 editor:newline (input.hidden-input)
     -5:04.4.0 welcome:show (atom-notification.error.icon.icon-flame.native-key-bindings.has-description.has-close)
     -4:09.1.0 core:backspace (input.hidden-input)
     -4:08.6.0 core:confirm (input.hidden-input)
  2x -3:37.6.0 editor:newline (input.hidden-input)
     -3:05.3.0 autocomplete-plus:confirm (input.hidden-input)
 12x -3:03.1.0 core:move-left (input.hidden-input)
     -3:00.7.0 core:backspace (input.hidden-input)
  3x -2:59 core:save (input.hidden-input)
```

### Non-Core Packages

```
angular-snippets 8.0.2 
atom-clock 0.1.17 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-typescript 13.5.0 
Hydrogen 2.14.1 
ide-html 0.6.0 
```

**Comment by darangi** [comment]
Thanks for reporting this!

This has already been fixed on `master`. It is currently scheduled for release when `v1.53.0` reaches Stable.
