### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.45.0\ softma...

### ISSUE THREAD

**Issue by leenremm** [atom/atom#20554]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\leenr\AppData\Local\atom\app-1.45.0\ softmax).h5'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\leenr\AppData\Local\atom\app-1.45.0\ softmax).h5'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1005297)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1012226)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:985857)
```

### Commands

```
     -0:39.9.0 core:copy (input.hidden-input)
     -0:39.3.0 core:confirm (input.hidden-input)
     -0:37 tree-view:move (span.name.icon.icon-file-text)
     -0:36.6.0 core:paste (input.hidden-input)
     -0:35.7.0 core:confirm (input.hidden-input)
     -0:31.9.0 tree-view:move (span.name.icon.icon-file-text)
     -0:31 core:paste (input.hidden-input)
 12x -0:30.6.0 editor:move-to-beginning-of-word (input.hidden-input)
  2x -0:28.6.0 core:move-left (input.hidden-input)
     -0:28.1.0 editor:select-to-beginning-of-word (input.hidden-input)
 11x -0:26.4.0 editor:move-to-end-of-word (input.hidden-input)
  2x -0:23.7.0 core:backspace (input.hidden-input)
  2x -0:18.9.0 core:move-left (input.hidden-input)
     -0:18.3.0 core:move-right (input.hidden-input)
  8x -0:17.8.0 core:backspace (input.hidden-input)
     -0:10.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
