### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by AsanovDinnur** [atom/atom#20565]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At /private/var/folders/d8/6_k0p3zd3bz95qjfpsbjrqsr0000gn/T/AppTranslocation/53322C03-6B92-4F51-A6DE-60BCF08FCA2E/d/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Right-hand side of 'instanceof' is not callable
    at ViewRegistry.createView (/private/var/folders/d8/6_k0p3zd3bz95qjfpsbjrqsr0000gn/T/AppTranslocation/53322C03-6B92-4F51-A6DE-60BCF08FCA2E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:324327)
    at ViewRegistry.getView (/private/var/folders/d8/6_k0p3zd3bz95qjfpsbjrqsr0000gn/T/AppTranslocation/53322C03-6B92-4F51-A6DE-60BCF08FCA2E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:324001)
    at HTMLElement.getActiveView (/app.asar/src/pane-element.js:206:23)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:44:25)
    at HTMLElement.activated (/app.asar/src/pane-element.js:115:12)
    at Function.simpleDispatch (/private/var/folders/d8/6_k0p3zd3bz95qjfpsbjrqsr0000gn/T/AppTranslocation/53322C03-6B92-4F51-A6DE-60BCF08FCA2E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/private/var/folders/d8/6_k0p3zd3bz95qjfpsbjrqsr0000gn/T/AppTranslocation/53322C03-6B92-4F51-A6DE-60BCF08FCA2E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at Pane.activate (/private/var/folders/d8/6_k0p3zd3bz95qjfpsbjrqsr0000gn/T/AppTranslocation/53322C03-6B92-4F51-A6DE-60BCF08FCA2E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:463849)
    at NotificationElement.removeNotificationAfterTimeout (/private/var/folders/d8/6_k0p3zd3bz95qjfpsbjrqsr0000gn/T/AppTranslocation/53322C03-6B92-4F51-A6DE-60BCF08FCA2E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:912433)
    at NotificationElement.removeNotification (/private/var/folders/d8/6_k0p3zd3bz95qjfpsbjrqsr0000gn/T/AppTranslocation/53322C03-6B92-4F51-A6DE-60BCF08FCA2E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:911319)
    at NotificationElement.handleRemoveNotificationClick (/private/var/folders/d8/6_k0p3zd3bz95qjfpsbjrqsr0000gn/T/AppTranslocation/53322C03-6B92-4F51-A6DE-60BCF08FCA2E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:911436)
    at HTMLDivElement.<anonymous> (/private/var/folders/d8/6_k0p3zd3bz95qjfpsbjrqsr0000gn/T/AppTranslocation/53322C03-6B92-4F51-A6DE-60BCF08FCA2E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:907753)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.16.0 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
