### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 78Error: Cannot call...

### ISSUE THREAD

**Issue by HenriDeh** [atom/atom#20562]
I work on a laptop that is closed and I use an external monitor as my main monitor. This happened when I opened my laptop which turned its screen back on and all that was on my external monitor was transferred to the laptop screen. I suspect this is because for a short time there was no screen.

Concretely there wasn't any disturbance, only the uncaught error message. So I figured I'd report it.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Windows 10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 78
Error: Cannot call function 'getPosition' on missing remote object 78
    at throwRPCError (C:\Users\Henri\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\rpc-server.js:145:17)
    at EventEmitter.<anonymous> (C:\Users\Henri\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\Henri\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\api\web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At C:\Users\Henri\AppData\Local\atom\app-1.40.1\resources\electron.asar\renderer\api\remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 78
Error: Cannot call function 'getPosition' on missing remote object 78
    at throwRPCError (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:1:731570)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:1:731985)
    at WindowEventHandler.handleWindowResize (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:285420)
    at l (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1197399)
```

### Commands

```
  2x -4:51.9.0 core:backspace (input.hidden-input)
     -3:10.1.0 intentions:highlight (input.hidden-input)
  6x -2:59.1.0 core:backspace (input.hidden-input)
     -2:54.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 2.0.1 
git-plus 8.7.1 
indent-detective 0.4.0 
ink 0.12.3 
intentions 1.1.5 
julia-client 0.12.3 
language-julia 0.19.2 
latex-completions 0.3.6 
linter 2.3.1 
linter-julia 0.8.3 
linter-ui-default 1.8.1 
save-workspace 0.5.0 
tool-bar 1.2.2 
uber-juno 0.3.0 
```

**Comment by sadick254** [comment]
Thank you for opening this issue. This was issue present in electron versions 4 and below. The latest atom version `v1.51.0` uses electron version `5.0.3`. The issue was fixed on this commit https://github.com/electron/electron/commit/a8f2646ba682d65f94ea628ac11b1a5521bcedcd. The fix has been available from electron version `5.0.0`. I would advice you to upgrade to the latest atom version. I am closing this for now but happy to reopen if you still experience the issue.
