### ISSUE TITLE
Uncaught The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by schnorea** [atom/atom#20566]
[Enter steps to reproduce:]

1. Start up 
2. In a project folder look at various files

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught The "path" argument must be of type string. Received type undefined

```
At path.js:39

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1155:7)
    at onEvents.e.map.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:24548)
    at Array.map (<anonymous>)
    at watcher.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:24400)
```

### Commands

```
  4x -1:42.8.0 core:backspace (input.hidden-input)
     -1:26.4.0 project-find:show-in-current-directory (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
build 0.70.0 
busy-signal 2.0.1 
compare-files 0.8.1 
file-icons 2.1.39 
hard-wrap 1.7.1 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc 0.9.0 
linter-gcc2 0.8.8 
linter-ui-default 1.8.1 
platformio-ide-terminal 2.10.0 
project-manager 3.3.8 
python-indent 1.2.5 
show-invisibles-plus 0.3.1 
sort-lines 0.19.0 
Sublime-Style-Column-Selection 1.7.5 
svg-preview 0.14.0 
tool-bar 1.2.2 
xml-formatter 0.13.0 
```

**Comment by schnorea** [comment]
![image](https://user-images.githubusercontent.com/10821682/77814446-8c011b00-7087-11ea-8100-81dd2d18672c.png)

This is the state when the error happens.

**Comment by schnorea** [comment]
Is there a way to work in the embedded space?

**Comment by schnorea** [comment]
I removed atom like this:
rm -rf ~/.atom
rm /usr/local/bin/atom
rm /usr/local/bin/apm
rm -rf /Applications/Atom.app
rm ~/Library/Preferences/com.github.atom.plist
rm ~/Library/Application\ Support/com.github.atom.ShipIt
rm -rf ~/Library/Application\ Support/Atom
rm -rf ~/Library/Saved\ Application\ State/com.github.atom.savedState
rm -rf ~/Library/Caches/com.github.atom
rm -rf ~/Library/Caches/Atom

Reinstalled latest 
![image](https://user-images.githubusercontent.com/10821682/77853216-fc578b80-71b0-11ea-81bd-32f31d4f5180.png)

Started Atom:
Added a project folder:
Was working without incident.
Did a build outside of Atom using CMake.
came back to Atom and these where waiting for me.

![image](https://user-images.githubusercontent.com/10821682/77853266-4a6c8f00-71b1-11ea-9b99-be1d1aebb990.png)

**Comment by schnorea** [comment]
It has no recognizable effect on anything that I can see.  Is there a way to ignore this and not display the red box?

**Comment by JesterEE** [comment]
Getting this error while working with files on a mapped network drive on a Windows computer.  In my scenario, the source file is on a Linux based NAS.

**Comment by titovanton** [comment]
> Getting this error while working with files on a mapped network drive on a Windows computer. In my scenario, the source file is on a Linux based NAS.

Have kinda the same build: win10 PC with Atom, Intel NUC with Ubuntu inside, Samba share between them. On Ubuntu Docker provides the setup. Using babel watch to compile js files from src to dist folder(gulp does that every time the src files have changed), right after babel made work and gulp setup files mode to 755, I got the red window with the error. Every time. Very annoying.

**Comment by titovanton** [comment]
> It has no recognizable effect on anything that I can see. Is there a way to ignore this and not display the red box?


very good point! With the fix of that bug, I would love to see a feature, which hides all similar errors in a future by clicking corresponding button.

**Comment by JesterEE** [comment]
> It has no recognizable effect on anything that I can see.  Is there a way to ignore this and not display the red box?
> 
> 

It impacts the automatic reloading of files.

**Comment by TomMargrave** [comment]
> It impacts the file watch process for when a file changes outside of the editor.

There should be some type of wait limit set or number of errors before raising to user.

**Comment by icecream17** [comment]
not stale
