### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.45.0\res...

### ISSUE THREAD

**Issue by MHayato39** [atom/atom#20579]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\USER\AppData\Local\atom\app-1.45.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:160

Error: The specified module could not be found.
\\?\C:\Users\USER\AppData\Local\atom\app-1.45.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:1:721712)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:2784203)
    at get_manager (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:2784305)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:2784431)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1083896)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1251844)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1249829)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:284496)
```

### Commands

```
     -5:53.1.0 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
atom-terminal 0.8.0 
japanese-menu 1.14.0 
language-latex 1.2.0 
language-latexsimple 0.12.1 
latexer 0.3.0 
linter 2.3.1 
linter-gcc 0.9.0 
linter-ruby 1.3.1 
pdf-view 0.72.0 
platformio-ide-terminal 2.10.0 
project-manager 3.3.8 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
