### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat '~/Documents\experimental\physics'

### ISSUE THREAD

**Issue by MalfunctioningRobots** [atom/atom#20573]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat 'C:\Users\26afa\Documents\experimental\physics'

```
At fs.js:115

Error: EPERM: operation not permitted, lstat 'C:\Users\26afa\Documents\experimental\physics'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1005297)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1012226)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:985857)
```

### Commands

```
  4x -1:07.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
com.games.src.main 0.0.0 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
