### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\w3c-validation\READM...

### ISSUE THREAD

**Issue by R3Mbr4ND** [atom/atom#20581]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Владислав\.atom\packages\w3c-validation\README.md'

```
At fs.js:115

Error: ENOENT: no such file or directory, open 'C:\Users\Владислав\.atom\packages\w3c-validation\README.md'
    at Object.openSync (fs.js:436:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
    at Proxy.readFileSync (fs.js:341:35)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:580:40)
    at PackageDetailView.renderReadme (<embedded>:14:825951)
    at PackageDetailView.updateInstalledState (<embedded>:14:825711)
    at <embedded>:14:826582
    at Function.simpleDispatch (<embedded>:11:1214120)
    at Emitter.emit (<embedded>:11:1215561)
    at PackageManager.emitPackageEvent (<embedded>:11:945159)
    at <embedded>:11:942291
    at r (<embedded>:11:936821)
    at n (<embedded>:14:1125047)
    at t.bufferStream (<embedded>:14:1125201)
    at Socket.e.on (<embedded>:14:1123803)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)

```

### Commands

```
 26x -7:44.7.0 core:backspace (input.hidden-input)
  3x -7:33.9.0 core:confirm (input.hidden-input)
     -3:41.9.0 core:backspace (input.hidden-input)
     -3:36.8.0 core:confirm (input.hidden-input)
     -1:12 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-bootstrap4 1.4.0 
atom-console 0.4.6 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-ternjs 0.20.0 
autocomplete 0.47.0 
autoprefixer 4.2.0 
busy-signal 2.0.1 
color-picker 2.3.0 
editorconfig 2.6.0 
emmet 2.4.3 
file-icons 2.1.40 
git-plus 8.7.1 
hyperclick 0.1.5 
intentions 1.1.5 
jquery-snippets 11.0.0 
linter 2.3.1 
linter-bootlint 1.1.9 
linter-csslint 2.0.6 
linter-eslint 8.5.5 
linter-htmlhint 1.6.3 
linter-jshint 3.1.19 
linter-stylelint 4.5.0 
linter-ui-default 1.8.1 
linter-write-good 0.9.3 
minimap 4.29.9 
minimap-linter 2.2.1 
platformio-ide-terminal 2.10.0 
remote-ftp 2.2.4 
w3c-validation 0.4.0 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
