### ISSUE TITLE
Uncaught Error: Could not call remote function 'emit'. Check that the function signature is correct. Underlying error: Invalid template for MenuItem: must have at least one of label, role or type

### ISSUE THREAD

**Issue by trymeouteh** [atom/atom#20591]
Uncaught Error: Could not call remote function 'emit'. Check that the function signature is correct. Underlying error: Invalid template for MenuItem: must have at least one of label, role or type

```
/app/share/atom/resources/electron.asar/renderer/api/remote.js:222
Show Stack Trace
```
This is likely a bug in Atom. This issue has already been reported.

I always get this error message when I right click in the Atom editor. I am using Atom 1.45.0 on Linux Mint 19.3 using the Atom Flatpak.

**Comment by dohkoo** [comment]
I am having the same issue. Any solutions yet?

**Comment by trymeouteh** [comment]
I switched over to the DEB installer and I still have this issue.

**Comment by gazambuja** [comment]
Same here, when I make a right click on some spelling error, I get the error:

**Atom**: 1.47.0-beta0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Could not call remote function 'emit'. Check that the function signature is correct. Underlying error: Invalid template for MenuItem: must have at least one of label, role or type

```
At /Applications/Atom Beta.app/Contents/Resources/electron.asar/renderer/api/remote.js:222

Error: Could not call remote function 'emit'. Check that the function signature is correct. Underlying error: Invalid template for MenuItem: must have at least one of label, role or type
    at callFunction (/Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/rpc-server.js:260:17)
    at /Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/rpc-server.js:411:10
    at EventEmitter.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/rpc-server.js:275:21)
    at EventEmitter.emit (events.js:194:13)
    at WebContents.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/api/web-contents.js:420:21)
    at WebContents.emit (events.js:194:13)

```

### Commands

```
  3x -0:35 sublime-word-navigation:move-to-beginning-of-word (input.hidden-input)
     -0:34.3.0 core:move-right (input.hidden-input)
  2x -0:34 core:backspace (input.hidden-input)
     -0:33.5.0 intentions:highlight (input.hidden-input)
     -0:33.3.0 sublime-word-navigation:move-to-end-of-word (input.hidden-input)
     -0:32.5.0 intentions:highlight (input.hidden-input)
  2x -0:32.4.0 sublime-word-navigation:move-to-end-of-word (input.hidden-input)
     -0:31.9.0 intentions:highlight (input.hidden-input)
     -0:31.8.0 sublime-word-navigation:move-to-beginning-of-word (input.hidden-input)
     -0:31.5.0 core:move-left (input.hidden-input)
  3x -0:31.2.0 sublime-word-navigation:select-to-end-of-word (input.hidden-input)
     -0:29.7.0 intentions:highlight (input.hidden-input)
     -0:29.6.0 core:select-left (input.hidden-input)
     -0:29.2.0 core:backspace (input.hidden-input)
     -0:27.4.0 core:move-right (input.hidden-input)
     -0:27.1.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-runner 2.7.1 
atom-wrap-in-tag 0.6.0 
auto-update-plus 0.5.8 
browse 2.6.2 
build 0.70.0 
busy-signal 2.0.1 
city-lights-icons 1.1.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
ctrl-dir-scroll 0.2.5 
highlight-selected 0.17.0 
indent-guide-ext 0.2.3 
intentions 1.1.5 
linter 2.3.1 
linter-jsonlint 1.4.0 
linter-ui-default 1.8.1 
minimap 4.29.9 
multi-cursor 3.0.0 
pretty-json 2.1.2 
python-indent 1.2.6 
rainbow-tabs 2.5.1 
satisfy-dependencies 0.4.2 
set-syntax 0.4.0 
sublime 0.5.0 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.5 
sublime-word-navigation 0.2.1 
sublimify 0.10.0 
tag 0.5.0 
text-manipulation 0.6.0 
website-minifier 1.4.0 
wordcount 3.2.0 
```

<img width="565" alt="Screen Shot 2020-05-28 at 10 51 39" src="https://user-images.githubusercontent.com/278550/83150084-42f23500-a0d1-11ea-8e81-a280fb67ad52.png">

**Comment by icecream17** [comment]
not stale

**Comment by webuxr** [comment]
Not stale.
Same issue here on Mac OS 11.6.5 Big Sur with Atom 1.60.0 (Electron: 9.4.4, Chrome: 83.0.4103.122, Node: v12.14.1).

`Uncaught Error: Could not call remote method 'emit'. Check that the method signature is correct. Underlying error: Invalid template for MenuItem: must have at least one of label, role or type Underlying stack: TypeError: Invalid template for MenuItem: must have at least one of label, role or type at Function.u.buildFromTemplate (electron/js2c/browser_init.js:73:4668) at new ContextMenu (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/context-menu.js:7:23) at BrowserWindow. (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/atom-window.js:185:14) at BrowserWindow.emit (events.js:223:5) at electron/js2c/browser_init.js:233:7839 at IpcMainImpl. (electron/js2c/browser_init.js:233:4244) at IpcMainImpl.emit (events.js:223:5) at WebContents. (electron/js2c/browser_init.js:173:8760) at WebContents.emit (events.js:223:5)`

`electron/js2c/renderer_init.js:83`

`Error: Could not call remote method 'emit'. Check that the method signature is correct. Underlying error: Invalid template for MenuItem: must have at least one of label, role or type
Underlying stack: TypeError: Invalid template for MenuItem: must have at least one of label, role or type
    at Function.u.buildFromTemplate (electron/js2c/browser_init.js:73:4668)
    at new ContextMenu (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/context-menu.js:7:23)
    at BrowserWindow.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/atom-window.js:185:14)
    at BrowserWindow.emit (events.js:223:5)
    at electron/js2c/browser_init.js:233:7839
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:233:4244)
    at IpcMainImpl.emit (events.js:223:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:173:8760)
    at WebContents.emit (events.js:223:5)
    at electron/js2c/browser_init.js:233:7867
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:233:4244)
    at IpcMainImpl.emit (events.js:223:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:173:8760)
    at WebContents.emit (events.js:223:5)`

Error invoked via right-click in any (in my case, a simple HTML) file.

Would be nice to see a solution for this.

Thank you!
