### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by spcanelon** [atom/atom#20593]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:76051)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:75983)
    at TextEditorComponent.renderContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:74509)
    at TextEditorComponent.renderScrollContainer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:73969)
    at TextEditorComponent.render (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:72748)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:132897)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:70606)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.didShow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:91682)
    at TextEditorComponent.didFocus (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:91873)
    at HTMLElement.addEventListener.event (/app.asar/src/text-editor-element.js:37:27)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:164:16)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:455685)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:457933)
    at TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1165207)
```

### Commands

```
     -2:37.7.0 markdown-preview:toggle (input.hidden-input)
     -2:29.7.0 core:copy (div.markdown-preview.has-selection)
  2x -0:49.6.0 markdown-preview:toggle (div.markdown-preview.has-selection)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-language-r 1.4.8 
file-icons 2.1.40 
highlight-selected 0.17.0 
ide-r 0.1.8 
pigments 0.40.2 
todo 0.6.0 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by Navigatron** [comment]
I've just had this happen to me as well. Atom's error message says that the bug has already been reported, and links to this page.

At the time, I had a markdown file open. I:

- Opened markdown-preview-enhanced
- Closed markdown-preview-enhanced
- Switched focus to a different window (a zoom meeting)
- Re-sized the zoom window to be larger, which:
- Re-sized the atom window to be smaller
    - I assume that this triggered the scroll event in the stack trace
- Two identical error messages appear in the upper-right corner of the window

Attempting to click into the atom window caused another error message to appear. I have the contents of the *second* message below. The contents of the *third*, from clicking into atom, were identical, but the "commands" section was empty. Unfortunately I do not have the contents of the first message.

This is the first time I have seen this error after many years of use (and many months with this package set). I understand that this may not be worth investigating due to its rarity, but I would like to document this trace here anyways in the hope it might help in the future.

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: "Arch Linux"
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /usr/lib/atom/src/text-editor-component.js:698

TypeError: Cannot read property 'id' of undefined
    at /usr/lib/atom/src/text-editor-component.js:698:42
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (/usr/lib/atom/src/text-editor-component.js:694:37)
    at TextEditorComponent.renderContent (/usr/lib/atom/src/text-editor-component.js:622:12)
    at TextEditorComponent.renderScrollContainer (/usr/lib/atom/src/text-editor-component.js:596:12)
    at TextEditorComponent.render (/usr/lib/atom/src/text-editor-component.js:541:14)
    at Object.updateSync (/usr/lib/atom/node_modules/etch/lib/component-helpers.js:119:34)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/lib/atom/src/text-editor-component.js:409:10)
    at TextEditorComponent.updateSync (/usr/lib/atom/src/text-editor-component.js:279:10)
    at TextEditorComponent.didMouseWheel (/usr/lib/atom/src/text-editor-component.js:1735:12)
```

### Commands

```
     -8:54.6.0 core:backspace (input.hidden-input)
     -8:54 editor:move-to-end-of-screen-line (input.hidden-input)
  8x -8:51.9.0 core:backspace (input.hidden-input)
  2x -8:13.6.0 editor:newline (input.hidden-input)
  2x -8:11.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-ide-ui 0.13.0 
autosave-onchange 1.5.1 
dracula-syntax 3.0.2 
firacode 0.3.0 
ide-rust 0.22.0-beta.3 
language-babel 2.85.0 
language-docker 1.1.8 
language-dot 1.7.0 
language-ini 1.23.0 
language-latex 1.2.0 
language-nginx 0.8.0 
livestyle-atom 0.2.10 
markdown-preview-enhanced 0.18.9 
pdf-view 0.72.0 
teletype 0.13.4 
wordcount 3.2.0 
zotero-citations 5.2.0 
```

**Comment by spcanelon** [comment]
> Thanks for reaching out!
> 
> We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.
> 
> Thanks for understanding and meeting us half way 😀

😱 I am mortified that I opened this issue and didn't follow up! I was new to GitHub then -- thanks for being so kind @darangi. I haven't used Atom for Markdown editing since April 2020 and don't remember what my experience was, so unfortunately I can't amend the original issue to see if it aligns with the experience @Navigatron is having.

**Comment by lenora2468B** [comment]
I am still hoping to learn in any case. :)
