### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/y1/cycmyb8x40j1t0x_pg22w55h0000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by softloga** [atom/atom#20609]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/y1/cycmyb8x40j1t0x_pg22w55h0000gn/T/AppTranslocation/B7AD2810-9517-47F2-937A-0ABC0669CB31/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): no suitable image found.  Did find:
	/private/var/folders/y1/cycmyb8x40j1t0x_pg22w55h0000gn/T/AppTranslocation/B7AD2810-9517-47F2-937A-0ABC0669CB31/d/Atom.app/Contents/Resources/app.asar.unpacked: not a file

```
At ELECTRON_ASAR.js:160

Error: dlopen(/private/var/folders/y1/cycmyb8x40j1t0x_pg22w55h0000gn/T/AppTranslocation/B7AD2810-9517-47F2-937A-0ABC0669CB31/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): no suitable image found.  Did find:
	/private/var/folders/y1/cycmyb8x40j1t0x_pg22w55h0000gn/T/AppTranslocation/B7AD2810-9517-47F2-937A-0ABC0669CB31/d/Atom.app/Contents/Resources/app.asar.unpacked: not a file
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/private/var/folders/y1/cycmyb8x40j1t0x_pg22w55h0000gn/T/AppTranslocation/B7AD2810-9517-47F2-937A-0ABC0669CB31/d/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at get_KeyboardLayoutManager (/private/var/folders/y1/cycmyb8x40j1t0x_pg22w55h0000gn/T/AppTranslocation/B7AD2810-9517-47F2-937A-0ABC0669CB31/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2781650)
    at get_manager (/private/var/folders/y1/cycmyb8x40j1t0x_pg22w55h0000gn/T/AppTranslocation/B7AD2810-9517-47F2-937A-0ABC0669CB31/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2781752)
    at Object.getCurrentKeyboardLayout (/private/var/folders/y1/cycmyb8x40j1t0x_pg22w55h0000gn/T/AppTranslocation/B7AD2810-9517-47F2-937A-0ABC0669CB31/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2781878)
    at e.keystrokeForKeyboardEvent (/private/var/folders/y1/cycmyb8x40j1t0x_pg22w55h0000gn/T/AppTranslocation/B7AD2810-9517-47F2-937A-0ABC0669CB31/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1083882)
    at KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/y1/cycmyb8x40j1t0x_pg22w55h0000gn/T/AppTranslocation/B7AD2810-9517-47F2-937A-0ABC0669CB31/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1251844)
    at KeymapManager.handleKeyboardEvent (/private/var/folders/y1/cycmyb8x40j1t0x_pg22w55h0000gn/T/AppTranslocation/B7AD2810-9517-47F2-937A-0ABC0669CB31/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1249829)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/y1/cycmyb8x40j1t0x_pg22w55h0000gn/T/AppTranslocation/B7AD2810-9517-47F2-937A-0ABC0669CB31/d/Atom.app/Contents/Resources/app/static/<embedded>:11:284496)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by lkashef** [comment]
Hey @softloga, thanks for the report!

This looks like an installation problem, did you try re-installing Atom?
