### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 370

### ISSUE THREAD

**Issue by davidfh34** [atom/atom#20612]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 370

```
At /Applications/Atom 2.app/Contents/Resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 370
    at throwRPCError (/Applications/Atom 2.app/Contents/Resources/electron.asar/browser/rpc-server.js:148:17)
    at /Applications/Atom 2.app/Contents/Resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (/Applications/Atom 2.app/Contents/Resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom 2.app/Contents/Resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
     -2:18.1.0 core:save (input.hidden-input)
     -2:01.5.0 core:cut (input.hidden-input)
     -1:59.8.0 core:paste (input.hidden-input)
     -1:58.3.0 core:save (input.hidden-input)
     -1:12.5.0 core:undo (input.hidden-input)
     -1:09.2.0 core:paste (input.hidden-input)
     -1:06.8.0 core:save (input.hidden-input)
     -0:38.6.0 core:cut (input.hidden-input)
     -0:38.3.0 core:backspace (input.hidden-input)
     -0:36.8.0 core:save (input.hidden-input)
     -0:30.5.0 core:paste (input.hidden-input)
     -0:27.8.0 core:save (input.hidden-input)
     -0:14.9.0 core:backspace (input.hidden-input)
 11x -0:14 core:move-right (input.hidden-input)
 18x -0:06.1.0 core:backspace (input.hidden-input)
     -0:01.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-i18n 0.23.0 
atom-ide-ui 0.13.0 
atom-json-color 0.6.0 
atom-minify 0.8.0 
color-indent 1.1.0 
color-picker 2.3.0 
config-import-export 0.3.1 
css-color-name 0.4.0 
dw-beta-syntax 0.1.5 
file-icons 2.1.40 
highlight-selected 0.17.0 
ide-php 0.7.18 
line-number-color 0.2.0 
minimap 4.29.9 
minimap-pigments 0.2.2 
php-cs-fixer 4.1.1 
pigments 0.40.2 
remote-ftp 2.2.4 
```

**Comment by sadick254** [comment]
Thank you for opening this issue. This was issue present in electron versions 4 and below. The latest atom version `v1.51.0` uses electron version `5.0.3`. The issue was fixed on this commit https://github.com/electron/electron/commit/a8f2646ba682d65f94ea628ac11b1a5521bcedcd. The fix has been available from electron version `5.0.0`. I would advice you to upgrade to the latest atom version. I am closing this for now but happy to reopen if you still experience the issue.
