### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getURI' of undefined

### ISSUE THREAD

**Issue by Ariurn** [atom/atom#20639]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getURI' of undefined

```
At C:\Users\ruvik\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'getURI' of undefined
    at items.find.t (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:463353)
    at Array.find (<anonymous>)
    at Pane.itemForURI (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:463324)
    at t (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:444966)
    at Function.findIndex (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1198987)
    at b.find.b.detect (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1195706)
    at PaneContainer.paneForURI (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:444937)
    at Dock.paneForURI (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:476868)
    at getPaneContainers.find.t (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:436132)
    at Array.find (<anonymous>)
    at Workspace.paneContainerForURI (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:436122)
    at TreeViewPackage.createOrDestroyTreeViewIfNeeded (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1180268)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1215561)
    at Project.addPath (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:410954)
    at confirm.n (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:1:749075)
    at CallbacksRegistry.apply (~/AppData/Local/atom/app-1.45.0/resources/electron.asar/renderer/callbacks-registry.js:47:25)
    at handleMessage (~/AppData/Local/atom/app-1.45.0/resources/electron.asar/renderer/api/remote.js:285:21)
    at EventEmitter.ipcRenderer.on.args (~/AppData/Local/atom/app-1.45.0/resources/electron.asar/renderer/api/remote.js:275:7)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -1:34.7.0 ftp-remote-edit:open-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:32.6.0 editor:fold-at-indent-level-1 (input.hidden-input)
```

### Non-Core Packages

```
ftp-remote-edit 0.18.0 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
