### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.45.0\ High A...

### ISSUE THREAD

**Issue by RumSpy** [atom/atom#20634]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Michael Hill\AppData\Local\atom\app-1.45.0\ High Availability - 2020 4 7 -1.png'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\Michael Hill\AppData\Local\atom\app-1.45.0\ High Availability - 2020 4 7 -1.png'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1005297)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1012226)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:985857)
```

### Commands

```
     -3:51.2.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -3:47.5.0 core:confirm (input.hidden-input)
  3x -3:16.8.0 tree-view:remove (span.name.icon.icon-file-directory)
     -2:17 tree-view:add-folder (span.name.icon.icon-file-directory)
 13x -2:13.6.0 core:backspace (input.hidden-input)
     -2:05.1.0 core:confirm (input.hidden-input)
     -2:00.2.0 tree-view:add-folder (span.name.icon.icon-file-directory)
 10x -1:55.7.0 core:move-left (input.hidden-input)
     -1:51.9.0 core:confirm (input.hidden-input)
     -1:48.1.0 tree-view:move (span.name.icon.icon-file-directory)
     -1:43.8.0 core:confirm (input.hidden-input)
     -1:37.9.0 tree-view:move (span.name.icon.icon-file-directory)
     -1:33.7.0 core:confirm (input.hidden-input)
     -1:21.6.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -1:14.6.0 core:confirm (input.hidden-input)
     -0:58.1.0 tree-view:remove (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-github-issues 0.4.3 
atom-github-notifications 0.3.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
better-git-blame 0.5.0 
busy-signal 2.0.1 
codestream 7.0.2 
create-github-repo 1.1.2 
git-diff-details 1.4.0 
git-menu 3.2.1 
git-plus 8.7.1 
git-status 0.3.4 
git-status-utils 0.2.0 
git-tools 0.5.0 
github-issue-blog 0.1.0 
github-search 0.1.0 
github-url-resolver 0.1.1 
github-user-datatip 0.3.2 
hey-pane 1.2.0 
imdone-atom-github 0.1.11 
intentions 1.1.5 
language-github-actions 0.1.0 
language-markdown 0.37.0 
language-plantuml 0.2.0 
linter 2.3.1 
linter-annotations 1.0.4 
linter-markdown 5.2.11 
linter-ui-default 1.8.1 
markdown-fold 0.3.0 
markdown-helper 0.3.0 
markdown-writer 2.11.10 
plantuml 0.1.2 
plantuml-toolkit 0.2.0 
plantuml-viewer 0.7.2 
pull-request 0.2.1 
quick-issues 0.9.3 
search-github 0.3.0 
snippet-creator 0.2.0 
split-diff 1.6.1 
tidy-markdown 3.0.1 
tool-bar 1.2.2 
tool-bar-markdown-writer 0.5.1 
tree-view-auto-fold 1.3.0 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.5.3 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
