### ISSUE TITLE
Atom build failed for macos

### ISSUE THREAD

**Issue by ZhangKejun** [atom/atom#20641]
zhangkkMAC:atom zhangkk$ script/bootstrap 
Node:	v10.2.1
Npm:	v6.14.4
Installing script dependencies
Installing apm
../src/repository.cc:242:17: warning: 'Call' is deprecated [-Wdeprecated-declarations]
      callback->Call(2, argv);
                ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/repository.cc:412:17: warning: 'Call' is deprecated [-Wdeprecated-declarations]
      callback->Call(2, argv);
                ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/repository.cc:749:17: warning: 'Call' is deprecated [-Wdeprecated-declarations]
      callback->Call(2, argv);
                ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
3 warnings generated.
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^

Error: read ECONNRESET
    at TLSWrap.onread (net.js:657:25)
/Users/zhangkk/github/atom/apm/node_modules/atom-package-manager/bin/apm: line 54: /Users/zhangkk/github/atom/apm/node_modules/atom-package-manager/bin/node: No such file or directory
child_process.js:624
    throw err;
    ^

Error: Command failed: /Users/zhangkk/github/atom/apm/node_modules/atom-package-manager/bin/apm --version
    at checkExecSyncError (child_process.js:603:11)
    at Object.execFileSync (child_process.js:621:13)
    at Object.<anonymous> (/Users/zhangkk/github/atom/script/bootstrap:39:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)

**Comment by darangi** [comment]
Hey @ZhangKejun, to resolve this, use node 12 to build atom
