### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/ and Everything.cpp'

### ISSUE THREAD

**Issue by Bab95** [atom/atom#20640]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/ and Everything.cpp'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat '/ and Everything.cpp'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1005283)
    at TreeView.onDrop (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1012212)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:985843)
```

### Commands

```
     -8:57 core:select-all (input.hidden-input)
     -8:56.6.0 core:copy (input.hidden-input)
     -1:24.7.0 application:new-file (input.hidden-input)
     -1:24.2.0 core:paste (input.hidden-input)
     -1:23.2.0 core:save (input.hidden-input)
     -0:27.1.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:23.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
