### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\x-terminal\README.md'

### ISSUE THREAD

**Issue by Lech69** [atom/atom#20680]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Laura\.atom\packages\x-terminal\README.md'

```
At fs.js:115

Error: ENOENT: no such file or directory, open 'C:\Users\Laura\.atom\packages\x-terminal\README.md'
    at Object.openSync (fs.js:436:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
    at Proxy.readFileSync (fs.js:341:35)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:580:40)
    at PackageDetailView.renderReadme (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:825951)
    at PackageDetailView.updateInstalledState (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:825711)
    at ~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:826582
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1215561)
    at PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:945159)
    at ~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:942291
    at r (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:936821)
    at n (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1125047)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1125253)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
```

### Non-Core Packages

```
apm-publish 0.3.2 
atom-ide-ui 0.13.0 
atom-linter-node-dependencies 1.5.0 
atom-terminal-powershell 1.1.0 
build-powershell 0.12.1 
busy-signal 2.0.1 
debugger 0.0.1 
eferet-atom-active-editor-info 1.2.1 
find-dependencies 1.1.0 
git-time-metric 1.1.8 
Hydrogen 2.14.1 
ide-json 0.2.1 
ide-livescript 0.2.0 
ide-powershell 0.1.0 
kite 0.180.0 
language-powershell 5.0.0 
livescript-ide 0.0.2 
livescript-ide-preview 0.5.0 
livescript-ide-timetracker 0.0.1 
package-dependencies 0.1.2 
process-palette 0.17.0 
satisfy-dependencies 0.4.2 
script 3.26.0 
teletype 0.13.4 
x-terminal 8.1.7 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
