### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.45.0\sort 01...

### ISSUE THREAD

**Issue by ghost** [atom/atom#20687]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\psys0s\AppData\Local\atom\app-1.45.0\sort 01.py'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\psys0s\AppData\Local\atom\app-1.45.0\sort 01.py'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1005297)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1012226)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:985857)
```

### Commands

```
     -4:41.1.0 Python run: run-f6 (input.hidden-input)
 11x -4:16.7.0 core:backspace (input.hidden-input)
     -3:56.1.0 Python run: run-f6 (input.hidden-input)
     -3:43.8.0 core:backspace (input.hidden-input)
     -3:42 Python run: run-f6 (input.hidden-input)
 33x -3:29.3.0 core:move-right (input.hidden-input)
     -3:23.2.0 Python run: run-f6 (input.hidden-input)
  7x -3:12.6.0 core:backspace (input.hidden-input)
     -3:08.4.0 editor:newline (input.hidden-input)
  3x -3:02.1.0 core:backspace (input.hidden-input)
     -2:58.2.0 Python run: run-f6 (input.hidden-input)
     -2:33.5.0 tree-view:move (span.name.icon.icon-file-text)
     -2:26.3.0 core:backspace (input.hidden-input)
     -2:20.4.0 core:confirm (input.hidden-input)
     -1:18.7.0 tree-view:add-folder (span.name.icon.icon-file-text)
     -1:11.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.7 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed on the `master` branch. It is currently scheduled for release when `v1.53.0` reaches Stable.
