### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 9342

### ISSUE THREAD

**Issue by AndreaGProg** [atom/atom#20699]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 9342

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 9342
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:148:17)
    at /Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
     -2:06.0 core:copy (input.hidden-input)
  2x -2:03.3.0 editor:newline (input.hidden-input)
     -2:02.8.0 core:move-up (input.hidden-input)
     -2:02.5.0 core:paste (input.hidden-input)
     -2:02.0 core:save (input.hidden-input)
     -1:32.4.0 editor:newline (input.hidden-input)
  2x -1:29 core:move-left (input.hidden-input)
     -1:26.7.0 core:save (input.hidden-input)
     -1:16.4.0 core:backspace (input.hidden-input)
  2x -1:16 datatip:toggle (input.hidden-input)
  5x -1:12.1.0 core:backspace (input.hidden-input)
     -1:10 core:move-right (input.hidden-input)
     -1:09.1.0 core:save (input.hidden-input)
     -0:52.4.0 core:copy (input.hidden-input)
     -0:51.1.0 core:paste (input.hidden-input)
  2x -0:50.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.5.3 
atom-typescript 12.3.3 
remote-ftp 2.2.2 
```

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

---

It might be worth upgrading to the latest stable version, at the time of this comment it's 1.46, also disabling community packages (via running in safe mode would be helpful as well)
