### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\emmet\README.md'

### ISSUE THREAD

**Issue by Ratnadeep-Paul** [atom/atom#20742]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Ratnadeep Paul\.atom\packages\emmet\README.md'

```
At fs.js:115

Error: ENOENT: no such file or directory, open 'C:\Users\Ratnadeep Paul\.atom\packages\emmet\README.md'
    at Object.openSync (fs.js:436:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
    at Proxy.readFileSync (fs.js:341:35)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:580:40)
    at PackageDetailView.renderReadme (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:826156)
    at PackageDetailView.updateInstalledState (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:825916)
    at PackageDetailView.populate (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:824468)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:819808)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:820020)
    at new PackageDetailView (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:816606)
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:959123)
    at SettingsView.showPanel (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:959844)
    at HTMLButtonElement.clickHandler (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:2636706)
```

### Commands

```
     -4:09.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
emmet 2.4.3 
```

**Comment by darangi** [comment]
Thanks for reporting this!

This has already been fixed on `master`. It is currently scheduled for release when `v1.53.0` reaches Stable.
