### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Pictures\mountain.png'

### ISSUE THREAD

**Issue by kibebew2020** [atom/atom#20751]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\kibeb\Pictures\mountain.png'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\kibeb\Pictures\mountain.png'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1002525)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1009698)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:983085)
```

### Commands

```
 14x -4:58.3.0 core:backspace (input.hidden-input)
     -4:13.6.0 core:save (input.hidden-input)
     -1:18.6.0 tree-view:remove (span.name.icon.icon-file-media)
```

### Non-Core Packages

```
atom-beautifier 0.5.0 
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-formatter-jsbeautify 1.1.2 
atom-justify 0.4.1 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-prettify 0.1.3 
atom-pug 0.2.0 
atom-stylus-supremacy 0.7.0 
atom-umlautify 0.2.0 
beautifier-istyle 0.2.0 
beautify-handlebars 1.0.3 
cssbeautify 1.3.0 
devmind-beautifier 1.3.0 
es-beautifier 1.1.0-atom 
format-shell 2.2.1 
formatter-jsbeautify 1.0.2 
hey-pane 1.2.0 
Hydrogen 2.14.1 
jade-beautify 0.1.5 
notify-atom 0.5.1 
open-project-file 1.1.1 
project-find-filter-defaults 3.0.0 
project-manager 3.3.8 
sassbeautify 0.2.0 
scroll-through-time 0.3.1 
Snippets-Atom-Vuetify 1.3.1 
teletype 0.13.4 
tree-view-menu 1.2.1 
unityscript-beautifier 0.2.0 
vue-template-beautify 0.1.2 
zentabs 0.8.9 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
