### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 156

### ISSUE THREAD

**Issue by qoneqo** [atom/atom#20752]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.12
**OS**: "Arch Linux"
**Thrown From**: Atom Core
**User**: root

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 156

```
At /usr/lib/electron4/resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 156
    at throwRPCError (/usr/lib/electron4/resources/electron.asar/browser/rpc-server.js:148:17)
    at /usr/lib/electron4/resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (/usr/lib/electron4/resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/lib/electron4/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
  2x -1:55.9.0 core:move-up (input.hidden-input)
     -1:48 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:48 editor:newline (input.hidden-input)
     -1:46.1.0 emmet:expand-abbreviation (input.hidden-input)
     -1:45 emmet:insert-formatted-line-break-only (input.hidden-input)
  2x -1:44.2.0 core:move-down (input.hidden-input)
  3x -1:43.5.0 core:select-down (input.hidden-input)
  2x -1:42.8.0 editor:move-line-up (input.hidden-input)
     -1:42.2.0 core:move-down (input.hidden-input)
     -1:41.8.0 core:cut (input.hidden-input)
     -1:41.5.0 core:save (input.hidden-input)
     -1:14 core:select-left (input.hidden-input)
     -1:13.8.0 core:backspace (input.hidden-input)
     -1:13.4.0 core:save (input.hidden-input)
  2x -0:11 core:undo (input.hidden-input)
     -0:09.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
auto-softwrap 1.0.1 
emmet 2.4.3 
language-blade 0.41.4 
laravel 0.7.1 
rain-syntax 2.1.2 
rain-ui 1.0.1 
```

**Comment by sadick254** [comment]
Thank you @qoneqo  for opening this issue. This was issue present in electron versions 4 and below. The latest atom version `v1.51.0` uses electron version `5.0.3`. The issue was fixed on this commit https://github.com/electron/electron/commit/a8f2646ba682d65f94ea628ac11b1a5521bcedcd. The fix has been available from electron version `5.0.0`. I would advice you to upgrade to the latest atom version. I am closing this for now but happy to reopen if you still experience the issue.
