### ISSUE TITLE
Uncaught Error: Cannot find module 'jconv'

### ISSUE THREAD

**Issue by bozhiraken** [atom/atom#20759]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.4
**Thrown From**: [utf8-to-sjis](https://github.com/atom/utf8-to-sjis) package 0.1.0

### Stack Trace

Uncaught Error: Cannot find module 'jconv'

```
At internal/modules/cjs/loader.js:586

Error: Cannot find module 'jconv'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/utf8-to-sjis/lib/utf8-to-sjis.coffee:2:9)
    at /packages/utf8-to-sjis/lib/utf8-to-sjis.coffee:1:1)
    at /packages/utf8-to-sjis/lib/utf8-to-sjis.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3197086)
    at Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3186374)
    at PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:937044)
    at PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2648133)
    at PackageCard.updateSettingsState (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2638413)
    at PackageCard.updateInterfaceState (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2638236)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2646366
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2648384
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1215907)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1217348)
    at PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:946501)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:943633
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:938163)
    at o (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1122261)
    at t.bufferStream (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1122415)
    at Socket.e.on (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1121017)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)
```

### Commands

```
     -2:31.4.0 encoding-selector:show (atom-text-editor.editor.is-focused)
  3x -2:26.2.0 core:backspace (input.hidden-input)
  2x -2:22.9.0 core:undo (input.hidden-input)
     -2:18.5.0 encoding-selector:show (atom-text-editor.editor.is-focused)
     -2:10.7.0 core:save-as (input.hidden-input)
     -1:24.6.0 core:close (input.hidden-input)
 10x -0:29.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
git-plus 8.7.1 
japanese-menu 1.15.0 
markdown-image-paste 2.5.2 
markdown-to-pdf 0.1.1 
utf8-to-sjis 0.1.0 
web-search 0.3.3 
```

**Comment by sadick254** [comment]
@bozhiraken Try updating to the latest atom version and confirm if the error is still showing. We no longer use [utf8-to-sjis](https://github.com/atom/utf8-to-sjis) in atom. I am going to close this for now.
