### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by GggggitHub** [atom/atom#20778]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

RangeError: Maximum call stack size exceeded
    at ResultRowGroup.generateRows (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1871826)
    at new ResultRowGroup (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1870856)
    at ResultsView.didAddResult (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:575575)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at ResultsModel.addResult (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:800728)
    at ResultsModel.setResult (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:800616)
    at inProgressSearchPromise.atom.workspace.scan (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:798277)
    at didMatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:440010)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:43716
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:42817)
    at ChildProcess.emit (events.js:182:13)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
     -0:30.9.0 project-find:show (atom-pane.pane.active)
     -0:29.5.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by Marcosffn** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Pop!_OS 20.04
**Thrown From**: Atom Core


### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /usr/share/atom/resources/app/static/<embedded>:11

RangeError: Maximum call stack size exceeded
    at BufferSearch.bufferStoppedChanging (/usr/share/atom/resources/app/static/<embedded>:11:751097)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1215561)
    at TextBuffer.emitDidStopChangingEvent (/usr/share/atom/resources/app/static/<embedded>:11:504974)
    at later (/usr/share/atom/resources/app/static/<embedded>:14:104450)
```

### Commands

```
     -3:26 core:move-up (input.hidden-input)
     -3:25.1.0 snippets:next-tab-stop (input.hidden-input)
     -3:25.1.0 snippets:expand (input.hidden-input)
     -3:25.1.0 editor:indent (input.hidden-input)
     -3:17.5.0 editor:newline (input.hidden-input)
     -2:39.5.0 core:backspace (input.hidden-input)
     -2:34.7.0 autocomplete-plus:confirm (input.hidden-input)
     -2:32.4.0 intentions:highlight (input.hidden-input)
     -2:32.3.0 core:paste (input.hidden-input)
     -2:26.2.0 core:move-left (input.hidden-input)
     -2:23 intentions:highlight (input.hidden-input)
     -2:22.9.0 core:save (input.hidden-input)
     -1:51.8.0 core:move-left (input.hidden-input)
     -1:48.1.0 autocomplete-plus:confirm (input.hidden-input)
     -1:47.7.0 intentions:highlight (input.hidden-input)
     -1:47.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-bracket-highlight 0.3.2 
autocomplete 0.47.0 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
file-icons 2.1.42 
highlight-selected 0.17.0 
Hydrogen 2.14.4 
intentions 1.1.5 
kite 0.185.0 
linter 2.3.1 
linter-flake8 2.4.0 
linter-ui-default 1.8.1 
platformio-ide-terminal 2.10.0 
python-autopep8 0.1.3 
Sublime-Style-Column-Selection 1.7.5 
```
