### ISSUE TITLE
Uncaught Error: The module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modu...

### ISSUE THREAD

**Issue by eli-stewart** [atom/atom#20776]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Unknown macOS version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/oniguruma/build/Release/onig_scanner.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 70. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

Error: The module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/oniguruma/build/Release/onig_scanner.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 70. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /app.asar/node_modules/oniguruma/src/oniguruma.js:3:21)
    at /app.asar/node_modules/oniguruma/src/oniguruma.js:116:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at get_OnigRegExp (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:560449)
    at TreeSitterLanguageMode.regexForPattern (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:560508)
    at TreeSitterLanguageMode.decreaseIndentRegexForScopeDescriptor (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:559999)
    at TreeSitterLanguageMode.suggestedIndentForEditedBufferRow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:551098)
    at TextEditor.autoDecreaseIndentForBufferRow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:58863)
    at Selection.insertText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:539496)
    at s.mutateSelectedText.n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:15695)
    at getSelectionsOrderedByBufferPosition.map (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16220)
    at Array.map (<anonymous>)
    at transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16209)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:492516)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
```

### Commands

```
     -1:36 tree-view:duplicate (span.name.icon.icon-file-text)
     -1:07.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by GSThina** [comment]
This just happened to me, immediately when I upgraded my TypeScript.

Just a quick restart of Atom helped me to overcome this. 

I believe, restarting is opening up with all the newly updated version.

Maybe an auto-refresh can be performed when there is a version change.

**Comment by sadick254** [comment]
@GSThina Thank you for letting us know that the issue has been resolved. I encourage you to open an issue describing the auto-refresh feature you are suggesting in the comment. For now I will close this and mark it as resolved.

**Comment by andrewpavlenko** [comment]
I got the same issue but with `nslog` package. Seems like the right explanation why in happens is here: #19646
As I understand it right, atom ships with it's own nodejs distribution and running `script/bootstrap` will install packages using that own npm version, so that version mismatch happens when atom binary was compiled using nodejs version different from that one, that is in current sources.
