### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by mpeters2** [atom/atom#20784]
[Enter steps to reproduce:]

1. ...Not sure when it occurred, but it now occurs whenever I try to start Julia.
2. ...I had been trying to debug a simple Tk program I was porting from Python

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Unknown macOS version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:160

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2778162)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2778264)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2778390)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1081110)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1253631)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1251616)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284744)
```

### Commands

```
     -6:45.9.0 julia-client:start-julia (a.stack-toggle)
     -1:12.7.0 julia:get-help (summary.welcome-summary.icon.icon-package)
```

### Non-Core Packages

```
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.12.3 
julia-client 0.12.4 
kite 0.184.0 
language-julia 0.19.3 
latex-completions 0.3.6 
tool-bar 1.2.2 
uber-juno 0.3.0 
```

**Comment by fourtotheside** [comment]
Got same error, clicked "About," got a prompt to upgrade to 1.47.0.  No error.  Good job, team.

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

---

Could you try a re-install and start atom in a safe mode? this could be a conflict between Atom Core and Community Packages or an installation problem.
