### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by vfilby** [atom/atom#20807]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: 10.15.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:160

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2778162)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2778264)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2778390)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1081110)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1253631)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1251616)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284744)
```

### Commands

```
     -4:08.9.0 command-palette:toggle (input.hidden-input)
     -3:56.1.0 settings-view:install-packages-and-themes (input.hidden-input)
     -1:31.7.0 symbols-view:toggle-file-symbols (div.package-detail)
     -1:24.8.0 core:close (div.package-detail)
     -1:20.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-ide-ui 0.13.0 
atom-typescript 13.6.0 
atom-yarn 0.9.0 
autocomplete 0.47.0 
autocomplete-python 1.16.0 
file-icons 2.1.41 
kite 0.184.0 
language-graphql 1.0.0 
minimap 4.29.9 
package-script-runner 1.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
script 3.26.0 
select-rectangle 1.0.2 
todo-show 2.3.2 
```

**Comment by vfilby** [comment]
Note, updated to 1.47 and this seems to have disappeared.
