### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'C:/ProgramData\LENOVO\atom\app-1.46.0\s...

### ISSUE THREAD

**Issue by oissakah** [atom/atom#20860]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\ProgramData\LENOVO\atom\app-1.46.0\startbootstrap-resume-gh-pages'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\ProgramData\LENOVO\atom\app-1.46.0\startbootstrap-resume-gh-pages'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (C:/ProgramData/LENOVO/atom/app-1.46.0/resources/app/static/<embedded>:14:1002525)
    at TreeView.onDrop (C:/ProgramData/LENOVO/atom/app-1.46.0/resources/app/static/<embedded>:14:1009698)
    at HTMLDivElement.<anonymous> (C:/ProgramData/LENOVO/atom/app-1.46.0/resources/app/static/<embedded>:14:983085)
```

### Commands

```
     -7:33.8.0 tree-view:paste (div.tool-panel.tree-view)
```

### Non-Core Packages

```

```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
