### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rubens29** [atom/atom#20867]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Linux Mint
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /opt/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/opt/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (/opt/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (/opt/atom/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/opt/atom/resources/app/src/text-editor-component.js:881:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/opt/atom/resources/app/src/text-editor-component.js:385:16)
    at TextEditorComponent.updateSync (/opt/atom/resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didShow (/opt/atom/resources/app/src/text-editor-component.js:1471:18)
    at TextEditorComponent.didFocus (/opt/atom/resources/app/src/text-editor-component.js:1495:35)
    at HTMLElement.addEventListener (/app.asar/src/text-editor-element.js:36:67)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:164:16)
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.setActiveItem (/opt/atom/resources/app/src/pane.js:443:26)
    at Pane.activateItemAtIndex (/opt/atom/resources/app/src/pane.js:566:23)
    at Pane.activatePreviousItem (/opt/atom/resources/app/src/pane.js:530:18)
    at Pane.removeItem (/opt/atom/resources/app/src/pane.js:702:20)
    at Pane.destroyItem (/opt/atom/resources/app/src/pane.js:783:16)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-material-ui 2.1.3 
autocomplete-java 1.2.7 
autocomplete-paths 2.12.2 
autoprefixer 3.7.1 
color-picker 2.3.0 
data-atom 0.29.1 
docblockr 0.13.7 
emmet 2.4.3 
file-icons 2.1.40 
goto-definition 1.3.4 
highlight-selected 0.17.0 
hyperlink-hyperclick 3.0.1 
linter 2.3.1 
merge-conflicts 1.4.5 
minimap-highlight-selected 4.6.1 
php-cs-fixer 4.1.1 
php-getters-setters 0.5.9 
php-integrator-autocomplete-plus 1.6.2 
remote-sync 4.1.8 
tool-bar 1.3.0 
```

**Comment by fensterhebel** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Linux Mint
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /opt/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/opt/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (/opt/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (/opt/atom/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/opt/atom/resources/app/src/text-editor-component.js:881:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/opt/atom/resources/app/src/text-editor-component.js:385:16)
    at TextEditorComponent.updateSync (/opt/atom/resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didShow (/opt/atom/resources/app/src/text-editor-component.js:1471:18)
    at TextEditorComponent.didAttach (/opt/atom/resources/app/src/text-editor-component.js:1438:20)
    at HTMLElement.attachedCallback (/app.asar/src/text-editor-element.js:41:25)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:152:22)
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.setActiveItem (/opt/atom/resources/app/src/pane.js:443:26)
    at Pane.activateItem (/opt/atom/resources/app/src/pane.js:583:18)
    at TabBarView.module.exports.TabBarView.onClick (/opt/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:721:25)
```

### Commands

```
     -4:35.9.0 application:open-file (input.hidden-input)
  3x -4:25.4.0 editor:newline (input.hidden-input)
     -4:24.4.0 core:paste (input.hidden-input)
     -4:12.5.0 core:save (input.hidden-input)
     -3:34.8.0 core:close (input.hidden-input)
     -3:23.2.0 core:paste (input.hidden-input)
     -3:02.3.0 core:save (input.hidden-input)
     -3:02.1.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.5.3 
atom-runner 2.7.1 
atom-typescript 12.5.3 
grammar-token-limit 0.1.1 
language-latex 1.2.0 
language-scheme 1.4.0 
language-speedata-publisher 3.9.16 
language-vue 0.25.0 
lint-sass-vue 1.0.5 
linter 2.3.1 
linter-autocomplete-jing 0.8.4 
pretty-json 2.1.2 
```
