### ISSUE TITLE
Uncaught TypeError: setTimeout(...).unref is not a function

### ISSUE THREAD

**Issue by daviemakz** [atom/atom#20907]
Steps to reproduce:

1. When I'm just using the editor I randomly get this error, it appears like clockwork roughly every 1-2 minutes. Sometimes shorter and sometimes longer

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: setTimeout(...).unref is not a function

```
At /Users/davidmakuni/dev/outlook-property-frontend/node_modules/applicationinsights/out/Library/Sender.js:100

TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (/Users/davidmakuni/dev/outlook-property-frontend/node_modules/applicationinsights/out/Library/Sender.js:100:117)
    at IncomingMessage.emit (events.js:199:15)
    at endReadableNT (_stream_readable.js:1141:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

### Commands

```
     -2:48.8.0 core:copy (input.hidden-input)
     -2:47.9.0 core:paste (input.hidden-input)
     -2:45.9.0 core:save (input.hidden-input)
  3x -2:45.6.0 linter:lint (atom-text-editor.editor.is-focused)
     -2:42.1.0 core:copy (input.hidden-input)
  2x -2:40.8.0 core:paste (input.hidden-input)
     -2:38.9.0 core:copy (input.hidden-input)
     -2:37.9.0 editor:newline (input.hidden-input)
     -2:37.6.0 core:paste (input.hidden-input)
     -2:36.6.0 core:copy (input.hidden-input)
  2x -2:35.6.0 core:paste (input.hidden-input)
     -2:34 core:save (input.hidden-input)
     -2:25.9.0 core:backspace (input.hidden-input)
  2x -2:23.9.0 core:save (input.hidden-input)
     -2:21.2.0 linter:lint (atom-text-editor.editor.is-focused.hyperclick)
  3x -2:09.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-typescript 13.6.0 
autocomplete-modules 2.3.0 
autocomplete-paths 2.12.2 
busy-signal 2.0.1 
case-keep-replace 0.6.2 
copy-filename 1.2.0 
file-type-icons 1.3.4 
highlight-selected 0.17.0 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.19.0 
language-babel 2.85.0 
less-than-slash 0.19.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-tslint 1.10.43 
linter-ui-default 1.8.1 
minimap 4.29.9 
minimap-autohide 0.10.1 
minimap-find-and-replace 4.5.2 
minimap-lens 0.3.0 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
pigments 0.40.2 
prettier-atom 0.60.0 
self-closing-tag 0.2.1 
toggle-quotes 1.1.4 
tree-view-copy-relative-path 1.2.0 
turbo-javascript 1.4.0 
```

**Comment by aminya** [comment]
This can be fixed by using: 
```
const { setTimeout } = require('timers')
```

Why is this related to Atom? I don't think this is thrown by Atom 🤔 

What is `outlook-property-frontend` project?

**Comment by daviemakz** [comment]
Thanks for replying. Yes it turns out to be caused by the package "applicationinsights". Reinstalling fixed it, closing the issue :)
