### ISSUE TITLE
Failed to activate the cmd-9 package

### ISSUE THREAD

**Issue by darkness91** [atom/atom#20902]
1. Try to install cmd-9 package
2. Getting error: 

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: 'cmd-9' package vundefined

### Stack Trace

Failed to activate the cmd-9 package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.exports.activate (/packages/cmd-9/index.js:4:13)
    at Package.activateNow (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3298513)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3297925
    at Package.measure (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3295535)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3297785
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3297728)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:382738)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:926575
    at r (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:921181)
    at n (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:1063434)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:1063588
    at Socket.<anonymous> (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:1062190)
    at Socket.emit (events.js:199:15)
    at Pipe.<anonymous> (net.js:593:12)
```

### Commands

```
```

### Non-Core Packages

```
cmd-9 0.0.3 
open_in_cmd 0.6.1 
```

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: 'cmd-9' package vundefined

### Stack Trace

Failed to activate the cmd-9 package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.exports.activate (/packages/cmd-9/index.js:4:13)
    at Package.activateNow (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3298513)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3297925
    at Package.measure (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3295535)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3297785
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3297728)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:382738)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:926575
    at r (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:921181)
    at n (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:1063434)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:1063588
    at Socket.<anonymous> (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:1062190)
    at Socket.emit (events.js:199:15)
    at Pipe.<anonymous> (net.js:593:12)
```

### Commands

```
```

### Non-Core Packages

```
cmd-9 0.0.3 
open_in_cmd 0.6.1 
```

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [cmd-9](https://atom.io/packages/cmd-9) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
