### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.47.0\ Female...

### ISSUE THREAD

**Issue by FRIARGREG** [atom/atom#20904]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\friar\AppData\Local\atom\app-1.47.0\ Female Cat Caster.txt'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'C:\Users\friar\AppData\Local\atom\app-1.47.0\ Female Cat Caster.txt'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:943665)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:950594)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:924225)
```

### Commands

```
     -3:48.7.0 core:confirm (input.hidden-input)
     -3:42.4.0 tree-view:add-folder (div.tool-panel.tree-view)
     -3:39.7.0 core:confirm (input.hidden-input)
     -3:38.4.0 tree-view:copy (div.tool-panel.tree-view)
     -3:36.4.0 tree-view:paste (div.tool-panel.tree-view)
     -2:19.4.0 tree-view:move (div.tool-panel.tree-view)
  2x -2:17.2.0 core:confirm (input.hidden-input)
     -2:06.9.0 core:cancel (input.hidden-input)
     -2:04.2.0 tree-view:move (div.tool-panel.tree-view)
     -2:01.3.0 core:confirm (input.hidden-input)
     -1:54.1.0 tree-view:add-folder (div.tool-panel.tree-view)
     -1:50.8.0 core:confirm (input.hidden-input)
     -1:29.4.0 tree-view:remove (div.tool-panel.tree-view)
     -0:50.2.0 tree-view:collapse-directory (div.tool-panel.tree-view)
     -0:48.4.0 tree-view:add-folder (div.tool-panel.tree-view)
     -0:43 core:confirm (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
