### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.48.0\bootstr...

### ISSUE THREAD

**Issue by BartGraaf1** [atom/atom#20921]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Bartg\AppData\Local\atom\app-1.48.0\bootstrap-4.4.1-dist'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'C:\Users\Bartg\AppData\Local\atom\app-1.48.0\bootstrap-4.4.1-dist'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:943665)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:950838)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:924225)
```

### Commands

```
     -5:32 project-find:show-in-current-directory (span.name.icon.icon-file-directory)
     -5:29.8.0 tree-view:show-in-file-manager (span.name.icon.icon-file-directory)
     -5:28.9.0 tree-view:copy (div.tool-panel.tree-view)
     -5:19.3.0 core:copy (input.hidden-input)
     -0:52.9.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:49.5.0 core:confirm (input.hidden-input)
     -0:47.6.0 tree-view:remove (div.tool-panel.tree-view)
     -0:41.8.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:40.6.0 core:confirm (input.hidden-input)
     -0:35.7.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:33.5.0 core:confirm (input.hidden-input)
     -0:31.7.0 core:delete (input.hidden-input)
     -0:31.5.0 editor:newline (input.hidden-input)
     -0:30.3.0 tree-view:remove (div.tool-panel.tree-view)
     -0:26 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:25 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
language-blade 0.43.1 
platformio-ide-terminal 2.9.4 
```

**Comment by harunayyildiz** [comment]
remove from rar and try

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
