### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/NRTNN_C_LEMM_20190823022020_2019082300...

### ISSUE THREAD

**Issue by veda-sunkara** [atom/atom#20951]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/NRTNN_C_LEMM_20190823022020_20190823001422_20190823001900_o_v200_l2sm.nc'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat '/NRTNN_C_LEMM_20190823022020_20190823001422_20190823001900_o_v200_l2sm.nc'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:943663)
    at TreeView.onDrop (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:950592)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:924223)
```

### Commands

```
  3x -7:45.4.0 core:backspace (input.hidden-input)
     -7:42.2.0 core:confirm (input.hidden-input)
     -6:06.8.0 editor:newline (input.hidden-input)
  2x -6:05.1.0 core:backspace (input.hidden-input)
     -6:03.9.0 core:save (input.hidden-input)
     -6:02.8.0 core:move-right (input.hidden-input)
  2x -2:03.5.0 core:backspace (input.hidden-input)
     -0:47.5.0 core:save (div.tool-panel.tree-view)
```

### Non-Core Packages

```

```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
