### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\LocalLow\1CGS\Caliber\SystemC...

### ISSUE THREAD

**Issue by DanilGet** [atom/atom#20960]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Майкрософт Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Homeb\AppData\LocalLow\1CGS\Caliber\SystemCfg_v2\ папки и интернет-хранилище-Библиотеки'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\Homeb\AppData\LocalLow\1CGS\Caliber\SystemCfg_v2\ папки и интернет-хранилище-Библиотеки'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:1005063)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:1011992)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:985623)
```

### Commands

```
```

### Non-Core Packages

```
teletype 0.13.4 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
