### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.48.0\ and JS...

### ISSUE THREAD

**Issue by SavageNo0b** [atom/atom#20964]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\vasin\AppData\Local\atom\app-1.48.0\ and JS - Full Reference'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'C:\Users\vasin\AppData\Local\atom\app-1.48.0\ and JS - Full Reference'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:943665)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:950594)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:924225)
```

### Commands

```
     -0:27 tree-view:add-file (div.tool-panel.tree-view)
     -0:25.6.0 core:cancel (input.hidden-input)
     -0:23.3.0 tree-view:add-folder (div.tool-panel.tree-view)
     -0:20.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
pigments 0.40.2 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
