### ISSUE TITLE
Uncaught Error: Cannot get property 'id' on missing remote object 35

### ISSUE THREAD

**Issue by jjcmjavascript** [atom/atom#20985]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot get property 'id' on missing remote object 35

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:222

Error: Cannot get property 'id' on missing remote object 35
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:148:17)
    at /usr/share/atom/resources/electron.asar/browser/rpc-server.js:428:5
    at EventEmitter.ipcMain.on.args (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
     -5:00.9.0 ftp-remote-edit:open-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -4:53.3.0 find-and-replace:show (input.hidden-input)
     -4:52.4.0 core:confirm (input.hidden-input)
  2x -4:48.3.0 core:copy (input.hidden-input)
     -4:47.7.0 find-and-replace:show (input.hidden-input)
     -4:40.3.0 core:paste (input.hidden-input)
     -4:40 core:save (input.hidden-input)
     -4:40 find-and-replace:select-next (input.hidden-input)
     -0:14 ftp-remote-edit:open-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-typescript 13.6.1 
atom-vue 0.6.0 
dvnk-icons 1.8.2 
ftp-remote-edit 0.18.0 
hyperclick 0.0.0 
hyperclick-php 0.3.0 
ide-typescript 0.9.1 
js-hyperclick 1.19.0 
language-ejs 0.4.0 
mark 1.3.3 
react 0.18.0 
vue-atom-snippets 1.2.0 
vue-hyperclick 0.2.0 
```

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
