### ISSUE TITLE
Failed to activate the atom-ide-terminal package

### ISSUE THREAD

**Issue by RuslanIurevich** [atom/atom#20982]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Debian GNU/Linux
**Thrown From**: [atom-ide-terminal](https://github.com/qicrosoft/atom-ide-terminal) package 5.0.1

### Stack Trace

Failed to activate the atom-ide-terminal package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'pio-terminal-status-icon'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'pio-terminal-status-icon'. A type with that name is already registered.
    at /packages/atom-ide-terminal/lib/status-icon.coffee:100:27)
    at /packages/atom-ide-terminal/lib/status-icon.coffee:1:1)
    at /packages/atom-ide-terminal/lib/status-icon.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147503)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146819)
    at /packages/atom-ide-terminal/lib/status-bar.coffee:5:14)
    at /packages/atom-ide-terminal/lib/status-bar.coffee:1:1)
    at /packages/atom-ide-terminal/lib/status-bar.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147503)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146819)
    at Object.consumeStatusBar (/packages/atom-ide-terminal/lib/atom-ide-terminal.coffee:11:27)
    at Provider.provide (/usr/share/atom/resources/app/static/<embedded>:14:1060525)
    at ServiceHub.consume (/usr/share/atom/resources/app/static/<embedded>:11:3185317)
    at Package.activateServices (/usr/share/atom/resources/app/static/<embedded>:11:3193549)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3190304)
    at /usr/share/atom/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1201460)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1202901)
    at /usr/share/atom/resources/app/static/<embedded>:11:383238
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:383200)
    at /usr/share/atom/resources/app/static/<embedded>:11:378114
    at Array.forEach (<anonymous>)
    at /usr/share/atom/resources/app/static/<embedded>:11:378098
    at /usr/share/atom/resources/app/static/<embedded>:11:335149
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1201460)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1202901)
    at Config.emitChangeEvent (/usr/share/atom/resources/app/static/<embedded>:11:337637)
    at Config.setRawValue (/usr/share/atom/resources/app/static/<embedded>:11:334877)
    at Config.set (/usr/share/atom/resources/app/static/<embedded>:11:330671)
    at Config.removeAtKeyPath (/usr/share/atom/resources/app/static/<embedded>:11:332694)
    at Package.enable (/usr/share/atom/resources/app/static/<embedded>:11:3187023)
    at PackageManager.enablePackage (/usr/share/atom/resources/app/static/<embedded>:11:375812)
    at HTMLButtonElement.enablementButtonClickHandler (/usr/share/atom/resources/app/static/<embedded>:14:2530876)
```

### Commands

```
     -2:22.8.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-file-icons 0.7.1 
atom-ide-terminal 5.0.1 
busy-signal 2.0.1 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.8.1 
minimap 4.29.9 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
texter 0.1.0 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
