### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.48.0\lib'

### ISSUE THREAD

**Issue by Abdallah2997** [atom/atom#20998]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Abdallah\AppData\Local\atom\app-1.48.0\lib'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'C:\Users\Abdallah\AppData\Local\atom\app-1.48.0\lib'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:943665)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:950838)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:924225)
```

### Commands

```
     -4:21.5.0 editor:newline (input.hidden-input)
     -4:03.3.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -4:03.3.0 editor:newline (input.hidden-input)
     -4:02.9.0 intentions:highlight (input.hidden-input)
     -4:02.8.0 editor:toggle-line-comments (input.hidden-input)
  4x -3:54 core:move-right (input.hidden-input)
     -3:52.9.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -3:52.9.0 editor:newline (input.hidden-input)
     -3:48.1.0 autocomplete-plus:confirm (input.hidden-input)
     -3:48.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
 15x -3:46 core:move-right (input.hidden-input)
     -3:43.5.0 core:move-left (input.hidden-input)
     -3:15.3.0 intentions:highlight (input.hidden-input)
     -3:15 core:copy (input.hidden-input)
     -3:05.5.0 intentions:highlight (input.hidden-input)
     -3:05.1.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-live-server 2.3.0 
atom-monokai 0.10.9 
busy-signal 2.0.1 
codeigniter 0.4.0 
emmet 2.4.3 
file-icons 2.1.41 
html-to-javascript 0.2.0 
intentions 1.1.5 
javascript-snippets 1.2.1 
linter 2.3.1 
linter-jshint 3.1.19 
linter-ui-default 1.8.1 
minimap 4.29.9 
minimap-pigments 0.2.2 
pigments 0.40.2 
seti-classic 0.10.3 
seti-dark-monokai 0.1.0 
seti-syntax 1.2.0 
seti-ui 1.11.0 
seti-ui-red 0.13.0 
seti-vs-syntax 0.1.1 
teletype 0.13.4 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
