### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\sync-settings\README...

### ISSUE THREAD

**Issue by hemanth05921** [atom/atom#21048]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\heman\.atom\packages\sync-settings\README.md'

```
At fs.js:115

Error: ENOENT: no such file or directory, open 'C:\Users\heman\.atom\packages\sync-settings\README.md'
    at Object.openSync (fs.js:436:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
    at Proxy.readFileSync (fs.js:341:35)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:580:40)
    at PackageDetailView.renderReadme (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:826156)
    at PackageDetailView.updateInstalledState (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:825916)
    at PackageDetailView.populate (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:824468)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:819808)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:820020)
    at ~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:826771
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:1215907)
    at Emitter.emit (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:1217348)
    at PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:946501)
    at ~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:943633
    at r (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:938163)
    at o (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1122275)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1122481)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
  3x -1:40.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
sync-settings 4.3.5 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
