### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/ divide by .cpp'

### ISSUE THREAD

**Issue by parthmshah1302** [atom/atom#21068]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 20.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/parth/ divide by .cpp'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat '/home/parth/ divide by .cpp'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (/usr/share/atom/resources/app/static/<embedded>:14:943663)
    at TreeView.onDrop (/usr/share/atom/resources/app/static/<embedded>:14:950592)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:924223)
```

### Commands

```
     -0:43.2.0 core:select-all (input.hidden-input)
     -0:43 core:copy (input.hidden-input)
     -0:36.4.0 core:backspace (input.hidden-input)
     -0:31.7.0 tree-view:add-file (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:30.8.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
autocomplete-python 1.16.0 
gpp-compiler 3.0.7 
python-tools 0.6.9 
script 3.26.0 
teletype 0.13.4 
```

**Comment by therobgirl** [comment]
I'm just so confused but also so interesting 🧐
