### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.0.80:80...

### ISSUE THREAD

**Issue by rk-puvvada** [atom/atom#21072]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.0.80:80 - Local (10.197.184.250:50809)

```
At internal/streams/legacy.js:57

Error: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.0.80:80 - Local (10.197.184.250:50809)
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:282:20)
    at ClientRequest.emit (events.js:194:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:194:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

### Commands

```
```

### Non-Core Packages

```
atom-file-icons 0.7.1 
```

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
