### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Documents/Web Development/Images'

### ISSUE THREAD

**Issue by Alhinds85** [atom/atom#21084]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/andrehinds/Documents/Web Development/Images'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat '/Users/andrehinds/Documents/Web Development/Images'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (/Users/andrehinds/Documents/Atom.app/Contents/Resources/app/static/<embedded>:14:943628)
    at TreeView.onDrop (/Users/andrehinds/Documents/Atom.app/Contents/Resources/app/static/<embedded>:14:950836)
    at HTMLDivElement.<anonymous> (/Users/andrehinds/Documents/Atom.app/Contents/Resources/app/static/<embedded>:14:924223)
```

### Commands

```
     -9:47.1.0 tree-view:remove (div.tool-panel.tree-view)
 17x -9:27.2.0 core:backspace (input.hidden-input)
     -8:56.6.0 core:save (input.hidden-input)
     -7:18.9.0 core:backspace (input.hidden-input)
     -7:16.3.0 core:save (input.hidden-input)
     -7:13.5.0 atom-beautify:beautify-editor (input.hidden-input)
     -7:09.3.0 atom-beautify:help-debug-editor (input.hidden-input)
 10x -6:33.3.0 core:backspace (input.hidden-input)
     -1:19.4.0 core:save (input.hidden-input)
     -1:16.6.0 atom-beautify:beautify-editor (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
