### ISSUE TITLE
Unable to build with nodejs > 12.16 due to ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by michaellass** [atom/atom#21091]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

atom fails to build with nodejs versions newer than 10 (e.g., 12 or 14).

### Steps to Reproduce

1. install nodejs 12 or higher
2. run `script/build --ci`

**Expected behavior:**

build script should run without errors.

**Actual behavior:**

```
internal/modules/cjs/loader.js:498
  throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
  ^

[Error [ERR_PACKAGE_PATH_NOT_EXPORTED] [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/helper-compilation-targets/package.json
  at applyExports (internal/modules/cjs/loader.js:498:9)
  at resolveExports (internal/modules/cjs/loader.js:514:23)
  at Function.Module._findPath (internal/modules/cjs/loader.js:642:31)
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1017:27)
  at Function.Module._load (internal/modules/cjs/loader.js:899:27)
  at Module.require (internal/modules/cjs/loader.js:1090:19)
  at require (internal/modules/cjs/helpers.js:75:18)
  at Object.<anonymous> (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/preset-env/lib/debug.js:8:33)
  at Module._compile (internal/modules/cjs/loader.js:1201:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
  at Module.load (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (internal/modules/cjs/loader.js:938:14)
  at Module.require (internal/modules/cjs/loader.js:1090:19)
  at require (internal/modules/cjs/helpers.js:75:18)
  at Object.<anonymous> (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/preset-env/lib/index.js:11:14)
  at Module._compile (internal/modules/cjs/loader.js:1201:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
  at Module.load (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (internal/modules/cjs/loader.js:938:14)
  at Module.require (internal/modules/cjs/loader.js:1090:19)
  at require (internal/modules/cjs/helpers.js:75:18)
  at requireModule (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
  at loadPreset (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/core/lib/config/files/plugins.js:83:17)
  at createDescriptor (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
  at /opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
  at Array.map (<anonymous>:null:null)
  at createDescriptors (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
  at createPresetDescriptors (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
  at presets (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
  at mergeChainOpts (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-chain.js:320:26)
  at /opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-chain.js:283:7
  at buildRootChain (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-chain.js:120:22)
  at loadPrivatePartialConfig (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/core/lib/config/partial.js:85:55)
  at loadFullConfig (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/core/lib/config/full.js:43:39)
  at Object.transformSync (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@babel/core/lib/transform.js:41:38)
  at /opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@atom/babel7-transpiler/lib/index.js:54:28
  at withBabelEnv (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@atom/babel7-transpiler/lib/index.js:18:15)
  at Object.transpile (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/out/app/node_modules/github/node_modules/@atom/babel7-transpiler/lib/index.js:53:12)
  at PackageTranspilationRegistry.transpileWithPackageTranspiler (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/src/package-transpilation-registry.js:158:33)
  at Object.compile (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/src/package-transpilation-registry.js:59:23)
  at compileFileAtPath (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/src/compile-cache.js:109:31)
  at Object.exports.addPathToCache (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/src/compile-cache.js:82:14)
  at transpilePath (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/script/lib/transpile-packages-with-custom-transpiler-paths.js:86:18)
  at Array.forEach (<anonymous>:null:null)
  at module.exports (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/script/lib/transpile-packages-with-custom-transpiler-paths.js:64:24)
  at Object.<anonymous> (/opt/local/var/macports/build/_Users_lass_ports_editors_atom/atom/work/atom-atom-1d0abfa/script/build:75:3)
  at Module._compile (internal/modules/cjs/loader.js:1201:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
  at Module.load (internal/modules/cjs/loader.js:1050:32)
  at Function.Module._load (internal/modules/cjs/loader.js:938:14)
  at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
  at internal/main/run_main_module.js:17:47
] {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Reproduces how often:**

100%

### Versions

macOS 10.15.6
XCode 11.6
npm: 6.14.6

Tested nodejs versions:

Working:
* v10.21.0

Not working:
* v14.5.0
* v12.18.2

### Additional Information

The problem seems to be this one: https://github.com/babel/babel/issues/11216

The solution would be to update all @babel packages to at least 7.8.7 (or at least 7.8.4 based on another comment in that bugreport).

**Comment by michaellass** [comment]
Full build output:
[atom-build-fail.log](https://github.com/atom/atom/files/4948955/atom-build-fail.log)

**Comment by michaellass** [comment]
I was able to build atom with nodejs v10.21.0, so the issue only occurs with higher versions (e.g., 12 or 14). I update the bug report accordingly.

**Comment by DeeDeeG** [comment]
Hi. I ran into this problem also. I wanted to add: I believe this requires newer babel (7.8.7 or newer), because the way babel was working before a certain release conflicts with a change in recent Node.

https://github.com/babel/babel/issues/11216

Affected versions of Node:

- 12.17.0 and newer (can use 12.16.x and older)
- 13.2.0 and newer (can use 13.0.0? I think.)
- 14.0.0 and newer (all versions 14.0.0 and newer are affected).

<details><summary>More details (click to expand):</summary>

Node 12.16.x is the most-recent version of Node 12 we can use without running into this:
https://github.com/babel/babel/issues/11216
Todo: Upgrade babel to 7.8.7 or newer, everywhere in Atom, so we can use newer Node.

Happens due to: ECMAScript Modules feature in Node, conflicting with something babel does.
https://github.com/nodejs/node/pull/29866

Earliest affected version for each major version since v12.x, when this was first introduced:
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.17.0
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V13.md#13.2.0
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.0.0

</details>

**Comment by aminya** [comment]
I added the support for ES6 default require in https://github.com/atom/atom/pull/21112, and then in https://github.com/atom/atom/pull/20965 I added the support for babel 7. To make this work I had to update Electron Link in https://github.com/atom/electron-link/pull/26 and https://github.com/atom/electron-link/pull/27. 
 
I am testing the babel 7 builds in our fork at https://github.com/atom-ide-community/atom/pull/67#issuecomment-663995431, if you are interested to look at.

**Comment by DeeDeeG** [comment]
@michaellass please consider changing the issue title to have "> 12.16", because Node 12 below that version can indeed be used. Thanks, and best regards.
