### ISSUE TITLE
Uncaught TypeError: Cannot read property 'minimapForEditor' of null

### ISSUE THREAD

**Issue by midiisc** [atom/atom#21099]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Linux Mint
**Thrown From**: 'minimap-lens' package vundefined

### Stack Trace

Uncaught TypeError: Cannot read property 'minimapForEditor' of null

```
At /home/midhun/.atom/packages/minimap-lens/lib/minimap-lens.js:148

TypeError: Cannot read property 'minimapForEditor' of null
    at MinimapLens.showLens (/packages/minimap-lens/lib/minimap-lens.js:148:34)
    at MinimapLens.onMouseEnter (/packages/minimap-lens/lib/minimap-lens.js:100:12)
```

### Commands

```
     -5:42.6.0 core:backspace (input.hidden-input)
     -5:42.4.0 core:confirm (input.hidden-input)
     -4:30.7.0 editor:consolidate-selections (input.hidden-input)
     -4:30.7.0 core:cancel (input.hidden-input)
     -4:27.4.0 core:confirm (input.hidden-input)
  3x -4:13.2.0 core:backspace (input.hidden-input)
     -3:35.4.0 core:confirm (input.hidden-input)
  4x -3:29.2.0 core:backspace (input.hidden-input)
  4x -3:26.7.0 core:confirm (input.hidden-input)
 15x -2:52.4.0 core:backspace (input.hidden-input)
     -2:48.7.0 core:confirm (input.hidden-input)
     -1:43.7.0 pane:split-up-and-copy-active-item (a.link)
     -1:32.4.0 pane:close (div.item-views)
     -1:17.7.0 application:open-your-keymap (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -0:37.4.0 intentions:highlight (input.hidden-input)
  2x -0:36.6.0 toggle-gutter:gutter (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-folding 0.0.9 
atom-ide-ui 0.13.0 
atom-latex 0.9.1 
atom-python-run 0.9.7 
atom-python-virtualenv 1.0.4 
atom-reveal-md 1.0.0 
autoclose-html 0.23.0 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
color-picker 2.3.0 
dbg 1.6.3 
dbg-gdb 1.7.8 
emmet 2.4.3 
git-plus 8.7.1 
gpp-compiler 3.0.7 
hey-pane 1.2.0 
highlight-selected 0.17.0 
Hydrogen 2.14.4 
hyperclick 0.1.5 
ide-python 1.5.0 
indent-detective 0.4.0 
ink 0.12.4 
intentions 1.1.5 
julia-client 0.12.5 
juno-plus 0.12.2 
language-hlsl 1.2.0 
language-julia 0.19.3 
language-latex 1.2.0 
latex-completions 0.3.6 
latex-folding 1.5.0 
latex-tree 0.5.0 
latex-wordcount 0.6.0 
linter 2.3.1 
linter-gcc 0.9.0 
linter-julia 0.8.3 
linter-ui-default 1.8.1 
linter-xmllint 1.4.4 
markdown-mindmap 0.6.2 
markdown-writer 2.11.10 
minimap 4.29.9 
minimap-autohider 1.6.0 
minimap-find-and-replace 4.5.2 
minimap-pigments 0.2.2 
output-panel 0.3.4 
pdf-view 0.72.0 
pigments 0.40.2 
python-debugger 0.2.0 
python-indent 1.2.6 
python-run-terminalnx 1.1.7 
python-tools 0.6.9 
revealjs-atom-snippets 0.1.4 
state-machine-cat-preview 4.6.13 
termination 0.7.6 
toggle-gutter 0.3.4 
tool-bar 1.3.0 
tool-bar-markdown-writer 0.5.1 
uber-juno 0.3.0 
xml-formatter 0.13.0 
Zen 0.18.0 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
