### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.49.0\res...

### ISSUE THREAD

**Issue by LDSgeek115** [atom/atom#21127]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\Hadi Chehayeb\AppData\Local\atom\app-1.49.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:138

Error: The specified module could not be found.
\\?\C:\Users\Hadi Chehayeb\AppData\Local\atom\app-1.49.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:1:735013)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:2676864)
    at get_manager (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:2676966)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:2677092)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:1022283)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1239383)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1237368)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:284830)
```

### Commands

```
     -1:03.4.0 core:save-as (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
Hydrogen 2.9.0 
zentabs 0.8.9 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
