### ISSUE TITLE
Не скачивается atomsetup.exe

### ISSUE THREAD

**Issue by please-helpme1515** [atom/atom#21136]
Короче, решил я установить Atom 1.49 (последняя версия, доступная на данный момент на сайте). И когда открывал установщик - сразу выдает ошибку CLR20r3  Update.exe , весь интернет облазил, не нашел нужной темы, которая решает мою проблему , прошу помочь мне.
Логи: (squirrelsetup)
5280> 2020-05-22 14:09:49> Program: Starting Squirrel Updater: --install .
5280> 2020-05-22 14:09:50> Program: Starting install, writing to C:\Users\jagaur\AppData\Local\SquirrelTemp
5280> 2020-05-22 14:09:50> Program: About to install to: C:\Users\jagaur\AppData\Local\Discord
5280> 2020-05-22 14:09:50> SingleGlobalInstance: Grabbing lockfile with timeout of 00:00:10
5280> 2020-05-22 14:09:50> CheckForUpdateImpl: Reading RELEASES file from C:\Users\jagaur\AppData\Local\SquirrelTemp
5280> 2020-05-22 14:09:50> CheckForUpdateImpl: Remote version 0.0.306 differs from local 
5280> 2020-05-22 14:09:50> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
5280> 2020-05-22 14:09:51> ApplyReleasesImpl: Writing files to app directory: C:\Users\jagaur\AppData\Local\Discord\app-0.0.306
5280> 2020-05-22 14:09:57> ApplyReleasesImpl: Moving file C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\lib\net45\app.ico to C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\app.ico
5280> 2020-05-22 14:09:57> ApplyReleasesImpl: Moving file C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\lib\net45\chrome_100_percent.pak to C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\chrome_100_percent.pak
5280> 2020-05-22 14:09:57> ApplyReleasesImpl: Moving file C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\lib\net45\chrome_200_percent.pak to C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\chrome_200_percent.pak
5280> 2020-05-22 14:09:57> ApplyReleasesImpl: Moving file C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\lib\net45\d3dcompiler_47.dll to C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\d3dcompiler_47.dll
5280> 2020-05-22 14:09:57> ApplyReleasesImpl: Moving file C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\lib\net45\Discord.exe to C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\Discord.exe
5280> 2020-05-22 14:09:57> ApplyReleasesImpl: Moving file C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\lib\net45\ffmpeg.dll to C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\ffmpeg.dll
5280> 2020-05-22 14:09:57> ApplyReleasesImpl: Moving file C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\lib\net45\icudtl.dat to C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\icudtl.dat
5280> 2020-05-22 14:09:57> ApplyReleasesImpl: Moving file C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\lib\net45\libEGL.dll to C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\libEGL.dll
5280> 2020-05-22 14:09:57> ApplyReleasesImpl: Moving file C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\lib\net45\libGLESv2.dll to C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\libGLESv2.dll
5280> 2020-05-22 14:09:57> ApplyReleasesImpl: Moving file C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\lib\net45\resources.pak to C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\resources.pak
5280> 2020-05-22 14:09:57> ApplyReleasesImpl: Moving file C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\lib\net45\natives_blob.bin to C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\natives_blob.bin
5280> 2020-05-22 14:09:57> ApplyReleasesImpl: Moving file C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\lib\net45\snapshot_blob.bin to C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\snapshot_blob.bin
5280> 2020-05-22 14:09:57> ApplyReleasesImpl: Moving file C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\lib\net45\Squirrel.exe to C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\Squirrel.exe
5280> 2020-05-22 14:09:57> ApplyReleasesImpl: Moving file C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\lib\net45\v8_context_snapshot.bin to C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\v8_context_snapshot.bin
5280> 2020-05-22 14:10:00> ApplyReleasesImpl: Started updateSelf pid 2156
5280> 2020-05-22 14:10:03> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\Discord.exe]
5280> 2020-05-22 14:10:04> Utility: Process Started: C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\Discord.exe --squirrel-install 0.0.306, pid 4416
5280> 2020-05-22 14:10:17> Utility: Received exitcode 0 from process C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\Discord.exe
5280> 2020-05-22 14:10:17> ApplyReleasesImpl: ran C:\Users\jagaur\AppData\Local\Discord\app-0.0.306\Discord.exe, pid 2584
5280> 2020-05-22 14:10:17> ApplyReleasesImpl: Starting fixPinnedExecutables
5280> 2020-05-22 14:10:17> ApplyReleasesImpl: fixPinnedExecutables: newCurrentFolder: app-0.0.306
5280> 2020-05-22 14:10:17> ApplyReleasesImpl: fixPinnedExecutables: enumerating path C:\Users\jagaur\AppData\Roaming\Microsoft\Windows\Start Menu failed: System.UnauthorizedAccessException: Access to the path 'C:\Users\jagaur\AppData\Roaming\Microsoft\Windows\Start Menu\Программы' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, SearchOption searchOption)
   at Squirrel.UpdateManager.ApplyReleasesImpl.fixPinnedExecutables(SemanticVersion newCurrentVersion)
5280> 2020-05-22 14:10:17> ApplyReleasesImpl: Updating shortcut C:\Users\jagaur\Desktop\Discord.lnk
5280> 2020-05-22 14:10:17> ApplyReleasesImpl: Fixing up tray icons
5280> 2020-05-22 14:10:17> ApplyReleasesImpl: cleanDeadVersions: for version 0.0.306
5280> 2020-05-22 14:10:17> ApplyReleasesImpl: cleanDeadVersions: exclude current version folder app-0.0.306
2020-07-31 10:23:23> Program: Starting Squirrel Updater: --install .
2020-07-31 10:23:25> Program: Starting install, writing to C:\Users\jagaur\AppData\Local\SquirrelTemp
2020-07-31 10:23:26> Program: About to install to: C:\Users\jagaur\AppData\Local\Figma
2020-07-31 10:23:27> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Не удалось найти часть пути "C:\Users\jagaur\AppData\Local\Figma\packages\.betaId".
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   в System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   в System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   в System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   в Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2020-07-31 10:23:27> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Не удалось найти часть пути "C:\Users\jagaur\AppData\Local\Figma\packages\RELEASES".
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   в Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   в Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2020-07-31 10:23:27> CheckForUpdateImpl: Reading RELEASES file from C:\Users\jagaur\AppData\Local\SquirrelTemp
2020-07-31 10:23:28> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2020-07-31 10:23:29> ApplyReleasesImpl: Writing files to app directory: C:\Users\jagaur\AppData\Local\Figma\app-86.5.0
2020-07-31 10:23:33> LogHost: Rigging execution stub for Figma_ExecutionStub.exe to C:\Users\jagaur\AppData\Local\Figma\Figma.exe
2020-07-31 10:23:41> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\jagaur\AppData\Local\Figma\app-86.5.0\Figma.exe]
2020-07-31 10:23:49> ApplyReleasesImpl: Starting fixPinnedExecutables
2020-07-31 10:23:49> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2020-07-31 10:23:49> ApplyReleasesImpl: Examining Pin: Internet Explorer (2).lnk
2020-07-31 10:23:49> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2020-07-31 10:23:49> ApplyReleasesImpl: Examining Pin: samp.lnk
2020-07-31 10:23:49> ApplyReleasesImpl: Examining Pin: Windows Explorer (2).lnk
2020-07-31 10:23:49> ApplyReleasesImpl: Examining Pin: Windows Explorer.lnk
2020-07-31 10:23:49> ApplyReleasesImpl: Examining Pin: Windows Media Player (2).lnk
2020-07-31 10:23:49> ApplyReleasesImpl: Examining Pin: Windows Media Player.lnk
2020-07-31 10:23:49> ApplyReleasesImpl: Examining Pin: Диспетчер задач Windows.lnk
2020-07-31 10:23:49> ApplyReleasesImpl: Fixing up tray icons
2020-07-31 10:23:50> ApplyReleasesImpl: cleanDeadVersions: for version 86.5.0
2020-07-31 10:23:50> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-86.5.0

Прошу заметить, %appdata% local / atom пустой , в нем только два файла update exe и еще папка одна

**Comment by sadick254** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
