### ISSUE TITLE
Building Atom

### ISSUE THREAD

**Issue by jeff-hykin** [atom/atom#21137]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

As usual, its an issue with node-gyp

### Steps to Reproduce

1. Try to install dependencies `./script/bootstrap`
2. node-gyp Fail on fuzzy-search because you have node 13
3. Downgrade to node 12 using `asdf`
4. Install dependencies
5. `./script/build`
6. node-gyp Fail #.2 because (somehow) python can't be found
7. set PYTHON="/usr/local/bin/python"
8. Fail again, but different error: `unknown command: python. Perhaps you have to reshim?`
9. try manually installing the offending module `superstring@2.4.2`
10. successfully run `npm install superstring@2.4.2`
11. `./script/build`
12. Fail again, same error: `unknown command: python. Perhaps you have to reshim?`

### Additional Info

@darangi (I'm tagging you since https://github.com/atom/text-buffer/pull/317 is closest related thing I can find)

Is there some internal node/environment thats being used that explains how `npm install superstring@2.4.2` works but the build script doesn't?

### Versions
MacOS 10.12.6 (Seirra)

![Screen Shot 2020-07-31 at 10 45 56 PM](https://user-images.githubusercontent.com/17692058/89093747-a7a46700-d382-11ea-9b32-e0728ff85479.png)

**Comment by jeff-hykin** [comment]
For anyone with similar problems, based on https://github.com/asdf-vm/asdf/issues/162 
I ran `asdf plugin remove python`, which 'fixed' the issue (not sure why its only failing on build)

Then that allowed me to reach the following error
```
[Error [ERR_PACKAGE_PATH_NOT_EXPORTED] [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/helper-compilation-targets/package.json
  at applyExports (internal/modules/cjs/loader.js:490:9)
  at resolveExports (internal/modules/cjs/loader.js:506:23)
  at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
  at Function.Module._load (internal/modules/cjs/loader.js:841:27)
  at Module.require (internal/modules/cjs/loader.js:1025:19)
  at require (internal/modules/cjs/helpers.js:72:18)
  at Object.<anonymous> (/Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/preset-env/lib/debug.js:8:33)
  at Module._compile (internal/modules/cjs/loader.js:1137:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
  at Module.load (/Users/jeffhykin/Nextcloud/Programming/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (internal/modules/cjs/loader.js:878:14)
  at Module.require (internal/modules/cjs/loader.js:1025:19)
  at require (internal/modules/cjs/helpers.js:72:18)
  at Object.<anonymous> (/Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/preset-env/lib/index.js:11:14)
  at Module._compile (internal/modules/cjs/loader.js:1137:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
  at Module.load (/Users/jeffhykin/Nextcloud/Programming/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (internal/modules/cjs/loader.js:878:14)
  at Module.require (internal/modules/cjs/loader.js:1025:19)
  at require (internal/modules/cjs/helpers.js:72:18)
  at requireModule (/Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
  at loadPreset (/Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/files/plugins.js:83:17)
  at createDescriptor (/Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
  at /Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
  at Array.map (<anonymous>:null:null)
  at createDescriptors (/Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
  at createPresetDescriptors (/Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
  at presets (/Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
  at mergeChainOpts (/Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-chain.js:320:26)
  at /Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-chain.js:283:7
  at buildRootChain (/Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-chain.js:120:22)
  at loadPrivatePartialConfig (/Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/partial.js:85:55)
  at loadFullConfig (/Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/full.js:43:39)
  at Object.transformSync (/Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@babel/core/lib/transform.js:41:38)
  at /Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@atom/babel7-transpiler/lib/index.js:54:28
  at withBabelEnv (/Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@atom/babel7-transpiler/lib/index.js:18:15)
  at Object.transpile (/Users/jeffhykin/Nextcloud/Programming/atom/out/app/node_modules/github/node_modules/@atom/babel7-transpiler/lib/index.js:53:12)
  at PackageTranspilationRegistry.transpileWithPackageTranspiler (/Users/jeffhykin/Nextcloud/Programming/atom/src/package-transpilation-registry.js:158:33)
  at Object.compile (/Users/jeffhykin/Nextcloud/Programming/atom/src/package-transpilation-registry.js:59:23)
  at compileFileAtPath (/Users/jeffhykin/Nextcloud/Programming/atom/src/compile-cache.js:109:31)
  at Object.exports.addPathToCache (/Users/jeffhykin/Nextcloud/Programming/atom/src/compile-cache.js:82:14)
  at transpilePath (/Users/jeffhykin/Nextcloud/Programming/atom/script/lib/transpile-packages-with-custom-transpiler-paths.js:86:18)
  at Array.forEach (<anonymous>:null:null)
  at module.exports (/Users/jeffhykin/Nextcloud/Programming/atom/script/lib/transpile-packages-with-custom-transpiler-paths.js:64:24)
  at Object.<anonymous> (/Users/jeffhykin/Nextcloud/Programming/atom/script/build:75:3)
  at Module._compile (internal/modules/cjs/loader.js:1137:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
  at Module.load (internal/modules/cjs/loader.js:985:32)
  at Function.Module._load (internal/modules/cjs/loader.js:878:14)
  at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
  at internal/main/run_main_module.js:17:47
] {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by DeeDeeG** [comment]
As a (not very widely?) known issue, Atom currently does not build on certain newer versions of Node.

See: https://github.com/atom/atom/issues/21091

Using Node 12.16.x, or 10.x should work for now.

**Comment by jeff-hykin** [comment]
adding `"node": "12.16.x"` to the package.json would help with this in the future
