### ISSUE TITLE
Error creating build for Windows in Ubuntu

### ISSUE THREAD

**Issue by abaracedo** [atom/atom#21151]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I have an Atom repository cloned in Ubuntu 20.04 LTS (WSL2) and I followed all the steps for building Atom in Ubuntu. When I run script/build --create-windows-installer it throws the following error.

```
Transpiling packages with custom transpiler configurations in /home/myUser/github/atom/out/app
 transpiling for package github
Installing modules ✓
internal/modules/cjs/loader.js:491
  throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
  ^

[Error [ERR_PACKAGE_PATH_NOT_EXPORTED] [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/helper-compilation-targets/package.json
  at applyExports (internal/modules/cjs/loader.js:491:9)
  at resolveExports (internal/modules/cjs/loader.js:507:23)
  at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
  at Function.Module._load (internal/modules/cjs/loader.js:842:27)
  at Module.require (internal/modules/cjs/loader.js:1026:19)
  at require (internal/modules/cjs/helpers.js:72:18)
  at Object.<anonymous> (/home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/preset-env/lib/debug.js:8:33)
  at Module._compile (internal/modules/cjs/loader.js:1138:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
  at Module.load (/home/myUser/github/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (internal/modules/cjs/loader.js:879:14)
  at Module.require (internal/modules/cjs/loader.js:1026:19)
  at require (internal/modules/cjs/helpers.js:72:18)
  at Object.<anonymous> (/home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/preset-env/lib/index.js:11:14)
  at Module._compile (internal/modules/cjs/loader.js:1138:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
  at Module.load (/home/myUser/github/atom/script/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (internal/modules/cjs/loader.js:879:14)
  at Module.require (internal/modules/cjs/loader.js:1026:19)
  at require (internal/modules/cjs/helpers.js:72:18)
  at requireModule (/home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
  at loadPreset (/home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/files/plugins.js:83:17)
  at createDescriptor (/home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
  at /home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
  at Array.map (<anonymous>:null:null)
  at createDescriptors (/home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
  at createPresetDescriptors (/home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
  at presets (/home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
  at mergeChainOpts (/home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-chain.js:320:26)
  at /home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-chain.js:283:7
  at buildRootChain (/home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/config-chain.js:120:22)
  at loadPrivatePartialConfig (/home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/partial.js:85:55)
  at loadFullConfig (/home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/core/lib/config/full.js:43:39)
  at Object.transformSync (/home/myUser/github/atom/out/app/node_modules/github/node_modules/@babel/core/lib/transform.js:41:38)
  at /home/myUser/github/atom/out/app/node_modules/github/node_modules/@atom/babel7-transpiler/lib/index.js:54:28
  at withBabelEnv (/home/myUser/github/atom/out/app/node_modules/github/node_modules/@atom/babel7-transpiler/lib/index.js:18:15)
  at Object.transpile (/home/myUser/github/atom/out/app/node_modules/github/node_modules/@atom/babel7-transpiler/lib/index.js:53:12)
  at PackageTranspilationRegistry.transpileWithPackageTranspiler (/home/myUser/github/atom/src/package-transpilation-registry.js:158:33)
  at Object.compile (/home/myUser/github/atom/src/package-transpilation-registry.js:59:23)
  at compileFileAtPath (/home/myUser/github/atom/src/compile-cache.js:109:31)
  at Object.exports.addPathToCache (/home/myUser/github/atom/src/compile-cache.js:82:14)
  at transpilePath (/home/myUser/github/atom/script/lib/transpile-packages-with-custom-transpiler-paths.js:86:18)
  at Array.forEach (<anonymous>:null:null)
  at module.exports (/home/myUser/github/atom/script/lib/transpile-packages-with-custom-transpiler-paths.js:64:24)
  at Object.<anonymous> (/home/myUser/github/atom/script/build:75:3)
  at Module._compile (internal/modules/cjs/loader.js:1138:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
  at Module.load (internal/modules/cjs/loader.js:986:32)
  at Function.Module._load (internal/modules/cjs/loader.js:879:14)
  at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
  at internal/main/run_main_module.js:17:47
] {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

### Steps to Reproduce

I followed the steps from the [guide](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#building) 

**Expected behavior:**

It creates the installer for Windows

**Actual behavior:**

It doesn't create the installer.

**Reproduces how often:**

Two times I tried, the second time without the `--create-windows-installer` and it threw the same error.

**Comment by jeff-hykin** [comment]
I had the same issue on Mac, might want to copy paste yours over there and close this one as a duplicate 

https://github.com/atom/atom/issues/21137
