### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.49.0\CSS - M...

### ISSUE THREAD

**Issue by natanyeshurun** [atom/atom#21158]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Natan-PC\AppData\Local\atom\app-1.49.0\CSS - My Site Images'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'C:\Users\Natan-PC\AppData\Local\atom\app-1.49.0\CSS - My Site Images'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:943665)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:950838)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:924225)
```

### Commands

```
     -5:57 tree-view:add-file (span.name.icon.icon-file-directory)
  3x -5:54.6.0 core:backspace (input.hidden-input)
     -5:32.6.0 core:confirm (input.hidden-input)
     -5:24.1.0 tree-view:remove (div.tool-panel.tree-view)
     -5:16.1.0 tree-view:add-folder (div.header.list-item.project-root-header)
     -5:09.8.0 core:confirm (input.hidden-input)
  2x -1:41.8.0 tree-view:remove (span.name.icon.icon-file-zip)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
pigments 0.40.2 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
