### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\Temp\7zE4691BD7F'

### ISSUE THREAD

**Issue by AtomGitH** [atom/atom#21153]
[Enter steps to reproduce:]

1. ...Downloading bootstrap
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Owner\AppData\Local\Temp\7zE4691BD7F'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'C:\Users\Owner\AppData\Local\Temp\7zE4691BD7F'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:943665)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:950838)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:924225)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
