### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/ 07-08-2020 - 20200807153216.md'

### ISSUE THREAD

**Issue by raphaelhuleux** [atom/atom#21171]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/ 07-08-2020 - 20200807153216.md'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat '/ 07-08-2020 - 20200807153216.md'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:969249)
    at TreeView.onDrop (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:976178)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:949809)
```

### Commands

```
  7x -0:51 tree-view:toggle (atom-pane.pane)
```

### Non-Core Packages

```
apex-syntax 0.2.0 
apex-ui 1.2.0 
atom-file-icons 0.7.1 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
autocomplete-bibtex 1.2.10 
document-outline 2.1.2 
hey-pane 1.2.0 
Hydrogen 2.14.4 
hypest-dark 0.8.0 
hypest-dark-syntax 0.1.0 
ide-python 1.5.0 
keymap-control 1.2.0 
language-latex 1.2.0 
language-matlab-octave 1.0.5 
latex 0.50.2 
markdown-preview-enhanced 0.18.5 
minimap 4.29.9 
native-ui 0.27.0 
pdf-view 0.72.0 
predawn-syntax 1.0.4 
predawn-ui 1.0.7 
project-plus 1.0.0 
python-autopep8 0.1.3 
script 3.26.0 
wikilink 0.14.0 
zotero-citations 5.2.0 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
