### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.50.0\ LLC'

### ISSUE THREAD

**Issue by kumarschitturi** [atom/atom#21187]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Kumara.Chitturi\AppData\Local\atom\app-1.50.0\ LLC'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'C:\Users\Kumara.Chitturi\AppData\Local\atom\app-1.50.0\ LLC'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:14:969251)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:14:976180)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:14:949811)
```

### Commands

```
     -2:20.2.0 tree-view:paste (span.name.icon.icon-file-directory)
  3x -1:51.8.0 core:save (input.hidden-input)
  2x -1:35.7.0 core:backspace (input.hidden-input)
     -1:30.5.0 core:save (input.hidden-input)
     -1:25.1.0 core:backspace (input.hidden-input)
     -1:24 core:delete (input.hidden-input)
  2x -1:22.2.0 core:save (input.hidden-input)
     -1:04.2.0 core:backspace (input.hidden-input)
     -1:03.9.0 core:delete (input.hidden-input)
  3x -1:02.8.0 core:move-right (input.hidden-input)
     -0:58.4.0 core:save (input.hidden-input)
     -0:50.6.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:46 core:confirm (input.hidden-input)
     -0:30.8.0 tree-view:remove (span.name.icon.icon-file-directory)
     -0:26.6.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:24 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-material-ui 2.1.3 
file-icons 2.1.42 
ide-java 0.9.0 
ide-json 0.2.1 
ide-python 1.5.0 
ide-yml 0.7.8-0 
language-groovy 0.7.0 
language-terraform 0.9.3 
platformio-ide-terminal 2.10.0 
terminal-tab 0.6.0 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
