### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.50.0\fylo-da...

### ISSUE THREAD

**Issue by DeadEyeEviLL** [atom/atom#21181]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\vaish\AppData\Local\atom\app-1.50.0\fylo-data-storage-component-master'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'C:\Users\vaish\AppData\Local\atom\app-1.50.0\fylo-data-storage-component-master'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:14:969251)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:14:976424)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:14:949811)
```

### Commands

```
     -1:40.4.0 core:save (input.hidden-input)
  2x -1:22.9.0 core:backspace (input.hidden-input)
     -1:21.1.0 core:move-down (input.hidden-input)
  3x -1:20.8.0 core:move-left (input.hidden-input)
  3x -1:20.1.0 core:backspace (input.hidden-input)
     -1:16.4.0 intentions:highlight (input.hidden-input)
     -1:16.2.0 core:save (input.hidden-input)
  8x -1:10.8.0 core:move-down (input.hidden-input)
     -1:09.5.0 core:move-up (input.hidden-input)
  4x -1:08.8.0 core:backspace (input.hidden-input)
     -1:05.4.0 intentions:highlight (input.hidden-input)
     -1:05.2.0 core:save (input.hidden-input)
     -1:01.0 core:move-left (input.hidden-input)
     -1:00.7.0 core:move-down (input.hidden-input)
     -0:47.5.0 tree-view:add-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:43.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
