### ISSUE TITLE
Uncaught Error: Could not call remote function 'emit'. Check that the function signature is corre...

### ISSUE THREAD

**Issue by TECHNOFAB11** [atom/atom#21227]
[Enter steps to reproduce:]

1. Just right click anything in the editor

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: "openSUSE Leap
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Could not call remote function 'emit'. Check that the function signature is correct. Underlying error: Invalid template for MenuItem: must have at least one of label, role or type

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:222

Error: Could not call remote function 'emit'. Check that the function signature is correct. Underlying error: Invalid template for MenuItem: must have at least one of label, role or type
    at callFunction (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:258:17)
    at /usr/share/atom/resources/electron.asar/browser/rpc-server.js:409:10
    at EventEmitter.ipcMain.on.args (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
  2x -3:44.6.0 core:move-right (input.hidden-input)
     -3:44 core:delete (input.hidden-input)
     -3:43.9.0 intentions:highlight (input.hidden-input)
     -3:43.7.0 core:save (input.hidden-input)
  3x -3:36.3.0 Code-Time:refresh-code-time-metrics (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:38.5.0 iv-terminal:clear (input.hidden-input)
     -2:36.4.0 Code-Time:refresh-code-time-metrics (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:31.1.0 core:backspace (input.hidden-input)
     -2:30.5.0 core:confirm (input.hidden-input)
  2x -2:06.4.0 Code-Time:refresh-code-time-metrics (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:09.4.0 intentions:highlight (input.hidden-input)
     -1:08.9.0 color-picker:open (input.hidden-input)
     -1:06.4.0 Code-Time:refresh-code-time-metrics (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:04.8.0 intentions:highlight (input.hidden-input)
     -1:04.4.0 color-picker:open (input.hidden-input)
  2x -0:36.4.0 Code-Time:refresh-code-time-metrics (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-color-the-tag-name 1.14.0 
atom-discord 2.0.2 
atom-jinja2 0.6.0 
atom-live-server-plus 3.0.1 
atom-minify 0.8.0 
atom-package-sync 0.4.0 
busy-signal 2.0.1 
cacher 1.1.0 
chrome-color-picker 0.8.0 
code-time 4.1.15 
color-picker 2.3.0 
color-tabs 0.1.8 
emmet 2.4.3 
gitlab 0.1.3-7 
gitlab-manager 0.2.2 
intentions 1.1.5 
iv-terminal 1.3.0 
kite 0.185.0 
linter 2.3.1 
linter-ui-default 1.8.1 
live-reload-sass 0.1.0 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-git-diff 4.3.1 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
php-server 0.8.0 
pigments 0.40.2 
project-view 0.6.5 
project-viewer 1.4.0 
seti-icons 1.5.4 
svg-icons 0.6.0 
teletype 0.13.4 
wakatime 9.0.2 
website-minifier 1.4.0 
```

**Comment by sadick254** [comment]
@TECHNOFAB11 Thank you for reaching out.
Could you confirm if this still happens on the latest version of atom `v1.50`

**Comment by alekks** [comment]
> @TECHNOFAB11 Thank you for reaching out.
> Could you confirm if this still happens on the latest version of atom `v1.50`

I can confirm I have same issue on v.150 of atom.
