### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.50.0\ dude!'

### ISSUE THREAD

**Issue by GT-77** [atom/atom#21235]
Steps to reproduce:

1. Grab a file in tree view with mouse.
2. Move it to another folder in tree view.

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\user\AppData\Local\atom\app-1.50.0\ dude!'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'C:\Users\user\AppData\Local\atom\app-1.50.0\ dude!'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:14:969251)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:14:976180)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:14:949811)
```

### Commands

```
     -1:46.2.0 application:reopen-project (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
gpp-compiler 3.0.7 
```

Possibly related to my D: drive name containing spaces?

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
