### ISSUE TITLE
Uncaught Error: libxkbfile.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by staticvoidliam7** [atom/atom#21238]
[Enter steps to reproduce:]

1. make a new file, clone from repo
2. click any key

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: linux 5.4.40-04224-g891a6cce2d44
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: libxkbfile.so.1: cannot open shared object file: No such file or directory

```
At electron/js2c/asar.js:138

Error: libxkbfile.so.1: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:695413)
    at get_KeyboardLayoutManager (/usr/share/atom/resources/app/static/<embedded>:14:2715520)
    at get_manager (/usr/share/atom/resources/app/static/<embedded>:14:2715622)
    at Object.getCurrentKeyboardLayout (/usr/share/atom/resources/app/static/<embedded>:14:2715748)
    at e.keystrokeForKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:14:1047867)
    at KeymapManager.keystrokeForKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1228085)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1226070)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:284829)
```

### Commands

```
     -1:33.3.0 github:toggle-github-tab (input.hidden-input)
     -1:18 core:paste (div.line)
     -1:02.6.0 pane:split-up-and-copy-active-item (a.)
     -1:00.2.0 core:undo (div.github-StubItem-generic)
  2x -0:43.3.0 github:toggle-github-tab (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```

```

**Comment by mfonville** [comment]
Which distribution are you using? Because `/usr/lib/x86_64-linux-gnu/libxkbfile.so.1` is at least on Debian part of `libxkbfile1:amd64` and specified as a dependency.

And can you check if `libxkbfile.so.1` exists somewhere on your system?

**Comment by saltedcoffii** [comment]
I know this issue's closed, but on fedora 33, the atom rpm file available from `atom.io` doesn't pull in `libxkbfile` as a dependency. Maybe it should do that.

**Comment by mfonville** [comment]
@saltedcoffii you are right that its dependency should be pulled in. If it is not in our RPM, could you help with updating our https://github.com/atom/atom/blob/master/resources/linux/redhat/atom.spec.in file with the `Requires` that we would need?

**Comment by saltedcoffii** [comment]
@mfonville unfortunately I don't know enough about RPM to do that correctly, however the binary is just called `libxkbfile`. Perhaps reopening this issue will call attention and someone who knows more than me will be able to fix it?

**Comment by mfonville** [comment]
Thanks, for the information of the binary name. I checked on the Fedora pkgs website and will make an appropriate pull-request

**Comment by mfonville** [comment]
@saltedcoffii https://github.com/atom/atom/pull/21980 should be a fix
