### ISSUE TITLE
Uncaught RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by MrBIN89** [atom/atom#21243]
**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Windows 10.0.18363 
**Thrown From**: Atom Core

### Stack Trace

Uncaught RangeError: Array buffer allocation failed

```
At internal/buffer.js:788

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:788:1)
    at Function.alloc (buffer.js:262:10)
    at Proxy.fs.readFile (electron/js2c/asar.js:561:29)
    at Object.readFile (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:581844)
    at Object.loadSnippetsFile (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:232336)
    at m.map.n (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:232141)
    at ~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:935651
    at ~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:934628
    at Array.forEach (<anonymous>)
    at s (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:934080)
    at n.each (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:934612)
    at c (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:935589)
    at Object.map (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:935403)
    at ~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:232093
    at electron/js2c/asar.js:24:28
    at processTicksAndRejections (internal/process/task_queues.js:79:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-python-virtualenv 1.0.4 
autocomplete-python 1.16.0 
autocomplete-robot-framework 3.9.0 
goto-definition 1.3.4 
highlight-selected 0.17.0 
hyperclick 0.1.5 
hyperclick-robot-framework 1.9.0 
kite 0.185.0 
language-groovy 0.7.0 
language-robot-framework 2.4.0 
linter-python-pep8 0.2.0 
minimap 4.29.9 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
pretty-html 1.0.0 
pretty-json 2.1.2 
python-autopep8 0.1.3 
python-tools 0.6.9 
terminal-tab 0.6.0 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
