### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/rb/0qqj4ls529vgcyhdv4s5rdg00000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by 404piano** [atom/atom#21260]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Unknown macOS version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/rb/0qqj4ls529vgcyhdv4s5rdg00000gn/T/AppTranslocation/520BFBDE-8FF6-4FDC-B229-F0C47DDBD0B0/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): no suitable image found.  Did find:
	/private/var/folders/rb/0qqj4ls529vgcyhdv4s5rdg00000gn/T/AppTranslocation/520BFBDE-8FF6-4FDC-B229-F0C47DDBD0B0/d/Atom.app/Contents/Resources: not a file

```
At electron/js2c/asar.js:138

Error: dlopen(/private/var/folders/rb/0qqj4ls529vgcyhdv4s5rdg00000gn/T/AppTranslocation/520BFBDE-8FF6-4FDC-B229-F0C47DDBD0B0/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): no suitable image found.  Did find:
	/private/var/folders/rb/0qqj4ls529vgcyhdv4s5rdg00000gn/T/AppTranslocation/520BFBDE-8FF6-4FDC-B229-F0C47DDBD0B0/d/Atom.app/Contents/Resources: not a file
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/private/var/folders/rb/0qqj4ls529vgcyhdv4s5rdg00000gn/T/AppTranslocation/520BFBDE-8FF6-4FDC-B229-F0C47DDBD0B0/d/Atom.app/Contents/Resources/app/static/<embedded>:1:695414)
    at get_KeyboardLayoutManager (/private/var/folders/rb/0qqj4ls529vgcyhdv4s5rdg00000gn/T/AppTranslocation/520BFBDE-8FF6-4FDC-B229-F0C47DDBD0B0/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2715520)
    at get_manager (/private/var/folders/rb/0qqj4ls529vgcyhdv4s5rdg00000gn/T/AppTranslocation/520BFBDE-8FF6-4FDC-B229-F0C47DDBD0B0/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2715622)
    at Object.getCurrentKeyboardLayout (/private/var/folders/rb/0qqj4ls529vgcyhdv4s5rdg00000gn/T/AppTranslocation/520BFBDE-8FF6-4FDC-B229-F0C47DDBD0B0/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2715748)
    at e.keystrokeForKeyboardEvent (/private/var/folders/rb/0qqj4ls529vgcyhdv4s5rdg00000gn/T/AppTranslocation/520BFBDE-8FF6-4FDC-B229-F0C47DDBD0B0/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1047867)
    at KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/rb/0qqj4ls529vgcyhdv4s5rdg00000gn/T/AppTranslocation/520BFBDE-8FF6-4FDC-B229-F0C47DDBD0B0/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1228085)
    at KeymapManager.handleKeyboardEvent (/private/var/folders/rb/0qqj4ls529vgcyhdv4s5rdg00000gn/T/AppTranslocation/520BFBDE-8FF6-4FDC-B229-F0C47DDBD0B0/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1226070)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/rb/0qqj4ls529vgcyhdv4s5rdg00000gn/T/AppTranslocation/520BFBDE-8FF6-4FDC-B229-F0C47DDBD0B0/d/Atom.app/Contents/Resources/app/static/<embedded>:11:284829)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 2.0.1 
intentions 1.1.5 
kite 0.185.0 
linter 2.3.1 
linter-pycodestyle 2.1.3 
linter-ui-default 1.8.1 
platformio-ide-terminal 2.10.0 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
