### ISSUE TITLE
Uncaught Error: error: 126/\?\~\AppData\Local\atom\app-1.51.0\resources\app.asar.unpacked\node_mo...

### ISSUE THREAD

**Issue by juanfranciscocp** [atom/atom#21297]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: error: 126\\?\C:\Users\USUARIO\AppData\Local\atom\app-1.51.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:138

Error: error: 126\\?\C:\Users\USUARIO\AppData\Local\atom\app-1.51.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:1:722026)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:14:2716581)
    at get_manager (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:14:2716683)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:14:2716809)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:14:1047862)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1228180)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1226165)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:284829)
```

### Commands

```
     -5:22.7.0 core:save-as (input.hidden-input)
  2x -3:44.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Non-Core Packages

```
atom-live-server 2.3.0 
busy-signal 2.0.1 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.42 
ide-html 0.6.0 
ide-typescript 0.9.1 
intentions 1.1.5 
linter 2.3.1 
linter-htmllint 1.1.9 
linter-stylint 2.3.0 
linter-ui-default 1.8.1 
minimap 4.29.9 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
