### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.51.0\CSS - M...

### ISSUE THREAD

**Issue by Endri12345678** [atom/atom#21316]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Asus\AppData\Local\atom\app-1.51.0\CSS - My Site Images'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'C:\Users\Asus\AppData\Local\atom\app-1.51.0\CSS - My Site Images'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:14:969244)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:14:976417)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:14:949804)
```

### Commands

```
     -9:27.5.0 project-find:show-in-current-directory (div.header.list-item)
     -9:14.7.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -7:43.1.0 application:add-project-folder (div.header.list-item)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose 0.0.2 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
