### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/desktop/websites/dinorah/CleaningSite...

### ISSUE THREAD

**Issue by anthony-silva** [atom/atom#21339]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/anthonysilva/desktop/websites/dinorah/CleaningSite/static'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat '/Users/anthonysilva/desktop/websites/dinorah/CleaningSite/static'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (/Users/anthonysilva/Desktop/Software/IDEs/Atom.app/Contents/Resources/app/static/<embedded>:14:969214)
    at TreeView.onDrop (/Users/anthonysilva/Desktop/Software/IDEs/Atom.app/Contents/Resources/app/static/<embedded>:14:976422)
    at HTMLDivElement.<anonymous> (/Users/anthonysilva/Desktop/Software/IDEs/Atom.app/Contents/Resources/app/static/<embedded>:14:949809)
```

### Commands

```
     -8:28.9.0 tree-view:add-file (div.header.list-item)
     -1:04.2.0 tree-view:remove (div.tool-panel.tree-view)
     -1:03.4.0 tree-view:open-selected-entry (div.tool-panel.tree-view)
  2x -1:02.0 tree-view:remove (div.tool-panel.tree-view)
     -0:12.2.0 window:save-all (div.tool-panel.tree-view)
```

### Non-Core Packages

```

```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
