### ISSUE TITLE
Atom 1.52 beta requires CXXABI_1.3.9 which is not available in some distro releases

### ISSUE THREAD

**Issue by cdmackay** [atom/atom#21348]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

apm fails due to library API mismatch; atom also fails to start, but without obvious error logged

### Steps to Reproduce

apm-beta upgrade

**Expected behavior:**

check for pkgs to upgrade

**Actual behavior:**

$ apm-beta upgrade
internal/modules/cjs/loader.js:815
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/atom-beta/resources/app/apm/node_modules/git-utils/build/Release/git.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:815:18)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/share/atom-beta/resources/app/apm/node_modules/git-utils/src/git.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)

**Reproduces how often:**

100%

### Versions

OK 1.51.0.beta0-0.1

BAD 1.52.0.beta0-0.1

### Additional Information

Oracle Linux Server release 7.8 (based on RHEL 7.8)

/usr/lib64/libstdc++.so.6.0.19

Name        : libstdc++
Arch        : x86_64
Version     : 4.8.5
Release     : 39.0.5.el7

$ strings /usr/lib64/libstdc++.so.6 | grep ^CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7

**Comment by sergkudinov** [comment]
Same problem

**Comment by neeters9** [comment]
i am having this problem as well what was the solution to fix this?

**Comment by cdmackay** [comment]
No solution or workaround known, as far as I'm aware.

**Comment by ThatXliner** [comment]
Does this still happen on the latest stable release? I mean, I guess they can bundle this...

**Comment by neeters9** [comment]
I am getting this error on atom version 1.54.0

**Comment by Garyblagga122** [comment]
I'm not understanding any of it as a novice to the set up of it ALL can't help sorry but don't fink I'm right 4 it I told just click watch get dollars lol click watch bank nnnaarr lol 
I

**Comment by cdmackay** [comment]
workaround as here:

https://github.com/atom/language-shellscript/issues/142#issuecomment-709820884
