### ISSUE TITLE
atom crashes with permission denied

### ISSUE THREAD

**Issue by bbarker** [atom/atom#21359]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
When trying to launch the `atom` installed via nixpkgs, I get a "permisison denied" error, though it isn't entirely clear to me why.

### Steps to Reproduce

1.[ Install nix](https://nixos.org/download.html) in a linux distribution (for me, this is WSL2/Ubuntu)
2.  `nix-shell -p atom` then in the new shell run `atom`
3. 

**Expected behavior:**

atom to start up

**Actual behavior:**

$ atom --safe

```
[nix-shell:~/workspace/idris2-lua]$ Application server failed { Error: listen EACCES: permission denied /run/user/1000/atom-8e6b7b857507.sock
    at Server.setupListenHandle [as _listen2] (net.js:1216:19)
    at listenInCluster (net.js:1281:12)
    at Server.listen (net.js:1380:5)
    at /nix/store/p6jyv20lx8ykg421qbckw08kzbl08xz9-atom-1.48.0/share/atom/resources/app.asar/src/main-process/atom-application.js:537:14
    at new Promise (<anonymous>:null:null)
    at AtomApplication.listenForArgumentsFromNewProcess (/nix/store/p6jyv20lx8ykg421qbckw08kzbl08xz9-atom-1.48.0/share/atom/resources/app.asar/src/main-process/atom-application.js:536:12)

  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '/run/user/1000/atom-8e6b7b857507.sock',
  port: -1 }
```

**Reproduces how often:**

every time

### Versions

```
$ atom --version
Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

### Additional Information

If using WSL2 you also [need a properly configured X server](https://stackoverflow.com/a/61110604/3096687).

**Comment by sadick254** [comment]
Can you try upgrading to the latest version of atom and try again.
