### ISSUE TITLE
Uncaught Error: /\?\~\AppData\Local\atom\app-1.51.0\resources\app.asar.unpacked\node_modules\keyb...

### ISSUE THREAD

**Issue by kingofarsenal** [atom/atom#21402]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: \\?\C:\Users\Paul\AppData\Local\atom\app-1.51.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node is not a valid Win32 application.
\\?\C:\Users\Paul\AppData\Local\atom\app-1.51.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:138

Error: \\?\C:\Users\Paul\AppData\Local\atom\app-1.51.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node is not a valid Win32 application.
\\?\C:\Users\Paul\AppData\Local\atom\app-1.51.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:1:722026)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:14:2716581)
    at get_manager (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:14:2716683)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:14:2716809)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:14:1047862)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1228180)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1226165)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:284829)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
autocomplete-boilerplate 0.2.0 
autocomplete-unity 0.1.3 
color-picker 2.3.0 
highlight-colors 0.9.0 
highlight-selected 0.17.0 
language-renpy 2.5.0 
language-wren 0.2.0 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-highlight-selected 4.6.1 
minimap-lens 0.8.1 
monokai 0.24.0 
pigments 0.40.2 
renpy-dark-syntax 1.2.0 
renpy-dialogue-plus 0.0.8 
set-syntax 0.4.0 
ue4-snippets 1.0.0 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
