### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/ Loops'

### ISSUE THREAD

**Issue by chriscaldwell** [atom/atom#21432]
[Enter steps to reproduce:]

1. Rename a subdirectory of a subdirectory of the root /Root/Sub/SubOld -> /Root/SubDirectory/SubRenamed in the left directory listing of your project. 
2. Drag and drop the subdirectory in the root project directory. The intent was to end up with this/Root/SubRenamed.

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/ Loops'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat '/ Loops'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:969249)
    at TreeView.onDrop (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:976178)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:949809)
```

### Commands

```
     -3:31.3.0 intentions:highlight (input.hidden-input)
     -3:11.7.0 tree-view:duplicate (span.name.icon.icon-file-directory)
     -2:58.3.0 core:move-right (input.hidden-input)
  2x -2:58 editor:select-to-beginning-of-word (input.hidden-input)
  3x -2:55 core:backspace (input.hidden-input)
     -2:50.6.0 core:confirm (input.hidden-input)
     -2:34.1.0 core:backspace (input.hidden-input)
     -2:32.2.0 core:select-right (input.hidden-input)
     -2:28.4.0 core:select-left (input.hidden-input)
  3x -2:21.8.0 core:backspace (input.hidden-input)
     -2:19.4.0 core:save (input.hidden-input)
     -0:54.3.0 tree-view:move (span.name.icon.icon-file-directory)
     -0:47.2.0 core:confirm (input.hidden-input)
     -0:36.6.0 tree-view:unfocus (div.tool-panel.tree-view)
     -0:24.3.0 tree-view:move (span.name.icon.icon-file-directory)
     -0:14.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-monokai 0.10.9 
atom-typescript 13.4.8 
busy-signal 2.0.1 
chary-tree-view 0.2.13 
color-picker 2.3.0 
docblockr 0.13.7 
editorconfig 2.6.0 
emmet 2.4.3 
file-types 1.0.1 
highlight-selected 0.17.0 
intentions 1.1.5 
keyboard-scroll 0.7.0 
language-actionscript3 0.3.0 
language-babel 2.85.0 
language-htaccess 0.2.0 
linter 2.3.1 
linter-ui-default 1.8.1 
merge-conflicts 1.4.5 
monokai-extended 0.3.0 
multi-wrap-guide 1.1.10 
p5xjs-autocomplete 2.3.0 
pane-manager 1.0.1 
pigments 0.40.2 
project-manager 3.3.8 
terminal-plus 0.14.5 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed on `master`. It is currently scheduled for release when `v1.53.0` reaches Stable.
