### ISSUE TITLE
[1.52.0] {Centos 7.8.2003}: Atom doesn't launch.

### ISSUE THREAD

**Issue by alexisfrjp** [atom/atom#21497]
# Description

After the update of Atom of the latest version 1.52.0, Atom doesn't launch anymore on Centos 7.8.2003.
I reverted to 1.51.0 and it works.

### Steps to Reproduce

1. Install Atom 1.52.0 on Centos 7.8.2003 (latest at time).
2.a. `atom .` => return the cursor in bash but it never shows the GUI.
2.b. `atom --version` => freeze the bash forever with a blinking cursor, can be killed with SIGINT

**Expected behavior:**

Seeing the GUI.

**Actual behavior:**

GUI not shown, Atom never runs even though I see the process.

### Versions

* `atom-1.52.0-0.1.x86_64`
* Centos 7.8.2003

### Additional Information

```
$ apm --version
internal/modules/cjs/loader.js:815
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/atom/resources/app/apm/node_modules/git-utils/build/Release/git.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:815:18)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/git-utils/src/git.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
```

**Comment by RudiFueller** [comment]
Starting atom 1.52.0 on CentOS 7.8.2003 delivers for me:

```
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/atom/resources/app.asar.unpacked/node_modules/nslog/build/Release/nslog.node)
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/nslog/lib/nslog.js:5:11)
```
Processes are launched, but no GUI visible.

**Comment by shtepan** [comment]
I hot a same problem on CentOS 7.8.2003, Atom 1.51 starts OK.

**Comment by pinacoelho** [comment]
Same problem on Red Hat Enterprise Linux Workstation release 7.8 (Maipo)

Downgrading to atom-1.51.0-0.1.x86_64 "solves" the problem.

**Comment by pinacoelho** [comment]
/usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9^
# strings /usr/lib64/libstdc++.so.6 | grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21'

# strings /lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH

Both files are delivered by libstdc++-4.8.5-39.el7.x86_64 (the current version in RHEL)

**Comment by mo-slefley** [comment]
Same issue on Red Hat Enterprise Linux Client release 7.9 (Maipo)

**Comment by shtepan** [comment]
RH 7 uses an old /usr/lib64/libstdc++.so.6
Nice and easy solution is to take a newer one for example from gcc or anaconda. Great idea from Brasil a year+ ago.
https://github.com/cdr/code-server/issues/347#issuecomment-482670081

**Comment by ju276** [comment]
Ok

**Comment by prazape** [comment]
Does the same for me on Centos 7.9.2009 and both Atom 1.52 and Atom 1.53. The last working version is 1.51
[user@machine ~]$ atom -f
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/atom/resources/app.asar.unpacked/node_modules/nslog/build/Release/nslog.node)
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/nslog/lib/nslog.js:5:11)

I am gonna try getting newer gcc.

**Comment by shtepan** [comment]
Just the right one newer 'libstdc++.so.6' is enough. I posted the solution two comments above. Cheers

**Comment by alexisfrjp** [comment]
Just need to install anaconda3 as said in the issue in the previous comment.

**Comment by blackshale** [comment]
shtepan's changing libstdc method worked for me! Thank you.

**Comment by fastzombies** [comment]
Following the above links, if you have a recent Anaconda3 with libstdc++.so.6.0.25 or later:

    export LD_LIBRARY_PATH=/path/to/anaconda3/install/lib

Now Atom 1.52.0+ works and some broken packages are resolved as well.
