### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.52.0\res...

### ISSUE THREAD

**Issue by NishankShah** [atom/atom#21505]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\nisha\AppData\Local\atom\app-1.52.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:138

Error: The specified module could not be found.
\\?\C:\Users\nisha\AppData\Local\atom\app-1.52.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:1:735077)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:2716464)
    at get_manager (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:2716566)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:2716692)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:1047827)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:1228394)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:1226379)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:284820)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
