### ISSUE TITLE
Particular directory name causes crash

### ISSUE THREAD

**Issue by MDBenson** [atom/atom#2151]
for some reason the particular directory name 'unconf' causes atom to throw up with a pathwatcher error:

```
Error: /Users/mark/github/unconf is a directory
  at new File (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:30:15)
  at TextBuffer.module.exports.TextBuffer.setPath (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:614:21)
  at new TextBuffer (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:82:14)
  at Function.module.exports.Serializable.deserialize (/Applications/Atom.app/Contents/Resources/app/node_modules/serializable/lib/serializable.js:72:22)
  at DeserializerManager.module.exports.DeserializerManager.deserialize (/Applications/Atom.app/Contents/Resources/app/src/deserializer-manager.js:42:29)
  at /Applications/Atom.app/Contents/Resources/app/src/project.js:84:35
  at Array.map (native)
  at Project.module.exports.Project.deserializeParams (/Applications/Atom.app/Contents/Resources/app/src/project.js:83:39)
  at Function.module.exports.Serializable.deserialize (/Applications/Atom.app/Contents/Resources/app/node_modules/serializable/lib/serializable.js:58:25)
  at DeserializerManager.module.exports.DeserializerManager.deserialize (/Applications/Atom.app/Contents/Resources/app/src/deserializer-manager.js:42:29)
  at Atom.module.exports.Atom.deserializeProject (/Applications/Atom.app/Contents/Resources/app/src/atom.js:300:94)
  at Atom.module.exports.Atom.deserializeEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:323:12)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:348:12)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:14:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:20:4)
  at Module._compile (module.js:455:26)
  at Object.Module._extensions..js (module.js:473:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:363:17)
  at require (module.js:379:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:20:5)
```
I deleted and recreated the directory multiple times, ensured permissions were right etc. No dice. If I opened atom inside the directory (via the terminal) using the 'atom' command it barfed. I also tried the directory with and without a git repo in it and it made no difference. It's always that EXACT error too, not different for various files inside the directory, regardless of if I open the directory itself or a file inside it.

Any other directory name is fine, anywhere else I create 'unconf' so far seems to be fine too. Very odd :\

**Comment by ioquatix** [comment]
+1 just had this problem.

**Comment by ioquatix** [comment]
```
Error: /home/samuel/Documents/Programming/trenni is a directory
  at new File (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:50:17)
  at TextBuffer.module.exports.TextBuffer.setPath (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:279:21)
  at new TextBuffer (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:100:14)
  at Function.module.exports.Serializable.deserialize (/usr/share/atom/resources/app/node_modules/serializable/lib/serializable.js:72:22)
  at DeserializerManager.module.exports.DeserializerManager.deserialize (/usr/share/atom/resources/app/src/deserializer-manager.js:56:29)
  at /usr/share/atom/resources/app/src/project.js:128:35
  at Array.map (native)
  at Project.module.exports.Project.deserializeParams (/usr/share/atom/resources/app/src/project.js:127:39)
  at Function.module.exports.Serializable.deserialize (/usr/share/atom/resources/app/node_modules/serializable/lib/serializable.js:58:25)
  at DeserializerManager.module.exports.DeserializerManager.deserialize (/usr/share/atom/resources/app/src/deserializer-manager.js:56:29)
  at Atom.module.exports.Atom.deserializeProject (/usr/share/atom/resources/app/src/atom.js:725:52)
  at Atom.module.exports.Atom.deserializeEditorWindow (/usr/share/atom/resources/app/src/atom.js:753:12)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:603:12)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:66:25)
```

**Comment by paulyoung** [comment]
I updated my instructions for reproducing the issue to be more accurate. It also seems like deleting the directory allows atom to be opened again.

**Comment by Stephen304** [comment]
You can also have this issue propogate over to other folders with the following steps:

* Use @paulyoung 's steps in your home directory
* Open a folder that doesnt exist

**Comment by postcasio** [comment]
@Stephen304 @paulyoung are you able to reproduce this on the latest version of Atom? I tried to use your steps and didn't get an error.

@benogle should https://github.com/atom/atom/pull/5114 have fixed this?

**Comment by paulyoung** [comment]
Still an issue for me in Version 0.176.0 (0.176.0).

**Comment by kevinsawicki** [comment]
@paulyoung Can you try upgrading to 0.186 ?

**Comment by paulyoung** [comment]
No longer an issue in Version 0.186.0 (0.186.0).

Thanks! :gem:

**Comment by kevinsawicki** [comment]
Great to hear, thanks for the update :+1:
