### ISSUE TITLE
Uncaught Error: Could not call remote method 'emit'. Check that the method signature is correct. ...

### ISSUE THREAD

**Issue by vidarjb** [atom/atom#21513]
[Enter steps to reproduce:]
1. Install the plugin website-minifier
2. Open a file in Atom, in the case of error an HTML file
3. Select a portion of the text
4. Right click on it
5. A red popup appears, whith the message of this error.

After uninstalling the plugin 'website-minifier', the problem went away.

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Linux Mint
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Could not call remote method 'emit'. Check that the method signature is correct. Underlying error: Invalid template for MenuItem: must have at least one of label, role or type
Underlying stack: TypeError: Invalid template for MenuItem: must have at least one of label, role or type
    at Function.Menu.buildFromTemplate (/usr/share/atom/resources/electron.asar/browser/api/menu.js:161:15)
    at new ContextMenu (/usr/share/atom/resources/app.asar/src/main-process/context-menu.js:7:23)
    at BrowserWindow.<anonymous> (/usr/share/atom/resources/app.asar/src/main-process/atom-window.js:173:14)
    at BrowserWindow.emit (events.js:200:13)
    at /usr/share/atom/resources/electron.asar/browser/rpc-server.js:370:67
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:249:27)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:342:29)
    at WebContents.emit (events.js:200:13)

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:219

Error: Could not call remote method 'emit'. Check that the method signature is correct. Underlying error: Invalid template for MenuItem: must have at least one of label, role or type
Underlying stack: TypeError: Invalid template for MenuItem: must have at least one of label, role or type
    at Function.Menu.buildFromTemplate (/usr/share/atom/resources/electron.asar/browser/api/menu.js:161:15)
    at /app.asar/src/main-process/context-menu.js:7:23)
    at /app.asar/src/main-process/atom-window.js:173:14)
    at BrowserWindow.emit (events.js:200:13)
    at /usr/share/atom/resources/electron.asar/browser/rpc-server.js:370:67
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:249:27)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:342:29)
    at WebContents.emit (events.js:200:13)


    at /usr/share/atom/resources/electron.asar/browser/rpc-server.js:373:21
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:249:27)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:342:29)
    at WebContents.emit (events.js:200:13)

```

### Commands

```
```

### Non-Core Packages

```
pretty-html 1.0.0 
pretty-json 2.1.2 
website-minifier 1.4.0 
xml-formatter 0.13.0 
xml-tools 0.2.1 
```

**Comment by sadick254** [comment]
Thanks for contributing!

It appears that this is being caused by the [website-minifier](https://github.com/bossley9/website-minifier) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by eamonbohan** [comment]
Unless this is being caused by other Atom packages, it might be better to close it, given that the website-minifier repository has been archived 2 years ago by the owner, and is now read-only.
