### ISSUE TITLE
Failed to activate the atom-miku package

### ISSUE THREAD

**Issue by sniperrenren** [atom/atom#21528]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: 'atom-miku' package vundefined

### Stack Trace

Failed to activate the atom-miku package

```
At url.indexOf is not a function

TypeError: url.indexOf is not a function
    at jQuery.fn.init.jQuery.fn.load (/packages/atom-miku/node_modules/jquery/dist/jquery.js:10353:13)
    at MikuView.module.exports.MikuView.initEventBind (/packages/atom-miku/lib/miku-view.js:106:21)
    at Object.activate (/packages/atom-miku/lib/main.js:21:23)
    at Package.activateNow (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:3288314)
    at ~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:14:1879
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1190297)
    at Emitter.emit (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1191738)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:349412)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:348255)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:1:752586)
    at EventEmitter.t (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:1:760509)
    at EventEmitter.emit (events.js:194:13)
```

### Commands

```
     -1:28.2.0 AtomMiku:toggle (input.hidden-input)
     -1:09.8.0 settings-view:uninstall-packages (input.hidden-input)
```

### Non-Core Packages

```
atom-ctags 5.1.2 
highlight-selected 0.17.0 
hyperclick-php 0.3.0 
ide-php 0.7.18 
simplified-chinese-menu 5.3.5 
symbols-tree-view 0.14.0 
```

**Comment by sadick254** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-miku](https://github.com/sunqibuhuake/atom-miku) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
