### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\gpp-compiler\README.md'

### ISSUE THREAD

**Issue by ScarlettRed** [atom/atom#21619]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\drdik\.atom\packages\gpp-compiler\README.md'

```
At fs.js:115

Error: ENOENT: no such file or directory, open 'C:\Users\drdik\.atom\packages\gpp-compiler\README.md'
    at Object.openSync (fs.js:436:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
    at Proxy.readFileSync (fs.js:341:35)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:580:40)
    at PackageDetailView.renderReadme (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:825951)
    at PackageDetailView.updateInstalledState (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:825711)
    at PackageDetailView.populate (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:824263)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:819603)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:819815)
    at ~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:826566
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1215561)
    at PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:945159)
    at ~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:942291
    at r (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:936821)
    at n (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1125047)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1125253)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
     -8:02.9.0 editor:newline (input.hidden-input)
     -7:24.7.0 core:move-right (input.hidden-input)
     -7:22.3.0 editor:newline (input.hidden-input)
     -7:09.5.0 core:move-right (input.hidden-input)
     -6:55.8.0 core:backspace (input.hidden-input)
     -6:50.8.0 core:move-right (input.hidden-input)
     -6:47.9.0 core:backspace (input.hidden-input)
     -6:43.1.0 core:move-down (input.hidden-input)
     -6:42.4.0 editor:newline (input.hidden-input)
     -6:38 core:move-left (input.hidden-input)
     -6:37.2.0 core:backspace (input.hidden-input)
     -6:33.5.0 intentions:highlight (input.hidden-input)
     -6:33.3.0 core:save (input.hidden-input)
     -5:55.8.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:36.5.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -3:49.2.0 server-script:run (li.file.entry.list-item.selected)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
gpp-compiler 3.0.7 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
script 3.26.0 
server-script 0.1.3 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by ClassicOG** [comment]
1

**Comment by darangi** [comment]
could you verify this exists on atom 1.52?

**Comment by sadick254** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
