### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/ типы'

### ISSUE THREAD

**Issue by OB11TO** [atom/atom#21658]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 20.04.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/obiito/ типы'

```
At fs.js:143

Error: ENOENT: no such file or directory, lstat '/home/obiito/ типы'
    at Proxy.realpathSync (fs.js:1744:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:335:40)
    at TreeView.moveEntry (/usr/share/atom/resources/app/static/<embedded>:14:1009292)
    at TreeView.onDrop (/usr/share/atom/resources/app/static/<embedded>:14:1016221)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:989852)
```

### Commands

```
     -0:46.2.0 tree-view:add-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -0:44.5.0 core:backspace (input.hidden-input)
  2x -0:19.3.0 tree-view:add-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
  5x -0:13 core:backspace (input.hidden-input)
     -0:06.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-black 0.2.3 
atom-black-ui 0.28.0 
atom-i18n 0.24.0 
atom-material-syntax 1.0.8 
atom-monokai 0.10.9 
atom-runner 2.7.1 
autocomplete-haskell 1.0.1 
autocomplete-java 1.2.7 
autocomplete-java-minus 0.14.0 
autocomplete-latex 0.9.2 
autocomplete-python 1.16.0 
busy 0.7.0 
color-picker 2.3.0 
dark-one-dark-syntax 2.3.0 
dark-python-syntax 2.3.0 
darker-one-dark-syntax 1.1.0 
emmet 2.4.3 
file-icons 2.1.43 
git-control 0.9.0 
git-plus 8.7.1 
gl-light-syntax 3.0.0 
highlight-selected 0.17.0 
Hydrogen 2.14.6 
ide-haskell 2.4.1 
ide-haskell-cabal 2.5.0 
java-classpath-registry 0.4.0 
java-import-wiz 0.5.0 
java-plus 0.1.0 
language-common-lisp 0.9.5 
language-emacs-lisp 1.4.0 
language-haskell 1.20.0 
language-kotlin 0.5.0 
language-lisp 0.2.0 
linter 3.1.1 
markdown-preview-plus 3.11.5 
minimap 4.29.9 
new-era-syntax 1.3.4 
nv-dark-syntax 1.4.1 
nv-dark-ui 3.0.8 
one-black-syntax 1.14.0 
open-recent 5.0.0 
pdf-view 0.72.0 
pigments 0.40.6 
purple-papers-syntax 0.1.1 
purplest-inc-dark-ui 1.0.2 
schelp-syntax 0.6.3 
script 3.26.0 
seti-ui 1.11.0 
seti-ui-red 0.13.0 
seti-vs-syntax 0.1.1 
twifty-black-syntax 0.0.1 
two-dark-ui 1.0.2 
```

**Comment by darangi** [comment]
Thanks for reporting this!

This has already been fixed on `master`. It is currently scheduled for release when `v1.53.0` reaches Stable.
