### ISSUE TITLE
Uncaught Error: The module (electron/js2c/asar.jar:138, fuzzy-native)

### ISSUE THREAD

**Issue by Iazzetta** [atom/atom#21703]
[Enter steps to reproduce:]

1. Open atom
2. Command + Save (save document)

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.14
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The module '/Users/my_user/Downloads/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/@atom/fuzzy-native/build/Release/fuzzy-native.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

```
At electron/js2c/asar.js:138

Error: The module '/Users/my_user/Downloads/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/@atom/fuzzy-native/build/Release/fuzzy-native.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /app.asar/node_modules/@atom/fuzzy-native/lib/main.js:1:173)
    at /app.asar/node_modules/@atom/fuzzy-native/lib/main.js:3:3)
    at Module.get_Module._compile (/Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:1:695414)
    at get_NativeFuzzy (/Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:14:585880)
    at /Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:14:589904
    at Config.observeKeyPath (/Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:334918)
    at Config.observe (/Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:329400)
    at new FuzzyFinderView (/Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:14:589699)
    at new ProjectView (/Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:797215)
    at Object.createProjectView (/Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:188438)
    at HTMLElement.fuzzy-finder:toggle-file-finder (/Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:186936)
    at CommandRegistry.handleCommandEvent (/Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:349780)
    at KeymapManager.dispatchCommandEvent (/Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:1230988)
    at KeymapManager.handleKeyboardEvent (/Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:1227122)
    at WindowEventHandler.handleDocumentKeyEvent (/Users/my_user/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:284829)
```

### Commands

```
     -0:55.1.0 core:copy (input.hidden-input)
     -0:54.9.0 core:save (input.hidden-input)
     -0:38.1.0 tree-view:add-folder (div.header.list-item)
  6x -0:36.1.0 core:backspace (input.hidden-input)
     -0:33.9.0 core:confirm (input.hidden-input)
     -0:31.3.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:30.6.0 core:backspace (input.hidden-input)
     -0:29.9.0 core:confirm (input.hidden-input)
     -0:23.8.0 fuzzy-finder:toggle-file-finder (div.tool-panel.tree-view)
     -0:23.4.0 tree-view:move (div.tool-panel.tree-view)
     -0:22.3.0 core:select-all (input.hidden-input)
     -0:22 core:cancel (input.hidden-input)
     -0:21.4.0 tree-view:unfocus (div.tool-panel.tree-view)
     -0:19.4.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:16.5.0 core:save (input.hidden-input)
     -0:15.8.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
```

### Non-Core Packages

```
atom-jade 0.3.0 
atom-wrap-in-tag 0.6.0 
auto-update-plus 0.5.8 
browse 3.1.2 
build 0.70.0 
busy 0.7.0 
busy-signal 2.0.1 
ctrl-dir-scroll 0.2.5 
gloom 0.6.5 
language-elixir 0.24.0 
language-vue 0.26.0 
minimap 4.29.9 
multi-cursor 3.0.0 
satisfy-dependencies 0.4.3 
set-syntax 0.4.0 
sublime 0.5.0 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.5 
sublime-word-navigation 0.2.1 
sublimify 0.10.0 
tag 0.5.0 
teletype 0.13.4 
text-manipulation 0.6.0 
uikit-atom 0.3.2 
xml-formatter 0.13.0 
```

**Comment by sadick254** [comment]
Have you tried installing the latest version of atom `v1.53.0` ? Have you seen any error while trying to open the latest version? If you have please let us know.
