### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.52.0\1.txt'

### ISSUE THREAD

**Issue by Solrak97** [atom/atom#21718]
[Enter steps to reproduce:]

1. Created a Directory from Atom
2. Copy some text files directly from Winrar to the Atom directory
The files where uncompressed on Winrar, they usually decompress automatically when you drag them into a new directory

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Solrak\AppData\Local\atom\app-1.52.0\1.txt'

```
At fs.js:126

Error: ENOENT: no such file or directory, lstat 'C:\Users\Solrak\AppData\Local\atom\app-1.52.0\1.txt'
    at Proxy.realpathSync (fs.js:1470:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:969209)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:976382)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:949769)
```

### Commands

```
     -2:12.6.0 editor:newline (input.hidden-input)
     -2:11.3.0 snippets:next-tab-stop (input.hidden-input)
     -2:11.3.0 snippets:expand (input.hidden-input)
     -2:11.3.0 editor:indent (input.hidden-input)
  4x -2:07.8.0 core:move-left (input.hidden-input)
  4x -2:02.4.0 core:move-right (input.hidden-input)
     -2:00.3.0 core:move-left (input.hidden-input)
     -1:59.9.0 core:backspace (input.hidden-input)
     -1:59.4.0 core:move-right (input.hidden-input)
     -1:58.7.0 editor:newline (input.hidden-input)
     -1:58.2.0 intentions:highlight (input.hidden-input)
     -1:58.1.0 core:save (input.hidden-input)
     -1:49.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:27.4.0 tree-view:add-folder (span.name.icon.icon-repo)
  4x -1:22.9.0 core:backspace (input.hidden-input)
     -1:21.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-haskell 0.4.0 
autocomplete-haskell 1.0.1 
busy-signal 2.0.1 
haskell-ghc-mod 2.2.6 
haskell-pointfree 0.2.0 
haskell-scry 1.0.9 
hasklig 0.4.0 
ide-haskell 2.4.1 
ide-haskell-cabal 2.5.0 
ide-haskell-hasktags 0.0.17 
ide-haskell-hoogle 0.1.2 
ide-haskell-repl 0.10.0 
intentions 1.1.5 
language-haskell 1.20.0 
linter 2.3.1 
linter-ui-default 1.8.1 
```

**Comment by Solrak97** [comment]
Ok so it seems like the Directory was never created on the file system, just on the interface and thats causing the error
