### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.53.0\1422223...

### ISSUE THREAD

**Issue by anonymous675** [atom/atom#21720]
[Enter steps to reproduce:]

1. Download zipped folder with files
2. Paste files from the zipped folder to the project folder

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\user\AppData\Local\atom\app-1.53.0\1422223-tools'

```
At fs.js:126

Error: ENOENT: no such file or directory, lstat 'C:\Users\user\AppData\Local\atom\app-1.53.0\1422223-tools'
    at Proxy.realpathSync (fs.js:1470:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:996434)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:1003624)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:976614)
```

### Commands

```
     -4:30.2.0 core:undo (input.hidden-input)
     -4:08.1.0 core:paste (input.hidden-input)
     -4:07.5.0 core:save (input.hidden-input)
     -4:00.4.0 core:backspace (input.hidden-input)
     -3:59.5.0 core:save (input.hidden-input)
  6x -3:49.4.0 core:backspace (input.hidden-input)
     -3:47.9.0 core:save (input.hidden-input)
  2x -3:46.8.0 editor:newline (input.hidden-input)
     -3:43.4.0 core:save (input.hidden-input)
     -3:41.7.0 core:move-left (input.hidden-input)
 16x -3:41.4.0 core:move-right (input.hidden-input)
     -3:30.9.0 core:move-left (input.hidden-input)
     -3:29.7.0 core:save (input.hidden-input)
     -2:16 tree-view:add-folder (span.icon-file-directory.name.icon)
  9x -2:05.2.0 core:backspace (input.hidden-input)
     -1:55.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-nodejs-snippets 2.1.1 
atom-pug 0.2.0 
file-icons 2.1.43 
minimap 4.29.9 
pigments 0.40.6 
pug-paste 1.1.0 
todo-show 2.3.2 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
