### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\C:\Program Files\atom\app-1.48.0\re...

### ISSUE THREAD

**Issue by MansiLad** [atom/atom#21738]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Program Files\atom\app-1.48.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:138

Error: The specified module could not be found.
\\?\C:\Program Files\atom\app-1.48.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (C:/Program Files/atom/app-1.48.0/resources/app/static/<embedded>:1:735013)
    at get_KeyboardLayoutManager (C:/Program Files/atom/app-1.48.0/resources/app/static/<embedded>:14:2676864)
    at get_manager (C:/Program Files/atom/app-1.48.0/resources/app/static/<embedded>:14:2676966)
    at Object.getCurrentKeyboardLayout (C:/Program Files/atom/app-1.48.0/resources/app/static/<embedded>:14:2677092)
    at e.keystrokeForKeyboardEvent (C:/Program Files/atom/app-1.48.0/resources/app/static/<embedded>:14:1022283)
    at KeymapManager.keystrokeForKeyboardEvent (C:/Program Files/atom/app-1.48.0/resources/app/static/<embedded>:11:1239343)
    at KeymapManager.handleKeyboardEvent (C:/Program Files/atom/app-1.48.0/resources/app/static/<embedded>:11:1237328)
    at WindowEventHandler.handleDocumentKeyEvent (C:/Program Files/atom/app-1.48.0/resources/app/static/<embedded>:11:284835)
```

### Commands

```
     -2:26.2.0 window:toggle-full-screen (input.hidden-input)
     -2:23.4.0 window:toggle-menu-bar (input.hidden-input)
  3x -1:45.7.0 window:toggle-full-screen (input.hidden-input)
  2x -1:13.8.0 application:open-file (input.hidden-input)
```

### Non-Core Packages

```
platformio-ide-terminal 2.10.0 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
