### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\GitHubDesktop\app-2.6.0...

### ISSUE THREAD

**Issue by Integromedia-BlackCode** [atom/atom#21798]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: PC-MAIN
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Nutzer\AppData\Local\GitHubDesktop\app-2.6.0\app'

```
At fs.js:126

Error: ENOENT: no such file or directory, lstat 'C:\Users\Nutzer\AppData\Local\GitHubDesktop\app-2.6.0\app'
    at Proxy.realpathSync (fs.js:1470:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:969209)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:976382)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:949769)
```

### Commands

```
     -0:58.3.0 core:undo (div.tool-panel.tree-view)
  3x -0:53.2.0 tree-view:remove (div.tool-panel.tree-view)
     -0:22 tree-view:copy (div.header.list-item.project-root-header)
     -0:20 tree-view:remove (div.header.list-item.project-root-header)
```

### Non-Core Packages

```

```

**Comment by darangi** [comment]
Hi, this has been resolved in verion 1.53, you can get it [here](https://atom.io/)
