### ISSUE TITLE
apm run error

### ISSUE THREAD

**Issue by Doumor** [atom/atom#21829]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
Appears in the theme installation menu and in the package installation menu.

```
internal/modules/cjs/loader.js:1065
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/lib/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeEPKNS_9CFunctionE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1065:18)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/src/git.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

**Actual behavior:**
I can't install any theme or packages.

### Versions
OS: Manjaro 20.2 Nibia
Kernel: x86_64 Linux 5.9.11-3-MANJARO

Atom    : 1.53.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

### Additional Information
apm --version cannot be started because of that error.

**Comment by Zakgeki** [comment]
I'm having a similar issue on my machine too.

### Description
This appears in the Packages, Themes, Updates and Install settings tabs. It also appears when running `apm` from the terminal.

```
internal/modules/cjs/loader.js:1057
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/lib/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeEPKNS_9CFunctionE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/src/git.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
```
#### Actual behavior:
Can't search install, update, or uninstall packages and themes.

### Versions
OS: Manjaro 20.2.1 Nibia
Kernel: x86_64 Linux 5.9.16-1-MANJARO

Atom    : 1.54.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

### Additional Information
n/a

**Comment by Zakgeki** [comment]
I was doing a bit of reading on the arch forums, maybe this bug should be moved to the repo for apm, since appears to be an issue with apm and not atom itself?

[The forum post.](https://bbs.archlinux.org/viewtopic.php?id=219053l)

**Comment by Doumor** [comment]
> I was doing a bit of reading on the arch forums, maybe this bug should be moved to the repo for apm, since appears to be an issue with apm and not atom itself?
> 
> [The forum post.](https://bbs.archlinux.org/viewtopic.php?id=219053l)

Anyway, I haven't had the problem for a long time. In my case, the problem turned out to be different package versions. I put on top of the Manjaro repositories the BlackArch repositories.

I hope you don't have that problem anymore.
