### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Dropbox\My PC (DESKTOP-OMGKASR)\Deskt...

### ISSUE THREAD

**Issue by caldwelljt2** [atom/atom#21838]
[Enter steps to reproduce:]

1. added folder to ATOM (i'm new to ATOM)
2. opened separate window/folder in explorer.exe
3. attempted to drag a file from explorer to the folder in atom (just testing if it would "just work") to copy the file to the relative folder
4. I don't know if it matters, but one of the folders was a streamed folder for like, onedrive or google drive

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\jonathan\Dropbox\My PC (DESKTOP-OMGKASR)\Desktop\test.js'

```
At fs.js:126

Error: ENOENT: no such file or directory, lstat 'C:\Users\jonathan\Dropbox\My PC (DESKTOP-OMGKASR)\Desktop\test.js'
    at Proxy.realpathSync (fs.js:1470:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:996434)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:1003624)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:976614)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by caldwelljt2** [comment]
Looks like it was related to non-existent file in recent history?

**Comment by ThatXliner** [comment]
When you mean the folder in atom, do you mean the [tree-view](https://github.com/atom/tree-view)?

**Comment by sadick254** [comment]
Have you experienced the issue again?
