### ISSUE TITLE
Centos Linux 7.9: 7.9.2009: Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found 

### ISSUE THREAD

**Issue by ExcellentServ** [atom/atom#21860]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
$atom
$ cat ~/.atom/nohup.out 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/atom/resources/app.asar.unpacked/node_modules/nslog/build/Release/nslog.node)
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/nslog/lib/nslog.js:5:11)

### Steps to Reproduce

Run atom from terminal or try to open any file with atom

**Expected behavior:**

Open atom

**Actual behavior:**

Nothing open and throw error in log as below :

$ cat ~/.atom/nohup.out 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/atom/resources/app.asar.unpacked/node_modules/nslog/build/Release/nslog.node)
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/nslog/lib/nslog.js:5:11)

**Reproduces how often:**

always!

### Versions

$ atom --version
Atom    : 1.53.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

$ apm --version
internal/modules/cjs/loader.js:815
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/atom/resources/app/apm/node_modules/git-utils/build/Release/git.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:815:18)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/git-utils/src/git.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)

$ cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

### Additional Information

None

**Comment by onmeac** [comment]
Confirmed, latest atom fails for me too.

I had to reverd back to version 1.46 before atom could start.

**Comment by janime42** [comment]
I'm seeing this issue as well.

Atom    : 1.56.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1

**Comment by AndrewMeir** [comment]
Still broken in 1.57.0.

Atom    : 1.57.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1

$ cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

$ cat .atom/nohup.out 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/atom/resources/app.asar.unpacked/node_modules/nslog/build/Release/nslog.node)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/nslog/lib/nslog.js:5:11)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/nslog/lib/nslog.js:15:4)

**Comment by ZUUL42** [comment]
I have run into this as well using RHEL7.
The only work around I've found so far is to  downgrade to Atom 1.51.0.

**Comment by robert914** [comment]
I'm still seeing this same issue on CentOS 7.9 with Atom versions 1.49.0 and 1.51.0. Is there any resolution or workaround for this issue?

**Comment by fastzombies** [comment]
1.58.0 also has this issue.  Tried setting LD_LIBRARY_PATH to a locally installed libstdc++.so.6.0.25 (no sudo) and no version of atom will start.  Workaround is use 1.51.0 and keep closing the bug window.
