### ISSUE TITLE
Error when renaming file that has only numbers in name

### ISSUE THREAD

**Issue by Caellion** [atom/atom#21881]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When trying to RENAME/MOVE (not delete or create) a file in a git repository which (the file) contains only numbers in name (in test it was 20210119.md) following error is reported in developer tools and no further changes to the commit / staging is registered in atom. File extensions seem to not matter.

When closing and reopening atom the same error appears immediately and repository is not shown, as if it did not exist.

The error:
```
Uncaught (in promise) TypeError: Cannot read property '9' of null
    at parseRenamedOrCopiedEntry (C:\Users\<USER>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:14:3256055)
    at parseLine (C:\Users\<USER>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:14:3256508)
    at Stream.<anonymous> (C:\Users\<USER>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:14:3257436)
    at Stream.emit (events.js:200:13)
    at drain (C:\Users\<USER>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:14:3798125)
    at Stream.d.queue.d.push (C:\Users\<USER>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:14:3798343)
    at emit (C:\Users\<USER>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:14:3707443)
    at next (C:\Users\<USER>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:14:3707630)
    at Stream.<anonymous> (C:\Users\<USER>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:14:3707662)
    at Stream.d.write (C:\Users\<USER>\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:14:3798253)
    at Readable.ondata (_stream_readable.js:713:22)
    at Readable.emit (events.js:200:13)
    at Readable.read (_stream_readable.js:508:10)
    at flow (_stream_readable.js:977:34)
    at emitReadable_ (_stream_readable.js:572:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

### Steps to Reproduce

1. Initialize a git repo
2. Create 20210119.md in root of the repo
3. Stage and commit
4. Move the file into a folder inside the repo
5. Create another file in the repo, name it whatever you wish
5. Stage the move from step 4
6. Try staging the addition

**Expected behavior:**

The changes get staged

**Actual behavior:**

Editor is stuck without showing the stage and git module gets unresponsive

**Reproduces how often:**

Reproducible 100% on files containing only numbers in name. Succeded in reproducing when file had date in name.
Problem was impossible to reproduce when file had any letter in name. Adding just an a at the beginning of the file fixes the problem immediately (besides having to recreate the repo, because atom won't move or rename the file in question)

### Versions

Atom 1.54 and Atom 1.52 running on Windows 10 20H2

atom version from latest test:
```
Atom    : 1.54.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.54.0
python 3.7.9
git 2.30.0.windows.2
visual studio 2015
```

**Comment by darangi** [comment]
Could you try reproducing this in[ safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by Caellion** [comment]
I have reproduced this in safe mode, in both 1.52 and 1.54 (thought checking X in prerequisite meant that I did reproduce in safe mode and I don't have to mention this)

**Comment by Caellion** [comment]
I have just confirmed the issue also appears on 1.52  with Windows 7 SP1, so it seems not related to the OS, or at least not significantly.

**Comment by Caellion** [comment]
After looking around a bit, this might be related to #21826
@DeeDeeG can you take a look at this?

**Comment by DeeDeeG** [comment]
I can reproduce the problem at least.

According to some more-useful error messages in [another issue](https://github.com/Tehnix/ide-haskell-hie/issues/5), I learned what package this error message is generated from (it's `what-the-status`):

Here's the `parseRenamedOrCopiedEntry()` function: https://github.com/kuychaco/what-the-status/blob/v1.0.3/index.js#L150

**Comment by DeeDeeG** [comment]
Either some version or other of `git` used by the `github` package (`dugite`? shelling out to `git` on the `PATH`?) is feeding `what-the-diff` some bad data, or there is a type safety issue in `what-the-diff`, or something loosely related to all that. (An educated guess to start off with).

**Comment by Caellion** [comment]
I have enabled git output to console, the error appears when atom tries to execute this statement:
```
git status --porcelain=v2 --branch --untracked-files=all --ignore-submodules=dirty -z in C:\Users\Caellion\Desktop\aa
```
From devtools i got also these:
```
exit status 0

full arguments [ '-c', 'color.ui=false', '-c', 'color.status=false', '-c', 'color.showBranch=false', '-c', 'color.diff=false', '-c', 'color.branch=false', 'status', '--porcelain=v2', '--branch', '--untracked-files=all', '--ignore-submodules=dirty', '-z' ]

stdout
# branch.oid 59ab4ae3a6877e0b767858c34e4c1b7cbed8da5e<NUL>
# branch.head master<NUL>
2 R. N... 100644 100644 100644 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 R100 ax/22222222.md<NUL>
22222222.md<NUL>

stderr
22:53:55.333000 exec-cmd.c:237          trace: resolved executable dir: E:/Atom/app-1.52.0/resources/app.asar.unpacked/node_modules/dugite/git/mingw64/bin
22:53:55.335000 git.c:440               trace: built-in: git status --porcelain=v2 --branch --untracked-files=all --ignore-submodules=dirty -z
```

When i run it in cmd i get this:
```
# branch.oid 59ab4ae3a6877e0b767858c34e4c1b7cbed8da5e # branch.head master 2 R. N... 100644 100644 100644 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 R100 ax/22222222.md 22222222.md
```

And when I ran with git from this path `E:/Atom/app-1.52.0/resources/app.asar.unpacked/node_modules/dugite/git/mingw64/bin`  I got exactly same output


The entrypoint for this data seems to lay around here https://github.com/kuychaco/what-the-status/blob/64688d745bc4324f08de8f0795cf5609d2cf6588/index.js#L66
and it seems `parseRenamedOrCopiedEntry` gets this fed in `R. N... 100644 100644 100644 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 R100 ax/22222222.md`

I am not skilled enough to lok through regex but it seems with that input this https://github.com/kuychaco/what-the-status/blob/64688d745bc4324f08de8f0795cf5609d2cf6588/index.js#L7 regex returns null

**Comment by Caellion** [comment]
I think I have pinpointed the issue:

In my tests I only used files that were based on today's and yesterday's dates, with YEAR at start. They all were starting with `2`!

I did try to reproduce this issue with file named `555.md` and it did not happen.

What it seems to me now is that when git returns `[...] R100 ax/22222222.md<NUL>22222222.md<NUL>` then `what-the-status` gets the first line (null-termination) right (as in, it parses and shows that I have staged something), but then gets to the second line, which happens to be  `22222222.md` and thinks its first character (`2`) denotes another move and then it derps out from there.

Guess simple length check around here https://github.com/kuychaco/what-the-status/blob/64688d745bc4324f08de8f0795cf5609d2cf6588/index.js#L56 would get this fixed. I may of course be wrong as I am not sure if ignoring that half-baked line would not implode the universe.

curiously, when I tried the same process with file named #.md5 (hash; same for !.md - exclamation) I got this result in atom, although it did not derp out completely - possibly it didn't derp out because I moved to folder named `uu`.
![image](https://user-images.githubusercontent.com/19575594/105249407-5aa68e00-5b78-11eb-8a55-df5bb943f480.png)

And for files starting with `1` or `u` I get exactly the same result as with `2`.

**Comment by DeeDeeG** [comment]
If you can propose a more specific patch to `what-the-status`, I'd be willing to build Atom with it and see if it fixes the problem for these steps to reproduce, once I get a good moment to do that.

**Comment by Caellion** [comment]
I am kind of in progress of making a PR now. Although I don't know js very well but I think I got it.
