### ISSUE TITLE
Failed to load the atom-emmet-css-in-js package

### ISSUE THREAD

**Issue by Elyasomer** [atom/atom#21933]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: 'atom-emmet-css-in-js' package vundefined

### Stack Trace

Failed to load the atom-emmet-css-in-js package

```
At The "path" argument must be of type string. Received type object

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:107:11)
    at Object.resolve (path.js:136:9)
    at /packages/atom-emmet-css-in-js/lib/shims.js:4:26)
    at /packages/atom-emmet-css-in-js/lib/shims.js:52:34)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/atom-emmet-css-in-js/lib/atom-emmet-css-in-js.js:3:24)
    at /packages/atom-emmet-css-in-js/lib/atom-emmet-css-in-js.js:92:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:1:723602)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3670531)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3657071
    at Package.measure (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3655871)
    at Package.load (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3656644)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:382220)
    at PackageManager.loadPackage (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:380948)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:383520)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:916751
    at r (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:911357)
    at s (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:1121307)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:1121513)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
  4x -2:15.1.0 core:undo (input.hidden-input)
     -2:13.9.0 core:save (input.hidden-input)
     -2:08.9.0 core:select-all (input.hidden-input)
     -2:07.1.0 core:backspace (input.hidden-input)
     -1:21.3.0 snippets:next-tab-stop (input.hidden-input)
     -1:21.3.0 snippets:expand (input.hidden-input)
     -1:21.3.0 editor:indent (input.hidden-input)
     -1:20.7.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -1:20 core:save (input.hidden-input)
     -1:11 editor:newline (input.hidden-input)
     -1:07.5.0 core:backspace (input.hidden-input)
     -1:06.9.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
  2x -1:06.0 core:undo (input.hidden-input)
  3x -1:05.2.0 core:backspace (input.hidden-input)
     -1:04.3.0 core:save (input.hidden-input)
     -0:49 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
atom-emmet-css-in-js 0.2.0 
react 0.18.0 
```

**Comment by ThatXliner** [comment]
This is probably (I'm not that great at JS) a problem with the [`atom-emmet-css-in-js`](https://atom.io/packages/atom-emmet-css-in-js) package. Does this reproduce in [safe mode](https://flight-manual.atom.io/faq/sections/what-does-safe-mode-do/)? If not, then you should open an issue at their [repo](https://github.com/brumm/atom-emmet-css-in-js/issues).

**Comment by Elyasomer** [comment]
I don't need it anymore but thanks for your response

**Comment by Elyasomer** [comment]
No need anymore

**Comment by HeeyaAmin** [comment]
I'm also having the same issue with emmet-js
Could you please share how you resolved the issue?
