### ISSUE TITLE
Failed to activate the atom-template-engine package

### ISSUE THREAD

**Issue by tirtharajbhowmik** [atom/atom#22009]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: 'atom-template-engine' package vundefined

### Stack Trace

Failed to activate the atom-template-engine package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at /packages/atom-template-engine/lib/atom-template-engine.js:53:26
    at Array.forEach (<anonymous>)
    at Object.plugin.activate (/packages/atom-template-engine/lib/atom-template-engine.js:52:6)
    at Package.activateNow (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3658881)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3658293
    at Package.measure (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3655871)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3658153
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3658096)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:383646)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:916751
    at r (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:911357)
    at s (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:1121307)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:1121513)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
     -1:08.9.0 core:backspace (input.hidden-input)
  8x -1:07.4.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-live-server-plus 3.0.1 
atom-material-ui 2.1.3 
atom-smart-template 0.3.2 
atom-ternjs 0.20.0 
atom-whatsapp 0.1.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
code-share 1.0.0 
csslint 1.2.0 
emmet 2.4.3 
Hydrogen 2.14.1 
hyperclick 0.1.5 
ide-c-cpp 0.1.0 
ide-cquery 0.14.0 
ide-sourcekit 1.0.1 
intentions 1.1.5 
kite 0.197.0 
language-ejs 0.4.0 
linter 3.1.1 
linter-eslint 8.5.5 
linter-js-standard-engine 2.3.0 
linter-jshint 3.1.19 
linter-tree-sitter 0.1.3 
linter-ui-default 2.3.1 
minimap 4.35.7 
minimap-tree-sitter-syntax 0.0.0 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
TabNine 2.8.1 
teletype 0.13.4 
template-atom 1.1.0 
```

**Comment by ThatXliner** [comment]
This is probably an issue with that package

**Comment by darangi** [comment]
Could you report this issue in the `atom-template-engine` repo? we do not maintain this packaage
