### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\Temp\peazip-tmp\drop8BF...

### ISSUE THREAD

**Issue by manas-ENG** [atom/atom#22010]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\MANAS\AppData\Local\Temp\peazip-tmp\drop8BF614\source\*'

```
At fs.js:126

Error: ENOENT: no such file or directory, lstat 'C:\Users\MANAS\AppData\Local\Temp\peazip-tmp\drop8BF614\source\*'
    at Proxy.realpathSync (fs.js:1470:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:996503)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:1003693)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:976665)
```

### Commands

```
  2x -8:11 tree-view:add-file (span.name.icon.icon-file-directory)
     -7:47 tree-view:add-folder (span.name.icon.icon-file-directory)
  2x -7:45.1.0 core:confirm (input.hidden-input)
     -7:27.2.0 tree-view:remove (span.name.icon.icon-file-directory)
     -7:00.5.0 tree-view:move (span.name.icon.icon-file-directory)
     -4:59.9.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -4:59.9.0 editor:newline (input.hidden-input)
     -4:56.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:49.8.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -2:46.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
pigments 0.40.6 
```

**Comment by LinuxRocks2000** [comment]
Looks like its trying to use `*` files/directories on a Windows system. `*` is a Linux-only thing. Perhaps try reinstalling using the official EXE, or just running in an Ubuntu VM
