### ISSUE TITLE
Package installation error

### ISSUE THREAD

**Issue by ThisIsMatin** [atom/atom#22031]
I installed Atom on Linux. But I get an error when installing the package
```
node:internal/modules/cjs/loader:478
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bin/npm-cli' is not defined by "exports" in /usr/lib/node_modules/npm/package.json
    at new NodeError (node:internal/errors:329:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:337:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:562:3)
    at resolveExports (node:internal/modules/cjs/loader:472:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:512:31)
    at Function.node_module._findPath (/usr/lib/node_modules/atom-package-manager/node_modules/asar-require/lib/require.js:141:32)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:909:27)
    at Function.resolve (node:internal/modules/cjs/helpers:98:19)
    at new Install (/usr/lib/node_modules/atom-package-manager/lib/install.js:53:34)
    at Object.run (/usr/lib/node_modules/atom-package-manager/lib/apm-cli.js:240:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```
I deleted the .atom folder, package-lock.json, install @babel/helper-compilation-targets, re-install atom, re-install npm, re-install node.js
But there is still a problem!

**Comment by UziTech** [comment]
What version of linux?

**Comment by ThisIsMatin** [comment]
> What version of linux?

This is my screenfetch
![image](https://user-images.githubusercontent.com/59957018/111058362-5ecd9880-84a3-11eb-906b-0bbb805ea72c.png)

**Comment by mobrine1** [comment]
@ThisIsMatin this is an issue in the mainstream arch linux. It will take some time before the manjaro repos get the latest updates
https://github.com/atom/apm/issues/918

**Comment by aminya** [comment]
Are you using the official binaries downloaded from `atom.io` or it is an unofficial package?

https://atom.io/

**Comment by ThisIsMatin** [comment]
> Are you using the official binaries downloaded from `atom.io` or it is an [unofficial unsupported Atom](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md)?
> 
> https://atom.io/

Yes, this is the original version of the atom

**Comment by aminya** [comment]
Follow the instructions here:
https://github.com/atom/apm/issues/918#issuecomment-799637198
