### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=503

### ISSUE THREAD

**Issue by zhang1career** [atom/atom#22056]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.2.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=503

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:288:20)
    at ClientRequest.emit (events.js:200:13)
    at Socket.socketOnData (_http_client.js:485:11)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by darangi** [comment]
This could be a temporary network problem or maybe you are behind a proxy?

**Comment by zhang1career** [comment]
Yes, I was behind a proxy.

**Comment by darangi** [comment]
There goes the problem. I will go ahead and close this issue
