### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.46.0\ C  '

### ISSUE THREAD

**Issue by thom0075** [atom/atom#22083]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\thoma\AppData\Local\atom\app-1.46.0\ C  '

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\thoma\AppData\Local\atom\app-1.46.0\ C  '
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1002525)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1009454)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:983085)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
script 3.26.0 
```

**Comment by thom0075** [comment]
..
