### ISSUE TITLE
Meta: Outdated javascript compilers + old atom repos

### ISSUE THREAD

**Issue by icecream17** [atom/atom#22099]
## Summary

I changed some files in an atom clone to use newer syntax (#22099)

I followed the instructions on [hacking atom core](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#platform-windows), but when I did `script/build`

![image](https://user-images.githubusercontent.com/58114641/112916960-44acd080-90c7-11eb-83dc-0fd25e70ec4f.png)
```
PS C:\Users\Steven\Documents\GitHub\clones\atom> script/build
Node:   v15.10.0
Npm:    v6.14.8
Python: v3.9.2
Installing script dependencies
Installing apm
apm  2.5.2
npm  6.14.8
node 15.10.0 x64
atom 1.57.0-dev
python 3.9.2
git 2.31.1.windows.1
visual studio 2015
Installing modules done
Wrote Dependencies Fingerprint: C:\Users\Steven\Documents\GitHub\clones\atom\node_modules\.dependencies-fingerprint 00ccb4f780c4ba9edc1c0ce04d886e84d2f0c1dd
Copying assets to C:\Users\Steven\Documents\GitHub\clones\atom\out\app
Transpiling packages with custom transpiler configurations in C:\Users\Steven\Documents\GitHub\clones\atom\out\app
 transpiling for package github
Installing modules done
Transpiling Babel paths in C:\Users\Steven\Documents\GitHub\clones\atom\out\app
Transpiling CoffeeScript paths in C:\Users\Steven\Documents\GitHub\clones\atom\out\app
Transpiling CSON paths in C:\Users\Steven\Documents\GitHub\clones\atom\out\app
Transpiling PEG.js paths in C:\Users\Steven\Documents\GitHub\clones\atom\out\app
Generating module cache for C:\Users\Steven\Documents\GitHub\clones\atom\out\app
Generating pre-built less cache in C:\Users\Steven\Documents\GitHub\clones\atom\out\app\less-compile-cache
Generating metadata for C:\Users\Steven\Documents\GitHub\clones\atom\out\app\package.json
Generating API docs at C:\Users\Steven\Documents\GitHub\clones\atom\docs\output\atom-api.json
Error: processing joanna docs for file src/atom-environment.js
C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\src\index.js:18
      throw e
      ^

[SyntaxError: Unexpected token (63:25)
  at Parser.pp$5.raise (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:4454:13)
  at Parser.pp.unexpected (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:1761:8)
  at Parser.pp$3.parseExprAtom (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:3750:12)
  at Parser.parseExprAtom (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:7238:22)
  at Parser.pp$3.parseExprSubscripts (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:3494:19)
  at Parser.pp$3.parseMaybeUnary (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:3474:19)
  at Parser.pp$3.parseExprOps (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:3404:19)
  at Parser.pp$3.parseMaybeConditional (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:3381:19)
  at Parser.pp$3.parseMaybeAssign (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:3344:19)
  at Parser.pp$3.parseConditional (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:3391:28)
  at Parser.pp$3.parseMaybeConditional (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:3384:15)
  at Parser.pp$3.parseMaybeAssign (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:3344:19)
  at Parser.pp$3.parseMaybeAssign (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:3367:23)
  at Parser.pp$3.parseExpression (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:3306:19)
  at Parser.pp$1.parseStatement (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:1906:19)
  at Parser.pp$1.parseBlockBody (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:2268:21)
  at Parser.pp$1.parseBlock (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:2247:8)
  at Parser.pp$3.parseFunctionBody (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:4235:22)
  at Parser.pp$3.parseMethod (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:4180:8)
  at Parser.pp$1.parseClassMethod (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:2583:8)
  at Parser.pp$1.parseClassBody (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:2510:14)
  at Parser.pp$1.parseClass (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:2406:8)
  at Parser.pp$1.parseStatement (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:1843:19)
  at Parser.pp$1.parseBlockBody (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:2268:21)
  at Parser.pp$1.parseTopLevel (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:1778:8)
  at Parser.parse (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:1673:17)
  at Object.parse (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\node_modules\babylon\lib\index.js:7305:37)
  at Generator.generate (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\src\generate.js:26:24)
  at generate (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\src\generate.js:6:30)
  at run (C:\Users\Steven\Documents\GitHub\clones\atom\script\node_modules\joanna\src\index.js:15:32)
  at module.exports (C:\Users\Steven\Documents\GitHub\clones\atom\script\lib\generate-api-docs.js:22:22)
  at Object.<anonymous> (C:\Users\Steven\Documents\GitHub\clones\atom\script\build:85:3)
  at Module._compile (node:internal/modules/cjs/loader:1091:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
  at Module.load (node:internal/modules/cjs/loader:971:32)
  at Function.Module._load (node:internal/modules/cjs/loader:812:14)
  at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
  at node:internal/main/run_main_module:17:47
] {
  pos: 2732,
  loc: Position { line: 63, column: 25 }
}
```

But oh no! "??" isn't parsed correctly!

Turns out, this error comes from `joanna`, which uses `babylon` instead of `@babel/parser` and is obviously outdated by several years

## Motivation

Wanted to "fix" something and use "??" but now this happened.

Also joanna has a bunch of security vulnerabilities

When I updated joanna's dependencies, the tester dependency `mocha` found errors in the dependency `donna`, which is also by atom.

```
npm test

> joanna@0.0.12 test
> mocha test        


C:\Users\Steven\Documents\GitHub\clones\joanna\node_modules\donna\src\nodes\file.coffee:20:7: error: Can't reference 'this' before calling super in derived class constructors
      @methods = []
      ^
```

## Additional context
Opening up atom beta, and putting `navigator` in the console gets this:
![image](https://user-images.githubusercontent.com/58114641/112921772-fac8e800-90d0-11eb-8201-87957f747655.png)

```javascript
appCodeName: "Mozilla"
appName: "Netscape"
appVersion: "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Atom/1.56.0-beta0 Chrome/83.0.4103.122 Electron/9.4.4 Safari/537.36"
```

Those stats are outdated, but the console actually supports nullish coalescing (but not logical assignment) which means that `joanna` is more outdated than those stats

Old repo links:
https://github.com/atom/joanna
https://github.com/atom/donna
https://github.com/atom/tello

**Comment by aminya** [comment]
Neither Node 12 nor Babel 5 support optional chaining or nullish coelcinsg.

These changes require merging #21623

**Comment by icecream17** [comment]
For some reason [CompositeDisposable](https://github.com/atom/event-kit/blob/master/lib/composite-disposable.js) expands into a for...of iteration polyfill, even though that's already supported

![image](https://user-images.githubusercontent.com/58114641/151290568-259065f2-084e-46e5-99e7-4d9fae8f8d89.png)

Maybe it would be possible to update babel just a little bit
