### ISSUE TITLE
Fails to build due to Python 3 being /usr/bin/python

### ISSUE THREAD

**Issue by Kwpolska** [atom/atom#2211]
The [build instructions](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md) say to do `npm config set python /usr/bin/python2 -g` — and so I did, yet I still couldn’t build Atom.  I had to do `PYTHON=/usr/bin/python2 script/build` to bypass this.

Arch Linux x86_64.

_Also, bonus bit of pedantry: doesn’t build if CC/CXX = clang. That’s a non-issue, though._

**ninja edit:** misspelled `python2` in `PYTHON=…`

**Comment by Moter8** [comment]
Still an issue today, full stacktrace here:

```bash
[shell@arch-moter8-vm atom]$ sudo npm config set python /usr/bin/python2 -g
[shell@arch-moter8-vm atom]$ script/build
Node: v0.12.2
npm: v2.5.1
Installing build modules...
Installing apm...
Installing modules ✗
> atom@0.189.0 preinstall /home/shell/git/atom
> node -e 'process.exit(0)'


> oniguruma@4.2.0 install /home/shell/git/atom/node_modules/oniguruma
> node-gyp rebuild


> scrollbar-style@2.0.0 install /home/shell/git/atom/node_modules/scrollbar-style
> node-gyp rebuild


> keyboard-layout@0.10.0 install /home/shell/git/atom/node_modules/atom-keymap/node_modules/keyboard-layout
> node-gyp rebuild


> runas@2.0.0 install /home/shell/git/atom/node_modules/runas
> node-gyp rebuild


> nslog@2.0.0 install /home/shell/git/atom/node_modules/nslog
> node-gyp rebuild


> git-utils@3.0.0 install /home/shell/git/atom/node_modules/git-utils
> node-gyp rebuild


> pathwatcher@4.4.0 install /home/shell/git/atom/node_modules/pathwatcher
> node-gyp rebuild


npm WARN package.json stacktrace-parser@0.1.1 No repository field.
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.                     
gyp ERR! stack     at failPythonVersion (/home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)                                                     
gyp ERR! stack     at /home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9                                                                           
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)                                     
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)                                                   
gyp ERR! stack     at maybeClose (child_process.js:766:16)                                                  
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)                          
gyp ERR! System Linux 3.19.3-1-ARCH                                                                         
gyp ERR! command "node" "/home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"                                                                   
gyp ERR! cwd /home/shell/git/atom/node_modules/oniguruma                                                    
gyp ERR! node -v v0.10.35                                                                                   
gyp ERR! node-gyp -v v1.0.2                                                                                 
gyp ERR! not ok                                                                                             
gyp ERR! configure error                                                                                    
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.                  
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.                     
gyp ERR! stack     at failPythonVersion (/home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)                                                     
gyp ERR! stack     at /home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9                                                                           
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)                                     
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)                                                   
gyp ERR! stack     at maybeClose (child_process.js:766:16)                                                  
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)                          
gyp ERR! System Linux 3.19.3-1-ARCH                                                                         
gyp ERR! command "node" "/home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"                                                                   
gyp ERR! cwd /home/shell/git/atom/node_modules/scrollbar-style                                              
gyp ERR! node -v v0.10.35                                                                                   
gyp ERR! node-gyp -v v1.0.2                                                                                 
gyp ERR! not ok                                                                                             
gyp ERR! configure error                                                                                    
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.                  
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.                     
gyp ERR! stack     at failPythonVersion (/home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)                                                     
gyp ERR! stack     at /home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9                                                                           
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)                                     
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)                                                   
gyp ERR! stack     at maybeClose (child_process.js:766:16)                                                  
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)                          
gyp ERR! System Linux 3.19.3-1-ARCH                                                                         
gyp ERR! command "node" "/home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"                                                                   
gyp ERR! cwd /home/shell/git/atom/node_modules/atom-keymap/node_modules/keyboard-layout                     
gyp ERR! node -v v0.10.35                                                                                   
gyp ERR! node-gyp -v v1.0.2                                                                                 
gyp ERR! not ok                                                                                             
gyp ERR! configure error                                                                                    
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.                  
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.                     
gyp ERR! stack     at failPythonVersion (/home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)                                                     
gyp ERR! stack     at /home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9                                                                           
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)                                     
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)                                                   
gyp ERR! stack     at maybeClose (child_process.js:766:16)                                                  
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)                          
gyp ERR! System Linux 3.19.3-1-ARCH                                                                         
gyp ERR! command "node" "/home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"                                                                   
gyp ERR! cwd /home/shell/git/atom/node_modules/runas                                                        
gyp ERR! node -v v0.10.35                                                                                   
gyp ERR! node-gyp -v v1.0.2                                                                                 
gyp ERR! not ok                                                                                             
gyp ERR! configure error                                                                                    
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.                  
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.                     
gyp ERR! stack     at failPythonVersion (/home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)                                                     
gyp ERR! stack     at /home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9                                                                           
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)                                     
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)                                                   
gyp ERR! stack     at maybeClose (child_process.js:766:16)                                                  
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)                          
gyp ERR! System Linux 3.19.3-1-ARCH                                                                         
gyp ERR! command "node" "/home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"                                                                   
gyp ERR! cwd /home/shell/git/atom/node_modules/nslog                                                        
gyp ERR! node -v v0.10.35                                                                                   
gyp ERR! node-gyp -v v1.0.2                                                                                 
gyp ERR! not ok                                                                                             
gyp ERR! configure error                                                                                    
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.                  
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.                     
gyp ERR! stack     at failPythonVersion (/home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)                                                     
gyp ERR! stack     at /home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9                                                                           
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)                                     
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)                                                   
gyp ERR! stack     at maybeClose (child_process.js:766:16)                                                  
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)                          
gyp ERR! System Linux 3.19.3-1-ARCH                                                                         
gyp ERR! command "node" "/home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"                                                                   
gyp ERR! cwd /home/shell/git/atom/node_modules/git-utils                                                    
gyp ERR! node -v v0.10.35                                                                                   
gyp ERR! node-gyp -v v1.0.2                                                                                 
gyp ERR! not ok                                                                                             
gyp ERR! configure error                                                                                    
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.                  
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.                     
gyp ERR! stack     at failPythonVersion (/home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)                                                     
gyp ERR! stack     at /home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9                                                                           
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)                                     
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)                                                   
gyp ERR! stack     at maybeClose (child_process.js:766:16)                                                  
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)                          
gyp ERR! System Linux 3.19.3-1-ARCH                                                                         
gyp ERR! command "node" "/home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"                                                                   
gyp ERR! cwd /home/shell/git/atom/node_modules/pathwatcher
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.19.3-1-ARCH
npm ERR! argv "/home/shell/git/atom/apm/node_modules/atom-package-manager/bin/node" "/home/shell/git/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/shell/.atom/.apm/.apmrc" "--userconfig" "/home/shell/.atom/.apmrc" "install" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@4.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@4.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shell/git/atom/npm-debug.log
```

**Comment by 2c4e** [comment]
Can confirm this issue still exists with the latest version of Atom using the latest version of Arch Linux.
[Build log output](https://gist.github.com/2c4e/e2a6e44e20229db4c70b).

Atom compiles just fine using <code>PYTHON=/usr/bin/python2 script/build</code> as @Moter8 said.

**Comment by jokeyrhyme** [comment]
This probably won't be a problem once Chromium / V8 / Node.js / etc all replace GYP with GN:
https://chromium.googlesource.com/chromium/src/+/master/tools/gn/README.md

**Comment by mangecoeur** [comment]
Same problem when running apm rebuild. When using npm install I can pass --python=python2.7 on OSX which correctly overrides the default python, but apm rebuild doesn't support this option

**Comment by tbranyen** [comment]
Now that latest NodeGit prebuilt is used, this can be closed right?

**Comment by mtbdeano** [comment]
On the Mac, I solved for this issue by finding where `apm` was installed (on my machine, MacOSX Sierra:  `/Applications/Atom.app/Contents/Resources/app/apm/bin`), then running: `./apm config set python /usr/bin/python2.7` in that folder. This command sets the python config for the `apm` program installed with atom, and doesn't mess with your global node setup. Or for copy/paste convenience:

    cd /Applications/Atom.app/Contents/Resources/app/apm/bin
    ./apm config set python /usr/bin/python2.7
