### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.55.0\bootstr...

### ISSUE THREAD

**Issue by KaterynePO** [atom/atom#22176]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Wizard\AppData\Local\atom\app-1.55.0\bootstrap-social-gh-pages'

```
At fs.js:126

Error: ENOENT: no such file or directory, lstat 'C:\Users\Wizard\AppData\Local\atom\app-1.55.0\bootstrap-social-gh-pages'
    at Proxy.realpathSync (fs.js:1470:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:996748)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:1003938)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:976910)
```

### Commands

```
     -4:20 emmet:insert-formatted-line-break-only (input.hidden-input)
     -4:20 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
linter 3.3.0 
linter-eslint 8.5.5 
linter-ui-default 3.2.5 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by KaterynePO** [comment]
commented
