### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.56.0\js'

### ISSUE THREAD

**Issue by Jaibeypi** [atom/atom#22316]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Jaibey Pisco\AppData\Local\atom\app-1.56.0\js'

```
At internal/fs/utils.js:220

Error: ENOENT: no such file or directory, lstat 'C:\Users\Jaibey Pisco\AppData\Local\atom\app-1.56.0\js'
    at Proxy.realpathSync (fs.js:1529:7)
    at Proxy.<anonymous> (electron/js2c/asar.js:302:42)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:14:1000634)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:14:1007824)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:14:980796)
```

### Commands

```
     -4:40.6.0 core:backspace (input.hidden-input)
     -4:38.3.0 autocomplete-plus:confirm (input.hidden-input)
 14x -4:37.4.0 core:backspace (input.hidden-input)
  3x -4:30.1.0 core:move-up (input.hidden-input)
 13x -4:28.5.0 core:move-left (input.hidden-input)
  2x -4:21.7.0 core:backspace (input.hidden-input)
  3x -4:14.4.0 core:move-down (input.hidden-input)
     -2:43.5.0 core:move-up (input.hidden-input)
     -2:42.9.0 core:move-right (input.hidden-input)
     -2:42.3.0 core:move-up (input.hidden-input)
     -2:41.8.0 core:move-left (input.hidden-input)
  2x -2:40.2.0 core:move-down (input.hidden-input)
 14x -2:39.5.0 core:move-right (input.hidden-input)
     -2:35 core:backspace (input.hidden-input)
  2x -2:29.9.0 autocomplete-plus:confirm (input.hidden-input)
  3x -2:24.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-bracket-highlight 0.3.2 
atom-clock 0.1.18 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-phpactor 0.3.8 
autocomplete-paths undefined 
ayu-dark-syntax 0.1.0 
blade-snippets 0.2.0 
bracket-colorizer 1.4.0 
busy-signal 2.0.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
ctrl-dir-scroll 0.2.5 
docblock-format-helper 0.3.0 
emmet 2.4.3 
expose 0.15.0 
file-icons 2.1.47 
highlight-selected 0.17.0 
hyperclick 0.1.5 
intentions 1.1.5 
language-blade 0.46.0 
laravel 0.7.1 
linter 3.3.1 
linter-ui-default 3.3.1 
minimap 4.39.13 
nms-color-bracket 0.1.0 
php-cs-fixer 4.2.0 
php-integrator-autocomplete-plus 1.6.2 
php-integrator-autocomplete-plus-legacy-php56 1.0.1 
php-integrator-navigation 1.2.1 
php-server 0.8.0 
pigments 0.40.6 
prettier-atom 0.60.1 
terminus 4.1.3 
```

**Comment by brightly-salty** [comment]
I'm having a similar issue whenever I try to use regex with find and replace or perform a project-wide search: 

**Atom**: 1.58.0-nightly0 x64
**Electron**: 9.4.4
**OS**: macOS 11.2.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: dlopen(/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app.asar.unpacked/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node, 1): image not found

```
At /private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app.asar/node_modules/tree-sitter/index.js:8

Error: dlopen(/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app.asar.unpacked/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node, 1): image not found
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:149153)
    at /app.asar/node_modules/tree-sitter/index.js:3:13)
    at /app.asar/node_modules/tree-sitter/index.js:757:3)
    at Module.get_Module._compile (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:1:756278)
    at get_Parser (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:3291620)
    at Function._patchSyntaxNode (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:3292128)
    at new TreeSitterLanguageMode (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:3292384)
    at GrammarRegistry.languageModeForGrammarAndBuffer (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:358290)
    at TextEditor.setGrammar (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:46374)
    at FindView.updateSyntaxHighlighting (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:761839)
    at Function.simpleDispatch (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:1187631)
    at FindOptions.set (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:733310)
    at BufferSearch.search (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:735841)
    at FindView.search (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:756054)
    at FindView.toggleRegexOption (/private/var/folders/2s/gzz0f5_n20g1pc2mnnbf_1c40000gn/T/AppTranslocation/EBE98D36-9F51-415D-9A68-B7BCE311E4E1/d/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:763139)
```

### Commands

```
  2x -6:57.2.0 core:move-right (input.hidden-input)
     -6:55.1.0 core:save (input.hidden-input)
  2x -6:22.2.0 core:move-up (input.hidden-input)
 13x -6:18.9.0 core:move-left (input.hidden-input)
  4x -6:08.1.0 core:backspace (input.hidden-input)
     -6:02.1.0 core:save (input.hidden-input)
     -5:56.4.0 core:move-left (input.hidden-input)
  3x -5:39.2.0 core:move-right (input.hidden-input)
  3x -5:32.6.0 core:save (input.hidden-input)
     -3:21.8.0 core:move-left (input.hidden-input)
     -1:21.5.0 core:backspace (input.hidden-input)
     -0:59.4.0 core:move-left (input.hidden-input)
     -0:56.4.0 core:backspace (input.hidden-input)
     -0:48.3.0 core:save (input.hidden-input)
     -0:21.1.0 find-and-replace:show (input.hidden-input)
  2x -0:15.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-ide-ui 0.13.0 
atom-ocaml-mliml 0.3.0 
busy-signal 2.0.1 
hasklig 0.4.0 
ide-haskell 2.7.0 
ide-haskell-cabal 2.5.0 
ide-rust 0.22.0-beta.3 
ide-yaml 0.7.1 
intentions 1.1.5 
language-haskell 1.23.0 
linter 3.3.1 
linter-hlint 2.1.0 
linter-rust 1.0.1 
linter-ui-default 3.3.1 
ocaml-merlin 0.14.7 
```
