### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.57.0\res...

### ISSUE THREAD

**Issue by OffalyPops** [atom/atom#22393]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\Pc1\AppData\Local\atom\app-1.57.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:140

Error: The specified module could not be found.
\\?\C:\Users\Pc1\AppData\Local\atom\app-1.57.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:802772)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2893541)
    at get_manager (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2893643)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2893769)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1118316)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1224088)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1222073)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:286551)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
autoclose 0.0.2 
csslint 1.2.0 
emmet 2.4.3 
emoji-syntax 1.7.6 
hyperclick 0.1.5 
language-ejs 0.4.0 
pigments 0.40.6 
```

**Comment by AndreeaGardelean** [comment]
I had the same issue recently and updating the version of the editor has fixed the issue.

**Comment by Aessone** [comment]
Have the same issue, no update available for me.

**Comment by vansh4720** [comment]
i also have the same issue [Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package 2.4.3


### Stack Trace

Failed to activate the emmet package

```
At Cannot find module 'C:\Users\hp\.atom\packages\emmet\node_modules\emmet\lib\emmet.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module 'C:\Users\hp\.atom\packages\emmet\node_modules\emmet\lib\emmet.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:301:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:532:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/emmet/lib/emmet.coffee:5:9)
    at /packages/emmet/lib/emmet.coffee:1:1)
    at /packages/emmet/lib/emmet.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1191588)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3520819)
    at Package.activateNow (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3508803)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3508581
    at Package.measure (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3506159)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3508441
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3508384)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:385497)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:385113
    at Config.transactAsync (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:334641)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:385063)
```

### Commands

```
```

### Non-Core Packages

```
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
emmet 2.4.3 
file-icons 2.1.47 
language-ejs 0.4.0 
linter-csslint 2.0.6 
```

**Comment by icecream17** [comment]
#22467 #22538 #22540 are duplicates

Also here's a better stacktrace. (Using the first stacktrace and not the emmet one)
```
C:\Users\Steven\AppData\Local\atom-beta\app-1.58.0-beta0\resources\app.asar\src\window-event-handler.js
At electron/js2c/asar.js:140

Error: The specified module could not be found.
    at (same file as below, line 4)
    at Object.getCurrentKeyboardLayout (atom/keyboard-layout/lib/keyboard-layout.js:24)
    at e.keystrokeForKeyboardEvent (atom/atom-keymap/src/helpers.js:140)
    at KeymapManager.keystrokeForKeyboardEvent (atom/atom-keymap/src/keymap-manager.js:656)
    at KeymapManager.handleKeyboardEvent (atom/atom-keymap/src/keymap-manager.js:513)
    at WindowEventHandler.handleDocumentKeyEvent (atom/src/window-event-handler.js:153)
```

So here's the problem... the file doesn't exist?????
https://github.com/atom/keyboard-layout/blob/a325ddfc9070592c2eafa29b9bd57f2f739ba561/lib/keyboard-layout.js#L4

**Comment by vansh4720** [comment]
thank you now its resolved
