### ISSUE TITLE
Uncaught Error: ENOENT, node_modules/typescript/lib/lib.d.ts not found in /Applications/Atom.app/...

### ISSUE THREAD

**Issue by retorquere** [atom/atom#22432]
[Enter steps to reproduce:]

1. install zotero-citations 5.4.2

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.3.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, node_modules/typescript/lib/lib.d.ts not found in /Applications/Atom.app/Contents/Resources/app.asar

```
At electron/js2c/asar.js:548

Error: ENOENT, node_modules/typescript/lib/lib.d.ts not found in /Applications/Atom.app/Contents/Resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.fs.readFileSync (electron/js2c/asar.js:548:24)
    at TypeScriptSimple.createService (/app.asar/node_modules/typescript-simple/index.js:79:61)
    at TypeScriptSimple.compile (/app.asar/node_modules/typescript-simple/index.js:63:37)
    at Object.e.compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:582100)
    at Object.compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:577878)
    at compileFileAtPath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150953)
    at Object.value [as .ts] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153351)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at requireModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1191586)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3402829)
    at Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3392117)
    at PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:907975)
    at PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2722529)
    at PackageCard.updateSettingsState (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2712797)
    at PackageCard.updateInterfaceState (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2712620)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2720762
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2722780
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1187631)
    at PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:917432)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:914564
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:909094)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1190909)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1190997
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1189665)
    at Socket.emit (events.js:228:7)
    at Pipe.<anonymous> (net.js:664:12)
```

### Commands

```
     -1:20.8.0 command-palette:toggle (atom-pane.pane.active)
     -1:17.4.0 settings-view:install-packages-and-themes (atom-pane.pane.active)
```

### Non-Core Packages

```
zotero-citations 5.4.2 
```

**Comment by ReedMerrill** [comment]
Thanks for the work to fix this. I'd love to have this feature as I think it would speed up my workflow.

I have updated `zotero-citations` but still get the following error:

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 20.04.2
**Thrown From**: [zotero-citations](ssh://git@github.com/retorquere/zotero-citations) package 5.5.1


### Stack Trace

Failed to activate the zotero-citations package

```
At ENOENT, node_modules/typescript/lib/lib.d.ts not found in /usr/share/atom/resources/app.asar

Error: ENOENT, node_modules/typescript/lib/lib.d.ts not found in /usr/share/atom/resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.fs.readFileSync (electron/js2c/asar.js:548:24)
    at TypeScriptSimple.createService (/app.asar/node_modules/typescript-simple/index.js:79:61)
    at TypeScriptSimple.compile (/app.asar/node_modules/typescript-simple/index.js:63:37)
    at Object.e.compile (/usr/share/atom/resources/app/static/<embedded>:11:582100)
    at Object.compile (/usr/share/atom/resources/app/static/<embedded>:11:577878)
    at compileFileAtPath (/usr/share/atom/resources/app/static/<embedded>:11:150953)
    at Object.value [as .ts] (/usr/share/atom/resources/app/static/<embedded>:11:153351)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:756277)
    at requireModule (/usr/share/atom/resources/app/static/<embedded>:14:1191586)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3400508)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3388492)
    at /usr/share/atom/resources/app/static/<embedded>:14:1879
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1187631)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:351847)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1226991)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1223125)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:286551)
```

### Commands

```
     -3:02.6.0 tabs:open-in-new-window (div.title)
     -0:03.0 zotero-citations:pick (input.hidden-input)
```

### Non-Core Packages

```
contrast-syntax 0.8.1 
count-word 0.2.3 
pandoc-convert 1.1.1 
vim-mode-plus 1.36.5 
zotero-citations 5.5.1 
```
