### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '$ATOM_HOME/packages\atom-beautify\README...

### ISSUE THREAD

**Issue by alexg1989** [atom/atom#22435]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Education
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\agomez4\.atom\packages\atom-beautify\README.md'

```
At internal/fs/utils.js:220

Error: ENOENT: no such file or directory, stat 'C:\Users\agomez4\.atom\packages\atom-beautify\README.md'
    at statSync (fs.js:915:3)
    at Proxy.fs.statSync (electron/js2c/asar.js:278:27)
    at PackageDetailView.renderReadme (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:863302)
    at PackageDetailView.updateInstalledState (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:863069)
    at PackageDetailView.populate (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:861621)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:856961)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:857173)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:863970
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1187631)
    at PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:917432)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:914564
    at r (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:909094)
    at n (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1190911)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1191117)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
     -4:44.1.0 settings-view:open (div.tool-panel.tree-view)
  2x -4:13.5.0 core:paste (input.hidden-input)
 18x -2:52.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
```

**Comment by icecream17** [comment]
The error is saying that your package `atom-beautify` couldn't be found even though it's supposedly installed.

https://discuss.atom.io/t/uninstall-packages/1273/2 - maybe try `apm uninstall atom-beautify`?
