### ISSUE TITLE
Uncaught Error: ENOENT, node_modules/typescript\lib\lib.d.ts not found in ~\AppData\Local\atom\ap...

### ISSUE THREAD

**Issue by Klemet** [atom/atom#22484]
[Enter steps to reproduce:]

1. Install the latest version of Atom (1.57.0)
2. Try to install the package `zotero-citations`
3. The error gets displayed during the installation of the package.

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, node_modules\typescript\lib\lib.d.ts not found in C:\Users\Asus\AppData\Local\atom\app-1.57.0\resources\app.asar

```
At electron/js2c/asar.js:548

Error: ENOENT, node_modules\typescript\lib\lib.d.ts not found in C:\Users\Asus\AppData\Local\atom\app-1.57.0\resources\app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.fs.readFileSync (electron/js2c/asar.js:548:24)
    at TypeScriptSimple.createService (/app.asar/node_modules/typescript-simple/index.js:79:61)
    at TypeScriptSimple.compile (/app.asar/node_modules/typescript-simple/index.js:63:37)
    at Object.e.compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:582100)
    at Object.compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:577878)
    at compileFileAtPath (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:150953)
    at Object.value [as .ts] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153351)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1191588)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3520819)
    at Package.activateConfig (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3510107)
    at PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:907975)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2725665)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2715933)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2715756)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2723898
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2725916
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1187631)
    at PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:917432)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:914564
    at r (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:909094)
    at n (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1190911)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1191117)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
     -2:20.1.0 core:backspace (input.hidden-input)
 12x -1:51 intentions:highlight (input.hidden-input)
     -1:49.9.0 command-palette:toggle (input.hidden-input)
     -1:48.6.0 core:confirm (input.hidden-input)
     -1:48.6.0 zotero-citations:pick (input.hidden-input)
     -1:39 intentions:highlight (input.hidden-input)
     -1:38.6.0 command-palette:toggle (input.hidden-input)
     -1:36.8.0 editor:consolidate-selections (input.hidden-input)
     -1:36.8.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-webbrowser 2.1.4 
autocomplete-bibtex 1.2.10 
busy-signal 2.0.1 
file-icons 2.1.47 
fonts 3.13.0 
inline-markdown-images 1.15.0 
intentions 1.1.5 
language-markdown 0.37.0 
linter 3.3.1 
linter-retextjs 0.31.0 
linter-ui-default 3.3.1 
markdown-preview-enhanced 0.18.10 
markdown-preview-plus 4.10.0 
markdown-table-editor 1.1.3 
markdown-writer 2.11.11 
notes-from-pdf 0.4.2 
pandoc 0.2.2 
pandoc-convert-plus 0.3.0 
pandocia 0.1.0 
tool-bar 1.4.2 
tool-bar-markdown-writer 0.5.1 
zotero-citations 5.5.1 
```

**Comment by icecream17** [comment]
See #22455 & #22432

**Comment by Klemet** [comment]
Thanks, @icecream17 ! And sorry for the duplicate. As a Google search and the Atom error pop up didn't tell me that the issue already existed, I went ahead to post it. I'll close it so that the intention is kept on the original posts.

**Comment by Aarojas3012a** [comment]
Çss colo4
