### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/9k/y_634fg916n_ptcprwy7cbn40000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by Endla-18** [atom/atom#22512]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/9k/y_634fg916n_ptcprwy7cbn40000gn/T/AppTranslocation/006A5917-D66F-419F-9092-4FBDA8892B66/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/fs-admin/build/Release/fs_admin.node, 1): image not found

```
At electron/js2c/asar.js:140

Error: dlopen(/private/var/folders/9k/y_634fg916n_ptcprwy7cbn40000gn/T/AppTranslocation/006A5917-D66F-419F-9092-4FBDA8892B66/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/fs-admin/build/Release/fs_admin.node, 1): image not found
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/private/var/folders/9k/y_634fg916n_ptcprwy7cbn40000gn/T/AppTranslocation/006A5917-D66F-419F-9092-4FBDA8892B66/d/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at get_binding (/private/var/folders/9k/y_634fg916n_ptcprwy7cbn40000gn/T/AppTranslocation/006A5917-D66F-419F-9092-4FBDA8892B66/d/Atom.app/Contents/Resources/app/static/<embedded>:14:18260)
    at Object.unlink (/private/var/folders/9k/y_634fg916n_ptcprwy7cbn40000gn/T/AppTranslocation/006A5917-D66F-419F-9092-4FBDA8892B66/d/Atom.app/Contents/Resources/app/static/<embedded>:14:19227)
    at CommandInstaller.createSymlink (/private/var/folders/9k/y_634fg916n_ptcprwy7cbn40000gn/T/AppTranslocation/006A5917-D66F-419F-9092-4FBDA8892B66/d/Atom.app/Contents/Resources/app/static/<embedded>:11:406059)
    at /private/var/folders/9k/y_634fg916n_ptcprwy7cbn40000gn/T/AppTranslocation/006A5917-D66F-419F-9092-4FBDA8892B66/d/Atom.app/Contents/Resources/app/static/<embedded>:11:405988
    at /private/var/folders/9k/y_634fg916n_ptcprwy7cbn40000gn/T/AppTranslocation/006A5917-D66F-419F-9092-4FBDA8892B66/d/Atom.app/Contents/Resources/app/static/<embedded>:11:406157
    at /private/var/folders/9k/y_634fg916n_ptcprwy7cbn40000gn/T/AppTranslocation/006A5917-D66F-419F-9092-4FBDA8892B66/d/Atom.app/Contents/Resources/app/static/<embedded>:11:272913
    at /private/var/folders/9k/y_634fg916n_ptcprwy7cbn40000gn/T/AppTranslocation/006A5917-D66F-419F-9092-4FBDA8892B66/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1205885
    at FSReqCallback.oncomplete (fs.js:158:21)
```

### Commands

```
     -9:59.8.0 window:copy-active-item-to-pane-below (ul.list-inline.tab-bar.inset-panel)
     -9:15.6.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
     -9:10.7.0 settings-view:core (ul.list-inline.tab-bar.inset-panel)
     -6:31.7.0 command-palette:toggle (div.panels-item)
     -6:25.6.0 window:install-shell-commands (div.panels-item)
     -0:20.8.0 command-palette:toggle (div.panels-item)
     -0:06.9.0 window:install-shell-commands (div.panels-item)
```

### Non-Core Packages

```

```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
