### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '$ATOM_HOME/packages/atom-beautify/README...

### ISSUE THREAD

**Issue by Tobias0624** [atom/atom#22727]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: linux 5.4.99-12983-g8b7876ab9f5e
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/home/tobiadeyeye/.atom/packages/atom-beautify/README.md'

```
At internal/fs/utils.js:220

Error: ENOENT: no such file or directory, stat '/home/tobiadeyeye/.atom/packages/atom-beautify/README.md'
    at statSync (fs.js:915:3)
    at Proxy.fs.statSync (electron/js2c/asar.js:278:27)
    at PackageDetailView.renderReadme (/usr/share/atom/resources/app/static/<embedded>:14:863300)
    at PackageDetailView.updateInstalledState (/usr/share/atom/resources/app/static/<embedded>:14:863067)
    at PackageDetailView.populate (/usr/share/atom/resources/app/static/<embedded>:14:861619)
    at PackageDetailView.completeInitialization (/usr/share/atom/resources/app/static/<embedded>:14:856959)
    at PackageDetailView.loadPackage (/usr/share/atom/resources/app/static/<embedded>:14:857171)
    at /usr/share/atom/resources/app/static/<embedded>:14:863968
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1187631)
    at PackageManager.emitPackageEvent (/usr/share/atom/resources/app/static/<embedded>:11:917432)
    at /usr/share/atom/resources/app/static/<embedded>:11:914564
    at r (/usr/share/atom/resources/app/static/<embedded>:11:909094)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1190909)
    at /usr/share/atom/resources/app/static/<embedded>:14:1191063
    at Socket.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:1189665)
    at Socket.emit (events.js:228:7)
    at Pipe.<anonymous> (net.js:664:12)
```

### Commands

```
 61x -9:53.4.0 core:backspace (input.hidden-input)
     -6:20.4.0 tree-view:show-in-file-manager (div.header.list-item.project-root-header)
     -5:10 tree-view:remove-project-folder (div.header.list-item.project-root-header)
 23x -3:36.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
csslint 1.2.0 
emmet undefined 
linter 3.4.0 
linter-eslint 8.6.6 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by lenora2468B** [comment]
Where is the trash bin

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
