### ISSUE TITLE
Uncaught Error: Module did not self-register: '/usr/share/atom/resources/app.asar.unpacked/node_m...

### ISSUE THREAD

**Issue by Fefiente** [atom/atom#22753]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Pop!_OS 21.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register: '/usr/share/atom/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'.

```
At electron/js2c/asar.js:140

Error: Module did not self-register: '/usr/share/atom/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'.
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:756277)
    at get_KeyboardLayoutManager (/usr/share/atom/resources/app/static/<embedded>:14:2890405)
    at get_manager (/usr/share/atom/resources/app/static/<embedded>:14:2890507)
    at Object.getCurrentKeyboardLayout (/usr/share/atom/resources/app/static/<embedded>:14:2890633)
    at e.keystrokeForKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:14:1118314)
    at KeymapManager.keystrokeForKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1224088)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1222073)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:286551)
```

### Commands

```
     -4:32.1.0 github:toggle-git-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:35.9.0 application:open-folder (div.package-detail)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
