### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '$ATOM_HOME/packages\emmet\README.md'

### ISSUE THREAD

**Issue by kenansafadi** [atom/atom#22758]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: ??Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\kenan\.atom\packages\emmet\README.md'

```
At internal/fs/utils.js:220

Error: ENOENT: no such file or directory, stat 'C:\Users\kenan\.atom\packages\emmet\README.md'
    at statSync (fs.js:915:3)
    at Proxy.fs.statSync (electron/js2c/asar.js:278:27)
    at PackageDetailView.renderReadme (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:863302)
    at PackageDetailView.updateInstalledState (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:863069)
    at PackageDetailView.populate (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:861621)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:856961)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:857173)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:863970
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1187631)
    at PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:917432)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:914564
    at r (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:909094)
    at n (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1190911)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1191117)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
  2x -3:08.9.0 tree-view:add-file (div.header.list-item.project-root-header)
     -2:59.9.0 core:confirm (input.hidden-input)
     -2:56.6.0 tree-view:add-file (div.header.list-item.project-root-header)
     -2:53 core:confirm (input.hidden-input)
     -2:49.7.0 core:paste (input.hidden-input)
 16x -2:42.5.0 core:move-down (input.hidden-input)
 65x -2:41.4.0 core:move-up (input.hidden-input)
 31x -2:37.2.0 core:move-down (input.hidden-input)
     -2:32.9.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:43.8.0 core:confirm (input.hidden-input)
     -0:36.4.0 core:move-down (div.panels-item)
  2x -0:35.9.0 core:move-up (div.panels-item)
  2x -0:23.7.0 core:move-down (div.package-detail)
```

### Non-Core Packages

```
emmet 2.4.3 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
