### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/cp/8zcr3l6155n7ctd2dy8xl1780000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by dgroves888** [atom/atom#22809]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.5.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/cp/8zcr3l6155n7ctd2dy8xl1780000gn/T/AppTranslocation/F215D1A0-4986-4A03-BF80-31A4F94B61A3/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): no suitable image found.  Did find:
	/private/var/folders/cp/8zcr3l6155n7ctd2dy8xl1780000gn/T/AppTranslocation/F215D1A0-4986-4A03-BF80-31A4F94B61A3/d/Atom.app/Contents/Resources: not a file

```
At electron/js2c/asar.js:140

Error: dlopen(/private/var/folders/cp/8zcr3l6155n7ctd2dy8xl1780000gn/T/AppTranslocation/F215D1A0-4986-4A03-BF80-31A4F94B61A3/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): no suitable image found.  Did find:
	/private/var/folders/cp/8zcr3l6155n7ctd2dy8xl1780000gn/T/AppTranslocation/F215D1A0-4986-4A03-BF80-31A4F94B61A3/d/Atom.app/Contents/Resources: not a file
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/private/var/folders/cp/8zcr3l6155n7ctd2dy8xl1780000gn/T/AppTranslocation/F215D1A0-4986-4A03-BF80-31A4F94B61A3/d/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at get_KeyboardLayoutManager (/private/var/folders/cp/8zcr3l6155n7ctd2dy8xl1780000gn/T/AppTranslocation/F215D1A0-4986-4A03-BF80-31A4F94B61A3/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2894476)
    at get_manager (/private/var/folders/cp/8zcr3l6155n7ctd2dy8xl1780000gn/T/AppTranslocation/F215D1A0-4986-4A03-BF80-31A4F94B61A3/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2894578)
    at Object.getCurrentKeyboardLayout (/private/var/folders/cp/8zcr3l6155n7ctd2dy8xl1780000gn/T/AppTranslocation/F215D1A0-4986-4A03-BF80-31A4F94B61A3/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2894704)
    at e.keystrokeForKeyboardEvent (/private/var/folders/cp/8zcr3l6155n7ctd2dy8xl1780000gn/T/AppTranslocation/F215D1A0-4986-4A03-BF80-31A4F94B61A3/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1119649)
    at KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/cp/8zcr3l6155n7ctd2dy8xl1780000gn/T/AppTranslocation/F215D1A0-4986-4A03-BF80-31A4F94B61A3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1224825)
    at KeymapManager.handleKeyboardEvent (/private/var/folders/cp/8zcr3l6155n7ctd2dy8xl1780000gn/T/AppTranslocation/F215D1A0-4986-4A03-BF80-31A4F94B61A3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1222810)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/cp/8zcr3l6155n7ctd2dy8xl1780000gn/T/AppTranslocation/F215D1A0-4986-4A03-BF80-31A4F94B61A3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:286651)
```

### Commands

```
     -9:03.0 julia-client:start-julia (atom-pane.pane.active)
     -6:59.2.0 core:confirm (input.hidden-input)
  2x -6:54.1.0 core:backspace (input.hidden-input)
  3x -6:47.7.0 core:confirm (input.hidden-input)
  2x -3:24 core:backspace (input.hidden-input)
  7x -3:19.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-julia-run 1.0.5 
ink 0.12.6 
julia-client 0.12.6 
language-julia 0.21.2 
```

**Comment by dgroves888** [comment]
I'm using an M1 Macbook Pro and am unable to install the Julia package in Atom.

**Comment by darangi** [comment]
@dgroves888 is this happening after you attempt to install Julia package? or After you have installed the package?

**Comment by dgroves888** [comment]
The problem has been solved. Thanks for your input!
