### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom....

### ISSUE THREAD

**Issue by KristinaYahupova** [atom/atom#22831]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Unknown macOS version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At electron/js2c/asar.js:140

Error: dlopen(/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at get_KeyboardLayoutManager (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:14:2894476)
    at get_manager (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:14:2894578)
    at Object.getCurrentKeyboardLayout (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:14:2894704)
    at e.keystrokeForKeyboardEvent (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:14:1119649)
    at KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:11:1224825)
    at KeymapManager.handleKeyboardEvent (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:11:1222810)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:11:286651)
```

### Commands

```
     -3:03.6.0 core:undo (button.github-Project-avatarBtn)
```

### Non-Core Packages

```
atom-i18n 0.26.0 
```

**Comment by qul-d** [comment]
> [Enter steps to reproduce:]
> 
>     1. ...
> 
>     2. ...
> 
> 
> **Atom**: 1.58.0 x64
> **Electron**: 9.4.4
> **OS**: Unknown macOS version
> **Thrown From**: Atom Core
> ### Stack Trace
> 
> Uncaught Error: dlopen(/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
> 
> ```
> At electron/js2c/asar.js:140
> 
> Error: dlopen(/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
>     at process.func [as dlopen] (electron/js2c/asar.js:140:31)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
>     at Object.func [as .node] (electron/js2c/asar.js:149:18)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
>     at Module._load (internal/modules/cjs/loader.js:727:14)
>     at Function.Module._load (electron/js2c/asar.js:769:28)
>     at Module.require (/app.asar/static/index.js:72:46)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at customRequire (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
>     at get_KeyboardLayoutManager (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:14:2894476)
>     at get_manager (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:14:2894578)
>     at Object.getCurrentKeyboardLayout (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:14:2894704)
>     at e.keystrokeForKeyboardEvent (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:14:1119649)
>     at KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:11:1224825)
>     at KeymapManager.handleKeyboardEvent (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:11:1222810)
>     at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/tr/519q8n9s1llc3_vydqwtcs140000gn/T/wzQL.wPuMP0/Atom.app/Contents/Resources/app/static/<embedded>:11:286651)
> ```
> 
> ### Commands
> 
> ```
>      -3:03.6.0 core:undo (button.github-Project-avatarBtn)
> ```
> 
> ### Non-Core Packages
> 
> ```
> atom-i18n 0.26.0 
> ```
