### ISSUE TITLE
The App Just Opening And Then show the app crashed!

### ISSUE THREAD

**Issue by TuNiDeVe** [atom/atom#22872]
I Just Opening The Atom Editor And It Crashed After 30 sec.
Plz Fix!

From: TuNiDeVe

**Comment by phoebe-leong** [comment]
uhh

**Comment by phoebe-leong** [comment]
what operating system r u using?

**Comment by phoebe-leong** [comment]
and...is this reproducable?
any possible reasons as to why this happens?

**Comment by simonspa** [comment]
Same here, and I'm not sure how to produce some diagnostics for you to figure out what's going on. I do start `atom` from the terminal but since it detaches, there is no stack trace or similar produced.

**Comment by TuNiDeVe** [comment]
I using windows 10

**Comment by simonspa** [comment]
From `~/.atom/nohup.cson`

```
--2021-09-03 19:11:39--  https://atom.io/crash_reports
Resolving atom.io (atom.io)... 52.202.168.65, 54.237.133.81, 18.205.222.128, ...
Connecting to atom.io (atom.io)|52.202.168.65|:443... connected.
HTTP request sent, awaiting response... 204 No Content
2021-09-03 19:11:40 (0.00 B/s) - ‘/dev/fd/4’ saved [0]


Unexpected crash report id length
Failed to get crash dump id.
Report Id: 
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: <embedded>:11:652489
Remote event names: blur, focus
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: <embedded>:14:705427
Remote event names: crashed, destroyed
Cannot read property 'send' of null
TypeError: Cannot read property 'send' of null
    at /usr/share/atom/resources/app.asar/src/main-process/atom-window.js:295:38
    at new Promise (<anonymous>:null:null)
    at AtomWindow.prepareToUnload (/usr/share/atom/resources/app.asar/src/main-process/atom-window.js:281:39)
    at /usr/share/atom/resources/app.asar/src/main-process/atom-application.js:731:45
    at Array.map (<anonymous>:null:null)
    at App.<anonymous> (/usr/share/atom/resources/app.asar/src/main-process/atom-application.js:729:61)
    at App.emit (events.js:223:5)
    at App.<anonymous> (/usr/share/atom/resources/app.asar/src/main-process/atom-application.js:770:15)
    at App.emit (events.js:228:7)
    at WebContents.<anonymous> (/usr/share/atom/resources/app.asar/src/main-process/atom-window.js:258:30)

```

**Comment by TuNiDeVe** [comment]
Actually I Didn’t see any friend or anyone else that having this strange
problem.
Also I tried to fix it by myself, It not worked.

I can open atom just for 10/15/20 seconds,
And then show me an error massage if you want, i will send you the error
massage in picture file.

Anyway, the error massage tells me that the app crashed, and also the error
massage offers me to report it to GitHub.com/atom/atom.

I think it’s because the version of atom i installed which the newest
version, also i have the most updated version of windows 10.

I provided about the service.

From: TuNiDeve

**Comment by TuNiDeVe** [comment]
> what operating system r u using?

I using windows 10 newest and most updated version

**Comment by TuNiDeVe** [comment]
> and...is this reproducable?
> any possible reasons as to why this happens?

No reason, Just installed it and it suddenly crashed, i tried anything plz help

**Comment by TuNiDeVe** [comment]
And if there is an atom discord server plz sent me the link because I want to be updated

**Comment by phoebe-leong** [comment]
wellll try restarting your computer

**Comment by phoebe-leong** [comment]
i dont think there is a discord server sadly, we only have github

**Comment by TuNiDeVe** [comment]
> wellll try restarting your computer

Tried it many times…

**Comment by phoebe-leong** [comment]
oh :(

**Comment by phoebe-leong** [comment]
> From `~/.atom/nohup.cson`
> 
> ```
> --2021-09-03 19:11:39--  https://atom.io/crash_reports
> Resolving atom.io (atom.io)... 52.202.168.65, 54.237.133.81, 18.205.222.128, ...
> Connecting to atom.io (atom.io)|52.202.168.65|:443... connected.
> HTTP request sent, awaiting response... 204 No Content
> 2021-09-03 19:11:40 (0.00 B/s) - ‘/dev/fd/4’ saved [0]
> 
> 
> Unexpected crash report id length
> Failed to get crash dump id.
> Report Id: 
> Attempting to call a function in a renderer window that has been closed or released.
> Function provided here: <embedded>:11:652489
> Remote event names: blur, focus
> Attempting to call a function in a renderer window that has been closed or released.
> Function provided here: <embedded>:14:705427
> Remote event names: crashed, destroyed
> Cannot read property 'send' of null
> TypeError: Cannot read property 'send' of null
>     at /usr/share/atom/resources/app.asar/src/main-process/atom-window.js:295:38
>     at new Promise (<anonymous>:null:null)
>     at AtomWindow.prepareToUnload (/usr/share/atom/resources/app.asar/src/main-process/atom-window.js:281:39)
>     at /usr/share/atom/resources/app.asar/src/main-process/atom-application.js:731:45
>     at Array.map (<anonymous>:null:null)
>     at App.<anonymous> (/usr/share/atom/resources/app.asar/src/main-process/atom-application.js:729:61)
>     at App.emit (events.js:223:5)
>     at App.<anonymous> (/usr/share/atom/resources/app.asar/src/main-process/atom-application.js:770:15)
>     at App.emit (events.js:228:7)
>     at WebContents.<anonymous> (/usr/share/atom/resources/app.asar/src/main-process/atom-window.js:258:30)
> ```

this seems like a syntax error, try viewing the code if u can read it

**Comment by phoebe-leong** [comment]
then maybe ull be able to fix it, or at least suggest a fix to it

**Comment by TuNiDeVe** [comment]
How do I do that?

בתאריך שבת, 4 בספט׳ 2021 ב-11:15 מאת ph3b3 ***@***.***>:

**Comment by icecream17** [comment]
That's not a syntax error, it's a TypeError.

The error above says there's `null.send` here:
https://github.com/atom/atom/blob/master/src/main-process/atom-window.js#295

**Comment by simonspa** [comment]
For me it appeared only for one project / in one folder. Deleting the file `.tags` in that folder solved it for me.

**Comment by Pysis868** [comment]
I have also seen some failed to resolve promise error when different processes of an Electron-based application could not operate successfully together, such as due to a GPU or other process crash for another application I was using with the same framework.  Could see if this is one of your issues: https://github.com/atom/atom/issues/22872
