### ISSUE TITLE
Missing atom-1.57.0-full.nupkg when building 1.58.0 Windows installer

### ISSUE THREAD

**Issue by Pepperonieyed** [atom/atom#22907]
I'm sure that this must just be down to my own ignorance but I've been unable to find a solution anywhere. Whenever I try to build Atom on Windows everything goes well until it starts creating the Windows installer.

After running:
`git clone https://github.com/atom/atom`
`git checkout 1.58-releases`
and then
`script\build --create-windows-installer --compress-artifacts`
I get the following output:
```
Node:   v14.17.5
Npm:    v6.14.14
Python: v3.9.6
Installing script dependencies
Installing apm
apm  2.6.2
atom 1.58.0
git 2.33.0.windows.2
visual studio 2019
Installing modules done
Wrote Dependencies Fingerprint: C:\AtomBuilds\1.58.0\build\atom\node_modules\.dependencies-fingerprint 636277b81182c149261d00cd65823d2e717d930f
Copying assets to C:\AtomBuilds\1.58.0\build\atom\out\app
Transpiling packages with custom transpiler configurations in C:\AtomBuilds\1.58.0\build\atom\out\app
 transpiling for package github
Installing modules done
Transpiling Babel paths in C:\AtomBuilds\1.58.0\build\atom\out\app
Transpiling CoffeeScript paths in C:\AtomBuilds\1.58.0\build\atom\out\app
Transpiling CSON paths in C:\AtomBuilds\1.58.0\build\atom\out\app
Transpiling PEG.js paths in C:\AtomBuilds\1.58.0\build\atom\out\app
Generating module cache for C:\AtomBuilds\1.58.0\build\atom\out\app
Generating pre-built less cache in C:\AtomBuilds\1.58.0\build\atom\out\app\less-compile-cache
Generating metadata for C:\AtomBuilds\1.58.0\build\atom\out\app\package.json
Generating API docs at C:\AtomBuilds\1.58.0\build\atom\docs\output\atom-api.json
Skipping symbol dumping because minidump is not supported on Windows
Running electron-packager on C:\AtomBuilds\1.58.0\build\atom\out\app with app name "atom"
Packaging app for platform win32 ia32 using electron v9.4.4
Copying non-ASAR resources to C:\AtomBuilds\1.58.0\build\atom\out\Atom\resources
Writing LICENSE.md to C:\AtomBuilds\1.58.0\build\atom\out\Atom\resources
Application bundle created at C:\AtomBuilds\1.58.0\build\atom\out\Atom
Generating snapshot script at "C:\AtomBuilds\1.58.0\build\atom\out\startup.js" (1467)##[warning] The reference to the module is replaced with the lazy function, but it is assigned to "module" or "exports". In some cases the bundle might not work, which you should fix manually:
 C:\AtomBuilds\1.58.0\build\atom\out\app\node_modules\spell-check\node_modules\debug\src\node.js

Generating snapshot script at "C:\AtomBuilds\1.58.0\build\atom\out\startup.js" (2294)##[warning] The reference to the module is replaced with the lazy function, but it is assigned to "module" or "exports". In some cases the bundle might not work, which you should fix manually:
 C:\AtomBuilds\1.58.0\build\atom\out\app\node_modules\less\lib\less-node\fs.js

Generating snapshot script at "C:\AtomBuilds\1.58.0\build\atom\out\startup.js" (5202)
Minifying startup script
Verifying if snapshot can be executed via `mksnapshot`
Generating startup blob with mksnapshot
Moving generated startup blob into "C:\AtomBuilds\1.58.0\build\atom\out\Atom\v8_context_snapshot.bin"
Moving generated startup blob into "C:\AtomBuilds\1.58.0\build\atom\out\Atom\snapshot_blob.bin"
Skipping code-signing. Specify the --code-sign option to perform code-signing
Creating Windows Installer for C:\AtomBuilds\1.58.0\build\atom\out\Atom
Error: Failed with exit code: 4294967295
Output:
System.IO.FileNotFoundException: The base package release does not exist
File name: 'C:\AtomBuilds\1.58.0\build\atom\out\atom-1.57.0-full.nupkg'
   at Squirrel.DeltaPackageBuilder.CreateDeltaPackage(ReleasePackage basePackage, ReleasePackage newPackage, String outputFile)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, Boolean packageAs64Bit, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)

  at ChildProcess.<anonymous> (C:\AtomBuilds\1.58.0\build\atom\script\node_modules\@atom\electron-winstaller\lib\spawn-promise.js:62:16)
  at ChildProcess.emit (events.js:400:28)
  at maybeClose (internal/child_process.js:1055:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

It would seem that it's looking for atom-1.57.0-full.nupkg but I have no idea why. I've tried this on a few different clean installs of Windows 10 and get the same problem. It's also the case when building 1.54.0 as it looks for atom-1.53.0-full.nupkg.

**Comment by lildaddy423** [comment]
https://ol52o3.mimo.run/index.htmlOn Aug 27, 2021 8:32 PM, Pepperonieyed ***@***.***> wrote:
I'm sure that this must just be down to my own ignorance but I've been unable to find a solution anywhere. Whenever I try to build Atom on Windows everything goes well until it starts creating the Windows installer.
After running:
git clone https://github.com/atom/atom
git checkout 1.58-releases
and then
script\build --create-windows-installer --compress-artifacts
I get the following output:
Node:   v14.17.5
Npm:    v6.14.14
Python: v3.9.6
Installing script dependencies
Installing apm
apm  2.6.2
atom 1.58.0
git 2.33.0.windows.2
visual studio 2019
Installing modules done
Wrote Dependencies Fingerprint: C:\AtomBuilds\1.58.0\build\atom\node_modules\.dependencies-fingerprint 636277b81182c149261d00cd65823d2e717d930f
Copying assets to C:\AtomBuilds\1.58.0\build\atom\out\app
Transpiling packages with custom transpiler configurations in C:\AtomBuilds\1.58.0\build\atom\out\app
 transpiling for package github
Installing modules done
Transpiling Babel paths in C:\AtomBuilds\1.58.0\build\atom\out\app
Transpiling CoffeeScript paths in C:\AtomBuilds\1.58.0\build\atom\out\app
Transpiling CSON paths in C:\AtomBuilds\1.58.0\build\atom\out\app
Transpiling PEG.js paths in C:\AtomBuilds\1.58.0\build\atom\out\app
Generating module cache for C:\AtomBuilds\1.58.0\build\atom\out\app
Generating pre-built less cache in C:\AtomBuilds\1.58.0\build\atom\out\app\less-compile-cache
Generating metadata for C:\AtomBuilds\1.58.0\build\atom\out\app\package.json
Generating API docs at C:\AtomBuilds\1.58.0\build\atom\docs\output\atom-api.json
Skipping symbol dumping because minidump is not supported on Windows
Running electron-packager on C:\AtomBuilds\1.58.0\build\atom\out\app with app name "atom"
Packaging app for platform win32 ia32 using electron v9.4.4
Copying non-ASAR resources to C:\AtomBuilds\1.58.0\build\atom\out\Atom\resources
Writing LICENSE.md to C:\AtomBuilds\1.58.0\build\atom\out\Atom\resources
Application bundle created at C:\AtomBuilds\1.58.0\build\atom\out\Atom
Generating snapshot script at "C:\AtomBuilds\1.58.0\build\atom\out\startup.js" (1467)##[warning] The reference to the module is replaced with the lazy function, but it is assigned to "module" or "exports". In some cases the bundle might not work, which you should fix manually:
 C:\AtomBuilds\1.58.0\build\atom\out\app\node_modules\spell-check\node_modules\debug\src\node.js

Generating snapshot script at "C:\AtomBuilds\1.58.0\build\atom\out\startup.js" (2294)##[warning] The reference to the module is replaced with the lazy function, but it is assigned to "module" or "exports". In some cases the bundle might not work, which you should fix manually:
 C:\AtomBuilds\1.58.0\build\atom\out\app\node_modules\less\lib\less-node\fs.js

Generating snapshot script at "C:\AtomBuilds\1.58.0\build\atom\out\startup.js" (5202)
Minifying startup script
Verifying if snapshot can be executed via `mksnapshot`
Generating startup blob with mksnapshot
Moving generated startup blob into "C:\AtomBuilds\1.58.0\build\atom\out\Atom\v8_context_snapshot.bin"
Moving generated startup blob into "C:\AtomBuilds\1.58.0\build\atom\out\Atom\snapshot_blob.bin"
Skipping code-signing. Specify the --code-sign option to perform code-signing
Creating Windows Installer for C:\AtomBuilds\1.58.0\build\atom\out\Atom
Error: Failed with exit code: 4294967295
Output:
System.IO.FileNotFoundException: The base package release does not exist
File name: 'C:\AtomBuilds\1.58.0\build\atom\out\atom-1.57.0-full.nupkg'
   at Squirrel.DeltaPackageBuilder.CreateDeltaPackage(ReleasePackage basePackage, ReleasePackage newPackage, String outputFile)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, Boolean packageAs64Bit, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)

  at ChildProcess.<anonymous> ***@***.***\electron-winstaller\lib\spawn-promise.js:62:16)
  at ChildProcess.emit (events.js:400:28)
  at maybeClose (internal/child_process.js:1055:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

It would seem that it's looking for atom-1.57.0-full.nupkg but I have no idea why. I've tried this on a few different clean installs of Windows 10 and get the same problem. It's also the case when building 1.54.0 as it looks for atom-1.53.0-full.nupkg.

**Comment by Pepperonieyed** [comment]
After some further digging it would seem that building from the master branch works perfectly so I'm assuming that either there's an issue with the release branches or I'm trying to build from them incorrectly. I suspect it's more likely the latter.

**Comment by DeeDeeG** [comment]
I believe building a stable/beta version that already exists at `atom.io`/ already published on GitHub will lead to errors.

The dev builds (`master` branch) are less finnicky, as they don't try to integrate with the update system as tightly (they don't try to auto-update either when you launch them). You should be able to build installers for the release branches if you inrement the version number in`package.json`, if I recall correctly.

**Comment by Pepperonieyed** [comment]
Yes, it would appear that changing the version number to anything that doesn't exist allows it to build properly. Thanks for your help.
