### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '$ATOM_HOME/packages\material-ui-snippets...

### ISSUE THREAD

**Issue by TTforTT** [atom/atom#22946]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\theot\.atom\packages\material-ui-snippets\README.md'

```
At internal/fs/utils.js:220

Error: ENOENT: no such file or directory, stat 'C:\Users\theot\.atom\packages\material-ui-snippets\README.md'
    at statSync (fs.js:915:3)
    at Proxy.fs.statSync (electron/js2c/asar.js:278:27)
    at PackageDetailView.renderReadme (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:864637)
    at PackageDetailView.updateInstalledState (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:864404)
    at PackageDetailView.populate (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:862956)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:858296)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:858508)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:865305
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1188366)
    at PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:917977)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:915109
    at r (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:909639)
    at n (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1194945)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1195151)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
  4x -9:38.6.0 core:undo (input.hidden-input)
     -9:21.9.0 core:backspace (input.hidden-input)
     -9:17.6.0 core:save (input.hidden-input)
  2x -9:04.6.0 editor:newline (input.hidden-input)
  2x -8:55.1.0 core:save (input.hidden-input)
  3x -8:48.2.0 core:undo (input.hidden-input)
     -7:24.7.0 core:backspace (input.hidden-input)
     -7:22.7.0 core:undo (input.hidden-input)
  2x -7:20.6.0 core:backspace (input.hidden-input)
     -7:17.2.0 core:undo (input.hidden-input)
     -2:18 core:backspace (input.hidden-input)
     -2:11 core:move-left (input.hidden-input)
  3x -2:03.7.0 core:backspace (input.hidden-input)
  5x -1:58.4.0 core:move-left (input.hidden-input)
     -1:52.8.0 core:save (input.hidden-input)
     -0:40.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
batman-syntax 1.1.0 
ksx-matrix 1.4.1 
material-ui-snippets 1.0.3 
```

**Comment by kazaksaeed** [comment]
> _No description provided._
0xa9125520BeD7842465800d6B37cCC6d38B1fAf21
