### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/ Tutoring.md'

### ISSUE THREAD

**Issue by joegarciaatcare** [atom/atom#22962]
[Enter steps to reproduce:]

1. Create a file named `Teacher, Tutoring.md`
2. Drag and drop the file into a child directory

I'm guessing you're splitting on commas when a comma on a filename is valid

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: macOS 11.5.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/ Tutoring.md'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat '/ Tutoring.md'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (/private/var/folders/48/r6d27f4n1rq1bb4kl778r0p8j30sm8/T/AppTranslocation/8DC719B4-5278-4C12-A8D4-0B3EA9F2434E/d/Atom.app/Contents/Resources/app/static/<embedded>:14:969249)
    at TreeView.onDrop (/private/var/folders/48/r6d27f4n1rq1bb4kl778r0p8j30sm8/T/AppTranslocation/8DC719B4-5278-4C12-A8D4-0B3EA9F2434E/d/Atom.app/Contents/Resources/app/static/<embedded>:14:976178)
    at HTMLDivElement.<anonymous> (/private/var/folders/48/r6d27f4n1rq1bb4kl778r0p8j30sm8/T/AppTranslocation/8DC719B4-5278-4C12-A8D4-0B3EA9F2434E/d/Atom.app/Contents/Resources/app/static/<embedded>:14:949809)
```

### Commands

```
     -4:10 core:save (input.hidden-input)
     -4:09.7.0 pane:show-previous-item (input.hidden-input)
     -4:09.3.0 core:save (input.hidden-input)
     -4:08.9.0 pane:show-previous-item (input.hidden-input)
     -4:07.8.0 core:move-to-top (input.hidden-input)
     -4:07.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -4:07.6.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -4:07.1.0 pane:show-next-item (input.hidden-input)
     -4:06.1.0 application:new-file (input.hidden-input)
  2x -4:04.9.0 core:save (input.hidden-input)
  2x -3:22.4.0 editor:newline (input.hidden-input)
     -3:22 core:save (input.hidden-input)
     -0:32.3.0 core:close (input.hidden-input)
     -0:24.1.0 tree-view:show-in-file-manager (span.name.icon.icon-file-text)
```

### Non-Core Packages

```

```

**Comment by N1KN1M** [comment]
Works fine for me on Windows 10 atom 1.58
