### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/v_/2sg4330s3v3_yfvymns8wglr0000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by aheninger07** [atom/atom#23020]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Unknown macOS version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/v_/2sg4330s3v3_yfvymns8wglr0000gn/T/AppTranslocation/3BBDF90F-2F63-4FCB-B97B-4E4EA052736E/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At electron/js2c/asar.js:140

Error: dlopen(/private/var/folders/v_/2sg4330s3v3_yfvymns8wglr0000gn/T/AppTranslocation/3BBDF90F-2F63-4FCB-B97B-4E4EA052736E/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/private/var/folders/v_/2sg4330s3v3_yfvymns8wglr0000gn/T/AppTranslocation/3BBDF90F-2F63-4FCB-B97B-4E4EA052736E/d/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at get_KeyboardLayoutManager (/private/var/folders/v_/2sg4330s3v3_yfvymns8wglr0000gn/T/AppTranslocation/3BBDF90F-2F63-4FCB-B97B-4E4EA052736E/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2894476)
    at get_manager (/private/var/folders/v_/2sg4330s3v3_yfvymns8wglr0000gn/T/AppTranslocation/3BBDF90F-2F63-4FCB-B97B-4E4EA052736E/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2894578)
    at Object.getCurrentKeyboardLayout (/private/var/folders/v_/2sg4330s3v3_yfvymns8wglr0000gn/T/AppTranslocation/3BBDF90F-2F63-4FCB-B97B-4E4EA052736E/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2894704)
    at e.keystrokeForKeyboardEvent (/private/var/folders/v_/2sg4330s3v3_yfvymns8wglr0000gn/T/AppTranslocation/3BBDF90F-2F63-4FCB-B97B-4E4EA052736E/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1119649)
    at KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/v_/2sg4330s3v3_yfvymns8wglr0000gn/T/AppTranslocation/3BBDF90F-2F63-4FCB-B97B-4E4EA052736E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1224825)
    at KeymapManager.handleKeyboardEvent (/private/var/folders/v_/2sg4330s3v3_yfvymns8wglr0000gn/T/AppTranslocation/3BBDF90F-2F63-4FCB-B97B-4E4EA052736E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1222810)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/v_/2sg4330s3v3_yfvymns8wglr0000gn/T/AppTranslocation/3BBDF90F-2F63-4FCB-B97B-4E4EA052736E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:286651)
```

### Commands

```
     -5:27.2.0 core:paste (input.hidden-input)
     -5:23.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
