### ISSUE TITLE
Uncaught Error: dlopen(~/Library/Mobile Documents/com~apple~CloudDocs/CIS 111/Atom.app/Contents/R...

### ISSUE THREAD

**Issue by PoRadchenko** [atom/atom#23055]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.5.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/Users/polinaradchenko/Library/Mobile Documents/com~apple~CloudDocs/CIS 111/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At electron/js2c/asar.js:140

Error: dlopen(/Users/polinaradchenko/Library/Mobile Documents/com~apple~CloudDocs/CIS 111/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/Users/polinaradchenko/Library/Mobile Documents/com~apple~CloudDocs/CIS 111/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at get_KeyboardLayoutManager (/Users/polinaradchenko/Library/Mobile Documents/com~apple~CloudDocs/CIS 111/Atom.app/Contents/Resources/app/static/<embedded>:14:2894476)
    at get_manager (/Users/polinaradchenko/Library/Mobile Documents/com~apple~CloudDocs/CIS 111/Atom.app/Contents/Resources/app/static/<embedded>:14:2894578)
    at Object.getCurrentKeyboardLayout (/Users/polinaradchenko/Library/Mobile Documents/com~apple~CloudDocs/CIS 111/Atom.app/Contents/Resources/app/static/<embedded>:14:2894704)
    at e.keystrokeForKeyboardEvent (/Users/polinaradchenko/Library/Mobile Documents/com~apple~CloudDocs/CIS 111/Atom.app/Contents/Resources/app/static/<embedded>:14:1119649)
    at KeymapManager.keystrokeForKeyboardEvent (/Users/polinaradchenko/Library/Mobile Documents/com~apple~CloudDocs/CIS 111/Atom.app/Contents/Resources/app/static/<embedded>:11:1224825)
    at KeymapManager.handleKeyboardEvent (/Users/polinaradchenko/Library/Mobile Documents/com~apple~CloudDocs/CIS 111/Atom.app/Contents/Resources/app/static/<embedded>:11:1222810)
    at WindowEventHandler.handleDocumentKeyEvent (/Users/polinaradchenko/Library/Mobile Documents/com~apple~CloudDocs/CIS 111/Atom.app/Contents/Resources/app/static/<embedded>:11:286651)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
emmet 2.4.3 
intentions 2.1.1 
isotope-light-ui 2.3.0 
linter 3.4.0 
linter-htmlhint 1.6.3 
linter-jshint 3.1.19 
linter-ui-default 3.4.1 
night-light 1.0.5 
open-in-browser 0.5.2 
open-recent 5.0.0 
prettier-atom 0.60.1 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
