### ISSUE TITLE
no such file or directory v8_context_snapshot.bin

### ISSUE THREAD

**Issue by ZhangKejun** [atom/atom#23253]
Error message at the end

MACdeMacBook-Pro atom % script/build
Node:	v10.16.0
Npm:	v6.14.8
Python:	v2.7.16
Installing script dependencies
Installing apm
apm  2.6.2
npm  6.14.13
node 10.20.1 x64
atom 1.61.0-dev
python 2.7.16
git 2.24.3
Installing modules ✓
Wrote Dependencies Fingerprint: /Users/a01388087/github/atom/node_modules/.dependencies-fingerprint 576d2407b2f80ed82e5d81f228f58ab3c523c5e0
Copying assets to /Users/a01388087/github/atom/out/app
Transpiling packages with custom transpiler configurations in /Users/a01388087/github/atom/out/app
 transpiling for package github
Installing modules ✓
Transpiling Babel paths in /Users/a01388087/github/atom/out/app
Transpiling CoffeeScript paths in /Users/a01388087/github/atom/out/app
Transpiling CSON paths in /Users/a01388087/github/atom/out/app
Transpiling PEG.js paths in /Users/a01388087/github/atom/out/app
Generating module cache for /Users/a01388087/github/atom/out/app
Generating pre-built less cache in /Users/a01388087/github/atom/out/app/less-compile-cache
Generating metadata for /Users/a01388087/github/atom/out/app/package.json
Generating API docs at /Users/a01388087/github/atom/docs/output/atom-api.json
Dumping symbols in /Users/a01388087/github/atom/out/symbols
(node:2155) ExperimentalWarning: The fs.promises API is experimental
Running electron-packager on /Users/a01388087/github/atom/out/app with app name "Atom Dev"
Packaging app for platform darwin x64 using electron v9.4.4
Setting Atom Helper Version for /Users/a01388087/github/atom/out/Atom Dev.app/Contents/Frameworks/Atom Helper.app/Contents/Info.plist
Copying non-ASAR resources to /Users/a01388087/github/atom/out/Atom Dev.app/Contents/Resources
Writing LICENSE.md to /Users/a01388087/github/atom/out/Atom Dev.app/Contents/Resources
Application bundle created at /Users/a01388087/github/atom/out/Atom Dev.app
Generating snapshot script at "/Users/a01388087/github/atom/out/startup.js" (177)
Minifying startup script
Verifying if snapshot can be executed via `mksnapshot`
Generating startup blob with mksnapshot
Moving generated startup blob into "/Users/a01388087/github/atom/out/Atom Dev.app/Contents/Frameworks/Electron Framework.framework/Resources/v8_context_snapshot.bin"
Error: ENOENT: no such file or directory, rename '/Users/a01388087/github/atom/out/v8_context_snapshot.bin' -> '/Users/a01388087/github/atom/out/Atom Dev.app/Contents/Frameworks/Electron Framework.framework/Resources/v8_context_snapshot.bin'
  at Object.renameSync (fs.js:598:3)
  at electronLink.then (/Users/a01388087/github/atom/script/lib/generate-startup-snapshot.js:338:10)

**Comment by kazaksaeed** [comment]
> Error message at the end
> 
> MACdeMacBook-Pro atom % script/build Node: v10.16.0 Npm: v6.14.8 Python: v2.7.16 Installing script dependencies Installing apm apm 2.6.2 npm 6.14.13 node 10.20.1 x64 atom 1.61.0-dev python 2.7.16 git 2.24.3 Installing modules ✓ Wrote Dependencies Fingerprint: /Users/a01388087/github/atom/node_modules/.dependencies-fingerprint 576d2407b2f80ed82e5d81f228f58ab3c523c5e0 Copying assets to /Users/a01388087/github/atom/out/app Transpiling packages with custom transpiler configurations in /Users/a01388087/github/atom/out/app transpiling for package github Installing modules ✓ Transpiling Babel paths in /Users/a01388087/github/atom/out/app Transpiling CoffeeScript paths in /Users/a01388087/github/atom/out/app Transpiling CSON paths in /Users/a01388087/github/atom/out/app Transpiling PEG.js paths in /Users/a01388087/github/atom/out/app Generating module cache for /Users/a01388087/github/atom/out/app Generating pre-built less cache in /Users/a01388087/github/atom/out/app/less-compile-cache Generating metadata for /Users/a01388087/github/atom/out/app/package.json Generating API docs at /Users/a01388087/github/atom/docs/output/atom-api.json Dumping symbols in /Users/a01388087/github/atom/out/symbols (node:2155) ExperimentalWarning: The fs.promises API is experimental Running electron-packager on /Users/a01388087/github/atom/out/app with app name "Atom Dev" Packaging app for platform darwin x64 using electron v9.4.4 Setting Atom Helper Version for /Users/a01388087/github/atom/out/Atom Dev.app/Contents/Frameworks/Atom Helper.app/Contents/Info.plist Copying non-ASAR resources to /Users/a01388087/github/atom/out/Atom Dev.app/Contents/Resources Writing LICENSE.md to /Users/a01388087/github/atom/out/Atom Dev.app/Contents/Resources Application bundle created at /Users/a01388087/github/atom/out/Atom Dev.app Generating snapshot script at "/Users/a01388087/github/atom/out/startup.js" (177) Minifying startup script Verifying if snapshot can be executed via `mksnapshot` Generating startup blob with mksnapshot Moving generated startup blob into "/Users/a01388087/github/atom/out/Atom Dev.app/Contents/Frameworks/Electron Framework.framework/Resources/v8_context_snapshot.bin" Error: ENOENT: no such file or directory, rename '/Users/a01388087/github/atom/out/v8_context_snapshot.bin' -> '/Users/a01388087/github/atom/out/Atom Dev.app/Contents/Frameworks/Electron Framework.framework/Resources/v8_context_snapshot.bin' at Object.renameSync (fs.js:598:3) at electronLink.then (/Users/a01388087/github/atom/script/lib/generate-startup-snapshot.js:338:10)

https://github.com/atom/atom/issues/23253#issue-1050778058
