### ISSUE TITLE
Uncaught Error: dlopen(~/Desktop/practice/Atom.app/Contents/Resources/app.asar.unpacked/node_modu...

### ISSUE THREAD

**Issue by JeongOMoon** [atom/atom#23359]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 12.0.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/Users/jeongomoon/Desktop/practice/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 0x0001): tried: '/Users/jeongomoon/Desktop/practice/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node' (no such file), '/usr/lib/keyboard-layout-manager.node' (no such file)

```
At electron/js2c/asar.js:140

Error: dlopen(/Users/jeongomoon/Desktop/practice/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 0x0001): tried: '/Users/jeongomoon/Desktop/practice/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node' (no such file), '/usr/lib/keyboard-layout-manager.node' (no such file)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/Users/jeongomoon/Desktop/practice/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at get_KeyboardLayoutManager (/Users/jeongomoon/Desktop/practice/Atom.app/Contents/Resources/app/static/<embedded>:14:2894476)
    at get_manager (/Users/jeongomoon/Desktop/practice/Atom.app/Contents/Resources/app/static/<embedded>:14:2894578)
    at Object.getCurrentKeyboardLayout (/Users/jeongomoon/Desktop/practice/Atom.app/Contents/Resources/app/static/<embedded>:14:2894704)
    at e.keystrokeForKeyboardEvent (/Users/jeongomoon/Desktop/practice/Atom.app/Contents/Resources/app/static/<embedded>:14:1119649)
    at KeymapManager.keystrokeForKeyboardEvent (/Users/jeongomoon/Desktop/practice/Atom.app/Contents/Resources/app/static/<embedded>:11:1224825)
    at KeymapManager.handleKeyboardEvent (/Users/jeongomoon/Desktop/practice/Atom.app/Contents/Resources/app/static/<embedded>:11:1222810)
    at WindowEventHandler.handleDocumentKeyEvent (/Users/jeongomoon/Desktop/practice/Atom.app/Contents/Resources/app/static/<embedded>:11:286651)
```

### Commands

```
  3x -4:55.5.0 tree-view:add-file (div.header.list-item.project-root-header)
```

### Non-Core Packages

```

```

**Comment by Gercino69** [comment]
Probable cause: File deleted by antivirus.
Reinstall the app. Configure your antivirus. Create a backup of "keyboard-layout-manager.node".
Try again.
