### ISSUE TITLE
Uncaught Error: dlopen(~/Desktop/python/Atom.app/Contents/Resources/app.asar.unpacked/node_module...

### ISSUE THREAD

**Issue by Pearl-xi** [atom/atom#23384]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node, 1): image not found

```
At /Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app.asar/node_modules/tree-sitter/index.js:8

Error: dlopen(/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node, 1): image not found
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app/static/<embedded>:11:149207)
    at /app.asar/node_modules/tree-sitter/index.js:3:13)
    at /app.asar/node_modules/tree-sitter/index.js:757:3)
    at Module.get_Module._compile (/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at get_Parser (/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app/static/<embedded>:11:3291341)
    at Function._patchSyntaxNode (/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app/static/<embedded>:11:3291849)
    at new TreeSitterLanguageMode (/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app/static/<embedded>:11:3292105)
    at GrammarRegistry.languageModeForGrammarAndBuffer (/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app/static/<embedded>:11:358401)
    at GrammarRegistry.assignGrammar (/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app/static/<embedded>:11:357922)
    at Object.didConfirmSelection (/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app/static/<embedded>:11:830790)
    at SelectListView.confirmSelection (/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app/static/<embedded>:14:733654)
    at SelectListView.didClickItem (/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app/static/<embedded>:14:731596)
    at ListItemView.onclick (/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app/static/<embedded>:14:730586)
    at ListItemView.didClick (/Users/gaolei/Desktop/python/Atom.app/Contents/Resources/app/static/<embedded>:14:734674)
```

### Commands

```
     -1:00.9.0 editor:newline (input.hidden-input)
     -1:00.1.0 core:backspace (input.hidden-input)
     -0:55.6.0 editor:newline (input.hidden-input)
     -0:54.1.0 core:backspace (input.hidden-input)
  2x -0:51.7.0 grammar-selector:show (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```

```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
