### ISSUE TITLE
Cannot install/delete packages/themes at Atom

### ISSUE THREAD

**Issue by SirNed** [atom/atom#23468]
### Description

When I try to install (or uninstall) a package, I just wait a few minutes and get an error.

### Steps to Reproduce

1. File -> Settings.
2. Install

**Reproduces how often:**

### Versions

apm  2.6.2
npm  6.14.13
node 12.14.1 x64
atom 1.58.0
python 3.10.0
git 2.31.1.windows.1
visual studio

### Additional Information

The logs:
Installing “hydrogen@2.16.3” failed.Hide output…
npm WARN invalid config https-proxy=""
npm WARN invalid config Must be a full url with 'http://'

npm WARN invalid config https-proxy=""
npm WARN invalid config Must be a full url with 'http://'
(node:15200) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://codeload.github.com/nteract/hydrogen/legacy.tar.gz/refs/tags/v2.16.3 failed, reason: connect ECONNREFUSED 127.0.0.1:443
npm ERR!     at ClientRequest.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:223:5)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:406:9)
npm ERR!     at TLSSocket.emit (events.js:223:5)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:92:8)
npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:81:21)
npm ERR!  FetchError: request to https://codeload.github.com/nteract/hydrogen/legacy.tar.gz/refs/tags/v2.16.3 failed, reason: connect ECONNREFUSED 127.0.0.1:443
npm ERR!     at ClientRequest.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:223:5)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:406:9)
npm ERR!     at TLSSocket.emit (events.js:223:5)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:92:8)
npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
npm ERR!   message: 'request to https://codeload.github.com/nteract/hydrogen/legacy.tar.gz/refs/tags/v2.16.3 failed, reason: connect ECONNREFUSED 127.0.0.1:443',
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   stack: 'FetchError: request to https://codeload.github.com/nteract/hydrogen/legacy.tar.gz/refs/tags/v2.16.3 failed, reason: connect ECONNREFUSED 127.0.0.1:443\n' +
npm ERR!     '    at ClientRequest.<anonymous> (C:\\Users\\user\\AppData\\Local\\atom\\app-1.58.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-fetch-npm\\src\\index.js:68:14)\n' +
npm ERR!     '    at ClientRequest.emit (events.js:223:5)\n' +
npm ERR!     '    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n' +
npm ERR!     '    at TLSSocket.emit (events.js:223:5)\n' +
npm ERR!     '    at emitErrorNT (internal/streams/destroy.js:92:8)\n' +
npm ERR!     '    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n' +
npm ERR!     '    at processTicksAndRejections (internal/process/task_queues.js:81:21)'
npm ERR! }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\.atom\.apm\_logs\2022-01-09T04_32_05_207Z-debug.log

**Comment by SirNed** [comment]
**C:\Windows\System32\drivers\etc\hosts**
I had a github subdomain blocked XD
