### ISSUE TITLE
Uncaught Error: The specified module could not be found.

### ISSUE THREAD

**Issue by paranoidsunny** [atom/atom#23469]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Program Files (x86)\GitHub\Atom\app-1.58.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:140

Error: The specified module could not be found.
\\?\C:\Program Files (x86)\GitHub\Atom\app-1.58.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:1:802772)
    at get_KeyboardLayoutManager (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:14:2897612)
    at get_manager (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:14:2897714)
    at Object.getCurrentKeyboardLayout (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:14:2897840)
    at e.keystrokeForKeyboardEvent (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:14:1119651)
    at KeymapManager.keystrokeForKeyboardEvent (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:11:1224825)
    at KeymapManager.handleKeyboardEvent (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:11:1222810)
    at WindowEventHandler.handleDocumentKeyEvent (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:11:286651)
```

### Commands

```
     -0:50.6.0 core:copy (span.syntax--comment.syntax--line)
```

### Non-Core Packages

```

```

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by icecream17** [comment]
I think there's something on atom that checks if the issue has already been reported - but it doesn't trigger in this case

**Comment by paranoidsunny** [comment]
I keep getting the same when trying to copy a snippet of the code

**Comment by paranoidsunny** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Program Files (x86)\GitHub\Atom\app-1.58.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:140

Error: The specified module could not be found.
\\?\C:\Program Files (x86)\GitHub\Atom\app-1.58.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:1:802772)
    at get_KeyboardLayoutManager (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:14:2897612)
    at get_manager (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:14:2897714)
    at Object.getCurrentKeyboardLayout (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:14:2897840)
    at e.keystrokeForKeyboardEvent (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:14:1119651)
    at KeymapManager.keystrokeForKeyboardEvent (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:11:1224825)
    at KeymapManager.handleKeyboardEvent (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:11:1222810)
    at WindowEventHandler.handleDocumentKeyEvent (C:/Program Files (x86)/GitHub/Atom/app-1.58.0/resources/app/static/<embedded>:11:286651)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by icecream17** [comment]
this is a duplicate btw
