### ISSUE TITLE
Atom fails to find a tree-sitter package

### ISSUE THREAD

**Issue by tohoyn** [atom/atom#23571]
**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Debian GNU/Linux
**Thrown From**: [language-rust-bundled](https://github.com/atom/language-rust) package 0.1.0

I get the following error when I created a copy of the language-rust package (language-test2) into the github directory. How can I get Atom to find package tree-sitter-rust? The stack trace refers to directory /usr/share/atom/resources/app/static/ but it does not exist in my system. So where is the code that signals the error?

### Stack Trace

Failed to load a language-rust-bundled package grammar

```
At Cannot find module 'tree-sitter-rust'
Require stack:
- /home/tohoyn/.atom/packages/language-test2/grammars/tree-sitter-rust.cson in /home/tohoyn/.atom/packages/language-test2/grammars/tree-sitter-rust.cson

Error: Cannot find module 'tree-sitter-rust'
Require stack:
- /home/tohoyn/.atom/packages/language-test2/grammars/tree-sitter-rust.cson
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:157920)
    at new TreeSitterGrammar (/usr/share/atom/resources/app/static/<embedded>:11:3311968)
    at GrammarRegistry.createGrammar (/usr/share/atom/resources/app/static/<embedded>:11:362991)
    at /usr/share/atom/resources/app/static/<embedded>:11:362832
    at /usr/share/atom/resources/app/static/<embedded>:11:585501
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
  at /packages/language-test2/grammars/tree-sitter-rust.cson:1:1
```

### Commands

```
     -0:58.1.0 editor:copy-path (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
auto-indent-file 0.2.0 
language-scheme 1.4.0 
motif-syntax 0.0.0 
scheme-syntax 0.4.0 
test1-syntax 0.0.0 
tree-parser-sexp 0.0.0 
```

**Comment by icecream17** [comment]
running atom in dev mode gives better stacktraces (making it much easier to figure out where the problem is) (you can also track some stuff in the console with ctrl+shift+i if you know what you're doing) `atom --dev`

You can get atom to recognize your local copy with `apm --link`

https://github.com/icecream17/atom-update-backlog/blob/main/Debugging-atom.md#opening-atom-in-devsafe-mode
