### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.59.0\res...

### ISSUE THREAD

**Issue by DustIv** [atom/atom#23583]
Hi, this is my first time using Atom. 
When I try to type, suddenly it immediately appears like this. I don't understand what happened. Downloaded atom yesterday
![Screenshot (67)](https://user-images.githubusercontent.com/99316464/153140795-4adf7f11-27f0-434d-b050-ad691574d0b7.png)

**Atom**: 1.59.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\ivand\AppData\Local\atom\app-1.59.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:140

Error: The specified module could not be found.
\\?\C:\Users\ivand\AppData\Local\atom\app-1.59.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:1:789785)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:14:2875504)
    at get_manager (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:14:2875606)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:14:2875732)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:14:1119687)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:1225346)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:1223331)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:286651)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by HummyMolecula** [comment]
You may have installed the module incorrectly.
Have you tried reinstalling Atom?

**Comment by DustIv** [comment]
> Hello! You may have installed the module incorrectly. Have you tried reinstalling Atom?

I've tried to reinstall Atom. It's worked 👍
