### ISSUE TITLE
Attempt to build apm fails : oniguruma.js (?)

### ISSUE THREAD

**Issue by alines7777** [atom/atom#23590]
### Description

My latest attempts to build Atom are progressing, but are still being halted, now on the phase to build `apm`. It is throwing the following compiler warnings and errors at the build of oniguruma libraries.

### Steps to Reproduce

1. ./script/build

**Behavior:**

```
Node:	v16.13.2
Python:	v2.7.18
Installing script dependencies
Installing apm
(node:72759) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
../deps/onig/regcomp.c:563:3: warning: cast to smaller integer type 'unsigned int' from 'OnigUChar *' (aka 'unsigned char *') [-Wpointer-to-int-cast]
  GET_ALIGNMENT_PAD_SIZE(p, pad_size);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/onig/regint.h:234:19: note: expanded from macro 'GET_ALIGNMENT_PAD_SIZE'
               - ((unsigned int )(addr) % WORD_ALIGNMENT_SIZE);\
                  ^~~~~~~~~~~~~~~~~~~~~
../deps/onig/regexec.c:1672:2: warning: cast to smaller integer type 'unsigned int' from 'OnigUChar *' (aka 'unsigned char *') [-Wpointer-to-int-cast]
        ALIGNMENT_RIGHT(q);
        ^~~~~~~~~~~~~~~~~~
../deps/onig/regint.h:240:14: note: expanded from macro 'ALIGNMENT_RIGHT'
  (addr) -= ((unsigned int )(addr) % WORD_ALIGNMENT_SIZE);\
             ^~~~~~~~~~~~~~~~~~~~~
../deps/onig/regexec.c:1737:2: warning: cast to smaller integer type 'unsigned int' from 'OnigUChar *' (aka 'unsigned char *') [-Wpointer-to-int-cast]
        ALIGNMENT_RIGHT(q);
        ^~~~~~~~~~~~~~~~~~
../deps/onig/regint.h:240:14: note: expanded from macro 'ALIGNMENT_RIGHT'
  (addr) -= ((unsigned int )(addr) % WORD_ALIGNMENT_SIZE);\
             ^~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
1 warning generated.
In file included from ../src/onig-scanner-worker.cc:1:
In file included from ../src/onig-scanner-worker.h:7:
In file included from ../../nan/nan.h:56:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/node.h:63:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8.h:30:
/Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:710:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
In file included from ../src/onig-string.cc:1:
In file included from ../src/onig-string.h:6:
In file included from ../../nan/nan.h:56:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/node.h:63:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8.h:30:
/Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:710:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
In file included from ../src/onig-reg-exp.cc:1:
In file included from ../src/onig-reg-exp.h:7:
In file included from ../src/onig-result.h:4:
In file included from ../../nan/nan.h:56:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/node.h:63:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8.h:30:
/Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:710:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
In file included from ../src/onig-result.cc:1:
In file included from ../src/onig-result.h:4:
In file included from ../../nan/nan.h:56:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/node.h:63:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8.h:30:
/Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:710:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
In file included from ../src/onig-searcher.cc:1:
In file included from ../src/onig-searcher.h:5:
In file included from ../src/onig-string.h:6:
In file included from ../../nan/nan.h:56:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/node.h:63:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8.h:30:
/Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:710:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
In file included from ../src/onig-scanner.cc:1:
In file included from ../src/onig-scanner.h:4:
In file included from ../../nan/nan.h:56:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/node.h:63:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8.h:30:
/Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:710:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
1 error generated.
make: *** [Release/obj.target/onig_scanner/src/onig-result.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
make: *** [Release/obj.target/onig_scanner/src/onig-string.o] Error 1
1 error generated.
make: *** [Release/obj.target/onig_scanner/src/onig-scanner-worker.o] Error 1
1 error generated.
make: *** [Release/obj.target/onig_scanner/src/onig-reg-exp.o] Error 1
1 error generated.
make: *** [Release/obj.target/onig_scanner/src/onig-searcher.o] Error 1
1 error generated.
make: *** [Release/obj.target/onig_scanner/src/onig-scanner.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/alines7777/Git/atom/script/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 21.3.0
gyp ERR! command "/usr/local/bin/node" "/Users/alines7777/Git/atom/script/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/alines7777/Git/atom/apm/node_modules/atom-package-manager/node_modules/oniguruma
gyp ERR! node -v v16.13.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oniguruma@7.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@7.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alines7777/.npm/_logs/2022-02-10T15_33_02_392Z-debug.log
node:child_process:867
    throw err;
    ^

Error: Command failed: /Users/alines7777/Git/atom/script/node_modules/.bin/npm --global-style --loglevel=error install
(node:72759) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
../deps/onig/regcomp.c:563:3: warning: cast to smaller integer type 'unsigned int' from 'OnigUChar *' (aka 'unsigned char *') [-Wpointer-to-int-cast]
  GET_ALIGNMENT_PAD_SIZE(p, pad_size);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/onig/regint.h:234:19: note: expanded from macro 'GET_ALIGNMENT_PAD_SIZE'
               - ((unsigned int )(addr) % WORD_ALIGNMENT_SIZE);\
                  ^~~~~~~~~~~~~~~~~~~~~
../deps/onig/regexec.c:1672:2: warning: cast to smaller integer type 'unsigned int' from 'OnigUChar *' (aka 'unsigned char *') [-Wpointer-to-int-cast]
        ALIGNMENT_RIGHT(q);
        ^~~~~~~~~~~~~~~~~~
../deps/onig/regint.h:240:14: note: expanded from macro 'ALIGNMENT_RIGHT'
  (addr) -= ((unsigned int )(addr) % WORD_ALIGNMENT_SIZE);\
             ^~~~~~~~~~~~~~~~~~~~~
../deps/onig/regexec.c:1737:2: warning: cast to smaller integer type 'unsigned int' from 'OnigUChar *' (aka 'unsigned char *') [-Wpointer-to-int-cast]
        ALIGNMENT_RIGHT(q);
        ^~~~~~~~~~~~~~~~~~
../deps/onig/regint.h:240:14: note: expanded from macro 'ALIGNMENT_RIGHT'
  (addr) -= ((unsigned int )(addr) % WORD_ALIGNMENT_SIZE);\
             ^~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
1 warning generated.
In file included from ../src/onig-scanner-worker.cc:1:
In file included from ../src/onig-scanner-worker.h:7:
In file included from ../../nan/nan.h:56:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/node.h:63:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8.h:30:
/Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:710:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
In file included from ../src/onig-string.cc:1:
In file included from ../src/onig-string.h:6:
In file included from ../../nan/nan.h:56:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/node.h:63:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8.h:30:
/Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:710:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
In file included from ../src/onig-reg-exp.cc:1:
In file included from ../src/onig-reg-exp.h:7:
In file included from ../src/onig-result.h:4:
In file included from ../../nan/nan.h:56:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/node.h:63:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8.h:30:
/Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:710:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
In file included from ../src/onig-result.cc:1:
In file included from ../src/onig-result.h:4:
In file included from ../../nan/nan.h:56:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/node.h:63:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8.h:30:
/Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:710:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
In file included from ../src/onig-searcher.cc:1:
In file included from ../src/onig-searcher.h:5:
In file included from ../src/onig-string.h:6:
In file included from ../../nan/nan.h:56:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/node.h:63:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8.h:30:
/Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:710:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
In file included from ../src/onig-scanner.cc:1:
In file included from ../src/onig-scanner.h:4:
In file included from ../../nan/nan.h:56:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/node.h:63:
In file included from /Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8.h:30:
/Users/alines7777/Library/Caches/node-gyp/16.13.2/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:710:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
1 error generated.
make: *** [Release/obj.target/onig_scanner/src/onig-result.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
make: *** [Release/obj.target/onig_scanner/src/onig-string.o] Error 1
1 error generated.
make: *** [Release/obj.target/onig_scanner/src/onig-scanner-worker.o] Error 1
1 error generated.
make: *** [Release/obj.target/onig_scanner/src/onig-reg-exp.o] Error 1
1 error generated.
make: *** [Release/obj.target/onig_scanner/src/onig-searcher.o] Error 1
1 error generated.
make: *** [Release/obj.target/onig_scanner/src/onig-scanner.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/alines7777/Git/atom/script/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 21.3.0
gyp ERR! command "/usr/local/bin/node" "/Users/alines7777/Git/atom/script/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/alines7777/Git/atom/apm/node_modules/atom-package-manager/node_modules/oniguruma
gyp ERR! node -v v16.13.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oniguruma@7.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@7.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alines7777/.npm/_logs/2022-02-10T15_33_02_392Z-debug.log

    at checkExecSyncError (node:child_process:826:11)
    at Object.execFileSync (node:child_process:864:15)
    at module.exports (/Users/alines7777/Git/atom/script/lib/install-apm.js:14:16)
    at Object.<anonymous> (/Users/alines7777/Git/atom/script/bootstrap:38:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(3509) [Uint8Array] [
       10,  62,  32, 111, 110, 105, 103, 117, 114, 117, 109,  97,
       64,  55,  46,  50,  46,  49,  32, 105, 110, 115, 116,  97,
      108, 108,  32,  47,  85, 115, 101, 114, 115,  47,  97, 108,
      105, 110, 101, 115,  55,  55,  55,  55,  47,  71, 105, 116,
       47,  97, 116, 111, 109,  47,  97, 112, 109,  47, 110, 111,
      100, 101,  95, 109, 111, 100, 117, 108, 101, 115,  47,  97,
      116, 111, 109,  45, 112,  97,  99, 107,  97, 103, 101,  45,
      109,  97, 110,  97, 103, 101, 114,  47, 110, 111, 100, 101,
       95, 109, 111, 100,
      ... 3409 more items
    ],
    Buffer(8642) [Uint8Array] [
       40, 110, 111, 100, 101,  58,  55,  50,  55,  53,  57,  41,
       32,  91,  68,  69,  80,  48,  49,  53,  48,  93,  32,  68,
      101, 112, 114, 101,  99,  97, 116, 105, 111, 110,  87,  97,
      114, 110, 105, 110, 103,  58,  32,  83, 101, 116, 116, 105,
      110, 103,  32, 112, 114, 111,  99, 101, 115, 115,  46,  99,
      111, 110, 102, 105, 103,  32, 105, 115,  32, 100, 101, 112,
      114, 101,  99,  97, 116, 101, 100,  46,  32,  73, 110,  32,
      116, 104, 101,  32, 102, 117, 116, 117, 114, 101,  32, 116,
      104, 101,  32, 112,
      ... 8542 more items
    ]
  ],
  pid: 72735,
  stdout: Buffer(3509) [Uint8Array] [
     10,  62,  32, 111, 110, 105, 103, 117, 114, 117, 109,  97,
     64,  55,  46,  50,  46,  49,  32, 105, 110, 115, 116,  97,
    108, 108,  32,  47,  85, 115, 101, 114, 115,  47,  97, 108,
    105, 110, 101, 115,  55,  55,  55,  55,  47,  71, 105, 116,
     47,  97, 116, 111, 109,  47,  97, 112, 109,  47, 110, 111,
    100, 101,  95, 109, 111, 100, 117, 108, 101, 115,  47,  97,
    116, 111, 109,  45, 112,  97,  99, 107,  97, 103, 101,  45,
    109,  97, 110,  97, 103, 101, 114,  47, 110, 111, 100, 101,
     95, 109, 111, 100,
    ... 3409 more items
  ],
  stderr: Buffer(8642) [Uint8Array] [
     40, 110, 111, 100, 101,  58,  55,  50,  55,  53,  57,  41,
     32,  91,  68,  69,  80,  48,  49,  53,  48,  93,  32,  68,
    101, 112, 114, 101,  99,  97, 116, 105, 111, 110,  87,  97,
    114, 110, 105, 110, 103,  58,  32,  83, 101, 116, 116, 105,
    110, 103,  32, 112, 114, 111,  99, 101, 115, 115,  46,  99,
    111, 110, 102, 105, 103,  32, 105, 115,  32, 100, 101, 112,
    114, 101,  99,  97, 116, 101, 100,  46,  32,  73, 110,  32,
    116, 104, 101,  32, 102, 117, 116, 117, 114, 101,  32, 116,
    104, 101,  32, 112,
    ... 8542 more items
  ]
}
```

**Reproduces how often:**

Everytime

### Versions

atom: `1.61.0-dev`

`Darwin 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64`

**Comment by thatcomputerguy0101** [comment]
I’m getting the same issue. I’m assuming it’s a similar root problem as node-sass in nodejs/node#38367 based on the mentions of `std::remove_cv_t`.

**Comment by thatcomputerguy0101** [comment]
Oniguruma fixed this in atom/node-oniguruma#112, released in v7.2.3. Working up the dependency chain, apm bumped their dependency in v2.6.5, the most recent release. I have confirmed that updating the version in atom/apm/package.json to 2.6.5 seems to allow apm to be successfully installed with npm v8.3.0, but it does not seem to be installable with the included v6.14.16 that the bootstrap scripts use. I believe that is caused by NodeJS 16 increasing the minimum npm compatibility requirement to v7.x.x, as described on [StackOverflow](https://stackoverflow.com/questions/69320619/npm-does-not-support-node-js-v16-10-0). The published version of atom uses NodeJS 12.14.1, making all of this a non-issue.

**Comment by thatcomputerguy0101** [comment]
If anyone else encounters this issue, I’ve found the following workaround.

Install Node 12 using nvm, and install Python 2.7 using pyenv. Enable both, then bootstrap Atom.

This dependency on Python 2 definitely feels like something that should be addressed, although my Python 3 version was 3.9. I wasn't able to use pyenv to install Python 3.7, which is listed as a supported version of node-gyp v5.1.0 that is used by the dependencies of atom.

This is still encountering the apm package install error #25417, but that is a separate issue unrelated to this problem.
