### ISSUE TITLE
Problem with a tree-sitter parser

### ISSUE THREAD

**Issue by tohoyn** [atom/atom#23593]
**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Debian GNU/Linux

I get the following error when I created a tree-sitter parser from scratch and used it in an atom language package:

### Stack Trace

Failed to load a language-test1 package grammar

```
At The module '/home/tohoyn/github/tree-sitter-sexp2/build/Release/tree_sitter_sexp_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 102. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /home/tohoyn/.atom/packages/language-test1/grammars/test1.cson

Error: The module '/home/tohoyn/github/tree-sitter-sexp2/build/Release/tree_sitter_sexp_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 102. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/tohoyn/github/tree-sitter-sexp2/bindings/node/index.js:2:20)
    at Object.<anonymous> (/home/tohoyn/github/tree-sitter-sexp2/bindings/node/index.js:21:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /app.asar/src/tree-sitter-grammar.js:61:27)
    at GrammarRegistry.createGrammar (/app.asar/src/grammar-registry.js:604:14)
    at /app.asar/src/grammar-registry.js:583:29
    at /app.asar/node_modules/season/lib/cson.js:219:59
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
  at /packages/language-test1/grammars/test1.cson:1:1
```

### Non-Core Packages

```
language-test1 0.0.0 
```

**Comment by icecream17** [comment]
Atom uses an order version of node (`v14`)

The error is saying that your grammar was compiled with a different version of node than (the version atom is using).

So try rebuilding your grammar with node 14 and `npm rebuild` or `npm install`?

**Comment by tohoyn** [comment]
pe, 2022-02-11 kello 08:40 -0800, Steven Nguyen kirjoitti:
> Atom uses an older version of node (v14)
> The error is saying that your grammar was compiled with a different
> version of node than (the version atom is using).
> So try rebuilding your grammar with node 14 and npm rebuild or npm
> install?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
There is still something wrong with the versions. I changed node to
version 14 with "nvm use 14". I also changed the parser in the language
package to tree-sitter-c. Now I get the following error:

The module '/home/tohoyn/node_modules/tree-sitter-
c/build/Release/tree_sitter_c_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in
/home/tohoyn/.atom/packages/language-test1/grammars/test1.cson

     - Tommi

-- 
Kotisivu / Homepage: http://www.iki.fi/tohoyn/
Sähköposti / E-Mail: ***@***.***
GPG-sormenjälki / GPG fingerprint:
55F4 2477 7155 3528 5CB2 2B7A BB86 1FDE 4046 0F83
FM, Debian-ylläpitäjä / M.Sc., Debian Maintainer

**Comment by icecream17** [comment]
It seems like NODE_MODULE_VERSION 80 doesn't exist anymore!?? https://nodejs.org/en/download/releases/ (skips from 83 to 79)

Don't have an answer/fix right now...

**Comment by tohoyn** [comment]
Now the problem is that I can't open atom at all because I can't find
the atom command. Should I install atom from the debian package?

pe, 2022-02-18 kello 07:26 -0800, Steven Nguyen kirjoitti:
> try adding atom to path
> https://github.com/icecream17/atom-update-backlog/blob/main/Debugging-atom.md#adding-atom-to-path--adding-atom-shell-commands
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>

-- 
Kotisivu / Homepage: http://www.iki.fi/tohoyn/
Sähköposti / E-Mail: ***@***.***
GPG-sormenjälki / GPG fingerprint:
55F4 2477 7155 3528 5CB2 2B7A BB86 1FDE 4046 0F83
FM, Debian-ylläpitäjä / M.Sc., Debian Maintainer

**Comment by claytonrcarter** [comment]
I can't help w/ the issues related to atom being a local/custom install/build, but FWIW I have a local tree-sitter grammar that I'm working on and if I run `npm rebuild`, I get this in the Atom console:

```
Failed to load grammar: /Users/crcarter/.atom/packages/language-php/grammars/tree-sitter-phpdoc.cson Error: The module '/Users/crcarter/src/Atom/language-php/node_modules/tree-sitter-phpdoc/build/Release/tree_sitter_phpdoc_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

After I run `electron-rebuild --version 9.4.4`, I can reload my Atom window and my package works as expected (ie w/o these errors). If you're working off of a local build of Atom, it might be using electron 11, so you might need `11.4.12` instead of `9.4.4` (which is what's in use for the current beta version I'm using).

@icecream17 I forget the details, but I seem to recall that some of these phantom Node version are related to Electron and how it bundles Node.

**Comment by tohoyn** [comment]
I reinstalled atom from the debian package and now I can't find command
electron-rebuild.

la, 2022-02-19 kello 17:10 -0800, claytonrcarter kirjoitti:
> I can't help w/ the issues related to atom being a local/custom
> install/build, but FWIW I have a local tree-sitter grammar that I'm
> working on and if I run npm rebuild, I get this in the Atom console:
> Failed to load grammar: /Users/crcarter/.atom/packages/language-php/grammars/tree-sitter-phpdoc.cson Error: The module '/Users/crcarter/src/Atom/language-php/node_modules/tree-sitter-phpdoc/build/Release/tree_sitter_phpdoc_binding.node'
> was compiled against a different Node.js version using
> NODE_MODULE_VERSION 83. This version of Node.js requires
> NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
> the module (for instance, using `npm rebuild` or `npm install`).
> After I run electron-rebuild --version 9.4.4, I can reload my Atom
> window and my package works as expected (ie w/o these errors). If
> you're working off of a local build of Atom, it might be using
> electron 11, so you might need 11.4.12 instead of 9.4.4 (which is
> what's in use for the current beta version I'm using).
> @icecream17 I forget the details, but I seem to recall that some of
> these phantom Node version are related to Electron and how it bundles
> Node.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>

-- 
Kotisivu / Homepage: http://www.iki.fi/tohoyn/
Sähköposti / E-Mail: ***@***.***
GPG-sormenjälki / GPG fingerprint:
55F4 2477 7155 3528 5CB2 2B7A BB86 1FDE 4046 0F83
FM, Debian-ylläpitäjä / M.Sc., Debian Maintainer

**Comment by claytonrcarter** [comment]
Try `npx electron-rebuild --version 9.4.4` as described here: https://github.com/atom/atom/discussions/23565#discussioncomment-2154131
