### ISSUE TITLE
GPU process isn't usable

### ISSUE THREAD

**Issue by Lithimlin** [atom/atom#23608]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When starting up atom, it crashes with a fatal error

### Steps to Reproduce

1. Run `atom`, `atom --safe`, or `atom --disable-gpu`

**Expected behavior:**

Atom starts successfully.

**Actual behavior:**

Atom crashes with a GPU error:
```console
/usr/bin/atom: line 86:  5746 Illegal instruction     (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
[...]
[5746:0215/121832.223620:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
[...]
```

**Reproduces how often:**

100%

### Versions

```console
❯ atom --version
Atom    : 1.58.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1
❯ apm --version
apm  2.6.4
npm  6.14.9
node 17.3.1 x64
atom 1.58.0
python 3.10.2
git 2.35.1
```
OS: Arch Linux x86_64
Kernel: 5.16.9-arch1-1

**Comment by Theraa0** [comment]
Experiencing the same problem.
I found an old issue where they used `atom --in-progress-gpu` or `atom --no-sandbox` as a temporary solution, but i have no clue what those do, so I can't really recommend using them.

**Comment by hummeltech** [comment]
Yeah,  it seems related to a recently updated package, but I haven't figured out which one yet, here are some that I think might be related:
```
[2022-02-14T08:23:41-0700] [ALPM] upgraded npm (8.4.1-1 -> 8.5.0-1)
[2022-02-14T21:07:22-0700] [ALPM] upgraded glibc (2.33-5 -> 2.35-2)
[2022-02-14T21:07:24-0700] [ALPM] upgraded gcc-libs (11.1.0-3 -> 11.2.0-3)
[2022-02-14T21:07:36-0700] [ALPM] upgraded nodejs (17.3.0-1 -> 17.3.1-1)
```

**Comment by builderdev212** [comment]
Can confirm that this is in fact an issue. It appears that this may be caused by depreciated electron renderer modules? The terminal output during the crash says to see [this issue.](https://github.com/electron/electron/issues/18397) I assume the depreciated renderer modules cause that "GPU process isn't usable." warning.

**Comment by garpu** [comment]
This happens to me on slackware-current with glibc 2.35. Launches with --no-sandbox.

**Comment by JurijOrlow** [comment]
Same on Manjaro

**Comment by ExistingProgrammer** [comment]
Same for me on EndeavourOS

**Comment by daneenjah** [comment]
Same issue on Artix.

**Comment by Fluffy-Bean** [comment]
Having same issue when starting atom with `atom` or with `atom --disable-gpu`. I can only get it to start with `atom --in-process-gpu`

**Comment by icecream17** [comment]
Duplicate of https://bugzilla.suse.com/show_bug.cgi?id=1191012?

**Comment by MurdoMaclachlan** [comment]
Also on Slackware Current with this issue, `atom --no-sandbox` makes it work. It also seems to be affecting Microsoft Teams (same symptoms, same fix), so it might not be Atom-specific?

**Comment by dhdeangelis** [comment]
This happens too in openSUSE Tumbleweed. As noted above, the same problem and the same solution happens with MS Teams. Very probably not Atom specific.

**Comment by 3dprogramin** [comment]
Issue is not from atom but from electron (or some library used by it).
I had the same issue with an electron app I've built, and solution was the same as mentioned, to start it with the arguments.
The arguments are a workaround if you ask me, still looking for an alternative, but the workaround is better than nothing though.

**Comment by MurdoMaclachlan** [comment]
Is there an issue for it open on the Electron repository? If not, it's probably best that one's opened there instead of spamming the Atom devs. =)

**Comment by 3dprogramin** [comment]
I agree.
That's why I commented previously, to confirm from my end too that it's not an atom issue.

**Comment by alerque** [comment]
I believe this is/was an Electron issue. Since the report is on Atom 1.58.0 / Electron 9 and the current Arch packaging is 1.61.0beta0 / Electron 11 and I cannot reproduce this, I suggest this issue is likely not relevant to this repository and can be closed.

**Comment by Lithimlin** [comment]
This issue still very much persists for me on the newest version for Arch. Interestingly though I think it only happens on my desktop but not on my laptop (I still have to check that) which have a very similar setup.

**Comment by alerque** [comment]
@Lithimlin Can you confirm what `--version` shows for `atom` and `apm` now? Also are you sure you aren't just a victim of the [nvidia/electron issue linked above](https://github.com/atom/atom/issues/23608#issuecomment-1057661196)?

**Comment by Lithimlin** [comment]
> Can you confirm what `--version` shows for `atom` and `apm` now?

```console
❯ atom --version
Atom    : 1.58.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1
❯ apm --version
apm  2.6.5
npm  6.14.9
node 16.14.2 x64
atom 1.58.0
python 3.10.4
git 2.35.1
```

> Also are you sure you aren't just a victim of the https://github.com/atom/atom/issues/23608#issuecomment-1057661196?

Quite the contrary, I'm sure that that's the issue since my laptop doesn't have an nvidia graphics card.
I am already using the `--nosandbox --in-progress-gpu` workaround but that's all that is: A workaround. Not a solution to the problem. Do correct me if I'm seeing this wrong.

As the [Electron bug tracker says](https://bugzilla.suse.com/show_bug.cgi?id=1191012#c32):
> I agree, most apps obviously upgraded their electron codebase now. For atom, the --no-sandbox switch is still required.

**Comment by alerque** [comment]
@Lithimlin You are still using outdated packages. Per my [comment above](https://github.com/atom/atom/issues/23608#issuecomment-1092104266) the current official Atom package in Arch Linux is `1.61.0-beta0`. We know the 1.58.0 package was broken, only reports of the current packages are eligible for bug fixes. We packaged the beta on Arch Linux because even the 1.60.0 stable release used Electron 9 which is EOL and we are dropping it from the distro.

**Comment by Lithimlin** [comment]
I'm just confused as to why on my Laptop, the beta seems to be in the regular community package while on my desktop, it's a separate AUR package.

**Comment by alerque** [comment]
@Lithimlin Because you installed different packages. The [community] package is `atom` and currently at version 1.61.0-beta0 like I said. The [AUR] package you probably have installed there is `atom-editor-beta-bin` and also at the same version as of this moment. You are welcome to use either, but they are completely different. The [community] package will do things like use the Arch system Electron package, the Arch apm package, etc. The AUR package is just a binary blob with all of that bundled inside however upstream builds it. Pick your poison.


-----

Again as the Arch Linux maintainer for the [community] package I'd like to reiterate that this whole issue is *not an upstream Atom Editor issue* and this issue can be closed. If you have trouble with the Arch **packaging** please use Arch Linux's bug tracker (or the AUR comments if you are using the AUR pakcage). Otherwise this issue tracker should be used for issues with the actual editor, not the distro packaging.

**Comment by russeree** [comment]
Same issue on centos9 stream. Using --in-process-gpu fixes it.

**Comment by stanier** [comment]
Same on Pop!_OS 22.04, `--in-process-gpu` and `--no-sandbox` both fix.  Worked peachy back on 21.10

**Comment by JeremyPerpignani** [comment]
> 

Are using these arguments going to matter at all? I am having the same issue in Pop!_OS 22.04 and need Atom for a class.

**Comment by JeremyPerpignani** [comment]
> Same on Pop!_OS 22.04, `--in-process-gpu` and `--no-sandbox` both fix. Worked peachy back on 21.10

Are using these arguments going to matter at all? I am having this same issue in Pop!_OS 22.04 and they are the only way I can run Atom. I need to use it for a course and just want to make sure I will be fine opening it like this. Thanks.

**Comment by russeree** [comment]
> > Same on Pop!_OS 22.04, `--in-process-gpu` and `--no-sandbox` both fix. Worked peachy back on 21.10
> 
> Are using these arguments going to matter at all? I am having this same issue in Pop!_OS 22.04 and they are the only way I can run Atom. I need to use it for a course and just want to make sure I will be fine running it like this. Thanks.

For your use case it likely will not matter at all, Drawing performance and cpu usage is affected if I am correct.

**Comment by stanier** [comment]
So is Atom officially deprecated in favor of VS Code?

Or does Github just wanna let it fade into obscurity because people can't launch it?

**Comment by garpu** [comment]
> So is Atom officially deprecated in favor of VS Code?
> 
> Or does Github just wanna let it fade into obscurity because people can't launch it?

? It works fine, so long as you start it with --no-sandbox.  I believe the beta version is using the patched version of electron, as well.

**Comment by blueglyph** [comment]
Same issue on Manjaro in a VirtualBox VM. The crash reporter itself doesn't seem able to transmit the information and crashes.

While it may be an Electron issue, I have no idea how it's implemented, and I have no issue with other Electron applications in the same environment, so I'll post the details here. IMO it's up to the dev to know whether it needs to be reported to Electron by them with details on how it's used in this application.

For example, Code - OSS runs fine, but I see it relies on electron17, not electron9.

`atom --disable-gpu` is the only workaround I could try that allows Atom to run.

**Versions:**

Atom downloaded from here, version 1.60.0-amd64. Same problem with the Manjaro's repository version which is stuck at 1.58 at the moment.

> Atom    : 1.60.0
> Electron: 9.4.4
> Chrome  : 83.0.4103.122
> Node    : 12.14.1

or

> Atom    : 1.58.0
> Electron: 9.4.4
> Chrome  : 83.0.4103.122
> Node    : 12.14.1

**Feedback on the console of version 1.60:**

> [1169:0512/143250.331533:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
> --2022-05-12 14:32:50--  https://atom.io/crash_reports
> Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
> Resolving atom.io (atom.io)... 20.119.16.4
> Connecting to atom.io (atom.io)|20.119.16.4|:443... connected.
> HTTP request sent, awaiting response... 204 No Content
> 2022-05-12 14:32:52 (0,00 B/s) - ‘/dev/fd/4’ saved [0]
> 
> 
> Unexpected crash report id length
> Failed to get crash dump id.
> Report Id: 
> --2022-05-12 14:32:52--  https://atom.io/crash_reports
> Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
> Resolving atom.io (atom.io)... 20.119.16.4
> Connecting to atom.io (atom.io)|20.119.16.4|:443... connected.
> HTTP request sent, awaiting response... 204 No Content
> 2022-05-12 14:32:53 (0,00 B/s) - ‘/dev/fd/4’ saved [0]
> 
> 
> Unexpected crash report id length
> Failed to get crash dump id.
> Report Id: 
> Illegal instruction (core dumped)

**Feedback on the console of version 1.58:** (the repetition below is not a copy/paste mistake on my part)

> /usr/bin/atom: line 86:  2002 Illegal instruction     (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
> [2002:0512/145355.377070:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
> --2022-05-12 14:53:55--  https://atom.io/crash_reports
> Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
> Resolving atom.io (atom.io)... 20.119.16.4
> Connecting to atom.io (atom.io)|20.119.16.4|:443... connected.
> HTTP request sent, awaiting response... 204 No Content
> 2022-05-12 14:53:56 (0,00 B/s) - ‘/dev/fd/4’ saved [0]
> 
> 
> Unexpected crash report id length
> Failed to get crash dump id.
> Report Id: 
> --2022-05-12 14:53:56--  https://atom.io/crash_reports
> Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
> Resolving atom.io (atom.io)... 20.119.16.4
> Connecting to atom.io (atom.io)|20.119.16.4|:443... connected.
> HTTP request sent, awaiting response... 204 No Content
> 2022-05-12 14:53:57 (0,00 B/s) - ‘/dev/fd/4’ saved [0]
> 
> 
> Unexpected crash report id length
> Failed to get crash dump id.
> Report Id:

**Comment by blueglyph** [comment]
Interestingly, I see that after installing Atom, an "Electron" was added to the menu. Code - OSS added one of its own too.

If I launch electron9, I get the same issue. If I launch electron17, it's fine. So a change in the dependencies seem to be necessary indeed.

> (node:1290) UnhandledPromiseRejectionWarning: Error: Image could not be created from /usr/share/pixmaps/electron.png
>     at createWindow (/usr/lib/electron9/resources/default_app.asar/default_app.js:57:18)
>     at async exports.loadFile (/usr/lib/electron9/resources/default_app.asar/default_app.js:83:18)
> (node:1290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:1290) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> [1290:0512/152349.482221:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
> Trace/breakpoint trap (core dumped)

**Comment by raer0** [comment]
BE ADVISED: Disabling electron sandbox with the ```--no-sandbox``` flag opens your workstation to security vulnerabilities. https://github.com/electron/electron/issues/15760

**Comment by raer0** [comment]
> I believe this is/was an Electron issue. Since the report is on Atom 1.58.0 / Electron 9 and the current Arch packaging is 1.61.0beta0 / Electron 11 and I cannot reproduce this, I suggest this issue is likely not relevant to this repository and can be closed.


I have done a bit of tracking on this issue, and can confirm that this issue is a duplicate of #23036

I second that this issue should be closed, and all further discussion/research should be directed to #23036.

**Comment by raer0** [comment]
https://github.com/atom/atom/issues/23036#issuecomment-1139239233

This is a duplicate of #23036 and the issue should be closed. Please follow the link above for more information on this issue.

**Comment by stanier** [comment]
> So is Atom officially deprecated in favor of VS Code?
> 
> Or does Github just wanna let it fade into obscurity because people can't launch it?

Just popping back in to say "CALLED IT!"

**Comment by misterBart** [comment]
Same problem, after upgrading Ubuntu Linux from 21.10 to 22.04.
Used `atom --in-process-gpu` to work around the issue.

**Comment by jj15warrior** [comment]
same issue (and workaround with --no-sandbox) with betterdiscord-installer on manjaro

**Comment by tomishiyo** [comment]
Hi, I'm experiencing the same problem in a Kali 5.18 running in VirtualBox. I can also confirm that running with --no-sandbox and --in-progress-gpu circumvented the issue.
