### ISSUE TITLE
Can not able to install Atom in Windows 8.1

### ISSUE THREAD

**Issue by mohamadsheam** [atom/atom#23605]
### Description

Error Log

2022-02-15 00:52:14> Program: Starting Squirrel Updater: --install .
2022-02-15 00:52:14> Program: Starting install, writing to C:\Users\Alucard\AppData\Local\SquirrelTemp
2022-02-15 00:52:14> Program: About to install to: C:\Users\Alucard\AppData\Local\WhatsApp
2022-02-15 00:52:15> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Alucard\AppData\Local\WhatsApp\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2022-02-15 00:52:15> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Alucard\AppData\Local\WhatsApp\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2022-02-15 00:52:15> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Alucard\AppData\Local\SquirrelTemp
2022-02-15 00:52:15> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2022-02-15 00:52:15> ApplyReleasesImpl: Writing files to app directory: C:\Users\Alucard\AppData\Local\WhatsApp\app-2.2202.12
2022-02-15 00:52:23> LogHost: Rigging execution stub for WhatsApp_ExecutionStub.exe to C:\Users\Alucard\AppData\Local\WhatsApp\WhatsApp.exe
2022-02-15 00:52:24> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Alucard\AppData\Local\WhatsApp\app-2.2202.12\WhatsApp.exe]
2022-02-15 00:52:26> ApplyReleasesImpl: Starting fixPinnedExecutables
2022-02-15 00:52:26> ApplyReleasesImpl: Fixing up tray icons
2022-02-15 00:52:26> ApplyReleasesImpl: cleanDeadVersions: for version 2.2202.12
2022-02-15 00:52:26> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2.2202.12
2022-02-15 01:06:24> Program: Starting Squirrel Updater: --install . --exeName=Teams_windows_x64.exe
2022-02-15 01:06:24> LogHost: Write failed.
2022-02-15 01:06:24> LogHost: Message: Object reference not set to an instance of an object.
2022-02-15 01:06:24> LogHost: Stack trace: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Alucard\AppData\Roaming\Microsoft\Teams\SquirrelTelemetry.log'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at Telemetry.AriaWrapper.LogToFile(String message)
2022-02-15 01:06:24> LogHost: Write failed.
2022-02-15 01:06:24> LogHost: Message: Scenario.Status: success, scenario: 184e87af-28ba-4663-8d7a-f366b29865f5, Scenario.Name: desktop_squirrel_install, Scenario.Step: start, sequence: 0, appversion: 1.5.00.2164, platformId: 27, DeviceInfo.OsName: Windows, DeviceInfo.CpuArchitecture: x64, DeviceInfo.OsVersion: 6.3.9600.0, AppInfo.ProcessArchitecture: x86, AppInfo.ClientType: desktop, dllSearchPathState: unset, clientType: desktop, source: exe, distSrc: default, breadcrumb: , desktopSession: desktop-7350ad18-15d2-4b43-b664-5862a53bef0d, installSessionId: 35333d990ab0727833cf262b3714801919aae350de28d414b3a952bad589fba2, delta: 6, scenarioDelta: 6, elapsed: 1644865584654, stepDelta: 0, DeviceInfo.ComputerUuid: 9b52f8c56ebbe111a1a5b888e34cbb99, DeviceInfo.OfficeMachineId: 9b52f8c56ebbe111a1a5b888e34cbb99, InstallerVersion: 1.10.84.0, eventpdclevel: 1, userpdclevel: 0
2022-02-15 01:06:24> LogHost: Stack trace: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Alucard\AppData\Roaming\Microsoft\Teams\SquirrelTelemetry.log'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at Telemetry.AriaWrapper.LogToFile(String message)
2022-02-15 01:06:24> Program: setup.json does not exist
2022-02-15 01:06:24> Program: Starting install, writing to C:\Users\Alucard\AppData\Local\SquirrelTemp
2022-02-15 01:06:25> Program: File does not contain contextual info: Teams_windows_x64.exe
2022-02-15 01:06:25> UpdateManager: using rootAppDirectory: C:\Users\Alucard\AppData\Local\Microsoft\Teams
2022-02-15 01:06:25> Program: About to install to: C:\Users\Alucard\AppData\Local\Microsoft\Teams
2022-02-15 01:06:25> Program: Setup.json exist, copying over
2022-02-15 01:06:25> RegistryService: RegKeyExists: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run does not have TeamsMachineInstaller
2022-02-15 01:06:25> Program: CheckMsiAndTryAddInstallSource: Not MSI, no need to add HKEY_CURRENT_USER\Software\Microsoft\Office\Teams\InstallSource
2022-02-15 01:06:25> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Alucard\AppData\Local\Microsoft\Teams\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2022-02-15 01:06:25> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Alucard\AppData\Local\Microsoft\Teams\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__7.MoveNext()
2022-02-15 01:06:25> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Alucard\AppData\Local\SquirrelTemp
2022-02-15 01:06:25> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2022-02-15 01:06:25> RegistryService: RegKeyExists: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\Teams\ does not exist
2022-02-15 01:06:25> ApplyReleasesImpl: No delta packages found. Applying current release package.
2022-02-15 01:06:25> ApplyReleasesImpl: getting squirrel aware apps failed with exception Could not find a part of the path 'C:\Users\Alucard\AppData\Local\Microsoft\Teams\current'.
2022-02-15 01:06:25> ApplyReleasesImpl: Writing files to app directory: C:\Users\Alucard\AppData\Local\Microsoft\Teams\current
2022-02-15 01:06:30> RegistryService: RegKeyExists: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\Teams\ does not exist
2022-02-15 01:06:31> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Alucard\AppData\Local\Microsoft\Teams\current\Teams.exe]
2022-02-15 01:06:35> ApplyReleasesImpl: About to RemoveOldShorcuts for Teams.exe, rootAppDir C:\Users\Alucard\AppData\Local\Microsoft\Teams
2022-02-15 01:06:35> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Cloud\Office\16.0\Teams does not exist
2022-02-15 01:06:35> ApplyReleasesImpl: Registry value Software\Policies\Microsoft\Cloud\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-02-15 01:06:35> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\Teams does not exist
2022-02-15 01:06:35> ApplyReleasesImpl: Registry value Software\Policies\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-02-15 01:06:35> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Teams does not exist
2022-02-15 01:06:35> ApplyReleasesImpl: Registry value Software\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-02-15 01:06:35> ApplyReleasesImpl: Registry flags are not set: proceed with default value NotConfigured
2022-02-15 01:06:35> ApplyReleasesImpl: Starting fixPinnedExecutables
2022-02-15 01:06:35> ApplyReleasesImpl: Fixing up tray icons
2022-02-15 01:06:35> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__34_0(RegistryView view)
2022-02-15 01:06:35> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__34_0(RegistryView view)
2022-02-15 01:06:35> MeetingAddinInstaller: System.ArgumentException: Cannot delete a subkey tree because the subkey does not exist.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey)
   at Squirrel.MeetingAddinInstaller.<InstallMeetingAddinAsync>d__15.MoveNext()
2022-02-15 01:06:35> MeetingAddinInstaller: StagedAppDirectory does not exist. Using Current
2022-02-15 01:06:35> MeetingAddinInstaller: There is no version.txt. Falling back to getting version from folder name
2022-02-15 01:06:35> MeetingAddinInstaller: Version: 1.0.21348.1; addinPackageDirectory: 1.0.21348.1
2022-02-15 01:06:35> MeetingAddinInstaller: .dead exists: False
2022-02-15 01:06:35> MeetingAddinInstaller: path to .dead: C:\Users\Alucard\AppData\Local\Microsoft\TeamsMeetingAddin\1.0.21348.1\.dead
2022-02-15 01:06:35> MeetingAddinInstaller: before cleanup unused versions
2022-02-15 01:06:35> MeetingAddinInstaller: Addin directory exists. Copy was successful
2022-02-15 01:06:35> MeetingAddinInstaller: Failed to install the Teams meeting add-in: COM registration failed. Regsvr Path: C:\Windows\system32\regsvr32.exe, Arguments: /s /n /i:user "C:\Users\Alucard\AppData\Local\Microsoft\TeamsMeetingAddin\1.0.21348.1\x64\Microsoft.Teams.AddinLoader.dll", ErrorCode: 3, % Message: 
2022-02-15 01:06:35> PresenceAddinInstaller: Installing Teams Presence addin for Outlook...
2022-02-15 01:06:35> PresenceAddinInstaller: Copying C:\Users\Alucard\AppData\Local\Microsoft\Teams\current\resources\assets\tlb\Uc.tlb to C:\Users\Alucard\AppData\Local\Microsoft\TeamsPresenceAddin
2022-02-15 01:06:35> PresenceAddinInstaller: Copying C:\Users\Alucard\AppData\Local\Microsoft\Teams\current\resources\assets\tlb\Uc.win32.tlb to C:\Users\Alucard\AppData\Local\Microsoft\TeamsPresenceAddin
2022-02-15 01:06:35> PresenceAddinInstaller: check if UC TypeLib points to current\resources\assets\tlb\Uc.tlb
2022-02-15 01:06:35> PresenceAddinInstaller: Registering UC Typelib WIN32 under HKCU...
2022-02-15 01:06:35> PresenceAddinInstaller: UC Typelib WIN32 successfully registered to C:\Users\Alucard\AppData\Local\Microsoft\TeamsPresenceAddin\Uc.win32.tlb under HKCU!
2022-02-15 01:06:35> PresenceAddinInstaller: Registering UC Typelib WIN64 under HKCU...
2022-02-15 01:06:35> PresenceAddinInstaller: UC Typelib WIN64 successfully registered to C:\Users\Alucard\AppData\Local\Microsoft\TeamsPresenceAddin\Uc.tlb under HKCU!
2022-02-15 01:06:36> PresenceAddinInstaller: IM Provider registry key has been created!
2022-02-15 01:06:36> ApplyReleasesImpl: cleanDeadVersions: for original version of  and current version of 1.5.00.2164
2022-02-15 01:06:36> ApplyReleasesImpl: cleanDeadVersions: exclude current folder stage
2022-02-15 01:06:37> RegistryService: TryDeleteRegKey: HKEY_CURRENT_USER\Software\Microsoft\Office\Teams not found

**Expected behavior:**

**Actual behavior:**

![Screenshot_1](https://user-images.githubusercontent.com/13189814/153942635-32674022-1f08-451f-8d08-de13b838b7ef.png)

**Reproduces how often:**

### Versions
1.59.0

### Additional Information
My PC config
![Screenshot_2](https://user-images.githubusercontent.com/13189814/153943254-0af4fd22-1f9f-47f6-a61c-c30de4e68fe5.png)

**Comment by mohamadsheam** [comment]
Hi, any possible solution? still not able to install Atom

**Comment by Anaqqa** [comment]
Same issue, did you find a solution?

**Comment by mohamadsheam** [comment]
> Same issue, did you find a solution?

Nope I did not. Now using Versions 1.60.0
