### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\C:\ProgramData\himan\atom\app-1.59....

### ISSUE THREAD

**Issue by renumehta7368** [atom/atom#23602]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.59.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\ProgramData\himan\atom\app-1.59.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:140

Error: The specified module could not be found.
\\?\C:\ProgramData\himan\atom\app-1.59.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (C:/ProgramData/himan/atom/app-1.59.0/resources/app/static/<embedded>:1:789785)
    at get_KeyboardLayoutManager (C:/ProgramData/himan/atom/app-1.59.0/resources/app/static/<embedded>:14:2875504)
    at get_manager (C:/ProgramData/himan/atom/app-1.59.0/resources/app/static/<embedded>:14:2875606)
    at Object.getCurrentKeyboardLayout (C:/ProgramData/himan/atom/app-1.59.0/resources/app/static/<embedded>:14:2875732)
    at e.keystrokeForKeyboardEvent (C:/ProgramData/himan/atom/app-1.59.0/resources/app/static/<embedded>:14:1119687)
    at KeymapManager.keystrokeForKeyboardEvent (C:/ProgramData/himan/atom/app-1.59.0/resources/app/static/<embedded>:11:1225346)
    at KeymapManager.handleKeyboardEvent (C:/ProgramData/himan/atom/app-1.59.0/resources/app/static/<embedded>:11:1223331)
    at WindowEventHandler.handleDocumentKeyEvent (C:/ProgramData/himan/atom/app-1.59.0/resources/app/static/<embedded>:11:286651)
```

### Commands

```
     -8:06.0 core:save (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```

```

**Comment by renumehta7368** [comment]
can anyone helps me on this please

**Comment by renumehta7368** [comment]
help me please
