### ISSUE TITLE
Uncaught Error: /usr/lib/x86_64-linux-gnu/libstdc  .so.6: version `GLIBCXX_3.4.22' not found (req...

### ISSUE THREAD

**Issue by ayubondarenko** [atom/atom#23641]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.59.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 16.04.7
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: /usr/lib/x86_64-linux-gnu/libstdc  .so.6: version `GLIBCXX_3.4.22' not found (required by /usr/share/atom/resources/app.asar.unpacked/node_modules/@atom/fuzzy-native/build/Release/fuzzy-native.node)

```
At electron/js2c/asar.js:140

Error: /usr/lib/x86_64-linux-gnu/libstdc  .so.6: version `GLIBCXX_3.4.22' not found (required by /usr/share/atom/resources/app.asar.unpacked/node_modules/@atom/fuzzy-native/build/Release/fuzzy-native.node)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149207)
    at /app.asar/node_modules/@atom/fuzzy-native/lib/main.js:1:173)
    at /app.asar/node_modules/@atom/fuzzy-native/lib/main.js:3:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:756277)
    at get_NativeFuzzy (/usr/share/atom/resources/app/static/<embedded>:14:614871)
    at /usr/share/atom/resources/app/static/<embedded>:14:618921
    at Config.observeKeyPath (/usr/share/atom/resources/app/static/<embedded>:11:337801)
    at Config.observe (/usr/share/atom/resources/app/static/<embedded>:11:332283)
    at new FuzzyFinderView (/usr/share/atom/resources/app/static/<embedded>:14:618716)
    at new ProjectView (/usr/share/atom/resources/app/static/<embedded>:11:801326)
    at Object.createProjectView (/usr/share/atom/resources/app/static/<embedded>:11:190530)
    at HTMLElement.fuzzy-finder:toggle-file-finder (/usr/share/atom/resources/app/static/<embedded>:11:189028)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:352663)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1228249)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1224383)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:286651)
```

### Commands

```
     -2:52.1.0 intentions:highlight (input.hidden-input)
     -2:51.8.0 core:undo (input.hidden-input)
     -2:50.2.0 intentions:highlight (input.hidden-input)
     -2:49.9.0 core:undo (input.hidden-input)
  3x -2:49.1.0 core:redo (input.hidden-input)
     -2:47.8.0 intentions:highlight (input.hidden-input)
     -2:47.7.0 core:undo (input.hidden-input)
     -2:30.5.0 intentions:highlight (input.hidden-input)
     -2:29.8.0 core:copy (input.hidden-input)
     -2:24.7.0 intentions:highlight (input.hidden-input)
     -2:24.1.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -2:12.8.0 editor:consolidate-selections (input.hidden-input)
     -2:12.8.0 core:cancel (input.hidden-input)
     -2:11.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:25.2.0 intentions:highlight (input.hidden-input)
     -0:24.8.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
busy-signal 2.0.1 
color-picker 2.3.0 
formatters-python 1.2.1 
hyperclick 0.1.5 
ide-python 1.7.2 
ide-rust 0.22.0-beta.3 
intentions 2.1.1 
linter 3.4.0 
linter-csslint 2.0.6 
linter-eslint 9.0.0 
linter-python-pep8 0.2.0 
linter-rust 1.0.1 
linter-ui-default 3.4.1 
prettier-atom 0.60.1 
react 0.18.0 
react-redux-snippets 0.1.6 
```

**Comment by ROBOTIS-David** [comment]
Same Issue Occured

**Comment by juansecaro** [comment]
Same here
