### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.S...

### ISSUE THREAD

**Issue by ElectricalAptitude** [atom/atom#23661]
1. Open Atom app
2. File menu > Open > select .html file
3. File does not open
4. Repeat steps 2-3
5. Force quit Atom
6. Locate file in Finder
7. Open file with > Atom
8. Atom opens file, with error
9. Submit issue!

**Atom**: 1.59.0 x64
**Electron**: 9.4.4
**OS**: 12.2.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 0x0001): tried: '/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node' (no such file), '/usr/lib/keyboard-layout-manager.node' (no such file)

```
At electron/js2c/asar.js:140

Error: dlopen(/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 0x0001): tried: '/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node' (no such file), '/usr/lib/keyboard-layout-manager.node' (no such file)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at get_KeyboardLayoutManager (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:14:2872375)
    at get_manager (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:14:2872477)
    at Object.getCurrentKeyboardLayout (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:14:2872603)
    at e.keystrokeForKeyboardEvent (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:14:1119692)
    at KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:11:1225346)
    at KeymapManager.handleKeyboardEvent (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:11:1223331)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:11:286651)
```

### Commands

```
     -0:12.5.0 core:select-all (input.hidden-input)
     -0:12.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
column-select 1.0.1 
srt-syntax 0.0.0 
tablr 1.8.3 
web-accessibility-checker 0.1.4 
```

**Comment by Cazzanova32** [comment]
Man do I have a juicy story to tell you. The day is December 7th 2019 and please just snowed 6in outside two men come to my house at 43 Mechanic Street Apartment 5 limited New Hampshire they tried to force their way through my front door I hope my front door back as I was sleeping on the couch jumped up to the commotion the old through the door the two men to leave me alone unmanned continues to try to beat my door down cuz I'm holding it shut and yelled through the door two more times to get off the property to leave me alone at this time the much larger, a 6-3 300 lb tries to force his way into my house at this time I'm coming very frightened. Keep in mind I am in my pajamas and my slippers and I'm falling asleep on my couch watching Donald Trump being persecuted by Nancy Pelosi back in the nineteen remember like it was yesterday. I had a camping Implement a k a a hatchet next to my front door. Because that was it's natural home in my apartment I grabbed it and told them again to leave me alone and get off my F$#% property. At this point and I'm leaving my place of residence and they're still trying to gain entry into my house I unlock the door busted the lock and what's left of the door frame and I stepped out to the entryway and ask them if they wanted to really do this right then and there. They back up my driveway a few feet can I go back into my apartment they come back down to my apartment door and try again to assault my door and gain entry I open the door in back in chain persuade them to go back up the driveway a few feet. This unnatural dance going to the door up the driveway persisting that they weren't leaving until they gained entry into my home and thoroughly beat me I think their intent was to gain possession and which were in my house. The last time let it go out unbeknownst to me my next door neighbor was outside at this point she had been woken up by these men trying to beat my door down her bedroom is a good 80 ft away from my front door these men were beating on my door so hard that they woke her from a dead sleep in her bedroom 80 ft away. She comes out the states video taping me with a hedge in my hand looking like a wild man but no background contacts to this you would think I was just acting irrationally it was not at this point I was seriously fearful of my life as they had made it very clear that they were not leaving until they had pleaded what they had come to my home to do. Put a bit of back story at 7 a.m. that morning one of the gentleman that came in the house at sent me a text message that said that he was going to my work if I wasn't at work he was going to my house and he was going to throw me a beating / kill me. I very wrong for you mistook this as him being a keyboard Warrior unbeknownst to me that he had gone to get his biggest and toughest friend that he had come to my house and try to physically assault me and break into my home. Please show up at this point and very agitated and trot as a discount through a very stressful situation I'm confused and still have sleep I tell the police officers that the men had just barely left my house in a black SUV dark blue SUV. Upon review of the dash cam footage of the cruiser you can see the darkest she be going by one of the Cruisers they went back to their apartment complex on the other side of Lebanon purposely switched cars out and goes into a silver or gold sedan and then subsequently been trying to leave their apartment complex can people that are innocent of a crime do not go and switch vehicles out in try to avoid police at all cost. A police officer in the Lebanon PD officer Hughes and absurd Dorado came to my front door with a shotgun pointed in my general direction I open the door slightly and told them that they had to go get the men that were trying to break into my home and assault me. general description and a description of the vehicle and where I thought they might be. Upon pulling the sedan over in talking to one of the two men who is clearly high on methamphetamine and whacked out of his mind you can see in the place where they can put in he tells the police officer his intent was to cause me physical bodily harm let me spend some crazy story about he was defending his friends girlfriends. In reality Phoebe knew that I had valuables in my house and they possibly had a little bit of cash stashed away. The police officer Dorado Inn helps himself back into my house does not announce himself does not knock hits me in the head with my own door apologizes upon hitting me in the head for just helping himself into my home no warrant no real reason to force his way into my home he would later state that he thought he had implied consent implied consent but at least it in choir or require a knock and announcement of your presents. To you then walks into Main Kitchen this whole time just helping himself and blatantly just trampling over my constitutional rights for illegal search and seizure but alone the right to just walk into some of these hoes he literally did the same thing that the two men that were there before trying to beat my door down did helped himself to my home without permission or consent by myself. He then states that unfortunately for me I have to fill out a voluntary statement form and that is not leaving my apartment until the voluntary statement form is filled out to his satisfaction. At this point I'm very nervous and wondering how he is just let himself into my home and it's not leaving it then continues to look around my home and search my home without my consent and or permissions to do anything inside my house as he did not have permission to come into my house keep in mind this is the gentleman that was holding a shotgun in my general direction moments before. At some point in time the officer that left to speak with me too criminal would be burglars. Comes back and coaxes me out of my apartment with a story about needing to be shown exactly what happened this is a way to get me a set of my apartment knowing that they had no right to arrest me and I had no intention on leaving my apartment. Its Saturday morning and I had just worked a 69 hour week Monday through Friday. Reluctantly I go up to the doorway and basically show them the footprints in the snow where the men went back and forth and I went back to my doorway several times. Officer Hughes then places me under arrest and puts me in the back of his Cruiser it does not allow me just grab my cell phone it does not allow me to lock my apartment up doesn't even allow me to get my keys to my apartment and my other belongings remember I am in my pajamas and my slippers. As I'm handcuffed in the back of the cruiser I expressly tell him that he needs to lock my apartment up because they were obviously going to come back and help themselves to my property if I was going to be arrested and detained for an extended. Of time. Episode Dorado and officer Hughes and the OIC officer-in-charge Sergeant Gifford oh failed to secure my apartment and my belongings. Subsequently I was held without bail for a period of eight months in which all of my belongings were stolen and my personal information was stolen. There were three to four people squatting in my apartment for a period of at least six months well with your landlord assumed I was just not paying my rent. I have been charged with 1 degree assault with a deadly weapon and criminal threatening falsifying physical evidence all three felony charges and I was subsequently charged with thoughts of lying to a police officer and breaking a bogus bail condition both class A misdemeanors. It is now end of February 2022 and I've still yet to resolve this case but I am not going to take a plea deal for x amount of years suspended over my head for good behavior probation was he good standing citizen in the community a hard-working individual who did nothing but went to work and went home and minded his own business in the matter of moments. Lebanon Police Department and come to find out one of their paid informed was a man that came to my House. Because of this Christmas Justice it was my job was my place to live past all of my belongings I lost my identity due to my personal information social security card birth certificate a photo ID home being stolen out of the apartment that the Lebanon Police Department failed to secure the scene of a so-called crime. New Hampshire has the stand-your-ground law doesn't matter from the supermarket or if I'm in my front yard or in my living room if people threaten my life and or my property I have the right to defend myself within any means. 
I have contacted both Senators for New Hampshire and they're showing express interest in this situation as it is a blatant violation of my constitutional rights and just when God given rights to maintain life liberty and the pursuit of happiness. My fifth grandfather removed was actually the signer of the Declaration of Independence for New Hampshire Matthew Thornton. What do you think my great-great-great-grandfather would think if he saw this and was able to witness this go on today you think this is what he had in mind when he said my piece of paper all those many years ago. 

Sent from ProtonMail mobile

**Comment by ragoboy** [comment]
> 1. Open Atom app
> 2. File menu > Open > select .html file
> 3. File does not open
> 4. Repeat steps 2-3
> 5. Force quit Atom
> 6. Locate file in Finder
> 7. Open file with > Atom
> 8. Atom opens file, with error
> 9. Submit issue!
> 
> **Atom**: 1.59.0 x64 **Electron**: 9.4.4 **OS**: macOS 12.2.1 **Thrown From**: Atom Core
> 
> ### Stack Trace
> Uncaught Error: dlopen(/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 0x0001): tried: '/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node' (no such file), '/usr/lib/keyboard-layout-manager.node' (no such file)
> 
> ```
> At electron/js2c/asar.js:140
> 
> Error: dlopen(/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 0x0001): tried: '/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node' (no such file), '/usr/lib/keyboard-layout-manager.node' (no such file)
>     at process.func [as dlopen] (electron/js2c/asar.js:140:31)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
>     at Object.func [as .node] (electron/js2c/asar.js:149:18)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
>     at Module._load (internal/modules/cjs/loader.js:727:14)
>     at Function.Module._load (electron/js2c/asar.js:769:28)
>     at Module.require (/app.asar/static/index.js:72:46)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at customRequire (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
>     at get_KeyboardLayoutManager (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:14:2872375)
>     at get_manager (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:14:2872477)
>     at Object.getCurrentKeyboardLayout (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:14:2872603)
>     at e.keystrokeForKeyboardEvent (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:14:1119692)
>     at KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:11:1225346)
>     at KeymapManager.handleKeyboardEvent (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:11:1223331)
>     at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:11:286651)
> ```
> 
> ### Commands
> ```
>      -0:12.5.0 core:select-all (input.hidden-input)
>      -0:12.5.0 core:save (input.hidden-input)
> ```
> 
> ### Non-Core Packages
> ```
> atom-beautify 0.33.4 
> atom-material-syntax 1.0.8 
> atom-material-ui 2.1.3 
> column-select 1.0.1 
> srt-syntax 0.0.0 
> tablr 1.8.3 
> web-accessibility-checker 0.1.4 
> ```

**Comment by ragoboy** [comment]
> > 1. Open Atom app
> > 2. File menu > Open > select .html file
> > 3. File does not open
> > 4. Repeat steps 2-3
> > 5. Force quit Atom
> > 6. Locate file in Finder
> > 7. Open file with > Atom
> > 8. Atom opens file, with error
> > 9. Submit issue!
> > 
> > **Atom**: 1.59.0 x64 **Electron**: 9.4.4 **OS**: macOS 12.2.1 **Thrown From**: Atom Core
> > ### Stack Trace
> > Uncaught Error: dlopen(/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 0x0001): tried: '/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node' (no such file), '/usr/lib/keyboard-layout-manager.node' (no such file)
> > ```
> > At electron/js2c/asar.js:140
> > 
> > Error: dlopen(/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 0x0001): tried: '/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node' (no such file), '/usr/lib/keyboard-layout-manager.node' (no such file)
> >     at process.func [as dlopen] (electron/js2c/asar.js:140:31)
> >     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
> >     at Object.func [as .node] (electron/js2c/asar.js:149:18)
> >     at Module.load (internal/modules/cjs/loader.js:815:32)
> >     at Module._load (internal/modules/cjs/loader.js:727:14)
> >     at Function.Module._load (electron/js2c/asar.js:769:28)
> >     at Module.require (/app.asar/static/index.js:72:46)
> >     at require (internal/modules/cjs/helpers.js:74:18)
> >     at customRequire (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
> >     at get_KeyboardLayoutManager (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:14:2872375)
> >     at get_manager (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:14:2872477)
> >     at Object.getCurrentKeyboardLayout (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:14:2872603)
> >     at e.keystrokeForKeyboardEvent (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:14:1119692)
> >     at KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:11:1225346)
> >     at KeymapManager.handleKeyboardEvent (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:11:1223331)
> >     at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/4m/jgt1xmds7c978cc_9wlw3s940000gn/T/com.github.atom.ShipIt.4Z9tJkPz/Atom.app/Contents/Resources/app/static/<embedded>:11:286651)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Commands
> > ```
> >      -0:12.5.0 core:select-all (input.hidden-input)
> >      -0:12.5.0 core:save (input.hidden-input)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Non-Core Packages
> > ```
> > atom-beautify 0.33.4 
> > atom-material-syntax 1.0.8 
> > atom-material-ui 2.1.3 
> > column-select 1.0.1 
> > srt-syntax 0.0.0 
> > tablr 1.8.3 
> > web-accessibility-checker 0.1.4 
> > ```
