### ISSUE TITLE
Find all > Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by mglikesbikes** [atom/atom#23691]
### Description

Project find doesn't work

### Steps to Reproduce

1. Cmd+Shift+F
2. Enter a search string
3. Press return

**Expected behavior:**

Project is searched

**Actual behavior:**

Error

### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: Unknown macOS version (12.2.1)
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:200

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:676:19)
    at Task.send (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:44024)
    at Task.start (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:43856)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:34231
    at new Promise (<anonymous>)
    at new DirectorySearch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:34168)
    at DefaultDirectorySearcher.search (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:34507)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:443908
    at Map.forEach (<anonymous>)
    at Workspace.scan (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:443440)
    at ResultsModel.search (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:787128)
    at ProjectFindView.search (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:778119)
    at async Promise.all (index 0)
```

### Commands

```
     -1:04.6.0 core:close (div.results-view.focusable-panel)
     -1:03.2.0 project-find:show (input.hidden-input)
     -1:02.5.0 core:confirm (input.hidden-input)
     -0:59.8.0 core:close (div.results-view.focusable-panel)
     -0:58.7.0 settings-view:open (input.hidden-input)
  2x -0:57.4.0 core:close (div.panels-item)
     -0:42 settings-view:open (input.hidden-input)
     -0:41.2.0 core:close (div.panels-item)
     -0:02.2.0 project-find:show (input.hidden-input)
     -0:01.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-wrap-in-tag 0.6.0 
autocomplete 0.47.0 
change-case 0.6.5 
clipboard-plus 0.5.1 
close-on-left 0.9.2 
close-other-tabs 0.1.2 
close-tags 0.6.0 
escape-utils 0.5.3 
import-sf-mono 1.0.1 
language-postcss 1.3.1 
project-manager 3.3.8 
react 0.18.0 
react-nextjs-snippets 0.2.0 
single-click-open 0.2.2 
sync-settings 5.2.15 
tailwindcss-autocomplete 0.10.1 
```

**Comment by mariale425** [comment]
Today I got this error

**Comment by RonnieOnRails** [comment]
+1, how to solve please ? 

Atom 1.58.0 (up-to-date)
macOS 12.2.1

**Comment by mariale425** [comment]
> +1, how to solve please ?
> 
> Atom 1.58.0 (up-to-date) macOS 12.2.1

I restarted my mac and this works again.
