### ISSUE TITLE
Find all > Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by joshuambg** [atom/atom#23769]
**Description**
Project find doesn't work

**Steps to Reproduce**

1. Cmd+Shift+F
2. Enter a search string
3. Press return

**Expected behavior:**

Project is searched

**Actual behavior:**

Error

Versions
Atom: 1.60.0 x64
Electron: 9.4.4
OS: Unknown macOS version (12.2.1)
Thrown From: Atom Core

**Stack Trace**
Uncaught Error: write EPIPE
```
At events.js:200

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:676:19)
    at Task.send (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:44024)
    at Task.start (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:43856)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:34231
    at new Promise (<anonymous>)
    at new DirectorySearch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:34168)
    at DefaultDirectorySearcher.search (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:34507)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:443908
    at Map.forEach (<anonymous>)
    at Workspace.scan (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:443440)
    at ResultsModel.search (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:787128)
    at ProjectFindView.search (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:778119)
    at async Promise.all (index 0)
```

**Commands**
```
     -1:04.6.0 core:close (div.results-view.focusable-panel)
     -1:03.2.0 project-find:show (input.hidden-input)
     -1:02.5.0 core:confirm (input.hidden-input)
     -0:59.8.0 core:close (div.results-view.focusable-panel)
     -0:58.7.0 settings-view:open (input.hidden-input)
  2x -0:57.4.0 core:close (div.panels-item)
     -0:42 settings-view:open (input.hidden-input)
     -0:41.2.0 core:close (div.panels-item)
     -0:02.2.0 project-find:show (input.hidden-input)
     -0:01.7.0 core:confirm (input.hidden-input)
```

**Comment by sdaviss** [comment]
Same issue doing Find in Project. Will try updating Atom version.

### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.6.2
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:200

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:676:19)
    at Task.send (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:44024)
    at Task.start (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:43856)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:34231
    at new Promise (<anonymous>)
    at new DirectorySearch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:34168)
    at DefaultDirectorySearcher.search (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:34507)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:443908
    at Map.forEach (<anonymous>)
    at Workspace.scan (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:443440)
    at ResultsModel.search (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:787128)
    at ProjectFindView.search (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:778119)
    at async Promise.all (index 0)
```

### Commands

```
     -2:31.3.0 project-find:show (div.tool-panel.tree-view)
     -2:21.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
kite 0.206.0 
nord-atom-ui 0.12.0 
```

### Additional Information
