### ISSUE TITLE
Uncaught Error: dlopen(~/Desktop/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keybo...

### ISSUE THREAD

**Issue by marcelafsantos29** [atom/atom#24790]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: macOS 12.0.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/Users/marcela.fsantos/Desktop/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 0x0001): tried: '/Users/marcela.fsantos/Desktop/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node' (no such file), '/usr/lib/keyboard-layout-manager.node' (no such file)

```
At electron/js2c/asar.js:140

Error: dlopen(/Users/marcela.fsantos/Desktop/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 0x0001): tried: '/Users/marcela.fsantos/Desktop/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node' (no such file), '/usr/lib/keyboard-layout-manager.node' (no such file)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/Users/marcela.fsantos/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at get_KeyboardLayoutManager (/Users/marcela.fsantos/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:2873999)
    at get_manager (/Users/marcela.fsantos/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:2874101)
    at Object.getCurrentKeyboardLayout (/Users/marcela.fsantos/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:2874227)
    at e.keystrokeForKeyboardEvent (/Users/marcela.fsantos/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:1121316)
    at KeymapManager.keystrokeForKeyboardEvent (/Users/marcela.fsantos/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:1225566)
    at KeymapManager.handleKeyboardEvent (/Users/marcela.fsantos/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:1223551)
    at WindowEventHandler.handleDocumentKeyEvent (/Users/marcela.fsantos/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:286682)
```

### Commands

```
     -0:14.6.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
