### ISSUE TITLE
Uncaught TypeError: Cannot read property 'textContent' of null

### ISSUE THREAD

**Issue by Egidius** [atom/atom#2537]
Since Atom.io 0.99 whenever I attempt to drag a folder to the editor, in stead of showing the neat little sidebar on the left my console opens with the following error:

```
Uncaught TypeError: Cannot read property 'textContent' of null

Uncaught TypeError: Cannot read property 'textContent' of null /Applications/Atom.app/Contents/Resources/app/src/lines-component.js:335
TypeError: Cannot read property 'textContent' of null
  at [object Object].module.exports.React.createClass.measureCharactersInLine (/Applications/Atom.app/Contents/Resources/app/src/lines-component.js:335:59)
  at [object Object].boundMethod [as measureCharactersInLine] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1434:21)
  at [object Object].module.exports.React.createClass.measureCharactersInNewLines (/Applications/Atom.app/Contents/Resources/app/src/lines-component.js:303:30)
  at [object Object].boundMethod [as measureCharactersInNewLines] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1434:21)
  at [object Object].module.exports.React.createClass.componentDidUpdate (/Applications/Atom.app/Contents/Resources/app/src/lines-component.js:87:21)
  at ReactMountReady.mixInto.notifyAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactMountReady.js:69:18)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:87:26)
  at ReactReconcileTransaction.Mixin.closeAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:242:42)
  at ReactReconcileTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:175:16)
  at [object Object].ReactComponent.Mixin.performUpdateIfNecessary (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactComponent.js:478:19)
  at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1157:51)
  at Object.enqueueUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:107:15)
  at [object Object].ReactCompositeComponentMixin.forceUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1379:18)
  at [object Object].module.exports.React.createClass.requestUpdate (/Applications/Atom.app/Contents/Resources/app/src/editor-component.js:226:21)
  at [object Object].boundMethod [as requestUpdate] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1434:21)
  at [object Object].module.exports.React.createClass.onBatchedUpdatesEnded (/Applications/Atom.app/Contents/Resources/app/src/editor-component.js:943:21)
  at boundMethod (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1434:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:133:30
  at Array.forEach (native)
  at Editor.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:132:47)
  at Editor.module.exports.Editor.batchUpdates (/Applications/Atom.app/Contents/Resources/app/src/editor.js:1922:14)
  at [object Object].module.exports.React.createClass.componentDidMount (/Applications/Atom.app/Contents/Resources/app/src/editor-component.js:195:21)
  at ReactMountReady.mixInto.notifyAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactMountReady.js:69:18)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:87:26)
  at ReactReconcileTransaction.Mixin.closeAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:242:42)
  at ReactReconcileTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:175:16)
  at [object Object].ReactComponent.Mixin.mountComponentIntoNode (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactComponent.js:537:19)
  at Object._renderNewRootComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactMount.js:309:25)
  at Object.ReactMount.renderComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactMount.js:359:32)
  at ReactEditorView.module.exports.ReactEditorView.afterAttach (/Applications/Atom.app/Contents/Resources/app/src/react-editor-view.js:93:30)
  at callAttachHook (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:343:107)
  at [object Object].jQuery.fn.(anonymous function) [as append] (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:359:9)
  at Atom.module.exports.Atom.deserializeWorkspaceView (/Applications/Atom.app/Contents/Resources/app/src/atom.js:312:50)
  at Atom.module.exports.Atom.deserializeEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:324:19)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:348:12)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:14:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:20:4)
  at Module._compile (module.js:455:26)
  at Object.Module._extensions..js (module.js:473:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:363:17)
  at require (module.js:379:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:20:5)
 index.js:29
Uncaught TypeError: Cannot read property 'textContent' of null /Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactMountReady.js:69
```

I tried to run a clean atom.app without any luck. Is this bug known? Couldn't find anyone else having these kind of problems yet.

I'm running OSX 10.9.3 with node v0.10.28

**Comment by marcandrebenoit** [comment]
i have this issue in v0.182.0 in windows 7 64bit after mistakenly opening an xlsx file into atom ..

**Comment by benogle** [comment]
@marcandrebenoit can you open a new issue?

**Comment by sivalingams** [comment]
I'm having this issue on Version 0.192.0 (0.192.0) on mac OS X yosemite

TypeError: Cannot read property 'textContent' of null
  at LinesComponent.module.exports.LinesComponent.measureCharactersInLine (/Applications/Atom.app/Contents/Resources/app/src/lines-component.js:396:59)
  at /Applications/Atom.app/Contents/Resources/app/src/lines-component.js:353:21
  at DisplayBuffer.module.exports.DisplayBuffer.batchCharacterMeasurement (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:552:7)
  at TextEditor.module.exports.TextEditor.batchCharacterMeasurement (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2672:33)
  at TextEditorPresenter.module.exports.TextEditorPresenter.batchCharacterMeasurement (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:1039:18)
  at LinesComponent.module.exports.LinesComponent.measureCharactersInNewLines (/Applications/Atom.app/Contents/Resources/app/src/lines-component.js:345:29)
  at TextEditorComponent.module.exports.TextEditorComponent.readAfterUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:3:61
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:167:9)
  at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:61

**Comment by levythu** [comment]
encountered in v0.209.0, while I was opening a .pptx file by mistake.

**Comment by dareTake** [comment]
Same issue with v0.210.0 on OSX Yosemite.

Stack Trace: 
/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/tile-component.js:440
Hide Stack Trace
TypeError: Cannot read property 'textContent' of null
    at TileComponent.module.exports.TileComponent.measureCharactersInLine (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/tile-component.js:440:59)
    at TileComponent.module.exports.TileComponent.measureCharactersInNewLines (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/tile-component.js:398:16)
    at /Applications/Dev/Atom.app/Contents/Resources/app.asar/src/lines-component.js:157:23
    at DisplayBuffer.module.exports.DisplayBuffer.batchCharacterMeasurement (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:572:7)
    at TextEditor.module.exports.TextEditor.batchCharacterMeasurement (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2718:33)
    at TextEditorPresenter.module.exports.TextEditorPresenter.batchCharacterMeasurement (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1301:18)
    at LinesComponent.module.exports.LinesComponent.measureCharactersInNewLines (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/lines-component.js:151:29)
    at TextEditorComponent.module.exports.TextEditorComponent.readAfterUpdateSync (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:246:29)
    at /Applications/Dev/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/view-registry.js:172:9)

**Comment by as-cii** [comment]
I am trying to reproduce it on some random `.pptx` or `.mp4` file but Atom seems to handle everything correctly. 

@levythu @dareTake: would you be willing to share one of those problematic files so that I can have a better look at this problem? You can either post them here or send them to my e-mail address (which you can find on my GitHub profile page). If you don’t want to share them, it is totally okay, so thank you anyway for taking the time to report the issue. :pray:

**Comment by levythu** [comment]
@as-cii  I would like to but the computer where the issue was encountered is not here, nor is the file. Just now I tried to reproduce another one on my PC but failed. So sorry.

**Comment by dareTake** [comment]
@as-cii : I tried it again on the 1.0 release, it does not seem to bug out. I think this issue has been resolved on the new version, perhaps related to some other bug fixing ?

**Comment by dvy** [comment]
I tried to open a .docx file on the 1.0.4 release. Got "Uncaught TypeError: Cannot read property 'textContent' of null" errors. Running on Windows 7.

**Comment by as-cii** [comment]
Hey @dvy, thank you for reporting this problem!

Are you able to reproduce this problem consistently? If yes, could you attach the file (or a minimal version of it) here or send an email to my personal address so that I can have a look at fix the problem? Your help would be super appreciated! ⚡️

**Comment by dvy** [comment]
Hey @as-cii!  Emailed you a file that causes an error.

**Comment by as-cii** [comment]
> Emailed you a file that causes an error.

@dvy: thanks a lot! :sparkles: :sparkles: :sparkles: I will have a look later this week. :mag_right:

**Comment by as-cii** [comment]
@dvy: I am not able to see it fail on Atom `1.0.6` (Mac OS X Yosemite). Some quick questions:

* Could you confirm the error gets raised consistently with the file you sent me? 
* Does it happen when you perform a particular action or only while opening the file?
* Are you opening the file in a particular way? e.g. drag and drop, `File -> Open File...`, via tree-view

Thanks a lot for your support on this! :bow:

**Comment by dvy** [comment]
@as-cii Hi! I still have this error with the file I sent you in Atom 1.0.6 on Windows 7 x64. Just opened it with `Right click -> Open with Atom`.

**Comment by as-cii** [comment]
@dvy: ok, thank you for sharing these insights! I am suspecting this issue could be related to the platform, somehow: I'll setup a Windows virtual machine and check if I can spot any error in there.

**Comment by as-cii** [comment]
Okay, it seems like I managed to reproduce this exact problem on Yosemite. It consistently reproduces with the file you sent me, so I'll take a look at the root of the issue right away.

Thanks @dvy! :sparkles:

**Comment by m-aciek** [comment]
I've just encountered this:

1. Opened DOCX with Atom.

**Atom Version**: 1.0.7
**System**: Ubuntu 14.04.4
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'textContent' of null

```
At /usr/share/atom/resources/app.asar/src/lines-tile-component.js:445

TypeError: Cannot read property 'textContent' of null
    at LinesTileComponent.module.exports.LinesTileComponent.measureCharactersInLine (/usr/share/atom/resources/app.asar/src/lines-tile-component.js:445:40)
    at LinesTileComponent.module.exports.LinesTileComponent.measureCharactersInNewLines (/usr/share/atom/resources/app.asar/src/lines-tile-component.js:403:16)
    at /usr/share/atom/resources/app.asar/src/lines-component.js:134:23
    at DisplayBuffer.module.exports.DisplayBuffer.batchCharacterMeasurement (/usr/share/atom/resources/app.asar/src/display-buffer.js:574:7)
    at TextEditor.module.exports.TextEditor.batchCharacterMeasurement (/usr/share/atom/resources/app.asar/src/text-editor.js:2759:33)
    at TextEditorPresenter.module.exports.TextEditorPresenter.batchCharacterMeasurement (/usr/share/atom/resources/app.asar/src/text-editor-presenter.js:1292:18)
    at LinesComponent.module.exports.LinesComponent.measureCharactersInNewLines (/usr/share/atom/resources/app.asar/src/lines-component.js:128:29)
    at TextEditorComponent.module.exports.TextEditorComponent.readAfterUpdateSync (/usr/share/atom/resources/app.asar/src/text-editor-component.js:246:29)
    at /usr/share/atom/resources/app.asar/src/text-editor-component.js:3:61
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app.asar/src/view-registry.js:176:9)
```

### Commands

```
  4x -9:29.2.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -9:28.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -9:24.9.0 core:save (atom-text-editor.editor.is-focused)
     -4:10.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:01.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:56.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 13x -3:26.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:59.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:56.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:49.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/maciek/workspace",
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {},
    "softTabs": false,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-django, v0.3.2
livereload, v0.4.4
minimap, v4.19.0
svn, v0.0.9

# Dev
No dev packages
```

**Comment by nathansobo** [comment]
@m-aciek You're on a pretty old version. You should upgrade.
