### ISSUE TITLE
Potential conflict between new frameworks and packages extending atom-ide

### ISSUE THREAD

**Issue by ray-rock** [atom/atom#25398]
OS: Arch Linux
Version: v1.61.0-beta0

Hi, I believe i've found a potential issue with the new frameworks implemented in atom v1.61.0-beta0. The packages mentioned [here](https://github.com/atom-community/ide-python/issues/483#issuecomment-1098805108) fail to load, and each return the same error:

```
call.getFileName is not a function
```

This is my first time attempting to debug an issue like this, but an educated guess from taking a look at the stack traces tells me that this is an issue with atom, or electron. Perhaps a node dependency? Unfortunately, i've hit a wall attempting to fix the problem myself. So i'm opening the issue here in hopes that someone more experienced could see this and provide insight. 

Please close this issue and accept my apologies if it turns out to be irrelevant.

**Comment by ray-rock** [comment]
# A copy of the link above, for posterity

I'm on Arch Linux, latest updates as time of posting. running Atom v1.61.0-beta0. I'm encountering the same issue across three installed packages: 

---

- https://github.com/atom-community/ide-python
 <details>
 <summary>stack trace:</summary>

 ```
ide-python
TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:278:25)
    at innerOk (assert.js:372:17)
    at ok (assert.js:392:3)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:45:21)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:305:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/ray/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:16:17)
    at Object.<anonymous> (/home/ray/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/ray/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:14:62)
    at Object.<anonymous> (/home/ray/.atom/packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
```

</details>

---

- https://github.com/atom-community/atom-ide-javascript
- (see https://github.com/atom-community/atom-ide-javascript/issues/45 for more)

<details>
<summary>stack trace</summary>

```
atom-ide-javascript
TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:278:25)
    at innerOk (assert.js:372:17)
    at ok (assert.js:392:3)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:45:21)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:305:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:16:17)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:14:62)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
```

</details>

---

- https://github.com/atom-community/atom-ide-debugger

<details>
<summary>stack trace</summary>

```
atom-ide-debugger
TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:278:25)
    at innerOk (assert.js:372:17)
    at ok (assert.js:392:3)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:45:21)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:305:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/dist/ui/DebuggerLaunchAttachUI.js:18:17)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/dist/ui/DebuggerLaunchAttachUI.js:262:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/dist/main.js:52:54)
    at Object.<anonymous> (/home/ray/.atom/packages/atom-ide-debugger/dist/main.js:930:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:67:27)
```


</details>



# My Conclusion
I ran into a few walls attempting to debug this because i'm not exactly a pro. I think this problem is an issue with atom and not the packages themselves.
