### ISSUE TITLE
apm package installs are failing... server code 500.

### ISSUE THREAD

**Issue by ladar** [atom/atom#25417]
Atom package installs have started failing. The server doesn't appear to be redirecting clients to a download tarball. The issue is easy to see using the `apm` CLI tool. 

I've created a bug report here: https://github.com/atom/apm/issues/946

Opening this issue to redirect users looking to report this problem, or add new information to the issue in the `apm` repo, since that seems like the more appropriate place.

**Comment by victor4pro** [comment]
Hello, I'm having the same issue. Working on Macbook pro m1. I'm trying to install any package or any theme and getting the same error. 

```
19 error code E500
20 error 500 Internal Server Error - GET https://www.atom.io/api/packages/teletype/versions/0.13.4/tarball
```

Working with:
```
apm  2.6.2
npm  6.14.13
node 12.14.1 x64
atom 1.60.0
python 
git 2.30.1
```

**Comment by alisondsgn** [comment]
Eu não estou conseguindo instalar o pack emmet, alguém me ajuda.

**Comment by marti-toonen** [comment]
Experiencing the same issue with a totally fresh install. I was experimenting with using Atom as a very bare bones word processor, so I have a totally default set up aside from some rudimentary settings adjustments (I initially thought the problem stemmed from missing something tbh). Same error as well, wasn't able to install anything I tried, but was trying to download language-markdown in particular (did branch out to see if it was only an error with particular files). Didn't work from the command window or from the install tab within Atom.

**Comment by hand-accident** [comment]
same error here on windows 10.

**Comment by zeref-dragneel** [comment]
Installing “atom-beautify@0.33.4” failed.
```

npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://www.atom.io/api/packages/atom-beautify/versions/0.33.4/tarball

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Zeref\.atom\.apm\_logs\2022-04-19T05_44_07_125Z-debug.log

```

**Comment by kslim1025** [comment]
캐시 때문에 일어나는 문제 같네요.
npm config get cache

npm cache clean --force

**Comment by TempoDiValse** [comment]
모든 패키지 설치 및 업데이트가 되지 않는 것을 보니 Atom 패키지 관리하는 서버에 문제가 생긴 것 같아보입니다

**Comment by nelson6e65** [comment]
It's not cache. In web browser the link gives 500: https://www.atom.io/api/packages/ide-typescript/versions/0.9.5/tarball

**Comment by aco319sig** [comment]
Installing “make-executable@1.0.0” failed.[Hide output…]()

npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://www.atom.io/api/packages/make-executable/versions/1.0.0/tarball

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jcopleyx\.atom\.apm\_logs\2022-04-19T16_43_31_077Z-debug.log


debug log:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Users\\jcopleyx\\AppData\\Local\\atom\\app-1.60.0\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\jcopleyx\\AppData\\Local\\atom\\app-1.60.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\jcopleyx\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\jcopleyx\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/make-executable/versions/1.0.0/tarball',
1 verbose cli   '--target=9.4.4',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v12.14.1
4 verbose npm-session 998147319e0ccc88
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 500 https://www.atom.io/api/packages/make-executable/versions/1.0.0/tarball 73293ms attempt #3
8 silly fetchPackageMetaData error for https://www.atom.io/api/packages/make-executable/versions/1.0.0/tarball 500 Internal Server Error - GET https://www.atom.io/api/packages/make-executable/versions/1.0.0/tarball
9 timing stage:rollbackFailedOptional Completed in 4ms
10 timing stage:runTopLevelLifecycles Completed in 73365ms
11 verbose stack Error: 500 Internal Server Error - GET https://www.atom.io/api/packages/make-executable/versions/1.0.0/tarball
11 verbose stack     at C:\Users\jcopleyx\AppData\Local\atom\app-1.60.0\resources\app\apm\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:117:15
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:94:5)
12 verbose statusCode 500
13 verbose pkgid https://www.atom.io/api/packages/make-executable/versions/1.0.0/tarball
14 verbose cwd C:\Users\jcopleyx\AppData\Local\Temp\apm-install-dir-2022319-17424-1ttoa8d.w7l
15 verbose Windows_NT 10.0.19044
16 verbose argv "C:\\Users\\jcopleyx\\AppData\\Local\\atom\\app-1.60.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\jcopleyx\\AppData\\Local\\atom\\app-1.60.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\jcopleyx\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\jcopleyx\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/make-executable/versions/1.0.0/tarball" "--target=9.4.4" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
17 verbose node v12.14.1
18 verbose npm  v6.14.13
19 error code E500
20 error 500 Internal Server Error - GET https://www.atom.io/api/packages/make-executable/versions/1.0.0/tarball
21 verbose exit [ 1, true ]

**Comment by DrBecky22** [comment]
Same issue - thank goodness it is not me.  I'm a brand-new-newbie and assumed I was doing something wrong...

**Comment by osimers1** [comment]
apparemment je suis pas le seul et le problème a l'air récent, surement leur serveur a eu qui a un problème :shrug:

**Comment by JamesThePaladin** [comment]
I am having this same issue, logs below:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/share/atom/resources/app/apm/bin/node',
1 verbose cli   '/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/home/itcoordinator/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/home/itcoordinator/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/vaporwave-ui/versions/0.0.2/tarball',
1 verbose cli   '--target=9.4.4',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v12.14.1
4 verbose npm-session 30cc9163d075c246
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 500 https://www.atom.io/api/packages/vaporwave-ui/versions/0.0.2/tarball 76103ms attempt #3
8 silly fetchPackageMetaData error for https://www.atom.io/api/packages/vaporwave-ui/versions/0.0.2/tarball 500 Internal Server Error - GET https://www.atom.io/api/packages/vaporwave-ui/versions/0.0.2/tarball
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 76130ms
11 verbose stack Error: 500 Internal Server Error - GET https://www.atom.io/api/packages/vaporwave-ui/versions/0.0.2/tarball
11 verbose stack     at /usr/share/atom/resources/app/apm/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:117:15
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:94:5)
12 verbose statusCode 500
13 verbose pkgid https://www.atom.io/api/packages/vaporwave-ui/versions/0.0.2/tarball
14 verbose cwd /tmp/apm-install-dir-2022319-55892-1sts9z3.yxn9
15 verbose Linux 5.4.0-91-generic
16 verbose argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/itcoordinator/.atom/.apm/.apmrc" "--userconfig" "/home/itcoordinator/.atom/.apmrc" "install" "https://www.atom.io/api/packages/vaporwave-ui/versions/0.0.2/tarball" "--target=9.4.4" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
17 verbose node v12.14.1
18 verbose npm  v6.14.13
19 error code E500
20 error 500 Internal Server Error - GET https://www.atom.io/api/packages/vaporwave-ui/versions/0.0.2/tarball
21 verbose exit [ 1, true ]

**Comment by saqib-ali** [comment]
same issue here.

**Comment by eylau-ucsd** [comment]
same issue here, when I run `apm install ide-haskell` I get the following error:

```
Installing ide-haskell to /home/eugenelau/.atom/packages ✗

npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://www.atom.io/api/packages/ide-haskell/versions/2.7.0/tarball

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eugenelau/.atom/.apm/_logs/2022-04-19T18_24_00_571Z-debug.log

```

**Comment by felipecrubio** [comment]
yes, same here when running **apm i auto-semicolon**:

> $ apm i auto-semicolon
> Installing auto-semicolon to C:\Users\felip\.atom\packages failed
> npm ERR! code E500
> npm ERR! 500 Internal Server Error - GET https://www.atom.io/api/packages/auto-semicolon/versions/1.1.0/tarball
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\felip\.atom\.apm\_logs\2022-04-19T22_23_14_217Z-debug.log

**Comment by albertomarcano** [comment]
Same issue here...

Installing “atom-ternjs@0.20.0” failed.
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://www.atom.io/api/packages/atom-ternjs/versions/0.20.0/tarball

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alberto\.atom\.apm\_logs\2022-04-19T22_38_43_319Z-d

**Comment by eylau-ucsd** [comment]
Has there been any response from the ppl running the servers? I believe the servers have been down for almost a day.

**Comment by Miiixay** [comment]
Same here 
```
Installing ide-python to C:\Users\jerem\.atom\packages failed

npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://www.atom.io/api/packages/ide-python/versions/1.9.7/tarball

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jerem\.atom\.apm\_logs\2022-04-19T22_51_25_014Z-debug.log
```

**Comment by murilosaut** [comment]
It's the second day I've been struggling with that.

**Comment by carldsmith** [comment]
> Same issue - thank goodness it is not me. I'm a brand-new-newbie and assumed I was doing something wrong...

Same here, I was just setting it up for first use and was like now what did I do?!

**Comment by EB-coder** [comment]
I have same issue, i don't know what to do

**Comment by EdoLom** [comment]
Same here. Impossible to install the script package:
500 Internal Server Error - GET https://www.atom.io/api/packages/script/versions/3.32.2/tarball

**Comment by lerbal7** [comment]
I am having the same issue. I thought I was doing something wrong, but I noticed it's not me and it's even a recent issue.

**Comment by abnormal749** [comment]
I have same error on mac Monterey.
Using command: apm update
Then get:
Request for package information failed: <html>
    <head>
        <title> Server Error </title>
    </head>
    <body>
        <font color =\"#aa0000\">
            <h2>Server Error.</h2>
        </font>
        There was an unexpected error in the request processing.
    </body>
</html>

**Comment by radim10** [comment]
If you remove the /tarball part of the URL, you get no error.

**Comment by ovmonk** [comment]
I have the same issue....

**Comment by TheLuiZaina** [comment]
Same issue here. Tried every OS and install option

**Comment by Marius0817** [comment]
Same issue here. Server seems to be available, package details are loading but the link to the tarball is broken.

**Comment by mferrodo** [comment]
I'm having the same exact problems with the R installation I was doing on Atom. Glad it's not me but mad there is nothing I can do for now

**Comment by SanjuSoni** [comment]
Dear All

I have a similar error while installing a package: 

The error message is:-
```

Installing “language-freefem-official@0.3.0” failed.[Hide output…]()

npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://www.atom.io/api/packages/language-freefem-official/versions/0.3.0/tarball

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\suman\.atom\.apm\_logs\2022-04-20T09_16_16_903Z-debug.log
```

How to fix it?

**Comment by meacodes** [comment]
same here in POP OS 21..10

`
<font color="#CC0000">npm ERR! 500 Internal Server Error - GET https://www.atom.io/api/packages/atom-beautify/versions/0.33.4/tarball</font>

<font color="#CC0000">npm ERR! A complete log of this run can be found in:</font>
<font color="#CC0000">npm ERR!     /root/.atom/.apm/_logs/2022-04-20T10_21_14_055Z-debug.log</font>
</pre>`

**Comment by mjmar01** [comment]
Possible solution. Install using git repo if available like:
`apm install mechatroner/atom-rainbow-csv`

**Comment by SunilSKamath4s** [comment]
> apm install mechatroner/atom-rainbow-csv

This works Thanks

**Comment by Benji377** [comment]
Could it be that the whole https://atom.io/ server is down? I don't seem to be able to reach the Website or ping it.

**Comment by ladar** [comment]
@Benji377 the website still works for me. And the DNF/APT repos appear to be working, based on my CI results.

**Comment by Benji377** [comment]
@ladar Pinging doesn't work for me:

![Screenshot 2022-04-20 141131](https://user-images.githubusercontent.com/50681275/164227803-bc1f32ee-3332-465b-a4e0-a6874cc31429.png)

**Comment by felipecrubio** [comment]
> Possible solution. Install using git repo if available like: `apm install mechatroner/atom-rainbow-csv

Still no luck..
> $ apm install bdougherty/auto-semicolon
> Cloning https://github.com/bdougherty/auto-semicolon.git failed
> Cloning git+ssh://git@github.com/bdougherty/auto-semicolon.git failed
> Couldn't clone https://github.com/bdougherty/auto-semicolon.git or git+ssh://git@github.com/bdougherty/auto-semicolon.git

**Comment by sebisebman** [comment]
Same here. No Ping. No 'apm install...' Nothing...

**Comment by mjmar01** [comment]
@felipecrubio That might have been a typo on your end. Try: `apm install bdougherty/atom-auto-semicolon` :)

**Comment by Marius0817** [comment]
apm install not working for me :/ 
![grafik](https://user-images.githubusercontent.com/51262799/164233142-2cfe6c05-e177-4777-8aa6-ef2002c2a04e.png)

**Comment by mjmar01** [comment]
In that case I'm betting it's a windows error. I can't complain:
```
apm install bdougherty/atom-auto-semicolon
Cloning https://github.com/bdougherty/atom-auto-semicolon.git ✓
Installing modules ✓
Moving auto-semicolon to /home/<user>/.atom/packages/auto-semicolon ✓
```
Pop!_OS 21.04
Also it says cloning failed. Maybe your git is just borked. Does it even work to clone the repo manually for you?

**Comment by Marius0817** [comment]
You were right @mjmar01, seems to have been a git problem. Working after reinstall of git

> C:\Users\mariu\GitLibrary>apm install  jesseweed/seti-ui
> Cloning https://github.com/jesseweed/seti-ui.git done
> Installing modules done
> Moving seti-ui to C:\Users\mariu\.atom\packages\seti-ui done

**Comment by GunterJr** [comment]
I have also noticed that trying to access a profile from the built in package manager will crash Atom.

**Comment by SanjuSoni** [comment]
It has been fixed now automatically. Try again with the conventional steps.

It Might be a server issue.

**Comment by ladar** [comment]
@SanjuSoni I concur. The issue appears to have been fixed.

```bash
vagrant@debian-build:~$ apm install sort-lines
Installing sort-lines to /home/vagrant/.atom/packages ✓
vagrant@debian-build:~$ apm install open-recent
Installing open-recent to /home/vagrant/.atom/packages ✓
vagrant@debian-build:~$ apm install atom-beautify
Installing atom-beautify to /home/vagrant/.atom/packages ✓    
vagrant@debian-build:~$ apm install language-cmake
Installing language-cmake to /home/vagrant/.atom/packages ✓
vagrant@debian-build:~$ apm install language-groovy
Installing language-groovy to /home/vagrant/.atom/packages ✓
vagrant@debian-build:~$ apm install language-gradle
Installing language-gradle to /home/vagrant/.atom/packages ✓
vagrant@debian-build:~$ apm install language-kotlin
Installing language-kotlin to /home/vagrant/.atom/packages ✓
vagrant@debian-build:~$ apm install language-openvpn
Installing language-openvpn to /home/vagrant/.atom/packages ✓
```

**Comment by Izzy-L** [comment]
> Possible solution. Install using git repo if available like: `apm install mechatroner/atom-rainbow-csv`

Thank you for your help!

`apm install atom-html-preview` gave me 
`npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://www.atom.io/api/packages/atom-html-preview/versions/0.2.7/tarball` 

but running `apm install harmsk/atom-html-preview ` worked!

**Comment by gronk-droid** [comment]
this is not fixed!!!! still happening.

**Comment by nelson6e65** [comment]
https://status.atom.io is not updated, because this is a server error. That status page should be active for this kind of issues.

**Comment by tomk-** [comment]
Besides of using a git repo, was this fixed so the built-in package manager works properly? (apparently, not yet)

**Comment by sardaslar** [comment]
have the same probnlem. Hope they will fix the servers soon

**Comment by joshdatraveler** [comment]
down here also. i thought i was doing something wrong, but it seems its a recurring thing

**Comment by Leezarius** [comment]
Same problem

**Comment by Bruguera-cbcat** [comment]
Same here

**Comment by TimiWho** [comment]
Same problem
Windows10
apm  2.6.2
npm  6.14.13
node 12.14.1 x64
atom 1.60.0
python 3.7.2
git
visual studio

**Comment by nosuke86** [comment]
Having the same error by attempting to install the split-diff package.

Installing “split-diff@1.6.1” failed.Hide output…

npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://www.atom.io/api/packages/split-diff/versions/1.6.1/tarball

**Comment by Kizustan** [comment]
Same error for trying to download a debugging plugin, does anyone have a solution or something else I should try? every debugger ive tried to download fails from outside of atom and inside I get the same 500 int server error

**Comment by filinvadim** [comment]
`apm install language-rust`
Same error...

**Comment by mjmar01** [comment]
Repeating myself since it seems to have been gone under a  bit. You can directly install from github using apm. So in @filinvadim's case try: `apm install zargony/atom-language-rust`

**Comment by McBean29** [comment]
Still having the same issue, regardless if I install in Atom or via command line

**Comment by ivan006** [comment]
As atoms api is down millions in gdp is lost  :'( xD

**Comment by ivan006** [comment]
Why is this topic closed?

**Comment by mjmar01** [comment]
@McBean29 what package are you trying to install and what command are you using. If you install using github you can't get the same issue. The original issue is a code 500 from the atom.io api. This api is not in use when installing from github...

You might be experiencing a different issue

**Comment by McBean29** [comment]
I’m trying to install code time. On the command line I’m getting a cloning failure

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mjmar01** [comment]
If you are getting a cloning failure check if you can clone the repo manually using git cli. You might be experiencing a similar issue like this user here where git just might be borked: https://github.com/atom/atom/issues/25417#issuecomment-1103922788

Installing via GitHub is working for me with that package: [Code Time](https://github.com/swdotcom/swdc-atom) `apm install swdotcom/swdc-atom`

**Comment by Moreless91** [comment]
Getting 500 internal error this morning when installing packages

**Comment by rafal-pracht** [comment]
I've this issue now, when I try to install uber-juno

**Comment by apandeycars** [comment]
Still getting the same error!

**Comment by clpacheco90** [comment]
Apparently all packages are unavailable.
Please reopen this topic

**Comment by AaronPenders** [comment]
When trying to circumvent the problem of installing pacakges using the alternative command window or atom package manager (apm), e.g.:

`apm install <atom-community>/<atom-script>`

or in my case: 
`apm install packages/pdf-view`

The command window expresses:
> Cloning https://github.com/packages/pdf-view.git

At the same time I get a pop-up to login to my github account. Inserting the username and password adds to the command line:

> Cloning https://github.com/packages/pdf-view.git Username for 'https://github.com':

after which it broke. 

I do not have the ability to directly type my username and password in the command line. Please suggest alternative solution!

**Comment by raziraz** [comment]
Same issue here. Really frustrating..

**Comment by mysrsk** [comment]
I am facing the same issue, my instructor is using Atom in her class. It's become very difficult to practice.

**Comment by dbrookeUAB** [comment]
> Repeating myself since it seems to have been gone under a bit. You can directly install from github using apm. So in @filinvadim's case try: `apm install zargony/atom-language-rust`

To emphasize @filinvadim, install the apps directly in the terminal using `apm`. 

For example, I want to install [Hydrogen](https://atom.io/packages/Hydrogen). To do so, I need to get the original GitHub repo for the package. You can get it directly from atom.... 
![atom-package](https://user-images.githubusercontent.com/7574868/165146316-cc77f11d-0964-430d-b8e1-29229b147eb8.jpg)

or from GitHub.

![github](https://user-images.githubusercontent.com/7574868/165148537-45c34dc3-e603-407b-b441-4dd7b7d90f2b.jpg)


Then, simply install with `apm install GITHUB-USERNAME/PACKAGE`.

```zsh
user@computer ~ %  apm install nteract/Hydrogen
 apm install nteract/Hydrogen
Cloning https://github.com/nteract/Hydrogen.git ✓
Installing modules ✓
Moving Hydrogen to /Users/user/.atom/packages/Hydrogen ✓
user@computer ~ %
```

Presto!

**Comment by Naddox** [comment]
I am getting this error when trying to install with apm.
![image](https://user-images.githubusercontent.com/845312/165154412-2d203569-be43-45ff-9a05-7998e0c04231.png)

I have done a fresh install of both Atom and Github Desktop and still get error. Tried with both Cmd Prompt and PowerShell ran as Admin and as User.

**Comment by mysrsk** [comment]
> > Repeating myself since it seems to have been gone under a bit. You can directly install from github using apm. So in @filinvadim's case try: `apm install zargony/atom-language-rust`
> 
> To emphasize @filinvadim, install the apps directly in the terminal using `apm`.
> 
> For example, I want to install [Hydrogen](https://atom.io/packages/Hydrogen). To do so, I need to get the original GitHub repo for the package. You can get it directly from atom.... ![atom-package](https://user-images.githubusercontent.com/7574868/165146316-cc77f11d-0964-430d-b8e1-29229b147eb8.jpg)
> 
> or from GitHub.
> 
> ![github](https://user-images.githubusercontent.com/7574868/165148537-45c34dc3-e603-407b-b441-4dd7b7d90f2b.jpg)
> 
> Then, simply install with `apm install GITHUB-USERNAME/PACKAGE`.
> 
> ```shell
> user@computer ~ %  apm install nteract/Hydrogen
>  apm install nteract/Hydrogen
> Cloning https://github.com/nteract/Hydrogen.git ✓
> Installing modules ✓
> Moving Hydrogen to /Users/user/.atom/packages/Hydrogen ✓
> user@computer ~ %
> ```
> 
> Presto!

Thanks, it really works for me! but I also installed a fresh copy of Atom.

**Comment by ivan006** [comment]
ok today things seem to work but u never know when this issue might occur again

**Comment by ladar** [comment]
Reopening since it still seems to be an issue for some, if you see this, please post a comment with working/not working as appropriate. And if your on *nix, it be helpful to post the output from `dig +short www.atom.io ; dig +short atom.io` so as well, so people can see which server you're accessing. For those hitting a still broken server, you might be able to redirect your installs using a hosts file.

```bash
# apm install sort-lines
Installing sort-lines to /home/ladar/.atom/packages ✓
# dig +short www.atom.io ; dig +short atom.io
atom-io.azurewebsites.net.
waws-prod-blu-323.sip.azurewebsites.windows.net.
waws-prod-blu-323-1104.eastus.cloudapp.azure.com.
20.119.16.4
20.119.16.4
```

**Comment by victor4pro** [comment]
> Hello, I'm having the same issue. Working on Macbook pro m1. I'm trying to install any package or any theme and getting the same error.
> 
> ```
> 19 error code E500
> 20 error 500 Internal Server Error - GET https://www.atom.io/api/packages/teletype/versions/0.13.4/tarball
> ```
> 
> Working with:
> 
> ```
> apm  2.6.2
> npm  6.14.13
> node 12.14.1 x64
> atom 1.60.0
> python 
> git 2.30.1
> ```

It is working now on my mac, I installed some packages without issues. But packages like linter or python-linter are not working, they aren't showing errors.

**Comment by DG12** [comment]
Web server admin: I would suggest you create an interesting 
500.cgi  
page

Something better than:

```
#!/bin/bash
export TZ=US/Eastern
echo Content-type: text/html
echo
  cat << +++++
<!doctype html>
<html>
<head><title> We're offline right now. </title>
<meta http-equiv="Cache-Control" content="no-cache"> <meta http-equiv="Pragma"        content="no-cache">
<meta http-equiv=Expire          content=now>
</head>
<body bgcolor=pink style=margin:0;> <center>
<small>
<form name=loger     method=POST
  action="http://www.atom.io/500-submit.cgi" >
<!-- putting the info in a text area allows cellphone to  edit it for easy scrolling. -->

<textarea name=tr1  cols=120  rows=3  border=0
  style=font-size:120%;margin:0px;padding:5px;border-color:red;border-style:dashed;font-family:monospace>

               Gosh, I hate when this happens!!


      Either the program is not accessible at this time or has failed.(  500 )

Maybe there is for output before the  content-type: text/html
+++++
echo '++++++++++ '         >> 500.log
date +"%m/%d %H:%M:%S %Z"
date +"%m/%d %H:%M:%S %Z"  >> 500.log
echo $REMOTE_ADDR          >> 500.log
echo   "++++ \$HTTP_REFERER: $HTTP_REFERER "
echo   "++++ \$HTTP_REFERER: $HTTP_REFERER should be a file, instead " >> 500.log
export HTTP_REFERER=`echo $HTTP_REFERER |sed "s/www\.//i"`
export daFILE=`echo $HTTP_REFERER |sed "s/http:\/\/.*\///i"`
file $daFILE
file $daFILE >> 500.logif [ $MODE != 'r-x' ] ; then echo "^^^ mode chould be r-x.  chmod 775 .$daFILE" ;fi

echo " +++++ head $daFILE +++++++++++++++++++++++++++++++++++"
head  $daFILE
## I know this is not the best but
export PGM=`echo $daFILE                   ` ; echo PGM: $PGM
export CWD=`echo $daFILE                 `   ; echo CWD: $CWD
#export PGM=`echo $daFILE | sed "s/\/.*\///"` ; echo PGM: $PGM
#export CWD=`echo $daFILE | sed "s/$PGM//"`   ; echo CWD: $CWD

echo " ++++ wc -l $PWD/$CWD stderr ++++++++++++++++++++"
wc -l $PWD/$CWD/*stderr  2>&1
echo " ++++ tail -n20 $PWD$CWD stderr +show ALL stderr files (maybe one has info +++++++++++++++++++"
tail -n 20 $PWD/$CWD/*stderr  2>&1
echo " ++++ hexdump -C ++++++++++++++++++++++++++++"
head $daFILE | hexdump -C

echo "first line should be #!/bin/....."
head -1 $daFILE
echo +++++++++  ls -la  .$daFILE :
/bin/ls -la $daFILE| head -20 | cut -c 8- 

MODE=`/bin/ls -l $daFILE| head -3|  cut -c8-10`
if [ $MODE != 'r-x' ] ; then echo "^^^ mode chould be r-x.  chmod 775 .$daFILE" ;fi
cat << END
</textarea><p>
</body>
</html>
END
```

**Comment by shellscape** [comment]
Still an issue in August 2022

**Comment by victor4pro** [comment]
@shellscape Hi, You should migrate to another IDE bacause atom repo will be archived soon.
Atom and all repositories under Atom will be archived on December 15, 2022[ Learn more in our official statement](https://github.blog/2022-06-08-sunsetting-atom/)

**Comment by shellscape** [comment]
@victor4pro you can pry Atom from my cold, dead hands. In all seriousness though, your reply generally isn't helpful. That archive date is a full 4 months away, and it's pretty poor form to let the supporting API for the entire ecosystem wither and fail before the archive date. I'd be embarrassed if I were associated with that product and connected to that happening.

**Comment by Uzunie123** [comment]
> Atom package installs have started failing. The server doesn't appear to be redirecting clients to a download tarball. The issue is easy to see using the `apm` CLI tool.
> 
> I've created a bug report here: [atom/apm#946](https://github.com/atom/apm/issues/946)
> 
> Opening this issue to redirect users looking to report this problem, or add new information to the issue in the `apm` repo, since that seems like the more appropriate place.

Hello, I have the same issue. Did you fix the problem? Can you give me some suggestions?

**Comment by adminka-root** [comment]
https://github.com/kiteco/atom-plugin.git is does not exist... I think the repository was made private

**Comment by ktavabi** [comment]
And I'd just given up on vscode. It's a miracle anyone gets anything done.

**Comment by shellscape** [comment]
I'm working on a comprehensive extension for VS code that makes it more like the atom experience. follow my GitHub for releases and updates

**Comment by ktavabi** [comment]
🤮🤮🤮 [No!](https://github.blog/2022-06-08-sunsetting-atom/)

**Comment by phun-ky** [comment]
Still having issues with this. apm and GUI fails. Also get errors from the search function..

**Comment by annahosanna** [comment]
I am also seeing this error. A 500 indicates a server error, and indeed retrying (after several attempts) eventually worked.

**Comment by shellscape** [comment]
for a while I was working with one of the GitHub developer advocates to find out why this was happening. he managed to get nowhere, but indicated that this is an intentional failure in order to get people to migrate. it's a very shady tactic.

**Comment by phun-ky** [comment]
@shellscape migrate to what?

**Comment by shellscape** [comment]
VSCode, clearly. It's an MS property.

**Comment by phun-ky** [comment]
@shellscape  yeah, I figured that one out. too bad, really like the independence Atom had. Have tested VScode out today, and it works fine, just had to remap the key bindings to the atom bind map. Was afrad that it would be to fluffly and bloated, but atm it is a perfect replacement. 

However, the current tactic used by Atom (intentionally or unintentionally) is not a way to communicate to the users.
