### ISSUE TITLE
trying to compile from source on ubuntu arm64 and got an error

### ISSUE THREAD

**Issue by gabrielpasv** [atom/atom#25486]
`34686 verbose stack Error: electron-mksnapshot@11.0.1 install: `node ./download-mksnapshot.js`
34686 verbose stack Exit status 1
34686 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
34686 verbose stack     at EventEmitter.emit (events.js:400:28)
34686 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
34686 verbose stack     at ChildProcess.emit (events.js:400:28)
34686 verbose stack     at maybeClose (internal/child_process.js:1088:16)
34686 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
34687 verbose pkgid electron-mksnapshot@11.0.1
34688 verbose cwd /home/parallels/atom/script
`

**Comment by raer0** [comment]
Atom is abandonedware. Due to complications with github being acquired by microsoft, it is unclear if/when this will ever be formally acknowledged. To give an idea of how abandoned this software is: 

- The discussions section was deleted without notice after getting spammed despite methods existing to fix discussion board spam. 
- None of the original maintainers/devs have committed to the repo since 2020
- There are, as far as I can tell, two official maintainers for this repo these days.
- The CI pipeline is broken with no indications of being fixed


This software should not be used. Nearly all of its dependencies are ancient, and nobody is left to pass the torch. It is too big, has been touched by too many hands, and has been left to die for too long to be rescued. 

If you would like to explore a de-microsfted text editor based on Electron, try [VSCodium](https://github.com/VSCodium/vscodium), a repackaged binary of VSCode's open source codebase with all the microsoft telemetry stripped out, and which uses an open source extension distribution platform separate again from Microsoft. 

I personally find it to be quite adequate.
