### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\C:\ProgramData\ebra5\atom\app-1.60....

### ISSUE THREAD

**Issue by Ibrahimalsubaihi** [atom/atom#25488]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\ProgramData\ebra5\atom\app-1.60.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:140

Error: The specified module could not be found.
\\?\C:\ProgramData\ebra5\atom\app-1.60.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (C:/ProgramData/ebra5/atom/app-1.60.0/resources/app/static/<embedded>:1:802772)
    at get_KeyboardLayoutManager (C:/ProgramData/ebra5/atom/app-1.60.0/resources/app/static/<embedded>:14:2877135)
    at get_manager (C:/ProgramData/ebra5/atom/app-1.60.0/resources/app/static/<embedded>:14:2877237)
    at Object.getCurrentKeyboardLayout (C:/ProgramData/ebra5/atom/app-1.60.0/resources/app/static/<embedded>:14:2877363)
    at e.keystrokeForKeyboardEvent (C:/ProgramData/ebra5/atom/app-1.60.0/resources/app/static/<embedded>:14:1121318)
    at KeymapManager.keystrokeForKeyboardEvent (C:/ProgramData/ebra5/atom/app-1.60.0/resources/app/static/<embedded>:11:1225566)
    at KeymapManager.handleKeyboardEvent (C:/ProgramData/ebra5/atom/app-1.60.0/resources/app/static/<embedded>:11:1223551)
    at WindowEventHandler.handleDocumentKeyEvent (C:/ProgramData/ebra5/atom/app-1.60.0/resources/app/static/<embedded>:11:286682)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by raer0** [comment]
Atom is abandonedware. Due to complications with github being acquired by microsoft, it is unclear if/when this will ever be formally acknowledged. To give an idea of how abandoned this software is: 

- The discussions section was deleted without notice after getting spammed despite methods existing to fix discussion board spam. 
- None of the original maintainers/devs have committed to the repo since 2020
- There are, as far as I can tell, two official maintainers for this repo these days.
- The CI pipeline is broken with no indications of being fixed


This software should not be used. Nearly all of its dependencies are ancient, and nobody is left to pass the torch. It is too big, has been touched by too many hands, and has been left to die for too long to be rescued. 

If you would like to explore a de-microsfted text editor based on Electron, try [VSCodium](https://github.com/VSCodium/vscodium), a repackaged binary of VSCode's open source codebase with all the microsoft telemetry stripped out, and which uses an open source extension distribution platform separate again from Microsoft. 

I personally find it to be quite adequate.
