### ISSUE TITLE
Atom does not build (error raised in src/atom-1.61.0-beta0/script/lib/dump-symbols.js:33)

### ISSUE THREAD

**Issue by DAC324** [atom/atom#25518]
Hello all,

trying to build Atom, I get
```
Transpiling Babel paths in /opt/.cache/yay/atom/src/atom-1.61.0-beta0/out/app
Transpiling CoffeeScript paths in /opt/.cache/yay/atom/src/atom-1.61.0-beta0/out/app
Transpiling CSON paths in /opt/.cache/yay/atom/src/atom-1.61.0-beta0/out/app
Transpiling PEG.js paths in /opt/.cache/yay/atom/src/atom-1.61.0-beta0/out/app
Generating module cache for /opt/.cache/yay/atom/src/atom-1.61.0-beta0/out/app
Generating pre-built less cache in /opt/.cache/yay/atom/src/atom-1.61.0-beta0/out/app/less-compile-cache
Generating metadata for /opt/.cache/yay/atom/src/atom-1.61.0-beta0/out/app/package.json
Generating API docs at /opt/.cache/yay/atom/src/atom-1.61.0-beta0/docs/output/atom-api.json
Dumping symbols in /opt/.cache/yay/atom/src/atom-1.61.0-beta0/out/symbols
/opt/.cache/yay/atom/src/atom-1.61.0-beta0/script/lib/dump-symbols.js:33
        throw new Error(error);
        ^

[Error: Error
  at /opt/.cache/yay/atom/src/atom-1.61.0-beta0/script/lib/dump-symbols.js:33:15
  at ChildProcess.<anonymous> (/opt/.cache/yay/atom/src/atom-1.61.0-beta0/script/node_modules/minidump/lib/minidump.js:27:7)
  at ChildProcess.emit (events.js:315:20)
  at maybeClose (internal/child_process.js:1021:16)
  at Socket.<anonymous> (internal/child_process.js:443:11)
  at Socket.emit (events.js:315:20)
  at Pipe.<anonymous> (net.js:674:12)
]
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: atom
```
This is due to the following code around line 33 of `src/atom-1.61.0-beta0/script/lib/dump-symbols.js`:
```
      if (error) {
        // fswin.node is only used on windows, ignore the error on other platforms
        if (process.platform !== 'win32' && binaryPath.match(/fswin.node/))
          return resolve();
       throw new Error(error);
```

**Comment by Ruzie** [comment]
Try this one https://github.com/atom-community/atom/
Since atom is now abandoned and the project is concluded.

**Comment by DAC324** [comment]
With that package, I get exactly the same error:
```
Dumping symbols in /opt/.cache/yay/atom/src/atom-1.61.0-beta0/out/symbols
/opt/.cache/yay/atom/src/atom-1.61.0-beta0/script/lib/dump-symbols.js:33
        throw new Error(error);
        ^

[Error: Error
  at /opt/.cache/yay/atom/src/atom-1.61.0-beta0/script/lib/dump-symbols.js:33:15
  at ChildProcess.<anonymous> (/opt/.cache/yay/atom/src/atom-1.61.0-beta0/script/node_modules/minidump/lib/minidump.js:27:7)
  at ChildProcess.emit (events.js:315:20)
  at maybeClose (internal/child_process.js:1021:16)
  at Socket.<anonymous> (internal/child_process.js:443:11)
  at Socket.emit (events.js:315:20)
  at Pipe.<anonymous> (net.js:674:12)
]
```

**Comment by embedvr** [comment]
> With that package, I get exactly the same error:
> 
> ```
> Dumping symbols in /opt/.cache/yay/atom/src/atom-1.61.0-beta0/out/symbols
> /opt/.cache/yay/atom/src/atom-1.61.0-beta0/script/lib/dump-symbols.js:33
>         throw new Error(error);
>         ^
> 
> [Error: Error
>   at /opt/.cache/yay/atom/src/atom-1.61.0-beta0/script/lib/dump-symbols.js:33:15
>   at ChildProcess.<anonymous> (/opt/.cache/yay/atom/src/atom-1.61.0-beta0/script/node_modules/minidump/lib/minidump.js:27:7)
>   at ChildProcess.emit (events.js:315:20)
>   at maybeClose (internal/child_process.js:1021:16)
>   at Socket.<anonymous> (internal/child_process.js:443:11)
>   at Socket.emit (events.js:315:20)
>   at Pipe.<anonymous> (net.js:674:12)
> ]
> ```

make an issue or pr there, you will get no support here.

**Comment by iamunadike** [comment]
Please Note, the beta 1.61 is not a stable release yet, Its a testing release and more work is being put into it 
Use 1.60 instead
By the end of the year or so, github (microsoft) want to archive atom 
but we have a wonder continuation going on here for really indicate the team working hard to do the best they can while being careful not to break anything yet

https://github.com/atom-community/atom/
