### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\Temp\360zip$Temp\36...

### ISSUE THREAD

**Issue by mabelcris82** [atom/atom#25534]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.60.0 ia32
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\Mabel\AppData\Local\Temp\360zip$Temp\360$0\Atom\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:140

Error: The specified module could not be found.
\\?\C:\Users\Mabel\AppData\Local\Temp\360zip$Temp\360$0\Atom\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/Temp/360zip$Temp/360$0/Atom/resources/app/static/<embedded>:1:802772)
    at get_KeyboardLayoutManager (~/AppData/Local/Temp/360zip$Temp/360$0/Atom/resources/app/static/<embedded>:14:2877135)
    at get_manager (~/AppData/Local/Temp/360zip$Temp/360$0/Atom/resources/app/static/<embedded>:14:2877237)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/Temp/360zip$Temp/360$0/Atom/resources/app/static/<embedded>:14:2877363)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/Temp/360zip$Temp/360$0/Atom/resources/app/static/<embedded>:14:1121318)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/Temp/360zip$Temp/360$0/Atom/resources/app/static/<embedded>:11:1225566)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/Temp/360zip$Temp/360$0/Atom/resources/app/static/<embedded>:11:1223551)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/Temp/360zip$Temp/360$0/Atom/resources/app/static/<embedded>:11:286682)
```

### Commands

```
     -1:38.3.0 core:save-as (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by SoftOrangeTech** [comment]
**Hello, thanks for creating an issue here, but:**
GitHub is ending support for Atom and archiving, so please do not create any new issues or pull requests unless you want to discuss. - I am not a developer.
Thank you.

**Comment by SoftOrangeTech** [comment]
Hello there!
Thanks for creating the issue, but you need at least a description and some steps to reproduce (unless it doesn't apply to you).
Hope this Helps!
