### ISSUE TITLE
Can't build Atom on Arch Linux

### ISSUE THREAD

**Issue by Limones-07** [atom/atom#25591]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I can't build Atom.

### Steps to Reproduce
On a bash shell:

1. git clone https://github.com/atom/atom.git
2. cd atom/scripts
3. ./build --install=/limonesdata/ProgramFiles
4. Boom! Error after the "Installing apm" message.

I tried to do a ./clean and repeating step 3, but didn't suceed.

**Expected behavior:**

Build and install Atom on the specified directory.

**Actual behavior:**

Doesn't install neither build anything.

**Reproduces how often:**

100% of the time.

### Versions

The atom and apm commands weren't found.
OS: Arch Linux (rolling release).
Compositor: Picom.
WM: BSPWM.

### Additional Information

The output of ./build --install=/limonesdata/ProgramFiles:

Node:	v16.16.0
Python:	v3.10.6
Installing script dependencies
Installing apm
(node:164598) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
In file included from ../../nan/nan.h:56,
                 from ../src/onig-scanner.h:4,
                 from ../src/onig-scanner.cc:1:
/home/limones/.cache/node-gyp/16.16.0/include/node/node.h:847:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  847 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/limones/.cache/node-gyp/16.16.0/include/node/node.h:881:3: note: in expansion of macro ‘NODE_MODULE_X’
  881 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/onig-scanner.cc:23:1: note: in expansion of macro ‘NODE_MODULE’
   23 | NODE_MODULE(onig_scanner, InitModule)
      | ^~~~~~~~~~~
(node:165694) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
../deps/libgit2/deps/zlib/infback.c: In function ‘inflateBack’:
../deps/libgit2/deps/zlib/infback.c:479:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
  479 |             state->mode = LEN;
      |             ~~~~~~~~~~~~^~~~~
../deps/libgit2/deps/zlib/infback.c:481:9: note: here
  481 |         case LEN:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c: In function ‘inflate’:
../deps/libgit2/deps/zlib/inflate.c:841:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
  841 |             state->mode = DICT;
      |             ~~~~~~~~~~~~^~~~~~
../deps/libgit2/deps/zlib/inflate.c:842:9: note: here
  842 |         case DICT:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:848:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
  848 |             state->mode = TYPE;
      |             ~~~~~~~~~~~~^~~~~~
../deps/libgit2/deps/zlib/inflate.c:849:9: note: here
  849 |         case TYPE:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:850:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
  850 |             if (flush == Z_BLOCK || flush == Z_TREES) goto inf_leave;
      |                ^
../deps/libgit2/deps/zlib/inflate.c:851:9: note: here
  851 |         case TYPEDO:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:900:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
  900 |             if (flush == Z_TREES) goto inf_leave;
      |                ^
../deps/libgit2/deps/zlib/inflate.c:901:9: note: here
  901 |         case COPY_:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:902:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
  902 |             state->mode = COPY;
      |             ~~~~~~~~~~~~^~~~~~
../deps/libgit2/deps/zlib/inflate.c:903:9: note: here
  903 |         case COPY:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:1041:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1041 |             if (flush == Z_TREES) goto inf_leave;
      |                ^
../deps/libgit2/deps/zlib/inflate.c:1042:9: note: here
 1042 |         case LEN_:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:1043:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1043 |             state->mode = LEN;
      |             ~~~~~~~~~~~~^~~~~
../deps/libgit2/deps/zlib/inflate.c:1044:9: note: here
 1044 |         case LEN:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:1092:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1092 |             state->mode = LENEXT;
      |             ~~~~~~~~~~~~^~~~~~~~
../deps/libgit2/deps/zlib/inflate.c:1093:9: note: here
 1093 |         case LENEXT:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:1102:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1102 |             state->mode = DIST;
      |             ~~~~~~~~~~~~^~~~~~
../deps/libgit2/deps/zlib/inflate.c:1103:9: note: here
 1103 |         case DIST:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:1129:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1129 |             state->mode = DISTEXT;
      |             ~~~~~~~~~~~~^~~~~~~~~
../deps/libgit2/deps/zlib/inflate.c:1130:9: note: here
 1130 |         case DISTEXT:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:1145:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1145 |             state->mode = MATCH;
      |             ~~~~~~~~~~~~^~~~~~~
../deps/libgit2/deps/zlib/inflate.c:1146:9: note: here
 1146 |         case MATCH:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:1233:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1233 |             state->mode = DONE;
      |             ~~~~~~~~~~~~^~~~~~
../deps/libgit2/deps/zlib/inflate.c:1234:9: note: here
 1234 |         case DONE:
      |         ^~~~
../deps/libgit2/deps/http-parser/http_parser.c: In function ‘http_parser_parse_url’:
../deps/libgit2/deps/http-parser/http_parser.c:2094:18: warning: this statement may fall through [-Wimplicit-fallthrough=]
 2094 |         found_at = 1;
      |         ~~~~~~~~~^~~
../deps/libgit2/deps/http-parser/http_parser.c:2097:7: note: here
 2097 |       case s_req_server:
      |       ^~~~
In file included from ../../nan/nan.h:56,
                 from ../src/repository.h:29,
                 from ../src/repository.cc:22:
/home/limones/.cache/node-gyp/16.16.0/include/node/node.h:847:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  847 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/limones/.cache/node-gyp/16.16.0/include/node/node.h:881:3: note: in expansion of macro ‘NODE_MODULE_X’
  881 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/repository.cc:71:1: note: in expansion of macro ‘NODE_MODULE’
   71 | NODE_MODULE(git, Repository::Init)
      | ^~~~~~~~~~~
../src/repository.cc: In member function ‘virtual void Repository::GetHeadAsync(Nan::NAN_METHOD_ARGS_TYPE)::HeadAsyncWorker::HandleOKCallback()’:
../src/repository.cc:242:21: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
  242 |       callback->Call(2, argv);
      |       ~~~~~~~~~~~~~~^~~~~~~~~
../../nan/nan.h:1742:3: note: declared here
 1742 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
../src/repository.cc: In member function ‘virtual void Repository::GetStatusAsync(Nan::NAN_METHOD_ARGS_TYPE)::StatusAsyncWorker::HandleOKCallback()’:
../src/repository.cc:412:21: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
  412 |       callback->Call(2, argv);
      |       ~~~~~~~~~~~~~~^~~~~~~~~
../../nan/nan.h:1742:3: note: declared here
 1742 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
../src/repository.cc: In member function ‘virtual void Repository::CompareCommitsAsync(Nan::NAN_METHOD_ARGS_TYPE)::CompareCommitsAsyncWorker::HandleOKCallback()’:
../src/repository.cc:749:21: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
  749 |       callback->Call(2, argv);
      |       ~~~~~~~~~~~~~~^~~~~~~~~
../../nan/nan.h:1742:3: note: declared here
 1742 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
(node:168976) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
/bin/sh: linha 1: Compressed/atom/apm/node_modules/atom-package-manager/node_modules/node-addon-api: Arquivo ou diretório inexistente
/bin/sh: linha 1: Compressed/atom/apm/node_modules/atom-package-manager/node_modules/node-addon-api: Arquivo ou diretório inexistente
make: *** [keytar.target.mk:115: Release/obj.target/keytar/src/async.o] Erro 127
make: ** Esperando que outros processos terminem.
make: *** [keytar.target.mk:115: Release/obj.target/keytar/src/main.o] Erro 127
g++: fatal error: no input files
compilation terminated.
/bin/sh: linha 1: Compressed/atom/apm/node_modules/atom-package-manager/node_modules/node-addon-api: Arquivo ou diretório inexistente
g++: fatal error: no input files
compilation terminated.
make: *** [keytar.target.mk:115: Release/obj.target/keytar/src/keytar_posix.o] Erro 127
g++: fatal error: no input files
compilation terminated.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/limones/Sources&Compressed/atom/script/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.18.16-arch1-1
gyp ERR! command "/usr/bin/node" "/home/limones/Sources&Compressed/atom/script/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/limones/Sources&Compressed/atom/apm/node_modules/atom-package-manager/node_modules/keytar
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@6.0.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@6.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/limones/.npm/_logs/2022-08-06T17_21_54_479Z-debug.log
node:child_process:866
    throw err;
    ^

Error: Command failed: /home/limones/Sources&Compressed/atom/script/node_modules/.bin/npm --global-style --loglevel=error install
(node:164598) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
In file included from ../../nan/nan.h:56,
                 from ../src/onig-scanner.h:4,
                 from ../src/onig-scanner.cc:1:
/home/limones/.cache/node-gyp/16.16.0/include/node/node.h:847:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  847 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/limones/.cache/node-gyp/16.16.0/include/node/node.h:881:3: note: in expansion of macro ‘NODE_MODULE_X’
  881 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/onig-scanner.cc:23:1: note: in expansion of macro ‘NODE_MODULE’
   23 | NODE_MODULE(onig_scanner, InitModule)
      | ^~~~~~~~~~~
(node:165694) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
../deps/libgit2/deps/zlib/infback.c: In function ‘inflateBack’:
../deps/libgit2/deps/zlib/infback.c:479:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
  479 |             state->mode = LEN;
      |             ~~~~~~~~~~~~^~~~~
../deps/libgit2/deps/zlib/infback.c:481:9: note: here
  481 |         case LEN:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c: In function ‘inflate’:
../deps/libgit2/deps/zlib/inflate.c:841:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
  841 |             state->mode = DICT;
      |             ~~~~~~~~~~~~^~~~~~
../deps/libgit2/deps/zlib/inflate.c:842:9: note: here
  842 |         case DICT:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:848:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
  848 |             state->mode = TYPE;
      |             ~~~~~~~~~~~~^~~~~~
../deps/libgit2/deps/zlib/inflate.c:849:9: note: here
  849 |         case TYPE:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:850:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
  850 |             if (flush == Z_BLOCK || flush == Z_TREES) goto inf_leave;
      |                ^
../deps/libgit2/deps/zlib/inflate.c:851:9: note: here
  851 |         case TYPEDO:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:900:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
  900 |             if (flush == Z_TREES) goto inf_leave;
      |                ^
../deps/libgit2/deps/zlib/inflate.c:901:9: note: here
  901 |         case COPY_:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:902:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
  902 |             state->mode = COPY;
      |             ~~~~~~~~~~~~^~~~~~
../deps/libgit2/deps/zlib/inflate.c:903:9: note: here
  903 |         case COPY:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:1041:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1041 |             if (flush == Z_TREES) goto inf_leave;
      |                ^
../deps/libgit2/deps/zlib/inflate.c:1042:9: note: here
 1042 |         case LEN_:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:1043:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1043 |             state->mode = LEN;
      |             ~~~~~~~~~~~~^~~~~
../deps/libgit2/deps/zlib/inflate.c:1044:9: note: here
 1044 |         case LEN:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:1092:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1092 |             state->mode = LENEXT;
      |             ~~~~~~~~~~~~^~~~~~~~
../deps/libgit2/deps/zlib/inflate.c:1093:9: note: here
 1093 |         case LENEXT:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:1102:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1102 |             state->mode = DIST;
      |             ~~~~~~~~~~~~^~~~~~
../deps/libgit2/deps/zlib/inflate.c:1103:9: note: here
 1103 |         case DIST:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:1129:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1129 |             state->mode = DISTEXT;
      |             ~~~~~~~~~~~~^~~~~~~~~
../deps/libgit2/deps/zlib/inflate.c:1130:9: note: here
 1130 |         case DISTEXT:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:1145:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1145 |             state->mode = MATCH;
      |             ~~~~~~~~~~~~^~~~~~~
../deps/libgit2/deps/zlib/inflate.c:1146:9: note: here
 1146 |         case MATCH:
      |         ^~~~
../deps/libgit2/deps/zlib/inflate.c:1233:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1233 |             state->mode = DONE;
      |             ~~~~~~~~~~~~^~~~~~
../deps/libgit2/deps/zlib/inflate.c:1234:9: note: here
 1234 |         case DONE:
      |         ^~~~
../deps/libgit2/deps/http-parser/http_parser.c: In function ‘http_parser_parse_url’:
../deps/libgit2/deps/http-parser/http_parser.c:2094:18: warning: this statement may fall through [-Wimplicit-fallthrough=]
 2094 |         found_at = 1;
      |         ~~~~~~~~~^~~
../deps/libgit2/deps/http-parser/http_parser.c:2097:7: note: here
 2097 |       case s_req_server:
      |       ^~~~
In file included from ../../nan/nan.h:56,
                 from ../src/repository.h:29,
                 from ../src/repository.cc:22:
/home/limones/.cache/node-gyp/16.16.0/include/node/node.h:847:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  847 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/limones/.cache/node-gyp/16.16.0/include/node/node.h:881:3: note: in expansion of macro ‘NODE_MODULE_X’
  881 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/repository.cc:71:1: note: in expansion of macro ‘NODE_MODULE’
   71 | NODE_MODULE(git, Repository::Init)
      | ^~~~~~~~~~~
../src/repository.cc: In member function ‘virtual void Repository::GetHeadAsync(Nan::NAN_METHOD_ARGS_TYPE)::HeadAsyncWorker::HandleOKCallback()’:
../src/repository.cc:242:21: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
  242 |       callback->Call(2, argv);
      |       ~~~~~~~~~~~~~~^~~~~~~~~
../../nan/nan.h:1742:3: note: declared here
 1742 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
../src/repository.cc: In member function ‘virtual void Repository::GetStatusAsync(Nan::NAN_METHOD_ARGS_TYPE)::StatusAsyncWorker::HandleOKCallback()’:
../src/repository.cc:412:21: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
  412 |       callback->Call(2, argv);
      |       ~~~~~~~~~~~~~~^~~~~~~~~
../../nan/nan.h:1742:3: note: declared here
 1742 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
../src/repository.cc: In member function ‘virtual void Repository::CompareCommitsAsync(Nan::NAN_METHOD_ARGS_TYPE)::CompareCommitsAsyncWorker::HandleOKCallback()’:
../src/repository.cc:749:21: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
  749 |       callback->Call(2, argv);
      |       ~~~~~~~~~~~~~~^~~~~~~~~
../../nan/nan.h:1742:3: note: declared here
 1742 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
(node:168976) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
/bin/sh: linha 1: Compressed/atom/apm/node_modules/atom-package-manager/node_modules/node-addon-api: Arquivo ou diretório inexistente
/bin/sh: linha 1: Compressed/atom/apm/node_modules/atom-package-manager/node_modules/node-addon-api: Arquivo ou diretório inexistente
make: *** [keytar.target.mk:115: Release/obj.target/keytar/src/async.o] Erro 127
make: ** Esperando que outros processos terminem.
make: *** [keytar.target.mk:115: Release/obj.target/keytar/src/main.o] Erro 127
g++: fatal error: no input files
compilation terminated.
/bin/sh: linha 1: Compressed/atom/apm/node_modules/atom-package-manager/node_modules/node-addon-api: Arquivo ou diretório inexistente
g++: fatal error: no input files
compilation terminated.
make: *** [keytar.target.mk:115: Release/obj.target/keytar/src/keytar_posix.o] Erro 127
g++: fatal error: no input files
compilation terminated.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/limones/Sources&Compressed/atom/script/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.18.16-arch1-1
gyp ERR! command "/usr/bin/node" "/home/limones/Sources&Compressed/atom/script/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/limones/Sources&Compressed/atom/apm/node_modules/atom-package-manager/node_modules/keytar
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@6.0.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@6.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/limones/.npm/_logs/2022-08-06T17_21_54_479Z-debug.log

    at checkExecSyncError (node:child_process:828:11)
    at Object.execFileSync (node:child_process:863:15)
    at module.exports (/home/limones/Sources&Compressed/atom/script/lib/install-apm.js:14:16)
    at Object.<anonymous> (/home/limones/Sources&Compressed/atom/script/bootstrap:37:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(16164) [Uint8Array] [
       10,  62,  32, 111, 110, 105, 103, 117, 114, 117, 109,  97,
       64,  55,  46,  50,  46,  49,  32, 105, 110, 115, 116,  97,
      108, 108,  32,  47, 104, 111, 109, 101,  47, 108, 105, 109,
      111, 110, 101, 115,  47,  83, 111, 117, 114,  99, 101, 115,
       38,  67, 111, 109, 112, 114, 101, 115, 115, 101, 100,  47,
       97, 116, 111, 109,  47,  97, 112, 109,  47, 110, 111, 100,
      101,  95, 109, 111, 100, 117, 108, 101, 115,  47,  97, 116,
      111, 109,  45, 112,  97,  99, 107,  97, 103, 101,  45, 109,
       97, 110,  97, 103,
      ... 16064 more items
    ],
    Buffer(10415) [Uint8Array] [
       40, 110, 111, 100, 101,  58,  49,  54,  52,  53,  57,  56,
       41,  32,  91,  68,  69,  80,  48,  49,  53,  48,  93,  32,
       68, 101, 112, 114, 101,  99,  97, 116, 105, 111, 110,  87,
       97, 114, 110, 105, 110, 103,  58,  32,  83, 101, 116, 116,
      105, 110, 103,  32, 112, 114, 111,  99, 101, 115, 115,  46,
       99, 111, 110, 102, 105, 103,  32, 105, 115,  32, 100, 101,
      112, 114, 101,  99,  97, 116, 101, 100,  46,  32,  73, 110,
       32, 116, 104, 101,  32, 102, 117, 116, 117, 114, 101,  32,
      116, 104, 101,  32,
      ... 10315 more items
    ]
  ],
  pid: 164559,
  stdout: Buffer(16164) [Uint8Array] [
     10,  62,  32, 111, 110, 105, 103, 117, 114, 117, 109,  97,
     64,  55,  46,  50,  46,  49,  32, 105, 110, 115, 116,  97,
    108, 108,  32,  47, 104, 111, 109, 101,  47, 108, 105, 109,
    111, 110, 101, 115,  47,  83, 111, 117, 114,  99, 101, 115,
     38,  67, 111, 109, 112, 114, 101, 115, 115, 101, 100,  47,
     97, 116, 111, 109,  47,  97, 112, 109,  47, 110, 111, 100,
    101,  95, 109, 111, 100, 117, 108, 101, 115,  47,  97, 116,
    111, 109,  45, 112,  97,  99, 107,  97, 103, 101,  45, 109,
     97, 110,  97, 103,
    ... 16064 more items
  ],
  stderr: Buffer(10415) [Uint8Array] [
     40, 110, 111, 100, 101,  58,  49,  54,  52,  53,  57,  56,
     41,  32,  91,  68,  69,  80,  48,  49,  53,  48,  93,  32,
     68, 101, 112, 114, 101,  99,  97, 116, 105, 111, 110,  87,
     97, 114, 110, 105, 110, 103,  58,  32,  83, 101, 116, 116,
    105, 110, 103,  32, 112, 114, 111,  99, 101, 115, 115,  46,
     99, 111, 110, 102, 105, 103,  32, 105, 115,  32, 100, 101,
    112, 114, 101,  99,  97, 116, 101, 100,  46,  32,  73, 110,
     32, 116, 104, 101,  32, 102, 117, 116, 117, 114, 101,  32,
    116, 104, 101,  32,
    ... 10315 more items
  ]
}

**Comment by stech11845** [comment]
So many errors..... 10315 MORE? Someone cannot help with this.

**Comment by rilysh** [comment]
Atom wasn't made for to build under Arch or another distro besides Debian or Debian based (Ubuntu). To be fair, this issue is known, and the development has already stopped. For now try to compile it on Ubuntu (VM) and see what you get.

**Comment by lwvmobile** [comment]
Just FYI, as of 2022-09-20, I was able to install a version of atom using this method in Garuda (Arch). I originally found it on the AUR page for Atom. Comments suggest it will eventually break too, but figured I'd share it for anybody else needed it. Make sure to uninstall your current version and clean any orphans first, and then run.

#fast way to install
git clone https://gitlab.com/andrew_ryan/atom-bin.git
cd atom-bin
yay -U ./atom-bin-1.60.0-1-x86_64.pkg.tar.zst
