### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\C:\ProgramData\User\atom\app...

### ISSUE THREAD

**Issue by venger17** [atom/atom#25718]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.63.1 x64
**Electron**: 11.5.0
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\ProgramData\User\atom\app-1.63.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar_bundle.js:5

Error: The specified module could not be found.
\\?\C:\ProgramData\User\atom\app-1.63.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:72:18)
    at customRequire (C:/ProgramData/Andy García/atom/app-1.63.1/resources/app/static/<embedded>:1:821096)
    at get_KeyboardLayoutManager (C:/ProgramData/Andy García/atom/app-1.63.1/resources/app/static/<embedded>:14:2938000)
    at get_manager (C:/ProgramData/Andy García/atom/app-1.63.1/resources/app/static/<embedded>:14:2938102)
    at Object.getCurrentKeyboardLayout (C:/ProgramData/Andy García/atom/app-1.63.1/resources/app/static/<embedded>:14:2938228)
    at e.keystrokeForKeyboardEvent (C:/ProgramData/Andy García/atom/app-1.63.1/resources/app/static/<embedded>:14:1169281)
    at KeymapManager.keystrokeForKeyboardEvent (C:/ProgramData/Andy García/atom/app-1.63.1/resources/app/static/<embedded>:11:1223396)
    at KeymapManager.handleKeyboardEvent (C:/ProgramData/Andy García/atom/app-1.63.1/resources/app/static/<embedded>:11:1221381)
    at WindowEventHandler.handleDocumentKeyEvent (C:/ProgramData/Andy García/atom/app-1.63.1/resources/app/static/<embedded>:11:286622)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autoclose-html 0.23.0 
emmet 2.4.3 
file-icons 2.1.47 
highlight-selected 0.17.0 
minimap 4.40.1 
pigments 0.40.6 
Quick-JavaScript 2.2.0 
zentabs 0.8.9 
```

**Comment by venger17** [comment]
I went back to the previous version of atom and it was solved
