### ISSUE TITLE
Unix process substitution displays nothing

### ISSUE THREAD

**Issue by kylewlacy** [atom/atom#2766]
[Process substitution](http://en.wikipedia.org/wiki/Process_substitution) is a feature common in Unix derivatives that allows one process' `stdout` to be fed into another process' `stdin` as a file descriptor. Here's the canonical `diff` example:

``` sh
$ diff -u <(echo 'Hello wrold') myfile.txt
--- /dev/fd/63  2014-06-28 23:41:39.000000000 -0700
+++ myfile.txt  2014-06-28 23:41:37.000000000 -0700
@@ -1 +1 @@
-Hello wrold
+Hello wrold!
```

(where the `echo 'Hello wrold'` can be any command, run within a subshell)

Thus, the following should work:

``` sh
$ atom <(echo 'Hello wrold!')
```

The expected result of this is that Atom should open a file descriptor containing "Hello wrold!" (which works in both `vim` and `nano`). While `/dev/fd/63` is successfully opened, the file is always blank (when run in `--safe` mode). No errors appear in the WebKit console.

I tested this on OS X 10.9.3, in Atom 0.106.0

**Comment by pazustep** [comment]
I get an error when trying to use process substitution:

```
Error: EBADF: bad file descriptor, open '/dev/fd/11'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:371:27)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:449:31)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:375:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:46:25)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
```
