### ISSUE TITLE
Cannot open a file through Webdav on Windows

### ISSUE THREAD

**Issue by stevebeauge** [atom/atom#3115]
Hello,

I'm working with some webdav file repository (actually a SharePoint server).

I'm trying to open a file from this repository with Atom (Windows 8.1 X64), but this does not works. Atom opens, but the editor is empty.

For example, if I try to open `http://myserver/Style%20Library/XSL%20Style%20Sheets/rss.xsl` it fails.

Using Fiddler, I can trace these http paquets:

![image](https://cloud.githubusercontent.com/assets/184604/3733446/0fb204ee-1708-11e4-983d-f48d7a02269a.png)

(the process is svchost because of Windows "WebClient" service to wrap WebDav access).

I guess the 404 errors may be ignored, as it's only a *try to find a file* request.

The two last responses are:

    HTTP/1.1 207 MULTI-STATUS
    Via: 1.1 FW02
    Connection: Keep-Alive
    Proxy-Connection: Keep-Alive
    Content-Length: 7094
    Date: Tue, 29 Jul 2014 10:01:28 GMT
    Content-Type: text/xml
    Server: Microsoft-IIS/7.5
    Cache-Control: no-cache
    X-SharePointHealthScore: 0
    Public-Extension: http://schemas.microsoft.com/repl-2
    SPRequestGuid: e23ba99c-8e3a-f07d-d7df-865474ff42bc
    request-id: e23ba99c-8e3a-f07d-d7df-865474ff42bc
    X-FRAME-OPTIONS: SAMEORIGIN
    SPRequestDuration: 18
    SPIisLatency: 0
    Persistent-Auth: false
    X-Powered-By: ASP.NET
    MicrosoftSharePointTeamServices: 15.0.0.4420
    X-Content-Type-Options: nosniff
    X-MS-InvokeApp: 1; RequireReadOnly

    <?xml version="1.0" encoding="utf-8" ?><D:multistatus xmlns:D="DAV:" xmlns:Office="urn:schemas-microsoft-com:office:office" xmlns:Repl="http://schemas.microsoft.com/repl/" xmlns:Z="urn:schemas-microsoft-com:">
    <D:response><D:href>http://sbdev02/Style%20Library/XSL%20Style%20Sheets/</D:href><D:propstat><D:prop><D:displayname>XSL Style Sheets</D:displayname><D:lockdiscovery/><D:supportedlock/><D:isFolder>t</D:isFolder><D:iscollection>1</D:iscollection><D:ishidden>0</D:ishidden><D:getcontenttype>application/octet-stream</D:getcontenttype><D:getcontentlength>0</D:getcontentlength><D:resourcetype><D:collection/></D:resourcetype><Repl:authoritative-directory>t</Repl:authoritative-directory><D:getlastmodified>Wed, 30 Apr 2014 13:12:52 GMT</D:getlastmodified><D:creationdate>2014-04-30T13:12:52Z</D:creationdate><Repl:repl-uid>rid:{4A4C0DD6-0755-40EF-B150-598B44980EBE}</Repl:repl-uid><Repl:resourcetag>rt:4A4C0DD6-0755-40EF-B150-598B44980EBE@00000000000</Repl:resourcetag><D:getetag>&quot;{4A4C0DD6-0755-40EF-B150-598B44980EBE},0&quot;</D:getetag></D:prop>
    <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
    </D:response>

    <D:response><D:href>http://sbdev02/Style%20Library/XSL%20Style%20Sheets/ContentQueryMain.xsl</D:href><D:propstat><D:prop><D:displayname>ContentQueryMain.xsl</D:displayname><D:lockdiscovery/><D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock><D:getlastmodified>Wed, 30 Apr 2014 13:12:52 GMT</D:getlastmodified><D:creationdate>2014-04-30T13:12:52Z</D:creationdate><D:getcontentlength>19044</D:getcontentlength><Repl:repl-uid>rid:{15B92016-CABA-4F16-B893-3833A61CE8F2}</Repl:repl-uid><Repl:resourcetag>rt:15B92016-CABA-4F16-B893-3833A61CE8F2@00000000001</Repl:resourcetag><D:getetag>&quot;{15B92016-CABA-4F16-B893-3833A61CE8F2},1&quot;</D:getetag><Office:modifiedby>SHAREPOINT\system</Office:modifiedby></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response>
    <D:response><D:href>http://sbdev02/Style%20Library/XSL%20Style%20Sheets/SummaryLinkMain.xsl</D:href><D:propstat><D:prop><D:displayname>SummaryLinkMain.xsl</D:displayname><D:lockdiscovery/><D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock><D:getlastmodified>Wed, 30 Apr 2014 13:12:52 GMT</D:getlastmodified><D:creationdate>2014-04-30T13:12:52Z</D:creationdate><D:getcontentlength>19943</D:getcontentlength><Repl:repl-uid>rid:{E5CCDF95-CEBA-4F39-A6EE-3C48A11E023D}</Repl:repl-uid><Repl:resourcetag>rt:E5CCDF95-CEBA-4F39-A6EE-3C48A11E023D@00000000001</Repl:resourcetag><D:getetag>&quot;{E5CCDF95-CEBA-4F39-A6EE-3C48A11E023D},1&quot;</D:getetag><Office:modifiedby>SHAREPOINT\system</Office:modifiedby></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response>
    <D:response><D:href>http://sbdev02/Style%20Library/XSL%20Style%20Sheets/ItemStyle.xsl</D:href><D:propstat><D:prop><D:displayname>ItemStyle.xsl</D:displayname><D:lockdiscovery/><D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock><D:getlastmodified>Wed, 30 Apr 2014 13:12:52 GMT</D:getlastmodified><D:creationdate>2014-04-30T13:12:52Z</D:creationdate><D:getcontentlength>32345</D:getcontentlength><Repl:repl-uid>rid:{22000306-7939-420A-B84B-52975FF730C1}</Repl:repl-uid><Repl:resourcetag>rt:22000306-7939-420A-B84B-52975FF730C1@00000000001</Repl:resourcetag><D:getetag>&quot;{22000306-7939-420A-B84B-52975FF730C1},1&quot;</D:getetag><Office:modifiedby>SHAREPOINT\system</Office:modifiedby></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response>
    <D:response><D:href>http://sbdev02/Style%20Library/XSL%20Style%20Sheets/LevelStyle.xsl</D:href><D:propstat><D:prop><D:displayname>LevelStyle.xsl</D:displayname><D:lockdiscovery/><D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock><D:getlastmodified>Wed, 30 Apr 2014 13:12:52 GMT</D:getlastmodified><D:creationdate>2014-04-30T13:12:52Z</D:creationdate><D:getcontentlength>6103</D:getcontentlength><Repl:repl-uid>rid:{A038577D-C962-4A6F-8CAB-54F42367EB2A}</Repl:repl-uid><Repl:resourcetag>rt:A038577D-C962-4A6F-8CAB-54F42367EB2A@00000000001</Repl:resourcetag><D:getetag>&quot;{A038577D-C962-4A6F-8CAB-54F42367EB2A},1&quot;</D:getetag><Office:modifiedby>SHAREPOINT\system</Office:modifiedby></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response>
    <D:response><D:href>http://sbdev02/Style%20Library/XSL%20Style%20Sheets/TableOfContentsMain.xsl</D:href><D:propstat><D:prop><D:displayname>TableOfContentsMain.xsl</D:displayname><D:lockdiscovery/><D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock><D:getlastmodified>Wed, 30 Apr 2014 13:12:52 GMT</D:getlastmodified><D:creationdate>2014-04-30T13:12:52Z</D:creationdate><D:getcontentlength>6246</D:getcontentlength><Repl:repl-uid>rid:{848CF049-31FF-45B6-8496-6678B7815F33}</Repl:repl-uid><Repl:resourcetag>rt:848CF049-31FF-45B6-8496-6678B7815F33@00000000001</Repl:resourcetag><D:getetag>&quot;{848CF049-31FF-45B6-8496-6678B7815F33},1&quot;</D:getetag><Office:modifiedby>SHAREPOINT\system</Office:modifiedby></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response>
    <D:response><D:href>http://sbdev02/Style%20Library/XSL%20Style%20Sheets/Header.xsl</D:href><D:propstat><D:prop><D:displayname>Header.xsl</D:displayname><D:lockdiscovery/><D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock><D:getlastmodified>Wed, 30 Apr 2014 13:12:52 GMT</D:getlastmodified><D:creationdate>2014-04-30T13:12:52Z</D:creationdate><D:getcontentlength>2606</D:getcontentlength><Repl:repl-uid>rid:{64B77616-1D76-464B-81BC-817ABD97F06A}</Repl:repl-uid><Repl:resourcetag>rt:64B77616-1D76-464B-81BC-817ABD97F06A@00000000001</Repl:resourcetag><D:getetag>&quot;{64B77616-1D76-464B-81BC-817ABD97F06A},1&quot;</D:getetag><Office:modifiedby>SHAREPOINT\system</Office:modifiedby></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response>
    <D:response><D:href>http://sbdev02/Style%20Library/XSL%20Style%20Sheets/Rss.xsl</D:href><D:propstat><D:prop><D:displayname>Rss.xsl</D:displayname><D:lockdiscovery/><D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock><D:getlastmodified>Wed, 30 Apr 2014 13:12:52 GMT</D:getlastmodified><D:creationdate>2014-04-30T13:12:52Z</D:creationdate><D:getcontentlength>9005</D:getcontentlength><Repl:repl-uid>rid:{92233992-AC9E-4936-A7C2-F5D97763D2F1}</Repl:repl-uid><Repl:resourcetag>rt:92233992-AC9E-4936-A7C2-F5D97763D2F1@00000000001</Repl:resourcetag><D:getetag>&quot;{92233992-AC9E-4936-A7C2-F5D97763D2F1},1&quot;</D:getetag><Office:modifiedby>SHAREPOINT\system</Office:modifiedby></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response></D:multistatus>

I assume this response is part of the webdav protocol.

When it fails, I can see this error dump in the ATOM console:

    Failed to activate package named 'tree-view' TypeError: Unable to watch path
      at HandleWatcher.start (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\pathwatcher\lib\main.js:66:29)
      at new HandleWatcher (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\pathwatcher\lib\main.js:30:12)
      at new PathWatcher (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\pathwatcher\lib\main.js:120:30)
      at Object.exports.watch (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\pathwatcher\lib\main.js:179:12)
      at Directory.module.exports.Directory.subscribeToNativeChangeEvents (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\pathwatcher\lib\directory.js:219:109)
      at c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\pathwatcher\lib\directory.js:33:24
      at c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\emissary\lib\emitter.js:133:30
      at Array.forEach (native)
      at Directory.module.exports.Emitter.emit (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\emissary\lib\emitter.js:132:47)
      at Directory.module.exports.Emitter.on (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\emissary\lib\emitter.js:50:16)
      at Directory.module.exports.Directory.watch (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\tree-view\lib\directory.js:163:49)
      at Directory.module.exports.Directory.expand (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\tree-view\lib\directory.js:215:19)
      at DirectoryView.module.exports.DirectoryView.expand (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:151:24)
      at DirectoryView.module.exports.DirectoryView.initialize (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:76:21)
      at DirectoryView.View (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\space-pen\lib\space-pen.js:135:25)
      at new DirectoryView (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:18:50)
      at TreeView.module.exports.TreeView.updateRoot (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\tree-view\lib\tree-view.js:438:21)
      at TreeView.module.exports.TreeView.initialize (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\tree-view\lib\tree-view.js:254:12)
      at TreeView.View (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\space-pen\lib\space-pen.js:135:25)
      at TreeView.ScrollView (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\src\scroll-view.js:12:47)
      at new TreeView (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\tree-view\lib\tree-view.js:41:45)
      at Object.module.exports.createView (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\tree-view\lib\tree.js:88:25)
      at Object.module.exports.activate (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\tree-view\lib\tree.js:22:14)
      at Package.module.exports.Package.activateNow (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\src\package.js:163:27)
      at c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\src\package.js:149:28
      at Package.module.exports.Package.measure (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\src\package.js:95:15)
      at Package.module.exports.Package.activate (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\src\package.js:143:14)
      at PackageManager.module.exports.PackageManager.activatePackage (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\src\package-manager.js:109:21)
      at PackageManager.module.exports.PackageManager.activatePackages (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\src\package-manager.js:98:14)
      at PackageManager.module.exports.PackageManager.activate (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\src\package-manager.js:85:19)
      at Atom.module.exports.Atom.startEditorWindow (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\src\atom.js:367:21)
      at Object.<anonymous> (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\src\window-bootstrap.js:14:8)
      at Object.<anonymous> (c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\src\window-bootstrap.js:20:4)
      at Module._compile (module.js:455:26)
      at Object.Module._extensions..js (module.js:473:10)
      at Module.load (C:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
      at Function.Module._load (module.js:311:12)
      at Module.require (module.js:363:17)
      at require (module.js:379:17)
      at window.onload (file:///C:/ProgramData/Chocolatey/lib/Atom.0.120.0/tools/Atom/resources/app/static/index.js:20:5)
     c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\src\package.js:168
    Window load time: 6218ms c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\src\window-bootstrap.js:18
    Uncaught TypeError: Unable to watch path c:\ProgramData\Chocolatey\lib\Atom.0.120.0\tools\Atom\resources\app\node_modules\pathwatcher\lib\ma…:66

If I compare the exact same operation with Notepad++, I can monitor these requests:

![image](https://cloud.githubusercontent.com/assets/184604/3733489/62d7d644-1708-11e4-9b88-33a11d005a82.png)

As you can see, Notepad++ goes a step further, and download the file.

I'm using the latest version of Atom provided by chocolatey (0.120 by now).

Let me know if I can help in any manner.

**Comment by stevebeauge** [comment]
Seems to be related to #6106

**Comment by damieng** [comment]
While I agree we shouldn't crash Atom does not support WebDAV at all so this wouldn't work.
