### ISSUE TITLE
Add note for publishing UI themes (mine got published in "packages")

### ISSUE THREAD

**Issue by keeev** [atom/atom#3347]
Hey, 

yesterday I published my first UI theme and followed all the steps in [Creating an Interface Theme](https://atom.io/docs/v0.123.0/creating-a-theme). That means I forked **atom-dark-ui** and when I tried [publishing](https://atom.io/docs/v0.123.0/publishing-a-package) my theme finally it was listed as package because some weird things happened during older commits of the forked repo. 

I would like to help others and add a note that if they have the same problems and their theme appears as package they should create a new repo and everything will work fine then. 

I hope this is the right place for telling you guys that or is there a way to contribute to the documentation directly? I found something but had no idea if it would have worked.

**Comment by melinadonati** [comment]
Please, please, please... Fix this one.

Had the problem with my first theme.  
With my first ui theme right after that.  

Look at the mess created in "packages" :   https://atom.io/users/melinadonati
And I can't even unpublish any of those "ghost" packages...

It's ugly and furthermore, even renaming the theme + theme repo + theme name in files didn't work after 3 tries (precision: working directory fully clean, an untouched clone of distant repo).

Help accepted on the unpublish problem in the waiting time...

**Comment by lee-dohm** [comment]
@melinadonati I deleted the two packages that are not backed by repositories. You should be able to unpublish the other two with the `apm unpublish` command since the repositories for them still exist. If not, let me know.

**Comment by melinadonati** [comment]
Thanks a lot lee-dohm !
I will try again to unpublish the other two, and will hopefully be successful this time.

**Comment by melinadonati** [comment]
The apm unpublish is getting me the following error :

`
Error: EINVAL, invalid argument
    at new Socket (net.js:157:18)
    at process.stdin (node.js:693:19)
    at Unpublish.module.exports.Unpublish.promptForConfirmation (C:\Users\Melina\AppData\Local\atom\app-1.7.3\resources\app\apm\lib\unpublish.js:87:48)
    at Unpublish.module.exports.Unpublish.run (C:\Users\Melina\AppData\Local\atom\app-1.7.3\resources\app\apm\lib\unpublish.js:126:21)
    at Object.module.exports.run (C:\Users\Melina\AppData\Local\atom\app-1.7.3\resources\app\apm\lib\apm-cli.js:226:32)
    at Object.<anonymous> (C:\Users\Melina\AppData\Local\atom\app-1.7.3\resources\app\apm\lib\cli.js:8:7)
    at Object.<anonymous> (C:\Users\Melina\AppData\Local\atom\app-1.7.3\resources\app\apm\lib\cli.js:19:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
`
