### ISSUE TITLE
Specs fail if editor's emitter is disposed on destroy

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom#3580]
Calling `@emitter.dispose()` from `Editor::destroyed` causes the following spec to fail:

```
>> EditorComponent
>>   hiding and showing the editor
>>     when the editor is hidden when it is mounted
>>       it defers measurement and rendering until the editor becomes visible
>>         Error: Emitter has been disposed
>>           at Emitter.module.exports.Emitter.on (/private/var/lib/jenkins/workspace/atom/node_modules/event-kit/lib/emitter.js:31:15)
>>           at Editor.module.exports.Editor.onDidChange (/private/var/lib/jenkins/workspace/atom/src/editor.coffee:208:14)
>>           at [object Object].module.exports.React.createClass.observeEditor (/private/var/lib/jenkins/workspace/atom/src/editor-component.coffee:353:23)
>>           at [object Object].boundMethod [as observeEditor] (/private/var/lib/jenkins/workspace/atom/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
>>           at [object Object].module.exports.React.createClass.componentDidMount (/private/var/lib/jenkins/workspace/atom/src/editor-component.coffee:175:6)
>>           at CallbackQueue.mixInto.notifyAll (/private/var/lib/jenkins/workspace/atom/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
>>           at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/private/var/lib/jenkins/workspace/atom/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
>>           at ReactReconcileTransaction.Mixin.closeAll (/private/var/lib/jenkins/workspace/atom/node_modules/react-atom-fork/lib/Transaction.js:214:42)
>>           at ReactReconcileTransaction.Mixin.perform (/private/var/lib/jenkins/workspace/atom/node_modules/react-atom-fork/lib/Transaction.js:155:16)
>>           at [object Object].ReactComponent.Mixin.mountComponentIntoNode (/private/var/lib/jenkins/workspace/atom/node_modules/react-atom-fork/lib/ReactComponent.js:388:19)
>>           at Object.<anonymous> (/private/var/lib/jenkins/workspace/atom/node_modules/react-atom-fork/lib/ReactMount.js:313:25)
>>           at Object._renderNewRootComponent (/private/var/lib/jenkins/workspace/atom/node_modules/react-atom-fork/lib/ReactPerf.js:57:21)
>>           at Object.ReactMount.renderComponent (/private/var/lib/jenkins/workspace/atom/node_modules/react-atom-fork/lib/ReactMount.js:379:32)
>>           at Object.renderComponent (/private/var/lib/jenkins/workspace/atom/node_modules/react-atom-fork/lib/ReactPerf.js:57:21)
>>           at new EditorView (/private/var/lib/jenkins/workspace/atom/src/editor-view.coffee:97:24)
>>           at [object Object].<anonymous> (/private/var/lib/jenkins/workspace/atom/spec/editor-component-spec.coffee:2002:27)
```

**Comment by kevinsawicki** [comment]
Closing this out, I don't think this is something we need to explicitly track.
