### ISSUE TITLE
issue in ubuntu 12.04 grunt-legacy-util while building

### ISSUE THREAD

**Issue by Chitrank-Dixit** [atom/atom#3780]
I have installed nodejs , npm and all required utilities for github atom. But when I tried building atom using the following command.

`sh script/build`

I am getting this error

``` sh
module.js:340
    throw err;
          ^
Error: Cannot find module 'grunt-legacy-util'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/chitrank/Documents/github_atom/atom/build/node_modules/grunt/lib/grunt.js:26:12)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/chitrank/Documents/github_atom/atom/build/node_modules/grunt-cli/bin/grunt:45:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:901:3

```

So I tried to install grunt-legacy-util seperately from npm sources , but then again I build it removes the grunt-legacy-utility and then throws the error grunt-legacy-util is not install stuck with this , someone please help.

**Comment by waleedsamy** [comment]
same error occur with fedora 21 using 
Node: v0.12.4
npm: v2.5.1
