### ISSUE TITLE
Cannot find module '../build/Release/git.node'

### ISSUE THREAD

**Issue by thedaniel** [atom/atom#3918]
cc #3815 

```
C:\atom [squirrel-win-updates]> .\script\build
Node: v0.10.32
npm: v1.4.28
Python: v2.7.8
Installing build modules...
Installing apm...

module.js:340
    throw err;
    ^
Error: Cannot find module '../build/Release/git.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\atom\apm\node_modules\atom-package-manager\node_modules\git-utils\lib\git.js:8:16)
    at Object.<anonymous> (C:\atom\apm\node_modules\atom-package-manager\node_modules\git-utils\lib\git.js:346:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

`npm install -g atom-package-manager` appears to succeed, but apm is not found in the path.

**Comment by kevinsawicki** [comment]
I think this can be closed out, I haven't seen this happen on CI or by anyone else building on Windows.

**Comment by Announcement** [comment]
I'm having this issue too...

**Comment by chengfanke** [comment]
I also met "Error: Cannot find module '../build/Release/runas.node' " on macOs 10.12.3 (16D32)

**Comment by karipov** [comment]
I'm having the exact same issue:
```
module.js:471
    throw err;
    ^

Error: Cannot find module '../build/Release/git.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Komron\AppData\Local\atom\app-1.23.1\resources\app\apm\node_modules\git-utils\lib\git.js:8:16)
    at Object.<anonymous> (C:\Users\Komron\AppData\Local\atom\app-1.23.1\resources\app\apm\node_modules\git-utils\lib\git.js:371:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```
Running Windows 10. This issue has been persisting whenever I try to access the packages and themes section of atom
