### ISSUE TITLE
Reverse delete consumes too many characters

### ISSUE THREAD

**Issue by ghost** [atom/atom#4026]
![rev-del-bug](https://cloud.githubusercontent.com/assets/440132/4870418/ed6416ca-6167-11e4-99e6-4166a63ff9c4.gif)

Atom 0.141.0, Mac OS 10.9.5. When using `alt-delete` to delete to end of word, I feel like the natural thing should be to erase all the whitespace in one stop, without removing any visible characters. As you can see above, if I wanted to eliminate a bunch of whitespace by hitting `alt-delete`, it eats up some of the code in the process.

**Comment by curio** [comment]
Any news on this topic?  I, too, am in the crowd of people annoyed by the default Ctrl+Del behavior.

**Comment by CaptSaltyJack** [comment]
I was working on a fix but I haven't had time lately. I hope to hop back on it soon, next month maybe. Unless someone beats me to it.

**Comment by CaptSaltyJack** [comment]
Can I upload my patch somewhere and have someone else commit this? The code is all there, works great. I still can't run package specs. Same error as above:

```
Error: Module did not self-register.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
  at Module.load (/Users/bob/github/atom/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/bob/GitHub/atom/node_modules/pathwatcher/lib/main.js:6:13)
  at Object.<anonymous> (/Users/bob/GitHub/atom/node_modules/pathwatcher/lib/main.js:207:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Users/bob/github/atom/src/babel.coffee:159:19)
  at Module.load (/Users/bob/github/atom/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/bob/GitHub/atom/src/theme-manager.coffee:6:10)
  at Object.<anonymous> (/Users/bob/GitHub/atom/src/theme-manager.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Users/bob/github/atom/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (/Users/bob/github/atom/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/bob/GitHub/atom/spec/atom-spec.coffee:5:16)
  at Object.<anonymous> (/Users/bob/GitHub/atom/spec/atom-spec.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Users/bob/github/atom/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (/Users/bob/github/atom/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at requireSpecs (/Users/bob/github/atom/spec/spec-suite.coffee:8:5)
  at Object.<anonymous> (/Users/bob/github/atom/spec/spec-suite.coffee:52:3)
  at Object.<anonymous> (/Users/bob/github/atom/spec/spec-suite.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Users/bob/github/atom/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (/Users/bob/github/atom/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at module.exports.runSpecSuite (/Users/bob/github/atom/spec/jasmine-helper.coffee:36:3)
  at Object.<anonymous> (/Users/bob/github/atom/spec/spec-bootstrap.coffee:24:3)
  at Object.<anonymous> (/Users/bob/github/atom/spec/spec-bootstrap.coffee:2:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Users/bob/github/atom/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at window.onload (file:///Users/bob/github/atom/static/index.js:51:25)
```

**Comment by dogancelik** [comment]
Please someone fix this.

**Comment by CaptSaltyJack** [comment]
I fixed it and put in a pull request which is getting rather dusty. Anyone here can feel free to go to the PR and apply a little pressure. :) https://github.com/atom/atom/pull/6086

**Comment by jhasse** [comment]
Is it correct that the current situation is that your PR has been merged but the default keybinding hasn't changed yet?

**Comment by dwelle** [comment]
@jhasse Yes, it has been merged. The default keybinding probably won't change, though, but you can do so yourself:

```
'ctrl-backspace': 'editor:delete-to-previous-word-boundary'
'ctrl-delete': 'editor:delete-to-next-word-boundary'
```

**Comment by jhasse** [comment]
Thanks for the info. Why won't the default keybinding change though?

Also adding those lines to my keymap.cson doesn't work somehow. Selecting "Delete To Previous Word Boundary" from the command palette does though.

**Comment by dwelle** [comment]
Forgot to mention you need to namespace them to `.editor`, if you didn't

```
'.editor':
    'ctrl-backspace': 'editor:delete-to-previous-word-boundary'
    'ctrl-delete': 'editor:delete-to-next-word-boundary'
```

**Comment by jhasse** [comment]
Thanks, this works :)

I see. I guess it's just an annoyance for us former Sublime Text users ;)
Btw: There's still a tiny difference left: Sublime Text apparently only deletes whitespace if it's more than one character. But I can live with Atom's behavior now.

**Comment by dwelle** [comment]
Also it seems `.editor` selector is deprecated, so use `.atom-text-editor` (I edited the comment above).

**Comment by mnquintana** [comment]
@dwelle There is no `.atom-text-editor` - it's a custom element, not a class. So it should be:

```cson
'atom-text-editor':
    'ctrl-backspace': 'editor:delete-to-previous-word-boundary'
    'ctrl-delete': 'editor:delete-to-next-word-boundary'
```

**Comment by dwelle** [comment]
Didn't notice, my bad. Although you need to also namespace to `atom-workspace` for the `ctrl-delete` to overwrite the default.

```
'atom-workspace atom-text-editor':
    'ctrl-backspace': 'editor:delete-to-previous-word-boundary'
    'ctrl-delete': 'editor:delete-to-next-word-boundary'
```

**Comment by Laufire** [comment]
I guess the issue is no just with the deletions, but with the way atom handles the selection. especially  the *non-word-characters* and *white-spaces.*

But this doesn't seem to be recognized as bug as per the [Issue 8410](https://github.com/atom/atom/issues/8410).

**Comment by tylerb** [comment]
Is there a list of bindings somewhere that will give me my `ctrl-*` movements/deletions/etc? Such as `ctrl-left` and all the others?

Also, `'ctrl-backspace': 'editor:delete-to-previous-word-boundary'` simply doesn't do anything for me. It only deletes one character. Anyone else having this issue? I'm on Mac.

**Comment by tylerb** [comment]
Figured it out. Thanks for the replies in here. If anyone is interested, I am using:

```cson
'.platform-darwin atom-workspace atom-text-editor':
  'ctrl-left': 'editor:move-to-previous-word-boundary'
  'ctrl-right': 'editor:move-to-next-word-boundary'
  'ctrl-shift-left': 'editor:select-to-previous-word-boundary'
  'ctrl-shift-right': 'editor:select-to-next-word-boundary'
  'ctrl-backspace': 'editor:delete-to-previous-word-boundary'
  'ctrl-delete': 'editor:delete-to-next-word-boundary'
```

**Comment by gustavompo** [comment]
Nice to have a "solution". This behavior should be the default. 
Sublime, Eclipse, Visual Studio/Code are just some examples of IDEs/editors that work this way.

**Comment by PhiLhoSoft** [comment]
OK, looks like I found the bug I wanted to report.
Indeed, I am used, in lot of different editors (including the one where I type this, in Firefox), to have Ctrl+Delete, when caret is at the start of an indented line (or before spaces in the middle of a line) to delete all whitespace characters up to the first non-whitespace char, not to eat also the word (or characters) after them. The current behavior is neither logical nor practical, and breaks with existing practices.
I suggest to make this a default, with some note to indicate how to go back to old behavior for those wanting it...

**Comment by efkan** [comment]
@tylerb really thank you! :+1:

**Comment by VoronaPavel** [comment]
I'm confused with the default behavior aswell, probably it's a good idea to change it.

**Comment by zachsteffens** [comment]
The keymap fix still doesn't fully solve my problem.  

`'ctrl-delete': 'editor:delete-to-next-word-boundary' `

does not remove new lines.  Any one else think this is an issue?

**Comment by PhiLhoSoft** [comment]
@zachsteffens It is probably a different issue.
At least because this "not removing new line" behavior is the default in Atom, which is another annoyance. But a different one: this thread is about deleting too much chars, not about not deleting EOL.

**Comment by PhiLhoSoft** [comment]
@zachsteffens Yes! When I am at the end of the line, and hit Ctrl+Del, I expect, with this key-binding, to delete EOL and next indentation, up to the significant start of the next line. In other words, it should properly join the two lines...

But maybe this belongs to a different issue, about this verb.

**Comment by fwuensche** [comment]
Yay! Thanks a lot! I was going crazy with this weird behaviour.

Below is my config. It just seemed more intuitive to me on a Mac:

```
'.platform-darwin atom-workspace atom-text-editor':
  'alt-left': 'editor:move-to-previous-word-boundary'
  'alt-right': 'editor:move-to-next-word-boundary'
  'alt-shift-left': 'editor:select-to-previous-word-boundary'
  'alt-shift-right': 'editor:select-to-next-word-boundary'
  'alt-backspace': 'editor:delete-to-previous-word-boundary'
  'alt-delete': 'editor:delete-to-next-word-boundary'
```

**Comment by bcorcoran** [comment]
Over a year later and `editor:delete-to-next-word-boundary` still does not delete past new lines. Any progress?

**Comment by redonwhite** [comment]
Just my 0.02 - this needs to be the default behavior! (and please fix the newline thing too).

It's hard for me to imagine a viable use case for the default behavior - delete all white space *and one more word*? Meanwhile, the alternative is super-useful for formatting, a staple tool for many, and all the other majors editors seem to be aware of.

**Comment by valtido** [comment]
wow? over 2 years with a simple task, and it ends up closing ... all that effort of reporting goes out of the window :)

shocked
