### ISSUE TITLE
Unable to watch path

### ISSUE THREAD

**Issue by toverux** [atom/atom#4262]
I'm using ST3 but I'm following the evolution of Atom, and today I tried to test Atom again.

I opened a folder, and then I tried to open a file with Ctrl+P. The console is immediately shown and I can read : `Uncaught TypeError: Unable to watch path`.

YES, I tried `sudo sysctl fs.inotify.max_user_watches=32768` :)
Obviously it doesn't works. Should I put a greater value ? Yes, I restart Atom.

By the way, after a restart Atom shows a more detailed error:

```
TypeError: Unable to watch path
  at TypeError (native)
  at HandleWatcher.start (/opt/atom/resources/app/node_modules/pathwatcher/lib/main.js:66:29)
  at new HandleWatcher (/opt/atom/resources/app/node_modules/pathwatcher/lib/main.js:30:12)
  at new PathWatcher (/opt/atom/resources/app/node_modules/pathwatcher/lib/main.js:120:30)
  at Object.exports.watch (/opt/atom/resources/app/node_modules/pathwatcher/lib/main.js:179:12)
  at File.module.exports.File.subscribeToNativeChangeEvents (/opt/atom/resources/app/node_modules/pathwatcher/lib/file.js:364:109)
  at File.module.exports.File.willAddSubscription (/opt/atom/resources/app/node_modules/pathwatcher/lib/file.js:101:14)
  at File.willAddSubscription (/opt/atom/resources/app/node_modules/pathwatcher/lib/file.js:3:61)
  at File.module.exports.File.onDidChange (/opt/atom/resources/app/node_modules/pathwatcher/lib/file.js:85:12)
  at KeymapManager.module.exports.KeymapManager.watchKeymap (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:288:74)
  at KeymapManager.module.exports.KeymapManager.loadKeymap (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:273:16)
  at KeymapManager.loadUserKeymap (/opt/atom/resources/app/src/keymap-extensions.js:37:19)
  at Atom.module.exports.Atom.startEditorWindow (/opt/atom/resources/app/src/atom.js:564:20)
  at Object.<anonymous> (/opt/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/opt/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/opt/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///opt/atom/resources/app/static/index.js:41:25)
```

**Comment by toverux** [comment]
Time have passed, that's probably no longer an issue :)
