### ISSUE TITLE
./script/grunt install --install-dir=/opt/atom  only create skeletons 

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#4285]
The content is left behind at /tmp/$USER/atom-build .

Its happening since 0.145 .

**Comment by algassimou** [comment]
@bs-ug I had the same problem with archlinux and nodejs v0.10.34.
it was a certificate problem (for more details) :
```sh
script/build  --debug --stack --verbose
```
updating nodejs (v0.10.35) solves the problem for me.

**Comment by bs-ug** [comment]
@algassimou 
Thanks, I tried another mtehod. Because installation of previous releases from source also didn't work I did so:
1. Installed clean OS.
2. Installed all mumbo-jumbo stuff (nodejs, npm and so on).
3. Installed previous release of Atom (0.145) from source - was ok, but Atom started with errors.
4. Pulled newest version and installed it (like in docs) - also was ok, but Atom started with errors.
5. Read error messages (some rights problems in .atom folder), found solution and voila, Atom started without errors.

**Comment by dideler** [comment]
Can confirm what @algassimou says.

```
$ script/build  --debug --stack --verbose
...
Fatal error: CERT_UNTRUSTED
Error: CERT_UNTRUSTED
  at SecurePair.<anonymous> (tls.js:1381:32)
  at SecurePair.emit (events.js:92:17)
  at SecurePair.maybeInitFinished (tls.js:980:10)
  at CleartextStream.read [as _read] (tls.js:472:13)
  at CleartextStream.Readable.read (_stream_readable.js:341:10)
  at EncryptedStream.write [as _write] (tls.js:369:25)
  at doWrite (_stream_writable.js:226:10)
  at writeOrBuffer (_stream_writable.js:216:5)
  at EncryptedStream.Writable.write (_stream_writable.js:183:11)
  at write (_stream_readable.js:602:24)
  at flow (_stream_readable.js:611:7)
  at Socket.pipeOnReadable (_stream_readable.js:643:5)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at emitReadable (_stream_readable.js:423:5)
  at readableAddChunk (_stream_readable.js:166:9)
  at Socket.Readable.push (_stream_readable.js:128:10)
  at TCP.onread (net.js:529:21)
```

Switching from Node 0.10.34 to **0.10.35** and then rebuilding fixed the issue :tada:

**Comment by horvan** [comment]
with node 0.136 this issue is still present on ubuntu 14.04
just a thought could grunt copy the contents of --build-dir to what --install-dir points to in addition to create the share/applications folder

I am not familiar with node js

but a simple bash command like 

cp -r /<builddir>/atom/* <installdir> should solve the problem if it is possible to copy files with grunt and declare two variable the equivalent in nodejs will solve this.

**Comment by prasoon2211** [comment]
I'm trying to build atom on Ubuntu 14.04 and getting the same problem. The error is not a certificate issue:
```
Running "download-atom-shell" task
[D] Task source: /home/prasoon/work/atom/build/node_modules/grunt-download-atom-shell/tasks/download-atom-shell-task.coffee
Verifying properties download-atom-shell.version, download-atom-shell.outputDir exist in config...OK
Fatal error: Request path contains unescaped characters.
TypeError: Request path contains unescaped characters.
  at new ClientRequest (_http_client.js:73:11)
  at TunnelingAgent.exports.request (http.js:49:10)
  at TunnelingAgent.createSocket (/home/prasoon/work/atom/build/node_modules/request/node_modules/tunnel-agent/index.js:117:25)
  at TunnelingAgent.createSecureSocket [as createSocket] (/home/prasoon/work/atom/build/node_modules/request/node_modules/tunnel-agent/index.js:184:41)
  at TunnelingAgent.addRequest (/home/prasoon/work/atom/build/node_modules/request/node_modules/tunnel-agent/index.js:80:8)
  at new ClientRequest (_http_client.js:154:16)
  at Object.exports.request (http.js:49:10)
  at Object.exports.request (https.js:136:15)
  at Request.start (/home/prasoon/work/atom/build/node_modules/request/request.js:584:30)
  at Request.end (/home/prasoon/work/atom/build/node_modules/request/request.js:1212:28)
  at /home/prasoon/work/atom/build/node_modules/request/request.js:416:12
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3
```

What should I do?

**Comment by thomasjo** [comment]
@prasoon2211 You are not experiencing the same problem. Your problem is caused by a proxy in your internetwork. See this SO question concerning the problem:
http://stackoverflow.com/questions/18006179/typeerror-request-path-contains-unescaped-characters

**Comment by prasoon2211** [comment]
Hi @thomasjo Thanks for the reply. I posted here because I was getting the error
```
nohup: failed to run command ‘/tmp/atom-build/Atom/atom’: No such file or directory
```
which a few other people are getting as well, according to this issue. And so, I ran the build script in debug mode and pasted the output here. And yes, I had already tried the SO link (and several others which mostly suggest the same thing as the link above) before posting here, all to no avail. I've even changed atom's own `.npmrc` to accomodate my proxy settings. The build is working fine for a lot of node modules until it gets stuck at the error I mentioned above.

Anyway, I was thinking of taking a look at [github.coffee](https://github.com/atom/node-github-releases/blob/master/src/github.coffee#L13)'s `getReleases` method (where the problem starts) to see if I can find the cause of this. In the meantime, any other help is greatly appreciated.

**Comment by prasoon2211** [comment]
Never mind. After much hair-pulling, I decided to do a clean install. And, it worked :laughing:

**Comment by 50Wliu** [comment]
:smile:

**Comment by varemenos** [comment]
This also happens with the packages posted in ArchLinux's AUR [atom-editor](https://aur.archlinux.org/packages/atom-editor/) [atom-editor-bin](https://aur.archlinux.org/packages/atom-editor-bin/)

**Comment by varemenos** [comment]
I've "temporary" fixed my problem by changing the $ATOM_PATH to `/usr/share/atom/atom`.

**Comment by zrax** [comment]
For those who are running into the proxy issue even when their NPM proxy is set correctly, I found a reference to [this issue](https://github.com/npm/npm/issues/4569#issuecomment-62051308) with the tunnel-agent dependency of the request module.  Modifying the request module in the build directory to depend on a newer (0.4.1) version of tunnel-agent fixed the issue and allowed me to finally successfully build atom behind a proxy.

**Comment by aronj** [comment]
This seems to work for me
```
sudo mv /usr/local/bin/atom /usr/local/bin/atom-bak
```

**Comment by aronj** [comment]
This worked for me
```
sudo mv /usr/local/bin/atom /usr/local/bin/atom-bak
```
