### ISSUE TITLE
Atom 0.152.0 (installed from official .deb file) won't start on Ubuntu 14.10

### ISSUE THREAD

**Issue by itaibh** [atom/atom#4346]
When I start it from my user, it gives me this error:

**A JavaScript error occured in the browser process**

```
Uncaught Exception:
Error: EPERM, operation not permitted '/tmp/atom.sock'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:807:18)
    at AtomApplication.module.exports.AtomApplication.deleteSocketFile (/usr/share/atom/resources/app/src/browser/atom-application.js:193:21)
    at AtomApplication.module.exports.AtomApplication.listenForArgumentsFromNewProcess (/usr/share/atom/resources/app/src/browser/atom-application.js:172:12)
    at new AtomApplication (/usr/share/atom/resources/app/src/browser/atom-application.js:88:12)
    at Socket.createAtomApplication (/usr/share/atom/resources/app/src/browser/atom-application.js:43:16)
    at Socket.emit (events.js:107:17)
    at net.js:436:14
    at process._tickCallback (node.js:378:11)
```

Once I close this message, a debug tools window launches:
![atom_debug_tools](https://cloud.githubusercontent.com/assets/140983/5234076/d9fed9d4-77bb-11e4-88c2-b371410254d6.png)

However, when I start it as root, it launches just fine. Except it is running as root, of course.

**Comment by yaunj** [comment]
The socket in /tmp also makes using atom on a multiuser system harder. There is an undocumented argument --socket-path that can be passed, but putting the socket in ~/.atom or $XDG_RUNTIME_DIR/atom by default seems like a better option than doing stuff in the shell script.

**Comment by mray** [comment]
I installed 1.16.0 from a downloaded .deb package on my Ubuntu 17.04 and also just end up with a debug window:

![image](https://cloud.githubusercontent.com/assets/164785/26299305/a8f4b2ee-3eda-11e7-8be9-92c665707ee1.png)

`apt-get purge` and installing again did not work. What can I do to use atom again?

**Comment by mray** [comment]
I found a dirty way: I un-installed atom, backed up & removed `~/.atom` and repalced */packages* and *keymap.json* from my backup again. Almost works as before again.

**Comment by 50Wliu** [comment]
There's been some fixes and improvements to the socket file since this issue was created, and there have been no further reports of it.  Closing.

@mray, if you encounter that screen in the future, please select the "Console" tab which will display the error.
