### ISSUE TITLE
Atom requires local app.js file when current folder has one (and stop loading)

### ISSUE THREAD

**Issue by gfpacheco** [atom/atom#4436]
From command line, when the current folder has an app.js file, atom tries to load it instead of the right one.

Running:
```
touch app.js
atom .
```
Doesn't output anything but also doesn't open the editor

Running:
```
echo "foo" > app.js
atom .
```
Will output:
```
[5864:1207/143634:ERROR:browser_main_loop.cc(162)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
/home/gfpacheco/Workspace/foo/app.js:1
(function (exports, require, module, __filename, __dirname) { foo
                                                              ^
ReferenceError: foo is not defined
    at Object.<anonymous> (/home/gfpacheco/Workspace/foo/app.js:1:63)
    at Module._compile (module.js:468:26)
    at Object.Module._extensions..js (module.js:486:10)
    at Module.load (module.js:363:32)
    at Function.Module._load (module.js:318:12)
    at Module.require (module.js:373:17)
    at require (module.js:392:17)
    at Object.<anonymous> (/opt/atom/resources/atom/browser/api/lib/dialog.js:11:9)
    at Object.<anonymous> (/opt/atom/resources/atom/browser/api/lib/dialog.js:150:4)
    at Module._compile (module.js:468:26)
```

I'm running v0.152.0 on Linux

**Comment by jokeyrhyme** [comment]
Just noticed this happening with the v0.190.0 RPM running Fedora 22 alpha.

```shell
env | grep NODE
```

> NODE_PATH=/home/ron/.npm-packages/lib/node_modules:

Is it because I have a colon on the end of my NODE_PATH?

**Comment by zcbenz** [comment]
@jokeyrhyme That must be the reason!

**Comment by gfpacheco** [comment]
Old issue, can't reproduce anymore
