### ISSUE TITLE
Uncaught Error: EINTR, interrupted system call

### ISSUE THREAD

**Issue by d4rkr00t** [atom/atom#4467]
Uncaught Error: EINTR, interrupted system call

**Atom Version**: 0.154.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:311

Error: EINTR, interrupted system call
  at Error (native)
  at Object.fs.closeSync (fs.js:428:18)
  at Object.fs.writeFileSync (fs.js:1024:8)
  at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:228:17)
  at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:227:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:297:21)
  at File.module.exports.File.write (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:286:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:966:17)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:954:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:585:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:511:16)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:501:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:597:56)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:287:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

**Comment by zacharytamas** [comment]
Happening for me as well occasionally while using `sshfs`. Usually after the volume has been unmounted/remounted or otherwise disrupted (computer slept, Internet connection lost, etc.)

**Comment by csnover** [comment]
Also using sshfs, also seeing this error randomly. I’ve also seen garbage `^@` characters dumped at EOF, or truncated end of a file, when this error occurs. I never had this problem with sshfs when using TextMate, Komodo Edit, or Sublime Text.

**Comment by csnover** [comment]
Oh, I am using OS X 10.9.5, sshfs from homebrew, and Atom 0.182.0.

**Comment by Cangit** [comment]
Just chiming in with my own bug report below:

1. Saving file, over ssh(fs).
2. Happens rarely.

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EINTR, interrupted system call

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:782

Error: EINTR, interrupted system call
  at Error (native)
  at Object.fs.closeSync (fs.js:472:18)
  at Object.fs.writeFileSync (fs.js:1129:8)
  at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:243:17)
  at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:239:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:309:21)
  at File.module.exports.File.write (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:298:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:970:17)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:621:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:542:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:525:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:689:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -1:29.0 editor:newline (atom-text-editor.editor)
     -1:28.8 core:paste (atom-text-editor.editor)
     -1:18.0 core:copy (atom-text-editor.editor)
     -1:14.9 core:paste (atom-text-editor.editor)
     -1:13.8 core:undo (atom-text-editor.editor)
     -1:08.9 core:paste (atom-text-editor.editor)
     -1:05.6 core:copy (atom-text-editor.editor)
     -1:03.4 core:paste (atom-text-editor.editor)
     -1:00.8 core:copy (atom-text-editor.editor)
     -1:00.0 core:paste (atom-text-editor.editor)
     -0:58.5 core:copy (atom-text-editor.editor)
     -0:56.2 core:paste (atom-text-editor.editor)
  2x -0:53.4 core:backspace (atom-text-editor.editor)
     -0:52.9 core:save (atom-text-editor.editor)
  4x -0:18.1 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:16.4 core:save (atom-text-editor.editor.is-focused)
```

**Comment by izuzak** [comment]
Reported in https://github.com/atom/atom/issues/6260 as well:

> command + S. Yes over SSHFS VM ubuntu server on my local network.
