### ISSUE TITLE
Uncaught TypeError: Array.prototype.indexOf called on null or undefined

### ISSUE THREAD

**Issue by Laragh** [atom/atom#4490]
Uncaught TypeError: Array.prototype.indexOf called on null or undefined

**Atom Version**: 0.155.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Users/Lara_Sweeney/.atom/packages/function-name-in-status-bar/lib/function-name-status-bar.coffee:10

TypeError: Array.prototype.indexOf called on null or undefined
  at indexOf (native)
  at atom-text-editor.<anonymous> (/Users/Lara_Sweeney/.atom/packages/function-name-in-status-bar/lib/function-name-status-bar.coffee:10:18)
  at atom-text-editor.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at atom-text-editor.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-text-editor.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

**Comment by benogle** [comment]
Is this still an issue?

**Comment by Laragh** [comment]
Hi, apologies ive just seen this now - no everything is fine now - thanks!
