### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/paulomcnally/develop/test/img/example_resized.png'

### ISSUE THREAD

**Issue by paulomcnally** [atom/atom#4492]
Uncaught Error: ENOENT, no such file or directory '/Users/paulomcnally/develop/test/img/example_resized.png'

**Atom Version**: 0.154.0
**System**: Mac OS X 10.10
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At fs.js:455

Error: ENOENT, no such file or directory '/Users/paulomcnally/develop/test/img/example_resized.png'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:313:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at TreeView.module.exports.TreeView.pasteEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:855:58)
  at space-pen-div.atom.commands.add.tree-view:paste (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:250:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

**Comment by benogle** [comment]
This issue was moved to atom/tree-view#316
