### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by ghost** [atom/atom#4532]
Uncaught Error: channel closed

**Atom Version**: 0.154.0
**System**: Mac OS X 10.10.1
**Thrown From**: [atom-jshint](https://github.com/Joezo/atom-jshint) package

### Steps To Reproduce

1. Continually shows a continuously growing list of these errors as I type in a JS file.

### Stack Trace

```
At events.js:85

Error: channel closed
  at ChildProcess.target.send (child_process.js:413:26)
  at AtomJsHint.module.exports.AtomJsHint.run (/Users/espressive/.atom/packages/atom-jshint/lib/atom-jshint.js:123:21)
  at /Users/espressive/.atom/packages/atom-jshint/lib/atom-jshint.js:72:16
  at later (/Applications/Atom.app/Contents/Resources/app/node_modules/scandal/node_modules/underscore/underscore.js:705:41)

```

**Comment by izuzak** [comment]
This should have been reported on atom-jshint, e.g. https://github.com/Joezo/atom-jshint/issues/105
