### ISSUE TITLE
Uncaught TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by ghost** [atom/atom#4572]
Uncaught TypeError: Cannot read property 'text' of undefined

**Atom Version**: 0.155.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core
### Steps To Reproduce
1. Editing a wordpress plugin file with a few functions (php+html)
2. Selected all the text
3. Edit > Line > Auto indent

The cmd+A didn't select all the text (some functions were collapsed). When executed the cmd+A, the functions didn't expand. Closed the file, opened it again, everything worked as expected.
### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1480

TypeError: Cannot read property 'text' of undefined
  at DisplayBuffer.module.exports.DisplayBuffer.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1480:70)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1434:20)
  at Fold.module.exports.Fold.updateDisplayBuffer (/Applications/Atom.app/Contents/Resources/app/src/fold.js:95:35)
  at Fold.module.exports.Fold.destroyed (/Applications/Atom.app/Contents/Resources/app/src/fold.js:103:19)
  at /Applications/Atom.app/Contents/Resources/app/src/fold.js:21:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:318:20)
  at Fold.module.exports.Fold.destroy (/Applications/Atom.app/Contents/Resources/app/src/fold.js:48:26)
  at DisplayBuffer.module.exports.DisplayBuffer.unfoldBufferRow (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:784:28)
  at TextEditor.module.exports.TextEditor.unfoldBufferRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2529:33)
  at TextEditor.module.exports.TextEditor.destroyFoldsIntersectingBufferRange (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2597:28)
  at Selection.module.exports.Selection.setBufferRange (/Applications/Atom.app/Contents/Resources/app/src/selection.js:116:21)
  at Selection.module.exports.Selection.selectAll (/Applications/Atom.app/Contents/Resources/app/src/selection.js:299:19)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1872:26
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2024:27
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2077:18)
  at TextEditor.module.exports.TextEditor.expandSelectionsForward (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2017:19)
  at TextEditor.module.exports.TextEditor.selectAll (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1871:19)
  at TextEditor.atom.commands.add.stopEventPropagation.core:select-all (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:322:19)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:272:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

**Comment by muchweb** [comment]
This just happened to me (Atom `0.175.0` on GNU Operating System).

---

**Steps to reproduce (reliable):**

1. Have this sample text in file:

  ```text
  for bar
  ```
2. Double click `for` to select it.
3. Double click `bar` to select it. Now you will have two 'multiple selections'.
4. Copy text to buffer <kbd>Ctrl+C</kbd>
5. Double click `for` to select it.
6. Hold <kdb>Ctrl</kdb> to add to your current selection.
7. Click between `b` and `a` in `bar` to place new cursor.
8. Double click `bar` batween `a` and `r` to whole word, not loosing a cursor within it.
9. Paste <kbd>Ctrl+P</kbd>

Enjoy your crash :smile_cat:

**Comment by benogle** [comment]
Legit repro steps. Though that creates a different trace than the original

```
Uncaught TypeError: Cannot read property 'text' of undefined

At /Users/ben/github/atom/node_modules/text-buffer/lib/history.js:124

TypeError: Cannot read property 'text' of undefined
  at /Users/ben/github/atom/src/text-editor.coffee:2609:10
  at /Users/ben/github/atom/src/text-editor.coffee:820:18
  at History.module.exports.History.transact (/Users/ben/github/atom/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Users/ben/github/atom/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Users/ben/github/atom/src/text-editor.coffee:1126:47)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Users/ben/github/atom/src/text-editor.coffee:820:6)
  at TextEditor.module.exports.TextEditor.pasteText (/Users/ben/github/atom/src/text-editor.coffee:2607:6)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.core:paste (/Users/ben/github/atom/src/text-editor-element.coffee:280:21)
  at /Users/ben/github/atom/src/text-editor-element.coffee:236:27
  at History.module.exports.History.transact (/Users/ben/github/atom/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Users/ben/github/atom/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Users/ben/github/atom/src/text-editor.coffee:1126:47)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Users/ben/github/atom/src/text-editor-element.coffee:235:15)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/ben/github/atom/src/command-registry.coffee:225:27)
  at /Users/ben/github/atom/src/command-registry.coffee:1:1
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/ben/github/atom/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/ben/github/atom/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/ben/github/atom/src/window-event-handler.coffee:126:18)

```

### Commands

```
     -1:25.5 core:save (atom-text-editor.editor.is-focused)
     -1:07.5 core:copy (atom-text-editor.editor.is-focused)
     -0:35.0 core:paste (atom-text-editor.editor.is-focused)
     -0:33.3 core:undo (atom-text-editor.editor.is-focused)
  3x -0:32.3 core:move-left (atom-text-editor.editor.is-focused)
     -0:21.4 core:copy (atom-text-editor.editor.is-focused)
     -0:01.2 core:paste (atom-text-editor.editor.is-focused)
```

**Comment by benogle** [comment]
I just got this, with a trace similar to the original.

1. Had file open with some folds
1. Switched branches on the CLI

At this point the rendering was fucked:

![screen shot 2015-03-24 at 5 36 40 pm](https://cloud.githubusercontent.com/assets/69169/6816161/9deae15e-d24c-11e4-9663-29a2da1caa48.png)

1. I went into the buffer and tried to fold all
1. This error

**Atom Version**: 0.188.0-f77b4c0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'text' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1559

TypeError: Cannot read property 'text' of undefined
  at DisplayBuffer.module.exports.DisplayBuffer.findMaxLineLength (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1559:28)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1457:12)
  at Fold.module.exports.Fold.updateDisplayBuffer (/Applications/Atom.app/Contents/Resources/app/src/fold.js:91:35)
  at Fold.module.exports.Fold.destroyed (/Applications/Atom.app/Contents/Resources/app/src/fold.js:99:19)
  at /Applications/Atom.app/Contents/Resources/app/src/fold.js:21:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:350:20)
  at Fold.module.exports.Fold.destroy (/Applications/Atom.app/Contents/Resources/app/src/fold.js:44:26)
  at LanguageMode.module.exports.LanguageMode.unfoldAll (/Applications/Atom.app/Contents/Resources/app/src/language-mode.js:137:16)
  at LanguageMode.module.exports.LanguageMode.foldAllAtIndentLevel (/Applications/Atom.app/Contents/Resources/app/src/language-mode.js:144:12)
  at TextEditor.module.exports.TextEditor.foldAllAtIndentLevel (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2608:32)
  at TextEditor.atom.commands.add.stopEventPropagation.editor:fold-at-indent-level-2 (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:530:19)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:280:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
     -5:07.3 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -5:07.1 core:delete (atom-text-editor.editor.is-focused)
     -5:06.8 core:save (atom-text-editor.editor.is-focused)
     -5:06.1 git:view-and-commit-changes (atom-text-editor.editor.is-focused)
     -4:57.6 core:confirm (git-status-list-view)
     -4:57.3 git:focus-commit-message (git-status-list-view)
     -4:52.5 editor:move-to-beginning-of-word (atom-text-editor.commit-description.editor)
     -4:49.4 editor:move-to-end-of-screen-line (atom-text-editor.commit-description.editor)
     -4:48.2 editor:select-to-beginning-of-word (atom-text-editor.commit-description.editor)
     -4:47.2 core:move-right (atom-text-editor.commit-description.editor)
     -4:44.3 core:backspace (atom-text-editor.commit-description.editor)
     -4:40.4 git:commit (atom-text-editor.commit-description.editor)
     -0:42.6 core:close (git-status-list-view)
     -0:13.7 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:13.5 pane:show-previous-item (atom-text-editor.editor)
     -0:00.6 editor:fold-at-indent-level-2 (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autosave",
      "color-picker",
      "css-color-highlighting",
      "font-viewer",
      "atom-css-comb",
      "live-archive",
      "atomatigit",
      "minimap",
      "autocomplete"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "editor": {
    "showInvisibles": true,
    "showIndentGuide": true,
    "autoIndentOnPaste": false,
    "softWrapAtPreferredLineLength": true,
    "scrollPastEnd": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v0.4.0
autocomplete-atom-api, v0.7.0
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-plus, v2.6.0
autocomplete-snippets, v1.2.0
block-travel, v1.0.2
comment-newline, v0.0.0
error-generator, v0.0.0
git, v0.0.0
language-jade, v0.3.0
welcome, v0.25.0

# Dev
autocomplete-atom-api, v0.7.0
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-snippets, v1.2.0
comment-newline, v0.0.0
feedback, v0.35.0
notifications, v0.33.0
```
