### ISSUE TITLE
Uncaught Error: Can't redo with an open transaction

### ISSUE THREAD

**Issue by amyroi** [atom/atom#4614]
Uncaught Error: Can't redo with an open transaction

**Atom Version**: 0.156.0
**System**: Mac OS X 10.10
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:91

Error: Can't redo with an open transaction
  at History.module.exports.History.redo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:91:15)
  at TextBuffer.module.exports.TextBuffer.redo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:679:27)
  at TextEditor.module.exports.TextEditor.redo (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1142:26)
  at TextEditor.atom.commands.add.stopEventPropagation.core:redo (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:307:19)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:272:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

**Comment by izuzak** [comment]
I'm going to pull @maxbrunsfeld :spades: into this old issue. Max, do you think we can close this one? I don't remember any other reports and I think you made quite a few changes to that part of text-buffer.

**Comment by maxbrunsfeld** [comment]
Yeah, this exception won't happen anymore: redo with an open transaction is allowed now.

**Comment by amyroi** [comment]
Thanks!
