### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by sventropy** [atom/atom#4618]
Uncaught TypeError: Cannot read property '0' of undefined

**Atom Version**: 0.155.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:121

TypeError: Cannot read property '0' of undefined
  at IntervalSkipList.module.exports.IntervalSkipList.adjustMarkersOnRemove (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:310:69)
  at IntervalSkipList.module.exports.IntervalSkipList.removeNode (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:293:14)
  at IntervalSkipList.module.exports.IntervalSkipList.remove (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:198:14)
  at IntervalSkipList.module.exports.IntervalSkipList.update (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:206:12)
  at Marker.module.exports.Marker.updateIntervals (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:545:37)
  at Marker.module.exports.Marker.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:495:14)
  at MarkerManager.module.exports.MarkerManager.applyPatches (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-manager.js:213:68)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:578:15)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:503:12)
  at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:600:19)
  at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:556:37)
  at Selection.module.exports.Selection.backspace (/Applications/Atom.app/Contents/Resources/app/src/selection.js:489:19)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:765:26
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:777:27
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:112:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1146:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:770:19)
  at TextEditor.module.exports.TextEditor.backspace (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:764:19)
  at TextEditor.object.(anonymous function) [as backspace] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:70:27)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.core:backspace (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:408:19)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:291:34
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:112:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1146:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:290:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

**Comment by Yajo** [comment]
<a>
        <b>
            <c>
        </b>    
    </a>

**Comment by maxbrunsfeld** [comment]
We never actually tracked this down, but the code that was throwing the exception has been completely removed and replaced with our new b-tree marker system as described in @nathansobo's [excellent blog post](http://blog.atom.io/2015/06/16/optimizing-an-important-atom-primitive.html).
