### ISSUE TITLE
Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

### ISSUE THREAD

**Issue by AdamJarvis** [atom/atom#4625]
Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

**Atom Version**: 0.155.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/invariant.js:56

Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
  at invariant (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/invariant.js:42:15)
  at [object Object].ReactBrowserComponentMixin.getDOMNode (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactBrowserComponentMixin.js:38:9)
  at [object Object].boundMethod [as getDOMNode] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
  at [object Object].module.exports.React.createClass.isVisible (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1006:19)
  at [object Object].boundMethod [as isVisible] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
  at [object Object].module.exports.React.createClass.refreshScrollbars (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1161:16)
  at [object Object].boundMethod [as refreshScrollbars] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:875:19

```

**Comment by muchweb** [comment]
Just happened on `v0.174.0`, while using <kbd>Ctrl+Space</kbd> 'auto-complete'.

**Comment by benogle** [comment]
Does it happen all the time you autocomplete? What system are you on?

**Comment by muchweb** [comment]
@benogle, no just once. I was pressing and cancelling 'autocomplete' *really* quick :smile_cat:.

I am using GNU Operating System (Archlinux distribution).

**Comment by Victorystick** [comment]
**Atom Version**: 0.176.0
**System**: Ubuntu 14.04 LTS

Happened again while using Ctrl+Space 'auto-complete', repeatedly.

## Stack Trace
```
At /opt/atom/resources/app/node_modules/react-atom-fork/lib/invariant.js:56

Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
  at invariant (/opt/atom/resources/app/node_modules/react-atom-fork/lib/invariant.js:42:15)
  at [object Object].ReactBrowserComponentMixin.getDOMNode (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactBrowserComponentMixin.js:38:9)
  at [object Object].boundMethod [as getDOMNode] (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
  at [object Object].ReactCompositeComponent.createClass.componentDidUpdate (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactDOMInput.js:101:25)
  at CallbackQueue.mixInto.notifyAll (/opt/atom/resources/app/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
  at ReactReconcileTransaction.Mixin.closeAll (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactReconcileTransaction.Mixin.perform (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at /opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19
  at ReactUpdatesFlushTransaction.NESTED_UPDATES.close (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:55:7)
  at ReactUpdatesFlushTransaction.Mixin.closeAll (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactUpdatesFlushTransaction.Mixin.perform (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.mixInto.perform (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.forceUpdate (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1232:18)
  at /opt/atom/resources/app/src/text-editor-component.js:313:28
```

**Comment by kevinsawicki** [comment]
React is no longer used since https://github.com/atom/atom/pull/5293 so this issue can be closed.
