### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by Tr4pSt3R** [atom/atom#4643]
Uncaught Error: Pane has been destroyed

**Atom Version**: 0.156.0
**System**: Mac OS X 10.9.4
**Thrown From**: Atom Core

### Steps To Reproduce

1. View
2. Panes
3. Close Panes

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:579

Error: Pane has been destroyed
  at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:579:15)
  at Pane.module.exports.Pane.focus (/Applications/Atom.app/Contents/Resources/app/src/pane.js:217:21)
  at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:53:23)

```

**Comment by ValentinGavan** [comment]
I'm having the same issue when trying to split panes a couple of times in a row. Please see bellow:

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /Users/Valentin/Downloads/Atom.app/Contents/Resources/app/src/pane.js:635

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/Users/Valentin/Downloads/Atom.app/Contents/Resources/app/src/pane.js:635:15)
    at Pane.module.exports.Pane.focus (/Users/Valentin/Downloads/Atom.app/Contents/Resources/app/src/pane.js:231:21)
    at atom-pane.<anonymous> (/Users/Valentin/Downloads/Atom.app/Contents/Resources/app/src/pane-element.js:53:23)
```

### Commands

```
  3x -8:57.9 editor:newline (atom-text-editor.editor)
     -8:57.1 core:paste (atom-text-editor.editor)
     -8:32.3 core:move-left (atom-text-editor.editor)
     -8:23.2 core:move-up (atom-text-editor.editor)
     -8:23.1 core:move-left (atom-text-editor.editor)
     -8:14.8 core:save (atom-text-editor.editor.autocomplete-active)
     -7:52.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -7:40.5 pane:split-down (atom-text-editor.editor.autocomplete-active)
     -6:36.6 pane:split-right (atom-text-editor.editor.autocomplete-active)
     -6:31.9 pane:split-down (atom-text-editor.editor.autocomplete-active)
     -6:23.2 pane:split-right (atom-text-editor.editor.autocomplete-active)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.23.0
autocomplete-plus, v2.6.0
jsformat, v0.7.18
language-twig, v1.5.2

# Dev
No dev packages
```

---------
After updating to 0.188.0 it worked better in the beginning but after a while the slipt panes command stopped working and then it crashed. Please see bellow, after the update.


**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /Users/Valentin/Downloads/Atom.app/Contents/Resources/app/src/pane.js:645

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/Users/Valentin/Downloads/Atom.app/Contents/Resources/app/src/pane.js:645:15)
    at Pane.module.exports.Pane.focus (/Users/Valentin/Downloads/Atom.app/Contents/Resources/app/src/pane.js:232:21)
    at atom-pane.<anonymous> (/Users/Valentin/Downloads/Atom.app/Contents/Resources/app/src/pane-element.js:53:23)
```

### Commands

```
     -3:59.6 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:35.5 pane:split-right (ul.list-inline.tab-bar.inset-panel)
  2x -2:30.3 pane:split-down (atom-text-editor.editor.is-focused)
     -1:55.3 pane:split-right (atom-text-editor.editor.is-focused)
     -1:50.2 pane:split-left (atom-text-editor.editor)
     -1:33.8 pane:split-down (atom-text-editor.editor.is-focused)
     -0:42.4 application:new-file (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.7.0
jsformat, v0.7.18
language-twig, v1.6.0

# Dev
No dev packages
```

**Comment by v3ss0n** [comment]
This still have problem when atom-markdown-preview is active and try to do split pane.

**Comment by bradleyflood** [comment]
Same for me using markdown-preview and split pane. Tried to close preview pane and received this said error.

**Comment by izuzak** [comment]
There are steps to reproduce this reliably for markdown-preview in https://github.com/atom/tabs/issues/108. Also https://github.com/atom/command-palette/issues/47 might be related.

/cc @benogle @nathansobo @kevinsawicki for :eyes:

**Comment by benogle** [comment]
This seems like a corner case in markdown preview. I can split the preview pane when the original file is open, but cannot split the preview pane after closing the original file. I would guess that markdown preview holds a reference to the original buffer or pane, and tries to use it when splitting the preview pane.

**Comment by 50Wliu** [comment]
Closing in favor of #8652.
