### ISSUE TITLE
Uncaught Error: spawn /Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node ENFILE

### ISSUE THREAD

**Issue by fungilation** [atom/atom#4736]
[Enter steps to reproduce below:]

1. Simply restarting atom on update

**Atom Version**: 0.165.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node ENFILE

```
At events.js:85

Error: spawn /Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node ENFILE
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

### Commands

```
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "metrics",
      "wrap-guide",
      "autosave",
      "htmlhint",
      "autoclose-html",
      "atom-handlebars",
      "font-awesome-snippetset",
      "underscorejs-snippets",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "minimap-highlight-selected",
      "minimap-selection",
      "emmet",
      "minimap",
      "angularjs",
      "autocomplete"
    ],
    "themes": [
      "seti-ui",
      "base16-tomorrow-dark-theme"
    ],
    "useReactEditor": true,
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".gitignore"
    ],
    "projectHome": "/Users/garyfung/Documents/code"
  },
  "editor": {
    "showIndentGuide": true,
    "softWrap": true,
    "preferredLineLength": 500,
    "scrollPastEnd": true,
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v2.0.14
autocomplete-paths, v0.9.0
autocomplete-plus, v1.0.0
autocomplete-snippets, v0.3.1
bezier-curve-editor, v0.6.2
color-picker, v1.2.6
html-entities, v0.2.0
javascript-snippets, v1.0.0
linter, v0.9.0
linter-coffeelint, v0.1.7
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-php, v0.0.11
linter-shellcheck, v0.0.6
meteor-api, v2.9.0
script, v2.15.1
seti-ui, v0.5.1
tabs-to-spaces, v0.8.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/atom/notifications/pull/62
