### ISSUE TITLE
Uncaught Error: Cannot find module './load-config'

### ISSUE THREAD

**Issue by ashrafuzzaman** [atom/atom#4783]
[Enter steps to reproduce below:]

1. Installed 'Atom Lint' plugin
2. Removed a semi colon in JS script to check the lint
3. It produced the following error
4. When restarted Atom, the Lint error shows properly

**Atom Version**: 0.165.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './load-config'

```
At module.js:346

Error: Cannot find module './load-config'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:380:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at /Users/newscred/.atom/packages/jshint/node_modules/lazy-req/index.js:6:43
  at lint (/Users/newscred/.atom/packages/jshint/index.js:156:34)
  at delayed (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/node_modules/lodash/dist/lodash.js:5408:27)

```

### Commands

```
     -7:06.4 settings-view:open (atom-text-editor.editor.is-focused)
     -7:03.8 core:backspace (atom-text-editor.editor.mini)
     -6:59.1 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini)
     -6:56.4 core:confirm (atom-text-editor.editor.mini)
     -6:20.2 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini)
  2x -6:19.0 core:confirm (atom-text-editor.editor.mini)
     -0:03.5 core:close (atom-text-editor.editor.mini)
     -0:02.3 pane:show-next-item (atom-text-editor.editor)
     -0:00.7 core:move-up (atom-text-editor.editor.is-focused)
     -0:00.2 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:00.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```
{
  "core": {
    "ignoredNames": [
      ".git",
      ".idea.sass-chache",
      "node_modules",
      "reports"
    ],
    "followSymlinks": true
  },
  "editor": {
    "useShadowDOM": true,
    "autoIndent": false,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-lint, v0.20.1
git-diff-details, v0.5.0
git-tab-status, v1.3.0
highlight-selected, v0.7.0
javascript-snippets, v1.0.0
js-refactor, v0.3.0
language-scala, v1.1.0
refactor, v0.4.1

# Dev
No dev packages
```

**Comment by benogle** [comment]
This is strange. Do you have [jshint](https://github.com/sindresorhus/atom-jshint) installed and enabled? Looks like the trace is coming from that, but it is not showing up in your installed packages. In any case, this is an issue with jshint.

**Comment by benogle** [comment]
This issue was moved to sindresorhus/atom-jshint#56
