### ISSUE TITLE
Uncaught Error: EINVAL, invalid argument '/Volumes/Supaku/gitroot/nodejs/zyvc/routes/admin.js'

### ISSUE THREAD

**Issue by MarkKropf** [atom/atom#4820]
I'm unable to save any file due to this error even when in safe mode:

### Stack Trace
```
Error: EINVAL, invalid argument '/Users/markkropf/Supaku/gitroot/nodejs/zyvc/views/admin/people-add.hbs'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.writeFileSync (fs.js:1011:15)
  at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:228:17)
  at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:227:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:297:21)
  at File.module.exports.File.write (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:286:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:966:17)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:954:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:585:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:511:16)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:501:19)
  at Workspace.module.exports.Workspace.saveActivePaneItemAndReportErrors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:603:44)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:593:19)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)
```

### Dev Screenshot

![image](https://cloud.githubusercontent.com/assets/1703729/5591594/dacd622a-913a-11e4-985b-477b92fd56fe.png)

**Comment by MarkKropf** [comment]
Also the read popup to open an issue is going to a link that results in a github 404: http://git.io/90Evpg

**Comment by lee-dohm** [comment]
What OS and version?

**Comment by MarkKropf** [comment]
@lee-dohm OSX 10.10.1 (14B25) Yosemite running on the latest 1.7GHz Intel Core i7 with 8GB of ram

**Comment by MarkKropf** [comment]
Not sure if it's worth keeping this open. I was able to resolve it via ejecting my SD card where I was attempting to save to and re-inserting it. Other apps were able to use it when Atom could not, maybe this is just an opportunity with more detailed error info. I can no longer reproduce this issue.

**Comment by kevinsawicki** [comment]
Yeah, I didn't see any node issues related to this when doing a quick search over on https://github.com/joyent/node

It is hard to tell via grep'ing though the node code base to determine what that error means and what circumstances it occurs in so I'm not sure a better error message can be shown until we can reproduce it and probe the error object for more details if they exist.

So I think closing it out is probably best for now, please comment if you see it happening reliably or in other cases.
