### ISSUE TITLE
Uncaught TypeError: Cannot read property 'selectToScreenPosition' of undefined

### ISSUE THREAD

**Issue by pvico** [atom/atom#4821]
[Enter steps to reproduce below:]

1. Typed **for** then TAB to create the for loop

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'selectToScreenPosition' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1828

TypeError: Cannot read property 'selectToScreenPosition' of undefined
  at TextEditor.module.exports.TextEditor.selectToScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1828:20)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:771:23
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:976:15
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:334:11

```

### Commands

```
     -2:35.8 core:confirm (input.hidden-input)
  3x -1:43.0 core:move-right (input.hidden-input)
  3x -1:33.4 core:move-down (input.hidden-input)
     -1:32.6 core:move-up (input.hidden-input)
     -1:21.9 autocomplete:toggle (input.hidden-input)
     -1:21.2 core:move-right (input.hidden-input)
     -1:20.1 core:confirm (input.hidden-input)
     -1:19.6 core:move-right (input.hidden-input)
  2x -1:15.2 core:move-down (input.hidden-input)
     -1:13.6 editor:move-to-first-character-of-line (input.hidden-input)
  3x -1:12.9 core:select-down (input.hidden-input)
     -1:11.8 core:backspace (input.hidden-input)
     -1:10.5 core:save (input.hidden-input)
     -0:24.3 editor:newline (input.hidden-input)
  2x -0:22.9 snippets:next-tab-stop (input.hidden-input)
     -0:00.0 core:save (input.hidden-input)
```

### Config

```
{
  "core": {
    "ignoredNames": [
      ".*"
    ],
    "disabledPackages": [
      "minimap"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "tabLength": 4,
    "softWrap": true,
    "preferredLineLength": 120,
    "fontSize": 11
  }
}
```

### Installed Packages

```coffee
# User
build, v0.21.0
linter, v0.9.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@pvico Can you reproduce the error reliably? If so, can you try reproducing it in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode)? Which type of file were you editing? (Python, JavaScript, ...)

**Comment by hakatashi** [comment]
I reproduced this even in safe mode.

[Enter steps to reproduce below:]

1. Disable two core packages, status-bar and bracket-mathcer. (which might likely be affected by this bug)
2. Launch atom in an empty directory by `atom --safe`
3. Create new file named `test.cpp` from tree view
4. Type 'for' and press Tab to expand
5. Press Esc (Important)
6. Press Tab again and atom freezes

**Atom Version**: 0.176.0
**System**: Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'selectToScreenPosition' of undefined

```
At c:\Users\hakatashi\AppData\Local\atom\app-0.176.0\resources\app\src\text-editor.js:1867

TypeError: Cannot read property 'selectToScreenPosition' of undefined
  at TextEditor.module.exports.TextEditor.selectToScreenPosition (c:\Users\hakatashi\AppData\Local\atom\app-0.176.0\resources\app\src\text-editor.js:1867:20)
  at c:\Users\hakatashi\AppData\Local\atom\app-0.176.0\resources\app\src\text-editor-component.js:770:23
  at c:\Users\hakatashi\AppData\Local\atom\app-0.176.0\resources\app\src\text-editor-component.js:975:15
  at c:\Users\hakatashi\AppData\Local\atom\app-0.176.0\resources\app\src\text-editor-component.js:327:11

```

### Commands

```
     -1:25.7 core:confirm (input.hidden-input)
     -1:24.0 snippets:next-tab-stop (input.hidden-input)
     -1:24.0 snippets:expand (input.hidden-input)
     -1:23.2 editor:consolidate-selections (input.hidden-input)
     -1:22.6 snippets:next-tab-stop (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "minimap",
      "jsformat",
      "language-jade",
      "autocomplete-snippets",
      "autocomplete-plus",
      "color-picker",
      "emmet",
      "bracket-matcher",
      "status-bar"
    ],
    "themes": [
      "seti-ui",
      "base16-syntax"
    ]
  },
  "editor": {
    "fontFamily": "Ricty",
    "fontSize": 14,
    "showInvisibles": true,
    "preferredLineLength": 800,
    "tabLength": 4,
    "softTabs": false,
    "useShadowDOM": false,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by QuantumPhi** [comment]
Can consistently reproduce using TeX language bindings (haven't tried for others).

```TeX
begin (+ tab)

----------

% result of above

\begin{env}

\end{env}

----------

% some other place in the document, repeat the autocomplete

begin (+ tab)

% exception thrown
```

**Comment by izuzak** [comment]
@nathansobo I was able to reproduce this in Atom 0.180.0 by following the steps in https://github.com/atom/atom/issues/4821#issuecomment-71965142.

**Comment by as-cii** [comment]
This has been fixed in [snippets v0.79](https://github.com/atom/snippets/pull/113), which is now [included by default in atom (master)](https://github.com/atom/atom/commit/1bda787e0d936500e9acebe353722f5cdd49f1a6).

**Comment by aloncarmel** [comment]
Im seeing this error again. has anyone verified this is resolved? 
![screen shot 2015-04-29 at 2 22 16 pm](https://cloud.githubusercontent.com/assets/912405/7389897/2fd77696-ee7b-11e4-894a-8469c0f01d7a.png)

**Comment by izuzak** [comment]
@aloncarmel Which version of Atom are you using and can you please provide the full output of that notification? (What you get when you click on the clipboard icon next to "View issue")
