### ISSUE TITLE
Cannot read property 'prototype' of undefined connect-redis.js

### ISSUE THREAD

**Issue by Trudko** [atom/atom#4841]
Hi,

I have reinstalled atom and installed 0.165 on windows 7 64bit. I tried this with atom --safe

When I open folder I got error Cannot find module 'socket.io' module.js:346. Does something changed in last updates?

Anyway I have installed socket.io, then I had to install redis, express, connect-redis and after that I got error:
```
Cannot read property 'prototype' of undefined c:\Users\Peter\node_modules\connect-redis\lib\connect-redis.js:121
TypeError: Cannot read property 'prototype' of undefined
at module.exports (c:\Users\Peter\node_modules\connect-redis\lib\connect-redis.js:121:41)
at Object. (c:\Users\Peter\node_modules\atom\lib\server.js:4:42)
at Module._compile (module.js:468:26)
at Object.Module._extensions..js (module.js:486:10)
at Module.load (c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
at Function.Module._load (module.js:318:12)
at Module.require (module.js:373:17)
at require (module.js:392:17)
at c:\Users\Peter\node_modules\atom\index.js:3:41
at Array.forEach (native)
at Object. (c:\Users\Peter\node_modules\atom\index.js:1:109)
at Module._compile (module.js:468:26)
at Object.Module._extensions..js (module.js:486:10)
at Module.load (c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
at Function.Module._load (module.js:318:12)
at Module.require (module.js:373:17)
at require (module.js:392:17)
at Object. (c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\node_modules\fuzzy-finder\lib\load-paths-handler.js:10:9)
at Object. (c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\node_modules\fuzzy-finder\lib\load-paths-handler.js:141:4)
at Module._compile (module.js:468:26)
at Object.Module._extensions..js (module.js:486:10)
at Module.load (c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
at Function.Module._load (module.js:318:12)
at Module.require (module.js:373:17)
at require (module.js:392:17)
at Object. (c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\src\task-bootstrap.js:95:13)
at Object. (c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\src\task-bootstrap.js:97:4)
at Module._compile (module.js:468:26)
at Object.Module._extensions..js (module.js:486:10)
at Module.load (c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
at Function.Module._load (module.js:318:12)
at Module.require (module.js:373:17)
at require (module.js:392:17)
at [eval]:3:1
at Object.exports.runInThisContext (vm.js:74:17)
at Object. ([eval]-wrapper:6:22)
at Module._compile (module.js:468:26)
at evalScript (node.js:465:25)
at startup (node.js:91:7)
at node.js:848:3
c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\src\task.js:51(anonymous function) c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\src\task.js:51(anonymous function) c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\node_modules\emissary\lib\emitter.js:155module.exports.Emitter.emitSlow c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\node_modules\emissary\lib\emitter.js:154module.exports.Emitter.emit c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\node_modules\emissary\lib\emitter.js:107(anonymous function) c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\src\task.js:69emit events.js:110handleMessage child_process.js:323channel.onread child_process.js:351
Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
at process. (c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\src\task-bootstrap.js:82:23)
at process.emit (events.js:110:17)
at handleMessage (child_process.js:323:10)
at Pipe.channel.onread (child_process.js:351:11)
c:\Users\Peter\AppData\Local\atom\app-0.165.0\resources\app\src\task.js:51
```

**Comment by benogle** [comment]
Atom does not require redis, express or socket.io.

This line: `at Object. (c:\Users\Peter\node_modules\atom\lib\server.js:4:42)` confuses me. 

What is at `c:\Users\Peter\node_modules\atom`?

**Comment by Trudko** [comment]
Sorry I bit forgot about this.  I just got same error after completely reinstalling Atom. I've delete .atom folder and also C:\Users\Peter\AppData\Roaming\Atom. Here is the content

![node-modules-content](https://cloud.githubusercontent.com/assets/3289225/6204011/43311f90-b53b-11e4-8953-4bdaae8901d9.png)

**Comment by kevinsawicki** [comment]
I believe this was fixed by https://github.com/atom/electron/issues/1390 and was an issue with having an `atom` module installed globally via `npm` and those global paths being on the require path.
