### ISSUE TITLE
Uncaught Error: spawn php_beautifier ENOENT

### ISSUE THREAD

**Issue by Choncha33** [atom/atom#4843]
[Enter steps to reproduce below:]

1. update atom from 0.100 to newest
2. restart atom
3. found a bug
4. report an issue

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn php_beautifier ENOENT

```
At events.js:85

Error: spawn php_beautifier ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

### Commands

```
  2x -0:00.0 core:backspace (input.hidden-input)
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "spell-check",
      "wrap-guide",
      "language-c",
      "language-coffee-script",
      "language-gfm",
      "language-git",
      "language-go",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-shellscript",
      "language-todo",
      "language-toml",
      "language-yaml",
      "link",
      "metrics",
      "update-package-dependencies",
      "autocomplete"
    ]
  },
  "editor": {
    "fontSize": 13,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.13.0
autocomplete-paths, v0.6.0
autocomplete-plus, v0.20.0
autocomplete-snippets, v0.2.0
color-picker, v1.2.6
command-logger, v0.20.0
linter, v0.4.7
linter-json, v0.0.1
linter-php, v0.0.11
minimap, v1.3.0
minimap-color-highlight, v0.2.0
minimap-highlight-selected, v0.1.1
project-manager, v1.14.1

# Dev
No dev packages
```

**Comment by benogle** [comment]
Please install php_beautifier installed or add it to your PATH.
