### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by gilmae** [atom/atom#4847]
Uncaught TypeError: Cannot read property 'length' of null

**Atom Version**: 0.154.0
**System**: Mac OS X 10.10.1
**Thrown From**: [status-wordcount](https://github.com/segphault/status-wordcount) package

### Steps To Reproduce

1. Create document with contents. Mine was a markdown document.
2. Toggle status-wordcount package.
3. Enter more content in document
4. Ctrl-N to create a new document.
5. Click on new document's tab.
6. Error occurs.

Error continues to occur when status-wordcount package is toggled off.

### Stack Trace

```
At /Users/gilmae/.atom/packages/status-wordcount/lib/status-wordcount-view.coffee:13

TypeError: Cannot read property 'length' of null
  at StatusWordcountView.module.exports.StatusWordcountView.updateWordCount (/Users/gilmae/.atom/packages/status-wordcount/lib/status-wordcount-view.coffee:13:43)
  at atom-workspace.<anonymous> (/Users/gilmae/.atom/packages/status-wordcount/lib/status-wordcount-view.coffee:1:1)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:110:34)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at PaneContainerView.jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at PaneContainerView.module.exports.PaneContainerView.onActivePaneItemChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-container-view.js:53:19)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container-view.js:3:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:314:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:184:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

**Comment by kevinsawicki** [comment]
This looks like an issue with the status-wordcount package, mind reopening this issue there?

https://github.com/segphault/status-wordcount/issues/new
