### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by AtmoEntity** [atom/atom#4869]
This error occurs every time I start Atom.

**Atom Version**: 0.165.0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'push' of undefined

```
At c:\Users\...\AppData\Local\atom\app-0.165.0\resources\app\node_modules\first-mate\lib\grammar.js:219

TypeError: Cannot read property 'push' of undefined
  at Grammar.module.exports.Grammar.addIncludedGrammarScope (c:\Users\...\AppData\Local\atom\app-0.165.0\resources\app\node_modules\first-mate\lib\grammar.js:219:42)
  at Pattern.module.exports.Pattern.ruleForInclude (c:\Users\...\AppData\Local\atom\app-0.165.0\resources\app\node_modules\first-mate\lib\pattern.js:162:22)
  at Pattern.module.exports.Pattern.getIncludedPatterns (c:\Users\...\AppData\Local\atom\app-0.165.0\resources\app\node_modules\first-mate\lib\pattern.js:170:21)
  at new Injections (c:\Users\...\AppData\Local\atom\app-0.165.0\resources\app\node_modules\first-mate\lib\injections.js:29:49)
  at new Grammar (c:\Users\...\AppData\Local\atom\app-0.165.0\resources\app\node_modules\first-mate\lib\grammar.js:46:25)
  at GrammarRegistry.module.exports.GrammarRegistry.createGrammar (c:\Users\...\AppData\Local\atom\app-0.165.0\resources\app\node_modules\first-mate\lib\grammar-registry.js:221:17)
  at c:\Users\...\AppData\Local\atom\app-0.165.0\resources\app\node_modules\first-mate\lib\grammar-registry.js:129:76
  at c:\Users\...\AppData\Local\atom\app-0.165.0\resources\app\node_modules\season\lib\cson.js:244:61
  at fs.js:295:14
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-monokai"
    ]
  },
  "editor": {
    "fontSize": 13,
    "fontFamily": "Consolas",
    "tabLength": 4,
    "softTabs": false
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.2.6
minimap, v3.4.9
seti-monokai, v0.3.1
seti-ui, v0.5.1
space-tab, v0.1.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
Thanks for reporting this, it will be fixed in Atom 0.167
