### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

### ISSUE THREAD

**Issue by michaeljcalkins** [atom/atom#4875]
```
Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined
c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\history.js:124
Hide Stack Trace
TypeError: Cannot read property 'getBufferPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorBufferPosition (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:1304:34)
  at c:\Users\Michael J. Calkins\.atom\packages\slash-closer\lib\slash-closer.coffee:49:22
  at Emitter.module.exports.Emitter.emit (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:590:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:503:12)
  at Selection.module.exports.Selection.insertText (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\selection.js:446:43)
  at c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:742:31
  at c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:781:27
  at History.module.exports.History.transact (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:1150:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:774:19)
  at TextEditor.module.exports.TextEditor.insertText (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:739:21)
  at TextEditor.object.(anonymous function) [as insertText] (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
  at c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor-component.js:653:23
  at History.module.exports.History.transact (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:1150:26)
  at [object Object].module.exports.React.createClass.onTextInput (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor-component.js:652:30)
  at HTMLDivElement.boundMethod (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\react-atom-fork\lib\ReactCompositeComponent.js:1295:21)
```

I was just typin away in mah css and then it froze and then this guy came up and then http://git.io/d5NEZg results in a 404.

**Comment by benogle** [comment]
Looks like this might be from slash-closer. My total wild guess is that slash-closer is calling that method on a destroyed/merged cursor or a destroyed editor.

When you reproduce the issue, you should get a button that asks you to open the issue. Click that, and the report should include a lot more information.

**Comment by michaeljcalkins** [comment]
I moved the issue over to https://github.com/postcasio/slash-closer/issues/1

**Comment by RodrigoEspinosa** [comment]
1. Open a file in Atom.
2. Modify the file in another editor.

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:128

TypeError: Cannot read property 'getBufferPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1378:34)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1744:41
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.reload (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:981:20)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1104:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:373:40
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:364:11)

```

### Commands

```
     -4:16.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -4:15.2 emmet:toggle-comment (atom-text-editor.editor.is-focused)
     -4:15.2 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -4:14.5 emmet:toggle-comment (atom-text-editor.editor.is-focused)
     -4:14.5 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -4:14.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -4:14.0 AtomPair:hide views (atom-text-editor.editor.is-focused)
     -1:48.2 editor:fold-all (atom-text-editor.editor.is-focused)
     -1:47.4 editor:unfold-current-row (atom-text-editor.editor.is-focused)
  5x -1:46.6 core:move-down (atom-text-editor.editor.is-focused)
  3x -1:45.4 core:move-up (atom-text-editor.editor.is-focused)
     -1:41.6 core:select-down (atom-text-editor.editor.is-focused)
     -1:41.2 core:backspace (atom-text-editor.editor.is-focused)
     -1:39.8 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:39.8 AtomPair:hide views (atom-text-editor.editor.is-focused)
     -1:36.2 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "atom-lint",
      "linter-pep8",
      "linter-pylint",
      "python-isort",
      "autocomplete",
      "timekeeper",
      "symbols-view",
      "vim-mode",
      "atom-spotify",
      "color-picker",
      "bower-install",
      "Tern",
      "atom-ctags",
      "atom-wield",
      "terminal-status",
      "autocomplete-jedi",
      "slack-chat",
      "web-view",
      "web-browser"
    ],
    "themes": [
      "quantum-ui",
      "quantum-syntax"
    ],
    "projectHome": "/User/rec/Documents/Projects/rec",
    "excludeVcsIgnoredPaths": false,
    "audioBeep": false
  },
  "editor": {
    "useHardwareAcceleration": false,
    "useShadowDOM": true,
    "invisibles": {},
    "fontSize": 11
  }
}
```

### Installed Packages

```coffee
# User
achievements, v0.7.0
atom-django, v0.2.1
atom-jade, v0.1.0
atom-pair, v0.37.0
atom-ternjs, v0.5.2
auto-update-packages, v0.2.2
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.0
autocomplete-snippets, v1.0.1
django-templates, v0.3.0
editorconfig, v0.3.0
emmet, v2.3.4
file-icons, v1.5.0
git-log, v0.3.0
irc, v0.2.9
language-csharp, v0.5.0
language-jade, v0.3.0
language-lua, v0.9.0
language-puppet, v0.10.0
language-restructuredtext, v0.3.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-flake8, v1.3.0
linter-jshint, v0.1.0
minimap, v4.5.0
project-manager, v1.15.5
quantum-syntax, v0.2.1
quantum-ui, v0.2.0
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```
