### ISSUE TITLE
Atom not openning files on windows 7

### ISSUE THREAD

**Issue by hanoc** [atom/atom#4884]
Hi,
I am a regular atom on mac and I tried to install and use it on windows.

With a fresh windows instalation (w7) (well I did install my [starred packages](https://atom.io/users/hanoc/stars)) I'm getting this error every time I try to open a file or a folder:
![capture](https://cloud.githubusercontent.com/assets/4996457/5641870/a39128b8-9640-11e4-8d47-a95dd9d202eb.PNG)

Atom is not starting from windows power shell in safe mode using:

    atom --safe

In fact I'm not being able to start atom from the console. My powershell recognises atom and apm as commands (and apm stars --install did work) but if I do atom foo.txt foo.txt does not get opened in atom.

If I run atom specs I get this:

    Error: Cannot find module '../lib/snippet-body-parser.coffee'
      at Module._resolveFilename (module.js:344:15)
      at Function.Module._resolveFilename (c:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\src\module-cache.js:380:52)
      at Function.Module._load (module.js:286:25)
      at Module.require (module.js:373:17)
      at require (module.js:392:17)
      at Object.<anonymous> (c:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\node_modules\snippets\spec\body-parser-spec.js:4:16)
      at Object.<anonymous> (c:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\node_modules\snippets\spec\body-parser-spec.js:40:4)
      at Module._compile (module.js:468:26)
      at Object.Module._extensions..js (module.js:486:10)
      at Module.load (c:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
      at Function.Module._load (module.js:318:12)
      at Module.require (module.js:373:17)
      at require (module.js:392:17)
      at requireSpecs (c:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\spec\spec-suite.coffee:8:5)
      at runAllSpecs (c:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\spec\spec-suite.coffee:44:3)
      at Object.<anonymous> (c:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\spec\spec-suite.coffee:55:3)
      at Object.<anonymous> (c:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\spec\spec-suite.coffee:1:1)
      at Module._compile (module.js:468:26)
      at Object.requireCoffeeScript [as .coffee] (c:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\src\coffee-cache.js:61:19)
      at Module.load (c:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
      at Function.Module._load (module.js:318:12)
      at Module.require (module.js:373:17)
      at require (module.js:392:17)
      at module.exports.runSpecSuite (c:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\spec\jasmine-helper.coffee:36:3)
      at Object.<anonymous> (c:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\spec\spec-bootstrap.coffee:24:3)
      at Object.<anonymous> (c:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\spec\spec-bootstrap.coffee:2:1)
      at Module._compile (module.js:468:26)
      at Object.requireCoffeeScript [as .coffee] (c:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\src\coffee-cache.js:61:19)
      at Module.load (c:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
      at Function.Module._load (module.js:318:12)
      at Module.require (module.js:373:17)
      at require (module.js:392:17)
      at window.onload (file:///C:/Users/nitrel/AppData/Local/atom/app-0.166.0/resources/app/static/index.js:59:25)
     index.js:73window.onload index.js:73

*Run package specs* is not opening any window.

The atom instalation did end without problems (that i know of) but it seems that something is missing.
Could you help me to discover what? Thanks!

**Comment by kevinsawicki** [comment]
Does `atom -h` and `atom -v` display output in power shell?

**Comment by hanoc** [comment]
Yes, it does:

    atom -h 

    [3576:0107/214435:INFO:CONSOLE(0)] Atom Editor v0.166.0

    Usage: atom [options] [path ...]

    One or more paths to files or folders to open may be specified.

    File paths will open in the current window.

    Folder paths will open in an existing window if that folder has already been
    opened or a new window if it hasn't.

    Environment Variables:
    ATOM_DEV_RESOURCE_PATH  The path from which Atom loads source code in dev mode.
                            Defaults to `~/github/atom`.

    Options:
      -d, --dev             Run in development mode.                                                             [boolean]
      -f, --foreground      Keep the browser process in the foreground.                                          [boolean]
      -h, --help            Print this usage message.                                                            [boolean]
      -l, --log-file        Log all output to file.                                                              [string]
      -n, --new-window      Open a new window.                                                                   [boolean]
      -r, --resource-path   Set the path to the Atom source directory and enable dev-mode.                       [string]
      -s, --spec-directory  Set the directory from which to run package specs (default: Atom's spec directory).  [string]
      --safe                Do not load packages from ~/.atom/packages or ~/.atom/dev/packages.                  [boolean]
      -t, --test            Run the specified specs and exit with error code on failures.                        [boolean]
      -v, --version         Print the version.                                                                   [boolean]
      -w, --wait            Wait for window to be closed before returning.                                       [boolean]


    atom -v
    [1564:0107/214522:INFO:CONSOLE(0)] 0.166.0

**Comment by kevinsawicki** [comment]
> Error: Cannot find module '../lib/snippet-body-parser.coffee'

This was a bug, fixed via https://github.com/atom/snippets/commit/9bdbd9c9c40b08f9e79832b53248093eb78466f1 and will be included in the next Atom release, 0.167

**Comment by lee-dohm** [comment]
Thanks @50Wliu! Closing this, let us know if it isn't fixed.

**Comment by hanoc** [comment]
Great! thanks! I'll wait for the update.

**Comment by hanoc** [comment]
I'm not sure if related or if I should open another ticket...

I tried to ugrade atom using the command palete (it said there was an upgrade available) but nothing happened.

Then I tried to uninstall it and re-install it freshly donwloaded from the website and I get this error:

		Program: Starting Squirrel Updater: --install .
		Program: Starting install, writing to C:\Users\nitrel\AppData\Local\SquirrelTemp
		CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\nitrel\AppData\Local\atom\packages\RELEASES'.
		   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
		   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
		   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
		   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
		   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
		CheckForUpdateImpl: Reading RELEASES file from C:\Users\nitrel\AppData\Local\SquirrelTemp
		CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
		ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\nitrel\AppData\Local\atom\app-0.166.0
		Utility: Starting to delete folder: C:\Users\nitrel\AppData\Local\atom\app-0.166.0
		Utility: Starting to delete folder: C:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources
		Utility: Starting to delete folder: C:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app
		Utility: Starting to delete folder: C:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\node_modules
		Utility: Starting to delete folder: C:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\node_modules\nslog
		Utility: Starting to delete folder: C:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\node_modules\oniguruma
		Utility: Starting to delete folder: C:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\node_modules\nslog\build
		Utility: Starting to delete folder: C:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\node_modules\oniguruma\build
		Utility: Starting to delete folder: C:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\node_modules\nslog\build\Release
		Utility: Starting to delete folder: C:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\node_modules\oniguruma\lib
		Utility: Starting to delete folder: C:\Users\nitrel\AppData\Local\atom\app-0.166.0\resources\app\node_modules\oniguruma\build\Release
		IEnableLogger: Failed to install package to app dir: System.UnauthorizedAccessException: Access to the path 'C:\Users\nitrel\AppData\Local\atom\app-0.166.0\atom.exe' is denied.
		   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
		   at System.IO.File.InternalDelete(String path, Boolean checkHost)
		   at System.IO.File.Delete(String path)
		   at Squirrel.Utility.<DeleteDirectory>b__2f(String file)
		   at Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
		   at System.Threading.Tasks.Task.InnerInvoke()
		   at System.Threading.Tasks.Task.Execute()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at Squirrel.Utility.<DeleteDirectory>d__36.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__86.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at Squirrel.Utility.<LogIfThrows>d__4b`1.MoveNext()
