### ISSUE TITLE
Uncaught Error: spawn osascript ENOENT

### ISSUE THREAD

**Issue by lean** [atom/atom#4887]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.166.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn osascript ENOENT

```
At events.js:85

Error: spawn osascript ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

### Commands

```
  2x -0:00.0 atom-spotify:next (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete"
    ],
    "themes": [
      "monokai-tweaked-ui",
      "monokai"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "fontFamily": "DejaVu Sans Mono",
    "showIndentGuide": true,
    "softWrap": true,
    "useShadowDOM": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-spotify, v0.6.1
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
emmet, v2.3.0
monokai, v0.9.0
monokai-tweaked-ui, v0.1.0
open-last-project, v0.1.1
react, v0.7.8

# Dev
No dev packages
```

**Comment by awesomayur** [comment]
I am getting this

**Comment by adityamandlekar** [comment]
whats a resolution here though

**Comment by armybrat78** [comment]
I am getting this error message:  'osascript' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.
