### ISSUE TITLE
v0.168.0 crashes when attempting to do right-click actions under windows

### ISSUE THREAD

**Issue by Ingramz** [atom/atom#4904]
Right click actions (such as adding a file from tree view or pasting to editor) seem to crash the application under windows 7 and 8.1 (64-bit).

**Comment by kevinsawicki** [comment]
Stack from https://github.com/atom/tree-view/issues/317

```
/C:/Atom/resources/app/static/index.js (64)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
  at exports._errnoException (util.js:746:11)
  at process.target._send (child_process.js:482:28)
  at process.target.send (child_process.js:415:12)
  at global.emit (c:\Atom\resources\app\src\task-bootstrap.js:54:22)
  at Object.console.error (c:\Atom\resources\app\src\task-bootstrap.js:20:21)
  at process.<anonymous> (c:\Atom\resources\app\src\task-bootstrap.js:67:22)
  at process.emit (events.js:107:17)
  at process._fatalException (node.js:251:26)
```
