### ISSUE TITLE
Uncaught Error: spawn undefined ENOENT

### ISSUE THREAD

**Issue by anirul** [atom/atom#4912]
Uncaught Error: spawn undefined ENOENT

**Atom Version**: 0.155.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Steps To Reproduce

1. clang_complete (probably)
2. have a .clang_complete file in the root

### Stack Trace

```
At events.js:85

Error: spawn undefined ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

**Comment by anirul** [comment]
Seams to work with Atom 0.168.0
