### ISSUE TITLE
Windows build seems successful but no binary produced

### ISSUE THREAD

**Issue by liudonghua123** [atom/atom#4918]
I run "script\build"  followed "https://github.com/atom/atom/blob/master/docs/build-instructions/windows.md", but I cann't found `Program Files` directory.
Here is my cmd execution info

E:\code\atom\atom>script\build
Node: v0.10.34
npm: v1.4.28
Python: v2.7.8
Installing build modules...
Installing apm...
Installing modules done
Deduping modules done
Running "download-atom-shell" task

E:\code\atom\atom>

**Comment by kevinsawicki** [comment]
It looks like it didn't complete, can you run `script\build --stack` to get more output?

**Comment by liudonghua123** [comment]
Well, I tried "script\build --stack", it does give me some error infomation
```
E:\code\atom\atom>script\build --stack
Node: v0.10.34
npm: v1.4.28
Python: v2.7.8
Installing build modules...
Installing apm...
Installing modules done
Deduping modules done
Running "download-atom-shell" task
Error: CERT_UNTRUSTED
  at SecurePair.<anonymous> (tls.js:1381:32)
  at SecurePair.emit (events.js:92:17)
  at SecurePair.maybeInitFinished (tls.js:980:10)
  at CleartextStream.read [as _read] (tls.js:472:13)
  at CleartextStream.Readable.read (_stream_readable.js:341:10)
  at EncryptedStream.write [as _write] (tls.js:369:25)
  at doWrite (_stream_writable.js:226:10)
  at writeOrBuffer (_stream_writable.js:216:5)
  at EncryptedStream.Writable.write (_stream_writable.js:183:11)
  at write (_stream_readable.js:602:24)
  at flow (_stream_readable.js:611:7)
  at Socket.pipeOnReadable (_stream_readable.js:643:5)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at emitReadable (_stream_readable.js:423:5)
  at readableAddChunk (_stream_readable.js:166:9)
  at Socket.Readable.push (_stream_readable.js:128:10)
  at TCP.onread (net.js:529:21)
```
But I don't know how to solve it.

**Comment by liudonghua123** [comment]
It's a bug of node v0.10.34, see [node v0.10.34 causes untrusted cert errors](https://github.com/joyent/node/issues/8894 "node v0.10.34 causes untrusted cert errors").

Just update node to v0.10.35+ to fix this problem

**Comment by liudonghua123** [comment]
Also notice that the output location of build binary is `"%ProgramFiles%\Atom"`(It's `"C:\Program Files\Atom"` for me) system path, not in the current directory.

## Instructions
  ```bat
  # Use the `Git Shell` app which was installed by GitHub for Windows. Also Make
  # sure you have logged into the GitHub for Windows GUI App.
  cd C:\
  git clone https://github.com/atom/atom/
  cd atom
  script/build # Creates application in the `"%ProgramFiles%\Atom"` directory
  ```

**Comment by kevinsawicki** [comment]
Closing this out since it was resolved as a node issue fixed by upgrading versions.
