### ISSUE TITLE
After removing minimap plugin.  Uncaught TypeError: Cannot read property 'editor' of null

### ISSUE THREAD

**Issue by gauravsaini23** [atom/atom#4945]
Uncaught TypeError: Cannot read property 'editor' of null

**Atom Version**: 0.154.0
**System**: linux 3.16.0-29-generic
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /home/gaurav/.atom/packages/minimap-selection/lib/minimap-selection-view.coffee:26

TypeError: Cannot read property 'editor' of null
  at MinimapSelectionView.module.exports.MinimapSelectionView.handleSelection (/home/gaurav/.atom/packages/minimap-selection/lib/minimap-selection-view.coffee:26:17)
  at atom-text-editor.<anonymous> (/home/gaurav/.atom/packages/minimap-selection/lib/minimap-selection-view.coffee:1:1)
  at atom-text-editor.handler (/opt/atom/resources/app/src/space-pen-extensions.js:112:34)
  at atom-text-editor.jQuery.event.dispatch (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-text-editor.elemData.handle (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app/src/command-registry.js:156:19)
  at TextEditorView.jQuery.fn.trigger (/opt/atom/resources/app/src/space-pen-extensions.js:64:23)
  at [object Object].module.exports.React.createClass.componentDidUpdate (/opt/atom/resources/app/src/text-editor-component.js:278:49)
  at CallbackQueue.mixInto.notifyAll (/opt/atom/resources/app/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
  at ReactReconcileTransaction.Mixin.closeAll (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactReconcileTransaction.Mixin.perform (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.forceUpdate (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1232:18)
  at /opt/atom/resources/app/src/text-editor-component.js:320:28

```

**Comment by mnquintana** [comment]
This is really a [minimap-selection](https://github.com/abe33/atom-minimap-selection) issue – you're getting this error because you uninstalled minimap, which is a dependency of minimap-selection, another package you have installed. minimap-selection is looking for minimap, which no longer exists because you uninstalled it.

**Comment by izuzak** [comment]
@mnquintana's explanation makes sense to me. Closing this. 

@gauravsaini23 I'd also recommend updating to a more recent version of Atom, you'll get much better exception reports.

**Comment by gauravsaini23** [comment]
@mnquintana Thanks for explanation
