### ISSUE TITLE
Uncaught Error: socket hang up

### ISSUE THREAD

**Issue by digitalian** [atom/atom#4959]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: socket hang up

```
At events.js:85

Error: socket hang up
  at createHangUpError (_http_client.js:214:15)
  at TLSSocket.socketCloseListener (_http_client.js:246:23)
  at TLSSocket.emit (events.js:129:20)
  at TCP.close (net.js:469:12)

```

### Commands

```
     -5:25.0 pane:reopen-closed-item (atom-text-editor.editor)
  2x -4:17.2 core:backspace (atom-text-editor.editor)
     -4:13.3 core:close (atom-text-editor.editor)
     -4:10.6 term2:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-unity-ui)
  2x -0:14.2 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-unity-ui)
     -0:00.0 settings-view:open (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "monokai"
    ]
  },
  "editor": {
    "fontSize": 14,
    "showInvisibles": true,
    "showIndentGuide": true,
    "autoIndentOnPaste": false,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "invisibles": {},
    "zoomFontWhenCtrlScrolling": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.1.3
color-picker, v1.2.6
git-tab-status, v1.3.0
japanese-wrap, v0.2.1
language-batch, v0.3.2
language-rspec, v0.2.1
minimap, v3.5.4
monokai, v0.9.0
term2, v0.9.4
unity-ui, v1.0.7
whitespace, v0.28.0

# Dev
No dev packages
```

**Comment by Fank** [comment]
Could you please add the steps to reproduce?

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/atom/settings-view/commit/3fe0db5dc1c7db9f936b506a126d689057a24e0d
