### ISSUE TITLE
Uncaught Error: spawn scala ENOENT

### ISSUE THREAD

**Issue by mohnishkodnani** [atom/atom#4970]
[Enter steps to reproduce below:]

1. Select Package -> Run Scala Worksheet
2. ...

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn scala ENOENT

```
At events.js:85

Error: spawn scala ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

### Commands

```
 34x -2:20.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:16.3 core:move-up (atom-text-editor.editor.is-focused)
 11x -2:15.0 core:select-right (atom-text-editor.editor.is-focused)
 11x -2:13.4 core:select-left (atom-text-editor.editor.is-focused)
     -2:10.6 core:move-down (atom-text-editor.editor.is-focused)
     -2:10.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -2:09.7 core:select-down (atom-text-editor.editor.is-focused)
  5x -2:08.3 core:select-right (atom-text-editor.editor.is-focused)
  3x -2:07.4 core:move-up (atom-text-editor.editor.is-focused)
 13x -2:05.7 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -2:03.2 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -2:02.7 core:select-right (atom-text-editor.editor.is-focused)
     -2:02.0 core:select-down (atom-text-editor.editor.is-focused)
  5x -2:01.6 core:select-up (atom-text-editor.editor.is-focused)
  3x -1:59.2 core:select-down (atom-text-editor.editor.is-focused)
     -0:00.0 scala-worksheet:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "projectHome": "/Users/mkodnani/git"
  },
  "editor": {
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
language-scala, v1.1.0
linter-scalac, v0.3.3
scala-worksheet, v0.3.4

# Dev
No dev packages
```

**Comment by benogle** [comment]
Please install the scala binary and make sure it is on your path.

**Comment by benogle** [comment]
Also, please upgrade atom to the latest version. The error message should be better for this case.
