### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=write EPROTO 140514097773056:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../../vendor/node/deps/openssl/openssl/ssl/s23_clnt.c:787:

### ISSUE THREAD

**Issue by polybuildr** [atom/atom#5004]
Steps to reproduce:

- Type a package's name in the search box in `Install packages` (from behind a proxy server).
- Numerous red box errors appear with the same error message.

**Atom Version**: 0.169.0
**System**: linux 3.13.0-43-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=write EPROTO 140514097773056:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../../vendor/node/deps/openssl/openssl/ssl/s23_clnt.c:787:

```
At stream.js:94

Error: tunneling socket could not be established, cause=write EPROTO 140514097773056:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../../vendor/node/deps/openssl/openssl/ssl/s23_clnt.c:787:

  at ClientRequest.onError (/opt/atom/resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/tunnel-agent/index.js:168:17)
  at ClientRequest.g (events.js:199:16)
  at ClientRequest.emit (events.js:107:17)
  at TLSSocket.socketErrorListener (_http_client.js:271:9)
  at TLSSocket.emit (events.js:129:20)
  at onwriteError (_stream_writable.js:290:10)
  at onwrite (_stream_writable.js:308:5)
  at WritableState.onwrite (_stream_writable.js:103:5)
  at fireErrorCallbacks (net.js:441:13)
  at TLSSocket.Socket._destroy (net.js:479:3)
  at Object.afterWrite (net.js:759:10)

```

### Commands

```
     -30:06.4 command-palette:toggle (atom-text-editor.editor)
  2x -30:05.1 core:move-down (atom-text-editor.editor.mini)
     -30:03.9 core:confirm (atom-text-editor.editor.mini)
     -30:03.9 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -30:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "remember-session",
      "emmet"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "fontFamily": "Ubuntu Mono",
    "fontSize": 18,
    "showInvisibles": true,
    "tabLength": 4,
    "softWrap": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-lint, v0.20.0
autocomplete-plus, v1.1.0
color-picker, v1.2.6
seti-syntax, v0.2.1
seti-ui, v0.5.1
view-tail-large-files, v0.1.6

# Dev
No dev packages
```

**Comment by Nittarab** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Ubuntu 16.04
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=write EPROTO

```
At stream.js:74

Error: tunneling socket could not be established, cause=write EPROTO
    at ClientRequest.onError (/usr/share/atom/resources/app.asar/node_modules/request/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:265:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at onwriteError (_stream_writable.js:304:10)
    at onwrite (_stream_writable.js:322:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:442:13)
    at TLSSocket.Socket._destroy (net.js:480:3)
    at WriteWrap.afterWrite (net.js:765:10)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "activate-power-mode",
      "minimap"
    ],
    "packagesWithKeymapsDisabled": [
      "autoclose-html"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "editor": {
    "fontSize": 15,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.10
file-icons, v1.7.7
linter, v1.11.4
wakatime, v5.0.8

# Dev
No dev packages
```
