### ISSUE TITLE
Uncaught Error: getaddrinfo ENOTFOUND avatars0.githubusercontent.com

### ISSUE THREAD

**Issue by david-byng** [atom/atom#5023]
[Enter steps to reproduce below:]

1. Open settings
2. Select install
3. Search for "highlight"

**Atom Version**: 0.170.0
**System**: linux 3.13.0-43-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: getaddrinfo ENOTFOUND avatars0.githubusercontent.com

```
At stream.js:94

Error: getaddrinfo ENOTFOUND avatars0.githubusercontent.com
  at errnoException (dns.js:41:10)
  at Object.onlookup [as oncomplete] (dns.js:91:26)

```

### Commands

```
     -7:16.5 settings-view:open (atom-pane.pane.active)
  7x -6:35.7 core:backspace (atom-text-editor.editor.mini)
     -4:15.8 core:cut (atom-text-editor.editor.mini)
  2x -4:13.9 core:paste (atom-text-editor.editor.mini)
     -3:48.3 editor:select-to-first-character-of-line (atom-text-editor.editor.mini)
     -3:48.1 core:backspace (atom-text-editor.editor.mini)
     -2:44.2 settings-view:open (atom-pane.pane.active)
     -0:45.0 core:backspace (atom-text-editor.editor.mini)
     -0:17.8 core:confirm (atom-text-editor.editor.mini)
     -0:01.2 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai-dark"
    ]
  },
  "editor": {
    "fontFamily": "monaco",
    "fontSize": 12,
    "showInvisibles": true,
    "showIndentGuide": true,
    "tabLength": 4,
    "scrollPastEnd": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-emojis, v0.7.1
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
file-icons, v1.4.5
linter, v0.10.0
linter-jshint, v0.1.0
minimap, v3.5.4
minimap-highlight-selected, v3.1.0
monokai-dark, v1.0.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
Was your internet connection working? I get a similar error if I disable my connection.

**Comment by david-byng** [comment]
It was working, and loaded results correctly. One icon next to a listed
package was a broken-username icon.
