### ISSUE TITLE
Failed to load keymap.cson and snippets.cson if empty

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#5037]
Ir looks like this has to do with the recent update to [season](https://github.com/atom/season) to stop eval'ing CSON. (Let me know if I should re-open this there.) After upgrading from 0.170.0 to 0.171.0 I got the following errors:

```
SyntaxError: Syntax error on line 39, column 23: One top level value expected
  at nodeTransforms.Block (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-safe/lib/parse.js:74:15)
  at transformNode (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-safe/lib/parse.js:199:12)
  at Object.parse (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-safe/lib/parse.js:205:12)
  at parseObject (/usr/share/atom/resources/app/node_modules/season/lib/cson.js:34:19)
  at parseContentsSync (/usr/share/atom/resources/app/node_modules/season/lib/cson.js:42:14)
  at Object.module.exports.readFileSync (/usr/share/atom/resources/app/node_modules/season/lib/cson.js:110:14)
  at KeymapManager.module.exports.KeymapManager.readKeymap (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:326:23)
  at KeymapManager.module.exports.KeymapManager.loadKeymap (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:280:43)
  at KeymapManager.loadUserKeymap (/usr/share/atom/resources/app/src/keymap-extensions.js:37:19)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:606:20)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:66:25)
```

and

```
SyntaxError: Syntax error on line 19, column 2: One top level value expected
  at nodeTransforms.Block (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-safe/lib/parse.js:74:15)
  at transformNode (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-safe/lib/parse.js:199:12)
  at Object.parse (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-safe/lib/parse.js:205:12)
  at parseObject (/usr/share/atom/resources/app/node_modules/season/lib/cson.js:34:19)
  at parseContents (/usr/share/atom/resources/app/node_modules/season/lib/cson.js:52:16)
  at /usr/share/atom/resources/app/node_modules/season/lib/cson.js:133:23
  at fs.js:295:14
  at Object.oncomplete (fs.js:93:15)
```

**Steps to reproduce:**
1. Make sure you're on Atom 0.171.0
2. Make sure `keymap.cson` and `snippets.cson` are empty except for comments (I have the default comments still)
3. Try starting / restarting Atom
4. Try saving `keymap.cson` / `snippets.cson`

**OS:** Ubuntu 14.01.1 LTS
**Atom:** 0.171.0

**Comment by kevinsawicki** [comment]
What commit did you build?

**Comment by mnquintana** [comment]
@kevinsawicki This was the tagged release of [Atom 0.171.0](https://github.com/atom/atom/tree/v0.171.0), and I just used the pre-built `.deb` package.

**Comment by kevinsawicki** [comment]
Can you open the dev tools and run `require('season/package.json').version` ?

**Comment by mnquintana** [comment]
Sure, it returns `"5.0.4"`

**Comment by kevinsawicki** [comment]
And the files are zero bytes?

**Comment by danfuzz** [comment]
I just ran into this too, v0.171 on OS X. Can confirm that my keymap.cson file is the default one which is just a big comment and no actual data.

**Comment by kevinsawicki** [comment]
Great, thanks

**Comment by mnquintana** [comment]
Not zero bytes - they just contain the default starter comments:

**keymap.cson:**
```cson
# Your keymap
#
# Atom keymaps work similarly to stylesheets. Just as stylesheets use selectors
# to apply styles to elements, Atom keymaps use selectors to associate
# keystrokes with events in specific contexts.
#
# You can create a new keybinding in this file by typing "key" and then hitting
# tab.
#
# Here's an example taken from Atom's built-in keymap:
#
# 'atom-text-editor':
#   'enter': 'editor:newline'
#
# 'atom-workspace':
#   'ctrl-shift-p': 'core:move-up'
#   'ctrl-p': 'core:move-down'
#
# You can find more information about keymaps in these guides:
# * https://atom.io/docs/latest/customizing-atom#customizing-key-bindings
# * https://atom.io/docs/latest/advanced/keymaps
#
# This file uses CoffeeScript Object Notation (CSON).
# If you are unfamiliar with CSON, you can read more about it here:
# https://github.com/bevry/cson#what-is-cson
```

**snippets.cson:**
```cson
# Your snippets
#
# Atom snippets allow you to enter a simple prefix in the editor and hit tab to
# expand the prefix into a larger code block with templated values.
#
# You can create a new snippet in this file by typing "snip" and then hitting
# tab.
#
# An example CoffeeScript snippet to expand log to console.log:
#
# '.source.coffee':
#   'Console log':
#     'prefix': 'log'
#     'body': 'console.log $1'
#
# This file uses CoffeeScript Object Notation (CSON).
# If you are unfamiliar with CSON, you can read more about it here:
# https://github.com/bevry/cson#what-is-cson
```

**Comment by kevinsawicki** [comment]
Thanks for reporting this, releasing a fix now for it

**Comment by amayer5125** [comment]
Is this bug in release 172? I still get this bug.

**Comment by kevinsawicki** [comment]
@amayer5125 We were having some CI issues yesterday with the `.rpm` build and it looks like this fix didn't make it in the 0.172 `.rpm` release.

It will be fixed in 0.173 which should be out in the next couple hours.

**Comment by AdrianTP** [comment]
My Atom seems to have auto-updated and it broke lots of things. Every startup I now get "Failed to load keymap.cson".

I'm running it on OS X 10.9.2.

**Comment by kevinsawicki** [comment]
@AdrianTP What version of Atom are you on?

**Comment by joehanko** [comment]
Hey @kevinsawicki, it doesn't seem like multiline comments are permitted in the snippets.cson, is that true? Not much experience in coffee script, but I ran into some trouble commenting out and making my snippets file more fun. #2 threw an error, any thoughts?

(1) Allowed:
```
# _    _ _______ __  __ _
#| |  | |__   __|  \/  | |
#| |__| |  | |  | \  / | |
#|  __  |  | |  | |\/| | |
#| |  | |  | |  | |  | | |____
#|_|  |_|  |_|  |_|  |_|______|
#
```
(2) Not Allowed:
```
### Some ASCII Art to make snippets more readble
 _    _ _______ __  __ _
| |  | |__   __|  \/  | |
| |__| |  | |  | \  / | |
|  __  |  | |  | |\/| | |
| |  | |  | |  | |  | | |____
|_|  |_|  |_|  |_|  |_|______|
###

'.text.html.basic':
  'Montserrat':
    'prefix': 'Google'
    'body': "<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>"
  'text':
```

**Comment by lee-dohm** [comment]
@joehanko [We're trying to control the amount of Issues that we have to triage](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
