### ISSUE TITLE
node-gyp rebiuld of minidump@0.8.0 fails with clang on debian

### ISSUE THREAD

**Issue by victorhaggqvist** [atom/atom#5041]
Just found out that the node-gyp rebiuld of minidump@0.8.0 fails on clang. Changing default `cc` and `cc+` to `gcc`.

The actual fail is `clang: error: unknown argument: '-fno-tree-sink'`.

Logs and info
```
$ ./script/build
Node: v0.10.35
npm: v1.4.28
Installing build modules...
clang: error: unknown argument: '-fno-tree-sink'
make: *** [Release/obj.target/minidump_stackwalk/deps/breakpad/src/third_party/libdisasm/ia32_implicit.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/n_node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/opt/n_node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/victor/Downloads/atmmm/build/node_modules/minidump
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! minidump@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the minidump@0.8.0 install script.
npm ERR! This is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "--userconfig=/home/victor/Downloads/atmmm/.npmrc" "install" "--quiet"
npm ERR! cwd /home/victor/Downloads/atmmm/build
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
1:36.10s total, 44.93s user, 4.38s system, 51% cpu

$ clang -v
Debian clang version 3.5.0-9 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: x86_64-pc-linux-gnu
Thread model: posix

$ node --version
 v0.10.35

$ npm --version
1.4.28

$ uname -a
Linux minos 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 GNU/Linux
```

**Comment by kevinsawicki** [comment]
Would you mind reopening this on the https://github.com/atom/node-minidump repo?

**Comment by victorhaggqvist** [comment]
Sure, here it is https://github.com/atom/node-minidump/issues/7.
