### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by rafaelstz** [atom/atom#5070]
1. Open SQL file with size 395MB
2. Not open, but show this mensage

**Atom Version**: 0.165.0
**System**: linux 3.13.0-44-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /usr/share/atom/resources/app/src/project.js:462

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/usr/share/atom/resources/app/src/project.js:462:15)
  at Project.module.exports.Project.bufferForPath (/usr/share/atom/resources/app/src/project.js:439:63)
  at Project.module.exports.Project.open (/usr/share/atom/resources/app/src/project.js:393:19)
  at Workspace.module.exports.Workspace.openUriInPane (/usr/share/atom/resources/app/src/workspace.js:482:29)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app/src/workspace.js:409:19)
  at Ipc.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
```

### Config

```
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by benogle** [comment]
See #307 to track this issue
