### ISSUE TITLE
Can't open a directory called specs

### ISSUE THREAD

**Issue by jonathanong** [atom/atom#5084]
i'm not sure what's going on here. it only happens on this directory, but if i make another directory called specs, atom opens.

i open atom by going to the folder in the terminal and typing `atom` or `atom .`.

![screen shot 2015-01-15 at 11 13 51 am](https://cloud.githubusercontent.com/assets/643505/5764594/2e7d96a6-9ca8-11e4-86db-63b5308f6a83.png)

what else do you guys need?

**Comment by 50Wliu** [comment]
What version of Atom is this?

**Comment by kevinsawicki** [comment]
Can you scroll to the top of that error displayed and copy and paste the entire text of the error into this issue?

**Comment by jonathanong** [comment]
o fuck

**Comment by jonathanong** [comment]
```
index.js:80 Error: /Users/jong/Workspace/sunsetmtn84/specs is a directory
  at new File (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:49:15)
  at TextBuffer.module.exports.TextBuffer.setPath (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:279:21)
  at new TextBuffer (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:100:14)
  at Function.module.exports.Serializable.deserialize (/Applications/Atom.app/Contents/Resources/app/node_modules/serializable/lib/serializable.js:72:22)
  at DeserializerManager.module.exports.DeserializerManager.deserialize (/Applications/Atom.app/Contents/Resources/app/src/deserializer-manager.js:56:29)
  at /Applications/Atom.app/Contents/Resources/app/src/project.js:128:35
  at Array.map (native)
  at Project.module.exports.Project.deserializeParams (/Applications/Atom.app/Contents/Resources/app/src/project.js:127:39)
  at Function.module.exports.Serializable.deserialize (/Applications/Atom.app/Contents/Resources/app/node_modules/serializable/lib/serializable.js:58:25)
  at DeserializerManager.module.exports.DeserializerManager.deserialize (/Applications/Atom.app/Contents/Resources/app/src/deserializer-manager.js:56:29)
  at Atom.module.exports.Atom.deserializeProject (/Applications/Atom.app/Contents/Resources/app/src/atom.js:725:52)
  at Atom.module.exports.Atom.deserializeEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:753:12)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:603:12)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:66:25)
index.js:80 window.onload
```

**Comment by jonathanong** [comment]
0.173.0

**Comment by jonathanong** [comment]
--safe didn't work

**Comment by kevinsawicki** [comment]
Can you run `atom.constructor.getStatePath('editor')` from the console tab of the dev tools and see what path that prints out, and then delete that path on disk and re-open atom?

**Comment by jonathanong** [comment]
```
"/Users/jong/.atom/storage/editor-40a591882dd3329fcfa111b38d774f43dbe666aa"
```

:+1: it works!
