### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by frank-hexiang** [atom/atom#5087]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.172.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /Applications/Atom.app/Contents/Resources/app/src/project.js:360

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/Applications/Atom.app/Contents/Resources/app/src/project.js:360:15)
  at Project.module.exports.Project.bufferForPath (/Applications/Atom.app/Contents/Resources/app/src/project.js:337:63)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app/src/project.js:291:19)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:487:29)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:414:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 18,
    "showInvisibles": true,
    "showIndentGuide": true,
    "tabLength": 4,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v1.1.0
minimap, v3.5.4
vim-mode, v0.26.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
See #307 to track this issue

**Comment by mark-hahn** [comment]
** Off-topic not relating to this particular issue submission ...

There are two weird things about these repetitive 2MB error reports. There
must be dozens of them.

One is that they are obviously not bugs but a limitation.  The second is
that surely these can be found by searching the issues here.

Maybe Atom should put up a dialog saying this is a current known limitation
and "do not submit an issue".  It doesn't really make sense to throw an
exception.

Anyone want a PR for this idea?

**Comment by kevinsawicki** [comment]
> Anyone want a PR for this idea?

0.173 include a better error notification linking directly to the issue, see #4906 for the details.
