### ISSUE TITLE
Uncaught Error: socket hang up

### ISSUE THREAD

**Issue by TheSeamau5** [atom/atom#5094]
[Enter steps to reproduce below:]

1. Have flaky internet connection
2. Go to Settings > Install

Comes along with issue #5093 

**Atom Version**: 0.170.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: socket hang up

```
At events.js:85

Error: socket hang up
  at createHangUpError (_http_client.js:214:15)
  at TLSSocket.socketCloseListener (_http_client.js:246:23)
  at TLSSocket.emit (events.js:129:20)
  at TCP.close (net.js:469:12)

```

### Commands

```
     -6:41.4 core:move-right (atom-text-editor.editor)
     -6:39.0 core:move-left (atom-text-editor.editor)
     -6:32.0 core:move-right (atom-text-editor.editor)
     -6:31.2 editor:newline (atom-text-editor.editor)
  5x -6:18.0 core:move-right (atom-text-editor.editor)
  2x -6:13.7 core:save (atom-text-editor.editor)
  2x -6:05.9 core:backspace (atom-text-editor.editor)
  2x -6:05.2 core:save (atom-text-editor.editor)
     -0:28.2 tree-view:toggle (div.settings-view.pane-item)
 67x -0:00.0 core:backspace (atom-text-editor#editor.fontFamily.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-gjslint",
      "linter",
      "linter-dartanalyzer"
    ]
  },
  "editor": {
    "fontFamily": "Source Code Pro, Menlo, monospace",
    "fontSize": 18,
    "autoIndentOnPaste": false,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
atom-typescript-tools, v0.5.2
autoclose-html, v0.13.0
autocomplete-plus, v1.1.0
better-language-dart, v1.0.1
color-picker, v1.2.6
dart-tools, v0.8.5
language-ada, v0.2.0
language-coq, v0.1.0
language-css-plus, v0.3.0
language-d, v3.0.0
language-elm, v0.4.1
language-glsl, v0.2.2
language-julia, v2.0.0
language-opencl, v0.1.0
language-pegjs, v0.5.0
language-r, v0.1.1
language-sml, v0.2.0
language-typescript, v0.15.0
language-x86, v0.1.0
linter-csslint, v0.0.11
minimap, v3.5.5

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
This should be fixed in the latest release, 0.174
