### ISSUE TITLE
On Windows 7, if you right-click on a file, then a stack trace is returned

### ISSUE THREAD

**Issue by wluu** [atom/atom#5098]
1. In Atom, open a file
2. Right-click on the file
3. Then, wait for below error to appear

**Atom Version**: 0.174.0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: Atom Core

### Stack Trace

Uncaught SyntaxError: Failed to execute 'webkitMatchesSelector' on 'Element': '`atom-workspace atom-text-editor:not(.mini)' is not a valid selector.

```
At c:\Users\Wilson\AppData\Local\atom\app-0.174.0\resources\app\src\context-menu-manager.js:95

Error: Failed to execute 'webkitMatchesSelector' on 'Element': '`atom-workspace atom-text-editor:not(.mini)' is not a valid selector.
  at Error (native)
  at c:\Users\Wilson\AppData\Local\atom\app-0.174.0\resources\app\src\context-menu-manager.js:95:32
  at Array.filter (native)
  at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (c:\Users\Wilson\AppData\Local\atom\app-0.174.0\resources\app\src\context-menu-manager.js:94:42)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (c:\Users\Wilson\AppData\Local\atom\app-0.174.0\resources\app\src\context-menu-manager.js:165:27)
  at HTMLDocument.<anonymous> (c:\Users\Wilson\AppData\Local\atom\app-0.174.0\resources\app\src\window-event-handler.js:141:33)
  at HTMLDocument.handler (c:\Users\Wilson\AppData\Local\atom\app-0.174.0\resources\app\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (c:\Users\Wilson\AppData\Local\atom\app-0.174.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (c:\Users\Wilson\AppData\Local\atom\app-0.174.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
  2x -0:00.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "audioBeep": false
  },
  "editor": {
    "fontSize": 14,
    "autoIndent": false,
    "autoIndentOnPaste": false,
    "tabLength": 4,
    "softWrap": true,
    "confirmCheckoutHeadRevision": false,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
go-plus, v3.0.13

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Can you reproduce this in safe mode (`atom --safe`)?

**Comment by kevinsawicki** [comment]
This is mostly a package that has a context menu with an invalid selector in it.

This case should be handled more gracefully and not throw an uncaught error.

**Comment by wluu** [comment]
@50Wliu It's going to take some time for me to try to reproduce this issue in safe mode since I'll be away from my Windows machine over the weekend. But, I'll try to reproduce it once I get back.

**Comment by benogle** [comment]
Yeah, there's a backtick in the selector. No bueno.

**Comment by wluu** [comment]
@50Wliu Was not able to reproduce this issue in safe mode. Right-click on a folder works fine in safe mode.

**Comment by benogle** [comment]
@wluu My guess is that it is the go-plus package causing this. Try disabling it and right clicking again.

**Comment by wluu** [comment]
@benogle Disabled go-plus package, restarted atom, and still was able to reproduce the same stack trace.
