### ISSUE TITLE
Uncaught Error: EPERM, operation not permitted when opening a readonly file

### ISSUE THREAD

**Issue by pboudoin** [atom/atom#5102]
1. ... Open a file with atom which is read only
2. ... Get an error alert 

**Atom Version**: 0.174.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM, operation not permitted 'e:\****\myFile.js'

```
At c:\Users\***\AppData\Local\atom\app-0.174.0\resources\app\src\workspace.js:504

Error: EPERM, operation not permitted 'e:\****\myFile.js'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (c:\Users\***\AppData\Local\atom\app-0.174.0\resources\atom\common\lib\asar.js:422:20)
  at Project.module.exports.Project.open (c:\Users\***\AppData\Local\atom\app-0.174.0\resources\app\src\project.js:287:31)
  at Workspace.module.exports.Workspace.openURIInPane (c:\Users\***\AppData\Local\atom\app-0.174.0\resources\app\src\workspace.js:492:31)
  at Workspace.module.exports.Workspace.open (c:\Users\***\AppData\Local\atom\app-0.174.0\resources\app\src\workspace.js:418:19)
  at Ipc.<anonymous> (c:\Users\***\AppData\Local\atom\app-0.174.0\resources\app\src\window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (c:\Users\***\AppData\Local\atom\app-0.174.0\resources\atom\renderer\api\lib\ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by pboudoin** [comment]
It seems you try to open the file with 'r+' flag in the Project.prototype.open()

fs.openSync (fs.js:455)
module.(anonymous function) (c:\Users\p1z\Ap…ib\asar.js:422)
module.exports.Project.open (c:\Users\p1z\Ap…project.js:287)
module.exports.Workspace.openURIInPane (c:\Users\p1z\Ap…rkspace.js:492)
module.exports.Workspace.open (c:\Users\p1z\Ap…rkspace.js:418)
module.exports.TreeView.openSelectedEntry (c:\Users\p1z\Ap…ee-view.js:639)
module.exports.TreeView.entryClicked (c:\Users\p1z\Ap…ee-view.js:383)
(anonymous function) (c:\Users\p1z\Ap…ee-view.js:171)
jQuery.event.dispatch (c:\Users\p1z\Ap…dules\at…:4676)
elemData.handle (c:\Users\p1z\Ap…dules\at…:4360)
