### ISSUE TITLE
Uncaught Error: EBUSY, resource busy or locked 'c:\code\ta.mobile\Source\TAMobile6Simulator\bin\Debug\TrackAbout.Mobile.Log'

### ISSUE THREAD

**Issue by ronrat** [atom/atom#5112]
[Enter steps to reproduce below:]

Attempting to open a log file that is open for write by the logging app. I was able to open the same file in Notepad and Sublime Text.

**Atom Version**: 0.174.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EBUSY, resource busy or locked 'c:\code\ta.mobile\Source\TAMobile6Simulator\bin\Debug\TrackAbout.Mobile.Log'

```
At c:\Users\rratzlaff\AppData\Local\atom\app-0.174.0\resources\app\src\workspace.js:504

Error: EBUSY, resource busy or locked 'c:\code\ta.mobile\Source\TAMobile6Simulator\bin\Debug\TrackAbout.Mobile.Log'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (c:\Users\rratzlaff\AppData\Local\atom\app-0.174.0\resources\atom\common\lib\asar.js:422:20)
  at Project.module.exports.Project.open (c:\Users\rratzlaff\AppData\Local\atom\app-0.174.0\resources\app\src\project.js:287:31)
  at Workspace.module.exports.Workspace.openURIInPane (c:\Users\rratzlaff\AppData\Local\atom\app-0.174.0\resources\app\src\workspace.js:492:31)
  at Workspace.module.exports.Workspace.open (c:\Users\rratzlaff\AppData\Local\atom\app-0.174.0\resources\app\src\workspace.js:418:19)
  at Ipc.<anonymous> (c:\Users\rratzlaff\AppData\Local\atom\app-0.174.0\resources\app\src\window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (c:\Users\rratzlaff\AppData\Local\atom\app-0.174.0\resources\atom\renderer\api\lib\ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
     -0:45.1 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:44.6 core:paste (atom-text-editor.editor.mini)
  4x -0:40.4 core:move-down (atom-text-editor.editor.mini)
     -0:39.6 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 core:copy (atom-text-editor.editor)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
autocomplete-plus-async, v0.22.0
color-picker, v1.3.0
language-csharp, v0.3.0
language-mediawiki, v0.1.0
language-powershell, v0.6.6
linter, v0.10.0
minimap, v3.5.6
omnisharp-atom, v0.1.6
project-manager, v1.14.1

# Dev
No dev packages
```

**Comment by VarLong** [comment]
How about 
Run: npm cache clean  
Run: npm install
