### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by ankurpshah** [atom/atom#5113]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.170.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /Applications/Atom.app/Contents/Resources/app/src/project.js:360

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/Applications/Atom.app/Contents/Resources/app/src/project.js:360:15)
  at Project.module.exports.Project.bufferForPath (/Applications/Atom.app/Contents/Resources/app/src/project.js:337:63)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app/src/project.js:291:19)
  at Workspace.module.exports.Workspace.openUriInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:487:29)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:414:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
better-language-dart, v1.0.1
color-picker, v1.2.6
dart-tools, v0.8.5
git-log, v0.2.0
jsformat, v0.7.18
language-dart, v0.1.1
language-scala, v1.1.0
linter, v0.9.1
linter-scalac, v0.3.3
minimap, v3.5.3
pretty-json, v0.3.1
remote-sync, v2.3.1
scala-format, v0.1.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please upgrade to the latest Atom version (currently 0.174.0) to experience a better warning message for this.  You might also want to subscribe to #307 for updates to this issue.
