### ISSUE TITLE
Uncaught TypeError: Unable to watch path

### ISSUE THREAD

**Issue by zchan0** [atom/atom#5121]
Uncaught TypeError: Unable to watch path

**Atom Version**: 0.162.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core
### Steps To Reproduce
1. ...
2. ...
### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:66

TypeError: Unable to watch path
  at TypeError (native)
  at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:66:29)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:43:25
  at Object.oncomplete (fs.js:93:15)

```

**Comment by lee-dohm** [comment]
You might want to update to the latest version of Atom. I think these error messages have been improved in more recent versions.

**Comment by jasonmit** [comment]
I am on 0.174.0 Linux (official deb bins)  and still seeing this.

**Comment by jvanoli** [comment]
Hi, I'm facing this issue when opening files on a network folder (\\vboxsvr\vagrant), it also fails to open files trough the "mapped" folder C:\vagrant (this is a VritualBox feature that links a folder with the share)
Updated today to version 0.1.7.6.0 and still fails.

Thanks,

**Comment by lee-dohm** [comment]
If this is always in reference to being unable to watch network paths, there are other issues open to cover that: #4849 and atom/node-pathwatcher#39 for example.

**Comment by yzuniversal** [comment]
I'm on Ubuntu 14.04 LTS, with most recent version of Atom, and have experienced this problem. I haven't seen this mentioned here so just wanted to add that the bug only seems to occur when running Atom as a regular user. When run as a superuser from terminal, Atom seems to work normal.

**Comment by curtiszimmerman** [comment]
I am using Linux Mint 17, version 0.177.0. All I did was save an untitled file to a new directory (though the untitled window was the left pane of a two-pane window, and the right pane contained an untitled file as well). I did not try to reproduce this issue. Here are my details:

**Atom Version**: 0.177.0
**System**: linux 3.13.0-35-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Unable to watch path

```
At /usr/share/atom/resources/app/src/workspace.js:710

TypeError: Unable to watch path
  at TypeError (native)
  at HandleWatcher.start (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:66:29)
  at new HandleWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:30:12)
  at new PathWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:120:30)
  at Object.exports.watch (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:179:12)
  at File.module.exports.File.subscribeToNativeChangeEvents (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:399:109)
  at File.module.exports.File.write (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:296:14)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:970:17)
  at TextEditor.module.exports.TextEditor.saveAs (/usr/share/atom/resources/app/src/text-editor.js:624:26)
  at Pane.module.exports.Pane.saveItemAs (/usr/share/atom/resources/app/src/pane.js:554:14)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:542:21)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app/src/pane.js:522:19)
  at Workspace.module.exports.Workspace.saveActivePaneItemAndReportErrors (/usr/share/atom/resources/app/src/workspace.js:689:44)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app/src/workspace.js:679:19)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:21.7 core:delete (atom-text-editor.editor.is-focused)
     -0:19.8 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:18.2 autocomplete-plus:cancel (input)
     -0:17.2 core:backspace (atom-text-editor.editor.is-focused)
     -0:15.4 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "destroyEmptyPanes": false
  },
  "editor": {
    "fontSize": 11,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v1.1.0
go-plus, v3.0.13
gofmt, v0.2.0
linter, v0.10.0
minimap, v3.5.4

# Dev
No dev packages
```

**Comment by curtiszimmerman** [comment]
Incidentally, this issue-tracking feature of Atom is definitely in my top three favorite things about this editor. Awesome!

**Comment by benogle** [comment]
> this issue-tracking feature of Atom is definitely in my top three favorite things about this editor

:heart: 

The issue discovery has evolved over several versions. So the fact that you got to one of them is a plus.

**Comment by curtiszimmerman** [comment]
Haha @benogle that made me laugh. :) Totally understood!

On this issue, for some reason I am now unable to open any file in Atom due to this error. I've had a rough day and I can't really remember if I did anything (but nothing memorable, just got home and fired up Atom for some evening programming). Here's a slightly different stack trace:

**Atom Version**: 0.177.0
**System**: linux 3.13.0-35-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Unable to watch path

```
At /usr/share/atom/resources/app/src/workspace.js:510

TypeError: Unable to watch path
  at TypeError (native)
  at HandleWatcher.start (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:66:29)
  at new HandleWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:30:12)
  at new PathWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:120:30)
  at Object.exports.watch (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:179:12)
  at File.module.exports.File.subscribeToNativeChangeEvents (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:399:109)
  at File.module.exports.File.willAddSubscription (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:108:14)
  at File.willAddSubscription (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:3:61)
  at File.module.exports.File.onDidChange (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:88:12)
  at TextBuffer.module.exports.TextBuffer.subscribeToFile (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1089:44)
  at TextBuffer.module.exports.TextBuffer.setPath (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:281:14)
  at new TextBuffer (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:100:14)
  at Project.module.exports.Project.buildBuffer (/usr/share/atom/resources/app/src/project.js:381:16)
  at Project.module.exports.Project.bufferForPath (/usr/share/atom/resources/app/src/project.js:355:63)
  at Project.module.exports.Project.open (/usr/share/atom/resources/app/src/project.js:309:19)
  at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app/src/workspace.js:492:31)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app/src/workspace.js:418:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:45:32)
  at EventEmitter.emit (events.js:119:17)
```

### Commands

```
     -0:10.2 application:open-file (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "vim-mode"
    ]
  },
  "editor": {
    "fontSize": 11,
    "tabLength": 4,
    "invisibles": {},
    "showInvisibles": true,
    "softTabs": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.0
color-picker, v1.4.4
go-plus, v3.1.3
gofmt, v0.2.0
language-docker, v1.1.2
linter, v0.11.1
minimap, v4.1.0
save-session, v0.11.5

# Dev
No dev packages
```

### (And here are commands from a previous attempt to open files):

```
     -1:22.5 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:33.7 application:open-file (atom-text-editor.editor.is-focused)
```

**Comment by curtiszimmerman** [comment]
And just to follow up. This morning when I got into the office, I fired up Atom and I'm not getting the error any longer (and can open files and use the editor as normal). I tried disabling a bunch of packages, rebooting a couple of times in the process, and still had this error. The only thing I can think of is that here at the office I'm using an external laptop dock that feeds four monitors, and at home I'm just using the laptop display. This has caused some issues previously, so if this actually is the source of the problem, it very likely has little to do with Atom. I'll try to remember to update this evening when I get back to the house.

**Comment by curtiszimmerman** [comment]
Interesting. So I had the same problem when I started using the regular display versus using multiple displays via the laptop dock at the office (giving the same ish stack trace), but this time some of the errors referred to [this document](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#typeerror-unable-to-watch-path) instructing users to increase `fs.inotify.max_user_watches` from ~8k to ~32k. I hadn't been directed to this before, and followed the instructions there. I closed Atom and restarted it, and now am able to use the editor. Interesting that I hadn't run across that solution before despite some research. According to the linked document, this issue affects Linux users, so give it a try and see if that works.

**Comment by mrtdoulaty** [comment]
I'm having this problem using 0.179.0 on Fedora (I used official rpm package to install)
(the path is a network path)

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.179.0
**System**: linux 3.18.5-101.fc20.x86_64
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Unable to watch path

```
At /usr/share/atom/resources/app/src/workspace.js:510

TypeError: Unable to watch path
  at TypeError (native)
  at HandleWatcher.start (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:66:29)
  at new HandleWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:30:12)
  at new PathWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:120:30)
  at Object.exports.watch (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:179:12)
  at File.module.exports.File.subscribeToNativeChangeEvents (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:399:109)
  at File.module.exports.File.willAddSubscription (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:108:14)
  at File.willAddSubscription (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:3:61)
  at File.module.exports.File.onDidChange (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:88:12)
  at TextBuffer.module.exports.TextBuffer.subscribeToFile (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1089:44)
  at TextBuffer.module.exports.TextBuffer.setPath (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:281:14)
  at new TextBuffer (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:100:14)
  at Project.module.exports.Project.buildBuffer (/usr/share/atom/resources/app/src/project.js:381:16)
  at Project.module.exports.Project.bufferForPath (/usr/share/atom/resources/app/src/project.js:355:63)
  at Project.module.exports.Project.open (/usr/share/atom/resources/app/src/project.js:309:19)
  at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app/src/workspace.js:492:31)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app/src/workspace.js:418:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:45:32)
  at EventEmitter.emit (events.js:119:17)

```

### Commands

```
     -0:51.6 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:37.7 tree-view:collapse-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:37.4 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:37.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:36.5 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:20.6 tree-view:collapse-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:20.4 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:19.9 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:19.5 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:18.7 tree-view:collapse-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:18.5 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:16.6 tree-view:collapse-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -0:16.5 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -0:15.6 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:15.0 tree-view:collapse-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:14.2 application:open-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "scrollPastEnd": true,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.6
linter-python-pyflakes, v0.1.0

# Dev
No dev packages
```

**Comment by Enkouyami** [comment]
I'm also having this problem on Linux Mint 17.1 when trying to open files from the partition my OS is installed on my laptop.

**Atom Version**: 0.182.0
**System**: linux 3.13.0-37-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Unable to watch path

```
At /opt/atom/resources/app/src/workspace.js:508

TypeError: Unable to watch path
  at TypeError (native)
  at HandleWatcher.start (/opt/atom/resources/app/node_modules/pathwatcher/lib/main.js:66:29)
  at new HandleWatcher (/opt/atom/resources/app/node_modules/pathwatcher/lib/main.js:30:12)
  at new PathWatcher (/opt/atom/resources/app/node_modules/pathwatcher/lib/main.js:120:30)
  at Object.exports.watch (/opt/atom/resources/app/node_modules/pathwatcher/lib/main.js:179:12)
  at File.module.exports.File.subscribeToNativeChangeEvents (/opt/atom/resources/app/node_modules/pathwatcher/lib/file.js:404:109)
  at File.module.exports.File.willAddSubscription (/opt/atom/resources/app/node_modules/pathwatcher/lib/file.js:108:14)
  at File.willAddSubscription (/opt/atom/resources/app/node_modules/pathwatcher/lib/file.js:3:61)
  at File.module.exports.File.onDidChange (/opt/atom/resources/app/node_modules/pathwatcher/lib/file.js:88:12)
  at TextBuffer.module.exports.TextBuffer.subscribeToFile (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1089:44)
  at TextBuffer.module.exports.TextBuffer.setPath (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:281:14)
  at new TextBuffer (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:100:14)
  at Project.module.exports.Project.buildBuffer (/opt/atom/resources/app/src/project.js:496:16)
  at Project.module.exports.Project.bufferForPath (/opt/atom/resources/app/src/project.js:470:63)
  at Project.module.exports.Project.open (/opt/atom/resources/app/src/project.js:424:19)
  at Workspace.module.exports.Workspace.openURIInPane (/opt/atom/resources/app/src/workspace.js:490:31)
  at Workspace.module.exports.Workspace.open (/opt/atom/resources/app/src/workspace.js:416:19)
  at EventEmitter.<anonymous> (/opt/atom/resources/app/src/window-event-handler.js:45:34)
  at EventEmitter.emit (events.js:119:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "metrics"
    ]
  },
  "editor": {
    "fontSize": 16
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by curtiszimmerman** [comment]
Have you tried increasing the `fs.inotify.max_user_watches` from 8k to 32k as mentioned [in this document](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#typeerror-unable-to-watch-path)? This worked for me (in particular on LM17).

**Comment by Enkouyami** [comment]
@curtiszimmerman That fixed it.

**Comment by cstockton** [comment]
I have the same issue on the latest 0.187.0 version, I am running Atom inside a virtualbox windows7 vm and trying to open a VBoxSharedFolderFS shared folder. Since it's a error about "watching" the file, my guess is that virtualbox's built in share implementation doesn't have any sort of "fsnotify" type behavior? Or perhaps implemented differently? 

The big problem is just that it won't let me even open the files for editing, rather then just falling back to not having whatever feature is provided by the "watching". Might be good to have a more trivial polling fallback or something.

**Comment by digital-shokunin** [comment]
I get this issue when trying to open a file that is a network location in Windows, its a WebDav directory using Windows Explorer WebClient.

**Comment by Lohit9** [comment]
I also had this issue, in my case it was because I had changed the directory of the file I was working on with Atom open. I restarted Atom and resolved pathname and this solved the issue for me.

**Comment by mverissimo** [comment]
This worked for me on fedora 27:

echo fs.inotify.max_user_watches=524288 | sudo tee /etc/sysctl.d/40-max-user-watches.conf && sudo sysctl --system

https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
