### ISSUE TITLE
Uncaught Error: read ETIMEDOUT

### ISSUE THREAD

**Issue by ShiningRay** [atom/atom#5122]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.170.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: read ETIMEDOUT

```
At stream.js:94

Error: read ETIMEDOUT
  at exports._errnoException (util.js:746:11)
  at TCP.onread (net.js:543:26)

```

### Commands

```
     -0:10.2 core:move-right (atom-text-editor.editor.is-focused)
     -0:09.3 core:delete (atom-text-editor.editor.is-focused)
     -0:08.8 core:save (atom-text-editor.editor.is-focused)
     -0:08.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
 11x -0:07.5 core:select-right (atom-text-editor.editor.is-focused)
     -0:05.5 core:cut (atom-text-editor.editor.is-focused)
     -0:05.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:04.5 core:paste (atom-text-editor.editor.is-focused)
     -0:03.1 core:move-left (atom-text-editor.editor.is-focused)
     -0:02.7 core:move-right (atom-text-editor.editor.is-focused)
     -0:02.4 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:01.7 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.5 core:cut (atom-text-editor.editor.is-focused)
     -0:00.7 core:undo (atom-text-editor.editor.is-focused)
     -0:00.4 core:move-left (atom-text-editor.editor.is-focused)
     -0:00.0 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      "tmp",
      "*.log"
    ],
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": true,
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  },
  "editor": {
    "fontFamily": "Ubuntu Mono derivative Powerline",
    "showInvisibles": true,
    "showIndentGuide": true,
    "softWrap": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
atom-color-highlight, v3.0.4
expand-selection-to-quotes, v0.1.0
file-icons, v1.4.5
html2haml, v0.6.0
javascript-snippets, v1.0.0
language-haml, v0.14.0
language-slim, v0.3.0
linter, v0.10.0
ruby-slim, v0.2.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please update to the latest version of Atom (0.174.0).  This error has been fixed since then.
