### ISSUE TITLE
Uncaught Error: EROFS, read-only file system '...'

### ISSUE THREAD

**Issue by yrjo** [atom/atom#5126]
During trying to open file from external NTFS device (via USB) mounted as readonly I have got:
```
/Applications/Atom.app/Contents/Resources/app/src/workspace.js:504
--
Error: EROFS, read-only file system '/Volumes/data/trizeni/getconfig757/getconfig757/getcfg'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app/src/project.js:287:31)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:492:31)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:418:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)
```

------
<b>OS:</b>
      System Version: OS X 10.10.1 (14B25)
      Kernel Version: Darwin 14.0.0
Darwin XXXX 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64

<b>Atom:</b>
Version 0.174.0 (0.174.0)

<b>FS:</b>
/dev/disk2s1 on /Volumes/data (ntfs, local, nodev, nosuid, read-only, noowners)

**Comment by hetsch** [comment]
Same happend to me.
All the same but I'm on OSX 10.8.5

**Comment by izuzak** [comment]
Should have been fixed by https://github.com/atom/atom/pull/5157. Let us know if you can still reproduce. :bow:
