### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by ASilver228** [atom/atom#5186]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.172.0
**System**: linux 3.13.0-44-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /usr/share/atom/resources/app/src/project.js:360

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/usr/share/atom/resources/app/src/project.js:360:15)
  at Project.module.exports.Project.bufferForPath (/usr/share/atom/resources/app/src/project.js:337:63)
  at Project.module.exports.Project.open (/usr/share/atom/resources/app/src/project.js:291:19)
  at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app/src/workspace.js:487:29)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app/src/workspace.js:414:19)
  at Ipc.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please upgrade your Atom version and also subscribe to #307 for updates.
