### ISSUE TITLE
Uncaught Error: empty range in char class

### ISSUE THREAD

**Issue by dfaranha** [atom/atom#5195]
Hello! First of all, thanks a lot for the amazing Atom text editor.

I am trying to edit MAGMA files with syntax highlighting and have found the problem below. Steps do reproduce:
1. Convert https://github.com/dhowden/Magma.tmbundle and install the resulting package with the apm utility.
2. Open the MAGMA file below.
3. Switch to Magma with Ctrl+Shift+L.

```
m := 251;
conv := function(x)
    s := Sprintf("%h", Seqint([Integers() ! l : l in Eltseq(x)], 2));
    s := Substring(s, 3, #s-2);
    return "0x" * ("0"^(Ceiling(m/4)-#s)) * s;
end function;

PP<t> := PolynomialRing(GF(2));
Fq<T> := ext<GF(2) | t^251 + t^243 + t^229 + t^211 + 1>;

B := 1;
repeat
    a := 1;
    B := B + 1;
    s := IntegerToSequence(B, 2);
    b := 0;
    for i:=#s to 1 by -1 do
        b := b*t + s[i];
    end for;
    print b;
    E := EllipticCurve([Fq|1,1,0,0,b]);
    print E;
    n := Order(E);
until IsPrime(n) or (IsPrime(n div 4) and (n mod 4 eq 0)) or (IsPrime(n div 2) and (n mod 2 eq 0));
print Factorization(n);

P := 2*Random(E);
conv(P[1]);
conv(P[2]);
```

Thanks a lot!

**Atom Version**: 0.174.0
**System**: linux 3.18.2-2-ARCH
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: empty range in char class

```
At /usr/share/atom/resources/app/node_modules/first-mate/lib/scanner.js:31

Error: empty range in char class
  at Error (native)
  at Scanner.module.exports.Scanner.createScanner (/usr/share/atom/resources/app/node_modules/first-mate/lib/scanner.js:31:24)
  at Scanner.module.exports.Scanner.getScanner (/usr/share/atom/resources/app/node_modules/first-mate/lib/scanner.js:37:31)
  at Scanner.module.exports.Scanner.findNextMatch (/usr/share/atom/resources/app/node_modules/first-mate/lib/scanner.js:56:22)
  at Rule.module.exports.Rule.findNextMatch (/usr/share/atom/resources/app/node_modules/first-mate/lib/rule.js:101:28)
  at Rule.module.exports.Rule.getNextTokens (/usr/share/atom/resources/app/node_modules/first-mate/lib/rule.js:143:21)
  at Grammar.module.exports.Grammar.tokenizeLine (/usr/share/atom/resources/app/node_modules/first-mate/lib/grammar.js:125:39)
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedTokenizedLineForRow (/usr/share/atom/resources/app/src/tokenized-buffer.js:432:28)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/usr/share/atom/resources/app/src/tokenized-buffer.js:265:43)
  at /usr/share/atom/resources/app/src/tokenized-buffer.js:247:26
  at /usr/share/atom/resources/app/node_modules/roaster/node_modules/underscore/underscore.js:666:47

```
### Commands

```
  2x -2:22.6 core:backspace (atom-text-editor.editor)
     -2:21.3 core:save (atom-text-editor.editor)
     -2:20.2 core:backspace (atom-text-editor.editor)
     -2:18.6 core:save (atom-text-editor.editor)
     -2:17.0 core:backspace (atom-text-editor.editor)
     -2:16.5 core:save (atom-text-editor.editor)
     -2:15.3 core:backspace (atom-text-editor.editor)
     -2:14.7 core:save (atom-text-editor.editor)
     -2:12.2 core:move-down (atom-text-editor.editor)
     -0:47.0 core:move-up (atom-text-editor.editor)
     -0:46.4 core:backspace (atom-text-editor.editor)
     -0:45.9 core:save (atom-text-editor.editor)
     -0:44.7 core:backspace (atom-text-editor.editor)
     -0:44.3 core:save (atom-text-editor.editor)
     -0:31.5 core:close (atom-text-editor.editor)
     -0:00.0 grammar-selector:show (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "/home/dfaranha/projects"
  },
  "editor": {
    "fontSize": 14,
    "invisibles": {}
  }
}
```
### Installed Packages

``` coffee
# User
language-magma, v0.0.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
Can you share the grammar from the converted TextMate bundle?

**Comment by dfaranha** [comment]
Sure! 

http://www.ic.unicamp.br/~dfaranha/magma.cson
http://www.ic.unicamp.br/~dfaranha/spec.cson

The whole package is available at http://www.ic.unicamp.br/~dfaranha/language-magma.tar.gz

Thanks!

**Comment by skevy** [comment]
This happened to me as well while converting a tmLanguage from this project: https://github.com/6to5/6to5-sublime

I would love to know how I begin to debug this and figure out which regex is causing the problem.

**Comment by Ingramz** [comment]
While working on a grammar of my own, I found the culprit to be something like this:
`[+-*]`
A regex debugger instantly told that the `-` sign is interpreted as a range, as in `[0-9]`. So this character needs to be escaped or rearranged to be the first element.

**Comment by devragj** [comment]
Yesterday I built language-magma from the TextMate bundle.  So far it seems to be working fine.  In particular, it had no problem with the code in the original post.
