### ISSUE TITLE
Uncaught Error: EROFS, read-only file system '/Volumes/EDEXCEL_MATHS_M1/content/sb/content/m1_rev1_a_31.html'

### ISSUE THREAD

**Issue by notrodash** [atom/atom#5197]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.174.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EROFS, read-only file system '/Volumes/EDEXCEL_MATHS_M1/content/sb/content/m1_rev1_a_31.html'

```
At /Applications/Atom.app/Contents/Resources/app/src/workspace.js:504

Error: EROFS, read-only file system '/Volumes/EDEXCEL_MATHS_M1/content/sb/content/m1_rev1_a_31.html'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app/src/project.js:287:31)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:492:31)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:418:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "wrap-guide",
      "autoflow"
    ],
    "themes": [
      "solarized-dark-ui",
      "monokai-soda"
    ],
    "projectHome": "/Volumes/MacintoshHD/notrodash/git"
  },
  "editor": {
    "fontSize": 17,
    "showInvisibles": true,
    "showIndentGuide": true,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.2.6
dash, v1.0.0
monokai-soda, v0.4.0
solarized-dark-ui, v0.3.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
This should be fixed in the latest release, 0.175

Fixed by #5157
