### ISSUE TITLE
Uncaught error on open file

### ISSUE THREAD

**Issue by adrien59cadri** [atom/atom#5209]
Note, this looks like a permission error on open file in C:\Progradata directly from atom

Uncaught Error: EPERM, operation not permitted 'c:\Program Files (x86)\Bitwig Studio\resources\controllers\arturia\KeyLab.js'
c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\src\workspace.js:504
Hide Stack Trace
Error: EPERM, operation not permitted 'c:\Program Files (x86)\Bitwig Studio\resources\controllers\arturia\KeyLab.js'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\atom\common\lib\asar.js:422:20)
  at Project.module.exports.Project.open (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\src\project.js:287:31)
  at Workspace.module.exports.Workspace.openURIInPane (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\src\workspace.js:492:31)
  at Workspace.module.exports.Workspace.open (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\src\workspace.js:418:19)
  at Ipc.<anonymous> (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\src\window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\atom\renderer\api\lib\ipc.js:22:29)
  at process.emit (events.js:118:17)

**Comment by postcasio** [comment]
Please update to 0.175.0 which fixes this issue.

**Comment by adrien59cadri** [comment]
I can't, I just tried and had an issue (Although I did not know at that time there was a 175 version):

see Issue here  [restart and install update restarts lost 1 window #5212](https://github.com/atom/atom/issues/5209)

**Comment by adrien59cadri** [comment]
I installed with the installer from atom.io
I confirm, it is fixed, thank you
