### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by usmanalikr** [atom/atom#5229]
When I tried to open an sql file got the following error:

**Atom Version**: 0.166.0-9422a80
**System**: Mac OS X 10.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /Applications/Atom.app/Contents/Resources/app/src/project.js:462

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/Applications/Atom.app/Contents/Resources/app/src/project.js:462:15)
  at Project.module.exports.Project.bufferForPath (/Applications/Atom.app/Contents/Resources/app/src/project.js:439:63)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app/src/project.js:393:19)
  at Workspace.module.exports.Workspace.openUriInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:482:29)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:409:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
```

### Config

```
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "softWrapAtPreferredLineLength": true,
    "softWrap": true,
    "preferredLineLength": 120,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v0.4.0
autocomplete-plus, v1.1.0
better-handlebars, v0.1.1
ember-cli-helper, v0.4.0
ember-snippets, v1.0.0
emmet, v2.3.0
language-emblem, v0.1.0
language-haml, v0.14.0
language-ruby, v0.47.0
language-slim, v0.3.0
linter-rubocop, v0.2.1
minimap, v3.4.9
rspec-snippets, v0.4.0
ruby-block, v0.1.0
ruby-block-converter, v2.5.0
ruby-slim, v0.2.0
script, v2.15.1
seti-syntax, v0.2.1
seti-ui, v0.5.1
slim-language, v2.0.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
Please upgrade atom and See #307
