### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by MrOerni** [atom/atom#5231]
Uncaught TypeError: Cannot read property 'substr' of undefined

**Atom Version**: 0.155.0
**System**: Mac OS X 10.10.1
**Thrown From**: 'atom-compile-coffee' package, vundefined

### Steps To Reproduce

1. save a file without a name

### Stack Trace

```
At /Users/bjebb/.atom/packages/atom-compile-coffee/lib/atom-compile-coffee.coffee:48

TypeError: Cannot read property 'substr' of undefined
  at atomCompileCoffee (/Users/bjebb/.atom/packages/atom-compile-coffee/lib/atom-compile-coffee.coffee:48:23)
  at atom-workspace.<anonymous> (/Users/bjebb/.atom/packages/atom-compile-coffee/lib/atom-compile-coffee.coffee:68:48)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

**Comment by mnquintana** [comment]
This looks like an [atom-compile-coffee](https://github.com/freshl/atom-compile-coffee) issue, and probably not an Atom core issue. Can you open an issue [there](https://github.com/freshl/atom-compile-coffee)? 

Chances are that it's buggy because it hasn't been updated since June, and Atom has changed quite a bit since then. It might also help if you were on the latest version of Atom.

**Comment by kevinsawicki** [comment]
Also, you are on a very old version of Atom, you probably want to upgrade to the latest release, 0.175
