### ISSUE TITLE
Uncaught Error: getaddrinfo ENOTFOUND avatars2.githubusercontent.com

### ISSUE THREAD

**Issue by Patrick-Kox** [atom/atom#5233]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: linux 3.16.0-4-amd64
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: getaddrinfo ENOTFOUND avatars2.githubusercontent.com

```
At stream.js:94

Error: getaddrinfo ENOTFOUND avatars2.githubusercontent.com
  at errnoException (dns.js:41:10)
  at Object.onlookup [as oncomplete] (dns.js:91:26)

```

### Commands

```
     -0:10.8 core:copy (div.settings-view.pane-item)
     -0:07.2 core:paste (atom-text-editor.editor.mini)
     -0:05.3 core:select-all (atom-text-editor.editor.mini)
  3x -0:01.4 core:backspace (atom-text-editor.editor.mini)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "minimap",
      "restore-windows",
      "enhanced-package-list"
    ],
    "themes": [
      "mac-os-ui",
      "rainbow-theme"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
ascii-codes, v0.3.3
autocomplete-clang, v0.5.5
build, v0.23.1
git-log, v0.2.0
git-projects, v1.2.0
git-tab-status, v1.5.2
language-csharp, v0.3.0
linter, v0.10.0
linter-clang, v2.10.0
linter-cpplint, v0.1.3
mac-os-ui, v0.3.0
open-last-project, v0.1.1
rainbow-theme, v1.2.0
recent-files, v0.3.0
set-syntax, v0.1.0
sync-settings, v0.2.0
toolbar, v0.0.9

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
This was fixed in Atom 0.174.0 (see #4986)
