### ISSUE TITLE
Uncaught Error: Cannot find module 'jshint/src/cli'

### ISSUE THREAD

**Issue by gwilakers** [atom/atom#5275]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module 'jshint/src/cli'

```
At module.js:346

Error: Cannot find module 'jshint/src/cli'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at /Users/Garrett/.atom/packages/jshint/node_modules/lazy-req/index.js:6:43
  at lint (/Users/Garrett/.atom/packages/jshint/index.js:164:14)
  at delayed (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/node_modules/lodash/dist/lodash.js:5408:27)

```

### Commands

```
  2x -6:24.9 core:backspace (atom-text-editor.editor.mini)
     -6:18.6 core:confirm (atom-text-editor.editor.mini)
     -6:17.1 core:paste (atom-text-editor.editor.css)
     -6:15.4 core:save (atom-text-editor.editor.css)
     -4:52.9 core:backspace (atom-text-editor.editor.mini)
     -4:47.8 core:confirm (atom-text-editor.editor.mini)
     -4:45.8 core:paste (atom-text-editor.editor.css)
     -4:44.4 core:save (atom-text-editor.editor.css)
     -3:09.8 core:confirm (atom-text-editor.editor.mini)
     -3:08.6 core:paste (atom-text-editor.editor.javascript)
     -3:06.8 core:save (atom-text-editor.editor.javascript)
  2x -2:45.1 core:confirm (atom-text-editor.editor.mini)
     -2:11.5 core:copy (div.alert.alert-danger.alert-dismissable.native-key-bindings)
     -0:17.7 core:confirm (atom-text-editor.editor.mini)
     -0:16.3 core:paste (atom-text-editor.editor.is-focused)
     -0:00.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/Garrett/Documents/Github"
  },
  "editor": {
    "fontFamily": "Helvetica",
    "fontSize": 14,
    "lineHeight": 1.25,
    "showIndentGuide": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v1.1.0
color-picker, v1.4.4
editor-stats, v0.16.0
emmet, v2.3.2
highlight-line, v0.9.3
language-haml, v0.15.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
This issue was moved to sindresorhus/atom-jshint#59

**Comment by gwilakers** [comment]
@benogle Thanks.
