### ISSUE TITLE
Uncaught Error: EACCES, permission denied '/Applications/MAMP/htdocs/event_calendar_proj/vendor/autoload.php'

### ISSUE THREAD

**Issue by mahdera** [atom/atom#5292]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EACCES, permission denied '/Applications/MAMP/htdocs/event_calendar_proj/vendor/autoload.php'

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:315

Error: EACCES, permission denied '/Applications/MAMP/htdocs/event_calendar_proj/vendor/autoload.php'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.writeFileSync (fs.js:1011:15)
  at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:228:17)
  at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:234:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:304:21)
  at File.module.exports.File.write (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:293:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:970:17)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:620:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:538:16)
  at Pane.module.exports.Pane.saveItems (/Applications/Atom.app/Contents/Resources/app/src/pane.js:565:28)
  at PaneContainer.module.exports.PaneContainer.saveAll (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:245:28)
  at Workspace.module.exports.Workspace.saveAll (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:671:33)
  at atom-workspace.atom.commands.add.window:save-all (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:277:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
  2x -6:55.1 core:move-right (atom-text-editor.editor)
  2x -6:50.1 window:save-all (atom-text-editor.editor)
  3x -2:16.8 core:move-right (atom-text-editor.editor)
     -2:15.2 core:move-down (atom-text-editor.editor)
  3x -2:15.0 core:move-left (atom-text-editor.editor)
  4x -2:13.4 core:move-right (atom-text-editor.editor)
     -2:12.4 core:move-left (atom-text-editor.editor)
     -2:11.2 core:move-down (atom-text-editor.editor)
  3x -2:11.0 core:move-left (atom-text-editor.editor)
  3x -2:09.6 core:move-right (atom-text-editor.editor)
  5x -0:32.1 core:backspace (atom-text-editor.editor)
     -0:26.7 core:save (atom-text-editor.editor)
     -0:24.3 window:save-all (atom-text-editor.editor)
     -0:21.0 editor:consolidate-selections (atom-text-editor.editor)
     -0:21.0 core:cancel (atom-text-editor.editor)
     -0:12.4 window:save-all (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 16
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@benogle was this not caught by #4906?

**Comment by benogle** [comment]
Yeah, it should be. Not sure why it isnt
