### ISSUE TITLE
Uncaught TypeError: Cannot read property 'selectWord' of undefined

### ISSUE THREAD

**Issue by rachel-carvalho** [atom/atom#5309]
I don't know exactly how to reproduce, this is the first time this happens.

1. Editing a 101 line less file
2. Selected a large block of properties (lines 57-98) and pressed [TAB] to indent it into a newly created selector.

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'selectWord' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:764

TypeError: Cannot read property 'selectWord' of undefined
  at [object Object].module.exports.React.createClass.onMouseDown (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:764:36)
  at HTMLDivElement.boundMethod (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)

```

### Commands

```
  8x -0:19.3 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:17.6 core:copy (atom-text-editor.editor.is-focused)
     -0:17.2 core:cut (atom-text-editor.editor.is-focused)
     -0:16.6 core:select-down (atom-text-editor.editor.is-focused)
     -0:16.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:15.2 snippets:next-tab-stop (input)
     -0:15.2 snippets:expand (input)
     -0:14.3 core:paste (atom-text-editor.editor.is-focused)
  2x -0:13.0 core:backspace (atom-text-editor.editor.is-focused)
  8x -0:12.1 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -0:08.9 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:08.8 core:cancel (atom-text-editor.editor.is-focused)
     -0:07.4 core:cut (atom-text-editor.editor.is-focused)
     -0:06.8 core:select-down (atom-text-editor.editor.is-focused)
     -0:06.4 core:cut (atom-text-editor.editor.is-focused)
     -0:03.2 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "remember-session",
      "linter-jshint",
      "merge-conflicts"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "fontSize": 14,
    "showIndentGuide": true,
    "autoIndentOnPaste": false,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.5
autoclose-html, v0.14.0
autocomplete-plus, v1.1.0
file-types, v0.3.0
highlight-line, v0.9.3
language-jade, v0.3.0
language-smarty-php, v0.4.0
linter, v0.10.1
linter-jscs, v1.4.9
monokai, v0.11.0
save-session, v0.11.3

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
This stack trace passes through React which is no longer used as of https://github.com/atom/atom/pull/5293 so I'm going to close this out and optimistically assume it was fixed as part of that refactor.

**Comment by aloncarmel** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'selectWord' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:554

TypeError: Cannot read property 'selectWord' of undefined
  at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:554:41)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "devunityatom",
      "devunityx",
      "firepad"
    ]
  },
  "editor": {
    "fontSize": 13,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
devunity, v2.1.0

# Dev
No dev packages
```

**Comment by aloncarmel** [comment]
![screen shot 2015-05-12 at 5 12 53 pm](https://cloud.githubusercontent.com/assets/912405/7589221/2ab10d68-f8ca-11e4-8ea5-6d7835448536.png)

**Comment by mnquintana** [comment]
@aloncarmel I think that's a different issue - can you open that in a separate issue?

**Comment by aloncarmel** [comment]
yes, thanks.
