### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by gttiankai** [atom/atom#5320]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.174.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:85

Error: write EPIPE
  at exports._errnoException (util.js:746:11)
  at Object.afterWrite (net.js:757:14)

```

### Commands

```
 29x -0:42.2 core:move-down (atom-text-editor.editor.is-focused)
 11x -0:40.7 core:move-up (atom-text-editor.editor.is-focused)
  9x -0:39.9 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:39.1 core:move-up (atom-text-editor.editor.is-focused)
     -0:38.2 core:move-left (atom-text-editor.editor.is-focused)
     -0:37.7 core:backspace (atom-text-editor.editor.is-focused)
     -0:31.0 clang-format:format (atom-text-editor.editor.is-focused)
     -0:23.9 core:select-all (atom-text-editor.editor.is-focused)
     -0:19.8 clang-format:format (atom-text-editor.editor.is-focused)
     -0:15.8 core:move-left (atom-text-editor.editor.is-focused)
     -0:15.2 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:15.2 snippets:expand (atom-text-editor.editor.is-focused)
     -0:15.2 editor:indent (atom-text-editor.editor.is-focused)
     -0:14.2 core:save (atom-text-editor.editor.is-focused)
     -0:01.1 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "fontSize": 17,
    "lineHeight": 1.4,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.6.1
clang-format, v1.7.0
monokai, v0.12.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
Closing in favor of #4708
