### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 2 is larger than or equal to the node's length (1).

### ISSUE THREAD

**Issue by bezigon** [atom/atom#5349]
[Enter steps to reproduce below:]

1. Opened `waf` script
2. Scrolled up to binary data

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 2 is larger than or equal to the node's length (1).

```
At /Applications/Atom.app/Contents/Resources/app/src/lines-component.js:465

Error: Failed to execute 'setEnd' on 'Range': The offset 2 is larger than or equal to the node's length (1).
  at Error (native)
  at [object Object].module.exports.React.createClass.measureCharactersInLine (/Applications/Atom.app/Contents/Resources/app/src/lines-component.js:465:33)
  at [object Object].boundMethod [as measureCharactersInLine] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
  at /Applications/Atom.app/Contents/Resources/app/src/lines-component.js:418:21
  at DisplayBuffer.module.exports.DisplayBuffer.batchCharacterMeasurement (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:560:7)
  at TextEditor.module.exports.TextEditor.batchCharacterMeasurement (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2877:33)
  at [object Object].module.exports.React.createClass.measureCharactersInNewLines (/Applications/Atom.app/Contents/Resources/app/src/lines-component.js:411:21)
  at [object Object].boundMethod [as measureCharactersInNewLines] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
  at [object Object].module.exports.React.createClass.componentDidUpdate (/Applications/Atom.app/Contents/Resources/app/src/lines-component.js:147:14)
  at CallbackQueue.mixInto.notifyAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
  at ReactReconcileTransaction.Mixin.closeAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactReconcileTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.forceUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1232:18)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:313:28

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 16
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by as-cii** [comment]
**System**: Mac OS X 10.10.2

I cannot reproduce the issue on Atom (v0.176) and on Atom (master). Except from being remarkably slow when it reaches line 163–165 (namely the binary data), the editor still loads the file properly.

I tried with waf-1.6.11. To get the file you can simply download waf Python script from:

```bash
$ wget http://waf.googlecode.com/files/waf-1.6.11
$ atom waf-1.6.11
```

@bezigon A few questions:

* Did you use another waf version? 
* How did you scroll? Using a scrollbar or via keyboard?
  * I confirm that either ways, it works fine. Even scrolling left and right in the binary line doesn't cause any issue;

**Comment by WriterOfAlicrow** [comment]
I think I'm getting the same issue here  (the error popup directed me to this issue). On openSUSE 13.2, Atom 0.177.0. immediately upon opening a certain file (I pasted the file to http://pastebin.com/m9Wyry4c), and again when I scroll near the top or select text near the top.

It seems to be linked to this line:
    ̂δ(δ(q,x),q)=C
and even a file containing just that one line is giving the same behaviour.

I tried the file as-cii mentioned, and that works just fine for me. Editor isn't even slowed down by the binary data.

**Comment by kasimir-k** [comment]
**System:** Mac OS X 10.10.2, Atom 0.178.0

Steps to reproduce:
1. Start Atom / create new file
2. type a space
3. type " ̋" - that is [shift] + [opt] + 0 (on a Finnish keyboard)
4. Atom gives an error message

When I save the file, it contains bytes 20 CC 8B 0A
When I open the file in Atom, it again gives me the same error message

**Comment by izuzak** [comment]
@kasimir-k Thanks so much, that's very helpful.

@nathansobo I'm able to reproduce this issue like this:

1. Start Atom
2. Create empty file
3. Type a space
4. Copy/paste this character into the file after the space: ` ̋`

**Comment by nathansobo** [comment]
This was caused by complications handling combining characters following spaces, of which ` ̋` is an example. We always consider a character followed by a combining character to be a "paired" character, meaning we treat it as 1 character on screen but 2 characters in the buffer. However, in the case of a combining character following leading whitespace, the two components paired character were getting separated into different tokens. This threw off our math during character measurement.

The solution is to never break a space followed by a combining character into its own leading whitespace token. It really makes more sense to consider a space preceding a combining character as non-whitespace, since that's how it renders.
