### ISSUE TITLE
Uncaught Error: UNKNOWN, unknown error 'c:\Users\X\Documents\servers\jetty\9.2.6\webapps\vd-estinzione\index.html'

### ISSUE THREAD

**Issue by ekr-paolo-carraro** [atom/atom#5350]
[Enter steps to reproduce below:]

1. use core html helper to create tags
2. save file source

**Atom Version**: 0.176.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: UNKNOWN, unknown error 'c:\Users\Paolo\Documents\servers\jetty\9.2.6\webapps\vd-estinzione\index.html'

```
At c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\src\workspace.js:710

Error: UNKNOWN, unknown error 'c:\Users\Paolo\Documents\servers\jetty\9.2.6\webapps\vd-estinzione\index.html'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\atom\common\lib\asar.js:422:20)
  at Object.fs.writeFileSync (fs.js:1011:15)
  at Object.fsPlus.writeFileSync (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\node_modules\fs-plus\lib\fs-plus.js:228:17)
  at File.module.exports.File.writeFileSync (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\node_modules\pathwatcher\lib\file.js:234:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\node_modules\pathwatcher\lib\file.js:304:21)
  at File.module.exports.File.write (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\node_modules\pathwatcher\lib\file.js:293:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:970:17)
  at TextBuffer.module.exports.TextBuffer.save (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\src\text-editor.js:620:26)
  at Pane.module.exports.Pane.saveItem (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\src\pane.js:538:16)
  at Pane.module.exports.Pane.saveActiveItem (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\src\pane.js:522:19)
  at Workspace.module.exports.Workspace.saveActivePaneItemAndReportErrors (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\src\workspace.js:689:44)
  at Workspace.module.exports.Workspace.saveActivePaneItem (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\src\workspace.js:679:19)
  at atom-workspace.atom.commands.add.core:save (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\src\workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\src\command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\src\command-registry.js:156:19)
  at Ipc.<anonymous> (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\app\src\window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (c:\Users\Paolo\AppData\Local\atom\app-0.176.0\resources\atom\renderer\api\lib\ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
     -1:56.7 snippets:expand (atom-text-editor.editor.is-focused)
     -1:56.7 editor:indent (atom-text-editor.editor.is-focused)
     -1:54.2 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:54.2 snippets:expand (atom-text-editor.editor.is-focused)
  7x -1:47.9 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:31.3 core:move-right (atom-text-editor.editor.is-focused)
     -1:28.2 core:move-down (atom-text-editor.editor.is-focused)
     -1:25.8 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:25.8 snippets:expand (atom-text-editor.editor.is-focused)
     -1:11.6 core:backspace (atom-text-editor.editor.is-focused)
  7x -1:08.7 core:move-right (atom-text-editor.editor.is-focused)
  8x -1:04.8 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:48.6 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:44.8 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:11.5 core:move-right (atom-text-editor.editor.is-focused)
     -0:05.8 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 12,
    "showIndentGuide": true,
    "preferredLineLength": 160,
    "tabLength": 3,
    "softTabs": false,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
color-picker, v1.4.4
comment, v0.2.7
linter, v0.10.1
rest-client, v0.3.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Could you please try reproducing this in safe mode (`atom --safe`)?
