### ISSUE TITLE
Saving to readonly file - Uncaught Error: EPERM, operation not permitted foo.txt

### ISSUE THREAD

**Issue by OMGtechy** [atom/atom#5356]
### Repro
1. Edit a readonly file
2. Save

### Result
Atom hangs for a while and eventually an uncaught exception (propergates)

### Desired
Atom should report "cannot save readonly file, save under different file name?" or something to that effect.

### Info

**Atom Version**: 0.166.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM, operation not permitted 'c:\Users\josh.gerrard\foo.txt

```
At c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\src\workspace.js:622

Error: EPERM, operation not permitted 'c:\Users\josh.gerrard\foo.txt
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (C:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\atom\common\lib\asar.js:422:20)
  at Object.fs.writeFileSync (fs.js:1011:15)
  at Object.fsPlus.writeFileSync (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\node_modules\fs-plus\lib\fs-plus.js:228:17)
  at File.module.exports.File.writeFileSync (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\node_modules\pathwatcher\lib\file.js:227:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\node_modules\pathwatcher\lib\file.js:297:21)
  at File.module.exports.File.write (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\node_modules\pathwatcher\lib\file.js:286:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:966:17)
  at TextBuffer.module.exports.TextBuffer.save (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:954:19)
  at TextEditor.module.exports.TextEditor.save (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:589:26)
  at Pane.module.exports.Pane.saveItem (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\src\pane.js:511:16)
  at Pane.module.exports.Pane.saveActiveItem (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\src\pane.js:501:19)
  at Workspace.module.exports.Workspace.saveActivePaneItemAndReportErrors (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\src\workspace.js:611:44)
  at Workspace.module.exports.Workspace.saveActivePaneItem (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\src\workspace.js:601:19)
  at atom-workspace.atom.commands.add.core:save (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\src\workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\src\command-registry.js:243:29)
  at c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (c:\Users\josh.gerrard\AppData\Local\atom\app-0.166.0\resources\app\src\window-event-handler.js:167:20)

```

### Commands

```
     -0:25.3 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:23.4 project-find:show (atom-text-editor.editor.mini)
     -0:21.6 core:confirm (atom-text-editor.editor.mini)
     -0:15.6 core:paste (atom-text-editor.editor.mini)
     -0:14.9 core:undo (atom-text-editor.editor.mini)
     -0:00.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "editor": {
    "fontSize": 17
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Yep, that is exactly what it does now.  Would you mind upgrading to the latest version please? :smile:

**Comment by benogle** [comment]
Thanks @50Wliu. Note that currently on OSX it will attempt privilege escalation, but it will not on other platforms.
