### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by cmtp** [atom/atom#5360]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: linux 3.17.8-300.fc21.x86_64
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /usr/local/share/atom/resources/app/src/project.js:462

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/usr/local/share/atom/resources/app/src/project.js:462:15)
  at Project.module.exports.Project.bufferForPath (/usr/local/share/atom/resources/app/src/project.js:439:63)
  at Project.module.exports.Project.open (/usr/local/share/atom/resources/app/src/project.js:393:19)
  at Workspace.module.exports.Workspace.openUriInPane (/usr/local/share/atom/resources/app/src/workspace.js:482:29)
  at Workspace.module.exports.Workspace.open (/usr/local/share/atom/resources/app/src/workspace.js:409:19)
  at Ipc.<anonymous> (/usr/local/share/atom/resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/usr/local/share/atom/resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
```

### Config

```
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
Update your version of Atom for improved error messages.  Also, this is
obviously not a bug but rather a limitation.

**Comment by benogle** [comment]
Thanks @mark-hahn
