### ISSUE TITLE
Uncaught TypeError: Cannot set property 'localAddress' of undefined

### ISSUE THREAD

**Issue by abestic9** [atom/atom#5389]
1. New file
2. Set file type to PHP
3. Beautify (without php_beautifier)

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot set property 'localAddress' of undefined

```
At net.js:840

TypeError: Cannot set property 'localAddress' of undefined
  at connect (net.js:840:23)
  at net.js:943:9
  at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:83:16)
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:101:10)

```

### Commands

```
     -0:19.3 editor:newline (atom-text-editor.editor.is-focused)
     -0:18.9 core:paste (atom-text-editor.editor.is-focused)
     -0:18.4 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:16.6 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:16.6 core:cancel (atom-text-editor.editor.mini)
     -0:15.2 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:13.2 core:confirm (atom-text-editor.editor.mini)
     -0:12.3 command-palette:toggle (a.inline-block)
     -0:11.3 core:confirm (atom-text-editor.editor.mini)
     -0:11.3 beautify:beautify-editor (a.inline-block)
     -0:09.2 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:08.2 core:confirm (atom-text-editor.editor.mini)
     -0:08.2 beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:02.9 core:select-all (atom-text-editor.editor.is-focused)
     -0:02.5 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:02.5 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "background-tips"
    ],
    "themes": [
      "solarized-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "fontFamily": "Menlo",
    "fontSize": 12,
    "showIndentGuide": true,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
color-picker, v1.4.4
emmet, v2.3.3
file-icons, v1.4.8
hex, v0.5.0
language-blade, v0.7.0
language-html5-subtlegradient, v0.1.0
language-jade, v0.3.0
linter, v0.11.1
linter-js-yaml, v0.1.3
linter-jshint, v0.1.0
linter-lua, v0.1.3
linter-php, v0.0.11
linter-pylint, v0.2.0
linter-ruby, v0.1.4
linter-scss-lint, v0.0.11
linter-tidy, v0.0.1
minimap, v4.0.2
project-manager, v1.15.5
solarized-dark-ui, v0.3.0

# Dev
No dev packages
```

### Screenshot

![screenshot 2015-02-04 16 25 34](https://cloud.githubusercontent.com/assets/635078/6118669/d8220530-b124-11e4-891a-ac70d41ed224.png)

**Comment by 50Wliu** [comment]
Could you please try to reproduce this in safe mode (`atom --safe`)?

**Comment by benogle** [comment]
Looks like it happened after a select all, then un indent, post beautify. 

```
     -0:08.2 beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:02.9 core:select-all (atom-text-editor.editor.is-focused)
     -0:02.5 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:02.5 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
```

> Beautify (without php_beautifier)

Can you elaborate on the `without php_beautifier` bit? Is it looking for some binary and it cant find it?

**Comment by abestic9** [comment]
Unable to reproduce in safe mode, will not load the package providing the Beautify method. Please excuse if I'm missing something as I'm quite new to Atom.

I don't have php_beautifier installed so Atom would fail to find a binary, see https://github.com/Glavin001/atom-beautify/issues/112.

Whether this is the cause of the problem or unrelated, the error handler isn't super helpful in either case.

**Comment by 50Wliu** [comment]
Safe mode disables all of the non-core packages and themes (basically it disables anything you're installed).

**Comment by abestic9** [comment]
Would that mean this is not an issue with Atom Core, but one of the 3rd party packages relating to Beautify?

**Comment by abestic9** [comment]
Looks like this will be resolved as per https://github.com/iojs/io.js/issues/510
