### ISSUE TITLE
Uncaught Error: UNKNOWN, unknown error 'c:\xampp\htdocs\buco\app\index.html'

### ISSUE THREAD

**Issue by S3ak** [atom/atom#5396]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: UNKNOWN, unknown error 'c:\xampp\htdocs\buco\app\index.html'

```
At C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\src\workspace.js:710

Error: UNKNOWN, unknown error 'c:\xampp\htdocs\buco\app\index.html'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\atom\common\lib\asar.js:422:20)
  at Object.fs.writeFileSync (fs.js:1116:15)
  at Object.fsPlus.writeFileSync (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\lib\fs-plus.js:228:17)
  at File.module.exports.File.writeFileSync (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\node_modules\pathwatcher\lib\file.js:241:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\node_modules\pathwatcher\lib\file.js:304:21)
  at File.module.exports.File.write (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\node_modules\pathwatcher\lib\file.js:293:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:970:17)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\src\text-editor.js:620:26)
  at Pane.module.exports.Pane.saveItem (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\src\pane.js:538:16)
  at Pane.module.exports.Pane.saveActiveItem (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\src\pane.js:522:19)
  at Workspace.module.exports.Workspace.saveActivePaneItemAndReportErrors (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\src\workspace.js:689:44)
  at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\src\workspace.js:679:19)
  at atom-workspace.atom.commands.add.core:save (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\src\workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\src\command-registry.js:243:29)
  at C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Titan-PC\AppData\Local\atom\app-0.177.0\resources\app\src\window-event-handler.js:170:20)

```

### Commands

```
  2x -0:19.1 core:undo (atom-text-editor.editor.autocomplete-active)
     -0:12.8 core:save (atom-text-editor.editor.autocomplete-active)
  3x -0:12.4 editor:select-to-beginning-of-word (atom-text-editor.editor.autocomplete-active)
     -0:11.7 core:copy (atom-text-editor.editor.autocomplete-active)
     -0:11.5 core:save (atom-text-editor.editor.autocomplete-active)
     -0:10.1 core:move-right (atom-text-editor.editor.autocomplete-active)
  3x -0:09.9 core:move-left (atom-text-editor.editor.autocomplete-active)
     -0:09.3 core:backspace (atom-text-editor.editor.autocomplete-active)
     -0:09.0 core:save (atom-text-editor.editor.autocomplete-active)
     -0:08.8 editor:move-to-end-of-word (atom-text-editor.editor.autocomplete-active)
  3x -0:08.4 editor:select-to-beginning-of-word (atom-text-editor.editor.autocomplete-active)
     -0:07.6 core:copy (atom-text-editor.editor.autocomplete-active)
  3x -0:07.3 core:save (atom-text-editor.editor.autocomplete-active)
     -0:06.7 core:copy (atom-text-editor.editor.autocomplete-active)
  3x -0:06.4 core:save (atom-text-editor.editor.autocomplete-active)
     -0:00.2 core:move-down (atom-text-editor.editor.autocomplete-active.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".sass-cache",
      ".scssc"
    ],
    "disabledPackages": [
      "language-objective-c",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-java",
      "atom-gist",
      "html-tab",
      "atom-color-highlight",
      "bower-install",
      "docblockr",
      "grunt-runner",
      "terminal-status",
      "terminal-panel",
      "terminal-runner",
      "quantum-shell"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
alignment, v1.1.4
atom-css-comb, v0.6.1
auto-reveal-in-sidebar, v0.4.0
autocomplete-plus, v2.0.11
autocomplete-snippets, v1.0.0
color-picker, v1.4.4
editorconfig, v0.3.0
emmet, v2.3.3
gist-it, v0.6.4
git-log, v0.2.0
highlight-line, v0.9.3
html-img, v0.3.2
img-placeholder, v0.2.0
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.6
linter, v0.11.1
linter-bootlint, v0.0.3
linter-coffeelint, v0.1.7
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-php, v0.0.11
linter-scss-lint, v0.0.11
linter-tidy, v0.0.1
minimap, v4.0.2
monokai, v0.12.0
project-manager, v1.15.5
tag, v0.2.3
tasks, v1.2.4

# Dev
No dev packages
```

**Comment by benogle** [comment]
Can you access `c:\xampp\htdocs\buco\app\index.html`? Does it require admin privileges to access? Is it read only? Any special ACL settings on that file?
