### ISSUE TITLE
Uncaught Error: spawn /usr/share/atom/atom.dpkg-new (deleted) ENOENT

### ISSUE THREAD

**Issue by skitta** [atom/atom#5400]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: linux 3.16.0-23-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /usr/share/atom/atom.dpkg-new (deleted) ENOENT

```
At events.js:94

Error: spawn /usr/share/atom/atom.dpkg-new (deleted) ENOENT
  at exports._errnoException (util.js:753:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:364:11)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "Ubuntu Mono",
    "tabLength": 4,
    "softWrapAtPreferredLineLength": true,
    "softWrap": true,
    "showIndentGuide": true,
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by benogle** [comment]
What were you doing when this happened? Do you see this often? Do you have steps to reproduce?

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/atom/notifications/pull/62
