### ISSUE TITLE
Uncaught TypeError: Cannot read property 'compositionInProgress' of null

### ISSUE THREAD

**Issue by TheSeamau5** [atom/atom#5402]
[Enter steps to reproduce below:]

I have absolutely no idea what happened :( sorry

1. Had two tabs open (the first was my code, the second was the settings)
2. Pressed "Update All" to update different packages
3. While packages were just starting to download, went back to my first tab and tried modifying some code (namely, I just pressed the enter bar)

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'compositionInProgress' of null

```
At /Users/hassanhayat/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:234

TypeError: Cannot read property 'compositionInProgress' of null
  at AutocompleteManager.module.exports.AutocompleteManager.bufferChanged (/Users/hassanhayat/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:234:30)
  at /Users/hassanhayat/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:594:20)
  at BufferPatch.module.exports.BufferPatch.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/buffer-patch.js:74:21)
  at Transaction.module.exports.Transaction.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/transaction.js:60:29)
  at History.module.exports.History.abortTransaction (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:165:24)
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:122:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1178:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -2:06.1 core:backspace (atom-text-editor.editor.is-focused)
     -2:05.3 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:05.3 snippets:expand (atom-text-editor.editor.is-focused)
     -2:05.3 editor:indent (atom-text-editor.editor.is-focused)
     -2:04.7 editor:newline (atom-text-editor.editor.is-focused)
  4x -2:03.9 core:backspace (atom-text-editor.editor.is-focused)
     -2:01.7 core:move-left (atom-text-editor.editor.is-focused)
     -2:00.9 core:move-right (atom-text-editor.editor.is-focused)
     -1:55.6 autocomplete-plus:confirm (input)
  5x -1:52.6 core:backspace (atom-text-editor.editor.is-focused)
     -1:18.3 core:move-left (atom-text-editor.editor.is-focused)
     -1:03.9 core:backspace (atom-text-editor.editor.is-focused)
     -1:03.2 core:move-right (atom-text-editor.editor.is-focused)
     -0:57.0 core:save (atom-text-editor.editor.is-focused)
     -0:55.1 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:00.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-gjslint",
      "linter",
      "linter-dartanalyzer"
    ]
  },
  "editor": {
    "fontFamily": "Source Code Pro, Menlo, monospace",
    "fontSize": 15,
    "autoIndentOnPaste": false,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
atom-typescript-tools, v0.6.2
autoclose-html, v0.14.0
better-language-dart, v1.0.1
color-picker, v1.4.4
dart-tools, v0.8.5
language-ada, v0.2.0
language-coq, v0.1.0
language-css-plus, v0.3.0
language-elm, v0.4.1
language-glsl, v0.2.2
language-julia, v2.0.0
language-opencl, v0.1.0
language-pegjs, v0.5.0
language-r, v0.1.1
language-sml, v0.2.0
language-typescript, v0.15.0
language-x86, v0.1.0
linter-csslint, v0.0.11

# Dev
No dev packages
```

**Comment by benogle** [comment]
Closing in favor of atom-community/autocomplete-plus#241
