### ISSUE TITLE
Uncaught Error: getaddrinfo ENOTFOUND circleci.com

### ISSUE THREAD

**Issue by tiwilliam** [atom/atom#5422]
1. Open Atom with `circle-ci` installed
2. Put your computer to sleep with Atom window open
3. Wake up your computer and find the exception

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: getaddrinfo ENOTFOUND circleci.com

```
At events.js:85

Error: getaddrinfo ENOTFOUND circleci.com
  at errnoException (dns.js:41:10)
  at Object.onlookup [as oncomplete] (dns.js:91:26)

```

### Commands

```
     -0:01.4 project-manager:toggle (atom-pane.pane.active)
     -0:00.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:00.0 core:cancel (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".pyc"
    ],
    "disabledPackages": [
      "minimap"
    ],
    "projectHome": "/Users/wille/Documents/Code"
  },
  "editor": {
    "fontFamily": "Menlo",
    "fontSize": 15,
    "lineHeight": 1.4,
    "preferredLineLength": 100,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-plus, v2.0.12
circle-ci, v0.4.2
color-picker, v1.4.4
editorconfig, v0.3.0
file-icons, v1.4.8
language-haml, v0.15.0
linter, v0.11.1
linter-flake8, v1.3.0
linter-jshint, v0.1.0
project-manager, v1.15.5
travis-ci-status, v0.11.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Could you please report this over on the [circle-ci](atom.io/packages/circle-ci) package please?
