### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isActive' of null

### ISSUE THREAD

**Issue by TheSeamau5** [atom/atom#5437]
[Enter steps to reproduce below:]

See these issues :
https://github.com/atom/atom/issues/5402
https://github.com/atom-community/autocomplete-plus/issues/241

1. Had two tabs open (the first was my code, the second was the settings)
2. Pressed "Update All" to update different packages
3. While packages were just starting to download, went back to my first tab and tried modifying some code (namely, I just pressed the enter bar)

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'isActive' of null

```
At /Users/hassanhayat/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:222

TypeError: Cannot read property 'isActive' of null
  at AutocompleteManager.module.exports.AutocompleteManager.requestNewSuggestions (/Users/hassanhayat/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:222:48)
  at AutocompleteManager.requestNewSuggestions (/Users/hassanhayat/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.bufferChanged (/Users/hassanhayat/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:258:8)
  at /Users/hassanhayat/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:594:20)
  at BufferPatch.module.exports.BufferPatch.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/buffer-patch.js:74:21)
  at Transaction.module.exports.Transaction.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/transaction.js:60:29)
  at History.module.exports.History.abortTransaction (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:165:24)
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:122:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1181:26)
  at [object Object].module.exports.React.createClass.onTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:647:30)
  at HTMLDivElement.boundMethod (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)

```

### Commands

```
     -3:57.9 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -3:56.2 editor:newline (atom-text-editor.editor.autocomplete-active.is-focused)
     -3:53.6 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -3:49.6 core:save (atom-text-editor.editor.autocomplete-active.is-focused)
     -2:33.7 editor:newline (atom-text-editor.editor.autocomplete-active.is-focused)
     -2:25.8 core:move-down (atom-text-editor.editor.autocomplete-active.is-focused)
     -2:25.5 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -2:25.0 core:save (atom-text-editor.editor.autocomplete-active.is-focused)
     -2:12.3 tree-view:toggle (atom-text-editor.editor.autocomplete-active.is-focused)
     -1:30.3 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:10.5 editor:newline (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:09.8 core:save (atom-text-editor.editor.autocomplete-active.is-focused)
  2x -0:09.1 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:08.3 core:move-down (atom-text-editor.editor.autocomplete-active.is-focused)
  2x -0:08.0 editor:newline (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:07.6 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-gjslint",
      "linter",
      "linter-dartanalyzer"
    ]
  },
  "editor": {
    "fontFamily": "Source Code Pro, Menlo, monospace",
    "fontSize": 15,
    "autoIndentOnPaste": false,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
atom-typescript-tools, v0.6.2
better-language-dart, v1.0.1
color-picker, v1.4.4
dart-tools, v0.8.5
language-ada, v0.2.0
language-coq, v0.1.0
language-css-plus, v0.3.0
language-d, v3.0.1
language-elm, v0.4.1
language-julia, v2.0.0
language-opencl, v0.1.0
language-pegjs, v0.5.0
language-r, v0.1.1
language-sml, v0.2.0
language-typescript, v0.15.0
language-x86, v0.1.0
linter-csslint, v0.0.11
minimap, v4.1.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
This was handled in https://github.com/atom-community/autocomplete-plus/issues/241
