### ISSUE TITLE
Uncaught Error: error evaluating function `darken`: Cannot read property 'toHSL' of undefined

### ISSUE THREAD

**Issue by nickckaye** [atom/atom#5441]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: linux 3.13.0-45-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: error evaluating function `darken`: Cannot read property 'toHSL' of undefined

```
At /usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/lib/less/parser.js:604

Error: 
  at new Parser (/usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
  at Object.module.exports.grammars.LESS.render (/home/nick/.atom/packages/preview/lib/renderer.coffee:73:21)
  at PreviewView.module.exports.PreviewView.renderPreviewWithRenderer (/home/nick/.atom/packages/preview/lib/preview-view.coffee:270:27)
  at PreviewView.renderPreviewWithRenderer (/home/nick/.atom/packages/preview/lib/preview-view.coffee:1:1)
  at PreviewView.module.exports.PreviewView.renderPreview (/home/nick/.atom/packages/preview/lib/preview-view.coffee:155:6)
  at PreviewView.renderPreview (/home/nick/.atom/packages/preview/lib/preview-view.coffee:1:1)
  at later (/usr/share/atom/resources/app/node_modules/roaster/node_modules/underscore/underscore.js:724:25)

```

### Commands

```
  2x -0:14.9 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:13.5 core:move-right (atom-text-editor.editor.is-focused)
     -0:13.4 core:move-up (atom-text-editor.editor.is-focused)
     -0:13.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:12.8 core:move-left (atom-text-editor.editor.is-focused)
     -0:12.4 core:move-right (atom-text-editor.editor.is-focused)
  6x -0:12.1 core:move-left (atom-text-editor.editor.is-focused)
     -0:10.6 core:move-right (atom-text-editor.editor.is-focused)
 10x -0:10.4 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.1 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:08.9 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:08.6 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:05.6 core:move-right (atom-text-editor.editor.is-focused)
  3x -0:04.9 core:move-down (atom-text-editor.editor.is-focused)
     -0:04.6 core:move-left (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.21.2
git-blame, v0.4.0
git-log, v0.2.0
go-plus, v3.2.1
language-jade, v0.3.0
last-cursor-position, v0.7.0
linter-less, v0.3.1

# Dev
No dev packages
```

**Comment by nickckaye** [comment]
Autocomplete typing a `darken(..` function in a LESS file.

**Comment by 50Wliu** [comment]
Is this reproducible in safe mode (`atom --safe`)?

**Comment by izuzak** [comment]
Seems like you have or had the https://github.com/Glavin001/atom-preview package installed and it's causing problems. Let us know if you can reproduce in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode).
