### ISSUE TITLE
Uncaught Error: variable @brand-pop-color is undefined

### ISSUE THREAD

**Issue by nickckaye** [atom/atom#5443]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: linux 3.13.0-45-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: variable @brand-pop-color is undefined

```
At /usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/lib/less/parser.js:604

Error: 
  at new Parser (/usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
  at Object.module.exports.grammars.LESS.render (/home/nick/.atom/packages/preview/lib/renderer.coffee:73:21)
  at PreviewView.module.exports.PreviewView.renderPreviewWithRenderer (/home/nick/.atom/packages/preview/lib/preview-view.coffee:270:27)
  at PreviewView.renderPreviewWithRenderer (/home/nick/.atom/packages/preview/lib/preview-view.coffee:1:1)
  at PreviewView.module.exports.PreviewView.renderPreview (/home/nick/.atom/packages/preview/lib/preview-view.coffee:155:6)
  at PreviewView.renderPreview (/home/nick/.atom/packages/preview/lib/preview-view.coffee:1:1)
  at later (/usr/share/atom/resources/app/node_modules/roaster/node_modules/underscore/underscore.js:724:25)

```

### Commands

```
 10x -2:15.4 core:backspace (atom-text-editor.editor.is-focused)
     -2:14.2 core:move-up (atom-text-editor.editor.is-focused)
  2x -2:14.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:13.7 core:move-up (atom-text-editor.editor.is-focused)
  2x -2:10.7 core:move-right (atom-text-editor.editor.is-focused)
  3x -2:10.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:09.6 core:move-left (atom-text-editor.editor.is-focused)
     -0:26.2 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:22.1 core:move-down (atom-text-editor.editor.mini)
     -0:21.6 core:move-up (atom-text-editor.editor.mini)
     -0:21.2 core:move-down (atom-text-editor.editor.mini)
     -0:20.8 core:confirm (atom-text-editor.editor.mini)
     -0:20.8 settings-view:uninstall-packages (atom-text-editor.editor.is-focused)
     -0:16.9 core:confirm (atom-text-editor.editor.mini)
     -0:01.6 core:move-right (atom-text-editor.editor.is-focused)
     -0:01.3 core:move-left (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-less"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.21.2
git-blame, v0.4.0
git-log, v0.2.0
go-plus, v3.2.1
language-jade, v0.3.0
last-cursor-position, v0.7.0

# Dev
No dev packages
```

**Comment by nickckaye** [comment]
Autocomplete typing a `darken(..` function in a LESS file.

**Comment by mnquintana** [comment]
Was this in `styles.less`?

**Comment by izuzak** [comment]
@nickckaye I'm having trouble reproducing this. 

Can you please share which steps exactly reproduce the error for you in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode)? A specific example might be useful as well.

**Comment by izuzak** [comment]
Actually, it seems that you have or had the https://github.com/Glavin001/atom-preview package installed (e.g. you uninstalled it but it's still handing around) and it's causing problems. Let us know if you can reproduce in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode).
