### ISSUE TITLE
Uncaught Error: error evaluating function `darken`: undefined is not a function

### ISSUE THREAD

**Issue by nickckaye** [atom/atom#5444]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: linux 3.13.0-45-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: error evaluating function `darken`: undefined is not a function

```
At /usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/lib/less/parser.js:604

Error: 
  at new Parser (/usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
  at Object.module.exports.grammars.LESS.render (/home/nick/.atom/packages/preview/lib/renderer.coffee:73:21)
  at PreviewView.module.exports.PreviewView.renderPreviewWithRenderer (/home/nick/.atom/packages/preview/lib/preview-view.coffee:270:27)
  at PreviewView.renderPreviewWithRenderer (/home/nick/.atom/packages/preview/lib/preview-view.coffee:1:1)
  at PreviewView.module.exports.PreviewView.renderPreview (/home/nick/.atom/packages/preview/lib/preview-view.coffee:155:6)
  at PreviewView.renderPreview (/home/nick/.atom/packages/preview/lib/preview-view.coffee:1:1)
  at later (/usr/share/atom/resources/app/node_modules/roaster/node_modules/underscore/underscore.js:724:25)

```

### Commands

```
  3x -3:17.6 core:move-down (atom-text-editor.editor.is-focused)
     -3:17.2 core:move-left (atom-text-editor.editor.is-focused)
     -1:33.8 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:29.8 core:move-down (atom-text-editor.editor.mini)
     -1:29.2 core:move-up (atom-text-editor.editor.mini)
     -1:28.9 core:move-down (atom-text-editor.editor.mini)
     -1:28.4 core:confirm (atom-text-editor.editor.mini)
     -1:28.4 settings-view:uninstall-packages (atom-text-editor.editor.is-focused)
     -1:24.6 core:confirm (atom-text-editor.editor.mini)
     -1:09.2 core:move-right (atom-text-editor.editor.is-focused)
     -1:08.9 core:move-left (atom-text-editor.editor.is-focused)
     -1:07.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:06.5 core:save (atom-text-editor.editor.is-focused)
     -0:12.9 core:copy (atom-text-editor.editor)
     -0:00.9 core:paste (atom-text-editor.editor.is-focused)
     -0:00.1 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-less"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.21.2
git-blame, v0.4.0
git-log, v0.2.0
go-plus, v3.2.1
language-jade, v0.3.0
last-cursor-position, v0.7.0

# Dev
No dev packages
```

**Comment by nickckaye** [comment]
In the middle of editing a `darken()` and it's empty at this moment.

**Comment by 50Wliu** [comment]
Is this reproducible in safe mode (`atom --safe`)?

I notice that in this bug report you don't have `linter-less` installed, but there still seem to be a few packages that may be causing your errors.

**Comment by izuzak** [comment]
Seems like you have or had the https://github.com/Glavin001/atom-preview package installed and it's causing problems. Let us know if you can reproduce in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode).
