### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/blakelieberman/.atom/packages/atom-development-server/node_modules/livereload/lib/../ext/livereload.js'

### ISSUE THREAD

**Issue by blakel11** [atom/atom#5456]
[Enter steps to reproduce below:]

1.Run livereload
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/blakelieberman/.atom/packages/atom-development-server/node_modules/livereload/lib/../ext/livereload.js'

```
At fs.js:503

Error: ENOENT, no such file or directory '/Users/blakelieberman/.atom/packages/atom-development-server/node_modules/livereload/lib/../ext/livereload.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Server.<anonymous> (/Users/blakelieberman/.atom/packages/atom-development-server/node_modules/livereload/lib/livereload.js:194:27)
  at Server.emit (events.js:119:17)
  at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:493:12)
  at HTTPParser.parserOnHeadersComplete (_http_common.js:113:23)
  at Socket.socketOnData (_http_server.js:345:22)
  at Socket.emit (events.js:116:17)
  at readableAddChunk (_stream_readable.js:164:16)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:530:20)

```

### Commands

```
     -1:35.3 core:backspace (atom-text-editor.editor.mini)
     -0:43.6 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:43.6 editor:newline (atom-text-editor.editor)
     -0:43.4 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:43.4 editor:newline (atom-text-editor.editor)
     -0:41.8 emmet:expand-abbreviation-with-tab (atom-text-editor.editor)
  2x -0:40.2 core:undo (atom-text-editor.editor)
     -0:37.3 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:37.3 editor:newline (atom-text-editor.editor)
     -0:29.4 emmet:expand-abbreviation-with-tab (atom-text-editor.editor)
     -0:25.8 core:save (atom-text-editor.editor)
     -0:03.8 livereload:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {},
  "editor": {
    "softWrap": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
color-picker, v1.4.4
emmet, v2.3.3
linter, v0.11.1
livereload, v0.2.0
run-in-browser, v0.1.2

# Dev
No dev packages
```

**Comment by batjko** [comment]
Sounds like it may be an issue best placed on the [livereload](https://github.com/taggon/livereload/issues) package's repository.

**Comment by blakel11** [comment]
Thanks

**Comment by izuzak** [comment]
Yep, please re-open on livereload's issue tracker and report back here if there does seem to be an issue with Atom here.
