### ISSUE TITLE
atom permissions problem on ubuntu after building

### ISSUE THREAD

**Issue by horvan** [atom/atom#5470]
![result of compiling atom](https://cloud.githubusercontent.com/assets/5676367/6145711/14f00488-b1e5-11e4-8ff8-269f5eaaa845.PNG)
Building atom with a source dir and an installation dir show es error messages instead of building atom. May somebody test that, please.  

The error occurred on Ubuntu 14.04.1

**Comment by kevinsawicki** [comment]
What are the error messages?

**Comment by horvan** [comment]
Basically there are no error messages. But if you use the command line switches for build - dir and install - dir what you gut os not atom but a blank chrome java script engine window with a did functional menu bar.

**Comment by YuriSolovyov** [comment]
Hi, I'm getting errors on Ubuntu too.
```
$ script/build
Node: v0.12.0
npm: v2.5.1
Installing build modules...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
Installing apm...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/user/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: node_module_register
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/user/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
  at Object.<anonymous> (/home/user/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:359:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/user/atom/apm/node_modules/atom-package-manager/lib/publish.js:11:9)
  at Object.<anonymous> (/home/user/atom/apm/node_modules/atom-package-manager/lib/publish.js:500:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/user/atom/apm/node_modules/atom-package-manager/lib/apm-cli.js:38:266)
  at Object.<anonymous> (/home/user/atom/apm/node_modules/atom-package-manager/lib/apm-cli.js:219:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/user/atom/apm/node_modules/atom-package-manager/lib/cli.js:4:9)
  at Object.<anonymous> (/home/user/atom/apm/node_modules/atom-package-manager/lib/cli.js:17:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:929:3
```

**Comment by horvan** [comment]
This is just because your node version is a minor one. You should unintelligible nodes and non and then install it with the package manager solution for node source here on github.

As I said building atom is no problem but the result is not the atom editor as it was about a few weeks ago but a blank chrome engine.

**Comment by horvan** [comment]
``` Shell
Klone nach '/opt/atom'...
remote: Counting objects: 126206, done.
remote: Compressing objects: 100% (35555/35555), done.
remote: Total 126206 (delta 89026), reused 125942 (delta 88838)
Empfange Objekte: 100% (126206/126206), 256.38 MiB | 285.00 KiB/s, done.
Löse Unterschiede auf: 100% (89026/89026), done.
Prüfe Konnektivität... Fertig.

Note: checking out 'v0.178.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD ist jetzt bei 7f0110f... Update cursors as soon as all required measurements are assigned
Node: v0.10.36
npm: v1.4.28
Installing build modules...
Installing apm...
Installing modules ✓
Installing atom-dark-syntax@0.26.0 ✓
Installing atom-dark-ui@0.47.0 ✓
Installing atom-light-syntax@0.26.0 ✓
Installing atom-light-ui@0.41.0 ✓
Installing base16-tomorrow-dark-theme@0.25.0 ✓
Installing base16-tomorrow-light-theme@0.8.0 ✓
Installing one-dark-ui@0.4.0 ✓
Installing one-dark-syntax@0.3.0 ✓
Installing one-light-syntax@0.3.0 ✓
Installing one-light-ui@0.3.0 ✓
Installing solarized-dark-syntax@0.32.0 ✓
Installing solarized-light-syntax@0.19.0 ✓
Installing archive-view@0.47.0 ✓
Installing autocomplete@0.44.0 ✓
Installing autoflow@0.22.0 ✓
Installing autosave@0.20.0 ✓
Installing background-tips@0.22.0 ✓
Installing bookmarks@0.35.0 ✓
Installing bracket-matcher@0.71.0 ✓
Installing command-palette@0.34.0 ✓
Installing deprecation-cop@0.34.0 ✓
Installing dev-live-reload@0.41.0 ✓
Installing encoding-selector@0.17.0 ✓
Installing exception-reporting@0.21.0 ✓
Installing find-and-replace@0.156.0 ✓
Installing fuzzy-finder@0.65.0 ✓
Installing git-diff@0.51.0 ✓
Installing go-to-line@0.30.0 ✓
Installing grammar-selector@0.44.0 ✓
Installing image-view@0.48.0 ✓
Installing incompatible-packages@0.21.0 ✓
Installing keybinding-resolver@0.27.0 ✓
Installing link@0.30.0 ✓
Installing markdown-preview@0.134.0 ✓
Installing metrics@0.42.0 ✓
Installing notifications@0.27.0 ✓
Installing open-on-github@0.32.0 ✓
Installing package-generator@0.37.0 ✓
Installing release-notes@0.47.0 ✓
Installing settings-view@0.175.0 ✓
Installing snippets@0.72.0 ✓
Installing spell-check@0.54.0 ✓
Installing status-bar@0.59.0 ✓
Installing styleguide@0.44.0 ✓
Installing symbols-view@0.81.0 ✓
Installing tabs@0.65.0 ✓
Installing timecop@0.29.0 ✓
Installing tree-view@0.154.0 ✓
Installing update-package-dependencies@0.8.0 ✓
Installing welcome@0.21.0 ✓
Installing whitespace@0.28.0 ✓
Installing wrap-guide@0.31.0 ✓
Installing language-c@0.38.0 ✓
Installing language-clojure@0.11.0 ✓
Installing language-coffee-script@0.39.0 ✓
Installing language-csharp@0.5.0 ✓
Installing language-css@0.28.0 ✓
Installing language-gfm@0.63.0 ✓
Installing language-git@0.10.0 ✓
Installing language-go@0.21.0 ✓
Installing language-html@0.29.0 ✓
Installing language-hyperlink@0.12.2 ✓
Installing language-java@0.14.0 ✓
Installing language-javascript@0.56.0 ✓
Installing language-json@0.12.0 ✓
Installing language-less@0.24.0 ✓
Installing language-make@0.13.0 ✓
Installing language-mustache@0.11.0 ✓
Installing language-objective-c@0.15.0 ✓
Installing language-perl@0.10.0 ✓
Installing language-php@0.20.0 ✓
Installing language-property-list@0.8.0 ✓
Installing language-python@0.32.0 ✓
Installing language-ruby@0.48.0 ✓
Installing language-ruby-on-rails@0.18.0 ✓
Installing language-sass@0.34.0 ✓
Installing language-shellscript@0.12.0 ✓
Installing language-source@0.9.0 ✓
Installing language-sql@0.14.0 ✓
Installing language-text@0.6.0 ✓
Installing language-todo@0.16.0 ✓
Installing language-toml@0.15.0 ✓
Installing language-xml@0.28.0 ✓
Installing language-yaml@0.22.0 ✓
Deduping modules ✓
Running "download-atom-shell" task

Running "download-atom-shell-chromedriver" task


Running "build" task

Running "coffee:glob_to_multiple" (coffee) task
>> 363 files created.

Running "prebuild-less:src" (prebuild-less) task

Running "cson:glob_to_multiple" (cson) task
>> 179 files compiled to JSON.

Running "peg:glob_to_multiple" (peg) task

Running "generate-license:save" (generate-license) task

Running "generate-module-cache" task

Running "compile-packages-slug" task

Running "set-version" task
Done, without errors.
Running "install" task
Done, without errors.
Installing drupal-info-file to /home/drupal/.atom/packages ✓
Installing drupal to /home/drupal/.atom/packages ✓
Installing language-drupal to /home/drupal/.atom/packages ✓
Installing git-plus to /home/drupal/.atom/packages ✓
drupal@ubuntu:~$ atom
```
This is what I cot when I compile it. and installl some modules with apm the screenshot I upladed above is the result of this process

**Comment by YuriSolovyov** [comment]
it is probably better to wait till apm moves to newer node/iojs

**Comment by horvan** [comment]
may be a duplicate of #4115

**Comment by YuriSolovyov** [comment]
I'm not sure what you mean, I getting error on build step, not when launching atom.

**Comment by horvan** [comment]
Take a look at https:// raw.github.com/drubuntu/features/master/atom.sh.

This requires to apt-gget remove nodes name

and apt-get install curl 

before running it.

It is basically the building guide for Ubuntu in a script. It works on Ubuntu 14.04.1 and above.

when you have saved a copy to your disk and preformed the steps above just type sumo bash <script>
This will install atom. The build will be stored in /src/atom if the script is done.

**Comment by batjko** [comment]
This used to come up in much older versions. As a workaround, permissions to the `.atom` folder needed to be adjusted (can't find the original ticket atm).

**Comment by horvan** [comment]
I figured out that regardless of what I doing.  Atom needs to be cut with sudo. Mac users have the same problem.  I referenced the issue above.

**Comment by lee-dohm** [comment]
@horvan I'm running Atom v0.179.0-98e126b on Mac OS X 10.10.2 and I do *not* need to build nor install Atom with sudo.

**Comment by horvan** [comment]
But you need to run it with sudo right?

**Comment by lee-dohm** [comment]
@horvan No, I do not run it with sudo either.

**Comment by horvan** [comment]
@lee-dohm  alright so this is actually an Ubuntu thing. Have you set some special permissions to the atom folder to avoid using sudo?

I am asking because if you just run atom after building the result is the image I postet  with the first replay here.

**Comment by horvan** [comment]
quick fix for ubuntu

```Shell
#!/bin/bash
exprot username=`logname`
chmod -R 777 /home/"$username"/.atom
```

**Comment by mehdi-bouhalassa** [comment]
Awesome solution, worked, thanks!!
