### ISSUE TITLE
Atom throw permission denied error when trying to open.

### ISSUE THREAD

**Issue by miketamis** [atom/atom#5506]
when trying to open atom the screen is white and in the javascript console is this error:

```
Error: EACCES, permission denied '/home/mrtemp/.atom/compile-cache/less/3e6243fd266b04c3edffe341f452e2cfb2f555af/imports.json'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/usr/share/atom/resources/atom/common/lib/asar.js:422:20)
  at Object.fs.writeFileSync (fs.js:1116:15)
  at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:243:17)
  at LessCache.module.exports.LessCache.writeJson (/usr/share/atom/resources/app/node_modules/less-cache/lib/less-cache.js:152:17)
  at LessCache.module.exports.LessCache.setImportPaths (/usr/share/atom/resources/app/node_modules/less-cache/lib/less-cache.js:113:12)
  at new LessCache (/usr/share/atom/resources/app/node_modules/less-cache/lib/less-cache.js:32:12)
  at new LessCompileCache (/usr/share/atom/resources/app/src/less-compile-cache.js:20:20)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/usr/share/atom/resources/app/src/theme-manager.js:354:26)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (/usr/share/atom/resources/app/src/theme-manager.js:341:21)
  at ThemeManager.module.exports.ThemeManager.requireStylesheet (/usr/share/atom/resources/app/src/theme-manager.js:263:24)
  at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (/usr/share/atom/resources/app/src/theme-manager.js:315:12)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:606:19)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/6to5.js:138:21)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:74:25)
```

**Comment by kevinsawicki** [comment]
What version of Atom are you using? Also, did you run `atom` with `sudo` by any chance before you saw this error?

**Comment by miketamis** [comment]
Atom: 0.179.0, I may of run atom with sudo at one point to edit a file that only root can edit.

**Comment by djhi** [comment]
Got the same prb, solved by running
```
sudo chown -R `whoami` ~/.atom
```

Haven't noticed any side effects yet

**Comment by clivend** [comment]
last post did the trick for me too

**Comment by liposo** [comment]
djhi solution fix it. Thanks dude.

**Comment by nikhilbalyan** [comment]
thanx @djhi it worked for me as well.. but why did it worked ?

**Comment by rkhayat** [comment]
Thank you!

**Comment by PierreCBSI** [comment]
thx djhi - experienced the same issue after node crashed overnight, and rebooting the box did not fix it. But running `sudo chown -R `whoami` ~/.atom`  did.

**Comment by itsthejb** [comment]
Have had a related problem forever and still can't fix it. My log:

```
Error: EACCES: permission denied, mkdir '/~'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at sync (/Users/jc/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
    at sync (/Users/jc/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
    at sync (/Users/jc/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
    at sync (/Users/jc/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
    at sync (/Users/jc/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
    at Function.sync (/Users/jc/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
    at Object.fsPlus.makeTreeSync (/Users/jc/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:372:23)
    at Config.module.exports.Config.initializeConfigDirectory (/Users/jc/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:427:10)
    at Config.module.exports.Config.load (/Users/jc/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:412:12)
    at new AtomEnvironment (/Users/jc/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:268:19)
    at module.exports (/Users/jc/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:25:19)
    at setupWindow (file:///Users/jc/Applications/Atom.app/Contents/Resources/app.asar/static/index.js:87:12)
    at window.onload (file:///Users/jc/Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

Permissions change doesn't work, wiping/reinstalling don't work :/

**Comment by itsthejb** [comment]
Still no hope here. Notice in my stack stack that it's trying to create a directory at the invalid location `/~`. This would seem to be the error in my case...?

**Comment by ItamarGronich** [comment]
Yeah.. i'm experiencing this also only when running atom with sudo. 
Ubuntu 16.04
Atom 1.4.0
works on my 14.04 at work (with sudo).

here is the error.
```
Error: EACCES: permission denied, open '/home/itamar/.atom/compile-cache/less/df1b7fbc57dbeed23a8f1f8de95b4dfebcc06066/imports.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.writeFileSync (fs.js:1171:15)
    at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:155:17)
    at LessCache.module.exports.LessCache.setImportPaths (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:113:12)
    at new LessCache (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:32:12)
    at new LessCompileCache (/usr/share/atom/resources/app.asar/src/less-compile-cache.js:20:20)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/usr/share/atom/resources/app.asar/src/theme-manager.js:270:26)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/usr/share/atom/resources/app.asar/src/theme-manager.js:257:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (/usr/share/atom/resources/app.asar/src/theme-manager.js:174:24)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (/usr/share/atom/resources/app.asar/src/theme-manager.js:237:12)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (/usr/share/atom/resources/app.asar/src/theme-manager.js:232:19)
    at new AtomEnvironment (/usr/share/atom/resources/app.asar/src/atom-environment.js:250:19)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:19:19)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)handleSetupError @ index.js:62
````

**Comment by itsthejb** [comment]
@ItamarGronich, I'm afraid I've long since tried this. However, in my case it isn't even targeting that directory - but `/~`...

**Comment by tvld** [comment]
Got this this morning again on Ubuntu 16.04  When I ``chown`` to myself, it opened. Then I noticed a project folder owner by root there. I remembered that I had run ``sudo atom`` the other day.  Might help to solve this bug?

**Comment by jhessin** [comment]
This issue just came up for me.
Atom 1.23.3
Ubuntu 17.10

Steps:
Ran `sudo atom /usr/share/X11/xkb/` to modify my keymap. Atom ran with no issues.
Rebooted my system to instigate changes.
Launched atom normally and had the issue (white screen with Permission Denied error).
ran ```sudo chown -R `whoami` ~/.atom``` and the issue was fixed (but it shouldn't have happened anyway).
