### ISSUE TITLE
Uncaught Error: EEXIST, file already exists '/Volumes/xxxxxx.com/assets/templates/site/js/custom'

### ISSUE THREAD

**Issue by Cipa** [atom/atom#5518]
[Enter steps to reproduce below:]

1. I just saved a file, project is on a remote mounted disk(FTP)

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EEXIST, file already exists '/Volumes/xxxxxx.com/assets/templates/site/js/custom'

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:782

Error: EEXIST, file already exists '/Volumes/xxxxxx.com/assets/templates/site/js/custom'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:752:18)
  at Function.sync (/Applications/Atom.app/Contents/Resources/app/node_modules/mkdirp/index.js:55:12)
  at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:242:14)
  at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:234:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:304:21)
  at File.module.exports.File.write (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:293:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:970:17)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:620:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:542:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:525:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:679:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:172:20)

```

### Commands

```
     -0:19.5 editor:indent (atom-text-editor.editor)
     -0:18.9 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:18.9 editor:newline (atom-text-editor.editor)
     -0:18.7 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:18.7 editor:newline (atom-text-editor.editor)
     -0:18.6 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:18.6 editor:newline (atom-text-editor.editor)
     -0:18.4 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:18.4 editor:newline (atom-text-editor.editor)
  3x -0:18.1 core:move-up (atom-text-editor.editor)
     -0:17.5 core:paste (atom-text-editor.editor)
     -0:14.5 emmet:toggle-comment (atom-text-editor.editor)
     -0:14.5 editor:toggle-line-comments (atom-text-editor.editor)
     -0:11.2 core:copy (atom-text-editor.editor)
     -0:09.4 core:paste (atom-text-editor.editor)
     -0:08.2 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  },
  "editor": {
    "showInvisibles": true,
    "showIndentGuide": true,
    "tabLength": 4,
    "softWrap": true,
    "softTabs": false,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Sublime-Style-Column-Selection, v1.2.3
atom-beautify, v0.21.3
atom-ctags, v2.6.0
autoclose-html, v0.15.0
emmet, v2.3.3
highlight-selected, v0.7.0
html-entities, v0.3.1
less-autocompile, v0.3.3
linter, v0.11.1
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-less, v0.3.1
linter-php, v0.0.11
red-wavy-underline, v0.2.4
todo-show, v0.8.0
white-cursor, v0.5.2

# Dev
No dev packages
```

**Comment by Cipa** [comment]
It happened because the disk was not available anymore. Maybe a warning could be added when this happens
