### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by mglaman** [atom/atom#5527]
[Enter steps to reproduce below:]

1. Select all of document's text
2. Paste to overwrite from clip board.

**Atom Version**: 0.178.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:124

TypeError: Cannot read property 'id' of undefined
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateLinesState (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:238:37)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:81:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:210:32
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:320:20)
  at DisplayBuffer.module.exports.DisplayBuffer.handleBufferMarkersUpdated (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1588:21)
  at /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:599:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:507:12)
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:446:43)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2557:30
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:826:27
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1195:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:819:19)
  at TextEditor.module.exports.TextEditor.pasteText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2531:19)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.core:paste (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:434:19)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:305:34
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1195:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:172:20)

```

### Commands

```
     -2:00.9 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:00.9 core:cancel (atom-text-editor.editor.is-focused)
     -1:57.9 encoding-selector:show (atom-text-editor.editor.is-focused)
  3x -1:55.2 core:backspace (atom-text-editor.editor.mini)
     -1:53.3 editor:consolidate-selections (atom-text-editor.editor.mini)
  2x -1:53.3 core:cancel (atom-text-editor.editor.mini)
     -1:51.8 grammar-selector:show (atom-text-editor.editor.is-focused)
     -1:50.0 core:confirm (atom-text-editor.editor.mini)
     -1:46.5 core:select-all (atom-text-editor.editor.is-focused)
     -1:45.2 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:43.1 core:confirm (atom-text-editor.editor.mini)
     -1:43.1 pretty-json:prettify (atom-text-editor.editor.is-focused)
     -1:41.3 core:save (atom-text-editor.editor.is-focused)
 11x -1:30.5 pane:show-next-item (ul.list-inline.tab-bar.inset-panel)
     -0:01.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:00.6 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "archive-view"
    ],
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 12,
    "showInvisibles": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
behat-atom, v0.1.2
language-puppet, v0.10.0
linter-puppet, v0.1.0
pretty-json, v0.3.2

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
@nathansobo do you think this is a presenter regression? Just wondering from the stack trace.

**Comment by nathansobo** [comment]
@kevinsawicki Seems very likely.

**Comment by nathansobo** [comment]
Having a hard time reproducing. @mglaman if you can reproduce reliably, would be great to get some more information. I added a more detailed assertion at that spot in the code so we can hopefully get some more information about what might be going on if it happens again.

**Comment by mglaman** [comment]
It happened about three times in a row, so I finally shot issue over. Go figure after opening issue it didn't happen again.

However, should have been more specific on select/paste.
* CMD+Tab to Atom
* CMD+A
* CMD+V

@nathansobo I wish I had more :/

**Comment by maaarghk** [comment]
Just happened to me.

1. Select all text (cmd+a)
2. Hit backspace

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:124

TypeError: Cannot read property 'id' of undefined
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateLinesState (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:238:37)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:81:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:210:32
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:320:20)
  at DisplayBuffer.module.exports.DisplayBuffer.handleBufferMarkersUpdated (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1588:21)
  at /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:599:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:507:12)
  at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:604:19)
  at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:562:37)
  at Selection.module.exports.Selection.backspace (/Applications/Atom.app/Contents/Resources/app/src/selection.js:495:19)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:814:26
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:826:27
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1195:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:819:19)
  at TextEditor.module.exports.TextEditor.backspace (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:813:19)
  at TextEditor.object.(anonymous function) [as backspace] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.core:backspace (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:422:19)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:305:34
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1195:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:172:20)

```

### Commands

```
     -0:38.0 core:paste (atom-text-editor.editor)
     -0:37.4 editor:newline (atom-text-editor.editor)
     -0:34.8 core:backspace (atom-text-editor.editor)
     -0:32.3 core:move-down (atom-text-editor.editor)
  4x -0:29.8 core:backspace (atom-text-editor.editor)
     -0:28.6 core:save (atom-text-editor.editor)
     -0:24.3 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -0:22.0 core:confirm (atom-text-editor.editor.mini)
     -0:19.0 core:move-up (atom-text-editor.editor)
  2x -0:18.7 editor:newline (atom-text-editor.editor)
     -0:18.2 core:move-up (atom-text-editor.editor)
     -0:17.9 core:paste (atom-text-editor.editor)
     -0:04.8 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -0:03.6 core:confirm (atom-text-editor.editor.mini)
     -0:01.5 core:select-all (atom-text-editor.editor.is-focused)
     -0:00.8 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "monokai"
    ]
  },
  "editor": {
    "fontSize": 14,
    "lineHeight": 1.5,
    "showIndentGuide": true,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
language-apache, v1.2.0
language-ini, v1.3.0
monokai, v0.9.0
project-manager, v1.14.1
unity-ui, v1.0.7

# Dev
No dev packages
```

**Comment by LinusU** [comment]
Happend to me as well. I opened an empty document pasted in some text. Then marked part of that text and removed it. Upon pressing command + Z to undo, the error presented itself.

```text
/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:124
Hide Stack Trace
TypeError: Cannot read property 'id' of undefined
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLinesState (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:246:37)
    at TextEditorPresenter.module.exports.TextEditorPresenter.setScrollTop (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:611:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:117:32
    at /Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:155:30
    at Array.forEach (native)
    at Behavior.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:154:47)
    at Behavior.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:107:30)
    at Behavior.module.exports.Behavior.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/behavior.js:44:38)
    at Behavior.module.exports.Signal.emitValue (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/signal.js:82:19)
```

**Comment by izuzak** [comment]
Happened to me as well, but can't reproduce it. What I was doing: pasted text from an external app into Atom, used find and replace to replace some text in the document, selected all lines, tried cutting the text. The text was copied to my clipboard, but it wasn't removed from the editor (which would be expected since I used `cut` not `copy`) and the exception was thrown.

**Atom Version**: 0.183.0-25befa7
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:124

TypeError: Cannot read property 'id' of undefined
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateLinesState (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:308:37)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:86:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:210:32
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:318:20)
  at DisplayBuffer.module.exports.DisplayBuffer.handleBufferMarkersUpdated (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1586:21)
  at /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:599:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:507:12)
  at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:604:19)
  at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:561:37)
  at Selection.module.exports.Selection.delete (/Applications/Atom.app/Contents/Resources/app/src/selection.js:532:19)
  at Selection.module.exports.Selection.cut (/Applications/Atom.app/Contents/Resources/app/src/selection.js:681:28)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2515:21
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:826:27
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1195:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:819:19)
  at TextEditor.module.exports.TextEditor.cutSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2510:19)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.core:cut (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:422:19)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:299:34
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1195:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:298:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:176:20)

```

### Commands

```
     -0:19.2 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:17.8 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:17.8 core:cancel (atom-text-editor.editor.is-focused)
     -0:17.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:17.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:16.4 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:16.4 core:cancel (atom-text-editor.editor.is-focused)
     -0:16.2 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:16.2 core:cancel (atom-text-editor.editor.is-focused)
     -0:16.1 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:16.1 core:cancel (atom-text-editor.editor.is-focused)
     -0:15.9 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:15.9 core:cancel (atom-text-editor.editor.is-focused)
     -0:12.7 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:03.3 core:select-all (atom-text-editor.editor.is-focused)
     -0:01.2 core:cut (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "relative-numbers",
      "emmet",
      "git-tab-status",
      "jsformat"
    ],
    "audioBeep": false,
    "excludeVcsIgnoredPaths": false
  },
  "editor": {
    "showIndentGuide": true,
    "softWrap": true,
    "invisibles": {},
    "scrollPastEnd": true,
    "showInvisibles": true,
    "fontSize": 25
  }
}
```

### Installed Packages

```coffee
# User
atom-the-closer, v0.4.0

# Dev
No dev packages
```

**Comment by nathansobo** [comment]
These errors should be replaced by errors resembling #5667 now that an assertion has been added to the code. I'll leave this open until that issue is solved however.

**Comment by nathansobo** [comment]
I just eliminated one category of this error, which was associated with trying to preserve the target of the most recent mousewheel event for a window of time, even after it had been deleted. There still remains one case in #5667 which used to throw this exception and now throws a more specific error message. Trying to figure that one out still.
