### ISSUE TITLE
Unable to install on windows

### ISSUE THREAD

**Issue by drtweety** [atom/atom#5541]
I am not able to install atom on windows, here is the install log:

```
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\Daniyaal Khan.livingroom-pc\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\Daniyaal Khan.livingroom-pc\AppData\Local\SquirrelTemp
ApplyReleasesImpl: Writing files to app directory: C:\Users\Daniyaal Khan.livingroom-pc\AppData\Local\atom\app-0.179.0
IEnableLogger: Failed to write file: C:\Users\Daniyaal Khan.livingroom-pc\AppData\Local\atom\app-0.179.0: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.PhysicalPackageFile.GetStream()
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass90.<copyFileToLocation>b__8f()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.PhysicalPackageFile.GetStream()
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass90.<copyFileToLocation>b__8f()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.UpdateManager.ApplyReleasesImpl.copyFileToLocation(FileSystemInfo target, IPackageFile x)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass86.<installPackageToAppDir>b__83(IPackageFile x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass86.<installPackageToAppDir>b__82()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__88.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4b`1.MoveNext()
```

**Comment by melchiorb** [comment]
Probably same as this one: https://github.com/atom/atom/issues/5109

**Comment by 50Wliu** [comment]
Yes, please subscribe to #5109 for updates.  Thanks @melchiorb.
