### ISSUE TITLE
Right-clicking window with no tabs throws an error

### ISSUE THREAD

**Issue by karai17** [atom/atom#5551]
```
Uncaught Error: Cannot find module './context-menu' Error: Cannot find module './context-menu'
at Function.Module._resolveFilename (module.js:351:15)
at Function.Module._load (module.js:293:25)
at Module.require (module.js:380:17)
at require (module.js:399:17)
at BrowserWindow. (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\app\src\browser\atom-window.js:127:27)
at BrowserWindow.emit (events.js:116:17)
at callFunction (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\atom\browser\lib\rpc-server.js:116:18)
at EventEmitter. (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\atom\browser\lib\rpc-server.js:208:14)
at EventEmitter.emit (events.js:127:17)
at EventEmitter. (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\atom\browser\api\lib\web-contents.js:99:23)
```

```
C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\atom\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at BrowserWindow.<anonymous> (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\app\src\browser\atom-window.js:127:27)
    at BrowserWindow.emit (events.js:116:17)
    at callFunction (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\atom\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\atom\browser\lib\rpc-server.js:208:14)
    at EventEmitter.emit (events.js:127:17)
    at EventEmitter.<anonymous> (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\atom\browser\api\lib\web-contents.js:99:23)
  at metaToValue (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\atom\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\atom\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\app\src\context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\app\src\window-event-handler.js:143:33)
  at HTMLDocument.handler (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\app\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
```

**Comment by karai17** [comment]
Looks like my install was corrupted, this no longer occurs after a reinstall.
