### ISSUE TITLE
Uncaught Error: spawn ENOMEM

### ISSUE THREAD

**Issue by daxliar** [atom/atom#5560]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.179.0
**System**: linux 3.13.0-45-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn ENOMEM

```
At child_process.js:1160

Error: spawn ENOMEM
  at exports._errnoException (util.js:753:11)
  at ChildProcess.spawn (child_process.js:1160:11)
  at exports.spawn (child_process.js:993:9)
  at exports.fork (child_process.js:594:10)
  at module.(anonymous function) (/usr/share/atom/resources/atom/common/lib/asar.js:422:20)
  at child_process.fork (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:62:14)
  at new Task (/usr/share/atom/resources/app/src/task.js:40:27)
  at Function.module.exports.Task.once (/usr/share/atom/resources/app/src/task.js:17:14)
  at GitRepository.module.exports.GitRepository.refreshStatus (/usr/share/atom/resources/app/src/git-repository.js:398:37)
  at /usr/share/atom/resources/app/src/git-repository.js:81:26

```

### Commands

```
  2x -6:44.9 editor:toggle-soft-wrap (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -6:14.6 core:copy (atom-text-editor.editor.is-focused)
     -5:09.8 core:paste (atom-text-editor.editor.is-focused)
     -5:04.3 core:move-down (atom-text-editor.editor.is-focused)
     -5:04.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -5:03.5 core:move-left (atom-text-editor.editor.is-focused)
 10x -5:01.1 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
 18x -4:57.4 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  5x -4:55.2 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -4:52.8 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -4:50.7 core:move-down (atom-text-editor.editor.is-focused)
  2x -4:50.5 core:move-left (atom-text-editor.editor.is-focused)
     -4:48.6 core:move-down (atom-text-editor.editor.is-focused)
  2x -4:48.3 core:move-left (atom-text-editor.editor.is-focused)
     -4:46.4 core:save (atom-text-editor.editor.is-focused)
  2x -1:13.7 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 22,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
markdown-writer, v0.10.2

# Dev
No dev packages
```

**Comment by KeitIG** [comment]
Got the same after a `git pull`

**Comment by Stephen304** [comment]
I just had this issue, error out of nowhere

**Comment by 50Wliu** [comment]
@Stephen304 What Atom version are you on?

**Comment by Stephen304** [comment]
1.0.5. My tmpfs on /tmp ran out of space while I was upgrading packages while atom was running, I think that might have caused it.

**Comment by jamen** [comment]
I just got this issue.

**Comment by ciacicode** [comment]
just got this issue as well Atom v 1.4.3 running on ubuntu 14.04. The error occured while i was testing on my localhost a Flask application.
