### ISSUE TITLE
Uncaught Error: ENXIO, no such device or address '/Users/tobe/mnt/sprix/monkey/goalstart.git/goalstart/gs_frontend_webview/classes/controller/web/invite/list.php'

### ISSUE THREAD

**Issue by shinyatto** [atom/atom#5576]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENXIO, no such device or address '/Users/tobe/mnt/sprix/monkey/goalstart.git/goalstart/gs_frontend_webview/classes/controller/web/invite/list.php'

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:782

Error: ENXIO, no such device or address '/Users/tobe/mnt/sprix/monkey/goalstart.git/goalstart/gs_frontend_webview/classes/controller/web/invite/list.php'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.writeFileSync (fs.js:1116:15)
  at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:243:17)
  at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:234:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:304:21)
  at File.module.exports.File.write (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:293:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:970:17)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:620:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:542:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:525:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:679:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:172:20)

```

### Commands

```
     -1:50.8 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  4x -1:50.5 core:move-left (atom-text-editor.editor.is-focused)
  3x -1:49.4 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:47.9 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  5x -1:47.5 core:move-up (atom-text-editor.editor.is-focused)
  9x -1:46.2 core:select-down (atom-text-editor.editor.is-focused)
     -1:44.7 core:select-up (atom-text-editor.editor.is-focused)
     -1:43.7 core:copy (atom-text-editor.editor.is-focused)
     -1:43.3 core:move-down (atom-text-editor.editor.is-focused)
     -1:42.4 core:paste (atom-text-editor.editor.is-focused)
  5x -1:42.0 core:move-up (atom-text-editor.editor.is-focused)
  5x -0:12.5 core:move-down (atom-text-editor.editor)
     -0:10.7 editor:move-to-end-of-screen-line (atom-text-editor.editor)
     -0:10.3 core:move-up (atom-text-editor.editor)
  2x -0:09.7 editor:newline (atom-text-editor.editor)
     -0:00.7 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true,
    "tabLength": 4,
    "preferredLineLength": 9999
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@shinyatto, could you please share some steps to reproduce?
