### ISSUE TITLE
Error building atom on Arch Linux

### ISSUE THREAD

**Issue by franktopel** [atom/atom#5583]
[connexo@archgott atom]$ script/build
Node: v0.12.0
npm: v2.5.1
Installing build modules...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
Installing apm...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/connexo/packages/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/connexo/packages/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/home/connexo/packages/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:359:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by izuzak** [comment]
See https://github.com/atom/atom/issues/3385

**Comment by franktopel** [comment]
The page you suggested tells me to do script/clean before script/build. I did, with the same resulting error.

**Comment by izuzak** [comment]
@franktopel Have you tried using the required version of node (v0.10.x):

https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#requirements

**Comment by amiuhle** [comment]
Same problem on Ubuntu 14.10 with io.js 1.2

**Comment by kevinsawicki** [comment]
@amiuhle what commit did you try and build?

**Comment by amiuhle** [comment]
Tried on both `v0.180.0` and `v0.181.0`
