### ISSUE TITLE
Access denied while installing atom 0.180 on administrator mode

### ISSUE THREAD

**Issue by emarques** [atom/atom#5612]
I've tried to install the atom 0.180 setup on my computer, tried to run it as administrator and install it on windows 7, but got no luck installing it :/

```
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\emarques.QUIDGEST\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.FileNotFoundException: Could not find file 'C:\Users\emarques.QUIDGEST\AppData\Local\atom\packages\RELEASES'.
File name: 'C:\Users\emarques.QUIDGEST\AppData\Local\atom\packages\RELEASES'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
Utility: Starting to delete folder: C:\Users\emarques.QUIDGEST\AppData\Local\atom\packages
CheckForUpdateImpl: Reading RELEASES file from C:\Users\emarques.QUIDGEST\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\emarques.QUIDGEST\AppData\Local\atom\app-0.180.0
Utility: Starting to delete folder: C:\Users\emarques.QUIDGEST\AppData\Local\atom\app-0.180.0
...
Utility: Starting to delete folder: C:\Users\emarques.QUIDGEST\AppData\Local\atom\app-0.180.0\resources\app\menus
ApplyReleasesImpl: Writing files to app directory: C:\Users\emarques.QUIDGEST\AppData\Local\atom\app-0.180.0
IEnableLogger: Failed to write file: C:\Users\emarques.QUIDGEST\AppData\Local\atom\app-0.180.0: System.UnauthorizedAccessException: Access to the path 'C:\Users\emarques.QUIDGEST\AppData\Local\Temp\nuget\3josmkgd.yyg\lib\net45\resources\app\node_modules\6to5-core\node_modules\core-js\src\core.log.js' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.PhysicalPackageFile.GetStream()
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass90.<copyFileToLocation>b__8f()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
IEnableLogger: Failed to install package to app dir: System.UnauthorizedAccessException: Access to the path 'C:\Users\emarques.QUIDGEST\AppData\Local\Temp\nuget\3josmkgd.yyg\lib\net45\resources\app\node_modules\6to5-core\node_modules\core-js\src\core.log.js' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.PhysicalPackageFile.GetStream()
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass90.<copyFileToLocation>b__8f()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.UpdateManager.ApplyReleasesImpl.copyFileToLocation(FileSystemInfo target, IPackageFile x)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass86.<installPackageToAppDir>b__83(IPackageFile x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass86.<installPackageToAppDir>b__82()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__88.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4b`1.MoveNext()
```

**Comment by 50Wliu** [comment]
To be clear-are you right-clicking and choosing `Run as Administrator` or just trying to install it under an administrator account?

/cc @paulcbetts

**Comment by emarques** [comment]
I am an administrator and I am also choosing to run it as administrator

**Comment by Taiterio** [comment]
Getting exactly the same error with versions 0.180 and 0.181, it works perfectly for me when using the installer for 0.179.

**Comment by paulcbetts** [comment]
Can you try this on 0.182?

**Comment by emarques** [comment]
Got the same error in the same file

```
IEnableLogger: Failed to write file: C:\Users\emarques.QUIDGEST\AppData\Local\atom\app-0.182.0: System.UnauthorizedAccessException: Access to the path 'C:\Users\emarques.QUIDGEST\AppData\Local\Temp\nuget\u24a0h33.fv5\lib\net45\resources\app\node_modules\6to5-core\node_modules\core-js\src\core.log.js' is denied.
```

**Comment by paulcbetts** [comment]
@emarques Do you have an Antivirus app installed?

**Comment by emarques** [comment]
@paulcbetts I have Comodo Internet Security Premium installed, I've disabled it and everything went smooth while installing :+1: thanks

you may close this issue :smile:

**Comment by Taiterio** [comment]
Had Comodo aswell, but Atom didnt show up in any of the antivirus events, disabling it worked though; should have checked that out earlier :D

**Comment by paulcbetts** [comment]
This appears to be Antivirus-related
