### ISSUE TITLE
Uncaught Error: RegExp is not valid

### ISSUE THREAD

**Issue by roonie** [atom/atom#5638]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.180.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: RegExp is not valid

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:124

Error: RegExp is not valid
    at Error (native)
    at OnigScanner.findNextMatchSync (/Applications/Atom.app/Contents/Resources/app/node_modules/oniguruma/lib/oniguruma.js:35:18)
    at Scanner.module.exports.Scanner.findNextMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:57:23)
    at Rule.module.exports.Rule.findNextMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/rule.js:101:28)
    at Rule.module.exports.Rule.getNextTokens (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/rule.js:143:21)
    at Grammar.module.exports.Grammar.tokenizeLine (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:125:39)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:488:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:477:19)
    at TokenizedBuffer.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:430:31)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLinesForRows (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:438:10)
```
### Commands

```
     -6:49.6 core:copy (atom-text-editor.editor)
     -6:48.8 core:paste (atom-text-editor.editor)
     -6:48.5 core:save (atom-text-editor.editor)
     -5:56.9 core:copy (atom-text-editor.editor)
     -5:56.3 core:paste (atom-text-editor.editor)
     -5:55.5 core:backspace (atom-text-editor.editor)
  2x -5:51.4 core:undo (atom-text-editor.editor)
     -5:48.0 core:copy (atom-text-editor.editor)
     -5:47.1 core:move-right (atom-text-editor.editor)
     -5:46.7 core:paste (atom-text-editor.editor)
     -5:41.2 core:copy (atom-text-editor.editor)
     -5:40.1 core:paste (atom-text-editor.editor)
     -5:39.8 core:save (atom-text-editor.editor)
     -5:37.7 core:close (atom-text-editor.editor)
     -0:11.3 core:paste (atom-text-editor.editor.is-focused)
  2x -0:07.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "editor": {
    "fontSize": 12,
    "showIndentGuide": true,
    "invisibles": {}
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v1.1.0
language-ember-script, v0.1.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
Did you get this error while editing an EmberScript file?

**Comment by roonie** [comment]
No, while editing a rails erb file.
Now getting it constantly :(

**Comment by roonie** [comment]
After restarting atom the issue seems to be gone for now
