### ISSUE TITLE
Uncaught TypeError: Cannot read property 'copy' of undefined

### ISSUE THREAD

**Issue by thomashermant** [atom/atom#5649]
[Enter steps to reproduce below:]
1. Fold some method
2. Select these folded method
3. CUT (cmd+x)
   -> error is displayed

**Atom Version**: 0.181.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'copy' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:124

TypeError: Cannot read property 'copy' of undefined
  at DisplayBuffer.module.exports.DisplayBuffer.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1493:35)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1462:20)
  at Fold.module.exports.Fold.updateDisplayBuffer (/Applications/Atom.app/Contents/Resources/app/src/fold.js:91:35)
  at Fold.module.exports.Fold.destroyed (/Applications/Atom.app/Contents/Resources/app/src/fold.js:99:19)
  at /Applications/Atom.app/Contents/Resources/app/src/fold.js:21:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:318:20)
  at Fold.module.exports.Fold.destroy (/Applications/Atom.app/Contents/Resources/app/src/fold.js:44:26)
  at /Applications/Atom.app/Contents/Resources/app/src/fold.js:29:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.resumeChangeEvents (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:559:24)
  at MarkerManager.module.exports.MarkerManager.resumeChangeEvents (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-manager.js:235:30)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:597:15)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:507:12)
  at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:604:19)
  at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:561:37)
  at Selection.module.exports.Selection.delete (/Applications/Atom.app/Contents/Resources/app/src/selection.js:532:19)
  at Selection.module.exports.Selection.cut (/Applications/Atom.app/Contents/Resources/app/src/selection.js:681:28)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2515:21
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:826:27
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1195:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:819:19)
  at TextEditor.module.exports.TextEditor.cutSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2510:19)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.core:cut (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:428:19)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:305:34
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1195:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:176:20)

```
### Commands

```
  2x -5:38.0 editor:move-to-beginning-of-word (atom-text-editor.editor)
  3x -5:37.4 editor:move-to-end-of-word (atom-text-editor.editor)
     -5:36.6 core:move-left (atom-text-editor.editor)
  4x -5:36.3 editor:select-to-end-of-word (atom-text-editor.editor)
     -5:35.0 core:copy (atom-text-editor.editor)
     -5:27.0 core:save (atom-text-editor.editor)
     -5:22.9 core:copy (atom-text-editor.editor)
     -5:20.7 core:paste (atom-text-editor.editor)
  2x -5:20.4 core:save (atom-text-editor.editor)
     -3:35.5 core:paste (atom-text-editor.editor)
     -3:35.1 core:save (atom-text-editor.editor)
     -3:17.5 core:paste (atom-text-editor.editor)
     -3:17.1 core:save (atom-text-editor.editor)
     -0:08.8 core:move-down (atom-text-editor.editor.is-focused)
 12x -0:08.2 core:select-down (atom-text-editor.editor.is-focused)
     -0:01.6 core:cut (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "minimap",
      "meteor-api"
    ],
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 12,
    "fontFamily": "Menlo",
    "lineHeight": 1.4,
    "showIndentGuide": true,
    "showInvisibles": true,
    "tabLength": 4
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.1.6
color-picker, v1.4.4
emmet, v2.3.3
language-jade, v0.3.0
react, v0.9.9
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

**Comment by thomashermant** [comment]
Hummm ...

Sorry I have unfolded these methods then cut it -> it's working
Then I retry to reproduce the bug : folding these methods and cut it... 
but it's working now...

I've got this error 4 times before submit the issue
Sorry guys (and girls)
