### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/6to5-core/node_modules/regenerator-6to5/node_modules/commoner/node_modules/iconv-lite/lib/index.js'

### ISSUE THREAD

**Issue by nallie** [atom/atom#5650]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/6to5-core/node_modules/regenerator-6to5/node_modules/commoner/node_modules/iconv-lite/lib/index.js'

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:782

Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/6to5-core/node_modules/regenerator-6to5/node_modules/commoner/node_modules/iconv-lite/lib/index.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:136:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:239:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:304:21)
  at File.module.exports.File.write (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:293:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:970:17)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:620:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:542:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:525:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:679:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:172:20)

```

### Commands

```
     -0:02.8 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:02.8 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:00.8 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tabs",
      "tree-view"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "destroyEmptyPanes": false
  },
  "editor": {
    "showIndentGuide": true,
    "invisibles": {},
    "autoIndentOnPaste": false
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v0.5.3
autoclose-html, v0.15.0
autocomplete-plus, v2.1.6
color-picker, v1.4.4
editorconfig, v0.3.0
emmet, v2.3.3
file-icons, v1.4.11
highlight-selected, v0.9.0
linter, v0.11.1
minimap, v4.2.2
monokai, v0.12.0
sublime-tabs, v0.4.9

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Can you try upgrading to 0.181.0 and see if that helps? 

Similar to https://github.com/atom/release-notes/issues/29 and https://github.com/atom/tree-view/issues/377.

**Comment by izuzak** [comment]
@atom/core There's a couple of these issues around: atom/release-notes#29, atom/tree-view#377 and this one. All seem to be <0.179.0, I haven't seen a report for 0.180.0 or higher. Not sure if that's relevant. And as far as I can tell, it's not reproducible.

Anyway, I have no idea why this might be happening. Just wondering if you have any :thought_balloon: or :bulb:.

**Comment by nallie** [comment]
I currently am using 0.181.0 and that error is not reproducible on my end either. I installed file-icons, restarted atom, then tried to save and it gave me that error. Closed atom, open the file, then saved; I had no problems. Maybe it was just a one time thing? Thanks for the quick response.

**Comment by kevinsawicki** [comment]
This should be fixed now that [asar support in Atom](https://github.com/atom/atom/pull/6313) has shipped. Please comment if it happens again on Atom 0.194.0+.
