### ISSUE TITLE
Uncaught Error: EROFS, read-only file system '/Volumes/RECOVERY/recovery.cmdline'

### ISSUE THREAD

**Issue by johnkors** [atom/atom#5665]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.174.0
**System**: Mac OS X 10.8.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EROFS, read-only file system '/Volumes/RECOVERY/recovery.cmdline'

```
At /Applications/Atom.app/Contents/Resources/app/src/workspace.js:504

Error: EROFS, read-only file system '/Volumes/RECOVERY/recovery.cmdline'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app/src/project.js:287:31)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:492:31)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:418:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {}
}
```

### Installed Packages

```coffee
# User
atom-runner, v1.1.0
jshint, v0.7.2
linter, v0.5.14
monokai, v0.7.0
pain-split, v1.1.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please upgrade Atom to the latest version (currently 0.182.0).

**Comment by johnkors** [comment]
Thanks, that works :)
