### ISSUE TITLE
Uncaught Error: No line exists for row 18. Last screen row: 17

### ISSUE THREAD

**Issue by dantreasure** [atom/atom#5667]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.180.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: No line exists for row 18. Last screen row: 17

```
At /Users/dan.treasure/Downloads/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:234

Error: No line exists for row 18. Last screen row: 17
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLinesState (/Users/dan.treasure/Downloads/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:234:17)
    at TextEditorPresenter.module.exports.TextEditorPresenter.characterWidthsChanged (/Users/dan.treasure/Downloads/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:835:12)
    at TextEditorPresenter.module.exports.TextEditorPresenter.batchCharacterMeasurement (/Users/dan.treasure/Downloads/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:815:21)
    at module.exports.React.createClass.measureCharactersInNewLines (/Users/dan.treasure/Downloads/Atom.app/Contents/Resources/app/src/lines-component.js:341:24)
    at boundMethod [as measureCharactersInNewLines] (/Users/dan.treasure/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
    at module.exports.React.createClass.componentDidUpdate (/Users/dan.treasure/Downloads/Atom.app/Contents/Resources/app/src/lines-component.js:108:14)
    at CallbackQueue.mixInto.notifyAll (/Users/dan.treasure/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Users/dan.treasure/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
    at ReactReconcileTransaction.Mixin.closeAll (/Users/dan.treasure/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
    at ReactReconcileTransaction.Mixin.perform (/Users/dan.treasure/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
```

### Commands

```
     -0:00.8 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "editor": {
    "fontSize": 23
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v1.4.3
autocomplete-plus, v0.21.0
linter, v0.4.11
linter-coffeelint, v0.1.1
ruby-slim, v0.2.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @dantreasure, can you please try to reproduce this in safe mode (`atom --safe`)?  What were you doing when this happened?  Does this happen in the latest Atom version (currently 0.182.0)?

/cc @nathansobo

**Comment by nathansobo** [comment]
@50Wliu This is most likely legit.

**Comment by nathansobo** [comment]
Looking into this today. The fundamental question I need to answer is how the number of lines can change without the `endRow` being recalculated in the presenter. This bug is being caused by our `endRow` in the presenter getting out of sync with the actual content in the editor.

**Comment by nathansobo** [comment]
Any information about reproducing this one would be most helpful.

**Comment by mitzkia** [comment]
Maybe I found a similar issue, please see: #5883

**Comment by izuzak** [comment]
@nathansobo I finally managed to reproduce this :beetle:. :tada: 

Steps:

1. Make sure you have the autosave package enabled and the config option to autosave checked
2. Make sure you have the whitespace package enabled and the option "Remove trailing whitespace" checked
3. Open a file
4. Split panes
5. Add a few empty lines to the end of the file
6. Add new cursors to the empty lines you added
7. Close the split pane
8. :boom:

:tv:

![rows](https://cloud.githubusercontent.com/assets/38924/6525013/6cd08178-c400-11e4-943b-9c2156ad6cee.gif)
