### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getScopeDescriptor' of undefined

### ISSUE THREAD

**Issue by jutaz** [atom/atom#5689]
[Enter steps to reproduce below:]

1. Save a HTML file

I had 3 open panes at the time. (top left, bottom left, single right)

it looks like it only happens when I save a HTML (only HTML) file in bottom left pane (only in this pane).

**EDIT:**

After the error happens in described pane, moving the file to other panes will cause the same error.

**Atom Version**: 0.178.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getScopeDescriptor' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:782

TypeError: Cannot read property 'getScopeDescriptor' of undefined
  at TextEditor.module.exports.TextEditor.scopesAtCursor (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2474:34)
  at TextEditor.module.exports.TextEditor.getCursorScopes (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2479:19)
  at Object.module.exports.format (/Users/jutaz/.atom/packages/go-format/lib/go-format.coffee:45:22)
  at /Users/jutaz/.atom/packages/go-format/lib/go-format.coffee:34:10
  at TextBuffer.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:977:19)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:620:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:542:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:525:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:679:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:172:20)

```

### Commands

```
     -3:21.6 pane:split-down (atom-text-editor.editor)
  2x -2:51.6 editor:newline (atom-text-editor.editor.is-focused)
     -2:21.0 core:copy (atom-text-editor.editor)
     -2:18.8 core:paste (atom-text-editor.editor.is-focused)
  2x -2:18.1 core:save (atom-text-editor.editor.is-focused)
  2x -1:42.8 core:backspace (atom-text-editor.editor.is-focused)
     -1:42.4 core:save (atom-text-editor.editor.is-focused)
     -0:58.2 settings-view:open (atom-text-editor.editor)
     -0:26.6 core:backspace (atom-text-editor.editor.is-focused)
     -0:21.9 core:save (atom-text-editor.editor.is-focused)
     -0:19.6 core:copy (atom-text-editor.editor.is-focused)
     -0:16.0 settings-view:open (atom-text-editor.editor)
     -0:00.5 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "color-picker",
      "dev-live-reload",
      "jsformat",
      "markdown-preview",
      "go-format"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "projectHome": "/Users/jutaz/Repos"
  },
  "editor": {
    "preferredLineLength": 120,
    "softTabs": false,
    "invisibles": {},
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
atom-lint, v0.20.1
editorconfig, v0.3.0
language-puppet, v0.10.0
linter, v0.11.1
linter-puppet-lint, v0.2.8
seti-syntax, v0.2.1
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This:
```
at Object.module.exports.format (/Users/jutaz/.atom/packages/go-format/lib/go-format.coffee:45:22)
at /Users/jutaz/.atom/packages/go-format/lib/go-format.coffee:34:10
```
But...this:
```
"disabledPackages": [
      "go-format"
    ],
```
?

**Comment by jutaz** [comment]
oh, that\`s a nice find!

I have no idea, how this happened, though.
I disabled this plugin just a few minutes before this error started popping out

**Comment by postcasio** [comment]
Yes this looks like a problem with `go-format`. It persists despite deactivation because the package does not clean up its subscriptions when it's deactivated.

It's quite old and hasn't been updated for almost a year. I recommend uninstalling it and trying [go-plus](https://atom.io/packages/go-plus) instead, it offers formatting and a few other features as well.

**Comment by postcasio** [comment]
The existing issue for this is https://github.com/lsegal/atom-go-format/issues/9
