### ISSUE TITLE
apm install --check TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by adicirstei** [atom/atom#5710]
Hi,

When I try to check if everything is installed and configured properly for `apm` to run, I get the bellow error. Any Idea what is going wrong?

Thanks!

```
D:\proiecte>node --version
v0.12.0
D:\proiecte>npm --version
2.5.1
D:\proiecte>atom --version
[28240:0224/121457:INFO:CONSOLE(0)] 0.181.0
D:\proiecte>apm --version
apm  0.140.0
npm  2.5.1
node 0.10.35
python 2.7.8
git 1.8.1.msysgit.1
visual studio 2013
D:\proiecte>apm install --check
Checking for native build tools
D:\Users\adrian_cirstei\AppData\Local\atom\app-0.181.0\resources\app\apm\lib\install.js:77
      useStrictSsl = (_ref = this.npm.config.get('strict-ssl')) != null ? _ref
                                     ^
TypeError: Cannot read property 'config' of undefined
    at Install.module.exports.Install.installNode (D:\Users\adrian_cirstei\AppData\Local\atom\app-0.181.0\resources\app\apm\lib\install.js:77:38)
    at Install.installNode (D:\Users\adrian_cirstei\AppData\Local\atom\app-0.181.0\resources\app\apm\lib\install.js:3:61)
    at Install.module.exports.Install.checkNativeBuildTools (D:\Users\adrian_cirstei\AppData\Local\atom\app-0.181.0\resources\app\apm\lib\install.js:559:19)
    at Install.module.exports.Install.run (D:\Users\adrian_cirstei\AppData\Local\atom\app-0.181.0\resources\app\apm\lib\install.js:724:21)
    at Object.module.exports.run (D:\Users\adrian_cirstei\AppData\Local\atom\app-0.181.0\resources\app\apm\lib\apm-cli.js:209:32)
    at Object.<anonymous> (D:\Users\adrian_cirstei\AppData\Local\atom\app-0.181.0\resources\app\apm\lib\cli.js:6:7)
    at Object.<anonymous> (D:\Users\adrian_cirstei\AppData\Local\atom\app-0.181.0\resources\app\apm\lib\cli.js:17:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by steelbrain** [comment]
You might want to open this issue on this repo https://github.com/atom/apm

**Comment by adicirstei** [comment]
Hi,

sorry, I wasn't aware that there are two separate projects.
