### ISSUE TITLE
Unable to build on CentOS 6.5

### ISSUE THREAD

**Issue by zachradtka** [atom/atom#5731]
This issue may be related to issue #2177. 

My system is 
- Cent OS 6.5
- node v0.10.36
- npm 1.4.28

It is important to note that **libgnome-keyring-dev** is not available from the Cent OS 6 repos, so I was unable to install it. I was able to **install gnome-keyring**, but that obviously doesn't have the development headers.

I originally tried to download and run the latest rpm, but I was given the following output.

```
$ atom
/usr/local/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /usr/local/share/atom/atom)
/usr/local/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/local/share/atom/atom)
/usr/local/share/atom/atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/share/atom/atom)
/usr/local/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/local/share/atom/libchromiumcontent.so)
/usr/local/share/atom/atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/share/atom/libchromiumcontent.so)
/usr/local/share/atom/atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/share/atom/libgcrypt.so.11)
/usr/local/share/atom/atom: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /usr/local/share/atom/libgcrypt.so.11)
```

After that failed and I found issue [2177](https://github.com/atom/atom/issues/2177) I tried to compile Atom on my local machine.

I followed all of the guides, multiple times, but I am still unable to successfully build Atom from source. The output I get when attempting to build is as follows:

```
$ script/build 
Node: v0.10.36
npm: v1.4.28
Installing build modules...
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/memory:83,
                 from ../node_modules/native-mate/vendor/base-minimal/src/base/threading/thread_collision_warner.h:8,
                 from ../node_modules/native-mate/vendor/base-minimal/src/base/memory/ref_counted.h:13,
                 from ../node_modules/native-mate/vendor/base-minimal/src/base/callback_internal.h:14,
                 from ../node_modules/native-mate/vendor/base-minimal/src/base/callback.h:14,
                 from ../node_modules/native-mate/vendor/base-minimal/src/base/bind_helpers.h:147,
                 from ../node_modules/native-mate/vendor/base-minimal/src/base/bind_internal.h:13,
                 from ../node_modules/native-mate/vendor/base-minimal/src/base/bind.h:13,
                 from ../node_modules/native-mate/vendor/src/native_mate/object_template_builder.h:8,
                 from ../node_modules/native-mate/vendor/src/native_mate/dictionary.h:9,
                 from ../node_modules/native-mate/vendor/src/native_mate/dictionary.cc:5:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_deleter<_Ptr, _Deleter, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:146: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:204: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In constructor ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, _Alloc, _Args&& ...)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:861: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In function ‘_Del* std::get_deleter(const std::__shared_ptr<_Tp2, _Lp>&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:1005: error: cannot use typeid with -fno-rtti
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-unused-local-typedefs"
make: *** [Release/obj.target/native_mate/node_modules/native-mate/vendor/src/native_mate/dictionary.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-504.3.3.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/zach/Downloads/atom/build/node_modules/grunt-atom-shell-installer/node_modules/asar/node_modules/chromium-pickle
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

npm ERR! chromium-pickle@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromium-pickle@0.1.4 install script.
npm ERR! This is most likely a problem with the chromium-pickle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls chromium-pickle
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "--userconfig=/home/zach/Downloads/atom/.npmrc" "install" "--loglevel" "error"
npm ERR! cwd /home/zach/Downloads/atom/build
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

I looked to see if I could build with a more verbose output, but I was unable to find any options.

I was wondering if anyone has any success or solutions?

**Comment by gliurn** [comment]
I have same errors, it came from atom-shell but it seems like there is nobody who find solutions . I hope some people will help us.

**Comment by 50Wliu** [comment]
Isn't this the same issue as #2177?

**Comment by gliurn** [comment]
Really? this issue end without solution, just a lost guy who speak about NW, don t think i haven t search, all existing issues about atom or atom-shell on CentOS aren t solved they are just close because "CentOS isn t the most popular linux distribution so we don t care"

**Comment by zachradtka** [comment]
Ubuntu is a popular Linux distro, so if software is developed on dependencies that exist in Ubuntu and don't exist in CentOS, then the software being developed will not work on CentOS. I am sure that CentOS 7 would have the dependencies needed to build Atom, but as far as popularity goes, CentOS 6 is much more popular than CentOS 7 because most of the industry is is still using RHEL 6.

It is kinda sad that a lot of software only support Ubuntu/Debian distros, but that is the way it is.

**Comment by KarateSnowMachine** [comment]
If you upgrade your compiler to gcc 4.8 by installing devtoolset-2 (see: http://superuser.com/questions/381160/how-to-install-gcc-4-7-x-4-8-x-on-centos ) -- you should be able to get past the build error, however, you'll still run into the runtime problem described in #2177 .

**Comment by zachradtka** [comment]
That is a good point. When I was initially trying to solve this problem, I did install devtoolset-2. It does fix the build errors, but none of the devtoolset's came with a libstdc++.so.6 that contained GLIBCXX_3.4.14 or GLIBCXX_3.4.15.

**Comment by codeassassin** [comment]
Still no solution? This is sad

**Comment by jeffshaver** [comment]
also having this issue

**Comment by damodaran** [comment]
I am using Centos 6.8. The editor is not working.
```
$ atom .
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/share/atom/libnode.so)
```
```
$ cat /etc/centos-release
CentOS release 6.8 (Final)

```
