### ISSUE TITLE
Failed to activate package - can we improve user notification ?

### ISSUE THREAD

**Issue by crucialfelix** [atom/atom#5743]
I am the developer of a package https://atom.io/packages/supercollider

Recently the package stopped working due to 6to5 raising an issue with unsafe use of eval in a dependency of a dependency of a dependency of atom-supercollider. Its functionality that is not even being used in atom-supercollider

1. The user isn't informed that the package failed to activate, has to look in console 
2. There is no report in the Packages pane for atom-supercollider
3. Developer (moi) who uses apm link does not experience this particular issue

For 1 I think that the nice red pop up panel should have been activated and allow the user to report the issue.

For 2 I suggest marking the package as "failed to activate" in some way. But maybe handling 1 is enough.

For 3: As a developer I was unaware that this was happening. I'm using the package with apm link so it doesn't get processed in the same way.  I had to unlink and then install it to see the error.

I can separate these issues if you want.

Error posted below. 

Its depd (which ironically is a package for reporting deprecations) which is in express which is used by supercollider.js (my npm module). Express isn't used by my atom package, so I can factor that functionality into a separate npm module.

```
 Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
/Users/crucial/github/atom-supercollider/node_modules/supercolliderjs/node_modules/express/node_modules/depd/index.js:414 wrapfunction
/Applications/Atom.app/Contents/Resources/app/src/package.js:241 Failed to activate package named 'atom-supercollider' EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function.wrapfunction (/Users/crucial/github/atom-supercollider/node_modules/supercolliderjs/node_modules/express/node_modules/depd/index.js:414:5)
  at Object.<anonymous> (/Users/crucial/github/atom-supercollider/node_modules/supercolliderjs/node_modules/express/node_modules/send/index.js:156:47)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/crucial/github/atom-supercollider/node_modules/supercolliderjs/node_modules/express/lib/utils.js:16:12)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/crucial/github/atom-supercollider/node_modules/supercolliderjs/node_modules/express/lib/application.js:15:15)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/crucial/github/atom-supercollider/node_modules/supercolliderjs/node_modules/express/lib/express.js:7:13)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/crucial/github/atom-supercollider/node_modules/supercolliderjs/node_modules/express/index.js:2:18)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/crucial/github/atom-supercollider/node_modules/supercolliderjs/lib/nodejs/bridge.js:39:13)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/crucial/github/atom-supercollider/node_modules/supercolliderjs/index.js:6:18)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/crucial/github/atom-supercollider/lib/repl.coffee:6:19)
  at Object.<anonymous> (/Users/crucial/github/atom-supercollider/lib/repl.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:67:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/crucial/github/atom-supercollider/lib/controller.coffee:2:8)
  at Object.<anonymous> (/Users/crucial/github/atom-supercollider/lib/controller.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:67:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/crucial/github/atom-supercollider/lib/supercollider.coffee:1:14)
  at Object.<anonymous> (/Users/crucial/github/atom-supercollider/lib/supercollider.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:67:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:651:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:251:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:232:14)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:710:29
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:224:20)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:176:20)
```

**Comment by kevinsawicki** [comment]
> For 1 I think that the nice red pop up panel should have been activated and allow the user to report the issue.

Yeah, I think notifications for packages that fail to load/activate is the right first step here.

**Comment by Zireael07** [comment]
I am trying to figure out why the Lua linter isn't working, so notifications on failing to load/activate are a must.
