### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('highlight-selected background') contains HTML space characters, which are not valid in tokens.

### ISSUE THREAD

**Issue by ewhitebloom** [atom/atom#5747]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.183.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('highlight-selected background') contains HTML space characters, which are not valid in tokens.

```
At /Applications/Atom.app/Contents/Resources/app/src/highlights-component.js:63

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('highlight-selected background') contains HTML space characters, which are not valid in tokens.
  at Error (native)
  at HighlightsComponent.module.exports.HighlightsComponent.updateHighlightNode (/Applications/Atom.app/Contents/Resources/app/src/highlights-component.js:63:33)
  at HighlightsComponent.module.exports.HighlightsComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/highlights-component.js:47:28)
  at LinesComponent.module.exports.LinesComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/lines-component.js:118:32)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:213:27)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:283:28
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:159:9)
  at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:61

```

### Commands

```
     -3:03.6 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -3:03.0 pane:show-next-item (atom-text-editor.editor)
     -3:01.9 pane:show-previous-item (atom-text-editor.editor.is-focused)
  3x -3:01.3 pane:show-next-item (atom-text-editor.editor)
     -2:59.1 pane:show-previous-item (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "tags"
    ],
    "disabledPackages": [
      "rails-transporter",
      "term2",
      "term2",
      "term2",
      "vim-mode",
      "atom-ctags"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "fontSize": 13,
    "showIndentGuide": true,
    "autoIndent": false,
    "preferredLineLength": 120,
    "invisibles": {},
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autocomplete-paths, v1.0.2
autocomplete-plus, v2.2.0
color-picker, v1.4.4
command-logger, v0.22.0
file-icons, v1.4.11
git-tab-status, v1.5.3
highlight-selected, v0.9.0
language-emblem, v0.1.0
language-haml, v0.15.0
linter, v0.11.1
linter-clang, v2.25.1
linter-coffeelint, v0.1.7
linter-csslint, v0.0.11
linter-erb, v0.1.0
linter-javac, v0.1.3
linter-jshint, v0.1.0
linter-ruby, v0.1.4
linter-scss-lint, v0.0.14
monokai, v0.12.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@nathansobo Is this a problem in the `highlight-selected` package? Seeing it for the first time in 0.183, so just want to double-check.

**Comment by benogle** [comment]
Yes. They are probably passing in `'highlight-selected background'` as a className for some decoration, which is not allowed by `element.classList.add`. We could check for this, though, and throw a warning?

**Comment by nathansobo** [comment]
We should probably just support it by breaking the class on spaces.
