### ISSUE TITLE
Lots of specs fail

### ISSUE THREAD

**Issue by gnzlbg** [atom/atom#5763]
I just updated atom because i wanted to make sure i reported an issue correctly to a third party package. 

I decided to run the specs to check that i didn't screwed anything up in my system and to my surprise some core specs fail (10-20), and most of bundled packages spec fail. 

Is this normal or there is definitely an issue with my system? (It is MacOS Yosemite). 

I feel I cannot report an issue correctly to a third party package since it seems that my atom installation is completely screwed up. If the third party package builds on any of the bundled or core packages, it is completely normal that it doesn't work correctly in my system.

**Comment by izuzak** [comment]
Can you share how exactly you're running specs and what output you're getting?

**Comment by izuzak** [comment]
For what it's worth, I just tried running the specs and got one failure:

```
$ apm test
[19159:0226/133100:WARNING:dns_config_service_posix.cc(151)] dns_config has unhandled options!
2015-02-26 13:31:00.251 Atom[19159:1874948] Could not get code signature for running application, application updates are disabled: Error Domain=NSOSStatusErrorDomain Code=-67062 "The operation couldn’t be completed. (OSStatus error -67062.)"
[19161:0226/133100:INFO:renderer_main.cc(211)] Renderer process started
[19159:0226/133109:INFO:CONSOLE(57)] "Window load time: 8783ms", source: file:///Users/izuzak/github/atom/static/index.js (57)
...................[19159:0226/133110:INFO:CONSOLE(104)] "Uncaught BufferedProcessError: Failed to spawn command `bad-command-nope`. Make sure `bad-command-nope` is installed and on your PATH", source: /Users/izuzak/github/atom/src/buffered-process.coffee (104)
............................................................................[19159:0226/133112:INFO:CONSOLE(988)] "Error setting item in object: Validation failed at null.foo.int, null cannot be coerced into an int", source: /Users/izuzak/github/atom/src/config.coffee (988)
[19159:0226/133112:INFO:CONSOLE(988)] "Error setting item in object: Validation failed at foo.int, null cannot be coerced into an int", source: /Users/izuzak/github/atom/src/config.coffee (988)
......[19159:0226/133112:INFO:CONSOLE(680)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
[19159:0226/133112:INFO:CONSOLE(680)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
.[19159:0226/133112:INFO:CONSOLE(680)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
[19159:0226/133112:INFO:CONSOLE(680)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
.[19159:0226/133112:INFO:CONSOLE(680)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
[19159:0226/133112:INFO:CONSOLE(680)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
[19159:0226/133112:INFO:CONSOLE(680)] "'foo.bar' could not set the default. Attempted default: undefined; Schema: {"type":"array","default":"def","items":{"type":"string"}}", source: /Users/izuzak/github/atom/src/config.coffee (680)
[19159:0226/133112:INFO:CONSOLE(988)] "Error setting item in object: Validation failed at null.foo.bar, "baz" must be an array", source: /Users/izuzak/github/atom/src/config.coffee (988)
.[19159:0226/133112:INFO:CONSOLE(680)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
[19159:0226/133112:INFO:CONSOLE(680)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
.[19159:0226/133112:INFO:CONSOLE(680)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
[19159:0226/133112:INFO:CONSOLE(680)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
.[19159:0226/133112:INFO:CONSOLE(680)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
[19159:0226/133112:INFO:CONSOLE(680)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
.[19159:0226/133112:INFO:CONSOLE(680)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
[19159:0226/133112:INFO:CONSOLE(680)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
.[19159:0226/133112:INFO:CONSOLE(680)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
[19159:0226/133112:INFO:CONSOLE(680)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
.[19159:0226/133112:INFO:CONSOLE(680)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
[19159:0226/133112:INFO:CONSOLE(680)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
.[19159:0226/133112:INFO:CONSOLE(680)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
[19159:0226/133112:INFO:CONSOLE(680)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Users/izuzak/github/atom/src/config.coffee (680)
.............[19159:0226/133113:INFO:CONSOLE(988)] "Error setting item in object: Validation failed at null.foo.bar.int, null cannot be coerced into an int", source: /Users/izuzak/github/atom/src/config.coffee (988)
[19159:0226/133113:INFO:CONSOLE(988)] "Error setting item in object: Validation failed at null.foo.bar.int, null cannot be coerced into an int", source: /Users/izuzak/github/atom/src/config.coffee (988)
.................[19159:0226/133113:INFO:CONSOLE(988)] "Error setting item in object: Validation failed at foo.bar.anInt, null cannot be coerced into an int", source: /Users/izuzak/github/atom/src/config.coffee (988)
.........[19159:0226/133113:INFO:CONSOLE(1012)] "Error setting item in array: Validation failed at foo.bar.arr, "five" is not one of ["one","two","three"]", source: /Users/izuzak/github/atom/src/config.coffee (1012)
.....................................................................................................................................................................................................................[19159:0226/133122:INFO:CONSOLE(194)] "Failed to load package named 'package-with-invalid-styles'", source: /Users/izuzak/github/atom/src/package.coffee (194)
............................................F.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................[19159:0226/133213:INFO:CONSOLE(27)] "Uncaught TypeError: undefined is not a function", source: /Users/izuzak/github/atom/node_modules/event-kit/lib/composite-disposable.js (27)
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................[19159:0226/133232:INFO:CONSOLE(648)] "Failed to require the main module of 'package-with-incompatible-native-module' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve.", source: /Users/izuzak/github/atom/src/package.coffee (648)
[19159:0226/133232:INFO:CONSOLE(194)] "Failed to load package named 'package-with-invalid-styles'", source: /Users/izuzak/github/atom/src/package.coffee (194)
[19159:0226/133233:INFO:CONSOLE(194)] "Failed to load package named 'package-with-stylesheets-manifest'", source: /Users/izuzak/github/atom/src/package.coffee (194)
..[19159:0226/133233:INFO:CONSOLE(1012)] "Error setting item in array: Validation failed at core.themes, null must be a string", source: /Users/izuzak/github/atom/src/config.coffee (1012)
[19159:0226/133233:INFO:CONSOLE(1012)] "Error setting item in array: Validation failed at core.themes, undefined must be a string", source: /Users/izuzak/github/atom/src/config.coffee (1012)
[19159:0226/133233:INFO:CONSOLE(1012)] "Error setting item in array: Validation failed at core.themes, false must be a string", source: /Users/izuzak/github/atom/src/config.coffee (1012)
[19159:0226/133233:INFO:CONSOLE(1012)] "Error setting item in array: Validation failed at core.themes, 4 must be a string", source: /Users/izuzak/github/atom/src/config.coffee (1012)
[19159:0226/133233:INFO:CONSOLE(1012)] "Error setting item in array: Validation failed at core.themes, {} must be a string", source: /Users/izuzak/github/atom/src/config.coffee (1012)
[19159:0226/133233:INFO:CONSOLE(1012)] "Error setting item in array: Validation failed at core.themes, [] must be a string", source: /Users/izuzak/github/atom/src/config.coffee (1012)
...[19159:0226/133233:INFO:CONSOLE(225)] "Enabled theme 'definitely-not-a-theme' is not installed.", source: /Users/izuzak/github/atom/src/theme-manager.coffee (225)
..............[19159:0226/133236:INFO:CONSOLE(225)] "Enabled theme 'installed-dark-ui' is not installed.", source: /Users/izuzak/github/atom/src/theme-manager.coffee (225)
[19159:0226/133236:INFO:CONSOLE(225)] "Enabled theme 'installed-dark-syntax' is not installed.", source: /Users/izuzak/github/atom/src/theme-manager.coffee (225)
.[19159:0226/133236:INFO:CONSOLE(225)] "Enabled theme 'installed-dark-ui' is not installed.", source: /Users/izuzak/github/atom/src/theme-manager.coffee (225)
.[19159:0226/133237:INFO:CONSOLE(225)] "Enabled theme 'installed-dark-syntax' is not installed.", source: /Users/izuzak/github/atom/src/theme-manager.coffee (225)
......................................................................................................................................................................

PackageManager
  ::activate()
    it calls callbacks registered with ::onDidActivateInitialPackages
      Error: Leaking subscriptions for paths: /Users/izuzak/.atom/styles.less
        at ensureNoPathSubscriptions (/Users/izuzak/github/atom/spec/spec-helper.coffee:174:15)
        at [object Object].<anonymous> (/Users/izuzak/github/atom/spec/spec-helper.coffee:166:3)


Finished in 120.774 seconds
1558 tests, 5404 assertions, 1 failure, 0 skipped
```

**Comment by gnzlbg** [comment]
In atom, under Yosemite, I go to view -> developer -> run atom specs.

It's 2000s and still going, but I'll reply when it finished with all the
errors. It is going to be a long reply, i'll have to put that in a gist.

**Comment by gnzlbg** [comment]
Still running... the spec suite window is very slow due to the list of issues being really large.
If this is not the common case under Yosemite I might just need to reinstall or something.

![screen shot 2015-02-26 at 17 16 48](https://cloud.githubusercontent.com/assets/904614/6395868/506451d4-bddb-11e4-8a9a-b402db6161f1.png)

**Comment by izuzak** [comment]
@gnzlbg Sorry for not getting back to you on this. Not really sure what might be up with that -- do you see the same output when you run `apm test`? Can you post a few failures from the core specs?

@kevinsawicki Do you have any ideas what might be the problem here? Also, I'm constantly seeing [one spec failing locally when I run `apm test`](https://github.com/atom/atom/issues/5763#issuecomment-76181863) -- any thoughts how to fix that one? :thought_balloon:

**Comment by lee-dohm** [comment]
I just ran both `apm test` and `View > Developer > Run Package Specs` from my Atom source directory. `apm test` resulted in one failure, the same one that @izuzak mentioned. Run Package Specs resulted in four failures:

![screen shot 2015-03-24 at 12 18 46 pm](https://cloud.githubusercontent.com/assets/1038121/6810718/ff24c4bc-d21f-11e4-9ff5-4ec2bd874418.png)

Run Atom Specs results in a blank spec screen and nothing executes.

**Comment by gnzlbg** [comment]
> Not really sure what might be up with that -- do you see the same output when you run apm test? Can you post a few failures from the core specs?

@izuzak when I run `apm test` on the console (MacOS Yosemite) I get:

```bash
apm test
[68360:0325/125402:INFO:renderer_main.cc(211)] Renderer process started


Finished in 0 seconds
0 tests, 0 assertions, 0 failures, 0 skipped

Tests passed
```

**Comment by thomasjo** [comment]
`apm test` needs to be executed from the root of the package directory, or in the case of Atom the root of the cloned git repository; e.g. 

``` bash
$ cd ~/github/atom
$ apm test
```

**Comment by gnzlbg** [comment]
I didn't clone anything. I just downloaded the atom binary from the site. Does that mean that I cannot run the tests?

**Comment by thomasjo** [comment]
Assuming you installed to the default Applications folder;

``` bash
$ cd /Applications/Atom.app/Contents/Resources/app
$ apm test
```

There's little benefit in running these tests if you aren't developing on Atom, but they are shipped so you can certainly run them.

**Comment by gnzlbg** [comment]
Thanks, I ran that and get the following output:

```bash
apm test
[78673:0325/172620:INFO:renderer_main.cc(211)] Renderer process started
[78671:0325/172627:INFO:CONSOLE(56)] "Window load time: 6463ms", source: file:///Applications/Atom.app/Contents/Resources/app/static/index.js (56)
.......................[78671:0325/172629:INFO:CONSOLE(104)] "Uncaught BufferedProcessError: Failed to spawn command `bad-command-nope`. Make sure `bad-command-nope` is installed and on your PATH", source: /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js (104)
.............................................................................[78671:0325/172630:INFO:CONSOLE(977)] "Error setting item in object: Validation failed at null.foo.int, null cannot be coerced into an int", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (977)
[78671:0325/172630:INFO:CONSOLE(977)] "Error setting item in object: Validation failed at foo.int, null cannot be coerced into an int", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (977)
......[78671:0325/172630:INFO:CONSOLE(669)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
[78671:0325/172630:INFO:CONSOLE(669)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
.[78671:0325/172630:INFO:CONSOLE(669)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
[78671:0325/172630:INFO:CONSOLE(669)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
.[78671:0325/172630:INFO:CONSOLE(669)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
[78671:0325/172630:INFO:CONSOLE(669)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
[78671:0325/172630:INFO:CONSOLE(669)] "'foo.bar' could not set the default. Attempted default: undefined; Schema: {"type":"array","default":"def","items":{"type":"string"}}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
[78671:0325/172630:INFO:CONSOLE(977)] "Error setting item in object: Validation failed at null.foo.bar, "baz" must be an array", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (977)
.[78671:0325/172630:INFO:CONSOLE(669)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
[78671:0325/172630:INFO:CONSOLE(669)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
.[78671:0325/172630:INFO:CONSOLE(669)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
[78671:0325/172630:INFO:CONSOLE(669)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
.[78671:0325/172630:INFO:CONSOLE(669)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
[78671:0325/172630:INFO:CONSOLE(669)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
.[78671:0325/172630:INFO:CONSOLE(669)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
[78671:0325/172630:INFO:CONSOLE(669)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
.[78671:0325/172630:INFO:CONSOLE(669)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
[78671:0325/172630:INFO:CONSOLE(669)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
.[78671:0325/172630:INFO:CONSOLE(669)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
[78671:0325/172630:INFO:CONSOLE(669)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
.[78671:0325/172630:INFO:CONSOLE(669)] "'foo.baz' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
[78671:0325/172630:INFO:CONSOLE(669)] "'foo.scoped' could not set the default. Attempted default: undefined; Schema: {"type":"boolean"}", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (669)
.............[78671:0325/172631:INFO:CONSOLE(977)] "Error setting item in object: Validation failed at null.foo.bar.int, null cannot be coerced into an int", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (977)
[78671:0325/172631:INFO:CONSOLE(977)] "Error setting item in object: Validation failed at null.foo.bar.int, null cannot be coerced into an int", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (977)
.................[78671:0325/172631:INFO:CONSOLE(977)] "Error setting item in object: Validation failed at foo.bar.anInt, null cannot be coerced into an int", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (977)
.........[78671:0325/172631:INFO:CONSOLE(1001)] "Error setting item in array: Validation failed at foo.bar.arr, "five" is not one of ["one","two","three"]", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (1001)
...........................................................................................................................................[78671:0325/172635:INFO:CONSOLE(0)] "Unhandled promise rejection", source: file:///Applications/Atom.app/Contents/Resources/app/static/index.html#%7B%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%2Fspec%2Fspec-bootstrap.coffee%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%22%2C%22exitWhenDone%22%3Atrue%2C%22isSpec%22%3Atrue%2C%22devMode%22%3Atrue%2C%22specDirectory%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%2Fspec%22%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.188.0%22%2C%22initialPaths%22%3A%5B%5D%7D (0)
FF...................................................................................................................................F................................................................................................................................................................................F..............[78671:0325/172650:INFO:CONSOLE(0)] "Unhandled promise rejection", source: file:///Applications/Atom.app/Contents/Resources/app/static/index.html#%7B%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%2Fspec%2Fspec-bootstrap.coffee%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%22%2C%22exitWhenDone%22%3Atrue%2C%22isSpec%22%3Atrue%2C%22devMode%22%3Atrue%2C%22specDirectory%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%2Fspec%22%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.188.0%22%2C%22initialPaths%22%3A%5B%5D%7D (0)
F.........F....................................................................................................................................................................................................................................................................................................[78671:0325/172728:INFO:CONSOLE(27)] "Uncaught TypeError: undefined is not a function", source: /Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/composite-disposable.js (27)
......................................................................................................................................................[78671:0325/172732:INFO:CONSOLE(94)] "Uncaught Error: ENOENT, open '/Applications/Atom.app/Contents/Resources/app/spec/fixtures/a'", source: events.js (94)
[78671:0325/172732:INFO:CONSOLE(94)] "Uncaught Error: ENOENT, open '/Applications/Atom.app/Contents/Resources/app/spec/fixtures/b'", source: events.js (94)
.[78671:0325/172732:INFO:CONSOLE(94)] "Uncaught Error: ENOENT, open '/Applications/Atom.app/Contents/Resources/app/spec/fixtures/a'", source: events.js (94)
[78671:0325/172732:INFO:CONSOLE(94)] "Uncaught Error: ENOENT, open '/Applications/Atom.app/Contents/Resources/app/spec/fixtures/test.js'", source: events.js (94)
..........................................................................................................................................................................................................................................................................................................................................................F...[78671:0325/172748:INFO:CONSOLE(672)] "Failed to require the main module of 'package-with-incompatible-native-module' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve.", source: /Applications/Atom.app/Contents/Resources/app/src/package.js (672)
...[78671:0325/172749:INFO:CONSOLE(1001)] "Error setting item in array: Validation failed at core.themes, null must be a string", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (1001)
[78671:0325/172749:INFO:CONSOLE(1001)] "Error setting item in array: Validation failed at core.themes, undefined must be a string", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (1001)
[78671:0325/172749:INFO:CONSOLE(1001)] "Error setting item in array: Validation failed at core.themes, false must be a string", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (1001)
[78671:0325/172749:INFO:CONSOLE(1001)] "Error setting item in array: Validation failed at core.themes, 4 must be a string", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (1001)
[78671:0325/172749:INFO:CONSOLE(1001)] "Error setting item in array: Validation failed at core.themes, {} must be a string", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (1001)
[78671:0325/172749:INFO:CONSOLE(1001)] "Error setting item in array: Validation failed at core.themes, [] must be a string", source: /Applications/Atom.app/Contents/Resources/app/src/config.js (1001)
.[78671:0325/172749:INFO:CONSOLE(225)] "Enabled theme 'definitely-not-a-theme' is not installed.", source: /Applications/Atom.app/Contents/Resources/app/src/theme-manager.js (225)
................[78671:0325/172757:INFO:CONSOLE(225)] "Enabled theme 'installed-dark-ui' is not installed.", source: /Applications/Atom.app/Contents/Resources/app/src/theme-manager.js (225)
[78671:0325/172757:INFO:CONSOLE(225)] "Enabled theme 'installed-dark-syntax' is not installed.", source: /Applications/Atom.app/Contents/Resources/app/src/theme-manager.js (225)
[78671:0325/172757:INFO:CONSOLE(225)] "Enabled theme 'installed-dark-ui' is not installed.", source: /Applications/Atom.app/Contents/Resources/app/src/theme-manager.js (225)
.[78671:0325/172758:INFO:CONSOLE(225)] "Enabled theme 'installed-dark-syntax' is not installed.", source: /Applications/Atom.app/Contents/Resources/app/src/theme-manager.js (225)
.......................................................................................................................................................................

GitRepositoryProvider
  .repositoryForDirectory(directory)
    when specified a Directory with a Git repository
      it returns a Promise that resolves to a GitRepository
        Expected null to be instance of GitRepository class
          Error: Expected null to be instance of GitRepository class
          at /Applications/Atom.app/Contents/Resources/app/spec/git-repository-provider-spec.coffee:16:28
        Expected promise to be resolved, but it was rejected with {  }
      it returns the same GitRepository for different Directory objects in the same repo
        Expected null to be instance of GitRepository class (spec/git-repository-provider-spec.coffee:35:29)
PackageManager
  ::activate()
    it calls callbacks registered with ::onDidActivateInitialPackages
      Error: Leaking subscriptions for paths: /Users/gnzlbg/.atom/styles.less
        at ensureNoPathSubscriptions (/Applications/Atom.app/Contents/Resources/app/spec/spec-helper.coffee:174:15)
        at [object Object].<anonymous> (/Applications/Atom.app/Contents/Resources/app/spec/spec-helper.coffee:166:3)
Project
  constructor
    it does not update @repositories if every path has a Repository
      Expected null to be truthy. (spec/project-spec.coffee:116:26)
      Expected [ { destroy : Function } ] to be [ null ]. (spec/project-spec.coffee:126:46)
  .repositoryForDirectory(directory)
    it resolves to a GitRepository and is cached when the given directory is a Git repo
      Expected null to be instance of GitRepository class
        Error: Expected null to be instance of GitRepository class
        at /Applications/Atom.app/Contents/Resources/app/spec/project-spec.coffee:329:26
      Expected promise to be resolved, but it was rejected with {  }
  .removePath(path)
    it doesn't destroy the repository if it is shared by another root directory
      TypeError: Cannot read property 'isSubmodule' of null (spec/project-spec.coffee:437:47)
TextEditor
  .checkoutHeadRevision()
    it reverts to the version of its file checked into the project repository
      Expected '---' to be 'var quicksort = function () {'.
        at [object Object].<anonymous> (/Applications/Atom.app/Contents/Resources/app/spec/text-editor-spec.coffee:4162:48)
        at runMicrotasksCallback (node.js:348:7)
        at process._tickCallback (node.js:366:11)


Finished in 151.539 seconds
1610 tests, 5519 assertions, 10 failures, 0 skipped

Tests failed
```

**Comment by kevinsawicki** [comment]
Closing this out since the specs are no longer shipped with Atom and now require cloning the repository locally which should resolve the issues being experienced.

**Comment by izuzak** [comment]
@kevinsawicki I have a local clone checked out (latest master version), and running `apm test` from the root directory still causes one spec to fail. 

```
PackageManager
  ::activate()
    it calls callbacks registered with ::onDidActivateInitialPackages
      Error: Leaking subscriptions for paths: /Users/izuzak/.atom/styles.less
        at ensureNoPathSubscriptions (/Users/izuzak/github/atom/spec/spec-helper.coffee:194:15)
        at [object Object].<anonymous> (/Users/izuzak/github/atom/spec/spec-helper.coffee:187:3)


Finished in 200.43 seconds
1781 tests, 6412 assertions, 1 failure, 0 skipped
```

:confused:

**Comment by kevinsawicki** [comment]
> I have a local clone checked out (latest master version), and running apm test from the root directory still causes one spec to fail.

Yeah, that is a known issue with having a local `~/.atom/styles.less` file when running the specs.

**Comment by izuzak** [comment]
> Yeah, that is a known issue with having a local ~/.atom/styles.less file when running the specs.

Ahhh, thank you @kevinsawicki! :zap: Do we have a tracking issue for that problem (I don't remember seeing it, but totally possible I missed it)? Happy to create one if we don't and it's something we'd like to improve in the future.

**Comment by kevinsawicki** [comment]
> Do we have a tracking issue for that problem (I don't remember seeing it, but totally possible I missed it)?

I couldn't find one either, a focused issue for it sounds good, thanks.

**Comment by gnzlbg** [comment]
@kevinsawicki thanks!
