### ISSUE TITLE
v.183 will not find update for .184

### ISSUE THREAD

**Issue by GradyD** [atom/atom#5772]
I updated to .183 yesterday am having issue #5747 but no matter what I do to update it says no update found. 

I downloaded the new EXE and tried to install it (over current version which was not running) and it errors,
```
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\gduncan\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\gduncan\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\gduncan\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\gduncan\AppData\Local\atom\app-0.169.0
ApplyReleasesImpl: runPostInstallAndCleanup: starting fixPinnedExecutables
ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\gduncan\AppData\Local\atom\app-0.169.0\atom.exe]
ApplyReleasesImpl: cleanDeadVersions: for version 0.169.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.169.0
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\gduncan\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\gduncan\AppData\Local\SquirrelTemp
ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\gduncan\AppData\Local\atom\app-0.184.0
ApplyReleasesImpl: Writing files to app directory: C:\Users\gduncan\AppData\Local\atom\app-0.184.0
IEnableLogger: Failed to update local releases file: System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Squirrel.ReleaseEntry.BuildReleasesFile(String releasePackagesDir)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>b__ed()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>d__ee.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4b`1.MoveNext()
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\gduncan\AppData\Local\SquirrelTemp
IEnableLogger: Failed to copy Update.exe to C:\Users\gduncan\AppData\Local\atom\Update.exe: System.IO.IOException: The process cannot access the file 'C:\Users\gduncan\AppData\Local\atom\Update.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass2e.<Install>b__27()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
```

Is there anyway I can update without uninstalling? If I uninstall will I lose all my settings and installed plugins?

**Comment by paulcbetts** [comment]
Hey @GradyD, easiest thing to do is just uninstall and reinstall, it's super fast and painless.

>  If I uninstall will I lose all my settings and installed plugins?

Nope, they'll be intact

**Comment by GradyD** [comment]
Sweet! That did it, thanks!

**Comment by batjko** [comment]
Happens quite often though that the updater just doesn't recognize the newer version.
Mine is still on v182 right now and each time I click on "Check For Updates", it takes 10 minutes (I kid you not) before it finally returns with the message that - according to it apparently extensive search - v182 is the latest version.

**Comment by paulcbetts** [comment]
@batjko Can you have a look at the SquirrelSetup.log? I suspect that we're finding a new version, attempting to install it, then something is going pear-shaped.

**Comment by yesmar** [comment]
I got the same issue with 0.179 indicating it was the latest, even though 0.184 had been released. Attempting to install 0.184 over 0.179 resulted in the same error that @GradyD reported, above. I then tried to reinstall after first uninstalling and got the same error message again. Then I manually removed AppData\Local\atom and AppData\Roaming\Atom and tried a fresh install, and got a similar error (except this time there were no 'dead versions' to deal with)…

```
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\Ramsey\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Ramsey\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\Ramsey\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\Ramsey\AppData\Local\atom\app-0.184.0
IEnableLogger: Failed to update local releases file: System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Squirrel.ReleaseEntry.BuildReleasesFile(String releasePackagesDir)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>b__ed()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>d__ee.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4b`1.MoveNext()
```
This is a pretty crummy user experience. Is anyone testing these releases before they go out the door?

**Comment by paulcbetts** [comment]
@yesmar Fuck if I know, I just write the installer. Do you have Antivirus installed?

**Comment by yesmar** [comment]
It's a standard Windows 8.1 install with Defender running. But I don't see any popups from Defender complaining about anything.

**Comment by batjko** [comment]
@paulcbetts Looks like you're right. There must have been a previously failed update, which prevented any new one:



Program: Starting update, downloading from https://atom.io/api/updates
CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
FileDownloader: Downloading url: 
FileDownloader: Downloading file: 
FileDownloader: Downloading file: 
Program: Failed to apply updates, falling back to full updates: System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Squirrel.DeltaPackageBuilder.applyDiffToFile(String deltaPath, String relativeFilePath, String workingDirectory)
   at Squirrel.DeltaPackageBuilder.<>c__DisplayClass1b.<ApplyDeltaPackage>b__c(String file)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass9d.<createFullPackagesFromDeltas>b__99()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__9f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__5c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__41.MoveNext()
CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
FileDownloader: Downloading url: 
FileDownloader: Downloading file: 
ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\free\AppData\Local\atom\app-0.184.0
ApplyReleasesImpl: Writing files to app directory: C:\Users\free\AppData\Local\atom\app-0.184.0
IEnableLogger: Failed to update local releases file: System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Squirrel.ReleaseEntry.BuildReleasesFile(String releasePackagesDir)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>b__ed()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>d__ee.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4b`1.MoveNext()
Program: Really couldn't apply updates!: System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Squirrel.ReleaseEntry.BuildReleasesFile(String releasePackagesDir)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>b__ed()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>d__ee.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4b`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__5c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__41.MoveNext()
Program: Starting Squirrel Updater: --download https://atom.io/api/updates
Program: Fetching update information, downloading from https://atom.io/api/updates
CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
FileDownloader: Downloading url: 
FileDownloader: Downloading file: 
FileDownloader: Downloading file: 
UpdateInfo: Couldn't get release notes for:atom-0.183.0-delta.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\free\AppData\Local\atom\..\atom\packages\atom-0.183.0-delta.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__2(ReleaseEntry x)
UpdateInfo: Couldn't get release notes for:atom-0.184.0-delta.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\free\AppData\Local\atom\..\atom\packages\atom-0.184.0-delta.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__2(ReleaseEntry x)

**Comment by paulcbetts** [comment]
^^ another example where System.IO.Path.InternalGetTempFileName fails :-/

**Comment by paulcbetts** [comment]
@batjko Clear your temp directory (`C:\Users\free\AppData\Local\temp`)

**Comment by batjko** [comment]
Yea that did the trick. 
Cheers.
