### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getScreenPosition' of undefined

### ISSUE THREAD

**Issue by benogle** [atom/atom#5776]
Consistent repro steps in safe mode:

1. create empty coffee spec file
1. type `req` then tab
1. type some things. I typed `grim`
1. hit `esc` to clear the multiple cursors
1. move to end of line
1. make some new lines
1. type `be` then tab
1. :boom: 

This has bracket matcher in the trace, but I'm not sure who the originator is. 

See https://github.com/atom/bracket-matcher/issues/88

**Atom Version**: 0.185.0-30e3813
**System**: Mac OS X 10.9.5
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.71.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getScreenPosition' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1393

TypeError: Cannot read property 'getScreenPosition' of undefined
    at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1393:34)
    at TextEditor.module.exports.TextEditor.isFoldedAtCursorRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2652:44)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:111:23)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:94:26
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
    at /Applications/Atom.app/Contents/Resources/app/src/cursor.js:70:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
    at Marker.module.exports.Marker.destroyed (/Applications/Atom.app/Contents/Resources/app/src/marker.js:264:20)
    at /Applications/Atom.app/Contents/Resources/app/src/marker.js:51:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
```

### Commands

```
     -0:17.1 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:17.1 snippets:expand (atom-text-editor.editor.is-focused)
     -0:13.9 editor:move-to-next-word-boundary (atom-text-editor.editor.is-focused)
     -0:13.4 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:12.9 editor:newline (atom-text-editor.editor.is-focused)
     -0:10.3 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:10.3 snippets:expand (atom-text-editor.editor.is-focused)
  5x -0:08.6 core:select-up (atom-text-editor.editor.is-focused)
  2x -0:07.7 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.8 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:05.8 snippets:expand (atom-text-editor.editor.is-focused)
     -0:03.3 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.8 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:02.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:01.6 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.4 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autosave",
      "color-picker",
      "css-color-highlighting",
      "font-viewer",
      "atom-css-comb",
      "live-archive",
      "atomatigit",
      "minimap",
      "autocomplete"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
welcome, v0.23.0

# Dev
metrics, v0.45.0
notifications, v0.30.0
snippets, v0.76.0
welcome, v0.23.0
```

**Comment by benogle** [comment]
Cursor merging changed recently. I wonder if it's related to that. Hitting `esc` and merging the cursors is the key to making this happen. 

If I move to the end of the line and merge the cursors, everything is fine.

cc @nathansobo

**Comment by kevinsawicki** [comment]
I reproduced it using your steps

**Comment by nathansobo** [comment]
Will look at this tomorrow.

**Comment by nathansobo** [comment]
This seems to be a bug in the snippets package.

**Comment by nathansobo** [comment]
This is because the snippets package is only listening to move events on a single cursor, but that cursor ends up getting destroyed and replaced by a new one when the selection is cleared, so snippets doesn't realize that you've moved outside of the last snippet expansion.

**Comment by benogle** [comment]
This issue was moved to atom/snippets#112
