### ISSUE TITLE
Atom gets caught in loop, can't escape until force quit.

### ISSUE THREAD

**Issue by dval** [atom/atom#5801]
I cloned anchor-cms without creating a fork. So, I don't actually have permission to push to the repository. If I make a change to any of the files, I am prompted for a password. Entering my password, or canceling just causes another error, and another password prompt. I can't interact with any of the red error box's because the password prompt blocks the rest of the editor from responding.

If I just wait and do nothing long enough, I am given the option to close the editor.

![screen shot 2015-02-28 at 9 58 03 pm](https://cloud.githubusercontent.com/assets/1014630/6429281/bad777d8-bf95-11e4-95a0-e398f7d4b6b7.png)

**Comment by 50Wliu** [comment]
What version of Atom is this?  Can you reproduce this in safe mode (`atom --safe`)?  If not, could you please tell us what packages you have installed (`apm list --installed`)?  Thanks.

**Comment by dval** [comment]
I am using Atom 0.184.0. 
/Users/dylan/.atom/packages (1)
└── open-recent@2.2.0

I was having trouble reproducing the error. I have discovered it has nothing to do with the repository. It is related to file permissions. 
If I don't have write access to a file, then this error is reproducible in any project. 

In safe mode, there is a different behavior.
I am still prompted for a password. But, entering a password allows me to save changes. (Assuming it's because of elevated privileges)
I still can not cancel changes I have made.  I am continuously asked for a password and given another error.

Hope it helps some, 
For right now, a simple chmod a+w fixes the issue.

**Comment by dval** [comment]
Additionally, here is the error report (clicked on in safe-mode):   
I am posting it here, instead of opening another issue.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.184.0
**System**: Mac OS X 10.8.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EACCES, permission denied '/Users/dylan/Development/anchor/anchor-cms/anchor/routes/metadata.php'

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:320

Error: EACCES, permission denied '/Users/dylan/Development/anchor/anchor-cms/anchor/routes/metadata.php'
    at Error (native)
    at Object.fs.openSync (fs.js:503:18)
    at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
    at Object.fs.writeFileSync (fs.js:1116:15)
    at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:243:17)
    at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:239:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:309:21)
    at File.module.exports.File.write (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:298:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:970:17)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
```

### Commands

```
     -4:00.4 core:save (atom-text-editor.editor)
  2x -2:13.0 core:backspace (atom-text-editor.editor)
  2x -2:11.6 core:save (atom-text-editor.editor)
  2x -1:27.8 core:confirm (atom-text-editor.editor.mini)
     -0:07.5 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 14,
    "showIndentGuide": true,
    "tabLength": 4,
    "scrollPastEnd": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```
