### ISSUE TITLE
Cannot read property 'setProperties' of undefined

### ISSUE THREAD

**Issue by Trudko** [atom/atom#5802]
When I run atom (0.184) --safe from command line in my home folder under Ubuntu 14.04 my screen gets blank and I get an error:

TypeError: Cannot read property 'setProperties' of undefined
    at new TextEditor (/opt/atom/resources/app/src/text-editor.js:99:15)
    at Function.module.exports.Serializable.deserialize (/opt/atom/resources/app/node_modules/serializable/lib/serializable.js:72:22)
    at DeserializerManager.module.exports.DeserializerManager.deserialize (/opt/atom/resources/app/src/deserializer-manager.js:56:29)
    at /opt/atom/resources/app/src/pane.js:81:35
    at Array.map (native)
    at Pane.module.exports.Pane.deserializeParams (/opt/atom/resources/app/src/pane.js:80:36)
    at Function.module.exports.Serializable.deserialize (/opt/atom/resources/app/node_modules/serializable/lib/serializable.js:58:25)
    at DeserializerManager.module.exports.DeserializerManager.deserialize (/opt/atom/resources/app/src/deserializer-manager.js:56:29)
    at PaneContainer.module.exports.PaneContainer.deserializeParams (/opt/atom/resources/app/src/pane-container.js:71:40)
    at Function.module.exports.Serializable.deserialize (/opt/atom/resources/app/node_modules/serializable/lib/serializable.js:58:25)index.js:65 window.onload

**Comment by 50Wliu** [comment]
Kind of guessing here, but could you try renaming `~/.atom` to something like `~/.atom-backup` and try starting Atom and seeing if that works?

**Comment by Trudko** [comment]
@50Wliu that actually worked

**Comment by 50Wliu** [comment]
All right, then I'd suggest for you to take a look at your config files (`config.cson`, `init.coffee`, `keymap.cson`, `snippets.cson`, and `styles.less`).  Sounds like there's something invalid in at least one of those (someone more experienced at Coffeescript could probably tell you exactly which one).
