### ISSUE TITLE
Uncaught Error: ENOSPC, no space left on device

### ISSUE THREAD

**Issue by douglascliques** [atom/atom#5825]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOSPC, no space left on device

```
At C:\Users\Windows\AppData\Local\atom\app-0.182.0\resources\app\src\pane.js:782

Error: ENOSPC, no space left on device
    at Error (native)
    at Object.fs.writeSync (fs.js:616:20)
    at Object.fs.writeFileSync (fs.js:1125:21)
    at Object.fsPlus.writeFileSync (C:\Users\Windows\AppData\Local\atom\app-0.182.0\resources\app\node_modules\fs-plus\lib\fs-plus.js:243:17)
    at File.module.exports.File.writeFileSync (C:\Users\Windows\AppData\Local\atom\app-0.182.0\resources\app\node_modules\pathwatcher\lib\file.js:239:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (C:\Users\Windows\AppData\Local\atom\app-0.182.0\resources\app\node_modules\pathwatcher\lib\file.js:309:21)
    at File.module.exports.File.write (C:\Users\Windows\AppData\Local\atom\app-0.182.0\resources\app\node_modules\pathwatcher\lib\file.js:298:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Windows\AppData\Local\atom\app-0.182.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:970:17)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\Windows\AppData\Local\atom\app-0.182.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:958:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\Windows\AppData\Local\atom\app-0.182.0\resources\app\src\text-editor.js:620:26)
```

### Commands

```
     -0:15.2 core:paste (atom-text-editor.editor.is-focused)
     -0:14.5 core:undo (atom-text-editor.editor.is-focused)
     -0:13.8 core:paste (atom-text-editor.editor.is-focused)
  8x -0:12.5 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-light-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 6,
    "showIndentGuide": true,
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by benogle** [comment]
@50Wliu I think you were right to add the `error-from-save` label
