### ISSUE TITLE
Uncaught TypeError: Cannot read property 'measureLineHeightAndDefaultCharWidth' of undefined

### ISSUE THREAD

**Issue by crisu83** [atom/atom#5836]
Tried to open an empty npm-debug.log when the error occurred.

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'measureLineHeightAndDefaultCharWidth' of undefined

```
At /Users/Chris/Downloads/Atom.app/Contents/Resources/app/src/text-editor-component.js:836

TypeError: Cannot read property 'measureLineHeightAndDefaultCharWidth' of undefined
    at module.exports.React.createClass.measureLineHeightAndDefaultCharWidth (/Users/Chris/Downloads/Atom.app/Contents/Resources/app/src/text-editor-component.js:836:31)
    at boundMethod [as measureLineHeightAndDefaultCharWidth] (/Users/Chris/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
    at module.exports.React.createClass.sampleFontStyling (/Users/Chris/Downloads/Atom.app/Contents/Resources/app/src/text-editor-component.js:817:14)
    at boundMethod [as sampleFontStyling] (/Users/Chris/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
    at module.exports.React.createClass.becameVisible (/Users/Chris/Downloads/Atom.app/Contents/Resources/app/src/text-editor-component.js:211:12)
    at boundMethod [as becameVisible] (/Users/Chris/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
    at module.exports.React.createClass.checkForVisibilityChange (/Users/Chris/Downloads/Atom.app/Contents/Resources/app/src/text-editor-component.js:765:16)
    at boundMethod [as checkForVisibilityChange] (/Users/Chris/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
    at module.exports.React.createClass.pollDOM (/Users/Chris/Downloads/Atom.app/Contents/Resources/app/src/text-editor-component.js:754:17)
    at boundMethod (/Users/Chris/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
```

### Commands

```
     -4:58.9 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-jinja2, v0.5.0
emmet, v2.3.3
language-docker, v1.1.2
monokai, v0.12.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
React hasn't been used since #5293 so this issue can be closed.
