### ISSUE TITLE
Building atom with io.js fails

### ISSUE THREAD

**Issue by Cangit** [atom/atom#5838]
I have been building atom myself since support for io.js was introduced, but it recently started to fail.

OSX 10.10.3

```
Node: v1.4.3
npm: v2.5.1
Installing build modules...
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/Users/fe/Sites/git/atom/build/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/fe/Sites/git/atom/build/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:403:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:293:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/Users/fe/Sites/git/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/fe/Sites/git/atom/build/node_modules/grunt-atom-shell-installer/node_modules/asar/node_modules/chromium-pickle
gyp ERR! node -v v1.4.3
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/fe/Sites/git/atom/build/node_modules/.bin/npm" "--userconfig=/Users/fe/Sites/git/atom/.npmrc" "install" "--loglevel" "error"
npm ERR! node v1.4.3
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! chromium-pickle@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by izuzak** [comment]
@Cangit Works for me on  OSX 10.10.2 with io.js 1.4.3. That error message you provided shows a 404, might have been a temporary thing? Can you try running `script/build` again (and perhaps `script/clean`)?

Here's my output:

```
$ script/clean
$ script/build
Node: v1.4.3
npm: v2.6.1
Installing build modules...
Installing apm...
Installing modules ✓
Installing atom-dark-syntax@0.26.0 ✓
Installing atom-dark-ui@0.47.0 ✓
...
Installing language-xml@0.28.0 ✓
Installing language-yaml@0.22.0 ✓
Deduping modules ✓
Running "download-atom-shell" task


Running "download-atom-shell-chromedriver" task


Running "build" task

Running "coffee:glob_to_multiple" (coffee) task
>> 375 files created.

Running "prebuild-less:src" (prebuild-less) task

Running "cson:glob_to_multiple" (cson) task
>> 176 files compiled to JSON.

Running "peg:glob_to_multiple" (peg) task

Running "generate-license:save" (generate-license) task

Running "generate-module-cache" task

Running "compile-packages-slug" task

Running "copy-info-plist" task

Running "set-version" task

Running "install" task
Done, without errors.
```

**Comment by Cangit** [comment]
Tried again, failed.

Did ```script/clean```, tried again and now it works. :+1: Thanks! Didn't think about doing this, sorry.

**Comment by izuzak** [comment]
No worries, thanks for the report and for letting us know. :+1:

**Comment by abbshr** [comment]
I built atom in Ubuntu 32bit 14.04 LTS, follow the guide and finally I got the similar error:

```
Node: v1.5.0
npm: v1.4.11
Installing build modules...
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:243:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:832:10)
gyp ERR! stack     at ClientRequest.g (events.js:257:16)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:403:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:293:20)
gyp ERR! System Linux 3.13.0-46-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ran/programs/atom/build/node_modules/runas
gyp ERR! node -v v1.5.0
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-46-generic
npm ERR! command "node" "/usr/local/bin/npm" "--userconfig=/home/ran/programs/atom/.npmrc" "install" "--loglevel" "error"
npm ERR! cwd /home/ran/programs/atom/build
npm ERR! node -v v1.5.0
npm ERR! npm -v 1.4.11
npm ERR! code ELIFECYCLE
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:243:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:832:10)
gyp ERR! stack     at ClientRequest.g (events.js:257:16)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:403:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:293:20)
gyp ERR! System Linux 3.13.0-46-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ran/programs/atom/build/node_modules/minidump
gyp ERR! node -v v1.5.0
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:243:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:832:10)
gyp ERR! stack     at ClientRequest.g (events.js:257:16)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:403:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:293:20)
gyp ERR! System Linux 3.13.0-46-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ran/programs/atom/build/node_modules/grunt-atom-shell-installer/node_modules/asar/node_modules/chromium-pickle
gyp ERR! node -v v1.5.0
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ran/programs/atom/build/npm-debug.log
npm ERR! not ok code 0
```

**Comment by vindicatorr** [comment]
Here is "more information", so please  reopen this issue:
Relating to 'gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"'

If I manually run:
.../atom$ "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node gyp.js" "rebuild"
<hr>
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@1.6.5 | linux | x64
gyp http GET http://nodejs.org/dist/v1.6.5/node-v1.6.5.tar.gz
gyp http 404 http://nodejs.org/dist/v1.6.5/node-v1.6.5.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1156:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:410:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:300:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/Desktop/atom
gyp ERR! node -v v1.6.5
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
<hr>
Note "http GET http://nodejs.org/dist/v1.6.5/node-v1.6.5.tar.gz"
IOJS is at 1.6.5 while NodeJS is using versions in the 0.# range, so there is no "dist/v1.#", thus 404.

**Comment by vindicatorr** [comment]
Negatory on my previous comment.
I had built npm from github and should have been using the built-in npm that iojs "./configure" defaults to.

Even then, I need to make sure I don't use iojs master branch, but rather checkout the latest tag that correlates with the latest dist path at "https://iojs.org/dist", else I may still get a 404 because the master branch may be a later version than what is available in dist.
eg. current iojs master branch from github version is 1.6.5, but iojs.org/dist subdirs only go up to 1.6.4.
