### ISSUE TITLE
Uncaught Error: spawn /usr/local/bin/atom ENOENT

### ISSUE THREAD

**Issue by venkatsanthanam** [atom/atom#5842]
[Enter steps to reproduce below:]

1. ...Set up a new project using mavens mate
2. ...

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /usr/local/bin/atom ENOENT

```
At events.js:94

Error: spawn /usr/local/bin/atom ENOENT
  at exports._errnoException (util.js:753:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:364:11)

```

### Commands

```
     -9:53.3 core:paste (iframe#iframe-fcf08cd0-c2c0-11e4-a6da-b927efd3dc8c.native-key-bindings)
     -9:51.3 core:copy (iframe#iframe-fcf08cd0-c2c0-11e4-a6da-b927efd3dc8c.native-key-bindings)
     -9:37.6 core:paste (iframe#iframe-fcf08cd0-c2c0-11e4-a6da-b927efd3dc8c.native-key-bindings)
     -6:45.5 mavensmate:edit-project (atom-text-editor.editor)
  2x -6:40.7 mavensmate:new-project (atom-text-editor.editor)
     -6:11.8 core:save (ul.list-inline.tab-bar.inset-panel)
  2x -6:09.2 core:save-as (ul.list-inline.tab-bar.inset-panel)
     -5:34.1 mavensmate:new-project (atom-text-editor.editor)
     -5:07.8 core:paste (iframe#iframe-ac1bfeb0-c2c1-11e4-a6da-b927efd3dc8c.native-key-bindings)
  2x -4:33.6 core:copy (iframe#iframe-ac1bfeb0-c2c1-11e4-a6da-b927efd3dc8c.native-key-bindings)
     -1:12.7 core:paste (atom-text-editor#MavensMate-Atom.mm_workspace.editor.mini)
  4x -1:02.4 core:save (atom-text-editor#MavensMate-Atom.mm_workspace.editor.mini)
     -0:54.5 mavensmate:new-project (atom-text-editor#MavensMate-Atom.mm_workspace.editor.mini)
     -0:26.6 core:paste (iframe#iframe-52bba270-c2c2-11e4-a6da-b927efd3dc8c.native-key-bindings)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.20
git-projects, v1.8.1

# Dev
No dev packages
```

**Comment by mh2292** [comment]
I can also reproduce this.

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/atom/notifications/pull/62
