### ISSUE TITLE
Atom v0.186.0 for Windows; No Bin Folder

### ISSUE THREAD

**Issue by LiquidFlame** [atom/atom#5869]
I just installed v0.186.0 of Atom and I noticed that it didn't install a Bin folder usually under "...\Users\...\AppData\Local\atom", instead I saw that the command line stuff was created under "...\Users\...\AppData\Local\atom\app-0.186.0\resources\cli".  I added the file location to my path under Environment Variables, and I can run Atom for the command line, but apm doesn't work.  Should there be a Bin folder created, and how can I get apm working?

Thanks.

**Comment by kevinsawicki** [comment]
> Should there be a Bin folder created

Yes there should be.

Is there anything in your `SquirrelLog.log` file in `AppData\Local\atom`?

**Comment by LiquidFlame** [comment]
Yes, quite a bit.  Unfortunately, I'm trying to install this at work, which I just got approved, but my company uses some heavy security.

>Program: Starting Squirrel Updater: --download https://atom.io/api/updates
Program: Fetching update information, downloading from https://atom.io/api/updates
CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES
IEnableLogger: Failed to download url: https://atom.io/api/updates/RELEASES: System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
FileDownloader: Downloading url: https://atom.io/api/updates/releases
IEnableLogger: Failed to download url: https://atom.io/api/updates/releases: System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
CheckForUpdateImpl: Download resulted in WebException (returning blank release list): System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES
IEnableLogger: Failed to download url: https://atom.io/api/updates/RELEASES: System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
FileDownloader: Downloading url: https://atom.io/api/updates/releases
IEnableLogger: Failed to download url: https://atom.io/api/updates/releases: System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
CheckForUpdateImpl: Download resulted in WebException (returning blank release list): System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES
IEnableLogger: Failed to download url: https://atom.io/api/updates/RELEASES: System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
FileDownloader: Downloading url: https://atom.io/api/updates/releases
IEnableLogger: Failed to download url: https://atom.io/api/updates/releases: System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
CheckForUpdateImpl: Download resulted in WebException (returning blank release list): System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES
IEnableLogger: Failed to download url: https://atom.io/api/updates/RELEASES: System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
FileDownloader: Downloading url: https://atom.io/api/updates/releases
IEnableLogger: Failed to download url: https://atom.io/api/updates/releases: System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
CheckForUpdateImpl: Download resulted in WebException (returning blank release list): System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()

**Comment by LiquidFlame** [comment]
Curiously enough, I just installed an older version (0.176.0) that we have access to, and that installed the bin folder, but I still got all the same errors as above in the  `SquirrelLog.log`

**Comment by paulcbetts** [comment]
@LiquidFlame This is telling you that Squirrel is trying to check for updates and is getting back 407 Proxy Authentication required

**Comment by LiquidFlame** [comment]
@paulcbetts To be honest, not sure.  I develop internal java web apps, so I don't do any C#, and got a feeling the apps we use are created in C#.  Are computers are pretty locked down from us, try to find a contact at work to see if I can get past this proxy issue, but probably won't have any luck, since they probably won't want us to do auto updates.  We have to download all of our Open-source software through OLEX.

**Comment by paulcbetts** [comment]
@LiquidFlame If you can get a certain version working, you can safely ignore the message (of course, auto-updates don't work)

**Comment by LiquidFlame** [comment]
Another question that I have is, I'm trying to install Linter manually, by unzipping the file into my `...\Users\...\.atom\packages`I'm guessing that doing the regular `apm install linter` installs the `font-awesome`  So my question is how do I install Linter manually from the zip?

**Comment by LiquidFlame** [comment]
@paulcbetts I know I can get v0.176.0 working, but it's a shame because I would like to have the latest build.  The only reason I'm looking at v0.176.0, is that was the last AtomSetup.exe we had access to.  I just don't get why the bin folder gets created correctly under v0.176.0 and not v0.186.0

**Comment by RoboPhred** [comment]
I believe I have the same problem.  After an auto update, I get the message:

"Failed to spawn command ~\AppData\Local\atom\app-0.186.0\resources\app\apm\bin\node. Make sure ~\AppData\Local\atom\app-0.186.0\resources\app\apm\bin\node is installed and on your PATH"

This has happened twice.  Once for a normal auto update, and the second time in an additional auto update after I had reinstalled to work around the problem.


The SquirrelSetup.log file shows no trouble in downloading the updates.  However, it has a somewhat contradictory error on installing:

System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully

```
Utility: Starting to delete folder: ~\AppData\Local\Temp\e\lib\net45\resources\app\node_modules\semver
Utility: Starting to delete folder: ~\AppData\Local\Temp\e\lib\net45\resources\app\node_modules\semver\bin
Program: Failed to apply updates, falling back to full updates: System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
   at DeltaCompressionDotNet.MsDelta.MsDeltaCompression.ApplyDelta(String deltaFilePath, String oldFilePath, String newFilePath)
   at Squirrel.DeltaPackageBuilder.applyDiffToFile(String deltaPath, String relativeFilePath, String workingDirectory)
   at Squirrel.DeltaPackageBuilder.<>c__DisplayClass1b.<ApplyDeltaPackage>b__c(String file)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass94.<createFullPackagesFromDeltas>b__90()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__96.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__5b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__3f.MoveNext()
CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
FileDownloader: Downloading url: 
FileDownloader: Downloading file: 
ApplyReleasesImpl: Writing files to app directory: ~\AppData\Local\atom\app-0.186.0
ApplyReleasesImpl: runPostInstallAndCleanup: starting fixPinnedExecutables
ApplyReleasesImpl: Processing shortcut ''
ApplyReleasesImpl: Does not match '~\AppData\Local\atom\app-0.175.0', continuing to next directory
ApplyReleasesImpl: Processing shortcut 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
ApplyReleasesImpl: Does not match '~\AppData\Local\atom\app-0.175.0', continuing to next directory
ApplyReleasesImpl: Processing shortcut 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe'
ApplyReleasesImpl: Does not match '~\AppData\Local\atom\app-0.175.0', continuing to next directory
ApplyReleasesImpl: Squirrel Enabled Apps: [~\AppData\Local\atom\app-0.186.0\atom.exe]
ApplyReleasesImpl: cleanDeadVersions: for version 0.186.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.175.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.186.0
Program: Starting Squirrel Updater: --download https://atom.io/api/updates
Program: Fetching update information, downloading from https://atom.io/api/updates
CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES
```

I am primarily a C# developer, and other C# applications work fine on the environment I am installing to.  This is also a work pc, so it is possible there are some security settings in play that I am not aware of.

**Comment by paulcbetts** [comment]
@LiquidFlame Honestly, the easiest thing to do is to get another machine with the same version of Atom but not under super lockdown, `apm install` everything, then copy over your entire `.atom` folder across

**Comment by LiquidFlame** [comment]
So good news, I found this post [Atom installation error on Windows 8.1] (https://discuss.atom.io/t/atom-installation-error-on-windows-8-1/15050) and even though I'm running Windows 7, I tired clearing everything in my `%LOCALAPPDATA%\Temp` and deleting the `Path` under the `Environment Variables -> User variables`  and it worked.  I know have my bin file.

@paulcbetts Unfortunately that's not an option.  I going to try and work with our workstation team, but more than likely I will not be able to use Atom at our company.  The main reason is trying to install these packages manually is going to be more of a PITA, because I'll have to open up a ticket for every dependency that a package needs.  My fingers are crossed, but I'm guessing workstation and security are not going to give me an exception.

**Comment by kevinsawicki** [comment]
Looks like this can be closed out based on the last comment, thanks for the details.
