### ISSUE TITLE
Uncaught Error: No line exists for row 6. Last screen row: 5

### ISSUE THREAD

**Issue by mitzkia** [atom/atom#5883]
[Enter steps to reproduce below:]

1. Unfortunatelly can not reproduce it.

**Atom Version**: 0.186.0
**System**: linux 3.13.0-37-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: No line exists for row 6. Last screen row: 5

```
At /usr/share/atom/resources/app/src/text-editor-presenter.js:385

Error: No line exists for row 6. Last screen row: 5
  at TextEditorPresenter.<anonymous> (/usr/share/atom/resources/app/src/text-editor-presenter.js:385:19)
  at TextEditorPresenter.module.exports.TextEditorPresenter.batch (/usr/share/atom/resources/app/src/text-editor-presenter.js:91:12)
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateLinesState (/usr/share/atom/resources/app/src/text-editor-presenter.js:375:19)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/usr/share/atom/resources/app/src/text-editor-presenter.js:123:14)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/share/atom/resources/app/src/text-editor-component.js:172:38)
  at /usr/share/atom/resources/app/src/text-editor-component.js:280:28
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app/src/view-registry.js:159:9)
  at /usr/share/atom/resources/app/src/view-registry.js:3:61

```

### Commands

```
     -0:57.1 editor:newline (atom-text-editor.editor.is-focused)
  8x -0:23.6 core:move-left (atom-text-editor.editor.is-focused)
     -0:22.1 core:move-right (atom-text-editor.editor.is-focused)
     -0:22.0 core:delete (atom-text-editor.editor.is-focused)
     -0:21.8 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:19.2 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:18.1 core:backspace (atom-text-editor.editor.is-focused)
     -0:13.3 core:move-up (atom-text-editor.editor.is-focused)
  8x -0:13.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:11.7 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:11.4 core:copy (atom-text-editor.editor.is-focused)
     -0:11.1 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.5 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:09.4 core:move-up (atom-text-editor.editor.is-focused)
     -0:09.2 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:07.5 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true,
    "showIndentGuide": true,
    "softWrap": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
github-issues, v0.3.0
highlight-line, v0.10.1
language-docker, v1.1.2
language-dockerfile, v0.1.0
linter, v0.12.0
trailing-spaces, v0.2.4
underline-trailing-whitespace, v1.0.1

# Dev
No dev packages
```

**Comment by mitzkia** [comment]
This issue appears very frequent for me (3-4 times from the first notification). 
Now I can reproduce it.
1, Editing a file (some lines in it, last line is empty line)
2, From the "tab menu" using "split right"
3, Uncaught error happended  when I closing the newly created tab in right.

Hope it can help.

**Comment by mitzkia** [comment]
I dont know if it help, but it not appears when I start atom in "--safe mode".

**Comment by mitzkia** [comment]
Sorry, but it seems the reproduction step is not so "good", after closing and restarting the editor the issue is not appears. But before the restart it works (the reproduction).

**Comment by izuzak** [comment]
@nathansobo I'm guessing we can close this in favor of https://github.com/atom/atom/issues/5667, but gonna let you take a look first just in case. :v:

Thanks for the report, @mitzkia!
