### ISSUE TITLE
Windows 0.186.0 update: "Failed to spawn command atom\app-0.186.0\resources\app\apm\bin\node"

### ISSUE THREAD

**Issue by RoboPhred** [atom/atom#5886]
After atom updated to 0.186, when launching atom and at random intervals, I get multiple instances of the message

```
"Failed to spawn command ~\AppData\Local\atom\app-0.186.0\resources\app\apm\bin\node. Make sure ~\AppData\Local\atom\app-0.186.0\resources\app\apm\bin\node is installed and on your PATH"
```

Atom will also crash on shutdown during this time.

At first I had reinstalled from an earlier installation executable (0.17x) to work around the issue, but it came back after the reinstalled version went through its auto update cycle.

The SquirrelSetup.log file shows no trouble in downloading the updates.  However, it has a somewhat contradictory error on installing:

System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully

```
Utility: Starting to delete folder: ~\AppData\Local\Temp\e\lib\net45\resources\app\node_modules\semver
Utility: Starting to delete folder: ~\AppData\Local\Temp\e\lib\net45\resources\app\node_modules\semver\bin
Program: Failed to apply updates, falling back to full updates: System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
   at DeltaCompressionDotNet.MsDelta.MsDeltaCompression.ApplyDelta(String deltaFilePath, String oldFilePath, String newFilePath)
   at Squirrel.DeltaPackageBuilder.applyDiffToFile(String deltaPath, String relativeFilePath, String workingDirectory)
   at Squirrel.DeltaPackageBuilder.<>c__DisplayClass1b.<ApplyDeltaPackage>b__c(String file)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass94.<createFullPackagesFromDeltas>b__90()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__96.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__5b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__3f.MoveNext()
CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
FileDownloader: Downloading url: 
FileDownloader: Downloading file: 
ApplyReleasesImpl: Writing files to app directory: ~\AppData\Local\atom\app-0.186.0
ApplyReleasesImpl: runPostInstallAndCleanup: starting fixPinnedExecutables
ApplyReleasesImpl: Processing shortcut ''
ApplyReleasesImpl: Does not match '~\AppData\Local\atom\app-0.175.0', continuing to next directory
ApplyReleasesImpl: Processing shortcut 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
ApplyReleasesImpl: Does not match '~\AppData\Local\atom\app-0.175.0', continuing to next directory
ApplyReleasesImpl: Processing shortcut 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe'
ApplyReleasesImpl: Does not match '~\AppData\Local\atom\app-0.175.0', continuing to next directory
ApplyReleasesImpl: Squirrel Enabled Apps: [~\AppData\Local\atom\app-0.186.0\atom.exe]
ApplyReleasesImpl: cleanDeadVersions: for version 0.186.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.175.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.186.0
Program: Starting Squirrel Updater: --download https://atom.io/api/updates
Program: Fetching update information, downloading from https://atom.io/api/updates
CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES
```

The contents of app-0.186.0\resources\app\apm\bin is:
apm
apm.cmd
node.exe

both apm.cmd and node.exe work fine when ran from the terminal.

**Comment by loque** [comment]
Same here with Atom 0.189 and Win 7. Any hint?

**Comment by damieng** [comment]
Hi. Are either of you still experiencing this problem in recent builds?

**Comment by damieng** [comment]
No response and unable to repro so closing.

Please re-open this issue if you are still having problems.
