### ISSUE TITLE
Atom install failed on Windows 10 Techincal Preview

### ISSUE THREAD

**Issue by adomas187** [atom/atom#5889]
Hello,
I had older version of Atom editor and I wanted to update. Update first failed, so I uninstalled old version of Atom via Control Panel > Uninstall Programs. Then I was trying to do fresh install, but got same problem. I deleted these dirs:

C:\Users\Adomas\AppData\Local\SquirrelTemp
C:\Users\Adomas\AppData\Local\atom\

And tried install again, but got same problem. Here is last log:
```
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\Adomas\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Adomas\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\Adomas\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\Adomas\AppData\Local\atom\app-0.186.0
IEnableLogger: Failed to update local releases file: System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Squirrel.ReleaseEntry.BuildReleasesFile(String releasePackagesDir)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>b__ec()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>d__ed.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\Adomas\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.FileNotFoundException: Could not find file 'C:\Users\Adomas\AppData\Local\atom\packages\RELEASES'.
File name: 'C:\Users\Adomas\AppData\Local\atom\packages\RELEASES'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\Adomas\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\Adomas\AppData\Local\atom\app-0.186.0
ApplyReleasesImpl: Writing files to app directory: C:\Users\Adomas\AppData\Local\atom\app-0.186.0
IEnableLogger: Failed to update local releases file: System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Squirrel.ReleaseEntry.BuildReleasesFile(String releasePackagesDir)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>b__ec()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>d__ed.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
```

-------------
Since I deteled old installation I am unable to get Atom working again, it simply does not install anymore. Any ideas how to fix this? Is this because I am using **Windows 10 Technical Preview**?

**Comment by Zireael07** [comment]
Check out your c:/windows/temp, delete any leftover files there too.

Other than that, maybe it's a permissions error? First it can't find the file, then it can't start from scratch... Maybe you don't have write permissions for the folder involved?

**Comment by paulcbetts** [comment]
This has nothing to do with Win10, @Zireael07 is correct. Delete all your files in %temp% and it'll work again.

**Comment by austinbutler** [comment]
Running CCleaner then trying the install again worked for me.

**Comment by trickyearlobe** [comment]
This happened to me after letting Windows 10 auto update me to latest preview.
Some apps (including Microsofts VS 2015 RC) failed after the upgrade, some still worked.

Re-installation of Atom (and a few other apps) failed despite performing the steps above.

It seems root cause is that the upgrade process messes with dir permissions and a lot of dirs (including some stuff in my home dir) become owned by "system installer". Doing anything in those dirs requires permission from system installer.

Recovery process is to reclaim ownership of those dirs and remove rights for "system installer". Its pretty time consuming finding all the stuff it broke and in hindsight I think I would have just re-installed.

**Comment by jhfoo** [comment]
I'm using Win 10 and had the same error installing. Mine is a refresh install of Win 10. Clearing the %temp% made the difference. Not sure why.

**Comment by speeves** [comment]
Verified that cleaning the %temp% dir fixed the issue

**Comment by terschure** [comment]
for me cleaning %temp% alone did not work, but ccleaner worked like magic

**Comment by JiwonHwang** [comment]
I have the same problem. Not I'm using sublime, but miss atom.

**Comment by schliesser** [comment]
cleaning %temp% dir fixed the issue. running win 10 pro (Build 10240)

**Comment by cdubya13** [comment]
I tried all these solutions, nothing worked. Also I tried running the program from straight from the download folder, it worked, but there were lots of features missing. Not satisfied, I turned off my antivirus software and it installed like a charm.

**Comment by ojoadeolagabriel** [comment]
Disabled the antivirus.. this fixed it

**Comment by rubens001** [comment]
For me ; "Disabled the antivirus.. this fixed it".
Great ! Tks

**Comment by mindtrix** [comment]
Disable antivirus fix this problem.

**Comment by SNC2897** [comment]
Yeah! 
Disabling antivirus and cleaning %temp% worked

**Comment by sanjeev45** [comment]
what git we should download to download script in atom

**Comment by Announcement** [comment]
[github for windows](https://windows.github.com/) is always recommended, comes with gui and cmd sysgit but [git-scm](https://git-scm.com/download/win)

**Comment by jaysonsantos** [comment]
After uninstalling McAffee it worked, would be nice to have something that would detect it before installintg.

**Comment by elfrevaldes** [comment]
You don't have to uninstall your antivirus. Just disabled it while you install atom and then it will work. The problem is that atom is trying to modify files and that looks like a suspicious activity for any decent antivirus. Again suspend your antivirus for a bit and then install and presto.

**Comment by davidayers** [comment]
Any ideas what I can do if I cant disable antivirus?

**Comment by 50Wliu** [comment]
@davidayers Then you'll have to install the zipped version.

**Comment by purplyrocky** [comment]
If you have McAfee, turn off "Real-Time Scanning" worked for me
