### ISSUE TITLE
Uncaught Error: premature end of char-class (mediawiki.tmbundle)

### ISSUE THREAD

**Issue by laurelnaiad** [atom/atom#5908]
1. `apm init --package ~/.atom/packages/language-mediawiki --convert https://github.com/textmate/mediawiki.tmbundle`
2. `atom ~/myfile.wiki`

Doesn't much matter what's in the .wiki file, e.g.:

```
== This Breaks It ==

Nothing fancy required.
```

...is all it takes. The mediawiki.tmbundle works well in Sublime... I imagine the port of the tmbundle might not be a clean one, but the unhandled nature of surprises coming from language extensions may not be desirable.

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: premature end of char-class

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:31

Error: premature end of char-class
  at Error (native)
  at Scanner.module.exports.Scanner.createScanner (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:31:24)
  at Scanner.module.exports.Scanner.getScanner (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:37:31)
  at Scanner.module.exports.Scanner.findNextMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:56:22)
  at Rule.module.exports.Rule.findNextMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/rule.js:101:28)
  at Rule.module.exports.Rule.getNextTokens (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/rule.js:143:21)
  at Grammar.module.exports.Grammar.tokenizeLine (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:125:39)
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedTokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:432:28)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:265:43)
  at /Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:247:26
  at /Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/underscore/underscore.js:666:47

```

### Commands

```
     -1:20.7 grammar-selector:show (atom-text-editor.editor)
     -0:46.9 window:update-available (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-format"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "editor": {
    "invisibles": {},
    "fontSize": 14,
    "fontFamily": "Anonymous Pro"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
auto-update-packages, v0.2.2
autocomplete-paths, v1.0.2
autocomplete-plus, v2.2.0
css-color-highlighting, v0.2.4
cucumber, v0.4.1
docblockr, v0.6.3
file-types, v0.3.0
language-mediawiki, v0.0.0
language-xquery, v0.0.1
linter, v0.12.0
linter-jscs, v1.8.0
linter-jshint, v0.1.0
linter-scss-lint, v0.0.14
markdown-stream, v0.6.0
minimap, v4.3.1
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
monokai, v0.12.0
recent-files, v0.3.0
syntax-settings, v0.7.1

# Dev
No dev packages
```

**Comment by artemisart** [comment]
Same issue here when i have a ] in a range of chars (in a regex in a grammar file) like [][(){}] (this is a valid pcrejs/py regex which should match a single character in the list ][(){} literally).

**Comment by wcandillon** [comment]
for me escaping [ and ] solved the issues. http://www.rubular.com/ is an extremely useful tool when developing syntax highlighting for Atom.

**Comment by laurelnaiad** [comment]
I just tried this again on a fresh Atom installation and the problem I reported is no longer apparent. I had had that prior Atom install since the early days, and it doesn't much surprise me that with current Atom version, cleanly installed, I don't seem to suffer this anymore.

**Comment by mikelittman** [comment]
This issue persists for me, even after a clean install.

**Comment by 50Wliu** [comment]
Awesome, thanks for the update @laurelnaiad!

**Comment by DerpfacePython** [comment]
I'm experiencing this issue in the newest stable version of Atom (1.10.2) when making a custom syntax highlighter (for my own language).

This is the code for the language:

    'scopeName': 'source.logicode'
    'name': 'Logicode'
    'fileTypes': ['lgc']
    'patterns': [
      {
        'comment': 'Binary Strings'
        'match': '[01]+'
        'name': 'constant.numeric.logicode'
      }
      {
        'comment': 'Declarers'
        'match': '(var|cond|circ|out)'
        'name': 'keyword.control.logicode'
      }
      {
        'comment': 'Keywords'
        'match': '([+\\[\\]\\/<>]|->|input)'
        'name': 'keyword.operator.logicode'
      }
    ]

When I open a `.lgc` file, however, this error pops up:

    Error: premature end of char-class
        at Error (native)
        at Scanner.module.exports.Scanner.createScanner (C:\Users\User\atom\app-1.10.2\resources\app.asar\node_modules\first-mate\lib\scanner.js:31:24)
        at Scanner.module.exports.Scanner.getScanner (C:\Users\User\atom\app-1.10.2\resources\app.asar\node_modules\first-mate\lib\scanner.js:37:31)
        at Scanner.module.exports.Scanner.findNextMatch (C:\Users\User\atom\app-1.10.2\resources\app.asar\node_modules\first-mate\lib\scanner.js:56:22)
        at Rule.module.exports.Rule.findNextMatch (C:\Users\User\atom\app-1.10.2\resources\app.asar\node_modules\first-mate\lib\rule.js:99:28)
        at Rule.module.exports.Rule.getNextTags (C:\Users\User\atom\app-1.10.2\resources\app.asar\node_modules\first-mate\lib\rule.js:141:21)
        at Grammar.module.exports.Grammar.tokenizeLine (C:\Users\User\atom\app-1.10.2\resources\app.asar\node_modules\first-mate\lib\grammar.js:150:44)
        at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (C:\Users\User\atom\app-1.10.2\resources\app.asar\src\tokenized-buffer.js:494:28)
        at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (C:\Users\User\atom\app-1.10.2\resources\app.asar\src\tokenized-buffer.js:482:19)
        at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (C:\Users\User\atom\app-1.10.2\resources\app.asar\src\tokenized-buffer.js:287:43)
        at C:\Users\User\atom\app-1.10.2\resources\app.asar\src\tokenized-buffer.js:264:26
        at C:\Users\User\atom\app-1.10.2\resources\app.asar\node_modules\underscore\underscore.js:666:47

This error doesn't appear in Dev mode, though, which is the weird thing.

**Comment by d5dhatch** [comment]
Somehow this just started appearing:
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: premature end of char-class

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:31

Error: premature end of char-class
    at Error (native)
    at Scanner.module.exports.Scanner.createScanner (/app.asar/node_modules/first-mate/lib/scanner.js:31:24)
    at Scanner.module.exports.Scanner.getScanner (/app.asar/node_modules/first-mate/lib/scanner.js:37:31)
    at Scanner.module.exports.Scanner.findNextMatch (/app.asar/node_modules/first-mate/lib/scanner.js:56:22)
    at Rule.module.exports.Rule.findNextMatch (/app.asar/node_modules/first-mate/lib/rule.js:99:28)
    at Rule.module.exports.Rule.getNextTags (/app.asar/node_modules/first-mate/lib/rule.js:155:21)
    at Grammar.module.exports.Grammar.tokenizeLine (/app.asar/node_modules/first-mate/lib/grammar.js:148:44)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/app.asar/src/tokenized-buffer.js:359:27)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/app.asar/src/tokenized-buffer.js:347:19)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/app.asar/src/tokenized-buffer.js:203:43)
    at /app.asar/src/tokenized-buffer.js:185:26
    at /app.asar/node_modules/underscore/underscore.js:666:47
```

### Commands

```
     -2:19.8.0 project-manager:list-projects (input.hidden-input)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-beautify 0.29.17 
atom-css-class-checker 0.4.3 
atom-terminal-panel 4.4.4 
atomizr 0.23.1 
aurora-theme 1.2.2 
color-tabs 0.1.8 
command-executor 1.4.3 
compare-files 0.8.0 
cson 2.0.1 
css-edit-groups 0.4.2 
file-type-icons 1.3.3 
file-type-icons 1.3.3 
foldername-tabs 0.2.4 
language-gedcom 1.1.1 
gedcom-theme-syntax 1.0.3 
git-time-machine 1.5.9 
grammar-live-reload 1.0.5 
grammar-tab-colors 0.2.8 
language-SCSS 0.4.0 
language-sml 0.7.0 
line-ending-converter 1.3.2 
nord-atom-syntax 0.7.0 
nord-atom-ui 0.11.0 
open-in-browser 0.5.0 
php-cs-fixer 4.1.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
pretty-dir 0.0.17 
project-manager 3.3.4 
quick-editor 0.4.3 
regex-filter-and-generator 1.4.2 
remove-whitespace 0.2.1 
restart-atom 0.2.0 
Sass-Syntax-Highlight 0.1.1 
ScssBundle 0.5.0 
set-syntax 0.3.2 
TreeColor 1.0.6 
```

**Comment by triaglesis** [comment]
Check regexes:
THIS trace current error in my grammar:
`\\\"(\#(?:(\\w+)(:|\\.))+(\\w+))\\\"\:\\s\[`
But this not:
`\\\"(\\\#(?:(\\w+)(:|\\.))+(\\w+))\\\"\\\:\\s\\\[`

try to escape any additional unusual symbols
