### ISSUE TITLE
Uncaught Error: No line exists for row 31. Last screen row: 30

### ISSUE THREAD

**Issue by Jaballadares** [atom/atom#5927]
[Enter steps to reproduce below:]

1. ...Drag js file from one window pain to another. Not sure it matters,  but the pane I was moving it to already had that file on it's side. 

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: No line exists for row 31. Last screen row: 30

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:385

Error: No line exists for row 31. Last screen row: 30
  at TextEditorPresenter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:385:19)
  at TextEditorPresenter.module.exports.TextEditorPresenter.batch (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:91:12)
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateLinesState (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:375:19)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:123:14)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:172:38)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:280:28
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:159:9)
  at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:61

```

### Commands

```
     -4:30.4 pane:reopen-closed-item (input.hidden-input)
     -4:27.6 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-Clouds.theme-atom-light-ui)
     -4:10.2 core:close (div.deprecation-cop.pane-item.native-key-bindings)
     -3:01.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-Clouds.theme-atom-light-ui)
     -1:28.7 core:save (input.hidden-input)
  6x -0:57.2 core:move-right (input.hidden-input)
     -0:53.6 core:save (input.hidden-input)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "Clouds"
    ],
    "disabledPackages": [
      "metrics"
    ]
  },
  "editor": {
    "fontFamily": "'Source Code Pro'",
    "fontSize": 13,
    "lineHeight": 1.6,
    "scrollPastEnd": true,
    "softWrap": true,
    "invisibles": {},
    "softTabs": false,
    "useShadowDOM": false
  }
}
```

### Installed Packages

```coffee
# User
Clouds, v1.0.5
atom-alignment, v0.11.0
atom-beautify, v0.21.4
atom-color-highlight, v3.0.8
atom-ternjs, v0.5.4
autocomplete-css, v0.4.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.1
color-picker, v1.4.4
file-icons, v1.5.1
highlight-line, v0.10.1
jshint, v1.3.0
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by philipgiuliani** [comment]
Please update Atom, this has been fixed with 0.187.0 (see https://github.com/atom/atom/pull/5904).
