### ISSUE TITLE
Windows installer fails to install

### ISSUE THREAD

**Issue by postal2600** [atom/atom#5933]
Hello,

Just wanted to upgrade my Atom to the latest version (I can't tell the version, the download link mentions "release 3228505") but the installer fails with the following error:

	Program: Starting Squirrel Updater: --install .
	Program: Starting install, writing to C:\Users\nicolae.surdu\AppData\Local\SquirrelTemp
	CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\nicolae.surdu\AppData\Local\atom\packages\RELEASES'.
	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
	   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
	   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
	CheckForUpdateImpl: Reading RELEASES file from C:\Users\nicolae.surdu\AppData\Local\SquirrelTemp
	CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
	ApplyReleasesImpl: Writing files to app directory: C:\Users\nicolae.surdu\AppData\Local\atom\app-0.187.0
	IEnableLogger: Failed to update local releases file: System.IO.IOException: The file exists.

	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	   at System.IO.__Error.WinIOError()
	   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
	   at Squirrel.ReleaseEntry.BuildReleasesFile(String releasePackagesDir)
	   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>b__ec()
	   at System.Threading.Tasks.Task`1.InnerInvoke()
	   at System.Threading.Tasks.Task.Execute()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>d__ed.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()

Uninstalling the old version and attempting again does not fix the issue

**Comment by 50Wliu** [comment]
Could you try deleting everything inside `%temp%` or running Disk Cleanup and trying again?
If that still doesn't work, what antivirus do you have installed?

/cc @paulcbetts

**Comment by postal2600** [comment]
Running the disk cleanup solved the problem. Just for the sake of completeness, I am running McAfee antivirus.
