### ISSUE TITLE
Uncaught Error: Command failed: /bin/sh -c virtualenv pu/bin/sh: virtualenv: command not found

### ISSUE THREAD

**Issue by oppianmatt** [atom/atom#5937]
[Enter steps to reproduce below:]

1. Try run any package that runs a command

Trying to run virtualenv, it's in /usr/local/bin and that's in the $PATH but still not found

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Command failed: /bin/sh -c virtualenv pu
/bin/sh: virtualenv: command not found

```
At events.js:94

Error: Command failed: /bin/sh -c virtualenv pu
/bin/sh: virtualenv: command not found

  at ChildProcess.exithandler (child_process.js:749:12)
  at ChildProcess.emit (events.js:119:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:116:17)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -0:09.7 core:close (atom-text-editor.editor.is-focused)
     -0:02.5 virtualenv:make (atom-pane.pane.active)
     -0:01.1 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true,
    "showIndentGuide": true,
    "preferredLineLength": 120
  }
}
```

### Installed Packages

```coffee
# User
atom-django, v0.2.1
linter, v0.12.0
linter-csslint, v0.0.11
linter-flake8, v1.3.0
linter-htmlhint, v0.0.8
linter-jshint, v0.1.0
minimap, v4.6.0
python-isort, v0.0.6
virtualenv, v0.6.2

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
I believe this is an issue with the virtualenv package and has been opened here: https://github.com/jhutchins/virtualenv/issues/21
