### ISSUE TITLE
Uncaught Error: EPERM, operation not permitted 'c:\Users\mmandam\bench\adminWorkFlows\nwf\components\shell\nwfLogin\nwfLogin-directive.js'

### ISSUE THREAD

**Issue by manoj84** [atom/atom#5954]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM, operation not permitted 'c:\Users\mmandam\bench\adminWorkFlows\nwf\components\shell\nwfLogin\nwfLogin-directive.js'

```
At c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\src\workspace.js:614

Error: EPERM, operation not permitted 'c:\Users\mmandam\bench\adminWorkFlows\nwf\components\shell\nwfLogin\nwfLogin-directive.js'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (C:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\atom\common\lib\asar.js:422:20)
  at Object.fs.writeFileSync (fs.js:1011:15)
  at Object.fsPlus.writeFileSync (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\node_modules\fs-plus\lib\fs-plus.js:228:17)
  at File.module.exports.File.writeFileSync (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\node_modules\pathwatcher\lib\file.js:227:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\node_modules\pathwatcher\lib\file.js:297:21)
  at File.module.exports.File.write (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\node_modules\pathwatcher\lib\file.js:286:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:966:17)
  at TextBuffer.module.exports.TextBuffer.save (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:954:19)
  at TextEditor.module.exports.TextEditor.save (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\src\text-editor.js:585:26)
  at Pane.module.exports.Pane.saveItem (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\src\pane.js:511:16)
  at Pane.module.exports.Pane.saveActiveItem (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\src\pane.js:501:19)
  at Workspace.module.exports.Workspace.saveActivePaneItemAndReportErrors (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\src\workspace.js:603:44)
  at Workspace.module.exports.Workspace.saveActivePaneItem (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\src\workspace.js:593:19)
  at atom-workspace.atom.commands.add.core:save (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\src\workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:243:29)
  at c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (c:\Users\mmandam\AppData\Local\atom\app-0.165.0\resources\app\src\window-event-handler.js:167:20)

```

### Commands

```
     -0:00.0 core:save (input.hidden-input)
```

### Config

```
{
  "editor": {
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please update Atom to the latest version (currently 0.187.0)-this has been resolved since 0.165.0.
