### ISSUE TITLE
Failed to activate the copy-paste-context package

### ISSUE THREAD

**Issue by jgh0721** [atom/atom#5958]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the copy-paste-context package

```
At Cannot read property 'apply' of undefined

TypeError: Cannot read property 'apply' of undefined
    at Function.<anonymous> (C:\Users\규호\AppData\Local\atom\app-0.187.0\resources\app\node_modules\space-pen\lib\space-pen.js:122:30)
    at Function.View.buildHtml (C:\Users\규호\AppData\Local\atom\app-0.187.0\resources\app\node_modules\space-pen\lib\space-pen.js:96:10)
    at CopyPasteContextView.View (C:\Users\규호\AppData\Local\atom\app-0.187.0\resources\app\node_modules\space-pen\lib\space-pen.js:121:33)
    at new CopyPasteContextView (/c:/Users/%EA%B7%9C%ED%98%B8/.atom/packages/copy-paste-context/lib/copy-paste-context-view.coffee:12:57)
    at Object.module.exports.activate (/c:/Users/%EA%B7%9C%ED%98%B8/.atom/packages/copy-paste-context/lib/copy-paste-context.coffee:8:42)
    at Package.module.exports.Package.activateNow (C:\Users\규호\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:240:19)
    at C:\Users\규호\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:221:30
    at Package.module.exports.Package.measure (C:\Users\규호\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:167:15)
    at Package.module.exports.Package.activate (C:\Users\규호\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:214:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\규호\AppData\Local\atom\app-0.187.0\resources\app\src\package-manager.js:465:21)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontFamily": "나눔고딕코딩",
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
copy-paste-context, v2.1.0
drag-drop-text, v0.1.0
restore-windows, v0.3.2

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
This looks like a bug in the `copy-paste-context` package, so [open an issue on its repo](https://github.com/shieldal/copy-paste-context/issues) instead.
