### ISSUE TITLE
Failed to activate the gist-it package

### ISSUE THREAD

**Issue by davionxiang** [atom/atom#5977]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the gist-it package

```
At undefined is not a function

TypeError: undefined is not a function
  at GistView.module.exports.GistView.initialize (/Users/davion/.atom/packages/gist-it/lib/gist-view.coffee:32:40)
  at GistView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:145:25)
  at new GistView (/Users/davion/.atom/packages/gist-it/lib/gist-view.coffee:8:3)
  at Object.module.exports.activate (/Users/davion/.atom/packages/gist-it/lib/gist.coffee:7:21)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:742:29
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:227:20)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -6:12.5 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
     -0:00.7 settings-view:open (atom-text-editor.editor.vim-mode.command-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-jshint"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
command-logger, v0.22.0
dash, v1.1.0
editor-stats, v0.17.0
file-icons, v1.5.1
gist-it, v0.6.6
language-elixir, v0.3.4
linter, v0.12.0
minimap, v4.6.0
monokai, v0.12.0
script, v2.18.0
travis-ci-status, v0.13.0
vim-mode, v0.39.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@davionxiang This seems to be a problem in the gist-it package, and as far as I can tell, it was already fixed in a more recent version of that package: https://github.com/rpowelll/gist-it/issues/37

It also seems that Atom's mechanism for detecting where an issue should be opened needs some tweaking to cover these cases. We're tracking that over in https://github.com/atom/notifications/issues/48.
