### ISSUE TITLE
Uncaught Error: write EOF

### ISSUE THREAD

**Issue by matgara** [atom/atom#5983]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: write EOF

```
At events.js:94

Error: write EOF
  at Object.exports._errnoException (util.js:753:11)
  at exports._exceptionWithHostPort (util.js:776:20)
  at WriteWrap.afterWrite (net.js:766:14)

```

### Commands

```
  2x -0:43.9 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:15.4 core:undo (atom-text-editor.editor.is-focused)
     -0:03.5 clang-format:format (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
clang-format, v1.8.0
linter-clang, v2.25.1

# Dev
No dev packages
```

**Comment by benogle** [comment]
This issue was moved to LiquidHelium/atom-clang-format#17
