### ISSUE TITLE
Failed to load the todo-list package

### ISSUE THREAD

**Issue by rogrmil** [atom/atom#5996]
[Enter steps to reproduce below:]

1. Launched Atom

**Atom Version**: 0.187.0
**System**: linux 3.18.6-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Failed to load the todo-list package

```
At variable @scrollbar-color is undefined

Error
    at new Parser (/usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
    at LessCache.module.exports.LessCache.parseLess (/usr/share/atom/resources/app/node_modules/less-cache/lib/less-cache.js:244:16)
    at LessCache.module.exports.LessCache.cssForFile (/usr/share/atom/resources/app/node_modules/less-cache/lib/less-cache.js:275:20)
    at LessCompileCache.module.exports.LessCompileCache.cssForFile (/usr/share/atom/resources/app/src/less-compile-cache.js:40:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/usr/share/atom/resources/app/src/theme-manager.js:368:33)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/usr/share/atom/resources/app/src/theme-manager.js:346:21)
    at /usr/share/atom/resources/app/src/package.js:436:45
    at Array.map (native)
    at Package.module.exports.Package.loadStylesheets (/usr/share/atom/resources/app/src/package.js:435:59)
    at /usr/share/atom/resources/app/src/package.js:186:19
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "*.meta"
    ],
    "themes": [
      "spacegray-eighties-ui",
      "spacegray-eighties-dark-syntax"
    ],
    "disabledPackages": [
      "emmet"
    ]
  },
  "editor": {
    "fontFamily": "Anonymous Pro for Powerline",
    "showIndentGuide": true,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
aural-coding, v0.6.0
autocomplete-plus, v2.5.0
autocomplete-plus-async, v0.22.0
autocomplete-plus-jedi, v0.0.8
color-picker, v1.4.4
file-icons, v1.5.1
file-types, v0.3.0
linter, v0.12.0
linter-clang, v2.25.1
linter-pep257, v0.2.0
linter-pep8, v0.1.0
linter-php, v0.0.11
linter-pylint, v0.2.1
live-editor-reload, v0.1.0
minimap, v4.6.0
minimap-color-highlight, v4.1.0
omnisharp-atom, v0.2.1
slickedit-select, v1.3.0
spacegray-eighties-dark-syntax, v0.7.1
spacegray-eighties-ui, v0.8.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@rogrmil This seems to be a problem similar to what's described here: https://github.com/atom/settings-view/issues/418#issuecomment-78482227

It's a problem that manifests for a certain combination of packages and the theme you use -- the todo-list page seems to be using [a variable](https://github.com/AnthonyCalandra/todo-list/blob/c53740958de6a74666d38c4f45f36000c27111f1/stylesheets/todo-list.less#L80) which [isn't defined in the theme which you're using](https://github.com/atom/atom-dark-ui/blob/eb80df7ebd7a6542df126666b1161690fcc5ec92/styles/ui-variables.less#L64) (for example, the [Atom Dark theme](https://github.com/atom/atom-dark-ui/blob/eb80df7ebd7a6542df126666b1161690fcc5ec92/styles/ui-variables.less#L64) does define it).

Suggestion: open an issue on the package's [issue tracker](https://github.com/AnthonyCalandra/todo-list/issues) so that it can handle themes which don't have this variable defined.

Also, it seems that Atom's mechanism for detecting where an issue should be opened needs some tweaking to cover these cases. We have an issue to track that: https://github.com/atom/notifications/issues/48
