### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 4 is larger than or equal to the node's length (3).

### ISSUE THREAD

**Issue by jdaniellhebert** [atom/atom#5997]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 4 is larger than or equal to the node's length (3).

```
At /Applications/Atom.app/Contents/Resources/app/src/lines-component.js:415

Error: Failed to execute 'setEnd' on 'Range': The offset 4 is larger than or equal to the node's length (3).
  at Error (native)
  at LinesComponent.module.exports.LinesComponent.measureCharactersInLine (/Applications/Atom.app/Contents/Resources/app/src/lines-component.js:415:33)
  at /Applications/Atom.app/Contents/Resources/app/src/lines-component.js:368:21
  at DisplayBuffer.module.exports.DisplayBuffer.batchCharacterMeasurement (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:558:7)
  at TextEditor.module.exports.TextEditor.batchCharacterMeasurement (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2929:33)
  at TextEditorPresenter.module.exports.TextEditorPresenter.batchCharacterMeasurement (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:1006:18)
  at LinesComponent.module.exports.LinesComponent.measureCharactersInNewLines (/Applications/Atom.app/Contents/Resources/app/src/lines-component.js:360:29)
  at TextEditorComponent.module.exports.TextEditorComponent.readAfterUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:230:36)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:3:61
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:162:9)
  at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:61

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.12.0
minimap, v4.6.0
pretty-json, v0.3.2
script, v2.18.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Do you have any steps to reproduce?  Can you reproduce this in safe mode (`atom --safe`)?
