### ISSUE TITLE
Uncaught Error: EACCES, permission denied '/Users/cavenmitchell/Documents/dump/kiste'

### ISSUE THREAD

**Issue by cavenmitchell** [atom/atom#5999]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: EACCES, permission denied '/Users/cavenmitchell/Documents/dump/kiste'

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:326

Error: EACCES, permission denied '/Users/cavenmitchell/Documents/dump/kiste'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:752:18)
    at Function.sync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
    at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:242:14)
    at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:245:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:315:21)
    at File.module.exports.File.write (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:304:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:970:17)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:621:26)
```
### Commands

```
     -0:00.7 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```
### Config

``` json
{
  "core": {
    "projectHome": "/users/cavenmitchell/projects"
  },
  "editor": {
    "invisibles": {}
  }
}
```
### Installed Packages

``` coffee
# User
vim-mode, v0.9.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Similar to https://github.com/atom/atom/issues/5292 and related to https://github.com/atom/atom/pull/5424. I'm hoping we cancatch these as well and show the custom notification? /cc @kevinsawicki @benogle

**Comment by cavenmitchell** [comment]
i don't know how to reproduce the issue but as far as i remember i had a document open in atom, replaced the folder and/or document in the command line. then opened a separate document in atom.  the error message came from the first document and I was unable close the document.  I had to quit atom and start over.

**Comment by kevinsawicki** [comment]
> the error message came from the first document and I was unable close the document.

Did the error popup after you clicked to close the editor or before?

**Comment by cavenmitchell** [comment]
it appeared after i attempted to close the first window. the window i wasn't editing.
