### ISSUE TITLE
Failed to load the virtualenv package

### ISSUE THREAD

**Issue by egeriicw** [atom/atom#6001]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Failed to load the virtualenv package

```
At Arguments to path.join must be strings

TypeError: Arguments to path.join must be strings
    at f (path.js:201:13)
    at Object.filter (native)
    at Object.win32.join (path.js:206:38)
    at new VirtualenvManager (/c:/Users/bill.eger/.atom/packages/virtualenv/lib/virtualenv-manager.coffee:34:24)
    at Object.<anonymous> (/c:/Users/bill.eger/.atom/packages/virtualenv/lib/init.coffee:13:14)
    at Object.<anonymous> (/c:/Users/bill.eger/.atom/packages/virtualenv/lib/init.coffee:76:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (C:\Users\bill.eger\AppData\Local\atom\app-0.187.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
linter-jsonlint, v0.1.2
pretty-json, v0.3.2
virtualenv, v0.6.2

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@egeriicw This seems to be a problem in the virtualenv package, somewhere around [here](https://github.com/jhutchins/virtualenv/blob/3b6b9337aeac72413756f03277f3b508bcb3837a/lib/virtualenv-manager.coffee#L26) (as far as I can tell by looking at the stack trace).

Could you re-open this on that package's [issue tracker](https://github.com/jhutchins/virtualenv/issues)? It seems that Atom's mechanism for detecting where an issue should be opened needs some tweaking to cover these cases.
