### ISSUE TITLE
Error installing v0.187.0 on Windows 

### ISSUE THREAD

**Issue by animedbz16** [atom/atom#6036]
Trying to install on Windows 7, trying to install the AtomSetup.exe from atom.io

I get the following in th SquirrelSetup.log:

```
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\<userid>\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\<userid>\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\<userid>\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\<userid>\AppData\Local\atom\app-0.187.0
IEnableLogger: Failed to update local releases file: System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Squirrel.ReleaseEntry.BuildReleasesFile(String releasePackagesDir)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>b__ec()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>d__ed.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
```

Looking under `C:\Users\<userid>\AppData\Local\atom`, it seems that there is an `app-0.187.0`, `packages`, and `Updater.exe` directories/files, under packages the only thing `atom-0.187.0-full.nupkg` exists, there is no `RELEASES` directory.

Not sure if this may be a bug in the installation or what.

**Comment by 50Wliu** [comment]
Could you please try deleting everything inside `%temp%` and trying again?
If that doesn't work, what antivirus do you have installed?

**Comment by animedbz16** [comment]
@50Wliu 
Clearing %temp% seemed to fix this issue.

Does the install process rely on potentially old data from %temp%, seems like it should download / create separate/new files during installation

**Comment by 50Wliu** [comment]
No it was a bug with Squirrel where it was flooding the temp directory with empty files and failing to clean up after itself.  Then during the next release %temp% was marked as full and the entire update would fail.  Pretty sure this has been fixed since then.
