### ISSUE TITLE
`grunt install` fails with EACCES

### ISSUE THREAD

**Issue by dasilvacontin** [atom/atom#6052]
```bash
> grunt install-dv --stack

Reading /var/folders/zz/zyxvpxvq6csfxvn_n00019cr000_b6/T/atom-build/Atom.app/Contents/Resources/atom.icns...OK
Writing /var/folders/zz/zyxvpxvq6csfxvn_n00019cr000_b6/T/115220-66696-1qo2hmr/Contents/Resources/atom.icns...OK
Reading /var/folders/zz/zyxvpxvq6csfxvn_n00019cr000_b6/T/atom-build/Atom.app/Contents/Resources/file.icns...OK
Writing /var/folders/zz/zyxvpxvq6csfxvn_n00019cr000_b6/T/115220-66696-1qo2hmr/Contents/Resources/file.icns...OK
Reading /var/folders/zz/zyxvpxvq6csfxvn_n00019cr000_b6/T/atom-build/Atom.app/Contents/Resources/speakeasy.pem...OK
Writing /var/folders/zz/zyxvpxvq6csfxvn_n00019cr000_b6/T/115220-66696-1qo2hmr/Contents/Resources/speakeasy.pem...OK
Copied /var/folders/zz/zyxvpxvq6csfxvn_n00019cr000_b6/T/atom-build/Atom.app to /var/folders/zz/zyxvpxvq6csfxvn_n00019cr000_b6/T/115220-66696-1qo2hmr.
Warning: EACCES, permission denied '/var/folders/zz/zyxvpxvq6csfxvn_n00019cr000_b6/T/115220-66696-1qo2hmr' Use --force to continue.
Error: EACCES, permission denied '/var/folders/zz/zyxvpxvq6csfxvn_n00019cr000_b6/T/115220-66696-1qo2hmr'
  at Object.fs.renameSync (fs.js:554:18)
  at Object.<anonymous> (/Volumes/Data/nfs/zfs-student-2/users/2014/dda-silv/github/atom-dasilvacontin/build/tasks/install-task.coffee:29:10)
  at Object.thisTask.fn (/Volumes/Data/nfs/zfs-student-2/users/2014/dda-silv/github/atom-dasilvacontin/build/node_modules/grunt/lib/grunt/task.js:82:16)
  at Object.<anonymous> (/Volumes/Data/nfs/zfs-student-2/users/2014/dda-silv/github/atom-dasilvacontin/build/node_modules/grunt/lib/util/task.js:301:30)
  at Task.runTaskFn (/Volumes/Data/nfs/zfs-student-2/users/2014/dda-silv/github/atom-dasilvacontin/build/node_modules/grunt/lib/util/task.js:251:24)
  at Task.<anonymous> (/Volumes/Data/nfs/zfs-student-2/users/2014/dda-silv/github/atom-dasilvacontin/build/node_modules/grunt/lib/util/task.js:300:12)
  at /Volumes/Data/nfs/zfs-student-2/users/2014/dda-silv/github/atom-dasilvacontin/build/node_modules/grunt/lib/util/task.js:227:11
  at process._tickCallback (node.js:419:13)


Aborted due to warnings.
```

**Comment by kevinsawicki** [comment]
This looks like a local permissions issue with the build folder.  But it looks like certain files were written successfully to `/var/folders/zz/zyxvpxvq6csfxvn_n00019cr000_b6/T/115220-66696-1qo2hmr` and other were not.

You can use the `--build-dir` and `--install-dir` command line options to specify where to build and install Atom to make sure no permissions issue are hit with the temp directory.

**Comment by dasilvacontin** [comment]
Thanks for the tips @kevinsawicki!
