### ISSUE TITLE
Uncaught Error: Unable to watch path

### ISSUE THREAD

**Issue by Gimly** [atom/atom#6106]
I was trying to save a file directly from Atom to a SharePoint document library. The file got saved correctly, but Atom gave this error report.
1. Create a simple text file
2. Save the created file to a SharePoint document library, using the following URL (here on an Office365 hosted SharePoint): http://yourSPSite.sharepoint.com/PathTo/YourDocument/Library

**Atom Version**: 0.188.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: Unable to watch path

```
At C:\Users\Xavier\AppData\Local\atom\app-0.188.0\resources\app\src\pane.js:794

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (C:\Users\Xavier\AppData\Local\atom\app-0.188.0\resources\app\node_modules\pathwatcher\lib\main.js:66:29)
    at new HandleWatcher (C:\Users\Xavier\AppData\Local\atom\app-0.188.0\resources\app\node_modules\pathwatcher\lib\main.js:30:12)
    at new PathWatcher (C:\Users\Xavier\AppData\Local\atom\app-0.188.0\resources\app\node_modules\pathwatcher\lib\main.js:120:30)
    at Object.exports.watch (C:\Users\Xavier\AppData\Local\atom\app-0.188.0\resources\app\node_modules\pathwatcher\lib\main.js:179:12)
    at File.module.exports.File.subscribeToNativeChangeEvents (C:\Users\Xavier\AppData\Local\atom\app-0.188.0\resources\app\node_modules\pathwatcher\lib\file.js:482:109)
    at File.module.exports.File.writeSync (C:\Users\Xavier\AppData\Local\atom\app-0.188.0\resources\app\node_modules\pathwatcher\lib\file.js:360:14)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Xavier\AppData\Local\atom\app-0.188.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:970:17)
    at TextEditor.module.exports.TextEditor.saveAs (C:\Users\Xavier\AppData\Local\atom\app-0.188.0\resources\app\src\text-editor.js:632:26)
    at Pane.module.exports.Pane.saveItemAs (C:\Users\Xavier\AppData\Local\atom\app-0.188.0\resources\app\src\pane.js:575:16)
```
### Commands

```
     -1:02.2 application:new-file (ul.list-inline.tab-bar.inset-panel)
  3x -0:54.2 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:53.3 core:select-right (atom-text-editor.editor.is-focused)
     -0:53.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  5x -0:51.3 core:backspace (atom-text-editor.editor.is-focused)
     -0:48.8 editor:newline (atom-text-editor.editor.is-focused)
     -0:43.9 core:paste (atom-text-editor.editor.is-focused)
     -0:41.6 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```
### Installed Packages

``` coffee
# User
language-powershell, v2.0.0

# Dev
No dev packages
```

**Comment by countingtoten** [comment]
I get a similar message when I empty my trash.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Unable to watch path

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:66

Error: Unable to watch path
  at Error (native)
  at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:66:29)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:43:25
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -7:05.2 core:cut (atom-text-editor.editor.insert-mode)
     -5:57.5 core:paste (atom-text-editor.editor)
  2x -5:50.8 core:delete (atom-text-editor.editor)
     -5:49.4 core:save (atom-text-editor.editor)
  2x -5:40.0 core:undo (atom-text-editor.editor)
     -5:37.6 core:save (atom-text-editor.editor)
     -5:02.1 editor:toggle-line-comments (atom-text-editor.editor)
  2x -5:01.3 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "linter-bootlint",
      "vim-mode"
    ]
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true,
    "showIndentGuide": true,
    "softWrapAtPreferredLineLength": true,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
angularjs, v0.2.0
api-blueprint-preview, v0.3.0
ember-cli-helper, v0.7.2
linter, v0.12.0
linter-clang, v2.25.1
linter-csslint, v0.0.11
linter-erb, v0.1.0
linter-javac, v0.1.3
linter-jshint, v0.1.0
linter-less, v0.3.1
linter-rubocop, v0.2.2
linter-ruby, v0.1.4
linter-scalac, v0.3.3
linter-scss-lint, v0.0.14
linter-shellcheck, v0.0.7
minimap, v4.7.1
project-palette-finder, v2.4.16
tabs-to-spaces, v0.9.1

# Dev
No dev packages
```

**Comment by SaifurRahmanMohsin** [comment]
+1

**Comment by nfleclerc** [comment]
Just had this happen to me on OS X

**Comment by ZeroCool2u** [comment]
Bump/+1

I'll leave this here:

I was saving a file to a remote directory on my remotely hosted server. 

**Atom Version**: 0.194.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Unable to watch path

```
At C:\Users\Tech Specialist\AppData\Local\atom\app-0.194.0\resources\app.asar\src\pane.js:759

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (C:\Users\Tech Specialist\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:66:29)
    at new HandleWatcher (C:\Users\Tech Specialist\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:30:12)
    at new PathWatcher (C:\Users\Tech Specialist\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:120:30)
    at Object.exports.watch (C:\Users\Tech Specialist\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:179:12)
    at File.module.exports.File.subscribeToNativeChangeEvents (C:\Users\Tech Specialist\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\pathwatcher\lib\file.js:467:109)
    at File.module.exports.File.writeSync (C:\Users\Tech Specialist\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\pathwatcher\lib\file.js:339:14)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Tech Specialist\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:913:17)
    at TextEditor.module.exports.TextEditor.saveAs (C:\Users\Tech Specialist\AppData\Local\atom\app-0.194.0\resources\app.asar\src\text-editor.js:558:26)
    at Pane.module.exports.Pane.saveItemAs (C:\Users\Tech Specialist\AppData\Local\atom\app-0.194.0\resources\app.asar\src\pane.js:544:16)
```

### Commands

```
     -1:38.5.0 core:backspace (atom-text-editor.editor)
     -1:30.5.0 editor:newline (atom-text-editor.editor)
  3x -1:28.8.0 core:backspace (atom-text-editor.editor)
     -1:23.5.0 editor:newline (atom-text-editor.editor)
  7x -1:22 core:backspace (atom-text-editor.editor)
     -1:12.5.0 editor:newline (atom-text-editor.editor)
     -1:08.5.0 core:save (atom-text-editor.editor)
     -1:00.9.0 core:save-as (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 15,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.24.1
autocomplete-html, v0.5.0
autocomplete-plus, v2.12.0
minimap, v4.7.6

# Dev
No dev packages
```

**Comment by LunarLanding** [comment]
[Enter steps to reproduce below:]

1. Entered this in the console: atom /Users/miguel/.pyenv/versions/env3.4.3/lib/python3.4/site-packages/usb/core.py
2. Atom opens the file , but complains.

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Unable to watch path

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:66

Error: Unable to watch path
  at Error (native)
  at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:66:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:43:25
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -4:52.6.0 core:move-left (atom-text-editor.editor)
  2x -4:51.9.0 core:backspace (atom-text-editor.editor)
  9x -4:45.7.0 core:move-right (atom-text-editor.editor)
     -4:43.4.0 core:save (atom-text-editor.editor)
     -1:29.8.0 command-palette:toggle (atom-text-editor.editor)
     -1:27.8.0 core:confirm (atom-text-editor.editor.mini)
     -1:27.8.0 go-to-line:toggle (atom-text-editor.editor)
     -1:24.2.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.12.1
minimap, v4.7.6
script, v2.19.0
script-runner, v1.7.3

# Dev
No dev packages
```

**Comment by liv3d** [comment]
Was working on files within a git repo, Arom was open but not the main focus.

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Unable to watch path

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:66

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:66:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:43:25
    at FSReqWrap.oncomplete (fs.js:77:15)
```

### Commands

```
  4x -8:13.3.0 core:select-left (atom-text-editor.editor)
     -8:11.8.0 core:backspace (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "solarized-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "fontSize": 14,
    "fontFamily": "Source Code Pro"
  }
}
```

### Installed Packages

```coffee
# User
language-puppet, v0.11.0
linter-puppet, v0.1.0
solarized-dark-ui, v0.3.0
trailing-spaces, v0.2.5

# Dev
No dev packages
```

**Comment by jmm** [comment]
[Enter steps to reproduce below:]

1. `File > Save As`

Dialog that popped up directed me to this issue.

**Atom Version**: 0.201.0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Unable to watch path

```
At C:\Program Files (x86)\GitHub Atom\resources\app.asar\src\pane.js:759

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (C:\Program Files (x86)\GitHub Atom\resources\app.asar\node_modules\pathwatcher\lib\main.js:66:29)
    at new HandleWatcher (C:\Program Files (x86)\GitHub Atom\resources\app.asar\node_modules\pathwatcher\lib\main.js:30:12)
    at new PathWatcher (C:\Program Files (x86)\GitHub Atom\resources\app.asar\node_modules\pathwatcher\lib\main.js:120:30)
    at Object.exports.watch (C:\Program Files (x86)\GitHub Atom\resources\app.asar\node_modules\pathwatcher\lib\main.js:179:12)
    at File.module.exports.File.subscribeToNativeChangeEvents (C:\Program Files (x86)\GitHub Atom\resources\app.asar\node_modules\pathwatcher\lib\file.js:467:109)
    at File.module.exports.File.writeSync (C:\Program Files (x86)\GitHub Atom\resources\app.asar\node_modules\pathwatcher\lib\file.js:339:14)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Program Files (x86)\GitHub Atom\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:981:17)
    at TextEditor.module.exports.TextEditor.saveAs (C:\Program Files (x86)\GitHub Atom\resources\app.asar\src\text-editor.js:571:26)
    at Pane.module.exports.Pane.saveItemAs (C:\Program Files (x86)\GitHub Atom\resources\app.asar\src\pane.js:544:16)
```

### Commands

```
     -2:38.7.0 core:page-down (atom-text-editor.editor.is-focused)
     -2:38.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:37.9.0 core:page-down (atom-text-editor.editor.is-focused)
  2x -2:36.6.0 core:move-down (atom-text-editor.editor.is-focused)
 22x -2:35.1.0 core:select-down (atom-text-editor.editor.is-focused)
  3x -2:33.8.0 core:select-up (atom-text-editor.editor.is-focused)
  4x -2:32.5.0 core:select-down (atom-text-editor.editor.is-focused)
     -2:29 core:save (atom-text-editor.editor.is-focused)
  2x -2:26.9.0 core:page-up (atom-text-editor.editor.is-focused)
  4x -1:28.9.0 core:page-down (atom-text-editor.editor.is-focused)
     -1:22.3.0 core:move-left (atom-text-editor.editor.is-focused)
undefined -1:21.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:24.7.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -0:23.2.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:22.7.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -0:13.8.0 core:save-as (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      "bower_components",
      "node_modules"
    ]
  },
  "editor": {
    "fontSize": 12,
    "autoIndentOnPaste": false,
    "softWrap": true,
    "invisibles": {},
    "softWrapAtPreferredLineLength": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by multiwebinc** [comment]
The way I reproduced this bug (linux) was:

1) Click on File > Open
2) Manually type in a **nonexistent** file name
3) Modify and save the new file

Here's the stack trace:

/usr/share/atom/resources/app.asar/src/pane.js:774
Hide Stack Trace
Error: Unable to watch path
  at Error (native)
  at HandleWatcher.start (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:66:29)
  at new HandleWatcher (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:30:12)
  at new PathWatcher (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:120:30)
  at Object.exports.watch (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:179:12)
  at File.module.exports.File.subscribeToNativeChangeEvents (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:476:109)
  at File.module.exports.File.writeSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:348:14)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:992:17)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:535:18)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:518:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:592:35)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app.asar/src/workspace-element.js:311:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

On a side note, there should definitely be some indication that a file doesn't exist when using the "Open" dialog. People could accidentally mistype the name and think that a file is empty when it is not.

**Comment by indyaah** [comment]
+1

[Enter steps to reproduce below:]
Working with git based repo, atom window was not in focus for a while.
Move back to atom and atoms shows the error.

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Unable to watch path

```
At /Users/Anuj/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:66

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/Users/Anuj/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:66:29)
    at /Users/Anuj/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:43:25
    at FSReqWrap.oncomplete (fs.js:77:15)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by bbashy** [comment]
1. Opened file
2. Renamed file while still open

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Unable to watch path

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:66

Error: Unable to watch path
  at Error (native)
  at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:66:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:43:25
  at FSReqWrap.oncomplete (fs.js:82:15)

```

### Commands

```
     -2:40.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:40.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:36.1.0 core:save (atom-text-editor.editor.is-focused)
     -2:17.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  4x -2:16.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:10.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:39.2.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:51.6.0 core:copy (atom-text-editor.editor.is-focused)
 11x -0:51.3.0 core:close (atom-text-editor.editor.is-focused)
     -0:37.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:31.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:14 core:move-right (atom-text-editor.editor.is-focused)
     -0:09.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.1.0 core:close (atom-text-editor.editor.is-focused)
     -0:03.5.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
language-blade, v0.16.0
laravel, v0.7.0

# Dev
No dev packages
```

**Comment by zachrattner** [comment]
FYI, I'm seeing this issue when I do the following:

(1) Open a text file in Atom that is mounted on an OS X Fuse drive (El Capitan)
(2) Change the name of the file in Finder
(3) Go back to Atom

**Comment by ZeroCool2u** [comment]
It seems like maybe Atom is not handling loss of connectivity to the remote location gracefully. Perhaps has something to do with the Path Watching implementation?

**Comment by artagnon** [comment]
Reproduces with a `mv` on an open file, on NFS.

**Comment by bbashy** [comment]
Yeah definitely on remote/smb/nfs issue.

**Comment by TylerNakamura** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Unable to watch path

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:66

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:66:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:43:25
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ]
  },
  "editor": {
    "fontSize": 13,
    "invisibles": {},
    "showIndentGuide": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.20.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by zmy** [comment]
[Enter steps to reproduce below:]

1. Move the file already opened in Atom to another directory.
2. Drag'n'drop to open another file.

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Unable to watch path

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:66

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:66:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:43:25
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -7:54.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:54.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/moony/Projects",
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "autoIndent": false,
    "fontSize": 9,
    "invisibles": {},
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
language-latex, v0.6.1
pretty-json, v0.4.1
seti-syntax, v0.4.1
seti-ui, v0.9.1

# Dev
No dev packages
```
