### ISSUE TITLE
Uncaught TypeError: Cannot read property 'screenDelta' of undefined

### ISSUE THREAD

**Issue by ysakmrkm** [atom/atom#6116]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'screenDelta' of undefined

```
At /usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/tokenized-line.js:208

TypeError: Cannot read property 'screenDelta' of undefined
  at TokenizedLine.module.exports.TokenizedLine.softWrapAt (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/tokenized-line.js:208:46)
  at DisplayBuffer.module.exports.DisplayBuffer.buildScreenLines (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:1501:37)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:1453:20)
  at DisplayBuffer.module.exports.DisplayBuffer.updateAllScreenLines (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:233:19)
  at DisplayBuffer.module.exports.DisplayBuffer.updateWrappedScreenLines (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:339:12)
  at DisplayBuffer.module.exports.DisplayBuffer.setWidth (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:465:14)
  at TextEditor.module.exports.TextEditor.setWidth (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor.js:2936:33)
  at TextEditorPresenter.module.exports.TextEditorPresenter.setContentFrameWidth (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:899:20)
  at TextEditorComponent.module.exports.TextEditorComponent.measureHeightAndWidth (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-component.js:832:31)
  at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-component.js:249:12)
  at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-component.js:790:16)
  at atom-text-editor.TextEditorElement.attachedCallback (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-element.js:91:22)
  at atom-pane.PaneElement.activeItemChanged (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:273:22)
  at Pane.module.exports.Pane.addItem (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:368:14)
  at Pane.module.exports.Pane.activateItem (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:336:14)
  at /usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/workspace.js:532:16
  at _fulfilled (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/q/q.js:756:13)
  at /usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/q/q.js:564:44
  at flush (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:366:11)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "grunt-runner",
      "atom-html-preview"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "projectHome": "/Users/ysakmrkm/git"
  },
  "editor": {
    "fontFamily": "SourceCodePro-Light",
    "autoIndentOnPaste": false,
    "tabLength": 4,
    "scrollPastEnd": true,
    "invisibles": {
      "eol": "$",
      "tab": "▶==="
    },
    "fontSize": 14,
    "softTabs": false,
    "showInvisibles": true,
    "showIndentGuide": true,
    "softWrapAtPreferredLineLength": true,
    "softWrap": true,
    "preferredLineLength": 100
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
compass, v0.7.5
emmet, v2.3.4
file-icons, v1.5.2
japanese-wrap, v0.2.4
language-apache, v1.2.0
language-jade, v0.3.0
minimap, v4.6.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
monokai, v0.13.0
recent-files, v0.3.0
regex-railroad-diagram, v0.7.1
vim-mode, v0.40.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@ysakmrkm Thanks for the report! You opened 3 other issues with no steps to reproduce or other context -- that makes it hard to investigate and fix problems. Can you share more information about when this happens, when it started happening, if you can reliably reproduce the problem, and if you can reproduce in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? Please provide that information for the three other issues as well: https://github.com/atom/atom/issues/6119, https://github.com/atom/atom/issues/6118, https://github.com/atom/atom/issues/6117.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/6116#issuecomment-87831587. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
