### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getMaxScreenColumn' of undefined

### ISSUE THREAD

**Issue by ysakmrkm** [atom/atom#6117]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'getMaxScreenColumn' of undefined

```
At /usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:1093

TypeError: Cannot read property 'getMaxScreenColumn' of undefined
  at DisplayBuffer.module.exports.DisplayBuffer.clipScreenPosition (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:1093:35)
  at TextEditor.module.exports.TextEditor.clipScreenPosition (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor.js:1268:33)
  at TextEditorPresenter.module.exports.TextEditorPresenter.pixelPositionForScreenPosition (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:1035:37)
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateContentDimensions (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:622:34)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:99:12)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-component.js:172:38)
  at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-component.js:260:21)
  at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-component.js:790:16)
  at TextEditorComponent.module.exports.TextEditorComponent.pollDOM (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-component.js:778:17)
  at /usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-component.js:3:61
  at ViewRegistry.module.exports.ViewRegistry.performDocumentPoll (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/view-registry.js:186:11)
  at /usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/view-registry.js:3:61

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "grunt-runner",
      "atom-html-preview"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "projectHome": "/Users/ysakmrkm/git"
  },
  "editor": {
    "fontFamily": "SourceCodePro-Light",
    "autoIndentOnPaste": false,
    "tabLength": 4,
    "scrollPastEnd": true,
    "invisibles": {
      "eol": "$",
      "tab": "▶==="
    },
    "fontSize": 14,
    "softTabs": false,
    "showInvisibles": true,
    "showIndentGuide": true,
    "softWrapAtPreferredLineLength": true,
    "softWrap": true,
    "preferredLineLength": 100
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
compass, v0.7.5
emmet, v2.3.4
file-icons, v1.5.2
japanese-wrap, v0.2.4
language-apache, v1.2.0
language-jade, v0.3.0
minimap, v4.6.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
monokai, v0.13.0
recent-files, v0.3.0
regex-railroad-diagram, v0.7.1
vim-mode, v0.40.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/6116#issuecomment-87831587. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
