### ISSUE TITLE
Uncaught TypeError: Cannot read property 'screenDelta' of undefined

### ISSUE THREAD

**Issue by ysakmrkm** [atom/atom#6119]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'screenDelta' of undefined

```
At /usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/tokenized-line.js:208

TypeError: Cannot read property 'screenDelta' of undefined
  at TokenizedLine.module.exports.TokenizedLine.softWrapAt (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/tokenized-line.js:208:46)
  at DisplayBuffer.module.exports.DisplayBuffer.buildScreenLines (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:1501:37)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:1453:20)
  at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:1433:12)
  at /usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:294:22)
  at /usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:247:26
  at /usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "grunt-runner",
      "atom-html-preview"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "projectHome": "/Users/ysakmrkm/git"
  },
  "editor": {
    "fontFamily": "SourceCodePro-Light",
    "autoIndentOnPaste": false,
    "tabLength": 4,
    "scrollPastEnd": true,
    "invisibles": {
      "eol": "$",
      "tab": "▶==="
    },
    "fontSize": 14,
    "softTabs": false,
    "showInvisibles": true,
    "showIndentGuide": true,
    "softWrapAtPreferredLineLength": true,
    "softWrap": true,
    "preferredLineLength": 100
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
compass, v0.7.5
emmet, v2.3.4
file-icons, v1.5.2
japanese-wrap, v0.2.4
language-apache, v1.2.0
language-jade, v0.3.0
minimap, v4.6.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
monokai, v0.13.0
recent-files, v0.3.0
regex-railroad-diagram, v0.7.1
vim-mode, v0.40.0

# Dev
No dev packages
```

**Comment by nathansobo** [comment]
The code causing this exception has since changed.
