### ISSUE TITLE
Uncaught Error: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by coldfumonkeh** [atom/atom#6121]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:128

Error: The workspace can only contain one instance of item [object Object]
  at ItemRegistry.module.exports.ItemRegistry.addItem (/Applications/Atom.app/Contents/Resources/app/src/item-registry.js:11:15)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:374:25)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:362:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:363:20)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:336:14)
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:532:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:817:14
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:366:11)

```

### Commands

```
     -9:09.7 irc:toggle (atom-text-editor.editor)
  3x -9:00.6 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-seti-ui)
     -4:45.2 irc:disconnect (ul.list-inline.tab-bar.inset-panel)
     -4:39.1 irc:toggle (ul.list-inline.tab-bar.inset-panel)
     -4:29.0 core:confirm (atom-text-editor.editor.mini)
     -3:30.7 irc:disconnect (atom-text-editor.editor)
     -3:28.7 irc:toggle (atom-text-editor.editor)
     -3:25.5 irc:connect (input.irc-input.native-key-bindings)
     -1:27.6 command-palette:toggle (atom-pane.pane)
     -1:24.6 core:confirm (atom-text-editor.editor.mini)
     -1:24.6 settings-view:open (atom-pane.pane)
     -1:19.7 core:confirm (atom-text-editor.editor.mini)
  2x -1:01.3 irc:connect (atom-pane.pane)
     -0:04.8 irc:disconnect (atom-text-editor.editor)
     -0:02.4 irc:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-jshint",
      "linter"
    ],
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-backbone, v0.6.0
atom-jasmine, v0.5.0
editorconfig, v0.3.3
file-icons, v1.5.2
grunt-runner, v0.8.0
irc, v0.2.9
jenkins, v0.3.1
markdown-pdf, v1.3.5
minimap-git-diff, v4.1.2
pdf-view, v0.17.0
seti-ui, v0.6.3
wordcount, v2.1.0

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
This looks like a bug in the irc package. Please [open an issue on the package repo](https://github.com/cjsaylor/atom-irc/issues).

**Comment by mauricioszabo** [comment]
This bug still happens with me... 

Here's the stacktrace:

```
Uncaught (in promise) Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/usr/share/atom/resources/app.asar/src/item-registry.js:11:15)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app.asar/src/pane-container.js:389:25)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:368:19
    at /usr/share/atom/resources/app.asar/src/pane-container.js:95:16
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.didAddPane (/usr/share/atom/resources/app.asar/src/pane-container.js:308:27)
    at Pane.module.exports.Pane.setContainer (/usr/share/atom/resources/app.asar/src/pane.js:131:26)
    at PaneAxis.module.exports.PaneAxis.setContainer (/usr/share/atom/resources/app.asar/src/pane-axis.js:88:30)
    at PaneContainer.module.exports.PaneContainer.setRoot (/usr/share/atom/resources/app.asar/src/pane-container.js:162:17)
    at PaneContainer.module.exports.PaneContainer.deserialize (/usr/share/atom/resources/app.asar/src/pane-container.js:62:12)
    at Workspace.module.exports.Workspace.deserialize (/usr/share/atom/resources/app.asar/src/workspace.js:171:33)
    at AtomEnvironment.module.exports.AtomEnvironment.deserialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:1063:24)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:775:21
```

I've opened Atom with --safe and it worked. Now, it's opening my project again. Why did it happen, I have no idea...

**Comment by inoas** [comment]
Encountered this when trying to split panes to move the project drawer/tree view to the right

**Comment by nofishonfriday** [comment]
> Encountered this when trying to split panes to move the project drawer/tree view to the right

Me too.
