### ISSUE TITLE
Failing loading module in Atom package

### ISSUE THREAD

**Issue by surdu** [atom/atom#6139]
I'm trying to use the [node-serialport](https://github.com/voodootikigod/node-serialport) in an Atom package, but this simple code:

```JavaScript
var serialPort = require("serialport");

module.exports = {
    activate: function(state) {
      serialPort.list(function (err, ports) {
        ports.forEach(function(port) {
          console.log(port.comName);
        });
      });
    }
};
```

yield the following error:

```
Cannot find module '/home/postal/Dropbox/Area51/myPackage/node_modules/serialport/build/serialport/v1.6.3/Release/node-v41-linux-x64/serialport.node'

Error: Cannot find module '/home/postal/Dropbox/Area51/myPackage/node_modules/serialport/build/serialport/v1.6.3/Release/node-v41-linux-x64/serialport.node'
    at Module._resolveFilename (module.js:351:15)
    at Function.exports.register.Module._resolveFilename (/opt/atom/resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/home/postal/Dropbox/Area51/myPackage/node_modules/serialport/serialport.js:15:25)
    at Module._compile (module.js:475:26)
    at Object.loadFile [as .js] (/opt/atom/resources/app/src/babel.js:162:21)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
```

I can confirm that the module specified as not found is actually at that location and the following code runs OK when ran directly with `node`:

```JavaScript
var serialPort = require("serialport");

serialPort.list(function (err, ports) {
  ports.forEach(function(port) {
    console.log(port.comName);
  });
});
```

**Comment by kevinsawicki** [comment]
Looks like `/home/postal/Dropbox/Area51/myPackage/node_modules/serialport/build/serialport/v1.6.3/Release/node-v41-linux-x64/serialport.node` is missing or was not built/installed correctly.

Rebuilding and making sure this file exists should resolve things, closing this out.
