### ISSUE TITLE
Uncaught Error: ENOENT,  not found in /opt/atom/share/atom/resources/atom.asar

### ISSUE THREAD

**Issue by mMerlin** [atom/atom#6140]
This one is easy to reproduce in my environment.

/opt/atom is where I have atom installed
$ pwd
/opt/atom/share/atom/resources
$ ls -lsn
total 116
  4 drwxrwxr-x. 15 1000 1000   4096 Mar 27 01:22 app
112 -rw-rw-r--.  1 1000 1000 112711 Mar 27 01:22 atom.asar

[Enter steps to reproduce below:]
1. cd /opt/atom/share/atom/resources/
2. atom
3. click "atom.asar" in tree view

**Atom Version**: 0.188.0-d462895
**System**: linux 3.19.1-201.fc21.i686
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: ENOENT,  not found in /opt/atom/share/atom/resources/atom.asar

```
At /opt/atom/share/atom/resources/app/src/workspace.js:518

Error: ENOENT,  not found in /opt/atom/share/atom/resources/atom.asar
    at createNotFoundError (ATOM_SHELL_ASAR.js:101:13)
    at Object.module.(anonymous function) [as open] (ATOM_SHELL_ASAR.js:156:25)
    at ReadStream.open (fs.js:1630:6)
    at new ReadStream (fs.js:1617:10)
    at Object.fs.createReadStream (fs.js:1571:10)
    at File.module.exports.File.read (/opt/atom/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:307:27)
    at TextBuffer.module.exports.TextBuffer.updateCachedDiskContents (/opt/atom/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1009:61)
    at TextBuffer.module.exports.TextBuffer.load (/opt/atom/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1033:19)
    at Project.module.exports.Project.buildBuffer (/opt/atom/share/atom/resources/app/src/project.js:507:21)
    at Project.module.exports.Project.bufferForPath (/opt/atom/share/atom/resources/app/src/project.js:477:63)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {},
    "autoIndentOnPaste": false,
    "showInvisibles": true,
    "softWrap": true,
    "fontSize": 14
  }
}
```
### Installed Packages

``` coffee
# User
tabs-to-spaces, v0.9.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
@zcbenz is there a way to read `atom.asar` (or `app.asar`) directly using `fs`?

**Comment by zcbenz** [comment]
@kevinsawicki You can use the [original-fs](https://github.com/atom/electron/blob/master/docs/tutorial/application-packaging.md#treating-asar-archive-as-normal-file) built-in module.

**Comment by kevinsawicki** [comment]
> You can use the original-fs built-in module.

Awesome, thanks!
