### ISSUE TITLE
Failed to load the welcome package

### ISSUE THREAD

**Issue by rafvall** [atom/atom#6144]
1. Launch app

**Atom Version**: 0.188.0
**System**: linux 3.10.0-031000-generic
**Thrown From**: Atom Core

### Stack Trace

Failed to load the welcome package

```
At EACCES, permission denied '/home/rafvall/.atom/compile-cache/less/e1251573b94229de3a9ca9779a708bc3ffe3707e/content/c5485ae838479004bcb2ece34c3281e62cf8e853/welcome.json'

Error: EACCES, permission denied '/home/rafvall/.atom/compile-cache/less/e1251573b94229de3a9ca9779a708bc3ffe3707e/content/c5485ae838479004bcb2ece34c3281e62cf8e853/welcome.json'
    at Error (native)
    at Object.fs.openSync (fs.js:503:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1116:15)
    at Object.fsPlus.writeFileSync (/opt/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:246:17)
    at LessCache.module.exports.LessCache.writeJson (/opt/atom/resources/app/node_modules/less-cache/lib/less-cache.js:155:17)
    at LessCache.module.exports.LessCache.putCachedCss (/opt/atom/resources/app/node_modules/less-cache/lib/less-cache.js:225:19)
    at LessCache.module.exports.LessCache.cssForFile (/opt/atom/resources/app/node_modules/less-cache/lib/less-cache.js:276:12)
    at LessCompileCache.module.exports.LessCompileCache.cssForFile (/opt/atom/resources/app/src/less-compile-cache.js:40:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/opt/atom/resources/app/src/theme-manager.js:368:33)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.11.0
color-picker, v1.4.4
docblockr, v0.6.3
emmet, v2.3.4
jslint, v1.2.0
linter, v0.12.0
monokai, v0.12.0
prefixr, v0.2.0

# Dev
No dev packages
```

**Comment by Zireael07** [comment]
It looks to me like those four reports are identical, why send four issues?

**Comment by rafvall** [comment]
Sorry, I hadn't seen stack trace. I only saw its titles and I thought they were different issues.

**Comment by rafvall** [comment]
I've fixed the issue. It was a problem with my configuration folder permissions. I'm going to close this issue. Thanks and sorry for send this report.
