### ISSUE TITLE
Failed to load the emmet-atom package

### ISSUE THREAD

**Issue by benbrandt** [atom/atom#6158]
[Enter steps to reproduce below:]

1. Open Atom and get error

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Failed to load the emmet-atom package

```
At Cannot find module 'C:\Users\benbrandt\AppData\Local\atom\app-0.187.0\resources\app\node_modules\snippets'

Error: Cannot find module 'C:\Users\benbrandt\AppData\Local\atom\app-0.187.0\resources\app\node_modules\snippets'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (C:\Users\benbrandt\AppData\Local\atom\app-0.187.0\resources\app\src\module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/c:/Users/benbrandt/.atom/packages/emmet-atom/lib/editor-proxy.coffee:20:14)
    at Object.<anonymous> (/c:/Users/benbrandt/.atom/packages/emmet-atom/lib/editor-proxy.coffee:207:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (C:\Users\benbrandt\AppData\Local\atom\app-0.187.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "softWrap": true,
    "fontSize": 15,
    "invisibles": {},
    "fontFamily": "Courier Prime Source"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.7.0
color-picker, v1.5.0
editor-stats, v0.17.0
emmet, v2.3.4
emmet-atom, v2.1.2
linter, v0.12.0
minimap, v4.6.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Try updating to the latest version of Atom and emmet-atom and open an issue at https://github.com/emmetio/emmet-atom/issues if you can still reproduce this.
