### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/iconv-lite/lib/index.js'

### ISSUE THREAD

**Issue by jeromeds** [atom/atom#6165]
[Enter steps to reproduce below:]

1. I just saved my file during a git rebase. The message appear and I cannot save anymore...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/iconv-lite/lib/index.js'

```
At /Applications/Atom.app/Contents/Resources/app/src/workspace.js:710

Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/iconv-lite/lib/index.js'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:313:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.Module._extensions..js (module.js:485:20)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:239:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:304:21)
  at File.module.exports.File.write (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:293:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:970:17)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:620:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:538:16)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:522:19)
  at Workspace.module.exports.Workspace.saveActivePaneItemAndReportErrors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:689:44)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:679:19)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -3:51.5 core:paste (atom-text-editor.editor.is-focused)
     -3:27.8 core:copy (atom-text-editor.editor.is-focused)
     -3:26.9 core:paste (atom-text-editor.editor.is-focused)
  2x -3:07.4 core:copy (atom-text-editor.editor.is-focused)
 17x -1:19.1 core:undo (atom-text-editor.editor.is-focused)
  8x -1:15.5 core:cut (atom-text-editor.editor.is-focused)
     -1:03.6 core:save (atom-text-editor.editor.is-focused)
     -1:03.0 project-find:show (atom-text-editor.editor.is-focused)
  6x -1:00.4 core:backspace (atom-text-editor.editor.mini)
     -0:58.2 core:confirm (atom-text-editor.editor.mini)
  2x -0:50.5 core:undo (atom-text-editor.editor)
     -0:48.0 core:cut (atom-text-editor.editor)
  2x -0:40.4 core:save (atom-text-editor.editor.is-focused)
 32x -0:13.1 core:undo (atom-text-editor.editor.is-focused)
  4x -0:03.5 core:cut (atom-text-editor.editor.is-focused)
     -0:00.8 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "eslint"
    ],
    "themes": [
      "atom-dark-ui",
      "seti-monokai"
    ]
  },
  "editor": {
    "fontSize": 12,
    "showIndentGuide": true,
    "softWrap": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v0.3.0
linter, v0.10.1
linter-jshint, v0.1.0
linter-jsxhint, v0.1.0
react, v0.8.8
seti-monokai, v0.3.1

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
This should be fixed now that [asar support in Atom](https://github.com/atom/atom/pull/6313) has shipped. Please comment if it happens again on Atom 0.194.0+.
