### ISSUE TITLE
Failed to load the a-package-loader package

### ISSUE THREAD

**Issue by bradbergeron-us** [atom/atom#6192]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Failed to load the a-package-loader package

```
At Cannot find module '/Applications/Atom.app/Contents/Resources/app\src\package'

Error: Cannot find module '/Applications/Atom.app/Contents/Resources/app\src\package'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Volumes/Macintosh%20HD/Users/bradleybergeron/.atom/packages/a-package-loader/lib/main.coffee:89:17)
    at Object.<anonymous> (/Volumes/Macintosh%20HD/Users/bradleybergeron/.atom/packages/a-package-loader/lib/main.coffee:287:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "sync-on-save",
      "MavensMate-Atom",
      "jasmine-runner",
      "angularjs",
      "angularjs-helper",
      "angularjs-snippets",
      "asteroids",
      "atom-angularjs",
      "atom-grails",
      "atom-python-debugger",
      "cakephp-snippets",
      "language-python-django-templates",
      "laravel-facades",
      "laravel",
      "linter-python-pyflakes",
      "linter-python-pep8",
      "meteor-api",
      "meteor-helper",
      "minimap",
      "my-package",
      "pep8",
      "python",
      "python-isort",
      "vim-mode",
      "atom-django",
      "autocomplete-jedi",
      "color-picker",
      "genesis-snippets",
      "animation-showcase",
      "language-coffee-script-angular",
      "linter-flake8",
      "localization"
    ],
    "followSymlinks": true,
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
a-package-loader, v1.0.0
atom-ternjs, v0.5.6
auto-detect-indentation, v0.3.0
block-travel, v1.0.2
bootstrap-3-snippetset, v0.0.6
emmet, v2.3.4
foundation5-snippets, v0.2.0
git-log, v0.3.0
git-projects, v1.10.1
go-to-view, v0.1.2
linter, v0.12.0
linter-ruby, v0.1.4
monokai, v0.12.0
related-files, v0.3.0
ruby-block, v0.3.3
ruby-define-method, v0.2.0
script, v2.18.0
syntax-settings, v0.7.1
travis-ci-status, v0.13.0
tree-view-git-projects, v0.5.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Please reopen the issue here: https://github.com/zren/atom-a-package-loader/issues. 

Seems to be a problem with this line in that package:

https://github.com/Zren/atom-a-package-loader/blob/3e305f925085bf174f7c320acc70a704afcec39d/lib/main.coffee#L68
