### ISSUE TITLE
Deleting a file in Atom will throw an exception when you actually empty the garbage

### ISSUE THREAD

**Issue by countingtoten** [atom/atom#6207]
[Enter steps to reproduce below:]
1. Right click in the sidebar and delete any file that's in the project. Possibly requires the file to be open.
2. Empty the Trash
3. Observe the error message
4. If the file had been open see it still open but with garbage characters

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: Unable to watch path

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:66

Error: Unable to watch path
  at Error (native)
  at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:66:29)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:43:25
  at FSReqWrap.oncomplete (fs.js:100:15)

```
### Commands

```
     -7:05.2 core:cut (atom-text-editor.editor.insert-mode)
     -5:57.5 core:paste (atom-text-editor.editor)
  2x -5:50.8 core:delete (atom-text-editor.editor)
     -5:49.4 core:save (atom-text-editor.editor)
  2x -5:40.0 core:undo (atom-text-editor.editor)
     -5:37.6 core:save (atom-text-editor.editor)
     -5:02.1 editor:toggle-line-comments (atom-text-editor.editor)
  2x -5:01.3 core:save (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "linter-bootlint",
      "vim-mode"
    ]
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true,
    "showIndentGuide": true,
    "softWrapAtPreferredLineLength": true,
    "softWrap": true
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
angularjs, v0.2.0
api-blueprint-preview, v0.3.0
ember-cli-helper, v0.7.2
linter, v0.12.0
linter-clang, v2.25.1
linter-csslint, v0.0.11
linter-erb, v0.1.0
linter-javac, v0.1.3
linter-jshint, v0.1.0
linter-less, v0.3.1
linter-rubocop, v0.2.2
linter-ruby, v0.1.4
linter-scalac, v0.3.3
linter-scss-lint, v0.0.14
linter-shellcheck, v0.0.7
minimap, v4.7.1
project-palette-finder, v2.4.16
tabs-to-spaces, v0.9.1

# Dev
No dev packages
```

**Comment by mathiasvr** [comment]
I use Mac OS X 10.10.2 and Atom 0.188.0 as well, but when I delete a file (move to trash) it remains open and editable, when emptying trash the file automatically closes in atom without errors.
