### ISSUE TITLE
Install task failing when building from source

### ISSUE THREAD

**Issue by stramel** [atom/atom#6238]
I get the following error on the install task when building from source. I can't find the file that it is saying exists. The issue just started today, was not an issue yesterday.

**OS:** Ubuntu 14.04 64bit

```console
Running "install" task
Error: EEXIST, file already exists '../share/atom/resources/app/apm/node_modules/.bin/apm'
  at Object.fs.symlinkSync (fs.js:742:18)
  at Object.<anonymous> (/home/stramel/Projects/atom/build/tasks/install-task.coffee:59:10)
  at Object.thisTask.fn (/home/stramel/Projects/atom/build/node_modules/grunt/lib/grunt/task.js:82:16)
  at Object.<anonymous> (/home/stramel/Projects/atom/build/node_modules/grunt/lib/util/task.js:301:30)
  at Task.runTaskFn (/home/stramel/Projects/atom/build/node_modules/grunt/lib/util/task.js:251:24)
  at Task.<anonymous> (/home/stramel/Projects/atom/build/node_modules/grunt/lib/util/task.js:300:12)
  at Task.start (/home/stramel/Projects/atom/build/node_modules/grunt/lib/util/task.js:309:5)
  at Object.grunt.tasks (/home/stramel/Projects/atom/build/node_modules/grunt/lib/grunt.js:164:8)
  at Object.module.exports [as cli] (/home/stramel/Projects/atom/build/node_modules/grunt/lib/grunt/cli.js:38:9)
  at Object.<anonymous> (/home/stramel/Projects/atom/build/node_modules/grunt-cli/bin/grunt:45:20)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:929:3
```

**Comment by izuzak** [comment]
Which version of Atom are you building? Which is the last version you are able to build successfully?

**Comment by stramel** [comment]
@izuzak Just pulled down the latest master and it is now fixed.

**Comment by buhtz** [comment]
How do you even build this on 14.04?

On my Kubuntu 14.04.2 (32bit) is the npm-Version to low. The build script doesn't run.

**Comment by kubetz** [comment]
@buhtz You should be able to update npm by typing `npm install npm -g`

Complete build instruction for Linux are located [here](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md).

**Comment by buhtz** [comment]
Your hint with updating npm is missing in that documentation!

**Comment by stramel** [comment]
@kubetz Here are the two scripts that I use.

```shell
#!/bin/sh
# Build From Master

cd ~/Projects/atom/ # Navigate to folder containing Atom Repo
git checkout master
git fetch -p # Fetch is optional since pull will already fetch from the current branch
git pull
script/build
sudo script/grunt install
```

```shell
#!/bin/sh
# Build from latest release

cd ~/Projects/atom/ # Navigate to folder containing Atom Repo
git fetch -p
git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
script/build
sudo script/grunt install
```

I think I have a permission problem since I have to do `sudo script/grunt install`

**Comment by buhtz** [comment]
Thanks but I am waiting for a deb. I just wanted to check out "atom".
I don't know if I like it so I need to test.
I'll check out a video about it maybe.

**Comment by stramel** [comment]
@buhtz They already have a .deb and .rpm file available via their website.

https://atom.io/
[deb](https://atom.io/download/deb)
[rpm](https://atom.io/download/rpm)

**Comment by buhtz** [comment]
@stramel The packages only for (exotic) 64-bit systems - not for 32-bit.

**Comment by buhtz** [comment]
The npm-update doesn't work. See
Linux TONNE 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:27:48 UTC 2015 i686 athlon i686 GNU/Linux
Ubuntu 14.04.2 LTS \n \l

user@TONNE:~$ npm -v
2.12.0
user@TONNE:~$ sudo npm install npm -g
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
npm@2.12.1 /usr/lib/node_modules/npm
user@TONNE:~$ npm -v
2.12.0

**Comment by buhtz** [comment]
There is a nice PPA for 32-bit available.
https://launchpad.net/~webupd8team/+archive/ubuntu/atom?field.series_filter=trusty

**Comment by JPRuehmann** [comment]
I have this Message to,
But it builds just fine.
But I would be very gracefull if someone could tell me why this is happening, and why it is treated as error, therefore it is just an Info and should not come via errout but via stdout.

I am using Kubuntu 16.04 LTS (32Bit)

Thanks,
