### ISSUE TITLE
Uncaught Error: EINTR: interrupted system call, close

### ISSUE THREAD

**Issue by micheltlutz** [atom/atom#6260]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EINTR: interrupted system call, close

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:794

Error: EINTR: interrupted system call, close
  at Error (native)
  at Object.fs.closeSync (fs.js:513:18)
  at Object.fs.writeFileSync (fs.js:1168:8)
  at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:246:17)
  at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:285:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:383:21)
  at File.module.exports.File.writeSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:357:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:980:17)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:968:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:628:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:554:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:537:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:687:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:552:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:392:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:53.1 core:cut (atom-text-editor.editor.is-focused)
  4x -0:52.9 core:move-up (atom-text-editor.editor.is-focused)
     -0:52.2 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:52.2 snippets:expand (atom-text-editor.editor.is-focused)
     -0:52.2 editor:indent (atom-text-editor.editor.is-focused)
     -0:51.9 core:paste (atom-text-editor.editor.is-focused)
  2x -0:51.7 core:move-down (atom-text-editor.editor.is-focused)
     -0:50.8 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:50.5 core:paste (atom-text-editor.editor.is-focused)
     -0:46.5 core:backspace (atom-text-editor.editor.is-focused)
     -0:46.0 core:save (atom-text-editor.editor.is-focused)
     -0:26.7 core:move-right (atom-text-editor.editor)
     -0:25.1 core:save (atom-text-editor.editor)
     -0:09.3 core:copy (atom-text-editor.editor.is-focused)
     -0:08.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:07.6 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "jshint"
    ],
    "ignoredNames": [
      "._.DS_Store",
      ".apdisk",
      "._.apdisk",
      ".DS_Store",
      ".TemporaryItems"
    ]
  },
  "editor": {
    "fontSize": 13,
    "showIndentGuide": true,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.12.0
linter-php, v0.0.11
monokai, v0.12.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@micheltlutz This looks very similar to https://github.com/atom/atom/issues/4467. Can you share the steps which reproduce this for you or at least what you were doing when this error was triggered? Are you working with files over sshfs?

**Comment by micheltlutz** [comment]
@izuzak simple, command + S. Yes over SSHFS VM ubuntu server on my local network.

**Comment by izuzak** [comment]
Great, thanks @micheltlutz -- I just added [a comment](https://github.com/atom/atom/issues/4467#issuecomment-91242836) to that other issue about your report so I'm closing this.
