### ISSUE TITLE
Uncaught Error: Definition for rule 'no-multiple-empty-lines' was not found.

### ISSUE THREAD

**Issue by pearson-lucas-dev** [atom/atom#6271]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.13.0-48-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Definition for rule 'no-multiple-empty-lines' was not found.

```
At /usr/share/atom/resources/app/src/pane.js:784

Error: Definition for rule 'no-multiple-empty-lines' was not found.
  at /home/lpearson/.atom/packages/eslint/node_modules/eslint/lib/eslint.js:323:27
  at Array.forEach (native)
  at EventEmitter.module.exports.api.verify (/home/lpearson/.atom/packages/eslint/node_modules/eslint/lib/eslint.js:297:16)
  at ESLintGutterView.module.exports.ESLintGutterView.lint (/home/lpearson/.atom/packages/eslint/lib/eslint-gutter-view.coffee:40:24)
  at /home/lpearson/.atom/packages/eslint/lib/eslint-gutter-view.coffee:1:1
  at TextBuffer.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:977:19)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app/src/text-editor.js:621:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:542:18)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app/src/pane.js:525:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app/src/workspace.js:689:35)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:246:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -5:10.9 core:backspace (atom-text-editor.editor.is-focused)
     -5:09.8 core:move-right (atom-text-editor.editor.is-focused)
  9x -5:09.6 core:backspace (atom-text-editor.editor.is-focused)
     -4:50.1 core:save (atom-text-editor.editor.is-focused)
     -4:27.7 core:select-right (atom-text-editor.editor.is-focused)
     -4:27.3 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:23.9 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "fontSize": 17,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
linter-eslint, v0.5.0
regex-railroad-diagram, v0.7.3

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
This looks like an issue with [linter-eslint](https://github.com/AtomLinter/linter-eslint) - would you mind reopening this there?
