### ISSUE TITLE
Uncaught Error: /opt/atom/resources/atom.asar/browser/api/lib/dialog.js:1(function (exports, require, module, __filename, __dirname) { .exports.DEFAULT                                                              ^Unexpected token ./opt/atom/resources/atom.asar/browser/api/lib/dialog.js:1(function (exports, require, module, __filename, __dirname) { .exports.DEFAULT                                                              ^SyntaxError: Unexpected token .    at exports.runInThisContext (vm.js:75:16)    at Module._compile (module.js:458:25)    at Object.Module._extensions..js (module.js:493:10)    at Module.load (module.js:370:32)    at Function.Module._load (module.js:325:12)    at Module.require (module.js:380:17)    at EventEmitter.<anonymous> (/opt/atom/resources/atom.asar/browser/lib/rpc-server.js:128:79)    at EventEmitter.emit (events.js:119:17)    at EventEmitter.<anonymous> (/opt/atom/resources/atom.asar/browser/api/lib/web-contents.js:99:23)    at EventEmitter.emit (events.js:119:17)

### ISSUE THREAD

**Issue by ybounya** [atom/atom#6299]
[Enter steps to reproduce below:]

1. File > Save As
2. Ubuntu 14.04

**Atom Version**: 0.188.0
**System**: linux 3.13.0-46-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: /opt/atom/resources/atom.asar/browser/api/lib/dialog.js:1
(function (exports, require, module, __filename, __dirname) { .exports.DEFAULT
                                                              ^
Unexpected token .
/opt/atom/resources/atom.asar/browser/api/lib/dialog.js:1
(function (exports, require, module, __filename, __dirname) { .exports.DEFAULT
                                                              ^
SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:75:16)
    at Module._compile (module.js:458:25)
    at Object.Module._extensions..js (module.js:493:10)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/opt/atom/resources/atom.asar/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/opt/atom/resources/atom.asar/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)

```
At /opt/atom/resources/atom.asar/renderer/api/lib/remote.js:77

Error: /opt/atom/resources/atom.asar/browser/api/lib/dialog.js:1
(function (exports, require, module, __filename, __dirname) { .exports.DEFAULT
                                                              ^
Unexpected token .
/opt/atom/resources/atom.asar/browser/api/lib/dialog.js:1
(function (exports, require, module, __filename, __dirname) { .exports.DEFAULT
                                                              ^
SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:75:16)
    at Module._compile (module.js:458:25)
    at Object.Module._extensions..js (module.js:493:10)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/opt/atom/resources/atom.asar/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/opt/atom/resources/atom.asar/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)
    at metaToValue (/opt/atom/resources/atom.asar/renderer/api/lib/remote.js:77:15)
    at Object.exports.require (/opt/atom/resources/atom.asar/renderer/api/lib/remote.js:157:34)
    at Atom.module.exports.Atom.showSaveDialogSync (/opt/atom/resources/app/src/atom.js:846:23)
    at Pane.module.exports.Pane.saveItemAs (/opt/atom/resources/app/src/pane.js:572:26)
    at Pane.module.exports.Pane.saveActiveItemAs (/opt/atom/resources/app/src/pane.js:541:19)
    at Workspace.module.exports.Workspace.saveActivePaneItemAs (/opt/atom/resources/app/src/workspace.js:691:35)
    at atom-workspace.atom.commands.add.core:save-as (/opt/atom/resources/app/src/workspace-element.js:298:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:242:29)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app/src/command-registry.js:157:19)
```

### Commands

```
     -0:00.4 core:save-as (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true
  },
  "editor": {
    "invisibles": {},
    "softWrap": true,
    "fontSize": 18
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by ybounya** [comment]
Probable duplicate of :  Error thrown when trying to close an untitled tab [Ubuntu 14.04] #128

**Comment by ybounya** [comment]
Duplicate of #6276
