### ISSUE TITLE
Uncaught Error: read EBADF

### ISSUE THREAD

**Issue by nshimada** [atom/atom#6301]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: read EBADF

```
At events.js:141

Error: read EBADF
  at exports._errnoException (util.js:734:11)
  at Pipe.onread (net.js:538:26)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 13,
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrapHangingIndent": 4
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
atom-lint, v0.20.1
atom-runner, v2.3.0
autocomplete-plus, v2.8.0
autocomplete-snippets, v1.2.0
file-icons, v1.5.3
highlight-column, v0.3.2
highlight-line, v0.10.1
minimap, v4.7.5
project-manager, v1.15.5
regex-railroad-diagram, v0.7.4
script, v2.18.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/atom/notifications/pull/62
