### ISSUE TITLE
Uncaught TypeError: Not a string or buffer

### ISSUE THREAD

**Issue by kenetik** [atom/atom#6321]
Attempted to copy and paste:
--
»
--

**Atom Version**: 0.187.0
**System**: linux 3.19.3-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Not a string or buffer

```
At /usr/share/atom/resources/app/node_modules/text-buffer/lib/history.js:124

TypeError: Not a string or buffer
  at TypeError (native)
  at Hash.update (crypto.js:120:16)
  at Clipboard.module.exports.Clipboard.md5 (/usr/share/atom/resources/app/src/clipboard.js:16:39)
  at Clipboard.module.exports.Clipboard.readWithMetadata (/usr/share/atom/resources/app/src/clipboard.js:32:46)
  at TextEditor.module.exports.TextEditor.pasteText (/usr/share/atom/resources/app/src/text-editor.js:2547:30)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.core:paste (/usr/share/atom/resources/app/src/text-editor-element.js:428:19)
  at /usr/share/atom/resources/app/src/text-editor-element.js:299:34
  at History.module.exports.History.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1215:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/usr/share/atom/resources/app/src/text-editor-element.js:298:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:246:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:42.9 core:delete (atom-text-editor.editor.is-focused)
     -0:42.1 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:41.7 editor:newline (atom-text-editor.editor.is-focused)
     -0:41.3 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:41.3 snippets:expand (atom-text-editor.editor.is-focused)
     -0:41.3 editor:indent (atom-text-editor.editor.is-focused)
     -0:40.9 core:paste (atom-text-editor.editor.is-focused)
     -0:39.9 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:39.9 snippets:expand (atom-text-editor.editor.is-focused)
     -0:39.9 editor:indent (atom-text-editor.editor.is-focused)
     -0:39.4 core:backspace (atom-text-editor.editor.is-focused)
     -0:15.2 core:select-left (atom-text-editor.editor.is-focused)
     -0:14.8 core:paste (atom-text-editor.editor.is-focused)
  3x -0:01.6 core:move-up (atom-text-editor.editor.is-focused)
     -0:00.8 core:select-left (atom-text-editor.editor.is-focused)
     -0:00.5 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview",
      "markdown-preview-plus",
      "language-mustache",
      "background-tips",
      "dev-live-reload",
      "exception-reporting",
      "feedback",
      "image-view",
      "welcome",
      "release-notes",
      "metrics"
    ],
    "autoHideMenuBar": true,
    "audioBeep": false
  },
  "editor": {
    "invisibles": {},
    "fontSize": 12,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.9.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hmm, I can't reproduce this on the latest master.  Could you first try to upgrade to 0.190.0, and if that doesn't fix it, then trying to start Atom in safe mode (`atom --safe`)?  Thanks.

**Comment by kenetik** [comment]
@50Wliu Seems that this may have been a fluke, as I am not able to replicate at this time either. Thanks for the quick reply.
