### ISSUE TITLE
Failed to activate the gulp-control package

### ISSUE THREAD

**Issue by Zoltu** [atom/atom#6350]
[Enter steps to reproduce below:]

1. `set ATOM_HOME=%APPDATA%\Atom`
1. `%LOCALAPPDATA%\atom\bin\apm link --dev`
1. Launch Atom (start screen).
1. Open in dev mode > checked out repo. (this appears to not actually open in dev but instead just open in current window)
1. Repeat previous step (second pass launches a dev window).
1. Packages > gulp-control > open

**Atom Version**: 0.190.0
**System**: Microsoft Windows 8.1 Enterprise N
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the gulp-control package

```
At Cannot find module 'ansi-to-html'

Error: Cannot find module 'ansi-to-html'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\Micah\AppData\Local\atom\app-0.190.0\resources\app\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Micah\Source\atom-gulp-control\lib\gulp-control-view.coffee:6:11)
  at Object.<anonymous> (C:\Users\Micah\Source\atom-gulp-control\lib\gulp-control-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Micah\AppData\Local\atom\app-0.190.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Micah\Source\atom-gulp-control\lib\gulp-control.coffee:1:19)
  at Object.<anonymous> (C:\Users\Micah\Source\atom-gulp-control\lib\gulp-control.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Micah\AppData\Local\atom\app-0.190.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Micah\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:665:34)
  at Package.module.exports.Package.activateConfig (C:\Users\Micah\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:242:12)
  at Package.module.exports.Package.activateNow (C:\Users\Micah\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:221:14)
  at C:\Users\Micah\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:728:25
  at Emitter.module.exports.Emitter.emit (C:\Users\Micah\AppData\Local\atom\app-0.190.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Micah\AppData\Local\atom\app-0.190.0\resources\app\src\command-registry.js:223:20)
  at CommandRegistry.handleCommandEvent (C:\Users\Micah\AppData\Local\atom\app-0.190.0\resources\app\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Micah\AppData\Local\atom\app-0.190.0\resources\app\src\command-registry.js:157:19)
  at EventEmitter.<anonymous> (C:\Users\Micah\AppData\Local\atom\app-0.190.0\resources\app\src\window-event-handler.js:73:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:03.5 gulp-control:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "monokai-light"
    ],
    "disabledPackages": [
      "wrap-guide"
    ],
    "ignoredNames": [
      ".idea"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "softTabs": false
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v2.14.5
autocomplete-plus, v2.9.0
autohide-tree-view, v0.16.5
linter, v0.12.0
monokai-light, v0.3.6

# Dev
gulp-control, v0.3.3
```

**Comment by thomasjo** [comment]
Did you remember to run `apm install` from the repo's root directory?

**Comment by Zoltu** [comment]
Ah, no.  I was reading an outdated version of https://atom.io/docs/v0.186.0/contributing-to-packages.
