### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/sakaeda11/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee'

### ISSUE THREAD

**Issue by sakaeda11** [atom/atom#6353]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/sakaeda11/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee'

```
At /Users/sakaeda11/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:126

Error: ENOENT, no such file or directory '/Users/sakaeda11/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:362:29)
  at Object.exports._compileFile (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:206:14)
  at getSourceMap (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:314:22)
  at getSourceMapping (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:322:19)
  at formatSourcePosition (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:274:16)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:340:34
  at Function.Error.prepareStackTrace (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:343:7)
  at trackRejection (/Users/sakaeda11/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:988:32)
  at reject (/Users/sakaeda11/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:1044:5)
  at _fulfilled (/Users/sakaeda11/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:789:20)
  at self.promiseDispatch.done (/Users/sakaeda11/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Users/sakaeda11/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:749:13)
  at /Users/sakaeda11/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:557:44
  at flush (/Users/sakaeda11/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:366:11)

```

### Commands

```
     -3:27.9 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -2:07.6 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
  2x -1:31.6 core:backspace (atom-text-editor.editor.mini)
     -1:29.2 editor:select-to-first-character-of-line (atom-text-editor.editor.mini)
     -1:28.6 core:copy (atom-text-editor.editor.mini)
     -1:28.4 core:move-right (atom-text-editor.editor.mini)
     -1:24.4 core:paste (atom-text-editor.editor.mini)
     -0:13.7 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v0.22.11
file-icons, v1.4.2
japanese-wrap, v0.2.1

# Dev
No dev packages
```

**Comment by benogle** [comment]
Can you provide steps to reproduce this? When did it happen? Upgrading the package? On load of atom? something else?

Looks like maybe an issue with atom-color-highlight, but not sure.
