### ISSUE TITLE
Uncaught Error: 'colors.less' wasn't found

### ISSUE THREAD

**Issue by iainn** [atom/atom#6356]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: 'colors.less' wasn't found

```
At /Applications/Atom 2.app/Contents/Resources/app/src/theme-manager.js:329

Error
    at new Parser (/Applications/Atom 2.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
    at LessCache.module.exports.LessCache.parseLess (/Applications/Atom 2.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:244:16)
    at LessCache.module.exports.LessCache.cssForFile (/Applications/Atom 2.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:275:20)
    at LessCompileCache.module.exports.LessCompileCache.cssForFile (/Applications/Atom 2.app/Contents/Resources/app/src/less-compile-cache.js:40:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Applications/Atom 2.app/Contents/Resources/app/src/theme-manager.js:308:33)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Applications/Atom 2.app/Contents/Resources/app/src/theme-manager.js:286:21)
    at /Applications/Atom 2.app/Contents/Resources/app/src/package.js:427:45
    at Array.map (native)
    at ThemePackage.module.exports.Package.loadStylesheets (/Applications/Atom 2.app/Contents/Resources/app/src/package.js:426:59)
    at /Applications/Atom 2.app/Contents/Resources/app/src/theme-package.js:55:17
```

### Commands

```
     -0:32.6 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
behat-atom, v0.1.2
cucumber, v0.5.0
language-gherkin, v1.0.1
monokai, v0.14.0
syntax-settings, v0.7.1

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report, @iainn. Can you share some steps to reproduce this and try reproducing in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

I'm guessing that you were using the monokai theme (listed in your installed packages) and some other package which is importing "colors". However, the monokai theme doesn't have a colors.less file, so my guess is that the import is failing for that reason. If that's true, then this doesn't sound like a problem in Atom, but it would be great if the notification you get was more helpful and pointed you to the package which is causing this. 

@kevinsawicki could we make these exceptions more helpful and point to the package?
