### ISSUE TITLE
Problems building Atom on Windows on latest master (98d3646)

### ISSUE THREAD

**Issue by izuzak** [atom/atom#6436]
Tried building Atom on Windows (8.1) after a long time and ran into some problems with the latest master version (98d3646).

```
C:\atom [master]> script/build
Node: v0.12.2
npm: v2.7.4
Python: v2.7.7
Installing build modules...
Installing apm...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\atom\build\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\atom\\build\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\atom\apm\node_modules\atom-package-manager\node_modules\asar-require\node_modules\asar\node_modules\chromium-pickle
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\atom\\build\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\atom\\build\\.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
npm ERR! node v0.12.2
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! chromium-pickle@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromium-pickle@0.1.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the chromium-pickle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls chromium-pickle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\atom\apm\npm-debug.log
```

Since that doesn't really tell me why `node-gyp rebuild` bailed, I ran the command manually in that directory:

```
C:\atom\apm\node_modules\atom-package-manager\node_modules\asar-require\node_modules\asar\node_modules\chromium-pickle [master]> node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.12.2 | win32 | x64
gyp info spawn python
gyp info spawn args [ 'C:\\Users\\izuzak\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\atom\\apm\\node_modules\\atom-package-manager\\node_modules\\asar-require\\node_modules\\asar\\node_modules\\chromium-pickle\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\izuzak\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\izuzak\\.node-gyp\\0.12.2\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\izuzak\\.node-gyp\\0.12.2',
gyp info spawn args   '-Dmodule_root_dir=C:\\atom\\apm\\node_modules\\atom-package-manager\\node_modules\\asar-require\\node_modules\\asar\\node_modules\\chromium-pickle',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\atom\\apm\\node_modules\\atom-package-manager\\node_modules\\asar-require\\node_modules\\asar\\node_modules\\chromium-pickle\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Missing input files:
C:\atom\apm\node_modules\atom-package-manager\node_modules\asar-require\node_modules\asar\node_modules\chromium-pickle\node_modules\native-mate\tests\compilation.cc
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  dynamic_annotations.c src\base\third_party\dynamic_annotations\dynamic_annotations.c(38): fatal error C1081: 'c:\atom\apm\node_modules\atom-package-manager\node_modules\asar-require\node_modules\asar\node_modules\chromium-pickle\node_modules\native-mate\vendor\base-minimal\src\base\third_party\dynamic_annotations\base\third_party\dynamic_annotations\dynamic_annotations.h': file name too long [C:\atom\apm\node_modules\atom-package-manager\node_modules\asar-require\node_modules\asar\node_modules\chromium-pickle\node_modules\native-mate\vendor\base-minimal\base.vcxproj] native_mate.vcxproj -> C:\atom\apm\node_modules\atom-package-manager\node_modules\asar-require\node_modules\asar\node_modules\chromium-pickle\build\Release\\native_mate.lib
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\izuzak\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\izuzak\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\atom\apm\node_modules\atom-package-manager\node_modules\asar-require\node_modules\asar\node_modules\chromium-pickle
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
```

Notice the path which is reported as too long:

```
c:\atom\apm\node_modules\atom-package-manager\node_modules\asar-require\node_modules\asar\node_modules\chromium-pickle\node_modules\native-mate\vendor\base-minimal\src\base\third_party\dynamic_annotations\base\third_party\dynamic_annotations\dynamic_annotations.h
```

That path is over 264 characters long = too long. I see the same error if I open base-minimal project in VS Studio Express and trigger a build.

I tried building an older version of Atom (e.g. Atom 0.192.0), and that took me past building apm and past installing packages, all the way to [this error](https://github.com/atom/atom/issues/6415). But that's another problem, and makes me believe this problem was introduced after 0.192.0. Also, I just tried cloning https://github.com/atom/node-chromium-pickle to a folder closer to the root and running `npm install` in that folder and that worked just fine -- no long file name problems.

Anyone else seeing the problem above when building the latest master on Windows?  /cc @kevinsawicki @zcbenz @paulcbetts Perhaps somehow related to https://github.com/atom/atom/pull/6313?

Possible cause of problems: that path above which is reported as too long looks very suspicious as well. Notice the duplicated `base\third_party\dynamic_annotations` part in the path near the end. As far as I can tell, that's happening [here](https://github.com/zcbenz/base-minimal/blob/383005fc9673e8f603cffc7ae653a74d160f9d07/src/base/third_party/dynamic_annotations/dynamic_annotations.c#L38). Notice that `dynamic_annotations.h` and `dynamic_annotations.c` are actually in the same folder. After I changed that line from:

```
#include "base/third_party/dynamic_annotations/dynamic_annotations.h"
```

to

```
#include "dynamic_annotations.h"
```

I was able to build chromium-pickle without the long file name problems.

**Comment by kevinsawicki** [comment]
> Anyone else seeing the problem above when building the latest master on Windows?

I haven't seen this and I also haven't seen this failure on CI

**Comment by zcbenz** [comment]
Fixed by https://github.com/atom/asar/pull/28.

**Comment by izuzak** [comment]
Thanks so much for fixing this, @zcbenz :crown: :zap:!
