### ISSUE TITLE
Uncaught Error: ENOENT, keymaps/darwin.json not found in /Users/holdicon/Downloads/Atom.app/Contents/Resources/app.asar

### ISSUE THREAD

**Issue by holdicon** [atom/atom#6511]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, keymaps/darwin.json not found in /Users/holdicon/Downloads/Atom.app/Contents/Resources/app.asar

```
At /Users/holdicon/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:457

Error: ENOENT, keymaps/darwin.json not found in /Users/holdicon/Downloads/Atom.app/Contents/Resources/app.asar
    at createNotFoundError (ATOM_SHELL_ASAR.js:101:13)
    at Object.module.(anonymous function) [as open] (ATOM_SHELL_ASAR.js:156:25)
    at ReadStream.open (fs.js:1668:6)
    at new ReadStream (fs.js:1655:10)
    at Object.fs.createReadStream (fs.js:1610:10)
    at File.module.exports.File.read (/Users/holdicon/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:286:27)
    at TextBuffer.module.exports.TextBuffer.updateCachedDiskContents (/Users/holdicon/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:948:61)
    at TextBuffer.module.exports.TextBuffer.load (/Users/holdicon/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:974:19)
    at Project.module.exports.Project.buildBuffer (/Users/holdicon/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:446:21)
    at Project.module.exports.Project.bufferForPath (/Users/holdicon/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:416:63)
```

### Commands

```
     -2:01.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-yosemite-unity-ui)
     -1:52.9.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-yosemite-unity-ui)
     -0:39.9.0 auto-update-packages:update-now (atom-text-editor.editor.vim-mode.command-mode)
     -0:32.4.0 key-binding-resolver:toggle (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:29.6.0 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:23.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  5x -0:18.9.0 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:09.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "package-that-throws-an-exception",
      "package-with-broken-package-json",
      "package-with-broken-keymap",
      "language-java",
      "debugger",
      "debugger"
    ],
    "themes": [
      "yosemite-unity-ui",
      "solarized-dark-syntax"
    ],
    "destroyEmptyPanes": false
  },
  "editor": {
    "fontFamily": "Courier",
    "useShadowDOM": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
auto-update-packages, v0.2.2
autocomplete-plus, v2.12.0
color-picker, v1.7.0
emmet, v2.3.8
language-javascript-semantic, v0.1.0
up2date, v0.0.7
vim-mode, v0.44.0
web-view, v0.3.0
yosemite-unity-ui, v0.3.13

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
Did you previously have the `keymaps/darwin.json` open in the editor?

**Comment by kevinsawicki** [comment]
@zcbenz Should this kind of error be emitted as an `error` event on the stream instead of explicitly thrown?

**Comment by zcbenz** [comment]
@kevinsawicki It has been fixed in https://github.com/atom/electron/pull/1453.
