### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'    at Function.Module._resolveFilename (module.js:328:15)    at Function.Module._load (module.js:270:25)    at Module.require (module.js:357:17)    at require (module.js:376:17)    at BrowserWindow.<anonymous> (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\app.asar\src\browser\atom-window.js:152:27)    at emitOne (events.js:77:13)    at BrowserWindow.emit (events.js:166:7)    at callFunction (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)    at EventEmitter.<anonymous> (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)    at emitMany (events.js:108:13)

### ISSUE THREAD

**Issue by josefc** [atom/atom#6516]
[Enter steps to reproduce below:]

1. Right click on file or folder in the side menu

**Atom Version**: 0.194.0
**System**: Microsoft Windows 10 Pro Technical Preview
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
    at metaToValue (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\app.asar\src\context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\app.asar\src\window-event-handler.js:149:33)
    at HTMLDocument.handler (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\app.asar\src\space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
    at HTMLDocument.elemData.handle (C:\Users\Josef\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
color-picker, v1.7.0
minimap, v4.7.6

# Dev
No dev packages
```

**Comment by josefc** [comment]
Didn't realise this already existed. #6514
