### ISSUE TITLE
Package search fails

### ISSUE THREAD

**Issue by pyrokinetiq** [atom/atom#6525]
Running Atom `0.194.0` on OpenSUSE 13.2, when I go to the "Install +" page of the settings panel, I get the following error:

````
/usr/share/atom/resources/app/apm/node_modules/asar-require/node_modules/asar/node_modules/chromium-pickle/node_modules/bindings/bindings.js:83

        throw e
              ^

Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/share/atom/resources/app/apm/node_modules/asar-require/node_modules/asar/node_modules/chromium-pickle/build/Release/pickle.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/share/atom/resources/app/apm/node_modules/asar-require/node_modules/asar/node_modules/chromium-pickle/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/asar-require/node_modules/asar/node_modules/chromium-pickle/lib/main.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```` 

This occurs on every attempt to search for a package, as well as when Atom attempts to retrieve featured packages:

http://i.imgur.com/nzEpMcw.png

**Comment by pyrokinetiq** [comment]
Duplicate of #6465
