### ISSUE TITLE
Failed to load the remote-debug package

### ISSUE THREAD

**Issue by rossross** [atom/atom#6534]
[Enter steps to reproduce below:]

1. Reference chrome-debug-protocol definition file
2. Restart and watch the above exception

**Atom Version**: 0.194.0
**System**: Microsoft Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Failed to load the remote-debug package

```
At L1: Declaration or statement expected.
L1: Expression expected.
L1: ';' expected.
L1: ';' expected.
L1: ';' expected.

Error: L1: Declaration or statement expected.
L1: Expression expected.
L1: ';' expected.
L1: ';' expected.
L1: ';' expected.
    at TypeScriptSimple.toJavaScript (C:\Users\Andrew\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\typescript-simple\index.js:118:23)
    at TypeScriptSimple.compile (C:\Users\Andrew\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\typescript-simple\index.js:50:25)
    at transpile (C:\Users\Andrew\AppData\Local\atom\app-0.194.0\resources\app.asar\src\typescript.js:86:14)
    at Object.loadFile [as .ts] (C:\Users\Andrew\AppData\Local\atom\app-0.194.0\resources\app.asar\src\typescript.js:98:67)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\Andrew\AppData\Local\atom\app-0.194.0\resources\app.asar\src\package.js:677:34)
    at C:\Users\Andrew\AppData\Local\atom\app-0.194.0\resources\app.asar\src\package.js:170:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.0
color-picker, v1.7.0
file-icons, v1.5.4
linter, v0.12.1
remote-debug, v0.0.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
This is a problem with the remote-debug package. Please open an issue on its repo.
