### ISSUE TITLE
Failed to activate the lorem-ipsum package

### ISSUE THREAD

**Issue by jeffdupont** [atom/atom#6541]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the lorem-ipsum package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/dupont/Dropbox/Application%20Data/atom/packages/lorem-ipsum/lib/index.coffee:16:32)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "space-tab",
      "linter-php",
      "linter-jshint",
      "linter"
    ]
  },
  "editor": {
    "softWrap": true,
    "invisibles": {},
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.0
atom-color-highlight, v3.0.9
autocomplete-plus, v2.12.0
color-picker, v1.7.0
emmet, v2.3.8
language-blade, v0.13.0
language-ejs, v0.1.0
language-nginx, v0.5.2
language-smarty-php, v0.5.0
lorem-ipsum, v0.4.0
open-last-project, v0.4.1
recent-files, v0.3.0
travis-ci-status, v0.13.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
This is an issue with the [lorem-ipsum](https://github.com/nickclaw/atom-lorem-ipsum) package - would you mind reopening this there?
