### ISSUE TITLE
Fatal X11 error with indirect rendering

### ISSUE THREAD

**Issue by rpavlik** [atom/atom#6583]
Using the latest (0.194.0) on Debian Jessie, though this has been around since the 180s at least.

General system setup:
- Host machine: Win 8.1
  - Cygwin X server, listening on TCP to allow direct connections on internal (vm-only) interface
- VirtualBox VM running Debian Jessie
  - Has `DISPLAY` set to the host machine's `:0.0` so I can X, multi-window, without the overhead of ssh on my local machine.

Initial situation:
Cygwin X release 1.17ish, has default `-iglx` flag disabling indirect GL. Chromium doesn't run, and neither does Atom.
Install the mesa SW rasterizer on the VM (as error message mentioning swrast seemed to suggest), no change.

Now:
Noticed in Cygwin X release notes the point about indirect GLX being disabled by default, so I add `+iglx` to my X server startup and swap swrast for the glx package in the VM. glxinfo properly shows:

```
ryan@jessie:~$ glxinfo |grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 635/PCIe/SSE2
OpenGL version string: 1.4 (4.5.0 NVIDIA 347.52)
OpenGL extensions:
```

as Cygwin docs suggest it should.

No environment variable changes (only `DISPLAY` set): Chromium starts and works, though prints an error to the console. Atom fails to load.

```
ryan@jessie:~$ chromium
ATTENTION: default value of option force_s3tc_enable overridden by environment.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[6990:6990:0430/145105:ERROR:gl_context_glx.cc(107)] Couldn't make context current with X drawable.
[6990:6990:0430/145105:ERROR:gpu_info_collector.cc(46)] gfx::GLContext::MakeCurrent() failed
[6990:6990:0430/145105:ERROR:gpu_info_collector.cc(95)] Could not create context for info collection.
[6990:6990:0430/145105:ERROR:gpu_main.cc(410)] gpu::CollectGraphicsInfo failed (fatal).
[6990:6990:0430/145105:ERROR:gpu_child_thread.cc(146)] Exiting GPU process due to errors during initialization


ryan@jessie:~$ atom 
ryan@jessie:~$ [7114:0430/145239:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[7114:0430/145239:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused
App load time: 128ms
ATTENTION: default value of option force_s3tc_enable overridden by environment.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[7138:0430/145239:ERROR:gl_context_glx.cc(107)] Couldn't make context current with X drawable.
[7138:0430/145239:ERROR:gpu_info_collector.cc(46)] gfx::GLContext::MakeCurrent() failed
[7138:0430/145239:ERROR:gpu_info_collector.cc(95)] Could not create context for info collection.
[7138:0430/145239:ERROR:gpu_main.cc(410)] gpu::CollectGraphicsInfo failed (fatal).
[7138:0430/145239:WARNING:x11_util.cc(1490)] X error received: serial 61, error_code 151 (GLXBadContext), request_code 149, minor_code 5 (X_GLXMakeCurrent)
[7138:0430/145239:WARNING:x11_util.cc(1490)] X error received: serial 61, error_code 0 (0), request_code 149, minor_code 26 (X_GLXMakeContextCurrent)
[7138:0430/145240:ERROR:gpu_child_thread.cc(146)] Exiting GPU process due to errors during initialization
[7150:0430/145240:INFO:renderer_main.cc(212)] Renderer process started
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 282 error_code 2 request_code 12 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

ryan@jessie:~$ atom -w
[7319:0430/145401:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[7319:0430/145401:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused
App load time: 95ms
ATTENTION: default value of option force_s3tc_enable overridden by environment.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[7343:0430/145401:ERROR:gl_context_glx.cc(107)] Couldn't make context current with X drawable.
[7343:0430/145401:ERROR:gpu_info_collector.cc(46)] gfx::GLContext::MakeCurrent() failed
[7343:0430/145401:ERROR:gpu_info_collector.cc(95)] Could not create context for info collection.
[7343:0430/145401:ERROR:gpu_main.cc(410)] gpu::CollectGraphicsInfo failed (fatal).
[7343:0430/145401:WARNING:x11_util.cc(1490)] X error received: serial 61, error_code 151 (GLXBadContext), request_code 149, minor_code 5 (X_GLXMakeCurrent)
[7343:0430/145401:WARNING:x11_util.cc(1490)] X error received: serial 61, error_code 0 (0), request_code 149, minor_code 26 (X_GLXMakeContextCurrent)
[7343:0430/145401:ERROR:gpu_child_thread.cc(146)] Exiting GPU process due to errors during initialization
[7356:0430/145402:INFO:renderer_main.cc(212)] Renderer process started
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 282 error_code 2 request_code 12 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

```

However, after running `export LIBGL_ALWAYS_INDIRECT=1` in the terminal, I get these results. Chromium again starts and works fine. (of course, `about:gpu` indicates that hardware rendering is unavailable since the GPU process crashed) Atom again fails to start. (In both this case and the previous one, using the `-w` switch prevented backgrounding of the process, but the error doesn't actually exit the program - still shows up on a `ps -a`, have to `ctrl-c`)

```
ryan@jessie:~$ export LIBGL_ALWAYS_INDIRECT=1
ryan@jessie:~$ chromium
[7466:7466:0430/145510:ERROR:gl_context_glx.cc(107)] Couldn't make context current with X drawable.
[7466:7466:0430/145510:ERROR:gpu_info_collector.cc(46)] gfx::GLContext::MakeCurrent() failed
[7466:7466:0430/145510:ERROR:gpu_info_collector.cc(95)] Could not create context for info collection.
[7466:7466:0430/145510:ERROR:gpu_main.cc(410)] gpu::CollectGraphicsInfo failed (fatal).
[7466:7466:0430/145510:ERROR:gpu_child_thread.cc(146)] Exiting GPU process due to errors during initialization

ryan@jessie:~$ atom -w
[7692:0430/145655:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[7692:0430/145655:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused
App load time: 111ms
[7717:0430/145655:ERROR:gl_context_glx.cc(107)] Couldn't make context current with X drawable.
[7717:0430/145655:ERROR:gpu_info_collector.cc(46)] gfx::GLContext::MakeCurrent() failed
[7717:0430/145655:ERROR:gpu_info_collector.cc(95)] Could not create context for info collection.
[7717:0430/145655:ERROR:gpu_main.cc(410)] gpu::CollectGraphicsInfo failed (fatal).
[7717:0430/145655:WARNING:x11_util.cc(1490)] X error received: serial 54, error_code 151 (GLXBadContext), request_code 149, minor_code 5 (X_GLXMakeCurrent)
[7717:0430/145655:WARNING:x11_util.cc(1490)] X error received: serial 54, error_code 0 (0), request_code 149, minor_code 26 (X_GLXMakeContextCurrent)
[7717:0430/145656:ERROR:gpu_child_thread.cc(146)] Exiting GPU process due to errors during initialization
[7725:0430/145656:INFO:renderer_main.cc(212)] Renderer process started
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 282 error_code 2 request_code 12 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

I suspect this might actually be an Electron bug, rather than Atom itself, but I did not have time to test with just Electron and a dummy app. However, the summary is: Cygwin X doesn't appear good enough for Chromium's GPU process, yet Chromium manages to finish starting and work, while Atom gets additional error messages and fails to display an interface.

**Comment by rpavlik** [comment]
Plot thickens: `--disable-gpu` does actually do something - doesn't try to start the ill-fated GPU process, but still fails:

```
ryan@jessie:~/.atom$ LIBGL_DEBUG=verbose atom -w --disable-gpu
[9087:0430/151702:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[9087:0430/151702:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused
App load time: 101ms
[9115:0430/151702:INFO:renderer_main.cc(212)] Renderer process started
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 282 error_code 2 request_code 12 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by rpavlik** [comment]
Got a backtrace from `gdk_x_error`:

```
ryan@jessie:~$ gdb --args /usr/share/atom/atom --sync
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/share/atom/atom...(no debugging symbols found)...done.
(gdb) break gdk_x_error
Function "gdk_x_error" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (gdk_x_error) pending.
(gdb) r
Starting program: /usr/share/atom/atom --sync
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[9745:0430/152949:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[New Thread 0x7fffe5fdb700 (LWP 9749)]
[New Thread 0x7fffe55ce700 (LWP 9751)]
[New Thread 0x7fffe4bc0700 (LWP 9752)]
[New Thread 0x7fffe43bf700 (LWP 9754)]
[New Thread 0x7fffe3bbe700 (LWP 9755)]
[New Thread 0x7fffe30fd700 (LWP 9757)]
[New Thread 0x7fffe28fc700 (LWP 9758)]
[New Thread 0x7fffe20fb700 (LWP 9759)]
[New Thread 0x7fffe20da700 (LWP 9760)]
[New Thread 0x7fffe20b9700 (LWP 9761)]
[New Thread 0x7fffdeeb1700 (LWP 9762)]
[9745:0430/152949:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused
[Thread 0x7fffe20b9700 (LWP 9761) exited]
[Thread 0x7fffdeeb1700 (LWP 9762) exited]
[New Thread 0x7fffdeeb1700 (LWP 9763)]
[New Thread 0x7fffe20b9700 (LWP 9764)]
[New Thread 0x7fffde6b0700 (LWP 9765)]
[New Thread 0x7fffddeaf700 (LWP 9766)]
[New Thread 0x7fffdd6ae700 (LWP 9767)]
[New Thread 0x7fffdcead700 (LWP 9768)]
[New Thread 0x7fffdc6ac700 (LWP 9769)]
[New Thread 0x7fffdbeab700 (LWP 9770)]
[New Thread 0x7fffdb6aa700 (LWP 9771)]
App load time: 228ms
[New Thread 0x7fffdac9a700 (LWP 9774)]
[New Thread 0x7fffda499700 (LWP 9775)]
[New Thread 0x7fffd9c98700 (LWP 9776)]

Breakpoint 1, gdk_x_error (display=0x2f677d720800, error=0x7fffffffdfa0) at /build/gtk+2.0-czQfyJ/gtk+2.0-2.24.25/gdk/x11/gdkmain-x11.c:458
458	/build/gtk+2.0-czQfyJ/gtk+2.0-2.24.25/gdk/x11/gdkmain-x11.c: No such file or directory.
(gdb) bt
#0  gdk_x_error (display=0x2f677d720800, error=0x7fffffffdfa0) at /build/gtk+2.0-czQfyJ/gtk+2.0-2.24.25/gdk/x11/gdkmain-x11.c:458
#1  0x00007ffff04e345d in _XError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#2  0x00007ffff04e03c7 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#3  0x00007ffff04e0485 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#4  0x00007ffff04e0e35 in _XEventsQueued () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007ffff04d2777 in XPending () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#6  0x00007fffefb8b8c1 in g_main_context_check (context=context@entry=0x2f677d602900, max_priority=2147483647, fds=fds@entry=0x2f677d856380, n_fds=n_fds@entry=4) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3622
#7  0x00007fffefb8be83 in g_main_context_iterate (context=context@entry=0x2f677d602900, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3778
#8  0x00007fffefb8bffc in g_main_context_iteration (context=0x2f677d602900, may_block=1) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3842
#9  0x00007ffff4004752 in base::MessagePumpGlib::Run(base::MessagePump::Delegate*) () from /usr/share/atom/libchromiumcontent.so
#10 0x00007ffff406beb0 in base::RunLoop::Run() () from /usr/share/atom/libchromiumcontent.so
#11 0x00007ffff4104fef in content::BrowserMainLoop::MainMessageLoopRun() () from /usr/share/atom/libchromiumcontent.so
#12 0x00007ffff4104f60 in content::BrowserMainLoop::RunMainMessageLoopParts() () from /usr/share/atom/libchromiumcontent.so
#13 0x00007ffff410805d in ?? () from /usr/share/atom/libchromiumcontent.so
#14 0x00007ffff4100573 in content::BrowserMain(content::MainFunctionParams const&) () from /usr/share/atom/libchromiumcontent.so
#15 0x00007ffff3ffaa15 in ?? () from /usr/share/atom/libchromiumcontent.so
#16 0x00007ffff3ff96c0 in content::ContentMain(content::ContentMainParams const&) () from /usr/share/atom/libchromiumcontent.so
#17 0x000000000066c48b in main ()
(gdb) 
```
