### ISSUE TITLE
spawn uncrustify ENOENT

### ISSUE THREAD

**Issue by frostiee22** [atom/atom#6652]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

spawn uncrustify ENOENT

```
At spawn uncrustify ENOENT

Error: spawn uncrustify ENOENT
  at exports._errnoException (util.js:734:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)

```

### Commands

```
  3x -0:55.8.0 editor:newline (atom-text-editor.editor)
     -0:50.8.0 core:move-right (atom-text-editor.editor)
     -0:49.8.0 editor:newline (atom-text-editor.editor)
  5x -0:47.3.0 core:backspace (atom-text-editor.editor)
  2x -0:36.6.0 core:move-right (atom-text-editor.editor)
  2x -0:34.8.0 editor:newline (atom-text-editor.editor)
  2x -0:26.6.0 core:move-right (atom-text-editor.editor)
     -0:25.5.0 editor:newline (atom-text-editor.editor)
     -0:17.8.0 core:save (atom-text-editor.editor)
  2x -0:17.1.0 beautify:beautify-editor (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.26.4
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by benogle** [comment]
You need to have the `uncrustify` binary installed. The error message should be more helpful. See https://github.com/Glavin001/atom-beautify/issues/311 for more details
