### ISSUE TITLE
Syntax settings error with split panes

### ISSUE THREAD

**Issue by clxe** [atom/atom#6661]
Normally, I'd report this to the [syntax-settings](https://github.com/cam-stitt/atom-syntax-settings) repo, but issues are disabled on it.

When writing Python code with panes split vertically, I get the following error whenever I save:
```
TypeError: Cannot read property 'setShowInvisibles' of null
  at TextEditorView.module.exports.TextEditorView.setShowInvisibles (C:\Users\Jacob\AppData\Local\atom\app-0.196.0\resources\app.asar\src\text-editor-view.js:360:28)
  at Object.module.exports._loopAndSetSettings (C:\Users\Jacob\.atom\packages\syntax-settings\lib\syntax-settings.coffee:83:9)
  at Object.module.exports._setSyntaxSettings (C:\Users\Jacob\.atom\packages\syntax-settings\lib\syntax-settings.coffee:72:6)
  at Object.module.exports._loadSettingsForEditorView (C:\Users\Jacob\.atom\packages\syntax-settings\lib\syntax-settings.coffee:59:8)
  at Object.<anonymous> (C:\Users\Jacob\.atom\packages\syntax-settings\lib\syntax-settings.coffee:52:10)
  at bound (C:\Users\Jacob\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\cheerio\node_modules\lodash\dist\lodash.js:729:21)
  at TextBuffer.module.exports.Emitter.emit (C:\Users\Jacob\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\emissary\lib\emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Jacob\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:921:21)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\Jacob\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:899:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\Jacob\AppData\Local\atom\app-0.196.0\resources\app.asar\src\text-editor.js:592:26)
  at Pane.module.exports.Pane.saveItem (C:\Users\Jacob\AppData\Local\atom\app-0.196.0\resources\app.asar\src\pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (C:\Users\Jacob\AppData\Local\atom\app-0.196.0\resources\app.asar\src\pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Jacob\AppData\Local\atom\app-0.196.0\resources\app.asar\src\workspace.js:585:35)
  at atom-workspace.atom.commands.add.core:save (C:\Users\Jacob\AppData\Local\atom\app-0.196.0\resources\app.asar\src\workspace-element.js:310:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Jacob\AppData\Local\atom\app-0.196.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\Jacob\AppData\Local\atom\app-0.196.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Jacob\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Jacob\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Jacob\AppData\Local\atom\app-0.196.0\resources\app.asar\src\window-event-handler.js:178:20)
```

The error doesn't seem to break anything (the file saves fine and the editor isn't visually affected), but it sure is annoying.

**Comment by mnquintana** [comment]
Why are you still using syntax-settings? This functionality was added to core a long time ago. You can scope settings out of the box, e.g.:

```cson
".python.source":
  editor:
    preferredLineLength: 90
```

You should uninstall syntax-settings and use the functionality in core.
