### ISSUE TITLE
Upgrade to 0.198.0 causing exception on package.json load

### ISSUE THREAD

**Issue by francoislaberge** [atom/atom#6693]
I'm getting the following error when loading my package right after update to ```Version 0.198.0 (0.198.0)```.

```js
Cannot read property 'getDefaultRepresentation' of undefined in /Users/francoislaberge/.atom/packages/jibo-atom/package.json

Stack Trace:

TypeError: Cannot read property 'getDefaultRepresentation' of undefined
    at Function.module.exports.Package.normalizeMetadata (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:53:17)
    at Function.module.exports.Package.loadMetadata (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:84:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:343:38)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:324:14)
    at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:620:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
  at /Users/francoislaberge/.atom/packages/jibo-atom/package.json:1:1
```

**Comment by francoislaberge** [comment]
I think this [code](https://github.com/atom/atom/blob/1d69d83410df2ba21f774f339d51b79979e1c525/src/package.coffee#L37) should also be checking if ```info``` exists:

```coffee
if info.getDefaultRepresentation() is 'shortcut'
    metadata.repository.url = info.https().replace(/^git\+/, '')
```

**Comment by izuzak** [comment]
cc @jlord I think you made some changes in that neighborhood recently?

**Comment by kevinsawicki** [comment]
Can you include the `repository` field from `/Users/francoislaberge/.atom/packages/jibo-atom/package.json` so we can add a spec for that style?

**Comment by francoislaberge** [comment]
@kevinsawicki Are you good, or did you need my package.json?

**Comment by kevinsawicki** [comment]
> Are you good, or did you need my package.json?

It would still be great to know the `repository` value still so I can gauge how widespread this problem might be and how many people it could be affecting.

**Comment by francoislaberge** [comment]
Ah. I think I have an erroneous one as it's not launched. In case it helps here's my package.json with some proprietary dependency stuff stripped out:

```json
{
  "name": "jibo-atom",
  "main": "./lib/main",
  "version": "1.0.1",
  "description": "Jibo's Robot SDK IDE Atom Packages",
  "repository": "ssh://git@git.jibo.com:7999/sdk/jibo-atom.git",
  "license": "MIT",
  "engines": {
    "atom": ">0.170.0"
  },
  "dependencies": {
    "URIjs": "^1.15.0",
    "atom-pane": "^1.0.1"
  },
  "devDependencies": {
    "gulp": "^3.8.11",
    "gulp-babel": "^4.0.1",
    "gulp-cached": "^1.0.4",
    "gulp-coffee": "^2.3.1",
    "gulp-sourcemaps": "^1.5.1",
    "gulp-watch": "^4.2.4"
  }
}
```

**Comment by kevinsawicki** [comment]
Great, thanks for providing it :+1:
