### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addMarkerAtLevel' of undefined

### ISSUE THREAD

**Issue by plafue** [atom/atom#6717]
I'm working on an [atom package](https://github.com/plafue/rust-api-docs-helper). It decorates the gutter doing the following:
``` coffeescript
    editor = atom.workspace.getActiveTextEditor()
    marker = editor.markBufferRange([[lineNr, 0], [lineNr, 0]], invalidate: 'never')
    editor.decorateMarker(marker, type : 'line-number', class : 'import-rust-logo')
```
The decoration appears as expected, but once i try to remove a line that has been decorated by that code i get the exception shown below. It seems only to happen when i select from the end of the line preceding the decorated line: 

![screen](https://cloud.githubusercontent.com/assets/1915763/7554042/33cb3712-f716-11e4-95c8-015ea9138e99.png)

I've compared my code with other projects, like git-diff, and i can't find where i do things differently (i don't have yet a "clean up" function that removes the markers when deactivating the plug in, for instance).

Thank you very much in advance

**Atom Version**: 0.198.0
**System**: linux 3.19.0-16-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'addMarkerAtLevel' of undefined

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:379

TypeError: Cannot read property 'addMarkerAtLevel' of undefined
  at IntervalSkipList.module.exports.IntervalSkipList.placeMarker (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:379:13)
  at IntervalSkipList.module.exports.IntervalSkipList.insert (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:183:12)
  at IntervalSkipList.module.exports.IntervalSkipList.update (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:207:19)
  at Marker.module.exports.Marker.updateIntervals (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:523:37)
  at Marker.module.exports.Marker.update (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:459:14)
  at MarkerManager.module.exports.MarkerManager.applySnapshot (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-manager.js:222:17)
  at Transaction.module.exports.Transaction.applyTo (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/transaction.js:73:31)
  at History.module.exports.History.abortTransaction (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/history.js:169:24)
  at History.module.exports.History.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/history.js:126:16)
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:647:27)
  at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1157:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/usr/share/atom/resources/app.asar/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at __bind (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:09.3.0 core:delete (atom-text-editor.editor.is-focused)
     -0:08.4.0 core:undo (atom-text-editor.editor.is-focused)
     -0:05.7.0 core:delete (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "one-dark-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "invisibles": {},
    "scrollPastEnd": true,
    "preferredLineLength": 120,
    "fontSize": 17
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
autocomplete-plus, v2.13.1
build, v0.30.0
coffee-refactor, v0.6.2
color-picker, v1.7.0
file-icons, v1.5.5
git-diff-details, v0.18.0
indent-guide-improved, v1.1.1
js-refactor, v0.3.0
language-jade, v0.4.0
language-puppet, v0.12.0
language-rust, v0.4.3
language-scala, v1.1.0
language-todotxt, v0.6.1
linter, v0.12.2
linter-javac, v0.1.3
linter-js-yaml, v1.0.0
linter-jshint, v0.1.4
linter-pylint, v0.2.1
linter-rust, v0.0.11
linter-scalac, v0.3.3
linter-shellcheck, v0.0.7
local-history, v3.1.0
markdown-preview, v0.148.0
markdown-preview-opener, v0.1.1
minimap, v4.8.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-selection, v4.2.0
racer, v0.10.1
refactor, v0.4.1
rust-api-docs-helper, v0.4.0
script, v2.21.0
seti-syntax, v0.4.0
subword-navigation, v2.7.0
vim-surround, v0.6.0
web-browser, v1.4.4

# Dev
No dev packages
```

**Comment by plafue** [comment]
Fail on my side. never mind :). Keep up the good work!
