### ISSUE TITLE
An error message shows up with no obvious abnormal behavior

### ISSUE THREAD

**Issue by cytsunny** [atom/atom#6834]
The following message keeps on appearing on the top right corner of atom when I am leaving my settings page. I don't sense any abnormal behavior but I guess it may be related to something at the background and you may want to know, so I copy the message using the default copy function and paste it below.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Microsoft Windows 7 Home Premium N 
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package, v0.9.3

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At C:\Users\Sunny Chan\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:25

TypeError: Cannot read property 'dispose' of undefined
  at C:\Users\Sunny Chan\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:25:28
  at Set.forEach (native)
  at CompositeDisposable.module.exports.CompositeDisposable.dispose (C:\Users\Sunny Chan\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:24:26)
  at HighlightedAreaView.module.exports.HighlightedAreaView.subscribeToActiveTextEditor (C:\Users\Sunny Chan\.atom\packages\highlight-selected\lib\highlighted-area-view.coffee:27:29)
  at C:\Users\Sunny Chan\.atom\packages\highlight-selected\lib\highlighted-area-view.coffee:13:8
  at Emitter.module.exports.Emitter.emit (C:\Users\Sunny Chan\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\Sunny Chan\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (C:\Users\Sunny Chan\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\Sunny Chan\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\Sunny Chan\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane.js:298:21)
  at tabs-tab.<anonymous> (C:\Users\Sunny Chan\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:159:24)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\Sunny Chan\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\Sunny Chan\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
  3x -2:15.6.0 core:move-left (atom-text-editor.editor.is-focused)
  9x -2:14.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:11.7.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:11.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
 14x -2:10.8.0 core:move-down (atom-text-editor.editor.is-focused)
  8x -2:03.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:00.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:59.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:03.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:04.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "wrap-guide",
      "autosave",
      "keybinding-resolver"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.9.3
language-blade, v0.14.0
open-last-project, v0.4.1
Sublime-Style-Column-Selection, v1.2.3
sync-settings, v0.2.2
tabs-to-spaces, v0.10.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
Can you reproduce this in safe mode (`atom --safe`)?

**Comment by mnquintana** [comment]
Actually, this is a `highlight-selected` issue - please reopen this issue on their repo. Thanks for the report!
