### ISSUE TITLE
Uncaught Error: connect ECONNREFUSED 127.0.0.1:1234

### ISSUE THREAD

**Issue by techverx** [atom/atom#6851]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: connect ECONNREFUSED 127.0.0.1:1234

```
At events.js:141

Error: connect ECONNREFUSED 127.0.0.1:1234
  at Object.exports._errnoException (util.js:734:11)
  at exports._exceptionWithHostPort (util.js:757:20)
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1001:14)

```

### Commands

```
  2x -1:49.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:48.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:48.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:48.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:48 core:move-right (atom-text-editor.editor.is-focused)
     -1:47.7.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -1:47.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:46.6.0 editor:newline (atom-text-editor.editor.is-focused)
  7x -1:44.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:42.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:40.8.0 project-find:show (atom-text-editor.editor.is-focused)
     -1:39.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:39.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:37.6.0 grammar-selector:show (atom-text-editor.editor)
     -1:31.7.0 encoding-selector:show (atom-text-editor.editor)
     -1:27.6.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
aligner-ruby, v1.4.0
angularjs, v0.1.0
angularjs-boilerplate-snippets, v0.3.1
angularjs-snippets, v0.10.2
angularjs-styleguide-snippets, v0.7.0
atom-angularjs, v0.1.2
atom-snippets, v0.1.1
autocomplete-ruby, v0.1.0
ruby-block, v0.3.3
ruby-debugger, v0.0.1
ruby-strftime-reference, v0.2.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
This should be fixed now by https://github.com/atom/notifications/pull/62
