### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by NKMR6194** [atom/atom#6870]
When using `markdown-pdf, v1.3.6`, atom raise it.
Is reporting plugin-repo better?

**Atom Version**: 0.200.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'call' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238

TypeError: Cannot read property 'call' of undefined
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:28)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:71:30)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
```

### Commands

```
     -0:00.8.0 markdown-pdf:convert (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-terminal",
      "language-haml",
      "web-view",
      "language-haskell",
      "language-slim",
      "japanese-wrap"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
markdown-pdf, v1.3.6

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This issue was moved to travs/markdown-pdf#54

**Comment by NKMR6194** [comment]
@50Wliu Thanks :smile:
