### ISSUE TITLE
Failed to load the find-and-replace package

### ISSUE THREAD

**Issue by searchs** [atom/atom#6887]
[Enter steps to reproduce below:]

1. Started atom via the commandline by typing 'atom'

**Atom Version**: 0.200.0
**System**: linux 3.19.0-16-generic
**Thrown From**: Atom Core

### Stack Trace

Failed to load the find-and-replace package

```
At EACCES: permission denied, open '/home/oladev/.atom/compile-cache/less/1a27b62b947a64381486d1ae700e135f52223a10/content/0ca72fa78b0f02602636d1eea2ee52e59c89b9ba/find-and-replace.json'

Error: EACCES: permission denied, open '/home/oladev/.atom/compile-cache/less/1a27b62b947a64381486d1ae700e135f52223a10/content/0ca72fa78b0f02602636d1eea2ee52e59c89b9ba/find-and-replace.json'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.fsPlus.writeFileSync (/opt/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (/opt/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:155:17)
    at LessCache.module.exports.LessCache.putCachedCss (/opt/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:225:19)
    at LessCache.module.exports.LessCache.cssForFile (/opt/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:276:12)
    at LessCompileCache.module.exports.LessCompileCache.cssForFile (/opt/atom/resources/app.asar/src/less-compile-cache.js:40:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/opt/atom/resources/app.asar/src/theme-manager.js:308:33)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "remember-session"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.13.1
autocomplete-ruby, v0.1.0
minimap, v4.8.0
ruby-block-converter, v3.5.0
seti-syntax, v0.4.0
seti-ui, v0.7.1
test-status, v0.30.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
What permissions are set on your `~/.atom` directory (and `~/.atom/compile-cache`)?

**Comment by ricardograca** [comment]
Not sure if related, but hitting `Ctrl+f` doesn't bring up the Find toolbar for me in 0.200. Used to work fine in 0.198. System is Ubuntu 15.04. The permissions are correct for those directories in my system.

**Comment by searchs** [comment]
​I think it's the permission settings on my directories that caused the
issue for me.  I ran atom with sudo (what!) - just checking if error will
indeed disappear based on trace messages and it indeed did not give any
error message.​



On 21 May 2015 at 14:43, Ricardo Graça <notifications@github.com> wrote:

> Not sure if related, but hitting Ctrl+f doesn't bring up the Find toolbar
> for me in 0.200. Used to work fine in 0.198. System is Ubuntu 15.04. The
> permissions are correct for those directories in my system.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/6887#issuecomment-104281404>.
>



-- 
Ohprice - Quick Price Comparison :  www.ohprice.com

**Comment by 50Wliu** [comment]
All right, then you might want to (recursively) change ownership of the .atom folder to your user, not root.
