### ISSUE TITLE
GLIBCXX_3.4.21 Not Found

### ISSUE THREAD

**Issue by ddamko** [atom/atom#6890]
I am running Arch Linux on kernel 4.0.2 x86_64. Trying to install v0.200.0.

```
Node: v0.12.3
npm: v2.10.0
Installing build modules...
Installing apm...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
              
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/derek/tmp/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/derek/tmp/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/home/derek/tmp/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:359:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by ardeshirj** [comment]
Are you using rpm package? 

There are couple other issues reported here #5172, #7988

**Comment by wolverine2k** [comment]
+1
