### ISSUE TITLE
Uncaught Error: ENOENT, LICENSE.md not found in C:\Users\Ian\AppData\Local\atom\app-0.201.0\resources\app.asar

### ISSUE THREAD

**Issue by iangcarroll** [atom/atom#6918]
1. Open the Command Pallet and type License
2. Select License

**Atom Version**: 0.201.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, LICENSE.md not found in C:\Users\Ian\AppData\Local\atom\app-0.201.0\resources\app.asar

```
At C:\Users\Ian\AppData\Local\atom\app-0.201.0\resources\app.asar\src\workspace.js:458

Error: ENOENT, LICENSE.md not found in C:\Users\Ian\AppData\Local\atom\app-0.201.0\resources\app.asar
    at createNotFoundError (ATOM_SHELL_ASAR.js:101:13)
    at Object.module.(anonymous function) [as open] (ATOM_SHELL_ASAR.js:156:25)
    at ReadStream.open (fs.js:1668:6)
    at new ReadStream (fs.js:1655:10)
    at Object.fs.createReadStream (fs.js:1610:10)
    at File.module.exports.File.read (C:\Users\Ian\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\pathwatcher\lib\file.js:286:27)
    at TextBuffer.module.exports.TextBuffer.updateCachedDiskContents (C:\Users\Ian\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1016:61)
    at TextBuffer.module.exports.TextBuffer.load (C:\Users\Ian\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1035:19)
    at Project.module.exports.Project.buildBuffer (C:\Users\Ian\AppData\Local\atom\app-0.201.0\resources\app.asar\src\project.js:446:21)
    at Project.module.exports.Project.bufferForPath (C:\Users\Ian\AppData\Local\atom\app-0.201.0\resources\app.asar\src\project.js:416:63)
```

### Commands

```
     -0:14.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:11.7.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:11.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
 29x -0:10.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
 15x -0:07.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:05.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.8.0 application:open-license (atom-text-editor.editor)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
remote-sync, v2.4.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
I can reproduce this using `application:open-license` on Atom 0.202.0-ec5b807 on Ubuntu 15.04.
