### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scopeName' of undefined

### ISSUE THREAD

**Issue by azerupi** [atom/atom#6926]
Hi, I get this error when I open a very specific html file:

**```Uncaught TypeError: Cannot read property 'scopeName' of undefined```**

```
/usr/share/atom/resources/app.asar/src/text-editor.js:2090

TypeError: Cannot read property 'scopeName' of undefined
  at TextEditor.module.exports.TextEditor.usesSoftTabs (/usr/share/atom/resources/app.asar/src/text-editor.js:2090:28)
  at TextEditor.module.exports.TextEditor.handleTokenization (/usr/share/atom/resources/app.asar/src/text-editor.js:2584:44)
  at /usr/share/atom/resources/app.asar/src/text-editor.js:220:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.markTokenizationComplete (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:321:22)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:312:21)
  at /usr/share/atom/resources/app.asar/src/tokenized-buffer.js:258:26
  at /usr/share/atom/resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47
```

I have disabled every community plug-in. I have multiple tabs open with several files, but this error occurs only when I switch to one specific file.

I have added the content of the file below, maybe it can help. 

```html
{% load staticfiles %}
{% load core_date_tags %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'components/fontawesome/css/font-awesome.min.css' %}" media="screen" title="no title">
    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,800,700,600,300' rel='stylesheet' type='text/css'>
    {% block extra_css %}{% endblock extra_css %}

    <title>{% block title %}Mathieu David{% endblock title %}</title>
</head>
<body>

    <div class="push-footer">

        <header>
            <nav class="navbar navbar-default">

                <div class="container-fluid">

                    <div class="navbar-name">
                        <a>
                            <span class="first-name">M<span class="closer">a</span>thieu</span>
                            <span class="last-name">D<span class="closer">a</span>vid</span>
                        </a>
                    </div>


                    <div class="navbar-social">
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-github"></i></a>
                    </div>

                    <div class="links">
                        <a href="{% url 'home' %}">Home</a>/
                        <a href="{% url 'projects' %}">Projects</a>/
                        <a>About me</a>/
                        <a>Quick Links</a>
                    </div>

                </div>
            </nav>
        </header>

        {% block content %}
        {% endblock content %}

    </div> <!-- End Push Footer -->

    <footer>
        <div class="copyright">
            © {{ "2014" | year_range }} | Mathieu David - All rights reserved
        </div>
    </footer>

    {% block extra_js %}{% endblock extra_js %}
</body>
</html>
```

**EDIT:** I forgot to mention, I am using **version 0.201.0** on Arch Linux

**Comment by azerupi** [comment]
**Update:** After reopening Atom this morning, it seems like everything is working fine. I can't reproduce the issue. I will close this issue and reopen later if necessary.
