### ISSUE TITLE
EINVAL: invalid argument after starting Atom, Atom is unsable

### ISSUE THREAD

**Issue by carstenhag** [atom/atom#6932]
![0](https://i.imgur.com/O0TZ7xk.png)

See https://imgrush.com/1A1an3GzCM6F for a video on this.

`atom 0.201.0` @ WIndows 10 TP x64

Atom 0.200.0 worked just fine yesterday.

I tried to open a file but that fails, nothing happens basically.

```
Error: EINVAL: invalid argument, read
    at Error (native)
    at Object.fs.readSync (fs.js:596:19)
    at Object.fs.readSync (C:\Users\Carsten\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\fstream\node_modules\graceful-fs\polyfills.js:218:23)
    at Object.fs.readFileSync (fs.js:433:28)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
    at File.module.exports.File.readSync (C:\Users\Carsten\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\pathwatcher\lib\file.js:248:36)
    at TextBuffer.module.exports.TextBuffer.updateCachedDiskContentsSync (C:\Users\Carsten\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1008:85)
    at TextBuffer.module.exports.TextBuffer.loadSync (C:\Users\Carsten\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1030:12)
    at Project.module.exports.Project.buildBufferSync (C:\Users\Carsten\AppData\Local\atom\app-0.201.0\resources\app.asar\src\project.js:431:14)
    at Project.module.exports.Project.bufferForPathSync (C:\Users\Carsten\AppData\Local\atom\app-0.201.0\resources\app.asar\src\project.js:407:61)index.js:62 handleSetupError
```

**Comment by mnquintana** [comment]
Can you reproduce this in safe mode? (`atom --safe`)

**Comment by Moter8** [comment]
```
Error: EINVAL: invalid argument, read
    at Error (native)
    at Object.fs.readSync (fs.js:596:19)
    at Object.fs.readFileSync (fs.js:433:28)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
    at File.module.exports.File.readSync (C:\Users\Carsten\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\pathwatcher\lib\file.js:248:36)
    at TextBuffer.module.exports.TextBuffer.updateCachedDiskContentsSync (C:\Users\Carsten\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1008:85)
    at TextBuffer.module.exports.TextBuffer.loadSync (C:\Users\Carsten\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1030:12)
    at Project.module.exports.Project.buildBufferSync (C:\Users\Carsten\AppData\Local\atom\app-0.201.0\resources\app.asar\src\project.js:431:14)
    at Project.module.exports.Project.bufferForPathSync (C:\Users\Carsten\AppData\Local\atom\app-0.201.0\resources\app.asar\src\project.js:407:61)
    at TokenizedBuffer.module.exports.TokenizedBuffer.deserializeParams (C:\Users\Carsten\AppData\Local\atom\app-0.201.0\resources\app.asar\src\tokenized-buffer.js:82:36)
```

Got that by doing atom.exe --safe.

**Comment by Moter8** [comment]
@steelbrain suggested that I rename my .atom so it starts with a fresh profile. 

Atom starts right again, not sure what this was. Not sure if I should close this?

**Comment by tarefa** [comment]
I have seen the same problem more than once on each of two PCs, one Windows 7 Pro x64 and one Windows 8.1 x32. Most recently with Atom 0.204.0. I'm still trying to find the steps to reproduce.

Deleting/renaming .atom removes installed packages and proxy settings in .apmrc but it is only a minor annoyance so far.
