### ISSUE TITLE
TypeError: Cannot read property 'loaded' of null

### ISSUE THREAD

**Issue by Moter8** [atom/atom#6933]
Started atom via `cmd`, opened some file, closed atom and got this error. Can reproduce without opening any file, just opening and closing atom.
I have to ctrl+c to return to the `cmd` prompt after this error appears.

It's not visible on the GUI at all.

```
C:\Users\Carsten\AppData\Local\atom\app-0.201.0>atom.exe --safe

C:\Users\Carsten\AppData\Local\atom\app-0.201.0>App load time: 117ms
[8532:0524/172025:INFO:renderer_main.cc(212)] Renderer process started
[4976:0524/172026:INFO:CONSOLE(52)] "Window load time: 543ms", source: file:///C:/Users/Carsten/AppData/Local/atom/app-0.201.0/resources/app.asar/static/index.js (52)
Cannot read property 'loaded' of null
TypeError: Cannot read property 'loaded' of null
    at AtomWindow.module.exports.AtomWindow.getLoadSettings (C:\Users\Carsten\AppData\Local\atom\app-0.201.0\resources\app.asar\src\browser\atom-window.js:135:41)
    at AtomApplication.module.exports.AtomApplication.saveState (C:\Users\Carsten\AppData\Local\atom\app-0.201.0\resources\app.asar\src\browser\atom-application.js:739:37)
    at BrowserWindow.<anonymous> (C:\Users\Carsten\AppData\Local\atom\app-0.201.0\resources\app.asar\src\browser\atom-application.js:188:26)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)

```

`atom 0.201.0`
Windows 10 TP x64

Happens without any community packages installed.

**Comment by izuzak** [comment]
Thanks for the report, @Moter8.

@zcbenz @kevinsawicki As far as I can tell, that's breaking [here](https://github.com/atom/atom/blob/08c4e8e0075725abbecb9042cab72c22f264c0a1/src/browser/atom-window.coffee#L90):

```coffee
getLoadSettings: ->
  if @browserWindow.webContents.loaded
    ...
```

Should `@browserWindow.webContents` ever be `null` here? I don't have Windows 10 so can't try and reproduce -- sorry.

**Comment by nopejpg** [comment]
Also applies to Ubuntu 15.04; I can reproduce by doing the following:

1. Run with `atom -f`.
2. Click X to close atom.

**Comment by izuzak** [comment]
I believe this was fixed in https://github.com/atom/atom/pull/7200. /cc @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
Yup! thanks @izuzak.
