### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by RF-Nelson** [atom/atom#6973]
I was editing files and had two tabs open for the same file, one split right.
On one of the file's tabs I started undoing a lot of changes in row holding down Command-Z.

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:475

TypeError: Cannot convert undefined or null to object
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateCursorState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:475:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1712:17
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:66:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Marker.module.exports.Marker.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:227:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:40:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:249:20)
    at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:51:25)
```
### Commands

```
 36x -1:12.4.0 core:undo (atom-text-editor.editor.is-focused)
 33x -1:07.4.0 core:redo (atom-text-editor.editor.is-focused)
undefined -0:58.8.0 core:undo (atom-text-editor.editor.is-focused)
  7x -0:24.8.0 core:redo (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "softWrap": true
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by RF-Nelson** [comment]
I had about twenty files open, split between two columns. Some of these files had tabs open to edit them in both columns. I wanted to rollback all changes in one file that was open in both columns (it was the active tab in only one of the columns). So I held down "Undo" for about ten seconds as changes were being undone before I encountered this exception.
