### ISSUE TITLE
Rebuilt atom after system update , and i am in trouble.

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#7016]
I just upgraded my sabayon linux (gentoo based)  , with GCC 4.9.2 and node 0.12.2
Then i tried to rebuild atom from clean but when i rebuild it is aborted due to warnings.
When i tried to do --force , atom binary is built but it crashes with error.

I am on https://github.com/atom/atom/commit/7c968542faccb5d09d501475c3761c0b65582950
```
./atom
[11876:0529/234211:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
A JavaScript error occured in the browser process
Uncaught Exception:
Error: Cannot find module 'camelcase'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/tmp/v3ss/atom-build/Atom/resources/app.asar/node_modules/yargs/lib/parser.js:3:17)
    at Module._compile (module.js:452:26)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
ATTENTION: default value of option force_s3tc_enable overridden by environment.
```

**Comment by v3ss0n** [comment]
i did another full rebuild by deleting eveything and now it works.
