### ISSUE TITLE
Uncaught Error: No screen line exists when converting buffer row to screen row

### ISSUE THREAD

**Issue by gnumoksha** [atom/atom#7070]
Steps:
- _Split right_ in tab
- Left tab in "read only" and right tab is on i am working
- **Ctrl + x** with 102 lines
- **Ctrl + z** launch exception. Now Ctrl+c, Ctrl+z Ctrl+Shift+z launch exception. Copy and paste in exception window does not work.

**Ctrl + c**

```
/usr/share/atom/resources/app.asar/src/display-buffer.js:1047
Hide Stack Trace
Error: No screen line exists when converting buffer row to screen row
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/usr/share/atom/resources/app.asar/src/display-buffer.js:1047:17)
    at Marker.module.exports.Marker.getHeadScreenPosition (/usr/share/atom/resources/app.asar/src/marker.js:174:33)
    at Marker.module.exports.Marker.notifyObservers (/usr/share/atom/resources/app.asar/src/marker.js:238:36)
    at /usr/share/atom/resources/app.asar/src/marker.js:45:24
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Marker.module.exports.Marker.emitChangeEvent (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:380:27)
    at Marker.module.exports.Marker.update (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:335:12)
    at Marker.module.exports.Marker.setRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:101:19)
    at Marker.module.exports.Marker.setBufferRange (/usr/share/atom/resources/app.asar/src/marker.js:132:32)
    at /usr/share/atom/resources/app.asar/src/selection.js:117:24
```

**Ctrl + Shift + z**

```
/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:555
Hide Stack Trace
TypeError: Cannot read property 'openScopes' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:555:49)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:369:113)
    at /usr/share/atom/resources/app.asar/src/tokenized-buffer.js:62:24
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:624:20)
    at TextBuffer.module.exports.TextBuffer.undo (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:712:16)
    at TextEditor.module.exports.TextEditor.undo (/usr/share/atom/resources/app.asar/src/text-editor.js:1126:19)
    at TextEditor.atom.commands.add.stopEventPropagation.core:undo (/usr/share/atom/resources/app.asar/src/text-editor-element.js:318:19)
    at atom-text-editor.newCommandListeners.(anonymous function) (/usr/share/atom/resources/app.asar/src/text-editor-element.js:286:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
```

```
/usr/share/atom/resources/app.asar/src/display-buffer.js:1047
Hide Stack Trace
Error: No screen line exists when converting buffer row to screen row
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/usr/share/atom/resources/app.asar/src/display-buffer.js:1047:17)
    at DisplayBuffer.module.exports.DisplayBuffer.screenRangeForBufferRange (/usr/share/atom/resources/app.asar/src/display-buffer.js:902:20)
    at Marker.module.exports.Marker.getScreenRange (/usr/share/atom/resources/app.asar/src/marker.js:136:33)
    at TextEditorPresenter.module.exports.TextEditorPresenter.didDestroyDecoration (/usr/share/atom/resources/app.asar/src/text-editor-presenter.js:1445:80)
    at /usr/share/atom/resources/app.asar/src/text-editor-presenter.js:1374:24
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Decoration.module.exports.Decoration.destroy (/usr/share/atom/resources/app.asar/src/decoration.js:79:20)
    at /usr/share/atom/resources/app.asar/src/decoration.js:64:24
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Marker.module.exports.Marker.destroyed (/usr/share/atom/resources/app.asar/src/marker.js:227:20)
```

**Comment by 50Wliu** [comment]
What version of Atom is this?  What packages, if any, do you have installed (you can check using `apm list --installed`)?  Since you're saying that the left tab is 'read only', can you please try to reproduce this in safe mode (`atom --safe`)?  Thanks.

**Comment by Lixquid** [comment]
I just got the same exception appear once, but now I've been utterly unable to reproduce it, with / without `--safe`. Stacktrace was the same, and the file I was copying from \*wasn't* read-only.

Version: `0.204`
Packages:
- calc@0.3.3
- file-icons@1.5.6
- git-tab-status@1.9.2
- highlight-selected@0.9.3
- language-gmod-lua@0.3.1
- language-jade@0.4.0
- script@2.23.0
- sort-lines@0.11.0
- Stylus@1.0.0
- Sublime-Style-Column-Selection@1.3.0
- todo-show@0.11.0

**Comment by gnumoksha** [comment]
@50Wliu version 0.204.0, debian package downloaded this week.

``apm list --instaled``:

```
Built-in Atom packages (88)
├── archive-view@0.57.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.49.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.41.0
├── autocomplete-atom-api@0.9.0
├── autocomplete-css@0.7.2
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.17.3
├── autocomplete-snippets@1.6.3
├── autoflow@0.24.0
├── autosave@0.20.0
├── background-tips@0.25.0
├── base16-tomorrow-dark-theme@0.26.0
├── base16-tomorrow-light-theme@0.9.0
├── bookmarks@0.35.0
├── bracket-matcher@0.74.0
├── command-palette@0.36.0
├── deprecation-cop@0.52.0
├── dev-live-reload@0.46.0
├── encoding-selector@0.20.0
├── exception-reporting@0.24.0
├── find-and-replace@0.169.0
├── fuzzy-finder@0.87.0
├── git-diff@0.55.0
├── go-to-line@0.30.0
├── grammar-selector@0.47.0
├── image-view@0.54.0
├── incompatible-packages@0.24.0
├── keybinding-resolver@0.33.0
├── language-c@0.45.0
├── language-clojure@0.15.0
├── language-coffee-script@0.40.0
├── language-csharp@0.5.0
├── language-css@0.30.0
├── language-gfm@0.76.0
├── language-git@0.10.0
├── language-go@0.26.0
├── language-html@0.38.0
├── language-hyperlink@0.13.0
├── language-java@0.15.0
├── language-javascript@0.78.0
├── language-json@0.14.0
├── language-less@0.27.0
├── language-make@0.14.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.24.0
├── language-php@0.24.0
├── language-property-list@0.8.0
├── language-python@0.35.0
├── language-ruby@0.56.0
├── language-ruby-on-rails@0.21.0
├── language-sass@0.38.0
├── language-shellscript@0.15.0
├── language-source@0.9.0
├── language-sql@0.15.0
├── language-text@0.6.0
├── language-todo@0.23.0
├── language-toml@0.16.0
├── language-xml@0.30.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.150.0
├── metrics@0.51.0
├── notifications@0.50.0
├── one-dark-syntax@0.5.0
├── one-dark-ui@0.8.2
├── one-light-syntax@0.6.0
├── one-light-ui@0.8.2
├── open-on-github@0.37.0
├── package-generator@0.39.0
├── release-notes@0.52.0
├── settings-view@0.206.0
├── snippets@0.91.0
├── solarized-dark-syntax@0.35.0
├── solarized-light-syntax@0.21.0
├── spell-check@0.58.0
├── status-bar@0.74.0
├── styleguide@0.44.0
├── symbols-view@0.97.0
├── tabs@0.69.0
├── timecop@0.31.0
├── tree-view@0.171.0
├── update-package-dependencies@0.10.0
├── welcome@0.27.0
├── whitespace@0.29.0
└── wrap-guide@0.35.0

/home/tobias/.atom/packages (0)
└── (empty)
```

I can reproduce the first error (Error: No screen line exists when converting buffer row to screen row), including in safe mode

**Comment by izuzak** [comment]
@gnumoksha Strange, I've followed your steps and I'm having trouble reproducing that in safe mode. Can you please help us investigate a bit more?

1. Try updating to 0.205.0
2. Record a short GIF while in safe mode which demonstrates the steps you're doing to reproduce the issue.
3. Share the file you're able to reproduce this with, e.g. in a gist.

Thanks!

**Comment by 50Wliu** [comment]
Also, can you clarify a bit about the left tab being "read only"?  As far as I know, there's nothing in Atom that allows you to make a tab read-only.

**Comment by gnumoksha** [comment]
Sorry for delay.

@50Wliu, "read only" was a expression. The left tab was used only for visualization and the right tab is where i am editing code.

@izuzak, My environment changed a little (i committed changes in file and i am working in other part of project) and i am not able to reproduce error now. I will try create environment again.

**Comment by gnumoksha** [comment]
Hi. A similar exception was launched a few moments ago. See http://tobias.ws/blog/wp-content/uploads/2015/07/atom_bug.png The error occurred when i selected some text in right tab and paste in the same tab.

Stack Trace:
```
/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:755
Hide Stack Trace
TypeError: Cannot read property 'isComment' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.isFoldableCommentAtRow (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:446:112)
    at TokenizedBuffer.module.exports.TokenizedBuffer.isFoldableAtRow (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:424:52)
    at TokenizedBuffer.module.exports.TokenizedBuffer.updateFoldableStatus (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:412:25)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:377:20)
    at /usr/share/atom/resources/app.asar/src/tokenized-buffer.js:62:24
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:624:20)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:789:16)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:753:14)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1136:26)
```

Atom 0.204.0 with few plugins enabled.
