### ISSUE TITLE
Multiple Uncaught Errors when using linter-xmllint

### ISSUE THREAD

**Issue by andya9** [atom/atom#7077]
Atom v. 205.0 on Linux
Every package up-to-date.

When trying to fix mismatching tags Atom gets crazy if linter-xmllint is enabled ([issue 13](https://github.com/AtomLinter/linter-xmllint/issues/13) on their repo, where you can find a gist with sample code and reproduce steps): duplication of characters, non-working backspace and starting/closing tags, ecc. A forced close is often needed.  
It doesn’t happen always, something like 7 times every 10: I tried finding a logical pattern, but I couldn’t find any, it seems completely random. The linter code seems clean and is really similar to linter-tidy, that doesn’t have this issue.

Here some of the errors (sometimes popups blame atom, sometimes bracket-matcher, sometimes git-diff, sometimes autocomplete-plus; neve linter-xmllint itself), I had to manually copy them as "report issue" didn’t do anything:

```
Uncaught TypeError: Cannot read property 'start' of undefined
/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/range.js:35
Hide Stack Trace
TypeError: Cannot read property 'start' of undefined
  at Function.module.exports.Range.fromObject (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/range.js:35:31)
  at DisplayBuffer.module.exports.DisplayBuffer.screenRangeForBufferRange (/usr/share/atom/resources/app.asar/src/display-buffer.js:901:27)
  at Marker.module.exports.Marker.getScreenRange (/usr/share/atom/resources/app.asar/src/marker.js:136:33)
  at Selection.module.exports.Selection.getScreenRange (/usr/share/atom/resources/app.asar/src/selection.js:88:26)
  at Selection.module.exports.Selection.autoscroll (/usr/share/atom/resources/app.asar/src/selection.js:893:53)
  at TextEditor.module.exports.TextEditor.undo (/usr/share/atom/resources/app.asar/src/text-editor.js:1138:38)
  at TextEditor.atom.commands.add.stopEventPropagation.core:undo (/usr/share/atom/resources/app.asar/src/text-editor-element.js:318:19)
  at atom-text-editor.newCommandListeners.(anonymous function) (/usr/share/atom/resources/app.asar/src/text-editor-element.js:286:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)
This is likely a bug in Atom.

Uncaught TypeError: Cannot read property 'isEmpty' of undefined
/usr/share/atom/resources/app.asar/src/selection.js:161
Hide Stack Trace
TypeError: Cannot read property 'isEmpty' of undefined
  at Selection.module.exports.Selection.isEmpty (/usr/share/atom/resources/app.asar/src/selection.js:161:35)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/share/atom/resources/app.asar/src/text-editor-component.js:187:87)
  at /usr/share/atom/resources/app.asar/src/text-editor-component.js:298:28
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app.asar/src/view-registry.js:168:9)
  at /usr/share/atom/resources/app.asar/src/view-registry.js:3:61
This is likely a bug in Atom.

Uncaught TypeError: Cannot read property 'isEmpty' of undefined
/usr/share/atom/resources/app.asar/src/selection.js:161
Hide Stack Trace
TypeError: Cannot read property 'isEmpty' of undefined
  at Selection.module.exports.Selection.isEmpty (/usr/share/atom/resources/app.asar/src/selection.js:161:35)
  at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/usr/share/atom/resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:108:43)
  at /usr/share/atom/resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:40:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/src/text-editor.js:239:32
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/usr/share/atom/resources/app.asar/src/display-buffer.js:302:20)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/usr/share/atom/resources/app.asar/src/display-buffer.js:1473:19)
  at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/usr/share/atom/resources/app.asar/src/display-buffer.js:1439:12)
  at /usr/share/atom/resources/app.asar/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:388:27)
  at /usr/share/atom/resources/app.asar/src/tokenized-buffer.js:62:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:624:20)
  at TextBuffer.module.exports.TextBuffer.undo (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:712:16)
  at TextEditor.module.exports.TextEditor.undo (/usr/share/atom/resources/app.asar/src/text-editor.js:1137:19)
  at TextEditor.atom.commands.add.stopEventPropagation.core:undo (/usr/share/atom/resources/app.asar/src/text-editor-element.js:318:19)
  at atom-text-editor.newCommandListeners.(anonymous function) (/usr/share/atom/resources/app.asar/src/text-editor-element.js:286:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)
The error was thrown from the bracket-matcher package.
```

**Comment by maxbrunsfeld** [comment]
@andya9 I'm following your steps in https://github.com/AtomLinter/linter-xmllint/issues/13, but not able to reproduce this yet. Is this still happening on Atom 0.209?

**Comment by izuzak** [comment]
@maxbrunsfeld I was able to reproduce these 2 days ago: https://github.com/atom/bracket-matcher/issues/137#issuecomment-110133233. Will give it a try on latest master again

**Comment by izuzak** [comment]
Yeah, still able to reproduce this -- just got these two after a bunch of edits and undos:

**Atom Version**: 0.209.0-f55c95b
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'row' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:32

TypeError: Cannot read property 'row' of undefined
  at Function.module.exports.Point.fromObject (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:32:23)
  at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:955:24)
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1100:27)
  at Marker.module.exports.Marker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:179:33)
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateOverlaysState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:568:51)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:139:14)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:182:38)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:298:28
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:168:9)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61

```

### Commands

```
  2x -1:04.3.0 core:undo (atom-text-editor.editor.is-focused)
  3x -1:03.2.0 core:redo (atom-text-editor.editor.is-focused)
     -1:02.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:00.9.0 core:undo (atom-text-editor.editor.is-focused)
  2x -1:00.0 core:redo (atom-text-editor.editor.is-focused)
     -0:57.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:57.4.0 core:undo (atom-text-editor.editor.is-focused)
     -0:56.4.0 core:redo (atom-text-editor.editor.is-focused)
     -0:55.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:53.9.0 core:undo (atom-text-editor.editor.is-focused)
  5x -0:49.2.0 core:redo (atom-text-editor.editor.is-focused)
  5x -0:36.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:21.6.0 editor:newline (atom-text-editor.editor.is-focused)
 12x -0:19.6.0 core:undo (atom-text-editor.editor.is-focused)
  4x -0:04.2.0 core:redo (atom-text-editor.editor.is-focused)
 22x -0:03.2.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 20,
    "invisibles": {},
    "softWrapAtPreferredLineLength": true,
    "showInvisibles": true,
    "tabLength": 4,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.12.7
linter-php, v0.0.15
linter-xmllint, v0.0.6

# Dev
No dev packages
```

----

**Atom Version**: 0.209.0-f55c95b
**System**: Mac OS X 10.10.3
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.76.0


### Stack Trace

Uncaught TypeError: Cannot read property 'isEmpty' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:161

TypeError: Cannot read property 'isEmpty' of undefined
  at Selection.module.exports.Selection.isEmpty (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:161:35)
  at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:108:43)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:40:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:236:32
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:311:20)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1560:19)
  at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1523:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:403:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:62:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:626:20)
  at TextBuffer.module.exports.TextBuffer.undo (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:713:16)
  at TextEditor.module.exports.TextEditor.undo (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1138:19)
  at TextEditor.atom.commands.add.stopEventPropagation.core:undo (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:320:19)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:288:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
  2x -1:04.2.0 core:undo (atom-text-editor.editor.is-focused)
  3x -1:03.1.0 core:redo (atom-text-editor.editor.is-focused)
     -1:02.0 core:save (atom-text-editor.editor.is-focused)
     -1:00.8.0 core:undo (atom-text-editor.editor.is-focused)
  2x -0:59.9.0 core:redo (atom-text-editor.editor.is-focused)
     -0:57.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:57.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:56.3.0 core:redo (atom-text-editor.editor.is-focused)
     -0:55.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:53.8.0 core:undo (atom-text-editor.editor.is-focused)
  5x -0:49.2.0 core:redo (atom-text-editor.editor.is-focused)
  5x -0:36.2.0 core:undo (atom-text-editor.editor.is-focused)
     -0:21.5.0 editor:newline (atom-text-editor.editor.is-focused)
 12x -0:19.6.0 core:undo (atom-text-editor.editor.is-focused)
  4x -0:04.1.0 core:redo (atom-text-editor.editor.is-focused)
 22x -0:03.1.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
linter, v0.12.7
linter-php, v0.0.15
linter-xmllint, v0.0.6

# Dev
No dev packages
```

**Comment by izuzak** [comment]
And when you click somewhere within the editor after those two exceptions show up, you get another one:

**Atom Version**: 0.209.0-f55c95b
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/range.js:35

TypeError: Cannot read property 'start' of undefined
  at Function.module.exports.Range.fromObject (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/range.js:35:31)
  at Range.module.exports.Range.compare (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/range.js:185:32)
  at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:382:156)
  at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:345:12)
  at Marker.module.exports.Marker.setProperties (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:236:19)
  at Marker.module.exports.Marker.setProperties (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:103:32)
  at Selection.module.exports.Selection.clear (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:199:19)
  at Cursor.module.exports.Cursor.clearSelection (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:653:55)
  at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:680:12)
  at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:119:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1355:23
  at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1555:9)
  at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1354:19)
  at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:548:25)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```

### Commands

```
  2x -4:07.5.0 core:undo (atom-text-editor.editor.is-focused)
  3x -4:06.4.0 core:redo (atom-text-editor.editor.is-focused)
     -4:05.3.0 core:save (atom-text-editor.editor.is-focused)
     -4:04.1.0 core:undo (atom-text-editor.editor.is-focused)
  2x -4:03.2.0 core:redo (atom-text-editor.editor.is-focused)
     -4:01.2.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -4:00.6.0 core:undo (atom-text-editor.editor.is-focused)
     -3:59.6.0 core:redo (atom-text-editor.editor.is-focused)
     -3:59 editor:newline (atom-text-editor.editor.is-focused)
  2x -3:57.1.0 core:undo (atom-text-editor.editor.is-focused)
  5x -3:52.5.0 core:redo (atom-text-editor.editor.is-focused)
  5x -3:39.5.0 core:undo (atom-text-editor.editor.is-focused)
     -3:24.8.0 editor:newline (atom-text-editor.editor.is-focused)
 12x -3:22.9.0 core:undo (atom-text-editor.editor.is-focused)
  4x -3:07.4.0 core:redo (atom-text-editor.editor.is-focused)
 22x -3:06.4.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 20,
    "invisibles": {},
    "softWrapAtPreferredLineLength": true,
    "showInvisibles": true,
    "tabLength": 4,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.12.7
linter-php, v0.0.15
linter-xmllint, v0.0.6

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@maxbrunsfeld I seem to have better luck triggering them after I make a bunch of changes (most of which include syntax errors), and then press and hold `cmd-z` to undo all of them

**Comment by andya9** [comment]
Same here, still happening; let me know if you need more info!

**Comment by andya9** [comment]
(@mnquintana Sorry, I clicked the wrong button)

**Comment by izuzak** [comment]
Man, these exceptions mess up Atom real good -- after quitting Atom and restarting, I get the white screen + devtools experience:

![screen shot 2015-06-10 at 21 45 52](https://cloud.githubusercontent.com/assets/38924/8092463/23b50ce2-0fba-11e5-9e88-815a096f4dee.png)

```
TypeError: Cannot read property 'start' of undefined
    at Function.module.exports.Range.fromObject (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/range.js:35:31)
    at MarkerStore.module.exports.MarkerStore.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:267:23)
    at Function.module.exports.MarkerStore.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:22:13)
    at TextBuffer.module.exports.TextBuffer.deserializeParams (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:168:40)
    at Function.module.exports.Serializable.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/serializable/lib/serializable.js:58:25)
    at DeserializerManager.module.exports.DeserializerManager.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/src/deserializer-manager.js:42:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/project.js:142:35
    at Array.map (native)
    at Project.module.exports.Project.deserializeParams (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:127:49)
    at Function.module.exports.Serializable.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/serializable/lib/serializable.js:58:25)
```

**Comment by maxbrunsfeld** [comment]
Thanks @izuzak. I just reproduced it. Gonna work on fixing this today.

**Comment by maxbrunsfeld** [comment]
Ok, what's happening is our MarkerIndex is getting corrupted because `linter-xmllint` is reporting a lint error whose end column is `NaN`. The entire `message` is:

```js
{
   line: "12",
   col: "\n  <section>\n  ",   // <--- should probably be a number
   level: "error",
   linter: "xmllint",
   message: "error parsing attribute name",
   range: Range(Point(11, 11), Point(11, NaN))
}
```

I'm adding validations for this inside of `text-buffer`, so that in the future, errors like this will be caught preemptively, and attributed to the package.

**Comment by maxbrunsfeld** [comment]
Actually, because of the way `linter` works, this type of error will probably be attributed to `linter`, not `linter-xmllint`, but I think that's the best we can do. It's much better than letting our buffer get into an invalid state.

**Comment by izuzak** [comment]
:zap: for figuring it out, @maxbrunsfeld!

**Comment by maxbrunsfeld** [comment]
Also thanks for the detailed initial report @andya9. I'm glad we caught that before 1.0.

**Comment by andya9** [comment]
Thank’you very much @maxbrunsfeld !
