### ISSUE TITLE
Uncaught Error: Cannot find module 'fs-plus'

### ISSUE THREAD

**Issue by brocknessmonster** [atom/atom#7087]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module 'fs-plus'

```
At module.js:353

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (C:\Users\bwhitaker\AppData\Local\atom\app-0.182.0\resources\app\src\module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/C:/Users/bwhitaker/.atom/packages/remote-sync-2.3.0/lib/RemoteSync.coffee:6:8)
    at Object.<anonymous> (/C:/Users/bwhitaker/.atom/packages/remote-sync-2.3.0/lib/RemoteSync.coffee:362:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (C:\Users\bwhitaker\AppData\Local\atom\app-0.182.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:67:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true,
    "fontSize": 11
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.10
remote-sync-2.3.0, v2.3.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
You're running an extremely old version of Atom – please update to the latest version (0.205.0).
