### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by wbelau** [atom/atom#7092]
Uncaught Error: Atom can only handle files < 2MB for now.

**Atom Version**: 0.161.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/src/project.js:461

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/Applications/Atom.app/Contents/Resources/app/src/project.js:461:15)
  at Project.module.exports.Project.bufferForPath (/Applications/Atom.app/Contents/Resources/app/src/project.js:438:63)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app/src/project.js:392:19)
  at Workspace.module.exports.Workspace.openUriInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:482:29)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:409:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

**Comment by 50Wliu** [comment]
Please update Atom to the latest version (currently 0.205.0).

**Comment by wbelau** [comment]
Error occurs when opening a large mail (*****imap.aol.txt) protocol file (size: 30.4 MB) with atom.

**Comment by wbelau** [comment]
I use  version 0.205.0 (0.205.0).

**Comment by 50Wliu** [comment]
Your bug report is saying that your Atom version is 0.161.0, so you might want to double-check that.
Large file support is actively being worked on and is almost ready.
