### ISSUE TITLE
Cannot read property 'loaded' of null When atom window is closed. 

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#7105]
Not serious , but when atom window is closed i got this error :

```
Cannot read property 'loaded' of null
TypeError: Cannot read property 'loaded' of null
    at AtomWindow.module.exports.AtomWindow.getLoadSettings (/opt/atom/resources/app.asar/src/browser/atom-window.js:135:41)
    at AtomApplication.module.exports.AtomApplication.saveState (/opt/atom/resources/app.asar/src/browser/atom-application.js:738:37)
    at EventEmitter.<anonymous> (/opt/atom/resources/app.asar/src/browser/atom-application.js:394:19)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
    at AtomApplication.module.exports.AtomApplication.removeWindow (/opt/atom/resources/app.asar/src/browser/atom-application.js:159:15)
    at BrowserWindow.<anonymous> (/opt/atom/resources/app.asar/src/browser/atom-window.js:193:41)
    at emitOne (events.js:82:20)
    at BrowserWindow.emit (events.js:166:7)
```

**Comment by benogle** [comment]
cc @maxbrunsfeld looks like it's coming from the state saving codez

**Comment by v3ss0n** [comment]
Awesome :+1:
