### ISSUE TITLE
Failed to load the nuclide-flow package

### ISSUE THREAD

**Issue by dotcool** [atom/atom#7120]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Failed to load the nuclide-flow package

```
At Cannot find module 'ssh2-streams'

Error: Cannot find module 'ssh2-streams'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/dotcoolgirl/Documents/nuclide/nuclide/pkg/nuclide/remote-connection/node_modules/ssh2/lib/client.js:6:20)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-light-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
nuclide-code-format, v0.0.0
nuclide-diff-view, v0.0.0
nuclide-file-tree, v0.0.0
nuclide-flow, v0.0.0
nuclide-hack, v0.0.0
nuclide-hg-repository, v0.0.0
nuclide-remote-projects, v0.0.0
nuclide-ssh-dialog, v0.0.0
nuclide-tabs, v0.0.0
nuclide-type-hint, v0.0.0
react, v0.12.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Sounds like a problem in nuclide -- can you report the problem to them? Also seems like we need to make the notifications package smarter so that it doesn't report this on Atom core. Added this to https://github.com/atom/notifications/issues/66.

**Comment by dotcool** [comment]
I have post the issue to them,thanks
