### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/matthew/Android/DU/.repo/local_manifests/sources.xml'

### ISSUE THREAD

**Issue by Matthew-333** [atom/atom#7133]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Ubuntu 15.04
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/matthew/Android/DU/.repo/local_manifests/sources.xml'

```
At /usr/share/atom/resources/app.asar/src/pane.js:759

Error: ENOENT: no such file or directory, open '/home/matthew/Android/DU/.repo/local_manifests/sources.xml'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.writeFileSync (fs.js:1155:15)
  at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
  at File.module.exports.File.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:264:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:362:21)
  at File.module.exports.File.writeSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:336:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1012:17)
  at TextEditor.module.exports.TextEditor.saveAs (/usr/share/atom/resources/app.asar/src/text-editor.js:582:26)
  at Pane.module.exports.Pane.saveItemAs (/usr/share/atom/resources/app.asar/src/pane.js:544:16)
  at Pane.module.exports.Pane.saveActiveItemAs (/usr/share/atom/resources/app.asar/src/pane.js:510:19)
  at Workspace.module.exports.Workspace.saveActivePaneItemAs (/usr/share/atom/resources/app.asar/src/workspace.js:589:35)
  at atom-workspace.atom.commands.add.core:save-as (/usr/share/atom/resources/app.asar/src/workspace-element.js:320:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -6:00.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:00.4.0 core:paste (atom-text-editor.editor.is-focused)
  6x -5:45.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:04.8.0 core:paste (atom-text-editor.editor.is-focused)
     -5:00.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:34.8.0 core:paste (atom-text-editor.editor.is-focused)
     -3:59.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:51.5.0 core:paste (atom-text-editor.editor.is-focused)
     -2:05.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:43.4.0 core:paste (atom-text-editor.editor.is-focused)
     -1:34.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:33.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:33 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:56 core:paste (atom-text-editor.editor.is-focused)
     -0:23.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.6.0 core:save-as (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi there @Matthew-333, could you please describe a bit what you were doing when this happened?  Did you by any chance execute a git command or otherwise change the file outside of Atom before this error occured?  Thanks!

**Comment by Matthew-333** [comment]
I found an error, it was completly my fault.. I tryed to save shourtcut instead of file.. Im so sorry, false alert, i will look better next time when i get and error.. (:
