### ISSUE TITLE
Atom build failed on 32 bit OpenSUSE 13.2

### ISSUE THREAD

**Issue by fusion809** [atom/atom#7134]
I was following the build technique outlined [here](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md), but at the `script/build` line (which I amended to `sudo script/build` due to permission errors) I received an error:

```
`npm WARN cannot run in wd atom@0.207.0 node -e 'process.exit(0)' (wd=/home/fusion809/atom)                                                                      
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.22.0"                                             
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/fusion809/atom/node_modules/scrollbar-style/.node-gyp"                                   
gyp WARN install got an error, rolling back install                             
gyp WARN install got an error, rolling back install                             
gyp ERR! configure error                                                        
gyp ERR! stack Error: 404 status code downloading tarball                       
gyp ERR! stack     at Request.<anonymous> (/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)                                                                             
gyp ERR! stack     at Request.emit (events.js:117:20)                           
gyp ERR! stack     at Request.onRequestResponse (/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:1176:10)                                                                           
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)                      
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)       
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)                                                                
gyp ERR! stack     at Socket.socketOnData (http.js:1588:20)                     
gyp ERR! stack     at TCP.onread (net.js:528:27)                                
gyp ERR! System Linux 3.16.6-2-default                                          
gyp ERR! command "node" "/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"           
gyp ERR! cwd /home/fusion809/atom/node_modules/scrollbar-style                  
gyp ERR! node -v v0.10.35                                                       
gyp ERR! node-gyp -v v1.0.2                                                     
gyp ERR! not ok                                                                 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.22.0"                                             
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/fusion809/atom/node_modules/nslog/.node-gyp"                                             
gyp WARN install got an error, rolling back install                             
gyp WARN install got an error, rolling back install                             
gyp ERR! configure error                                                        
gyp ERR! stack Error: 404 status code downloading tarball                       
gyp ERR! stack     at Request.<anonymous> (/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)                                                                             
gyp ERR! stack     at Request.emit (events.js:117:20)                           
gyp ERR! stack     at Request.onRequestResponse (/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:1176:10)                                                                           
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)                      
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)       
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)                                                                
gyp ERR! stack     at Socket.socketOnData (http.js:1588:20)                     
gyp ERR! stack     at TCP.onread (net.js:528:27)                                
gyp ERR! System Linux 3.16.6-2-default                                          
gyp ERR! command "node" "/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"           
gyp ERR! cwd /home/fusion809/atom/node_modules/nslog                            
gyp ERR! node -v v0.10.35                                                       
gyp ERR! node-gyp -v v1.0.2                                                     
gyp ERR! not ok                                                                 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.22.0"                                             
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/fusion809/atom/node_modules/runas/.node-gyp"                                             
gyp WARN install got an error, rolling back install                             
gyp WARN install got an error, rolling back install                             
gyp ERR! configure error                                                        
gyp ERR! stack Error: 404 status code downloading tarball                       
gyp ERR! stack     at Request.<anonymous> (/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)                                                                             
gyp ERR! stack     at Request.emit (events.js:117:20)                           
gyp ERR! stack     at Request.onRequestResponse (/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:1176:10)                                                                           
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)                      
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)       
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)                                                                
gyp ERR! stack     at Socket.socketOnData (http.js:1588:20)                     
gyp ERR! stack     at TCP.onread (net.js:528:27)                                
gyp ERR! System Linux 3.16.6-2-default                                          
gyp ERR! command "node" "/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"           
gyp ERR! cwd /home/fusion809/atom/node_modules/runas                            
gyp ERR! node -v v0.10.35                                                       
gyp ERR! node-gyp -v v1.0.2                                                     
gyp ERR! not ok                                                                 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.22.0"                                             
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/fusion809/atom/node_modules/oniguruma/.node-gyp"                                         
gyp WARN install got an error, rolling back install                             
gyp WARN install got an error, rolling back install                             
gyp ERR! configure error                                                        
gyp ERR! stack Error: 404 status code downloading tarball                       
gyp ERR! stack     at Request.<anonymous> (/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)                                                                             
gyp ERR! stack     at Request.emit (events.js:117:20)                           
gyp ERR! stack     at Request.onRequestResponse (/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:1176:10)                                                                           
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)                      
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)       
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)                                                                
gyp ERR! stack     at Socket.socketOnData (http.js:1588:20)                     
gyp ERR! stack     at TCP.onread (net.js:528:27)                                
gyp ERR! System Linux 3.16.6-2-default                                          
gyp ERR! command "node" "/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"           
gyp ERR! cwd /home/fusion809/atom/node_modules/oniguruma                        
gyp ERR! node -v v0.10.35                                                       
gyp ERR! node-gyp -v v1.0.2                                                     
gyp ERR! not ok                                                                 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.22.0"                                             
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/fusion809/atom/node_modules/atom-keymap/node_modules/keyboard-layout/.node-gyp"          
gyp WARN install got an error, rolling back install                             
gyp WARN install got an error, rolling back install                             
gyp ERR! configure error                                                        
gyp ERR! stack Error: 404 status code downloading tarball                       
gyp ERR! stack     at Request.<anonymous> (/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)                                                                             
gyp ERR! stack     at Request.emit (events.js:117:20)                           
gyp ERR! stack     at Request.onRequestResponse (/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:1176:10)                                                                           
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)                      
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)       
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)                                                                
gyp ERR! stack     at Socket.socketOnData (http.js:1588:20)                     
gyp ERR! stack     at TCP.onread (net.js:528:27)                                
gyp ERR! System Linux 3.16.6-2-default                                          
gyp ERR! command "node" "/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"           
gyp ERR! cwd /home/fusion809/atom/node_modules/atom-keymap/node_modules/keyboard-layout                                                                         
gyp ERR! node -v v0.10.35                                                       
gyp ERR! node-gyp -v v1.0.2                                                     
gyp ERR! not ok                                                                 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.22.0"                                             
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/fusion809/atom/node_modules/git-utils/.node-gyp"                                         
gyp WARN install got an error, rolling back install                             
gyp WARN install got an error, rolling back install                             
gyp ERR! configure error                                                        
gyp ERR! stack Error: 404 status code downloading tarball                       
gyp ERR! stack     at Request.<anonymous> (/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)                                                                             
gyp ERR! stack     at Request.emit (events.js:117:20)                           
gyp ERR! stack     at Request.onRequestResponse (/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:1176:10)                                                                           
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)                      
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)       
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)                                                                
gyp ERR! stack     at Socket.socketOnData (http.js:1588:20)                     
gyp ERR! stack     at TCP.onread (net.js:528:27)                                
gyp ERR! System Linux 3.16.6-2-default                                          
gyp ERR! command "node" "/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"           
gyp ERR! cwd /home/fusion809/atom/node_modules/git-utils                        
gyp ERR! node -v v0.10.35                                                       
gyp ERR! node-gyp -v v1.0.2                                                     
gyp ERR! not ok                                                                 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.22.0"                                             
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/fusion809/atom/node_modules/pathwatcher/.node-gyp"                                       
gyp WARN install got an error, rolling back install                             
gyp WARN install got an error, rolling back install                             
gyp ERR! configure error                                                        
gyp ERR! stack Error: 404 status code downloading tarball                       
gyp ERR! stack     at Request.<anonymous> (/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)                                                                             
gyp ERR! stack     at Request.emit (events.js:117:20)                           
gyp ERR! stack     at Request.onRequestResponse (/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:1176:10)                                                                           
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)                      
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)       
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)                                                                
gyp ERR! stack     at Socket.socketOnData (http.js:1588:20)                     
gyp ERR! stack     at TCP.onread (net.js:528:27)                                
gyp ERR! System Linux 3.16.6-2-default                                          
gyp ERR! command "node" "/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"           
gyp ERR! cwd /home/fusion809/atom/node_modules/pathwatcher                      
gyp ERR! node -v v0.10.35                                                       
gyp ERR! node-gyp -v v1.0.2                                                     
gyp ERR! not ok                                                                 
npm ERR! Linux 3.16.6-2-default                                                 
npm ERR! argv "/home/fusion809/atom/apm/node_modules/atom-package-manager/bin/node" "/home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/root/.atom/.apm/.apmrc" "--userconfig" "/root/.atom/.apmrc" "install" "--target=0.22.0" "--arch=ia32"                       
npm ERR! node v0.10.35                                                          
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! scrollbar-style@3.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrollbar-style@3.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the scrollbar-style package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrollbar-style
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fusion809/atom/npm-debug.log`
```

[here](https://drive.google.com/file/d/0B1_sXH68hMWBR2RvdWVNVXJSdDg/view?usp=sharing)'s my log file.

**Comment by w1748587889** [comment]
some errors make me confused.Neither I can build on 32 bit OpenSUSE 13.2

**Comment by MoritzKn** [comment]
It seams like it is not possible to run `script/build` as root. I think this is no real problem, but then the question is: what "permission errors" did you get when running `script/build` without `sudo`? Possible something similar to #14848?

**Comment by daviwil** [comment]
Not so fast, stale bot! Still need to finish up my PR that resolves this issue.
