### ISSUE TITLE
[Windows] updates kept failing and retrying

### ISSUE THREAD

**Issue by gera2ld** [atom/atom#7135]
`SquirrelSetup.log` says:
```
Program: Starting Squirrel Updater: --processStart atom.exe
Program: Want to launch '~\AppData\Local\atom\app-0.198.0\atom.exe'
Program: About to launch: '~\AppData\Local\atom\app-0.198.0\atom.exe': 
Program: Starting Squirrel Updater: --download https://atom.io/api/updates
Program: Fetching update information, downloading from https://atom.io/api/updates
CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES
FileDownloader: Downloading file: https://atom.io/api/updates/atom-0.207.0-full.nupkg
UpdateInfo: Couldn't get release notes for:atom-0.207.0-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at '~\AppData\Local\atom\..\atom\packages\atom-0.207.0-full.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__2(ReleaseEntry x)
```

**Comment by gera2ld** [comment]
BTW, the registration item `HKEY_CLASSES_ROOT\*\shell\Atom\` and `%LocalAppData%\atom\bin` scripts are never updated once installed.

**Comment by paulcbetts** [comment]
This error is just a warning, you need to paste more of the log

**Comment by gera2ld** [comment]
That's all of the log.
After that, atom-0.207.0-full.nupkg is downloaded again and again.

**Comment by damieng** [comment]
Hi gera2ld. Are you still having this problem?

Additionally the registration items are now updated each release and as of 1.0.7 that will also include new file associations.

**Comment by gera2ld** [comment]
It works well now, thanks for your great work.
