### ISSUE TITLE
[Windows 7] Atom deleted itself and can't re-install

### ISSUE THREAD

**Issue by iadj** [atom/atom#7140]
I tried to start up Atom today, and the default shortcut was no longer working.
I tried to reinstall Atom, which caused a `Installation Failed` error. I tried removing all leftover files from the AppData and Temp folders and tried to run the installer again, resulting in the same error.

Here's the SquirrelSetup.log:

```
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\IADJ\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\IADJ\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\IADJ\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\IADJ\AppData\Local\atom\app-0.207.0
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\IADJ\AppData\Local\atom\app-0.207.0\atom.exe]
ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\IADJ\AppData\Local\atom\app-0.207.0\atom.exe: System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb5.<<invokePostInstall>b__a9>d__b7.MoveNext()
IEnableLogger: Failed to invoke post-install: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>b__af(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__bb.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__51.MoveNext()
```

**Comment by Zireael07** [comment]
Did you uninstall first?

**Comment by iadj** [comment]
Forgot to remove the /username/.atom folder, now it properly reinstalled!

**Comment by sryze** [comment]
I'm getting the same error on Windows 10 while trying to install a new version using the Windows installer. Worst of all, it deleted the old version in the process, so I can't use Atom at all right now.
