### ISSUE TITLE
Unable to view local, featured, or search for any packages.

### ISSUE THREAD

**Issue by theoctopod** [atom/atom#7153]
Running version `0.207.0` on Windows 8.1.

Everything was running perfectly until I decided to make junction points from `C:\Users\<username>\AppData\Local` to `D:\Users\<username>\AppData\Local`, `C:\Users\<username>\AppData\LocalLow` to `D:\Users\<username>\AppData\LocalLow`, and `C:\Users\<username>\AppData\Roaming` to `D:\Users\<username>\AppData\Roaming` in order to free space on my C drive.

Anyway, ever since doing that, I was unable to search for any packages. The featured packages also fails with a seemingly uninformative error:
![](http://puu.sh/ifC5D/a5c3a514ce.png)

Also, viewing my local packages or themes doesn't work, as all the categories are frozen on "Loading packages...":
![](http://puu.sh/ifBOJ/ce82bb55d6.png)

In the Developer Console, there is an error about failing to fetch local packages:
```
Fetching local packages failed. Error: Fetching local packages failed.
  at D:\Users\<username>\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:83:21
  at exit (D:\Users\<username>\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:53:16)
  at triggerExitCallback (D:\Users\<username>\AppData\Local\atom\app-0.207.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (D:\Users\<username>\AppData\Local\atom\app-0.207.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
```
I could revert the junction points as a last resort if that's the only way to fix this problem, but I was wondering if anyone could pinpoint the exact cause of this issue.

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/settings-view?

**Comment by mnquintana** [comment]
This issue was moved to atom/settings-view#533
