### ISSUE TITLE
Error when doing ctrl-f

### ISSUE THREAD

**Issue by JPFrancoia** [atom/atom#7155]
I have a red notification opening each time I do ctrl-f. The behavior of the search feature is not altered however.

Is there a way to hide the red notification ?

Here is the error message:

```
Uncaught InvalidStateError: Failed to execute 'dispatchEvent' on 'EventTarget': The event provided is uninitialized.
```

Stack trace:

```
/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520
Hide Stack Trace
Error: Failed to execute 'dispatchEvent' on 'EventTarget': The event provided is uninitialized.
  at Error (native)
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)
```

**Comment by 50Wliu** [comment]
Hi @rififi, what Atom version is this (and what OS)?  In addition, can you please try to reproduce this in safe mode (`atom --safe`)?  Thanks.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/7155#issuecomment-109763436. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
