### ISSUE TITLE
Failed to activate the spotify-linux package

### ISSUE THREAD

**Issue by Yhozen** [atom/atom#7163]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.207.0
**System**: elementary OS
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the spotify-linux package

```
At Module did not self-register.

Error: Module did not self-register.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at bindings (/home/garox/node_modules/dbus-native/node_modules/abstract-socket/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/garox/node_modules/dbus-native/node_modules/abstract-socket/lib/abstract_socket.js:4:34)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "dark-flat-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
dark-flat-ui, v1.1.4
minimap, v4.9.4
spotify-linux, v0.3.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Could you please move this to the [spotify-linux](https://github.com/jazzpi/spotify-linux) package?  Thanks.
