### ISSUE TITLE
UI won't load

### ISSUE THREAD

**Issue by juanscv** [atom/atom#7164]
After updating to 0.2.0.7 all i see is the menu bar and a blank page. I get this error when i reload:
````
Error: EPERM: operation not permitted, open 'C:\Users\juan\.atom\compile-cache\less\0cc7f11b7e69c0ffbafd9097990f1462ab8206dc\imports.json'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.fsPlus.writeFileSync (C:\Users\juan\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (C:\Users\juan\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\less-cache\lib\less-cache.js:155:17)
    at LessCache.module.exports.LessCache.setImportPaths (C:\Users\juan\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\less-cache\lib\less-cache.js:113:12)
    at new LessCache (C:\Users\juan\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\less-cache\lib\less-cache.js:32:12)
    at new LessCompileCache (C:\Users\juan\AppData\Local\atom\app-0.207.0\resources\app.asar\src\less-compile-cache.js:20:20)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\juan\AppData\Local\atom\app-0.207.0\resources\app.asar\src\theme-manager.js:299:26)index.js:66 handleSetupError
````
I was trying to change a syntax theme before updating, because afer 0.2.0.6 y was using metro-syntax but highlighting wasn't working. It threw some errors but before reporting it told to upgrade first. Now it's all blank.

![screenshot 2](https://cloud.githubusercontent.com/assets/955241/8026489/756ca4c0-0d3d-11e5-852c-8e391237eb40.png)

**Comment by juanscv** [comment]
I deleted everything at the compile-cache folder and re-opened the app. Everything seems fine now.

**Comment by MadMcCrow** [comment]
Hum I'm very much glad that someone had this problem too. Maybe, since it seems to occurs always due to the same reason,so this is not some random bug. ( happened on 1.0.2 so this seems to be a long run problem on Windows Version )

**Comment by iamliamc** [comment]
Had the same problem v1.13.0 when I opened Atom on El Capitan 10.11.6 it popped up dozens and dozens of copies of atom... very annoying... so many that the uncaught console errors looking for import.json in the compile-cacher folder didn't even show up the first few times. I deleted everything in compile-cacher and relaunched everything works now...
