### ISSUE TITLE
Uncaught Error: Encountered an invalid scope end id. Popped -1, expected to pop -27.

### ISSUE THREAD

**Issue by jgoldfar** [atom/atom#7177]
1. Open atom
2. Open a file

**Atom Version**: 0.207.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Encountered an invalid scope end id. Popped -1, expected to pop -27.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:573

Error: Encountered an invalid scope end id. Popped -1, expected to pop -27.
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopesFromTags (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:573:21)
  at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:555:21)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:286:105)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:263:26
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47

```

### Commands

```
     -0:00.7.0 core:close (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "language-mustache",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-go",
      "language-java",
      "language-less",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sql",
      "language-toml",
      "language-xml",
      "release-notes",
      "whitespace",
      "deprecation-cop",
      "language-property-list",
      "language-sass",
      "open-on-github",
      "metrics",
      "package-generator"
    ]
  },
  "editor": {
    "invisibles": {},
    "softWrapAtPreferredLineLength": true,
    "fontSize": 12,
    "lineHeight": 1.2
  }
}
```

### Installed Packages

```coffee
# User
language-julia, v0.9.0
language-latex, v0.6.1
latex, v0.24.1
linter, v0.12.6
linter-chktex, v0.3.0
pdf-view, v0.22.0
project-manager, v1.15.10

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@jgoldfar Do you remember which type of file you opened (Ruby file, Python, LaTeX)? Does this happen for all files or only some files?

cc @nathansobo here's one more of these, from Atom v0.207.0

**Comment by jgoldfar** [comment]
This error happened only when opening a LaTeX file as far as I can tell. After working a bit it would reoccur, but I can't manage to reproduce that consistently.

**Comment by nathansobo** [comment]
@jgoldfar If it happens again, it would be really helpful to know the file contents that trigger it. If you're comfortable emailing them to me at `nathan@github.com` under a strict privacy promise that would help a ton. We're falling into some corner case and it's hard to fix without a reproduction case. Thanks!

**Comment by jgoldfar** [comment]
I've sent a message with a reproduction case more reliable than the intermittent issue I opened this issue for. The error reporting messages is the same, so I hope it helps this as well.

**Comment by jgoldfar** [comment]
Similar error message, looks also related to long lines in the editor:

1. Open a new document
2. Enter
```
Since $g^n \to g$ weakly in $W_2^1[0,T]$, it follows that $\norm{g_n}_{W_2^1[0,T]}$ is uniformly bounded, and moreover that $\norm{g_n}_{W_2^{1/4}[0,T]}$ is uniformly bounded. Therefore, $\norm{\hat{u}^\tau}_{W_2^{1,1}} \leq C$ independent of $n$ or $\tau$. Since $W_2^{1,1}(D)$ is an Hilbert space (and hence a reflexive Banach space,) it follows that $
```
3. Type "\"

**Atom Version**: 0.208.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Encountered an invalid scope end id. Popped -1, expected to pop -15.

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:741

Error: Encountered an invalid scope end id. Popped -1, expected to pop -15.
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopesFromTags (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:607:21)
  at TokenizedBuffer.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:483:31)
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLinesForRows (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:490:10)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:383:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:62:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:622:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:530:12)
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:452:43)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:742:31
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:787:29
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:736:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1148:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:781:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1974:43)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1948:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:779:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:739:21)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:440:35)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```

### Commands

```
     -3:42.5.0 core:close (atom-text-editor.editor.is-focused)
     -3:35.8.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -3:32.7.0 editor:toggle-soft-wrap (atom-text-editor.editor.is-focused)
  4x -3:29.2.0 core:select-down (atom-text-editor.editor.is-focused)
     -3:28.5.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -3:28.1.0 core:select-down (atom-text-editor.editor.is-focused)
     -3:27.7.0 core:copy (atom-text-editor.editor.is-focused)
     -3:27.1.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -3:26.4.0 core:paste (atom-text-editor.editor.is-focused)
     -3:20.3.0 core:cancel (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -3:18.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -3:17.6.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -3:16.7.0 core:save (atom-text-editor.editor.is-focused)
     -3:12.6.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -3:12.3.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:01.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "language-mustache",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-go",
      "language-java",
      "language-less",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sql",
      "language-toml",
      "language-xml",
      "release-notes",
      "whitespace",
      "deprecation-cop",
      "language-property-list",
      "language-sass",
      "open-on-github",
      "metrics",
      "package-generator",
      "symbols-view",
      "language-matlab-octave",
      "language-c",
      "language-css",
      "language-html",
      "language-json",
      "language-javascript",
      "language-python",
      "language-yaml",
      "styleguide",
      "welcome"
    ]
  },
  "editor": {
    "invisibles": {},
    "softWrapAtPreferredLineLength": true,
    "fontSize": 12,
    "lineHeight": 1.2
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.1.2
language-julia, v0.9.0
language-latex, v0.6.1
latex, v0.24.1
linter, v0.12.7
linter-chktex, v0.3.0
pdf-view, v0.22.0
project-manager, v1.15.10

# Dev
No dev packages
```

**Comment by nathansobo** [comment]
Thanks very much for taking the time to help me reproduce this. I really appreciate it. Should be fixed on the next release.

**Comment by jgoldfar** [comment]
Great. Thanks for your help and the amazing editor.
