### ISSUE TITLE
Uncaught Error: ENOTDIR, not a directory '/Users/jsun/Documents/atlantic-dev/atom'

### ISSUE THREAD

**Issue by sunnifer** [atom/atom#7188]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOTDIR, not a directory '/Users/jsun/Documents/atlantic-dev/atom'

```
At /Applications/Atom.app/Contents/Resources/app/src/workspace.js:518

Error: ENOTDIR, not a directory '/Users/jsun/Documents/atlantic-dev/atom'
    at Error (native)
    at Object.fs.openSync (fs.js:503:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app/src/project.js:423:27)
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:500:31)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:426:19)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:49:25)
    at EventEmitter.emit (events.js:119:17)
```

### Commands

```
     -0:02.2 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 14,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
You're running an extremely old version of Atom - please update to the latest version (0.207.0). If this error was thrown while trying to update, then you might have to download it from https://atom.io/ and reinstall.
