### ISSUE TITLE
Uncaught Error: Encountered an invalid scope end id. Popped -1, expected to pop -77.

### ISSUE THREAD

**Issue by d6e** [atom/atom#7198]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Encountered an invalid scope end id. Popped -1, expected to pop -77.

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:573

Error: Encountered an invalid scope end id. Popped -1, expected to pop -77.
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopesFromTags (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:573:21)
  at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:555:21)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:286:105)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:263:26
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "linter-pep257"
    ]
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true,
    "showIndentGuide": true,
    "tabLength": 4,
    "softTabs": false
  }
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.9.3
jsonlint, v1.1.2
language-arduino, v0.2.1
linter, v0.12.6
linter-pylint, v0.2.2
monokai, v0.14.0
python-jedi, v0.3.0
save-session, v0.15.5
tabs-to-spaces, v0.11.0
vim-mode, v0.51.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report, @d6e. Can you let us know which type of file you were editing when this happened? (e.g. Ruby file, Python, or something else?) I'm guessing this isn't happening for all file types, but only some?

cc @nathansobo here's another one of those errors.

**Comment by d6e** [comment]
I believe it was just a python file.

**Comment by izuzak** [comment]
Thanks, @d6e. If it happens again, it would be really helpful to know the file contents that trigger it -- see #7177 (comment) for details.
