### ISSUE TITLE
Error when previous session file was opened from network share that is not available

### ISSUE THREAD

**Issue by rex-dennis** [atom/atom#7203]
To Reproduce:

1. Open a file from a network share, e.g. \\\MyServer\Logfiles\error.log then close Atom.
2. Open Atom again when the network share is no longer present, e.g. on a different network at home.

**Atom Version**: 0.208.0
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: UNKNOWN: unknown error, open '\\\cpc-23949-001\LogFiles\'

```
At C:\Users\dw\AppData\Local\atom\app-0.208.0\resources\app.asar\src\workspace.js:458

Error: UNKNOWN: unknown error, open '\\cpc-23949-001\LogFiles\'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Project.module.exports.Project.open (C:\Users\dw\AppData\Local\atom\app-0.208.0\resources\app.asar\src\project.js:371:27)
    at Workspace.module.exports.Workspace.openURIInPane (C:\Users\dw\AppData\Local\atom\app-0.208.0\resources\app.asar\src\workspace.js:440:31)
    at Workspace.module.exports.Workspace.open (C:\Users\dw\AppData\Local\atom\app-0.208.0\resources\app.asar\src\workspace.js:366:19)
    at EventEmitter.<anonymous> (C:\Users\dw\AppData\Local\atom\app-0.208.0\resources\app.asar\src\window-event-handler.js:46:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-objective-c",
      "language-clojure",
      "language-go",
      "language-java",
      "language-perl",
      "language-php",
      "language-python",
      "language-toml"
    ],
    "projectHome": "C:\\Projects\\"
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
language-cshtml, v0.1.1
language-fsharp, v0.8.4
language-powershell, v2.0.1
minimap, v4.9.4
vim-mode, v0.51.0

# Dev
No dev packages
```

**Comment by TheSlider2** [comment]
I'm having this issue as well (using 1.03) Should i open a new issue or is this one not really "closed" and closed means it's on the todo list ? I don't get it.

Initial post in the forum :
https://discuss.atom.io/t/atom-startup-uncaught-error-for-a-folder-on-an-offline-file-server/19369
