### ISSUE TITLE
Failed to activate the syntax-settings package

### ISSUE THREAD

**Issue by sean-brandt** [atom/atom#7208]
[Enter steps to reproduce below:]

1. Start atom with packagte installed

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the syntax-settings package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/sean/Dropbox%20(Fuzzymagic)/AppData/atom.io/packages/syntax-settings/lib/syntax-settings.coffee:34:25)
    at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
    at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
    at PackageManager.module.exports.PackageManager.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:46)
    at Atom.module.exports.Atom.startEditorWindow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/atom.js:641:21)
    at Object.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-handlebars, v0.5.0
autocomplete-paths, v1.0.2
color-picker, v2.0.4
editor-stats, v0.17.0
editorconfig, v1.0.0
file-icons, v1.5.7
file-type-icons, v0.6.0
file-types, v0.4.0
highlight-line, v0.10.2
language-docker, v1.1.3
language-gradle, v0.0.3
language-groovy, v0.4.0
language-ini, v1.10.0
language-mediawiki, v2.0.0
language-tinymush, v0.1.0
linter, v0.12.7
project-manager, v1.15.10
recent-files, v0.3.0
soft-wrap-indicator, v0.7.0
syntax-settings, v0.7.1
travis-ci-status, v0.15.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
Do you know how/when you installed the `syntax-settings` package? It does not appear to still be published.

**Comment by kevinsawicki** [comment]
Looks like this package is no longer around so it will be impossible to diagnose what happened. I'd recommend uninstalling it or disabling it from the Settings view since it appears to no longer work because it is using APIs that are no longer available.
