### ISSUE TITLE
Uncaught Error: Encountered an invalid scope end id. Popped -1, expected to pop -113.

### ISSUE THREAD

**Issue by d6e** [atom/atom#7211]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Encountered an invalid scope end id. Popped -1, expected to pop -113.

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:607

Error: Encountered an invalid scope end id. Popped -1, expected to pop -113.
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopesFromTags (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:607:21)
  at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:589:21)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:294:105)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:271:26
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47

```

### Commands

```
     -0:27.3.0 pane:reopen-closed-item (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:22.4.0 settings-view:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:14.8.0 core:close (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "linter-pep257"
    ]
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true,
    "showIndentGuide": true,
    "tabLength": 4,
    "softTabs": false
  }
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.9.3
jsonlint, v1.1.2
language-arduino, v0.2.1
linter, v0.12.7
linter-pylint, v0.2.2
monokai, v0.14.0
python-jedi, v0.3.0
save-session, v0.15.5
tabs-to-spaces, v0.11.0
vim-mode, v0.51.0

# Dev
No dev packages
```

**Comment by d6e** [comment]
Sorry, this was a duplicate of https://github.com/atom/atom/issues/7198
