### ISSUE TITLE
TypeError: Expecting a function in instanceof check, but got undefined

### ISSUE THREAD

**Issue by moutons** [atom/atom#7215]
TypeError: Expecting a function in instanceof check, but got undefined
  at /usr/share/atom/resources/app/src/view-registry.js:70:34
  at Array.find (native)
  at ViewRegistry.module.exports.ViewRegistry.findProvider (/usr/share/atom/resources/app/src/view-registry.js:67:29)
  at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app/src/view-registry.js:48:34)
  at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app/src/view-registry.js:31:21)
  at Atom.module.exports.Atom.deserializeWorkspaceView (/usr/share/atom/resources/app/src/atom.js:656:39)
  at Atom.module.exports.Atom.deserializeEditorWindow (/usr/share/atom/resources/app/src/atom.js:671:19)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:534:12)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:41:25)

require.resolve('coffee-script')

gives "/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js"

![atom-error](https://cloud.githubusercontent.com/assets/2305030/8091313/b90e3184-0f78-11e5-9b97-3416d1b2a494.png)

`atom --safe` lets Atom open.

**Comment by snehasis** [comment]
Facing the Same Issue
Steps: 
1) Create Menu Item in Tray
2) Having a Click Event On the Menu Items
3) After Sometime may be reloading the webpage sometime on Clicking on any menu Item I am getting the Same Error below
Expecting a function in instanceof check, but got undefined 

Please help solving the issue.

Thanks
