### ISSUE TITLE
Uncaught TypeError: Cannot read property 'findWrapColumn' of undefined

### ISSUE THREAD

**Issue by mingzx** [atom/atom#7248]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'findWrapColumn' of undefined

```
At C:\Users\user\AppData\Local\atom\app-0.209.0\resources\app.asar\src\display-buffer.js:1594

TypeError: Cannot read property 'findWrapColumn' of undefined
    at DisplayBuffer.module.exports.DisplayBuffer.buildScreenLines (C:\Users\user\AppData\Local\atom\app-0.209.0\resources\app.asar\src\display-buffer.js:1594:52)
    at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (C:\Users\user\AppData\Local\atom\app-0.209.0\resources\app.asar\src\display-buffer.js:1546:20)
    at DisplayBuffer.module.exports.DisplayBuffer.updateAllScreenLines (C:\Users\user\AppData\Local\atom\app-0.209.0\resources\app.asar\src\display-buffer.js:235:19)
    at DisplayBuffer.module.exports.DisplayBuffer.updateWrappedScreenLines (C:\Users\user\AppData\Local\atom\app-0.209.0\resources\app.asar\src\display-buffer.js:325:12)
    at DisplayBuffer.module.exports.DisplayBuffer.setWidth (C:\Users\user\AppData\Local\atom\app-0.209.0\resources\app.asar\src\display-buffer.js:465:14)
    at TextEditor.module.exports.TextEditor.setWidth (C:\Users\user\AppData\Local\atom\app-0.209.0\resources\app.asar\src\text-editor.js:2742:33)
    at TextEditorPresenter.module.exports.TextEditorPresenter.setContentFrameWidth (C:\Users\user\AppData\Local\atom\app-0.209.0\resources\app.asar\src\text-editor-presenter.js:1173:20)
    at TextEditorComponent.module.exports.TextEditorComponent.measureDimensions (C:\Users\user\AppData\Local\atom\app-0.209.0\resources\app.asar\src\text-editor-component.js:851:24)
    at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (C:\Users\user\AppData\Local\atom\app-0.209.0\resources\app.asar\src\text-editor-component.js:267:12)
    at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (C:\Users\user\AppData\Local\atom\app-0.209.0\resources\app.asar\src\text-editor-component.js:808:16)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 17,
    "showIndentGuide": true,
    "softWrap": true
  }
}
```
### Installed Packages

``` coffee
# User
minimap, v4.10.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by polybuildr** [comment]
Got this error today. Any reason it was closed?

**Comment by izuzak** [comment]
@polybuildr Which version of Atom were you using when you got this error and which OS? Do you have any packages installed (`apm ls --installed`)?

**Comment by polybuildr** [comment]
```
$ atom --version
1.0.0

$ apm ls --installed
/home/vivek/.atom/packages (6)
├── atom-ternjs@0.6.4
├── autocomplete-plus-python-jedi@0.3.6
├── color-picker@2.0.7
├── docblockr@0.7.2
├── emmet@2.3.10
└── linter-scss-lint@1.0.4
```
I'm using the [webupd8 team's package](https://launchpad.net/~webupd8team/+archive/ubuntu/atom) on Ubuntu 14.04.

This issue has only occurred once, though, and unfortunately I didn't keep a copy of the stack trace because of the "This issue has already been reported." message.
