### ISSUE TITLE
Uncaught TypeError: Cannot read property 'row' of undefined

### ISSUE THREAD

**Issue by lierdakil** [atom/atom#7268]
For some reason, the following pattern sometimes throws the following error since 0.209:

```coffeescript
atom.workspace.open(uri).then (editor) ->
        editor.setCursorBufferPosition pos
```

**Atom Version**: 0.209.0-d965eb7
**System**: "Gentoo Base
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'row' of undefined

```
At /home/livid/bin/atom-dir/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:32

TypeError: Cannot read property 'row' of undefined
  at Function.module.exports.Point.fromObject (/home/livid/bin/atom-dir/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:32:23)
  at TextBuffer.module.exports.TextBuffer.clipPosition (/home/livid/bin/atom-dir/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:955:24)
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/home/livid/bin/atom-dir/share/atom/resources/app.asar/src/display-buffer.js:1100:27)
  at Marker.module.exports.Marker.getHeadScreenPosition (/home/livid/bin/atom-dir/share/atom/resources/app.asar/src/marker.js:179:33)
  at Cursor.module.exports.Cursor.getScreenPosition (/home/livid/bin/atom-dir/share/atom/resources/app.asar/src/cursor.js:127:26)
  at Cursor.module.exports.Cursor.getScreenRange (/home/livid/bin/atom-dir/share/atom/resources/app.asar/src/cursor.js:695:20)
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateHiddenInputState (/home/livid/bin/atom-dir/share/atom/resources/app.asar/src/text-editor-presenter.js:400:55)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/home/livid/bin/atom-dir/share/atom/resources/app.asar/src/text-editor-presenter.js:124:14)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/home/livid/bin/atom-dir/share/atom/resources/app.asar/src/text-editor-component.js:182:38)
  at /home/livid/bin/atom-dir/share/atom/resources/app.asar/src/text-editor-component.js:298:28
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/home/livid/bin/atom-dir/share/atom/resources/app.asar/src/view-registry.js:168:9)
  at __bind (/home/livid/bin/atom-dir/share/atom/resources/app.asar/src/view-registry.js:3:61)

```

### Commands

```
     -0:03.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.1.0 ide-haskell:check-file (atom-text-editor.editor.is-focused)
     -0:03.1.0 ide-haskell:lint-file (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-lint",
      "haskell-hindent",
      "markdown-preview-plus",
      "markdown-preview",
      "autocomplete",
      "terminal-status",
      "linter-hlint"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "autoIndentOnPaste": false,
    "invisibles": {},
    "fontFamily": "DejaVu Sans Mono",
    "fontSize": 23,
    "softWrapAtPreferredLineLength": true,
    "scrollPastEnd": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.4
autocomplete-paths, v1.0.2
autocomplete-plus-python-jedi, v0.3.6
build, v0.37.0
haskell-ghc-mod, v0.7.5
haskell-pointfree, v0.1.2
ide-haskell, v0.5.11
language-dot, v1.6.0
language-haskell, v1.1.1
language-latex, v0.6.1
linter, v0.12.7
linter-coffeelint, v0.3.2
linter-plus, v0.4.0
linter-pylint, v0.2.2
markdown-preview-pandoc, v0.0.14
markdown-table-formatter, v2.5.1
terminal-panel, v1.14.1
zotero-bibtex-autocomplete, v0.0.0

# Dev
autocomplete-plus, v2.3.0
```

**Comment by lierdakil** [comment]
Okay, figured out what causes it: Point with `row` and/or `column` being `String` instead of `Number`. Error message is very confusing, but error is mine, so I'll close this.
