### ISSUE TITLE
New Win7 install: Failed to load the editorconfig package

### ISSUE THREAD

**Issue by tomByrer** [atom/atom#7270]
Win7_64, installing v0.208.0 via zip, v0.209.0 via AtomSetup.exe, got same error both times.
Happens on every Atom startup.  No additional packages are added.

---
Failed to load the editorconfig package
Cannot find module 'emissary'

Hide Stack Trace
Error: Cannot find module 'emissary'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\t\AppData\Local\atom\app-0.209.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\t\.atom\packages\editorconfig\index.js:2:18)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\t\AppData\Local\atom\app-0.209.0\resources\app.asar\src\babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)

---
Package owner [punted the issue](https://github.com/sindresorhus/atom-editorconfig/issues/37) back here.

**Comment by thomasjo** [comment]
How did you install the package? In any case, navigate to the package folder from a terminal, and execute 'apm install'. That should resolve the issue.

**Comment by tomByrer** [comment]
I didn't 'install' the package; it is bundled with Atom [releases](https://github.com/atom/atom/releases).

**Comment by mnquintana** [comment]
`editorconfig` does not ship with Atom; it's a community package (you linked to the community package repo in the original post). You must have installed it at some point. Even if you re-downloaded Atom and re-installed it, if you had installed editorconfig at some point it would still be installed. Can you post the output of `apm links`?

**Comment by anettan** [comment]
Atom; it's a community package (you linked to the community package ??
 editorconfig at some point it would still be,,

**Comment by tomByrer** [comment]
`.atom` folder was not removed via uninstall.
