### ISSUE TITLE
Blank screen when launching Atom in development mode

### ISSUE THREAD

**Issue by schneiderderek** [atom/atom#7272]
When I launch Atom in development mode from the command line using `atom -d .` it displays a completely blank screen right after it loads. 

I only started seeing this issue when the developer tools were opening as Atom was opening. So, I have a hunch that this might be the issue. I tried closing the developer tools, then relaunching Atom, but that did not fix the issue. 

Here is a GIF of the issue: 
![example](https://cloud.githubusercontent.com/assets/2245041/8147085/0e8e1f6a-122c-11e5-85f1-e0071bf58d1d.gif)

I am running OSX 10.10.3 and Atom version 0.209.0

I launched Atom using `atom -d -l .` to capture logs and here is what showed up (I launched it several times):
```
6/14/15 12:18:19.199 AM Atom[51504]: App load time: 208ms
6/14/15 12:18:27.947 AM Atom[51271]: Cannot read property 'substr' of null
6/14/15 12:18:27.948 AM Atom[51271]: TypeError: Cannot read property 'substr' of null
    at AtomWindow.module.exports.AtomWindow.getLoadSettings (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-window.js:136:71)
    at AtomApplication.module.exports.AtomApplication.saveState (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:738:37)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:394:19)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
    at AtomApplication.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:271:20)
    at emitNone (events.js:67:13)
    at AtomApplication.emit (events.js:163:7)
    at AtomApplication.module.exports.AtomApplication.sendCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:512:22)
    at item.click (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/application-menu.js:226:45)
6/14/15 12:18:31.470 AM Atom[51599]: App load time: 357ms
6/14/15 12:18:35.286 AM Atom[51695]: App load time: 287ms
6/14/15 12:18:36.885 AM Atom[51599]: Cannot read property 'substr' of null
6/14/15 12:18:36.887 AM Atom[51599]: TypeError: Cannot read property 'substr' of null
    at AtomWindow.module.exports.AtomWindow.getLoadSettings (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-window.js:136:71)
    at AtomApplication.module.exports.AtomApplication.saveState (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:738:37)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:204:26)
    at EventEmitter.g (events.js:257:16)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
6/14/15 12:18:39.351 AM Atom[51599]: Cannot read property 'substr' of null
6/14/15 12:18:39.352 AM Atom[51599]: TypeError: Cannot read property 'substr' of null
    at AtomWindow.module.exports.AtomWindow.getLoadSettings (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-window.js:136:71)
    at AtomApplication.module.exports.AtomApplication.saveState (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:738:37)
    at BrowserWindow.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:188:26)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:491:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:86:23)
    at emitTwo (events.js:87:13)
6/14/15 12:18:43.646 AM Atom[51599]: Cannot read property 'substr' of null
6/14/15 12:18:43.647 AM Atom[51599]: TypeError: Cannot read property 'substr' of null
    at AtomWindow.module.exports.AtomWindow.getLoadSettings (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-window.js:136:71)
    at AtomApplication.module.exports.AtomApplication.saveState (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:738:37)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:394:19)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
6/14/15 12:18:43.717 AM Atom[51599]: Cannot read property 'substr' of null
6/14/15 12:18:43.718 AM Atom[51599]: TypeError: Cannot read property 'substr' of null
    at AtomWindow.module.exports.AtomWindow.getLoadSettings (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-window.js:136:71)
    at AtomApplication.module.exports.AtomApplication.saveState (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:738:37)
    at AtomApplication.module.exports.AtomApplication.removeWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:165:21)
    at BrowserWindow.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-window.js:193:41)
    at emitOne (events.js:82:20)
    at BrowserWindow.emit (events.js:166:7)
6/14/15 12:19:05.491 AM Atom[51829]: App load time: 354ms
6/14/15 12:19:12.706 AM Atom[51829]: Cannot read property 'substr' of null
6/14/15 12:19:12.709 AM Atom[51829]: TypeError: Cannot read property 'substr' of null
    at AtomWindow.module.exports.AtomWindow.getLoadSettings (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-window.js:136:71)
    at AtomApplication.module.exports.AtomApplication.saveState (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:738:37)
    at BrowserWindow.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:188:26)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
6/14/15 12:19:19.549 AM Atom[51829]: Cannot read property 'substr' of null
6/14/15 12:19:19.550 AM Atom[51829]: TypeError: Cannot read property 'substr' of null
    at AtomWindow.module.exports.AtomWindow.getLoadSettings (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-window.js:136:71)
    at AtomApplication.module.exports.AtomApplication.saveState (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:738:37)
    at BrowserWindow.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:188:26)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
6/14/15 12:19:35.470 AM Atom[51829]: Cannot read property 'substr' of null
6/14/15 12:19:35.470 AM Atom[51829]: TypeError: Cannot read property 'substr' of null
    at AtomWindow.module.exports.AtomWindow.getLoadSettings (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-window.js:136:71)
    at AtomApplication.module.exports.AtomApplication.saveState (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:738:37)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:394:19)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
    at AtomApplication.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:271:20)
    at emitNone (events.js:67:13)
    at AtomApplication.emit (events.js:163:7)
    at AtomApplication.module.exports.AtomApplication.sendCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:512:22)
    at item.click (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/application-menu.js:226:45)
6/14/15 12:19:43.026 AM Atom[52031]: App load time: 298ms
6/14/15 12:19:46.911 AM Atom[52031]: Invalid key 4 for ObjectsStore
6/14/15 12:19:46.912 AM Atom[52031]: Error: Invalid key 4 for ObjectsStore
    at ObjectsStore.remove (/Applications/Atom.app/Contents/Resources/atom.asar/browser/lib/objects-registry.js:38:15)
    at ObjectsRegistry.remove (/Applications/Atom.app/Contents/Resources/atom.asar/browser/lib/objects-registry.js:95:46)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:239:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:86:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)

```

Let me know if you guys need anything else!

**Comment by mnquintana** [comment]
Have you been hacking on Atom core, or developing a package?

**Comment by schneiderderek** [comment]
@mnquintana I was developing a package at the time. I tried disabling it and that did not fix the issue. However, I did notice that there was another package listed under the development section that i'm not sure how it got there. I assume it was from a mistyped `apm` command. After I disabled this 'rogue' package it seemed to fix the issue.

**Comment by mnquintana** [comment]
Thanks for the update @schneiderderek! Since it was that errant package causing this issue I'm going to close this out.

**Comment by david-levastre** [comment]
If you're using Windows, hiding the ".atom" directory will cause the error. Unhide it.
