### ISSUE TITLE
Uncaught TypeError: Cannot read property 'openScopes' of undefined

### ISSUE THREAD

**Issue by jellymann** [atom/atom#7285]
Steps to reproduce:

1. Open a project in atom
2. Open a bunch of files
3. Switch branches

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'openScopes' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

TypeError: Cannot read property 'openScopes' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:589:49)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:383:115)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:62:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:626:20)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:777:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:743:14)
  at TextBuffer.module.exports.TextBuffer.setTextViaDiff (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:478:19)
  at TextBuffer.module.exports.TextBuffer.reload (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1009:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1133:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:430:40
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -2:37.5.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -2:34.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:13.9.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -2:11.6.0 core:close (atom-text-editor.editor.is-focused)
     -2:05.6.0 core:move-left (atom-text-editor.editor.is-focused)
 18x -2:02.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:55.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "coffee-autocompile",
      "vim-mode"
    ],
    "projectHome": "/Users/daniel/Projects"
  },
  "editor": {
    "invisibles": {},
    "preferredLineLength": 120,
    "autoIndentOnPaste": false,
    "fontFamily": "Inconsolata-dz for Powerline",
    "lineHeight": 1.5,
    "showIndentGuide": true,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.0
autocomplete-ruby, v0.1.0
coffee-compile, v0.16.0
file-icons, v1.5.7
language-jade, v0.4.0
linter, v0.12.7
linter-coffeelint, v0.3.2
linter-ruby, v0.1.6
ruby-block, v0.3.3
ruby-slim, v0.2.0

# Dev
No dev packages
```

**Comment by Eschon** [comment]
Had this error today

1. Open Atom in project
2. Minimize Atom
3. Overwrite file in project with new version in finder
4. When I switched back to Atom the error was there

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'openScopes' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

TypeError: Cannot read property 'openScopes' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:589:49)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:383:115)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:62:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:626:20)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:777:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:743:14)
  at TextBuffer.module.exports.TextBuffer.setTextViaDiff (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:478:19)
  at TextBuffer.module.exports.TextBuffer.reload (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1009:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1133:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:430:40
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "image-view",
      "background-tips",
      "language-go",
      "language-less",
      "language-property-list",
      "language-todo",
      "language-toml",
      "spell-check",
      "bookmarks",
      "welcome",
      "autoflow",
      "markdown-preview",
      "go-to-line",
      "language-c",
      "language-csharp",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "package-generator",
      "linter-tidy"
    ]
  },
  "editor": {
    "invisibles": {},
    "softWrapAtPreferredLineLength": true,
    "showInvisibles": true,
    "scrollPastEnd": true
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v0.5.0
atom-ternjs, v0.6.4
color-picker, v2.0.7
linter, v1.0.2
linter-csslint, v0.0.13
linter-jscs, v1.12.0
linter-jshint, v0.1.6
linter-rubocop, v0.2.7
linter-xmllint, v0.0.6
pretty-json, v0.3.3
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by madelinecameron** [comment]
Got this today. It seems to only occur when I am editing a certain JSON file on a certain line. If I modify the file outside of Atom, it throws the error right when I save.

[Enter steps to reproduce below:]

Not entirely sure on the steps. Maybe I partly corrupted the file, not entirely sure.

**Atom Version**: 1.0.2
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'openScopes' of undefined

```
At C:\Users\madel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:745

TypeError: Cannot read property 'openScopes' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (C:\Users\madel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\tokenized-buffer.js:601:49)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (C:\Users\madel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\tokenized-buffer.js:383:115)
    at C:\Users\madel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\tokenized-buffer.js:62:24
    at Emitter.module.exports.Emitter.emit (C:\Users\madel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (C:\Users\madel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:626:20)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (C:\Users\madel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:777:16)
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\madel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:743:14)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\madel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\text-editor.js:1151:26)
    at C:\Users\madel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\text-editor.js:772:24
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\madel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\text-editor.js:2017:18)
```

### Commands

```
     -0:02.4.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "fontSize": 12,
    "softWrap": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
jslint, v1.4.0
jsonlint, v1.1.2
minimap, v4.12.0
pigments, v0.8.4

# Dev
No dev packages
```

**Comment by conmarap** [comment]
I got the same issue right now, as well.

[Enter steps to reproduce below:]

1. Open Atom through launcher
2. Wait for project to load (which takes a while)
3. After clicking on the "Keep waiting" button this happens.

**Atom Version**: 1.0.0
**System**: Ubuntu 15.04
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'openScopes' of undefined

```
At /usr/share/atom/resources/app.asar/src/tokenized-buffer.js:589

TypeError: Cannot read property 'openScopes' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:589:49)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:383:115)
    at /usr/share/atom/resources/app.asar/src/tokenized-buffer.js:62:24
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:626:20)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:777:16)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:743:14)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1152:26)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:785:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:1994:18)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-phpmd",
      "linter-csslint",
      "nuclide-file-tree",
      "language-jsx",
      "language-jsx",
      "language-jsx"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "scrollPastEnd": true,
    "showInvisibles": true,
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-erlang, v1.1.1
autocomplete-glsl, v0.2.3
color-picker, v2.0.9
file-watcher, v0.3.1
hyperclick, v0.0.24
linter, v1.3.4
linter-jshint, v1.1.5
minimap, v4.12.3
nuclide-code-format, v0.0.24
nuclide-diff-view, v0.0.24
nuclide-file-watcher, v0.0.24
nuclide-flow, v0.0.24
nuclide-hack, v0.0.24
nuclide-remote-projects, v0.0.24
nuclide-type-hint, v0.0.24
pigments, v0.11.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
@conmarap You're running an old version of Atom - mind updating to the latest (1.0.7) and seeing if you can reproduce this?

**Comment by conmarap** [comment]
@mnquintana Sure. I'll do that right now.

**Comment by conmarap** [comment]
@mnquintana After the upgrade it didn't happen, but when I hit `Ctrl + Alt + R` on I got this:

![image](https://cloud.githubusercontent.com/assets/939247/9307090/37518ca4-44ca-11e5-8094-fa80bcca12f1.png)

I'm not sure if this has been documented, though.

**Comment by mnquintana** [comment]
@conmarap Did you leave Atom open during the upgrade? Try quitting and restarting Atom.

**Comment by conmarap** [comment]
Yes, that's what I did. I had another window on a different workspace and forgot to close it; restarting helped.

**Comment by benogle** [comment]
Closing this as no one has seen it in a while.
