### ISSUE TITLE
Uncaught TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by vraravam** [atom/atom#7305]
This used to be in my init script:
```coffee
atom.workspace.observeTextEditors (editor) ->
  editor.onDidSave ->
    atom.commands.dispatch(atom.workspaceView.element, 'tree-view:reveal-active-file')
    atom.views.getView(editor).focus()
```
Till recently, it worked, but now, I'm unable to find the correct change. Please help

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At /usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:759

TypeError: Cannot read property 'element' of undefined
  at /Users/vijay/.atom/init.coffee:18:46
  at Emitter.module.exports.Emitter.emit (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:996:20)
  at TextBuffer.module.exports.TextBuffer.save (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace.js:594:35)
  at atom-workspace.atom.commands.add.core:save (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:317:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:05.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:05.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:04.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:04.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:02.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": true,
    "disabledPackages": [
      "language-c",
      "archive-view",
      "welcome",
      "jshint",
      "language-clojure",
      "language-coffee-script",
      "language-gfm",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-toml",
      "package-generator",
      "save-session",
      "linter-golint",
      "autocomplete-plus-async"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "coverage",
      "tmp/",
      "log/"
    ],
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "preferredLineLength": 170,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "invisibles": {},
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.5
auto-update-packages, v1.0.0
change-case, v0.6.0
coffee-compile, v0.16.1
file-icons, v1.5.7
git-tab-status, v1.9.2
highlight-line, v0.11.0
highlight-selected, v0.10.0
language-elixir, v0.5.1
language-rspec, v0.3.0
linter, v0.12.7
linter-csslint, v0.0.13
linter-jshint, v0.1.6
linter-less, v0.5.0
linter-rubocop, v0.2.7
linter-scss-lint, v1.0.4
minimap, v4.10.0
minimap-git-diff, v4.1.3
recent-files, v0.3.0
ruby-block-converter, v3.5.0
symbols-tree-view, v0.9.3
syntax-settings, v0.7.1
tabs-to-spaces, v0.11.0
tree-ignore, v0.2.6

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Could you try using `atom.views.getView(atom.workspace)` instead of `atom.workspaceView.element` and see if that works?

**Comment by vraravam** [comment]
Perfect - thanks, that worked. For those who are trying to do the same, here's the init.coffee script (this tries to reveal the file in the tree-view when the file is saved):
`atom.workspace.observeTextEditors (editor) ->
  editor.onDidSave -> handleEvents(editor)
  editor.onDidChangePath -> handleEvents(editor)

handleEvents = (editor) ->
  return if editor.getPath() is atom.config.getUserConfigPath()
  atom.commands.dispatch(atom.views.getView(atom.workspace), 'tree-view:reveal-active-file')
  atom.views.getView(editor).focus()
`

**Comment by PointedEars** [comment]
[Enter steps to reproduce:]

1. Start Atom, after X.org/KDE crashed, with 5 Atom windows restoring.
2. The window that has a .js file open in several panes (previously vertically split by `vim-mode-plus`) showed this error message while the windows were loading.

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At /usr/share/atom/resources/app/src/text-editor-component.js:1579

TypeError: Cannot read property 'element' of undefined
    at TextEditorComponent.didScrollDummyScrollbar (/usr/share/atom/resources/app/src/text-editor-component.js:1579:81)
```

### Commands

```
  3x -1:38.6.0 click (a.btn-issue.btn.btn-error)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-css-unit-converter 1.1.1 
atom-mysql-snippets 0.3.1 
atom-php-navigation 0.6.0 
atom-ternjs 0.18.3 
atom-x 0.4.0 
atomatigit 1.5.5 
autoclose-html 0.23.0 
autocomplete-awk 0.1.2 
autocomplete-bibtex 0.7.0 
autocomplete-clang 0.11.3 
autocomplete-html-entities 0.1.0 
autocomplete-paths 2.12.1 
autocomplete-php 0.3.7 
autocomplete-python 1.10.3 
autocomplete-xml 0.9.4 
autoupdate-packages 1.3.1 
block-comment 0.4.3 
busy-signal 1.4.3 
character-table 0.4.3 
clipboard-plus 0.5.1 
color-picker 2.2.5 
column-select 0.2.0 
compare-files 0.8.1 
css-snippets 1.1.0 
ctrl-last-tab 0.3.0 
data-atom 0.26.1 
docblockr 0.11.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
es6-javascript 1.0.0 
ex-mode 0.18.0 
filesize 3.0.0 
fixmyjs 1.4.1 
fold-comments 0.6.0 
git-blame 1.3.1 
git-clone 0.2.0 
git-control 0.9.0 
git-diff-details 1.4.0 
git-difftool 0.2.7 
git-go 1.0.5 
git-hide 1.0.0 
git-history 3.3.0 
git-log 0.4.1 
git-plus 7.10.0 
git-rebase 0.1.1 
git-status 0.3.4 
git-time-machine 1.5.9 
gitignore-snippets 0.2.5 
goto 1.8.3 
goto-definition 1.3.4 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
hyperclick-php 0.2.1 
indent-toggle-on-paste 0.1.3 
intentions 1.1.5 
iso8601-timestamp 0.1.1 
javascript-snippets 1.2.1 
js-hyperclick 1.11.1 
js-refactor 0.7.5 
language-apache 1.7.0 
language-awk 0.1.12 
language-babel 2.75.2 
language-diff 0.7.0 
language-gettext 0.6.1 
language-ini 1.19.0 
language-latex 1.1.1 
language-lua 0.9.11 
language-sql-mysql 0.3.1 
language-swift 0.5.0 
latex-autocomplete 1.0.0 
latex-completions 0.3.3 
latex-friend 0.0.11 
latex-hyperclick 0.2.0 
latexer 0.3.0 
latextools 0.8.5 
lcars-syntax 0.0.1 
less-autocompile 1.0.0 
less-than-slash 0.17.0 
line-count-status 0.0.3 
line-jumper 0.14.1 
linter 2.2.0 
linter-checkbashisms 0.1.5 
linter-chktex 1.3.1 
linter-csslint 2.0.0 
linter-htmlhint 1.3.4 
linter-jshint 3.1.6 
linter-less 2.6.0 
linter-mixed-indent 1.1.1 
linter-mypy 2.3.0 
linter-php 1.5.1 
linter-pylint 2.1.0 
linter-shellcheck 1.4.6 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
local-history 4.3.0 
MagicPython 1.0.12 
man 0.8.2 
merge-conflicts 1.4.5 
method-separator 0.2.0 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-hide 0.3.0 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.1 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.7 
multi-cursor 2.1.5 
multi-cursor-plus 1.2.0 
multi-file-open 0.1.1 
multirow-tabs 0.3.3 
navigate 0.1.17 
navigate-indent 0.1.0 
next-occurrence 0.5.0 
nuclide 0.260.0 
nuclide-format-js 0.0.41 
open-git-modified-files 0.2.4 
open-recent 5.0.0 
open-this 0.5.0 
pdf-view 0.59.0 
php-debug 0.2.5 
php-extract-method 0.2.1 
php-getters-setters 0.5.5 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
preview 0.17.0 
preview-inline 1.4.7 
project-folder 1.5.0 
project-view 0.6.2 
promote-folder-to-project 2.0.2 
punchclock 0.6.5 
python-isort 0.0.7 
python-tools 0.6.9 
qolor 0.4.2 
quantum-shell 0.7.1 
quick-query 0.12.2 
recent-projects 0.13.1 
refactor 0.11.5 
regex-tester 0.2.0 
remember-file-positions 0.2.3 
remote-edit 1.9.0 
revert-buffer 0.5.0 
script 3.18.0 
set-syntax 0.4.0 
seti-ui 1.9.0 
show-origin 0.2.0 
sloc 1.1.0 
sort-lines 0.18.0 
split-diff 1.5.1 
switch-header-source 0.22.1 
symbols-tree-nav 0.15.5 
symbols-tree-view 0.14.0 
term 0.2.4 
text-manipulation 0.6.0 
todo-show 2.1.0 
tool-bar 1.1.0 
tree-view-git-status 1.4.0 
up2date 0.1.2 
vim-mode-clipboard-plus 0.2.0 
vim-mode-plus 1.11.1 
w3c-validation 0.4.0 
wordcount 2.10.4 
xkcd-comics 0.3.0 
xml-tools 0.2.1 
Zen 0.18.0 
```
