### ISSUE TITLE
Uncaught Exception: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by curtiszimmerman** [atom/atom#7307]
Steps to reproduce:
1. Update to 0.209.0
2. Get deprecation message: "Style elements within text editors using the atom-text-editor::shadow selector or the .atom-text-editor.less file extension. If you want to target overlay elements, target them directly or as descendants of atom-overlay elements."
3. Attempt to split this link into another pane.

**Atom Version**: 0.209.0
**System**: Linux Mint
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At /usr/share/atom/resources/app.asar/src/item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
  at ItemRegistry.module.exports.ItemRegistry.addItem (/usr/share/atom/resources/app.asar/src/item-registry.js:11:15)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app.asar/src/pane-container.js:374:25)
  at /usr/share/atom/resources/app.asar/src/pane-container.js:357:19
  at /usr/share/atom/resources/app.asar/src/pane-container.js:127:16
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.didAddPane (/usr/share/atom/resources/app.asar/src/pane-container.js:315:27)
  at Pane.module.exports.Pane.setContainer (/usr/share/atom/resources/app.asar/src/pane.js:100:26)
  at PaneAxis.module.exports.PaneAxis.addChild (/usr/share/atom/resources/app.asar/src/pane-axis.js:142:13)
  at PaneAxis.module.exports.PaneAxis.insertChildAfter (/usr/share/atom/resources/app.asar/src/pane-axis.js:214:19)
  at Pane.module.exports.Pane.split (/usr/share/atom/resources/app.asar/src/pane.js:687:23)
  at Pane.module.exports.Pane.splitRight (/usr/share/atom/resources/app.asar/src/pane.js:653:19)
  at atom-pane.atom.commands.add.pane:split-right (/usr/share/atom/resources/app.asar/src/pane-element.js:270:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:148:33)
  at HTMLDocument.handler (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```
### Commands

```
     -0:03.6.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
```
### Config

``` json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "vim-mode",
      "language-config",
      "gofmt"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "fontSize": 11,
    "tabLength": 4,
    "invisibles": {},
    "showInvisibles": true,
    "softTabs": false
  }
}
```
### Installed Packages

``` coffee
# User
auto-indent, v0.5.0
autocomplete-clang, v0.7.0
color-picker, v2.0.4
go-plus, v3.3.11
language-docker, v1.1.3
linter, v0.12.7
linter-clang, v2.26.0
minimap, v4.10.0
monokai, v0.14.0
save-session, v0.15.5

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Confirmed on Ubuntu 15.04, Atom 0.210.0-7a80849.

However, should this be moved to deprecation-cop or stay in atom/atom?

**Comment by benogle** [comment]
This is probably a deprecation cop issue. It cant be split. I say move it.

**Comment by izuzak** [comment]
Also going to cc @nathansobo since he fixed the first instance of this problem for markdown preview back in https://github.com/atom/atom/issues/3976.
