### ISSUE TITLE
Uncaught Error - EACCES: permission denied

### ISSUE THREAD

**Issue by FlxAlbroscheit** [atom/atom#7321]
This issue has to do with a missing exception in atom's package 'autosave':
When being activated, I won't be able to close a file which is in read-only-mode. It seems like autosave tries to save it before closing the file-tab. However, as this is not possible, I receive an error-message ("Uncaught Error: EACCES: permission denied, open '/var/www/html/drupal/sites/default/settings.php'") which will keep on disturbing me till deactivating 'autosave' manually.

**Log:**

```
At /usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:376

Error: EACCES: permission denied, open '/var/www/html/drupal/sites/default/settings.php'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:264:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:362:21)
    at File.module.exports.File.writeSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:336:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:992:17)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
```

**Comment by kevinsawicki** [comment]
This was fixed by https://github.com/atom/autosave/pull/41 and has been released in 1.0.1
