### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by lczech** [atom/atom#7352]
[Enter steps to reproduce below:]

Cannot reproduce, but maybe the stack trace is still helpful. If not, this issue can also just be closed.

I did something like:
1. Pasted some code.
2. Used `ctrl + ]` for adjusting the indention.
3. Pressed something like `ctrl + z` and `x` at the same time (by accident).

The current line was cut (so probably `ctrl+x` happend first), but using `ctrl+z` did not restore it, instead I received the error message.

Solved it by re-pasting the code and paying attention to not press too many buttons at the same time ;-)

**Atom Version**: 0.210.0
**System**: Ubuntu 14.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /usr/share/atom/resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:881

TypeError: Cannot read property '0' of null
    at /usr/share/atom/resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:881:18
    at Array.forEach (native)
    at _.each._.forEach (/usr/share/atom/resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:79:11)
    at Object._.defaults (/usr/share/atom/resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:878:5)
    at History.module.exports.History.popUndoStack (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/history.js:94:11)
    at TextBuffer.module.exports.TextBuffer.undo (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:709:30)
    at TextEditor.module.exports.TextEditor.undo (/usr/share/atom/resources/app.asar/src/text-editor.js:1142:19)
    at TextEditor.atom.commands.add.stopEventPropagation.core:undo (/usr/share/atom/resources/app.asar/src/text-editor-element.js:320:19)
    at atom-text-editor.newCommandListeners.(anonymous function) (/usr/share/atom/resources/app.asar/src/text-editor-element.js:288:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
```

### Commands

```
     -0:57.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:56.4.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:55.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:55 core:save (atom-text-editor.editor.is-focused)
     -0:45.6.0 core:cut (atom-text-editor.editor.is-focused)
  2x -0:44.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:41.4.0 core:paste (atom-text-editor.editor.is-focused)
     -0:38.4.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
  2x -0:33.3.0 editor:indent-selected-rows (atom-text-editor.editor.is-focused)
     -0:28.6.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:28.6.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:16.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.5.0 core:cut (atom-text-editor.editor.is-focused)
  7x -0:12.5.0 core:undo (atom-text-editor.editor.is-focused)
 31x -0:02.8.0 core:redo (atom-text-editor.editor.is-focused)
  2x -0:01.2.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "linter",
      "simple-drag-drop-text",
      "drag-drop-text",
      "language-c",
      "atom-beautify",
      "autocomplete-python",
      "Sublime-Style-Column-Selection",
      "word-jumper",
      "linter-clang"
    ],
    "themes": [
      "one-dark-ui",
      "lucas-dark-syntax"
    ],
    "destroyEmptyPanes": false
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "preferredLineLength": 100,
    "softWrap": true,
    "tabLength": 4,
    "fontSize": 11
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.1.2
autocomplete-clang, v0.7.0
block-travel, v1.0.2
docblockr, v0.7.2
hex, v0.6.2
highlight-line, v0.11.0
highlight-selected, v0.10.1
language-cmake, v0.1.4
language-cpp, v0.0.1
lucas-dark-syntax, v0.0.0
minimap, v4.10.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report, @lczech. :zap: 

:wave: @maxbrunsfeld -- do you :eyes: anything in that stack trace which might indicate what went down? Pinging you because this happened in `popUndoStack` but not sure if some package might caused this somehow.

**Comment by maxbrunsfeld** [comment]
I think this will be fixed in 1.0.3.

**Comment by andrewufrank** [comment]
i pasted something and then asked for a buil-project (stack). 

the copy stacktrace to clipboard seems not to work. i wonder if this is related? 
i guess this is just a reminder that this error message can still occur in 1.14.3.

**Comment by qiujianzhong** [comment]
看了一下控制台，提示源码错误的地方，得知是日期格式问题。
然后恢复了后台--系统--通用设置--高级设置--日期相关的进行恢复，开启sprint正常。
