### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 20)

### ISSUE THREAD

**Issue by tejainece** [atom/atom#7398]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 20)

```
At C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\q\q.js:128

TypeError: Invalid Point: (NaN, 20)
  at Function.module.exports.Point.assertValid (C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\text-buffer\lib\point.js:65:15)
  at TextBuffer.module.exports.TextBuffer.clipPosition (C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:956:13)
  at MarkerStore.module.exports.MarkerStore.setMarkerRange (C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\text-buffer\lib\marker-store.js:304:29)
  at Marker.module.exports.Marker.update (C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\text-buffer\lib\marker.js:324:20)
  at Marker.module.exports.Marker.setHeadPosition (C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\text-buffer\lib\marker.js:143:19)
  at Marker.module.exports.Marker.setHeadBufferPosition (C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\src\marker.js:175:32)
  at C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\src\cursor.js:136:31
  at Cursor.module.exports.Cursor.changePosition (C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\src\cursor.js:683:7)
  at Cursor.module.exports.Cursor.setBufferPosition (C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\src\cursor.js:134:19)
  at C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\src\text-editor.js:1338:23
  at TextEditor.module.exports.TextEditor.moveCursors (C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\src\text-editor.js:1571:9)
  at TextEditor.module.exports.TextEditor.setCursorBufferPosition (C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\src\text-editor.js:1337:19)
  at C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\src\workspace.js:485:20
  at _fulfilled (C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\q\q.js:794:54)
  at self.promiseDispatch.done (C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\q\q.js:823:30)
  at Promise.promise.promiseDispatch (C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\q\q.js:756:13)
  at C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\q\q.js:564:44
  at flush (C:\Users\seragud\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\q\q.js:110:17)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -1:36.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "behave-theme"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-dart, v0.7.2
behave-theme, v1.5.0
go-find-references, v1.2.3
go-plus, v3.3.12
go-rename, v0.3.0
go-runtime, v0.2.0

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
Are you able to reproduce in safe mode? `atom --safe`
