### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/ferge/Library/Application Suppor...

### ISSUE THREAD

**Issue by fehrmanns** [atom/atom#7399]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/ferge/Library/Application Support/com.github.atom.ShipIt/update.0slQICW'

```
At ATOM_SHELL_ASAR.js:50

Error: ENOENT: no such file or directory, lstat '/Users/ferge/Library/Application Support/com.github.atom.ShipIt/update.0slQICW'
    at Error (native)
    at fs.lstatSync (fs.js:836:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:170:16)
    at realpathSync (fs.js:1439:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:253:24)
    at tryFile (module.js:122:15)
    at Function.Module._findPath (module.js:162:18)
    at Module._resolveFilename (module.js:326:25)
    at Function.Module._resolveFilename (/Users/ferge/Library/Application Support/com.github.atom.ShipIt/update.0slQICW/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (module.js:380:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @fehrmanns, could you please share what you were doing when this happened?  Thanks.

/cc @jspahrsummers

**Comment by fehrmanns** [comment]
I was trying to open a README.md via 'mouse right click context menu'.

**Comment by 50Wliu** [comment]
This was 'fixed' for a while by atom/notifications#62, but then the stacktrace length was increased, which led to the appearance of absolute paths.

/cc @joshaber

**Comment by 50Wliu** [comment]
From the few issues that have repro steps, it seems like this can happen when there's two different versions of Atom running at the same time.

**Comment by blhagadorn** [comment]
Also reproduced this error

Steps:

1.Downloaded a new version of Atom 1.2.3
2.Already had an older version of Atom 1.2.0 with already open files (believe), kept on Dock
3.Opened a shell script in finder and chose "Open As" Atom 1.2.3 instead of the usual, I believe the 1.2.0 was in my Applications folder and Atom 1.2.3 was in my downloads for some reason, not sure why
4. Nothing but empty lines on the file, code appears for a second in all files in the directory (an Xcode project), got error

**Comment by michelecos** [comment]
I had an error today after launching the second instance of Atom. I activated a markdown preview and got the error with the following stack frame.
Both instances of Atom where of the same release. I made sure that there is no other Atom in the system, with the exception of Atom beta. Worth noting: I had two green Atom icons in the dock, something that I tried to reproduce without success, but happens occasionally. In normal conditions, I can have many Atom windows open with a single dock icon.

[Enter steps to reproduce below:]

1. launch second copy of atom from command line with "open -a atom ."
2. navigate to an .md file
3. hit the keys to activate rendering


**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/michele/Library/Application Support/com.github.atom.ShipIt/update.W2M9a0q'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/michele/Library/Application Support/com.github.atom.ShipIt/update.W2M9a0q'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/michele/Library/Application Support/com.github.atom.ShipIt/update.W2M9a0q/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
```

### Commands

```
     -0:58.6.0 tree-view:collapse-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -0:57.2.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:54.8.0 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:53.8.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:53.4.0 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:52.2.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:51.8.0 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:51.2.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:50 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:43.9.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -0:28.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:18.9.0 markdown-preview:preview-file (span.name.icon.icon-file-text)
     -0:00.0 markdown-preview:toggle (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "northem-dark-atom-ui",
      "atom-monokai"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

Michele Costabile
michelecos@yahoo.com

**Comment by joshaber** [comment]
@blhagadorn @michelecos When you got this error, did it resolve after quitting and re-opening Atom? Or did you have to do anything else to resolve it?

**Comment by blhagadorn** [comment]
@joshaber It resolved after quitting and re-opening Atom.  I haven't been able to reproduce this error.

**Comment by kmyl** [comment]
For me the error was generated by .atom/storage/applications.json , which contains last opened files/folders. Deleting that file solved my problem

**Comment by BlueAccords** [comment]
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/BlueAccords/Documents/Atom.app'

error occurred after a fresh download(potentially corrupted? didn't check checksums/hashes. The internet connection i'm using has trouble loading pages constantly). And trying to open the theme picker. Quitting and restarting atom and going back to the welcome page and trying to open the theme picker afterwards solved it.

``` 
Error: ENOENT: no such file or directory, lstat '/Users/BlueAccords/Documents/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/lib/parse.js:4:18)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/lib/cheerio.js:6:13)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/index.js:5:28)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/roaster/node_modules/task-lists/lib/index.js:4:11)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/roaster/lib/roaster.js:14:15)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/roaster/lib/roaster.js:73:4)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-readme-view.js:8:13)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-readme-view.js:72:4)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:26:23)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:441:4)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:24:23)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:369:4)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at createSettingsView (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:20:22)
    at /Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:71:28
    at Workspace.module.exports.Workspace.openURIInPane (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/workspace.js:460:22)
    at Workspace.module.exports.Workspace.open (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/workspace.js:399:19)
    at HTMLButtonElement.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/welcome/lib/guide-view.js:302:31)
    at HTMLButtonElement.jQuery.event.dispatch (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)

```

**Comment by joshaber** [comment]
#9559 is favored rollup issue these days.
