### ISSUE TITLE
Cannot read property 'getTokenIterator' of undefined

### ISSUE THREAD

**Issue by flaviolaino** [atom/atom#7400]
I've just close a css file.

```
TypeError: Cannot read property 'getTokenIterator' of undefined
at TokenizedBuffer.module.exports.TokenizedBuffer.scopeDescriptorForPosition (C:\Users\flaviolaino\AppData\Local\atom\app-0.211.0\resources\app.asar\src\tokenized-buffer.js:660:42)
at DisplayBuffer.module.exports.DisplayBuffer.scopeDescriptorForBufferPosition (C:\Users\flaviolaino\AppData\Local\atom\app-0.211.0\resources\app.asar\src\display-buffer.js:1135:35)
at TextEditor.module.exports.TextEditor.scopeDescriptorForBufferPosition (C:\Users\flaviolaino\AppData\Local\atom\app-0.211.0\resources\app.asar\src\text-editor.js:2281:33)
at EditorLinter.lint (C:\Users\flaviolaino\.atom\packages\linter\lib\editor-linter.coffee:63:22)
at C:\Users\flaviolaino\.atom\packages\linter\lib\linter-plus.coffee:31:35
at Emitter.module.exports.Emitter.emit (C:\Users\flaviolaino\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
at C:\Users\flaviolaino\AppData\Local\atom\app-0.211.0\resources\app.asar\src\pane-container.js:343:34
at Emitter.module.exports.Emitter.emit (C:\Users\flaviolaino\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
at Pane.module.exports.Pane.setActiveItem (C:\Users\flaviolaino\AppData\Local\atom\app-0.211.0\resources\app.asar\src\pane.js:234:22)
at Pane.module.exports.Pane.activateItem (C:\Users\flaviolaino\AppData\Local\atom\app-0.211.0\resources\app.asar\src\pane.js:298:21)
at Pane.module.exports.Pane.activateItemAtIndex (C:\Users\flaviolaino\AppData\Local\atom\app-0.211.0\resources\app.asar\src\pane.js:292:19)
at Pane.module.exports.Pane.activatePreviousItem (C:\Users\flaviolaino\AppData\Local\atom\app-0.211.0\resources\app.asar\src\pane.js:263:21)
at Pane.module.exports.Pane.removeItem (C:\Users\flaviolaino\AppData\Local\atom\app-0.211.0\resources\app.asar\src\pane.js:372:16)
at Pane.module.exports.Pane.destroyItem (C:\Users\flaviolaino\AppData\Local\atom\app-0.211.0\resources\app.asar\src\pane.js:442:16)
at HTMLDivElement.<anonymous> (C:\Users\flaviolaino\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:236:22)
at space-pen-ul.jQuery.event.dispatch (C:\Users\flaviolaino\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
at space-pen-ul.elemData.handle (C:\Users\flaviolaino\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

**Comment by izuzak** [comment]
@flaviolaino Did that trigger a red notification in the top right corner of Atom? It should have, and that notification should have allowed you to create an issue automatically with lots more debugging information.

Can you reliably reproduce the problem?
