### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by unwitting** [atom/atom#7409]
1. Using package `git-plus`
2. Cmd-Shift-P
3. Git checkout
4. Choose branch

Sporadic, not always reproducible.

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, read

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

Error: EISDIR: illegal operation on a directory, read
  at Error (native)
  at Object.fs.readSync (fs.js:596:19)
  at Object.fs.readFileSync (fs.js:428:28)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at File.module.exports.File.readSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:248:36)
  at TextBuffer.module.exports.TextBuffer.updateCachedDiskContentsSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1019:85)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1123:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:430:40
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)

```
### Commands

```
  2x -0:33.6.0 core:close (atom-text-editor.editor.is-focused)
     -0:30.6.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -0:22.2.0 core:close (div.settings-view.pane-item)
     -0:20.4.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:19.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:19.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:18.7.0 command-palette:toggle (atom-pane.pane.active)
  4x -0:15.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:13.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.3.0 git-plus:diff-all (atom-pane.pane.active)
     -0:12.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.3.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  4x -0:06.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:05.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.5.0 git-plus:checkout (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:05.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "followSymlinks": false
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {},
    "fontFamily": "Bitstream Vera Sans Mono",
    "lineHeight": 1.4,
    "showInvisibles": true,
    "showIndentGuide": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-cli-diff, v1.0.0
color-picker, v2.0.7
fonts, v0.4.2
git-plus, v5.2.1
minimap, v4.10.0
project-view, v0.1.2
save-session, v0.15.5

# Dev
No dev packages
```

**Comment by ilikebits** [comment]
I'm also seeing this issue when using GVFS to edit files remotely.

**Comment by Yajo** [comment]
Me too in GFVS remote file.
