### ISSUE TITLE
linter-eslint triggers "Cannot read property 'match' of undefined"

### ISSUE THREAD

**Issue by atombender** [atom/atom#7418]
`linter-eslint` causes this error inside `TokenizedBuffer`:

```
/Users/alex/.atom/packages/linter-eslint/lib/linter-eslint.coffee:136 [Linter-ESLint] error while linting file
/Users/alex/.atom/packages/linter-eslint/lib/linter-eslint.coffee:137 Cannot read property 'match' of undefined
/Users/alex/.atom/packages/linter-eslint/lib/linter-eslint.coffee:138 TypeError: Cannot read property 'match' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:647:23)
  at DisplayBuffer.module.exports.DisplayBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:818:35)
  at TextEditor.module.exports.TextEditor.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2220:33)
  at TextEditor.module.exports.TextEditor.indentationForBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2192:19)
  at /Users/alex/.atom/packages/linter-eslint/lib/linter-eslint.coffee:108:44
  at Array.map (native)
  at /Users/alex/.atom/packages/linter-eslint/lib/linter-eslint.coffee:104:18
  at exports.allowUnsafeNewFunction (/Users/alex/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at Object.provider.lint (/Users/alex/.atom/packages/linter-eslint/lib/linter-eslint.coffee:101:13)
  at /Users/alex/.atom/packages/linter/lib/editor-linter.coffee:79:24
  at /Users/alex/.atom/packages/linter/lib/editor-linter.coffee:78:25
  at Set.forEach (native)
  at EditorLinter._lint (/Users/alex/.atom/packages/linter/lib/editor-linter.coffee:72:26)
  at EditorLinter.lint (/Users/alex/.atom/packages/linter/lib/editor-linter.coffee:66:18)
  at /Users/alex/.atom/packages/linter/lib/editor-linter.coffee:22:37
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1183:25
```

**Comment by thomasjo** [comment]
Please reopen this on the [linter-eslint repo](https://github.com/AtomLinter/linter-eslint).

**Comment by Arcanemagus** [comment]
Actually @thomasjo this is an issue with internal functions called by `TextEditor.indentationForBufferRow` not properly checking return values.

Specifically `TextEditor.indentationForBufferRow()` calls `DisplayBuffer.indentLevelForLine()` which calls `TokenizedBuffer.indentLevelForLine()` which attempts to match the line against a regex and assumes that it gets a match (Which it looks like it would fail if the line has no indentation).

Do you want a separate issue filed that specifically mentions that?
