### ISSUE TITLE
"System.OutOfMemoryException" when installing on windows

### ISSUE THREAD

**Issue by loivis** [atom/atom#7440]
latest atom setup on windows 7 enterprise sp1.

![image](https://cloud.githubusercontent.com/assets/5162663/8371800/9332c6d0-1c0e-11e5-83c4-cdd493407106.png)

there's "System.OutOfMemoryException" exception in log from SquirrelTemp. But task manager shows over 3G memory available.

![image](https://cloud.githubusercontent.com/assets/5162663/8371841/519ec3d0-1c0f-11e5-9a44-edf441897930.png)

```
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\x\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\x\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\x\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\x\AppData\Local\atom\app-1.0.0
IEnableLogger: Failed to install package to app dir: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.ToArray()
   at NuGet.StreamExtensions.ToStreamFactory(Stream stream)
   at NuGet.ZipPackageFile..ctor(PackagePart part)
   at NuGet.ZipPackage.<GetFilesNoCache>b__12(PackagePart part)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.ZipPackage.GetFilesNoCache()
   at NuGet.ZipPackage.GetFilesBase()
   at NuGet.LocalPackage.GetFiles()
   at NuGet.PackageExtensions.GetFiles(IPackage package, String directory)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__8e.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
```

**Comment by loivis** [comment]
there're files in "C:\Users\x\AppData\Local\atom\app-1.0.0".
![image](https://cloud.githubusercontent.com/assets/5162663/8371889/36b31520-1c10-11e5-82a9-8fc47f6abd4e.png)

atom.exe is executable here.
![image](https://cloud.githubusercontent.com/assets/5162663/8371912/8012ed12-1c10-11e5-8de6-1b58351ae1d4.png)

**Comment by shendaras** [comment]
I also have this problem with the Windows installer.  I'm running Windows 8.1.  I tried the installer using my local user as well as Administrator with no change.  The log messages appear to be the same.  I have 7Gb of free memory, around 50%, unused. 

```
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\x\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\x\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\x\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\x\AppData\Local\atom\app-1.0.0
IEnableLogger: Failed to install package to app dir: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.ToArray()
   at NuGet.StreamExtensions.ToStreamFactory(Stream stream)
   at NuGet.ZipPackageFile..ctor(PackagePart part)
   at NuGet.ZipPackage.<GetFilesNoCache>b__12(PackagePart part)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.ZipPackage.GetFilesNoCache()
   at NuGet.ZipPackage.GetFilesBase()
   at NuGet.LocalPackage.GetFiles()
   at NuGet.PackageExtensions.GetFiles(IPackage package, String directory)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__8e.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
```

**Comment by gcollombet** [comment]
+1

**Comment by kevinsawicki** [comment]
Atom just upgraded the auto-update/installer library used on Windows.

Can people try again using Atom 1.0.4+ from https://atom.io and see if this is still happening on newer versions?

**Comment by loivis** [comment]
great! no issue with the new installer. starting atom with windows~

**Comment by kevinsawicki** [comment]
> great! no issue with the new installer. 

Great, closing this out for now, can reopen if this starts happening again.

**Comment by paulcbetts** [comment]
This is permafixed in https://github.com/Squirrel/Squirrel.Windows/pull/403

**Comment by rossipedia** [comment]
I'm getting this now on Windows 10, with installer version 1.0.9 :(

**Comment by paulcbetts** [comment]
@rossipedia Delete %LocalAppData%\atom and try again

**Comment by rossipedia** [comment]
I've done that several times, no success.
