### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 2 is larger than or eq...

### ISSUE THREAD

**Issue by intfloat** [atom/atom#7464]
[Enter steps to reproduce below:]
1. add a project folder to atom
2. double click a text file with UTF-16LE encoding

**Atom Version**: 1.0.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core
### Stack Trace

Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 2 is larger than or equal to the node's length (1).

```
At /Users/air/Desktop/Atom.app/Contents/Resources/app.asar/src/tile-component.js:444

Error: Failed to execute 'setEnd' on 'Range': The offset 2 is larger than or equal to the node's length (1).
    at Error (native)
    at TileComponent.module.exports.TileComponent.measureCharactersInLine (/Users/air/Desktop/Atom.app/Contents/Resources/app.asar/src/tile-component.js:444:33)
    at TileComponent.module.exports.TileComponent.measureCharactersInNewLines (/Users/air/Desktop/Atom.app/Contents/Resources/app.asar/src/tile-component.js:398:16)
    at /Users/air/Desktop/Atom.app/Contents/Resources/app.asar/src/lines-component.js:157:23
    at DisplayBuffer.module.exports.DisplayBuffer.batchCharacterMeasurement (/Users/air/Desktop/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:572:7)
    at TextEditor.module.exports.TextEditor.batchCharacterMeasurement (/Users/air/Desktop/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2718:33)
    at TextEditorPresenter.module.exports.TextEditorPresenter.batchCharacterMeasurement (/Users/air/Desktop/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1301:18)
    at LinesComponent.module.exports.LinesComponent.measureCharactersInNewLines (/Users/air/Desktop/Atom.app/Contents/Resources/app.asar/src/lines-component.js:151:29)
    at TextEditorComponent.module.exports.TextEditorComponent.readAfterUpdateSync (/Users/air/Desktop/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:250:29)
    at /Users/air/Desktop/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61
```
### Commands

```
     -1:02.2.0 application:add-project-folder (ul.list-inline.tab-bar.inset-panel)
  2x -0:52.8.0 encoding-selector:show (atom-text-editor.editor)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
/cc @maxbrunsfeld @nathansobo 

Also https://github.com/atom/atom/issues/7465
