### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 501 is larger than or ...

### ISSUE THREAD

**Issue by cs0ip** [atom/atom#7465]
[Enter steps to reproduce below:]
1. open libsteam_api.so
2. scroll

**Atom Version**: 1.0.0
**System**: Linux Mint
**Thrown From**: Atom Core
### Stack Trace

Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 501 is larger than or equal to the node's length (500).

```
At /opt/atom/resources/app.asar/src/tile-component.js:444

Error: Failed to execute 'setEnd' on 'Range': The offset 501 is larger than or equal to the node's length (500).
    at Error (native)
    at TileComponent.module.exports.TileComponent.measureCharactersInLine (/opt/atom/resources/app.asar/src/tile-component.js:444:33)
    at TileComponent.module.exports.TileComponent.measureCharactersInNewLines (/opt/atom/resources/app.asar/src/tile-component.js:398:16)
    at /opt/atom/resources/app.asar/src/lines-component.js:157:23
    at DisplayBuffer.module.exports.DisplayBuffer.batchCharacterMeasurement (/opt/atom/resources/app.asar/src/display-buffer.js:572:7)
    at TextEditor.module.exports.TextEditor.batchCharacterMeasurement (/opt/atom/resources/app.asar/src/text-editor.js:2718:33)
    at TextEditorPresenter.module.exports.TextEditorPresenter.batchCharacterMeasurement (/opt/atom/resources/app.asar/src/text-editor-presenter.js:1301:18)
    at LinesComponent.module.exports.LinesComponent.measureCharactersInNewLines (/opt/atom/resources/app.asar/src/lines-component.js:151:29)
    at TextEditorComponent.module.exports.TextEditorComponent.readAfterUpdateSync (/opt/atom/resources/app.asar/src/text-editor-component.js:250:29)
    at /opt/atom/resources/app.asar/src/text-editor-component.js:3:61
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
language-rust, v0.4.3
language-scala, v1.1.3
rust-api-docs-helper, v0.5.1

# Dev
No dev packages
```

**Comment by nathansobo** [comment]
@mnquintana Were you able to reproduce this one?

**Comment by mnquintana** [comment]
Hmm no I couldn't reproduce either one yet.

**Comment by cs0ip** [comment]
Addition:
Try that file https://mega.co.nz/#!adEnGSqS!a2n56eNO4a0HYzVJx2wngzh33RGqJas2kETJ9CSGPsY
and scroll more than 1000 lines

**Comment by izuzak** [comment]
@cs0ip I just tried scrolling completely through that file and wasn't able to reproduce the problem on OSX. Does this happen every time for you?

**Comment by cs0ip** [comment]
Yes. The error occurs every time on my Linux Mint 17.1 Mate x64.

**Comment by izuzak** [comment]
Thanks, @cs0ip. Just to double-check -- does it happen in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) as well? Also, which encoding do you see in the bottom right corner? Do you have soft wrap turned on or off? Which font are you using? 

@nathansobo Any other questions we can ask to help investigate this?

**Comment by cs0ip** [comment]
Soft wrap is off. Encoding: utf-8.
A couple of screenshots (normal & safe mode):
http://s13.postimg.org/5jq9uo0dj/normal.png
http://s10.postimg.org/h90tug1ux/safe.png

**Comment by nathansobo** [comment]
At this point, maybe @sc0ip you could open the dev tools, set a breakpoint for uncaught exceptions, then  paste us the actual content of the node? We may need to insert some kind of assertion for this scenario and gather more data.

**Comment by cs0ip** [comment]
The results of my debugging )
http://s30.postimg.org/ce28fhgzl/console.png
