### ISSUE TITLE
Failed to activate the Sublime-Style-Column-Selection package

### ISSUE THREAD

**Issue by nemoDreamer** [atom/atom#7471]
1. Opened Atom 1.0 for the first time

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the Sublime-Style-Column-Selection package

```
At Cannot read property 'eachEditorView' of undefined

TypeError: Cannot read property 'eachEditorView' of undefined
    at Object.module.exports.activate (/Users/philip/Google%20Drive/Syncing/Atom/atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:33:47)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "cute-cursor",
      "coffee-lint",
      "coffee-compile",
      "coffee-refactor",
      "scope-inspector",
      "aural-coding",
      "css-color-highlighting"
    ],
    "themes": [
      "spacegray-dark-ui",
      "base16-ocean-dark-spacegray-lighter-invisibles"
    ],
    "audioBeep": false,
    "destroyEmptyPanes": false
  },
  "editor": {
    "fontFamily": "\"Andale Mono\"",
    "fontSize": 12,
    "preferredLineLength": 120,
    "softWrapAtPreferredLineLength": true,
    "useShadowDOM": false,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
Sublime-Style-Column-Selection, v1.1.3
autocomplete-plus, v1.1.0
base16-ocean-dark-spacegray-lighter-invisibles, v0.1.0
language-apache, v1.2.0
language-coldfusion, v0.2.0
language-freebasic, v0.0.10
language-haml, v0.14.0
minimap-git-diff, v3.1.0
project-manager, v1.14.1
spacegray-dark-ui, v0.5.0

# Dev
No dev packages
```

**Comment by nemoDreamer** [comment]
My init.coffee, whic worked in 0.x:

```coffeescript
# Your init script
#
# Atom will evaluate this file each time a new window is opened. It is run
# after packages are loaded/activated and after the previous editor state
# has been restored.
#
# An example hack to make opened Markdown files always be soft wrapped:

path = require 'path'

atom.workspaceView.eachEditorView (editorView) ->
  editor = editorView.getEditor()
  if path.extname(editor.getPath()) is '.md'
    editor.setSoftWrap(true)
```

**Comment by nemoDreamer** [comment]
Emptied out my config file, still seeing issue.

Closing this, as it seems to be a Sublime-Style-Column-Selection package issue now that all deprecations have been updated. (https://github.com/bigfive/atom-sublime-select/issues/60)
