### ISSUE TITLE
Uncaught InvalidStateError: Failed to execute 'dispatchEvent' on 'EventTarget': The event provide...

### ISSUE THREAD

**Issue by colin-kiegel** [atom/atom#7489]
[Enter steps to reproduce below:]

1. edit 'keymaps.cson'
```
'atom-text-editor:not(.mini)':
  'alt': ''
```
2. save
3. press 'alt'

results in error below - but despite this error, everything is still working fine 

note: this is related to https://github.com/AtomLinter/Linter/issues/648#issuecomment-116090522

**Atom Version**: 1.0.0
**System**: Ubuntu 15.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught InvalidStateError: Failed to execute 'dispatchEvent' on 'EventTarget': The event provided is uninitialized.

```
At /usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520

Error: Failed to execute 'dispatchEvent' on 'EventTarget': The event provided is uninitialized.
  at Error (native)
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
  3x -0:20.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:18.8.0 core:paste (atom-text-editor.editor.is-focused)
  3x -0:18.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:16 core:move-down (atom-text-editor.editor.is-focused)
     -0:14.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:13.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:12.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:11.6.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:11.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:08.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "vim-mode",
      "linter",
      "build"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "softWrap": true,
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
keyboard-localization, v1.4.3
language-rust, v0.4.3
minimap, v4.10.0
racer, v0.15.2
rust-api-docs-helper, v0.5.1

# Dev
No dev packages
```

**Comment by leonadler** [comment]
@colin-kiegel You can try this:
```cson
'atom-text-editor:not(.mini)':
  'alt': 'native!'
```

**Comment by colin-kiegel** [comment]
ok, great that's working - but still I think this error should probably be caught. :-)

**Comment by rumpelsepp** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: "Arch Linux"
**Thrown From**: Atom Core


### Stack Trace

Uncaught InvalidStateError: Failed to execute 'dispatchEvent' on 'EventTarget': The event provided is uninitialized.

```
At /usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524

Error: Failed to execute 'dispatchEvent' on 'EventTarget': The event provided is uninitialized.
  at Error (native)
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:25.6.0 git-projects:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:19.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
  2x -0:19.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:18 git-projects:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
  3x -0:14.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:14.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:12.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:12.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:11.2.0 git-projects:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
  3x -0:06.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:06.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:06.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:06.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:06.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:06.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:05.0 git-projects:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "spell-check",
      "keyboard-localization"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "CamingoCode, Liberation Mono, DejaVu Sans Mono, monospace",
    "tabLength": 4,
    "scrollPastEnd": true,
    "showInvisibles": true,
    "fontSize": 16
  }
}
```

### Installed Packages

```coffee
# User
atom-fuzzy-grep, v0.5.0
autocomplete-python, v0.5.3
file-icons, v1.6.9
git-plus, v5.4.7
git-projects, v1.15.0
language-asciidoc, v0.11.1
language-latex, v0.6.1
language-restructuredtext, v0.7.0
minimap, v4.13.2
minimap-git-diff, v4.1.8
tasks, v2.4.0
vim-mode, v0.58.0

# Dev
No dev packages
```
