### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setFlexScale' of undefined

### ISSUE THREAD

**Issue by spongecattle** [atom/atom#7509]
Reproduce steps below then this error will occure

1. Close all tabs in pane
2. Error: Uncaught TypeError: Cannot read property 'setFlexScale' of undefined pops up

**Atom Version**: 1.0.0
**System**: ChaletOS 14.04.2 (Ubuntu 14.04 LTS Distribution)
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'setFlexScale' of undefined

```
At /usr/share/atom/resources/app.asar/src/pane-axis.js:220

TypeError: Cannot read property 'setFlexScale' of undefined
  at PaneAxis.module.exports.PaneAxis.reparentLastChild (/usr/share/atom/resources/app.asar/src/pane-axis.js:220:16)
  at PaneAxis.module.exports.PaneAxis.removeChild (/usr/share/atom/resources/app.asar/src/pane-axis.js:186:21)
  at /usr/share/atom/resources/app.asar/src/pane-axis.js:229:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.destroyed (/usr/share/atom/resources/app.asar/src/pane.js:632:20)
  at Pane.module.exports.Model.destroy (/usr/share/atom/resources/app.asar/src/model.js:45:58)
  at Pane.module.exports.Pane.destroy (/usr/share/atom/resources/app.asar/src/pane.js:623:39)
  at Pane.module.exports.Pane.close (/usr/share/atom/resources/app.asar/src/pane.js:726:21)
  at atom-pane.atom.commands.add.pane:close (/usr/share/atom/resources/app.asar/src/pane-element.js:285:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
  3x -0:31.7.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-blue-dream-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by spongecattle** [comment]
fixed Use Split left or Split right
