### ISSUE TITLE
Launched as if its Google Chrome Debugger

### ISSUE THREAD

**Issue by jmigual** [atom/atom#7580]
When you open Atom editor it starts properly and then it transforms into google chrome debugger...

![sin titulo](https://cloud.githubusercontent.com/assets/6493651/8428697/deae3c42-1f20-11e5-85f2-0d761f9cb12c.png)

**Comment by izuzak** [comment]
That will happen only when there's an exception logged in the console tab of the devtools. Can you check the console tab and paste the exception message and the full stack trace here?

**Comment by jmigual** [comment]
```javascript
Error: EPERM: operation not permitted, open 'C:\Users\<user>\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\imports.json'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.fsPlus.writeFileSync (C:\Users\<user>\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (C:\Users\<user>\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\less-cache\lib\less-cache.js:155:17)
    at LessCache.module.exports.LessCache.setImportPaths (C:\Users\<user>\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\less-cache\lib\less-cache.js:113:12)
    at new LessCache (C:\Users\<user>\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\less-cache\lib\less-cache.js:32:12)
    at new LessCompileCache (C:\Users\<user>\AppData\Local\atom\app-1.0.0\resources\app.asar\src\less-compile-cache.js:20:20)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\<user>\AppData\Local\atom\app-1.0.0\resources\app.asar\src\theme-manager.js:299:26)
```

**Comment by batjko** [comment]
Looks like a permission issue?
Can you confirm your user account has write access to the `.atom` folder and everything underneath?

**Comment by jmigual** [comment]
Ok, I found that the folder had read only permission I don't know why. Now it's working, thanks.

**Comment by izuzak** [comment]
Thanks for the assist, @batjko :bow:. Happy to hear this solved your problem, @jmigual.
