### ISSUE TITLE
Uncaught Error: Encountered an invalid scope end id. Popped -117, expected to pop -65.

### ISSUE THREAD

**Issue by anatolii-volodko** [atom/atom#7582]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 14.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Encountered an invalid scope end id. Popped -117, expected to pop -65.

```
At /usr/share/atom/resources/app.asar/src/tokenized-buffer.js:607

Error: Encountered an invalid scope end id. Popped -117, expected to pop -65.
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopesFromTags (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:607:21)
  at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:589:21)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:294:105)
  at /usr/share/atom/resources/app.asar/src/tokenized-buffer.js:271:26
  at /usr/share/atom/resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47

```

### Commands

```
     -8:57.5.0 welcome:show (atom-text-editor.editor.is-focused)
  4x -5:50.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:00.0 core:paste (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by benogle** [comment]
cc @nathansobo

**Comment by nathansobo** [comment]
@anatolii-volodko can you tell us the grammar you were using and what content it included? Thanks.

**Comment by anatolii-volodko** [comment]
@nathansobo this issue happened after opening Ruby on Rails project (with some js views inside). After reinstall atom it doesn't returns. Probably it was a conflict with some old atom version (after update atom to 1.0)
