### ISSUE TITLE
Uncaught Error: /usr/local/share/atom/resources/app.asar/src/browser/context-menu.js:1(function ...

### ISSUE THREAD

**Issue by stramel** [atom/atom#7591]
[Enter steps to reproduce below:]

1. Right click on a git hook file that is not part of repository

**Atom Version**: 1.0.1-375cf27
**System**: Ubuntu 14.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: /usr/local/share/atom/resources/app.asar/src/browser/context-menu.js:1
(function (exports, require, module, __filename, __dirname) { mWindow) {
                                                                     ^
Unexpected token )
/usr/local/share/atom/resources/app.asar/src/browser/context-menu.js:1
(function (exports, require, module, __filename, __dirname) { mWindow) {
                                                                     ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:435:25)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (/usr/local/share/atom/resources/app.asar/src/browser/atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)

```
At /usr/local/share/atom/resources/atom.asar/renderer/api/lib/remote.js:77

Error: /usr/local/share/atom/resources/app.asar/src/browser/context-menu.js:1
(function (exports, require, module, __filename, __dirname) { mWindow) {
                                                                     ^
Unexpected token )
/usr/local/share/atom/resources/app.asar/src/browser/context-menu.js:1
(function (exports, require, module, __filename, __dirname) { mWindow) {
                                                                     ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:435:25)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (/usr/local/share/atom/resources/app.asar/src/browser/atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
  at metaToValue (/usr/local/share/atom/resources/atom.asar/renderer/api/lib/remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (/usr/local/share/atom/resources/atom.asar/renderer/api/lib/remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/local/share/atom/resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/usr/local/share/atom/resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/usr/local/share/atom/resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/usr/local/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/usr/local/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -7:42 core:save (atom-text-editor.editor.is-focused)
  4x -6:53.1.0 core:undo (atom-text-editor.editor.is-focused)
     -6:51.7.0 core:redo (atom-text-editor.editor.is-focused)
     -6:30.5.0 tree-view:toggle-vcs-ignored-files (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:26.8.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -5:26.4.0 core:save (atom-text-editor.editor.is-focused)
     -5:14.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -5:13.3.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -5:12.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:41.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:40.2.0 core:paste (atom-text-editor.editor.is-focused)
  4x -0:38.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:37 core:save (atom-text-editor.editor.is-focused)
     -0:21.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:20.4.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:19.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/stramel/Projects",
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-jscs",
      "linter-gjslint",
      "project-palette-finder",
      "autoclose-html",
      "atom-color-highlight",
      "emmet"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "invisibles": {},
    "preferredLineLength": 120,
    "showIndentGuide": true,
    "showInvisibles": true,
    "scrollPastEnd": true,
    "zoomFontWhenCtrlScrolling": false,
    "fontSize": 11
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-beautify, v0.28.7
atom-jasmine, v0.6.0
autocomplete-paths, v1.0.2
editorconfig, v1.0.1
file-icons, v1.5.8
highlight-line, v0.11.0
highlight-selected, v0.10.1
linter, v1.1.0
linter-jshint, v0.1.7
linter-less, v2.0.3
monokai, v0.14.0
pain-split, v1.4.0
project-manager, v1.15.10

# Dev
No dev packages
```

**Comment by stramel** [comment]
Got this in the window when I did a refresh.

```
.on('unhandledRejection', function(error, promise) { console.error('Unhandled promise rejection %o with error: %o', promise, error); }); // Ensure ATOM_HOME is always set before anything else is required setupAtomHo
```

**Comment by 50Wliu** [comment]
@kevinsawicki looks like #7560 wasn't a clean fix.

**Comment by 50Wliu** [comment]
Ignore the above.
@stramel, can you try updating to 259d42d2852fea9700fbcf85cb96a0aa9ebf9865 or above and see if it ever happens again?

**Comment by stramel** [comment]
@50Wliu I will check it later today. Thanks!
