### ISSUE TITLE
Cannot install packages both in UI & apm

### ISSUE THREAD

**Issue by anchoretics** [atom/atom#7619]
i download the latested Atom.app on my Mac, but can't install packages:
command:
```
~ apm install javascript-snippets
```
stack:
```
Installing javascript-snippets to /Users/lingfengliang/.atom/packages
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.35 | darwin | x64
gyp http GET https://atom.io/download/atom-shell/v0.22.0/node-v0.22.0.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: write EPIPE
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at Object.afterWrite (net.js:721:19)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.22.0" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/lingfengliang/.atom
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```
somtimes another stack:
```
Installing javascript-snippets to /Users/lingfengliang/.atom/packages
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.35 | darwin | x64
gyp http GET https://atom.io/download/atom-shell/v0.22.0/node-v0.22.0.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at TCP.onread (net.js:559:19)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.22.0" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/lingfengliang/.atom
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```
it's the same error in UI

**Comment by thomasjo** [comment]
Are you begin a firewall/proxy?

**Comment by anchoretics** [comment]
yes, i use shadowsocks, i tried PAC & global mode

**Comment by anchoretics** [comment]
```
➜  ~  apm install javascript-snippets
Installing javascript-snippets to /Users/lingfengliang/.atom/packages
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.35 | darwin | x64
gyp http GET https://atom.io/download/atom-shell/v0.22.0/node-v0.22.0.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: write EPIPE
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at Object.afterWrite (net.js:721:19)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.22.0" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/lingfengliang/.atom
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

➜  ~
```

**Comment by anchoretics** [comment]
![photo](http://s1.momo.moda/2015/07/04/fc3cf452d3da8402bebb765225ce8c0e.png)

i dont think it's my network's fault

**Comment by bapi24** [comment]
Hi there,

Is there any solution for this?
