### ISSUE TITLE
Uncaught Error: ENOTSUP: operation not supported on socket, write

### ISSUE THREAD

**Issue by VSuryaBhargava** [atom/atom#7651]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 15.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOTSUP: operation not supported on socket, write

```
At /usr/share/atom/resources/app.asar/src/pane.js:762

Error: ENOTSUP: operation not supported on socket, write
    at Error (native)
    at Object.fs.writeSync (fs.js:657:20)
    at Object.fs.writeFileSync (fs.js:1164:21)
    at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:264:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:362:21)
    at File.module.exports.File.writeSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:336:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:992:17)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:579:26)
```

### Commands

```
     -0:27.1.0 core:delete (atom-text-editor.editor.is-focused)
     -0:26.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:26 core:undo (atom-text-editor.editor.is-focused)
     -0:25.5.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:24.8.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -0:24.1.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:23.2.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:20.1.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:19.5.0 core:cut (atom-text-editor.editor.is-focused)
  6x -0:19.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:18.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:17.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:14.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:11.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:05.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -0:03.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.10.1
minimap-find-and-replace, v4.2.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
What were you doing when you got this error?

**Comment by izuzak** [comment]
Also, is there anything special about the file you wanted to save (e.g. is it a file on a network drive)?

**Comment by VSuryaBhargava** [comment]
@izuzak I opened a file on a network drive. I just saved the file after editing it.

**Comment by VSuryaBhargava** [comment]
@izuzak : The same just happened again.

I had a file in my local hard drive open.

I opened a file with the same name on a different machine over the server then tried to save the file when the error occurred.

Hope this helps.

**Comment by izuzak** [comment]
@VSuryaBhargava I think this is related to files on network drives -- I can't promise when this problem might be looked into by the core team, but the additional details are definitely appreciated. Thanks
