### ISSUE TITLE
Cannot use a secure FTP connection

### ISSUE THREAD

**Issue by ghost** [atom/atom#7681]
tls.js:175
Hide Stack Trace
TypeError: Cannot read property 'CN' of undefined
at Object.checkServerIdentity (tls.js:175:37)
at TLSSocket.<anonymous> (_tls_wrap.js:923:29)
at emitNone (events.js:67:13)
at TLSSocket.emit (events.js:163:7)
at TLSSocket._finishInit (_tls_wrap.js:506:8)
at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
at BrowserWindow.RemoteMemberFunction [as emit](/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)

I was able to work using insecure FTP connection.

**Comment by batjko** [comment]
Can you clarify which FTP package you're using?
It's not a part of core Atom, so may have to be reported to that package instead.
