### ISSUE TITLE
Uncaught TypeError: Cannot read property 'endsWith' of undefined, using Jekyll 

### ISSUE THREAD

**Issue by nmenag** [atom/atom#7714]
[Enter steps to reproduce below:

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'endsWith' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:744

TypeError: Cannot read property 'endsWith' of undefined
  at Pane.module.exports.Pane.handleSaveError (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:744:51)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:527:16)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:592:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:311:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:15.8.0 grammar-selector:show (atom-text-editor.editor)
  2x -0:12.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.9
autocomplete-php, v0.3.6
autocomplete-ruby, v0.1.0
autocomplete-sass, v0.1.0
color-picker, v2.0.7
css-snippets, v0.8.0
emmet, v2.3.12
highlight-line, v0.11.0
linter, v1.1.0
markdown-format, v2.5.1
minimap, v4.10.2
monokai, v0.14.0
project-manager, v1.15.10
seti-ui, v0.7.1
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@nmenag What do you mean "using Jekyll"? Can you share the exact steps which reproduce the problem for you, assuming that I don't have any packages installed? Can you reproduce this problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by nmenag** [comment]
Ok,  Jekyll http://jekyllrb.com, when i  edit/save a markdown file(edit the posts),  changed me the  format and return this error. only happens with Jekyll.

**Comment by izuzak** [comment]
@nmenag Does this happen for all markdown files or only some? Can you provide a link to one markdown file it happens with? Also, can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
