### ISSUE TITLE
Failed to load the markdown-writer package

### ISSUE THREAD

**Issue by KirillVladimirov** [atom/atom#7736]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Linux Mint
**Thrown From**: Atom Core
### Stack Trace

Failed to load the markdown-writer package

```
At path must be a string

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.readFileSync (fs.js:396:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
    at Object.module.exports.readFileSync (/usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:158:21)
    at /usr/share/atom/resources/app.asar/src/package.js:402:45
    at Array.map (native)
    at Package.module.exports.Package.loadKeymaps (/usr/share/atom/resources/app.asar/src/package.js:400:46)
    at /usr/share/atom/resources/app.asar/src/package.js:183:19
```
### Commands

```
```
### Config

``` json
{
  "core": {},
  "editor": {
    "fontSize": 16,
    "invisibles": {},
    "tabLength": 4
  }
}
```
### Installed Packages

``` coffee
# User
emmet, v2.3.12
linter-php, v0.0.15
php-debug, v0.1.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
No further reports, and it looks like this belongs on the markdown-writer package anyway.  Closing.
