### ISSUE TITLE
Error Opening Folder in Atom

### ISSUE THREAD

**Issue by dstack** [atom/atom#7742]
```
TypeError: Cannot read property 'onDidDestroy' of undefined
  at c:\app-tools\Atom\resources\app\src\project.js:70:24
  at new Project (c:\app-tools\Atom\resources\app\src\project.js:77:9)
  at Function.module.exports.Serializable.deserialize (c:\app-tools\Atom\resources\app\node_modules\serializable\lib\serializable.js:72:22)
  at DeserializerManager.module.exports.DeserializerManager.deserialize (c:\app-tools\Atom\resources\app\src\deserializer-manager.js:56:29)
  at Atom.module.exports.Atom.deserializeProject (c:\app-tools\Atom\resources\app\src\atom.js:707:51)
  at Atom.module.exports.Atom.deserializeEditorWindow (c:\app-tools\Atom\resources\app\src\atom.js:735:12)
  at Atom.module.exports.Atom.startEditorWindow (c:\app-tools\Atom\resources\app\src\atom.js:585:12)
  at Object.<anonymous> (c:\app-tools\Atom\resources\app\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (c:\app-tools\Atom\resources\app\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (c:\app-tools\Atom\resources\app\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///C:/app-tools/Atom/resources/app/static/index.js:59:25)
```

**Comment by 50Wliu** [comment]
Hi @dstack, does this still happen in safe mode (`atom --safe`)?  In addition, what Atom version is this?  Thanks.

**Comment by dstack** [comment]
Sorry for the lack of reply, missed this when you posted it.  Unfortunately, I didn't get to try this before I found that re-installing Atom would make the problem go away.  I'll keep an eye out for it in the future and remember to report version and try safe mode first.
