### ISSUE TITLE
The editor has crashed, just on opened

### ISSUE THREAD

**Issue by juliomatcom** [atom/atom#7755]
Hi, this is very undesearible issue, i recently installed <a href="https://atom.io/packages/atom-ctags ">  atom-ctags </a> and prety cool, but at some point my apps just got very slow, and now every time i open Atom it just stop and Crash. 
Im in a dead point. So in cases like this i would like to disable the problematic feature or something, but i cant, not in the editor for sure

**Comment by juliomatcom** [comment]
Anyway i just removed .ctags and .ctags1 file and then it does not crashed and says: 
<pre><code>
Stopped: Build more than 5 seconds, check if /var/www/rb/eatin/front contain too many file.
Suggest that add CmdArgs at atom-ctags package setting, example:
--exclude=some/path --exclude=some/other
</code>
</pre>

**Comment by thomasjo** [comment]
The problem you're experiencing is caused by [atom-ctags](https://atom.io/packages/atom-ctags).

It seems other people are having the same problem, so I suggest you subscribe to e.g. https://github.com/yongkangchen/atom-ctags/issues/103 and https://github.com/yongkangchen/atom-ctags/issues/107 for updates.

**Comment by kornan** [comment]
Error: Cannot find module 'nuclide-commons'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\nuclide-blame-provider-hg\node_modules\nuclide-hg-git-bridge\lib\repositoryForPath.js:1:102)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.get [as repositoryForPath] (C:\Users\Administrator\.atom\packages\nuclide-blame-provider-hg\node_modules\nuclide-hg-git-bridge\lib\main.js:20:14)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\nuclide-blame-provider-hg\lib\common.js:16:33)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\nuclide-blame-provider-hg\lib\HgBlameProvider.js:40:15)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.provideHgBlameProvider (C:\Users\Administrator\.atom\packages\nuclide-blame-provider-hg\lib\main.js:20:23)
    at Package.module.exports.Package.activateServices (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\package.js:348:69)
    at Package.module.exports.Package.activateNow (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\package.js:186:16)
