### ISSUE TITLE
installing packages on Windows with Mingw-64

### ISSUE THREAD

**Issue by stonebig** [atom/atom#7764]
Hello,

I would like to have Atom+Hydrogen working nicely with Winpython, which include a compiler Mingw-64.

Unfortunately, it seems the compilation steps, when installing Hydrogen, tries to use VisualStudio (as I see a `.vcproj`in the long error report.
Is there any workaround to have it compiled with Mingw-64  ?

````
[Enter steps to reproduce below:]

1. install a Winpython
2. unzip an atom-windows.zip in the subdirectory \tools\Atom (so we have `\tools\Atom\atom.exe`
3. modify the \scripts\env.bat file to add `%WINPYDIR%\..\tools\Atom` in the PATH 
4. launch `\scripts\cmd.bat` and then type Atom <Enter> .... Atom launches itself
5. modify default settings to subdirectory `\settings\github` 
6. ask to install Hydrogen, and then ...


**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At D:\result_tests\winpython-2.7.10.2build1.amd64\tools\Atom\resources\app.asar\src\window-event-handler.js:165

TypeError: undefined is not a function
  at HTMLDocument.<anonymous> (D:\result_tests\winpython-2.7.10.2build1.amd64\tools\Atom\resources\app.asar\src\window-event-handler.js:165:20)
  at HTMLDocument.handler (D:\result_tests\winpython-2.7.10.2build1.amd64\tools\Atom\resources\app.asar\src\space-pen-extensions.js:115:32)
  at HTMLDocument.jQuery.event.dispatch (D:\result_tests\winpython-2.7.10.2build1.amd64\tools\Atom\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (D:\result_tests\winpython-2.7.10.2build1.amd64\tools\Atom\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (D:\result_tests\winpython-2.7.10.2build1.amd64\tools\Atom\resources\app.asar\src\command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (D:\result_tests\winpython-2.7.10.2build1.amd64\tools\Atom\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (D:\result_tests\winpython-2.7.10.2build1.amd64\tools\Atom\resources\app.asar\src\command-registry.js:156:19)
  at EventEmitter.<anonymous> (D:\result_tests\winpython-2.7.10.2build1.amd64\tools\Atom\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -3:42.8.0 core:paste (atom-text-editor#core.projectHome.editor.mini.is-focused)
     -3:15.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:13.4.0 core:copy (div.alert.alert-danger.alert-dismissable.native-key-bindings)
```

### Config

```json
{
  "core": {
    "projectHome": "D:\\result_tests\\winpython-2.7.10.2build1.amd64\\settings\\github"
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
This seems like a question for [hydrogen](https://github.com/willwhitney/hydrogen) - can you reopen this there?

**Comment by stonebig** [comment]
ok
