### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by telos-io** [atom/atom#7765]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /Users/Koan/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

TypeError: Cannot read property 'match' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (/Users/Koan/Downloads/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:647:23)
    at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForRow (/Users/Koan/Downloads/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:641:21)
    at TokenizedBuffer.module.exports.TokenizedBuffer.retokenizeWhitespaceRowsIfIndentLevelChanged (/Users/Koan/Downloads/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:409:69)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Users/Koan/Downloads/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:387:18)
    at /Users/Koan/Downloads/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:62:24
    at Emitter.module.exports.Emitter.emit (/Users/Koan/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Users/Koan/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:626:20)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Users/Koan/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:777:16)
    at TextBuffer.module.exports.TextBuffer.transact (/Users/Koan/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:743:14)
    at TextBuffer.module.exports.TextBuffer.setTextViaDiff (/Users/Koan/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:478:19)
```
### Commands

```
```
### Config

``` json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi there @telos-io, can you please share what you were doing when this happened?  Thanks.

**Comment by telos-io** [comment]
I was trying to pull from github while atom already had the project open.


On Tue, Jul 7, 2015 at 10:06 AM, Wliu <notifications@github.com> wrote:

> Hi there @telos-io <https://github.com/telos-io>, can you please share
> what you were doing when this happened? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/7765#issuecomment-119269703>.
>



-- 
http://telos.io <http://www.telos.io>
http://www.meetup-roadwarrior.com/

**Comment by Arcanemagus** [comment]
Just traced out exactly what is going on here: https://github.com/atom/atom/issues/7418#issuecomment-157115101

Basically [`TokenizedBuffer.indentLevelForLine()`](https://github.com/atom/atom/blob/master/src/tokenized-buffer.coffee#L442) assumes all lines it is called on have at least some indentation and will fail if `/[\t ]/` fails to match.

**Comment by blacksunrise56** [comment]
As @Arcanemagus said, in [Tokenized-Buffer](https://github.com/atom/atom/blob/master/src/tokenized-buffer.coffee) the function [IndentLevelForLine()](https://github.com/atom/atom/blob/master/src/tokenized-buffer.coffee#L412-424) handles the tabs incorrectly. I don't know anything about coffeescript but the error seems to be on [line 423](https://github.com/atom/atom/blob/master/src/tokenized-buffer.coffee#L423), that `0` is never added to `indentLength` so when the function is called with no indentation it returns `undefined`.  
This is totally reproducible, just calling to `lineTextForBufferRow` with a unindented row is enough. And seems easy to fix, replacing [line 423](https://github.com/atom/atom/blob/master/src/tokenized-buffer.coffee#L423) with `indentLength = 0` would do.
