### ISSUE TITLE
Error on launch - LESS / ThemeManager related?

### ISSUE THREAD

**Issue by aaronbroad** [atom/atom#7774]
I have an error upon launching Atom on Mac OS 10.10.3. It appears to be related to the ThemeManager, but I'm not familiar enough to troubleshoot on my own. I have been using Atom for several months without problems, and just ran into this problem today. I'm unable to do open any files or preferences in app. Rest of system seems ok. I have reinstalled with no improvements.

Here's what shows up in the console:
```
Error
    at new Parser (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
    at LessCache.module.exports.LessCache.parseLess (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:244:16)
    at LessCache.module.exports.LessCache.cssForFile (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:275:20)
    at LessCache.module.exports.LessCache.readFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:263:19)
    at LessCompileCache.module.exports.LessCompileCache.read (/Applications/Atom.app/Contents/Resources/app.asar/src/less-compile-cache.js:36:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:310:33)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:286:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:203:24)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:266:12)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:261:19)index.js:66 handleSetupError
```

**Comment by aaronbroad** [comment]
Back up and running now after clearing out my ~/.atom folder. Probably not repeatable. Will re-open if it recurs.

**Comment by mnquintana** [comment]
@kevinsawicki Do you think we should add this to [the list](https://github.com/atom/atom/issues/7740)?

**Comment by kevinsawicki** [comment]
Yeah, :+1:

**Comment by 50Wliu** [comment]
Closing this in favor of #7282 which has a few examples of how this could happen.

**Comment by paulakfleck** [comment]
For those wondering, the full path to the folder you have to delete before reinstalling is "C:\Users\MyUser\.atom"
