### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, open 'C:\Work\Perforce\BlueStreak\Code\m.py'

### ISSUE THREAD

**Issue by ForestCSharp** [atom/atom#7836]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM: operation not permitted, open 'C:\Work\Perforce\BlueStreak\Code\m.py'

```
At C:\Users\forest.sharp\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\pathwatcher\lib\file.js:385

Error: EPERM: operation not permitted, open 'C:\Work\Perforce\BlueStreak\Code\m.py'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.fsPlus.writeFileSync (C:\Users\forest.sharp\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (C:\Users\forest.sharp\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\pathwatcher\lib\file.js:273:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (C:\Users\forest.sharp\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\pathwatcher\lib\file.js:371:21)
    at File.module.exports.File.writeSync (C:\Users\forest.sharp\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\pathwatcher\lib\file.js:345:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\forest.sharp\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:992:17)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\forest.sharp\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:978:19)
```

### Commands

```
     -0:38.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:37.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:37.3.0 script:run (atom-text-editor.editor)
     -0:14.5.0 core:select-all (atom-text-editor.editor.is-focused)
  3x -0:12.4.0 script:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-perforce, v1.3.0
script, v2.26.3

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
I believe this is an issue with the `script` package, I've reported it there, https://github.com/rgbkrk/atom-script/issues/644
