### ISSUE TITLE
Undefined is not a  function

### ISSUE THREAD

**Issue by keva161** [atom/atom#7843]
Using the latest version on OSX (1.0.2), if I try to open atom I am presented with this error:

![screen shot 2015-07-11 at 14 36 51](https://cloud.githubusercontent.com/assets/298930/8633903/563f4a46-27da-11e5-8e3d-64a314764a9b.png)

The full stack trace is:

```TypeError: undefined is not a function
    at Object.module.exports.activate (/Users/Keva161/.atom/packages/terminal/lib/terminal.coffee:23:20)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:46)```

If I open atom from the terminal by running ```atom --safe``` however, then it opens up without error.

**Comment by mnquintana** [comment]
As the error in your screenshot suggests, this is an issue with terminal or your custom Keva161 package, rather than an issue with Atom core. Closing this one out.
