### ISSUE TITLE
Uncaught Error: ECONNRESET: connection reset by peer, write

### ISSUE THREAD

**Issue by zubair1024** [atom/atom#7849]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ECONNRESET: connection reset by peer, write

```
At C:\Users\zubair.ROAM\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:774

Error: ECONNRESET: connection reset by peer, write
    at Error (native)
    at Object.fs.writeSync (fs.js:657:20)
    at Object.fs.writeFileSync (fs.js:1164:21)
    at Object.fsPlus.writeFileSync (C:\Users\zubair.ROAM\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (C:\Users\zubair.ROAM\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\pathwatcher\lib\file.js:273:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (C:\Users\zubair.ROAM\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\pathwatcher\lib\file.js:371:21)
    at File.module.exports.File.writeSync (C:\Users\zubair.ROAM\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\pathwatcher\lib\file.js:345:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\zubair.ROAM\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:992:17)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\zubair.ROAM\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:978:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\zubair.ROAM\AppData\Local\atom\app-1.0.2\resources\app.asar\src\text-editor.js:579:26)
```

### Commands

```
     -2:20.5.0 find-and-replace:show (atom-text-editor.editor)
  2x -2:18.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:17.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:09.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:08.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:56.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:40.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:38.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @zubair1024, can you please share what exactly you were doing when this error occured?  Thanks.
