### ISSUE TITLE
Uncaught Error: Encountered an invalid scope end id. Popped -23, expected to pop -63.

### ISSUE THREAD

**Issue by Angrycrow** [atom/atom#7853]
[Enter steps to reproduce below:]

1. ... I'm not quite sure... 
2. ... seems to have to do with deleting multiple lines or looking through large buffers. 

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Encountered an invalid scope end id. Popped -23, expected to pop -63.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:629

Error: Encountered an invalid scope end id. Popped -23, expected to pop -63.
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopesFromTags (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:619:23)
  at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:601:21)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:294:105)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:271:26
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47

```

### Commands

```
 16x -2:35.3.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
 13x -2:28.8.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -2:20.7.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
  7x -2:15.6.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:13.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
 20x -2:13.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:02.9.0 core:save (atom-text-editor.editor.is-focused)
     -2:02.0 project-find:show (atom-text-editor.editor.is-focused)
     -1:59.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:51.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:49.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:46.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:38.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:36.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:25.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:24.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "*.meta",
      "*.DS_Store",
      "*.csproj",
      "*.unityproj",
      "*.unity"
    ],
    "destroyEmptyPanes": false
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "fontSize": 17,
    "preferredLineLength": 100
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.11
linter, v1.2.3
minimap, v4.11.2
omnisharp-atom, v0.20.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report, @Angrycrow! If you could share the file for which this happened -- that'd be helpful.

**Comment by Angrycrow** [comment]
Probably in "HH_GM". The error would happen when I would remove multiple
lines. Some update made letters change color inside of comments. I'm sorry
if that isn't helpful. it's been a few days.

Ben Nix-Bradley
http://sotgdc.blogspot.com/
