### ISSUE TITLE
atom not starting

### ISSUE THREAD

**Issue by ceremcem** [atom/atom#7855]
atom is not starting. No error codes. Here is `~/.atom/nohup.out`: 

```
[21636:0712/113520:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
A JavaScript error occured in the browser process
Uncaught Exception:
Error: Module version mismatch. Expected 43, got 41.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/nslog/lib/nslog.js:5:11)
    at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/nslog/lib/nslog.js:15:4)
    at Module._compile (module.js:452:26)
ATTENTION: default value of option force_s3tc_enable overridden by environment.
```

**Comment by ceremcem** [comment]
Uninstalling atom didn't help, there is manual deletion needed: 

```
rm -r /usr/share/atom
```

Then reinstall fixed the problem.
