### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, open '/Users/username/Projects/proje...

### ISSUE THREAD

**Issue by quirm** [atom/atom#7864]
Opening a file which does not exist through terminal.

$ atom project/.git/modules/editor/config 

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, open '/Users/username/Projects/project/.git/modules/editor/config'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:466

Error: ENOTDIR: not a directory, open '/Users/username/Projects/project/.git/modules/editor/config'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:371:27)
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:449:31)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:375:19)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:46:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "tabLength": 4,
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by benogle** [comment]
This is likely because the parent folder does not exist. We should definitely handle this better.
