### ISSUE TITLE
Uncaught Error: kill EPERM

### ISSUE THREAD

**Issue by jh27408079** [atom/atom#7885]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Unknown Windows Version
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: kill EPERM

```
At events.js:141

Error: kill EPERM
  at exports._errnoException (util.js:734:11)
  at ChildProcess.kill (child_process.js:1223:26)
  at Task.module.exports.Task.terminate (C:\Users\Leal\AppData\Local\atom\app-1.0.2\resources\app.asar\src\task.js:143:25)
  at GitRepository.module.exports.GitRepository.refreshStatus (C:\Users\Leal\AppData\Local\atom\app-1.0.2\resources\app.asar\src\git-repository.js:396:15)
  at C:\Users\Leal\AppData\Local\atom\app-1.0.2\resources\app.asar\src\git-repository.js:77:26

```
### Commands

```
     -1:03.6.0 core:paste (atom-text-editor.editor.is-focused)
     -1:00.8.0 core:copy (atom-text-editor.editor.is-focused)
     -0:59 editor:newline (atom-text-editor.editor.is-focused)
     -0:58.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:58.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:58.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:58.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:56.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:53.2.0 core:cut (atom-text-editor.editor.is-focused)
     -0:51.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:50.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:48.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:46.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:46.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:46.3.0 editor:indent (atom-text-editor.editor.is-focused)
  5x -0:45.7.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "editor": {
    "fontSize": 19
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by rose1988c** [comment]
me  too...

**Comment by arunsamsung** [comment]
For me, Error pop up is disappeared after disabling git-diff package.git-diff is pre loaded package .

**Comment by lisaRao** [comment]
me too...

**Comment by mlyknown** [comment]
me too...

**Comment by mlyknown** [comment]
events.js:154
Hide Stack Trace
Error: kill EPERM
    at exports._errnoException (util.js:890:11)
    at ChildProcess.kill (internal/child_process.js:381:26)
    at Task.module.exports.Task.terminate (C:\Users\Administrator\AppData\Local\atom\app-1.10.0\resources\app.asar\src\task.js:152:25)
    at GitRepository.module.exports.GitRepository.refreshStatus (C:\Users\Administrator\AppData\Local\atom\app-1.10.0\resources\app.asar\src\git-repository.js:385:15)
    at C:\Users\Administrator\AppData\Local\atom\app-1.10.0\resources\app.asar\src\git-repository.js:77:26

**Comment by zhengli1987** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Unknown Windows Version
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: kill EPERM

```
At events.js:154

Error: kill EPERM
    at exports._errnoException (util.js:890:11)
    at ChildProcess.kill (internal/child_process.js:381:26)
    at Task.module.exports.Task.terminate (C:\Users\zhengli3\AppData\Local\atom\app-1.10.2\resources\app.asar\src\task.js:152:25)
    at GitRepository.module.exports.GitRepository.refreshStatus (C:\Users\zhengli3\AppData\Local\atom\app-1.10.2\resources\app.asar\src\git-repository.js:385:15)
    at C:\Users\zhengli3\AppData\Local\atom\app-1.10.2\resources\app.asar\src\git-repository.js:77:26
```

### Commands

```
     -2:40.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
```

**Comment by zhengli1987** [comment]
it pops up every time switch between Atom and other application windows

**Comment by shapl** [comment]
me too...

**Comment by frogwz** [comment]
disabling git-diff package，worked.

**Comment by GengDavid** [comment]
I created a repository and added a remote in my github, then it disappeared,

**Comment by lee-dohm** [comment]
Does anyone have steps to reproduce this problem? If not, there isn't enough information here to take action and we're going to have to close it.
