### ISSUE TITLE
Uncaught ReferenceError: Point is not defined

### ISSUE THREAD

**Issue by danielcbright** [atom/atom#7893]
[Enter steps to reproduce below:]

1. Ctrl-S to save a file.
2. Occassionaly this error pops up.

**Atom Version**: 1.0.2
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught ReferenceError: Point is not defined

```
At C:\Users\daniel.bright\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:774

ReferenceError: Point is not defined
    at /C:/Users/xxxxxxxxx/.atom/init.coffee:16:47
    at /C:/Users/xxxxxxxxx/.atom/init.coffee:21:13
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:740:18)
    at /C:/Users/xxxxxxxxx/.atom/init.coffee:8:21
    at Emitter.module.exports.Emitter.emit (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:985:20)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:978:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.0.2\resources\app.asar\src\text-editor.js:579:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:535:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:518:19)
```

### Commands

```
     -0:04.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:03.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "destroyEmptyPanes": false
  },
  "editor": {
    "invisibles": {},
    "fontSize": 19
  }
}
```

### Installed Packages

```coffee
# User
language-puppet, v0.12.0
language-terraform, v0.4.0
line-ending-converter, v1.2.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @danielcbright, this seems to be caused by something in your `init.coffee` file.  Can you please paste the contents of that file here?  Thanks.

**Comment by danielcbright** [comment]
# Your init script
#
# Atom will evaluate this file each time a new window is opened. It is run
# after packages are loaded/activated and after the previous editor state
# has been restored.
#
# An example hack to log to the console when each text editor is saved.
#
# atom.workspace.observeTextEditors (editor) ->
#   editor.onDidSave ->
#     console.log "Saved! #{editor.getPath()}"
atom.workspace.observeTextEditors (editor) ->
    editor.getBuffer().onWillSave ->
        preferredLineEnding = '\n'
        buffer = editor.getBuffer()
        lastRowIndex = buffer.getLastRow()
        buffer.transact ->
            for rowIndex in [0...lastRowIndex]
                do (rowIndex) ->
                    currEol = buffer.lineEndingForRow rowIndex
                    if currEol isnt preferredLineEnding
                        lineEndingRange = new Range(
                            new Point(rowIndex, buffer.lineLengthForRow(rowIndex)),
                            new Point(rowIndex + 1, 0)
                        )
                        buffer.setTextInRange lineEndingRange, preferredLineEnding,
                            { normalizeLineEndings: false }

**Comment by danielcbright** [comment]
The above init.coffee was being used prior to the 1.0 release because I'm using Atom in Windows and there is no way I can set a default to Unix EOL instead of Windows EOL. I've removed it, thanks for taking a look!

**Comment by izuzak** [comment]
You're trying to use the `Point` class, but it's not defined. Try adding this to the top of your init.coffee:

```
{Point} = require 'atom'
```

**Comment by gneiss01** [comment]
@izuzak I tried your suggestion but it didn't resolve the issue.

**Comment by izuzak** [comment]
@gneiss01 You didn't describe the issue _you_ are having, nor provide any code or exception traces. If you could do that, we might be able to provide advice.

**Comment by lachhebo** [comment]
`/var/home/isma/github/dedukti-editor/lib/dedukti-editor.js:69`

```
ReferenceError: Point is not defined
    at Object.toggle (/var/home/isma/github/dedukti-editor/lib/dedukti-editor.js:69:21)
    at HTMLElement.deduktiEditorToggle (/var/home/isma/github/dedukti-editor/lib/dedukti-editor.js:24:43)
    at CommandRegistry.handleCommandEvent (/app/share/atom/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/app/share/atom/resources/app/src/window-event-handler.js:110:40)
```

I'm just trying to create few point inside the toogle fonction : 

```
    let a = new Point(0,1);
    let b = new Point(5,10);
    let c = new Point(5,11);
    let d = new Point(10,10); 
```
I'v tried your fixe but it did not change something

**Comment by lachhebo** [comment]
It seem's point.coffee has been deprecated but it is still on the documentation.
