### ISSUE TITLE
Uncaught Error: ENAMETOOLONG: name too long, open '/Workspace/awesome-typescript...

### ISSUE THREAD

**Issue by s-panferov** [atom/atom#7902]
[Enter steps to reproduce below:]

1. Create a folder structure with recursive symlink
2. Copy the folder

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENAMETOOLONG: name too long, open '/Workspace/awesome-typescript-loader/examples/tsjsx0/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/.git/objects/pack/pack-3bca7f6ea4153ef80afc125d04b27551d9443052.idx'

```
At fs.js:519

Error: ENAMETOOLONG: name too long, open '/Workspace/awesome-typescript-loader/examples/tsjsx0/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/examples/node/node_modules/awesome-typescript-loader/.git/objects/pack/pack-3bca7f6ea4153ef80afc125d04b27551d9443052.idx'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.fsPlus.copySync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:336:28)
    at Object.fsPlus.copySync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:333:32)
    at Object.fsPlus.copySync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:333:32)
    at Object.fsPlus.copySync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:333:32)
    at Object.fsPlus.copySync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:333:32)
    at Object.fsPlus.copySync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:333:32)
```

### Commands

```
     -2:52 core:paste (atom-text-editor.editor.is-focused)
     -2:49.5.0 core:undo (atom-text-editor.editor.is-focused)
     -1:08.0 core:paste (atom-text-editor.editor.is-focused)
     -1:05.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:04.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:04.5.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:04.1.0 tree-view:copy (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:02.0 tree-view:paste (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "showIndentGuide": true,
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Stylus, v1.0.0
atom-typescript, v5.0.26
file-icons, v1.5.8
file-types, v0.4.1
git-diff-details, v0.18.0
language-rust, v0.4.3
linter, v1.2.3
racer, v0.15.2
tree-view-git-status, v0.1.1
tree-view-open-files, v0.2.4

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
This was fixed by https://github.com/atom/tree-view/pull/514 and will be included in the next Atom release, 1.0.3
