### ISSUE TITLE
Uncaught Error: Encountered an invalid scope end id. Popped -101, expected to pop -81.

### ISSUE THREAD

**Issue by gusennan** [atom/atom#7910]
[Enter steps to reproduce below:]

1.  I am using the vim and omnisharp plugins.  I visually-highlighted a method in a .CS-file, and then used 'dd' to delete it.  Then the error occurred. 

**Atom Version**: 1.0.2
**System**: "Fedora release
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Encountered an invalid scope end id. Popped -101, expected to pop -81.

```
At /usr/share/atom/resources/app.asar/src/tokenized-buffer.js:629

Error: Encountered an invalid scope end id. Popped -101, expected to pop -81.
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopesFromTags (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:619:23)
  at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:601:21)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:294:105)
  at /usr/share/atom/resources/app.asar/src/tokenized-buffer.js:271:26
  at /usr/share/atom/resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47

```

### Commands

```
     -0:29.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:29.3.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:28.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  4x -0:28.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:27.6.0 vim-mode:substitute (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:27 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:26.4.0 vim-mode:delete-right (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:25.4.0 vim-mode:undo (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:23.6.0 core:save (atom-text-editor.editor.vim-mode.is-focused.command-mode)
undefined -0:23.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:07.3.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  6x -0:05.7.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:02.9.0 vim-mode:activate-linewise-visual-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  6x -0:02.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  3x -0:02.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:01.2.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "ex-mode"
    ],
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.7
atom-yeoman, v0.3.11
linter, v1.2.3
omnisharp-atom, v0.20.0
vim-mode, v0.55.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report, @gusennan! If you could share the file itself and explain what you did on the file -- that'd be really helpful.

**Comment by thomasjo** [comment]
This looks to either be caused by `atom-beautify, `linter`, or `omnisharp-atom`. All are present in the (assumed) duplicate issue https://github.com/atom/atom/issues/7923.

If you're able to reproduce the problem, try disabling all then attempt to reproduce again. If you're unable to re-enable them one by one until you are.
