### ISSUE TITLE
Postinstall scripts don't work

### ISSUE THREAD

**Issue by ForbesLindesay** [atom/atom#7982]
@pgnd reported the following error when attempting to install spawn-sync.  Since spawn-sync only fails like this when installed as part of atom, I'm copying the issue over here in case anybody knows why.  It seems like atom is not actually downloading the postinstall script into the correct folder.

**begin copy of original issue ForbesLindesay/spawn-sync#28**

Running

```
atom --version
    1.0.3-9774b20
node -v
    v2.4.0
npm -v
    2.13.0
```

Upgrading atom-beautify from installed v0.28.7 to v0.28.8 FAILs:

```
Updating to “atom-beautify@0.28.8” failed.

> spawn-sync@1.0.13 postinstall /tmp/apm-install-dir-115617-5652-1i1ck6n/node_modules/atom-beautify/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

module.js:340
    throw err;
          ^
Error: Cannot find module '/tmp/apm-install-dir-115617-5652-1i1ck6n/node_modules/atom-beautify/node_modules/cross-spawn/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
npm ERR! Linux 4.1.1-2.gcac28b3-desktop
npm ERR! argv "/usr/local/share/atom/resources/app/apm/bin/node" "/usr/local/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/pgnd/.atom/.apm/.apmrc" "--userconfig" "/home/pgnd/.atom/.apmrc" "install" "/tmp/d-115617-5652-1qpfmy7/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.13 postinstall: `node postinstall`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.13 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115617-5652-1i1ck6n/npm-debug.log

ls -al /tmp/apm-install-dir-115617-5652-1i1ck6n/npm-debug.log
    ls: cannot access /tmp/apm-install-dir-115617-5652-1i1ck6n/npm-debug.log: No such file or directory
```

**Comment by JyBP** [comment]
Same problem on windows with postinstall and spawn-sync.
I tried everything.

```
node -v
v0.12.7

npm -v
2.14.0`

atom --version
1.0.8
```

Node version is the one bundled with atom.

```
> spawn-sync@1.0.13 postinstall C:\Users\Jy\AppData\Local\Temp\apm-install-dir-115728-2412-glzw7f\node_modules\atom-typescript\node_modules\json2dts\node_modules\yargs\node_modules\os-locale\node_modules\exec-file-sync\node_modules\spawn-sync
> node postinstall

module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\postinstall'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Jy\\AppData\\Local\\atom\\app-1.0.8\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Jy\\AppData\\Local\\atom\\app-1.0.8\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Jy\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Jy\\.atom\\.apmrc" "install" "C:\\Users\\Jy\\AppData\\Local\\Temp\\d-115728-2412-p6uhwc\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.13 postinstall: `node postinstall`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.13 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.
```

**Comment by ForbesLindesay** [comment]
That looks like npm is not correctly setting the current working directory.

**Comment by lukewatts** [comment]
Same issue. Is there a fix. Windows 8.1

**Comment by lukewatts** [comment]
Updating Node fixed this issues for me. It seems that older version of Node only update the User PATH variable and not the System Path variable or it does it incorrectly in some cases. Check both path variables and make sure they're correctly set to where Node is on your system. Or download the latest msi installer and see if that corrects it. Worked for me.

**Comment by cjpoor** [comment]
I have this problem on Mac OS X 10.10.5 with Atom 1.3.2
It would be great to have some more detailed instructions on how to fix this problem on the Mac since my knowledge of the Paths used is rudimentary at best.

**Comment by lygstate** [comment]
Failed on win32
```
Installing linter-js-standard to C:\CI-Tools\IDE\Atom-Bolt\.atom\packages failed

> spawn-sync@1.0.15 postinstall C:\Users\lygstate\AppData\Local\Temp\apm-install-dir-11654-27644-1mgjwq2\node_modules\li
nter-js-standard\node_modules\standard\node_modules\standard-format\node_modules\esformatter\node_modules\npm-run\node_m
odules\spawn-sync
> node postinstall

Installing native dependencies (this may take up to a minute)

> spawn-sync@1.0.15 postinstall C:\Users\lygstate\AppData\Local\Temp\apm-install-dir-11654-27644-1mgjwq2\node_modules\li
nter-js-standard\node_modules\happiness\node_modules\happiness-format\node_modules\esformatter\node_modules\npm-run\node
_modules\spawn-sync
> node postinstall

Installing native dependencies (this may take up to a minute)

> spawn-sync@1.0.15 postinstall C:\Users\lygstate\AppData\Local\Temp\apm-install-dir-11654-27644-1mgjwq2\node_modules\li
nter-js-standard\node_modules\semistandard\node_modules\semistandard-format\node_modules\standard-format\node_modules\es
formatter\node_modules\npm-run\node_modules\spawn-sync
> node postinstall


npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.
3"})
npm WARN engine get-stdin@5.0.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine get-stdin@5.0.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\CI-Tools\\IDE\\Atom-Bolt\\Atom\\resources\\app\\apm\\bin\\node.exe" "C:\\CI-Tools\\IDE\\Atom-Bolt\\At
om\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\CI-Tools\\IDE\\Atom-Bolt\\.atom\\.apm
\\.apmrc" "--userconfig" "C:\\CI-Tools\\IDE\\Atom-Bolt\\.atom\\.apmrc" "install" "C:\\Users\\lygstate\\AppData\\Local\\T
emp\\d-11654-27644-t5afwe\\package.tgz" "--target=0.36.8" "--arch=ia32" "--production" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file C:\windows\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

```
