### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by sinstein** [atom/atom#7987]
Suddenly Atom prompts this:
[Screenshot](http://i.imgur.com/U7o1SNd.png)

**Stack Trace**

```
Uncaught TypeError: undefined is not a function /Users/sauravkothari/Downloads/Atom.app/Contents/Resources/app.asar/src/task.js:120

TypeError: undefined is not a function
  at Task.module.exports.Task.send (/Users/sauravkothari/Downloads/Atom.app/Contents/Resources/app.asar/src/task.js:120:27)
  at Task.module.exports.Task.start (/Users/sauravkothari/Downloads/Atom.app/Contents/Resources/app.asar/src/task.js:111:12)
  at Function.module.exports.Task.once (/Users/sauravkothari/Downloads/Atom.app/Contents/Resources/app.asar/src/task.js:23:18)
  at GitRepository.module.exports.GitRepository.refreshStatus (/Users/sauravkothari/Downloads/Atom.app/Contents/Resources/app.asar/src/git-repository.js:398:37)
  at /Users/sauravkothari/Downloads/Atom.app/Contents/Resources/app.asar/src/git-repository.js:77:26
```

**Comment by mnquintana** [comment]
Can you provide some [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues)? Can you follow the suggestions in the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)? What version of Atom are you using? What OS? What were you doing when you got this error?

Also, in the future it would help if you clicked the "Create issue" button instead of pasting the error manually, because it will include much of the information we need to debug an issue. Thanks!

**Comment by sinstein** [comment]
Apologies for the lack of finesse in the complaint.
I tried using the `Create Issue` button but it did not appear to respond at the time.
I am using Atom 1.0.2 on OS X Yosemite 10.10.4

I was simply going about modifying my Rails App in Atom, when this popped up out of nowhere. A search appeared to have triggered a queue of prompts for the same error.

I could do away with it by restarting and hence cannot reproduce it right now to find more details

**Comment by maxbrunsfeld** [comment]
Can you list your installed packages `apm list --installed`?

**Comment by sinstein** [comment]
├── atom-material-syntax@0.2.1
├── atom-material-ui@0.5.4
├── atom-terminal@0.8.0
├── file-type-icons@0.7.0
├── git-plus@5.2.2
├── linter@1.2.4
├── minimap@4.12.0
├── minimap-git-diff@4.1.7
├── nucleus-dark-ui@0.1.3
├── ruby-block@0.3.4
├── seti-syntax@0.4.0
├── seti-ui@0.7.1
└── tree-view-open-files@0.2.4

**Comment by jbrownson** [comment]
I'm also seeing this error

It triggers when I try to split a view with the active tab being an instance of browser-plus

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:602

TypeError: undefined is not a function
  at Pane.module.exports.Pane.copyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:602:168)
  at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:685:32)
  at Pane.module.exports.Pane.splitDown (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:676:19)
  at atom-pane.atom.commands.add.pane:split-down (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:280:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
  2x -2:45.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:43.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:41.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:41.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -2:40.2.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:39.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:39.6.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:38.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:38.3.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  6x -2:37.3.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -2:35.8.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:34.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:33.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:14.7.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:14.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-haskell",
      "haskell-ghc-mod",
      "ide-haskell",
      "language-haskell",
      "ide-flow"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.30
minimap, v4.12.0
react, v0.12.6

# Dev
No dev packages
```

**Comment by jerone** [comment]
[Enter steps to reproduce below:]

1. Make sure [Preview](https://github.com/Glavin001/atom-preview/) is installed
2. Focus Preview pane
3. Split pane (any direction will do)
4. See error appear:

**Atom Version**: 1.0.2
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:602

TypeError: undefined is not a function
  at Pane.module.exports.Pane.copyActiveItem (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:602:168)
  at Pane.module.exports.Pane.split (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:685:32)
  at Pane.module.exports.Pane.splitUp (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:672:19)
  at atom-pane.atom.commands.add.pane:split-up (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane-element.js:275:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
  at CommandRegistry.__bind [as handleCommandEvent] (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\atom.asar\renderer\api\lib\remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.jQuery.event.add.handler (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.jQuery.event.add.elemData.handle (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -2:04.2.0 application:new-file (atom-pane.pane.active)
  4x -1:45.6.0 preview:toggle (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tool-bar-main",
      "toolbar-basic",
      "enhanced-tabs"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "editor": {
    "fontSize": 11,
    "invisibles": {},
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
about, v1.0.1
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.9
atom-notifier, v0.3.3
atom-yeoman, v0.3.11
color-picker, v2.0.11
editorconfig, v1.0.1
file-icons, v1.5.8
flex-tool-bar, v0.4.4
foldername-tabs, v0.1.4
gutter-shadow, v0.5.0
indentation-indicator, v0.6.0
json-schema, v0.1.10
language-jade, v0.5.1
language-sln, v0.1.0
linter, v1.2.4
linter-coffeelint, v1.0.0
markdown-scroll-sync, v0.4.0
menu-manager, v0.4.2
minimap, v4.12.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.7
minimap-selection, v4.3.0
new-tab, v0.3.0
open-recent, v2.3.0
preview, v0.16.3
project-view, v0.1.2
soft-wrap-indicator, v0.7.0
spell-check, v0.59.0
symbols-tree-view, v0.9.3
tool-bar, v0.1.8
travis-ci-status, v0.16.0
useful-context-menu, v0.2.1

# Dev
flex-tool-bar, v0.4.4
new-tab, v0.3.0
timecop, v0.31.0
tool-bar, v0.1.8
tree-view, v0.179.0
```
