### ISSUE TITLE
Uncaught TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by Protosac** [atom/atom#8014]
The app crashed while trying to open a file. I force closed it and re-opened it.

This has also happened on a normal close and re-open.

[Enter steps to reproduce below:]
1. Open Atom.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'text' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1655

TypeError: Cannot read property 'text' of undefined
    at DisplayBuffer.module.exports.DisplayBuffer.findMaxLineLength (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1655:28)
    at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1552:12)
    at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1525:12)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:320:22)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:271:26
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/khudson/code",
    "ignoredNames": [
      ".git",
      ".pyc",
      ".DS-STORE"
    ],
    "audioBeep": false
  },
  "editor": {
    "invisibles": {},
    "scrollPastEnd": true,
    "preferredLineLength": 120,
    "showIndentGuide": true,
    "softWrapAtPreferredLineLength": true,
    "softWrapHangingIndent": 2,
    "zoomFontWhenCtrlScrolling": true,
    "fontSize": 12
  }
}
```
### Installed Packages

``` coffee
# User
language-jade, v0.5.1
linter-pep8, v1.0.0
linter-pylint, v0.2.2
restore-windows, v0.4.1

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
Can you reproduce this in safe mode? (`atom --safe`)
