### ISSUE TITLE
Uncaught Error: EIO: i/o error, open '/Volumes/kmclient.com/var/www/leos.kmclient.com/html/wp-con...

### ISSUE THREAD

**Issue by kangomedia** [atom/atom#8049]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EIO: i/o error, open '/Volumes/kmclient.com/var/www/leos.kmclient.com/html/wp-content/themes/km_leos/style.css'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:774

Error: EIO: i/o error, open '/Volumes/kmclient.com/var/www/leos.kmclient.com/html/wp-content/themes/km_leos/style.css'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:273:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:371:21)
    at File.module.exports.File.writeSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:345:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:992:17)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
```

### Commands

```
     -0:17.4.0 find-and-replace:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:16.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -0:15.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:10.6.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -0:08.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:00.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "fontSize": 17,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
Does this happen reproducibly? Are you able to open the file on other editors?

**Comment by kangomedia** [comment]
Thanks for the quick response Max. I think the issue may have been related
to user permissions on a mounted disk using Transmit by Panic. I logged out
and back in with another user, remounted the disk and everything appears to
be working.

**Comment by maxbrunsfeld** [comment]
Ok, I'm gonna close this for now. Let me know if you continue to have issues related to this.
