### ISSUE TITLE
Uncaught Error: Encountered an invalid scope end id. Popped -57, expected to pop -111.

### ISSUE THREAD

**Issue by Claytonious** [atom/atom#8060]
Was editing a C# file in a Unity3d .sln with Omnisharp...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Encountered an invalid scope end id. Popped -57, expected to pop -111.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:629

Error: Encountered an invalid scope end id. Popped -57, expected to pop -111.
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopesFromTags (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:619:23)
  at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:601:21)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:294:105)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:271:26
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47

```

### Commands

```
     -0:17.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:17.4.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:15.3.0 omnisharp-atom:intellisense-dot (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:15.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:08.8.0 omnisharp-atom:intellisense-dot (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:08.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:07.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:06.8.0 core:move-down (atom-text-editor.editor.is-focused)
 12x -0:06.6.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:05.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:04.6.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:04.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:03.9.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:03.5.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:02.4.0 core:move-down (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-papercolor-dark-syntax"
    ],
    "disabledPackages": [
      "wrap-guide"
    ]
  },
  "editor": {
    "invisibles": {},
    "softTabs": false,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.11
base16-papercolor-dark-syntax, v0.2.0
linter, v1.2.4
minimap, v4.12.0
omnisharp-atom, v0.22.5
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This will be fixed in the next version of Atom.
