### ISSUE TITLE
Uncaught SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by plaxdan** [atom/atom#8147]
As far as I can tell I only needed to open a file to cause this.

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core
### Stack Trace

Uncaught SyntaxError: Unexpected token :

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:8587

SyntaxError: Unexpected token :
  at [object Object].Tooltip.getPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bootstrap/js/tooltip.js:365:61)
  at [object Object].Tooltip.show (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bootstrap/js/tooltip.js:210:31)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bootstrap/js/tooltip.js:135:41

```
### Commands

```
     -6:11.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -6:08.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:06.0 editor:fold-at-indent-level-2 (atom-text-editor.editor.is-focused)
     -6:04.3.0 editor:fold-at-indent-level-3 (atom-text-editor.editor.is-focused)
     -0:44.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:40 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:38.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:38.2.0 git-plus:diff (atom-text-editor.editor)
  2x -0:33.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:25 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:24.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby-on-rails",
      "language-ruby",
      "todo-show",
      "glist",
      "omnisharp-atom",
      "minimap-color-highlight",
      "live-archive",
      "language-diff",
      "crosshairs",
      "language-jsx",
      "url-encode",
      "atom-color-highlight"
    ],
    "projectHome": "/Users/daniel/dev/ds",
    "themes": [
      "one-light-ui",
      "sepia-syntax"
    ],
    "destroyEmptyPanes": false
  },
  "editor": {
    "scrollPastEnd": true,
    "invisibles": {},
    "showIndentGuide": true,
    "fontSize": 10
  }
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1
atom-beautify, v0.28.8
atom-cli-diff, v1.1.0
autocomplete-paths, v1.0.2
change-case, v0.6.0
coffee-compile, v0.17.3
file-icons, v1.5.8
filesize, v0.2.0
git-plus, v5.2.2
git-tab-status, v1.9.2
highlight-selected, v0.10.1
language-batch, v0.3.3
language-csharp, v0.6.0
language-fsharp, v0.8.4
language-gherkin, v1.0.2
last-cursor-position, v0.9.0
minimap, v4.12.1
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.7
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0
pigments, v0.9.2
project-palette-finder, v2.4.17
sepia-syntax, v1.0.5
set-syntax, v0.3.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
Can you reproduce this consistently? If so, can you be more specific about the steps that reproduce this consistently? Also, can you reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? (`atom --safe`)

**Comment by plaxdan** [comment]
It is inconsistent and I cannot find a way to reliably reproduce it. It just pops up every now and again when I open a coffeescript file.

**Comment by plaxdan** [comment]
One new data point: I can reliably get the error when hovering the mouse over the tab of any open file.

**Comment by mnquintana** [comment]
@plaxdan Can you try seeing if you can reproduce that in safe mode?

**Comment by plaxdan** [comment]
I can't reproduce it in safe or non-safe mode this morning :/ Will keep you posted if/when it emerges again.

**Comment by 50Wliu** [comment]
No follow-up, closing.
