### ISSUE TITLE
Uncaught Error: undefined is not a function

### ISSUE THREAD

**Issue by tswaters** [atom/atom#8187]
[Enter steps to reproduce below:]

1. ... run tests on a sails application

**Atom Version**: 1.0.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: undefined is not a function

```
At c:\Code\mocha-runner\lib\runner.js:44

TypeError: undefined is not a function
    at C:\Code\sails-example\node_modules\sails-disk\node_modules\async\lib\async.js:453:33
    at Array.forEach (native)
    at _each (C:\Code\sails-example\node_modules\sails-disk\node_modules\async\lib\async.js:32:24)
    at Object.async.auto (C:\Code\sails-example\node_modules\sails-disk\node_modules\async\lib\async.js:430:9)
    at Database.initialize (C:\Code\sails-example\node_modules\sails-disk\lib\database.js:56:9)
    at Object.module.exports.adapter.registerConnection (C:\Code\sails-example\node_modules\sails-disk\lib\adapter.js:51:40)
    at C:\Code\sails-example\node_modules\sails\node_modules\waterline\lib\waterline.js:203:29
    at C:\Code\sails-example\node_modules\sails\node_modules\waterline\node_modules\async\lib\async.js:157:13
    at _each (C:\Code\sails-example\node_modules\sails\node_modules\waterline\node_modules\async\lib\async.js:57:9)
    at Object.async.each (C:\Code\sails-example\node_modules\sails\node_modules\waterline\node_modules\async\lib\async.js:156:9)
    at Array.async.auto.registerConnections (C:\Code\sails-example\node_modules\sails\node_modules\waterline\lib\waterline.js:176:13)
    at C:\Code\sails-example\node_modules\sails\node_modules\waterline\node_modules\async\lib\async.js:640:38
    at _each (C:\Code\sails-example\node_modules\sails\node_modules\waterline\node_modules\async\lib\async.js:57:9)
    at Object.async.auto (C:\Code\sails-example\node_modules\sails\node_modules\waterline\node_modules\async\lib\async.js:600:9)
    at Waterline.initialize (C:\Code\sails-example\node_modules\sails\node_modules\waterline\lib\waterline.js:121:9)
    at buildORM (C:\Code\sails-example\node_modules\sails\lib\hooks\orm\build-orm.js:52:15)
```

### Commands

```
  2x -5:05.5.0 mocha-runner:run-specs (atom-text-editor.editor.is-focused)
     -4:16.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:13.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:11 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:04.8.0 mocha-runner:run-specs (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 18
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.0.0
language-ejs, v0.2.0
linter, v1.0.8
linter-eslint, v1.0.8
linter-jsonlint, v0.1.4
linter-scss-lint, v1.0.5
mocha-runner, v1.1.4

# Dev
No dev packages
```

**Comment by tswaters** [comment]
No idea why this is dying, but this is trying to run tests on a sails application -- [specifically this one](https://github.com/tswaters/sails-example)

The exception is during initialization of the sails-disk database.  Really hard to debug what is going on because the debugger isn't attached to that process.  All that can be done is to pass around console.logs ... and the logs I was getting defies any understanding I have of JavaScript.

```js
console.log(typeof tasks === 'function') // true
console.log(tasks) // null ... wat.
```

**Comment by tswaters** [comment]
Oops, thought I added this to the tracker for my own package.... closing this

**Comment by tswaters** [comment]
For posterity, https://github.com/tswaters/atom-mocha-runner/issues/4
