### ISSUE TITLE
Uncaught Error: spawn /usr/share/atom/atom EMFILE

### ISSUE THREAD

**Issue by muka** [atom/atom#8197]
[Enter steps to reproduce below:]

1. ... right click on file, select split on right

**Atom Version**: 1.0.3
**System**: Ubuntu 15.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /usr/share/atom/atom EMFILE

```
At events.js:141

Error: spawn /usr/share/atom/atom EMFILE
  at exports._errnoException (util.js:734:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)
  at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -6:11.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:24.6.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -0:24.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:23.3.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:22.9.0 core:move-up (atom-text-editor.editor.is-focused)
  5x -0:22.6.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:21.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:20.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:20.2.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:17.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:17.7.0 core:cut (atom-text-editor.editor.is-focused)
     -0:16.4.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
  3x -0:15.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:14.7.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:14.4.0 core:cut (atom-text-editor.editor.is-focused)
     -0:13.7.0 core:delete (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.6
js-autoimport, v0.4.0
language-babel, v0.8.0
language-javascript-jsx, v0.3.6
language-tss, v0.4.0
php-debug, v0.1.2
php-getters-setters, v0.5.5
php-introspector, v1.0.0
php-twig, v4.0.0
titanium-alloy, v0.3.4

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
This means that you've run out of file descriptors. When this happens, could you share the output of `ulimit -n` (file descriptor limit) and `lsof -c Atom` (files open due to Atom)?

**Comment by muka** [comment]
It happened once after installing a few plugins (a bit randomly). 
I was unable to get Atom working again (due to many in editor exceptions) so I've cleaned my atom home folder and started over
Anyway I will report back if it happens again. Closing for now

Thank you
