### ISSUE TITLE
Uncaught Error: EAGAIN: resource temporarily unavailable, open '/home/ferdbold/Documents/dev/medi...

### ISSUE THREAD

**Issue by ferdbold** [atom/atom#8202]
[Enter steps to reproduce below:]

1. Every once in a while when I save any type of file

**Atom Version**: 1.0.3
**System**: Ubuntu 14.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EAGAIN: resource temporarily unavailable, open '/home/ferdbold/Documents/dev/mediawiki-vagrant/mediawiki/extensions/Graph/modules/ve-graph/ve.ui.MWGraphDialog.js'

```
At /usr/share/atom/resources/app.asar/src/pane.js:801

Error: EAGAIN: resource temporarily unavailable, open '/home/ferdbold/Documents/dev/mediawiki-vagrant/mediawiki/extensions/Graph/modules/ve-graph/ve.ui.MWGraphDialog.js'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:273:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:371:21)
    at File.module.exports.File.writeSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:345:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1002:17)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:988:19)
```

### Commands

```
     -0:50 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:48.6.0 editor:move-line-down (atom-text-editor.editor.is-focused)
  2x -0:46.7.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:46.2.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:45.7.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -0:45.1.0 core:move-down (atom-text-editor.editor.is-focused)
  5x -0:44.5.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:43.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:42.7.0 core:save (atom-text-editor.editor.is-focused)
  5x -0:37.1.0 editor:move-line-down (atom-text-editor.editor.is-focused)
     -0:35.8.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:32.4.0 editor:move-line-down (atom-text-editor.editor.is-focused)
  3x -0:31.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:30.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:03.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:00.4.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "softTabs": false,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v5.2.4
docblockr, v0.7.3
linter, v1.3.0
linter-jshint, v1.1.4
minimap, v4.12.2
project-manager, v1.15.11
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by RiFi2k** [comment]
Do you happen to use a live reload setup for development?

I started using BrowserSync and now 50% of the time when I go to save a get this same sort of any error. It's driving me nuts...  I'm running Ubuntu and have NFS set up to a virtual server with the live reload.

**Comment by etremblay** [comment]
I get the same sort of errors with grunt watch with a similar setup.

vagrant box with sources shared via nfs.

Ubuntu 14.04

```
[D] Task source: /xxx/node_modules/grunt-contrib-copy/tasks/copy.js
Warning: Unable to write "public/js/AjaxUploader.js" file (Error code: EAGAIN). Use --force to continue.
Error: EAGAIN, resource temporarily unavailable 'public/js/AjaxUploader.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at Object.file.write (/xxx/node_modules/grunt/lib/grunt/file.js:296:10)
    at Object.file.copy (/xxx/node_modules/grunt/lib/grunt/file.js:332:10)
    at /xxx/node_modules/grunt-contrib-copy/tasks/copy.js:56:22
    at Array.forEach (native)
    at /xxx/node_modules/grunt-contrib-copy/tasks/copy.js:43:20
    at Array.forEach (native)
    at Object.<anonymous> (/xxx/node_modules/grunt-contrib-copy/tasks/copy.js:40:16)
```
