### ISSUE TITLE
Failed to load the atom-typescript package

### ISSUE THREAD

**Issue by xandervdm** [atom/atom#8223]
[Enter steps to reproduce below:]

1. Just opened Atom to load an Ember project folder...

**Atom Version**: 1.0.4
**System**: Microsoft Windows 7 Ultimate 64bit
**Thrown From**: Atom Core

### Stack Trace

Failed to load the atom-typescript package

```
At UNKNOWN: unknown error, open 'C:\Users\xander\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\content\3717b434a4e153298f9ddfdd9b9c8de3f621e195\documentationview.json'

Error: UNKNOWN: unknown error, open 'C:\Users\xander\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\content\3717b434a4e153298f9ddfdd9b9c8de3f621e195\documentationview.json'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.fsPlus.writeFileSync (C:\Users\xander\AppData\Local\atom\app-1.0.4\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (C:\Users\xander\AppData\Local\atom\app-1.0.4\resources\app.asar\node_modules\less-cache\lib\less-cache.js:155:17)
    at LessCache.module.exports.LessCache.putCachedCss (C:\Users\xander\AppData\Local\atom\app-1.0.4\resources\app.asar\node_modules\less-cache\lib\less-cache.js:225:19)
    at LessCache.module.exports.LessCache.cssForFile (C:\Users\xander\AppData\Local\atom\app-1.0.4\resources\app.asar\node_modules\less-cache\lib\less-cache.js:276:12)
    at LessCompileCache.module.exports.LessCompileCache.cssForFile (C:\Users\xander\AppData\Local\atom\app-1.0.4\resources\app.asar\src\less-compile-cache.js:40:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\xander\AppData\Local\atom\app-1.0.4\resources\app.asar\src\theme-manager.js:308:33)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v5.0.28
linter, v1.2.4

# Dev
No dev packages
```

**Comment by benogle** [comment]
This issue was moved to TypeStrong/atom-typescript#518
