### ISSUE TITLE
Make it possible to open an untitled TextEditor from `apm test`.

### ISSUE THREAD

**Issue by bolinfest** [atom/atom#8239]
I am trying to open an untitled window from `apm test`. Here is what I am trying to do from my test since it works fine from the Chrome DevTools console in Atom:

``` js
atom.commands.dispatch(atom.views.getView(atom.workspace), 'application:new-file');
```

Unfortunately, it does not appear to succeed when run from my test. I see the following stacktrace and `atom.workspace.getTextEditors().length` does not increase as I would expect:

```
-2015-08-03 23:34:10.031 Atom[46768:1925367] Cannot read property 'pathToOpen' of undefined
2015-08-03 23:34:10.033 Atom[46768:1925367] TypeError: Cannot read property 'pathToOpen' of undefined
    at AtomApplication.module.exports.AtomApplication.openPath (/Users/mbolin/src/atom/src/browser/atom-application.coffee:585:24)
    at AtomApplication.<anonymous> (/Users/mbolin/src/atom/src/browser/atom-application.coffee:280:70)
    at emitNone (events.js:67:13)
    at AtomApplication.emit (events.js:163:7)
    at EventEmitter.<anonymous> (/Users/mbolin/src/atom/src/browser/atom-application.coffee:460:24)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:86:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
```

It's good to test with untitled windows because most packages don't take into account that `TextEditor.getPath()` could return `undefined`.

@abe33 seems to have found the root cause in https://discuss.atom.io/t/create-an-untitled-window-from-apm-test/19568

**Comment by benogle** [comment]
What about 

```
aPromise = atom.workspace.open()
```

Does that do what you want?

**Comment by maxbrunsfeld** [comment]
The bug @abe33 found seems legit. @bolinfest are you interested in fixing this?
