### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, fdatasync

### ISSUE THREAD

**Issue by williamsEye** [atom/atom#8252]
[Enter steps to reproduce below:]
1. saving a file to a network drive
2. ...

**Atom Version**: 1.0.4
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, fdatasync

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:801

Error: ENOENT: no such file or directory, fdatasync
  at Error (native)
  at Object.fs.fdatasyncSync (fs.js:765:18)
  at TextBuffer.module.exports.TextBuffer.backUpFileContentsBeforeWriting (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1082:10)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1008:31)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:992:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:539:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:522:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -2:52.6.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -1:38.5.0 grammar-selector:show (atom-text-editor.editor)
     -1:36.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:28.6.0 grammar-selector:show (atom-text-editor.editor)
     -1:26.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:24.6.0 command-palette:toggle (a.inline-block)
  5x -1:19.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:07.2.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:01.5.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "project-manager",
      "indent-guide-improved",
      "sass-autocompile"
    ]
  },
  "editor": {
    "invisibles": {},
    "backUpBeforeSaving": true,
    "showIndentGuide": true
  }
}
```
### Installed Packages

``` coffee
# User
SFTP-deployment, v1.0.2
atom-autocomplete-php, v0.6.5
atom-beautify, v0.28.10
color-picker, v2.0.11
emmet, v2.3.12
emmet-snippets-compatibility, v1.0.0
language-SCSS, v0.4.0
linter-scss-lint, v2.0.0
meteor-api, v2.20.0
minimap, v4.12.2
pigments, v0.9.3
project-ring, v0.33.2
project-view, v0.1.2

# Dev
No dev packages
```

**Comment by bronson** [comment]
Network drives can be so weird.  @williamsEye do you know what the filesystem was?  SMB?

My first guess is that this is the way the filesystem is telling us that it doesn't support fdatasync.  At this point, though, there could be all kinds of reasons.
