### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory [..] app-1.0.2\resources\app.asar

### ISSUE THREAD

**Issue by sublines** [atom/atom#8268]
Not sure if duplicate of #7796, #6140?

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Jascha\AppData\Local\atom\app-1.0.2\resources\app.asar'

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: WORKSTATION
**Thrown From**: [release-notes](https://github.com/atom/release-notes) package, v0.53.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Jascha\AppData\Local\atom\app-1.0.2\resources\app.asar'

```
At fs.js:519

Error: ENOENT: no such file or directory, open 'C:\Users\Jascha\AppData\Local\atom\app-1.0.2\resources\app.asar'
    at Error (native)
    at fs.openSync (fs.js:544:18)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:402:12)
    at Object.loadFile [as .js] (C:\Users\Jascha\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:138:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at atom-workspace.<anonymous> (C:\Users\Jascha\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\release-notes\lib\main.js:40:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Jascha\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
```
### Commands

```
     -2:06.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
     -0:11.2.0 window:update-available (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "linter-jshint",
      "linter-js-standard"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
Could you reinstall Atom 1.0.5 and report whether this still happens? What OS are you on?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/8268#issuecomment-130383738. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
