### ISSUE TITLE
Atom crashes immediately on launch

### ISSUE THREAD

**Issue by calebjessie** [atom/atom#8286]
I've updated to the latest version.

Console spits out this:

```
Error: EPERM: operation not permitted, open 'C:\Users\Club\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\imports.json'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.fsPlus.writeFileSync (C:\Users\Club\AppData\Local\atom\app-1.0.4\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (C:\Users\Club\AppData\Local\atom\app-1.0.4\resources\app.asar\node_modules\less-cache\lib\less-cache.js:155:17)
    at LessCache.module.exports.LessCache.setImportPaths (C:\Users\Club\AppData\Local\atom\app-1.0.4\resources\app.asar\node_modules\less-cache\lib\less-cache.js:113:12)
    at new LessCache (C:\Users\Club\AppData\Local\atom\app-1.0.4\resources\app.asar\node_modules\less-cache\lib\less-cache.js:32:12)
    at new LessCompileCache (C:\Users\Club\AppData\Local\atom\app-1.0.4\resources\app.asar\src\less-compile-cache.js:20:20)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\Club\AppData\Local\atom\app-1.0.4\resources\app.asar\src\theme-manager.js:299:26)
```

**Comment by thomasjo** [comment]
Are you able to reproduce this in safe mode? `atom --safe`

**Comment by calebjessie** [comment]
Yeah, when I run it in safe mode it says the same thing in the console.

**Comment by damieng** [comment]
Are you by chance running an anti-virus package? EPERM tends to be a result of those denying access to files.

**Comment by damieng** [comment]
No response, closing.
