### ISSUE TITLE
Can't Complete Atom Build on Win10 (VS2013)

### ISSUE THREAD

**Issue by Quasaur** [atom/atom#8309]
npm-debug.log is here: https://www.dropbox.com/s/gwgvuz25zw86bnq/npm-debug.log?dl=0

Win10 Pro 64-bit Build 10.0.10240
HP EliteBook 8740w (i7) with 6GB RAM
Visual Studio 2013 with Update 4
Node.js\IO.js 3.0.0
npm 2.13.3
runas@2.0.0

```
Node: v3.0.0
npm: v2.13.3
Python: v2.7.10
Installing build modules...
gyp: C:\Users\quasa\.node-gyp\3.0.0\common.gypi not found (cwd: C:\src\atom\build\node_modules\runas) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\src\atom\build\node_modules\npm\node_modules\node-gyp\lib\configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\iojs\\node.exe" "C:\\src\\atom\\build\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\src\atom\build\node_modules\runas
gyp ERR! node -v v3.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\iojs\\node.exe" "C:\\src\\atom\\build\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\src\\atom\\build\\.npmrc" "install" "--loglevel" "error"
npm ERR! node v3.0.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\src\atom\build\npm-debug.log
```

**Comment by thomasjo** [comment]
Building with io.js v3.0.0 is not supported due to some breaking changes specific to node-gyp. This has been fixed in Electron v0.30.4, but we still need to [get Atom running Electron](https://github.com/atom/atom/pull/7877). In the meantime, downgrade to io.js v2.x when building Atom from source.
