### ISSUE TITLE
saving caused an error (bug?)

### ISSUE THREAD

**Issue by ilaudy** [atom/atom#8322]
Uncaught Error: EINVAL: invalid argument, fdatasync
Here is the stack trace:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.5
**System**: Debian GNU/Linux
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EINVAL: invalid argument, fdatasync

```
At /usr/share/atom/resources/app.asar/src/pane.js:801

Error: EINVAL: invalid argument, fdatasync
  at Error (native)
  at Object.fs.fdatasyncSync (fs.js:765:18)
  at TextBuffer.module.exports.TextBuffer.backUpFileContentsBeforeWriting (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1082:10)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1008:31)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:992:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:539:18)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:522:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app.asar/src/workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -1:22.6.0 find-and-replace:use-selection-as-find-pattern (atom-text-editor.editor.is-focused)
  3x -1:18.9.0 find-and-replace:find-next (atom-text-editor.editor.mini.is-focused)
     -1:11.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:24.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:24.8.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -0:23.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:05.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:05.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:03.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "atom-runner",
      "latex"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 13,
    "softWrap": true,
    "backUpBeforeSaving": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-bibtex, v0.6.0
autocomplete-python, v0.5.3
language-latex, v0.6.1
pdf-view, v0.23.0
remote-edit, v1.8.15

# Dev
No dev packages
```

**Comment by izuzak** [comment]
> Uncaught Error: EINVAL: invalid argument, fdatasync

cc @nathansobo

**Comment by nathansobo** [comment]
Looks like another issue syncing a directory entry. I should probably just swallow all exceptions that occur when we try to do that.
