### ISSUE TITLE
"Uncaught TypeError: undefined is not a function" when using native copy in Markdown preview

### ISSUE THREAD

**Issue by gpaumier** [atom/atom#8335]
Apologies if this has already been reported.

I can reproduce this every time I attempt to copy content using my keyboard's native Copy function (*not* Ctrl+C) in Markdown Preview. I'm reporting the issue here since it indicates it was thrown from "Atom Core".

The details are below:

**Atom Version**: 1.0.0
**System**: openSUSE 13.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/share/atom/resources/app.asar/src/window-event-handler.js:165

TypeError: undefined is not a function
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:165:20)
    at HTMLDocument.handler (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:115:32)
    at HTMLDocument.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
    at HTMLDocument.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:180:20)
```

### Commands

```
  2x -1:07.9.0 core:copy (div.markdown-preview.native-key-bindings)
```

**Comment by gpaumier** [comment]
Note: The same issue arises when using the native Cut and native Paste. They don't make sense in this context because the preview is read-only, but they probably shouldn't throw an error either.

The stack traces are the same as above; the commands are:

```
     -0:00.6.0 core:cut (div.markdown-preview.native-key-bindings)
```
and

```
     -0:34.5.0 core:paste (div.markdown-preview.native-key-bindings)
```

**Comment by izuzak** [comment]
Thanks for the report, @gpaumier  -- can you please update to Atom 1.0.5 and see if you can still reproduce? :bow:

**Comment by gpaumier** [comment]
@izuzak I've just updated to 1.0.6 (the latest version I could download from the website) but I don't have access to that keyboard today; I'll check tomorrow and follow up :)

**Comment by gpaumier** [comment]
I can confirm that the issue is fixed in 1.0.6. Thanks!

**Comment by stve** [comment]
Running 1.0.10 on Yosemite and I am also getting this error. 

It doesn't appear to be related to copy/paste, I usually get the error when I open a markdown file for the first time. 

Flow to reproduce is `cmt-t` to select and open the file, get the error, close the error dialog, `cmt-t` to select and open the file again and the second time the file opens without error.

```
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

TypeError: undefined is not a function
    at <anonymous>:5:12
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:281:16
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:342:18
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:352:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:339:26
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:345:20)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:313:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:489:16
    at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
    at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
    at process._tickCallback (node.js:357:13)
```

**Comment by davelnewton** [comment]
I get the error when I toggle the preview:

    TypeError: undefined is not a function
      at /Users/dnewton/.atom/init.coffee:10:20
      at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
      at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:352:27)
      at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:339:26
      at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
      at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:345:20)
      at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:313:14)
      at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:489:16
      at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
      at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
      at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
      at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:817:14
      at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
      at process._tickCallback (node.js:357:13)

**Comment by izuzak** [comment]
@stve Strange, I'm not getting the error when I do that. Can you try reproducing it in Atom 1.0.11 in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? If you can still reproduce the problem, can you record a GIF, just so I can see what exactly you're doing?

@davelnewton Your stack trace contains this at the top:

```
TypeError: undefined is not a function
  at /Users/dnewton/.atom/init.coffee:10:20
```

That makes me think something in your init.coffee is causing the problem. Do you have any content in that file and can you share it here?

**Comment by davelnewton** [comment]
@izuzak Agh, sorry, didn't mean to post that--I tracked it down, it was a hook I have for editor panes opening, the markdown preview window isn't one, so I had to check for `editor.lineTextForBufferRow`

**Comment by stve** [comment]
@izuzak I think `init.coffee` [may have been the culprit](https://github.com/stve/dotfiles/commit/3bac114923a9ff4e8052705e331cae0715e7888e#diff-c8ba2931c6557e793ac3915c98c46c10L3) for me as well, I haven't seen this in a few days now. Thanks for your help.
