### ISSUE TITLE
Uncaught Error: Authorization Required

### ISSUE THREAD

**Issue by Nitrino** [atom/atom#8336]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.5
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Authorization Required

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:673

Error: Authorization Required
  at Object.ensureErrorObject (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:261:20)
  at Promise._rejectCallback (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:465:22)
  at Promise._settlePromiseFromHandler (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:509:17)
  at Promise._settlePromiseAt (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:577:18)
  at Promise._settlePromises (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:693:14)
  at Async._drainQueue (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:123:16)
  at Async._drainQueues (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:133:10)
  at MutationObserver.Async.drainQueues (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:15:14)
  at process._tickCallback (node.js:367:9)

```

### Commands

```
     -6:04.9.0 atom-twitter:home (div.settings-view.pane-item)
     -5:56.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:37.9.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -3:32.9.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:24.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:24.5.0 slack-chat:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:44.3.0 command-palette:toggle (atom-pane.pane.active)
     -2:40 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:37.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:37.6.0 atom-twitter:tweet (atom-pane.pane.active)
 15x -2:34 core:backspace (atom-text-editor.editor.is-focused)
  4x -2:09.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -2:07.6.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -2:05.8.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:33.5.0 core:select-all (atom-text-editor.editor.is-focused)
 23x -0:42.9.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "fontSize": 13,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-spotify2, v2.1.2
atom-twitter-client, v0.4.2
bezier-curve-editor, v0.7.2
browser-plus, v0.0.34
clipboard-plus, v0.5.1
emmet, v2.3.12
file-icons, v1.6.3
imdone-atom, v1.1.16
language-svg, v0.8.0
project-manager, v1.15.11
ruby-block, v0.3.5
ruby-slim, v0.2.0
slack-chat, v3.2.8

# Dev
No dev packages
```

**Comment by Nitrino** [comment]
sorry, wrong issues
