### ISSUE TITLE
Windows scripts not updated after updating

### ISSUE THREAD

**Issue by avdg** [atom/atom#8352]
`C:\Users\<user>\AppData\Local\atom\bin` doesn't seem to be updated after an update has been installed. Though atom added this directory to the PATH variable so atom is available from the windows console.

So then there is a update and this is showing up in the console:

```
> atom .
The system cannot find the path specified.
```

So it happens that atom updated to version 1.0.6, but when I look at the files in `C:\Users\<user>\AppData\Local\atom\bin` I can see that these ~~binary~~ executable files all refer to `app-1.0.4`. By having this issue multiple times, I know I can fix this by rewriting this to `app-1.0.6`, but it would be very convenient if the updater all does this on instead of wasting time on figuring out why its not working.

**Comment by avdg** [comment]
Hmm I've done some research, though I don't know how to test if this function gets executed while the update is being executed.

https://github.com/atom/atom/blob/efb2ea544f64371fcbd8d149e06b223c3ea4ab56/src/browser/squirrel-update.coffee#L135

**Comment by 50Wliu** [comment]
This happens to me occasionally as well.  Update to 1.0.7 worked perfectly, but I don't believe anything got updated during 1.0.8.  When I checked during 1.0.9 (due to the 'system cannot find the path specified' errors), this is what I found:
* Both apm and apm.cmd were pointing towards 1.0.7
* atom was empty (:exclamation:)
* atom.cmd was pointing towards 1.0.9

**Comment by avdg** [comment]
Hmm.. it would be nice to collect more information about that folder from other users (if they want)... it could be used as a test case. Or are there better ways to expose this problem?

**Comment by 50Wliu** [comment]
Here's some errors in my `SquirrelSetup.log`, not sure if they're entirely relevant though:
```
2015-08-29 11:05:40> UpdateInfo: Couldn't get release notes for:atom-1.0.9-delta.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\username\AppData\Local\atom\packages\atom-1.0.9-delta.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__2(ReleaseEntry x)
2015-08-29 11:05:41> Program: Starting Squirrel Updater: --update https://atom.io/api/updates
2015-08-29 11:05:41> Program: Starting update, downloading from https://atom.io/api/updates
2015-08-29 11:05:41> Program: About to update to: C:\Users\username\AppData\Local\atom
2015-08-29 11:05:41> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
2015-08-29 11:05:41> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES
2015-08-29 11:05:42> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.0.9-delta.nupkg
2015-08-29 11:06:11> Program: Failed to apply updates, falling back to full updates: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(String zipFileName, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(String zipFileName, String targetDirectory, String fileFilter)
   at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassaf.<createFullPackagesFromDeltas>b__ab()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__b1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__41.MoveNext()
2015-08-29 11:06:11> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
2015-08-29 11:06:11> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES
2015-08-29 11:06:13> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.0.9-full.nupkg
2015-08-29 11:06:30> ApplyReleasesImpl: Writing files to app directory: C:\Users\username\AppData\Local\atom\app-1.0.9
2015-08-29 11:07:20> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\username\AppData\Local\atom\app-1.0.9\atom.exe]
2015-08-29 11:07:38> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\username\AppData\Local\atom\app-1.0.9\atom.exe: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Squirrel.Utility.<>c__DisplayClassf.<InvokeProcessAsync>b__e()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassc8.<<invokePostInstall>b__bc>d__ca.MoveNext()
```

**Comment by avdg** [comment]
Uh, don't say that windows is complaining about long paths...

**Comment by avdg** [comment]
I found mine SquirrelSetup.log btw. There is lots of data so I might spend time studying it.

**Comment by avdg** [comment]
If there is a suggestion to make though.. I really don't like that every file compressed or decompressed (from I assume azar) is being logged. Clutters the logs very easily.

**Comment by damieng** [comment]
Tracking this under https://github.com/atom/atom/issues/11450 as there are a few that boil down to 'bin' not being installed or updated.
