### ISSUE TITLE
Atom error, windows

### ISSUE THREAD

**Issue by Gibbz** [atom/atom#8359]
Atom is opening in developer mode, and is unusable: 

Error: EPERM: operation not permitted, open 'C:\Users\Bronson\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\imports.json'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.fsPlus.writeFileSync (C:\Users\Bronson\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (C:\Users\Bronson\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\less-cache\lib\less-cache.js:155:17)
    at LessCache.module.exports.LessCache.setImportPaths (C:\Users\Bronson\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\less-cache\lib\less-cache.js:113:12)
    at new LessCache (C:\Users\Bronson\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\less-cache\lib\less-cache.js:32:12)
    at new LessCompileCache (C:\Users\Bronson\AppData\Local\atom\app-1.0.5\resources\app.asar\src\less-compile-cache.js:20:20)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\Bronson\AppData\Local\atom\app-1.0.5\resources\app.asar\src\theme-manager.js:299:26)

**Comment by maxbrunsfeld** [comment]
Maybe try reinstalling Atom? It looks like it's installed somewhere that your account lacks read/write permissions.

**Comment by Gibbz** [comment]
deleting my user profile fixed the issue... Not sure what happened as it
was working fine then suddenly that happened.

Cheers :)

**Comment by ilyaigpetrov** [comment]
I've stumbled upon the same `EPERM` error in `Windows/Atom 1.0.7` while opening file with restricted write permissions. Changing permissions with `chmod 777 filename` helped.  
Could you please make Atom not to respect filesystem write permissions somehow? In my case the file got restricted permissions after windows reinstall and now I just don't want to bother with massive permissions change for every project I work on.

**Comment by batjko** [comment]
Quite often the permissions issue is at the level of the `.atom` folder (under `C:\Users\[useraccount]\AppData\.atom`.

It makes sense to just change that folder (and children) to have full permissions for the current user. I don't know why that sometimes isn't the case.

**Comment by ilyaigpetrov** [comment]
@batjko maybe sometimes there are such issues with `.atom` but I've checked it for my case -- setting full permissions to `.atom` doesn't affect project folder permissions. And it is as it should be.  

In my case while reinstalling windows I've changed username so old files write permissions defined for an old user don't work any more for a new user, that's the case.  

After some consideration I came to conclusion that Atom can't ignore file owner until it is run as administrator (or root). Only file owner or admin can change permissions. And this makes sense.  

**So if you are faced with the same error -- just change permissions for files you are trying to edit.**
Or run Atom as administrator (under root), you may create a corresponding link in Windows for convenience. And maybe Atom on `EPERM` error should offer to restart itself with root privileges. That would be great.

**Comment by batjko** [comment]
Yes, of course your project files need to have the right permissions for the current user, that's a basic given on any OS and should be self-evident.

What I was saying is that on top of that, some people have reported problems working in Atom, that could be traced down to bad permissions on Atom's `.atom` folder (which contains packages and settings for the current user).

Glad you worked it out for your specific issue!

**Comment by ilyaigpetrov** [comment]
`Error: EPERM: operation not permitted` is somewhat cryptic, it may be `Can't edit readonly file with current Atom permissions.`
