### ISSUE TITLE
Saving files in the application bundle fails with backups enabled due to interference by ASAR

### ISSUE THREAD

**Issue by alflanagan** [atom/atom#8399]
[Enter steps to reproduce below:]
1. open a file in a read-only directory
2. try to activate find, hit some other key(s)(??) instead (sorry don't know which).

**Atom Version**: 1.0.7
**System**: Linux Mint
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: ENOENT, src/package-manager.js~ not found in /opt/atom/resources/app.asar

```
At /opt/atom/resources/app.asar/src/pane.js:801

Error: ENOENT, src/package-manager.js~ not found in /opt/atom/resources/app.asar
  at createNotFoundError (ATOM_SHELL_ASAR.js:101:13)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:126:15)
  at TextBuffer.module.exports.TextBuffer.backUpFileContentsBeforeWriting (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1077:21)
  at TextBuffer.module.exports.TextBuffer.saveAs (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1008:31)
  at TextBuffer.module.exports.TextBuffer.save (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:992:19)
  at TextEditor.module.exports.TextEditor.save (/opt/atom/resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/opt/atom/resources/app.asar/src/pane.js:539:18)
  at Pane.module.exports.Pane.saveActiveItem (/opt/atom/resources/app.asar/src/pane.js:522:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/opt/atom/resources/app.asar/src/workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (/opt/atom/resources/app.asar/src/workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:241:29)
  at /opt/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -3:49.2.0 editor:toggle-soft-wrap (atom-text-editor.editor.is-focused)
     -2:44.8.0 timecop:view (atom-text-editor.editor.is-focused)
     -2:18.6.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-material-ui)
     -1:01.9.0 project-manager:toggle (atom-text-editor.editor.is-focused)
     -0:59.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:59.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:58.3.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-material-ui)
 19x -0:51.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:14.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:14.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:01.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-light-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "backUpBeforeSaving": true,
    "preferredLineLength": 100
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.11
atom-material-ui, v0.5.20
autocomplete-plus-python-jedi, v0.3.6
clipboard-plus, v0.5.1
coffee-compile, v0.18.0
coffee-porter, v0.8.1
file-icons, v1.6.3
imdone-atom, v1.1.19
language-javascript-semantic, v0.2.1
language-python-django-templates, v0.1.0
linter, v1.3.4
linter-clojure, v0.0.5
linter-coffeelint, v1.0.2
linter-jshint, v1.1.5
linter-pep257, v0.2.1
linter-pep8, v1.0.1
linter-pylint, v0.2.2
minimap, v4.12.3
minimap-git-diff, v4.1.7
minimap-linter, v1.0.0
project-manager, v1.15.11
wordcount, vundefined

# Dev
No dev packages
```

**Comment by nathansobo** [comment]
@alflanagan From the stack trace it looks like you might be hitting save. Is that possible?

**Comment by nathansobo** [comment]
Ah, this looks to be related to editing Atom's own source code out of the App bundle. I think Atom is getting confused by the attempt to read from a location that's normally cached. Can you confirm that's what you're doing in this case?
