### ISSUE TITLE
Try install Atom on archlinux (script/build) err  

### ISSUE THREAD

**Issue by wkchen66** [atom/atom#8407]
```
[wkchen@wkchen atom]$ script/build 
Node: v0.12.7
npm: v2.13.5
Installing build modules...
Installing apm...
gyp ERR! configure error 
gyp ERR! stack Error: node-v0.10.35.tar.gz local checksum 0b2da40c0301d287891c810fea39a9ec901377cddaf13f51bb80339b98f0b3b8 not match remote 0043656bb1724cb09dbdc960a2fd6ee37d3badb2f9c75562b2d11235daa40a03
gyp ERR! stack     at deref (/home/wkchen/atom/build/node_modules/npm/node_modules/node-gyp/lib/install.js:307:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/home/wkchen/atom/build/node_modules/npm/node_modules/node-gyp/lib/install.js:348:13)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:908:16
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Linux 4.1.4-1-ARCH
gyp ERR! command "node" "/home/wkchen/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/wkchen/atom/apm/node_modules/atom-package-manager/node_modules/keytar
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: node-v0.10.35.tar.gz local checksum 1d8afa5af3565be4b941d798206d8fa7eca442200513eaa05f9553a0603e0119 not match remote 0043656bb1724cb09dbdc960a2fd6ee37d3badb2f9c75562b2d11235daa40a03
gyp ERR! stack     at deref (/home/wkchen/atom/build/node_modules/npm/node_modules/node-gyp/lib/install.js:307:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/home/wkchen/atom/build/node_modules/npm/node_modules/node-gyp/lib/install.js:348:13)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:908:16
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Linux 4.1.4-1-ARCH
gyp ERR! command "node" "/home/wkchen/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/wkchen/atom/apm/node_modules/atom-package-manager/node_modules/first-mate/node_modules/oniguruma
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: node-v0.10.35.tar.gz local checksum 8c1547ca496f29202abd0d2549ce83e84d9a420e19a488fcfa849be1af85fff4 not match remote 0043656bb1724cb09dbdc960a2fd6ee37d3badb2f9c75562b2d11235daa40a03
gyp ERR! stack     at deref (/home/wkchen/atom/build/node_modules/npm/node_modules/node-gyp/lib/install.js:307:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/home/wkchen/atom/build/node_modules/npm/node_modules/node-gyp/lib/install.js:348:13)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:908:16
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Linux 4.1.4-1-ARCH
gyp ERR! command "node" "/home/wkchen/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/wkchen/atom/apm/node_modules/atom-package-manager/node_modules/git-utils
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.1.4-1-ARCH
npm ERR! argv "node" "/home/wkchen/atom/build/node_modules/.bin/npm" "--userconfig=/home/wkchen/atom/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! keytar@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@2.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wkchen/atom/apm/npm-debug.log
```

**Comment by maxbrunsfeld** [comment]
Can you run `script/clean` and try again?

**Comment by wkchen66** [comment]
Tried, still err . @maxbrunsfeld

**Comment by deprint** [comment]
Did you install all dependencies before `script/build`, most importantly `libgnome-keyring`?
I had a similar error message because `keytar` depends on it.

**Comment by aerth** [comment]
I had same error today on arch linux after canceling first build. Worked after running ```script/clean``` like @maxbrunsfeld said

**Comment by hasJackb** [comment]
This is also failing for me. What I did:

```
git clone https://github.com/atom/atom.git
cd atom
sudo pacman -S --needed gconf base-devel git nodejs npm libgnome-keyring python2
export PYTHON=/usr/bin/python2
git fetch -p
git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
script/build # failed with the error above
sudo pacman -Syu
script/clean
script/build
python --version # Python 2.7.6
```

**Comment by afternone** [comment]
try
```
sudo npm config set python /usr/bin/python2 -g
```
then
```
script/build
```

**Comment by hasJackb** [comment]
@wkchen66 I was able to build on Arch (4.1.6-1-ARCH x86_64) after doing the following:

* Install [nvm](https://github.com/creationix/nvm)
* Set node to v0.12.0
* Set npm to v2.5.1 (done automatically by nvm)
* `export PYTHON=$(which python)`
* Run `script/clean && script/build`
* Run `sudo script/grunt install`

I'm not sure what was causing the problem. I'd previously been attempting to build using the system python2, but with pyenv active in my shell, which may have been causing conflicts. It's also possible that the version of node installed by default in Arch (4.2.1 at time of writing) is too new, and reverting to 0.12.0 via nvm solved it. YMMV.

**Comment by hasJackb** [comment]
I believe I've confirmed that it's the version of node that's causing the problem. I switched back to the system node (v4.2.1), but left the python version as it was on success. I got node-gyp errors both with and without @afternone's suggestion about setting the python.
