### ISSUE TITLE
Failed to activate the atom-beautify package

### ISSUE THREAD

**Issue by hukuuu** [atom/atom#8421]
[Enter steps to reproduce below:]

1. Trying to save .h file

**Atom Version**: 1.0.7
**System**: Microsoft Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\User\AppData\Local\atom\app-1.0.7\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/C:/Users/User/.dotfiles/atom/packages/atom-beautify/src/beautifiers/index.coffee:10:11)
    at Object.<anonymous> (/C:/Users/User/.dotfiles/atom/packages/atom-beautify/src/beautifiers/index.coffee:707:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\User\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
     -0:28.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-oceanic-reef-syntax.theme-one-dark-ui)
     -0:10.2.0 vim-mode:change (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:09.8.0 vim-mode:select-inside-word (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:05.9.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:04.6.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "projectHome": "d:\\projects",
    "themes": [
      "one-dark-ui",
      "oceanic-reef-syntax"
    ],
    "disabledPackages": [
      "highlight-column"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "fontSize": 20,
    "lineHeight": 1.25,
    "useHardwareAcceleration": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.11
atom-pair, v2.0.5
ctrl-last-tab, v0.2.0
ex-mode, vundefined
file-icons, v1.6.5
javascript-snippets, v1.0.0
oceanic-reef-syntax, v0.6.0
sync-settings, v0.6.0
vim-mode, v0.58.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Looks like there was an issue while installing the package, have you tried reinstalling it?

It it persists, I think this should be reported on the [atom-beautify](https://github.com/Glavin001/atom-beautify) repository instead.
