### ISSUE TITLE
Uncaught Error: EMFILE: too many open files, open 'C:\Users\t5r4e_000\Documents\stratosphere\stra...

### ISSUE THREAD

**Issue by asosoman** [atom/atom#8429]
[Enter steps to reproduce below:]

Working normal way. Just 4 files opened, Hours later, I got the error message and then the files opened get saved with 0 bytes. 
(so, losing all the info in them) 

**Atom Version**: 1.0.7
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EMFILE: too many open files, open 'C:\Users\t5r4e_000\Documents\stratosphere\stratosphere.py'

```
At C:\Users\t5r4e_000\AppData\Local\atom\app-1.0.7\resources\app.asar\src\workspace.js:476

Error: EMFILE: too many open files, open 'C:\Users\t5r4e_000\Documents\stratosphere\stratosphere.py'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Project.module.exports.Project.open (C:\Users\t5r4e_000\AppData\Local\atom\app-1.0.7\resources\app.asar\src\project.js:371:27)
    at Workspace.module.exports.Workspace.openURIInPane (C:\Users\t5r4e_000\AppData\Local\atom\app-1.0.7\resources\app.asar\src\workspace.js:453:31)
    at Workspace.module.exports.Workspace.open (C:\Users\t5r4e_000\AppData\Local\atom\app-1.0.7\resources\app.asar\src\workspace.js:379:19)
    at EventEmitter.<anonymous> (C:\Users\t5r4e_000\AppData\Local\atom\app-1.0.7\resources\app.asar\src\window-event-handler.js:46:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -5:18.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:01.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:51.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:46.5.0 core:save (atom-text-editor.editor.is-focused)
     -4:29 core:move-right (atom-text-editor.editor.is-focused)
     -4:28.7.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -4:25.4.0 core:undo (atom-text-editor.editor.is-focused)
  4x -4:21.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:00.2.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -3:59.5.0 core:select-to-bottom (atom-text-editor.editor.is-focused)
     -3:58.6.0 core:copy (atom-text-editor.editor.is-focused)
     -3:56.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:41.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:39.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:21.8.0 core:select-to-top (atom-text-editor.editor.is-focused)
     -0:21.2.0 core:copy (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "minimap"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 16
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.11
autocomplete-plus-python-jedi, v0.3.6
autocomplete-python, v0.5.3
create-github-repo, v1.1.2
github-utils, v0.6.1
linter, v1.3.4
linter-pylama, v0.1.5
my-github-profile, v0.2.1
odoo-snippets, v0.1.0
remote-edit, v1.8.15
run-in-terminal, v0.4.2
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@kevinsawicki I'm guessing this one was fixed by https://github.com/atom/atom/pull/8927 as well, but since it was opened a while ago, just wanted ping you on it in case I'm wrong.

**Comment by kevinsawicki** [comment]
> but since it was opened a while ago, 

Yeah, I saw this one but opted not to close it initially since it was older. Rouge packages could easily causing this kind of issue as well so I wanted to ping this issue once the next release happens to see if it has gone away.
