### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getFlexScale' of undefined

### ISSUE THREAD

**Issue by kevinsimper** [atom/atom#8455]
1. Try to drag a vertical pane

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getFlexScale' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane-resize-handle-element.js:62

TypeError: Cannot read property 'getFlexScale' of undefined
  at atom-pane-resize-handle.PaneResizeHandleElement.setFlexGrow (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-resize-handle-element.js:62:34)
  at atom-pane-resize-handle.PaneResizeHandleElement.resizePane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-resize-handle-element.js:86:21)

```

### Commands

```
     -0:51.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:48.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  3x -0:46.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:45.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  3x -0:44.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:42.2.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  2x -0:40 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:39.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:39.5.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -0:35 core:close (atom-text-editor.editor.is-focused)
     -0:03.4.0 pane:split-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "audioBeep": false,
    "disabledPackages": [
      "php-twig"
    ]
  },
  "editor": {
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-pair, v2.0.5
color-picker, v2.0.11
editorconfig, v1.0.1
emmet, v2.3.12
highlight-selected, v0.10.1
language-babel, v0.11.8
language-docker, v1.1.3
language-jade, v0.6.2
language-twig, v1.6.2
monokai, v0.18.0
react, v0.12.6
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by kevinsimper** [comment]
Had old plugin that tried to do the same, therefore there was a conflict!
