### ISSUE TITLE
Uncaught TypeError: Cannot set property 'display' of undefined

### ISSUE THREAD

**Issue by abbshr** [atom/atom#8477]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot set property 'display' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:463

TypeError: Cannot set property 'display' of undefined
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateTilesState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:463:63)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:134:14)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:182:38)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:298:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:172:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```
### Commands

```
  3x -9:54.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:48 core:save (atom-text-editor.editor.is-focused)
  6x -0:35 core:backspace (atom-text-editor.editor.is-focused)
     -0:33.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:32.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:31.9.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false
  },
  "editor": {
    "invisibles": {},
    "scrollPastEnd": true,
    "fontFamily": "MonacoB2,Hiragino Sans GB",
    "softWrapAtPreferredLineLength": true,
    "softWrap": true,
    "fontSize": 16
  }
}
```
### Installed Packages

``` coffee
# User
language-lisp, v0.1.2
language-lua, v0.9.4
minimap, v4.13.1

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@abbshr Can you share some steps which reproduce this error for you? Does this happen in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

/cc @as-cii for more :eyes: since this was thrown from `updateTilesState`

**Comment by as-cii** [comment]
Thanks for the ping, @izuzak. :+1: And thanks @abbshr for reporting this problem. :sparkles: 

I cannot immediately think of a reason why this should be happening, but it appears like this is the first time this exception is being thrown and I wonder if this could somehow be related to Atom's issues with international documents (e.g. `fontFamily` is set to `Hiragino Sans GB`).

@abbshr: it'd be great to have some reproducible steps to make sure we can fix this error. Your help on this would be super appreciated! :bow:

**Comment by abbshr** [comment]
@as-cii 
After opening a text-file (about 3W lines). When I scroll down the code fast, this error happened.
@izuzak not in safe mode

**Comment by izuzak** [comment]
@abbshr Does that mean you can reproduce this reliably when you're not in safe mode, but can't when you are in safe mode? Also, what does "3W lines" mean?

Can you also list the packages you have installed? `apm list --installed`

**Comment by resir014** [comment]
Sorry for bumping an old thread here, but this occurred to me just recently and I might have found a way to reproduce.

[Enter steps to reproduce below:]

1. Save file while a `grunt watch` task with CSScomb is running
2. Continue working on the file. If CSScomb runs while you're editing the file, the error will occur.

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot set property 'display' of undefined

```
At C:\Users\Resi\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor-presenter.js:567

TypeError: Cannot set property 'display' of undefined
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateTilesState (C:\Users\Resi\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor-presenter.js:567:63)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (C:\Users\Resi\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor-presenter.js:119:14)
    at LinesYardstick.module.exports.LinesYardstick.prepareScreenRowsForMeasurement (C:\Users\Resi\AppData\Local\atom\app-1.3.2\resources\app.asar\src\lines-yardstick.js:26:63)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getState (C:\Users\Resi\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor-presenter.js:182:27)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (C:\Users\Resi\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor-component.js:195:38)
    at C:\Users\Resi\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor-component.js:298:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\Resi\AppData\Local\atom\app-1.3.2\resources\app.asar\src\view-registry.js:190:9)
    at C:\Users\Resi\AppData\Local\atom\app-1.3.2\resources\app.asar\src\view-registry.js:3:61
```

### Commands

```
     -1:06.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:06.6.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:06.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:06.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:06.4.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:06.4.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -1:05.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:59.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:48.6.0 core:copy (atom-text-editor.editor.is-focused)
     -0:43.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:40.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:34.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:34.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:33.8.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:33.8.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:33.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "showInvisibles": true,
    "scrollPastEnd": true,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.11.3
color-picker, v2.0.14
docblockr, v0.7.3
editorconfig, v1.2.2
emmet, v2.3.17
language-blade, v0.16.0
laravel-snippets, v2.1.0
minimap, v4.18.0
tabs-to-spaces, v1.0.1
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by santosomar** [comment]
1. It is always happening to me scrolling down fast on a file 
2. System information below

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Mac OS X 10.11.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot set property 'display' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:485

TypeError: Cannot set property 'display' of undefined
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateTilesState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:485:63)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:126:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:263:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:193:12)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:323:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:219:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:59
```

### Commands

```
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  },
  "editor": {
    "fontSize": 16
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.8.6 (active)
bottom-dock, v0.4.4 (active)
remote-sync, v4.1.2 (active)
script, v3.9.0 (inactive)
terminal-plus, v0.14.5 (active)
todo-list, v1.0.0 (active)
todo-manager, v0.2.10 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by franekp** [comment]
Came across this error while writing some addon. Steps to reproduce:
Put an <atom-text-editor /> element inside a block decoration (http://blog.atom.io/2016/02/03/introducing-block-decorations.html) in another text editor. This should work, but adding second level of nesting should cause this error to happen when trying to scroll.

**Comment by franekp** [comment]
Removing these lines
```
if Number(id) is mouseWheelTileId
        @state.content.tiles[id].display = "none"
        @lineNumberGutter.tiles[id].display = "none"
      else
```
from function TextEditorPresenter.updateTilesState seems to prevent this error when having nested adom-text-editor.
