### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, open 'C:\work\...\text-buffer.js:1020'

### ISSUE THREAD

**Issue by mibgs** [atom/atom#8499]
[Enter steps to reproduce below:]

1. Copy/paste new files over old files.
2. Try to save in Atom, get red box of depression.
3. Open and save in Visual Studio, get dialog box to save or overwrite, click overwrite.
4. Now can save in Atom.

**Atom Version**: 1.0.7
**System**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM: operation not permitted, open 'C:\work\...\dashboard.html'

```
At C:\Users\mibrahim\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1020

Error: EPERM: operation not permitted, open 'C:\work\...\dashboard.html'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.fsPlus.writeFileSync (C:\Users\mibrahim\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (C:\Users\mibrahim\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\pathwatcher\lib\file.js:273:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (C:\Users\mibrahim\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\pathwatcher\lib\file.js:371:21)
    at File.module.exports.File.writeSync (C:\Users\mibrahim\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\pathwatcher\lib\file.js:345:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\mibrahim\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1011:19)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\mibrahim\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:992:19)
```

### Commands

```
     -0:13.8.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:13.8.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:11.9.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:11.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:11.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:11.6.0 editor:indent (atom-text-editor.editor.is-focused)
  3x -0:10.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:10.2.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:10 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:10 snippets:expand (atom-text-editor.editor.is-focused)
     -0:10 editor:indent (atom-text-editor.editor.is-focused)
  6x -0:09.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:07.1.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:06.7.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:05.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.9.0 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
atom-save-all, v0.4.1
auto-indent, v0.5.0
css-color-underline, v1.0.1
save-session, v0.15.7
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
> -0:04.9.0 atom-save-all:saveAll (atom-text-editor.editor.is-focused)

I believe this is an issue with the atom-save-all package and the stack trace is too large for the call sites from that package to be visible.

You might want to report this there if you are still using that package, https://github.com/BrownBear2/atom-save-all/issues/new
