### ISSUE TITLE
Cannot find module 'lodash'

### ISSUE THREAD

**Issue by shrynx** [atom/atom#8535]
Error: Cannot find module 'lodash'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\1089379\AppData\Local\atom\app-1.0.7\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\1089379\Desktop\atom-beautify-0.28.11\src\beautify.coffee:8:5)
  at Object.<anonymous> (C:\Users\1089379\Desktop\atom-beautify-0.28.11\src\beautify.coffee:2:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\1089379\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\1089379\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:759:34)
  at Package.module.exports.Package.activateConfig (C:\Users\1089379\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:261:14)
  at Package.module.exports.Package.activateNow (C:\Users\1089379\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:239:14)
  at C:\Users\1089379\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:836:25
  at Emitter.module.exports.Emitter.emit (C:\Users\1089379\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\1089379\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (C:\Users\1089379\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\1089379\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:156:19)
  at EventEmitter.<anonymous> (C:\Users\1089379\AppData\Local\atom\app-1.0.7\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

**Comment by 50Wliu** [comment]
Hi @madmantalking, a few questions for you: how did you install Atom?  Is this the first time you're using Atom (doesn't look like it since `atom-beautify` is listed, but just wanted to make sure)?  If you run Atom in safe mode (`atom --safe`), does that fix your issue?  And finally, if that doesn't, does renaming your `C:\Users\1089379\.atom` folder to something else help?  Thanks.

**Comment by cdebotton** [comment]
I've run into this issue as well. It happened when I upgraded to Node 5.0 (and more importantly, NPM 3+). When installing nuclide through their dev setup (not apm), I believe all packages installed into a flat architecture which caused the exact errors described here. When switching to Node 4.0 and NPM 2 to install the same software, I have no issues.
