### ISSUE TITLE
Failed to activate the alignment package

### ISSUE THREAD

**Issue by xatzipe** [atom/atom#8552]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.8
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the alignment package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:16:23)
    at Package.module.exports.Package.activateNow (C:\Users\t.chatziperis.SIEBEN\AppData\Local\atom\app-1.0.8\resources\app.asar\src\package.js:243:19)
    at C:\Users\t.chatziperis.SIEBEN\AppData\Local\atom\app-1.0.8\resources\app.asar\src\package.js:224:30
    at Package.module.exports.Package.measure (C:\Users\t.chatziperis.SIEBEN\AppData\Local\atom\app-1.0.8\resources\app.asar\src\package.js:167:15)
    at Package.module.exports.Package.activate (C:\Users\t.chatziperis.SIEBEN\AppData\Local\atom\app-1.0.8\resources\app.asar\src\package.js:216:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\t.chatziperis.SIEBEN\AppData\Local\atom\app-1.0.8\resources\app.asar\src\package-manager.js:486:21)
    at C:\Users\t.chatziperis.SIEBEN\AppData\Local\atom\app-1.0.8\resources\app.asar\src\package-manager.js:469:29
    at Config.module.exports.Config.transact (C:\Users\t.chatziperis.SIEBEN\AppData\Local\atom\app-1.0.8\resources\app.asar\src\config.js:324:16)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\t.chatziperis.SIEBEN\AppData\Local\atom\app-1.0.8\resources\app.asar\src\package-manager.js:464:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\t.chatziperis.SIEBEN\AppData\Local\atom\app-1.0.8\resources\app.asar\src\package-manager.js:445:46)
```

### Commands

```
```

### Config

```json
{
  "editor": {
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
alignment, v1.0.1

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Try updating to the newest version of that package -- seems like the latest is 1.1.5, and you're using 1.0.1.

https://atom.io/packages/alignment

If that doesn't fix things, consider opening an issue on that package's issue tracker:

https://github.com/blakeembrey/atom-alignment
