### ISSUE TITLE
Atom crashes on start after update (MacOS version)

### ISSUE THREAD

**Issue by scsirdx** [atom/atom#8562]
Atom 1.0.8, throws this on start:

    A JavaScript error occured in the browser process

    Uncaught Exception:
    Error: Command failed: defaults read -g AppleLocale
    2015-08-29 00:43:09.382 defaults[36672:2486249] 
    The domain/default pair of (kCFPreferencesAnyApplication, AppleLocale) does not exist

    at checkExecSyncError (child_process.js:1334:13)
    at execFileSync (child_process.js:1354:13)
    at Function.module.exports.sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/yargs/node_modules/os-locale/index.js:87:11)
    at Argv (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/yargs/index.js:22:22)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/yargs/index.js:10:1)
    at Module._compile (module.js:452:26)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)

**Comment by mnquintana** [comment]
@kevinsawicki @bcoe This affects OS X too.

Refs https://github.com/atom/atom/issues/8559

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/atom/atom/commit/f3a90c2ad0319cbdd5fdca4671832652fbda8b80 which rolls back the version to a pre-`os-locale` usage version.

@mnquintana thanks for linking the two issues, great find :blue_heart:
