### ISSUE TITLE
Error launching atom from terminal

### ISSUE THREAD

**Issue by peduxe** [atom/atom#8579]
Launching atom from the terminal emulator throws the following error.

If I launch atom as root there's no errors, but it doesn't load my local user packages/settings.

as root:
```bash
su root
atom
```

Commands to reproduce:
```bash
atom
atom -d
atom --safe
```

```bash
/usr/bin/atom: line 91: /home/alex/.atom/nohup.out: Permission denied 
[9252:0829/203003:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Arguments to path.join must be strings
Error reading compiled file TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:449:13)
    at readCachedJavascript (/usr/share/atom/resources/app.asar/src/compile-cache.js:81:24)
    at require.install.retrieveSourceMap (/usr/share/atom/resources/app.asar/src/compile-cache.js:125:22)
    at mapSourcePosition (/usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:132:21)
    at wrapCallSite (/usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:295:20)
    at /usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:330:26
    at Array.map (native)
    at Function.prepareStackTrace (/usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:329:24)
    at process.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/main.js:29:14)
    at emitOne (events.js:82:20)
Error reading compiled file TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:449:13)
    at readCachedJavascript (/usr/share/atom/resources/app.asar/src/compile-cache.js:81:24)
    at require.install.retrieveSourceMap (/usr/share/atom/resources/app.asar/src/compile-cache.js:125:22)
    at mapSourcePosition (/usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:132:21)
    at wrapCallSite (/usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:295:20)
    at /usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:330:26
    at Array.map (native)
    at Function.prepareStackTrace (/usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:329:24)
    at process.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/main.js:29:14)
    at emitOne (events.js:82:20)
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:449:13)
    at Object.exports.setAtomHomeDirectory (/usr/share/atom/resources/app.asar/src/compile-cache.js:19:21)
    at setupCompileCache (/usr/share/atom/resources/app.asar/src/browser/main.js:116:25)
    at start (/usr/share/atom/resources/app.asar/src/browser/main.js:37:5)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/main.js:206:3)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/main.js:208:4)
    at Module._compile (module.js:452:26)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```

Linux 64-bits
Xubuntu 15.04
Atom 1.0.9

**Comment by alexeightsix** [comment]
same issue for me, my name is also alex:

Error reading compiled file TypeError: Arguments to path.join must be strings
    at f (path.js:178:13)
    at Object.filter (native)
    at Object.win32.join (path.js:183:38)
    at readCachedJavascript (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:81:24)
    at require.install.retrieveSourceMap (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:125:22)
    at mapSourcePosition (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\node_modules\source-map-support\source-map-support.js:132:21)
    at wrapCallSite (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\node_modules\source-map-support\source-map-support.js:295:20)
    at c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\node_modules\source-map-support\source-map-support.js:330:26
    at Array.map (native)
    at Function.prepareStackTrace (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\node_modules\source-map-support\source-map-support.js:329:24)
    at handleSetupError (file:///C:/Users/alex/AppData/Local/atom/app-1.0.9/resources/app.asar/static/index.js:56:24)
    at window.onload (file:///C:/Users/alex/AppData/Local/atom/app-1.0.9/resources/app.asar/static/index.js:39:7)

**Comment by kevinsawicki** [comment]
This looks related to #8433
