### ISSUE TITLE
Atom does no longer work when ran as root

### ISSUE THREAD

**Issue by RoBi89** [atom/atom#8580]
This is on arch linux 64 bit. Atom version is: 1.0.8-1 

When running atom as root with

    sudo atom

nothing happens at all. Launching atom without root works just fine.

**Comment by kevinsawicki** [comment]
If you run `sudo atom -f` do you see any error output in the terminal?

**Comment by RoBi89** [comment]
This is the output that seems to cause the issue

    [23535:0831/190756:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused

**Comment by kevinsawicki** [comment]
Did this work in previous Atom versions for you and only start happening in `1.0.8`?

**Comment by RoBi89** [comment]
I don't exactly know when it started, but yes, it definitely worked fine in previous versions.

**Comment by kevinsawicki** [comment]
> So It's pulseaudio related? 

I wouldn't think so.

Do you have Atom open already when you run `sudo atom -f`? If you completely quit Atom and then run` sudo atom -f`, do you see more output?

**Comment by RoBi89** [comment]
This is the entire output after killing atom with

    sudo killall -9 atom

[9183:0831/191549:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Arguments to path.join must be strings
Error reading compiled file TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:449:13)
    at readCachedJavascript (/usr/share/atom/resources/app.asar/src/compile-cache.js:81:24)
    at require.install.retrieveSourceMap (/usr/share/atom/resources/app.asar/src/compile-cache.js:125:22)
    at mapSourcePosition (/usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:132:21)
    at wrapCallSite (/usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:295:20)
    at /usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:330:26
    at Array.map (native)
    at Function.prepareStackTrace (/usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:329:24)
    at process.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/main.js:29:14)
    at emitOne (events.js:82:20)
Error reading compiled file TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:449:13)
    at readCachedJavascript (/usr/share/atom/resources/app.asar/src/compile-cache.js:81:24)
    at require.install.retrieveSourceMap (/usr/share/atom/resources/app.asar/src/compile-cache.js:125:22)
    at mapSourcePosition (/usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:132:21)
    at wrapCallSite (/usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:295:20)
    at /usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:330:26
    at Array.map (native)
    at Function.prepareStackTrace (/usr/share/atom/resources/app.asar/node_modules/source-map-support/source-map-support.js:329:24)
    at process.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/main.js:29:14)
    at emitOne (events.js:82:20)
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:449:13)
    at Object.exports.setAtomHomeDirectory (/usr/share/atom/resources/app.asar/src/compile-cache.js:19:21)
    at setupCompileCache (/usr/share/atom/resources/app.asar/src/browser/main.js:116:25)
    at start (/usr/share/atom/resources/app.asar/src/browser/main.js:37:5)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/main.js:206:3)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/main.js:208:4)
    at Module._compile (module.js:452:26)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
[9183:0831/191549:ERROR:browser_main_loop.cc(198)] GTK theme error: Unable to locate theme engine in module_path: "adwaita",
[9183:0831/191549:ERROR:browser_main_loop.cc(198)] GTK theme error: Unable to locate theme engine in module_path: "equinox",
[9183:0831/191549:ERROR:browser_main_loop.cc(198)] GTK theme error: Unable to locate theme engine in module_path: "equinox",
<memory>:1: Invalid color constant '@selected_bg_color'
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `ChromeGtkFrame::scrollbar-slider-prelight-color' of type `GdkColor' from rc file value ""@selected_bg_color"" of type `gchararray'
[9183:0831/191550:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused

**Comment by kevinsawicki** [comment]
@RoBi89 thanks for that output, it looks very similar to #8579 so I'm going to close this out here, please subscribe to that issue for updates.

**Comment by peduxe** [comment]
@kevinsawicki 

This does indeed work,

```sh
atom -f
```
but atom launches only with the following error:
```sh
[4116:0831/204028:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.

```

**Comment by RoBi89** [comment]
It's fixed in the latest 1.0.11-1 build.

**Comment by peduxe** [comment]
@RoBi89 not yet for me

**Comment by maxbrunsfeld** [comment]
@peduxe I don't think that error is fatal. So on 1.0.11, no window opens when you run Atom as root?

**Comment by peduxe** [comment]
Oh my apologies, I mixed up the issues, this one is relative to running as sudo and this works for me now.

It does not run when I don't run as super user, this is the output/error:

```sh
/usr/bin/atom: line 91: /home/alex/.atom/nohup.out: Permission denied         
[9670:0903/172016:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App load time: 1249ms
[9706:0903/172018:INFO:renderer_main.cc(212)] Renderer process started
// package activation logs (..)
[9670:0903/172102:ERROR:channel.cc(305)] RawChannel read error (connection broken)
```

This flag does allow me to run without sudo, also, there are no errors:
```sh
atom -f
```
