### ISSUE TITLE
Error Opening Atom

### ISSUE THREAD

**Issue by michaelmena** [atom/atom#8593]
Hi

I'm receiving the following error when trying to open Atom:

2015-08-30 13:25:57> Program: Starting Squirrel Updater: --install .
> 2015-08-30 13:25:57> Program: Starting install, writing to C:\Users\laptop\AppData\Local\SquirrelTemp
> 2015-08-30 13:25:57> Program: About to install to: C:\Users\laptop\AppData\Local\atom
> 2015-08-30 13:25:58> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\laptop\AppData\Local\atom\packages\RELEASES'.
> at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
> at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
> at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
> at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
> at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3a.MoveNext()
> 2015-08-30 13:25:58> CheckForUpdateImpl: Reading RELEASES file from C:\Users\laptop\AppData\Local\SquirrelTemp
> 2015-08-30 13:25:58> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
> 2015-08-30 13:25:59> ApplyReleasesImpl: Writing files to app directory: C:\Users\laptop\AppData\Local\atom\app-1.0.9
> 2015-08-30 13:26:26> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\laptop\AppData\Local\atom\app-1.0.9\atom.exe]
> 2015-08-30 13:26:30> ApplyReleasesImpl: Starting fixPinnedExecutables
> 2015-08-30 13:26:30> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
> 2015-08-30 13:26:30> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.9
> 2015-08-30 13:26:30> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.9

**Comment by kevinsawicki** [comment]
Are you running Atom from the command line? Does it happen if you run Atom directly from the start menu or the desktop?

**Comment by michaelmena** [comment]
I'm not running it from the command line. I'm running it from start menu.

**Comment by kevinsawicki** [comment]
> I'm not running it from the command line. I'm running it from start menu.

And where is this error displaying? Could you provide a screenshot?

**Comment by michaelmena** [comment]
I uninstalled the program from my PC, and I'm trying to reinstall. When I
click on the AtomSetup exe file, I get the following:

[image: Inline image 3]

[image: Inline image 4]

This is the log:

2015-08-30 13:25:57> Program: Starting Squirrel Updater: --install .
2015-08-30 13:25:57> Program: Starting install, writing to
C:\Users\laptop\AppData\Local\SquirrelTemp
2015-08-30 13:25:57> Program: About to install to:
C:\Users\laptop\AppData\Local\atom
2015-08-30 13:25:58> CheckForUpdateImpl: Failed to load local releases,
starting from scratch: System.IO.DirectoryNotFoundException: Could not find
a part of the path 'C:\Users\laptop\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess
access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize,
FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean
bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess
access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at
Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3a.MoveNext()
2015-08-30 13:25:58> CheckForUpdateImpl: Reading RELEASES file from
C:\Users\laptop\AppData\Local\SquirrelTemp
2015-08-30 13:25:58> CheckForUpdateImpl: First run or local directory is
corrupt, starting from scratch
2015-08-30 13:25:59> ApplyReleasesImpl: Writing files to app directory:
C:\Users\laptop\AppData\Local\atom\app-1.0.9
2015-08-30 13:26:26> ApplyReleasesImpl: Squirrel Enabled Apps:
[C:\Users\laptop\AppData\Local\atom\app-1.0.9\atom.exe]
2015-08-30 13:26:30> ApplyReleasesImpl: Starting fixPinnedExecutables
2015-08-30 13:26:30> ApplyReleasesImpl: fixPinnedExecutables:
oldAppDirectories is empty, this is pointless
2015-08-30 13:26:30> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.9
2015-08-30 13:26:30> ApplyReleasesImpl: cleanDeadVersions: exclude folder
app-1.0.9

**Comment by kevinsawicki** [comment]
> I uninstalled the program from my PC, and I'm trying to reinstall. When I
click on the AtomSetup exe file, I get the following

Image attachments sent via email don't render in the issue. Would you mind uploading them directly from the https://github.com/atom/atom/issues/8593 page?

**Comment by michaelmena** [comment]
![capture](https://cloud.githubusercontent.com/assets/2381865/9585709/898efa5c-4fe6-11e5-8590-1a6f59da26be.PNG)
![capture2](https://cloud.githubusercontent.com/assets/2381865/9585711/8e068154-4fe6-11e5-9ee6-7ad4cff608be.PNG)

The log file:

2015-08-30 13:25:57> Program: Starting Squirrel Updater: --install .
2015-08-30 13:25:57> Program: Starting install, writing to C:\Users\laptop\AppData\Local\SquirrelTemp
2015-08-30 13:25:57> Program: About to install to: C:\Users\laptop\AppData\Local\atom
2015-08-30 13:25:58> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\laptop\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3a.MoveNext()
2015-08-30 13:25:58> CheckForUpdateImpl: Reading RELEASES file from C:\Users\laptop\AppData\Local\SquirrelTemp
2015-08-30 13:25:58> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2015-08-30 13:25:59> ApplyReleasesImpl: Writing files to app directory: C:\Users\laptop\AppData\Local\atom\app-1.0.9
2015-08-30 13:26:26> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\laptop\AppData\Local\atom\app-1.0.9\atom.exe]
2015-08-30 13:26:30> ApplyReleasesImpl: Starting fixPinnedExecutables
2015-08-30 13:26:30> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
2015-08-30 13:26:30> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.9
2015-08-30 13:26:30> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.9

**Comment by michaelmena** [comment]
I attached it to issue #8593.

Thanks for helping out!

**Comment by kevinsawicki** [comment]
So you see that error when launching the Atom installer or the Atom application itself?

**Comment by michaelmena** [comment]
Yes

**Comment by michaelmena** [comment]
Atom installer

**Comment by kevinsawicki** [comment]
Can you try deleting `C:\Users\laptop\AppData\Local\atom` and `C:\Users\laptop\AppData\Local\SquirrelTemp` and re-running the installer?

**Comment by michaelmena** [comment]
I removed both folders as indicated and tried to re-install and I'm still
receiving an error:

The application was unable to start correctly (0xc000007b)

**Comment by damieng** [comment]
Hi micahelmena are you still having this issue?

**Comment by michaelmena** [comment]
Hi

I have not used Atom in a while.

I started using Brackets by adobe

Sorry
Mike

**Comment by damieng** [comment]
Closing as we don't have a repro.
