### ISSUE TITLE
Failed to activate the enhanced-package-list package

### ISSUE THREAD

**Issue by jbw91** [atom/atom#8607]
[Enter steps to reproduce below:]

1. Make sure enhanced-package-list is installed.
2. Open Atom.

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the enhanced-package-list package

```
At undefined is not a function

TypeError: undefined is not a function
    at Object.module.exports.activate (<anonymous>:35:18)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:469:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:324:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:464:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:46)
    at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:670:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:166:19)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-jscs",
      "atom-typescript"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "showInvisibles": true,
    "tabLength": 4,
    "softWrap": true,
    "softTabs": false,
    "invisibles": {},
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
autoclose-html, v0.18.0
autocomplete-paths, v1.0.2
editorconfig, v1.1.1
enhanced-package-list, v1.0.3
file-icons, v1.6.9
language-docker, v1.1.3
linter, v1.4.3
linter-jshint, v1.1.5
minimap, v4.13.2
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0
monokai, v0.18.0
pigments, v0.13.0
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Closing in favor of postcasio/enhanced-package-list#8, please subscribe there for updates.
