### ISSUE TITLE
Uncaught Error: write EBADF

### ISSUE THREAD

**Issue by ghost** [atom/atom#8626]
[Enter steps to reproduce below:]

1: Start atom from terminal with command:

``` sh
atom -f
```

2: Reload editor

**Atom Version**: 1.0.9
**System**: Ubuntu 15.04
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: write EBADF

```
At events.js:141

Error: write EBADF
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at WriteWrap.afterWrite (net.js:753:14)
    at EventEmitter.ipc.sendSync (/opt/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as getPosition] (/opt/atom/resources/atom.asar/renderer/api/lib/remote.js:110:29)
    at Atom.module.exports.Atom.getWindowDimensions (/opt/atom/resources/app.asar/src/atom.js:555:29)
    at Atom.module.exports.Atom.storeDefaultWindowDimensions (/opt/atom/resources/app.asar/src/atom.js:588:25)
    at /opt/atom/resources/app.asar/src/window-event-handler.js:104:21
    at handler (/opt/atom/resources/app.asar/src/space-pen-extensions.js:115:32)
    at jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
    at elemData.handle (/opt/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "bookmarks",
      "background-tips",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-hyperlink",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-property-list",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-source",
      "language-sql",
      "language-toml",
      "language-xml",
      "language-yaml",
      "metrics",
      "spell-check",
      "styleguide",
      "linter-jshint",
      "atom-beautify",
      "atom-typescript"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-dark-ui",
      "atom-material-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "preferredLineLength": 120,
    "backUpBeforeSaving": true,
    "softWrap": true,
    "lineHeight": 1.7,
    "fontFamily": "Consolas"
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
atom-material-syntax, v0.2.3
autoclose-html, v0.18.0
autocomplete-modules, v1.1.0
autocomplete-paths, v1.0.2
color-picker, v2.0.11
emmet, v2.3.12
file-icons, v1.6.9
highlight-selected, v0.10.1
indent-guide-improved, v1.4.2
language-babel, v0.13.0
language-hack, v0.1.1
language-ini, v1.12.0
language-ts, v1.0.0
linter, v1.5.0
linter-csslint, v1.0.5
linter-eslint, v3.0.2
linter-htmlhint, v0.1.1
linter-jsonlint, v0.1.4
open-recent, v2.3.0

# Dev
No dev packages
```

**Comment by N4M3Z** [comment]
I am seeing the same issue. From the packages listed by @50Wliu I am currently running:
```
autoclose-html, v0.18.0
color-picker, v2.0.11
emmet, v2.3.12
file-icons, v1.6.9
highlight-selected, v0.10.1
linter, v1.5.0
linter-csslint, v1.0.5
linter-eslint, v3.0.2
linter-htmlhint, v0.1.1
linter-jsonlint, v0.1.4
```

**Comment by 50Wliu** [comment]
@N4M3Z I think you meant @peduxe :wink:

**Comment by N4M3Z** [comment]
Yes, indeed :-D
