### ISSUE TITLE
Failed to activate the terminal package

### ISSUE THREAD

**Issue by pasi1** [atom/atom#8628]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Ubuntu 14.04.3
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the terminal package

```
At undefined is not a function

TypeError: undefined is not a function
    at Object.module.exports.activate (<anonymous>:13:18)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:243:19)
    at /opt/atom/resources/app.asar/src/package.js:224:30
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:216:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:486:21)
    at /opt/atom/resources/app.asar/src/package-manager.js:469:29
    at Config.module.exports.Config.transact (/opt/atom/resources/app.asar/src/config.js:324:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/atom/resources/app.asar/src/package-manager.js:464:19)
    at PackageManager.module.exports.PackageManager.activate (/opt/atom/resources/app.asar/src/package-manager.js:445:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "quantum-shell"
    ]
  },
  "editor": {
    "fontSize": 16,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
I'm not sure how you partially installed this, but the [terminal package is not maintained or supported anymore](https://github.com/atom-archive/terminal), and hasn't been updated in well over a year.
