### ISSUE TITLE
Failed to activate the select-line package

### ISSUE THREAD

**Issue by juanchoVanegas** [atom/atom#8629]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Mac OS X 10.8.5
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the select-line package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:3:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:836:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:226:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
```

### Commands

```
     -0:01.3.0 click (a.btn-issue.btn.btn-error)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, vundefined
auto-update-packages, v1.0.0
docblockr, v0.7.3
emmet, v2.3.12
jsdoc-generator, v0.1.10
jshint, vundefined
language-twig, v1.6.2
project-manager, v2.2.0
search, v0.5.0
select-line, v0.16.0
terminal-status, v1.6.8

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hey @juanchoVanegas, the `select-line` package seems to have been deleted from atom.io, which means that the author isn't supporting it anymore.  Therefore, you'll probably want to uninstall it and look for an alternative package.
