### ISSUE TITLE
Failed to load the SFTP-deployment package

### ISSUE THREAD

**Issue by njaen** [atom/atom#8639]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.10
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to load the SFTP-deployment package

```
At Syntax error on line 10, column 2: One top level value expected

SyntaxError: Syntax error on line 10, column 2: One top level value expected
  at nodeTransforms.Block (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/lib/parse.js:74:15)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at Object.parse (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/lib/parse.js:203:12)
  at parseObject (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:42:23)
  at parseContentsSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:68:16)
  at Object.module.exports.readFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:170:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:447:45
  at Array.map (native)
  at Package.module.exports.Package.loadKeymaps (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:445:46)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:185:19
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:369:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:667:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:82:25)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
space-tab, v0.4.2
tabulation-control, v1.0.6

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This issue was moved to amoussard/sftp-deployment#77
