### ISSUE TITLE
Failed to activate the status-bar package

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#8673]
### Steps to Reproduce

1. Launched Atom from the command line with `atom .`

**Atom Version**: 1.0.12-21c411b
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the status-bar package

```
At Illegal invocation

TypeError: Illegal invocation
    at /Users/Lee/Source/atom/src/package.coffee:512:32
    at Emitter.module.exports.Emitter.emit (/Users/Lee/Source/atom/node_modules/event-kit/lib/emitter.js:82:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/Lee/Source/atom/src/command-registry.coffee:232:14)
    at CommandRegistry.handleCommandEvent (/Users/Lee/Source/atom/src/command-registry.coffee:1:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/Lee/Source/atom/src/command-registry.coffee:183:6)
    at [object Object].jQuery.fn.trigger (/Users/Lee/Source/atom/src/space-pen-extensions.coffee:34:21)
    at complete (/Users/Lee/Source/atom/node_modules/bootstrap/js/tooltip.js:322:10)
    at [object Object].Tooltip.hide (/Users/Lee/Source/atom/node_modules/bootstrap/js/tooltip.js:336:7)
    at [object Object].Tooltip.leave (/Users/Lee/Source/atom/node_modules/bootstrap/js/tooltip.js:166:70)
    at Disposable.disposalAction (/Users/Lee/Source/atom/src/tooltip-manager.coffee:92:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "projectHome": "/Users/Lee/Source",
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      ".keep",
      "._*",
      "*.pyc",
      "Thumbs.db"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "editor": {
    "preferredLineLength": 100,
    "scrollPastEnd": true,
    "invisibles": {
      "eol": " ",
      "tab": "⇥",
      "cr": "↩"
    },
    "showInvisibles": true,
    "fontFamily": "Source Code Pro",
    "backUpBeforeSaving": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-elixir, v1.3.12
autocomplete-emojis, v2.2.2
block-travel, v1.0.2
bug-report, v0.7.1
file-type-icons, v0.7.3
indentation-indicator, v0.6.0
language-asciidoc, v0.12.0
language-elixir, v0.5.2
language-generic-config, v0.2.0
language-haml, v0.21.0
language-todotxt, v0.6.1
minimap, v4.13.2
pigments, v0.13.2
red-wavy-underline, v0.3.0
regex-railroad-diagram, v0.8.4
set-syntax, v0.3.0
soft-wrap-indicator, v0.7.0
tabs-to-spaces, v0.11.1
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
Still an issue lee?

**Comment by lee-dohm** [comment]
No, it hasn't reproduced lately.

**Comment by benogle** [comment]
Ok. Obv reopen if you see it again.
