### ISSUE TITLE
Failed to load the go-format package

### ISSUE THREAD

**Issue by JonnyWalker81** [atom/atom#8674]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Failed to load the go-format package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "useReactEditor": true,
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "showInvisibles": true,
    "showIndentGuide": true,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-erlang, v1.1.1
go-format, v1.0.7
go-plus, v2.0.10
iex, v0.9.13
jsonlint, v1.1.2
language-elixir, v0.5.2
language-erlang, v3.0.0
language-kotlin, v0.3.0
linter-erlang, v0.2.0
linter-erlc, v0.3.0
linter-jsonlint, v0.1.4
linter-package-json-validator, v0.1.0
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
I think this is a bug in the package. It looks like this package has been deprecated in favor of [go-plus](https://atom.io/packages/go-plus). Could you try removing `go-format` and installing `go-plus`?
