### ISSUE TITLE
Failed to activate custom 'one-dark-ui' package

### ISSUE THREAD

**Issue by rasiquiz** [atom/atom#8683]
[Enter steps to reproduce below:]
1. Follow guide on how to make custom theme
2. Run Atom

**Atom Version**: 1.0.11
**System**: Mac OS X 10.9.4
**Thrown From**: Atom Core
### Stack Trace

Failed to activate the rm-dark-ui package

```
At Cannot read property 'toLowerCase' of undefined

TypeError: Cannot read property 'toLowerCase' of undefined
    at setLayoutMode (/Users/rasmus/Documents/Github/one-dark-ui/lib/main.coffee:56:63)
    at Object.module.exports.activate (/Users/rasmus/Documents/Github/one-dark-ui/lib/main.coffee:36:5)
    at ThemePackage.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:48:26
    at ThemePackage.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
    at ThemePackage.module.exports.ThemePackage.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:43:12)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:361:50
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:568:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "rm-dark-ui",
      "rm-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "showIndentGuide": true,
    "fontSize": 15
  }
}
```
### Installed Packages

``` coffee
# User
pigments, v0.13.2
rm-dark-syntax, v0.1.0
rm-dark-ui, v0.1.0

# Dev
No dev packages
```

**Comment by peduxe** [comment]
You probably didn't add the configuration schema for your package.

[Aren't you missing this?](https://github.com/atom/one-dark-ui/blob/master/lib/main.coffee#L16-L32)
