### ISSUE TITLE
Atom 1.0.5 and up fail to start

### ISSUE THREAD

**Issue by domenkozar** [atom/atom#8691]
I'm trying to upgrade Atom package in NixOS and we're using `.deb` as a base.

All Atom versions from 1.0.5 and up fail to start with following message http://i.imgur.com/2X6Xyof.png

```
[6826:0906/195612:INFO:CONSOLE(56)] "Error: Module did not self-register.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:129:18)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/nix/store/lyxrsbadnnxb5w50gdz26akc6lbrq2ra-atom-1.0.11/share/atom/resources/app.asar/node_modules/atom-keymap/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/nix/store/lyxrsbadnnxb5w50gdz26akc6lbrq2ra-atom-1.0.11/share/atom/resources/app.asar/node_modules/atom-keymap/node_modules/pathwatcher/lib/main.js:207:4)
    at Module._compile (module.js:452:26)", source: file:///nix/store/lyxrsbadnnxb5w50gdz26akc6lbrq2ra-atom-1.0.11/share/atom/resources/app.asar/static/index.js (56)
[6826:0906/195612:INFO:CONSOLE(64)] "Uncaught TypeError: Cannot read property 'dispatch' of null", source: /nix/store/lyxrsbadnnxb5w50gdz26akc6lbrq2ra-atom-1.0.11/share/atom/resources/app.asar/src/space-pen-extensions.js (64)
```

Upstream bug report: https://github.com/NixOS/nixpkgs/pull/9605

For some users it works, for others it doesn't and we're trying to figure out what could be going on.

**Comment by nathansobo** [comment]
Hey @domenkozar. When we see those errors, it usually means there's a native node module that's compiled against the wrong headers (Node rather than Electron). This can happen when a module is compiled with `npm install` or `npm rebuild` rather than `apm install` or `apm rebuild`. The `apm` commands run the equivalent npm commands, but link to the Atom-specific headers.

**Comment by domenkozar** [comment]
So Nix package manager makes sure the dependency tree is always the same. We have a few users reporting everything is fine, while others get the above error. All with **the same** dependencies and build process.

See dependency tree: https://gist.github.com/anonymous/a67e188e55a477c28faf

What I don't understand how could sometimes npm be used and sometimes apm? Would removing npm binary help?

**Comment by domenkozar** [comment]
I tried removing `npm` binary in atom package, it still didn't help. Could it be that `apm` command is broken?

**Comment by nathansobo** [comment]
Are people getting build errors trying to build that native module by chance? On second look it doesn't seem like a versioning issue, but just a general problem loading the shared library.

**Comment by domenkozar** [comment]
I just installed Atom, ran it and got the error. How do I see if there is an error building the native module? Can I run that outside Atom?

**Comment by domenkozar** [comment]
@mnquintana what more information do you need?

**Comment by nathansobo** [comment]
There's clearly something wrong with how Atom is being built by that package.

@kevinsawicki Any insight on the Debian package? I have zero context on it.

**Comment by kevinsawicki** [comment]
@domenkozar where did you download the `.deb` file from?

**Comment by domenkozar** [comment]
`https://github.com/atom/atom/releases/download/v${version}/atom-amd64.deb`

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/atom/default.nix, we change the interpreter (shouldn't matter) and then create an environment with libraries that sets `LD_LIBRARY_PATH` with specified packages

**Comment by domenkozar** [comment]
@kevinsawicki any ideas?

**Comment by kevinsawicki** [comment]
> any ideas?

Not immediately, `Module did not self register` usually indicates native modules are being used in Atom that were compiled against a different v8 version than the version shipping with Atom.

**Comment by domenkozar** [comment]
Is there a way to debug this? How do I find this native module to check if it works in standalone way?

**Comment by kevinsawicki** [comment]
> How do I find this native module to check if it works in standalone way?

All the native modules should be under `/nix/store/lyxrsbadnnxb5w50gdz26akc6lbrq2ra-atom-1.0.11/share/atom/resources/app.asar/node_modules`

**Comment by domenkozar** [comment]
There is only `/nix/store/s5xwlnxlzxfb5zllbzmrnybmp72iw1gz-atom-1.0.11/share/atom/resources/app.asar.unpacked/node_modules/pathwatcher/build/Release/pathwatcher.node`

**Comment by domenkozar** [comment]
Here is how to install Atom, you can reproduce on any Linux distro (works also on OSX, but that's a bit more complicated to install):

```
$ curl https://nixos.org/nix/install | sh
$ git clone https://github.com/NixOS/nixpkgs.git
$ cd nixpkgs
$ git checkout atom_1_0_11
$ nix-build -A atom
$ /nix/store/s5xwlnxlzxfb5zllbzmrnybmp72iw1gz-atom-1.0.11/bin/atom
```

**Comment by domenkozar** [comment]
Just for reference, same error on 1.0.19:

```
$ /nix/store/d0wsfsxjixzcx82sqjcgvm194xd72y55-atom-1.0.19/bin/atom -f
[6016:1028/121132:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[6016:1028/121132:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6016:1028/121132:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6016:1028/121132:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6016:1028/121132:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6042:1028/121132:INFO:renderer_main.cc(200)] Renderer process started
App load time: 377ms
[6059:1028/121133:INFO:renderer_main.cc(200)] Renderer process started
[6016:1028/121133:INFO:CONSOLE(56)] "Error: Module did not self-register.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:148:18)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/nix/store/d0wsfsxjixzcx82sqjcgvm194xd72y55-atom-1.0.19/share/atom/resources/app.asar/node_modules/atom-keymap/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/nix/store/d0wsfsxjixzcx82sqjcgvm194xd72y55-atom-1.0.19/share/atom/resources/app.asar/node_modules/atom-keymap/node_modules/pathwatcher/lib/main.js:207:4)
    at Module._compile (module.js:428:26)", source: file:///nix/store/d0wsfsxjixzcx82sqjcgvm194xd72y55-atom-1.0.19/share/atom/resources/app.asar/static/index.js (56)
[6016:1028/121133:INFO:CONSOLE(64)] "Uncaught TypeError: Cannot read property 'dispatch' of null", source: /nix/store/d0wsfsxjixzcx82sqjcgvm194xd72y55-atom-1.0.19/share/atom/resources/app.asar/src/space-pen-extensions.js (64)
```

**Comment by domenkozar** [comment]
Which hints that following line fails https://github.com/atom/atom/blob/5f4f6d2d175f1877a71c3fcc9657ee1ba14f884b/src/space-pen-extensions.coffee#L34

**Comment by domenkozar** [comment]
Looks very similar to https://github.com/atom/atom/issues/5639

**Comment by domenkozar** [comment]
I've also tried with a rpm, same result. I'm out of ideas here.

**Comment by domenkozar** [comment]
Atom 1.1.0 now starts up successfully.
