### ISSUE TITLE
Failed to load the php-checkstyle package

### ISSUE THREAD

**Issue by dadeg** [atom/atom#8714]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core
### Stack Trace

Failed to load the php-checkstyle package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:8:3
    at Object.<anonymous> (<anonymous>:8:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "fontFamily": "Menlo",
    "fontSize": 14
  }
}
```
### Installed Packages

``` coffee
# User
language-gherkin, v0.3.0
php-checkstyle, v0.15.0
seti-syntax, v0.1.7
seti-ui, v0.3.6

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
Sorry about this! After looking into this, it looks like this package is no longer published on apm, although we probably shouldn't be blowing up if that happens.

What were you doing when this error was thrown?

**Comment by dadeg** [comment]
This happens every time I start Atom. I guess I will just get rid of the
package for now, I don't even remember what I was using it for in the past.
Thanks.
