### ISSUE TITLE
Failed to activate the smart-tag-cycle package

### ISSUE THREAD

**Issue by cbstodd** [atom/atom#8733]
[Enter steps to reproduce below:]

1. Upgrade and restart Atom
2. Bam, error message arrived in my face.

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the smart-tag-cycle package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.registerCommandsForPattern (<anonymous>:17:23)
    at Object.module.exports.activate (<anonymous>:12:6)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:469:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:324:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:464:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "atom-html-preview",
      "livereload",
      "merge-conflicts",
      "rails-rspec",
      "script",
      "erb-helper"
    ],
    "themes": [
      "neutron-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 12,
    "fontFamily": "menlo",
    "showIndentGuide": true,
    "softWrap": true,
    "invisibles": {},
    "preferredLineLength": 100,
    "scrollPastEnd": true
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
atom-handlebars, v1.2.0
autoclose-html, v0.19.0
browser-plus, v0.0.34
color-picker, v2.0.11
ember-cli-helper, v0.9.0
ember-snippets, v1.4.0
file-icons, v1.6.9
language-ember-htmlbars, v0.3.0
language-ember-script, v0.2.0
language-emberscript, v0.1.0
linter, v1.5.1
minimap, v4.13.3
neutron-ui, v0.4.0
remember-session, v0.5.1
smart-tag-cycle, v0.2.0
travis-ci-status, v0.18.0
vim-mode, v0.60.0
word-jumper, v0.3.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This seems to already have been reported over at abe33/atom-smart-tag-cycle#1, so I'm going to close this out.  @cbstodd, you can follow there for updates.
