### ISSUE TITLE
Uncaught Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by burhandodhy** [atom/atom#8736]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: Cannot find module 'semver'

```
At module.js:330

Error: Cannot find module 'semver'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\BuRhan\AppData\Local\atom\app-1.0.11\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (<anonymous>:3:10)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\BuRhan\AppData\Local\atom\app-1.0.11\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-terminal-panel"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 17,
    "softWrap": true
  }
}
```
### Installed Packages

``` coffee
# User
aligner-php, v1.0.0
atom-alignment, v0.12.1
atom-wordpress, v0.3.0
autoclose-html, v0.18.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
emmet, v2.3.12
file-icons, v1.6.9
highlight-line, v0.11.0
javascript-snippets, v1.0.0
jquery-snippets, v11.0.0
linter, v1.5.0
linter-golinter, v1.0.0
linter-htmlhint, v0.1.1
linter-jshint, v1.1.5
linter-php, v1.0.3
linter-phpcs, v1.0.7
minimap, v4.13.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
php-cs-fixer, v2.4.0
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hey @burhandodhy, can you please share what you were doing when this error occured?  Thanks.

**Comment by burhandodhy** [comment]
each and every time when i save my file

**Comment by 50Wliu** [comment]
Ok, then can you try reproducing this in safe mode (`atom --safe`)?  Thanks.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/8736#issuecomment-139415628. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
