### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\Flamez-III\Downloads\testfail.php'

### ISSUE THREAD

**Issue by spanishtech** [atom/atom#8738]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\Flamez-III\Downloads\testfail.php'

```
At C:\Users\Flamez-III\AppData\Local\atom\app-1.0.11\resources\app.asar\src\pane.js:809

Error: ENOENT: no such file or directory, stat 'C:\Users\Flamez-III\Downloads\testfail.php'
    at Error (native)
    at fs.statSync (fs.js:846:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
    at new PathWatcher (C:\Users\Flamez-III\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\pathwatcher\lib\main.js:105:20)
    at Object.exports.watch (C:\Users\Flamez-III\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\pathwatcher\lib\main.js:179:12)
    at File.module.exports.File.subscribeToNativeChangeEvents (C:\Users\Flamez-III\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\pathwatcher\lib\file.js:476:109)
    at File.module.exports.File.writeSync (C:\Users\Flamez-III\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\pathwatcher\lib\file.js:348:14)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Flamez-III\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1024:19)
    at TextEditor.module.exports.TextEditor.saveAs (C:\Users\Flamez-III\AppData\Local\atom\app-1.0.11\resources\app.asar\src\text-editor.js:590:26)
    at Pane.module.exports.Pane.saveItemAs (C:\Users\Flamez-III\AppData\Local\atom\app-1.0.11\resources\app.asar\src\pane.js:571:16)
```
### Commands

```
     -0:17.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:15.3.0 core:close (atom-text-editor.editor.is-focused)
     -0:13.5.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:12.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:12.1.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "tabLength": 4
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hey @spanishtech, what were you doing when this exception occurred?  If it's specific to `C:\Users\Flamez-III\Downloads\testfail.php`, can you please upload that as a Gist and paste the link here?  Thanks.

**Comment by spanishtech** [comment]
Can't save any file anywhere.
