### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/d12frosted/.atom/packages/org/lib...

### ISSUE THREAD

**Issue by d12frosted** [atom/atom#8739]
Steps to reproduce:

1. `advanced-open-file`
2. navigate to `.org` file
3. open it
4. error

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/d12frosted/.atom/packages/org/lib/org-input.coffee'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:1036

Error: ENOENT: no such file or directory, open '/Users/d12frosted/.atom/packages/org/lib/org-input.coffee'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:396:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at Object.exports._compileFile (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:221:14)
  at getSourceMap (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:329:22)
  at getSourceMapping (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:337:19)
  at formatSourcePosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:289:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:355:34
  at Function.Error.prepareStackTrace (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:358:7)
  at Package.module.exports.Package.handleError (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:1036:31)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:250:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:836:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:226:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:31.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:31.6.0 advanced-open-file:autocomplete (atom-text-editor.editor.mini.is-focused)
     -0:30.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:25.4.0 core:close (atom-text-editor.editor.is-focused)
     -0:15.8.0 advanced-open-file:toggle (div.settings-view.pane-item)
     -0:13.3.0 advanced-open-file:autocomplete (atom-text-editor.editor.mini.is-focused)
  4x -0:12.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:11.5.0 advanced-open-file:autocomplete (atom-text-editor.editor.mini.is-focused)
  3x -0:08.6.0 advanced-open-file:move-cursor-down (atom-text-editor.editor.mini.is-focused)
  4x -0:08.2.0 advanced-open-file:autocomplete (atom-text-editor.editor.mini.is-focused)
  3x -0:06.2.0 advanced-open-file:move-cursor-down (atom-text-editor.editor.mini.is-focused)
     -0:05.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:04.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:03.5.0 advanced-open-file:toggle (atom-text-editor.editor.is-focused)
     -0:02.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:02.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "*.png",
      "*.meta"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabType": "hard",
    "fontSize": 12,
    "showInvisibles": true,
    "showIndentGuide": true,
    "preferredLineLength": 120
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.9.2
atom-yeoman, v0.3.13
json-schema, v0.1.13
language-fish-shell, v1.0.2
linter, v1.5.1
omnisharp-atom, v0.24.6

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@d12frosted can you please move this issue to https://github.com/Trudko/advanced-new-file?  Thanks.

**Comment by d12frosted** [comment]
Sorry, didn't receive notification about update. Reported to the right repo!
