### ISSUE TITLE
Failed to load the break package

### ISSUE THREAD

**Issue by Tjoosten** [atom/atom#8759]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core

### Stack Trace

Failed to load the break package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (/Users/tim/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "api-blueprint-preview"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "destroyEmptyPanes": false
  },
  "editor": {
    "fontSize": 10,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
Sasquatch, v0.2.0
atom-html-preview, v0.1.8
atom-jade, v0.3.0
bootstrap-3-snippetset, v0.0.6
break, v0.3.1
color-picker, v2.0.7
git-log, v0.4.1
http-status-codes, v1.0.4
irc, v0.4.0
language-ejs, v0.1.0
language-sql-mysql, v0.3.1
linter, v1.0.6
linter-cpplint, v0.1.4
linter-less, v2.1.0
my-github-profile, v0.2.0
php-getters-setters, v0.5.5
phpunit, v1.1.1
remote-edit, v1.8.2
sass-watch, v0.3.1
terminal-status, v1.6.7

# Dev
No dev packages
```

**Comment by benogle** [comment]
This might be an issue in the `break` package. Is it published or is it your package?

**Comment by Tjoosten** [comment]
Published
