### ISSUE TITLE
Build failure with NodeJS 4.0.0

### ISSUE THREAD

**Issue by tutukin** [atom/atom#8763]
Debian 8.2, i386
NodeJS 4.0.0
Atom v1.0.11

Build fails. The relevant part of npm-debug.log:

```
76598 verbose stack Error: runas@2.0.0 install: `node-gyp rebuild`
76598 verbose stack Exit status 1
76598 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
76598 verbose stack     at emitTwo (events.js:87:13)
76598 verbose stack     at EventEmitter.emit (events.js:172:7)
76598 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
76598 verbose stack     at emitTwo (events.js:87:13)
76598 verbose stack     at ChildProcess.emit (events.js:172:7)
76598 verbose stack     at maybeClose (internal/child_process.js:817:16)
76598 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
76599 verbose pkgid runas@2.0.0
76600 verbose cwd /home/tut/Загрузки/atom/build
76601 error Linux 3.16.0-4-686-pae
76602 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "--userconfig=/home/tut/Загрузки/atom/build/.npmrc" "install" "--loglevel" "error"
76603 error node v4.0.0
76604 error npm  v2.14.2
76605 error code ELIFECYCLE
76606 error runas@2.0.0 install: `node-gyp rebuild`
76606 error Exit status 1
76607 error Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
76607 error This is most likely a problem with the runas package,
76607 error not with npm itself.
76607 error Tell the author that this fails on your system:
76607 error     node-gyp rebuild
76607 error You can get their info via:
76607 error     npm owner ls runas
76607 error There is likely additional logging output above.
76608 verbose exit [ 1, true ]
76609 verbose unbuild node_modules/runas
76610 info preuninstall runas@2.0.0
76611 info uninstall runas@2.0.0
76612 verbose unbuild rmStuff runas@2.0.0 from /home/tut/Загрузки/atom/build/node_modules
76613 info postuninstall runas@2.0.0
76614 silly gentlyRm /home/tut/Загрузки/atom/build/node_modules/runas is being purged from base /home/tut/Загрузки/atom/build
76615 verbose gentlyRm don't care about contents; nuking /home/tut/Загрузки/atom/build/node_modules/runas
76616 silly vacuum-fs purging /home/tut/Загрузки/atom/build/node_modules/runas
76617 silly vacuum-fs quitting because other entries in /home/tut/Загрузки/atom/build/node_modules
```

**Comment by 50Wliu** [comment]
Atom has not yet updated to a version of runas that supports Node 4.0.  See #8508 for a tracking issue on when Atom can be built with Node 4.
