### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by blissGitHub** [atom/atom#8770]
[Enter steps to reproduce below:]
1. Drag React Native Project which contains js files and non js files such as Xcode files etc into the Atom Editor's Icon on the Application Menu Bar......
2. If that doesn't open the project and the folder.  Manually activate atom by clicking on the icon and then open the project like usual. After that try typing.....it won't let u type....a Uncaught SyntaxError warning inside of a Modal Box keeps on popping up......

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core
### Stack Trace

Uncaught SyntaxError: Unexpected token ILLEGAL

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:773

SyntaxError: Unexpected token ILLEGAL
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/set-helpers.js:26:31
    at Set.forEach (native)
    at subtractSet (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/set-helpers.js:24:18)
    at Leaf.splice (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-index.js:402:9)
    at Node.splice (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-index.js:154:32)
    at MarkerIndex.module.exports.MarkerIndex.splice (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-index.js:549:38)
    at MarkerStore.module.exports.MarkerStore.splice (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:194:25)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:636:15)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:553:12)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:472:43)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 13,
    "invisibles": {}
  }
}
```
### Installed Packages

``` coffee
# User
highlight-nbsp, v0.1.1
meteor-api, v2.12.0

# Dev
No dev packages
```

**Comment by umpirsky** [comment]
Just faced same issue in Atom 1.7.2 on Ubuntu Linux.

I just wanted to select some text in PHP file.
