### ISSUE TITLE
Failed to activate the set-syntax package

### ISSUE THREAD

**Issue by davidmoshal** [atom/atom#8803]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the set-syntax package

```
At Cannot read property 'getGrammars' of undefined

TypeError: Cannot read property 'getGrammars' of undefined
    at Object.module.exports.activate (<anonymous>:8:16)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:469:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:324:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:464:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:46)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
language-elixir, v0.3.3
language-erlang, v2.0.0
language-groovy, v0.3.0
language-livescript, v0.0.2
language-scala, v1.1.0
language-swift, v0.3.0
pain-split, v1.1.2
project-manager, v1.14.1
set-syntax, v0.1.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Huh, I wonder why `atom.grammars` would be `undefined` [here](https://github.com/lee-dohm/set-syntax/blob/a8a51e24e4fe8656bb73cd89512537a698c785ad/lib/main.coffee#L10)? Thanks for the report, @davidmoshal.

+Just a friendly cc to @lee-dohm since this is related to set-syntax. :v: :smile:

**Comment by lee-dohm** [comment]
Ah, I see why. Because it is not `undefined` there ... it is `undefined` [here](https://github.com/lee-dohm/set-syntax/blob/v0.1.0/lib/main.coffee#L8). Notice that @davidmoshal is using an out-of-date version of my [set-syntax package](https://atom.io/packages/set-syntax) ... which is currently at version 0.3.0. The version that @davidmoshal is running refers to the old `atom.syntax` name. v0.2.0 updated to the new `atom.grammars` name.

@davidmoshal this should go away if you update the version of set-syntax you're using to the latest. Please let us know if you have any questions.

**Comment by izuzak** [comment]
:zap: @lee-dohm -- thank you for looking into this.

**Comment by davidmoshal** [comment]
Thanks, I'll try that - I'm a bit surprised, as I downloaded the latest version of atom, replacing an older version. 
Also, not that there are actually 2 separate errors, here is the other one:

```
TypeError: Cannot read property 'eachPaneView' of undefined
    at Object.module.exports.activate (<anonymous>:3:39)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:469:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:324:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:464:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:46)
```

**Comment by lee-dohm** [comment]
> I'm a bit surprised, as I downloaded the latest version of atom

You're on the latest version of Atom, yes. But you need to install the latest version of my [set-syntax package](https://atom.io/packages/set-syntax). Notice in your initial report it states:

> set-syntax, v0.1.0

But if you look at the set-syntax package page:

<img width="744" alt="napkin 09-17-15 7 42 33 am" src="https://cloud.githubusercontent.com/assets/1038121/9936203/a999b1c6-5d0f-11e5-885d-e54c77b0fb2f.png">

v0.3.0 is the latest version.

**Comment by lee-dohm** [comment]
I just double-checked, the same goes for the pain-split package. You're running v1.1.2 and the current version is v1.4.0.

**Comment by davidmoshal** [comment]
@izuzak  @lee-dohm  guys, you get full marks for responsiveness
 - amazing, haven't seen such quick response to open source bug reports.

However, the updating mechanism in Atom doesn't get such a good report card!
Still struggling with updating the various packages.
Tried to update all the 'deprecated' packages - many of those updates failed.
Even read the manual:
https://atom.io/docs/v1.0.13/upgrading-to-1-0-apis-upgrading-your-package

**Comment by lee-dohm** [comment]
That article you linked to isn't for end-users. It is intended for package authors (who hopefully have already followed those pieces of advice :grinning:).

To upgrade your packages you can go into the Settings View using <kbd>Cmd+,</kbd> on OS X or <kbd>Ctrl+,</kbd> on other platforms. Once there, you select the Updates tab on the left. It should automatically check for updates and allow you to install them.

**Please note:** If you have a lot of packages that need updating (more than 10), you may want to update them one at a time. Trying to update too many at the same time can cause performance problems.

**Comment by davidmoshal** [comment]
Thanks, I seem to have dozens of packages, many that I don't recall using ever (e.g Haskell ?).

**Comment by davidmoshal** [comment]
The handling of deprecated packages seems odd to me, and more manual than I expected.
Either that or the error messages / help documentation could be improved.
Problem might just be that I installed a very old version long ago.

**Comment by davidmoshal** [comment]
Ok, problem sorted, I completely removed atom, then reinstalled a new version:

```bash
rm -rf ~/.atom
rm -rf /usr/local/bin/atom
rm -rf /usr/local/bin/apm
rm -rf /Applications/Atom.app
rm -rf ~/Library/Preferences/com.github.atom.plist
rm -rf ~/Library/Application Support/com.github.atom.ShipIt
rm -rf ~/Library/Application Support/Atom
rm -rf ~/Library/Saved Application State/com.github.atom.savedState
rm -rf ~/Library/Caches/com.github.atom
rm -rf ~/Library/Caches/Atom
```

Might be a bit drastic but was simply much quicker than trying to update all the plugins.
Thanks for your help.

Dave

**Comment by 50Wliu** [comment]
For future reference, you can get rid of all your installed packages by just doing `rm -rf ~/.atom/packages` :).  This will keep your Atom version, preferences, etc. intact.

**Comment by davidmoshal** [comment]
@50Wliu thanks,

However, I wanted to completely remove atom and re-install it because the version I had  was many years old.

Awesome project, though I'm not sure I'm ready to leave IntelliJ (yet).
