### ISSUE TITLE
Failed to activate the gamboge package

### ISSUE THREAD

**Issue by parshav7** [atom/atom#8825]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the gamboge package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:16:1)
    at <anonymous>:41:3
    at Object.<anonymous> (<anonymous>:41:3)
    at Object.<anonymous> (<anonymous>:16:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (/Users/rajinderchauhan/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "autoIndent": false,
    "fontFamily": "Comic sans"
  }
}
```

### Installed Packages

```coffee
# User
gamboge, v0.1.3

# Dev
No dev packages
```

**Comment by izuzak** [comment]
This seems like a problem with the https://github.com/eddieantonio/atom-gamboge package -- I suggest you report the issue there (btw, I just noticed in the README of that the package is no longer maintained, so you might not get a response).

The reason why the Atom core repository was associated with the exception is a problem that we're tracking in https://github.com/atom/notifications/issues/66, so I'll add this issue to that list. 

Thanks!
