### ISSUE TITLE
Package install failed "Xcode/iOS license requires admin privileges"

### ISSUE THREAD

**Issue by davidmoshal** [atom/atom#8832]
```
> child_pty@1.1.1 install /private/var/folders/gd/qgg5gjt90_n6dcywjrm3jccc0000gn/T/apm-install-dir-115817-29019-dxld6i/node_modules/iex/node_modules/child_pty
> node-gyp rebuild


> pty.js@0.2.13 install /private/var/folders/gd/qgg5gjt90_n6dcywjrm3jccc0000gn/T/apm-install-dir-115817-29019-dxld6i/node_modules/iex/node_modules/pty.js
> node-gyp rebuild




Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.





Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.


gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/gd/qgg5gjt90_n6dcywjrm3jccc0000gn/T/apm-install-dir-115817-29019-dxld6i/node_modules/iex/node_modules/child_pty
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 


Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.





Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.


gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/gd/qgg5gjt90_n6dcywjrm3jccc0000gn/T/apm-install-dir-115817-29019-dxld6i/node_modules/iex/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/davem/.atom/.apm/.apmrc" "--userconfig" "/Users/davem/.atom/.apmrc" "install" "/private/var/folders/gd/qgg5gjt90_n6dcywjrm3jccc0000gn/T/d-115817-29019-op8ivb/package.tgz" "--target=0.30.6" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! child_pty@1.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the child_pty@1.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the child_pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls child_pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/gd/qgg5gjt90_n6dcywjrm3jccc0000gn/T/apm-install-dir-115817-29019-dxld6i/npm-debug.log
```

**Comment by davidmoshal** [comment]
Solved by running XCode manually (which had been updated automatically, but not opened yet).
