### ISSUE TITLE
Uncaught TypeError: Cannot read property 'which' of undefined

### ISSUE THREAD

**Issue by calebmeyer** [atom/atom#8841]
[Enter steps to reproduce below:]

1. Using vim mode, set up a function to allow you to use j j to exit insert mode to normal mode
Here is that function:

init.coffee
```coffee
atom.commands.add 'atom-text-editor', 'custom:wait-key-press', (e)->
  oe = e.originalEvent
  char = String.fromCharCode(oe.which)
  char = char.toLowerCase() unless oe.shift
  atom.workspace.getActivePaneItem().insertText(char)
```

keymap.cson
```cson
'.editor.vim-mode.insert-mode':
  'j': 'custom:wait-key-press'

'.vim-mode.insert-mode:not(.mini)':
  'j j': 'vim-mode:activate-normal-mode'
```

2. Press the j key once.

### Notes
- I didn't write this function. I stole it from [here](https://github.com/atom/vim-mode/issues/334#issuecomment-110577371)
- It worked up til 1.0.11, but not for 1.0.12 or 1.0.13
- I may be missing that this was added natively to atom (key melodies, if you will) but I've looked at the release notes and don't see anything.

**Atom Version**: 1.0.13
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'which' of undefined

```
At /Users/cm022291/.dotfiles/atom/init.coffee:15

TypeError: Cannot read property 'which' of undefined
    at atom-text-editor.<anonymous> (/Users/cm022291/.dotfiles/atom/init.coffee:15:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/command-registry.js:240:29)
    at /opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at KeymapManager.module.exports.KeymapManager.terminatePendingState (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:498:14)
```

### Commands

```
     -0:02.6.0 vim-mode:insert-after (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.1.0 custom:wait-key-press (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-mustache",
      "linter-haml",
      "deprecation-cop",
      "overrides",
      "autocomplete-paths",
      "linter-foodcritic",
      "linter-less",
      "line-ending-selector"
    ],
    "themes": [
      "accents-ui",
      "photon-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "scrollPastEnd": true,
    "preferredLineLength": 120,
    "showIndentGuide": true,
    "fontFamily": "Consolas",
    "fontSize": 16
  }
}
```

### Installed Packages

```coffee
# User
accents-ui, v1.0.0
atom-jasmine, v0.6.0
auto-update-packages, v1.0.0
file-icons, v1.6.9
highlight-line, v0.11.0
language-diff, v0.3.1
language-gitignore, v0.2.0
language-haml, v0.21.0
language-lisp, v0.1.2
language-log, v0.6.0
language-restructuredtext, v0.9.0
language-rspec, v0.3.0
language-rust, v0.4.5
linter, v1.5.2
minimap, v4.13.3
minimap-autohide, v0.10.1
minimap-git-diff, v4.1.8
omni-ruler, v0.4.2
open-recent, v2.3.0
pain-split, v1.4.0
photon-syntax, v0.4.7
set-syntax, v0.3.0
trailing-spaces, v0.3.2
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by calebmeyer** [comment]
After some looking into this, I found that I actually don't need the function in the init script at all anymore. Does anyone know when this was introduced?

**Comment by calebmeyer** [comment]
Well, I haven't found the specific commit, but it's listed on the quality initiative: #7995 

Closing this issue.
