### ISSUE TITLE
Uncaught TypeError: Cannot read property 'index' of undefined

### ISSUE THREAD

**Issue by anwarule** [atom/atom#8856]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: linux 3.16.0-49-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'index' of undefined

```
At /usr/share/atom/resources/app/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:95

TypeError: Cannot read property 'index' of undefined
  at IntervalSkipList.module.exports.IntervalSkipList.findIntersecting (/usr/share/atom/resources/app/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:95:31)
  at MarkerManager.module.exports.MarkerManager.findMarkers (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker-manager.js:156:46)
  at TextBuffer.module.exports.TextBuffer.findMarkers (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:657:27)
  at DisplayBuffer.module.exports.DisplayBuffer.findMarkers (/usr/share/atom/resources/app/src/display-buffer.js:1278:26)
  at DisplayBuffer.module.exports.DisplayBuffer.decorationsForScreenRowRange (/usr/share/atom/resources/app/src/display-buffer.js:1171:20)
  at TextEditor.module.exports.TextEditor.decorationsForScreenRowRange (/usr/share/atom/resources/app/src/text-editor.js:1216:33)
  at [object Object].module.exports.React.createClass.render (/usr/share/atom/resources/app/src/text-editor-component.js:77:30)
  at [object Object]._renderValidatedComponent (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1249:34)
  at [object Object].updateComponent (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1179:33)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1123:10)
  at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1063:14)
  at runBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:152:17)
  at ReactReconcileTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.forceUpdate (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1232:18)
  at /usr/share/atom/resources/app/src/text-editor-component.js:320:28

```

### Commands

```
     -0:00.0 minimap:toggle (atom-text-editor.editor.editor-colors.is-focused)
```

### Config

```
{
  "editor": {
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.11
minimap, v3.5.6
php-twig, v4.0.0

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
This is an old version of Atom. Can you try upgrading to the latest (1.0.15)? Closing this out for now. I can reopen if you're still experiencing the problem after upgrading.

**Comment by anwarule** [comment]
I disable minimap and problem solved
