### ISSUE TITLE
failed to load the emmet package...

### ISSUE THREAD

**Issue by netmou** [atom/atom#8866]
![qq 20150920144321](https://cloud.githubusercontent.com/assets/7068058/9979568/6d0a3782-5fa6-11e5-912c-00b0754790cf.png)
linter-php,linter-jshint,atom-beautiy,and so on.many packages are failed to load width the same reason  since update atom to ver-1.012
env: ver1.015; win10 x86_64

**Comment by cjose3** [comment]
the 'tab'  command not not found for me.

**Comment by netmou** [comment]
### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "openEmptyEditorOnStart": false,
    "projectHome": "e:\\",
    "themes": [
      "one-light-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "wrap-guide",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-property-list",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-shellscript",
      "language-todo",
      "language-toml",
      "language-yaml",
      "markdown-preview",
      "metrics",
      "timecop",
      "language-gfm",
      "language-go",
      "language-clojure"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "editor": {
    "invisibles": {},
    "fontSize": 22,
    "fontFamily": "Source Code Pro",
    "softWrap": true,
    "showIndentGuide": true,
    "tabLength": 4,
    "zoomFontWhenCtrlScrolling": false
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@netmou can you please move this over to [emmetio/emmet](https://github.com/emmetio/emmet-atom/issues)?  Thanks.

**Comment by netmou** [comment]
no, update atom from v1.0.11 to  v1.0.15 

![qq 20150921175152](https://cloud.githubusercontent.com/assets/7068058/9989243/865dd70a-6089-11e5-80e5-49d73e8e9937.png)
then disabled the package  atom-beautify, the same just the errors were thrown from other packages

**Comment by netmou** [comment]
the specific error-info like this


**Atom Version**: 1.0.15
**System**: Unknown Windows Version
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.12


### Stack Trace

Failed to load the linter-csslint package

```
At Cannot find module 'atom-linter'

Error: Cannot find module 'atom-linter'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (D:\Program Files\Atom\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\志强\.atom\packages\linter-csslint\lib\main.coffee:4:13)
    at Object.<anonymous> (C:\Users\志强\.atom\packages\linter-csslint\lib\main.coffee:62:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (D:\Program Files\Atom\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

**Comment by netmou** [comment]
My os is windows 10, but atom can't recognize
