### ISSUE TITLE
Uncaught Error: EMFILE: too many open files, open 'C:\Users\gcollier\.atom\config.cson'

### ISSUE THREAD

**Issue by photex** [atom/atom#8882]
[Enter steps to reproduce below:]

1. Attempt to save config.cson
2. ...

**Atom Version**: 1.0.15
**System**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EMFILE: too many open files, open 'C:\Users\gcollier\.atom\config.cson'

```
At C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\src\pane.js:809

Error: EMFILE: too many open files, open 'C:\Users\gcollier\.atom\config.cson'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.writeFileSync (fs.js:1165:15)
  at Object.fsPlus.writeFileSync (C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
  at File.module.exports.File.writeFileSync (C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:277:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:377:21)
  at File.module.exports.File.writeSync (C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:350:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1021:19)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1002:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\src\text-editor.js:584:26)
  at Pane.module.exports.Pane.saveItem (C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\src\pane.js:547:18)
  at Pane.module.exports.Pane.saveActiveItem (C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\src\pane.js:530:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\src\workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\src\workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\gcollier\AppData\Local\atom\app-1.0.15\resources\app.asar\src\window-event-handler.js:184:20)

```

### Commands

```
  4x -1:32.8.0 core:select-up (atom-text-editor.editor.is-focused)
     -1:31.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:28.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:27.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  5x -1:20.7.0 core:move-down (atom-text-editor.editor.is-focused)
  9x -1:19.4.0 core:select-up (atom-text-editor.editor.is-focused)
     -1:15.4.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -1:13.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:12.6.0 core:save (atom-text-editor.editor.is-focused)
  9x -1:01.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:00.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:00.0 core:move-left (atom-text-editor.editor.is-focused)
  5x -0:59.2.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:51 core:save (atom-text-editor.editor.is-focused)
     -0:06.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "projectHome": "/projects",
    "themes": [
      "base-16-ocean-dark-ui-theme",
      "base16-ocean-dark"
    ]
  },
  "editor": {
    "invisibles": {},
    "preferredLineLength": 100,
    "showIndentGuide": true,
    "lineHeight": 1.25,
    "scrollPastEnd": true,
    "fontFamily": "Consolas"
  }
}
```

### Installed Packages

```coffee
# User
base-16-ocean-dark-ui-theme, v1.5.1
base16-ocean-dark, v0.3.0
language-rust, v0.4.5
linter-rust, v0.2.9
racer, v0.17.2
rust-api-docs-helper, v0.5.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Refs #8834, #8882, and atom/settings-view#653.

**Comment by izuzak** [comment]
Should be fixed with https://github.com/atom/atom/pull/8927
