### ISSUE TITLE
APM not working when using latest Atom package on Fedora 22 with Node 0.12

### ISSUE THREAD

**Issue by keirlawson** [atom/atom#8894]
When I try to run APM I get:

```/usr/share/atom/resources/app/apm/bin/node: bad option: --harmony_collections```

`/usr/share/atom/resources/app/apm/bin/node` is a symlink to the system's node, which I recently upgrades to 0.12 from 0.10

**Comment by nlaplante** [comment]
Same issue here. Removing `--harmony_collections` from */usr/share/atom/resources/app/apm/bin/apm* triggers another error:

```sh
$ apm
module.js:450
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:450:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

`/usr/share/atom/resources/app/apm/bin/node` is a symlink to `/usr/bin/node`.

```sh
$ node --version
v5.0.0
```

**Comment by xasx** [comment]
Still present with
* node v5.1.0 and
* Atom 1.2.1

**Comment by cortopy** [comment]
Experiencing same issue after upgrading node to 5.1.0 from 0.10

**Comment by keirlawson** [comment]
I'm finding with the official Atom packages this is no longer an issue, it seems to me like this may be with the Helber copr repo, are other folks using the official Atom RPMs or ones from that copr?

I've raised a bug with said repo here: https://github.com/helber/fedora-specs/issues/2

**Comment by cortopy** [comment]
Yes, I'm also using Helber copr repo. Thanks for that

**Comment by xasx** [comment]
Confirmed. Works with official RPM.

**Comment by jokeraces** [comment]
Confirmed. Works with official RPM.[2]!
