### ISSUE TITLE
Uncaught TypeError: this.activeItem.serialize is not a function

### ISSUE THREAD

**Issue by clackmac** [atom/atom#8916]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.16
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: this.activeItem.serialize is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:614

TypeError: this.activeItem.serialize is not a function
  at Pane.module.exports.Pane.copyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:614:168)
  at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:703:32)
  at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:686:19)
  at atom-pane.atom.commands.add.pane:split-right (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:273:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```
### Commands

```
     -1:30 browser-plus:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:43.7.0 pane:split-up (atom-text-editor.editor.is-focused)
     -0:35.2.0 pane:split-left (atom-text-editor.editor.is-focused)
     -0:00.6.0 pane:split-right (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "indent-helper"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "showInvisibles": true
  }
}
```
### Installed Packages

``` coffee
# User
browser-plus, v0.0.34
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @clackmac, what were you doing when this error occurred?  Were you trying to split a browser-plus pane?

**Comment by clackmac** [comment]
Hey, I was using rigth/left pane splitting to have a browser on one of the panes. 
Having my tabs on the left and browser on right, removed the tab from the right which ended up in a standard view (no split).
After that, If trying to split again the error occurs

**Comment by izuzak** [comment]
@nathansobo I'm able to reliably reproduce this with the browser-plus package:

1. install the package
2. run "Browser plus: open"
3. focus the pane with the browser
4. try splitting that pane and observe the exception

As far as I can tell, the pane item that's created doesn't have a `serialize` method, so things blow up and Atom is blamed. In such a case, what can we do so that Atom it isn't blamed here? Can we point the exception at the package somehow or handle this more gracefully without even throwing an exception? Is the `serialize` method required (I tried to find an answer to this, but failed)?

**Comment by skandasoft** [comment]
taken care in browser-plus.  you can close this ticket.

**Comment by nathansobo** [comment]
I still think we shouldn't blow up when trying to split an item that doesn't copy. We should just split empty, or move the item.
