### ISSUE TITLE
script/bootstrap failure installing runas@2.0.0 / node-gyp

### ISSUE THREAD

**Issue by g2p** [atom/atom#8922]
The build script tries to install runas@2.0.0, which fails due to incompatibilities with recent V8 headers (I'm running the latest node 4 from nvm).

```
$ script/build
…
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (~/var/co/git/atom/build/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-10-generic
gyp ERR! command "~/var/co/git/nvm/versions/node/v4.1.1/bin/node" "~/var/co/git/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ~/var/co/git/atom/build/node_modules/runas
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.2.0-10-generic
npm ERR! argv "~/var/co/git/nvm/versions/node/v4.1.1/bin/node" "~/var/co/git/atom/build/node_modules/.bin/npm" "--userconfig=~/var/co/git/atom/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v4.1.1
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.
```

Root cause is the runas version; npm install runas@2.0.0 fails, npm install runas@3.1.0 succeeds.

**Comment by mnquintana** [comment]
Fixed in https://github.com/atom/atom/pull/8926
