### ISSUE TITLE
un-usable blank white page

### ISSUE THREAD

**Issue by mid0ri** [atom/atom#8952]
So I recently installed atom text editor via the ppa. Unfortunately when i go to use the program it was different then how I last remembered it. It's completely blank white, with stuff for web editing which is something I DONT use. please fix!. I've purged it and reinstall it same thing. 
![screenshot from 2015-09-25 19-01-47](https://cloud.githubusercontent.com/assets/10860926/10113924/ec275b34-63b7-11e5-9a85-134c44aad8ef.png)

**Comment by maxbrunsfeld** [comment]
This probably means there was an error when loading the editor. Were there any errors in the javascript console?

We don't maintain the `ppa`, so I'm not sure what version you downloaded. Can you install the package from our releases page, and report whether you still see an error?

**Comment by mid0ri** [comment]
so purge it first? then remove ppa autoclean then install?

**Comment by mid0ri** [comment]
same error
![screenshot from 2015-09-25 19-10-31](https://cloud.githubusercontent.com/assets/10860926/10114035/1f51ace8-63b9-11e5-88a2-674b14967d93.png)

**Comment by maxbrunsfeld** [comment]
Before you get rid of that version of the app, could you open the app again and report any errors you see in the `Console` tab of the developer tools?

**Comment by mid0ri** [comment]
just re-installed it same thing and here is the error in console
Error: EACCES: permission denied, open '/home/canti/.atom/compile-cache/less/df1b7fbc57dbeed23a8f1f8de95b4dfebcc06066/imports.json'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.writeFileSync (fs.js:1165:15)
  at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
  at LessCache.module.exports.LessCache.writeJson (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:155:17)
  at LessCache.module.exports.LessCache.setImportPaths (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:113:12)
  at new LessCache (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:32:12)
  at new LessCompileCache (/usr/share/atom/resources/app.asar/src/less-compile-cache.js:20:20)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/usr/share/atom/resources/app.asar/src/theme-manager.js:299:26)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (/usr/share/atom/resources/app.asar/src/theme-manager.js:286:21)
  at ThemeManager.module.exports.ThemeManager.requireStylesheet (/usr/share/atom/resources/app.asar/src/theme-manager.js:203:24)
  at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (/usr/share/atom/resources/app.asar/src/theme-manager.js:266:12)
  at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (/usr/share/atom/resources/app.asar/src/theme-manager.js:261:19)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom.js:666:19)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:82:25)
  at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:35:9)

**Comment by mid0ri** [comment]
i fixed it uninstall and install sublime

**Comment by maxbrunsfeld** [comment]
Ok, it looks you ran Atom as root, or some other user previously, such that it created files in your home directory (in `~/.atom`), that are not readable by your current user. Atom needs to be able to read the files in `~/.atom`.

**Comment by mid0ri** [comment]
omg thank you so much
