### ISSUE TITLE
error building atom on archlinux (script/build) with gcc/c++ version 5.2

### ISSUE THREAD

**Issue by Linkaan** [atom/atom#8953]
I have had two issues so far building atom from scratch, one I was able to workaround the other one I need help with. After I cloned this repo to my computer I installed the required packages etc. and then I used the `script/build` script which gave me this error. I followed [these](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md) instructions.
```
Node: v4.1.1
npm: v3.3.4
Installing build modules...
npm ERR! Linux 4.1.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--userconfig=/home/linkan/src/atom/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.4
npm ERR! code EREADFILE

npm ERR! Error extracting /home/linkan/.atom/.npm/cson-safe/1.0.4/package.tgz archive: ENOENT: no such file or directory, open '/home/linkan/.atom/.npm/cson-safe/1.0.4/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/linkan/src/atom/build/npm-debug.log
```

I looked into the `/home/linkan/.atom/.npm/cson-safe/` directory and saw that there was indeed no directory with the name 1.0.4, instead there was the 1.0.5 directory. As a workaround I did this:
`ln -nsf /home/linkan/.atom/.npm/cson-safe/1.0.5 /home/linkan/.atom/.npm/cson-safe/1.0.4`

As to the second issue I believe it has something to do with the version of gnu c++ compiler installed on my system which is currently 5.2.0. The output (again partialy in swedish) of running `script/build` is below
```
Node: v4.1.1
npm: v3.3.4
Installing build modules...
In file included from ../src/main.cc:1:0:
../../nan/nan.h:260:25: fel: omdefinition av ”template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)”
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../../nan/nan.h:255:25: anm: ”template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)” tidigare deklarerad här
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../../nan/nan.h:660:13: fel: ”node::smalloc” har inte deklarerats
     , node::smalloc::FreeCallback callback
             ^
../../nan/nan.h:660:35: fel: expected ”,” or ”...” before ”callback”
     , node::smalloc::FreeCallback callback
                                   ^
../../nan/nan.h: I funktion ”v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)”:
../../nan/nan.h:664:50: fel: ”callback” deklarerades inte i detta definitionsområde
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../../nan/nan.h:664:60: fel: ”hint” deklarerades inte i detta definitionsområde
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../../nan/nan.h: I funktion ”v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)”:
../../nan/nan.h:671:67: fel: ingen funktion som stämmer för anrop av ”New(v8::Isolate*, const char*&, uint32_t&)”
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:25:0,
                 from ../src/main.cc:1:
/home/linkan/.node-gyp/4.1.1/include/node/node_buffer.h:31:40: anm: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <nära träff>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/linkan/.node-gyp/4.1.1/include/node/node_buffer.h:31:40: anm:   konvertering av argument 3 vore felformaterat:
In file included from ../src/main.cc:1:0:
../../nan/nan.h:671:67: fel: ogiltig konvertering från ”uint32_t {aka unsigned int}” till ”node::encoding” [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:25:0,
                 from ../src/main.cc:1:
/home/linkan/.node-gyp/4.1.1/include/node/node_buffer.h:43:40: anm: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <nära träff>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/linkan/.node-gyp/4.1.1/include/node/node_buffer.h:43:40: anm:   konvertering av argument 2 vore felformaterat:
In file included from ../src/main.cc:1:0:
../../nan/nan.h:671:67: fel: ogiltig konvertering från ”const char*” till ”char*” [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../../nan/nan.h: I funktion ”v8::Local<v8::Object> NanNewBufferHandle(uint32_t)”:
../../nan/nan.h:675:29: fel: kunde inte konvertera ”node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))” från ”v8::MaybeLocal<v8::Object>” till ”v8::Local<v8::Object>”
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                             ^
../../nan/nan.h: I funktion ”v8::Local<v8::Object> NanBufferUse(char*, uint32_t)”:
../../nan/nan.h:682:12: fel: ”Use” är inte en medlem av ”node::Buffer”
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/runas/src/main.o] Fel 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.6-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/linkan/src/atom/build/node_modules/runas
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.1.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--userconfig=/home/linkan/src/atom/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/linkan/src/atom/build/npm-debug.log
```

See the [npm-debug.log](https://gist.github.com/Linkaan/68054d9d653129c6fdf4) for details.

P.S if I skip part 2 (Checkout the latest Atom release) it seems to work fine, but that will build the atom from the master branch which I believe is unstable?

**Comment by 50Wliu** [comment]
Your problem is that you're using Node 4, which the latest release doesn't support yet.  `master`, as you've already figured out, does :smile:.

In general, master isn't *too* unstable - I really haven't ever had a problem with it.  Alternatively, you can try the `beta` branch which should be more stable than master.

**Comment by Linkaan** [comment]
@50Wliu Alright, I'll just use the latest code because that will probably save alot of time.
