### ISSUE TITLE
Failed to load a language-haml package grammar

### ISSUE THREAD

**Issue by Dezande** [atom/atom#8970]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.13.0-63-generic
**Thrown From**: Atom Core

### Stack Trace

Failed to load a language-haml package grammar

```
At Syntax error on line 241, column 18: evalmachine.<anonymous>:1
"#\\{" "end": "\\}"
       ^^^^^
Unexpected string in /home/vincent/.atom/packages/language-haml/grammars/ruby haml.cson

SyntaxError: Syntax error on line 241, column 18: evalmachine.<anonymous>:1
"#\\{" "end": "\\}"
       ^^^^^
Unexpected string
  at nodeTransforms.Literal (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:100:15)
  at transformNode (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at nodeTransforms.Value (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at /usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:114:17
  at Array.reduce (native)
  at nodeTransforms.Obj (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at nodeTransforms.Value (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at Array.map (native)
  at nodeTransforms.Arr (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:104:27)
  at transformNode (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at nodeTransforms.Value (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at /usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:114:17
  at Array.reduce (native)
  at nodeTransforms.Obj (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at nodeTransforms.Value (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at /usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:114:17
  at Array.reduce (native)
  at nodeTransforms.Obj (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at nodeTransforms.Value (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at /usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:114:17
  at Array.reduce (native)
  at nodeTransforms.Obj (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at nodeTransforms.Value (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at nodeTransforms.Block (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:76:14)
  at transformNode (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at Object.parse (/usr/share/atom/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:203:12)
  at parseObject (/usr/share/atom/resources/app/node_modules/season/lib/cson.js:42:23)
  at parseContents (/usr/share/atom/resources/app/node_modules/season/lib/cson.js:91:16)
  at /usr/share/atom/resources/app/node_modules/season/lib/cson.js:179:24
  at FSReqWrap.oncomplete (fs.js:100:15)

  at /home/vincent/.atom/packages/language-haml/grammars/ruby haml.cson:1:1
```

### Commands

```
     -8:41.2 core:delete (atom-text-editor.editor)
     -8:40.3 core:backspace (atom-text-editor.editor)
     -8:39.6 core:delete (atom-text-editor.editor)
     -8:39.0 core:move-up (atom-text-editor.editor)
     -8:38.7 core:delete (atom-text-editor.editor)
     -8:37.9 core:save (atom-text-editor.editor)
     -0:08.8 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "comment",
      "keyboard-localization"
    ]
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
language-haml, v0.22.2
language-slim, v0.5.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Can you please move this over to [ezekg/language-haml](https://github.com/ezekg/language-haml/issues)?  Thanks.

**Comment by ezekg** [comment]
@Dezande, move over to ezekg/language-haml#46 and let me know if the newest update fixes the issue.
