### ISSUE TITLE
Uncaught Error: EBUSY: resource busy or locked, open 'C:\inetpub\wwwroot\Cipher\js\vendor\kendo\k...

### ISSUE THREAD

**Issue by ryan-nauman** [atom/atom#8976]
I needed to update a file from a download so I:

1. Tried to drag from windows explorer into the folder in the directory tree. Gave file not found error.
2. Copy from explorer & paste into atom folder. Nothing happened.
3. Replaced the file from explorer. This EBUSY error appeared.

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EBUSY: resource busy or locked, open 'C:\inetpub\wwwroot\Cipher\js\vendor\kendo\kendo.web.js'

```
At C:\Users\ryan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:128

Error: EBUSY: resource busy or locked, open 'C:\inetpub\wwwroot\Cipher\js\vendor\kendo\kendo.web.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:384:29)
    at File.module.exports.File.readSync (C:\Users\ryan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:261:36)
    at TextBuffer.module.exports.TextBuffer.updateCachedDiskContentsSync (C:\Users\ryan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1072:85)
    at C:\Users\ryan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1213:17
    at Emitter.module.exports.Emitter.emit (C:\Users\ryan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at C:\Users\ryan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:447:40
    at _fulfilled (C:\Users\ryan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:794:54)
    at self.promiseDispatch.done (C:\Users\ryan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:823:30)
    at Promise.promise.promiseDispatch (C:\Users\ryan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:756:13)
    at C:\Users\ryan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:564:44
    at flush (C:\Users\ryan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:110:17)
    at doNTCallback0 (node.js:416:9)
```

### Commands

```
     -1:26.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:25.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:23.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {
      "eol": false,
      "cr": false,
      "tab": false,
      "space": false
    },
    "fontSize": 13,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-beautify, v0.28.14
atom-typescript, v7.0.1
build, v0.47.0
build-gulp, v0.2.0
linter, v1.6.0
seti-syntax, v0.4.0
seti-ui, v0.8.0

# Dev
No dev packages
```

**Comment by damieng** [comment]
Would be solved by https://github.com/atom/atom/issues/7659 so tracking it there.
