### ISSUE TITLE
Error thrown when trying to move an Editor with gutter between panes

### ISSUE THREAD

**Issue by steelbrain** [atom/atom#9012]
Steps to reproduce:
  - Install latest linter
  - Split the panes
  - Move an editor between split panes

Ref: atom-community/linter#913

**Comment by 50Wliu** [comment]
Relevant error:
Uncaught Error: Tried to create a gutter with a name that is already in use.

At /Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:36
```
Error: Tried to create a gutter with a name that is already in use.
  at GutterContainer.module.exports.GutterContainer.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:36:15)
  at TextEditor.module.exports.TextEditor.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2613:35)
  at EditorLinter.addGutter (/Users/Serdar/.atom/packages/linter/lib/editor-linter.js:106:33)
  at EditorLinter.handleGutter (/Users/Serdar/.atom/packages/linter/lib/editor-linter.js:99:14)
  at /Users/Serdar/.atom/packages/linter/lib/editor-linter.js:50:13
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
  at new EditorLinter (/Users/Serdar/.atom/packages/linter/lib/editor-linter.js:48:40)
  at EditorRegistry.create (/Users/Serdar/.atom/packages/linter/lib/editor-registry.coffee:13:24)
  at Linter.createEditorLinter (/Users/Serdar/.atom/packages/linter/lib/linter.coffee:80:29)
  at /Users/Serdar/.atom/packages/linter/lib/linter.coffee:36:71
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:281:16
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:342:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:352:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:339:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:345:20)
  at Pane.module.exports.Pane.moveItemToPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:439:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:706:20)
  at TabBarView.module.exports.TabBarView.onDrop (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:632:23)
  at space-pen-ul.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

Commands
```
     -5:37.9.0 core:save (atom-text-editor.editor.is-focused)
     -5:20.5.0 core:copy (atom-text-editor.editor.is-focused)
     -5:20.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  8x -5:19.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:16 core:backspace (atom-text-editor.editor.is-focused)
     -5:15.3.0 core:save (atom-text-editor.editor.is-focused)
     -5:12.3.0 core:cut (atom-text-editor.editor.is-focused)
  2x -5:11.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:09.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:09.5.0 core:paste (atom-text-editor.editor.is-focused)
     -5:09.1.0 core:save (atom-text-editor.editor.is-focused)
     -4:25.3.0 core:copy (atom-text-editor.editor.mini.is-focused)
     -4:24.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:18.9.0 core:paste (atom-text-editor.editor.is-focused)
     -4:18.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:29.3.0 core:copy (atom-text-editor.editor.is-focused)
```

Config
```cson
{
  "core": {
    "disabledPackages": [
      "tool-bar-main"
    ],
    "themes": [
      "one-dark-ui",
      "outlander-syntax"
    ]
  },
  "linter": {}
}
```

Installed Packages
```coffee
# User
angularjs, v0.3.0
angularjs-styleguide-snippets, v0.7.2
atom-beautify, v0.28.14
atom-jasmine, v0.6.0
atom-ternjs, v0.8.1
color-picker, v2.0.12
file-icons, v1.6.9
language-lua, v0.9.4
linter, v1.7.2
linter-jscs, v3.0.0
linter-jshint, v1.2.0
minimap, v4.13.4
outlander-syntax, v1.0.3
pigments, v0.15.0
save-session, v0.15.7
tool-bar, v0.1.9

# Dev
No dev packages
```

**Comment by rohanray** [comment]
Facing same issue:
Steps executed:

1. Split the panes
2. Move an editor between split panes

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.7.0


### Stack Trace

Uncaught Error: Tried to create a gutter with a name that is already in use.

```
At C:\Users\roray\AppData\Local\atom\app-1.0.19\resources\app.asar\src\gutter-container.js:36

Error: Tried to create a gutter with a name that is already in use.
  at GutterContainer.module.exports.GutterContainer.addGutter (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\src\gutter-container.js:36:15)
  at TextEditor.module.exports.TextEditor.addGutter (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\src\text-editor.js:2613:35)
  at EditorLinter.addGutter (C:\Users\rohan\.atom\packages\linter\lib\editor-linter.js:106:33)
  at EditorLinter.handleGutter (C:\Users\rohan\.atom\packages\linter\lib\editor-linter.js:99:14)
  at C:\Users\rohan\.atom\packages\linter\lib\editor-linter.js:50:13
  at Config.module.exports.Config.observeKeyPath (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\src\config.js:568:7)
  at Config.module.exports.Config.observe (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\src\config.js:135:21)
  at new EditorLinter (C:\Users\rohan\.atom\packages\linter\lib\editor-linter.js:48:40)
  at EditorRegistry.create (C:\Users\rohan\.atom\packages\linter\lib\editor-registry.coffee:13:24)
  at Linter.createEditorLinter (C:\Users\rohan\.atom\packages\linter\lib\linter.coffee:80:29)
  at C:\Users\rohan\.atom\packages\linter\lib\linter.coffee:36:71
  at C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\src\workspace.js:281:16
  at C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\src\workspace.js:342:18
  at Emitter.module.exports.Emitter.emit (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane-container.js:352:27)
  at C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane-container.js:339:26
  at Emitter.module.exports.Emitter.emit (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane.js:345:20)
  at Pane.module.exports.Pane.moveItemToPane (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane.js:439:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:706:20)
  at TabBarView.module.exports.TabBarView.onDrop (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:632:23)
  at space-pen-ul.<anonymous> (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -0:29.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:27.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:27.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:27.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:27.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:23.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:17.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:16.5.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:15.9.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:15.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:15 core:paste (atom-text-editor.editor.is-focused)
     -0:14.4.0 core:undo (atom-text-editor.editor.is-focused)
     -0:10.8.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:10.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:07.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:06.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "destroyEmptyPanes": false
  },
  "linter": {
    "showErrorTabFile": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
atom-handlebars, v1.2.0
atom-jshint, v2.0.0
color-tabs, v0.1.8
css-color-underline, v1.0.1
file-types, v0.5.1
jshint, v1.8.0
language-spacebars, v0.2.2
linter, v1.7.0
linter-handlebars, v2.1.0
meteor-api, v2.20.0
webbox-color, v0.5.8

# Dev
No dev packages
```

**Comment by jadatkins** [comment]
Aargh. I can't drag anything between panes anymore. Help!

**Atom Version**: 1.0.2
**System**: Debian GNU/Linux
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.7.0


### Stack Trace

Uncaught Error: Tried to create a gutter with a name that is already in use.

```
At /usr/share/atom/resources/app.asar/src/gutter-container.js:28

Error: Tried to create a gutter with a name that is already in use.
    at GutterContainer.module.exports.GutterContainer.addGutter (/usr/share/atom/resources/app.asar/src/gutter-container.js:28:15)
    at TextEditor.module.exports.TextEditor.addGutter (/usr/share/atom/resources/app.asar/src/text-editor.js:493:35)
    at EditorLinter.addGutter (/home/alexander/.atom/packages/linter/lib/editor-linter.js:106:33)
    at EditorLinter.handleGutter (/home/alexander/.atom/packages/linter/lib/editor-linter.js:99:14)
    at /home/alexander/.atom/packages/linter/lib/editor-linter.js:50:13
    at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app.asar/src/config.js:555:7)
    at Config.module.exports.Config.observe (/usr/share/atom/resources/app.asar/src/config.js:135:21)
    at new EditorLinter (/home/alexander/.atom/packages/linter/lib/editor-linter.js:48:40)
    at EditorRegistry.create (/home/alexander/.atom/packages/linter/lib/editor-registry.coffee:19:22)
    at Linter.createEditorLinter (/home/alexander/.atom/packages/linter/lib/linter.coffee:119:35)
```

### Commands

```
     -2:36.8.0 core:paste (atom-text-editor.editor.is-focused)
     -2:36.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:35.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:35 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -2:34.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:32.1.0 project-find:show (atom-text-editor.editor.is-focused)
     -0:31.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:29.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:17.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:17.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:16.2.0 core:undo (atom-text-editor.editor.is-focused)
     -0:15.6.0 project-find:show (atom-text-editor.editor.is-focused)
     -0:14.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:13.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:07.9.0 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "linter": {
    "showErrorTabLine": true,
    "statusIconScope": "File"
  }
}
```

### Installed Packages

```coffee
# User
docblockr, v0.7.3
linter, v1.7.0
linter-jshint, v1.2.0
linter-pep257, v0.3.1
linter-pep8, v1.0.1
linter-php, v1.0.4
linter-phpcs, v1.1.3
linter-pylint, v1.0.1
monokai, v0.18.0

# Dev
No dev packages
```

**Comment by despairblue** [comment]
The editors are actually moved to the new pane:
![screenshot from 2015-10-01 17-52-41](https://cloud.githubusercontent.com/assets/927609/10225926/4c6f42ca-6865-11e5-957f-b4f6ef19600b.png)

I have 4 editors open in the right pane. Try to use `ctrl-page-up` to cycle between open editors. The editors just don't show up in the tab bar.

**Comment by steelbrain** [comment]
Requesting your :eyes: @nathansobo

**Comment by jonathanong** [comment]
:+1:

**Comment by nathansobo** [comment]
Will take a look tomorrow.

**Comment by superlou** [comment]
:+1: Same issue on Linux x64, Atom 1.0.19.

**Comment by Palmer11** [comment]
Same issue on Ubuntu 14.04 x64, Atom 1.0.19.

**Comment by caedes** [comment]
:+1: 

Stack trace:
```
Error: Tried to create a gutter with a name that is already in use.
  at GutterContainer.module.exports.GutterContainer.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:36:15)
  at TextEditor.module.exports.TextEditor.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2613:35)
  at EditorLinter.addGutter (/Users/romain/Dropbox/Atom/.atom/packages/linter/lib/editor-linter.js:106:33)
  at EditorLinter.handleGutter (/Users/romain/Dropbox/Atom/.atom/packages/linter/lib/editor-linter.js:99:14)
  at /Users/romain/Dropbox/Atom/.atom/packages/linter/lib/editor-linter.js:50:13
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
  at new EditorLinter (/Users/romain/Dropbox/Atom/.atom/packages/linter/lib/editor-linter.js:48:40)
  at EditorRegistry.create (/Users/romain/Dropbox/Atom/.atom/packages/linter/lib/editor-registry.coffee:13:24)
  at Linter.createEditorLinter (/Users/romain/Dropbox/Atom/.atom/packages/linter/lib/linter.coffee:80:29)
  at /Users/romain/Dropbox/Atom/.atom/packages/linter/lib/linter.coffee:36:71
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:281:16
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:342:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:352:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:339:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:345:20)
  at Pane.module.exports.Pane.moveItemToPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:439:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:706:20)
  at TabBarView.module.exports.TabBarView.onDrop (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:632:23)
  at space-pen-ul.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
  ```

**Comment by josh-egan** [comment]
I'm getting this error too. If I move a tab from one pane to the other, the tab does not appear in either pane. However, after restarting atom, the tab appears in the pane that it was moved to.

Atom Version: 1.0.19
System: Windows 8.1 Pro
Thrown from: [linter](https://github.com/atom-community/linter) version 1.8.0

```
Uncaught Error: Tried to create a gutter with a name that is already in use.

C:\Users\ps-dev\AppData\Local\atom\app-1.0.19\resources\app.asar\src\gutter-container.js:36

Error: Tried to create a gutter with a name that is already in use.
    at GutterContainer.module.exports.GutterContainer.addGutter (C:\Users\ps-dev\AppData\Local\atom\app-1.0.19\resources\app.asar\src\gutter-container.js:36:15)
    at TextEditor.module.exports.TextEditor.addGutter (C:\Users\ps-dev\AppData\Local\atom\app-1.0.19\resources\app.asar\src\text-editor.js:2613:35)
    at EditorLinter.addGutter (C:/Users/ps-dev/.atom/packages/linter/lib/editor-linter.js:87:31)
    at EditorLinter.handleGutter (C:/Users/ps-dev/.atom/packages/linter/lib/editor-linter.js:81:12)
    at C:/Users/ps-dev/.atom/packages/linter/lib/editor-linter.js:34:12
    at Config.module.exports.Config.observeKeyPath (C:\Users\ps-dev\AppData\Local\atom\app-1.0.19\resources\app.asar\src\config.js:568:7)
    at Config.module.exports.Config.observe (C:\Users\ps-dev\AppData\Local\atom\app-1.0.19\resources\app.asar\src\config.js:135:21)
    at new EditorLinter (C:/Users/ps-dev/.atom/packages/linter/lib/editor-linter.js:32:40)
    at EditorRegistry.create (C:\Users\ps-dev\.atom\packages\linter\lib\editor-registry.coffee:13:24)
    at Linter.createEditorLinter (C:\Users\ps-dev\.atom\packages\linter\lib\linter.coffee:80:29)
    at C:\Users\ps-dev\.atom\packages\linter\lib\linter.coffee:36:71
    at C:\Users\ps-dev\AppData\Local\atom\app-1.0.19\resources\app.asar\src\workspace.js:281:16
    at C:\Users\ps-dev\AppData\Local\atom\app-1.0.19\resources\app.asar\src\workspace.js:342:18
    at Emitter.module.exports.Emitter.emit (C:\Users\ps-dev\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (C:\Users\ps-dev\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane-container.js:352:27)
    at C:\Users\ps-dev\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane-container.js:339:26

```

The error was thrown from the linter package. This issue has [already been reported](https://github.com/atom-community/linter/issues/913).

**Comment by shaungrady** [comment]
:cry: 

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11


### Stack Trace

Uncaught Error: Tried to create a gutter with a name that is already in use.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:36

Error: Tried to create a gutter with a name that is already in use.
  at GutterContainer.module.exports.GutterContainer.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:36:15)
  at TextEditor.module.exports.TextEditor.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2613:35)
  at EditorLinter.addGutter (/Users/shaun/.atom/packages/linter/lib/editor-linter.js:106:33)
  at EditorLinter.handleGutter (/Users/shaun/.atom/packages/linter/lib/editor-linter.js:99:14)
  at /Users/shaun/.atom/packages/linter/lib/editor-linter.js:50:13
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
  at new EditorLinter (/Users/shaun/.atom/packages/linter/lib/editor-linter.js:48:40)
  at EditorRegistry.create (/Users/shaun/.atom/packages/linter/lib/editor-registry.coffee:13:24)
  at Linter.createEditorLinter (/Users/shaun/.atom/packages/linter/lib/linter.coffee:80:29)
  at /Users/shaun/.atom/packages/linter/lib/linter.coffee:36:71
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:281:16
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:342:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:352:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:339:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:345:20)
  at Pane.module.exports.Pane.moveItemToPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:439:19)
  at atom-pane.commands.(anonymous function) (/Users/shaun/.atom/packages/pain-split/lib/pain-split.coffee:31:25)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

**Comment by nathansobo** [comment]
This is caused by us invoking `onDidAddPaneItem` observers redundantly when moving between panes. I'm fixing this on master, but it's going to be a while before it makes it to release. For now @steelbrain, as a workaround, you should keep a `WeakSet` of editors you've already added your gutter to to prevent it from happening redundantly. Once my fix is out you'll be able to remove the workaround.

**Comment by steelbrain** [comment]
@nathansobo Thanks for the pointer! I have a fix up locally, pushing it in a few minutes.

**Comment by multiplegeorges** [comment]
IMO, this warrants a bugfix release as this is a core piece of functionality that really impacts use of Atom.
Any idea what "a while" means, @nathansobo ?

Anyway, glad to see that this bug has been fixed. Thanks for taking a look and resolving this.

**Comment by francoiscote** [comment]
FYI, you can updater linter to v1.8.1. They implemented a workaround that circumvents this bug. But maybe you have other plugin that suffers from this.

**Comment by multiplegeorges** [comment]
@francoiscote eh, you are correct. Thanks for the info!
A restart of Atom is required to clear the error after updating to 1.8.1.

**Comment by Palmer11** [comment]
@multiplegeorges - You can also just reload (Ctl+Alt+R) and it should be fixed. (For the ones that don't want to lose precious seconds.)

**Comment by dkro** [comment]
Confirmed that v1.8.1 linter with a restart of Atom fixes this issue.
