### ISSUE TITLE
Failed to activate the remember-session package

### ISSUE THREAD

**Issue by ilewis** [atom/atom#9018]
[Enter steps to reproduce below:]

1. All I did was open Atom

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the remember-session package

```
At $ is not a function

TypeError: $ is not a function
    at attachListeners (<anonymous>:19:3)
    at Object.module.exports.activate (<anonymous>:5:5)
    at Package.module.exports.Package.activateNow (/Users/ilewis/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
    at /Users/ilewis/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:226:30
    at Package.module.exports.Package.measure (/Users/ilewis/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:169:15)
    at Package.module.exports.Package.activate (/Users/ilewis/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:218:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/ilewis/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
    at /Users/ilewis/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:469:29
    at Config.module.exports.Config.transact (/Users/ilewis/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:324:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/ilewis/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:464:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "snippets"
    ],
    "themes": [
      "proton",
      "ya-railscasts-syntax"
    ]
  },
  "editor": {
    "fontSize": 13,
    "tabLength": 4,
    "invisibles": {},
    "autoIndentOnPaste": false,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-color-highlight, v3.0.8
color-picker, v2.0.12
file-icons, v1.6.9
highlight-selected, v0.10.1
linter-rubocop, v0.4.4
proton, v4.0.2
remember-session, v0.5.1
symbol-gen, v1.0.0
ya-railscasts-syntax, v0.6.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
You should disable remember-session. Note the enormous heading in the repo: https://github.com/hampustagerud/atom-remember-session
