### ISSUE TITLE
Failed to activate the show-in-folder package

### ISSUE THREAD

**Issue by Fernando9** [atom/atom#9025]
[Enter steps to reproduce below:]

1. Close the folder tab and exit atom
2. Open atom again. 

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the show-in-folder package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:5:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:226:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:169:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:469:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:324:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:464:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".pyc",
      ".un~"
    ],
    "disabledPackages": [
      "jslint"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "fontSize": 15,
    "showInvisibles": true,
    "showIndentGuide": true,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.5.4
linter, v0.12.0
minimap, v4.7.6
seti-syntax, v0.3.3
seti-ui, v0.6.3
show-in-folder, v0.1.0

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
Duplicate of https://github.com/Flynsarmy/atom-show-in-folder/issues/4.

The package seems abandoned since there has been no activity since March 2014, in addition it looks as if it's been completely removed from the package directory; see https://atom.io/packages/show-in-folder, it's also not showing up in any searches.
