### ISSUE TITLE
Failed to load the max-tabs package

### ISSUE THREAD

**Issue by benjamine** [atom/atom#9030]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to load the max-tabs package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "ide-flow"
    ],
    "projectHome": "/Users/benja/proj"
  },
  "editor": {
    "useShadowDOM": true,
    "invisibles": {},
    "softTabs": false,
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
cucumber, v0.5.0
editor-stats, v0.17.0
file-icons, v1.6.9
highlight-selected, v0.10.1
language-gherkin, v1.0.3
language-jade, v0.6.2
language-nginx, v0.6.0
linter, v1.7.2
linter-flow, v3.1.3
linter-jscs, v3.0.0
linter-jshint, v1.2.1
linter-less, v2.1.0
max-tabs, v0.3.1
minimap, v4.13.4
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
node-debugger, v1.1.8
svg-preview, v0.6.1
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This package is deprecated.  Please use the [tidy-tabs](https://atom.io/packages/tidy-tabs) package instead.

**Comment by benjamine** [comment]
got it thx
