### ISSUE TITLE
Change event warning and EBUSY error when saving file

### ISSUE THREAD

**Issue by bellmg** [atom/atom#9031]
1. Open file from OneDrive folder
2. Edit file
3. Save file with Ctrl+S
4. Wait few seconds, get warning (Unable to read file after file change event), and then get error (EBUSY)

Note: Repeatable, has happened several times.

**Atom Version**: 1.0.19
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EBUSY: resource busy or locked, open 'C:\Users\bellmg\OneDrive - xxx\Task Management\Action Items\xxx.txt'

```
At C:\Users\bellmg\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:128

Error: EBUSY: resource busy or locked, open 'C:\Users\bellmg\OneDrive - xxx\Task Management\Action Items\xxx.txt'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.readFileSync (fs.js:397:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:384:29)
  at File.module.exports.File.readSync (C:\Users\bellmg\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:261:36)
  at TextBuffer.module.exports.TextBuffer.updateCachedDiskContentsSync (C:\Users\bellmg\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1072:85)
  at C:\Users\bellmg\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1213:17
  at Emitter.module.exports.Emitter.emit (C:\Users\bellmg\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\bellmg\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:447:40
  at _fulfilled (C:\Users\bellmg\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:794:54)
  at self.promiseDispatch.done (C:\Users\bellmg\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:823:30)
  at Promise.promise.promiseDispatch (C:\Users\bellmg\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:756:13)
  at C:\Users\bellmg\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:564:44
  at flush (C:\Users\bellmg\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:110:17)
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabType": "soft"
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
json-schema, v0.1.15
linter, v1.7.2
omnisharp-atom, v0.24.14

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @bellmg, can you please try to reproduce this in safe mode (`atom --safe`)?  Thanks.

**Comment by bellmg** [comment]
Starting atom from command line with 'atom --safe' did not stop the error from happening.

I did notice that when I tried to save a new file for first time, when the 'Save File' dialog opens I get an open file warning "You can't open this location using this program. Please try a different location."
After clicking ok, I can still save the file. A few seconds after that I get the 'Unable to read file after file change event' warning, and the EBUSY error. I also noticed that after saving a file quite a few times the error stopped happening?

I can open and save the files in Notepad++ and windows text pad without issue.

**Comment by 50Wliu** [comment]
@AskYous reported in #9163 that this also happens with Visual Studio.

**Comment by tmazur** [comment]
I also experienced this issue. The trigger in my case is when I have a file open in Atom that is changed during my build process (the build process is triggered outside of Atom). When I edit the file manually in another editor there are no problems.

**Comment by spiff72** [comment]
I get the same issue here, under Windows 7 Enterprise.  The error only occurs after saving a file opened from anywhere in my OneDrive folder structure, but it only seems to happen once.  For example, if I open a file, make a change, save it (error appears), and then make another change and save there is no error.  If I close that file, and then re-open it, edit, then save the error occurs again, but won't occur again until I close/reopen the file again.

Error doesn't occur when opening/saving files from outside my OneDrive folder.  (Google drive folder works fine).

**Comment by maxkoryukov** [comment]
Windows 7 x86
Atom 1.4.0 **from the box**, just installed, no additional packages

Steps to reproduce:
1. Open `AssemblyInfo.cs` (no matter, what is the filename) in Atom
2. Copy and replace file using explorer on the disk
3. Get this error
4. Cry :sob:

Seems like Atom don't want to be a file monitor for me. Sad...

**Comment by damieng** [comment]
Would be solved by https://github.com/atom/atom/issues/7659 so tracking it there.
