### ISSUE TITLE
Failed to load the merge-conflicts package

### ISSUE THREAD

**Issue by afreidz** [atom/atom#9063]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0-dev-360d667
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to load the merge-conflicts package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:6:3
    at Object.<anonymous> (<anonymous>:6:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "blackboard-dark-mod"
    ],
    "projectHome": "/Users/xaxf036/code"
  },
  "editor": {
    "fontFamily": "Monaco",
    "fontSize": 19,
    "showInvisibles": true,
    "showIndentGuide": true,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
blackboard-dark-mod, v0.2.0
file-icons, v1.4.4
merge-conflicts, v1.2.8

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
Try upgrading to the latest version of the `merge-conflicts` package.

```
apm update merge-conflicts
```

If the problem persists, could you open the issue on [the package's repo](https://github.com/smashwilson/merge-conflicts)?
