### ISSUE TITLE
Failed to activate the search package

### ISSUE THREAD

**Issue by raddevon** [atom/atom#9065]
I get this error every time I start Atom.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the search package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:19:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:226:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:169:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:469:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:324:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:464:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".hg"
    ],
    "disabledPackages": [
      "save-session"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-handlebars, v1.2.0
auto-update-packages, v1.0.0
autocomplete-paths, v1.0.2
color-picker, v2.0.13
compass, v0.9.1
emmet, v2.3.13
highlight-line, v0.11.0
javascript-snippets, v1.0.0
language-spacebars, v0.2.2
linter, v1.8.1
linter-coffeelint, v1.1.0
linter-csslint, v1.0.7
linter-haml, v1.0.0
linter-handlebars, v2.1.0
linter-htmlhint, v0.1.1
linter-jshint, v1.2.1
linter-php, v1.0.5
meteor-api, v2.20.0
minimap, v4.13.4
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
pigments, v0.15.0
project-manager, v2.6.1
run-in-terminal, v0.4.2
search, v0.5.0
set-syntax, v0.3.0
seti-syntax, v0.4.0
seti-ui, v0.8.0
tab-smart-sort, v0.1.4
travis-ci-status, v0.18.0
vim-mode, v0.60.0
white-cursor, v0.6.0
wordpress, v0.2.0
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
Looks like the `search` package doesn't work on the latest version of Atom.

```
apm remove search
```
