### ISSUE TITLE
Uncaught TypeError when fold section button clicked in .coffee file

### ISSUE THREAD

**Issue by giyyapan** [atom/atom#9081]
I've seen a [issue](https://github.com/smashwilson/merge-conflicts/issues/98) which has similar stack trace, but this one can be different.
### Step to reproduce:
1. open a .coffee file
2. click one of the fold button (on the left of edit panel, right to line number, only visible when mouse hover). This may cause the bug.
3. if bug didn't appear, try another fold button.

The bug dosn't appear every time, event when I click the same button. 
If you click one fold button for many times repidly, the bug appears to.

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.3
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

```
At /usr/share/atom/resources/app.asar/src/decoration.js:62

TypeError: Cannot read property 'onDidDestroy' of undefined
  at new Decoration (/usr/share/atom/resources/app.asar/src/decoration.js:62:49)
  at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/usr/share/atom/resources/app.asar/src/display-buffer.js:1319:20)
  at DisplayBuffer.module.exports.DisplayBuffer.decorateFold (/usr/share/atom/resources/app.asar/src/display-buffer.js:1720:19)
  at DisplayBuffer.module.exports.DisplayBuffer.handleBufferMarkerCreated (/usr/share/atom/resources/app.asar/src/display-buffer.js:1709:14)
  at /usr/share/atom/resources/app.asar/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.markerCreated (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1354:20)
  at MarkerStore.module.exports.MarkerStore.createMarker (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-store.js:332:21)
  at MarkerStore.module.exports.MarkerStore.markRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-store.js:149:19)
  at TextBuffer.module.exports.TextBuffer.markRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:695:31)
  at DisplayBuffer.module.exports.DisplayBuffer.createFold (/usr/share/atom/resources/app.asar/src/display-buffer.js:843:95)
  at TextEditor.module.exports.TextEditor.createFold (/usr/share/atom/resources/app.asar/src/text-editor.js:2571:33)
  at LanguageMode.module.exports.LanguageMode.foldBufferRow (/usr/share/atom/resources/app.asar/src/language-mode.js:148:30)
  at TextEditor.module.exports.TextEditor.foldBufferRow (/usr/share/atom/resources/app.asar/src/text-editor.js:2511:32)
  at LineNumberGutterComponent.module.exports.LineNumberGutterComponent.onClick (/usr/share/atom/resources/app.asar/src/line-number-gutter-component.js:137:30)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/src/line-number-gutter-component.js:3:61)

```
### Commands

```
     -1:28.8.0 editor:move-to-beginning-of-line (atom-text-editor.editor.emacs-plus.is-focused)
     -1:28.7.0 atomic-emacs:next-line (atom-text-editor.editor.emacs-plus.is-focused)
  2x -1:28.5.0 atomic-emacs:previous-line (atom-text-editor.editor.emacs-plus.is-focused)
     -1:28.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.emacs-plus.is-focused)
  2x -1:28.2.0 atomic-emacs:previous-line (atom-text-editor.editor.emacs-plus.is-focused)
     -1:27.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.emacs-plus.is-focused)
     -1:27.7.0 atomic-emacs:backward-char (atom-text-editor.editor.emacs-plus.is-focused)
     -1:27.4.0 atomic-emacs:next-line (atom-text-editor.editor.emacs-plus.is-focused)
     -1:27.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.emacs-plus.is-focused)
  2x -1:27.1.0 atomic-emacs:backward-char (atom-text-editor.editor.emacs-plus.is-focused)
  4x -1:25.7.0 editor:select-word (atom-text-editor.editor.emacs-plus.is-focused)
     -1:24.6.0 editor:consolidate-selections (atom-text-editor.editor.emacs-plus.is-focused.mark-mode)
     -1:24.6.0 core:cancel (atom-text-editor.editor.emacs-plus.is-focused.mark-mode)
     -1:24.4.0 editor:move-to-beginning-of-line (atom-text-editor.editor.emacs-plus.is-focused)
  3x -1:24.4.0 atomic-emacs:next-line (atom-text-editor.editor.emacs-plus.is-focused)
     -1:23.3.0 atomic-emacs:previous-line (atom-text-editor.editor.emacs-plus.is-focused)
```
### Config

``` json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "remote-edit"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "Remote-FTP"
    ]
  },
  "editor": {
    "invisibles": {},
    "backUpBeforeSaving": true
  }
}
```
### Installed Packages

``` coffee
# User
atomic-emacs, v0.7.4
coffee-compile, v0.19.0
emacs-plus, v0.9.8
less-autocompile, v1.0.0
minimap, v4.13.4
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-hide, v0.3.0
minimap-linter, v1.0.0
remote-edit, v1.8.21
symbol-gen, v1.0.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by giyyapan** [comment]
Let me know if there's more information I can provide :smile:

**Comment by izuzak** [comment]
Thanks for the report, @giyyapan, but I'm having trouble reproducing this. Have you been able to reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

Still, seems like something Atom should be handling better. /cc @nathansobo @maxbrunsfeld

**Comment by giyyapan** [comment]
No, I can't reproduce this in safe mode.

**Comment by giyyapan** [comment]
@izuzak I've been tested this for a while, and my current conclusion is this bug only appear when both package [atomic/emacs](https://github.com/avendael/atomic-emacs) and [aki77/atom-emacs-plus](https://github.com/aki77/atom-emacs-plus) enabled.
Well, to be honest, I'm not 100% sure about this, for this bug is really hard to trigger sometime. but I did my best to find some pattern out there, and I'm going to double check this conclusion.
Hope this helps :smiley_cat:

**Comment by giyyapan** [comment]
Ahh!  
Update: [aki77/atom-emacs-plus](https://github.com/aki77/atom-emacs-plus) is the key. The bug only appear when it's enabled.

**Comment by izuzak** [comment]
Thanks for helping investigate this, @giyyapan. :sparkle: I'm going to keep this open so that @nathansobo and @maxbrunsfeld can take a look and see if there's anything we should do about this in Atom core.

**Comment by giyyapan** [comment]
I guess I should close this for it's not appearing (for a long time!)
