### ISSUE TITLE
Update.exe error when installing

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [atom/atom#9094]
I have downloaded `AtomSetup.exe` from the homepage but it fails to load on Windows 7 x64.

Below is the data on `eventvwr.msc`:

```
Log Name:      Application
Source:        Application Error
Date:          08/10/2015 21:05:56
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Homer-PC
Description:
Faulting application name: Update.exe_Update, version: 1.0.2.0, time stamp: 0x55ef6439
Faulting module name: KERNELBASE.dll, version: 6.1.7601.18869, time stamp: 0x556363bc
Exception code: 0xe0434352
Fault offset: 0x0000c42d
Faulting process id: 0xae0
Faulting application start time: 0x01d1022641581655
Faulting application path: C:\Users\Homer\AppData\Local\SquirrelTemp\Update.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 832b3c3f-6e19-11e5-a580-0026367a4f2d
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-10-09T00:05:56.000000000Z" />
    <EventRecordID>96730</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Homer-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Update.exe_Update</Data>
    <Data>1.0.2.0</Data>
    <Data>55ef6439</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.1.7601.18869</Data>
    <Data>556363bc</Data>
    <Data>e0434352</Data>
    <Data>0000c42d</Data>
    <Data>ae0</Data>
    <Data>01d1022641581655</Data>
    <Data>C:\Users\Homer\AppData\Local\SquirrelTemp\Update.exe</Data>
    <Data>C:\Windows\syswow64\KERNELBASE.dll</Data>
    <Data>832b3c3f-6e19-11e5-a580-0026367a4f2d</Data>
  </EventData>
</Event>
```

```
Log Name:      Application
Source:        .NET Runtime
Date:          08/10/2015 21:05:55
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Homer-PC
Description:
Application: Update.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
Stack:
   at System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef)
   at System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance(System.Type, Boolean)
   at System.Activator.CreateInstance(System.Type)
   at System.Windows.Window.ApplyTaskbarItemInfo()
   at System.Windows.Window.WindowFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Squirrel.Update.AnimatedGifWindow+<>c__DisplayClass8.<ShowWindow>b__1()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-10-09T00:05:55.000000000Z" />
    <EventRecordID>96729</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Homer-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Update.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
Stack:
   at System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef)
   at System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance(System.Type, Boolean)
   at System.Activator.CreateInstance(System.Type)
   at System.Windows.Window.ApplyTaskbarItemInfo()
   at System.Windows.Window.WindowFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Squirrel.Update.AnimatedGifWindow+&lt;&gt;c__DisplayClass8.&lt;ShowWindow&gt;b__1()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
</Data>
  </EventData>
</Event>
```

I have no clue of what is going on.

![image](https://cloud.githubusercontent.com/assets/835857/10383118/787b2a72-6e01-11e5-98ea-b7cdd9089b97.png)

![image](https://cloud.githubusercontent.com/assets/835857/10383124/834aed16-6e01-11e5-873c-9164fe77b1d2.png)

*Note: when I click "Open Setup Log" it open an empty "SquirrelSetup.log"*

**Comment by paulcbetts** [comment]
Huh, that's a new one. This looks like a weirdo error condition that a lot of C# applications get into: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=COMException+System.Windows.Window.ApplyTaskbarItemInfo().  

We're trying to create a COM object that Explorer guarantees should exist on Win7+ and it's failing for some reason. You can try repairing / reinstalling the .NET Framework, and if that doesn't work, all I can suggest is to reinstall the OS :(

**Comment by FagnerMartinsBrack** [comment]
> all I can suggest is to reinstall the OS

Wow that's harsh! :D

Which .NET version you believe might fix this problem? I can try reinstalling it.
I am also available for any investigation in case you guys want to get to the bottom of this.

**Comment by paulcbetts** [comment]
@FagnerMartinsBrack Just install the latest one, https://www.microsoft.com/en-us/download/details.aspx?id=48130

**Comment by FagnerMartinsBrack** [comment]
I installed the latest `Microsoft .NET Framework 4.6 (Web Installer) for Windows Vista SP2, Windows 7 SP1, Windows 8, Windows 8.1, Windows Server 2008 SP2 Windows Server 2008 R2 SP1, Windows Server 2012 and Windows Server 2012 R2`, but `AtomSetup.exe` still fails.

**Comment by damieng** [comment]
Hi @FagnerMartinsBrack are you still getting this issue? I've not been able to reproduce on my VM with Windows 7.

**Comment by FagnerMartinsBrack** [comment]
I moved to another country and I am using Mac now. This is those kind of problems that cannot be consistently reproduced, but given enough details and stracktraces it might be possible to look for the root cause and potential incompatibilities so that the system can become **more robust**.

I tried to get most information I could from the error messages and logs. If you guys can't find the problem through the informations I posted, I can try to reproduce this again in my notebook when I get home, although the changes in entropy due to high usage and changes since the time this problem occurred could make it hard to be reproduced again.

**Comment by damieng** [comment]
Yeah, totally understand. Given nobody else seems to have reported this issue I wouldn't spend too much time on it - if it happens elsewhere I'm sure it will be re-opened or a new bug will be filed.

**Comment by FagnerMartinsBrack** [comment]
@damieng 

When you say that nobody else reported this issue, what are the key points that you are comparing? General errors on `Update.exe`or the specific stacktrace?

**Comment by damieng** [comment]
Specifically the CreateInstance COM Exception crash from within .NETs ApplyTaskbarItemInfo.  

There are other update.exe errors we're still investigating.

**Comment by FagnerMartinsBrack** [comment]
Do you think it's worth keeping this open? I am totally up to do anything to help debug this in case I am able to reproduce it again.

**Comment by damieng** [comment]
I don't think it's worth keeping open unless we see this specific error again. It looks like even Microsoft aren't too sure why their component fails there and any kind of mitigation we'd have to do would be a workaround.

**Comment by FagnerMartinsBrack** [comment]
Ok :+1:
