### ISSUE TITLE
Failed to activate the pigments package

### ISSUE THREAD

**Issue by dreesor** [atom/atom#9099]
[Enter steps to reproduce below:]

1. Just start atom and there is an error that pigments failed to activate.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the pigments package

```
At this.editorElement.onDidChangeScrollLeft is not a function

TypeError: this.editorElement.onDidChangeScrollLeft is not a function
    at pigments-markers.ColorBufferElement.setModel (<anonymous>:44:39)
    at Object.createView (<anonymous>:207:13)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:80:72)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:65:21)
    at <anonymous>:252:36
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:276:9)
    at ColorProject.module.exports.ColorProject.initializeBuffers (<anonymous>:249:39)
    at new ColorProject (<anonymous>:144:6)
    at Function.module.exports.ColorProject.deserialize (<anonymous>:104:9)
    at DeserializerManager.module.exports.DeserializerManager.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/src/deserializer-manager.js:42:29)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "fontSize": 16,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
api-blueprint-preview, v0.6.0
language-chef, v0.7.0
minimap, v4.13.4
monokai, v0.18.0
pigments, v0.16.1

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
Please update pigments to v0.16.3. @abe33 fixed this problem in that release.

**Comment by dreesor** [comment]
Thanks.

Interesting that atom claimes the pakcages are up to date but i don't have
.16.3

Thanks again, ill get the new version installed.
