### ISSUE TITLE
Uncaught TypeError: dialog.showSaveDialog is not a function

### ISSUE THREAD

**Issue by AlcaDesign** [atom/atom#9107]
Steps to reproduce:
1. Create a new file
2. Attempt to save it

**Atom Version**: 1.0.19
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: dialog.showSaveDialog is not a function

```
At C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\src\atom.js:939

TypeError: dialog.showSaveDialog is not a function
    at Atom.module.exports.Atom.showSaveDialogSync (C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\src\atom.js:939:21)
    at Pane.module.exports.Pane.saveItemAs (C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane.js:568:26)
    at Pane.module.exports.Pane.saveActiveItemAs (C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane.js:534:19)
    at Workspace.module.exports.Workspace.saveActivePaneItemAs (C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\src\workspace.js:613:35)
    at atom-workspace.atom.commands.add.core:save-as (C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\src\workspace-element.js:296:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
    at C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:184:20)
```

### Commands

```
     -6:35.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:14 core:save (atom-text-editor.editor.is-focused)
     -0:13.2.0 core:save-as (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "softTabs": false,
    "tabLength": 4,
    "autoIndentOnPaste": false
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.6.2
atom-minify, v0.4.2
autocomplete-modules, v1.3.0
language-javascript-better, v1.7.1
language-svg, v0.9.0
linter, v1.8.1
linter-jshint, v1.2.1
minimap, v4.13.4
minimap-selection, v4.3.1
sass-autocompile, v0.10.3

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @AlcaDesign, can you try to reproduce this in safe mode (`atom --safe`)?  Thanks.

**Comment by AlcaDesign** [comment]
Yes, `atom --safe` and repeating the steps still causes the error

**Comment by AlcaDesign** [comment]
Also, no dialogs at all work.

**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.84.0


### Stack Trace

Uncaught TypeError: dialog.showMessageBox is not a function

```
At C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\src\atom.js:757

TypeError: dialog.showMessageBox is not a function
    at Atom.module.exports.Atom.confirm (C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\src\atom.js:757:23)
    at Pane.module.exports.Pane.promptToSaveItem (C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane.js:512:21)
    at Pane.module.exports.Pane.destroyItem (C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane.js:465:18)
    at tabs-tab.<anonymous> (C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:216:24)
    at space-pen-ul.jQuery.event.dispatch (C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-ul.elemData.handle (C:\Users\Alca\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

**Comment by tschf** [comment]
My OS is Ubuntu 14.04 x64, Atom version: 1.0.18

I'm getting this error, but it only happens when I launch atom from the terminal. e.g. If I launch through the Unity launcher or alt + f2 and `/usr/share/atom/atom` it doesn't have the issue.

My desktop entry points to: `/usr/share/atom/atom`. 

```ini
[Desktop Entry]
Name=Atom
Comment=A hackable text editor for the 21st Century.
GenericName=Text Editor
Exec=/usr/share/atom/atom %U
<snip>
```

Steps:

1. Open gnome-terminal
2. Type: `/usr/share/atom/atom`
3. On the opened file, go: File -> Save As...

Error recevied at this point (from console output):

```bash
[16841:1025/134934:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[16841:1025/134934:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[16841:1025/134934:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[16841:1025/134934:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[16841:1025/134934:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[16873:1025/134934:INFO:renderer_main.cc(200)] Renderer process started
App load time: 311ms
[16841:1025/134934:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[16841:1025/134934:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[16841:1025/134934:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[16841:1025/134934:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[16841:1025/134935:INFO:CONSOLE(46)] "Window load time: 1068ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (46)
[16841:1025/134951:INFO:CONSOLE(939)] "Uncaught TypeError: dialog.showSaveDialog is not a function", source: /usr/share/atom/resources/app.asar/src/atom.js (939)
```

As well as receiving the red error in Atom itself. 

![screenshot from 2015-10-25 13 52 13](https://cloud.githubusercontent.com/assets/1747643/10713815/a6310786-7b1f-11e5-966a-74b8a61ca64c.png)

Full stack trace:

```
TypeError: dialog.showSaveDialog is not a function
    at Atom.module.exports.Atom.showSaveDialogSync (/usr/share/atom/resources/app.asar/src/atom.js:939:21)
    at Pane.module.exports.Pane.saveItemAs (/usr/share/atom/resources/app.asar/src/pane.js:568:26)
    at Pane.module.exports.Pane.saveActiveItemAs (/usr/share/atom/resources/app.asar/src/pane.js:534:19)
    at Workspace.module.exports.Workspace.saveActivePaneItemAs (/usr/share/atom/resources/app.asar/src/workspace.js:613:35)
    at atom-workspace.atom.commands.add.core:save-as (/usr/share/atom/resources/app.asar/src/workspace-element.js:296:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:145:19)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:70:30)
    at emitOne (events.js:77:13)
```

**Comment by 50Wliu** [comment]
No new reports, tentatively assuming fixed.
