### ISSUE TITLE
Atom is using around 300% of my CPU 

### ISSUE THREAD

**Issue by mvaneijgen** [atom/atom#9112]
When I open Atom after a few seconds my MacBook Pro (13-inch, Late 2011) is becoming a helicopter  and when I check activity monitor it looks something like this

![activity monitor](http://i.imgur.com/61QvDHH.jpg)

When I start atom with `atom --safe` there is only one `atom helper` but that one is still using `160%`

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:809

TypeError: Cannot read property 'getTokenIterator' of undefined
    at LanguageMode.module.exports.LanguageMode.suggestedIndentForTokenizedLineAtBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:300:31)
    at LanguageMode.module.exports.LanguageMode.suggestedIndentForBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:289:19)
    at LanguageMode.module.exports.LanguageMode.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:367:26)
    at LanguageMode.module.exports.LanguageMode.autoIndentBufferRows (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:361:14)
    at TextEditor._results.push._this.(anonymous function) [as autoIndentBufferRows] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/delegato/lib/delegator.js:67:61)
    at /Users/mvaneijgen/.atom/init.coffee:18:12
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1012:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1004:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:584:26)
```

### Commands

```
     -4:04.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:04.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  3x -4:03.5.0 core:select-left (atom-text-editor.editor.is-focused)
     -4:02.1.0 core:select-right (atom-text-editor.editor.is-focused)
     -4:00.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:59.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:59.5.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -3:55.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:53.7.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -3:49.3.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -3:48.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -3:44.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:01.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:01.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 13,
    "lineHeight": 1.4,
    "autoIndent": false
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.3
atom-material-ui, v0.6.0
pigments, v0.12.0
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by izuzak** [comment]
> Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

You already opened an issue for this, so let's discuss that there: https://github.com/atom/atom/issues/9109

> When I open Atom after a few seconds my MacBook Pro (13-inch, Late 2011) is becoming a helicopter and when I check activity monitor it looks something like this

There's already a few issues opened about this, so I recommend adding a comment to one of the existing issues: https://github.com/atom/atom/search?q=cpu+&type=Issues&utf8=%E2%9C%93. Thanks!
