### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by prasannavl** [atom/atom#9133]
**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Enterprise Insider Preview
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.216.0

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-card.js:27

TypeError: Cannot read property 'name' of undefined
  at Function.module.exports.PackageCard.content (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-card.js:27:18)
  at Function.<anonymous> (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:156:31)
  at Function.View.buildHtml (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:123:10)
  at PackageCard.View (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:155:33)
  at new PackageCard (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-card.js:22:48)
  at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:148:28)
  at C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:188:26
  at C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\atom-io-client.js:46:20
  at AtomIoClient.module.exports.AtomIoClient.fetchFromCache (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\atom-io-client.js:144:16)
  at AtomIoClient.module.exports.AtomIoClient.package (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\atom-io-client.js:43:19)
  at PackageDetailView.module.exports.PackageDetailView.fetchPackage (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:180:56)
  at PackageDetailView.module.exports.PackageDetailView.loadPackage (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:171:23)
  at PackageDetailView.module.exports.PackageDetailView.initialize (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:143:19)
  at PackageDetailView.View (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new PackageDetailView (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:38:54)
  at C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\settings-view.js:263:22
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\settings-view.js:268:19)
  at SettingsView.module.exports.SettingsView.showPanel (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\settings-view.js:313:24)
  at space-pen-div.<anonymous> (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-card.js:264:26)
  at space-pen-div.jQuery.event.dispatch (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-div.elemData.handle (C:\Users\PVL\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -2:33.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:32.4.0 core:close (atom-text-editor.editor.is-focused)
  3x -2:26.3.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:23.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:23.2.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -2:23.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:22.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:22.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:22.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:22 core:move-down (atom-text-editor.editor.is-focused)
     -2:21.4.0 core:move-left (atom-text-editor.editor.is-focused)
  4x -2:21.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:20.6.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -2:20.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:46.7.0 settings-view:open (atom-text-editor.editor.is-focused)
  3x -1:41.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-beautify, v0.28.14
atom-html-preview, v0.1.11
atom-ternjs, v0.8.2
atom-typescript, v7.4.1
atom-yeoman, v0.3.15
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
autocomplete-clang, v0.8.7
autocomplete-python, v0.6.2
color-picker, v2.0.13
go-find-references, v1.2.3
go-rename, v0.3.0
highlight-line, v0.11.0
highlight-selected, v0.10.1
javascript-snippets, v1.0.0
jshint, v1.8.0
json-schema, v0.1.15
language-powershell, v2.1.0
language-rust, v0.4.5
linter, v1.8.1
minimap, v4.13.4
node-debugger, v1.1.8
omnisharp-atom, v0.24.16
pigments, v0.17.1
save-session, v0.15.7

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This issue was moved to atom/settings-view#682
