### ISSUE TITLE
Uncaught Error: EBUSY: resource busy or locked, open 'C:\Users\mlgyshan\Workspace\Flexturo\public...

### ISSUE THREAD

**Issue by AskYous** [atom/atom#9163]
1. Run a web application in Visual Studio.
2. Have an HTML file open in Atom (that's part of the running web application).
3. In Visual Studio, right click on the top parent folder of the open HTML file, and click 'Replace <folder name> from Server' (so you would need a production server).
4. Get this error:

![image](http://i.imgur.com/Ev9258d.png)

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EBUSY: resource busy or locked, open 'C:\Users\mlgyshan\Workspace\Flexturo\public\js\admin.js'

```
At C:\Users\mlgyshan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:128

Error: EBUSY: resource busy or locked, open 'C:\Users\mlgyshan\Workspace\Flexturo\public\js\admin.js'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.readFileSync (fs.js:397:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:384:29)
  at File.module.exports.File.readSync (C:\Users\mlgyshan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:261:36)
  at TextBuffer.module.exports.TextBuffer.updateCachedDiskContentsSync (C:\Users\mlgyshan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1072:85)
  at C:\Users\mlgyshan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1213:17
  at Emitter.module.exports.Emitter.emit (C:\Users\mlgyshan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\mlgyshan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:447:40
  at _fulfilled (C:\Users\mlgyshan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:794:54)
  at self.promiseDispatch.done (C:\Users\mlgyshan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:823:30)
  at Promise.promise.promiseDispatch (C:\Users\mlgyshan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:756:13)
  at C:\Users\mlgyshan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:564:44
  at flush (C:\Users\mlgyshan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:110:17)
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```

### Commands

```
  2x -2:18.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:39.9.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -1:36.2.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:24.7.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -1:24.2.0 core:select-right (atom-text-editor.editor.is-focused)
     -1:23.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:23 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -1:21.9.0 core:save (atom-text-editor.editor.is-focused)
 19x -0:46.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:45.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:36.7.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:36.3.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:35.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:35.2.0 core:save (atom-text-editor.editor.is-focused)
 31x -0:29.6.0 core:undo (atom-text-editor.editor.is-focused)
  2x -0:28.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-ternjs",
      "atom-ternjs",
      "atom-ternjs",
      "atom-ternjs",
      "atom-ternjs"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v6.0.8
linter, v1.5.2
open-github-from-npm, v0.1.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Seems very similar to #9031, so I'm going to close this in favor of that issue.
