### ISSUE TITLE
Install Shell Commands is throwing an exception

### ISSUE THREAD

**Issue by thomasjo** [atom/atom#9186]
1. Build from `master` (6495f1a5314320cbc6d9a5936aab24e507e2d21d).
2. Open Atom.
3. Click *Atom* main menu, followed by *Install Shell Commands*.

**Atom Version**: 1.2.0-dev-6495f1a
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'confirm' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/command-installer.js:78

TypeError: Cannot read property 'confirm' of undefined
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-installer.js:78:48
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-installer.js:111:11
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -0:33.5.0 window:toggle-dev-tools (atom-pane.pane.active)
     -0:00.7.0 window:install-shell-commands (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "background-tips",
      "feedback",
      "metrics",
      "welcome"
    ],
    "projectHome": "/Users/thomasjo/Code"
  },
  "editor": {
    "fontFamily": "Hack, Fira Mono, Menlo",
    "lineHeight": 1.6,
    "showInvisibles": true,
    "showIndentGuide": true,
    "softWrapAtPreferredLineLength": true,
    "scrollPastEnd": true,
    "softWrapHangingIndent": 2,
    "invisibles": {
      "tab": "⇥"
    },
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
language-cuda, v0.1.0
language-latex, v0.6.1
latex, v0.26.0

# Dev
language-cuda, v0.1.0
latex, v0.26.0
```

**Comment by nathansobo** [comment]
Thanks @thomasjo. Sorry everyone building from master last night. I suppose a few regressions were to be expected with this big a change. Perhaps waiting until Monday morning would have been better.

**Comment by maxbrunsfeld** [comment]
:sparkles: thanks @thomasjo!
