### ISSUE TITLE
Cannot read property 'openExternal' of undefined

### ISSUE THREAD

**Issue by thomasjo** [atom/atom#9187]
1. Built from `master` (6495f1a5314320cbc6d9a5936aab24e507e2d21d).
2. Trigger a fatal exception (e.g. via clicking *Install Shell Commands* as of commit above).
3. Click *Create Issue* button.

**Atom Version**: 1.2.0-dev-6495f1a
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'openExternal' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:241

TypeError: Cannot read property 'openExternal' of undefined
    at module.exports.WindowEventHandler.handleLinkClick (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:241:40)
    at HTMLDocument.innerHandler (/Applications/Atom.app/Contents/Resources/app.asar/src/delegated-listener.js:10:11)
```

### Commands

```
     -2:50.3.0 window:toggle-dev-tools (atom-pane.pane.active)
     -2:17.5.0 window:install-shell-commands (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "background-tips",
      "feedback",
      "metrics",
      "welcome"
    ],
    "projectHome": "/Users/thomasjo/Code"
  },
  "editor": {
    "fontFamily": "Hack, Fira Mono, Menlo",
    "lineHeight": 1.6,
    "showInvisibles": true,
    "showIndentGuide": true,
    "softWrapAtPreferredLineLength": true,
    "scrollPastEnd": true,
    "softWrapHangingIndent": 2,
    "invisibles": {
      "tab": "⇥"
    },
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
language-cuda, v0.1.0
language-latex, v0.6.1
latex, v0.26.0

# Dev
language-cuda, v0.1.0
latex, v0.26.0
```

**Comment by thomasjo** [comment]
Seems like the application delegate is undefined at https://github.com/atom/atom/blob/670f200b5275af03254e34c6075d60bee48ff66b/src/window-event-handler.coffee#L181, otherwise the only option is that the `shell` module is not loading? Investigating.
