### ISSUE TITLE
Uncaught Error: UnknownSystemError: Unknown system error, fdatasync

### ISSUE THREAD

**Issue by justingrady** [atom/atom#9196]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: UnknownSystemError: Unknown system error, fdatasync

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:809

Error: UnknownSystemError: Unknown system error, fdatasync
  at Error (native)
  at Object.fs.fdatasyncSync (fs.js:773:18)
  at TextBuffer.module.exports.TextBuffer.backUpFileContentsBeforeWriting (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1103:10)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1020:31)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1004:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:584:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:547:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:530:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```
### Commands

```
     -0:33.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:33.2.0 editor:indent (atom-text-editor.editor.is-focused)
 13x -0:31.9.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:30 core:move-left (atom-text-editor.editor.is-focused)
  4x -0:29.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:28.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:28.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:28.1.0 editor:indent (atom-text-editor.editor.is-focused)
 13x -0:27.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:24.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:24.3.0 core:backspace (atom-text-editor.editor.is-focused)
 14x -0:23.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:20 core:backspace (atom-text-editor.editor.is-focused)
     -0:19.3.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -0:18.8.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:17.4.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Volumes/Seagate Backup Plus Drive/web_dev",
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "invisibles": {},
    "backUpBeforeSaving": true
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Looks like this error is coming either from https://github.com/atom/text-buffer/blob/0be2cc30fa0bd9d073b90251d74ecaae9af6693f/src/text-buffer.coffee#L1298 or https://github.com/atom/text-buffer/blob/0be2cc30fa0bd9d073b90251d74ecaae9af6693f/src/text-buffer.coffee#L1318.

/cc @nathansobo, @bronson

**Comment by nathansobo** [comment]
`fdatasync` flushes buffered file contents to disk so we're sure the backup is safe. Not sure what the system error could have been that prevented this. @justingrady were you able to subsequently save successfully. Was there anything interesting about the directory you were writing to permissions-wise?

**Comment by maddrag0n** [comment]
Happens as well for me on OS X 10.11.3 only when the `backup before saving` option is enabled. The only other non-standard configuration on my system is, that my project folder is on a NTFS volume (read/write access with Paragon NTFS driver).

**Comment by ianmartorell** [comment]
Having the same issue on OS X when trying to save a file on an NTFS drive with `backup before saving` enabled.

**Comment by nathansobo** [comment]
@as-cii can we drop this old backup approach now that you've added the recovery service?

**Comment by bronson** [comment]
@nathansobo, maybe I'm not understanding...  The recovery service is meant to reliably guard against out-of-disk-space errors?

**Comment by bronson** [comment]
Ah, you're talking about this feature: https://github.com/atom/atom/pull/11828  I thought you were talking about file restore.

Agreed, it does sound like it could replace backup files.  Sorry for the noise.

**Comment by as-cii** [comment]
> can we drop this old backup approach now that you've added the recovery service?

Yes, I believe so. I was thinking we might drop it in the next stable version before rolling the railcars after the current beta period in order to ensure everything works smoothly. Thoughts? 💭
