### ISSUE TITLE
We should avoid "item.serialize is not a function" exceptions when splitting panes

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#9217]
_From @AMPBEdu on October 17, 2015 22:18_

Steps to reproduce:
1. Install browser-plus plugin/package
2. Open browser window (ctrl + alt + o)
3. Right click on undefined tab containing browser window and select one of the split options (up down left or right)
4. Receive error

Not sure if this is atom's fault or the browser-plus plugin/package fault.

**Atom Version**: 1.0.19
**System**: Linux Mint
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.84.0

### Stack Trace

Uncaught TypeError: item.serialize is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:436

TypeError: item.serialize is not a function
  at TabBarView.module.exports.TabBarView.copyItem (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:436:133)
  at TabBarView.module.exports.TabBarView.splitTab (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:426:31)
  at Object.addElementCommands.tabs:split-right (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:135:26)
  at space-pen-ul.commandsWithPropagationStopped.(anonymous function) (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:86:36)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:145:19)
  at [object Object].jQuery.fn.trigger (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:157:33)
  at HTMLDocument.handler (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
  3x -9:36 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:28.5.0 browser-plus:open (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.35
language-html5-subtlegradient, v0.1.0

# Dev
No dev packages
```

_Copied from original issue: atom/tabs#221_

**Comment by nathansobo** [comment]
When splitting a pane with an item that can't be copied or serialized, we should just move the item to the new empty pane.

**Comment by nathansobo** [comment]
Just realized this is a duplicate of #8916.
