### ISSUE TITLE
Uncaught Error: ELOOP: too many symbolic links encountered, open '/Users/adamsaland/.nvmrc'

### ISSUE THREAD

**Issue by jpagnano** [atom/atom#9242]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ELOOP: too many symbolic links encountered, open '/Users/adamsaland/.nvmrc'

```
At /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/pane.js:809

Error: ELOOP: too many symbolic links encountered, open '/Users/adamsaland/.nvmrc'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.writeFileSync (fs.js:1165:15)
    at Object.fsPlus.writeFileSync (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:277:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:377:21)
    at File.module.exports.File.writeSync (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:350:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1023:19)
    at TextEditor.module.exports.TextEditor.saveAs (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/text-editor.js:590:26)
```

### Commands

```
     -2:52.4.0 core:cut (atom-text-editor.editor.is-focused)
  2x -2:52.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:50.8.0 core:undo (atom-text-editor.editor.is-focused)
     -2:48.9.0 core:paste (atom-text-editor.editor.is-focused)
     -2:46.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:45.3.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -2:44.5.0 core:cut (atom-text-editor.editor.is-focused)
     -2:43.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -2:42.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:42 core:paste (atom-text-editor.editor.is-focused)
     -2:41.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -2:41 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:40.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:12.1.0 application:new-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:11 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by ChrisJefferson** [comment]
Are you trying to edit /Users/adamsaland/.nvmrc (or have you previously opened it?)

What do you get if you type:

````
ls -l /Users/adamsaland/.nvmrc
cat /Users/adamsaland/.nvmrc
````
