### ISSUE TITLE
Uncaught TypeError: this.childProcess.send is not a function

### ISSUE THREAD

**Issue by mmcbride1007** [atom/atom#9255]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: this.childProcess.send is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:118

TypeError: this.childProcess.send is not a function
  at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:118:27)
  at Task.module.exports.Task.start (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:109:12)
  at Function.module.exports.Task.once (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:23:18)
  at GitRepository.module.exports.GitRepository.refreshStatus (/Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:398:37)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:77:26

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.css.scss": [
        "css"
      ],
      "source": [
        "[object Object]"
      ]
    },
    "disabledPackages": [
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-toml",
      "language-c",
      "wrap-guide",
      "welcome"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "one-dark-ui",
      "electron-highlighter-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "Hack"
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by edevil** [comment]
I think I have the same problem on Atom 1.4.0:
```
TypeError: this.childProcess.send is not a function
    at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:117:27)
    at Task.module.exports.Task.start (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:108:12)
    at Function.module.exports.Task.once (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:21:18)
    at GitRepository.module.exports.GitRepository.refreshStatus (/Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:374:37)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:75:26
```

**Comment by Jaswetz** [comment]
+1

`/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:117`

```TypeError: this.childProcess.send is not a function
    at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:117:27)
    at Task.module.exports.Task.start (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:108:12)
    at Function.module.exports.Task.once (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:21:18)
    at GitRepository.module.exports.GitRepository.refreshStatus (/Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:385:37)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:75:26```
