### ISSUE TITLE
Failed to load the css-color-highlight package

### ISSUE THREAD

**Issue by egglee** [atom/atom#9285]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Failed to load the css-color-highlight package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:7:3
    at Object.<anonymous> (<anonymous>:7:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 18,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
angularjs-snippets, v0.10.17
angularjs-styleguide-snippets, v0.7.0
atom-grails, v0.1.0
css-color-highlight, v0.3.0
css-snippets, v0.8.0
emmet, v2.3.10
go-find-references, v1.2.3
go-format, v1.0.7
go-plus, v3.3.12
go-rename, v0.3.0
go-to-view, v0.3.0
language-coffee-script-angular, v2.2.0
language-groovy, v0.4.0
language-groovy-cloned-from-java, v0.3.0
language-scala, v1.1.3
linter, v1.0.6
linter-scalac, v0.3.4
scala-format, v0.1.8

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The css-color-highlight package is no longer published - I suggest you uninstall it and try [pigments](https://atom.io/packages/pigments) instead.
