### ISSUE TITLE
Failed to activate the autocomplete-php package

### ISSUE THREAD

**Issue by tokra100** [atom/atom#9305]
[Enter steps to reproduce below:]

1. Open Atom and wait for the bang

**Atom Version**: 1.0.19
**System**: Ubuntu 15.10
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the autocomplete-php package

```
At fs is not defined

ReferenceError: fs is not defined
    at Object.module.exports.loadCompletions (<anonymous>:18:5)
    at Object.module.exports.activate (<anonymous>:4:25)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:245:19)
    at /opt/atom/resources/app.asar/src/package.js:226:30
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:169:15)
    at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:218:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:486:21)
    at /opt/atom/resources/app.asar/src/package-manager.js:469:29
    at Config.module.exports.Config.transact (/opt/atom/resources/app.asar/src/config.js:324:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/atom/resources/app.asar/src/package-manager.js:464:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-snippets",
      "autocomplete-plus"
    ]
  },
  "editor": {
    "preferredLineLength": 120,
    "tabLength": 4,
    "confirmCheckoutHeadRevision": false,
    "lineHeight": 1.15,
    "scrollSensitivity": 60,
    "softWrap": true,
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.3
autocomplete-python, v0.3.0
color-picker, v2.0.13
file-icons, v1.4.5
highlight-line, v0.10.1
linter, v1.9.1
minimap, v4.15.0
project-manager, v2.6.5

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please update autocomplete-php to the latest version (currently v0.3.7) - this has already been fixed.
