### ISSUE TITLE
Build Atom failed in OS X

### ISSUE THREAD

**Issue by xysDavid** [atom/atom#9317]
here is the log

```
Node: v4.2.1
npm: v2.14.7
Installing build modules...
Installing apm...


gyp ERR! configure error
gyp ERR! stack Error: node-v0.10.35.tar.gz local checksum 34ef8a38d75ded4f2aec3045abed4e31764dd337b6d21711a9ce852c2f547fde not match remote 0043656bb1724cb09dbdc960a2fd6ee37d3badb2f9c75562b2d11235daa40a03
gyp ERR! stack     at deref (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:300:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:339:13)
gyp ERR! stack     at emitNone (events.js:72:20)
gyp ERR! stack     at IncomingMessage.emit (events.js:166:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:903:12)
gyp ERR! stack     at doNTCallback2 (node.js:439:9)
gyp ERR! stack     at process._tickCallback (node.js:353:17)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/davidysxue/dev/git/atom/apm/node_modules/atom-package-manager/node_modules/keytar
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok


gyp ERR! configure error
gyp ERR! stack Error: node-v0.10.35.tar.gz local checksum e57cc75b4a819bcd9fba2cdd6c49453992af290787923d6b570f5618891f969a not match remote 0043656bb1724cb09dbdc960a2fd6ee37d3badb2f9c75562b2d11235daa40a03
gyp ERR! stack     at deref (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:300:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:339:13)
gyp ERR! stack     at emitNone (events.js:72:20)
gyp ERR! stack     at IncomingMessage.emit (events.js:166:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:903:12)
gyp ERR! stack     at doNTCallback2 (node.js:439:9)
gyp ERR! stack     at process._tickCallback (node.js:353:17)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/davidysxue/dev/git/atom/apm/node_modules/atom-package-manager/node_modules/first-mate/node_modules/oniguruma
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok


gyp ERR! configure error
gyp ERR! stack Error: node-v0.10.35.tar.gz local checksum 6f118682dac178a598eb1031a3feb3fd1f1325e48df4d542fc663dc741455fc6 not match remote 0043656bb1724cb09dbdc960a2fd6ee37d3badb2f9c75562b2d11235daa40a03
gyp ERR! stack     at deref (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:300:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:339:13)
gyp ERR! stack     at emitNone (events.js:72:20)
gyp ERR! stack     at IncomingMessage.emit (events.js:166:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:903:12)
gyp ERR! stack     at doNTCallback2 (node.js:439:9)
gyp ERR! stack     at process._tickCallback (node.js:353:17)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/davidysxue/dev/git/atom/apm/node_modules/atom-package-manager/node_modules/git-utils
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/Users/davidysxue/dev/git/atom/build/node_modules/.bin/npm" "--userconfig=/Users/davidysxue/dev/git/atom/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/davidysxue/dev/git/atom/apm/npm-debug.log
```

**Comment by lukaszwit** [comment]
I've got similar issue with 
```
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
```

**Comment by 50Wliu** [comment]
Here's a similar looking error from Travis: https://travis-ci.org/atom/atom/jobs/88706581
