### ISSUE TITLE
Javascript error on installation in Windows 10

### ISSUE THREAD

**Issue by markzoo** [atom/atom#9319]
Windows 10
AtomSetup.exe
v1.0.19.0

I'm on Windows 10 and every time I try and install Atom I get a javascript error. Each time I've deleted Atom and tried to install it fresh I get the same error:

![atom_error](https://cloud.githubusercontent.com/assets/7262755/10787163/b04d984e-7d66-11e5-9386-a950cd635735.png)

I'm using the latest version of the Windows installer file and below is the contents of SquirrelSetup.log from SquirrelTemp. Just wondering if anyone has seen anything similar on installation?

2015-10-28 11:22:20> Program: Starting Squirrel Updater: --install .
2015-10-28 11:22:20> Program: Starting install, writing to C:\Users\Mark\AppData\Local\SquirrelTemp
2015-10-28 11:22:20> Program: About to install to: C:\Users\Mark\AppData\Local\atom
2015-10-28 11:22:21> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Mark\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3c.MoveNext()
2015-10-28 11:22:21> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Mark\AppData\Local\SquirrelTemp
2015-10-28 11:22:21> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2015-10-28 11:22:21> ApplyReleasesImpl: Writing files to app directory: C:\Users\Mark\AppData\Local\atom\app-1.0.19
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\atom.exe to C:\Users\Mark\AppData\Local\atom\app-1.0.19\atom.exe
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\content_resources_200_percent.pak to C:\Users\Mark\AppData\Local\atom\app-1.0.19\content_resources_200_percent.pak
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\content_shell.pak to C:\Users\Mark\AppData\Local\atom\app-1.0.19\content_shell.pak
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\d3dcompiler_47.dll to C:\Users\Mark\AppData\Local\atom\app-1.0.19\d3dcompiler_47.dll
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\ffmpegsumo.dll to C:\Users\Mark\AppData\Local\atom\app-1.0.19\ffmpegsumo.dll
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\icudtl.dat to C:\Users\Mark\AppData\Local\atom\app-1.0.19\icudtl.dat
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\libEGL.dll to C:\Users\Mark\AppData\Local\atom\app-1.0.19\libEGL.dll
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\libGLESv2.dll to C:\Users\Mark\AppData\Local\atom\app-1.0.19\libGLESv2.dll
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\LICENSE to C:\Users\Mark\AppData\Local\atom\app-1.0.19\LICENSE
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\msvcp120.dll to C:\Users\Mark\AppData\Local\atom\app-1.0.19\msvcp120.dll
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\msvcr120.dll to C:\Users\Mark\AppData\Local\atom\app-1.0.19\msvcr120.dll
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\node.dll to C:\Users\Mark\AppData\Local\atom\app-1.0.19\node.dll
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\snapshot_blob.bin to C:\Users\Mark\AppData\Local\atom\app-1.0.19\snapshot_blob.bin
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\squirrel.exe to C:\Users\Mark\AppData\Local\atom\app-1.0.19\squirrel.exe
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\pdf.dll to C:\Users\Mark\AppData\Local\atom\app-1.0.19\pdf.dll
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\ui_resources_200_percent.pak to C:\Users\Mark\AppData\Local\atom\app-1.0.19\ui_resources_200_percent.pak
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\natives_blob.bin to C:\Users\Mark\AppData\Local\atom\app-1.0.19\natives_blob.bin
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\vccorlib120.dll to C:\Users\Mark\AppData\Local\atom\app-1.0.19\vccorlib120.dll
2015-10-28 11:22:47> ApplyReleasesImpl: Moving file C:\Users\Mark\AppData\Local\atom\app-1.0.19\lib\net45\xinput1_3.dll to C:\Users\Mark\AppData\Local\atom\app-1.0.19\xinput1_3.dll
2015-10-28 11:22:48> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Mark\AppData\Local\atom\app-1.0.19\atom.exe]
2015-10-28 11:23:04> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\Mark\AppData\Local\atom\app-1.0.19\atom.exe: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Squirrel.Utility.<>c__DisplayClassf.<InvokeProcessAsync>b__e()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassd3.<<invokePostInstall>b__c7>d__d5.MoveNext()
2015-10-28 11:23:04> ApplyReleasesImpl: Starting fixPinnedExecutables
2015-10-28 11:23:04> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
2015-10-28 11:23:04> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.19
2015-10-28 11:23:04> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.19
2015-10-28 11:23:05> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__11b.MoveNext()

**Comment by damieng** [comment]
Hi Mark are you still experiencing this problem?

**Comment by markzoo** [comment]
Just tried it there now and it installs directly from a new download with no issues. Thanks for getting back to me.
