### ISSUE TITLE
Failed to load the background-matrix package

### ISSUE THREAD

**Issue by Edozie101** [atom/atom#9326]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Failed to load the background-matrix package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:7:3
    at Object.<anonymous> (<anonymous>:7:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Users/edzye101/Desktop/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v2.0.0
auto-indent, v0.5.0
background-matrix, v0.0.2
jshint, v1.8.1
language-lua, v0.9.4

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The background-matrix package appears to have been unpublished.  Please remove it from your packages list.

**Comment by Edozie101** [comment]
Ok thanks
