### ISSUE TITLE
Uncaught Error: UnknownSystemError: Unknown system error, open 'D:\GIT\FifteenBelow.Interface\src...

### ISSUE THREAD

**Issue by marcusd1bb** [atom/atom#9345]
[Enter steps to reproduce below:]
1. Start Atom before de-crypting (Bitlocker) the drive where the current file tree is being viewed. 

**Atom Version**: 1.1.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: UnknownSystemError: Unknown system error, open 'D:\GIT\FifteenBelow.Interface\src\FifteenBelow.Interface.Content'

```
At C:\Users\marcus.dibb\AppData\Local\atom\app-1.1.0\resources\app.asar\src\workspace.js:461

Error: UnknownSystemError: Unknown system error, open 'D:\GIT\FifteenBelow.Interface\src\FifteenBelow.Interface.Content'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Project.module.exports.Project.open (C:\Users\marcus.dibb\AppData\Local\atom\app-1.1.0\resources\app.asar\src\project.js:348:27)
    at Workspace.module.exports.Workspace.openURIInPane (C:\Users\marcus.dibb\AppData\Local\atom\app-1.1.0\resources\app.asar\src\workspace.js:438:31)
    at Workspace.module.exports.Workspace.open (C:\Users\marcus.dibb\AppData\Local\atom\app-1.1.0\resources\app.asar\src\workspace.js:374:19)
    at EventEmitter.module.exports.WindowEventHandler.handleIPCMessage (C:\Users\marcus.dibb\AppData\Local\atom\app-1.1.0\resources\app.asar\src\window-event-handler.js:193:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
```
### Config

``` json
{
  "core": {},
  "editor": {
    "fontSize": 13,
    "invisibles": {},
    "tabLength": 4,
    "tabType": "soft",
    "showInvisibles": true
  }
}
```
### Installed Packages

``` coffee
# User
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by thedaniel** [comment]
Thanks for the report.

**Comment by nick-morhun** [comment]
Encountered this bug too. When you want to save any untitled document later, Atom tries to save it to that failed file path and a message box appears "Location not available".
