### ISSUE TITLE
Failed to load the atom-sharp package

### ISSUE THREAD

**Issue by marcofranssen** [atom/atom#9347]
[Enter steps to reproduce below:]

1. Open a folder in Atom

**Atom Version**: 1.1.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Failed to load the atom-sharp package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:7:3
    at Object.<anonymous> (<anonymous>:7:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Marco\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (<anonymous>:2:13)
    at Object.<anonymous> (<anonymous>:2:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Marco\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "welcome",
      "autocomplete-plus"
    ],
    "themes": [
      "atom-material-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "tabLength": 4,
    "invisibles": {},
    "autoIndentOnPaste": false,
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.6.3
atom-sharp, v0.1.0
atom-yeoman, v0.3.15
emmet, v2.3.13
json-schema, v0.1.15
language-babel, v0.15.12
language-csharp, v0.11.0
language-docker, v1.1.3
language-ejs, v0.2.0
language-elixir, v0.5.2
language-erlang, v3.0.0
language-fsharp, v0.8.4
language-mongodb, v0.2.0
language-powershell, v2.1.0
language-puppet, v0.15.0
language-scala, v1.1.4
linter, v1.9.1
linter-csslint, v1.0.5
linter-elixirc, v1.1.0
linter-js-yaml, v1.1.2
linter-jscs, v3.1.2
linter-jshint, v1.2.1
linter-pep8, v1.0.1
linter-php, v1.0.5
linter-phpcs, v1.2.2
linter-phpmd, v1.3.2
linter-python-pep8, v0.2.0
linter-scalac, v1.1.0
linter-tidy, v1.0.1
minimap, v4.15.0
minimap-find-and-replace, v4.3.1
omnisharp-atom, v0.25.9
php-getters-setters, v0.5.5
seti-syntax, v0.4.0
Stylus, v1.2.1
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
atom-sharp doesn't seem to be maintained anymore - I'd recommend finding a different package (also, see Azerothian/atom-sharp#14 for the original report of this).
