### ISSUE TITLE
Failed to activate the nuclide-test-runner package

### ISSUE THREAD

**Issue by despairblue** [atom/atom#9350]
I'm getting a ton of the `deprecationSite.getFileName is not a function` errors with the new beta, but only for nuclide packages :confused: 

**Atom Version**: 1.2.0-beta0
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the nuclide-test-runner package

```
At deprecationSite.getFileName is not a function

TypeError: deprecationSite.getFileName is not a function
    at Object.global.__grim__.deprecate (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56:36)
    at Object.defineProperty.get [as TextEditor] (/Applications/Atom Beta.app/Contents/Resources/app.asar/exports/atom.js:38:14)
    at Object.<anonymous> (/Users/kietsy/git/nuclide/pkg/nuclide/ui/atom-text-editor/lib/AtomTextEditor.js:16:13)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.load (/Users/kietsy/git/nuclide/pkg/nuclide/atom-npm/lib/main.js:62:31)
    at Object.<anonymous> (/Users/kietsy/git/nuclide/pkg/nuclide/ui/atom-text-editor/lib/main.js:12:46)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

### Commands

```
     -0:35 window:toggle-dev-tools (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "atom-color-highlight",
      "atom-pair",
      "atomatigit",
      "autocomplete",
      "autocomplete",
      "es-navigation",
      "filetype-color",
      "grunt-runner",
      "incremental-search",
      "linter-scspell",
      "markdown-scroll-sync",
      "metrics",
      "minimap-color-highlight",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "minimap-highlight-selected",
      "minimap",
      "navigate",
      "starred-package-installer",
      "symbols-tree-view",
      "tab-smart-sort",
      "Tern",
      "test-status",
      "themed-settings",
      "travis-ci-status",
      "tree-view-breadcrumb",
      "tree-view-open-files",
      "welcome",
      "nuclide-click-to-symbol",
      "nuclide-quick-open",
      "hyperclick",
      "linter-jshint",
      "nuclide-file-tree",
      "nuclide-flow",
      "nuclide-file-tree-deux",
      "markdown-preview-opener",
      "nuclide-diagnostics-store",
      "nuclide-diagnostics-ui",
      "nuclide-debugger-node"
    ],
    "projectHome": "~/vcs/git/",
    "autoHideMenuBar": true
  },
  "editor": {
    "fontFamily": "Fira Code, Symbola, Droid Sans Fallback",
    "scrollPastEnd": true,
    "invisibles": {},
    "zoomFontWhenCtrlScrolling": false,
    "backUpBeforeSaving": true,
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
atom-alignment, v0.12.1
atom-ternjs, v0.8.4
atom-zeal, v0.1.3
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
block-travel, v1.0.2
bug-report, v0.7.1
clipboard-plus, v0.5.1
color-picker, v2.0.13
compare-files, v0.6.2
docblockr, v0.7.3
editorconfig, v1.2.0
file-icons, v1.6.11
git-log, v0.4.1
go-plus, v3.5.1
grammar-token-limit, v0.1.1
highlight-selected, v0.10.1
imdone-atom, v1.1.51
indentation-indicator, v0.6.0
javascript-snippets, v1.0.0
language-docker, v1.1.3
language-dot, v1.6.0
language-fish-shell, v1.0.2
language-haskell, v1.4.12
language-latex, v0.6.1
language-nimrod, v0.1.0
language-puppet, v0.15.0
language-tss, v0.4.0
latex, v0.28.0
linter, v1.10.0
linter-coffeelint, v1.1.2
linter-eslint, v3.2.1
linter-flow, v3.1.3
linter-htmlhint, v0.2.1
linter-js-standard, v3.2.1
linter-js-yaml, v1.1.2
linter-puppet-lint, v0.6.1
linter-shellcheck, v1.0.2
nuclide-arcanist, v0.0.0
nuclide-blame, v0.0.0
nuclide-blame-provider-hg, v0.0.0
nuclide-blame-ui, v0.0.0
nuclide-buck-files, v0.0.0
nuclide-clang-atom, v0.0.0
nuclide-code-format, v0.0.0
nuclide-debugger-atom, v0.0.0
nuclide-debugger-hhvm, v0.0.0
nuclide-debugger-lldb, v0.0.0
nuclide-diff-view, v0.0.0
nuclide-file-watcher, v0.0.0
nuclide-find-references, v0.0.0
nuclide-fuzzy-filename-provider, v0.0.0
nuclide-hack, v0.0.0
nuclide-hack-symbol-provider, v0.0.0
nuclide-hg-repository, v0.0.0
nuclide-installer, v0.0.0
nuclide-language-hack, v0.0.0
nuclide-objc, v0.0.0
nuclide-ocaml, v0.0.0
nuclide-open-filenames-provider, v0.0.0
nuclide-remote-projects, v0.0.0
nuclide-test-runner, v0.0.0
nuclide-toolbar, v0.0.0
nuclide-type-hint, v0.0.0
one-tab, v0.8.0
package-cop, v0.2.10
package-sync, v0.2.0
pdf-view, v0.34.0
pigments, v0.18.1
react, v0.12.10
regex-railroad-diagram, v0.10.4
swap-panes, v0.2.0
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by WiWa** [comment]
Same!

**Comment by tomauty** [comment]
Also receiving these. Renders Atom unusable :disappointed:

**Comment by benogle** [comment]
cc @scv119

**Comment by gareth-ferneyhough** [comment]
Same here.

**Comment by nechmads** [comment]
Same here. Using the latest Atom version not the beta.

**Comment by lazorgator** [comment]
Same here. I've tried both the latest stable and latest beta with the same exceptions.

**Comment by lenaten** [comment]
+1

**Comment by jacobburns** [comment]
Same here.

**Comment by icyflash** [comment]
+1

**Comment by dbecker215** [comment]
+1

**Comment by bgnlordhelmut** [comment]
+1

**Comment by benogle** [comment]
Closing in favor of https://github.com/facebook/nuclide/issues/246 @scv119 is looking into it on facebook's side.

**Comment by kaffeel** [comment]
+1

**Comment by smLocal** [comment]
the editor has crashed. any tips?
