### ISSUE TITLE
Atom 1.1.0 crash in Windows

### ISSUE THREAD

**Issue by scott-wilson** [atom/atom#9355]
Hello,

I get a crash when following the following steps in Atom 1.1.0 with Windows 7:

1. Open a file in a project, or open the file fuzzy finder (ctrl + t)
2. Open another file in a project.

I get the following traceback when running in the command line:

```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:814:11)
    at process.target._send (internal/child_process.js:552:28)
    at process.target.send (internal/child_process.js:485:12)
    at global.emit (C:\Users\scott.wilson\AppData\Local\atom\app-1.1.0\resources\app.asar\src\task-bootstrap.js:54:22)
    at Object.console.error (C:\Users\scott.wilson\AppData\Local\atom\app-1.1.0\resources\app.asar\src\task-bootstrap.js:20:21)
    at process.<anonymous> (C:\Users\scott.wilson\AppData\Local\atom\app-1.1.0\resources\app.asar\src\task-bootstrap.js:67:22)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:219:26)
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:814:11)
    at process.target._send (internal/child_process.js:552:28)
    at process.target.send (internal/child_process.js:485:12)
    at global.emit (C:\Users\scott.wilson\AppData\Local\atom\app-1.1.0\resources\app.asar\src\task-bootstrap.js:54:22)
    at Object.console.error (C:\Users\scott.wilson\AppData\Local\atom\app-1.1.0\resources\app.asar\src\task-bootstrap.js:20:21)
    at process.<anonymous> (C:\Users\scott.wilson\AppData\Local\atom\app-1.1.0\resources\app.asar\src\task-bootstrap.js:67:22)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:219:26)
```

**Comment by albertosantini** [comment]
Duplicate #9339.

**Comment by 50Wliu** [comment]
Thanks @albertosantini!
