### ISSUE TITLE
Failed to activate the linter-eslint package

### ISSUE THREAD

**Issue by spprasad** [atom/atom#9364]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core
### Stack Trace

Failed to activate the linter-eslint package

```
At UnknownSystemError: Unknown system error, uv_pipe_open

Error: UnknownSystemError: Unknown system error, uv_pipe_open
    at Error (native)
    at new Socket (net.js:127:18)
    at createWritableStdioStream (node.js:602:18)
    at process.stdout (node.js:628:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/chalk/node_modules/supports-color/index.js:29:13
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/chalk/node_modules/supports-color/index.js:50:3)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.3
atom-perforce, v1.5.3
linter-eslint, v3.2.1
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
How did you install `linter-eslint`? I notice that the `linter` package is not being installed for you automatically, which is rather strange...

**Comment by spprasad** [comment]
apm install linter
apm install linter-eslint.

I kept getting an error with linter-eslint, tried couple installs and uninstalls.

**Comment by Arcanemagus** [comment]
Have you tried installing from within Atom's settings?

**Comment by spprasad** [comment]
Yes tried that and apm install also.

**Comment by Arcanemagus** [comment]
Can you try temporarily moving your `.atom` folder elsewhere and seeing if it will install on a fresh install?
