### ISSUE TITLE
Failed to load the latex package

### ISSUE THREAD

**Issue by issmirnov** [atom/atom#9368]
[Enter steps to reproduce below:]

1. Open atom
2. CMD+O to open a folder. I have a reactjs project that was working as intended yesterday, and with no code changes atom now crashes. Very odd.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Failed to load the latex package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Config

```json
{
  "core": {},
  "editor": {
    "tabLength": 4,
    "softWrap": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
fonts, v0.6.0
language-latex, v0.4.1
language-opencl, v0.1.1
latex, v0.14.0
merge-conflicts, v1.2.8

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please update the latex package - the current version is 0.28.0 and you're using 0.14.0 :wink:.
