### ISSUE TITLE
Failed to activate the latex package

### ISSUE THREAD

**Issue by Root-nix** [atom/atom#9371]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Ubuntu 14.04.3
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the latex package

```
At atom.packages.once is not a function

TypeError: atom.packages.once is not a function
    at Object.module.exports.activate (<anonymous>:14:19)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:232:19)
    at /usr/share/atom/resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:153:15)
    at /usr/share/atom/resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:474:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:457:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:300:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:452:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:436:46)
    at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom.js:625:21)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "welcome",
      "metrics"
    ]
  },
  "editor": {
    "fontSize": 19
  }
}
```

### Installed Packages

```coffee
# User
editor-stats, v0.17.0
file-type-icons, v0.5.4
javascript-snippets, v1.0.0
language-docker, v1.1.3
language-latex, v0.6.1
latex, v0.19.1
linter, v0.12.0
node-debugger, v1.0.2

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
Please update your packages, especially the latex package which is wildly outdated on your system.
