### ISSUE TITLE
[atom-beta@1.2] crashes when using the dev tool console while javascript execution is paused

### ISSUE THREAD

**Issue by despairblue** [atom/atom#9381]
## Repro Steps
1. open atom-beta in safe mode
2. open the dev tools
3. pause js execution
4. type something in the console
5. atom freezes and crashes after a couple of seconds

I also have a complete coredump, though it is 420mb.

```
           PID: 25871 (atom)
           UID: 1000 (despairblue)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Sun 2015-11-01 17:04:44 CET (40s ago)
  Command Line: /usr/share/atom-beta/atom --executed-from=/home/despairblue/.atom --pid=25858 --safe .
    Executable: /usr/share/atom-beta/atom
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (despairblue)
       Boot ID: 032555d194774c208f953df7bb594470
    Machine ID: 718617df45a04ebe9f141a7a51c50291
      Hostname: serenity
      Coredump: /var/lib/systemd/coredump/core.atom.1000.032555d194774c208f953df7bb594470.25871.1446393884000000.lz4
       Message: Process 25871 (atom) of user 1000 dumped core.
```
## Versions
- **Atom:**       1.2.0-beta0
- **Atom-Shell:** 
- **OS:**         linux 4.2.3-1-ARCH
- **Misc**
  - apm  1.1.1
  - npm  2.13.3
  - node 0.10.40
  - python 2.7.10
  - git 2.6.2

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by despairblue** [comment]
Not reproducible on a mac, so seems to be linux only. Unfortunately I don't have a windows machine to test this on.

**Comment by SpainTrain** [comment]
I can confirm this occurs in 1.2.4 stable

__atom__: 1.2.4
__OS__: Ubuntu 15.10 4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
__`apm --version`__:

- apm  1.4.0
- npm  2.13.3
- node 0.10.40
- python 2.7.10
- git 2.5.0

@Arcanemagus, would you be willing to test the absence or existence of this issue on Windows?

**Comment by Arcanemagus** [comment]
I'm **not** seeing this on Atom 1.3.0-beta6 on Windows, after typing something I get this:
![image](https://cloud.githubusercontent.com/assets/427137/11480480/7f8de1dc-974c-11e5-99fc-116dc9b4adeb.png)

**Comment by SpainTrain** [comment]
Thanks for checking!

**Comment by pleonex** [comment]
I am also seeing this from time ago. I can't use the console to debug packages. This is the backtrace of the coredump:
```
#0  0x0000000002f332e1 in TtsPlatformImplLinux::GetVoices(std::vector<VoiceData, std::allocator<VoiceData> >*) ()
#1  0x0000000002e8c321 in TtsMessageFilter::OnInitializeVoiceList() ()
#2  0x0000000002e8c094 in TtsMessageFilter::OnMessageReceived(IPC::Message const&) ()
#3  0x0000000001b82788 in  ()
#4  0x0000000001b9c921 in  ()
#5  0x0000000001b9cab9 in  ()
#6  0x0000000001b9cc9d in  ()
#7  0x0000000001b78bca in  ()
#8  0x00007ffff34fba8a in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#9  0x00007ffff34fbe20 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#10 0x00007ffff34fbecc in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#11 0x0000000001b78a87 in  ()
#12 0x0000000001bae330 in  ()
#13 0x000000000229d84b in  ()
#14 0x000000000229d790 in  ()
#15 0x00000000022a066d in  ()
#16 0x0000000002298ee3 in  ()
#17 0x00000000010a7881 in  ()
#18 0x00000000010a6780 in  ()
#19 0x0000000002e6fa77 in main ()
```

It's reproducible from safe mode too. Let me know if you need more info from the coredump.

Atom: 1.3.1-3937312
OS: Fedora 22 with KDE

**Comment by SpainTrain** [comment]
@pleonex want to share that coredump in the upstream issue as well? (sorry I didn't link to it earlier!)

https://github.com/atom/electron/issues/2645

**Comment by romanchyla** [comment]
also on Ubuntu 14.04, with atom 1.3.2 - all it takes is to set a brakpoint, it then stops on it (few seconds later it crashes)

**Comment by romanchyla** [comment]
```
/usr/bin/atom: line 113: 30520 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
auto-updater is not implemented on this platform
Error: auto-updater is not implemented on this platform
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:11:13)
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:14:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at AutoUpdateManager.module.exports.AutoUpdateManager.setupAutoUpdater (/usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:51:23)
    at /usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:42:24
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at NavigationController.loadUrl (/usr/share/atom/resources/atom.asar/browser/api/lib/navigation-controller.js:59:24)
    at EventEmitter.webContents.(anonymous function) [as loadUrl] (/usr/share/atom/resources/atom.asar/browser/api/lib/web-contents.js:81:27)
    at BrowserWindow.loadUrl (/usr/share/atom/resources/atom.asar/browser/api/lib/browser-window.js:121:37)
    at AtomWindow.module.exports.AtomWindow.setLoadSettings (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:125:33)
    at new AtomWindow (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:111:12)
    at AtomApplication.module.exports.AtomApplication.openPaths (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:667:24)
    at AtomApplication.module.exports.AtomApplication.openWithOptions (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:131:21)
    at AtomApplication.module.exports.AtomApplication.loadState (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:749:16)
    at new AtomApplication (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:113:14)
    at createAtomApplication (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:60:16)
    at Function.module.exports.AtomApplication.open (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:63:9)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/main.js:55:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
App load time: 622ms
Failed to get crash dump id.
```

**Comment by dangjc** [comment]
I'm also getting this on atom 1.5.4. Using atom on Linux Mint. Just set a breakpoint. Once it is hit, try to type anything into the console and it crashes. The console works normally otherwise. 
```
/usr/bin/atom: line 117: 19935 Segmentation fault      nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 201ms
auto-updater is not implemented on this platform
Error: auto-updater is not implemented on this platform
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:11:13)
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:14:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at AutoUpdateManager.module.exports.AutoUpdateManager.setupAutoUpdater (/usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:62:23)
    at /usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:53:24
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Failed to get crash dump id.
Report Id: 

```
