### ISSUE TITLE
Atom - Install and GUI problem

### ISSUE THREAD

**Issue by rafaellg8** [atom/atom#9386]
Hi, I installed Atom from the github, the 1.3-dev version, and before I try to install anothers version from the official web, but the problem is the same.  When I try to open atom, dont load the interface, load a tools for developers like a Internet browser. Can someone help, please?

![captura de pantalla de 2015-11-01 23 10 49](https://cloud.githubusercontent.com/assets/14802224/10871694/49cf2688-80ee-11e5-96a7-8cb62872c3b7.png)

**Comment by 50Wliu** [comment]
Can you please click the `1` next to the red "x"?  Thanks.

**Comment by rafaellg8** [comment]
I have an error
```
Error: EACCES: permission denied, open '/home/rafaellg8/.atom/config.cson'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.writeFileSync (fs.js:1171:15)
    at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at Object.module.exports.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:224:17)
    at Config.module.exports.Config.loadUserConfig (/usr/share/atom/resources/app.asar/src/config.js:424:14)
    at Config.module.exports.Config.load (/usr/share/atom/resources/app.asar/src/config.js:379:12)
    at new AtomEnvironment (/usr/share/atom/resources/app.asar/src/atom-environment.js:245:19)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:17)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:51:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:79:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:35:9)
```

**Comment by rafaellg8** [comment]
And If I close the toogle dev, I havent got the menu settings. Nothing only a white screen with the title "untitled"

**Comment by 50Wliu** [comment]
Just delete the `.atom` folder and then run Atom as a normal user.  Atom will recreate the folder with the correct permissions.

**Comment by rafaellg8** [comment]
Perfect, yesterday I was installing javascript nodejs etc,  but what easy solution XD. Thank you!

**Comment by 50Wliu** [comment]
No problem :smile:.
