### ISSUE TITLE
Failed to activate the git-diff package

### ISSUE THREAD

**Issue by ItsJonQ** [atom/atom#9401]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the git-diff package

```
At Cannot read property 'eachEditorView' of undefined

TypeError: Cannot read property 'eachEditorView' of undefined
    at Object.module.exports.activate (<anonymous>:17:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:300:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-ocean-dark"
    ]
  },
  "editor": {
    "fontSize": 13,
    "fontFamily": "Source Code Pro",
    "invisibles": {},
    "showIndentGuide": true,
    "softWrap": true,
    "lineHeight": 1.7
  }
}
```

### Installed Packages

```coffee
# User
base16-ocean-dark, v0.3.0
git-diff, v0.42.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
Please remove git-diff from the `~/.atom/packages` folder. git-diff should be bundled with atom
