### ISSUE TITLE
atom 1.1.0 failed to build in a sbuild chroot

### ISSUE THREAD

**Issue by amazingfate** [atom/atom#9403]
only failed in a sbuild chroot environment
```
npm cache clean && script/build --build-dir "atom-build"
Node: v4.2.1
npm: v1.4.21
Installing build modules...
Installing apm...
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:874:11)
gyp ERR! stack     at TLSWrap.onread (net.js:544:26)
gyp ERR! System Linux 4.2.0-1-amd64
gyp ERR! command "/usr/bin/nodejs" "/<<PKGBUILDDIR>>/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /<<PKGBUILDDIR>>/apm/node_modules/atom-package-manager/node_modules/keytar
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.2.0-1-amd64
npm ERR! argv "/usr/bin/nodejs" "/<<PKGBUILDDIR>>/build/node_modules/.bin/npm" "--userconfig=/<<PKGBUILDDIR>>/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
npm ERR! node v4.2.1
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /<<PKGBUILDDIR>>/apm/npm-debug.log
debian/rules:22: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
debian/rules:19: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
```

**Comment by 50Wliu** [comment]
Looks like an internet connectivity issue.  Can you try again in a few minutes/hours and see if that resolves your issue?

**Comment by amazingfate** [comment]
it should be the problem of my network, I will try a proxy
@50Wliu thank you very much!
