### ISSUE TITLE
Failed to load the scrapfy package

### ISSUE THREAD

**Issue by jhonn921007** [atom/atom#9404]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Failed to load the scrapfy package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Users/Jhonn/Documents/Apps Dev/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-plus"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
scrapfy, v0.3.4

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please update scrapfy to the latest version, currently v0.4.5.
