### ISSUE TITLE
Failed to load the placeholder-text package

### ISSUE THREAD

**Issue by SungYeolWoo** [atom/atom#9405]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to load the placeholder-text package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:8:3
    at Object.<anonymous> (<anonymous>:8:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-bootstrap3, v1.2.0
atom-color-highlight, v3.0.5
atom-terminal, v0.6.0
bootstrap-3-snippetset, v0.0.6
bower-install, v0.2.4
highlight-column, v0.4.0
meteor-api, v2.9.0
meteor-snippets, v0.2.0
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.1
minimap-highlight-selected, v3.1.2
minimap-selection, v3.1.1
open-in-browser, v0.4.0
placeholder-text, v0.1.1
polymer-snippets, v0.4.0
project-manager, v1.15.4
seti-syntax, v0.2.1
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The author of the placeholder-text package seems to have fixed this issue but hasn't released a new version yet.  Please follow Nonameghost/atom-placeholder-text#9 for updates.
