### ISSUE TITLE
Failed to activate the execute-as-perl package

### ISSUE THREAD

**Issue by Marc-Bellario** [atom/atom#9418]
[Enter steps to reproduce below:]

1. ...simply started atom
2. ...errors appeared as atom became active

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the execute-as-perl package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:5:23)
    at Package.module.exports.Package.activateNow (C:\Users\Marc\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:232:19)
    at C:\Users\Marc\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:212:32
    at Package.module.exports.Package.measure (C:\Users\Marc\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:153:15)
    at C:\Users\Marc\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:205:26
    at Package.module.exports.Package.activate (C:\Users\Marc\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Marc\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:474:21)
    at C:\Users\Marc\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:457:29
    at Config.module.exports.Config.transact (C:\Users\Marc\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:300:16)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Marc\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:452:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-grails, v0.1.0
execute-as-perl, v0.1.1
language-mongodb, v0.2.0
language-perl, v0.28.0
language-python, v0.38.0
script-runner, v1.8.3

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The execute-as-perl package is no longer available on Github.  I suggest you find a different package that offers similar functionality.
