### ISSUE TITLE
failed to build on debian sid: build script tried to download node-v0.30.7.tar.gz

### ISSUE THREAD

**Issue by amazingfate** [atom/atom#9427]
```
npm cache clean && script/build --build-dir "atom-build"
Node: v4.2.1
npm: v1.4.21
Installing build modules...
Installing apm...
Installing modules ✗
> scrollbar-style@3.2.0 install /«PKGBUILDDIR»/node_modules/scrollbar-style
> node-gyp rebuild


> nslog@3.0.0 install /«PKGBUILDDIR»/node_modules/nslog
> node-gyp rebuild


> runas@3.1.1 install /«PKGBUILDDIR»/node_modules/runas
> node-gyp rebuild


> keyboard-layout@1.0.0 install /«PKGBUILDDIR»/node_modules/atom-keymap/node_modules/keyboard-layout
> node-gyp rebuild


> oniguruma@5.1.2 install /«PKGBUILDDIR»/node_modules/oniguruma
> node-gyp rebuild


> pathwatcher@6.2.5 install /«PKGBUILDDIR»/node_modules/pathwatcher
> node-gyp rebuild


> git-utils@4.0.5 install /«PKGBUILDDIR»/node_modules/git-utils
> node-gyp rebuild


npm WARN cannot run in wd atom@1.1.0 node -e 'process.exit(0)' (wd=/«PKGBUILDDIR»)
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v0.30.7/node-v0.30.7.tar.gz
gyp ERR! stack     at Request.<anonymous> (/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1689:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at CleartextStream.socketOnData (http.js:1584:20)
gyp ERR! stack     at CleartextStream.read [as _read] (tls.js:514:12)
gyp ERR! stack     at CleartextStream.Readable.read (_stream_readable.js:341:10)
gyp ERR! stack     at EncryptedStream.write [as _write] (tls.js:369:25)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /«PKGBUILDDIR»/node_modules/scrollbar-style
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v0.30.7/node-v0.30.7.tar.gz
gyp ERR! stack     at Request.<anonymous> (/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1689:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at CleartextStream.socketOnData (http.js:1584:20)
gyp ERR! stack     at CleartextStream.read [as _read] (tls.js:514:12)
gyp ERR! stack     at CleartextStream.Readable.read (_stream_readable.js:341:10)
gyp ERR! stack     at EncryptedStream.write [as _write] (tls.js:369:25)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /«PKGBUILDDIR»/node_modules/nslog
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v0.30.7/node-v0.30.7.tar.gz
gyp ERR! stack     at Request.<anonymous> (/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1689:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at CleartextStream.socketOnData (http.js:1584:20)
gyp ERR! stack     at CleartextStream.read [as _read] (tls.js:514:12)
gyp ERR! stack     at CleartextStream.Readable.read (_stream_readable.js:341:10)
gyp ERR! stack     at EncryptedStream.write [as _write] (tls.js:369:25)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /«PKGBUILDDIR»/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v0.30.7/node-v0.30.7.tar.gz
gyp ERR! stack     at Request.<anonymous> (/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1689:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at CleartextStream.socketOnData (http.js:1584:20)
gyp ERR! stack     at CleartextStream.read [as _read] (tls.js:514:12)
gyp ERR! stack     at CleartextStream.Readable.read (_stream_readable.js:341:10)
gyp ERR! stack     at EncryptedStream.write [as _write] (tls.js:369:25)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /«PKGBUILDDIR»/node_modules/atom-keymap/node_modules/keyboard-layout
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v0.30.7/node-v0.30.7.tar.gz
gyp ERR! stack     at Request.<anonymous> (/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1689:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at CleartextStream.socketOnData (http.js:1584:20)
gyp ERR! stack     at CleartextStream.read [as _read] (tls.js:514:12)
gyp ERR! stack     at CleartextStream.Readable.read (_stream_readable.js:341:10)
gyp ERR! stack     at EncryptedStream.write [as _write] (tls.js:369:25)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /«PKGBUILDDIR»/node_modules/oniguruma
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v0.30.7/node-v0.30.7.tar.gz
gyp ERR! stack     at Request.<anonymous> (/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1689:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at CleartextStream.socketOnData (http.js:1584:20)
gyp ERR! stack     at CleartextStream.read [as _read] (tls.js:514:12)
gyp ERR! stack     at CleartextStream.Readable.read (_stream_readable.js:341:10)
gyp ERR! stack     at EncryptedStream.write [as _write] (tls.js:369:25)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /«PKGBUILDDIR»/node_modules/pathwatcher
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v0.30.7/node-v0.30.7.tar.gz
gyp ERR! stack     at Request.<anonymous> (/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1689:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at CleartextStream.socketOnData (http.js:1584:20)
gyp ERR! stack     at CleartextStream.read [as _read] (tls.js:514:12)
gyp ERR! stack     at CleartextStream.Readable.read (_stream_readable.js:341:10)
gyp ERR! stack     at EncryptedStream.write [as _write] (tls.js:369:25)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /«PKGBUILDDIR»/node_modules/git-utils
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/bin/node" "/«PKGBUILDDIR»/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/«PKGBUILDDIR»/.atom/.apm/.apmrc" "--userconfig" "/«PKGBUILDDIR»/.atom/.apmrc" "install" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! scrollbar-style@3.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrollbar-style@3.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the scrollbar-style package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrollbar-style
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /«PKGBUILDDIR»/npm-debug.log
```

**Comment by 50Wliu** [comment]
Well that's pretty odd.  Looks like it's using the Electron version.  /cc @zcbenz

**Comment by zcbenz** [comment]
It seems that `npm_config_disturl` is modified by something.
