### ISSUE TITLE
Failed to load the always-up package

### ISSUE THREAD

**Issue by fabiusss** [atom/atom#9430]
[Enter steps to reproduce below:]

1. Open atom

**Atom Version**: 1.1.0
**System**: Windows 10
**Thrown From**: Atom Core

### Stack Trace

Failed to load the always-up package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:6:3
    at Object.<anonymous> (<anonymous>:6:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Fabiano\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "data-atom",
      "atom-jshint",
      "jshint",
      "terminal-status",
      "save-session",
      "open-in-sourcetree",
      "open-last-project",
      "autoclose-html"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
always-up, v0.4.0
angularjs, v0.3.3
auto-indent, v0.5.0
autocomplete-paths, v1.0.2
color-picker, v2.0.13
debugger-lines, v0.5.2
docblockr, v0.7.3
git-log, v0.4.1
http-status-codes, v1.0.4
language-mongodb, v0.2.0
line-ending-converter, v1.3.2
linter, v1.10.0
linter-htmlhint, v0.2.1
linter-jshint, v1.2.1
local-history, v3.2.3
minimap, v4.16.0
modular-snippets, v0.2.1
pretty-json, v0.4.1
project-manager, v2.6.5

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The always-up package no longer seems to be maintained - I would suggest uninstalling it and finding an alternative.
