### ISSUE TITLE
Failed to load the npm-docs package

### ISSUE THREAD

**Issue by MrMic** [atom/atom#9433]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to load the npm-docs package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (<anonymous>:5:15)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/mic/WebstormProjects",
    "disabledPackages": [
      "coffee-compiler"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "showInvisibles": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
aligner-puppet, v0.1.1
angularjs, v0.3.3
angularjs-snippets, v0.10.18
atom-alignment, v0.12.1
atom-jinja2, v0.5.0
atom-material-syntax, v0.2.4
atom-material-ui, v0.7.1
autocomplete-html-entities, v0.1.0
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
autocomplete-python, v0.10.0
autocomplete-ruby, v0.1.0
command-logger, v0.23.0
emmet, v2.3.14
file-icon-supplement, v0.8.3
file-icons, v1.6.11
file-type-icons, v0.7.3
file-watcher, v0.4.0
git-diff-details, v0.21.0
git-log, v0.4.1
highlight-line, v0.11.0
language-ansible, v0.1.3
language-chef, v0.8.0
language-coffee-script-angular, v2.2.0
language-docker, v1.1.3
language-puppet, v0.15.0
line-ending-selector, v0.3.0
linter, v1.10.0
minimap, v4.16.0
node-resolver, v1.0.1
npm-docs, v0.2.0
pdf-view, v0.34.0
pigments, v0.18.1
project-colorize, v0.2.0
project-view, v0.1.2
run-in-browser, v0.1.3
symbols-tree-view, v0.10.1
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.2
vagrant, v0.1.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The npm-docs package no longer appears to be maintained.  I would suggest uninstalling it and finding an alternative.  See also jclem/npm-docs#9.
