### ISSUE TITLE
Failed to load the backbonejs-snippets package

### ISSUE THREAD

**Issue by jtryan** [atom/atom#9439]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Failed to load the backbonejs-snippets package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "meteor-helper",
      "language-fsharp",
      "archive-view",
      "language-objective-c",
      "background-tips",
      "deprecation-cop",
      "dev-live-reload",
      "encoding-selector",
      "exception-reporting",
      "language-c",
      "language-clojure",
      "language-java",
      "language-make",
      "language-php",
      "language-perl",
      "language-property-list",
      "language-toml",
      "language-yaml",
      "metrics",
      "styleguide",
      "welcome",
      "language-coffee-script",
      "language-ruby-on-rails",
      "language-shellscript",
      "omnisharp-atom",
      "change-case",
      "meteor-api",
      "language-sql",
      "feedback",
      "release-notes",
      "language-python",
      "autocomplete-atom-api",
      "autocomplete-css",
      "autocomplete-html",
      "language-go",
      "language-sass"
    ],
    "themes": [
      "atom-dark-ui",
      "cobalt2-syntax"
    ],
    "audioBeep": false
  },
  "editor": {
    "fontFamily": "inconsolata-dz",
    "showInvisibles": true,
    "showIndentGuide": true,
    "tabLength": 4,
    "softWrap": true,
    "scrollPastEnd": true,
    "invisibles": {},
    "tabType": "soft",
    "zoomFontWhenCtrlScrolling": true,
    "preferredLineLength": 160,
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-backbone, v0.6.1
atom-html-preview, v0.1.12
backbonejs-snippets, v0.4.1
cobalt2-syntax, v0.2.1
cucumber, v0.5.0
emmet, v2.3.13
jshint, v1.8.3
language-csharp, v0.11.0
language-dots, v0.0.4
language-gherkin, v1.0.3
linter, v1.10.0
minimap, v4.16.0
node-debugger, v1.1.9
react, v0.12.10
seti-icons, v0.4.5
tabs-to-spaces, v0.11.1
underscorejs-snippets, v0.2.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The backbonejs-snippets package no longer appears to be maintained.  I suggest you uninstall it and look for a package that offers similar functionality.
