### ISSUE TITLE
Failed to activate the base64 package

### ISSUE THREAD

**Issue by mpellerin** [atom/atom#9441]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the base64 package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:3:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:300:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-light-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "softWrap": true,
    "fontSize": 12,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.6.0
atomatigit, v1.5.1
base64, v0.1.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please update the base64 package.
