### ISSUE TITLE
Failed to load the modeline package

### ISSUE THREAD

**Issue by ioquatix** [atom/atom#9448]
[Enter steps to reproduce below:]

1. Open Atom

**Atom Version**: 1.1.0
**System**: linux 4.2.5-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Failed to load the modeline package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace",
      "autoflow",
      "autosave",
      "autocomplete",
      "autocomplete-clang"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "showInvisibles": true,
    "showIndentGuide": true,
    "softWrap": true,
    "softTabs": false,
    "invisibles": {},
    "softWrapHangingIndent": 2,
    "fontFamily": "Fira Code",
    "fontSize": 11
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
color-picker, v2.0.13
editor-stats, v0.17.0
file-icons, v1.6.11
modeline, v0.0.0
pdf-view, v0.34.0
script-runner, v1.8.4
tabs-to-spaces, v0.11.0
travis-ci-status, v0.18.0
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The modeline package appears to be unpublished (unless of course you're the one developing it since it's v0.0.0).  If you installed it from the Settings View, I would suggest uninstalling it and finding an alternative.

**Comment by ioquatix** [comment]
Thanks dude I'm an idiot :)
