### ISSUE TITLE
Failed to load the linter-clang package

### ISSUE THREAD

**Issue by steabert** [atom/atom#9466]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: linux 4.2.5-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Failed to load the linter-clang package

```
At Cannot find module 'lodash/lang/isFunction'

Error: Cannot find module 'lodash/lang/isFunction'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/babel-core/lib/api/node.js:21:29)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "tabLength": 4,
    "fontSize": 15,
    "fontFamily": "Mono"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
autocomplete-clang, v0.8.8
autocomplete-python, v0.10.3
latex, v0.28.2
linter, v1.10.0
linter-clang, v3.3.0
linter-flake8, v1.9.1
minimap, v4.16.0
minimap-git-diff, v4.1.8
monokai, v0.18.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by kepler0** [comment]
Hi, `linter-clang` maintainer here. I'm not super sure what this issue is, but I don't think it's on `linter-clang` because it doesn't use `lodash`.

**Comment by steabert** [comment]
Hi, this occurred with about 4 different modules. I've rebuilt atom from scratch with a clean build directory and the problem seems to be gone.
