### ISSUE TITLE
Failed to activate the scala-worksheet package

### ISSUE THREAD

**Issue by sffortytwo** [atom/atom#9467]
[Enter steps to reproduce below:]

1. Start up Atom

**Atom Version**: 1.1.0
**System**: Ubuntu 14.04.3
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the scala-worksheet package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:11:23)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:232:19)
    at /opt/atom/resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:153:15)
    at /opt/atom/resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:474:21)
    at /opt/atom/resources/app.asar/src/package-manager.js:457:29
    at Config.module.exports.Config.transact (/opt/atom/resources/app.asar/src/config.js:300:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/atom/resources/app.asar/src/package-manager.js:452:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "invisibles": {},
    "fontFamily": "Input",
    "lineHeight": 1.3
  }
}
```

### Installed Packages

```coffee
# User
git-diff-details, v0.21.0
git-tab-status, v1.9.2
highlight-line, v0.11.0
language-docker, v1.1.3
language-dockerfile, v0.1.0
language-groovy, v0.4.0
language-puppet, v0.15.0
language-scala, v1.1.4
scala-worksheet, v0.3.4
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The scala-worksheet package no longer appears to be maintained.  I would suggest uninstalling it and then finding an alternative.  See also lpenguin/atom-scala-worksheet#14.
