### ISSUE TITLE
Failed to load the atom-beautify package

### ISSUE THREAD

**Issue by babanesma** [atom/atom#9482]
1. install atom-beautify
2. open atom

**Atom Version**: 1.1.0
**System**: Ubuntu 14.04.3
**Thrown From**: Atom Core

### Stack Trace

Failed to load the atom-beautify package

```
At EACCES: permission denied, open '/home/adham/.atom/compile-cache/less/39c67e752d9491865edd700867961fb5777903bf/content/8aa933bdd00d463ea15ea0a95b4451210fea7e12/beautify.json'

Error: EACCES: permission denied, open '/home/adham/.atom/compile-cache/less/39c67e752d9491865edd700867961fb5777903bf/content/8aa933bdd00d463ea15ea0a95b4451210fea7e12/beautify.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.writeFileSync (fs.js:1165:15)
    at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:155:17)
    at LessCache.module.exports.LessCache.putCachedCss (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:225:19)
    at LessCache.module.exports.LessCache.cssForFile (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:276:12)
    at LessCompileCache.module.exports.LessCompileCache.cssForFile (/usr/share/atom/resources/app.asar/src/less-compile-cache.js:40:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/usr/share/atom/resources/app.asar/src/theme-manager.js:270:33)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "editor": {
    "fontSize": 11,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
linter, v1.10.0
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-js-yaml, v1.2.0
linter-jshint, v1.2.1
linter-phpcs, v1.3.0
linter-phpmd, v1.3.2
linter-scss-lint, v2.4.0
linter-tidy, v1.0.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please remove the `.atom/compile-cache` folder and try again.

**Comment by babanesma** [comment]
I have reinstalled atom from scratch , but I think your solution still applies .
Thanks @50Wliu
