### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by wcastand** [atom/atom#9495]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At C:\Users\William\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1008

Error: Can't save buffer with no file path
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\William\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1008:15)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\William\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1002:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\William\AppData\Local\atom\app-1.1.0\resources\app.asar\src\text-editor.js:519:26)
  at C:\Users\William\.atom\init.coffee:16:14
  at C:\Users\William\.atom\init.coffee:25:9
  at CallbacksRegistry.module.exports.CallbacksRegistry.apply (C:\Users\William\AppData\Local\atom\app-1.1.0\resources\atom.asar\common\api\lib\callbacks-registry.js:37:41)
  at EventEmitter.<anonymous> (C:\Users\William\AppData\Local\atom\app-1.1.0\resources\atom.asar\renderer\api\lib\remote.js:176:30)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)

```

### Commands

```
  2x -3:15.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:02.7.0 core:save (atom-text-editor.editor.is-focused)
     -2:02.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:01.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:59.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-seti-ui)
     -1:45.3.0 grammar-selector:show (atom-text-editor.editor)
     -1:41.4.0 auto-indent:apply (atom-text-editor.editor.is-focused)
     -1:41 core:save (atom-text-editor.editor.is-focused)
     -1:40.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:39.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:38.6.0 grammar-selector:show (atom-text-editor.editor)
     -1:22.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:22.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:47.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:46.8.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:46.7.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-material-syntax"
    ],
    "audioBeep": false,
    "disabledPackages": [
      "line-ending-selector"
    ]
  },
  "editor": {
    "invisibles": {
      "tab": "⇥"
    },
    "showIndentGuide": true,
    "showInvisibles": true,
    "fontFamily": "Hack",
    "scrollPastEnd": true,
    "autoIndentOnPaste": false
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-material-syntax, v0.2.4
auto-indent, v0.5.0
emmet, v2.3.14
file-types, v0.5.1
highlight-selected, v0.10.1
keyboard-localization, v1.4.10
language-babel, v2.3.0
line-ending-selector-unix, v0.0.9
seti-ui, v0.8.1
Stylus, v1.2.1

# Dev
No dev packages
```

**Comment by wcastand** [comment]
Hi, i'm pretty sure the problem come from the autosave package who try to save file name "untitled" or result's page for a "find in Directory" for example or even the settings tab.
I activate the option: save on lose focus or closed.

i hope it will help and sorry for my english, i do my best :)

**Comment by maxbrunsfeld** [comment]
Could you share the content of your `init.coffee`? It looks like the error may be coming from there.

**Comment by wcastand** [comment]
Here it is :)

```
# Your init script
#
# Atom will evaluate this file each time a new window is opened. It is run
# after packages are loaded/activated and after the previous editor state
# has been restored.
#
# An example hack to log to the console when each text editor is saved.
#
# atom.workspace.observeTextEditors (editor) ->
#   editor.onDidSave ->
#     console.log "Saved! #{editor.getPath()}"
atom.getCurrentWindow().on 'blur', ->
  for pane in atom.workspace.getPanes()
    for item in pane.items
      if item.isModified?
        item.save() if item.isModified()
      else
        item.save()
```

**Comment by maxbrunsfeld** [comment]
@wcastand The autosave package should do that for you. Just set `autosave.enabled` to true in your config.
