### ISSUE TITLE
Failed to activate the ruby-string-interpolation package

### ISSUE THREAD

**Issue by leoru** [atom/atom#9505]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the ruby-string-interpolation package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:6:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:300:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "atom-light-syntax"
    ]
  },
  "editor": {
    "fontFamily": "Consolas",
    "fontSize": 12,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.4.2
auto-indent, v0.5.0
color-picker, v2.0.13
language-blade, v0.16.0
ruby-slim, v0.2.0
ruby-string-interpolation, v0.1.8
unity-ui, v2.1.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The ruby-string-interpolation appears to have been unpublished.  I would suggest uninstalling it and finding another alternative.
