### ISSUE TITLE
TypeError when using custom test runner with atom package

### ISSUE THREAD

**Issue by johnislarry** [atom/atom#9517]
I'm on atom 1.2.0-beta2 and I'm trying to use a custom test runner.  My `package.json` has

```
{
"atomTestRunner": "./lib/main"
}
```

and `lib/main.js` has

```
module.exports = function () {
  console.log('Hi');
};
```

Finally I have a spec file `spec/main-spec.js` which has a single log statement:

```
console.log('Bye');
```

When I run `atom-beta --test spec/main-spec.js` I get this output:

```
$ atom-beta --test spec/main-spec.js
Hi
TypeError: Cannot read property 'then' of undefined
    at Object.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/initialize-test-window.js:76:14)
    at Object.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/initialize-test-window.js:88:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///Applications/Atom%20Beta.app/Contents/Resources/app.asar/static/index.js:79:5)
    at window.onload (file:///Applications/Atom%20Beta.app/Contents/Resources/app.asar/static/index.js:35:9)
```

Is there a workaround for this error?  It's also very possible I'm doing something wrong.  Please advise!

**Comment by maxbrunsfeld** [comment]
Hi @johnislarry, your function exported from `lib/main.js` just needs to return a `Promise`. Sorry that this interface is a bit rough. You could do this:

```js
module.exports = function () {
  console.log('Hi');
  // success
  Promise.resolve(0);
};
```

**Comment by johnislarry** [comment]
Oh awesome, that works.  Thanks!
