### ISSUE TITLE
Failed to activate the sort-lines package

### ISSUE THREAD

**Issue by widnyana** [atom/atom#9519]
[Enter steps to reproduce below:]

1. Download atom x86_64 rpm from [here](https://atom.io/download/rpm)
2. ```# yum localinstall atom.x86_64.rpm```, success
3. ```$ atom .```
4. atom gui is spawned, and the error shown in sidebar
![atom-error](https://cloud.githubusercontent.com/assets/937158/11083214/52825cdc-885f-11e5-9eba-f6e852c94bc1.png)

**Atom Version**: 1.1.0
**System**: "Fedora release
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the sort-lines package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:5:23)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:232:19)
    at /usr/share/atom/resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:153:15)
    at /usr/share/atom/resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:474:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:457:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:300:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:452:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ],
    "useReactEditor": true,
    "themes": [
      "solarized-dark-ui",
      "solarized-dark-syntax"
    ],
    "audioBeep": false
  },
  "editor": {
    "fontFamily": "source code pro",
    "showIndentGuide": true,
    "softWrap": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
Zen, v0.6.0
solarized-dark-ui, v0.3.0
sort-lines, v0.6.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please update all your packages.  They are extremely out of date.

In addition, please uninstall the `solarized-dark-ui` theme.  This theme comes bundled with Atom, so installing it manually can cause issues.  Once you uninstall it the bundled version will be used again.

**Comment by widnyana** [comment]
sorry my bad, thanks

**Comment by 50Wliu** [comment]
Also, you don't need to uninstall solarized-dark-ui; it's actually not a bundled package.  Sorry about that.
