### ISSUE TITLE
Error "auto-updater is not implemented on this platform" on Linux

### ISSUE THREAD

**Issue by olmokramer** [atom/atom#9534]
I'm getting the following message in `~/.atom/nohup.out` or in the terminal when I start atom with the `--foreground` option. Atom seems to function properly, though. I use Atom v1.3.0-dev-62f4f32 on Debian 9.

```
$ cat ~/.atom/nohup.out 
auto-updater is not implemented on this platform
Error: auto-updater is not implemented on this platform
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:11:13)
    at Object.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:14:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at AutoUpdateManager.module.exports.AutoUpdateManager.setupAutoUpdater (/usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:51:23)
    at /usr/share/atom/resources/app.asar/src/browser/auto-update-manager.js:42:24
App load time: 256ms
```

**Comment by kaarebs** [comment]
I am having the same problem - but is has been fixed
https://github.com/atom/electron/commit/f2439cefd0dba89df02993011ac46dd32a1f79a6

**Comment by 50Wliu** [comment]
Won't close this just yet until we update to Electron 0.35.0.

**Comment by steelbrain** [comment]
I just hit this in latest master's `apm test`

**Comment by mwleeds** [comment]
@steelbrain me too.
```
atom 1.4.0-beta2-f670dd8
apm  1.5.0
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1
```

**Comment by banacorn** [comment]
+1

**Comment by floriangosse** [comment]
+1

**Comment by ascarius** [comment]
Same with 1.4.0 and 1.4.3

Never had this error before

**Comment by hirootkit** [comment]
+1 in v.1.4.0 and 1.5.1

**Comment by jerone** [comment]
Seems related https://github.com/atom/atom/issues/10759

**Comment by 50Wliu** [comment]
@jerone #10759 is not related.  This error is completely harmless.

**Comment by marcellourbani** [comment]
Had the same issue, fixed removing folder .atom in my profile directory:

> sudo rm -Rf ~/.atom

The issue was simple: first time I ran atom was as root, so the .atom folder belonged to root, and my user couldn't access it.

**Comment by sanstream** [comment]
Changing the ownership to my user instead of root fixed it for me:
```
sudo chown [my username].[my username] ~/.atom/nohup.out
```
