### ISSUE TITLE
Uncaught Error: variable @syntax-background-color is undefined

### ISSUE THREAD

**Issue by damarte** [atom/atom#9541]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: variable @syntax-background-color is undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:291

Error
    at new Parser (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
    at LessCache.module.exports.LessCache.parseLess (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:244:16)
    at LessCache.module.exports.LessCache.cssForFile (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:275:20)
    at LessCache.module.exports.LessCache.readFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:263:19)
    at LessCompileCache.module.exports.LessCompileCache.read (/Applications/Atom.app/Contents/Resources/app.asar/src/less-compile-cache.js:36:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:272:33)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:248:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:165:24)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:12:15)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:361:4)
```

### Commands

```
  2x -0:17.4.0 command-palette:toggle (atom-pane.pane.active)
     -0:02.9.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "native-ui",
      "monokai"
    ],
    "projectHome": "/Applications/MAMP/htdocs/",
    "disabledPackages": [
      "local-history",
      "cakephp-snippets",
      "live-archive",
      "goto"
    ],
    "destroyEmptyPanes": false,
    "excludeVcsIgnoredPaths": false
  },
  "editor": {
    "fontSize": 15,
    "invisibles": {},
    "showIndentGuide": true,
    "softTabs": false,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
atom-minify, v0.5.0
atom-pair, v2.0.10
autocomplete-php, v0.3.7
color-picker, v2.0.13
editor-stats, v0.17.0
file-icons, v1.6.11
laravel, v0.7.0
linter, v1.10.0
linter-csslint, v1.1.0
monokai, v0.18.0
native-ui, v0.7.3
php-debug, v0.1.3
php-extract-method, v0.2.0
pretty-json, v0.4.1
project-manager, v2.6.5
save-session, v0.15.7
symbols-tree-view, v0.10.1

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
@damarte @derkcris @sumitpatidar can you try upgrading the `native-ui` theme to version `0.8.1` and see if the issue still occurs?

**Comment by sumitpatidar** [comment]
After that I uninstalled native-ui and my atom worked fine l as before without using the atom--safe. Now there is problem reinstalling the native-ui theme.

**Comment by derkcris** [comment]
@kevinsawicki Atom is fully broken and I can't perform any action:

<img width="810" alt="screen shot 2015-11-18 at 11 05 14 p m" src="https://cloud.githubusercontent.com/assets/3590272/11262077/dfad5a8c-8e48-11e5-91e9-df97ed11c198.png">

**Comment by sumitpatidar** [comment]
Try atom --safe using terminal.

**Comment by derkcris** [comment]
Thank you @sumitpatidar. With `atom --safe` I could update the `native-ui` package and now is working perfect.

**Comment by 50Wliu** [comment]
Closing as this is a problem with native-ui that has already been resolved.
