### ISSUE TITLE
Failed to activate the org package

### ISSUE THREAD

**Issue by wolves** [atom/atom#9543]
[Enter steps to reproduce below:]

1. Occurs upon startup

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the org package

```
At Cannot read property 'eachEditorView' of undefined

TypeError: Cannot read property 'eachEditorView' of undefined
    at new OrgInput (<anonymous>:9:23)
    at Object.module.exports.activate (<anonymous>:5:17)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:300:16)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "PATH": "/Users/USER/.rubies/ruby-2.2.3/bin:/Users/USER/.gem/ruby/2.2.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
    "GEM_PATH": "/Users/USER/.gem/ruby/2.2.3:/Users/USER/.rubies/ruby-2.2.3/lib/ruby/gems/2.2.0",
    "RUBY_VERSION": "2.2.3",
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "vim-mode",
      "filetype-color",
      "linter-rubocop",
      "linter-eslint"
    ],
    "themes": [
      "atom-material-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "softWrapAtPreferredLineLength": true,
    "invisibles": {},
    "lineHeight": 1.66,
    "scrollPastEnd": true,
    "fontFamily": "\"Fira Code\"",
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.2.0
atom-material-ui, v0.8.0
atom-ternjs, v0.8.4
autoclose-html, v0.19.0
emmet, v2.3.14
file-icons, v1.6.11
go-plus, v3.5.1
gulp-snippets, v0.6.2
html2haml, v0.10.0
language-babel, v2.4.1
language-docker, v1.1.3
language-elixir, v0.5.2
language-gherkin, v1.0.3
language-haml, v0.23.6
language-slim, v0.5.0
language-spacebars, v0.2.2
linter, v1.10.0
linter-ruby, v1.2.0
meteor-api, v2.20.0
org, v0.2.5
pretty-json, v0.4.1
project-manager, v2.6.5
react, v0.12.10
remote-atom, v1.2.9

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The org package no longer seems to be maintained.  I would suggest uninstalling it and finding an alternative.
