### ISSUE TITLE
Failed to load the php-beautifier package

### ISSUE THREAD

**Issue by augustinmerle** [atom/atom#9546]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to load the php-beautifier package

```
At Cannot read property 'getActiveView' of undefined

TypeError: Cannot read property 'getActiveView' of undefined
    at Object.<anonymous> (<anonymous>:3:32)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (<anonymous>:1:21)
    at Object.<anonymous> (<anonymous>:1:1)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "php-checkstyle"
    ]
  },
  "editor": {
    "lineHeight": 1.2,
    "showIndentGuide": true,
    "invisibles": {},
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.10
angularjs, v0.3.3
behat-atom, v0.1.2
color-picker, v2.0.13
language-docker, v1.1.3
language-dockerfile, v0.1.0
linter, v1.10.0
monokai, v0.18.0
php-beautifier, v0.2.0
php-twig, v4.0.0
phpunit-snippets, v0.1.0
remote-edit, v1.8.22
symfony-snippets, v0.3.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The php-beautifier package appears to have been unpublished.  I would recommend uninstalling it and finding an alternative.
