### ISSUE TITLE
Uncaught Error: spawn /Users/andersh/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/...

### ISSUE THREAD

**Issue by boxed** [atom/atom#9559]
Just opened a clojurescript project from a fresh install of atom :(

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: spawn /Users/andersh/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/andersh/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/andersh/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/andersh/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:155:27)
    at Object.windowState (/Users/andersh/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/andersh/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/andersh/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:132:14)
    at /Users/andersh/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:822:44
    at Emitter.module.exports.Emitter.emit (/Users/andersh/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Project.module.exports.Project.addPath (/Users/andersh/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Users/andersh/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1000:26)
    at EventEmitter.outerCallback (/Users/andersh/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:204:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -4:18.2.0 settings-view:open (atom-pane.pane.active)
     -4:02.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:00.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:31.7.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by joshaber** [comment]
@50Wliu Could you provide a bit more context? I'm not quite sure why I'm being cc'd :smile:

**Comment by 50Wliu** [comment]
Wow, wrong issue.  That's really embarrassing.

**Comment by benogle** [comment]
Actually, @joshaber you might be a good candidate to look into this. After the last release we got a lot of these reports. Many of them have `shipIt` in the message ([e.g.](https://github.com/atom/atom/issues/9626)). We are not sure what this could be caused by, nor how to reproduce. Yay vagueness!

We used to get these a bunch (https://github.com/atom/atom/issues/4475), but they didnt have a trace, and we papered over them in notifications because they didnt seem to have an effect, and had no trace. I suppose the difference now is that they have a trace. So they may have been happening the whole time, but now they're getting through due to the trace.

Looks like it's trying to spawn some process in the renderer process right after loading the window. Not sure what's up. It would be good to know what's going on with these at some point.

**Comment by boxed** [comment]
I might have a clue: I think I moved the app while it was running and tried to install an extension then. Try if that reproduces the problem.

**Comment by joshaber** [comment]
This is on my radar. My initial guess is that it's often caused by Atom being launched while it's in the middle of installing an update. The window of opportunity for that kinda thing is pretty big right now, unfortunately.

**Comment by joshaber** [comment]
@boxed When you got this error, did it resolve after quitting and re-opening Atom? Or did you have to do anything else to resolve it?

**Comment by boxed** [comment]
Just restarting cleared it.

**Comment by lourencoccc** [comment]
This error still happen on Version 1.7.2 for Windows 8.1.

[Enter steps to reproduce below:]

1. Start application or Add new project folder
2. ctrl + T

**Atom Version**: 1.7.2
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5


### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\joao_lourenco\AppData\Local\atom\app-1.7.2\atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat 'C:\Users\joao_lourenco\AppData\Local\atom\app-1.7.2\atom:'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at C:\Users\joao_lourenco\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (C:\Users\joao_lourenco\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (C:\Users\joao_lourenco\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\fuzzy-finder\lib\project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (C:\Users\joao_lourenco\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\fuzzy-finder\lib\project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (C:\Users\joao_lourenco\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\fuzzy-finder\lib\project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (C:\Users\joao_lourenco\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\joao_lourenco\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\joao_lourenco\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\joao_lourenco\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\joao_lourenco\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\joao_lourenco\AppData\Local\atom\app-1.7.2\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\joao_lourenco\AppData\Local\atom\app-1.7.2\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
  2x -1:43.3.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -1:29.8.0 keyboard-localization:keymap-generator (atom-pane.pane.active)
     -0:35.5.0 application:add-project-folder (ul.list-inline.tab-bar.inset-panel)
     -0:29.3.0 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:25.4.0 tool-panel:unfocus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:20.3.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:19.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:19.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:18.9.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:18.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:18.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:15.2.0 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:14.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:14.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:10.5.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:03.7.0 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.9.1
build-cmake, v0.3.3
build-gradle, v0.6.0
keyboard-localization, v1.4.18
language-cmake, v0.1.4
language-gradle, v0.0.3

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Tentatively closing as the last report of this was on July 30th.

**Comment by oscargoossens91** [comment]
It might be way overdue, but I'm running into the exact same issue when trying to save my bash_profile. For as far as i can see, there hasnt been given any solution yet, if I'm wrong please tell me where to look.

**Comment by 50Wliu** [comment]
We're getting a new wave of this with the update to Atom 1.14, albeit with a slightly different path (`~/Library/Caches/com.github.atom.ShipIt/update...`).

**Comment by keithjjones** [comment]
[Enter steps to reproduce:]

1. Packages->Markdown Preview->Toggle Preview

**Atom**: 1.14.2 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Keith/Library/Caches/com.github.atom.ShipIt/update.RhH9tQS'

```
At fs.js:982

Error: ENOENT: no such file or directory, lstat '/Users/Keith/Library/Caches/com.github.atom.ShipIt/update.RhH9tQS'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at realpathSync (fs.js:1657:19)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:326:24)
    at Function.Module._findPath (module.js:167:25)
    at Module._resolveFilename (module.js:453:25)
    at Module._resolveFilename (/Users/Keith/Library/Caches/com.github.atom.ShipIt/update.RhH9tQS/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
```

### Commands

```
  2x -2:02.4.0 markdown-preview:toggle (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.8.39 
hex 0.6.2 
kite 0.7.12 
linter 1.11.21 
linter-flake8 2.1.4 
python-indent 1.0.0 
python-tools 0.6.9 
```

**Comment by nkkollaw** [comment]
I upgraded to Atom 1.15 on macOS Sierra. 
When I selected "Preferences" from the menu, I would get the error, then the editor would crash.

I tried a few things, but eventually deleting the GitHub Desktop cache made the error disappear:
/Users/nbrogi/Library/Caches/com.github.GitHub/ (of course, you would need to replace "nbrogi" with your username)

All I did was close both Atom and GitHub Desktop, delete that folder, and restart. Everything went back to normal.

This is my error log:

> [Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.247.0


### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/nbrogi/Library/Caches/com.github.atom.ShipIt/update.qu0ZOLQ'

```
At fs.js:982

Error: ENOENT: no such file or directory, lstat '/Users/nbrogi/Library/Caches/com.github.atom.ShipIt/update.qu0ZOLQ'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at realpathSync (fs.js:1657:19)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:326:24)
    at Function.Module._findPath (module.js:167:25)
    at Module._resolveFilename (module.js:453:25)
    at Module._resolveFilename (/Users/nbrogi/Library/Caches/com.github.atom.ShipIt/update.qu0ZOLQ/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/cheerio/lib/parse.js:4:18)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/cheerio/lib/cheerio.js:6:13)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/cheerio/index.js:5:28)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/task-lists/lib/index.js:4:11)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/roaster/lib/roaster.js:14:15)
    at /app.asar/node_modules/roaster/lib/roaster.js:73:4)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/settings-view/lib/package-readme-view.js:8:13)
    at /app.asar/node_modules/settings-view/lib/package-readme-view.js:71:4)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/settings-view/lib/package-detail-view.js:26:23)
    at /app.asar/node_modules/settings-view/lib/package-detail-view.js:444:4)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/settings-view/lib/settings-view.js:18:23)
    at /app.asar/node_modules/settings-view/lib/settings-view.js:383:4)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.createSettingsView (/app.asar/node_modules/settings-view/lib/main.js:145:24)
    at /app.asar/node_modules/settings-view/lib/main.js:49:36
    at Workspace.module.exports.Workspace.openURIInPane (/app.asar/src/workspace.js:501:22)
    at Workspace.module.exports.Workspace.open (/app.asar/src/workspace.js:436:19)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/app.asar/src/atom-environment.js:1187:18)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:229:18)
    at emitThree (events.js:121:20)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
```

### Non-Core Packages

```
2-dark-syntax 1.1.0 
bright-dark-ui 0.5.1 
colorful-json 1.1.0 
custom-title 1.0.1 
dark-flat-ui 1.2.4 
glacier-dark-ui 0.5.0 
gloom 0.4.7 
goto 1.8.3 
highlight-line 0.12.0 
js-extras 1.9.0 
jshint 1.8.6 
jsonlint 1.1.4 
language-javascript-jsx 0.3.7 
language-javascript-subtlegradient 0.1.0 
language-jsx 0.1.1 
less-than-slash 0.16.0 
linter 1.11.23 
linter-csslint 1.3.4 
linter-jshint 3.0.3 
linter-json-lint 0.1.1 
linter-jsonlint 1.3.0 
linter-php 1.3.1 
minimap 4.26.8 
minimap-cursorline 0.2.0 
minimap-linter 1.6.0 
minimap-selection 4.4.0 
one-dark-shade-ui 0.1.0 
pacific-dark 0.5.0 
php-integrator-autocomplete-plus 1.3.0 
php-integrator-base 2.1.11 
php-integrator-linter 1.3.0 
php-integrator-symbol-viewer 0.6.4 
pulsing-cursor 0.3.1 
purplest-inc-dark-ui 1.0.0 
react 0.16.2 
slim-dark-ui 0.12.0 
symbols-list 2.3.5 
two-dark-ui 1.0.1 
varone-dark-ui 1.7.0 
```
