### ISSUE TITLE
Uncaught Error: variable @syntax-background-color is undefined

### ISSUE THREAD

**Issue by sumitpatidar** [atom/atom#9560]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: variable @syntax-background-color is undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:300

Error
    at new Parser (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
    at LessCache.module.exports.LessCache.parseLess (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:244:16)
    at LessCache.module.exports.LessCache.cssForFile (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:275:20)
    at LessCache.module.exports.LessCache.readFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:263:19)
    at LessCompileCache.module.exports.LessCompileCache.read (/Applications/Atom.app/Contents/Resources/app.asar/src/less-compile-cache.js:36:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:281:33)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:257:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:174:24)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:12:15)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:361:4)
```

### Commands

```
  2x -1:16.1.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
 18x -0:07.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-native-ui)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "themes": [
      "native-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "vim-mode"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 8,
    "fontSize": 15,
    "softTabs": false,
    "tabType": "soft"
  }
}
```

### Installed Packages

```coffee
# User
linter, v1.10.0
linter-clang, v3.3.0
minimap, v4.16.0
native-ui, v0.7.3

# Dev
No dev packages
```

**Comment by as-cii** [comment]
Hey @sumitpatidar, thanks for reporting this issue: we're sorry this is causing troubles to you. :bow: 

It would seem as if some variable cannot be found when requiring a stylesheet: could you tell whether it happens always or it seems _random_? Also, it'd be awesome if you could try to reproduce it through `atom --safe`, just to understand if any of your packages is causing this problem.

Thanks a lot! :pray:

**Comment by kevinsawicki** [comment]
This looks very similar to #9545, closing as a duplicate.

**Comment by sumitpatidar** [comment]
It is happening every time whenever I tries to use any feature of atom.

**Comment by sumitpatidar** [comment]
But its working fine in atom --safe.
