### ISSUE TITLE
Uncaught SyntaxError: Unexpected token �

### ISSUE THREAD

**Issue by patrickml** [atom/atom#9571]
1. Enable JSX
2. Save File

I do not know what exactly caused this it was kinda of random.

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core
### Stack Trace

Uncaught SyntaxError: Unexpected token �

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fpatricklewis%2FDocuments%2Fsites%2Fmeteor%2Fcontract-manager%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22windowInitializationScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.2.0%22%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fpatricklewis%2FDocuments%2Fsites%2Fmeteor%2Fcontract-manager%22%5D%7D:1

SyntaxError: Unexpected token �
    at Object.parse (native)
    at Pipe.channel.onread (internal/child_process.js:432:28)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as getPosition] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:138:29)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:555:29)
    at AtomEnvironment.module.exports.AtomEnvironment.storeDefaultWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:588:25)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:183:35)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61
```
### Commands

```
     -0:52.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:52.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:52.1.0 core:undo (atom-text-editor.editor.is-focused)
     -0:49.3.0 core:copy (atom-text-editor.editor.is-focused)
     -0:48.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:48.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:48.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:48 core:paste (atom-text-editor.editor.is-focused)
     -0:45.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:39.5.0 core:move-left (atom-text-editor.editor.is-focused)
  6x -0:35.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:28.8.0 core:copy (atom-text-editor.editor.is-focused)
     -0:27.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:23.2.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:05.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:04.4.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
```
### Config

``` json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "fontSize": 13
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-html-entities, v0.1.0
file-icons, v1.6.11
jshint, v1.8.3
language-SCSS, v0.4.0
language-babel, v2.4.1
language-javascript-jsx, v0.3.7
meteor-api, v2.20.0
pigments, v0.18.1
react, v0.12.10
terminal-plus, v0.14.0

# Dev
No dev packages
```

**Comment by nathansobo** [comment]
@patrickml Can you try moving or deleting the `~/.atom/storage` directory and seeing if that changes anything?

**Comment by lee-dohm** [comment]
@patrickml, you may need to completely exit all Atom instances first before moving or deleting the `~/.atom/storage` directory for things to be fixed.
