### ISSUE TITLE
Failed to activate the atom-alignment package

### ISSUE THREAD

**Issue by mpranivong** [atom/atom#9586]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the atom-alignment package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:10:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:490:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.0.5
atom-alignment, v0.9.3
autocomplete, v0.29.0
language-javascript, v0.39.0
linter-jshint, v0.0.18
seti-syntax, v0.1.7

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please update all your packages - they are extremely out of date.

In addition, please uninstall language-javascript as that comes bundled with Atom (and in fact, you're more than 61 versions behind on that one).
