### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addWarning' of undefined

### ISSUE THREAD

**Issue by keburton** [atom/atom#9587]
[Enter steps to reproduce below:]

1.Trying to save code
2. ...

**Atom Version**: 1.2.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'addWarning' of undefined

```
At C:\Users\kburton\AppData\Local\atom\app-1.2.0\resources\app.asar\src\pane.js:794

TypeError: Cannot read property 'addWarning' of undefined
    at C:\Users\kburton\AppData\Local\atom\app-1.2.0\resources\app.asar\src\pane.js:794:43
    at Pane.module.exports.Pane.handleSaveError (C:\Users\kburton\AppData\Local\atom\app-1.2.0\resources\app.asar\src\pane.js:802:16)
    at Pane.module.exports.Pane.saveItemAs (C:\Users\kburton\AppData\Local\atom\app-1.2.0\resources\app.asar\src\pane.js:557:16)
    at Pane.module.exports.Pane.saveActiveItemAs (C:\Users\kburton\AppData\Local\atom\app-1.2.0\resources\app.asar\src\pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItemAs (C:\Users\kburton\AppData\Local\atom\app-1.2.0\resources\app.asar\src\workspace.js:635:35)
    at atom-workspace.commandRegistry.add.core:save-as (C:\Users\kburton\AppData\Local\atom\app-1.2.0\resources\app.asar\src\register-default-commands.js:176:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\kburton\AppData\Local\atom\app-1.2.0\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\kburton\AppData\Local\atom\app-1.2.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\kburton\AppData\Local\atom\app-1.2.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\kburton\AppData\Local\atom\app-1.2.0\resources\app.asar\src\atom-environment.js:984:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -3:22.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:21.6.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -3:21.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -3:07.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:06.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:12.6.0 core:paste (atom-text-editor.editor.is-focused)
     -2:06.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:02.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:02.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:44.3.0 core:save (atom-text-editor.editor.is-focused)
  8x -1:19.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:16.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:58.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:58 core:copy (atom-text-editor.editor.is-focused)
 17x -0:17.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:12.5.0 core:save-as (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by katburton** [comment]
Figured it out.  Wrong path in code.

**Comment by appsforartists** [comment]
Same error trying to save on Ubuntu from `sudo atom /etc/sudoers`:

```
TypeError: Cannot read property 'addWarning' of undefined
    at /usr/share/atom/resources/app.asar/src/pane.js:794:43
    at Pane.module.exports.Pane.handleSaveError (/usr/share/atom/resources/app.asar/src/pane.js:800:16)
    at Pane.module.exports.Pane.saveItemAs (/usr/share/atom/resources/app.asar/src/pane.js:557:16)
    at Pane.module.exports.Pane.saveActiveItemAs (/usr/share/atom/resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItemAs (/usr/share/atom/resources/app.asar/src/workspace.js:635:35)
    at atom-workspace.commandRegistry.add.core:save-as (/usr/share/atom/resources/app.asar/src/register-default-commands.js:176:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by siliconic** [comment]
Still a bug in v1.2.4 on Ubuntu, occurs for me whenever I try to save changes to a file on a share mounted via sshfs.

Stack trace:

```
TypeError: Cannot read property 'addWarning' of undefined
    at /opt/atom/resources/app.asar/src/pane.js:794:43
    at Pane.module.exports.Pane.handleSaveError (/opt/atom/resources/app.asar/src/pane.js:800:16)
    at Pane.module.exports.Pane.saveItem (/opt/atom/resources/app.asar/src/pane.js:534:16)
    at Pane.module.exports.Pane.saveActiveItem (/opt/atom/resources/app.asar/src/pane.js:513:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/opt/atom/resources/app.asar/src/workspace.js:631:35)
    at atom-workspace.commandRegistry.add.core:save (/opt/atom/resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by quarxdmz** [comment]
this occured to me while overwriting a readonly file

**Comment by webhacking** [comment]
i got same issue

**Comment by cljforge** [comment]
Caught same exception, it seems to appear that anti-virus blocked file. After disabling real-time protection think works well. 

Don't know if this is real cause, but it solved my problem. I hope it would be helpful.

**Comment by jamperry** [comment]
Got this issue just now on Ubuntu Mate.

**Comment by mikethejet** [comment]
I got this on mounted ftp in os x.

**Comment by cmattoon** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Linux Mint
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'addWarning' of undefined

```
At /usr/share/atom/resources/app.asar/src/pane.js:798

TypeError: Cannot read property 'addWarning' of undefined
    at /usr/share/atom/resources/app.asar/src/pane.js:798:43
    at Pane.module.exports.Pane.handleSaveError (/usr/share/atom/resources/app.asar/src/pane.js:804:16)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:538:16)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:643:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:37.6.0 core:move-down (atom-text-editor.editor.emacs-plus.is-focused)
     -1:36.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.emacs-plus.is-focused)
     -1:36.6.0 editor:newline (atom-text-editor.editor.emacs-plus.is-focused)
     -1:35.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.emacs-plus.is-focused)
     -1:35.4.0 core:backspace (atom-text-editor.editor.emacs-plus.is-focused.mark-mode)
 20x -1:35 core:select-down (atom-text-editor.editor.emacs-plus.is-focused.mark-mode)
  2x -1:33.2.0 go-to-line:toggle (atom-text-editor.editor.emacs-plus.is-focused.mark-mode)
     -1:31.3.0 editor:consolidate-selections (atom-text-editor.editor.emacs-plus.mark-mode.is-focused)
     -1:31.3.0 git-diff-details:close-git-diff-details (atom-text-editor.editor.emacs-plus.mark-mode.is-focused)
     -1:31.3.0 core:cancel (atom-text-editor.editor.emacs-plus.mark-mode.is-focused)
 36x -1:31.1.0 core:move-down (atom-text-editor.editor.emacs-plus.is-focused)
     -1:14.2.0 emacs-plus:kill-region (atom-text-editor.editor.emacs-plus.is-focused.mark-mode)
  2x -1:13.8.0 core:paste (atom-text-editor.editor.emacs-plus.is-focused)
  2x -1:09.0 core:save (atom-text-editor.editor.emacs-plus.is-focused)
     -0:03.2.0 find-and-replace:show (atom-text-editor.editor.emacs-plus.is-focused)
     -0:01.3.0 core:save (atom-text-editor.editor.emacs-plus.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-html",
      "autocomplete-plus",
      "autocomplete-snippets",
      "autocomplete-css",
      "bracket-matcher",
      "todo-list",
      "linter-puppet-lint",
      "linter-php"
    ]
  },
  "editor": {
    "invisibles": {},
    "softTabs": false,
    "tabLength": 4,
    "tabType": "soft"
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.7
emacs-plus, v0.9.11
emacs-word-movement, v0.1.0
git-control, v0.4.0
git-diff-details, v0.21.0
hyperclick-php, v0.2.1
impress, v0.1.0
linter, v1.11.3
linter-php, v1.1.6
linter-pylint, v0.2.2
linter-scss-lint, v2.0.0
markdown-preview-plus, v2.2.2
minimap, v4.19.0
php-debug, v0.2.1
php-integrator-tooltips, v0.3.0
phpunit, v1.2.0
phpunit-snippets, v0.1.0
pigments, v0.21.0
smart-daemon-control, v0.8.6
todo-show, v1.3.0

# Dev
No dev packages
```

**Comment by Trudko** [comment]
Same here, I was saving plain old package.json at local disk.

**Atom Version**: 1.5.0
**System**: elementary OS
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'addWarning' of undefined

```
At /usr/share/atom/resources/app.asar/src/pane.js:809

TypeError: Cannot read property 'addWarning' of undefined
    at /usr/share/atom/resources/app.asar/src/pane.js:809:43
    at Pane.module.exports.Pane.handleSaveError (/usr/share/atom/resources/app.asar/src/pane.js:814:16)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:549:16)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:13.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:13.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:12.4.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:12.3.0 core:copy (atom-text-editor.editor.is-focused)
     -0:12.1.0 core:close (atom-text-editor.editor.is-focused)
     -0:07.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:07.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:07.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:06.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:05.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:05.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:03.8.0 tree-view:remove (span.name.icon.icon-file-text)
     -0:01.4.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:01.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint",
      "esformatter"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      "node_modules/"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "fontSize": 13,
    "invisibles": {},
    "preferredLineLength": 120
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
angularjs-styleguide-snippets, v0.7.3
atom-beautify, v0.28.22
atom-jasmine, v0.8.1
autocomplete-angular-material, v0.4.0
express-complete, v0.2.0
file-icons, v1.6.14
highlight-selected, v0.11.2
imdone-atom, v1.3.25
javascript-snippets, v1.2.0
linter, v1.11.3
linter-eslint, v6.0.0
live-archive, v0.1.15
markdown-writer, v2.3.0
node-debugger, v1.3.2
nodejs-snippets, v2.0.0
pretty-json, v0.4.1
project-manager, v2.7.6
react, v0.14.1
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by jonasflint** [comment]
Mounted ubuntu share on OSX.   Realizing Atom hates mounted drives.

**Comment by phluks** [comment]
I had this error:
 `Uncaught TypeError: Cannot read property 'addWarning' of undefined
At /usr/share/atom/resources/app.asar/src/pane.js:809`

I found out it was a problem with the file permissions when I tried to save a file. It woud have been nice with a better error message ;-)

Cheers, Olav

**Comment by 50Wliu** [comment]
Re-opening.

**Comment by 50Wliu** [comment]
Reproduced.  This happens when an error occurs while attempting to save a file in a split pane, as the notification manager isn't passed to the new pane.

**Comment by T04435** [comment]
change the instances of addWarning --> addWarningWithPath,
it might also be problems with file permission 
chmod 664 fileToSave

This solve for me...
