### ISSUE TITLE
Deserialization error: states is not defined (Atom-1.2.0)

### ISSUE THREAD

**Issue by mojodna** [atom/atom#9598]
I'm not entirely sure what I did to trigger this, but it does appear to be a typo in https://github.com/atom/atom/blob/f9a269ed995c4151678aef787573fe44657ed6dd/src/project.coffee#L58

```
index.js:56 ReferenceError: states is not defined
    at Project.module.exports.Project.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:98:9)
    at AtomEnvironment.module.exports.AtomEnvironment.loadStateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:906:22)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:38:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:51:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by abe33** [comment]
Thank you for noticing it and for having took the time to dig the source.

**Comment by NfNitLoop** [comment]
I just ran into this error too. Is there a work-around until there's a release that includes this fix?

**Comment by izuzak** [comment]
Thanks for fixing this, @abe33. 

@nathansobo @maxbrunsfeld Do you think this should be applied to beta as well? I just noticed another report of this in https://github.com/atom/atom/issues/9696.

**Comment by nathansobo** [comment]
It's also on stable. Man.

**Comment by maxbrunsfeld** [comment]
Thanks @abe33!
