### ISSUE TITLE
Failed to activate the dash-on-cursor package

### ISSUE THREAD

**Issue by sigmundlundgren** [atom/atom#9615]
steps to reproduce below:

1. Start atom
2. red alert, pop up

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the dash-on-cursor package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:26:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:490:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:668:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:40:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:51:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:79:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "virtualenv",
      "geojson-preview"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "zoomFontWhenCtrlScrolling": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
api-blueprint-preview, v0.6.0
asciidoc-preview, v0.6.0
atom-grails, v0.1.0
atom-html-preview, v0.1.13
clojure-eval-in-repl, v1.1.0
dash-on-cursor, v0.1.0
go-playground, v0.0.2
go-plus, v3.5.1
go-runtime, v0.2.0
jsonlint, v1.1.2
language-asciidoc, v0.12.0
language-docker, v1.1.3
language-dockerfile, v0.1.0
language-gradle, v0.0.3
language-groovy, v0.4.0
language-nginx, v0.6.1
language-shellscript, v0.20.0
linter-clojure, v1.0.0
linter-govet, v0.1.5
markdown-format, v2.5.1
markdown-preview-pandoc, v0.0.14
motepair, v0.21.0
raml, v0.2.0
rst-preview-pandoc, v0.1.11

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The dash-on-cursor package no longer appears to be maintained - I would suggest uninstalling it and finding an alternative.
