### ISSUE TITLE
Failed to load the autoclose-html package

### ISSUE THREAD

**Issue by ziedhajsalah** [atom/atom#9617]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Ubuntu 14.04.3
**Thrown From**: Atom Core

### Stack Trace

Failed to load the autoclose-html package

```
At EACCES: permission denied, open '/home/zied/.atom/compile-cache/less/df1b7fbc57dbeed23a8f1f8de95b4dfebcc06066/content/e7654ff9300e1d2d45ebdb7c5182dd3e987ca83a/autoclose-html.json'

Error: EACCES: permission denied, open '/home/zied/.atom/compile-cache/less/df1b7fbc57dbeed23a8f1f8de95b4dfebcc06066/content/e7654ff9300e1d2d45ebdb7c5182dd3e987ca83a/autoclose-html.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.writeFileSync (fs.js:1171:15)
    at Object.fsPlus.writeFileSync (/opt/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (/opt/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:155:17)
    at LessCache.module.exports.LessCache.putCachedCss (/opt/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:225:19)
    at LessCache.module.exports.LessCache.cssForFile (/opt/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:276:12)
    at LessCompileCache.module.exports.LessCompileCache.cssForFile (/opt/atom/resources/app.asar/src/less-compile-cache.js:40:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/opt/atom/resources/app.asar/src/theme-manager.js:279:33)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
autocomplete-php, v0.3.7
php-twig, v4.0.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please try deleting the `.atom/compile-cache` and try again.
