### ISSUE TITLE
Package install fails on npm EBADF error - Windows

### ISSUE THREAD

**Issue by RMAdeveloper** [atom/atom#9650]
Hello,

I've already installed other packages without any problem.
I have already tried a fresh Atom install, with no result.

Here's the atom stacktrace (I have replaced user folder path by a simple \user\).
```
Installing “asciidoc-preview@0.6.0” failed.Hide output…

npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm WARN addRemoteGit  git://github.com/anthonny/opal-npm-wrapper.git#0.1.1 resetting remote \user\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-1727a7b3 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm ERR! git clone --template=\user\.atom\.apm\_git-remotes\_templates --mirror git://github.com/anthonny/opal-npm-wrapper.git \user\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-1727a7b3: Cloning into bare repository '\user\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-1727a7b3'...
npm ERR! git clone --template=\user\.atom\.apm\_git-remotes\_templates --mirror git://github.com/anthonny/opal-npm-wrapper.git \user\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-1727a7b3: fatal: unable to connect to github.com:
npm ERR! git clone --template=\user\.atom\.apm\_git-remotes\_templates --mirror git://github.com/anthonny/opal-npm-wrapper.git \user\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-1727a7b3: github.com[0: 192.30.252.129]: errno=No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "\\user\\AppData\\Local\\atom\\app-1.2.0\\resources\\app\\apm\\bin\\node.exe" "\\user\\AppData\\Local\\atom\\app-1.2.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "\\user\\.atom\\.apm\\.apmrc" "--userconfig" "\\user\\.atom\\.apmrc" "install" "\\user\\AppData\\Local\\Temp\\d-1151017-8540-1r14r50\\package.tgz" "--target=0.34.0" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '\user\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-1727a7b3'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=No error
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

And here is the end of  stacktrace using `apm install` verbose command.
```
REQUEST emitting complete https://registry.npmjs.org/property-accessors
REQUEST onRequestResponse https://registry.npmjs.org/mixto 304 { date: 'Tue, 17
Nov 2015 12:44:27 GMT',
  via: '1.1 varnish',
  'cache-control': 'max-age=60',
  etag: '"2I4QJBQFV6TQJCZJ8LODC4K2W"',
  age: '0',
  connection: 'keep-alive',
  'x-served-by': 'cache-fra1233-FRA',
  'x-cache': 'HIT',
  'x-cache-hits': '1',
  'x-timer': 'S1447764267.933082,VS0,VE185',
  vary: 'Accept' }
REQUEST finish init function https://registry.npmjs.org/mixto
REQUEST response end https://registry.npmjs.org/mixto 304 { date: 'Tue, 17 Nov 2
015 12:44:27 GMT',
  via: '1.1 varnish',
  'cache-control': 'max-age=60',
  etag: '"2I4QJBQFV6TQJCZJ8LODC4K2W"',
  age: '0',
  connection: 'keep-alive',
  'x-served-by': 'cache-fra1233-FRA',
  'x-cache': 'HIT',
  'x-cache-hits': '1',
  'x-timer': 'S1447764267.933082,VS0,VE185',
  vary: 'Accept' }
REQUEST end event https://registry.npmjs.org/mixto
REQUEST emitting complete https://registry.npmjs.org/mixto
npm ERR! tar.unpack error reading \user\.atom\.apm\es6-weak-ma
p\0.1.4\package.tgz
npm ERR! git clone --template=\user\.atom\.apm\_git-remotes\_t
emplates --mirror git://github.com/anthonny/opal-npm-wrapper.git \user\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-17
27a7b3: Cloning into bare repository '\user\.atom\.apm\_git-re
motes\git-github-com-anthonny-opal-npm-wrapper-git-1727a7b3'...
npm ERR! git clone --template=\user\.atom\.apm\_git-remotes\_t
emplates --mirror git://github.com/anthonny/opal-npm-wrapper.git \user\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-17
27a7b3: fatal: unable to connect to github.com:
npm ERR! git clone --template=\user\.atom\.apm\_git-remotes\_t
emplates --mirror git://github.com/anthonny/opal-npm-wrapper.git \user\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-17
27a7b3: github.com[0: 192.30.252.129]: errno=No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "\\user\\AppData\\Local\\atom\\app-1.2.0\\resou
rces\\app\\apm\\bin\\node.exe" "\\user\\AppData\\Local\\atom\
\app-1.2.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalco
nfig" "\\user\\.atom\\.apm\\.apmrc" "--userconfig" "\\user\\.atom\\.apmrc" "install" "\\user\\AppData\\
Local\\Temp\\d-1151017-11748-1ehgl6v\\package.tgz" "--target=0.34.0" "--arch=ia3
2"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code EBADF
npm ERR! errno 9

npm ERR! EBADF, fstat
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
failed
```

Similar issue reported have been closed with no solution apparently.
Any idea ? 
Thx!

**Comment by abe33** [comment]
I'm not sure anyone can provide you with a solution, and it certainly not an issue in Atom.

In the stacktrace there are several `npm ERR! fatal: unable to connect to github.com` messages. As far as I can tell it looks like a network error to me, unrelated to Atom.

**Comment by abe33** [comment]
Just tried to install asciidoc-preview and I had no such error. There's definitely something with your network.

**Comment by RMAdeveloper** [comment]
I will report a status about as soon as I can try on another network.

**Comment by damieng** [comment]
Appears to be a networking issue or something relating specifically to that third-party package.
