### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/opt/atom/resources'

### ISSUE THREAD

**Issue by eLunate** [atom/atom#9653]
Got this error by pressing the Update indicator in the bottom right. The one that tells you when your packages can be updated.

**Atom Version**: 1.2.0
**System**: elementary OS
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/opt/atom/resources'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/opt/atom/resources'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
```
### Commands

```
     -1:31.5.0 core:copy (atom-text-editor.editor.is-focused)
     -1:22.3.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -1:20.2.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:09.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:47.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:47.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:47.1.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:01.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "autocomplete-atom-api",
      "autocomplete-css",
      "autocomplete-html"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 16
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by snirp** [comment]
Version 1.2.4 here and experiencing a similar error when trying to open the Preferences:
 
Uncaught Error: ENOENT: no such file or directory, Istat
'/Users/<username>/Library/Application Support/com.github.atom.ShipIt/update.ykapfTU'
 
(stack trace)
 
This error was thrown from the settings-view-package.

**Comment by 50Wliu** [comment]
@snirp you have a different issue: see #9559 and #7399 for more details.

**Comment by snirp** [comment]
@50Wliu You are right, I deleted my comment. Google brought me here ;)
