### ISSUE TITLE
package broken by 1.2.0 update

### ISSUE THREAD

**Issue by willwhitney** [atom/atom#9660]
My package Hydrogen no longer works after updating Atom to v1.2.0: https://github.com/willwhitney/hydrogen/issues/135

Atom fails to find or parse the `package.json` for a dependency of a dependency of mine.

**Atom Version**: 1.2.1
**System**: Mac OS X 10.11.1
**Thrown From**: [Hydrogen](https://github.com/willwhitney/hydrogen) package, v0.6.5
At Could not find module root given file: "undefined". Do you have a `package.json` file? 

```
Error: Could not find module root given file: "undefined". Do you have a `package.json` file? 
    at Function.getRoot (/Users/will/code/hydrogen/node_modules/zmq/node_modules/bindings/bindings.js:159:13)
    at bindings (/Users/will/code/hydrogen/node_modules/zmq/node_modules/bindings/bindings.js:55:32)
    at Object.<anonymous> (/Users/will/code/hydrogen/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/will/code/hydrogen/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/will/code/hydrogen/lib/main.coffee:4:7)
    at Object.<anonymous> (/Users/will/code/hydrogen/lib/main.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:661:34)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:14)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:166:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:738:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by nathansobo** [comment]
This looks like a problem installing the `zmq` library on the version of Node that's embedded in Atom. I just tried to install `zmq` with Node v4 on OS X on the command line and encountered a similar error. You may want to drop that dependency or talk to its author. Good luck!

**Comment by willwhitney** [comment]
Ah, that makes sense. Thanks for the help!

**Comment by n-riesco** [comment]
@nathansobo I would like to add more information so that this issue could be reopened:

- The problem is not really in `zmq` but in `bindings`.

- My understanding is that `bindings` is a requirement for any packages using native modules.

- This issue is caused by Atom v1.2.0 making `Error.prepareStackTrace` read-only (see commit https://github.com/atom/atom/commit/c36b4bd16930f0c6b639ab0d38b93c95d73a922c )

- `bindings` uses `Error.prepareStackTrace` to determine the filename that is invoking `bindings` (see details in https://github.com/TooTallNate/node-bindings/blob/master/bindings.js#L102 )

**Comment by nathansobo** [comment]
This `prepareStackTrace` API design is really causing serious problems. Everyone is abusing it to get raw stack traces. We're all fighting over a single global variable.

**Comment by jeancroy** [comment]
Would it make sens that instead of making the method read-only, atom simply store the original function.
Then always call that instead of the possibly overridden one ?

**Comment by nathansobo** [comment]
The problem is that it needs to be assigned when we call `error.stack` in order for us to get the raw stack trace. It's not a matter of calling it. It's a matter of it being assigned.

**Comment by jeancroy** [comment]
Then maybe after doing it's job, the atom function could chain to a custom function.
The setter `Error.prepareStackTrace = x` could keep the atom function in place but change the chained function. 

kind of a mix between current read only and an event system.

**Comment by n-riesco** [comment]
@nathansobo I've being experimenting and I've come up with an npm package to capture V8's stack traces that keeps `Error.prepareStackFrame()` functional. Please, see:

https://github.com/n-riesco/v8stack

Would a similar idea work in Atom?

**Comment by n-riesco** [comment]
@nathansobo I've been experimenting with the idea of wrapping `prepareStackTrace`. It turned out to be trickier than expected, but it seems to be working now. See here:

https://github.com/n-riesco/v8stack

Would something like that work for Atom?

**Comment by nathansobo** [comment]
It will now be possible to override `prepareStackTrace` within a single event loop tick, so modules like `bindings` will work correctly again in `1.3.x`.

**Comment by gnestor** [comment]
Great, thanks! Nice work @n-riesco 👍

**Comment by gnestor** [comment]
If you clone Atom from master branch, the current version is 1.4.0-dev. I tried to build and test Hydrogen with this version but encountered the following error on launch:

```
RangeError: Maximum call stack size exceeded
   at prepareStackTraceWithRawStackAssignment (/Users/grant/Downloads/atom/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:165:50)
   at prepareStackTraceWithRawStackAssignment (/Users/grant/Downloads/atom/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:167:10)
   at prepareStackTraceWithRawStackAssignment 
```

https://github.com/atom/atom/blob/89786918310e7ba20240f78d36e330ff7c431240/src/compile-cache.js#L167

**Comment by nathansobo** [comment]
@gnestor We didn't realize that our solution created infinite loops when the original value of `Error.prepareStackTrace` was reassigned. #9878 tests and avoids this circumstance. They should really define an official API for getting this information as safely sharing this global variable is leading to some pretty tortured code.

**Comment by gnestor** [comment]
Confirmed that Hydrogen is working again on atom@1.4.0-dev-c0bc38a (current master branch). Thanks @nathansobo.
