### ISSUE TITLE
Uncaught Error: Missing "providerName" property for hyperclick provider.

### ISSUE THREAD

**Issue by sevki** [atom/atom#9673]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.1
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Missing "providerName" property for hyperclick provider.

```
At /Volumes/Homer/nuclide/pkg/nuclide/hyperclick/lib/main.js:30

Error: Missing "providerName" property for hyperclick provider.
    at Object.consumeProvider (/Volumes/Homer/nuclide/pkg/nuclide/hyperclick/lib/main.js:30:13)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v0.10.4
hyperclick, v0.0.0
nuclide-arcanist, v0.0.0
nuclide-blame, v0.0.0
nuclide-blame-provider-hg, v0.0.0
nuclide-blame-ui, v0.0.0
nuclide-buck-files, v0.0.0
nuclide-busy-signal, v0.0.0
nuclide-clang-atom, v0.0.0
nuclide-code-format, v0.0.0
nuclide-code-highlight, v0.0.0
nuclide-debugger-atom, v0.0.0
nuclide-debugger-hhvm, v0.0.0
nuclide-debugger-lldb, v0.0.0
nuclide-debugger-node, v0.0.0
nuclide-diagnostics-store, v0.0.0
nuclide-diagnostics-ui, v0.0.0
nuclide-diff-view, v0.0.0
nuclide-file-tree, v0.0.0
nuclide-file-watcher, v0.0.0
nuclide-find-references, v0.0.0
nuclide-flow, v0.0.0
nuclide-fuzzy-filename-provider, v0.0.0
nuclide-hack, v0.0.0
nuclide-hack-symbol-provider, v0.0.0
nuclide-health, v0.0.0
nuclide-hg-repository, v0.0.0
nuclide-home, v0.0.0
nuclide-installer, v0.0.0
nuclide-language-hack, v0.0.0
nuclide-objc, v0.0.0
nuclide-ocaml, v0.0.0
nuclide-open-filenames-provider, v0.0.0
nuclide-quick-open, v0.0.0
nuclide-recent-files-provider, v0.0.0
nuclide-recent-files-service, v0.0.0
nuclide-remote-projects, v0.0.0
nuclide-test-runner, v0.0.0
nuclide-toolbar, v0.0.0
nuclide-type-hint, v0.0.0
python-tools, v0.6.6
react, v0.12.10
react-snippets, v0.3.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Looks like one of the provider to the hyperclick service doesn't define a name. As far as I can tell this has nothing to do with Atom. You should probably report it on the nuclide repo since hyperclick is part of their codebase.
