### ISSUE TITLE
1.3.0-beta4 fail to start on Debian AMD64

### ISSUE THREAD

**Issue by edomato** [atom/atom#9690]
I just downloaded the DEB package and installed on my laptop and when I tried to start it it throw the following error. Stable version 1.2.2 runs without problem. I was wondering if the problem could be that I have both versions installed, but I never had problems before with that.

Thanks for all.

Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at AtomApplication.module.exports.AtomApplication.openWithOptions (/usr/share/atom-beta/resources/app.asar/src/browser/atom-application.
js:130:29)
    at AtomApplication.module.exports.AtomApplication.loadState (/usr/share/atom-beta/resources/app.asar/src/browser/atom-application.js:749
:16)
    at new AtomApplication (/usr/share/atom-beta/resources/app.asar/src/browser/atom-application.js:113:14)
    at createAtomApplication (/usr/share/atom-beta/resources/app.asar/src/browser/atom-application.js:60:16)
    at Function.module.exports.AtomApplication.open (/usr/share/atom-beta/resources/app.asar/src/browser/atom-application.js:63:9)
    at EventEmitter.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/browser/main.js:55:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
auto-updater is not implemented on this platform
Error: auto-updater is not implemented on this platform
    at Object.<anonymous> (/usr/share/atom-beta/resources/atom.asar/browser/api/lib/auto-updater.js:11:13)
    at Object.<anonymous> (/usr/share/atom-beta/resources/atom.asar/browser/api/lib/auto-updater.js:14:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at AutoUpdateManager.module.exports.AutoUpdateManager.setupAutoUpdater (/usr/share/atom-beta/resources/app.asar/src/browser/auto-update-
manager.js:51:23)
    at /usr/share/atom-beta/resources/app.asar/src/browser/auto-update-manager.js:42:24

**Comment by nathansobo** [comment]
Shoot, we changed the name of a key in the serialized state and didn't provide a fallback. Fixing now.

**Comment by nathansobo** [comment]
We changed the name of a key in serialized application state without realizing it during the rename of an internal variable. We're going to leave the name the same in the state we read from disk so this doesn't happen. People that used `1.3.0-beta4` will need to start Atom with a specific directory or delete their `~/.atom/storage/application.json` file to resolve the issue after upgrading to `1.3.0-beta5`.

**Comment by nathansobo** [comment]
Having some issues publishing `1.3.0-beta5` right now. Just delete `~/.atom/storage/application.json` as a workaround.
