### ISSUE TITLE
Failed to load the atom-inspectly package

### ISSUE THREAD

**Issue by claudiucelfilip** [atom/atom#9693]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.2
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to load the atom-inspectly package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:6:5
    at Object.<anonymous> (<anonymous>:6:5)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "jslint"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "tabLength": 4,
    "fontSize": 13,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
ascii-art, v0.0.0
atom-inspectly, v0.0.0
color-picker, v2.0.13
command-logger, v0.23.0
emmet, v2.3.14
language-javascript-semantic, v0.2.1
monokai, v0.18.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The atom-inspectly package doesn't appear to be published.  Are you by any chance developing it?  If not, I would suggest uninstalling it and finding an alternative.
