### ISSUE TITLE
Uncaught Error: spawn /usr/local/share/atom/atom (deleted) ENOENT

### ISSUE THREAD

**Issue by scippio** [atom/atom#9700]
1. Just run

**Atom Version**: 1.4.0-dev-548c85e
**System**: linux 4.2.5-1-ARCH
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: spawn /usr/local/share/atom/atom (deleted) ENOENT

``````
At events.js:141

Error: spawn /usr/local/share/atom/atom (deleted) ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/usr/local/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/usr/local/share/atom/resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/usr/local/share/atom/resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/usr/local/share/atom/resources/app.asar/src/window-load-settings-helpers.js:27:52)
``.

### Config

```json
{
  "core": {
    "projectHome": "/home/scippio/projects",
    "themes": [
      "nucleus-dark-ui",
      "gruvbox"
    ],
    "disabledPackages": [
      "rainbow-extensions",
      "rename-tabs",
      "foldername-tabs",
      "color-tabs-regex",
      "terminal-plus",
      "symbols-view",
      "tree-view-git-branch",
      "minimap-autohide",
      "test-status"
    ],
    "autoHideMenuBar": true,
    "audioBeep": false,
    "packagesWithKeymapsDisabled": [
      "git-control",
      "git-log",
      "tool-bar",
      "minimap",
      "multirow-tabs",
      "git-plus",
      "highlight-line",
      "maximize-panes",
      "atom-ctags",
      "test-status",
      "tab-switcher",
      "move-panes",
      "highlight-selected",
      "wercker-status"
    ],
    "openEmptyEditorOnStart": false
  },
  "editor": {
    "invisibles": {},
    "fontSize": 10,
    "tabLength": 4
  }
}
``````
### Installed Packages

``` coffee
# User
atom-ctags, v4.4.1
atom-no-tab-close-button, v1.0.0
atom-terminal-panel, v4.4.4
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autohide-tree-view, v0.25.1
color-tabs, v0.1.8
file-icons, v1.6.11
git-log, v0.4.1
gruvbox, v1.0.5
highlight-line, v0.11.0
highlight-selected, v0.11.1
line-count-status, v0.0.3
minimap, v4.16.1
minimap-git-diff, v4.1.8
nucleus-dark-ui, v0.6.12
pain-split, v1.4.0
pigments, v0.19.0
pretty-json, v0.4.1
scippio-test-status, v0.35.0
symbols-tree-view, v0.10.1
tool-bar, v0.1.9
tool-bar-main, v0.0.8
travis-ci-status, v0.18.0
wercker-status, v1.0.6

# Dev
No dev packages
```

**Comment by rbottema** [comment]
Probably a duplicate of #9559

**Comment by 50Wliu** [comment]
> Probably a duplicate of #9559

Not in this case as #9559 is Mac-only.
