### ISSUE TITLE
Failed to activate the toggle-invisibles package

### ISSUE THREAD

**Issue by r12r** [atom/atom#9726]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the toggle-invisibles package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:22:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:490:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "feedback",
      "background-tips",
      "css-color-underline",
      "atom-typescript",
      "emmet",
      ".bin",
      "tree-folder-split",
      "atom-bootstrap3",
      "better-handlebars"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-light-syntax"
    ]
  },
  "editor": {
    "autoIndentOnPaste": false,
    "invisibles": {},
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
atom-ternjs, v0.8.4
bracket-matcher, v0.79.0
file-icons, v1.6.12
linter, v1.11.2
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
linter-less, v2.2.0
minimap, v4.16.1
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.2
minimap-linter, v1.0.0
toggle-invisibles, v0.1.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The toggle-invisibles package appears to have been unpublished.  I would suggest uninstalling it and finding an alternative.
