### ISSUE TITLE
Uncaught Error: undefined group option

### ISSUE THREAD

**Issue by dcvz** [atom/atom#9733]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.2
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: undefined group option

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:31

Error: undefined group option
    at Error (native)
    at Scanner.module.exports.Scanner.createScanner (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:31:24)
    at Scanner.module.exports.Scanner.getScanner (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:37:31)
    at Scanner.module.exports.Scanner.findNextMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:56:22)
    at Rule.module.exports.Rule.findNextMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/rule.js:99:28)
    at Rule.module.exports.Rule.getNextTags (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/rule.js:141:21)
    at Grammar.module.exports.Grammar.tokenizeLine (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar.js:150:44)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:546:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:532:19)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:292:43)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:269:26
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47
```
### Commands

```
     -0:11.6.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:09.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:06.7.0 encoding-selector:show (atom-text-editor.editor)
  4x -0:05.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 grammar-selector:show (atom-text-editor.editor)
     -0:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "preferredLineLength": 160,
    "showIndentGuide": true,
    "fontSize": 12
  }
}
```
### Installed Packages

``` coffee
# User
highlight-selected, v0.11.1
ios, v0.1.0
language-jade, v0.6.2
linter, v1.11.2
linter-flake8, v1.9.2
linter-javac, v1.3.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
What grammar were you switching to? Likely an issue with the grammar, but we should be better about identifying it.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/9733#issuecomment-158661045. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
