### ISSUE TITLE
Update coffeescript version

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#9739]
atom /atom has the dependency `coffee-script": "1.8.0` in package.json.  1.8.0 is over a year old.  1.9.0 introduced a lot of improvements including generators and the yield statement.  I have a package that would *really* benefit from generators.

Should I put in a pull request for this?

**Comment by jeancroy** [comment]
Also note, looking at the change log, that 1.9.0 had 3 bugfix release. 
1.9.3 is worth consideration if going this way.

**Comment by vojtatranta** [comment]
Can you guys please give me some advice related to coffee-script version?
I build project on top of atom/electron and sometimes I get error when I use eg. interpolation in key while creating new object using "literal" like this:
```
obj =
  "this-is-#{key}": value
```
And it happens when I just checkout to another branch, wich is really odd.
Interpolation in key was added in coffee-script 1.9.1. I set this version to be installed in package.json in root of project and event when I require coffee-script right in the app window, it shows 1.9.1, but script is not compiled with this version, otherwise I would not get this error.
Do you have any idea how I should update coffee-script reliably?

**Comment by mark-hahn** [comment]
Are we doomed to live with an outdated coffeescript now that ES6 is the new in thing?  It doesn't seem fair that ES6 people get generators when we coffeescript devotees don't get generators (and many other features) that have been available in coffeescript for over a year.

How hard is it to update coffeescript in Atom?  It is backwards compatible so no old Atom code needs changing.  Is it something I could do in a PR?

**Comment by jeancroy** [comment]
Maybe you can try updating coffescript version, rebuilding atom and running the test suite to see what if anything breaks ? I know jasmine is also stuck on a old version, maybe it's linked ?

**Comment by mark-hahn** [comment]
> rebuilding atom and running the test suite

I've never done this before but I should give it a try.  Can you point me
to some docs on how to do this on linux?

**Comment by 50Wliu** [comment]
@mark-hahn https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md
Make sure you have all the dependencies, then just `script/build && sudo script/grunt install`.

**Comment by lee-dohm** [comment]
> I know jasmine is also stuck on a old version, maybe it's linked ?

@jeancroy No, basically we can't upgrade Jasmine versions without breaking the tests for pretty much every Atom package and all third-party packages. If you look at the PRs for atom/atom, you'll see a couple abandoned attempts to do this.

**Comment by mark-hahn** [comment]
@jeancroy or @50Wliu: How do I run the test suite?  I couldn't find anything about it in the flight manual.

**Comment by jeancroy** [comment]
I think 'apm test'

**Comment by lee-dohm** [comment]
To run the full test suite, you can do `script/test` at the command line in
the root of the core Atom repository.

**Comment by 50Wliu** [comment]
Alternatively...`atom --test spec`, just as you would for any other package.

**Comment by mark-hahn** [comment]
Thanks to both of you...

**Comment by mark-hahn** [comment]
I'm sorry to be a pain, but I'm having trouble running the test suite.  When I run `script/test` it does a complete build (is this normal?) and then ends with the console output below.  There is no indication that any test was performed.

```
<<< a lot clipped >>>

Running "lesslint:src" (lesslint) task
>> 29 files lint free.
Running "generate-asar" task
Running "mkdeb" task
>> Created /tmp/atom-build/atom-1.5.0-beta0-amd64.deb
Running "publish-build" task
Running "upload-assets" task
Done, without errors.
```

When I use the other method `atom --test spec` in the atom directory it does something totally different.  It crashes (see below) while trying to open an X window.

```
Error: auto-updater is not implemented on this platform
    at Object.<anonymous> (/usr/local/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:11:13)
    at Object.<anonymous> (/usr/local/share/atom/resources/atom.asar/browser/api/lib/auto-updater.js:14:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at AutoUpdateManager.module.exports.AutoUpdateManager.setupAutoUpdater (/usr/local/share/atom/resources/app.asar/src/browser/auto-update-manager.js:62:23)
    at /usr/local/share/atom/resources/app.asar/src/browser/auto-update-manager.js:53:24
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at NavigationController.loadUrl (/usr/local/share/atom/resources/atom.asar/browser/api/lib/navigation-controller.js:59:24)
    at EventEmitter.webContents.(anonymous function) [as loadUrl] (/usr/local/share/atom/resources/atom.asar/browser/api/lib/web-contents.js:81:27)
    at BrowserWindow.loadUrl (/usr/local/share/atom/resources/atom.asar/browser/api/lib/browser-window.js:121:37)
    at AtomWindow.module.exports.AtomWindow.setLoadSettings (/usr/local/share/atom/resources/app.asar/src/browser/atom-window.js:124:33)
    at new AtomWindow (/usr/local/share/atom/resources/app.asar/src/browser/atom-window.js:110:12)
    at AtomApplication.module.exports.AtomApplication.runTests (/usr/local/share/atom/resources/app.asar/src/browser/atom-application.js:880:14)
    at AtomApplication.module.exports.AtomApplication.openWithOptions (/usr/local/share/atom/resources/app.asar/src/browser/atom-application.js:121:21)
    at new AtomApplication (/usr/local/share/atom/resources/app.asar/src/browser/atom-application.js:111:14)
    at createAtomApplication (/usr/local/share/atom/resources/app.asar/src/browser/atom-application.js:60:16)
    at Function.module.exports.AtomApplication.open (/usr/local/share/atom/resources/app.asar/src/browser/atom-application.js:63:9)
    at EventEmitter.<anonymous> (/usr/local/share/atom/resources/app.asar/src/browser/main.js:55:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
[2170:0115/144618:INFO:CONSOLE(85)] "Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'atom-styles'. A type with that name is already registered.
  at Error (native)
  at Object.<anonymous> (/root/dev/apps/atom/src/styles-element.coffee:117:43)
  at Object.<anonymous> (/root/dev/apps/atom/src/styles-element.coffee:1:1)
  at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (/usr/local/share/atom/resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/root/dev/apps/atom/src/atom-environment.coffee:12:17)
  at Object.<anonymous> (/root/dev/apps/atom/src/atom-environment.coffee:1:1)
  at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (/usr/local/share/atom/resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/root/dev/apps/atom/spec/atom-environment-spec.coffee:6:19)
  at Object.<anonymous> (/root/dev/apps/atom/spec/atom-environment-spec.coffee:1:1)
  at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (/usr/local/share/atom/resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at requireSpecs (/usr/local/share/atom/resources/app.asar/spec/jasmine-test-runner.js:96:9)
  at module.exports (/usr/local/share/atom/resources/app.asar/spec/jasmine-test-runner.js:49:7)
  at module.exports (/usr/local/share/atom/resources/app.asar/src/initialize-test-window.js:71:17)
  at setupWindow (file:///usr/local/share/atom/resources/app.asar/static/index.js:86:5)
  at window.onload (file:///usr/local/share/atom/resources/app.asar/static/index.js:41:9)
", source: /usr/local/share/atom/resources/app.asar/src/initialize-test-window.js (85)
Running exit commands...
/usr/bin/xinit: connection to X server lost
waiting for X server to shut down (EE) Server terminated successfully (0). Closing log file.
```

**Comment by mark-hahn** [comment]
FYI, when I just run `Atom --dev .` in the atom folder the atom app loads fine.  So it only fails with `--test spec`.

**Comment by mark-hahn** [comment]
Can I test using the online testing that releasing uses?  Would it show where the errors come from?

**Comment by 50Wliu** [comment]
@mark-hahn Yes, it should.

**Comment by EddyLuten** [comment]
@mark-hahn did you get this to work by any chance?

**Comment by mark-hahn** [comment]
I was unable to run the atom tests locally.  I never tried using any online
tests.

**Comment by 50Wliu** [comment]
@mark-hahn for the "failed to register element" error you may want to check out #10719.

**Comment by danielbayley** [comment]
CoffeeScript [1.11.0](https://github.com/jashkenas/coffeescript/issues/3162#event-801317152) was just released which supports ES6 `import`/`export` 👍

Pretty please can we update Atom's version?

**Comment by 50Wliu** [comment]
> Pretty please can we update Atom's version?

We're doing some preliminary work on that in #12189.  No promises though.
