### ISSUE TITLE
Failed to load the javascript-snippets package

### ISSUE THREAD

**Issue by pochi-sato** [atom/atom#9744]
[Enter steps to reproduce below:]

1. open atom ver 1.0
2. restart and install

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to load the javascript-snippets package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "black-ui",
      "one-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "projectHome": "/Users/pochi/Documents/Dropbox/develop/devDrop/gitLocal",
    "disabledPackages": [
      "vim-mode"
    ]
  },
  "editor": {
    "fontSize": 18,
    "fontFamily": "Source Code Pro",
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
black-ui, v0.2.2
javascript-snippets, v0.3.1
language-scala, v0.3.0
linter-scalac, v0.3.1
one-dark-syntax, v1.1.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please update `javascript-snippets` to the latest version, currently 1.0.0.
