### ISSUE TITLE
Literate CoffeeScript files crashing with an "unmatched parenthesis" error

### ISSUE THREAD

**Issue by vijithassar** [atom/atom#9752]
Started randomly getting this problem last night, did a clean reinstall of Atom and it still persists. These files work after they are hand-edited and converted to regular .coffee. This same problem [has previously occurred with PHP](https://github.com/atom/atom/issues/5565).

Steps to reproduce:

1. open a Literate CoffeeScript file with the .litcoffee extension

**Atom Version**: 1.2.3
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: end pattern with unmatched parenthesis

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:770

Error: end pattern with unmatched parenthesis
    at Error (native)
    at Scanner.module.exports.Scanner.createScanner (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:31:24)
    at Scanner.module.exports.Scanner.getScanner (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:37:31)
    at Scanner.module.exports.Scanner.findNextMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:56:22)
    at Rule.module.exports.Rule.findNextMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/rule.js:99:28)
    at Rule.module.exports.Rule.getNextTags (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/rule.js:141:21)
    at Grammar.module.exports.Grammar.tokenizeLine (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar.js:150:44)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:546:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:532:19)
    at TokenizedBuffer.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:485:34)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLinesForRows (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:494:10)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:376:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:69:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:645:20)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:799:16)
```

### Commands

```
     -0:10.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:01.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:01.2.0 editor:indent (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
minimap, v4.16.1
open-recent, v4.0.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This has already been fixed and should be out in the next 1.2 patch release.  If you need the fix *now*, execute `apm install language-coffee-script` from the command line.
