### ISSUE TITLE
Uncaught AssertionError: undefined == true

### ISSUE THREAD

**Issue by keer007** [atom/atom#9777]
[Enter steps to reproduce below:]

1. Install nuclide from source (because nuclide package install is currently broken)
2. Click 'Add remote project folder', use password to login to remote host and then command to run is 'nuclide-start-server -k -p 9090'

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught AssertionError: undefined == true

```
At assert.js:89

AssertionError: undefined == true
  at SshHandshake._updateServerInfo (/Users/sriramj/dev/nuclide/pkg/nuclide/remote-connection/lib/SshHandshake.js:187:7)
  at Channel.<anonymous> (/Users/sriramj/dev/nuclide/pkg/nuclide/remote-connection/lib/SshHandshake.js:261:22)
  at emitOne (events.js:77:13)
  at Channel.emit (events.js:169:7)
  at SSH2Stream.<anonymous> (/Users/sriramj/dev/nuclide/pkg/nuclide/remote-connection/node_modules/ssh2/lib/Channel.js:124:14)
  at SSH2Stream.g (events.js:260:16)
  at emitNone (events.js:67:13)
  at SSH2Stream.emit (events.js:166:7)
  at parsePacket (/Users/sriramj/dev/nuclide/pkg/nuclide/remote-connection/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3438:10)
  at SSH2Stream._transform (/Users/sriramj/dev/nuclide/pkg/nuclide/remote-connection/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:555:13)
  at SSH2Stream.Transform._read (_stream_transform.js:167:10)
  at SSH2Stream._read (/Users/sriramj/dev/nuclide/pkg/nuclide/remote-connection/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
  at SSH2Stream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:292:12)
  at writeOrBuffer (_stream_writable.js:278:5)
  at SSH2Stream.Writable.write (_stream_writable.js:207:11)
  at Socket.ondata (_stream_readable.js:525:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)

```

### Commands

```
     -3:19.6.0 nuclide-remote-projects:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-zenburn-theme.theme-one-dark-ui)
     -3:16.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:14.7.0 nuclide-remote-projects:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-zenburn-theme.theme-one-dark-ui)
     -0:12.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "zenburn-theme"
    ],
    "disabledPackages": [
      "tree-view"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 12,
    "fontFamily": "Menlo"
  }
}
```

### Installed Packages

```coffee
# User
emacs-plus, v0.9.9
hyperclick, v0.0.0
nuclide-arcanist, v0.0.0
nuclide-blame, v0.0.0
nuclide-blame-provider-hg, v0.0.0
nuclide-blame-ui, v0.0.0
nuclide-buck-files, v0.0.0
nuclide-busy-signal, v0.0.0
nuclide-clang-atom, v0.0.0
nuclide-code-format, v0.0.0
nuclide-code-highlight, v0.0.0
nuclide-debugger-atom, v0.0.0
nuclide-debugger-hhvm, v0.0.0
nuclide-debugger-lldb, v0.0.0
nuclide-debugger-node, v0.0.0
nuclide-diagnostics-store, v0.0.0
nuclide-diagnostics-ui, v0.0.0
nuclide-diff-view, v0.0.0
nuclide-file-tree, v0.0.0
nuclide-file-watcher, v0.0.0
nuclide-find-references, v0.0.0
nuclide-flow, v0.0.0
nuclide-fuzzy-filename-provider, v0.0.0
nuclide-hack, v0.0.0
nuclide-hack-symbol-provider, v0.0.0
nuclide-health, v0.0.0
nuclide-hg-repository, v0.0.0
nuclide-home, v0.0.0
nuclide-installer, v0.0.0
nuclide-language-hack, v0.0.0
nuclide-objc, v0.0.0
nuclide-ocaml, v0.0.0
nuclide-open-filenames-provider, v0.0.0
nuclide-quick-open, v0.0.0
nuclide-recent-files-provider, v0.0.0
nuclide-recent-files-service, v0.0.0
nuclide-remote-projects, v0.0.0
nuclide-test-runner, v0.0.0
nuclide-toolbar, v0.0.0
nuclide-type-hint, v0.0.0
nuclide-url-hyperclick, v0.0.0
react, v0.12.10
zenburn-theme, v1.3.0

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
Could you reopen this issue on the [https://github.com/facebook/nuclide](nuclide) repo?
