### ISSUE TITLE
Failed to load the jekyll-new-post package

### ISSUE THREAD

**Issue by bernars** [atom/atom#9778]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to load the jekyll-new-post package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:7:3
    at Object.<anonymous> (<anonymous>:7:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Users/sheribernard/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
documentation-renderer, v0.2.1
jekyll-new-post, v0.1.2
linter, v1.11.2
linter-js-yaml, v1.2.4
linter-write-good, v0.6.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The jekyll-new-post package no longer appears to be maintained.  I would suggest uninstalling it and finding an alternative.

See Arcath/jekyll-new-post#11 for the duplicate issue.
