### ISSUE TITLE
Failed to activate the atom-color-highlight package

### ISSUE THREAD

**Issue by santanajames** [atom/atom#9794]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the atom-color-highlight package

```
At Cannot read property 'eachEditorView' of undefined

TypeError: Cannot read property 'eachEditorView' of undefined
    at AtomColorHighlight.activate (<anonymous>:34:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:490:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autoflow",
      "minimap"
    ],
    "themes": [
      "atom-dark-ui",
      "tomorrow-night-eighties"
    ]
  },
  "editor": {
    "fontSize": 14,
    "preferredLineLength": 2000
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v2.0.14
autocomplete-plus, v0.22.3
merge-conflicts, v1.2.8
tomorrow-night-eighties, v0.1.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The atom-color-highlight package appears to have been unpublished.  I would suggest uninstalling it and finding an alternative.
