### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/neuromancer/Downloads/Atom.app'

### ISSUE THREAD

**Issue by marksdk** [atom/atom#9813]
1. Run Atom.app from the Downloads folder
2. While running, move Atom.app to Applications-folder
3. Breakage :grin: (not sure what else to expect, but consider the bug filed)

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/neuromancer/Downloads/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/neuromancer/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/neuromancer/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/neuromancer/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Users/neuromancer/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
```

### Commands

```
     -3:16.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:10.5.0 project-find:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:10.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:42.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:41.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:16.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:14.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:12.1.0 core:close (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:52.6.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  5x -0:48 find-and-replace:find-next (atom-text-editor.editor.mini.is-focused)
     -0:46.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:46.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:27.6.0 project-find:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:23.3.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
     -0:22.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:22.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "projectHome": "~/web"
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "Input Mono",
    "fontSize": 16,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Refs #9559 and #7399.  Pretty sure there was an issue for this before but I can't find it right now.

**Comment by yyanavichus** [comment]
I had the same issue with go-config package (as error message states). The fix was is to open file directory, not just file. Before that another directory was opened and go code was opened as a separate file. Hope this helps

**Comment by Ben3eeE** [comment]
Is this and https://github.com/atom/atom/issues/10774 the same issue?

**Comment by 50Wliu** [comment]
Yep, thanks!
