### ISSUE TITLE
Atom does not launch unless done by `sudo atom` in terminal - Ubuntu 14.04

### ISSUE THREAD

**Issue by lancelafontaine** [atom/atom#9822]
As the title suggests, after installing Atom for the first time on an Ubuntu 14.04 machine, Atom does not load when either the icon is clicked or when launched by the terminal with `atom`. The icon pops up in the launcher, but no window is ever launched. 

After filtering for the word `atom` in `htop`, I can see that the following processes are being run on my system (see image below).

When trying to launch Atom in safe mode, I get the following output, followed by my terminal hanging indefinitely.

```
[03:37 PM] [~] $ /usr/bin/atom: line 106: /home/lancelafontaine/.atom/nohup.out: Permission denied
App load time: 275ms


```

However, when typing `sudo atom` in the terminal, a window does end up launching (see image).

In the Atom menu in the top bar, there are the following options: `[Check for Update, Reload, Close Window, Toggle Dev Tools, Quit]`

The Dev Tools console displays the following message.

```
Error: EACCES: permission denied, open '/home/lancelafontaine/.atom/compile-cache/less/df1b7fbc57dbeed23a8f1f8de95b4dfebcc06066/imports.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.writeFileSync (fs.js:1171:15)
    at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:155:17)
    at LessCache.module.exports.LessCache.setImportPaths (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:113:12)
    at new LessCache (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:32:12)
    at new LessCompileCache (/usr/share/atom/resources/app.asar/src/less-compile-cache.js:20:20)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/usr/share/atom/resources/app.asar/src/theme-manager.js:270:26)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/usr/share/atom/resources/app.asar/src/theme-manager.js:257:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (/usr/share/atom/resources/app.asar/src/theme-manager.js:174:24)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (/usr/share/atom/resources/app.asar/src/theme-manager.js:237:12)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (/usr/share/atom/resources/app.asar/src/theme-manager.js:232:19)
    at new AtomEnvironment (/usr/share/atom/resources/app.asar/src/atom-environment.js:246:19)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:17)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:49:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:79:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:35:9)handleSetupError @ index.js:56
```

**Reproduction Steps and Observed Behavior:**
1. Whenever launched via Launcher icon, no window appears.
2. Whenever launched via terminal with `atom`, no window appears.

**Expected behavior:**

Expected behaviour is that the editor launches a window and loads.

**Screenshots and GIFs**

![screenshot from 2015-11-25 15 20 19](https://cloud.githubusercontent.com/assets/1548285/11408590/2a926d3c-9388-11e5-9416-274c1d13d36a.png)

However, when typing `sudo atom` in the terminal, a window does end up launching (see image).

![screenshot from 2015-11-25 15 22 37](https://cloud.githubusercontent.com/assets/1548285/11408825/a4db0bc0-9389-11e5-8073-baf0f159270b.png)

**Atom version:** 1.2.4
**OS and version:** Ubuntu 14.04 LTS

**Installed packages:**

This occurs when launching Atom for the first time after install. Only the default packages are included in atom.

**Additional information:**
- Problem can be reproduced in safe mode: Yes
- Problem started happening recently, didn't happen in an older version of Atom: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes
- Problem happens with all files and projects, not only some files or projects: Yes

**Comment by lee-dohm** [comment]
This happens often when there are permission problems with either the user's home directory or with the `~/.atom` directory. How did you install Atom?

**Comment by lancelafontaine** [comment]
I installed Atom from the .deb file on the website. I used `gdebi` to install it.

**Comment by lee-dohm** [comment]
Can you try the following?

1. Uninstalling that copy
1. Delete or move the `~/.atom` directory
1. Install Atom from the `deb` file using this command: `sudo dpkg --install atom-amd64.deb`

**Comment by lancelafontaine** [comment]
The machine that is giving me this issue is not available to me at the moment, so I'll only be able to post a full answer tomorrow. However, I can say that:
- I uninstalled Atom with both `apt-get remove` and `apt-get purge`, with no success.
- I `rm -rf`'ed `.atom/` and tried reinstalling from the .deb with no luck.

I will try installing it with `dpkg` tomorrow and provide updates here.

**Comment by lancelafontaine** [comment]
After uninstalling Atom today with, I found this `dpkg` warning:

```
[10:19 AM] [Downloads] $ sudo apt-get purge atom
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  atom*
0 upgraded, 0 newly installed, 1 to remove and 20 not upgraded.
After this operation, 218 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 303500 files and directories currently installed.)
Removing atom (1.2.4) ...
dpkg: warning: while removing atom, directory '/usr/share/atom/resources/app/apm' not empty so not removed
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
```

The `.atom/` directory was still present and seemingly have the same contents and directory structure as usual.

I `rm -rf`ed `.atom/` and reinstalled with `dpkg`:

```
[10:27 AM] [Downloads] $ sudo dpkg --install atom-amd64.deb
Selecting previously unselected package atom.
(Reading database ... 300477 files and directories currently installed.)
Preparing to unpack atom-amd64.deb ...
Unpacking atom (1.2.4) ...
Setting up atom (1.2.4) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
```

The bug is still present and the problem was not resolved.

**Comment by 50Wliu** [comment]
Looks like we're still assigning incorrect permissions to the `./atom` folder.

**Comment by lancelafontaine** [comment]
I have a feeling that it may be caused by a configuration or a different package on my system.

I tried downloading the 0.211.0 .deb from [here](https://github.com/atom/atom/releases/tag/v0.211.0), and I'm having a similar experience except that this time, even `sudo atom` doesn't launch a window.

**Comment by lancelafontaine** [comment]
After uninstalling with `sudo apt-get purge atom`, then manually removing `~/.atom/`, `/usr/bin/apm`, and `/usr/share/atom/`, I tried to reinstall the 1.2.4 atom .deb. I now get the following permissions error:

```
Error: EACCES: permission denied, open '/home/lancelafontaine/.atom/config.cson'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.writeFileSync (fs.js:1171:15)
    at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at Object.module.exports.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:224:17)
    at Config.module.exports.Config.loadUserConfig (/usr/share/atom/resources/app.asar/src/config.js:424:14)
    at Config.module.exports.Config.load (/usr/share/atom/resources/app.asar/src/config.js:379:12)
    at new AtomEnvironment (/usr/share/atom/resources/app.asar/src/atom-environment.js:245:19)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:17)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:49:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:79:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:35:9)handleSetupError @ index.js:56
```

**Comment by 50Wliu** [comment]
As a temporary workaround you should be able to get Atom working by removing `.atom` and then running Atom as a normal user.

**Comment by lancelafontaine** [comment]
@50Wliu After deleting `.atom/` and launching Atom again via `atom` I still don't get a window. In fact, the `.atom/` directory regenerates itself as soon as I specify the command `atom`. 

Also, in this case, doing `sudo atom` after deleting `~/.atom/` no longer launches a window as it used to. The `atom/` directory also regenerates itself after the command.

**Comment by lancelafontaine** [comment]
I've found a solution that takes me 95% of the way there. 

After uninstalling Atom as seen below, and then reinstalling it with the .deb above:

```
sudo rm /usr/local/bin/atom
sudo rm /usr/local/bin/apm
rm -rf ~/atom
rm -rf ~/.atom
rm -rf ~/.config/Atom-Shell
rm -rf ~/.config/Atom
sudo rm -rf /usr/local/share/atom/
```

I am now able to launch the Atom window just by clicking on the item or calling `atom` on the command line.

The last `bug` I have is that after the Atom window launches, I have the following error:

```
Unable to watch path: config.cson. Make sure you have permissions to /home/lancelafontaine/.atom/config.cson. On linux there are currently problems with watch sizes. See this document for more info.
```

It seems as though I do have read access to the `config.cson`

```
[11:48 AM] [.atom] $ ll
total 52
drwxrwxr-x  7 lancelafontaine lancelafontaine 4096 Dec 14 11:43 ./
drwxr-xr-x 52 lancelafontaine lancelafontaine 4096 Dec 14 11:43 ../
drwxrwxr-x  2 lancelafontaine lancelafontaine 4096 Dec 14 11:43 .apm/
drwxrwxr-x  2 lancelafontaine lancelafontaine 4096 Dec 14 11:43 blob-store/
drwxrwxr-x  6 lancelafontaine lancelafontaine 4096 Dec 14 11:43 compile-cache/
-rw-rw-r--  1 lancelafontaine lancelafontaine   41 Dec 14 11:43 config.cson
-rw-rw-r--  1 lancelafontaine lancelafontaine   41 Dec 14 11:43 .gitignore
-rw-rw-r--  1 lancelafontaine lancelafontaine  386 Dec 14 11:43 init.coffee
-rw-rw-r--  1 lancelafontaine lancelafontaine 1004 Dec 14 11:43 keymap.cson
drwxrwxr-x  2 lancelafontaine lancelafontaine 4096 Dec 14 11:43 packages/
-rw-rw-r--  1 lancelafontaine lancelafontaine  698 Dec 14 11:43 snippets.cson
drwxrwxr-x  2 lancelafontaine lancelafontaine 4096 Dec 14 11:43 storage/
-rw-rw-r--  1 lancelafontaine lancelafontaine  762 Dec 14 11:43 styles.less
```

**Comment by HadiLatifi** [comment]
I had the same problem. I did something that might be unsafe though:
I gave the .atom/compile-cache folder full access, with -R option, which gives all subdirectories and contents the same permission:
sudo chmod -R 777 compile-cache
the 777 is the full permission key number, you could find more help on web about it.
other permission types may work as well, but I didn't try.

**Comment by MechaCoder** [comment]
I had some successes useing but I had a small issue with the package manger but i found that useing the command `sudo chmod -R  777  ~/.atom/` I did try 755 but did not work :-(

**Comment by x-wf** [comment]
I'm using Lubuntu 16.04, and I was having this problem with Atom.

A temporary workaround, to simplify the process
Go to the main Menu -> Programming -> (right click) Atom -> Properties
Navigate to Desktop Entry, and change
`/opt/atom/atom %F`
to
`sudo /opt/atom/atom %F`
And make sure _Execute in terminal emulator_ is **checked**.

**Comment by MechaCoder** [comment]
Dose that Work with accounts passwords?

On 25 Oct 2016 18:09, "x-wf" <notifications@github.com> wrote:

I'm using Lubuntu 16.04, and I was having this problem with Atom.

A temporary workaround, to simplify the process
Go to the main Menu -> Programming -> (right click) Atom -> Properties
Navigate to Desktop Entry, and change
/opt/atom/atom %F
to
sudo /opt/atom/atom %F
And make sure *Execute in terminal emulator* is *checked*.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/atom/atom/issues/9822#issuecomment-256098029>, or mute
the thread

**Comment by x-wf** [comment]
Yes, I gave that solution special for users with passwords.

**Comment by smarv** [comment]
why not just 
$ sudo chown -R $USER:$USER /home/$USER/.atom

**Comment by chris-fry** [comment]
I had this issue on Ubuntu 16.04 (Xenial). Changing owner to myself didn't resolve it, but refining @HadiLatifi's to be a bit more secure suggestion did.

`sudo chmod -R 770 ~/.atom/compile-cache`

**Comment by thomasjo** [comment]
Unable to reproduce this. Closing since this has been stale for more than 6 months.
