### ISSUE TITLE
Failed to load the status-stats package

### ISSUE THREAD

**Issue by ggamel** [atom/atom#9826]
1. Open Atom.app
2. See the error.
3. I submitted this Issue per the request of Atom.app

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to load the status-stats package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "Zen",
      "Rdio",
      "Siteleaf"
    ]
  },
  "editor": {
    "fontFamily": "Source Code Pro",
    "showInvisibles": true,
    "showIndentGuide": true,
    "softWrap": true,
    "scrollPastEnd": true,
    "invisibles": {},
    "fontSize": 19
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
autocomplete-clang, v0.8.8
autocomplete-emojis, v2.2.2
bezier-curve-editor, v0.7.2
color-picker, v2.0.13
editor-stats, v0.17.0
file-icons, v1.6.12
language-liquid, v0.4.0
language-qml, v1.0.0
language-qtpro, v0.5.0
language-svg, v0.9.0
minimap, v4.16.1
save-session, v0.15.7
status-stats, v0.1.0
svg-preview, v0.6.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The status-stats package no longer appears to be maintained.  I would suggest uninstalling it and finding an alternative.  See cjoh/status-stats#10 for the duplicate issue.

**Comment by ggamel** [comment]
Thanks, @50Wliu. One of the few instances where I blindly mashed the button in Atom.app to submit a bug report.

**Comment by 50Wliu** [comment]
@ggamel No worries :).  The reason it got reported here was because of a long-standing bug where Atom blindly told everyone to report package load errors on atom/atom instead of on the package repo.  Thankfully it got fixed and will be out in the next version :smile:.
