### ISSUE TITLE
Failed to load the textstats package

### ISSUE THREAD

**Issue by eggya** [atom/atom#9830]
[Enter steps to reproduce below:]

1. `$ atom . ` 
2. Atom would then open with the warning

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to load the textstats package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".*"
    ],
    "themes": [
      "atom-dark-ui",
      "twilight"
    ],
    "disabledPackages": [
      "js-refactor"
    ]
  },
  "editor": {
    "fontFamily": "Monaco",
    "fontSize": 15,
    "preferredLineLength": 120,
    "invisibles": {},
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
cucumber, v0.5.0
file-icons, v1.6.11
highlight-line, v0.11.0
inline-autocomplete, v1.1.0
language-textile, v0.2.0
refactor, v0.6.0
textstats, v0.1.0
twilight, v0.3.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The textstats package no longer appears to be maintained.  I would suggest uninstalling it and finding an alternative.  See cjoh/atom-textstats#5 for the duplicate issue.
