### ISSUE TITLE
Failed to activate the language-golo package

### ISSUE THREAD

**Issue by jponge** [atom/atom#9835]
Just open Atom with the plugin installed.

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the language-golo package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:3:23)
    at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:490:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "projectHome": "/Users/jponge/Code"
  },
  "editor": {
    "preferredLineLength": 100,
    "softWrap": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
asciidoc-preview, v0.6.0
language-antlr, v0.1.0
language-asciidoc, v0.12.0
language-docker, v1.1.3
language-dockerfile, v0.1.0
language-golo, v0.11.0
language-gradle, v0.0.3
language-groovy, v0.4.0
language-latex, v0.6.1
language-scala, v1.1.4
language-textile, v0.2.0
linter, v1.9.1
minimap, v4.15.0
monokai, v0.18.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The language-golo package no longer appears to be maintained.  I would suggest uninstalling it and finding an alternative.  See the duplicate issue at k33g/language-golo#5.
