### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by HoiJean** [atom/atom#9845]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At C:\Users\Jean\AppData\Local\atom\app-1.2.4\resources\app.asar\src\pane.js:825

ReferenceError: path is not defined
    at file:///C:/Users/Jean/.atom/init.coffee:14:12
    at Emitter.module.exports.Emitter.emit (C:\Users\Jean\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Jean\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1010:20)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\Jean\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1002:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\Jean\AppData\Local\atom\app-1.2.4\resources\app.asar\src\text-editor.js:557:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\Jean\AppData\Local\atom\app-1.2.4\resources\app.asar\src\pane.js:530:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\Jean\AppData\Local\atom\app-1.2.4\resources\app.asar\src\pane.js:513:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Jean\AppData\Local\atom\app-1.2.4\resources\app.asar\src\workspace.js:631:35)
    at atom-workspace.commandRegistry.add.core:save (C:\Users\Jean\AppData\Local\atom\app-1.2.4\resources\app.asar\src\register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Jean\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:260:29)
```

### Commands

```
     -0:15.6.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:15.2.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:14 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:12.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  4x -0:11.1.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:10.1.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:09.6.0 vim-mode:insert-after (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:08.7.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:02.9.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v2.0.0
cakephp-snippets, v0.6.1
cakephp3-snippets, v0.5.0
color-picker, v2.0.13
file-icons, v1.6.12
javascript-snippets, v1.0.0
jshint, v1.8.3
language-vue, v0.8.0
minimap, v4.16.2
php-composer-completion, v0.3.4
php-integrator-navigation, v0.2.3
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
The exception stack trace indicates that you have something in tour `init.coffee` script causing this error:

```
ReferenceError: path is not defined
    at file:///C:/Users/Jean/.atom/init.coffee:14:12
```

In other words, it's not a problem in Atom itself. Try removing everything from that file and restarting Atom.

**Comment by HoiJean** [comment]
Yes it worked, but you will have to edit init.coffee in a different editor, otherwise you won't be able to save the file

**Comment by izuzak** [comment]
You can also start Atom in [safe mode](https://github.com/atom/docs/blob/master/book/03-hacking-atom/sections/A01-debugging.asc#check-if-the-problem-shows-up-in-safe-mode).
