### ISSUE TITLE
Failed to activate the atom-zeal package

### ISSUE THREAD

**Issue by seNadir** [atom/atom#9848]
**Atom Version**: 1.2.4
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the atom-zeal package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (file:///C:/Users/Nadire/Downloads/atom-zeal-master/lib/atom-zeal.coffee:6:23)
    at Package.module.exports.Package.activateNow (C:\Users\Nadire\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:170:19)
    at C:\Users\Nadire\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:150:32
    at Package.module.exports.Package.measure (C:\Users\Nadire\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:92:15)
    at C:\Users\Nadire\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:143:26
    at Package.module.exports.Package.activate (C:\Users\Nadire\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Nadire\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package-manager.js:512:21)
    at C:\Users\Nadire\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package-manager.js:495:29
    at Config.module.exports.Config.transact (C:\Users\Nadire\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Nadire\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package-manager.js:490:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "autosave"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.0
aligner-php, v1.0.0
angularjs, v0.3.0
atom-material-ui, v0.5.20
atom-wordpress, v0.3.0
atom-zeal, v0.1.0
compare-files, v0.6.2
emmet, v2.3.13

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
The atom-zeal package no longer has a Github repo associated with it, and therefore cannot receive further updates.  I would suggest uninstalling it and finding an alternative.

(/cc @thedaniel: any chance you can take remove atom-zeal from atom.io as well? :bow:)

**Comment by seNadir** [comment]
It is, just in a another user repos
https://github.com/futhrevo/atom-zeal
I used apm to install it, first downloaded the package, unzip it then used `apm link` to install it

**Comment by 50Wliu** [comment]
In that case, it still hasn't been updated in over a year.  I'd still recommend for you to find another package.
