### ISSUE TITLE
Install any packages failed

### ISSUE THREAD

**Issue by Bantes** [atom/atom#9867]
Installing “minimap@4.16.2” failed.Hide output…

gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | linux | x64
gyp http GET https://atom.io/download/atom-shell/v0.34.0/node-v0.34.0.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at TCP.onread (net.js:559:19)
gyp ERR! System Linux 4.2.0-18-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.34.0" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /home/bantes/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

**Comment by saschagehlich** [comment]
Check your internet connection and / or try again later. Might have been a server hiccup.

**Comment by akring** [comment]
Same problem,and i tried with `--verbose`,this is output:
```
✘ Akring@lvjundeMacBook-Pro  ~  apm install dash --verbose
Installing dash to /Users/Akring/.atom/packages REQUEST { url: 'https://atom.io/api/packages/dash',
 json: true,
 retries: 4,
 proxy: null,
 strictSSL: true,
 headers: { 'User-Agent': 'npm/2.13.3 node/v0.10.40 darwin x64' },
 callback: [Function],
 method: 'GET' }
REQUEST make request https://atom.io/api/packages/dash
REQUEST onRequestResponse https://atom.io/api/packages/dash 200 { server: 'Cowboy',
 connection: 'close',
 date: 'Fri, 18 Dec 2015 02:16:43 GMT',
 status: '200 OK',
 'strict-transport-security': 'max-age=631152000',
 'x-frame-options': 'DENY',
 'x-xss-protection': '1; mode=block',
 'x-content-type-options': 'nosniff',
 'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
 'content-type': 'application/json; charset=utf-8',
 etag: 'W/"d02b91b9b882cac8e036533b47c73e54"',
 'cache-control': 'max-age=0, private, must-revalidate',
 'x-request-id': 'e5a07f07-0e62-4026-b526-6b7f07890df3',
 'x-runtime': '0.018701',
 'x-rack-cache': 'miss',
 vary: 'Origin',
 via: '1.1 vegur' }
REQUEST finish init function https://atom.io/api/packages/dash
REQUEST response end https://atom.io/api/packages/dash 200 { server: 'Cowboy',
 connection: 'close',
 date: 'Fri, 18 Dec 2015 02:16:43 GMT',
 status: '200 OK',
 'strict-transport-security': 'max-age=631152000',
 'x-frame-options': 'DENY',
 'x-xss-protection': '1; mode=block',
 'x-content-type-options': 'nosniff',
 'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
 'content-type': 'application/json; charset=utf-8',
 etag: 'W/"d02b91b9b882cac8e036533b47c73e54"',
 'cache-control': 'max-age=0, private, must-revalidate',
 'x-request-id': 'e5a07f07-0e62-4026-b526-6b7f07890df3',
 'x-runtime': '0.018701',
 'x-rack-cache': 'miss',
 vary: 'Origin',
 via: '1.1 vegur' }
REQUEST end event https://atom.io/api/packages/dash
REQUEST has body https://atom.io/api/packages/dash 11898
REQUEST emitting complete https://atom.io/api/packages/dash
REQUEST { url: 'https://www.atom.io/api/packages/dash/versions/1.5.0/tarball',
 proxy: null,
 strictSSL: true,
 headers: { 'User-Agent': 'npm/2.13.3 node/v0.10.40 darwin x64' },
 method: 'GET',
 callback: undefined }
REQUEST make request https://www.atom.io/api/packages/dash/versions/1.5.0/tarball
REQUEST onRequestResponse https://www.atom.io/api/packages/dash/versions/1.5.0/tarball 302 { server: 'Cowboy',
 connection: 'close',
 date: 'Fri, 18 Dec 2015 02:16:46 GMT',
 status: '302 Found',
 'strict-transport-security': 'max-age=631152000',
 'x-frame-options': 'DENY',
 'x-xss-protection': '1; mode=block',
 'x-content-type-options': 'nosniff',
 'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
 location: 'https://codeload.github.com/blakeembrey/atom-dash/legacy.tar.gz/v1.5.0',
 'content-type': 'text/html; charset=utf-8',
 'cache-control': 'no-cache',
 'x-request-id': '24ce616e-1130-4134-a451-6dac463c5b6a',
 'x-runtime': '0.153470',
 'x-rack-cache': 'miss',
 vary: 'Origin',
 via: '1.1 vegur' }
REQUEST redirect https://codeload.github.com/blakeembrey/atom-dash/legacy.tar.gz/v1.5.0
REQUEST redirect to https://codeload.github.com/blakeembrey/atom-dash/legacy.tar.gz/v1.5.0
REQUEST {}
REQUEST make request https://codeload.github.com/blakeembrey/atom-dash/legacy.tar.gz/v1.5.0
REQUEST response end https://codeload.github.com/blakeembrey/atom-dash/legacy.tar.gz/v1.5.0 302 { server: 'Cowboy',
 connection: 'close',
 date: 'Fri, 18 Dec 2015 02:16:46 GMT',
 status: '302 Found',
 'strict-transport-security': 'max-age=631152000',
 'x-frame-options': 'DENY',
 'x-xss-protection': '1; mode=block',
 'x-content-type-options': 'nosniff',
 'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
 location: 'https://codeload.github.com/blakeembrey/atom-dash/legacy.tar.gz/v1.5.0',
 'content-type': 'text/html; charset=utf-8',
 'cache-control': 'no-cache',
 'x-request-id': '24ce616e-1130-4134-a451-6dac463c5b6a',
 'x-runtime': '0.153470',
 'x-rack-cache': 'miss',
 vary: 'Origin',
 via: '1.1 vegur' }
REQUEST onRequestResponse https://codeload.github.com/blakeembrey/atom-dash/legacy.tar.gz/v1.5.0 200 { 'content-length': '5963',
 'access-control-allow-origin': 'https://render.githubusercontent.com',
 'content-security-policy': 'default-src \'none\'',
 'x-xss-protection': '1; mode=block',
 'x-frame-options': 'deny',
 'x-content-type-options': 'nosniff',
 'strict-transport-security': 'max-age=31536000',
 vary: 'Authorization,Accept-Encoding',
 etag: '"9aaa78935d56acc9f75915356886f0ca75150b53"',
 'content-type': 'application/x-gzip',
 'content-disposition': 'attachment; filename=blakeembrey-atom-dash-v1.5.0-0-g9aaa789.tar.gz',
 date: 'Fri, 18 Dec 2015 02:16:48 GMT',
 'x-github-request-id': '758855C5:2F46:130B6544:56736C8F' }
REQUEST finish init function https://codeload.github.com/blakeembrey/atom-dash/legacy.tar.gz/v1.5.0
REQUEST response end https://codeload.github.com/blakeembrey/atom-dash/legacy.tar.gz/v1.5.0 200 { 'content-length': '5963',
 'access-control-allow-origin': 'https://render.githubusercontent.com',
 'content-security-policy': 'default-src \'none\'',
 'x-xss-protection': '1; mode=block',
 'x-frame-options': 'deny',
 'x-content-type-options': 'nosniff',
 'strict-transport-security': 'max-age=31536000',
 vary: 'Authorization,Accept-Encoding',
 etag: '"9aaa78935d56acc9f75915356886f0ca75150b53"',
 'content-type': 'application/x-gzip',
 'content-disposition': 'attachment; filename=blakeembrey-atom-dash-v1.5.0-0-g9aaa789.tar.gz',
 date: 'Fri, 18 Dec 2015 02:16:48 GMT',
 'x-github-request-id': '758855C5:2F46:130B6544:56736C8F' }
gyp info it worked if it ends with ok
gyp verb cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
gyp verb cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'install',
gyp verb cli   '--target=0.34.3',
gyp verb cli   '--dist-url=https://atom.io/download/atom-shell',
gyp verb cli   '--arch=x64',
gyp verb cli   '--ensure',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | darwin | x64
gyp verb command install []
gyp verb install input version string "0.34.3"
gyp verb install installing version: 0.34.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 0.34.3
gyp verb ensuring nodedir is created /Users/Akring/.atom/.node-gyp/.node-gyp/0.34.3
gyp verb created nodedir /Users/Akring/.atom/.node-gyp/.node-gyp/0.34.3
gyp http GET https://atom.io/download/atom-shell/v0.34.3/node-v0.34.3.tar.gz
REQUEST { uri: 'https://atom.io/download/atom-shell/v0.34.3/node-v0.34.3.tar.gz',
 headers: { 'User-Agent': 'node-gyp v2.0.2 (node v0.10.40)' },
 callback: undefined }
REQUEST make request https://atom.io/download/atom-shell/v0.34.3/node-v0.34.3.tar.gz
REQUEST onRequestResponse https://atom.io/download/atom-shell/v0.34.3/node-v0.34.3.tar.gz 302 { server: 'Cowboy',
 connection: 'close',
 date: 'Fri, 18 Dec 2015 02:16:50 GMT',
 status: '302 Found',
 'strict-transport-security': 'max-age=631152000',
 'x-frame-options': 'DENY',
 'x-xss-protection': '1; mode=block',
 'x-content-type-options': 'nosniff',
 'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
 location: 'http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz',
 'content-type': 'text/html; charset=utf-8',
 'cache-control': 'no-cache',
 'x-request-id': 'da4b7ec3-f0d8-408f-b518-4c840e810ccc',
 'x-runtime': '0.013130',
 'x-rack-cache': 'miss',
 via: '1.1 vegur' }
REQUEST redirect http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz
REQUEST redirect to http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz
REQUEST {}
REQUEST make request http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz
REQUEST response end http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz 302 { server: 'Cowboy',
 connection: 'close',
 date: 'Fri, 18 Dec 2015 02:16:50 GMT',
 status: '302 Found',
 'strict-transport-security': 'max-age=631152000',
 'x-frame-options': 'DENY',
 'x-xss-protection': '1; mode=block',
 'x-content-type-options': 'nosniff',
 'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
 location: 'http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz',
 'content-type': 'text/html; charset=utf-8',
 'cache-control': 'no-cache',
 'x-request-id': 'da4b7ec3-f0d8-408f-b518-4c840e810ccc',
 'x-runtime': '0.013130',
 'x-rack-cache': 'miss',
 via: '1.1 vegur' }
gyp WARN install got an error, rolling back install
gyp verb command remove [ '0.34.3' ]
gyp verb remove using node-gyp dir: /Users/Akring/.atom/.node-gyp/.node-gyp
gyp verb remove removing target version: 0.34.3
gyp verb remove removing development files for version: 0.34.3
gyp ERR! install error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at TCP.onread (net.js:559:19)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.34.3" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure" "--verbose"
gyp ERR! cwd /Users/Akring/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok


✘ Akring@lvjundeMacBook-Pro  ~ 
```

**Comment by lee-dohm** [comment]
The error `ECONNRESET` generally means that there is a problem with the Internet connection or the server, almost assuredly temporary.

@Bantes are you still having this issue?

@akring are you still having this issue?

**Comment by akring** [comment]
@lee-dohm Yep,I'm still working on it.

**Comment by Ed-0x1b** [comment]
cURL doesn't follow 3xx redirects without the -L option. Add a line to /etc/curlrc with -L on it and give it another try.

**Comment by Bantes** [comment]
@lee-dohm yes

**Comment by AdamDenoon** [comment]
Same issue:

`Updating to “atom-material-ui@1.3.5” failed. (Show output)…`

```
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | darwin | x64
gyp http GET https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at TCP.onread (net.js:559:19)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.37.8" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/apple/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
```

**Comment by AdamDenoon** [comment]
Here's my verbose output. It seems to hang on the following line:

`REQUEST make request http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.37.8/node-v0.37.8.tar.gz`

Verbose:

```
Installing atom-material-ui@1.3.5 to /Users/apple/.atom/packages REQUEST { url: 'https://atom.io/api/packages/atom-material-ui',
  json: true,
  retries: 4,
  strictSSL: true,
  headers: { 'User-Agent': 'npm/2.13.3 node/v0.10.40 darwin x64' },
  callback: [Function],
  method: 'GET' }
REQUEST make request https://atom.io/api/packages/atom-material-ui
REQUEST onRequestResponse https://atom.io/api/packages/atom-material-ui 200 { server: 'Cowboy',
  connection: 'close',
  date: 'Wed, 24 Aug 2016 14:19:28 GMT',
  status: '200 OK',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=631152000',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src https://github-atom-io-herokuapp-com.global.ssl.fastly.net; frame-s$
  'content-type': 'application/json; charset=utf-8',
  etag: 'W/"2189743722ce65dfd8fbba1756399d4e"',
  'cache-control': 'max-age=0, private, must-revalidate',
  'x-request-id': '57d81350-c6fe-464b-a4b1-c0a49ec3e0d4',
  'x-runtime': '0.012572',
  'x-rack-cache': 'miss',
  vary: 'Origin',
  via: '1.1 vegur' }
REQUEST finish init function https://atom.io/api/packages/atom-material-ui
REQUEST response end https://atom.io/api/packages/atom-material-ui 200 { server: 'Cowboy',
  connection: 'close',
  date: 'Wed, 24 Aug 2016 14:19:28 GMT',
  status: '200 OK',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=631152000',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src https://github-atom-io-herokuapp-com.global.ssl.fastly.net; frame-s$
  'content-type': 'application/json; charset=utf-8',
  etag: 'W/"2189743722ce65dfd8fbba1756399d4e"',
  'cache-control': 'max-age=0, private, must-revalidate',
  'x-request-id': '57d81350-c6fe-464b-a4b1-c0a49ec3e0d4',
  'x-runtime': '0.012572',
  'x-rack-cache': 'miss',
  vary: 'Origin',
  via: '1.1 vegur' }
REQUEST end event https://atom.io/api/packages/atom-material-ui
REQUEST has body https://atom.io/api/packages/atom-material-ui 21684
REQUEST emitting complete https://atom.io/api/packages/atom-material-ui
REQUEST { url: 'https://www.atom.io/api/packages/atom-material-ui/versions/1.3.5/tarball',
  strictSSL: true,
  headers: { 'User-Agent': 'npm/2.13.3 node/v0.10.40 darwin x64' },
  method: 'GET',
  callback: undefined }
REQUEST make request https://www.atom.io/api/packages/atom-material-ui/versions/1.3.5/tarball
REQUEST onRequestResponse https://www.atom.io/api/packages/atom-material-ui/versions/1.3.5/tarball 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Wed, 24 Aug 2016 14:19:29 GMT',
  status: '302 Found',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=631152000',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src https://github-atom-io-herokuapp-com.global.ssl.fastly.net; frame-s$
  location: 'https://codeload.github.com/atom-material/atom-material-ui/legacy.tar.gz/v1.3.5',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': '10ebf619-d589-45db-9fbe-53e9ca85f7f4',
  'x-runtime': '0.063075',
  'x-rack-cache': 'miss',
  vary: 'Origin',
  via: '1.1 vegur' }
REQUEST redirect https://codeload.github.com/atom-material/atom-material-ui/legacy.tar.gz/v1.3.5
REQUEST redirect to https://codeload.github.com/atom-material/atom-material-ui/legacy.tar.gz/v1.3.5
REQUEST {}
REQUEST make request https://codeload.github.com/atom-material/atom-material-ui/legacy.tar.gz/v1.3.5
REQUEST response end https://codeload.github.com/atom-material/atom-material-ui/legacy.tar.gz/v1.3.5 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Wed, 24 Aug 2016 14:19:29 GMT',
  status: '302 Found',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=631152000',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src https://github-atom-io-herokuapp-com.global.ssl.fastly.net; frame-s$
  location: 'https://codeload.github.com/atom-material/atom-material-ui/legacy.tar.gz/v1.3.5',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': '10ebf619-d589-45db-9fbe-53e9ca85f7f4',
  'x-runtime': '0.063075',
  'x-rack-cache': 'miss',
  vary: 'Origin',
  via: '1.1 vegur' }
REQUEST onRequestResponse https://codeload.github.com/atom-material/atom-material-ui/legacy.tar.gz/v1.3.5 200 { 'content-length': '449136',
  'access-control-allow-origin': 'https://render.githubusercontent.com',
  'content-security-policy': 'default-src \'none\'; style-src \'unsafe-inline\'',
  'strict-transport-security': 'max-age=31536000',
  vary: 'Authorization,Accept-Encoding',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'deny',
  'x-xss-protection': '1; mode=block',
  etag: '"1f8052bc066e1da0ebc321a18613e389f743c1d3"',
  'content-type': 'application/x-gzip',
  'content-disposition': 'attachment; filename=atom-material-atom-material-ui-v1.3.5-0-g1f8052b.tar.gz',
  'x-geo-block-list': '',
  date: 'Wed, 24 Aug 2016 14:19:29 GMT',
  'x-github-request-id': '4A72B1F1:2CFB7:3546DF:57BDACF1' }
REQUEST finish init function https://codeload.github.com/atom-material/atom-material-ui/legacy.tar.gz/v1.3.5
REQUEST response end https://codeload.github.com/atom-material/atom-material-ui/legacy.tar.gz/v1.3.5 200 { 'content-length': '449136',
  'access-control-allow-origin': 'https://render.githubusercontent.com',
  'content-security-policy': 'default-src \'none\'; style-src \'unsafe-inline\'',
  'strict-transport-security': 'max-age=31536000',
  vary: 'Authorization,Accept-Encoding',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'deny',
  'x-xss-protection': '1; mode=block',
  etag: '"1f8052bc066e1da0ebc321a18613e389f743c1d3"',
  'content-type': 'application/x-gzip',
  'content-disposition': 'attachment; filename=atom-material-atom-material-ui-v1.3.5-0-g1f8052b.tar.gz',
  'x-geo-block-list': '',
  date: 'Wed, 24 Aug 2016 14:19:29 GMT',
  'x-github-request-id': '4A72B1F1:2CFB7:3546DF:57BDACF1' }
gyp info it worked if it ends with ok
gyp verb cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
gyp verb cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'install',
gyp verb cli   '--target=0.37.8',
gyp verb cli   '--dist-url=https://atom.io/download/atom-shell',
gyp verb cli   '--arch=x64',
gyp verb cli   '--ensure',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | darwin | x64
gyp verb command install []
gyp verb install input version string "0.37.8"
gyp verb install installing version: 0.37.8
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 0.37.8
gyp verb ensuring nodedir is created /Users/apple/.atom/.node-gyp/.node-gyp/0.37.8
gyp verb created nodedir /Users/apple/.atom/.node-gyp/.node-gyp/0.37.8
gyp http GET https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
REQUEST { uri: 'https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz',
  headers: { 'User-Agent': 'node-gyp v2.0.2 (node v0.10.40)' },
  callback: undefined }
REQUEST make request https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
REQUEST onRequestResponse https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Wed, 24 Aug 2016 14:19:30 GMT',
  status: '302 Found',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=631152000',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src https://github-atom-io-herokuapp-com.global.ssl.fastly.net; frame-s$
  location: 'http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.37.8/node-v0.37.8.tar.gz',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': '094fb55e-3abe-40aa-a56f-01af736c9b0c',
  'x-runtime': '0.006983',
  'x-rack-cache': 'miss',
  via: '1.1 vegur' }
REQUEST redirect http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.37.8/node-v0.37.8.tar.gz
REQUEST redirect to http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.37.8/node-v0.37.8.tar.gz
REQUEST {}
REQUEST make request http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.37.8/node-v0.37.8.tar.gz
REQUEST response end http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.37.8/node-v0.37.8.tar.gz 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Wed, 24 Aug 2016 14:19:30 GMT',
  status: '302 Found',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=631152000',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src https://github-atom-io-herokuapp-com.global.ssl.fastly.net; frame-s$
  location: 'http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.37.8/node-v0.37.8.tar.gz',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': '094fb55e-3abe-40aa-a56f-01af736c9b0c',
  'x-runtime': '0.006983',
  'x-rack-cache': 'miss',
  via: '1.1 vegur' }
gyp WARN install got an error, rolling back install
gyp verb command remove [ '0.37.8' ]
gyp verb remove using node-gyp dir: /Users/apple/.atom/.node-gyp/.node-gyp
gyp verb remove removing target version: 0.37.8
gyp verb remove removing development files for version: 0.37.8
gyp ERR! install error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at TCP.onread (net.js:559:19)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node$
gyp ERR! cwd /Users/apple/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

**Comment by AdamDenoon** [comment]
I can reach that URL from another network. My firewall is likely blocking that request. I will speak to my employer's firewall admins.

**Comment by AdamDenoon** [comment]
It was definitely my workplace firewall. My employer made an exception rule and it went through.
