### ISSUE TITLE
Failed to activate the japanese-wrap package

### ISSUE THREAD

**Issue by ericallfesta** [atom/atom#9891]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the japanese-wrap package

```
At block[1].contains is not a function

TypeError: block[1].contains is not a function
    at Function.module.exports.UnicodeUtil.getRangeListByName (<anonymous>:19:19)
    at JapaneseWrapManager.module.exports.JapaneseWrapManager.setupCharRegexp (<anonymous>:108:25)
    at new JapaneseWrapManager (<anonymous>:9:6)
    at Object.module.exports.activate (<anonymous>:40:28)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 11,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v0.21.0
japanese-wrap, v0.2.0

# Dev
No dev packages
```

**Comment by thedaniel** [comment]
Would you mind reopening this on the https://github.com/raccy/japanese-wrap repo?
