### ISSUE TITLE
Failed to activate the jsfmt package

### ISSUE THREAD

**Issue by s4tar** [atom/atom#9902]
1. open a package.json file
2. select all, call Command Palette input jsfmt.

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the jsfmt package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Function (native)
    at makePredicate (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/detective/node_modules/acorn/dist/acorn.js:1576:10)
    at Object.7 (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/detective/node_modules/acorn/dist/acorn.js:1582:6)
    at s (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/detective/node_modules/acorn/dist/acorn.js:1:698)
    at /usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/detective/node_modules/acorn/dist/acorn.js:1:749
    at Object.13../identifier (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/detective/node_modules/acorn/dist/acorn.js:2273:19)
    at s (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/detective/node_modules/acorn/dist/acorn.js:1:698)
    at /usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/detective/node_modules/acorn/dist/acorn.js:1:749
    at Object.1../expression (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/detective/node_modules/acorn/dist/acorn.js:47:14)
    at s (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/detective/node_modules/acorn/dist/acorn.js:1:698)
```

### Commands

```
     -0:10 core:close (div.pane-item.native-key-bindings.about)
     -0:06.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:04.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 jsfmt:execute (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "excludeVcsIgnoredPaths": true,
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "emacs-core-keys"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-ctags, v0.3.3
autocomplete-php, v0.3.7
autosave, v0.23.0
jsfmt, v1.1.2
language-php, v0.34.0
pretty-json, v0.4.1
smart-tags, v0.1.0

# Dev
No dev packages
```

**Comment by thedaniel** [comment]
Looks like this might be an issue with the jsfmt package - can you open an issue on the package repo? It's here: https://github.com/bichiliad/atom-jsfmt
