### ISSUE TITLE
Failed to activate the pathfinder package

### ISSUE THREAD

**Issue by robertlilje** [atom/atom#9903]
[Enter steps to reproduce below:]

1. Open Atom

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the pathfinder package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:3:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:490:19)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 11,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.5.0
pathfinder, v0.4.0

# Dev
No dev packages
```

**Comment by thedaniel** [comment]
@robertlilje This looks like an issue with the pathfinder package - I'd suggest you open an issue on that repo, but it looks like it's been taken down: https://atom.io/packages/pathfinder
