### ISSUE TITLE
Atom fails to build OS X (failed on `Installing spell-check`)

### ISSUE THREAD

**Issue by drvinceknight** [atom/atom#9906]
OS: OS X 10.10.5
Atom version: From master with HEAD at: 427a32c3368e1207816e76920482e6d1efca0321

**Reproduction Steps**

```
git clone https://github.com/atom/atom.git  
cd atom
script/build
```

**Expected behaviour**

Atom to build :)

**Observed behaviour**

```
...
Installing settings-view@0.154.0 ✓                                                                                                                                           
Installing snippets@0.56.0 ✓
Installing spell-check@0.43.0 ✗

> spellchecker@1.1.0 install /Users/vince/src/atom/node_modules/spell-check/node_modules/spellchecker
> node-gyp rebuild

  CXX(target) Release/obj.target/spellchecker/src/main.o

In file included from ../src/main.cc:3:
../node_modules/nan/nan.h:301:13: error: no type named 'SetCounterFunction' in 'v8::V8'
    v8::V8::SetCounterFunction(cb);
    ~~~~~~~~^
../node_modules/nan/nan.h:306:13: error: no type named 'SetCreateHistogramFunction' in 'v8::V8'
    v8::V8::SetCreateHistogramFunction(cb);
    ~~~~~~~~^
../node_modules/nan/nan.h:311:13: error: no type named 'SetAddHistogramSampleFunction' in 'v8::V8'
    v8::V8::SetAddHistogramSampleFunction(cb);
    ~~~~~~~~^
../node_modules/nan/nan.h:315:12: error: no member named 'IdleNotification' in 'v8::V8'; did you mean 'NanIdleNotification'?
    return v8::V8::IdleNotification(idle_time_in_ms);
           ^~~~~~~~~~~~~~~~~~~~~~~~
           NanIdleNotification
../node_modules/nan/nan.h:314:19: note: 'NanIdleNotification' declared here
  NAN_INLINE bool NanIdleNotification(int idle_time_in_ms) {
                  ^
../node_modules/nan/nan.h:319:5: error: no member named 'LowMemoryNotification' in 'v8::V8'; did you mean 'NanLowMemoryNotification'?
    v8::V8::LowMemoryNotification();
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    NanLowMemoryNotification
../node_modules/nan/nan.h:318:19: note: 'NanLowMemoryNotification' declared here
  NAN_INLINE void NanLowMemoryNotification() {
                  ^
../node_modules/nan/nan.h:323:5: error: no member named 'ContextDisposedNotification' in 'v8::V8'; did you mean 'NanContextDisposedNotification'?
    v8::V8::ContextDisposedNotification();
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    NanContextDisposedNotification
../node_modules/nan/nan.h:322:19: note: 'NanContextDisposedNotification' declared here
  NAN_INLINE void NanContextDisposedNotification() {
                  ^
6 errors generated.
make: *** [Release/obj.target/spellchecker/src/main.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/vince/src/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/vince/src/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/vince/src/atom/node_modules/spell-check/node_modules/spellchecker
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! spellchecker@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spellchecker@1.1.0 install script.
npm ERR! This is most likely a problem with the spellchecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls spellchecker
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.5.0
npm ERR! command "/Users/vince/src/atom/apm/node_modules/atom-package-manager/bin/node" "/Users/vince/src/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/vince/src/atom/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/vince/.atom/.apmrc" "insta
ll" "/private/var/folders/98/t82xlbq54gz005lb_w2rrlg80000gn/T/d-115112-12526-17lt596/package.tgz" "--target=0.18.0" "--arch=x64" "--quiet"
npm ERR! cwd /Users/vince/src/atom
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/vince/src/atom/npm-debug.log
npm ERR! not ok code 0
```

(Apologies if this is a duplicate: have attempted to find. Perhaps need more :coffee:.)

**Comment by thedaniel** [comment]
Was this on your first attempt at building, or had you built from this checkout before? If the latter, does it still happen after running `./script/clean`? Also, can you install the [failing npm module](https://www.npmjs.com/package/spellchecker) outside of the atom build process on your system?

**Comment by drvinceknight** [comment]
> Was this on your first attempt at building, or had you built from this checkout before?

This was the first time.

> If the latter, does it still happen after running ./script/clean? 

I ran `./script/clean` followed `./script/build` and had the exact same error.

> Also, can you install the failing npm module outside of the atom build process on your system?

This didn't seem to be a problem (not super familiar with npm):

```
tmp: npm install spellchecker
-
> spellchecker@3.1.3 install /Users/vince/tmp/node_modules/spellchecker
> node-gyp rebuild

  CXX(target) Release/obj.target/spellchecker/src/main.o
  CXX(target) Release/obj.target/spellchecker/src/spellchecker_mac.o
  SOLINK_MODULE(target) Release/spellchecker.node
  SOLINK_MODULE(target) Release/spellchecker.node: Finished
spellchecker@3.1.3 node_modules/spellchecker
└── nan@2.1.0
tmp:
```

Anything else you'd like me to try?
