### ISSUE TITLE
Uncaught Error: spawn /Users/stephenwalker/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app...

### ISSUE THREAD

**Issue by spiffwalker** [atom/atom#9914]
[Enter steps to reproduce below:]

1. import project folder

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/stephenwalker/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/stephenwalker/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/stephenwalker/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/stephenwalker/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:155:27)
    at Object.windowState (/Users/stephenwalker/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/stephenwalker/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/stephenwalker/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:132:14)
    at /Users/stephenwalker/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:825:44
    at Emitter.module.exports.Emitter.emit (/Users/stephenwalker/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Project.module.exports.Project.addPath (/Users/stephenwalker/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Users/stephenwalker/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1003:26)
    at EventEmitter.outerCallback (/Users/stephenwalker/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:204:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:05.3.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by thedaniel** [comment]
Is it possible that you started Atom from your Downloads folder and then moved it to Applications while it was running? Can you still reproduce this?

**Comment by spiffwalker** [comment]
Yes this is exactly what happened! I figured it out a couple seconds later.

**Comment by 50Wliu** [comment]
Just for historical records: see a;sp #9559 and #7399 for the two main issues that are tracking this.
