### ISSUE TITLE
Uncaught TypeError: Cannot read property 'restoreFromSnapshot' of undefined

### ISSUE THREAD

**Issue by Alaneor** [atom/atom#9918]
Hello,

I am receiving this error while trying to undo a few changes, but I do not remember doing anything specific.

I was unable to reproduce this issue in a new file, but the error always appears in this file at a particular position in history. I can type a few characters, undo that typing normally, but the next undo will cause this error. I cannot seem to be able to undo to a state before this error.

**Atom Version**: 1.3.0-beta6
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'restoreFromSnapshot' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1280

TypeError: Cannot read property 'restoreFromSnapshot' of undefined
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1280:55)
    at TextBuffer.module.exports.TextBuffer.undo (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:765:14)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1186:31
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:2078:43)
    at TextEditor.module.exports.TextEditor.avoidMergingSelections (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:2064:35)
    at TextEditor.module.exports.TextEditor.undo (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1184:12)
    at TextEditor.commandRegistry.add.stopEventPropagation.core:undo (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/register-default-commands.js:223:21)
    at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/register-default-commands.js:554:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:07.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:38.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:36.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:26.5.0 terminal-plus:toggle (textarea.)
  7x -0:21.6.0 core:select-up (atom-text-editor.editor.is-focused)
  3x -0:20.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:19.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:19.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:18.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:15.6.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -0:12.1.0 core:undo (atom-text-editor.editor.is-focused)
     -0:09.6.0 core:redo (atom-text-editor.editor.is-focused)
     -0:08.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:08.7.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -0:07.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.7.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "turbo-javascript",
      "lcov-info",
      "atom-material-ui",
      "git-history",
      "minimap-linter",
      "sloc",
      "api-blueprint-preview",
      "tool-bar"
    ],
    "disabledPackages": [
      "git-control",
      "api-blueprint-preview"
    ],
    "projectHome": "/Users/BeBe/Dropbox/Repositories"
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "Source Code Pro",
    "preferredLineLength": 100,
    "showIndentGuide": true,
    "scrollPastEnd": true,
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
atom-chai-snippets, v0.3.0
atom-material-syntax, v0.2.6
atom-material-ui, v0.8.0
atom-pair, v2.0.10
autocomplete-modules, v1.3.1
build, v0.49.2
docblockr, v0.7.3
editor-stats, v0.17.0
editorconfig, v1.2.2
file-icons, v1.6.13
flex-tool-bar, v0.6.0
git-log, v0.4.1
git-plus, v5.6.6
highlight-selected, v0.11.1
language-api-blueprint, v1.0.2
language-babel, v2.5.3
language-gitignore, v0.2.0
language-ini, v1.14.0
language-jade, v0.6.2
linter, v1.11.3
linter-eslint, v5.2.4
minimap, v4.16.2
minimap-git-diff, v4.1.8
node-debugger, v1.3.0
project-manager, v2.6.5
terminal-plus, v0.14.5
tool-bar, v0.1.9
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
Can you reproduce this in safe mode?

**Comment by Alaneor** [comment]
I was unable to reproduce this at all. Not even in that same file at a different point in history. And it never happened again since that one time.

**Comment by maxbrunsfeld** [comment]
Ok, I'm going to close this out for now. I'll reopen it if you can find a way to reproduce it.

**Comment by tobypinder** [comment]
I'm afraid I'm in the same position - past certain undo steps trying to undo reproduces the error. Can't for the life of me think what the step would be, the file's been open for several hours at this point.

Will update if I can reliably repro.

**Atom Version**: 1.3.0
**System**: Linux Mint
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'restoreFromSnapshot' of undefined

```
At /opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1280

TypeError: Cannot read property 'restoreFromSnapshot' of undefined
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1280:55)
    at TextBuffer.module.exports.TextBuffer.undo (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:765:14)
    at /opt/atom/resources/app.asar/src/text-editor.js:1186:31
    at TextEditor.module.exports.TextEditor.mergeSelections (/opt/atom/resources/app.asar/src/text-editor.js:2078:43)
    at TextEditor.module.exports.TextEditor.avoidMergingSelections (/opt/atom/resources/app.asar/src/text-editor.js:2064:35)
    at TextEditor.module.exports.TextEditor.undo (/opt/atom/resources/app.asar/src/text-editor.js:1184:12)
    at TextEditor.commandRegistry.add.stopEventPropagation.core:undo (/opt/atom/resources/app.asar/src/register-default-commands.js:223:21)
    at atom-text-editor.newCommandListeners.(anonymous function) (/opt/atom/resources/app.asar/src/register-default-commands.js:554:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
 19x -0:11.1.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "openEmptyEditorOnStart": false,
    "disabledPackages": [
      "rubocop-auto-correct"
    ],
    "destroyEmptyPanes": false,
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "ignoredNames": [
      "2012*.rb",
      "2013*.rb",
      "2014*.rb"
    ],
    "packagesWithKeymapsDisabled": [
      "grammar-selector"
    ],
    "projectHome": "/home/toby/Documents/Code/Ruby"
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "Ubuntu Mono",
    "preferredLineLength": 120,
    "tabType": "soft"
  }
}
```

### Installed Packages

```coffee
# User
coverage, v0.6.1
file-icons, v1.6.13
highlight-selected, v0.11.1
language-haml, v0.23.13
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-haml, v1.0.0
linter-jshint, v1.2.1
linter-rubocop, v0.4.4
linter-ruby, v1.2.0
sync-settings, v0.6.0
synced-sidebar, v0.4.3
tasks, v2.6.0

# Dev
No dev packages
```

**Comment by Aweary** [comment]
Not sure how to reproduce this either, but here's my error report, just in case it helps:


**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'restoreFromSnapshot' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1280

TypeError: Cannot read property 'restoreFromSnapshot' of undefined
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1280:55)
    at TextBuffer.module.exports.TextBuffer.undo (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:765:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1186:31
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2082:18)
    at TextEditor.module.exports.TextEditor.avoidMergingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2064:35)
    at TextEditor.module.exports.TextEditor.undo (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1184:12)
    at TextEditor.commandRegistry.add.stopEventPropagation.core:undo (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:223:21)
    at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:554:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -3:10.8.0 core:move-up (input.hidden-input)
     -3:10.2.0 core:move-down (input.hidden-input)
     -3:09.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -3:09.8.0 editor:newline-below (input.hidden-input)
  4x -3:09.2.0 core:backspace (input.hidden-input)
     -3:08.3.0 snippets:next-tab-stop (input.hidden-input)
     -3:08.3.0 snippets:expand (input.hidden-input)
     -3:08.3.0 docblockr:parse-tab (input.hidden-input)
     -3:08.3.0 editor:indent (input.hidden-input)
     -3:04.8.0 core:move-right (input.hidden-input)
     -3:02.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
  4x -3:01.6.0 core:save (input.hidden-input)
     -2:38.6.0 editor:select-to-first-character-of-line (input.hidden-input)
  3x -2:37.7.0 core:backspace (input.hidden-input)
 11x -2:19.1.0 core:save (input.hidden-input)
 10x -0:02.0 core:undo (input.hidden-input)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-material-numix-syntax"
    ],
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "vim-mode",
      "turbo-javascript"
    ],
    "destroyEmptyPanes": false,
    "openEmptyEditorOnStart": false
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "Droid Sans Mono",
    "fontSize": 13,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "useShadowDOM": false
  }
}
```

### Installed Packages

```coffee
# User
atom-material-numix-syntax, v0.2.1
autocomplete-modules, v1.3.1
css-snippets, v0.9.0
docblockr, v0.7.3
editor-stats, v0.17.0
emmet, v2.3.16
file-icons, v1.6.13
language-postcss, v1.1.1
linter, v1.11.3
linter-eslint, v5.2.4
minimap, v4.16.2
minimap-find-and-replace, v4.3.2
my-minimap-plugin, v0.0.0
pigments, v0.19.1
react, v0.12.10
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
I've hit this as well, and @alexchandel has reported the same, so re-opening (for now - it still could definitely be related to installed packages).

@alexchandel could you please paste the output of `apm list --installed` here?  Thanks!

**Comment by stlaz** [comment]
To me, the error appeared when going back from an interactive rebase to HEAD. During that, I had a file that was changed from the rebased branch to HEAD opened in split view on both sides.

**Comment by bronson** [comment]
I got this error when undoing in a regular file.  Nothing special going on that I know of.

No idea how it reproduce it.  Quitting & restarting Atom fixed it.  For now.

**Comment by jazzpi** [comment]
I also just got this when pressing <kbd>Ctrl+Z</kbd> when (I think) there were no steps left to undo. Also happened with vim-mode's <kbd>u</kbd>.

**Comment by MentalGear** [comment]
+1 on undo
Uncaught TypeError: Cannot read property 'restoreFromSnapshot' of undefined

**Comment by zackkitzmiller** [comment]
I've been able to reproduce this. 

1. Open a File
2. Edit said file
3. `cmd-k ->` to open a new pane. This opens the focused file in pane 1 in the second pane
4. Close file in pane 2
5. `cmd-z` in pane 1. 
6. Exception is now thrown.

**Comment by maxbrunsfeld** [comment]
Sorry about this one everyone! We'll release 1.3.3 shortly with a fix for this bug.

**Comment by seemantk** [comment]
Hi, I just hit this bug with v 1.4.0 running on Arch Linux.

```
Built-in Atom packages (87)
├── about@1.3.0
├── archive-view@0.61.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.9.2
├── autocomplete-css@0.11.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.25.0
├── autocomplete-snippets@1.9.0
├── autoflow@0.26.0
├── autosave@0.23.0
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.0.0
├── base16-tomorrow-light-theme@1.0.0
├── bookmarks@0.38.0
├── bracket-matcher@0.79.0
├── command-palette@0.38.0
├── deprecation-cop@0.54.0
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── find-and-replace@0.194.0
├── fuzzy-finder@0.94.0
├── git-diff@0.57.0
├── go-to-line@0.30.0
├── grammar-selector@0.48.0
├── image-view@0.56.0
├── incompatible-packages@0.25.0
├── keybinding-resolver@0.33.0
├── language-c@0.51.1
├── language-clojure@0.19.0
├── language-coffee-script@0.46.0
├── language-csharp@0.11.0
├── language-css@0.36.0
├── language-gfm@0.82.0
├── language-git@0.11.0
├── language-go@0.42.0
├── language-html@0.43.1
├── language-hyperlink@0.16.0
├── language-java@0.17.0
├── language-javascript@0.104.0
├── language-json@0.17.2
├── language-less@0.29.0
├── language-make@0.21.0
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.32.0
├── language-php@0.34.0
├── language-property-list@0.8.0
├── language-python@0.42.1
├── language-ruby@0.65.0
├── language-ruby-on-rails@0.24.0
├── language-sass@0.45.0
├── language-shellscript@0.21.0
├── language-source@0.9.0
├── language-sql@0.20.0
├── language-text@0.7.0
├── language-todo@0.27.0
├── language-toml@0.18.0
├── language-xml@0.34.2
├── language-yaml@0.25.0
├── line-ending-selector@0.3.0
├── link@0.31.0
├── markdown-preview@0.157.0
├── notifications@0.62.1
├── one-dark-syntax@1.1.1
├── one-dark-ui@1.1.8
├── one-light-syntax@1.1.1
├── one-light-ui@1.1.8
├── open-on-github@0.40.0
├── package-generator@0.41.0
├── settings-view@0.232.1
├── snippets@1.0.1
├── solarized-dark-syntax@0.39.0
├── solarized-light-syntax@0.23.0
├── spell-check@0.63.0
├── status-bar@0.80.0
├── styleguide@0.45.0
├── symbols-view@0.110.1
├── tabs@0.88.0
├── timecop@0.33.0
├── tree-view@0.198.0
├── update-package-dependencies@0.10.0
├── welcome@0.33.0
├── whitespace@0.32.1
└── wrap-guide@0.38.1

/home/seemant/.atom/packages (1)
└── file-watcher@0.4.0
```

**Comment by brutalcrozt** [comment]
i'm on 1.4.0, with win8 64bit
i just got that error when i open somefile on the pane. Then i reopen that file, then press ctrl + z.
and the file actually opened on both pane.
Maybe this can help the developer. :kissing_heart:
```
TypeError: Cannot read property 'restoreFromSnapshot' of undefined
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (C:\Users\enter\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1287:55)
    at TextBuffer.module.exports.TextBuffer.undo (C:\Users\enter\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:772:14)
    at C:\Users\enter\AppData\Local\atom\app-1.4.0\resources\app.asar\src\text-editor.js:1200:31
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\enter\AppData\Local\atom\app-1.4.0\resources\app.asar\src\text-editor.js:2096:18)
    at TextEditor.module.exports.TextEditor.avoidMergingSelections (C:\Users\enter\AppData\Local\atom\app-1.4.0\resources\app.asar\src\text-editor.js:2078:35)
    at TextEditor.module.exports.TextEditor.undo (C:\Users\enter\AppData\Local\atom\app-1.4.0\resources\app.asar\src\text-editor.js:1198:12)
    at TextEditor.commandRegistry.add.stopEventPropagation.core:undo (C:\Users\enter\AppData\Local\atom\app-1.4.0\resources\app.asar\src\register-default-commands.js:223:21)
    at atom-text-editor.newCommandListeners.(anonymous function) (C:\Users\enter\AppData\Local\atom\app-1.4.0\resources\app.asar\src\register-default-commands.js:554:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\enter\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\enter\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\enter\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\enter\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\enter\AppData\Local\atom\app-1.4.0\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\enter\AppData\Local\atom\app-1.4.0\resources\app.asar\src\window-event-handler.js:3:61)```

**Comment by andradei** [comment]
Getting this error on OS X. Atom 1.4.0.

**Comment by couryrr** [comment]
Just hit this as well. This issue only occurs in one of my open files when undoing/redoing changes. Also, this only happens after a specific change in the file. 

For example I moved a variable sunk out of the constructor of a js file then made some changes after that updating some methods. When undoing or redoing at this point I will get the error every time I undo/redo. All of the undo/redo steps are working though. If I undo past the point of moving sunk then the error will no longer fire.

**Comment by Alienwaren** [comment]
I'm getting that exception too, editing a PXELINUX config file on Samba Share. I'm running Windows 10 Pro and Atom 1.4.0. 
This error occured when I split window to two panes, and tried to redo changes on first pane. I resolved the error by reopening file.

**Comment by 50Wliu** [comment]
@maxbrunsfeld Should this be re-opened?

**Comment by keithgordon** [comment]
+1

**Comment by maxbrunsfeld** [comment]
Sorry everyone, in 1.4.0 we accidentally upgraded a library dependency in a way that *removed* our fix for this bug. The bug should be gone in 1.4.1 and 1.5.0-beta1, which are now out.
