### ISSUE TITLE
Uncaught TypeError: string.indexOf is not a function

### ISSUE THREAD

**Issue by interaminense** [atom/atom#9919]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: string.indexOf is not a function

```
At C:\Users\Adriano\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\fuzzaldrin\lib\scorer.js:60

TypeError: string.indexOf is not a function
    at Object.exports.score (C:\Users\Adriano\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\fuzzaldrin\lib\scorer.js:60:31)
    at module.exports (C:\Users\Adriano\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\fuzzaldrin\lib\filter.js:25:24)
    at module.exports.filter (C:\Users\Adriano\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\fuzzaldrin\lib\fuzzaldrin.js:21:14)
    at ListView.module.exports.SelectListView.populateList (C:\Users\Adriano\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:195:25)
    at C:\Users\Adriano\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:350:26
```
### Commands

```
     -5:46.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -5:46.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -5:45.5.0 command-palette:toggle (div.package-detail.panels-item)
     -5:40.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -5:40.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -5:32.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:31.5.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -5:31.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:31.2.0 open-on-github:file (div.package-detail.panels-item)
     -5:27.9.0 core:move-up (div.package-detail.panels-item)
  2x -5:27.3.0 core:move-down (div.package-detail.panels-item)
     -0:38.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:37 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:37 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:33.7.0 fetch:file (span.name.icon.icon-file-directory)
     -0:02.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.3
auto-indent, v0.5.0
autocomplete-angular-material, v0.4.0
color-picker, v2.0.14
emmet, v2.3.16
fetch, v0.3.0
jQuery, v1.2.0
minimap, v4.16.2

# Dev
No dev packages
```

**Comment by siberian1967** [comment]
I received this as well. I had the config folder (not floobits eligible, uses atom:config) and my directory that I had added as a project folder. 

If config folder was selected during a floobits join this popped up.

If my floobits project folder was selected then it worked fine.

Just some color commentary that may help.
