### ISSUE TITLE
Failed to load the autocomplete-ctags package

### ISSUE THREAD

**Issue by sander90** [atom/atom#9922]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to load the autocomplete-ctags package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (<anonymous>:1:5)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-ctags, v0.3.3
build-cargo, v0.8.0
language-gmod-lua, v0.4.0
language-javascript-jsx, v0.3.7
language-lua, v0.9.4
language-rust, v0.4.5
linter-lua, v1.0.0
linter-lua-findglobals, v1.0.0
linter-luacheck, v1.1.3
racer, v0.17.2
react, v0.12.10
react-es6-snippets, v0.2.0
react-snippets, v0.3.0
rust-api-docs-helper, v0.5.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hey @sander90, can you please move this to [yasuyuky/autocomplete-ctags](https://github.com/yasuyuky/autocomplete-ctags) instead?  Thanks!
