### ISSUE TITLE
Cannot build Atom 1.3.0-beta6 on Ubuntu 15.10 64-bit: ECONNRESET and ELIFECYCLE errors

### ISSUE THREAD

**Issue by WarriorIng64** [atom/atom#9940]
I'm trying to build the latest beta release of Atom (1.3.0-beta6) on my laptop running Ubuntu 15.10 64-bit. I first ran the following inside `~/atom` to update my local copy of the source, as per [the Linux build instructions](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#instructions):
```
git fetch -p
git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
```
...but I'm getting the following output from `script/build` when run afterwards:

```
christopher@AuroraUnit:~/atom$ script/build
Node: v0.10.25
npm: v1.4.21
Installing build modules...
Installing apm...

Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
npm ERR! Linux 4.2.0-19-generic
npm ERR! argv "node" "/home/christopher/atom/build/node_modules/.bin/npm" "--userconfig=/home/christopher/atom/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
npm ERR! node v0.10.25
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! atom-package-manager@1.4.1 install: `node ./script/download-node.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the atom-package-manager@1.4.1 install script 'node ./script/download-node.js'.
npm ERR! This is most likely a problem with the atom-package-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/download-node.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls atom-package-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/christopher/atom/apm/npm-debug.log
```
The last version of Atom I tried to build was Atom 1.2.0-beta0, and that was successful. Running `script/clean` before `script/build` still does not resolve the issue.

**Comment by WarriorIng64** [comment]
Attempting this again at home seemed to fix the issue. Okay, then.
