### ISSUE TITLE
Uncaught TypeError: this.shouldNotAccessFileSystem is not a function

### ISSUE THREAD

**Issue by opensource-yl** [atom/atom#9943]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: this.shouldNotAccessFileSystem is not a function

```
At C:\Users\yuyl\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:419

TypeError: this.shouldNotAccessFileSystem is not a function
    at module.exports.Config.loadUserConfig (C:\Users\yuyl\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:419:16)
    at later (C:\Users\yuyl\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\underscore-plus\node_modules\underscore\underscore.js:724:25)
```
### Commands

```
     -9:45.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:42.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:59.2.0 remote-edit:show-open-files (atom-text-editor.editor.is-focused)
  2x -5:56.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:53.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:48 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -5:43.4.0 encoding-selector:show (atom-text-editor.editor)
     -5:01.0 remote-edit:browse (atom-text-editor.editor.is-focused)
     -4:40.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:40.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:35.2.0 remote-edit:show-open-files (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {},
    "backUpBeforeSaving": true
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by xonlly** [comment]
I have the same problem on:

**Atom Version**: 1.6.1
**System**: Unknown Windows Version
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: this.shouldNotAccessFileSystem is not a function

```
At C:\Users\Mrvin\AppData\Local\atom\app-1.6.1\resources\app.asar\src\config.js:453

TypeError: this.shouldNotAccessFileSystem is not a function
    at module.exports.Config.loadUserConfig (C:\Users\Mrvin\AppData\Local\atom\app-1.6.1\resources\app.asar\src\config.js:453:16)
    at later (C:\Users\Mrvin\AppData\Local\atom\app-1.6.1\resources\app.asar\node_modules\underscore-plus\node_modules\underscore\underscore.js:724:25)
```

### Commands

```
```

### Config

```json
{
  "editor": {}
}
```

### Installed Packages

```coffee
# User
aligner, v0.19.1
color-picker, v2.1.1
color-tabs, v0.1.8
javascript-snippets, v1.2.1
keyboard-localization, v1.4.16
language-diff, v0.4.0
language-js-specs, v0.1.0
language-scala, v1.1.6
linter, v1.11.4
linter-eslint, v7.1.3
linter-jshint, v2.0.3
linter-jsxhint, v0.1.2
minimap, v4.21.0
pigments, vundefined
react, v0.14.2
travis-ci-status, v1.0.0
wercker-status, v1.0.6

# Dev
No dev packages
```
