### ISSUE TITLE
Using Atom as a remote editor for Transmit crashes Atom

### ISSUE THREAD

**Issue by 128keaton** [atom/atom#9970]
[atom.pdf](https://github.com/atom/atom/files/54433/atom.pdf)
(I tried uploading a .log, but Github doesn't allow that)

Anyway, I hope this gets fixed. I love Atom!

**Comment by benogle** [comment]
Contents of PDF

```
12/7/15 12:51:05.242 PM Atom[3760] Cannot read property 'substr'
of null
12/7/15 12:51:05.244 PM Atom[3760] TypeError: Cannot read
property 'substr' of null
 at AtomWindow.module.exports.AtomWindow.getLoadSettings (/Users/
keatonburleson/Downloads/Atom.app/Contents/Resources/app.asar/src/
browser/atom-window.js:135:71)
 at AtomApplication.module.exports.AtomApplication.saveState (/
Users/keatonburleson/Downloads/Atom.app/Contents/Resources/app.asar/
src/browser/atom-application.js:732:37)
 at BrowserWindow.<anonymous> (/Users/keatonburleson/Downloads/
Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:
198:26)
 at emitOne (events.js:82:20)
 at BrowserWindow.emit (events.js:169:7)
 at Object.module.exports.showMessageBox (/Users/keatonburleson/
Downloads/Atom.app/Contents/Resources/atom.asar/browser/api/lib/
dialog.js:154:22)
 at EventEmitter.<anonymous> (/Users/keatonburleson/Downloads/
Atom.app/Contents/Resources/app.asar/src/browser/atom-window.js:
215:27)
 at emitOne (events.js:82:20)
 at EventEmitter.emit (events.js:169:7)
```
