### ISSUE TITLE
Can't search for any package

### ISSUE THREAD

**Issue by Komosa** [atom/atom#9978]
scenario: I go to `Settings`, then opened `Install` tab by mouse click, then filled textbox with `test`, and finally clicked `Packages` button.
I'm using Atom 1.2.4, I tried installing atom multiple times.
`uname -a`: `Linux myhostname 4.2.6-200.fc22.x86_64 #1 SMP Tue Nov 10 16:45:19 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
I cannot reproduce this bug on Fedora 23

```
Searching for “test” failed.Hide output…
/usr/share/atom/resources/app/apm/node_modules/npm/lib/npm.js:19

  , fs = gfs.gracefulify(require('fs'))

             ^

TypeError: Object #<Object> has no method 'gracefulify'
    at /usr/share/atom/resources/app/apm/node_modules/npm/lib/npm.js:19:14
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm/lib/npm.js:468:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/lib/apm-cli.js:12:9)
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/lib/apm-cli.js:237:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/lib/cli.js:4:9)
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/lib/cli.js:17:4)
```

**Comment by mnquintana** [comment]
How did you install Atom? Was it from one of the official downloads on https://atom.io or from somewhere else?

**Comment by Komosa** [comment]
Yes, it was from there.

**Comment by Komosa** [comment]
@mnquintana , what other information should I provide?

**Comment by Komosa** [comment]
I made workaround locally:
I changed `/usr/share/atom/resources/app/apm/node_modules/npm/lib/npm.js:18` in following way:

    +  , gfs = require('../node_modules/graceful-fs/graceful-fs.js')
    -  , gfs = require('graceful-fs')

**Comment by puranjayjain** [comment]
The following tasks resolved my issue:
1. Close atom
2. Update [node ](https://nodejs.org)to the latest **stable ** version
2. In terminal enter this code `npm rebuild`
3. Open atom and try again it will work.

**Comment by Komosa** [comment]
Closing since workarounds are provided and there is no interest in fixing (or even getting rid of more-information-needed label).
